### ISSUE TITLE
Inspections should warn about overridden members

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#1002]
While VBA doesn't allow real overriding your own class members, it does allow you to "override" the members of references. For example, you can write your own `MsgBox` function to override the `VBA.MsgBox` function. While some might consider this a _feature_, it's only a feature if it is intentional and used accordingly. If you unintentionally override a reference member, then you may get unexpected results in other code, and the bug can be hard to find.

**Comment by retailcoder** [comment]
That's *member hiding*, or *member shadowing*, and it's an awesome inspection idea!

**Comment by retailcoder** [comment]
Adding it to 2.0 milestone, but since the tests are back up (thanks @Hosch250!), unit tests should be written to cover that one end-to-end - dealing ditectly with resolver/scoping rules is tricky and error-prone.

**Comment by retailcoder** [comment]
The inspection results should say

 > {0} '{1}' hides {2} '{3}'.

Where 0 is the *DeclarationType* of 1, 1 is the issue/target, 2 is the *DeclarationType* of 2, and 2 is the "shadowed" declaration.

**Comment by ThunderFrame** [comment]
Might be worth making a distinction between shadowed member in private and public scopes (private shadow is perhaps more intentional), and also shadowed members that are in contention with references or other modules (eg. MsgBox function declared publicly in 1 module, and privately in 1 or more other modules)

**Comment by retailcoder** [comment]
This inspection would trigger on `Declaration` objects that use an identifier that already exists in a broader scope, e.g. a `Strings` module in `VBProject` "shadows" the built-in `VBA.Strings` module in the standard library, but user code can shadow itself too, given ambiguous naming such as the one trying to break the resolver in #934 and #973.

**Comment by rkapka** [comment]
Hey!

I started working on this, and to make it as robust as possible I'm currently trying to figure out which declaration types can be shadowed by which declaration types. There are tons of possible combinations, of course. Right now I'm focusing only on referenced projects, so I created one project and referenced it from another.

I would like to ask some questions here along the way to clarify things. I will probably have more questions in the future, but I'd like to clear up my current doubts.

1. Do I have to take the `Control` declaration type into consideration? I don't even know what it is. The same question applies for `UnresolvedDeclaration` and `ComAlias`.
2. Is it possible to instantiate a class from another module? I can write `New VBA.` and a couple of class names pop up in intellisense, but I cannot do this with my own class. Google says it's not possible (the workaround being `PublicNotCreatable`, but it's not what I'm after), but how can it be done using the built-in libraries? Do I need to create a .NET DLL or something?

**Comment by retailcoder** [comment]
`Control` is the declaration type we use for the on-the-fly field declarations we create for MSForms controls; you can probably ignore them, they're there so the resolver knows what `Label1` refers to in a form's code-behind (or anywhere else, e.g. `UserForm1.Label1.Caption = "hello"`.

`UnresolvedDeclaration` and `ComAlias` are resolver artifacts that can be ignored - they're respectively used for (resolver error recovery?) and for function aliases in referenced COM libraries (a rather rare occurrence AFAIK).

You can't instantiate a VBA class from another VBA project with the `New` keyword - PublicNotCreatable means the class can be used, but not created directly (a factory method can make be exposed). A non-VBA class that *is* creatable *can* indeed be `New`ed up, e.g. `Dim foo As New Collection`, or even `Private Assert As Rubherduck.AssertClass`.

**Comment by rkapka** [comment]
Are we closing this one or waiting for potential bug fixes, like #3397?

**Comment by retailcoder** [comment]
@rkapka oops, I though the merge would have auto-close it. When you commit or PR the fix for 3397, include the magic words "closes #xxxx" and GitHub will automatically close the issue when the commit gets merged.
