### ISSUE TITLE
Access Application without any open databases leaves most Rubberduck menus enabled

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#1010]
The resolver toolbar doesn't say Ready, Parsing or Error - It's blank.

The Rubberduck menu and context menus are all enabled, which is inappropriate if there's nothing to explore, inspect, refactor or test.

Steps to Reproduce
Start Access
Open a database
Close the database
Open VBE

Linking to #1009

**Comment by retailcoder** [comment]
The [default state](https://github.com/rubberduck-vba/Rubberduck/blob/b8968c69815c0a8547f459a3be51a5b1a6f070c9/Rubberduck.Parsing/VBA/ParserState.cs) for `RubberduckParserState`, is `Pending`. Which would make sense to use here, even more so than `Ready.

The startup code needs to ensure the `RubberduckMenu` and all context menus run their `EvaluateCanExecute` method at startup.

**Comment by ThunderFrame** [comment]
This defect is actually applicable to all host applications that don't have any VBProjects. PR #1080 allows for getting the host application, when there aren't any VBProjects open.

**Comment by ThunderFrame** [comment]
The `state` text seems to be determined by an enum, but it might be better to localize?

**Comment by Vogel612** [comment]
@ThunderFrame internal representation over an enum is probably necessary anyways. As such localization should happen over the enum-constants.

Since the enum members only can change with a full recompile it should be possible to rely on them for localization purposes.
