### ISSUE TITLE
Const, Variable, Type or Enum Block inside Compiler Directive - Parser Bug

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#1012]
A Type causes a a parser error:

```
#If Win64 Then

Private Type MyType
  MyMember As Long
End Type

#End If
```

as does an Enum
```
#If VBA7 Then

  Enum MyEnum
    MyMember = 1
  End Enum

#End If
```

And a Const (although a Compiler \#Const does not)
```
#If Win64 Then

  Const MyConst = 1

#End If
```

And variable declarations
```
#If Win64 Then

  Public MyVar As Long

#End If
```

Subs and Functions seem to be OK. First spotted this in CorelDRAW, but repeated tests in Excel produce the same outcome.

**Comment by retailcoder** [comment]
Wow, in other words, the grammar support for `#directives` is pretty much inexistent. I'm sure this can be fixed.
