### ISSUE TITLE
Code Explorer should sort projects by Project Name (by default, like Project Explorer)

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#1016]
Current sort order seems to be based on filename, or the order in which the projects were opened/created?

**Comment by retailcoder** [comment]
The intent is to sort them the way they're sorted in the Project Explorer, indeed.

**Comment by ThunderFrame** [comment]
I've just made a fix that sorts the projects by name, but the collation is still different to VBE's sorting. I guess we'll need an IComparer once we determine the exact sorting collation that VBE uses.

VBE will sort:
```vb
aaa
AAA
```

Rubberduck will sort:
```
AAA
aaa
```

**Comment by Hosch250** [comment]
Rubberduck is sorting by ASCII code.  The fix probably involves an `OrderBy().ThenBy()`, but I'm not sure what the arguments would be ATM.

**Comment by autoboosh** [comment]
Should the sort order be defined by the current language set in the options? See : http://stackoverflow.com/a/1846239/5895299. Code:

`var result = fruits.OrderBy(f => f, StringComparer.CurrentCulture);`

**Comment by ThunderFrame** [comment]
On closer inspection, thevVBA sort order is case insensitive, but the sort order is based on Project Name *and* File Name.

**Comment by Hosch250** [comment]
We have four sort orders implemented.  Closing this as status-declined.
