### ISSUE TITLE
issues in some VBA statements

### ISSUE THREAD

**Issue by u-riaz** [rubberduck-vba/Rubberduck#1017]
Hi,
VBA Statements --Get, Lock, Unlock, Seek, Width-- take file number with optional [#], according to [MSDN](https://msdn.microsoft.com/EN-US/library/office/gg251328.aspx),e.g.
Seek [#]filenumber, position
Lock [#]filenumber[, recordrange]    etc.

But, grammar is not handling '#' in above mentioned statements, without '#' all is fine.  You can see grammar rules e.g. 
seekStmt : SEEK WS valueStmt WS? ',' WS? valueStmt;
after SEEK there is 'valueStmt' not 'fileNumber'. 
Please have a look. Either i'm in need to modify the grammar or there can be another quick fix. 

Thanks

**Comment by Vogel612** [comment]
Thank you for reporting this one.

It looks like a grammar fix is necessary. It should be fixable by using

    seekStmt: SEEK WS '#' valueStmt WS? ',' WS? valueStmt;

similar applies to Lock, Unlock, ...   
Regarding:

> after SEEK there is 'valueStmt' not 'fileNumber'. 

That's because `fileNumber` is "just" a parameter name. It actually is a "value" with regards to the parser internals and as such `valueStmt` is correctly used here

**Comment by u-riaz** [comment]
As '#' is optional, so, instead of 
`seekStmt: SEEK WS '#' valueStmt WS? ',' WS? valueStmt;`
i think it would be more better
`seekStmt: SEEK WS '#'? valueStmt WS? ',' WS? valueStmt;`

am i right ?

**Comment by Vogel612** [comment]
You're completely correct, I did already correct that mistake of mine :+1:

**Comment by retailcoder** [comment]
The `fileNumber` rule I introduced handles the optional `'#'` token and would be more semantically correct, thanks for finding that one @u-riaz, I'll update the grammar accordingly - you've just fixed a few parser bugs in Rubberduck 2.0! :smile:

**Comment by retailcoder** [comment]
@Vogel612 `fileNumber` isn't "just" a parameter name ;-)

    fileNumber : '#'? valueStmt;

It's a parser rule I introduced to clean up file I/O parser rules; the `valueStmt` can be an integer literal or an `ambiguousIdentifier` usually referring to a local variable.

The `seekStmt` rule would therefore be:

    seekStmt: SEEK WS fieNumber WS? ',' WS? valueStmt;
