### ISSUE TITLE
Code Explorer should display protected projects

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#1018]
Even if you can't expand a protected project, it's still useful to see the project alongside your other projects.
Currently, protected projects aren't visible in Code Explorer, but they are visible in Project Explorer.

**Comment by retailcoder** [comment]
That's definitely a regression issue that needs to be fixed. Thanks!

**Comment by retailcoder** [comment]
I'll close this one as a dupe of #1020, it's the same issue and the other one is more detailed.
