### ISSUE TITLE
RubberDuck toolbar should be named Rubberduck

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#1027]
Currently the toolbar is named *Parsing* which, firstly, is a verb, so it's not a good name, and secondly, it's not obvious from the View..Toolbars.. menu, that Parsing is the Rubberduck toolbar.

**Comment by retailcoder** [comment]
good idea. at first I implemented that toolbar just as a "parser state" there's-no-status-bar-in-the-VBE-so-here-is-my-workaround... but yeah we can definitely add more to it, and name it "Rubberduck".

**Comment by ThunderFrame** [comment]
Implemented by #1080
