### ISSUE TITLE
High CPU usage when Parser state retruns Error

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#1033]
I have 4 projects present under CorelDRAW, 1 of which is protected, and at least one of which has compiler directives, so Rubberduck parser returns an Error status. I'm unsure whether it is the protected status, the number of projects, the compiler directives, or the host, or some combination of those things, that is causing the problem

I have 4 cores (8 loigical processors), and one of the processors goes to 100% usage for approximately 128 seconds after the parser runs, then returns to normal. If I run the parser again, the CPU usage spikes again, for another approx 128 seconds.

**Comment by Pitterling** [comment]
I'm also facing high CPU consumption, causing Excel almost not responding, literally Excel is not usable anylonger. Also my Parser returns an Error status. I'm using Office 2016 - 64bit

**Comment by retailcoder** [comment]
@Pitterling using release version 1.4.3?

**Comment by Pitterling** [comment]
no, the latest commit from the next branch

**Comment by autoboosh** [comment]
Some possible causes:

1. many COM calls (especially QualifiedModuleName.Project, only loading the project once has sped up rubberduck quite a bit)
2. many RuntimeBinderExceptions

**Comment by retailcoder** [comment]
`QualifiedModuleName.Project` is used in determining equality and a hash code, which is fundamentally important for that type. I'm open to suggestions but everything else I tried was too frail and broke the resolver, which pretty much kills the duck.

The `RuntimeBinderException` are thrown in the `Declaration` class, notably to determine whether a declaration is an array. The lack of a common interface between similar `ParserRuleContext` types is partly responsible for these - that and my lazy coding (*doing it right* is feasible, but requires quite a lot more code than a `dynamic` check).

I'm sure CPU usage has greater bottlenecks, we need to profile it, but the parser itself eats up lots of resources too.

**Comment by autoboosh** [comment]
In QualifiedModuleName there's this line of code:

`public VBProject Project { get { return _project ?? (_component == null ? null : _component.Collection.Parent); } }

If the project is cached in the constructor instead of being calculated each time the property is called, a VBA project that usually spends a few minutes in the pending state suddenly only takes a few seconds. Parsing is still relatively slow though.

Could this be because it uses a COM call for each property access? I don't know much about COM etc. so could be totally wrong. The visual studio performance profiler showed that ~15% of CPU is spent in that property...

**Comment by retailcoder** [comment]
@autoboosh yikes! Indeed, some caching is in order. I committed a modification to `Declaration` yesterday, dramatically reducing the number of `RuntimeBinderException` thrown by `IsArray` and `HasTypeHint`; I'll take a look at `QualifiedModuleName`.

**Comment by autoboosh** [comment]
Thank you. Just tested it and it is extremely fast compared to before!

**Comment by retailcoder** [comment]
CPU usage is still a concern though. I noticed the initial parse gets triggered by the code inspections' view model at startup, so the initial parse performance (and CPU usage) will be further improved tonight when I fix the inspections' view model to no longer register/unregister parser state changes, and work like the code explorer instead (i.e. register parser state changes in constructor, and don't call for a refresh at startup). If you look at the debug output when you bring up the VBE, you'll notice every module gets resolved *twice*.

**Comment by Pitterling** [comment]
I just tried the latest commit and see a lot of RuntimeBinder Exceptions, like these:

`Exception thrown: 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in System.Core.dll 
("'Rubberduck.Parsing.Grammar.VBAParser.ConstSubStmtContext' does not contain a definition for 'LPAREN'")`

**Comment by retailcoder** [comment]
@Pitterling that's my bad - I merged from my fork into the `CodeExplorer` branch - I intended to merge into `Next`... merged now, please pull the changes... when the `DeclarationType` is `DeclarationType.Const` the `IsArray` getter shouldn't even try to access the ParserRuleContext anymore.

**Comment by Hosch250** [comment]
Is this still an issue?

**Comment by Pitterling** [comment]
@Hosch250 seems to be fixed
