### ISSUE TITLE
RubberDuck menu items should be enabled depending on context

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#1037]
Many menu items remain enabled, regardless of whether they're actually *useful* at the time.

For example:
*Test Method* and *Test Method (Expected Error)* are both enabled, even if the project doesn't have any code modules. Executing the menu items does not produce an error, or make any change.

**Comment by sshikov** [comment]
At the moment some of commands in mouse context menu, like Find all references, could be disabled even if usable right now. 

I can't understand, how it depends of current editor context.
