### ISSUE TITLE
Unit Testing menu item texts require verbs

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#1038]
*Test* can be an adjective, a noun and a verb, so *Test Module* is ambiguous.

Adding *Add * or *Insert* before *Test Module*, *Test Method* and *Test Method (Expected Error)* would clarify the menu actions.

**Comment by Hosch250** [comment]
These are already in the Insert menu, though, are the not?

**Comment by ThunderFrame** [comment]
@Hosch250 I haven't pulled from upstream for a few days. Not back at my PC until later. Will check then, but earlier, the unit testing mrnus lacked *Add*.

**Comment by retailcoder** [comment]
I remember having this at one point:

    Add
      Add test module
      Add test method
      Add test method (expected error)

I figured clicking "Add" then "test module" would read just like that ;-)

**Comment by Hosch250** [comment]
I think this is good the way it is.
