### ISSUE TITLE
Should be able to launch a Git Shell on the current repo from within the VBE

### ISSUE THREAD

**Issue by ckuhn203** [rubberduck-vba/Rubberduck#104]

**Comment by ckuhn203** [comment]
This is a fairly big feature. There are two different ways I can think to do it. We can either check to see if Git is actually installed, and open the default command line tool or reinvent the wheel with our own custom console program utilizing LibGit2Sharp. 

RD doesn't actually require Git to be installed for source control to work. LibGit2Sharp provides all of the functionality, so I'm not certain which route to go yet. Either way, won't be in the initial release.

**Comment by Hosch250** [comment]
I think I'll go the VS way and require Git to be installed.

**Comment by ckuhn203** [comment]
That's a good call Hosch, but we'll need to warn users that it won't automatically import/export into the editor when using the cli

**Comment by Hosch250** [comment]
@ckuhn203 Only if I don't figure out how to detect when the repo is externally changed before release.

**Comment by retailcoder** [comment]
Just use a `FileSystemWatcher`, and prompt to reload when a file is modified outside the VBE! The hard part is to avoid prompting for every single module when every file is modified...

**Comment by Hosch250** [comment]
The harder part will be to avoid prompting during commits, fetches, &c.

**Comment by retailcoder** [comment]
Just unregister the FSW before these operations :wink:

**Comment by ckuhn203** [comment]
The mug beat me to the punch. Yes, a FileSystemWatcher was my original plan.

**Comment by ThunderFrame** [comment]
We know we can't (currently) use the immediate window as a shell, but maybe a new window could host a git shell, or at least pipe things so that the window looks like a git shell?

**Comment by ckuhn203** [comment]
@Thunderframe the purpose behind launching a Cli is to give access to the full power of Git. I didn't expose everything that Git can do through the VBA/Git adapter library. Just the most basic/common functionality. 
If a user wants to cherry pick, rebase, etc, they need an actual Git client to do it. 

Given that we want to expose the full Git Cli (ala visual studio), I don't think it makes sense to try to embed it in a tool window. The simplest thing to do is to just launch an external process.

**Comment by retailcoder** [comment]
Okay what's the deal with this issue, isn't it trivially implemented?

**Comment by ThunderFrame** [comment]
@ckuhn203 agreed. I confess it was more of a "we put a git click in a tool window *because we can*" idea.

It is possible, I assume, to just pipe commands from a tool window to a git shell, but just because we *could*, doesn't mean that we *should*...

**Comment by ckuhn203** [comment]
Relatively trivial @retailcoder. What I was never sure of is how to detect if there's a Git Cli installed. If we can detect it, we can launch it.
