### ISSUE TITLE
"Function return value not used" inspection false positive with interfaces

### ISSUE THREAD

**Issue by autoboosh** [rubberduck-vba/Rubberduck#1041]
The "Function return value not used" inspection doesn't work with interfaces.

Offending code:

```
IFoo
Public Function Bar() As Integer
    Bar = 42
End Function
```

```
Baz
Implements IFoo

Public Function IFoo_Bar() As Integer
    IFoo_Bar = 42
End Function
```

```
TestModule
Public Sub Test()
    Dim bazObject As IFoo
    Set bazObject = New Baz
    Dim result As Integer
    result = bazObject.Bar
End Sub
```

This reports the result value of `Baz.IFoo_Bar `as not being used even though it is.

**Comment by autoboosh** [comment]
Sorry about the commit spam, had some troubles squashing the commits into one. Only the last one should be considered the correct one.

**Comment by Vogel612** [comment]
You should be able to squash them down by running `git rebase -i next` after fetching an update for next from rubberduck-vba/Rubberduck

**Comment by autoboosh** [comment]
Done and merged.
