### ISSUE TITLE
2Byte Character Error?

### ISSUE THREAD

**Issue by kotaro4** [rubberduck-vba/Rubberduck#1044]
Hello, developpers.

I installed 1.4.3 and try "Rename" function but it does not work well for some reason.
So I wrote very simple code and tested.

![2016-02-09 2](https://cloud.githubusercontent.com/assets/17133446/12906430/7c3483ba-cf23-11e5-9be0-4a904931e337.png)

Next, I changed procedure name to English and tested
![2016-02-09 3](https://cloud.githubusercontent.com/assets/17133446/12906512/66ae7bf8-cf24-11e5-9b84-2fdc3cb29f57.png)

Succesful

I concluded that 2 Byte character procedure name is a bad influence on the "Paraser" program.
(In addition, It was able to change the "x" into 2 byte characters, but the reverse is "Paraser" error)

I want you to also support 2-byte character program, if possible...

I'm looking forward to awesome tool of next version.

Thank you

**Comment by Hosch250** [comment]
This is an interesting bug for sure.  If the VBE supports these, we definitely should.

**Comment by Vogel612** [comment]
Okay then.. according to http://stackoverflow.com/q/22560121/1803692 (thanks @ThunderFrame) the VBE uses Codepages to encode characters. I guess the Parser just assumes Unicode encoding for the Parsed content. :see_no_evil: ... 

Or we have a really bad case of Grammar Problem here, where the used characters are not taken into account for parsing. It might well be a combination. :fearful:

**Comment by kotaro4** [comment]
Hello Mr. @Hosch250 @Vogel612 

My Installation
OS: WIndows 10 (64 bit)
Office: 2016 (32 bit)

2 byte name is poplar in Japan.
I know Codepages are used to encode characters for the first time. thanks

I cannot write C++ code but translate the notation of menus, etc..
If you need Japanese translator, I willing to cooperate.

Thank you

**Comment by Hosch250** [comment]
@kotaro4 You have the same setup I do, except I have 64-bit Office.  Also, Rubberduck is written in C#, so C++ code likely wouldn't work, but it would be awesome of you would finish the Japanese translation!  We already received a preliminary translation, but many items have since been updated and need to have the translation revised, and many others have been added.  Please visit us in our warroom if you are interested: http://chat.stackexchange.com/rooms/14929/vba-rubberducking

**Comment by ckuhn203** [comment]
Well, it's definitely a grammar issue, as you can see right here. https://github.com/rubberduck-vba/Rubberduck/blob/next/Rubberduck.Parsing/Grammar/VBA.g4#L921

I don't think it would be terribly hard to fix though. We've at least a few Japanese users, so I believe this is worth doing. I'm just a little worried that even if we fix the grammar, something will blow up further up the stack and not work right. 

@retailcoder thoughts?

**Comment by ckuhn203** [comment]
Ok. It took some digging, but [Japanese identifiers are described in section 3.3.5.1.1 of the language specification.](https://msdn.microsoft.com/en-us/library/ee199767.aspx) Relevant quote from [3.3.5.1 NonLatin Identifiers:](https://msdn.microsoft.com/en-us/library/ee199825.aspx)

> Any Unicode character that corresponds to a character in a Microsoft Windows code page with a single byte code point in the **range %x80-FF** is a valid `<CP2-characters>`.

This stuff is seriously not for the front of heart. 

```
Japanese-identifier = first-Japanese-identifier-character *subsequent-Japanese-identifier-character 
first-Japanese-identifier-character = (first-Latin-identifier-character / CP932-initial-character) 
subsequent-Japanese-identifier-character = (subsequent-Latin-identifier-character / CP932-subsequent-character) 
CP932-initial-character = < character ranges specified in section 3.3.5.1.1> 
CP932-subsequent-character = < character ranges specified in section 3.3.5.1.1> 
 
Korean-identifier = first-Korean-identifier-character *subsequent Korean -identifier-character
first-Korean-identifier-character = (first-Latin-identifier-character / CP949-initial-character ) 
subsequent-Korean-identifier-character = (subsequent-Latin-identifier-character / CP949-subsequent-character) 
CP949-initial-character = < character ranges specified in section 3.3.5.1.2> 
CP949-subsequent-character = < character ranges specified in section 3.3.5.1.2> 
 
simplified-Chinese-identifier = first-sChinese-identifier-character 
         *subsequent-sChinese-identifier-character 
first-sChinese-identifier-character = (first-Latin-identifier-character / CP936-initial-character)
subsequent-sChinese-identifier-character = (subsequent-Latin-identifier-character / CP936-subsequent-character) 
CP936-initial-character = < character ranges specified in section 3.3.5.1.3> 
CP936-subsequent-character = < character ranges specified in section 3.3.5.1.3> 
   
traditional-Chinese-identifier = first-tChinese-identifier-character 
                  *subsequent-tChinese-identifier-character 
first-tChinese-identifier-character = (first-Latin-identifier-character / CP950-initial-character) 
subsequent-tChinese-identifier-character = (subsequent-Latin-identifier-character / CP950-subsequent-character) 
CP950-initial-character = < character ranges specified in section 3.3.5.1.4> 
CP950-subsequent-character = < character ranges specified in section 3.3.5.1.4> 
 
codepage-identifier = (first-Latin-identifier-character / CP2-character) 
       *(subsequent-Latin-identifier-character / CP2-character) 
 
CP2-character = <any Unicode character that has a mapping to the character range %x80-FF in a Microsoft Windows supported code page> 
```

**Comment by retailcoder** [comment]
@ckuhn203 the `LETTER` lexer token doesn't need to contain every single possible character that can be entered in the VBE for an identifier :-)

I (as well as the grammar's original author) assumed that VBA wanted to see Latin characters, and if there were non-Latin identifiers they'd be supported if surrounded with square brackets - after all, square-bracketed identifiers could include whitespace and other normally-illegal characters.

The solution is simple: redefine the `ambiguousIdentifier` rule (and `certainIdentifier` too), to allow *anything but whitespace*, and boom, done. Let's not put the specs in the grammar, we don't *need* to validate identifiers in the grammar.

**Comment by kotaro4** [comment]
Mr. @Hosch250 Thank you invite me to chat room.
But I have no reputation on the site. It seems that I have no right to talk in your room...

Mr.@ckuhn203  This tool have really great, especially about "Rename" function.(And next version's Smart Indenter!) I want to spread this awesome tool for Japanese.
This Unicode? problem is inevitable in Japanese...
(Some writes procedure/variable name in kanji, other writes only in alphabet, other writes in mix-kanji-alphabet....)

I don't have as specialized knowledge as you all.
But I'm happy if i can support even just aspects of the language translation.
Thank you

**Comment by Hosch250** [comment]
@kotaro4 If you enter the room while signed in to Code Review, I can give you write access.

**Comment by kotaro4** [comment]
Mr.@Hosch250 I singed in Coder Review. And I try to change my profile...

**Comment by kotaro4** [comment]
Yes! But I cannot write...
![2016-02-10](https://cloud.githubusercontent.com/assets/17133446/12939760/8c41c4b4-d006-11e5-91fb-e4dadba5fae0.png)
