### ISSUE TITLE
SelfAssignedDeclarationInspection false positives

### ISSUE THREAD

**Issue by autoboosh** [rubberduck-vba/Rubberduck#1048]
Found this one while running Rubberduck on a small code base I'm maintaining. The code base has a lot of code such as `Public Const CONST_VAL = 42` which led to a slew of SelfAssigned issues being reported.

The problem is that the `Declaration.IsSelfAssigned` property does not only return true for `As New` but also for more general cases of self-assignment.

What we are probably looking for are so called _automatic instantiation variables_. See [5.2.3.1.1 Variable Declarations](https://msdn.microsoft.com/en-us/library/ee177363.aspx).

I'll have a look and send a PR :)

**Comment by retailcoder** [comment]
Well spotted. The inspection is currently only looking at the `IsSelfAssigned` flag:

            return UserDeclarations
                .Where(declaration => declaration.IsSelfAssigned)
                .Select(issue => new SelfAssignedDeclarationInspectionResult(this, issue));

It should also look at the `DeclarationType` and only return results for `DeclarationType.Variable` declarations.
