### ISSUE TITLE
RubberDuck should add items to VBA's Insert menu

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#1052]
I often use the Insert menu, or Alt-i-m, Alt-i-c and Alt-i-u for adding modules, class modules and user forms, respectively.

Inserting a Test Module (is Alt-i-t available)/and a Test Method (is Alt-i-s available) should be just as easy. User has choice of inserting from Insert menu, *or* RubberDuck menu.

**Comment by retailcoder** [comment]
You mean both?

One of the things 2.0 is doing as far as menus are concerned, is bringing everything under a "Rubberduck" master menu - in all context menus, Rubberduck functionailty will be under a Rubberduck menu.

This avoids having functionality scattered everywhere, and makes it easier for us to determine where such or such menu item should go. It ultimately makes it easier for our users, who know they'll find everything they're looking for under a "Rubberduck" menu.

**Comment by ThunderFrame** [comment]
Hmm, I agree, centralised vs scattered, can be confusing. I forget which Add-In takes which approach, but IIRC, SmartIndenter, CodeCleaner and MZTools take varying approaches.

Maybe it's user configurable, along with the accelerators, should there be a conflict?

IMO if we want TDD to be a first class behaviour, then *those* menu items should be first class Inset menu items.

**Comment by retailcoder** [comment]
The *Project Explorer* context menu will have it under Rubberduck > Unit Testing; the *Code Explorer* being a Rubberduck feature itself, its context menu won't have a "Rubberduck" parent, and its "Add" dropdown can definitely have "Test Module" and "Test Method" entries.

**Comment by Hosch250** [comment]
What's going on here?
