### ISSUE TITLE
Rubberduck should integrate help content 

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#1053]
IMO, built-in help has been going downhill since Office 97, but 2013 and 2016, by default, force you to use online help. That's irritating, particularly when you hit F1 by mistake.

Integrating help content could draw in official _and_ user-contributed content (OOP topics, :smile: )

This [project](https://github.com/OfficeDev/VBA-content) looks like an opportunity.

**Comment by ThunderFrame** [comment]
Now that Rubberduck is collecting TypeInfos, and is context-aware of the selected symbol, or symbol under the cursor, we *can* launch a local copy of help (for VBA hosts that would otherwise force you to use online help), if the user has a copy of help available.

Offline help for Excel, Access, Word and PowerPoint is available for download from [GitHub](https://github.com/OfficeDev/VBA-content/tree/master/Offline-Docs). Rubberduck could look for a local copy of help in the default path, or allow a user to define the locations of offline help files.

`System.Windows.Forms.Help.ShowHelp` allows us to launch a specified help-file at a specific topic. All we need is the `helpfile` from the TypeLibarary, the `helpcontext` ID from each TypeInfo member, and a mapping from the helpconext ID to the topic address.

I've worked out how to create the mapping from helpcontext ID to topic address, and how to launch help at the correct page.

If the Helpcontext IDs can be collected from TypeInfos, adding context-aware help should just be a matter of a assigning a hotkey and building the launch mechanisms.

Here's a mock-up:
![contexthelp](http://i.stack.imgur.com/Zx6eZ.gif)

**Comment by retailcoder** [comment]
out of scope
