### ISSUE TITLE
Allow declarations to exist in multiple places

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#1055]
This sounds crazy, but it's the only way we'll be able to resolve references to anything declared inside a conditional compilation block - and that's not an uncommon situation:

    #If Win64 Then
        Declare PtrSafe DoSomething(...)
    #Else 
        Declare DoSomething(...)
    #EndIf 

Here `DoSomething` must be allowed to exist in two places, and references to `DoSomething` must resolve to the same, unique (in-scope) identifier.

The solution is to modify the `Declaration` type to have more than just one `Context` and `Selection`. By doing this we'll not only *not break* the resolver with such declarations, we'll also be able to refactor/rename all declaration sites at once, which would be impossible to do if we pre-processed the parser input to only account for the "live" compilation path, or if we ignored things declared inside precompiler directives.

This is a breaking change, but a necessary one.

**Comment by ThunderFrame** [comment]
You just made it easy for me to write `Evil #3` :smiling_imp: 

This compiles *and* runs under 32-bit Office 2013. Changing the case of any instance of `Sub Foo` or `Sub Boo`, causes *all* instances of `Foo` and `Boo` to `foo` and `boo`.

```vb
Option Explicit

#If Win64 Then
 '@TestModule
  Sub Foo()
  '@TestMethod
  Rem'@TestMethod
  Sub Bar()
  'TODO: Make time
  Sub Boo()
  @Folder Foo
  Sub Moo()
  @ignore '....
  Sub Now()
#Else
  Sub Foo()
    Debug.Print Now()
  End Sub
#End If

Sub Bar()
#If Win64 Then
  Sub Foo()
  Sub Bar()
  Sub Boo()
  Sub Moo()
  Sub Now()
  Call Foo
#ElseIf Win64 And Win7 Then
  Call Foo
#Else
  Call Foo
#End If
End Sub

#If Win64 Then
  
  Sub Boo(arg1 As String)

  End Sub
  Option Explicit
  Option Explicit
  Explicit Option 'This entire line is red in my VBE
  Stop Stop 'This entire line is red in my VBE
  Random Words
  Open 'This entire line is red in my VBE
  End
  Sub Rem
  Stop
  Foo Bar
  Boo Now
  
#Else
  Sub Moo()
    Dim dt(0) As Date
    dt(0) = Now
    Boo dt
  End Sub
  Sub Boo(arg1() As Date)
    Debug.Print arg1(0)
  End Sub
#End If
```

**Comment by retailcoder** [comment]
@ThunderFrame won't compile/run under x64 though. Yes, the grammar is more permissive than what VBA allows, but the only code we'll process, will be code that compiles and runs. I'm not sure what behavior this is supposed to test.

**Comment by ThunderFrame** [comment]
@retailcoder  - My point is that VBA compiler ignores the lines that are out of *Condition*, while the VBE seems to identify individual-line syntax issues (but is tolerant of them), but doesn't identify multi-line syntax issues.
If a False case Compiler-Condition block that doesn't have any immediate signs of syntax-issues won't compile, then the developer doesn't know about the problems unless they switch platforms (which they might not have access to). VBE will inform the user that the project compiles and runs, but Rubberduck will currently report an error?
Likewise, VBE will apply case-sensitive changes across *all* types in all compiler condition blocks, even if the types have differing signatures. I'm unsure whether you intend that Rubberduck be able to refactor code that's in a False-Case compiler condition?

**Comment by ThunderFrame** [comment]
FYI - I believe the Microsoft term for pre-compiled VBA, is *Twiddled*

**Comment by retailcoder** [comment]
> *VBE will inform the user that the project compiles and runs, but Rubberduck will currently report an error?*

Yes, exactly. I see this as a huge (yet unexpected) benefit, too.

> *I'm unsure whether you intend that Rubberduck be able to refactor code that's in a False-Case compiler condition?*

Absolutely! It would actually be *damaging* if it didn't.

    #If DEBUG Then
        Dim foo As Integer
    #Else 
        Dim foo As Long
    #EndIf 

Renaming `foo` in DEBUG should not break the production code!

**Comment by ThunderFrame** [comment]
hmmm. Maybe it should be an option on a refactoring/inspection, to include/exclude *out-of-condition* code?

**Comment by retailcoder** [comment]
@ThunderFrame that would be very complicated to implement, for very little benefit IMO...

**Comment by retailcoder** [comment]
Ok something's up. This doesn't parse:

    #Const DEBUG_ = True
    #If DEBUG_ Then
        Dim foo As Integer
    #Else 
        Dim bar As Integer
    #EndIf 

The `SyntaxErrorException` is thrown in the `macroElseBlockStmt`. Investigating.

**Comment by retailcoder** [comment]
Bwahahaha indentation is what's breaking it. This parses:

    #Const DEBUG_ = True
    #If DEBUG_ Then
    Dim bar As Long
    #ElseIf Not DEBUG_ Then
    Dim foo As Integer
    #Else
    Debug.Print "WTF"
    #End If

**Comment by retailcoder** [comment]
Okay, I give up. This parses:

    #Const DEBUG_ = True
    #If DEBUG_ Then
    Dim bar As Long
    #Else
    Dim FOO As Integer
    #End If
    
    Option Explicit
    
    Sub DoSomething()
    #Const DEBUG_ = True
    #If DEBUG_ Then
    Dim bar As Long
    #ElseIf Not DEBUG_ Then
    Dim FOO As Integer
    #Else
    #Const FOO = 42
    #If FOO = 12 Then
    Debug.Print "WTF"
    #End If
    #End If
    End Sub

But add a single whitespace anywhere, and nothing works anymore. I'm documenting it as a limitation, and moving on.

**Comment by retailcoder** [comment]
Now, regarding the actual issue. Allowing a declaration to exist in multiple places won't be enough; the type of a declaration can depend on the execution path, so it's back to square one here.

**Comment by autoboosh** [comment]
Did your macro example work before? This might be something I broke with the recent grammar change.

**Comment by retailcoder** [comment]
Ok. Now that the parser handles everything we throw at it, we're done here. This issue was created to tweak the resolver so that this:

    #If VBA7 Then
      Private Declare PtrSafe Function GetWindowLong Lib "user32" Alias "GetWindowLongA" _
    (ByVal hwnd As LongPtr, ByVal nIndex As LongPtr) As LongPtr
    #Else
        Private Declare Function GetWindowLong Lib "user32" Alias "GetWindowLongA" _
    (ByVal hwnd As Long, ByVal nIndex As Long) As Long
    #End If

...would resolve usages of `GetWindowLong` correctly. In theory, allowing a `Declaration` to exist in multiple places would solve *this specific case*, but then this:

    #If VBA7 Then
        Dim foo As Long
    #Else
        Dim foo as Integer
    #End If

Is just as legal, and yet the `Declaration` would not only need to *exist in multiple places*, it would also need to be allowed to have a different type, and this completely wrecks the model.

I don't think there's a solution for this. Let's document it as a limitation, and move on.

**Comment by ThunderFrame** [comment]
how about procedures *before* a declaration?

```vb
#If VBA7 Then
  
  Private Declare PtrSafe Function GetWindowLong Lib "user32" Alias "GetWindowLongA" _
    (ByVal hwnd As LongPtr, ByVal nIndex As LongPtr) As LongPtr
   
   Sub VBA7Proc()

   End Sub

#Else
     
  Private Declare Function GetWindowLong Lib "user32" Alias "GetWindowLongA" _
    (ByVal hwnd As Long, ByVal nIndex As Long) As Long

   Sub VBA6Proc()

   End Sub

#End If
```

**Comment by retailcoder** [comment]
Wow, you just broke my parser rule again.

**Comment by retailcoder** [comment]
@ThunderFrame fixed in cd8c727 :smiling_imp:

**Comment by retailcoder** [comment]
Applying [status-deferred] to this issue. The Roslyn compiler uses the precompiler constants and only processes the "live" code; we should be doing the same... but that means accessing the precompiler constants: not simple.

**Comment by autoboosh** [comment]
Tried out @ThunderFrame's last code example in this thread and the `Declaration `threw a `System.Reflection.AmbiguousMatchException` on line 322:

`var method = Context.GetType().GetMethod("typeHint");`
