### ISSUE TITLE
Parser bug with Rem statements immediately followed by special characters

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#1057]
Well, this one seems to confuse VBE too!

It's the #, $, % and & that VBE seems to remove (because of their implied types, but in doing so, VBE leaves the line as a comment), even though the line is not a comment!

Rubberduck, I think, fails on all of the statements.

**This code must be pasted into a module**, as VBE will strip out some of the characters, and honour the Rem statements, and will even compile and run the code, but if you comment all the lines, then uncomment them, VBE will no longer honour all of the Rems as comments, and will not compile or run.

```vb
Sub Foo()

  Rem~Test
  Rem`Test
  Rem!Test
  Rem/@Test
  Rem#Test   'Was originally pasted as "Rem#Test"
  Rem$Test   'Was originally pasted as "Rem$Test"
  Rem%Test   'Was originally pasted as "Rem%Test"
  Rem^Test
  Rem&Test   'Was originally pasted as "Rem&Test"
  Rem*Test
  Rem(Test
  Rem)Test
  Rem-Test
  Rem_Test   'It seems "Rem_" is a valid name/prefix for a variable/method?
  Rem=Test
  Rem+Test
  Rem[Test
  Rem{Test
  Rem]Test
  Rem}Test
  Rem\Test
  Rem|Test
  Rem;Test
  Rem:Test
  Rem'Test
  Rem"Test
  Rem,Test
  Rem<Test
  Rem.Test
  Rem>Test
  Rem/Test
  
  'Special cases of Rem(*
  Rem()
  Rem(0)
  Rem(0 to 1)
  Rem(0,0)
  Rem(x)

  Debug.Print Now

End Sub

Sub Rem_Test()

End Sub
```

**Comment by retailcoder** [comment]
`Rem` is defined as R-E-M-WhiteSpace, and can't quite be anything else. `Rem` is pretty much an edge case on its own, I don't think we need to account for and patch the VBE's own bugs with it!

**Comment by ThunderFrame** [comment]
Yes, VBE has issues with `#, $, % and &`, and I agree we shouldn't try to second guess the VBE.


But for the other special characters (excluding underscore), the written spec and the implemented spec are seemingly two different things. Shouldn't Rubberduck adhere to the Written Spec, *unless* we find specific Implementation exceptions/differences?

**Comment by ThunderFrame** [comment]
FWIW, the list of characters that may immediately follow `Rem` and *still* be considered a comment by the VBE are:

> Any ASCII character with a code between 0 and 127, **except**:
> - `0`-`9`
> - `A`-`Z`
>-  `_` an underscore
> - `a`-`z`

In CP1252, `Rem` is not treated as a comment when followed by any character with a code between 128 and 255.

If anybody ever needs the regex to find comments in a codepane (regardless of the spec), this should do it:

`('|Rem[\x01-\x08\x0B-\x0C\x0E-\x2F\x3A-\x40\x5B-\x5E\x60\x7B-\x7F])(.* _\n)*.*$`

**Comment by MDoerner** [comment]
When using this regex, just keep in mind that it will not necessarily find all Rem comments since the pretty printing gets in the way as mentioned in the original post.

**Comment by ThunderFrame** [comment]
I checked the p-code. The  `#`, `$`, `%` and `&` (and presumably `^` under 64-bit Office) are *permanently* lost once entered. For "normal" comments such as `Rem Foo`, the space between `Rem` and `Foo` is part of the comment, and in Office 2016 32-bit, the p-code has the op-code for a `Rem` statement `0x00E4` followed by 2 bytes indicating the length of the comment, followed by the comment, followed by 1-4 Null bytes for a 4-byte boundary alignment.

So, if we ever parse the code from p-code, we'll at least be able to determine that the statement is a comment, even if we can't determine what the missing character was.
