### ISSUE TITLE
Parser Error with comments that do not contain space after single quote

### ISSUE THREAD

**Issue by autoboosh** [rubberduck-vba/Rubberduck#1059]
This works:

`' Test`

This doesn't (note the lack of whitespace):

`'Test`

If there's no space before "Test" a parser error occurs.

**Comment by retailcoder** [comment]
oh, that's new. very possibly introduced by the now [too] relaxed `IDENTIFIER` lexer rule.

**Comment by autoboosh** [comment]
What I forgot to mention was that if there's only a comment single quote, without any actual comment, an error occurs as well. E.g.

`'`

**Comment by Vogel612** [comment]
So the grammar for comments doesn't account for this, I think @retailcoder has the right idea there... for reference:

    COMMENT : WS? ('\'' | ':'? REM WS) (LINE_CONTINUATION | ~('\n' | '\r'))* -> skip;

As you can see, a WS token is only needed after REM

**Comment by retailcoder** [comment]
@Vogel612  yeah.. basically I forgot to exclude the apostrophe in the `IDENTIFIER` rule:

    IDENTIFIER :  (~[!\]\(\)\r\n\t ])+ | L_SQUARE_BRACKET (~[!\]\r\n])+ R_SQUARE_BRACKET;

(and the dot, for that matter)

In other words, I completely broke the parser. Please refrain from creating new parser issues until I fix this.
