### ISSUE TITLE
Indent current procedure duplicates the last couple of lines

### ISSUE THREAD

**Issue by autoboosh** [rubberduck-vba/Rubberduck#1061]
Applying the Indent->Current procedure functionality to the following code:

```
Public Sub Foo()
    Dim a As String
    Dim b As Integer
    Dim c As Double
End Sub
```

Leads to the following result:

```
Public Sub Foo()

    Dim a As String
    Dim b As Integer
    Dim c As Double
End Sub

    Dim c As Double
End Sub
```

**Comment by retailcoder** [comment]
lol, indenter isn't halfway implemented yet. I merely made a "first pass" of translating the VB6 to C#, and possibly introduced new bugs too. We need an `IIndenterSettings` implementation (and settings page) to continue the indenter work.
