### ISSUE TITLE
Remove NuGet packages?

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#1062]
Nuget dependencies are outright *dangerous* as far as version management is concerned. Any breaking change in any of the Nuget dependencies will send everything to Hell, because Nuget defaults to the latest version.

Properly configuring it is more painful than it needs to be - let's just move the .dll dependencies into our `libs` folder and reference them from there instead.

**Comment by ckuhn203** [comment]
Or we could just specify the version and keep the binaries out of the repo. 
https://docs.nuget.org/create/versioning#specifying-version-ranges-in-.nuspec-files

**Comment by Hosch250** [comment]
What's up here?

**Comment by retailcoder** [comment]
I'm happy with the way things are right now. I think.
