### ISSUE TITLE
Parser bugs when Optional parameter default value is expression/contains operator or Explicit Enum/Const

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#1063]
I haven't synced with Next since before the Parsing breaks...

Expressions, whether they're just parentheses, or they involve operators, break the parser.

Referring to an enum member by explicitly referring to the enum itself, breaks the parser.

Likewise, referring to a constant, by explicitly referring to a Module, breaks the parser.

I expect anything with a period in it (eg, type members, class members, etc) will break the parser)

```vb
Public Enum eTest
  Boo = 1
  bar = 6
  [_min] = Boo
  [_max] = bar
End Enum

Const cA As Boolean = True
Const cB As Boolean = True

'special char operators
Sub foo1(Optional mForceOpen As Boolean = 6 = 6)
End Sub

Sub foo2(Optional mForceOpen As Boolean = 6 + 6)
End Sub

'Bitwise Operators
Sub foo3(Optional mForceOpen As Boolean = cA Or cB)
End Sub

'Keyword operators
Sub foo4(Optional mForceOpen As Boolean = 6 Eqv 6)
End Sub

'Parenthesis expressions
Sub foo5(Optional mForceOpen As Boolean = (6))
End Sub

'Expicit enum references
Sub foo6(Optional mForceOpen As eTest = eTest.bar)
End Sub

Sub foo7(Optional mForceOpen As eTest = eTest.[_min])
End Sub
'explicit Constant
'
Sub foo8(Optional mForceOpen As eTest = Module3.Module3Const)
End Sub
```

**Comment by retailcoder** [comment]
Good timing, I was just going to start fixing the grammar :smile:

**Comment by retailcoder** [comment]
Hmm no repro on the enum. It parses and resolves fine:

    Public Enum eTest
      renamed = 1
      bar = 6
      [_min] = renamed
      [_max] = bar
    End Enum
    
Nice catch on optional parameter default values though!

    argDefaultValue : EQ WS? (literal | ambiguousIdentifier);

An `argDefaultValue` is defined as an equal sign followed by a literal or a single identifier - and apparently that needs to be a `valueStmt`.

**Comment by ThunderFrame** [comment]
I should have been more clear, the Enum itself isn't causing the problem, but the Enum has to be there for compilation. It's just the use of the Enum in the optional params, that causes the problems.

**Comment by ThunderFrame** [comment]
Be sure to see #1064 which also adds Octal literals as problems in Optional Parameters (and everywhere else)

**Comment by retailcoder** [comment]
Ah, all clear now. Well, there's no more problem with that code module in my build now. Moving on to #1064...

Very very nice catch there! :+1:
