### ISSUE TITLE
Unit Testing Settings

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#1065]
Unit testing needs some options.

 - Whether the `Rubberduck.AssertClass` instance is early-bound or late-bound should be configurable. Use early binding by default.

   Implementation details:

   - When early binding is selected, any new test module should be created with the `AssertClass` instance already initialized, and a reference to the Rubberduck type library should be added to the project if it's not already there (this is the current 1.x behavior)
   - When late binding is selected, any new test module should be created with the `AssertClass` instance declared as `Object`, a `@ModuleInitialize` method that creates and assigns the instance, and a `@ModuleCleanup` method that destroys it. What to do with existing test modules remains TBD; let's leave them unchanged for now.

 - Whether the `Assert` object should be an instance of a `Rubberduck.AssertClass`, or an instance of a `Rubberduck.PermissiveAssertClass`.
 - Whether a new test module should include stub `@ModuleInitialize` and `@ModuleCleanup` methods.
 - Whether a new test module should include stub `@TestInitialize` and `@TestCleanup` methods.
 - Whether a new test module should include a `@TestMethod` stub.

**Comment by retailcoder** [comment]
Ref. #785

**Comment by Hosch250** [comment]
I'll handle the UI, and maybe the implementation if no one else handles it.

**Comment by Hosch250** [comment]
User interface implemented.
