### ISSUE TITLE
Indenter Settings

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#1066]
The `Rubberduck.Settings` namespace already contains an `IndenterSettings` class that's only waiting for a UI and default values:

    public class IndenterSettings : IIndenterSettings
    {
        public bool IndentProcedure { get; set; }
        public bool IndentComment { get; set; }
        public bool IndentCase { get; set; }
        public bool IndentDim { get; set; }
        public bool AlignContinuations { get; set; }
        public bool IndentFirst { get; set; }
        public bool AlignEndOfLine { get; set; }
        public bool AlignDim { get; set; }
        public bool ForceDebugStatementsInColumn1 { get; set; }
        public bool EnableUndo { get; set; }
        public int IndentSpaces { get; set; }
        public int EndOfLineAlignColumn { get; set; }
        public int AlignDimColumn { get; set; }
        public bool ForceCompilerStuffInColumn1 { get; set; }
        public bool IndentCompilerStuff { get; set; }
        public bool AlignIgnoreOps { get; set; }
        public bool EnableIndentProcedureHotKey { get; set; }
        public bool EnableIndentModuleHotKey { get; set; }
        public EndOfLineCommentStyle EndOfLineCommentStyle { get; set; }
    }

These settings need to be on their own dedicated tab in the settings dialog.

---

If user has *Smart Indenter* add-in installed, we should offer to import Smart Indenter settings from the Windows registry where the add-in saves them (details are in the legacy VB6 code).

**Comment by ThunderFrame** [comment]
Do we have an `@ignore` tag for not indenting a member/module/project?

**Comment by retailcoder** [comment]
@ThunderFrame nope. Indenting is triggered by user action anyway.

**Comment by ThunderFrame** [comment]
So if I have 100 modules, and I want to indent 99 of them but I don't want to indent modEvilCode, then what?

**Comment by retailcoder** [comment]
really?

**Comment by ThunderFrame** [comment]
If modEvilCode comes from a shared repo, and if I make changes to the indenting, then other teams (that use different indenting rules) complain about the changes.

**Comment by retailcoder** [comment]
Ok you win. But `@Ignore` is reserved for inspections. I propose `@NoIndenting` at module-level only. Procedure-level will interfere with other annotations, and encourage inconsistent indentation.

**Comment by ckuhn203** [comment]
Hmm... I don't know. Personally, I feel like indentation should be consistent across a *project*. If modEvilCode comes from a different repo, it should be in a separate project, right?

**Comment by ThunderFrame** [comment]
Common Repos are, erm, common. I might share classes between documents, between colleagues or between teams, and the repo might only exist for the swapping content, rather than being a project in its own right. IIRC, SmartIndenter can change line-continuations and comment positions, and I'm not convinced that all source controls can handle that.

@retailcoder  I agree, Module level seems granular enough.

How about `@NoIndent` as it's more verb-like than `@NoIndenting`

**Comment by ckuhn203** [comment]
Well, I suppose it's certainly a use case, even if it's not my preferred architecture.

**Comment by Hosch250** [comment]
I will implement the UI.  I'm not too sure how to go about importing the existing settings, that sounds like it will need admin access at the very least.

**Comment by Vogel612** [comment]
Might be interesting to move that "import existing settings" into a one-time script, that can be run separately from Rubberduck so we don't have to elevate the Duck for this

**Comment by ThunderFrame** [comment]
I doubt admin settings will be required. If SmartIndenter settings exist, at all, in the registry, then it seems likely that SmartIndenter must have had at least read rights to that key, and probably had write access too.
RubberDuck should be able to at least try to import the settings. Adding a script just makes installation more complicated than need be. If corporations want to install this Add-In, the software would typically go through a risk/vendor screening/approval process, and special install steps would not count in its favour.

**Comment by retailcoder** [comment]
Admin rights aren't required because the settings are saved under the HKCU hive.

**Comment by ThunderFrame** [comment]
Parts of HKCU are protected, IIRC, and group policy can lock it down further.

**Comment by retailcoder** [comment]
Ok... well we're going to be reading registry keys, so that's going to be wrapped in a `try..catch` block anyway.

**Comment by Hosch250** [comment]
User interface implemented.

**Comment by Hosch250** [comment]
Is this ready to be closed?

**Comment by retailcoder** [comment]
missing the preview box, but @comintern is working on a refactoring of the settings that will make it possible, so yeah.
