### ISSUE TITLE
Running all tests with more than one workbook open, sometimes crashes Excel

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#1071]
I can't get this to happen all of the time, so I'm not sure I've found the exact set of steps to reproduce, but it seems to occur when I have more than 1 workbook open. I think both workbooks have to have code, and I'm certain that I have security so that I can run Macros in both workbooks. The workbooks have different project names.

And yet, the COM exception on the Application.Run step is:

```
An unhandled exception of type 'System.Runtime.InteropServices.COMException' occurred in Rubberduck.VBEditor.dll

Additional information: Cannot run the macro 'VBAProject.TestModule1.TestCleanup'. The macro may not be available in this workbook or all macros may be disabled.
```

I've tried reverting to the standard Excel Application ctor, but it doesn't make any difference, so I'm fairly confident that it's not my code that is causing this.

**Comment by ThunderFrame** [comment]
OK, I've done a lot of testing of this (and have crashed Excel many times to do so)... I think I've found the causes of the problems...

- If I have a single workbook, and the workbook's macros are disabled, when I press Run All from Rubberduck menu, regardless of whether Test Explorer is showing, test hangs, can't be aborted/reset.

- If I have a single workbook, and the workbook's macros are disabled, when I press Run All from Test Explorer, then Excel crashes.

- If single open workbook has macros disabled AND it has a project reference (that doesn't open because macros are disabled) , then insert test module/method has no effect, Run All has no impact.

- If an open workbook with macros disabled AND it has a project reference (that is also open) , then insert test module/method works, Run from menu hangs, Run from Test Explorer crashes.

- If Book1 Macros Enabled and another book Macros Disabled, and test module/method only in Book1, then test hangs from run via menu, crashes Excel from run via Test Explorer

- Open Book1 and Book2, Make Book 1 active. Add tests only to Book1 Project, tests work.

- Open Book1 and Book2, Make Book 2 active. Add tests only to Book1 Project, tests hang from menu, crash from Test Explorer.

- Open Book1 and Book2, Make Book 2 active. Add tests only to Book2 Project, tests work.

- Open Book1 and Book2, Make Book 1 active. Add tests only to Book2 Project, tests hang from menu, crash from Test Explorer.

- Open Book1 and Book2, Make Book 1 active. Add tests to Book1 Project and Book2 Project, first test passes, then hangs from menu, crashes immediately (I suspect first test passes, but there is no visual feedback before crash) from Test Explorer.

- Open Book1 and Book2, Make Book 2 active. Add tests to Book1 Project and Book2 Project, test hangs from menu, crashes from Test Explorer.

It seems Application.Run *must* be run while a Project treeview node of the target project (that contains the target method) is selected, *unless* the selected project has a reference to the target reference. However, this is further complicated by the visibility of the host and the current activeworkbook....
When using Excel 2013, each workbook has its own window. In my testing, when using Application.Run from the immediate window, if a node of Project 1 is selected, then Application.Run is called for a method in Project1, and the method *is* called, but if the window for Book2/Project2 becomes active during the method execution (and this includes a msgbox from Project1 being displayed while Books2 is the activeworkbook), then the selected node in Project Explorer switches to Book2's project, so trying to re-run the same Application.Run statement from the immediate window, will now fail.

The behaviour of Application.Run is slightly different when called by Rubberduck, as it seems to ignore the current project node in Project Explorer, and instead default to the project of the current activeworkbook. 

It seems, at the very least, that to reliably use Application.Run, when there's more than one workbook open, that Rubberduck will need to either:
1 - Select a node of the target method's project in the treeview of the Project Explorer, or:
2 - Open/Activate a VBComponent of the target method's project, or better yet, the method's VBComponent.

But, if we're going so far as to open VBComponents, then it might be time to revisit the idea of placing the cursor/selection in the target method and using the Execute method of the "Run Sub" CommandBarControl. That way we gain testing under Outlook, and document-type projects under CorelDraw.

Then again, it seems that Application.Run *can* run methods in a locked/protected project. My tests showed that it can call private and public methods in both standard and private modules (which I didn't expect), so we could technically run tests on locked projects, but we'd have to come up with another means of annotation, *and* we'd need to rely on selecting the project node in Project explorer and using Application.Run

**Comment by ThunderFrame** [comment]
My last post in this thread was long, so you may have missed this:
> it seems that Application.Run can run methods in a locked/protected project. My tests showed that it can call private and public methods in both standard and private modules (which I didn't expect)...

**Comment by retailcoder** [comment]
Unit test discovery is going to be working off parser state / declarations and annotations (1.x worked off the VBIDE API); running code in protected projects is out of scope. Good to know though :-)

**Comment by retailcoder** [comment]
Do we have a way of knowing whether macros are enabled/disabled?

**Comment by ThunderFrame** [comment]
You can determine whether a project is in Design-mode by inspecting the state of the "Design Mode" button on the Run Toolbar, but that's not enough to know if macros are enabled when you exit design mode
You can exit design mode *and* determine whether macros are enabled by executing `Application.Run("Now()")`, but I can't tell if a project with disabled macros might cause a dialog box?

**Comment by retailcoder** [comment]
Fixed (tests are now discovered with the parser, so there can't be a locked/protected project with tests)
