### ISSUE TITLE
Clicking Add button inside Test Explorer toolbar, crashes host

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#1072]
This button used to work, IIRC,

It *should* pop up a menu, but it crashes instead.

The caption on the adjacent Run button is `#RubberduckUI.Run` so it seems like this explorer is a WIP.

There are multiple UI issues with this form. We need some @Hosch250 magic...

**Comment by Vogel612** [comment]
Sounds like a DI rewiring failure to me... do you have a Stacktrace? It could be a problem with a Command not being bound correctly and resulting in a `NullReferenceException`...

**Comment by Hosch250** [comment]
There are a few issues here.  The caption is the result of the new localization feature implemented by @autoboosh.  Sounds like the resx value may be missing, or something.  The button not working - that sounds very much like somebody hard-wired the caption name somewhere when determining what to do.  Now that the caption is messed up...  (Nothing for sure here, just a guess.)

**Comment by Hosch250** [comment]
Both I and @autoboosh checked this out, and can get no repro on it.

**Comment by ThunderFrame** [comment]
I can reproduce... But only under certain conditions.

Will commit a fix tonight.

**Comment by retailcoder** [comment]
> it seems like this explorer is a WIP

Indeed. We need to swap the treeview for a GroupingGrid :smile:

**Comment by Hosch250** [comment]
I suppose I can handle this after I finish the Settings if no one else wants.  Do you want to to get some WPF experience, @ckuhn203?

**Comment by ThunderFrame** [comment]
I think I've made this reproducible. Open 2 projects, 1 from an untrusted location (and don't enable Macros), and 1 project with Macros enabled.
If you have any item in Untrusted.xlsm selected/active, then Application.Run does not work, even if explicitly referencing a method in Trusted.xlsm.
That means that Rubberduck's Application.Run methods will fail, unless the active project has Macros enabled.
It also means that any test methods that RubberDuck finds in a macro-disabled project, cannot be run, regardless of whether the active project is macro enabled.

**Comment by ThunderFrame** [comment]
There's potentially a side issue here. If you have 2 or more projects that share project name, test module name and test method names, then Application.Run potentially *can't know* which project you mean, so I think we might have to select the project or component, *before* we try to use Application. Run

**Comment by retailcoder** [comment]
Hold on a second.

This:

    try
    {
        AssertHandler.OnAssertCompleted += HandleAssertCompleted;
        duration = _hostApp.TimedMethodCall(_qualifiedMemberName);
        AssertHandler.OnAssertCompleted -= HandleAssertCompleted;
                
        result = EvaluateResults();
    }
    catch(Exception exception)
    {
        result = TestResult.Inconclusive("Test raised an error. " + exception.Message);
    }

Is blowing up?

**Comment by ThunderFrame** [comment]
I think that means we need properties to determine the Macro-Enabled status and design mode of a project. I think we also need a method to select a project.

**Comment by retailcoder** [comment]
hmm..

This line:

    AssertHandler.OnAssertCompleted -= HandleAssertCompleted;

May never run, if an exception is thrown. The handler should be removed in a `finally` block. But to bring everything down with it? in a `try` block that `catch`es *every throwable exception type*? ...something else is going on.

**Comment by ThunderFrame** [comment]
@retailcoder I'm not sure it's that block that fails. Will check tonight.

**Comment by ThunderFrame** [comment]
Last night, I did step over the COM exceptions coming from Application. Run, and oddly, *sometimes* test Explorer said my tests had passed.

**Comment by retailcoder** [comment]
If no assertions are made, it makes complete sense for the test to just pass IMO. Step one in TDD is to write a failing test, and you can't write one without making an `Assert` call. That's completely by design.

That code block is in [`TestResult TestMethod.Run()`](https://github.com/rubberduck-vba/Rubberduck/blob/next/Rubberduck.UnitTesting/TestMethod.cs#L23-L43), it's where all test methods run - the only place `TimedMethodCall` is ever called, is in that specific code block. If an exception is trappable in `Application.Run`, it bubbles up to that `catch` block.

**Comment by ThunderFrame** [comment]
hmm - it seems everything from my 3rd comment in this thread was meant to be against #1071 (must have been editing on my phone), And for #1071 , I have already done further testing on and added comments to it.

This issue is still open. So my comments from here on *do* relate to this issue.

**Comment by ThunderFrame** [comment]
Test Explorer Add button in the Test Explorer does crash, if there aren't any projects open (i.e. Rubberduck can't determine the host).
PR inbound...

**Comment by ThunderFrame** [comment]
Fixed by #1080
