### ISSUE TITLE
Adding a Test Module then closing host document leaves ghost project

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#1078]
Adding a test module (from Test Explorer Add button/menu) adds a test module, but if you then immediately close the host document (I don't think saving changes makes a difference), VBA Project Explorer shows a ghost project.

I don't think the visibility of the Test Explorer matters (I left it open).
I'm unsure if the problem only occurs when adding a test module to a new/unsaved workbook, or any workbook.

**Comment by retailcoder** [comment]
Does it really matter than a test module is added? I don't think we're handling a VBA project being closed at all yet.

**Comment by ThunderFrame** [comment]
It doesn't occur if I *don't* add a test module, but yes, it could be other/certain/all Rubberduck actions.

**Comment by ThunderFrame** [comment]
I suspect this is related to #1085

**Comment by ThunderFrame** [comment]
Closing a story is good. Closing a project is bad.

**Comment by retailcoder** [comment]
fixed
