### ISSUE TITLE
Inspections Severity Location

### ISSUE THREAD

**Issue by Hosch250** [rubberduck-vba/Rubberduck#1079]
The inspections severity needs to become a public field as well as being assigned to the base in each and every inspection.  It should look something like this:

    public CodeInspectionSeverity Severity { get { CodeInspectionSeverity.Warning; } }
    public FunctionReturnValueNotUsedInspection(RubberduckParserState state)
        : base(state, Severity)
    {
    }

This is very easy, but also very monotonous.  You'll need to update the `InspectionBase` ctor:

    protected InspectionBase(RubberduckParserState state, CodeInspectionSeverity severity)
    {
        State = state;
        Severity = severity;
    }

**Comment by retailcoder** [comment]
This can't be right: we need to be able to `set` this value; I don't see why it couldn't just be an auto-property:

    public CodeInspectionSeverity Severity { get; set; }
    
The constructor would just pass the hard-coded default down to the base constructor:

    public FunctionReturnValueNotUsedInspection(RubberduckParserState state)
        : base(state, Severity.Warning)
    {
    }

Instead of assigning `_severity` in the same class. The idea is basically to have 2 severity properties: the default, and the current.

**Comment by Hosch250** [comment]
There is no `_severity` field in the same class.  The current implementation is:

    public WriteOnlyPropertyInspection(RubberduckParserState state)
        : base(state)
    {
        Severity = CodeInspectionSeverity.Warning;
    }

**Comment by retailcoder** [comment]
Right, an auto-property.

The base class could have this:

    public CodeInspectionSeverity DefaultSeverity { get; private set; }
