### ISSUE TITLE
Implement Settings Window in XAML

### ISSUE THREAD

**Issue by Hosch250** [rubberduck-vba/Rubberduck#1081]
We were originally going to implement the About window in XAML, but I got confused and implemented the Settings window in XAML.  Since I'm almost done at this point, we might as well keep it, so here is an issue for it.

**Comment by retailcoder** [comment]
lol, oops!

**Comment by Hosch250** [comment]
Merged in https://github.com/rubberduck-vba/Rubberduck/pull/1087/
