### ISSUE TITLE
Tooltips on Parsing toolbar need localization

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#1083]
The tooltips are currently hard-coded English string literals

**Comment by Vogel612** [comment]
Assuming that the code-side is fixed, #1043 will take care of the translation itself.

**Comment by Hosch250** [comment]
@Vogel612 The trouble is the code-side is not fixed.

**Comment by Hosch250** [comment]
What's the status on this?

**Comment by Hosch250** [comment]
Obsolete.
