### ISSUE TITLE
Closing a project causes Code Explorer to stop refreshing projects

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#1085]
Steps to reproduce,

Have 2 projects open (give the projects different names, to identify them)
Close 1 project
Code Explorer now caches the original 2 projects, and adding new projects do not register in the Code Explorer.

I wonder whether the declarations are being cached in some way. Maybe it has to do with the name of the project being closed, and whether it sorts before or after the projects that are still open.

**Comment by Hosch250** [comment]
Closing as obsolete.
