### ISSUE TITLE
Removing/Renaming a module is not reflected in a refreshed Code Explorer

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#1089]
Code Explorer persists the module name, and the child members.
Similarly to #1078 and #1085, Rubberduck doesn't seem to like Projects or Components being removed.

A removed module includes a worksheet being removed from the Excel workbook, or an Access Report/Form being renamed/removed from a database.

A renamed module, is treated as a new module, and the old name persists alongside the new name.

A renamed project and renamed module, results in a "folder" with the old project names, which contains a module with the old module name, and a "folder" with the new project name, which contains the modules that haven't been renamed.

Rubberduck gets confused by modules that have been removed, but where another module with the same name is subsequently added.

Renaming a folder does seem to work,.but if a module is "in" a folder, and the module is renamed, and then the `'@Folder` is renamed, then Code Explorer will persist the old module name under the old folder name and the newly named module under the newly named folder.

**Comment by Hosch250** [comment]
Obsolete.
