### ISSUE TITLE
Create views for todo markers

### ISSUE THREAD

**Issue by Hosch250** [rubberduck-vba/Rubberduck#1098]
Check R# for ideas.  One good one is sorting by project layout, basically showing the markers for each file in the namespace tree.

**Comment by retailcoder** [comment]
I added `GroupDescriptions` for `ItemsByMarker` and `ItemsByLocation`, does that cover it?

I'd like to add `ItemsByFolder` eventually (to all GroupingGrid views), but doing that for 2.0 literally amounts to *feature creep*. Let's just make an issue to extract the folder logic out of the *code explorer* at one point, and add that to 2.1 or something.

**Comment by Hosch250** [comment]
Sure.
