### ISSUE TITLE
Unit Testing - Support All Major Office Applications

### ISSUE THREAD

**Issue by ckuhn203** [rubberduck-vba/Rubberduck#112]
- [x] Excel
- [x] Access
- [x] Word
- [x] Power Point
- [ ] Project

Note: Outlook, Visio and Publisher `Application` classes don't expose a `Run` method, which is required for RD unit testing to work.

Instructions for adding support.

1. Determine the correct ProgId to be passed to `Marshal.GetActiveObject`.
2. Implement a new child class of [IHostApplication] (https://github.com/retailcoder/Rubberduck/blob/master/RetailCoder.VBE/IHostApplication.cs).  The name of the application needs to be passed to the base constructor like so.

        public ExcelApp() : base("Excel") { }

  You must also determine the proper way to call to call VBA's `Application.Run()` method and over ride `GenerateFullyQualifiedName` accordingly.

3. Determine the name of the reference and add it to [the VBE HostApplication extension method](https://github.com/retailcoder/Rubberduck/blob/master/RetailCoder.VBE/Extensions/VbeExtensions.cs#L51-L68)

**Comment by retailcoder** [comment]
[This SO question](http://stackoverflow.com/q/31954364/1188513) might help. I'm willing to award a +500 bounty to whoever has an answer that translates into RD 2.0 supporting unit tests in Outlook.

**Comment by retailcoder** [comment]
Outlook will not work. Removing from the check-list.

**Comment by retailcoder** [comment]
Do we have the MSProject PIAs? Otherwise it looks like we're done here :smile:

**Comment by ckuhn203** [comment]
Even if we did, none of us have a copy to test. Closing it. =)

**Comment by Hosch250** [comment]
I can get a copy of Project 2010/2013/2016 from DreamSpark for testing purposes.  We need a developer with 2007 to install these PIA's and reference the MSProject dll: https://www.microsoft.com/en-us/download/details.aspx?id=18346.

I would do it myself, but I do not have a product key for 2007, and MS took the trial downloads down.
