### ISSUE TITLE
Rubberduck requires a way of selecting a vbProject

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#1122]
VBIDE provides a method for activating a vbComponent, which necessarily activates the vbProject, but if a project is protected, then a vbComponent can't be selected, and the vbProject can't be activated.
Selecting a project can, it seems, only reliably be achieved by selecting the node in the Project Explorer Treeview. Once a project is selected, it *doesn't* require any code pane to be opened, and it updates the VBIDE to reflect properties of the project (eg. the Object Browser shows the members of the project and its references.)
The solution will need to *find* the Project Explorer window, and send Win32 messages to find the Project node, and then send a message to select it.

**Comment by retailcoder** [comment]
I'm pretty sure there's a VBIDE API method for this.

**Comment by ThunderFrame** [comment]
hmm, I should have tried harder....

```vb
  Set Application.VBE.ActiveVBProject = Application.VBE.VBProjects("proj")
```

**Comment by retailcoder** [comment]
So, the code explorer only needs to assign the VBProject object reference when a project is selected. I'm reopening the issue until it's implemented in the 2.0 explorer though.

**Comment by ThunderFrame** [comment]
as long as it's open, I should add that there's no way of selecting the component-type folders (eg. Microsoft Excel Objects, Modules, Class Modules)in Project Explorer, and as such, there's no way of collapsing/expanding the folders. IIRC, MZ Tools has that functionality. So it may still be necessary to walk the treeview.

**Comment by retailcoder** [comment]
TBH I don't really care about the Project Explorer's [lack of] functionality. When you have your components nicely organized in custom folders in Rubberduck's Code Explorer, I think you're not even going to even have the Project Explorer opened.

**Comment by ThunderFrame** [comment]
I agree, but node selections in the Code Explorer window should update the context and contents of the Properties Window, just like selections in the Project Explorer window do. I suspect that will *require* changing the node selection in the Project Explorer.

**Comment by retailcoder** [comment]
Not really. The Project Explorer merely responds to the `VBE.SelectingVBComponent` and `VBE.ActiveVBProject` changing; the Code Explorer simply needs to set these object references for the Project Explorer and Properties Window to understand what's going on.

**Comment by ThunderFrame** [comment]
But ideally, Project Explorer and Code Explorer would stay in sync. If a user had both visible, and used them interchangeably, then a "folder" selection in Project Explorer would update the Properties window content, and leave Code Explorer out of sync.
Code Explorer doesn't have document-type folders, so I'm unsure exactly what staying in sync might mean, but leaving the Code Explorer's selected node as it is, *after* a change of selection in the Project Explorer window, is not ideal.

**Comment by retailcoder** [comment]
I agree, but the VBIDE API doesn't provide a hook on selection change, so there's no "clean" way for Rubberduck to know the active project has changed. The best we can do is to ensure the Code Explorer has the module of the active code pane selected when the key hook picks up a key press in a code pane.

**Comment by ThunderFrame** [comment]
The Active code pane doesn't necessarily relate to the active project.
But, I'm 99% certain we can hook it using Win32 messages.
