### ISSUE TITLE
Investigate the possibility of switching from Microsoft's PIAs to NetOffice

### ISSUE THREAD

**Issue by ckuhn203** [rubberduck-vba/Rubberduck#113]
[NetOffice](http://netoffice.codeplex.com/) offers version independent .NET Wrapper Assemblies for accessing the following MS Office applications:

- Office
- Excel
- Word
- Outlook
- PowerPoint
- Access
- Project
- Visio

Could be a nice alternative. Worth looking into.

**Comment by ckuhn203** [comment]
I'm going to reopen this. I think it will be much simpler to make #607 happen if we're not using the PIAs.

**Comment by ckuhn203** [comment]
Also, I'm tired of fixing broken references everytime I pull.... how about you guys?

**Comment by retailcoder** [comment]
Point. If it works, why not?

**Comment by ckuhn203** [comment]
I think this is a beautiful idea, but there are two pretty big show stoppers in places where they broke with Microsoft's API. [There's an issue open on their project site](https://netoffice.codeplex.com/workitem/20295), but I'll summarize here.

CodeModule.Find and Windows.CreateToolWindow take in `ref` params. Net office failed to do that. Rossco actually wrote some VB code to get around the CreateToolWindow issue. I translated it to C#, but I don't understand it well enough to create one for the Find method. If someone can write that code, I wouldn't mind switching. Otherwise, I'll find another way to make the build server happen.

There's also an issue with Controls.Add. Net Office doesn't take in any optional params like the Office API does. We don't specify any Ids for any of our menu items, so we would have to specify Ids for all of our buttons, menus, etc.

**Comment by ckuhn203** [comment]
The extension method for posterity.

    using System;
    using System.Reflection;
    using NetOffice;
    using NetOffice.VBIDEApi;

    namespace Rubberduck.UI
    {
        public static class WindowExtensions
        {
            public static Window CreateToolWindow(this Windows windows, AddIn AddInInst, string ProgId, string Caption, string GuidPosition, ref Object DocObj)
            {
                ParameterModifier[] modifiers = Invoker.CreateParamModifiers(false, false, false, false, true);
                Object[] paramsArray = Invoker.ValidateParamsArray(AddInInst, ProgId, Caption, GuidPosition,
                    DocObj);

                var invoker = Invoker.Default;
                Object result = invoker.MethodReturn(windows, "CreateToolWindow", paramsArray, modifiers);

                DocObj = paramsArray[4];

                var core = new Core();
                var window = core.CreateObjectFromComProxy(windows, result, Window.LateBindingApiWrapperType) as Window;
                return window;
            }
        }
    }

**Comment by rossknudsen** [comment]
Update:
I think I have managed to find a fix for the Windows.CreateToolWindow and CodeModule.Find methods.  I say 'I think' because there are other issues to work through that prevent me from running it successfully.  However it doesn't crash when creating ToolWindows any more.

```CSharp
public static class WindowExtensions
{
	public static Window CreateToolWindowFixed(this Windows windows, AddIn addInInst, string progId, string caption, string guidPosition, ref object docObj)
	{
		ParameterModifier[] modifiers = Invoker.CreateParamModifiers(false, false, false, false, true);
		object[] paramsArray = Invoker.ValidateParamsArray(addInInst, progId, caption, guidPosition, new DispatchWrapper(docObj));

		object returnItem = windows.Invoker.MethodReturn(windows, "CreateToolWindow", paramsArray, modifiers);
		docObj = paramsArray[4];
		var newObject = windows.Factory.CreateKnownObjectFromComProxy(windows, returnItem, Window.LateBindingApiWrapperType) as Window;
		return newObject;
	}
}

internal static class CodeModuleExtensions
{
	internal static bool FindFixed(this CodeModule module, string target, ref int startLine, ref int startColumn, ref int endLine, ref int endColumn)
	{
		var modifiers = Invoker.CreateParamModifiers(false, true, true, true, true);
		object[] paramsArray = Invoker.ValidateParamsArray(target, startLine, startColumn, endLine, endColumn);
		object returnItem = module.Invoker.MethodReturn(module, "Find", paramsArray, modifiers);

		// update values for return.  
		// TODO We may not be able to do the cast as shown.
		startLine = (int)paramsArray[1];
		startColumn = (int)paramsArray[2];
		endLine = (int)paramsArray[3];
		endColumn = (int)paramsArray[4];

		return Convert.ToBoolean(returnItem);
	}
}
```
