### ISSUE TITLE
Clipboard Copy requires multiple formats

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#1133]
The current Copy methods (Code Inspections, Test Explorer, etc), only put text on the clipboard.

I've got an implementation, nearly complete, that puts at least 3 formats on the clipboard:
 - Unicode Text
 - CSV
 - HTML

Those extra formats give greater flexibility when copying data, but also act as a pseudo-export feature.

The HTML format pastes into Excel, and looks like this:

![htmltable](https://cloud.githubusercontent.com/assets/16574009/13204829/65ca203a-d92d-11e5-9dfc-18dd804f35c4.png)

I've still got a bit of work to do, but any ideas for other formats?

**Comment by retailcoder** [comment]
Hey, I like this! :+1:

**Comment by ThunderFrame** [comment]
I'm using inline styles on the HTML, so the pastes *should* work, even when pasting into clients/environments that don't recognise style blocks, like Gmail.

**Comment by Hosch250** [comment]
Perhaps you should allow an XML copy?

**Comment by ThunderFrame** [comment]
@Hosch250 The HTML will be largely XHTML compliant (it will necessarily lack an `<?xml >` tag), but yes, I plan to add a `XML Spreadsheet` format.

**Comment by retailcoder** [comment]
@ThunderFrame did I merge a PR for this?

**Comment by ThunderFrame** [comment]
Yes you did, but I'm nearly done on a revision that refactor the code and adds a format.

Then, I'll hook up the other windows that have a copy button. Iirc, Find all References doesn't have a copy button, but it might be useful to add.
