### ISSUE TITLE
Remember expanded/collapsed state of TreeView nodes and GroupingGrid groups

### ISSUE THREAD

**Issue by Hosch250** [rubberduck-vba/Rubberduck#1134]
The code inspections list does not sort the inspections, or even the groups, the same way every time.  Also, every group opens each time the view is refreshed, instead of the closed groups staying closed.  the same applies to the Code Explorer, where groups should remember their closed/opened state through refreshes.

**Comment by retailcoder** [comment]
Are you sure about the code inspections? I haven't had that problem since sort descriptions were added to the CVS's in the xaml..

**Comment by Hosch250** [comment]
I'm having it right now.

**Comment by retailcoder** [comment]
The `SortDescriptions` sorted by inspection type and then by inspection name; adding qualified module name and start line / start column fixes the sorting issue.

**Comment by Hosch250** [comment]
Code Explorer remembers which nodes were open, and the Code Inspections sorts correctly now.  Only thing left is leaving Grouping Grid group states the way they were.  Is that even worth it, or should we close this now?
