### ISSUE TITLE
Rubberduck 2.0 launch requires PR campaign

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#1136]
With 2.0 just <s>days</s> <s>weeks</s> months away, we need to think about the publicity at the time of launch.
- Press Release
- Tweets/hashtag

**Comment by retailcoder** [comment]
Really?

**Comment by retailcoder** [comment]
Okay I have ideas. Tons actually. One would be a "My duck [does something]. #SmartDucky" campaign. Something along the lines of...

> My duck can extract a method out of any code block. #SmartDucky #Refactor #VBA

> [animated .gif showing the *Extract Method* refactoring extracting a method out of a code block]



> My duck tells me if my #VBA code still works as intended after I changed it. #SmartDucky #UnitTest

> [animated .gif showing the *Test Explorer* running unit tests]



> My duck takes my #VBA code to #GitHub. #SmartDucky #SourceControl

> [animated .gif showing the *Source Control* panel in action



> My duck can review my #VBA. #SmartDucky

> [animated .gif showing the *inspection results* toolwindow and a few quick-fixes being applied]



> My duck fixes my bad indentation. #SmartDucky

> [animated .gif showing the *Smart Indenter* features at play]



> My duck sees everything, and gets me there. #SmartDucky #Navigate #VBA

> [animated .gif showing the *find symbol* feature]
> [animated .gif showing the *find all references* feature]
> [animated .gif showing the *find all implementations* feature]



> My duck can browse a 200-file #VBA project eyes closed. #SmartDucky

> [animated .gif showing nested custom folders in the *Code Explorer*]

...that kind of thing.

**Comment by retailcoder** [comment]
Anyway. Prepare for blog posts, tweets, <s>flyers, and TV spots</s> ...of course 2.0 will come out with a bang! :smiley:

Clearing the milestone on this one, since it's bringing down the %completion of v2.0 milestone while actually being about the release itself.

**Comment by Phrancis** [comment]
Have you guys thought of trying to get exposure/ads on VBA/Office-related forums? (like MrExcel, ExcelForum, etc.)

**Comment by retailcoder** [comment]
@Phrancis When the time is right, I'll contact them on Twitter. I'm following quite a bunch of Excel/VBA/Office-related forums on Twitter.

**Comment by PeterMTaylor** [comment]
https://excel.tv/excel-resources/ is another place to promote RD in the VBA section  👍🏻

**Comment by ThunderFrame** [comment]
how green are we?

**Comment by PeterMTaylor** [comment]
Does this also cover LinkedIn forums as there is a vba group there.

**Comment by Vogel612** [comment]
2.0 has been released ... quite a while ago.
