### ISSUE TITLE
Add-in not loading while trying to debug next branch

### ISSUE THREAD

**Issue by manfredk** [rubberduck-vba/Rubberduck#1138]
Hi,

I've followed the instructions on the installing page, built successfully the debug and debugaccess builds, ran regasm on ...debug\rubberduck.dll and registered the key with the .reg file, all as administrator. When starting up I've received the can not load add-in message. Same with the debugAccess build. I've cleaned my system from a previous 1.4.3 install and scratch my head on what to do to solve this issue. Any ideas?

**Comment by retailcoder** [comment]
hmm.. `debugAccess` seems to be a relic of some older version - we need to clean that up.. I'm using the `Debug` config.

Initial setup is a bit of a PITA indeed. The *Installing* page is meant for users, if you want to build the [next] version you'll find the instructions [on the *Constributing* page](https://github.com/rubberduck-vba/Rubberduck/wiki/Contributing).

Start fresh, make sure 1.4.3 (release build) is uninstalled. We use Visual Studio 2013 Community Edition (always running as administrator) and build with C# 4.5.

Once you have a build, register it with regasm.exe (only once!), and then go and manually create the registry keys as per the bitness of your Office install:

![RegEdit](https://camo.githubusercontent.com/67cd1f7c2aa2466762dd698c7a1824ed488f2f1b/687474703a2f2f692e737461636b2e696d6775722e636f6d2f7a7a3853782e706e67)

I'm not sure what's in the .reg file (I always create that key manually), but it might have been what blew it. Let us know how it goes :smiley:

**Comment by Vogel612** [comment]
no response since 9 months. closing with the ice-box
