### ISSUE TITLE
NullReference Exception within VariableTypeNotDeclaredInspectionResult.cs

### ISSUE THREAD

**Issue by Pitterling** [rubberduck-vba/Rubberduck#1150]
Hi,

I just tried the latest commit with the attached workbook and run into a NullReferenceException
`System.NullReferenceException was unhandled by user code
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=Rubberduck
  StackTrace:
       at Rubberduck.Inspections.VariableTypeNotDeclaredInspectionResult.get_Description() in C:\Code\Tools\Rubberduck\RetailCoder.VBE\Inspections\VariableTypeNotDeclaredInspectionResult.cs:line 26
  InnerException: 

hmmm ... attachement uploading not possible, please take the workbook from here:
#1145 InvalidOperationException in resolver

Thx,
P.

**Comment by retailcoder** [comment]
Good catch, fixed.
