### ISSUE TITLE
Get parsing under control

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#1152]
Launching the current build produces this debug output (from an Excel host):

> Resolving 'Sheet3'...
Resolving 'Sheet3'...
Resolving 'Sheet3'...
'Sheet3' is Ready.
'Sheet3' is Ready.
'Sheet3' is Ready.
Resolving 'ThisWorkbook'...
Resolving 'ThisWorkbook'...
Resolving 'ThisWorkbook'...
'ThisWorkbook' is Ready.
'ThisWorkbook' is Ready.
'ThisWorkbook' is Ready.
Resolving 'Sheet2'...
Resolving 'Sheet2'...
Resolving 'Sheet2'...
'Sheet2' is Ready.
'Sheet2' is Ready.
'Sheet2' is Ready.
Resolving 'Sheet1'...
Resolving 'ThisWorkbook'...
'Sheet1' is Ready.
'ThisWorkbook' is Ready.
Resolving 'Sheet2'...
Resolving 'Sheet3'...
Resolving 'ThisWorkbook'...
Resolving 'Sheet1'...
'Sheet2' is Ready.
'ThisWorkbook' is Ready.
'Sheet3' is Ready.
'Sheet1' is Ready.

That's 4 times more work than what's actually needed. With an empty workbook everything happens in about 1 second, but when a medium/large project is loaded, this extra work costs a lot, and definitely contributes to *high CPU usage* (see #1033).

Let's get parsing under control.

**Comment by ThunderFrame** [comment]
Interesting that there are **4** components and they're each resolving **4** times. What happens when there are 10 components?

**Comment by ThunderFrame** [comment]
Also, unsure if related, but I opened Word as a host last night, so 2 projects are loaded (Normal.dotn and Document1), but the parser didn't run, and I have to manually refresh.

**Comment by retailcoder** [comment]
@ThunderFrame currently the only things triggering a parse are the `VBProjects` and `VBComponents` event handlers, so it makes complete sense that we get a parse-per-component - I don't get a reliable startup parse either, but I just added debug output to these handlers, and the output is pretty darn interesting:

> Project 'Project1' was added.
Project 'VBAProject' was renamed. <<< really??!
Component 'ThisWorkbook' was added.
Component 'Sheet1' was added.
Component 'Sheet2' was added.
Component 'Sheet3' was added.
Component 'Sheet1' was selected.

**Comment by retailcoder** [comment]
Ok, so I didn't do much here, and it appears to have fixed it - I made the events `async` and `await`ed the parse tasks; now I get this output:

> Project 'Project1' was added.
Project 'VBAProject' was renamed.
Component 'ThisWorkbook' was added.
Component 'Sheet1' was added.
Component 'Sheet2' was added.
Component 'Sheet3' was added.
Component 'Sheet1' was selected.
A first chance exception of type 'System.OperationCanceledException' occurred in mscorlib.dll
A first chance exception of type 'System.OperationCanceledException' occurred in mscorlib.dll
A first chance exception of type 'System.OperationCanceledException' occurred in mscorlib.dll
A first chance exception of type 'System.OperationCanceledException' occurred in mscorlib.dll
A first chance exception of type 'System.OperationCanceledException' occurred in mscorlib.dll
A first chance exception of type 'System.OperationCanceledException' occurred in mscorlib.dll
Resolving 'Sheet1'...
Resolving 'Sheet2'...
Resolving 'Sheet3'...
Resolving 'ThisWorkbook'...
'ThisWorkbook' is Ready.
'Sheet1' is Ready.
'Sheet2' is Ready.
'Sheet3' is Ready.

All tests still pass, and I consistently get this output every time. Now if I close the blank workbook first, and open a given workbook, *and then* bring up the VBE - then I consistently need to manually trigger the parse.

**Comment by retailcoder** [comment]
Manually triggered parse (here with @Pitterling's file) seems to work ok now... but the state label says "Parsed" or "Pending" while, looking at the debug output, clearly it should be saying "Resolving".

Resolving takes forever, it's annoying - even if the UI thread isn't blocked.

Actually, *because* the UI thread isn't blocked, the user is able to ruin the parse results while identifier resolution is running, by simply starting to type something in any code pane.

**Comment by retailcoder** [comment]
After what felt like more than 10 minutes, I got this output out of a project with 23 components:

> Resolving 'fnCheckPri'...
Resolving 'vbVBAAllPri'...
Resolving 'fnConstPri'...
Resolving 'vbVarTypeNamePri'...
Resolving 'vbXlPivotLinePri'...
Resolving 'vbFnPivotItemPri'...
Resolving 'ThisWorkbook'...
Resolving 'vbXlPivotAxisPri'...
Resolving 'vbFnPivotFieldPri'...
Resolving 'vbFnPivotTablePri'...
Resolving 'fnTypePri'...
Resolving 'fnRegEx'...
Resolving 'fnToolsPri'...
Resolving 'vbFnCollectionPri'...
Resolving 'vbXlPivotTablePri'...
Resolving 'vbXlPivotItemPri'...
Resolving 'fnErrorPri'...
Resolving 'vbXlPivotFieldPri'...
Resolving 'vbXlRangePri'...
Resolving 'Sheet1'...
Resolving 'fnInfoErrMsgPri'...
Resolving 'fnEnumPri'...
Resolving 'fnPivotFieldStatFn_ParPri'...
'ThisWorkbook' is Ready.
'Sheet1' is Ready.
'fnEnumPri' is Ready.
'fnConstPri' is Ready.
'vbVBAAllPri' is Ready.
'vbXlPivotAxisPri' is Ready.
'fnCheckPri' is Ready.
'fnTypePri' is Ready.
'fnInfoErrMsgPri' is Ready.
'vbFnCollectionPri' is Ready.
'vbXlRangePri' is Ready.
'vbXlPivotLinePri' is Ready.
'vbVarTypeNamePri' is Ready.
'vbXlPivotFieldPri' is Ready.
'vbFnPivotTablePri' is Ready.
'vbXlPivotItemPri' is Ready.
'vbXlPivotTablePri' is Ready.
'fnPivotFieldStatFn_ParPri' is Ready.
'fnRegEx' is Ready.
'fnErrorPri' is Ready.

Resolver takes waaaaaay too long to complete, it's painful.

**Comment by retailcoder** [comment]
Ok well, seems to be under control now. Closing.
