### ISSUE TITLE
Pre-/post-BuildEvent causes an error in Visual Studio 2012

### ISSUE THREAD

**Issue by sshikov** [rubberduck-vba/Rubberduck#1156]
Error	2	Source parameter is used to identify custom applications/scripts only (not installed applications).	C:\workspace\oss\Rubberduck\RetailCoder.VBE\EXEC	Rubberduck

Error	3	The command "eventcreate /ID 1 /L APPLICATION /T INFORMATION  /SO RubberDuck.VBE /D "Deploying Rubberduck from Visual Studio Build"" exited with code 1.

**Comment by retailcoder** [comment]
Are you running VS as admin? Also, we're using VS2013, not sure if it affects anything (VS2012 can target .net 4.5 right?)...

These events aren't really needed, feel free to remove them if they're causing issues - they're creating entries in the event log; we've got NLog set up to be able to log there, but we're not logging anything yet.
