### ISSUE TITLE
Code Inspector - Implicit reference to ActiveSheet?

### ISSUE THREAD

**Issue by Pitterling** [rubberduck-vba/Rubberduck#1157]
Hi,

**Rows** within line `If rngDevice.Rows.Count = 1 Then` is flagged as Implicit reference to ActiveSheet?! I guess this is not correct ;)

```
Option Explicit

Public Function showMapping() As Boolean
 
 Dim lwsSource As Excel.Worksheet
 Dim rngDevice As Excel.Range
 
 Dim ParentDevices() As Variant

    Set lwsSource = Excel.Worksheets("TOPOvw")
    lwsSource.Activate  'avoids COM error
    
    Dim lstTop As Excel.ListObject
    Set lstTop = lwsSource.ListObjects("tblTOPOvw")
    
    Set rngDevice = lstTop.ListColumns("Device").DataBodyRange
    'rngDevice.Select
    
    'special handling if only 1 row in interval
    If rngDevice.Rows.Count = 1 Then
       ReDim ParentDevices(1 To 1, 1 To 1)
       ParentDevices(1, 1) = rngDevice.Value2
    Else
       ParentDevices() = rngDevice
    End If
 
 showMapping = True
End Function

```

Thx, Peter

**Comment by retailcoder** [comment]
Thanks for reporting this! I need to write some thorough tests for that inspection (and its big brother, "implicit reference to `ActiveWorkbook`" too) - better fix it before than after release :smiley:

**Comment by retailcoder** [comment]
Interesting...

            var issues = Declarations.Where(item => item.IsBuiltIn 
                && item.ParentScope == "Excel.Global"
                && Targets.Contains(item.IdentifierName) // "Cells", "Range", "Columns", "Rows"
                && item.References.Any())
                .SelectMany(declaration => declaration.References);

The only declarations under the `Excel.Global` scope are under the `Excel` module name ([here](https://github.com/rubberduck-vba/Rubberduck/blob/next/Rubberduck.Parsing/Symbols/ExcelObjectModel.cs#L157)) - we should also be tripping the inspection under the `Excel.Application` scope, however this code:

    If rngDevice.Rows.Count = 1 Then

Should be resolving `Rows` to the [Excel.Range](https://github.com/rubberduck-vba/Rubberduck/blob/next/Rubberduck.Parsing/Symbols/ExcelObjectModel.cs#L135) scope, given it's a member call on `rngDevice` which is known to be declared as a `Range` object.

Two bugs here - the inspection is missing the `Excel.Application` scope, and the resolver is not correctly resolving the member call.

**Comment by retailcoder** [comment]
Ok, I've fixed it the best I could.

There's an edge case I can't work around though:

    Sub Foo()
        Dim FooBarBaz
        FooBarBaz.Range("A1").Select
    End Sub

This code will cause a false positive, because `FooBarBaz` doesn't resolve to a type that's known to have a `Range` member, which causes the `Range` call to erroneously resolve to `Excel.Global.Range`. I've amended the inspection's meta accordingly:

> Implicit references to the active sheet make the code frail and harder to debug. Consider making these references explicit when they're intended, and prefer working off object references. **Ignore if the member call is referring to a type Rubberduck can't resolve.**

**Comment by Pitterling** [comment]
Thanks a lot.

**Comment by Pitterling** [comment]
Seems to cause new issues .. I open a new one.
