### ISSUE TITLE
Parser Errors : Function$, Open, Get

### ISSUE THREAD

**Issue by thetopic** [rubberduck-vba/Rubberduck#1165]
Source code : [https://msdn.microsoft.com/en-us/library/aa243377(v=vs.60).aspx](https://msdn.microsoft.com/en-us/library/aa243377(v=vs.60).aspx)

If you run this code 

```vba
Type Record   ' Define user-defined type.
   ID As Integer
   Name As String * 20
End Type

Private Function test()
    Dim MyRecord As Record, Position   ' Declare variables.
    ' Open sample file for random access.
    Open "TESTFILE" For Random As #1 Len = Len(MyRecord) 
    ' Read the sample file using the Get statement.
    Position = 3   ' Define record number.
    Get #1, Position, MyRecord   ' Read third record.
    Close #1   ' Close file.

End Function
```

Parser Error : extraneous input '(' expecting {'.','!',ACCESS etc. 
Code : _Len = Len**(**MyRecord)_

***

Source code : [http://faq.vb.free.fr/index.php?question=165](http://faq.vb.free.fr/index.php?question=165)

```vba
Private Function ReadFileToBuffer(ByVal szFileName As String, _
                                 ByRef errCode As Integer, _
                                 ByRef errString As String) As String
    Dim f As Integer
    Dim Buffer As String

    ' trappe les erreurs
    On Error GoTo ReadFileToBuffer_ERR

    ' Ouverture du fichier en 'Binary'
    f = FreeFile
    Open szFileName For Binary As #f
        ' préallocation d'un buffer à la taille du fichier
        Buffer = Space$(LOF(f))
        ' lecture complète du fichier
        Get #f, , Buffer
    Close #f
    ReadFileToBuffer = Buffer
ReadFileToBuffer_END:
    Exit Function
    
ReadFileToBuffer_ERR:
    ' Gestion d'erreur
    ReadFileToBuffer = ""
    errCode = Err.Number
    errString = Err.Description
    Resume ReadFileToBuffer_END
End Function
```

Parser Error : extraneous input '(' expecting {'.','!',ACCESS etc. ... 
Code : _Buffer = Space**$**(LOF(f))_ 'It didn't seem to like the $

***

For the same code if you comment the previsous error

Parser Error : extraneous input 'Get' expecting NEWLINE 
Code : _**Get** #f, , Buffer_

**Comment by retailcoder** [comment]
Thanks for the feedback! I'll test it tonight, but I'm 99.99% sure these grammar/parser issues are fixed in the latest build already.

**Comment by autoboosh** [comment]
Just tested it using the latest grammar and they both work fine.

**Comment by retailcoder** [comment]
Awesome, thanks @autoboosh!
