### ISSUE TITLE
IdentifierReferenceResolver tune-up

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#1166]
The code used in #1161 has about 20 modules of reasonable size; parsing completes in an *acceptable* amount of time (given all the attached listeners and everything that's going on during that phase), but resolving completes in just below 20 minutes, at least on my machine.

There *has* to be a way to improve this *dramatically*. The resolver does *lots* of work, but it's constantly iterating all `Declaration` objects to find a declaration for every single identifier reference is comes across as it walks every single parse tree - the code has over 2,200 declarations to work with, including 600-some built-in ones, which include the Excel object model declarations; I'd deem it an "average-sized" VBA project, and it taking 20 minutes to resolve is a complete showstopper.

We can get parsing to work faster by only parsing modified modules, but the resolver needs to walk all parse trees all the time, and it needs to do it faster. **Much** faster.

**Comment by Vogel612** [comment]
How deeply can you modify the `Declaration`-container? You may be able to drastically reduce search-space (and time) by using a prefix-tree or a similar datastructure to store and retrieve the declarations. 

That should get you to something between a quarter and a tenth of the runtime...

**Comment by retailcoder** [comment]
@Vogel612 right now the resolver is receiving an `IReadOnlyList<Declaration>` in its constructor, and then proceeds to "pre-filter" *some* of them:

            _scopingDeclarations = _declarations.Where(item =>
                _scopingTypes.Contains(item.DeclarationType)
                && item.Project == _qualifiedModuleName.Project
                && item.ComponentName == _qualifiedModuleName.ComponentName).ToList();

            _parentDeclarations = _declarations.Where(item =>
                _parentTypes.Contains(item.DeclarationType)
                && item.Project == _qualifiedModuleName.Project
                && item.ComponentName == _qualifiedModuleName.ComponentName).ToList();

...but these pre-filtered lists aren't used everywhere they should be, and there's not enough of them.

I don't know what a prefix-tree looks like, but there are TONS of examples like this one:

        private IEnumerable<Declaration> FindMatchingTypes(string identifier)
        {
            return _declarations.Where(declaration =>
                declaration.IdentifierName == identifier
                && (declaration.DeclarationType == DeclarationType.Class
                || declaration.DeclarationType == DeclarationType.UserDefinedType))
                .ToList();
        }

..where the entire `_declarations` list is being iterated and tested against a given `IdentifierName`. I'm thinking of reducing the number of objects to iterate, by doing something like this in the constructor:

            _types = _declarations.Where(declaration =>
                declaration.DeclarationType == DeclarationType.Class
                || declaration.DeclarationType == DeclarationType.UserDefinedType)
                .ToList();

And then `FindMatchingTypes` could do this:

        private IEnumerable<Declaration> FindMatchingTypes(string identifier)
        {
            return _types.Where(declaration => declaration.IdentifierName == identifier)
                .ToList();
        }

Which would be considerably faster.

Truth is, the whole class is a freakin' 1200-liner mess that needs to be refactored. Badly.

**Comment by retailcoder** [comment]
Performance felt like this yesterday:

> 'ThisWorkbook' is Ready. Resolver took 6488ms to complete.
'vbVBAAllPri' is Ready. Resolver took 15748ms to complete.
'fnConstPri' is Ready. Resolver took 9360ms to complete.
'fnTypePri' is Ready. Resolver took 41024ms to complete.
'vbXlPivotAxisPri' is Ready. Resolver took 45925ms to complete.
'fnInfoErrMsgPri' is Ready. Resolver took 80103ms to complete.
'fnCheckPri' is Ready. Resolver took 117537ms to complete.
'vbFnCollectionPri' is Ready. Resolver took 122700ms to complete.
'vbXlRangePri' is Ready. Resolver took 131213ms to complete.
'vbXlPivotLinePri' is Ready. Resolver took 235589ms to complete.
'vbXlPivotFieldPri' is Ready. Resolver took 280777ms to complete.
'vbFnPivotTablePri' is Ready. Resolver took 301612ms to complete.
'vbXlPivotItemPri' is Ready. Resolver took 301269ms to complete.
'vbXlPivotTablePri' is Ready. Resolver took 307364ms to complete.
'fnRegEx' is Ready. Resolver took 385093ms to complete.
'vbVarTypeNamePri' is Ready. Resolver took 153507ms to complete.
'fnPivotFieldStatFn_ParPri' is Ready. Resolver took 383385ms to complete.
'fnErrorPri' is Ready. Resolver took 860841ms to complete.
'vbFnPivotItemPri' is Ready. Resolver took 987314ms to complete.
'vbFnPivotFieldPri' is Ready. Resolver took 984727ms to complete.
'fnToolsPri' is Ready. Resolver took 1156145ms to complete. (includes about 30 seconds stopped on a breakpoint)

After edb6ce7 (not actual order - I lined them up with yesterday's for easier comparison):

> 'ThisWorkbook' is Ready. Resolver took 5193ms to complete.
'vbVBAAllPri' is Ready. Resolver took 6463ms to complete.
'fnConstPri' is Ready. Resolver took 6639ms to complete.
'fnTypePri' is Ready. Resolver took 7043ms to complete.
'vbXlPivotAxisPri' is Ready. Resolver took 9357ms to complete.
'fnInfoErrMsgPri' is Ready. Resolver took 3045ms to complete.
'fnCheckPri' is Ready. Resolver took 10007ms to complete.
'vbFnCollectionPri' is Ready. Resolver took 5877ms to complete.
'vbXlRangePri' is Ready. Resolver took 7746ms to complete.
'vbXlPivotLinePri' is Ready. Resolver took 10055ms to complete.
'vbXlPivotFieldPri' is Ready. Resolver took 3748ms to complete.
'vbFnPivotTablePri' is Ready. Resolver took 13708ms to complete.
'vbXlPivotItemPri' is Ready. Resolver took 11840ms to complete.
'fnRegEx' is Ready. Resolver took 19064ms to complete.
'vbVarTypeNamePri' is Ready. Resolver took 10462ms to complete.
'fnPivotFieldStatFn_ParPri' is Ready. Resolver took 13779ms to complete
'fnErrorPri' is Ready. Resolver took 57925ms to complete.
'vbFnPivotItemPri' is Ready. Resolver took 23379ms to complete.
'vbFnPivotFieldPri' is Ready. Resolver took 46433ms to complete.
'fnToolsPri' is Ready. Resolver took 52410ms to complete.

57 seconds is pretty long. But given it was 16 minutes before that commit, I'm calling it mission accomplished here -- and there's *still* room for improvement!

The "Ambiguous match in '{localScope}': '{identifierName}'" debug output shows all `ProjectScopeDeclaration` that couldn't be resolved because more than 1 declaration matches - that's potentially a problem.

"Unknown identifier in '{localScope}': '{identifierName}'" debug output shows all `ProjectScopeDeclaration` identifier references that couldn't be resolved because no declaration exists for it - that's an entirely different issue: perhaps the `ExcelObjectModel` or `VbaStandardLibrary` declarations could be modified to include them, but there's no real value in doing so. If `Option Explicit` isn't specified, it could also mean a reference to an undeclared identifier was encountered.

**Comment by retailcoder** [comment]
@Vogel612 

> That should get you to something between a quarter and a tenth of the runtime...

Make that anywhere between half, and 1/30th of the runtime.

**Comment by ThunderFrame** [comment]
I'm yet to pull the updates, but I have some ideas around resolving *all* of the non-project referenced types, exactly once. It seems that adding a reference to a project, prompts VBE to *immediately* load all of the TypeInfo details for the reference, *at the time* of adding the reference. Similarly, removing a reference seems to *immediately* remove those TypeInfo details.

Given VBIDE ReferenceEvents tell us when a reference is Added or Removed, couldn't we load and cache the TypeInfo details too? And if more than one VBA project is open, and 2 or more of those projects refer to the same underlying Type Library, then we only need to retrieve the TypeInfos once per library.

You could even load the TypeInfo for the *expected* references, on Rubberduck Initialize/load, or *before* a project is fully loaded in VBE, such as the references for VBA, the Host application, StdOLE and maybe the installed version of Office.

Furthermore, I *suspect* VBE makes a TypeInfo cache for the VBA projects, including *all variables*, and then ObjectBrowser merges the TypeInfos caches from the references and the projects. For existing projects, loaded from disk, I *suspect* VBE has the advantage of being able to read cached Project TypeInfo details from dedicated performance-cache IStreams in the VBA binary, and these binary formats are not detailed in the specification other than stating "Must be ignored on read", "Must not be present on write". For new projects (or newly *decompiled* projects), I suspect VBE builds the TypeInfo cache on the fly.

I suspect *that* is how EveythingAccess is able to *decompile* an MDE/ACCDE project from p-code, and yet claim:
> We retain the original procedure names
We retain the original variable names and data types

And ^that is frustrating, as it suggests that in addition to the types that are visible in Object Browser, VBE knows about *all* the types and variables, including the procedure level variables, but doesn't show the procedure level variables. Wouldn't that *also* bring about an improvement?

But if we knew all of the Referenced Type Declarations, and we could parse for the module level declarations, then we know all of the global and module-scoped types *before* resolving the procedure-level expressions.

**Comment by Pitterling** [comment]
@retailcoder This sounds promising!!! GREAT!! ... i pulled all commits and now Parsing takes forever ... 15min or so . Also a lot of Unknown identifier program outputs are floating my output window ...
Is anything missing on my side??

**Comment by retailcoder** [comment]
@ThunderFrame that's a very nice idea - however there's a fine line we need not to cross, between *collecting available data* and *reverse-engineering* code that's protected for a reason that sometimes goes beyond write protection. VBA needs the type information of protected projects to *compile and run* them.

I like that it could make this code useless:

 - [VbaStandardLib](https://github.com/rubberduck-vba/Rubberduck/blob/next/Rubberduck.Parsing/Symbols/VbaStandardLib.cs)
 - [MsFormsLib](https://github.com/rubberduck-vba/Rubberduck/blob/next/Rubberduck.Parsing/Symbols/MsFormsLib.cs)
 - [AdodbObjectModel](https://github.com/rubberduck-vba/Rubberduck/blob/next/Rubberduck.Parsing/Symbols/AdodbObjectModel.cs)
 - [ExcelObjectModel](https://github.com/rubberduck-vba/Rubberduck/blob/next/Rubberduck.Parsing/Symbols/ExcelObjectModel.cs)

..and all other object models that we wouldn't need to explicitly/statically create `Declaration` objects for.

**Comment by retailcoder** [comment]
@Pitterling when I tested against your workbook yesterday, parsing completed in a relatively reasonable amount of time (as it did before - no change there), and resolving completed in less than two minutes (which is a dramatic improvement)... not sure how the *parsing* step could take that long, this code wasn't modified and I'm not seeing it affected at all here.

The debug output is from the resolver, as I explainer above:

> The "Ambiguous match in '{localScope}': '{identifierName}'" debug output shows all ProjectScopeDeclaration that couldn't be resolved because more than 1 declaration matches - that's potentially a problem.

> "Unknown identifier in '{localScope}': '{identifierName}'" debug output shows all ProjectScopeDeclaration identifier references that couldn't be resolved because no declaration exists for it - that's an entirely different issue: perhaps the ExcelObjectModel or VbaStandardLibrary declarations could be modified to include them, but there's no real value in doing so. If Option Explicit isn't specified, it could also mean a reference to an undeclared identifier was encountered.

These `System.Diagnostics` calls are slowing down the resolver a bit in a debug-config build, but won't be compiled into a release-config build, so the actual 2.0 release build will perform even better.

I added these "unknown identifier" and "ambiguous match" outputs to help diagnose resolver issues and perhaps see opportunities in missing built-in declarations that could be added.

**Comment by ThunderFrame** [comment]
@retailcoder  Yes, I agree - Reverse Engineering, or circumvention is a bad idea.

But if it's visible in Object Explorer then at least those type declarations are not hidden from the user, and so we should know about them.

Object Explorer shows the public types, even for Protected Projects, and it shows Private and Public types for unprotected projects. It's amazing how many projects I've seen, that have project and sheet protection, only to expose public constants or methods that allow you to unlock the project/sheets. I guess not many developers know about Private Modules, and Public modules are the default.

**Comment by Pitterling** [comment]
@retailcoder hmmm .. does not work for me .. i just rebooted and downloaded my example ;) after 6min it still says "Parsing". At least the unknown identifier output messages are gone completely.

**Comment by ThunderFrame** [comment]
Resolve the TypeInfos, and then #1093 become *easy*.

**Comment by retailcoder** [comment]
@Pitterling I wonder if combining the parse tree listeners into one would help speed up the parsing... thing is, the parsing step is really the most resource-intensive part, and there's not much *we* can do to make it happen faster, since the parser is generated by ANTLR off the grammar.

We need to get an `IParseTree` from the ANTLR parser for every code module in the project; the time it takes to process a code module is directly proportional to the length of the code, and the complexity of the expressions in it.

Now, parsing *all modules* takes a little while; parsing only one module doesn't take very long - but we're just about to get parsing stabilized: once that's done, we'll only be parsing all modules *once* at startup, and then only modified modules, in the background, *as it's being modified*.

**Comment by Pitterling** [comment]
@retailcoder - i tried on another installation and here it is working as expected - tremendous performance improvement. GREAT. I need to fix my laptop setup ...

I love the outlook: 
> but we're just about to get parsing stabilized: once that's done, we'll only be parsing all modules once at startup, and then only modified modules, in the background, as it's being modified.
