### ISSUE TITLE
Parameterized properties break refactor/rename

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#1169]
Renaming the `index` parameter of a parameterized property:

    Property Get Foo(ByVal index As Integer) As String
    End Property

    Property Let Foo(ByVal index As Integer, ByVal value As String)
    End Property

Does not rename the parameter in all accessors, which breaks the code:

    Property Get Foo(ByVal renamed As Integer) As String
    End Property

    Property Let Foo(ByVal index As Integer, ByVal value As String)
    End Property

**Comment by Hosch250** [comment]
What's up here?

**Comment by retailcoder** [comment]
I don't think this was addressed. Needs verification, good catch @Hosch250
