### ISSUE TITLE
Update LibGit2Sharp version

### ISSUE THREAD

**Issue by ckuhn203** [rubberduck-vba/Rubberduck#1176]
LibGit2Sharp recently released version 0.22. 

https://github.com/libgit2/libgit2sharp/releases/tag/v0.22

I'd like to stay reasonably up to date, but I also don't want to put our own release of 2.0 at risk. 

There is some info about the FileStatus enumerating in #485 here, and is related to [1062 on LG2](https://github.com/libgit2/libgit2sharp/pull/1062). Should be simple enough to fix up on our end. #222 is also related. We need to make sure any changes bubble up to the COM interop library. I'd like to maintain the API if possible. If this means we need to do a more complicated mapping internally, so be it. I'd rather not leak the implementation detail out to existing clients, effectively breaking them. 

The one that concerns me more is [1171 on LG2](https://github.com/libgit2/libgit2sharp/pull/1171). We're currently relying on behavior that was removed in the latest version. We'll need to ensure that we're using the actual credentials provided by the user in the SourceControlSettings panel, instead of _trying_ to get them from the .gitconfig file. Very closely related to #770, #533, #532, #722, & #667.

**Comment by retailcoder** [comment]
I don't know what the impacts are (haven't touched the SC code in any way, ever) - but don't worry about risking the 2.0 release over this: there's still plenty of time to get things to work with the latest & greatest libgit2sharp version. Just take it to its own branch! Or am I missing something?

**Comment by ckuhn203** [comment]
I just don't want to get into a quagmire of trying to upgrade when @Hosch250 is just stabilizing the feature. There are a number of breaking changes. I think those are the only two that affect us, but I could have missed something. I can pull down the latest version of vNext next weekend and determine the impact.

**Comment by retailcoder** [comment]
Ok. Well then, let's let @Hosch250 get the feature release-ready (it's almost there), and then there can be a new branch made for the upgrading of the libgit2sharp dependency, done on-the-side while the SC stuff isn't being worked on anymore.

**Comment by Vogel612** [comment]
SourceControl is already on v0.22. I daresay that means this is fixed
