### ISSUE TITLE
Code Inspection for unsaved projects

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#1177]
Rubberduck should warn the user that the project is not saved, possibly by vbComponent.

Also, as it is possible to add modules to any unprotected workbook, even workbooks that were opened from CSV or TXT sources, Rubberduck should warn that the current "file-format" is not suitable for VBA.

**Comment by Vogel612** [comment]
This is already done by the Host-App. I know EXCEL does warnings when you try to save these workbooks, as well as asks you back when you didn't save them before closing.

I'd say this is out of scope for Rubberduck since it's already provided and frankly I'd hope Rubberduck users understand the implications of not saving or adding macros to Workbooks opened from TXT / CSV / [insert unsuitable file-format]

**Comment by ThunderFrame** [comment]
Iirc, a workbook that has never been saved, will not persist the VBA in a recovered workbook/document, should Excel/Word go Boom.
Given that RubberDuck has the <s>feature</s> capacity to make the application implode, and mis-calling some declared functions can do the same, providing a warning inspection might be considered useful?

**Comment by Vogel612** [comment]
I don't think it's useful as an "in-Rubberduck"-Warning. I agree it's useful to mention explicitly that Host-Apps may implode when Rubberduck is running. 

That would be on the download / install pages though...

**Comment by retailcoder** [comment]
I just want to say that Rubberduck's capacity to make the host app go boom, will be significantly impaired by the time 2.0 is release-ready :wink:

**Comment by retailcoder** [comment]
@ThunderFrame you know @Hosch250 implemented an #1115 auto-save feature, right?

**Comment by ThunderFrame** [comment]
Yeah I know the autosave feature, but iirc, it only works on projects that have been saved before (I.e. they have a FileName).
So maybe the inspection should be AutoSave not enabled?

**Comment by retailcoder** [comment]
Sounds like a job for a "Did you know?" pop-up at startup...
