### ISSUE TITLE
Parsing to Double _vbe.Version with comma

### ISSUE THREAD

**Issue by thetopic** [rubberduck-vba/Rubberduck#1178]
In the "**next**" branch with current sources.

File : Rubberduck.Parsing\VBA\RubberduckParser.cs Line 228

````c#
var preprocessor = new VBAPreprocessor(double.Parse(_vbe.Version));
```

If the decimal separator is a comma the `double.Parse` throw an exception.

**Comment by retailcoder** [comment]
Good catch!

**Comment by ThunderFrame** [comment]
Parse just need the IFormatProvider overload? CultureInfo.CurrentCulture?

We should probably check other Parse and Format methods, to make use of IFormatProvider too?

**Comment by autoboosh** [comment]
I would have said [CultureInfo.InvariantCulture](https://msdn.microsoft.com/en-us/library/system.globalization.cultureinfo.invariantculture(v=vs.110).aspx).

**Comment by autoboosh** [comment]
Here's a fix for number parsing methods. Do we need that for string.Formats as well, as you mentioned @ThunderFrame? Perhaps just the string.Formats that do not format a string specified in the resources file?
