### ISSUE TITLE
AmbiguousMatchException : Lib Alias typeHint

### ISSUE THREAD

**Issue by thetopic** [rubberduck-vba/Rubberduck#1179]
In the "**next**" branch with current sources.

I have the same kind of code that can be found here : #250 

```vba
Private Declare Function RegOpenKeyEx Lib "advapi32" Alias "RegOpenKeyExA" _
  (ByVal HKey As Long, ByVal lpSubKey As String, ByVal ulOptions As Long, _
  ByVal samDesired As Long, phkResult As Long) As Long
```

If I debug the current sources I have this exception : AmbiguousMatchException

File : Rubberduck.Parsing\Symbols\Declaration.cs Line 322

```c#
var method = Context.GetType().GetMethod("typeHint");
```

**Comment by retailcoder** [comment]
ugh. I'll revert to `dynamic` cast + invoke.
