### ISSUE TITLE
Auto-Implement Interface feature

### ISSUE THREAD

**Issue by ckuhn203** [rubberduck-vba/Rubberduck#118]
Add some kind of tool that allows you to select a Class to implement, and autopopulate a skeleton "template" of all the properties,subs,functions that will be required in the implementing class. Will probably use class names starting with `I` as available selections.

For example, given an Interface `ICyclesDataAdapter`

    Option Explicit
    
    Public Property Get Cycles() As Cycles
    End Property
    
    Public Property Get Recordset() As ADODB.Recordset
    End Property

Running the tool should result in a new class module that looks like this.

    
    Implements ICyclesDataAdapter
    
    Public Property Get Cycles() As Cycles

    End Property
    
    Public Property Get Recordset() As ADODB.Recordset
    
    End Property
    
    Private Property Get ICyclesDataAdapter_Cycles() As Cycles

    End Property
    
    Private Property Get ICyclesDataAdapter_Recordset() As ADODB.Recordset
        
    End Property

**Comment by retailcoder** [comment]
Use VS icon "implement interface" for whatever menu button this is called from.

**Comment by retailcoder** [comment]
I think we can push it a step further, and "map" the generated methods to existing ones, or even to generate method stubs for public members.

Take a painfully repetitive interface to implement, such as this `IRepository` interface:

    Option Explicit
    
    Public Sub SetConnection(ByRef value As ADODB.Connection)
    End Sub
    
    Public Function GetById(ByVal id As Long) As SqlResultRow
    End Function
    
    Public Function GetAll() As SqlResult
    End Function
    
    Public Function FindId(ByVal naturalKey As SqlResultRow) As Long
    End Function
    
    Public Function Search(ByVal terms As SqlResultRow) As SqlResult
    End Function
    
    Public Function Count() As Long
    End Function
    
    Public Sub Add(ByVal value As SqlResultRow)
    End Sub
    
    Public Sub Remove(ByVal id As Long)
    End Sub
    
    Public Sub Update(ByVal id As Long, ByVal value As SqlResultRow)
    End Sub
    
    Public Function NewItem(ByVal Model As SqlResult, ByVal values As Dictionary) As SqlResultRow
    End Function

---

**Use Case 1: Empty Class**

 - User adds a new class module to the project
 - User types `Implements IRepository` at the top of the module
 - <s>Clippy pops up and says "It looks like you are implementing an interface..."</s>
menu
 - Either... 
    - User right-clicks somewhere in the code pane and selects "Implement interface" from the code pane's context menu
       - Rubberduck knows the class module `Implements IRepository` and has no implementation for it; if there were two or more unimplemented interfaces, we would have to prompt for which one to implement.
   - OR user right-clicks the `Implements IRepository` instruction; Rubberduck sees no implementation for it; if the interface were fully implemented, we would have to notify the user to say "This interface is already implemented".
 

Rubberduck knows the class has no members, but not how the user might want to implement the interface and expose the members, so a UI is brought up where user can select...

 - (default?) **Private implementation**: interface members are only accessible when client code is working against the interface type.
 - **Public implementation**: interface members are also accessible when client code is working against the concrete type.

The *private implementation* would simply generate empty method stubs for each member of the interface to implement.

The *public implementation* would generate empty method stubs named after the members of the interface to implement, and then would generate the actual interface members, with a call to the public method stubs.

---

**Use Case 2: Class with an existing public implementation**

(I had a draft here, but this quickly gets out of hand. do we really need this?)

**Comment by retailcoder** [comment]
We could also have an option to raise some "Not implemented" error in the stubs.

**Comment by ckuhn203** [comment]
I like the not implemented error very much. I do this manually right now. Might as well populate it as part of the template. :+1: 

Oh, and :+1: to the rest of the idea as well.
