### ISSUE TITLE
Parser Errors on projects with pseudo-protection

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#1185]
Products like [Unviewable+](http://www.spreadsheet1.com/unviewable-vba-project-app-for-excel.html) are marketed at VBA Developers that want to distribute/sell Excel Workbooks and protect the VBA <u>in a way that keeps the module content _unviewable_, even if the project is unprotected using other techniques.</u>. Depending upon the implementation and settings, the modules are viewable in Project Explorer, but the modules don't display properly in VBE.

The "unviewable" status is achieved, _I think_, by deliberately corrupting the VBA Project's binary, such that it compiles and runs, but VBE can't/won't display the content. That's imperfect protection, but it's an extra layer that typical users won't be able to bypass.

There are commercial XLSM-based add-ins that re using such products already, and we can expect users of Rubberduck to have such XLSM-based add-ins installed. Rubberduck currently has difficulties with such add-ins/workbooks, because the project isn't necessarily protected (in the normal way), and yet the modules can't be parsed.

I _suspect_ that at least part of the "unviewability" is achieved by using [invalid characters](https://support.microsoft.com/en-us/kb/213560) in module names, but there may be other "tweaks" that contribute to the unviewability.

Rubberduck can probably avoid trying to parse an unviewable project by checking to see if _any_ of the modules have invalid module names.

**Comment by retailcoder** [comment]
That's unfortunate. Can you confirm that such modules would have *invalid names*?

Can such projects be properly protected by the users?

**Comment by ThunderFrame** [comment]
There are some sample projects on that page I linked. Direct download link [here](https://spreadsheet1.box.com/shared/static/evdm2py0mgry61kue9500jw5uupoidrd.zip)

**Comment by ThunderFrame** [comment]
Just to be clear, Rubberduck should **not** try to circumvent the psudo-protection, but nor should such projects break the parser....

**Comment by ThunderFrame** [comment]
MVP's are using these protections on their commercial products, and ideally they'll find a use for RubberDuck too. So fixing this issue is important because it gets RubberDuck working for MVP's.

**Comment by ThunderFrame** [comment]
It seems that Unviewable+ offers configurable levels/features of protection. Presumably most instances would include the use of a Protected Project (so Rubberduck *should* handle those without any trouble), so the only problematic projects are those that *aren't* protected projects, but *do* have *unviewable* module "protection".

We should be maybe treat those special case projects as a known issue for now.

**Comment by retailcoder** [comment]
Rubberduck's intended behavior when *any* module can't be parsed, is to skip identifier reference resolution and report a parsing error; this leaves refactorings and inspections disabled, by design.

I think we should be able to tell an *actual* parsing error from a `COMException` thrown accessing a module's code, and pretty much ignore the throwing project.

**Comment by retailcoder** [comment]
If we take *unviewable* as "I know it's there but I can't do anything with it", we can handle this cleanly I think.

**Comment by PeterMTaylor** [comment]
+1 It is better to be informed than none at all.

**Comment by retailcoder** [comment]
I've narrowed this one down to the `SourceControlViewViewModel`, rethrowing exceptions in its constructor and handling parser state changes before it's ready for it. Fix on the way.

@ThunderFrame that 2048 game is so pretty!!
