### ISSUE TITLE
HRESULT E_FAIL on VBA launch has returned

### ISSUE THREAD

**Issue by TJ2016** [rubberduck-vba/Rubberduck#1190]
This error had gone away for a while after applying the suggested fixes but it is back again.

Weird thing is sometimes everything works as it should with no sign of problems, however access does crash on exit most of the time.

**Comment by Talorthain** [comment]
I got the same error on first run after install. When I closed and restarted excel, error had gone.

Using the latest version

**Comment by Hosch250** [comment]
The crash on exit is known and will be addressed; we can't reproduce the crash on launch, is this still an issue?
