### ISSUE TITLE
Code Inspector - ByRef/ByVal - wrong proposal ByVal for Arrays

### ISSUE THREAD

**Issue by Pitterling** [rubberduck-vba/Rubberduck#1191]
CodeInspector is flagging this line: "Parameter can be passed by value" which in this case is not correct.

`Public Function processOneInterval(ByRef saInterval() As String) As Long`

Arrays need to be passed by "ByRef" otherwise you get an Compiler Error.

**Comment by retailcoder** [comment]
the inspection simply wasn't checking for array parameters. fixed now.

**Comment by Pitterling** [comment]
great. thx
