### ISSUE TITLE
False positive errors in Code Inspector

### ISSUE THREAD

**Issue by INOPIAE** [rubberduck-vba/Rubberduck#1195]
Why is the Code Inspector giving these false positive errors?

Hint: Variable 'sh' is never assigned

Here is the code

    Private Sub CreateDBfromScript()
        Dim strCMD As String
        Dim sh
        Dim FNr As Integer
    
        strCMD = "c:\script\createDB.bat"
    
        sh = Shell(strCMD, vbNormalFocus)
    
    End Sub

Hint: Return value auf member 'ConvertNumber' is never assigned

    Private Function ConvertNumber(ByVal Number As Double) As String
        ConvertNumber = Replace(Number, ",", ".")
    End Function

Hint: Procedure 'ConvertNumer' is never assigned

The Procedure is called in several places in the module.

**Comment by retailcoder** [comment]
Looks like the resolver needs more tests...

**Comment by retailcoder** [comment]
I copied your code to `ThisWorkbook`, like this:

    Private Sub CreateDBfromScript()
        Dim strCMD As String
        Dim sh
        Dim FNr As Integer
    
        strCMD = "c:\script\createDB.bat"
    
        sh = Shell(strCMD, vbNormalFocus)
        Debug.Print ConvertNumber(123)
    
    End Sub
    
    Private Function ConvertNumber(ByVal Number As Double) As String
        ConvertNumber = Replace(Number, ",", ".")
    End Function

Then ran code inspections and got these (removed the option explicit and naming issues for SheetX):

    Correct: procedure 'CreateDBfromScript' is not used - VBAProject.ThisWorkbook, line 1
    Correct: Consider renaming variable 'strCMD' - VBAProject.ThisWorkbook, line 2
    Correct: Consider renaming variable 'sh' - VBAProject.ThisWorkbook, line 3
    Correct: Consider renaming variable 'FNr' - VBAProject.ThisWorkbook, line 4
    Correct: Variable 'sh' is implicitly Variant - VBAProject.ThisWorkbook, line 3
    Correct: variable 'sh' is not used - VBAProject.ThisWorkbook, line 3
    Correct: variable 'FNr' is not used - VBAProject.ThisWorkbook, line 4
    Correct: Variable 'FNr' is never assigned - VBAProject.ThisWorkbook, line 4

Variable `sh` is *assigned* but effectively not referred to. I have no repro with the latest build. Which version are you using?

**Comment by INOPIAE** [comment]
Today I tested with commit 9bb420c197e800fab711ba3b761b294b347a1967

I used this code in a new module:
`Option Explicit

Private Sub CreateDBfromScript()
    Dim strCMD As String
    Dim sh

    strCMD = "c:\script\createDB.bat"

    sh = Shell(strCMD, vbNormalFocus)
    Debug.Print ConvertNumber(123)

End Sub

Private Function ConvertNumber(ByVal Number As Double) As String
    ConvertNumber = Replace(Number, ",", ".")
End Function

Sub Start()
    CreateDBfromScript
End Sub`

I get these results:
`Correct: member 'Start' is imlicitly public - VBAProject.module, line 18  - ok
`Correct: Consider renaming variable 'strCMD' - VBAProject.module, line 4 - ok
Correct: Consider renaming variable 'sh' - VBAProject.module, line 5  - ok
Correct: Variable 'sh' is implicitly Variant - VBAProject.module, line 5 - ok
Correct: variable 'sh' is not used - VBAProject.module, line 5 - FALSE` 

The problem with 

> Return value auf member 'ConvertNumber' is never assigned

has disappread with the latest commits.
