### ISSUE TITLE
"Finalize" parser

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#1201]
So the parser works. That's great, but it's really working too hard, and it's very manual - a number of things need to happen before it's release-ready:

 - [x] Enable cancellation or parser and resolver tasks: this will enable reinstating keyhook-triggered parsing.
 - [x] Make sure all features that modify the user code, request a reparse when they're done modifying the code.

**Comment by Hosch250** [comment]
The reparse will break the tests.

**Comment by Vogel612** [comment]
actually we could just inject a ParserMock, that verifies the parse is requested and delegates to the real implementation for the first call. Sounds good?
