### ISSUE TITLE
Disabled controls should look disabled

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#1206]
The *Branches* panel has an empty *Branch* drop-down, and [New Branch] and [Merge] buttons don't seem to be doing anything when there's no repo connected - the controls should be disabled, like the [Unpublish] and [Delete] buttons correctly are:

![image](https://cloud.githubusercontent.com/assets/5751684/13900513/98fc2a96-edde-11e5-8b8d-a72038cc8f4c.png)

Same with [Fetch] [Pull] [Push] and [Sync] buttons in the "Unsynced commits" tab - they're disabled but they don't look like it:

![image](https://cloud.githubusercontent.com/assets/5751684/13900523/c07d5a68-edde-11e5-82ab-02cbee1bf07f.png)

Also the *commit message* box and "Go" button (and the dropdown next to it), are/look enabled, but the [Go] button doens't do anything since we're offline:

![image](https://cloud.githubusercontent.com/assets/5751684/13900532/ecdb469c-edde-11e5-98da-7facec13f606.png)

**Comment by Hosch250** [comment]
These don't look enabled.  This is the working version:
![](http://imgur.com/YEUNNMG.png)
