### ISSUE TITLE
New files should be "Added", not "Untracked"

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#1207]
Steps to repro:

 - Create new repository for this project
 - Select local path
 - Add a new class module
 - Make a modification
 - Click 'refresh' in SC panel

The `Class1.cls` file goes to *Untracked files*:

![image](https://cloud.githubusercontent.com/assets/5751684/13900592/12074a32-ede0-11e5-9996-9b81f7587ca7.png)

...and then there's no way of moving it to "included changes" or in any way, shape or form of interacting with it. Also notice the [Go] button looks very much enabled, but doesn't do anything.

**Comment by retailcoder** [comment]
Modifying the existing `ThisWorkbook` module also puts the `ThisWorkbook.doccls` under *Untracked*

**Comment by retailcoder** [comment]
Oh gosh... I totally missed the [Include] button

![image](https://cloud.githubusercontent.com/assets/5751684/13900759/4199113c-ede4-11e5-8b4e-6f4c7b438d16.png)

The button needs an icon, it's almost invisible otherwise.

**Comment by retailcoder** [comment]
The files going to "untracked" might be just a by-product of me wrongly setting up the repo.

![image](https://cloud.githubusercontent.com/assets/5751684/13900796/e8a9338a-ede4-11e5-98bc-e51cdc5bc101.png)

...the initial setup needs to be documented.

**Comment by Hosch250** [comment]
This should be fixable with the new component_added sink.

**Comment by Vogel612** [comment]
@retailcoder having new files as "untracked" closely mirrors the behavior of vanilla git. New files are by default "untracked" once you `git add` them they're "staged". After a `git commit` the staged files are included into the working tree. Assuming that the file was already present in the working tree, it's "tracked" and will show up as "modified" when you change it

**Comment by retailcoder** [comment]
@Vogel612 perhaps we need to make a note of a user preference here, for the yet-to-be-implemented Source Control settings tab:

>  - [x] Automatically add new components to repository
