### ISSUE TITLE
SC should warn/prompt/something when project name doesn't match

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#1214]
I had created the repository off a project named after the remote repo, `rubberduck_sc_test`. Then things happened, and Excel went boom on me before I could save. Luckily I had my VBA code pushed to the GitHub remote already, so I brought up Excel/VBA again and clicked "open working directory" and selected my working directory.

Rubberduck added the files to the current project, which is awesome.

But it also silently created a new "repository" entry in the SC configuration file (I realize this is by design):

	  <Repositories>
		<Repository>
		  <Name>VBAProject</Name>
		  <LocalLocation>C:\Dev\VBA\Rubberduck-Repos\rubberduck_sc_test</LocalLocation>
		  <RemoteLocation>C:\Dev\VBA\Rubberduck-Repos\rubberduck_sc_test</RemoteLocation>
		</Repository>
		<Repository>
		  <Name>rubberduck_sc_test</Name>
		  <LocalLocation>C:\rubberduck_sc_test</LocalLocation>
		  <RemoteLocation />
		</Repository>
		<Repository>
		  <Name>rubberduck_sc_test</Name>
		  <LocalLocation>C:\Dev\VBA\Rubberduck-Repos\rubberduck_sc_test</LocalLocation>
		  <RemoteLocation>https://github.com/retailcoder/rubberduck_sc_test</RemoteLocation>
		</Repository>
		<Repository>
		  <Name>VBAProject</Name>
		  <LocalLocation>C:\Dev\VBA\Rubberduck-Repos\rubberduck_sc_test</LocalLocation>
		  <RemoteLocation />
		</Repository>
	  </Repositories>

Instead of just going ahead and creating the entries and loading it up into the current project, Rubberduck should try as hard as possible to reuse existing configuration entries, and ask the user what to do when it's not sure - what are the implications of the repository name mismatching the remote anyway? Do we even need a repository name? Does it have to be the project? It seems the working directory's folder would be a more stable option, is there a reason it wasn't done that way?

**Comment by retailcoder** [comment]
Things would obviously be different if I was working off a *saved* workbook.

**Comment by Hosch250** [comment]
This shouldn't be an issue now that we are working off the project ID.
