### ISSUE TITLE
Forms (.frm) are perpetually marked as "modified"

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#1216]
It seems exporting UserForm classes/modules keeps adding a newline at the top of the file, as shown in [this commit history](https://github.com/retailcoder/rubberduck_sc_test/commits/1ef4626363b6f4139f1b3947a335052f33307480/ProgressView.frm).

This is a bug that may require a dirty work-around.

**Comment by ckuhn203** [comment]
Im not sure that this is our bug. All we do is export the file to the file system. We only do "something fancy" for document type modules. https://github.com/rubberduck-vba/Rubberduck/blob/next/Rubberduck.VBEEditor/Extensions/VBComponentExtensions.cs

**Comment by retailcoder** [comment]
Every new commit (/export?) to the .frm adds a new newline - @ckuhn203 you could be right, this might be a bug with the VBIDE API.. it's ours to fix though ;-)

**Comment by ckuhn203** [comment]
Well... Yeah. I'm not saying it's not ours to work around. Just that it is probably a work around. Can you manually export a file through the VBE and verify that it adds the new line?

**Comment by retailcoder** [comment]
Yup. Manually exporting/importing behaves the same.

First export:

    Attribute VB_Exposed = False
    Option Explicit
 
Imported, and then re-exported:

    Attribute VB_Exposed = False
    
    Option Explicit

This is officially a VBIDE API bug!

**Comment by retailcoder** [comment]
I've been giving this some thought, and we need to split the export process - otherwise exporting the file and "fixing" it in place will still have git mark it as modified (despite there being no diff).

Proposed work-around:

 - Determine the number of declaration lines in the module
 - Export the module to a temp file
 - Load the exported file, determine the number of declaration lines in the file
 - Remove the extraneous carriage return if it's there
 - Move the modified file to where the extension method intended to export

Thoughts?
