### ISSUE TITLE
'Parsed' parser state should refresh SC panel asynchronously

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#1219]
Doing this will automatically have the source control feature pick up modified files, without manually refreshing anything.

And when the parser is triggered by the keyhook, code changes will automatically export to the local repository as they're being made.

This requires updating the SC panel refreshing to work asynchronously, to avoid constantly blocking the UI while files are being written to disk. Parsing isn't instantaneous, but we should still beware of race conditions and queue the I/O work.

`ParserState.Parsed` is the earliest parser state this refresh can safely happen:

 - 'Pending' wouldn't make sense.
 - 'Parsing' would constantly be firing (keyhook would trigger it at every keypress).
 - 'Parsed' means the code is in a compilable (well, grammatically correct at least) state.
 - 'Error' means the code isn't grammatically correct (as far as Rubberduck's parser can tell). Refreshing SC panel at that point could be damaging.
 - 'Resolving' would work.
 - 'Ready' would work as well.
 - 'ResolverError' means the code is breaking the resolver. Refreshing SC panel would work, but wouldn't be sane.

Starting the I/O upon 'Parsed' means it would be happening at the same time as the resolver is doing its thing.

**Comment by vovka1981** [comment]
Ai I understand when invoked by shortcut refresh is made on the background and the refresh button is inactive while it process it. 
The issue is when this button-icon becomes active, sometimes its not refreshes by keys shortcut, only by pressing this button directly (
