### ISSUE TITLE
Localisation problems with Code Inspector

### ISSUE THREAD

**Issue by INOPIAE** [rubberduck-vba/Rubberduck#1220]
I work with Excel2010 on a German system Win7 and Office.
The language setting for Rubberduck is English
I get these errors
![image](https://cloud.githubusercontent.com/assets/2772829/13903987/f43b6086-ee90-11e5-8c06-ff4dee7015e2.png)
The window title is in German.
The location shows FehlerTest ....

**Comment by Vogel612** [comment]
IIUC Location is about where in your code the inspection triggered. 

From the schema I'd guess your workbook is named "FehlerTest". I daresay that Location is not localized in any way, so this is probably [status-by-design]

**Comment by INOPIAE** [comment]
@Vogel612: you are correct with the wokrbook name.
But the problem with the wrong language in the window title remains.

**Comment by retailcoder** [comment]
Can you confirm the issue bring only about the *inspection results* toolwindow, or do all dockable toolwindows have the same issue?

**Comment by INOPIAE** [comment]
I find the following:
Codeinspector window caption shows the language of the application => false
Source control => correct
Settings window caption is in English only => false
About window caption is in English only => false
Test Explorer seems to be correct
Code Explorer is not localised at all => false
Todo Explorer seems to be correct

In the navigate menue some entries are missing in English and German
![image](https://cloud.githubusercontent.com/assets/2772829/13906177/86a11134-eed0-11e5-89f3-a97e4fd01a1f.png)

**Comment by retailcoder** [comment]
Aye, these have been bothering me for quite a while.. that's the *regex search* command - and there's a bug right here, making it appear twice:

        private IMenuItem GetNavigateParentMenu()
        {
            var items = new IMenuItem[]
            {
                _kernel.Get<CodeExplorerCommandMenuItem>(),
                _kernel.Get<ToDoExplorerCommandMenuItem>(),
                _kernel.Get<RegexSearchReplaceCommandMenuItem>(),
                _kernel.Get<FindSymbolCommandMenuItem>(),
                _kernel.Get<FindAllReferencesCommandMenuItem>(),
                _kernel.Get<FindAllImplementationsCommandMenuItem>(),
                _kernel.Get<RegexSearchReplaceCommandMenuItem>(),
            };
            return new NavigateParentMenu(items);
        }

The `RegexSearchReplaceCommandMenuItem` is expecting a `RubberduckMenu_RegexSearchReplace` resx key:

    public class RegexSearchReplaceCommandMenuItem : CommandMenuItemBase
    {
        public RegexSearchReplaceCommandMenuItem(ICommand command)
            : base(command)
        {
        }

        public override string Key { get { return "RubberduckMenu_RegexSearchReplace"; } }
        public override int DisplayOrder { get { return (int)NavigationMenuItemDisplayOrder.RegexSearchReplace; } }
    }

Apparently that key doesn't exist - creating it will make the caption show up.

**Comment by INOPIAE** [comment]
I found another place where the Rubberduck language is not used.
The tooltip of the Refresh button in the Rubberduck icon bar shows the Office language, German in my case. The Rubberduck language is English.
![image](https://cloud.githubusercontent.com/assets/2772829/13942944/3f5ce7de-eff8-11e5-9da8-0ee78b850247.png)

**Comment by INOPIAE** [comment]
And a second place in the Code Inspector.
Language settings again Office German, Rubberduck English
![image](https://cloud.githubusercontent.com/assets/2772829/13943080/b6fc21d2-eff9-11e5-95da-ae4155fda7b9.png)
The iconbar of the Code Inspector window shows the English terms. If I open the "Fix" sub menue it is in German.

**Comment by Vogel612** [comment]
#1397 seems to duplicate this...

**Comment by Hosch250** [comment]
This should be obsolete now.

**Comment by retailcoder** [comment]
Correct - and I confirm it fixed.
