### ISSUE TITLE
"Open working directory" should be selecting from known repositories

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#1222]
Rubberduck saves working directories in its `SourceControl.rubberduck` configuration file, under `Repository` entries:

```
<Repository>
  <Name>rubberduck_sc_test</Name>
  <LocalLocation>C:\Dev\VBA\Rubberduck-Repos\rubberduck_sc_test</LocalLocation>
  <RemoteLocation>https://github.com/retailcoder/rubberduck_sc_test</RemoteLocation>
</Repository>
<Repository>
  <Name>TestRepo2</Name>
  <LocalLocation>C:\Dev\VBA\Rubberduck-Repos\TestRepo2</LocalLocation>
  <RemoteLocation>https://github.com/retailcoder/TestRepo2</RemoteLocation>
</Repository>
```

When user clicks "open working directory" to resume work on an existing repo, Rubberduck is currently making the user browse for the folder; instead we should present the user with the list of `LocalLocation` folders and their corresponding respective repositories.

**Comment by INOPIAE** [comment]
Another way would be at least to start with the default repository path (if available)

**Comment by retailcoder** [comment]
True, but the default path could be changed anytime - besides by listing the actual contents of "known repositories", we gain visibility on "accidents" and other oddities.. e.g. my config file looks like this ATM:

  <Repositories>
    <Repository>
      <Name>VBAProject</Name>
      <LocalLocation>C:\Dev\VBA\Rubberduck-Repos\rubberduck_sc_test</LocalLocation>
      <RemoteLocation>C:\Dev\VBA\Rubberduck-Repos\rubberduck_sc_test</RemoteLocation>
    </Repository>
    <Repository>
      <Name>rubberduck_sc_test</Name>
      <LocalLocation>C:\rubberduck_sc_test</LocalLocation>
      <RemoteLocation />
    </Repository>
    <Repository>
      <Name>rubberduck_sc_test</Name>
      <LocalLocation>C:\Dev\VBA\Rubberduck-Repos\rubberduck_sc_test</LocalLocation>
      <RemoteLocation>https://github.com/retailcoder/rubberduck_sc_test</RemoteLocation>
    </Repository>
    <Repository>
      <Name>VBAProject</Name>
      <LocalLocation>C:\Dev\VBA\Rubberduck-Repos\rubberduck_sc_test</LocalLocation>
      <RemoteLocation />
    </Repository>
    <Repository>
      <Name>VBAProject</Name>
      <LocalLocation>C:\Dev\VBA\Rubberduck-Repos\rubberduck_sc_test</LocalLocation>
      <RemoteLocation />
    </Repository>
    <Repository>
      <Name>VBAProject</Name>
      <LocalLocation>C:\Dev\VBA\Rubberduck-Repos\rubberduck_sc_test</LocalLocation>
      <RemoteLocation />
    </Repository>
    <Repository>
      <Name>TestRepo2</Name>
      <LocalLocation>C:\Dev\VBA\Rubberduck-Repos\TestRepo2</LocalLocation>
      <RemoteLocation>https://github.com/retailcoder/TestRepo2</RemoteLocation>
    </Repository>
    <Repository>
      <Name>VBAProject</Name>
      <LocalLocation>C:\Dev\VBA\Rubberduck-Repos\TestRepo2</LocalLocation>
      <RemoteLocation />
    </Repository>
    <Repository>
      <Name>VBAProject</Name>
      <LocalLocation>C:\Dev\VBA\Rubberduck-Repos\TestRepo2</LocalLocation>
      <RemoteLocation />
    </Repository>
  </Repositories>

**Comment by INOPIAE** [comment]
good point

**Comment by Hosch250** [comment]
I disagree.  Someone might want to open an already-existing repository.  It probably won't be laid out RD-style, but they still might want to.  I would prefer just setting the initial location to the default repo location.

**Comment by retailcoder** [comment]
@Hosch250 fine. Is there a way to open up that SC config file from the settings dialog or something?

**Comment by rubberduck203** [comment]
#3758
