### ISSUE TITLE
Extract Method refactoring needs thorough testing

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#1225]
This refactoring is currently covered by exactly one, basic-basic-basic test, and it's one of the most complex refactorings we have... and I don't think I touched that code since, ....v1.3 or so.

We need tests that validate that...

 - When the selection is invalid (i.e. does not start in the same member it's ending in), `ExtractMethodPresenterFactory` returns a `null` presenter.
 - When a local variable/constant is only used within the selection, its declaration is moved to the extracted method
 - When a local variable/constant is only used before the selection, its declaration remains where it was
 - When a local variable/constant is only used after the selection, its declaration remains where it was
 - When a local variable/constant is used before and within the selection, it's considered an input
 - When a local variable/constant is used after and within the selection, it's considered an output
 - When there is no output needed, refactoring extracts a `Sub`
 - When there is only one possible output, refactoring extracts a `Function` and returns that value/reference
 - When the return value is a reference, the return assignment is `Set`
 - When there are multiple possible outputs, refactoring extracts a `Function` and returns whichever selected output the user selected; other outputs are `ByRef` parameters
 - When the selection contains a line label that is referred to before the selection, the selection should be deemed invalid. This rules out extracting `ErrHandler` subroutines and avoids having to deal with `Return` and `Resume` statements.
 - When the selection contains a line label that is only referred to within the selection, the line label and its reference(s) should be moved to the new method.

There's probably more to cover, but that would already be **much** better than the one happy-see-it-works test we have now.

**Comment by grleachman** [comment]
Current Extract Method isn't working.

for  
```
    Private Sub Foo()
        Dim x As Integer
        x = 1 + 2
    End Sub
```
The method currently generates

```
Private Sub Foo()
    x = Bar()
End Sub

Private Function Bar() As Integer
    Dim x As Integer
    x = 1 + 2
    Bar = x
End Function
```
This doesn't leave the dim of x
`    Dim X as integer`
in Foo()


for 
```
Option Explicit
Private Sub Foo()
    Dim x As Integer
    x = 1 + 2
End Sub
```
it generates
```
Option Explicit
Private Sub Foo()
    x = Bar()
    x = 1 + 2
End Sub

Private Function Bar() As Integer
    Dim x As Integer
    Bar = x
End Function
```
which is totally wrong.



2 possible correct options are  (ignoring caps)
```
Private Sub Foo()
   Dim x as integer
   x = Bar()
end Sub
private function Bar() as Integer
    dim x as integer
    x = 1 + 1
    Bar = x
end function
```
or; easier to generate
```
Private Sub Foo()
   Dim x as integer
   Bar(x)
end Sub
private sub Bar(byref x as integer)
    x = 1 + 2
end function
```

**Comment by Hosch250** [comment]
@grleachman Can you add unit tests for all major cases you find, both ones that work and ones that fail?

**Comment by grleachman** [comment]
TDD demands that you define what you want to happen before you write any application code.

**Comment by retailcoder** [comment]
@grleachman it's a bit hard to see what selections you're working with.

    Private Sub Foo()
        Dim x As Integer
        x = 1 + 2
    End Sub

Selecting the `x = 1 + 2` line seems to work fine in the preview box; the default `(none)` return value makes sense, since the method isn't used anywhere.

However you're correct, it removes the declaration for `x`, because `x` ends up being only used in the extracted scope:

    Private Sub Foo()
        Foo_1 x
    End Sub
    
    Private Sub Foo_1(ByVal x As Integer)
    
        x = 1 + 2
    End Sub

Which is wrong... but then, the original code was nonsense, too. Let's try extracting `x = 1 + 2` here:

    Private Sub Foo()
        Dim x As Integer
        x = 1 + 2
        Debug.Print x
    End Sub

If we leave it the suggested default (return `x`), we get this:

    Private Sub Foo()
        Dim x As Integer
        x = Foo_1()
        Debug.Print x
    End Sub
    
    Private Function Foo_1() As Integer
        x = 1 + 2
        Foo_1 = x
    End Function
    
If we change the suggested return value to `(none)`, we get this:

    Private Sub Foo()
        Dim x As Integer
        Foo_1 x
        Debug.Print x
    End Sub
    
    Private Sub Foo_1(ByRef x As Integer)
        x = 1 + 2
    End Sub

I can concede that there's a bug when the original declaration is removed and the refactoring actually breaks the code, but other than that it seems to work as specified for me - this point:

> *When a local variable/constant is only used within the selection, its declaration is moved to the extracted method*

Should be amended to say "unless the local variable/constant is also passed as a parameter to the extracted method" - I *think* that would solve it. Thoughts?

**Comment by grleachman** [comment]
My preference would to do a first iteration of a simple version that implements an `Action<type,returnType>` style

```
private Sub(Byref returnValue)
private Sub(byval inputValue1, byref returnValue)
private Sub(byval inputValue1, inputValue2, byref returnValue)

```
get the logic for that right.

Once that parses, then think about the next step.
if there are 2 out params though.. eg (over simplified)
```

public sub foo(byval z as integer)
    Dim x as integer
    Dim y as integer    
    x = z mod 7
    y = x * 4
    Debug.Print x, y
end sub
```

goes to

```
public sub foo(byval z as string)
    Dim x as integer
    Dim y as integer    
    call bar (z, x, y)
    Debug.Print x, y
end sub
public sub bar(byval z as integer, byref x as integer, byref y as integer)
    x = z mod 7
    y = x * 4
end sub
```

then you'd have to think carefully about how to use a function that can only return a single value.

**Comment by grleachman** [comment]
Tests are now breaking out a little 

ValidateSelectionTests (injected into CanExecute)

- When the selection is invalid (i.e. does not start in the same member it's ending in),ExtractMethodPresenterFactory returns a null presenter.
- When the selection is invalid is a deep topic itself... using the parser, I'm hoping to boil it down to a limited category of "When Selection not contained in a single block.", plus a few minor others 


Currently not required as all extracted methods are extracted as private Sub(byref ... )

- When there is no output needed, refactoring extracts a Sub
- When there is only one possible output, refactoring extracts a Function and returns that value/reference
- When the return value is a reference, the return assignment is Set
- When there are multiple possible outputs, refactoring extracts a Function and returns whichever selected output the user selected; other outputs are ByRef parameters


ExtractMethodModelTests

- When a local variable/constant is only used within the selection, its declaration is moved to the extracted method
- When a local variable/constant is only used before the selection, its declaration remains where it was
- When a local variable/constant is only used after the selection, its declaration remains where it was
- When the selection contains a line label that is only referred to within the selection, the line label and its reference(s) should be moved to the new method.
- When a local variable/constant is used before and within the selection, it's considered an input
- When a local variable/constant is used after and within the selection, it's considered an input
- When the selection contains a line label that is referred to before the selection, the selection should be deemed invalid. This rules out extracting ErrHandler subroutines and avoids having to deal with Return and Resume statements.



Side effects so far : ObsoleteUseOfCall needs to be removed.

**Comment by grleachman** [comment]
Oh no!!
public sub myOneLineSub : dim x as string : x = "nogo" : end sub

selection = "x = \"nogo\"

extract refatoring....
YUK

**Comment by retailcoder** [comment]
@grleachman hmm right.. multiple instructions in the same line, if you want to deal with that (otherwise just treat it as an invalid selection), would have to be valid only when a whole instruction (or `ValueStmt`?) is selected; surgically replacing part of the parse tree for this would require using a `TokenStreamRewriter`, which you can get from the parser state for the module you're in (the parser keeps the parse trees in the parser state specifically for this). As of now only the *rename* refactoring is using it I think.

**Comment by grleachman** [comment]
I'm discounting it for now, when I've got standard code refactoring properly, then I'll worry about edge cases. But first I need to worry about condition blocks and loop blocks and internal exits.
I'll cover the basic tests, then move onto something else, but raise an issue for the esoteric.

**Comment by retailcoder** [comment]
Good catch with internal `Exit` statements - I completely forgot to handle those.

**Comment by grleachman** [comment]
Loads of interesting code written. Useful to explorer some basics of Rubberduck, but I'm going to park this work for now...
https://github.com/grleachman/Rubberduck/tree/extractMethodRefactoring_Testing

**Comment by retailcoder** [comment]
Closing this issue, testing and coverage for this refactoring is now well above the standard - well done @grleachman! #1599 is really all that's left to do, and I don't really see it as a showstopper.
