### ISSUE TITLE
Port AccUnit tests to Rubberduck

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#1227]
ref. #856, AccUnit tests live in dedicated class modules, and contain signature boilerplate code (and project reference) that we can use to automatically detect whether a VBA project contains AccUnit tests: AccUnit test classes must implement a specific class/interface, and we can detect that easily.

We would need to refer to the AccUnit documentation for a complete syntax check, but this:

    Public Sub basUtility_GetLowestNumber_Test1()
        Assert.That GetLowestNumber(3, 4), Iz.EqualTo(3)
    End Sub

Would translate to this:

    '@TestMethod
    Public Sub basUtility_GetLowestNumber_Test1()
        Assert.AreEqual 3, GetLowestNumber(3, 4)
    End Sub

And this:

    ' AccUnit:Row(3,4,3).Name = "Smaller first"
    ' AccUnit:Row(4,3,3).Name = "Larger first"
    ' AccUnit:Row(3,3,3).Name = "Equal"
    ' AccUnit:Row(3.002,3.6,3.003).Name = "Decimals"
    ' AccUnit:Row(-3,3,-3).Name = "Mixed sign"
    ' AccUnit:Row(-7,-3,-7).Name = "Negative"
    Public Sub basUtility_GetLowestNumber_RowTest(Num1 As Double, Num2 As Double, Expected As Double)
        Assert.That GetLowestNumber(Num1, Num2), Iz.EqualTo(Expected)
    End Sub

Would translate to this:

    '@TestMethod
    Public Sub basUtility_GetLowestNumber_RowTest_SmallerFirst()
        Assert.AreEqual 3, GetLowestNumber(3, 4)
    End Sub

    '@TestMethod
    Public Sub basUtility_GetLowestNumber_RowTest_LargerFirst()
        Assert.AreEqual 3, GetLowestNumber(4, 3)
    End Sub

    '@TestMethod
    Public Sub basUtility_GetLowestNumber_RowTest_Equal()
        Assert.AreEqual 3, GetLowestNumber(3, 3)
    End Sub

    '@TestMethod
    Public Sub basUtility_GetLowestNumber_RowTest_Decimals()
        Assert.AreEqual 3.002, GetLowestNumber(3.6, 3.003)
    End Sub

    '@TestMethod
    Public Sub basUtility_GetLowestNumber_RowTest_MixedSign()
        Assert.AreEqual -3, GetLowestNumber(3, -3)
    End Sub

    '@TestMethod
    Public Sub basUtility_GetLowestNumber_RowTest_Negative()
        Assert.AreEqual -7, GetLowestNumber(-3, -7)
    End Sub

Optionally, we could prefix the new test methods with the word `Test`, or verify that the AccUnit methods don't already have it, and then omit the `@TestMethod` attribute.

**Comment by retailcoder** [comment]
Also, `' AccUnit: Ignore` comments should translate to a `'@TestIgnore` annotation. (ref. #1226)

**Comment by retailcoder** [comment]
Some AccUnit attributes are contrary to the philosophy of Rubberduck and *unit testing* in general - e.g. `AccUnit: Rollback` indicates an integration test and poorly decoupled data access components. That attribute will have no support in Rubberduck.

`AccUnit: ClickingMsgBox` has the same problem, indicates an integration test and poorly decoupled presentation concerns. That attribute will have no support in Rubberduck either.

Also `AccUnit: TestRelated` would serve no purpose in Rubberduck.

`AccUnit: TestClass` would be `'@TestModule`.

**Comment by joyfullservice** [comment]
I totally agree on the principle of not using comments to build test cases, but the real strength of AccUnit was the simplicity and readability of having everything inline. Here is an example of another testing function I was working on recently:


```
'---------------------------------------------------------------------------------------
' Procedure : basRules_CalculateBilling
' Author    : Adam Waller
' Date      : 3/17/2016
' Purpose   : Verify billing rules for various pricing combinations
'---------------------------------------------------------------------------------------
'
' AccUnit:Row("A166371",1,"Normal","Lunch",True,5,166371,127881).Name="Regular lunch benefit meal for employee"
' AccUnit:Row("A166371",1,"Normal","Dinner",False,94,166371,166371).Name="Regular dinner meal for employee"
' AccUnit:Row("A166371",1,"Normal","Lunch",False,5,166371,166371).Name="Lunch non-benefit meal for employee"
' AccUnit:Row("A166371",1,"Normal","Lunch",True,5,166371,127881).Name="Lunch benefit meal during event for employee"
' AccUnit:Row("A166371",1,"Normal","Breakfast",True,1,166371,127881).Name="Monday breakfast for employee"
' AccUnit:Row("A166371",1,"Cold Breakfast","Breakfast",False,112,166371,166371).Name="Tuesday breakfast for employee"
' AccUnit:Row("A16zd6371",1,"Cold Breakfast","Breakfast",False,113,0,0).Name="Invalid account number"
' AccUnit:Row("",1,"Cold Breakfast","Breakfast",False,113,0,0).Name="No account number"
Public Sub basRules_CalculateBilling(strCardID As String, intQuantity As Integer, strMealType As String, strMealCode As String, blnIsBenefit As Boolean, _
        lngExpPriceID As Long, lngExpAccount As Long, lngExpBillAccount As Long)
    
    Dim dbs As DAO.Database
    Dim rst As DAO.Recordset
    Dim strSQL As String
    Dim lngID As Long
    
    ' Add meal record
    Set dbs = CodeDb
    Set rst = dbs.OpenRecordset("tblMeal", dbOpenDynaset)
    With rst
        .AddNew
            !ImportID = 999999999
            !CardID = strCardID
            !Quantity = intQuantity
            !MealType = Nz(DLookup2("ID", "tblMealType", "MealType='" & strMealType & "'"), 0)
            !MealCode = Nz(DLookup2("ID", "tblMealCode", "MealCode='" & strMealCode & "'"), 0)
            !MealDate = Date
            !IsBenefit = blnIsBenefit
        .Update
        .Bookmark = .LastModified
        lngID = !ID
            
        ' Calculate billing
        CalculateBilling lngID
        
        ' Verify results
        Assert.AreEqual lngExpPriceID, !PriceID, "Wrong Price ID"
        Assert.AreEqual lngExpAccount, !AccountNumber, "Wrong account number"
        Assert.AreEqual lngExpBillAccount, !BillAccount, "Wrong billing account"
                
        ' Clean up
        .Delete
        .Close
    End With
    Set rst = Nothing
    
End Sub
```

The above routine runs three different assertions on eight input combinations to test different rules. Using AccUnit, only 8 lines of code are needed to test these combinations, along with a friendly description about what failed.

From what I am seeing in Rubberduck, would I actually need about 100 lines to produce the same effect as the 8 lines above? Or is there a way to create a wrapper "runner" that would run a series of very similar tests without all the additional "overhead"?

Perhaps the `Assert` methods could include an optional comment description parameter so you could add a note about the particular test. Something like the following:


```
'---------------------------------------------------------------------------------------
' Procedure : TestRunner
' Author    : Adam Waller
' Date      : 3/21/2016
' Purpose   : Run unit tests on billing rules
'---------------------------------------------------------------------------------------
'
Public Sub TestRunner()

    Assert.Pass basRules_CalculateBilling("A166371", 1, "Normal", "Lunch", True, 5, 166371, 127881, "Regular lunch benefit meal for employee")
    Assert.Pass basRules_CalculateBilling("A166371", 1, "Normal", "Dinner", False, 94, 166371, 166371, "Regular dinner meal for employee")
    Assert.Pass basRules_CalculateBilling("Normal", "Lunch", False, 5, 166371, 166371, "Lunch non-benefit meal for employee")
    ' (etc...)

End Sub
```

Just thinking through ideas on how to make the testing as clean and readable as possible when moving from AccUnit to Rubberduck...  :-)

**Comment by retailcoder** [comment]
@joyfullservice all `Rubberduck.AssertClass` methods *do* provide an optional `message` parameter that is displayed in the *test explorer* when the assertion fails - the syntax seems identical here.

I think 100 lines is being outright unfair here - you have 8 calls, each are one-liners - that makes 8 test methods, each with a one-liner body, so 8 "significant" lines. I only put the `'@TestMethod` annotation there to preserve the original naming, but by convention any method that starts with "Test" doesn't need an annotation.

I have to strongly disagree that having a blob of values in comments, without IntelliSense to tell you what argument is for which parameter, is more readable than 8 distinct methods to do the same thing.

As for the "runner"... as I said before, nothing forbids doing this:

    Public Sub TestCalculateBilling() 'this is the test method
        CalculateBilling "A166371",1,"Normal","Lunch",True,5,166371,127881, "Regular lunch benefit meal for employee"
        CalculateBilling "A166371",1,"Normal","Dinner",False,94,166371,166371, "Regular dinner meal for employee"
        '...
    End Sub

    Private Sub CalculateBilling(strCardID As String, intQuantity As Integer, strMealType As String, strMealCode As String, blnIsBenefit As Boolean, _
        lngExpPriceID As Long, lngExpAccount As Long, lngExpBillAccount As Long, testDesc As String)
    
        '...

        'Rubberduck syntax is identical here:
        Assert.AreEqual lngExpPriceID, !PriceID, testDesc & ": Wrong Price ID"
        Assert.AreEqual lngExpAccount, !AccountNumber, testDesc & ": Wrong account number"
        Assert.AreEqual lngExpBillAccount, !BillAccount, testDesc & ": Wrong billing account"

        '...

    End Sub

That will give you 1 test that does a truckload of things and have at least 24 reasons for failing, which is against all best practices in testing.. not to mention that a unit test that's accessing a database, isn't a *unit test* in the first place.

The logic of `CalculateBilling` should be decoupled from the database and the tests should be able to provide it with dummy values without having to hit the db at all.

**Comment by Vogel612** [comment]
What's missing here is a proper way to Parameterize Unit-Tests.

It might be interesting to look into something like a `@DataProvider` that gives us a way to compactly define test runs with parameters and expected outcomes without moving them into some kind of comments

**Comment by retailcoder** [comment]
Ok, so I did my homework, and researched parameterized tests a bit... sorry for the knee-jerk reaction @joyfullservice. Seems AccUnit is modeled to feel like NUnit tests. Rubberduck unit tests are modeled to feel like MS-Test.

In the MS-Test world, what we're looking at here, is a *data-driven test* - similar to what @Vogel612 mentioned... and it's basically moving the parameters/data away from the code/comments, and into a XML or CSV file... or a database. The test remains parameterless, but accesses a `TestContext` object that exposes the data, wherever it came from.

While I personally don't see any benefits in doing this, I can understand someone else might - I'll close/decline this issue: Rubberduck will not *automatically "port" AccUnit tests*, not by parsing the comments and generating test methods.

Instead, I'll create a new issue to support *data-driven tests*, and make it [up-for-grabs].

**Comment by retailcoder** [comment]
@joyfullservice take a look at linked #1229 - taking your example above, a data-driven Rubberduck unit test might look like this - notice the comment boilerplate is gone - assuming there's a `BillingTestData` table in your Access database that contains the test data.

	'@DataSource "Rubberduck.TestDataSource.Access", "ThisDatabase", "BillingTestData"
	Public Sub TestCalculateBilling()

		Dim dbs As DAO.Database
		Dim rst As DAO.Recordset
		Dim strSQL As String
		Dim lngID As Long

		' Add meal record
		Set dbs = CodeDb
		Set rst = dbs.OpenRecordset("tblMeal", dbOpenDynaset)
		With rst
			.AddNew
				!ImportID = 999999999
				!CardID = TestContext.DataRow("CardID")
				!Quantity = TestContext.DataRow("Quantity")
				!MealType = Nz(DLookup2("ID", "tblMealType", "MealType='" & TestContext.DataRow("MealType") & "'"), 0)
				!MealCode = Nz(DLookup2("ID", "tblMealCode", "MealCode='" & TestContext.DataRow("MealCode") & "'"), 0)
				!MealDate = Date
				!IsBenefit = TestContext.DataRow("IsBenefit")
			.Update
			.Bookmark = .LastModified
			lngID = !ID

			' Calculate billing
			CalculateBilling lngID

			' Verify results
			Assert.AreEqual TestContext.DataRow("ExpPriceID"), !PriceID, "Wrong Price ID"
			Assert.AreEqual TestContext.DataRow("ExpAccount"), !AccountNumber, "Wrong account number"
			Assert.AreEqual TestContext.DataRow("ExpBillAccount"), !BillAccount, "Wrong billing account"

			' Clean up
			.Delete
			.Close
		End With
		Set rst = Nothing

	End Sub

Thoughts?

**Comment by joyfullservice** [comment]
@retailcoder - Thanks for the constructive comments. I know I have much to learn on the unit testing side of things, and exploring the concept of Data-Driven Testing has been a helpful and educational experience. Thanks for pointing me in the right direction.  :-)

One of my main goals here is efficiency. We use VBA (mostly in Microsoft Access) for most of our inhouse development work because we have found it to be a rapid development environment that enables us to integrate with other systems without needing to hire professional programmers. (Software development is not our primary mission.)

I don't set up testing for everything I do, but when I have systems that are more complex, or data models that other systems are depending on, that is where I have been doing more unit testing. I would guess that much of our target audience with Rubberduck is going to be that middle range. More than just recording macros in Excel, but not necessarily your hard-core system architects either. 

To meet that need effectively, unit testing needs to be simple and straightforward. Easy to set up, and easy to run. If it's too complex, then most people simply won't use it. That's what I like about the Rubberduck approach. It hits that sweet spot of running test in an intuitive way without requiring too much development overhead.

As we look at the options for Data-Driven Testing, it would probably be good to have some options that are very simple (such as Dictionary objects) where people can load data sets with a few lines of code, while at the same time providing the more scaleable options of persistent XML data sets and database tables for those that want to go to that extent.

Thanks again for the great work!!

**Comment by retailcoder** [comment]
I'm not sure about a dictionary. The issue is that the data structure will need to be marshaled through COM interop and be iterated/accessed by managed (.net) code for this to work. I think a 2D array would be the best compromise here, being relatively easy to set up in plain VBA code, and can be passed to the `TestContext` instance through COM interop relatively easily too.

**Comment by peterennis** [comment]
@retailcoder, +1 on this:
'@DataSource "Rubberduck.TestDataSource.Access", "ThisDatabase", "BillingTestData"

Seems it would also be portable to Excel using VLookup/HLookup with a worksheet of defined data.
