### ISSUE TITLE
Opening a working directory systematically creates a new entry in the SC config file

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#1232]
Just to document the behavior - I've fixed this issue in my fork already.. more SC fixes to come.

**Comment by INOPIAE** [comment]
Did you think of a cleanup routine for the existing SC config files?

**Comment by retailcoder** [comment]
Nope. Plain deleting the file should "clean" it good :smiley:

**Comment by INOPIAE** [comment]
I do not observe this behaviour anymore. I am currently using 3d7d0bc.
