### ISSUE TITLE
How to trigger Source Control refresh for multiple projects?

### ISSUE THREAD

**Issue by scorchio** [rubberduck-vba/Rubberduck#1235]
I'm not using the built-in Source Control functionality to full extent, as I'm comfortable with using my desktop Git client. I would like to be able to call Source Control's "Refresh pending changes" functionality on multiple projects (3-5) at the same time. Is it possible to do this somehow?

**Comment by retailcoder** [comment]
@ckuhn203 @Hosch250  that one's for you - I believe the SC panel is only working off the active project, not sure how it handles multiple projects at all.

**Comment by Hosch250** [comment]
I'm not sure either.

**Comment by Hosch250** [comment]
Source control only works off one project at a time, and it is unlikely it will be changed until 2.1 at a minimum--this will be difficult UI-wise because we only have one window; even just refreshing the window every time the active project changed would be difficult.  You can have other projects open, and, AFAICT, it does only pick up changes to one of the projects.

**Comment by ckuhn203** [comment]
@scorchio are you doing this through the COM API? I may have a solution if you're using the library. Like Hosch alluded to, getting this into the GUI will be challenging.

**Comment by scorchio** [comment]
For now I would be fine if I could trigger this somehow from code, if it's possible to specify a project which ends up being refreshed then it's fine.

**Comment by ckuhn203** [comment]
We've exposed the API, but it feels like it's missing what you need. 

https://github.com/rubberduck-vba/Rubberduck/wiki/Source-Control-API

https://github.com/rubberduck-vba/Rubberduck/blob/next/Rubberduck.SourceControl/GitProvider.cs

https://github.com/rubberduck-vba/Rubberduck/blob/next/Rubberduck.SourceControl/SourceControlProviderBase.cs

Currently, the only way to refresh the file system through the API is to either Pull from a remote, or to Checkout a branch. I didn't anticipate this usecase. What we *should* do is push some of the Refresh code down from the UI into the lib, but I won't even pretend I have time to do that right now.

**Comment by rubberduck203** [comment]
#3758
