### ISSUE TITLE
Expose Ready parser state event to COM API, to work with BeginParse 

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#1239]
Have the parser state raise a `Ready()` event when the parsing/resolving completes to `Ready` state, and make it possible for VBA code to handle ready state in an event handler.

**Comment by retailcoder** [comment]
This is currently implemented (states `Ready`, `Error` and `Parsed` are exposed through events), but not working (see http://stackoverflow.com/q/36213087/1188513).

**Comment by retailcoder** [comment]
The COM events must simply be invoked from the UI thread - the code is otherwise perfectly fine.

**Comment by Hosch250** [comment]
What's the status on this? Also, is there any way to make it fire with an argument for the user to analyze since we have so many interesting parser states now?

**Comment by retailcoder** [comment]
@Hosch250 status is unchanged: the event handler isn't invoked from the thread that the VBA code registered from, so handlers are `null` and no event gets raised.
