### ISSUE TITLE
Parser Error: Line Continuation with Parens

### ISSUE THREAD

**Issue by dimitrimitropulos** [rubberduck-vba/Rubberduck#1242]
In a new module, type the following

```
Public Sub testParens()

Dim x As Integer

x = ( _
        1 / _
        1 _
    ) * 1

End Sub
```

which yields a parser error due to the last line continuation (on the "1 _" line)

**Comment by autoboosh** [comment]
Fixed with https://github.com/rubberduck-vba/Rubberduck/pull/1255.
