### ISSUE TITLE
Resolver Error: With Block

### ISSUE THREAD

**Issue by dimitrimitropulos** [rubberduck-vba/Rubberduck#1243]
The following code works:

```
Private Function GetPathFromFileDialog() As String
    Application.FileDialog(msoFileDialogFilePicker).Show
    GetPathFromFileDialog = Application.FileDialog(msoFileDialogFilePicker).SelectedItems(1)
End Function
```

while putting the object in a with block yields a resolver error:

```
Private Function GetPathFromFileDialog() As String
    With Application.FileDialog(msoFileDialogFilePicker)
        .title = "Rubberduck is super awesome!"
        .Show
        GetPathFromFileDialog = .SelectedItems(1)
    End With
End Function
```

The context this bug was found had many more things going on within the with block, but as far as I can tell, this is the most concise way to elicit the error.

**Comment by retailcoder** [comment]
Oh wow, see this `matches.Single()` assumption here?

            result = matches.Where(item => IsBuiltInDeclarationInScope(item, localScope)).ToList();
            if (result.Count == 1 && !SpecialCasedTokens.Contains(matches.Single().IdentifierName))
            {
                return result.SingleOrDefault();
            }

Turns out, there are 804 matches for the `Application` identifier. Not quite the unique snowflake huh!
