### ISSUE TITLE
Resolver Error: ReDim Array with Constant

### ISSUE THREAD

**Issue by dimitrimitropulos** [rubberduck-vba/Rubberduck#1244]
The following code works fine

```
Private Sub SomeSub()
    Dim someArray() As Byte
    ReDim someArray(32)
End Sub

```

while the following code is a Resolver Error

```
Private Const SOME_CONSTANT As Byte = 32
Private Sub SomeSub()
    Dim someArray() As Byte
    ReDim someArray(SOME_CONSTANT)
End Sub
```

---

For reference (and context) here were the original offending lines:

```
Private Const DEFAULT_CAPACITY As Long = 32
Private m_stringBuffer() As Byte

Private Sub Class_Initialize()
    ReDim m_stringBuffer(0 To (DEFAULT_CAPACITY * 2) - 1) 'Each unicode character is 2 bytes
End Sub
```

taken from [here about an attempt at a VBA StringBuilder](http://codereview.stackexchange.com/questions/67596/a-lightning-fast-stringbuilder)

**Comment by retailcoder** [comment]
Side note, that `StringBuilder` class is more than just an "attempt" :wink:
