### ISSUE TITLE
Parser Error: Fixed Length String

### ISSUE THREAD

**Issue by dimitrimitropulos** [rubberduck-vba/Rubberduck#1245]
The following yields the parser error: "no viable alternative at input '255'"

```
Sub FixedLengthString()
    Dim someString As String * 255
End Sub
```

Chip has a [good explanation](http://www.cpearson.com/excel/sizestring.htm) of the usage of this, as always

**Comment by Vogel612** [comment]
This should actually work... let's check with the grammar:

    asTypeClause : AS WS? (NEW WS)? type (WS? fieldLength)?;
    [...]
    fieldLength : MULT WS? (INTEGERLITERAL | ambiguousIdentifier);

from what I can see that should be covered ... is this from the current [next]?

**Comment by dimitrimitropulos** [comment]
Yes, this was an error in 2.0.0.23839

**Comment by autoboosh** [comment]
Fixed with https://github.com/rubberduck-vba/Rubberduck/pull/1255.
