### ISSUE TITLE
Parser Error: Open "x" for Input As #iFNotAnIfStatement

### ISSUE THREAD

**Issue by dimitrimitropulos** [rubberduck-vba/Rubberduck#1247]
The error "mismatched input 'ile' expecting WS" happens for the following code:

```
Sub FileTest()
    Open "TESTFILE" For Input As #iFile
    Close #iFile
End Sub
```

If I am right, the `#iF` portion is being interpreted as an `if` statement.  Changing `#iFile` to `#File` works as a temporary workaround.

can you guys make a tag for #TheGloriousAndConfusingBugsThatResultFromUsingDefTypes

**Comment by Vogel612** [comment]
actually this looks like an error in the preprocessing code where conditional compilation is "executed" because it breaks the parser otherwise

**Comment by retailcoder** [comment]
I made a tag for [preprocessing] instead :smiley:

**Comment by dimitrimitropulos** [comment]
I should probably add that the same error holds true for replacing `#iFile` with `#Elsex` or`#ElseIfx`, possibly more.

**Comment by autoboosh** [comment]
Roslyn has the same problem: https://github.com/dotnet/roslyn/issues/4726.

The preprocessor does not know of any VBA language concept besides the conditional compilation keywords (#if/#end if/etc.) that's why code like the above produces an error.

Not quite sure how to handle this though, the easiest way would be to forbid code like this.

**Comment by retailcoder** [comment]
Would there not be a way to avoid matching `#If` when there's anything but whitespace before the token on the line? Preprocessor instructions need to be first on a line, right?

**Comment by autoboosh** [comment]
Not quite sure, will give it a try.

**Comment by autoboosh** [comment]
Found a solution to this, already tested locally but haven't had time to make a PR yet.

**Comment by autoboosh** [comment]
This should be fixed with https://github.com/rubberduck-vba/Rubberduck/pull/1429.
