### ISSUE TITLE
Small adjustment for new test method

### ISSUE THREAD

**Issue by INOPIAE** [rubberduck-vba/Rubberduck#1254]
Should the phrase in line 19 NewTestMethodCommand.cs 

"Public Sub ", NamePlaceholder, "() 'TODO Rename test\n",

not better be  "...'TODO: Rename..."  with a colon after TODO so that it is automaticly shows up in the ToDo - Explorer.

**Comment by retailcoder** [comment]
The default TODO marker was changed to `TODO WS`, so it shouldn't matter. I'm starting to think we should either not bother trying to delimit the marker at all, or introduce some regex to force it to match at the beginning of a comment or delimited with `\b` (word boundary) ...but it might not be worth it.

**Comment by INOPIAE** [comment]
Should the texts "Test raised an error" and "Expected error was not raised." be translated so the text in the test result is not bilingual by default?

Both texts are located in NewTestMethodCommand.cs as well.

**Comment by Hosch250** [comment]
Discussing whether to change the function of the ToDo explorer is for a different issue.  The issue addressed here is by design.
