### ISSUE TITLE
Missing translation in Source Control explorer 

### ISSUE THREAD

**Issue by INOPIAE** [rubberduck-vba/Rubberduck#1256]
The file status is not translated.
I attached a screenshot in German where the file status is not translated.
![image](https://cloud.githubusercontent.com/assets/2772829/14054259/22b3d6aa-f2d8-11e5-9369-9cd32e449964.png)

**Comment by Hosch250** [comment]
Yup, we are just reading from an enum there.  A converter should do the trick.

**Comment by Hosch250** [comment]
This can display multiple values depending on the action (added and renamed, for example).

**Comment by retailcoder** [comment]
@Hosch250 just like `ParserState` and `DeclarationType` enums, file status enum values *should* have a proper resource. It is *not* by design that enum names we use in-code end up as-is anywhere in the UI.
