### ISSUE TITLE
App.cs does too many things

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#1258]
The constructor speaks for itself:

```
    public App(VBE vbe, IMessageBox messageBox,
        IRubberduckParser parser,
        IGeneralConfigService configService,
        IAppMenu appMenus,
        RubberduckCommandBar stateBar,
        IIndenter indenter,
        IRubberduckHooks hooks,
        IEnumerable<ICommand> appCommands)
```

Dependencies and functionality needs to be factored/regrouped into new classes.

**Comment by Hosch250** [comment]
This is pretty old now.  Is it cleaned up enough to suit you?

**Comment by rkapka** [comment]
Shouldn't this issue be closed?

**Comment by retailcoder** [comment]
@rkapka probably. Just took a quick look, and everything in app.cs looks like it legitimately belongs there.. except perhaps loading legacy indenter settings from the registry, but that wouldn't belong in the indenter assembly (msgbox dependency), or the shared config provider assembly (same reason).
