### ISSUE TITLE
Small access demo app with alternative unit testing framework

### ISSUE THREAD

**Issue by AndrewM-** [rubberduck-vba/Rubberduck#1270]
Instructions are in the zip file.  The form contains all the code for form function and for testing itself.  The other modules just provide generic functions or data structures used by the form.  Some GUI logic is in the form, for example use the lowest category combo only and your selection will be moved to the top combo.  This logic is unit tested.

[CodingPattern.zip](https://github.com/rubberduck-vba/Rubberduck/files/193424/CodingPattern.zip)

**Comment by retailcoder** [comment]
I don't have MS-Access handy, but I'd suggest you put your code up for review on [Code Review](http://www.codereview.stackexchange.com).

**Comment by AndrewM-** [comment]
The risk with RubberDucks method of uncoupling forms form code is that is is confusing for the majority of self-taught VBA developers.  Most of them would have to convert the MVC pattern back to plain old access before they could understand the application.  I have been there myself where I have had a ms-Access application written is some alien style with unbound forms and so on.  So I have found a style that overcomes most of RubberDucks objections.  The application can also be put through VBA RubberDucks parser and code inspector etc as just another test application.

**Comment by autoboosh** [comment]
Sounds interesting but as @retailcoder said, Code Review is probably a better place for your code since more people will see it.

**Comment by AndrewM-** [comment]
Just remember that i am also providing you test data for the rubberduck project as well.

**Comment by AndrewM-** [comment]
I do have an ms-access 2013 license that I could donate to the project if anyone wants to use if confirming vba-rubberduck plays well with ms-access

**Comment by ThunderFrame** [comment]
Thanks for the offer. I have all the Accesses. So I can test all versions.
