### ISSUE TITLE
Parser Errors with conditional compilation directives

### ISSUE THREAD

**Issue by mikesigs** [rubberduck-vba/Rubberduck#1271]
In #827 you mentioned that the parser doesn't handle #If and #Const very well. This is hitting me right now. I am using [VBA-Tools](https://github.com/VBA-tools/VBA-Web) which makes heavy use of these directives, and unfortunately it's breaking the RubberDuck Code Explorer.

To reproduce, download and install the VBA-Tools thing (using the instructions on their page) and open the Code Explorer. There are 5-6 parsing errors that would be helpful to you guys to keep tweaking your grammar.

Hope this helps!

**Comment by retailcoder** [comment]
Thanks for the feedback! That's all handled now, v2.0 is going to be pre-processing (literally *interpreting*) conditional compilation directives, effectively providing the parser with only the "live" code, which fixes the issue - with the only remaining problem of project-wide constants (they're nowhere in the VBIDE API, and nowhere in the code panes either).

**Comment by mikesigs** [comment]
That is great to hear. When might one expect a release of v2.0? Is there any way I can get my hands on it now?

**Comment by retailcoder** [comment]
We're shooting for mid-May :smiley:  ..the current build isn't exactly stable/complete right now, and still missing a couple of features (the *Code Explorer* being perhaps the major one; the parser is being worked on as well, there's an active PR that currently breaks 300-some tests but once that's fixed, will enable multithreaded parsing), but anyway feel free to fork the repo and build the [next] branch (and hey, contribute!) - see the [wiki](https://github.com/rubberduck-vba/Rubberduck/wiki/Contributing) for more details!
