### ISSUE TITLE
Error while opening VBE in Excel

### ISSUE THREAD

**Issue by INOPIAE** [rubberduck-vba/Rubberduck#1273]
Using the commit 6102efc
I run into this error while trying to open the VBE in Excel 2010, Win7
![image](https://cloud.githubusercontent.com/assets/2772829/14141204/fdf6109a-f67d-11e5-9f6f-c39a5e76fb88.png)

**Comment by INOPIAE** [comment]
The problem is not sovled with the latest commit f49d175 .
I use Office 2010 32-bit Win7 32 bit

**Comment by autoboosh** [comment]
Yes, because that's a fix for a different problem. The problem you're experiencing is unrelated to the other one. This one's related to key hook bugs and has to be looked at separately.

**Comment by INOPIAE** [comment]
After the commit 767bfe0 I do not get the crash any more. 
I think this issue is solved.
