### ISSUE TITLE
RubberDuck requires a change case "refactor"

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#1279]
Visual Studio puts the command under Edit..Advanced..Make Uppercase and Make Lowercase.

RubberDuck should allow for changing the case of the selection.

This feature is probably of most use when changing the case of string literals.

**Comment by comintern** [comment]
Worth noting - a peculiarity of VBA is that if you have an identifier with module level scope, changing the case of anything with the same identifier _anywhere_ in the project will change the case of _all_ of them.  I.e., if you have something like this:

```
'Module1
Dim Var As Integer
Private Sub Bar()
    Dim Var As Integer
End Sub

'Module2
Private Sub Foo()
    Dim Var As Integer
End Sub

Private Sub Var()
End Sub

'Class1
Public Property Get Var() As Integer
End Property
```
If you change `Var` to `var` anywhere, all of them change.

**Comment by ThunderFrame** [comment]
Case change propagation is minimized when Option Explicit is used. Then, *only* case changes to the declaration are propagated across scope.
I'm not certain but there might also be some propagation when you call late bound members, but you also have a local member with the same member name. Changing the case of the local member probably changes the case of the late bound member call.

**Comment by retailcoder** [comment]
AFAICT any `foo` will update to `Foo` as soon as any line declaring any `Foo` is parsed by the VBE. `Foo` could be a variable, constant, enum, type, procedure, property -- literally *anything*; the case of the last parsed declaration will be propagated to everything, including built-in / referenced declarations.

**Comment by retailcoder** [comment]
Because the VBE consistently propagates case changes to all declarations, implementing a refactoring for it would be much overkill... this feature would simply be fighting the IDE; declining.

**Comment by ThunderFrame** [comment]
I was thinking more for string literals where case sensitivity is important, like in XML or a shell command, or where case-conventions prefer particular casing, like SQL.

Eg.
```
X = "select * from emp order by 1 asc"
```

The user might want to select and capitalize `select * from` and/or `order by 1 asc`
