### ISSUE TITLE
Problems starting VBE resulting from Hotkeys

### ISSUE THREAD

**Issue by INOPIAE** [rubberduck-vba/Rubberduck#1281]
I am using commit 767bfe0

Each time I start the VBE in Excel I get this error:
![image](https://cloud.githubusercontent.com/assets/2772829/14198978/4a0320d2-f7e0-11e5-8963-a2c1f872e868.png)

First I thought there were no hotkey settings but when I check them I have these settings.
![image](https://cloud.githubusercontent.com/assets/2772829/14199014/9a25c68c-f7e0-11e5-91a8-9b98e2d214d2.png)

Some questions about the hotkeys: 
How can I use the Tab key or similar keys in the Hotkey settings?
What happens if the keys "^",  "+" and "%" are used?

**Comment by retailcoder** [comment]
Try deleting your configuration file, there should be more than 2 hotkey settings. As for keys needing a modifier and possible misconfigurations, .....it's on the user for now (no, tab can't be used)

**Comment by INOPIAE** [comment]
Deleting the config file solved the problem.
The error occured as I only hat two hotkey settings in the old file.

From my point of view the hotkey routine should catch such errors.

Some more thoughts:
Is there a difference of lowercase and uppercase characters for the hotkeys?
There should be a check to avoid to have the same hotkey twice. If I have the same hotkey there is an error when loading rubberduck again.

**Comment by retailcoder** [comment]
This is more of a configuration/settings issue than anything else - currently there's nothing in place to ...prevent the user from doing something stupid.

Also the settings should catch any load error, warn the user, and reset the settings if anything goes wrong loading them - i.e. the config file should be treated as user input, and not trusted to be well-formed.

**Comment by Hosch250** [comment]
@retailcoder What happened to the popup I put in 1.4 for this?

**Comment by INOPIAE** [comment]
Should the Tab key not work with "{TAB}"? 
Rubberduck:Common:Hotkeys.Hotkey private static readonly IDictionary at the end of the file.

When I add this to the Settings I run into an error while loading the VBE.

**Comment by Hosch250** [comment]
I suspect that not accepting `{TAB}` is a feature rather than a bug.

**Comment by Hosch250** [comment]
Is this still an issue?

**Comment by Hosch250** [comment]
At this point, I think I will close this.  We've made enough breaking changes that deleting the config and starting over when they install 2.0 isn't that big of a deal.
