### ISSUE TITLE
VB6 SmartIndenter applies indentation incorrectly for Reserved Words in Type Declarations

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#1286]
The VB6 SmartIndenter has a bug when indenting Type Declarations that include Member names that use reserved words. Specifically, the keywords `Enum`, `Function`, `Sub` and `Type`.

**`Enum` and `Type` are not indented correctly after SmartIndenter runs**
If `Enum` or `Type` is used as a member name, then SmartIndenter does not indent *that* member at all. All other members are indented correctly.
```vb
      'Original code, which is deliberately over-indented
      Private Type MyType
          x1 As Integer
          Enum As Integer
          x2 As Integer
          Type As Integer
          x3 As Integer
      End Type

'Code after SmartIndenter has run
Private Type MyType
    x1 As Integer
Enum As Integer
    x2 As Integer
Type As Integer
    x3 As Integer
End Type
```

**`Function` and `Sub` are not indented correctly after SmartIndenter runs**
If `Function` or `Sub` is used as a member name, then SmartIndenter does not indent *that member and all subsequent members* correctly.

```vb
      'Original code, which is deliberately over-indented
      Private Type MyFuncType
          x1 As Integer
          Function As Integer
          x2 As Integer
          x3 As Integer
      End Type

      Private Type MySubType
          x1 As Integer
          Sub As Integer
          x2 As Integer
          x3 As Integer
      End Type

'Code after SmartIndenter has run
Private Type MyFuncType
    x1 As Integer
Function As Integer
x2 As Integer
x3 As Integer
End Type

Private Type MySubType
    x1 As Integer
Sub As Integer
x2 As Integer
x3 As Integer
End Type
```

**Comment by comintern** [comment]
Does VBA accept _any_ identifier as an Type member?

Private Type Foo
    If As Integer
    Select As Integer
    Split As String
    For As Integer
    Dim As Integer
    Then As Integer
    UBound As Variant
    To As Integer
    Or As Integer
    Case As Integer
End Type

Private Sub WTF()
    Dim Bar As Foo
    
    With Bar
        .UBound = Split(.Split)
        If Not .Then Xor .If Then
            For .For = UBound(.UBound) To .Dim
                Select Case .Select
                    Case .Case
                        .Or = .Or Or .Or + UBound(.UBound)
                End Select
            Next .For
        End If
        Debug.Print .Or
    End With
End Sub

**Comment by ThunderFrame** [comment]
Yes Types are very accommodating.

@retailcoder  - I'm not in sync with Next, but @comintern 's code breaks my parser.

**Comment by comintern** [comment]
LOL! I'm not surprised at all. It breaks my grip on reality too. It does appear to be valid though - compiles and runs.

**Comment by ThunderFrame** [comment]
Actually, thanks to #934 and #973 , and numerous other bug reports, @retailcoder has ironed out many of the problems.

Interestingly, it's only a single line in @comintern 's code that causes the problem, and specifically, it's the use of a Type member as a loop variable that is causing the problem:

```vb
For .For = UBound(.UBound) To .Dim
```
Although there's a chance the `Next` statement is also problematic:
```vb
Next .For
```

Who knew you <s>would want to</s> could use a Type member as a loop variable!

**Comment by comintern** [comment]
Luckily, it only appears to be relevant for Type members.  This doesn't compile:

**Class1.cls:**
```
Private mIndex As Integer

Public Property Get Index() As Integer
    Index = mIndex
End Property

Public Property Let Index(Value As Integer)
    mIndex = Value
End Property
```

**Calling code:**
```
Private Sub Whewww()
    Dim Foo As New Class1
    With Foo
        For .Index = 1 To 10
            Debug.Print .Index
        Next .Index
    End With
End Sub
```

**Comment by autoboosh** [comment]
Nice find. It looks like the for-next-statement only allows identifiers and not as specified l-expressions such as with expressions. I'll have a look :)
