### ISSUE TITLE
VB6 SmartIndenter applies indentation incorrectly for member and variable declarations with line continuations

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#1287]
Line continuations in member and variable declarations are *evil* VBA, but VB6 SmartIndenter doesn't indent them properly.
```vb
'Code before Smart Indentation
      Private Type MyType
          x1 As Integer
          x2 _
          As Integer
          x3 As _
          Integer
          x4 _
          As _
          Integer
          x5 As Integer: _
          x6 As _
          Integer
          x7 As Integer _
          'Comment _
           as _
           integer
      End Type
      
      Sub MySub()
          Dim x1 As Integer
          Dim _
          x2 _
          As Integer
          Dim x3 As _
          Integer
          Dim x4 _
          As _
          Integer
          Dim x5 As Integer: _
          Dim x6 As _
          Integer
          Dim x7 As Integer _
          'Comment _
          as _
          integer
      End Sub
```

Notice the indentation of continued-lines, and the indentation of the `End Type` and `End Sub` statements.

```vb
'Code after indentation
Private Type MyType
    x1 As Integer
    x2 _
            As Integer
    x3 As _
            Integer
    x4 _
            As _
            Integer
    x5 As Integer: _
            x6 As _
            Integer
    x7 As Integer _
    'Comment _
     as _
     integer
        End Type

Sub MySub()
    Dim x1 As Integer
    Dim _
            x2 _
            As Integer
    Dim x3 As _
            Integer
    Dim x4 _
            As _
            Integer
    Dim x5 As Integer: _
            Dim x6 As _
            Integer
    Dim x7 As Integer _
    'Comment _
     as _
     integer
        End Sub
```

**Comment by autoboosh** [comment]
I have volunteered to implement the indentation feature.

What indentation would you expect in this case?

**Comment by ThunderFrame** [comment]
I have the `Align continued strings and parameters` setting set to `Unchecked`, so the implied indentation is 8-spaces for continued lines, regardless of the multi-statement `:` syntax. i.e. The 8-spaces is not user-configurable.

```vb
Option Explicit

Sub MySub1()
'With `Align continued strings and parameters` setting set to `Unchecked`
    Dim x1 As _
            Integer: _
            Dim x2 As _
            Integer
End Sub

Sub MySub2()
'With `Align continued strings and parameters` setting set to `Checked`
    Dim x1 As _
        Integer: _
        Dim x2 As _
            Integer
End Sub
```
So, the indentation of line-breaks is perhaps by-design, although the hard-coded `8-spaces` is *probably* 2*`4-spaces` which is the default indent - see #1290

But the treatment of the `End Sub` and `End Type` are not ideal, and it seems to be the trailing multi-line comment that breaks it.

```vb
'With `Align continued strings and parameters` setting set to `Checked`
Option Explicit

Sub MySub1()
    Dim x7 As Integer _
    'Comment foo _

    End Sub

Sub MySub2()
    Dim x7 As Integer _
    'Comment _
    foo
End Sub
```

```vb
'With `Align continued strings and parameters` setting set to `Unchecked`
Option Explicit

Sub MySub1()
    Dim x7 As Integer _
    'Comment foo _

     End Sub

        Sub MySub2()
    Dim x7 As Integer _
    'Comment _
     foo
        End Sub
```
And it gets even stranger when you reverse the order of those `Subs`. Note the `Option Explicit` *only* gets indented on the *second* pass of SmartIndenter (bizarrely, this is only reproducible if you swap the order of the Subs back to `MySub1`, `MySub2`, and then back to `MySub2`, `MySub1`).

```vb
'With `Align continued strings and parameters` setting set to `Unchecked`
        Option Explicit

Sub MySub2()
    Dim x7 As Integer _
    'Comment _
     foo
        End Sub

Sub MySub1()
    Dim x7 As Integer _
    'Comment foo _

     End Sub
```

**Comment by comintern** [comment]
@ThunderFrame - Do you want to test this against my last commit ([491e3fe](https://github.com/rubberduck-vba/Rubberduck/commit/491e3fe137207ae77e1561c6cba01e2bf28766da))?  I'm getting reasonable results, but I guess I'm not sure exactly what you expect to see (other than the End Sub not getting shoved to the right):

```
Private Type MyType
    x1 As Integer
    x2 _
    As Integer
    x3 As _
            Integer
    x4 _
    As _
    Integer
    x5 As Integer: _
            x6 As _
            Integer
    x7 As Integer _
            'Comment _
    as _
    integer
End Type

Sub MySub()
    Dim x1 As Integer
    Dim _
    x2 _
    As Integer
    Dim x3 As _
            Integer
    Dim x4 _
    As _
    Integer
    Dim x5 As Integer: _
            Dim x6 As _
            Integer
    Dim x7 As Integer _
            'Comment _
    as _
    integer
End Sub
```

**Comment by comintern** [comment]
Interestingly, the SmartIndenter isn't the only thing that has problems with your example. I temporarily breaks the syntax highlighter in the VBE:

![screenshot from 2016-05-19 21 51 50](https://cloud.githubusercontent.com/assets/8944005/15416032/c50a4268-1e0c-11e6-8ea5-b47d7c8c1088.png)

**Comment by comintern** [comment]
The tests for this were based on the assumption that the indenter's behavior was "good enough" for this dodgy code, and the issue closed simply due to the `End Sub` being positioned correctly. The next PR will actually make this correct to my read:

```
Sub MySub()
    Dim x1 As Integer
    Dim _
    x2 _
    As Integer
    Dim x3 As _
    Integer
    Dim x4 _
    As _
    Integer
    Dim x5 As Integer: _
    Dim x6 As _
    Integer
    Dim x7 As Integer _
        'Comment _
        as _
        integer
End Sub
```

Nothing in the continuations should be indented at all in this example except for the comment, which is being treated as an end-of-line comment.
