### ISSUE TITLE
Unhandled COMException closing Excel with protected add-in

### ISSUE THREAD

**Issue by comintern** [rubberduck-vba/Rubberduck#1289]
Similar to [Test module does not work with protected projects #354](https://github.com/rubberduck-vba/Rubberduck/issues/354).  In my case, I have the Solver add-in installed in Excel.  When I close Excel, I get an unhandled `COMException` "Can't perform operation since the project is protected." in `sink_ProjectRemoved`. 

Not sure how big a deal this is, because the application is shutting down anyway.  It should probably be handled though - if Rubberduck crashes at this point none of the hooks are removed.  I'm not exactly sure how COM handles that, but the decent thing to do would be to ensure that `Dispose` executes.

**Comment by retailcoder** [comment]
It's not the hooks, it's the ProjectsEvents sink, a simple handler ...that needs to check project protection before trying to clean anything up.

**Comment by comintern** [comment]
Right, but it prevents  `App.Dispose()` from running.

**Comment by retailcoder** [comment]
Ooh nice catch!
