### ISSUE TITLE
Settings window should either be sizeable or larger.

### ISSUE THREAD

**Issue by comintern** [rubberduck-vba/Rubberduck#1292]
Currently, the General Settings option has 7 options for Hotkeys.  Only 3 of them are visible in the scrolling area.  

Code Inspection Settings opens with all of the parent nodes expanded, and has a scroll area that shows at most 9 of the 38 child nodes. None of the parent nodes will expand with all of it's child nodes visible in the scrolling area.

Indenter Settings has a fixed layout in the top pane, but only half of the pane is visible without scrolling.

**Comment by INOPIAE** [comment]
The should be an automtic line break in the list of the Code Inspector settings.
See 
![codeinstpector](https://cloud.githubusercontent.com/assets/2772829/14232854/70aa367a-f9b7-11e5-9117-07e374a558d3.PNG)

**Comment by retailcoder** [comment]
@INOPIAE nice one - I'll try to put the fix in the `GroupingGrid` control itself, so everything wraps everywhere.

**Comment by INOPIAE** [comment]
Are you sure that you fixed this? Looking at the settings window with 4bb6243 I still cannot change the settings window nor is the line wrap for longer text visible. The screenshot above is the same I see just now.
