### ISSUE TITLE
SourceControl UI feature

### ISSUE THREAD

**Issue by INOPIAE** [rubberduck-vba/Rubberduck#1296]
It would be nice to have also the column "date" on the tab Unsynced commits.
![soucrecontrol column date](https://cloud.githubusercontent.com/assets/2772829/14233015/e0e20efe-f9bc-11e5-972e-e2ab5ce39095.PNG)

May be there can be a feature to decide what columns to display.

**Comment by Vogel612** [comment]
in git there's two dates associated with a commit... I'd opt for having a choice to display different columns for the commits, which would then allow the choice between the two.

But by default I'd also include a date in there, probably after the Author. 

If there'd be such a feature, I hope it would also support rearranging the columns

**Comment by rubberduck203** [comment]
#3758
