### ISSUE TITLE
RubberDuck should display better *selection/cursor* properties

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#1308]
Now that RubberDuck provides a "status bar" it would be useful to display richer details about the active codepane selection/cursor.

VBE's Standard toolbar displays the cursors _line_ and _column_ position, and while useful, it would also be useful to see things like:
- The total number of lines in the module
- The total number of characters in the module
- The number of procedures in a module
- The number of physical lines in a selection
- The number of logical lines in a selection
- The number of characters in a selection

Ideally, the Column and Line position details from the Standard toolbar would appear alongside the enhanced selection details on the Rubberduck toolbar, so that all of the properties appear together.

**Comment by retailcoder** [comment]
Closing as completed, although not as requested - the status bar does indeed now display richer details about the active code pane selection.
