### ISSUE TITLE
Can VBA code snippet be available to search via Bing?

### ISSUE THREAD

**Issue by PeterMTaylor** [rubberduck-vba/Rubberduck#1313]
G'Day,
I just thought to make a interesting topic for discussion about VBA code could/would be searchable.
http://techcrunch.com/2016/04/07/microsoft-and-hackerrank-bring-executable-code-snippets-to-bings-search-results-pages/
I learnt that Microsoft is partnering with HackRank to make code searchable.
If I used Rubberduck to pass my code to Github and somehow Github gets searchable.
Would this in theory work for .bas and .cls files?
I am not bothered much about binary worksheets though.
Peter.

**Comment by retailcoder** [comment]
out of scope
