### ISSUE TITLE
RubberDuck 1.4.3 needs to seamlessly upgrade to 2.0

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#1322]
With a 2.0 release _imminent_, and an expected 3000+ users of 1.4.3 at release, we need to ensure that an upgrade from 1.4.3 is easy and error-free.

Maybe also a wiki page on troubleshooting, and link to it from the release page.

**Comment by PeterMTaylor** [comment]
Agreed. Perhaps the troubleshooting section is categorised accordingly.

**Comment by INOPIAE** [comment]
You should also consider how you want to make sure that the config file can be extendet if a value is missing due to the fact of a new version.
Currently I observe when new hotkey shortcuts are implemented that I have to delete the old config file to get the new shortcuts as well.

**Comment by Vogel612** [comment]
2.0 release has been **quite** some time ago and we recently released 2.1 ... this isn't applicable anymore, IMO. Closing accordingly
