### ISSUE TITLE
COM reflection should pick up constant values

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#1328]
Instead of a `Declaration` for `DeclarationType.Constant` and `DeclarationType.EnumMember`, the code that inspects the types of COM libraries should generate a `ValuedDeclaration` to store the value.

The value could be displayed in the "current selection" status in the `RubberduckCommandBar`, and in other places such as the _Code Explorer_.

**Comment by ThunderFrame** [comment]
What to do when constant value assignment is a bitwise / UNION / expression?

**Comment by retailcoder** [comment]
@ThunderFrame good question. I'm pretty sure we could use @autoboosh's code to interpret those.

**Comment by ThunderFrame** [comment]
Might be nice to display the expression *and* the value. And also show hex/octal/decimal values for numerics.

**Comment by comintern** [comment]
The COM collector is already gathering this information from the typelib, so this would be really easy from the standpoint of non-user declarations. `ConstantDeclaration` already has an `Expression` member for user declarations (and the non-user ones don't need it). I'm up in the air as to whether enumeration members need their own declaration though. 

Naming aside, an enumeration member really is a "constant declaration", it's just a sub-set that happens to be the member of an `Enum`. We're currently creating `DeclarationType.EnumerationMember`s using the base `Declaration`, so it might be sufficient to just add a `Value` member to `ConstantDeclaration` and simply rename it to `ValuedDeclaration`.

The other option would be to have `ValuedDeclaration` be a base class for `ConstantDeclaration` and an added `EnumMemberDeclaration`, but  that seems like much ado about nothing in that the derived classes would be identical. Is there any reason that we can think of where their implementations would differ? Other thoughts?

**Comment by bclothier** [comment]
I don't know if this applies but one difference between a constant and a enum is that you can't qualify the constant like you can with an enum. For that reason, a enum member should know which enum they belong to, which can be important in creating inspections dealing with mismatched enum (e.g. using `Foo.Bar` as an input to a function expecting a `Bar` enum which incidentally has a `Bar` member with same value). If that information isn't already present, then that would be a case for a different subtype of `Declaration`?

**Comment by comintern** [comment]
@bclothier Wouldn't that be implicit from the `Parent`? Any enumeration member's parent should be an enumeration (or we have a resolver problem).
