### ISSUE TITLE
Resolver must account for inter-project references

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#1330]
The resolver currently escalates its searches like this:

 1. Look at parameters and local-scope variables
 2. Look at module-scope members
 3. Look at project-scope globals
 4. Look at the global-scope stuff

It should be this:

 1. Look at parameters and local-scope variables
 2. Look at module-scope members
 3. Look at project-scope globals
 4. Look at the global-scope stuff

   4.1. Look at exposed members in referenced VBA projects
   4.2. Look at exposed members in referenced COM libraries

**Comment by autoboosh** [comment]
Fixed with https://github.com/rubberduck-vba/Rubberduck/pull/1429
