### ISSUE TITLE
"Search results" tweaks

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#1334]
- [x] It should listen for parser state events, and refresh itself; remove tabs where the declaration is no longer found.

**Comment by Hosch250** [comment]
I disagree.  R# doesn't refresh itself--it just keeps the invalid references.

**Comment by retailcoder** [comment]
R# *does* refresh itself. It keeps the invalid references in the view, but with a strikethrough when a reference is actually removed.

If the view model kept a reference to the target declaration, this wouldn't be too hard to implement.

Also the "parser errors" view should definitely refresh itself.

**Comment by Hosch250** [comment]
Not here.  When I do Find All References, it just sticks them in a panel at the bottom of VS.  Besides, I wouldn't want them to refresh every time I typed.
