### ISSUE TITLE
Resolver: Different references from different projects could lead to wrong identifier reference

### ISSUE THREAD

**Issue by autoboosh** [rubberduck-vba/Rubberduck#1340]
References aren't associated with the projects that reference them so if there's project A referencing Connection in ADODB and project B referencing Connection in DAO then there could be a mixup.

**Comment by retailcoder** [comment]
Moreover, if a declaration is ambiguous, e.g. a project references *both* ADODB and DAO (gosh!), the "as type" declaration of this variable should resolve to whichever `Reference` comes first when a project's references are iterated:

    Dim c As Connection

IMO this unqualified reference should also trigger an inspection result, and the quick-fix would turn it into this:

    Dim c As ADODB.Connection

(assuming the type resolves to the ADODB library)

**Comment by autoboosh** [comment]
Fixed with https://github.com/rubberduck-vba/Rubberduck/pull/1429
