### ISSUE TITLE
Alternative NEQ/GEQ/LEQ are missing in the grammar

### ISSUE THREAD

**Issue by autoboosh** [rubberduck-vba/Rubberduck#1346]
Lexer rules:

```
GEQ : '>=';
ALTGEQ : '=>';
LEQ : '<=';
ALTLEQ : '=<';
NEQ : '<>';
ALTNEQ : '><';
```

The ALT-rules are currently missing. The VBE actually transforms the alternative into the "main" one but I don't know if every VBA editor out there does that.

**Comment by Vogel612** [comment]
Would it not be easier for the resolver if these were not separate Lexer rules, but combined ones?

   GEQ : '>=' | '=>';
   [...]

**Comment by autoboosh** [comment]
You're right, that makes a lot more sense, thanks :)

**Comment by autoboosh** [comment]
Done.
