### ISSUE TITLE
Implements should allow expressions instead of mere identifiers

### ISSUE THREAD

**Issue by autoboosh** [rubberduck-vba/Rubberduck#1348]
This is allowed:

`Implements VBAProject.ITest`

But destroys the parser.

"Correct" parser rule:

`implementsStmt : IMPLEMENTS whiteSpace valueStmt;`

I'd like to take this as an opportunity to sneak in expressions per VBA spec by creating an ExpressionParser. The expression parser could parse the valueStmt and build an expression tree. We could then hand off this tree to the binder. I'd start with simple-name-expressions in this case because that's what we currently support. This way we don't have to change everything in Rubberduck to accommodate the new grammar but at the same time we get to test the expression based binder with real world code.

This could also lead to an implementation of a solution to https://github.com/rubberduck-vba/Rubberduck/issues/1340.

**Comment by Vogel612** [comment]
I'm not sure that this is a `valueStmt`. Isn't it more correct to see this as a FQN? or are these in fact `valueStmt`s and only the resolver gives them the notion of being a Type?

**Comment by autoboosh** [comment]
There's a bit of a chaos in the grammar right now because valueStmts should actually be expressions.

The VBA spec says that the implements-directive takes a class-type-name: https://msdn.microsoft.com/en-us/library/ee177434.aspx

A class-type-name in turn is defined as a defined-type-expression: https://msdn.microsoft.com/en-us/library/ee200228.aspx.

A defined-type-expression is then defined as simple-name-expression (basically an "ambiguousIdentifier") and a member-access-expression (this is the part the valueStmt covers): https://msdn.microsoft.com/en-us/library/ee199065.aspx.

So I'd say you are correct in saying that valueStmts are not the correct solution but it's the way treat cases like this right now. E.g. the value stmt also allows midStmts and typeOfStmts which are completely out of place. It would be nice to slowly move towards expressions.

**Comment by autoboosh** [comment]
Fixed with https://github.com/rubberduck-vba/Rubberduck/pull/1429
