### ISSUE TITLE
ByVal/ByRef with ParamArray not possible

### ISSUE THREAD

**Issue by dimitrimitropulos** [rubberduck-vba/Rubberduck#1350]
With the following code:
```
Public Sub test(ParamArray someArray() As Variant)

End Sub
```

the Code Inspections throws an "implicit ByRef parameter".  The "Fix" then changes the code to this:
```
Public Sub test(ByRef ParamArray someArray() As Variant)

End Sub
```
which is a compile error.

**Comment by autoboosh** [comment]
Nice find. Paramarrays are apparently always ByRef. I'll take a look :)
