### ISSUE TITLE
Copying text from the immediate window should remove line breaks in long text

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#1354]
The immediate window limits line lengths to 1023 visible characters, so any value (that has lines with more than 1023 characters) is rendered in the immediate window with line-breaks inserted by the VBE.

If you want to subsequently use that text in another context (eg SQL in SSMS, XML in Visual Studio, or Lorem Ipsum in Notepad++), then the value that is copied from the immediate window needs to be pasted into the target context and then be manually corrected. That's tedious and error prone.

Rubberduck should implement a _Copy Selection from Immediate Window_ command, which strips out the line breaks of lines that have exactly 1023 characters.

There will need to be special handling of text selections that involve a 1023 character line, but where the selection doesn't start at the start of that line.

**Comment by retailcoder** [comment]
There's no [easy] programmatic access to the immediate pane; if debug output needs to be *used*, then it should be output to a file, no?

**Comment by ThunderFrame** [comment]
Copying the selection to clipboard,and then modifying the clipboard contents would do it.

Writing to a file would be better, but you don't always want to do that in a debugging situation.

If there was a COM exposed object, then you could do something like:

```vb
Public Debug2 as New RubberDuck.Debug

Sub dummy
  s = String(10000,"*")
  Debug2.Print s
End Sub
```

**Comment by retailcoder** [comment]
out of scope
