### ISSUE TITLE
Website needs to be updated

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#1363]
Needs new screenshots for pretty much everything, and a description for the new features. Review every content page.

**Comment by Hosch250** [comment]
I just did a lot of work on this, and pretty much the only thing left is the content of each page.

[ ] Proper, small-file-size thumbnails.
[ ] New descriptions for each of the features.
[ ] Full-size images for each of the pictures (preferably only showing the relevant material, and not a bunch of faded, irrelevant text.

Not required, but nice-to-have, would be referencing the main project and inspecting user-input code.  I will take a look at this.

**Comment by Vogel612** [comment]
@Hosch250 IIRC, RubberDuck did look into that ... maybe you can ask him for some info :smile:

**Comment by Hosch250** [comment]
The user can now input code and run the inspections against it.

**Comment by Hosch250** [comment]
Anyone else who wants to contribute is welcome, of course.

**Comment by Vogel612** [comment]
Seems like this one can be closed. Website concerns should be going to http://github.com/rubberduck-vba/RubberduckWeb from now on, right?

**Comment by retailcoder** [comment]
@Vogel612 yup. Thanks!
