### ISSUE TITLE
Regex Builder/Assistant

### ISSUE THREAD

**Issue by CaffeinatedCoderSO** [rubberduck-vba/Rubberduck#1364]
A feature to assist in the building of Regular Expressions that would provide clickable options that build the formula as the user selects what they would like to search for.

**Comment by Vogel612** [comment]
I'd be interested in building the guts for this. Can someone point me towards a resource outlining the RegEx support for VBA? 

Sidequestion: Wouldn't https://regex101.com or similar do the trick already?

**Comment by CaffeinatedCoderSO** [comment]
That site would, but it'd be much more convenient to have it all in one place (and accessible without internet connection). The documentation for the regex used in vba is below. Vba uses the vbscript version of it. https://msdn.microsoft.com/en-us/library/ms974570.aspxBest regards,Michael Hill------ Original Message ------From: Clemens LiebTo: rubberduck-vba/RubberduckCc: Michael Hill, AuthorSent: April 23, 2016 at 3:30 PMSubject: Re: [rubberduck-vba/Rubberduck] Regex Builder/Assistant (#1364)I'd be interested in building the guts for this. Can someone point me towards a resource outlining the RegEx support for VBA? 

Sidequestion: Wouldn't https://regex101.com or similar do the trick already?

**Comment by Vogel612** [comment]
I'm starting work on this now. the current WIP status can be found [at my repo](https://github.com/Vogel612/Rubberduck/tree/RegexAssistant)

**Comment by Vogel612** [comment]
Fixed as of #1871

**Comment by retailcoder** [comment]
@Vogel612 not quite yet. The "Regex Assistant" feature, for now, simply *analyses* a regex pattern.

We'll need to add another tab to that dialog, to implement an actual "builder", and then a place to paste some sample text and evaluate/validate the regex against some data (we don't have to reimplement the regex engine, we can very well use the .net engine for this - and use the analyzer to determine if the pattern is a valid VBScript-flavor regex pattern).

But it's a good start.

**Comment by Vogel612** [comment]
@retailcoder what do you think of moving the actual builder into a new issue? That would allow cleaner specification without the baggage from this issue

**Comment by retailcoder** [comment]
@Vogel612 definitely!

**Comment by Vogel612** [comment]
Closed as fixed, the additonal builder is specified in #3250
