### ISSUE TITLE
4K display messes up WPF toolwindows

### ISSUE THREAD

**Issue by BobTB** [rubberduck-vba/Rubberduck#1371]
Using windows 10, 64 bit, MS Access, the latest alpha fix release (old one was ok) has this when source control is opened. I do not use any scaling, have desktop at 100%, no large icons, fonts etc..

![image](https://cloud.githubusercontent.com/assets/15887688/14799863/d3ec41cc-0b3e-11e6-8837-6960b5754acc.png)

**Comment by retailcoder** [comment]
4K display?

**Comment by BobTB** [comment]
Yes, but on last pre fix release it was ok.

**Comment by retailcoder** [comment]
Looks like Windows is over-compensating for something.... :smiley:  :sweat_smile: :

**Comment by Hosch250** [comment]
Holy smokes, this looks awful.

**Comment by Hosch250** [comment]
This is still acting up in the latest release, I suppose...  None of us has a 4k screen, so I'm not too sure how we'll go about fixing this.

**Comment by BobTB** [comment]
no, miraculously it is not, it looks ok now!

**Comment by Hosch250** [comment]
Awesome! :smile:
