### ISSUE TITLE
Resolver needs to account for subclasses

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#1377]
Given public field `Foo` in `ThisWorkbook`:

![image](https://cloud.githubusercontent.com/assets/5751684/14839750/85f5edd4-0bfb-11e6-9f9c-7de2af90393c.png)

When `Foo` is accessed in `Module1`, `ThisWorkbook` resolves to `Excel._Global.ThisWorkbook`, a `Property Get` accessor that returns a `Workbook` object:

![image](https://cloud.githubusercontent.com/assets/5751684/14839770/c1b35d20-0bfb-11e6-92bc-bd7ed606f994.png)

That's great and completely by-design. The problem is, the `Workbook` class doesn't have a `Foo` public field, so `ThisWorkbook.Foo` doesn't resolve to a reference to our `Foo` public field:

![image](https://cloud.githubusercontent.com/assets/5751684/14839828/14a86368-0bfc-11e6-8f09-a39a021379d1.png)

This also means any document-type and UserForm modules' public members can't be resolved correctly. This is a problem.

The resolver needs to look for a match in the base class, yes. *And then it needs to look at the subclass' members*.

**Comment by autoboosh** [comment]
Isn't this overthinking it a bit? Couldn't we just take the "local" one in our project if there's a ThisWorkbook there, otherwise take the built-in one? The "ThisWorkbook" part is a simple name expression: https://msdn.microsoft.com/en-us/library/ee177495.aspx and the lookup rules are split up into tiers. In our case we should actually be matching the module in the "Enclosing Project namespace", right?

**Comment by retailcoder** [comment]
@autoboosh okay. now consider `Sheet1`, or `Form1`, respectively inheriting members from `Worksheet` and `UserForm` classes, or the case where `ThisWorkbook` is renamed to `MyWorkbook` such as the module's name no longer happily matches the name of a `_Global` member: we have all these thousands of built-in declarations picked up, and we wouldn't be using them?

**Comment by autoboosh** [comment]
I understand what you're trying to say but it seems like it's not actually inheritance that's at play here but what VBA calls module extensibility: https://msdn.microsoft.com/en-us/library/ee199717.aspx. Both extended module as well as the module "doing the extending" have to have the same name. So the situation you are describing should never happen.:

> The module name (section 4.2) of an extension module must be identical to that of the 
> extensible module it is extending.  

Btw, I'm just trying to find a fix for the mouse/keyboard hooks and just realized that the status bar is amazing :)

**Comment by retailcoder** [comment]
lol, that status bar was first and foremost created to help "see the code through Rubberduck's eyes" and diagnose resolver issues that would otherwise fly under the radar. Did you notice the tooltip when you're on a member that has a `VB_Description` attribute? :wink: 

I know it's not exactly *inheritance*, but at the end of the day `Sheet1` exposes members of both the `Worksheet` type and the `Sheet1` VBComponent module we're seeing - and Rubberduck needs to be able to resolve `Sheet1.Range("A1")` to a call to the `Worksheet.Range()` function, and `Sheet1.DoSomething` to a call to the `Sheet1.DoSomething` public method. Right?

**Comment by autoboosh** [comment]
In your example there should be a built-in declaration called "Sheet1" which it would resolve to. If the local Sheet1-module does not have the Range function, the resolver would simply move onto the next resolution tier and find the built-in one.

**Comment by retailcoder** [comment]
hmm current resolver won't attempt to match `Range` anywhere other than in the resolved type of the "parent"... where would the built-in `Sheet1` declaration come from? IMO there would be a `Sheet1` *user* declaration (`DeclarationType.ClassModule`), with an `AsTypeName` of `Sheet1` - so `Range` in `Sheet1.Range` wouldn't resolve.

The current resolver would resolve it, however, if the `AsTypeName` of `Sheet1` were `Worksheet` - so it would try to locate the `Range` member of the `Worksheet` type, find it, and bingo, got it.

**Comment by autoboosh** [comment]
Ah, so you are right, they really are just like subclasses.

So in other words we'd have to find out whether a module is an extension module right? If Sheet1.Range can't be found we'd have to check if it's an extended module of something else, if it is, check that module. Do we have that info somewhere?

**Comment by retailcoder** [comment]
It's not necessarily consistent, but we can make it work to the best of our knowledge.

I didn't commit it yet, but I have code at home that returns `Worksheet` for worksheet document modules, and `Workbook` for a workbook document module (aka `ThisWorkbook`), by inspecting the `VBComponent.Properties` collection, looking for the `Object` property of a `Parent` member - that returns a `__ComObject`, and then some `ITypeInfo` COM magic gets the actual type name.

If it works in all hosts, fine. If it doesn't... well at least we tried something :smiley:

**Comment by ThunderFrame** [comment]
AFAICT all document-type components are subclasses of host-specific classes, and AFAICT all User Forms are also subclasses or `UserForm`.

Things get interesting when you add a WithEvents variable (or add an ActiveX control to a worksheet, or an Access control to an Access Form/Report) to a document-type component. Likewise, when adding a control to a User Form, all of the controls inherit from `Control`.And ditto for CommandBarControls, which inherit from CommandBarControl.

How does Rubberduck decide what to do with this:

```vb
Dim ctl As Control

'Set ctl to a Label Control
Set ctl = UserForm1.Label1
Label1.Caption = "Foo"

'Set ctl to a TextBox Control
Set ctl = UserForm1.TextBox1
ctl.MultiLine = True
```

**Comment by autoboosh** [comment]
That example won't work because we only look at ctl's declared type.
