### ISSUE TITLE
Resolver: ByRef Parameter to Argument binding

### ISSUE THREAD

**Issue by autoboosh** [rubberduck-vba/Rubberduck#1388]
If a local variable is used as an argument for a parameter that is ByRef, the variable can be changed. Should we add an identifier reference from Parameter to local variable?

**Comment by retailcoder** [comment]
The inspection for "variable is never assigned" does a fair amount of processing to figure out whether a variable is passed by reference as an argument to a procedure, and I'm not sure it accounts for `ByRef` arguments forced-passed by value:

    Sub DoSomething(ByRef value As Integer)
        value = 42
    End Sub

    Sub Test()
        Dim foo As Integer
        DoSomething (foo) 'parens override the ByRef modifier and pass a copy of the value
        Debug.Print foo 'outputs 0 / variable isn't actually assigned at this point

        DoSomething foo
        Debug.Print foo 'outputs 42 / variable was passed by reference and assigned in another method
    End Sub

Doing this work in the resolver would greatly simplify the inspection.

**Comment by retailcoder** [comment]
On the other hand, it seems we would need a "different kind" of `IdentifierReference` for this to work.

Or, we'd need to tweak the `Rename` refactoring to verify that the `IdentifierName` being referenced matches that of the `Declaration` being renamed.

**Comment by retailcoder** [comment]
This is now implemented in the `DeclarationFinder`.
