### ISSUE TITLE
unhandled exception in todo

### ISSUE THREAD

**Issue by Talorthain** [rubberduck-vba/Rubberduck#1389]
Todo list empty. Clicked the X button and had an unhandled exception.
![unhandled](https://cloud.githubusercontent.com/assets/6796503/14896464/cb3fc696-0d75-11e6-8b3f-3c62f51cd1de.PNG)

**Comment by retailcoder** [comment]
Please confirm: this is with v1.4.3, correct?

**Comment by Hosch250** [comment]
No repro in the latest build.  This is probably fixed already.

**Comment by retailcoder** [comment]
"fixed" is a big word... the whole UI was redone :smiley: 

The hint is in the stack trace: `System.Windows.Forms.DataGridView.SelectedRowCollection.get_Item` - the 2.0 toolwindow is a WPF user control with a `GroupingGrid`. This bug pertains to 1.x, closing.

**Comment by Hosch250** [comment]
Cleared my assignment because we all took a hand in this.

**Comment by Talorthain** [comment]
Yes this is in 1.4.3
