### ISSUE TITLE
Object variable assigned without 'Set' keyword false positives

### ISSUE THREAD

**Issue by autoboosh** [rubberduck-vba/Rubberduck#1391]
This triggers an inspection result:

```
Public Sub Test()
    Dim a As Variant
    a = 20
End Sub
```

**Comment by retailcoder** [comment]
Oh wow what a dumb oversight of my part - this is literally 2 seconds to fix..

**Comment by Hosch250** [comment]
So, this should not alert on Variant types?

**Comment by retailcoder** [comment]
@Hosch250 correct. Simply add `Tokens.Variant` to the list of value type tokens to ignore; there's a chance that the variable *might* actually hold an object reference, but then I'd rather not report anything than report a much more likely false positive.
