### ISSUE TITLE
Resolver: type annotate the declaration tree with declared type

### ISSUE THREAD

**Issue by autoboosh** [rubberduck-vba/Rubberduck#1392]
Looks like we need the declared types in the declarations to figure out how to resolve each expression.Perhaps we could also reverse the linkage between declarations, from child->parent to parent->child so the tree is easier to walk?

Edit: To find the declared types we'd also have to consider the "Define directives" (DefBool etc.).

**Comment by retailcoder** [comment]
Definitely. This would put all these 'parent type' lookups up front and further improve resolution performance.

**Comment by autoboosh** [comment]
The ReferenceDeclarationsCollector sets the parent of enum types and UDTs to project instead of module. Do we not have that information?

**Comment by retailcoder** [comment]
@autoboosh possible... but, as far as I understood COM, UDT's and enums *are* types, and their members are fields - not sure how to translate that into proper VB-speak... it's also not collecting enum/const values, I've no idea how to pick those up

**Comment by autoboosh** [comment]
Regarding your first point. The problem is that the declaration finder expects these types to have modules as parents because they're needed to check the accessibility. It's possible to mark a module as private thus preventing it from being used outside of the enclosing project. Could we change that perhaps or is there a simpler way I'm not seeing?

As for your second point, I'm sure @ThunderFrame or @comintern  can help you out with that :)

**Comment by autoboosh** [comment]
The declaration finder should be able to work with types that don't have a module parent but it would still be nice to have the same model throughout the code base.

The latest PR https://github.com/rubberduck-vba/Rubberduck/pull/1429 annotates all declarations in a separate type annotation pass. There's a new "AsTypeDeclaration" property on the declaration for this purpose.
