### ISSUE TITLE
Code Inspections can be opened with Ctrl+Shift+I even when menu item is disabled

### ISSUE THREAD

**Issue by SteGriff** [rubberduck-vba/Rubberduck#1395]
I created a new Excel file, and added some simple VBA to change a few cell values. The code compiled, and worked as expected when run as a Macro.

This whole time, the rubberduck bar was stuck on "Parsed" instead of "Ready", and Code Inspections was greyed out (disabled) on the menu. I fixed this by restarting Excel.

**However, while the menu item was disabled, I was still able to open Code Inspections with Ctrl+Shift+I** but it contained a load of goofy errors which were out of sync with the project.

**Comment by retailcoder** [comment]
@Hosch250 note that this holds true for all commands - e.g. the Code Explorer can be brought up with the hotkey even though `CanExecute` returns false.

**Comment by Hosch250** [comment]
This menu item is never disabled.  It will refresh with each reparse.

**Comment by SteGriff** [comment]
@Hosch250 Ok, but it is disabled if parsing fails, so I guess that's what we're seeing in my scenario?

**Comment by Hosch250** [comment]
@SteGriff I removed that check.  CanExecute always turns true now.
