### ISSUE TITLE
StringVariant Returning functions QuickFix breaks code. 

### ISSUE THREAD

**Issue by Vogel612** [rubberduck-vba/Rubberduck#1405]
Coming from following code:

            DriveVSN = Left(Hex(d.SerialNumber), 4) & "-" & Right(Hex(d.SerialNumber), 4)

Running "Fix All Occurences in Module" results in:

            DriveVSN = Left$(Hex$$(d.SerialNumber), 4) & "-" & Right$(Hex$$(d.SerialNumber), 4)

That's obviously broken, and shouldn't happen.

**Comment by Vogel612** [comment]
Probably related: One can run the "Fix: Replace Left with Left$" multiple times, when the parser takes a while to rerun. Could it be that the parser isn't correctly triggered after applying this quickfix?

**Comment by retailcoder** [comment]
This is probably a mix of several issues:

 - Resolver bug not correctly resolving `Left$` as a reference to `_B_str_Left`
 - Bug with the inspection quick-fix itself

I'm pretty sure applying any quick-fix *does* trigger a reparse.

**Comment by Vogel612** [comment]
Additionally related: The Fix menu entry has the functions backwards:

![Replace 'Hex$' with 'Hex'](https://cloud.githubusercontent.com/assets/7288995/14926370/2792a9f0-0e4c-11e6-883f-caef196583c1.PNG)

Seems to happen for all Functions that do this

**Comment by autoboosh** [comment]
"Resolver bug not correctly resolving Left$ as a reference to _B_str_Left"

Why exactly is Left handled differently and are there any more cases like these? The VBA spec even mentions it specially in the simple name expression section:

> There is a special exception to these namespace tiers when the match has the name value "Left":  
> - If the match has the name value "Left", references a function or subroutine that has no 
> parameters, or a property with a Property Get that has no parameters, the declared type of the 
> match is any type except a specific class, Object or Variant, and this simple name expression is 
> the <l-expression> within an index expression with an argument list containing 2 arguments, 
> discard the match and continue searching for a match on lower tiers.

**Comment by Hosch250** [comment]
This doesn't even report any errors anymore.

**Comment by retailcoder** [comment]
Ok.. could the ugly hack that made this work before be somehow reinstated?

The `DeclarationFinder` class was falling back to `"_B_var_" + identifierName` when no type hint was involved, and to `"_B_str_" + identifierName` when there was a type hint.

Since `Left` is *usually* a member call when it's not the globally-scoped string function, chances of a false positive are pretty slim, since if we're trying to match a member call or a local function named `Left`, we'll find a match before we run the fallback code anyway.

**Comment by comintern** [comment]
Would it make more sense to put the ugly hack in the ReferencedDeclarationsCollector class? That might give more flexibility in how FUNCFLAG_FHIDDEN is handled (`Left` and friends are all marked hidden IIR), and wouldn't get called repeatedly.

**Comment by retailcoder** [comment]
@comintern what makes it hard is that `Left` and `Left$` both have `Left` as the `IdentifierName`, the type hint being parsed as a suffix to the identifier. But the idea isn't crazy at all, the resolver could treat `Left`+`$` as `Left$`, and match that.

**Comment by Hosch250** [comment]
The string-variant inspection doesn't even fire for me.

**Comment by Hosch250** [comment]
Whoever wrote this bug deserves to be shot.  The trouble is it is a simple search/replace, and `Hex` gets replaced twice...
