### ISSUE TITLE
Virus warning - version 2 pre release

### ISSUE THREAD

**Issue by Talorthain** [rubberduck-vba/Rubberduck#1406]
version 2 pre - release
![capture](https://cloud.githubusercontent.com/assets/6796503/14926751/9184568a-0e45-11e6-83e1-1fec6416f2f2.PNG)

Is it a false positive????

**Comment by retailcoder** [comment]
WTF??

**Comment by Vogel612** [comment]
soo... just for reference: If you want to know whether something is a virus, asking the people who wrote it and trusting them may not be the best idea. 

That being said... WTF? let me guess... ESET being overly sensitive to breathing again? That should be a FP

**Comment by Talorthain** [comment]
just installed version 2 pre from git.. so I could test..

Windows defender popped up 1 minute later with virus warning

**Comment by Talorthain** [comment]
lol. totally understand your main point... and yes.. I agree, but the project and earlier versions no issues.. I wouldnt keep on system even if a false positive.

It is windows defender that flagged it. Im now runnign aditional software to check system

**Comment by retailcoder** [comment]
This *may* have something to do with the low-level keyboard and mouse hooks, which make Win32 API calls to intercept keys and clicks sent to the active code pane, which is the only way we have of detecting a change in caret position...

**Comment by retailcoder** [comment]
Just to be clear: we did **NOT** implement a keylogger, we do **NOT** care about WM messages sent anywhere other than the active code pane, and we did **NOT** intentionally package a virus with out installer.

**Comment by retailcoder** [comment]
FWIW Symantec is also flagging the 2.0.1a installer as "Malicious: There is strong evidence that this file is untrustworthy".

We did have a similar warning with Symantec in v1.1 (IIRC); v1.22 was white-listed, but not v1.3 and not v1.4, and we didn't have any reports with them.

**Comment by Talorthain** [comment]
Thank you for the update. I will wait on the next installer.

**Comment by PeterMTaylor** [comment]
I too wanna "have a go" with pre-alpha release RB so I grabbed a version from Github myself.
A moment after installation the Window Defender spat this same virus error reported eariler.
Also followed the link as Defender suggested.

![rubberduck pre-alpha release malware report](https://cloud.githubusercontent.com/assets/2254567/14941433/0bbeb776-0fde-11e6-8747-aade714937dd.PNG)

Other news of interest ;-
No crashes when I used it the first time. - nice
Parser took about 25 seconds "manually counted" to process all files loaded in memory. - will baseline that for reference.

![rubberduck rpg-075a code inspection report](https://cloud.githubusercontent.com/assets/2254567/14941437/78c456be-0fde-11e6-85f0-409cde615474.PNG)

Looks like I have my work cut out for me. ;-)
Peter.

**Comment by Talorthain** [comment]
I originally flagged it, because false positives or real issues can cause problems with peoples trust of an appication. I did try the file again and I got a different virus detection, so it does look like anti virus software is flagging falsely.

@PeterMTaylor : I am assuming you continued with the install. You didnt say if the version that highlighted your issues was the same as the virus warning file.

**Comment by PeterMTaylor** [comment]
@Talorthain yes your correct I kept going with the installation as given. 2.0.1a version.

**Comment by Talorthain** [comment]
ok, just to further update. I have tried twice more.

1) Downloaded V2a, scanned file with WD and no issue. Installed and had virus warning.
2) Downloaded v2a, scanned file with WD and no issue. Installed. Deleted original file and everythign installed correclty and no issues on loading excel.

**Comment by retailcoder** [comment]
@PeterMTaylor don't wreck your setup for this, but I'd be pretty curious to see how long v1.4.3 takes to process the same project! Do the 25 seconds include running the inspections? (they start running as soon as the parser is in `Ready` state)

**Comment by PeterMTaylor** [comment]
Ok, will do a test to compare for the same length of code.

**Comment by billyaraujo** [comment]
Hi,

I had the same issue and I think it is related with InnoSetup.

So I solved by removing all calls to the registry and the code section of my setup and now it passes Windows Defender scan. 

Hope this helps.

**Comment by retailcoder** [comment]
@billyaraujo that's helpful indeed - so, we need to package a PowerShell script to do the COM registration post-installation then? How did you keep it a simple one-step installer experience for your users?

**Comment by billyaraujo** [comment]
@retailcoder  For now I just removed the registry entries since it is just an executable and I don't need to register it. 

I didn't have time to determine if it was the [Registry] section or the [code] section that was creating the problems. What I suggest is to comment each section and see what is causing the problem in your case. 

Maybe running a script for post-installation operations such as the COM registration and other sensitive stuff will do the trick.

**Comment by Cocotteseb** [comment]
Please take a look here. I've encountered the same issue for my own app and contacted Microsoft. 
It should now be resolved. 
http://news.jrsoftware.org/read/article.php?id=103838&group=jrsoftware.innosetup#103838

**Comment by retailcoder** [comment]
Seems silly that an installer gets flagged for registering stuff in the registry... that's what installers do... unless I missed a memo.

**Comment by Cocotteseb** [comment]
There is a problem with Windows Defender and Inno Setup 5.5.9. 
Please take a look : http://news.jrsoftware.org/read/article.php?id=103838&group=jrsoftware.innosetup#103838

I've emailed Microsoft for my own app and they've done a new definition buiild and now it works 4/5 times. I've emailed them again.

**Comment by retailcoder** [comment]
I've submitted the installer executable as a false positive to the Microsoft Malware Protection Center, awaiting response.

**Comment by PeterMTaylor** [comment]
Ok, Rubberduckers!
Windows Defender on my own local system at home had updated their definition as at Wed 4th and Sat 7th. 

Found out v2.0.1a pre file has a new virus name Win32/Gatrid.E!cl as opposed to Win32/Fathale.B!plock reported

![capture win def rd 2 0 1a pre new virus name gatrid e cl](https://cloud.githubusercontent.com/assets/2254567/15090173/fc16df5c-145f-11e6-85f9-ac3144e1e702.PNG)

Will redo another download test to confirm is this is replicable.

**Comment by retailcoder** [comment]
Microsoft's Malware Protection Center deems our installer [clean](https://www.microsoft.com/security/portal/submission/SubmissionHistory.aspx?SubmissionId=ba57c544-718a-46f9-ae0b-4505bdff4bd5), you can mark them as false positives. Annoying, but I'm not sure what else we can do.

**Comment by PeterMTaylor** [comment]
ok. the download test with my Win Def (1.219.1026.0) passes as green for me. :)
