### ISSUE TITLE
Code Explorer should show project/component/member summaries

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#1410]
It would be useful to see statistics like the total number of modules (total and by type), number of lines, and number of members. That would allow a user to quickly say, "Gee, I have 400 standard modules and 0 classes. I may have a problem."

It seems like a natural place for this information would be in the Code Explorer? Select the Project/Component/Member, and a tooltip or status bar could tell you the relevant details.

**Comment by Vogel612** [comment]
The standard approach to this in MS IDEs seems to be a special "Properties" Window. This would allow displaying additional information, when the user requests it. I think we need to start being mindful of how much "unsolicited" information we pack into views to prevent an information overload.

**Comment by Hosch250** [comment]
I agree with Vogel that this is not CE information.
