### ISSUE TITLE
Keyboard shortcuts need to consider UserForm and Properties windows

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#1413]
TIL - When in User Form design mode, or when the Properties Window is active, Ctrl+Shift+X will select the first/next Property name (in the Properties window) that starts with "X", even if the Properties window is not visible.

Rubberduck may need to consider whether to honor this behavior or apply a shortcut, based on the active window. It might need to be a user setting?

**Comment by retailcoder** [comment]
Not sure what this is about. How does it affect Rubberduck? Or rather, how does Rubberduck affect this shortcut?

**Comment by Vogel612** [comment]
IIUC what this issue suggests is that Rubberduck Hotkeys with `Ctrl + Shift` should not trigger in User Form design mode, since the designer already uses that key-combination to select Properties based on their name. 

The alternative would be to ignore this behaviour.

**Comment by ThunderFrame** [comment]
Maybe an option in RD settings, to determine the priority of shortcuts when a designer is active?

**Comment by bclothier** [comment]
The hotkeys are now configurable so this shouldn't be a problem anymore. At minimum open a new issue for where the default for a particular hotkey isn't that great.
