### ISSUE TITLE
Problems with MS Project

### ISSUE THREAD

**Issue by INOPIAE** [rubberduck-vba/Rubberduck#1414]
Working with 33daf0c
When I removed the last module from a file in MS Project 2013 I get this error:
![image](https://cloud.githubusercontent.com/assets/2772829/14935219/0740111e-0eca-11e6-9c26-483ac66ec7ef.png)

When closing the VBE from MS Project I get this error in Extensions.cs

![image](https://cloud.githubusercontent.com/assets/2772829/14935224/33738e78-0eca-11e6-947c-58ca287cd650.png)

**Comment by retailcoder** [comment]
Is this still happening in the latest build?

**Comment by INOPIAE** [comment]
Using commit dab17fb:
I create a new modul in MS Project 2013.
When start typing some code I run into this error in Rubberduck.Inspections.ImplicitActiveSheetReferenceInspection
![image](https://cloud.githubusercontent.com/assets/2772829/15151134/401146d0-16d0-11e6-97ab-ee9745e5938d.png)

**Comment by retailcoder** [comment]
@INOPIAE that's a new one. This needs a `null` check to be sure to only run the inspection when the host is known to be Excel.

**Comment by INOPIAE** [comment]
It happens with a new project, no Excel reference present.

**Comment by INOPIAE** [comment]
Another error come:
Created a new project, code window open, Tools - Referneces when closing the referens form this error shows up.
![image](https://cloud.githubusercontent.com/assets/2772829/15151876/625220f4-16d3-11e6-886a-4590509833d4.png)

**Comment by INOPIAE** [comment]
I seem to have simalar problem when opening the VBE in Word. I do not get any error, the system hang up.

**Comment by INOPIAE** [comment]
The problem still exists in commit 44f4bad
OT: I am not quite sure if this depends on the commit name. ;-)

**Comment by INOPIAE** [comment]
The problem still exists with 3b65933

**Comment by INOPIAE** [comment]
Working with 118f532  I also get this problem with Excel.
Steps to reproduce the problem

1. Open VBE
2. Close all windows
3. Goto Tools - Reference
4. Close Reference Dialog

Then the error occurs

**Comment by retailcoder** [comment]
@Hosch250 you have a repro on that one?

**Comment by Hosch250** [comment]
No repro on the Excel error.  The initial COM exception is caused by a call to the parser.  The parser eventually calls `QualifiedModuleName(VBComponent)`, which throws a COMException to wait.

**Comment by INOPIAE** [comment]
I do NOT get the errors any more with commit 760ec98

**Comment by ThunderFrame** [comment]
no more flames for me either
