### ISSUE TITLE
Code Explorer implementation issues

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#1418]
The (commented-out) code explorer implementation is currently doing quite a lot of work in the ViewModel's constructor, including:

 - Iterating modules' `@Folder` annotations, and figuring out out the folder hierarchy
 - Generating ViewModel instances for all tree nodes

The folder logic needs to be extracted out of the code explorer stuff, so we can reuse it in other places, for example if we want to make a "group by folder" grouping in the various `GroupingGrid` controls (test explorer, inspection results, etc.)

Here's how I'm seeing it work:

 - Handles the parser state changing to a `Ready` state (ideally there would be a state between `Parsed` and `Resolving`, to indicate when the parser state has all `Declaration` instances and is about to start walking parse trees to add `IdentifierReference` instances to the declarations - but there's no such state for now, so let's just make the code explorer require a `Ready` state)
 - In order to avoid blocking the UI thread, generating the nodes should be done in a background worker thread, with the `BusyIndicator` being visible during that time.
 - If we simply iterate declarations, we'll be missing nodes for protected projects and any module that failed to produce a valid parse tree (i.e. all modules in an `Error` state); we want to still display error-state modules as tree nodes. To achieve this, we must be iterating `VBComponents` and checking the `ParserState` to determine if a `VBComponent` has an `Error` state - in which case the navigation info for the node should point to the parser error.

 - "Toggle signatures" button toggles between "identifier name" and "full signature" of member-level nodes
 - "Edit folder" and "Rename folder" buttons should be removed; we'll make a separate "refactoring" to handle this. Extracting the folder logic is step one for this; for now let's just make the code explorer display whatever folder hierarchy the `@Folder` annotations create.
 - "Add" menu commands should add components to the project.
 - "Refresh" command should trigger the `ReparseCommand`.

**Comment by Hosch250** [comment]
This can be closed once my latest PR is merged.
