### ISSUE TITLE
Crash when Indenting Project

### ISSUE THREAD

**Issue by Hosch250** [rubberduck-vba/Rubberduck#1422]
private static bool HasCode(CodeModule module, ref int lineCount)
    {
        lineCount += module.CountOfLines;
        for (var i = 0; i < module.CountOfLines; i++)
        {
            ^if (!string.IsNullOrWhiteSpace(module.Lines[i, 1]))
            {
                return true;
            }
        }
        return false;
    }

Excel crashes completely, and VS puts the cursor where I put the caret.  Line 111 of Indenter.cs, to be exact.

**Comment by autoboosh** [comment]
Do you have some example code that you've tried to indent?

**Comment by Hosch250** [comment]
Just any code.  I believe I used:

```
Sub foo()
Dim dd As Boolean
dd = True
End Sub

**Comment by autoboosh** [comment]
That works for me though. I've tried both Indent -> Procedure + Module. Have you tried it with the latest version in next?

**Comment by Hosch250** [comment]
Yes.  You need to go into the Code Explorer, select the Project node, and try to indent the entire project.

**Comment by autoboosh** [comment]
Off by one error, because VBE starts with 1 not 0 :(.

Should be fixed with https://github.com/rubberduck-vba/Rubberduck/pull/1429.

**Comment by Hosch250** [comment]
Awesome.
