### ISSUE TITLE
RubberDuck should offer a better Properties window

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#1430]
As long as we're going WPF, we could recreate the properties window.

It seems the host has to specify which Properties are displayed, and which categories they fall under, so, for example, Excel _doesn't_ display all Worksheet properties.

While categories might be difficult, we could show _all_ non-read-only properties that return simple types or enums, and maybe properties that return objects like Font and Picture. We'd need to handle the special case of `CodeName`.

Aside from being an exercise in aesthetics, we could have better color pickers, allow for loading transparent PNG pictures, and better font pickers.

**Comment by Vogel612** [comment]
out of scope for v2 development work at this point
