### ISSUE TITLE
ModuleExporter: vbext_ComponentType.vbext_ct_Document doesn't export attributes into file

### ISSUE THREAD

**Issue by autoboosh** [rubberduck-vba/Rubberduck#1432]
In Excel ThisWorkbook for example is marked as default instance variable but those attributes don't get exported / parsed in Rubberduck. Is this a known issue?

**Comment by ThunderFrame** [comment]
IIRC, it's VBE that doesn't write those attributes when exporting.

**Comment by retailcoder** [comment]
Like @ThunderFrame said. The VBE doesn't export attributes for `vbext_ct_document` modules. Whatever the reason is. I'd say that's beyond our scope/reach then.
