### ISSUE TITLE
StatusBar selection label text can be stale

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#1434]
The status bar text still shows the last code-module name and selection position when:

You close all open codepanes.
Move focus to a designer, like a form in design mode.
Close a host project, and there aren't any other code panes open.

**Comment by retailcoder** [comment]
If the VBE correctly removes a project from its `VBProjects` collection when the host document is closed, then we get to run a handler for "project removed"; we can use that opportunity to clear the "current selection" text from the context-sensitive status bar when there is no *active code pane*.

Other than that, the VBE simply doesn't tell us anything about what's going on, so short of running a timer every second to verify that there's an active code pane (which isn't happening), I'd need fresh ideas to handle this.

**Comment by ThunderFrame** [comment]
The Project Explorer window repaints, when these type of events occur. We could listen there.

**Comment by retailcoder** [comment]
Of course it repaints. But short of p/invoking everything here, there's no clean way of doing this.

**Comment by ThunderFrame** [comment]
I meant the Project Explorer treeview receives messages and we can read the nodes, so we can see when a project is closed.
alternatively, maybe we can hook the open code pane windows, and catch the close/destroy?

**Comment by retailcoder** [comment]
More hooks and p/invoking means more failure points, I'd rather avoid them whenever possible.

**Comment by ThunderFrame** [comment]
OK, how about clearing the status bar if Refresh is clicked, or the status bar is clicked. It can check if there are any code pane windows open/active?

**Comment by Hosch250** [comment]
I have this fixed as well as I can with the events.

1) If a component is selected in the PE, it will check the status selection (does not work when a component is selected in the CE, making that stay synced with the VBE is a more major issue).
2) If a component is activated, it will refresh.
3) If a project is removed, it will refresh.

There are no events about forms and designers, so it will not change when a form designer is activated.  In fact, even when a designer has focus, the active codepane is the last codepane the user was in if it is still open.

**Comment by ThunderFrame** [comment]
@Comintern I wonder if we might get better events if we track the win32 messages?
