### ISSUE TITLE
Tear down menus

### ISSUE THREAD

**Issue by Hosch250** [rubberduck-vba/Rubberduck#1436]
Tearing down the menus doesn't work.  This is a part of the memory leak problem, and needs to be addressed before release.

**Comment by Hosch250** [comment]
The menus and status bar correctly disappear from the VBE when Rubberduck is unloaded.  I don't think they are completely being torn down correctly as things crash when Rubberduck is reloaded.

**Comment by Hosch250** [comment]
I believe the menus are correctly torn down, the only thing that seems to have problems is reconnecting the app hooks and correctly removing docked windows from the VBE.

**Comment by retailcoder** [comment]
@Hosch250 closing this one then; I'm considering shutdown/teardown cleanup part of #1438
