### ISSUE TITLE
Rubberduck doesn't exit properly

### ISSUE THREAD

**Issue by autoboosh** [rubberduck-vba/Rubberduck#1438]
When closing Excel for example, the process does not get killed which might be because still have references to COM objects somewhere. Here's an article about that problem: http://stackoverflow.com/questions/158706/how-to-properly-clean-up-excel-interop-objects.

Also it seems that the component parser tasks never get disposed of properly but I'm not sure how important that is.

**Comment by Hosch250** [comment]
@autoboosh This is our old friend the memory leak.  It is because not everything is disposed correctly.  When we tear it down, we need to go through and manually call `Dispose()` on every single item that implements IDisposable.

**Comment by autoboosh** [comment]
What about the "two dot" problem though as described here: http://stackoverflow.com/a/158752/5895299?

**Comment by Hosch250** [comment]
That may well be part of this.

**Comment by Hosch250** [comment]
Reference #1436

**Comment by retailcoder** [comment]
@autoboosh isn't the "two dot" problem only a problem when you're out-of-process?

If that's not the case, then we have TONS of `Marshal.ReleaseCOMObject` calls to sprinkle just about everywhere, ...and perhaps that might explain some of the intermittent crashing-on-exit.

Thoughts?

**Comment by autoboosh** [comment]
Oh my bad then, ignore what I just said.

**Comment by retailcoder** [comment]
@autoboosh well I *hope* with fingers quadruple-crossed that being in-process matters. Otherwise you could very well be correct here.

**Comment by Vogel612** [comment]
Is this still relevant to the latest releases?

**Comment by Hosch250** [comment]
Some people are still having trouble with this.  Autoboosh has not been in contact with us for +/- 6 months.
