### ISSUE TITLE
RubberduckParser shouldn't need to know about Inspections

### ISSUE THREAD

**Issue by Vogel612** [rubberduck-vba/Rubberduck#1441]
Right now the Inspections `ObsoleteCallStatement`, `ObsoleteLetStatement`, `EmptyStringLiteral` and `ArgumentListWithOneByRefParameter` are performed during the walk for Declaration Resolution, see
https://github.com/rubberduck-vba/Rubberduck/blob/next/Rubberduck.Parsing/VBA/RubberduckParser.cs#L504

It would be semantically more correct (and more adherent to SRP) to get those out of RubberduckParser and into the process of inspecting the code. This could possibly speed up the Resolving step of the Parser.

Additionally it would allow to remove:

```
ArgListsWithOneByRefParam
EmptyStringLiterals
ObsoleteLetContexts
ObsoleteCallContexts 
``` 

from RubberduckParserState, which greatly simplifies the API and clarifies the responsibilities.

Additionally it would eliminate the discord between those four Listeners and the DeclarationsListener's usage. The four "Inspections" are stateful listeners, they accumulate the results during traversal, the DeclarationListener is Event-Based and passes Declaration instances to RubberduckParserState for accumulation.

**Comment by Hosch250** [comment]
This is because it is much simpler to listen for them as they are called than to try to dig this stuff out of the declarations.  I would agree to get this out of this class, but I would prefer they were still listeners.

**Comment by Vogel612** [comment]
Nothing wrong about keeping them as listeners. The RubberduckParserState keeps the IParseTree that results from Parsing. We can just rewalk it

**Comment by Vogel612** [comment]
Discussion wrt. implementation changes necessary: https://chat.stackexchange.com/transcript/message/29527260#29527260
