### ISSUE TITLE
Resolver issues

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#1446]
`Strings.Format` somehow manages to resolve to `Excel.LegendKey.Format`:

![image](https://cloud.githubusercontent.com/assets/5751684/15103151/de8ccdae-1575-11e6-8e2a-abcf6f4f382d.png)

I suspect we need to be looking for a match against `_B_str_Format` and `_B_var_Format` in the VBA library before moving on to the Excel type library.

---

The supertypes are now accounted for:

![image](https://cloud.githubusercontent.com/assets/5751684/15103817/0be84b18-157e-11e6-8a77-4d4865f2aa82.png)

![image](https://cloud.githubusercontent.com/assets/5751684/15103915/eeb9f7b6-157e-11e6-916c-c5a36f8576e5.png)

Yet...

![image](https://cloud.githubusercontent.com/assets/5751684/15103968/abe3380c-157f-11e6-8e65-3660d9852250.png)

![image](https://cloud.githubusercontent.com/assets/5751684/15103974/bc1a418e-157f-11e6-8e63-5194cf3dd1e4.png)

![image](https://cloud.githubusercontent.com/assets/5751684/15103981/c4ae040c-157f-11e6-9324-27674d7cc71c.png)

@autoboosh did I break something?

**Comment by autoboosh** [comment]
Regarding the first point, could we search for aliases in the type libraries, add them to the declarations and have the declaration finder add the declarations under all possible names? Or does that cause problems somewhere else in the code base if we solve it this way?

The second point is my bad, I should have told you about this:

```
            // TODO: Depending on how the responsibility of looking up built-in interfaces is split up, we might not have to do this here.
            if (potentialClassModule.IsBuiltIn)
            {
                return;
            }
```

I wasn't sure whether you'd link up those type hierarchies directly in the com collector or if the type hierarchy pass should do that. I agree with the approach you've taken though. Removing that code makes everything work:

![workbook](https://cloud.githubusercontent.com/assets/11047288/15122420/5adce912-161f-11e6-8cff-93d50fad2ecd.PNG)

![worksheet](https://cloud.githubusercontent.com/assets/11047288/15122417/580eb8b4-161f-11e6-9ab1-da893ce0ca9d.PNG)

And here's the code from your image so I don't have to type it out again:

```
Public Sub Test()
    Debug.Print ThisWorkbook.Name
    Dim sheet As Worksheet
    Set sheet = ThisWorkbook.Worksheets("Sheets1")
    Debug.Print sheet.Name
End Sub
```

**Comment by retailcoder** [comment]
Removing 'Critical' label; `ThisWorkbook` resolves to "class `ThisWorkbook`"; it's a bug, but not a showstopper.

**Comment by Hosch250** [comment]
`ThisWorkbook` now knows that it is a `Workbook`.  Does this close the remaining part of this issue?
