### ISSUE TITLE
Parse Error: "Dim output"

### ISSUE THREAD

**Issue by dimitrimitropulos** [rubberduck-vba/Rubberduck#1450]
```
Public Function test() as Long
    Dim output As Long
    test = output
End Function
```

This code creates the following parse error
> no viable alternative at input 'Dim output'

I should not that this also happens with ReDim:
```
Public Function test() As Variant
    ReDim output(1) As Variant
    test = output
End Function
```

Perhaps other contexts for using 'output' in VBA will yield parse errors as well?

**Comment by retailcoder** [comment]
Yup. `output` is the problem.

> output is a keyword -_-
had to change the grammar to skip certain keywords otherwise it wouldn't build the correct parse tree for nested if statements and the like

http://chat.stackexchange.com/transcript/message/29545212#29545212

**Comment by dimitrimitropulos** [comment]
just as an aside, this error seemed to apply to ERROR, APPEND, BINARY, OUTPUT, RANDOM, ACCESS, READ, RESET, and WIDTH as well.  It didn't apply to WRITE and SHARED since neither of those will compile.  The 1d3832b fix should account for all of these, but I just thought it relevant to mention.  Some of the keywords that were removed in the 1d3832b fix were not causing this problem, namely EXIT_DO, EXIT_FOR, EXIT_FUNCTION, EXIT_PROPERTY, EXIT_SUB, END_SELECT, END_WITH, ON_ERROR, RESUME_NEXT, READ_WRITE, LOCK_READ, LOCK_WRITE, LOCK_READ_WRITE, LINE_INPUT.

**Comment by autoboosh** [comment]
Thanks for the info.
