### ISSUE TITLE
Parser errors in Single-Line If statements

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#1457]
**If** *condition* **Then** [*statements*] [**Else** *elsestatements*]

*statements* are optional if **Else** is present
*elsestatements* are always optional

both can be 1 or or more statements separated by colons.

The following lines causes a Parser error.

```vb
Sub test()
  
  'This parses
  If False Then Else
  
  'This fails
  If False Then: Else
  
  'This fails
  If False Then MsgBox False: MsgBox False Else
    
  'This fails
  If False Then MsgBox False: MsgBox False Else MsgBox False: MsgBox False
  
  'This fails
  If False Then Else MsgBox True
  
  'This fails
  If False Then MsgBox True Else

End Sub
```

**Comment by dimitrimitropulos** [comment]
I have come across a real world example (for whatever it's worth)

```
    With Application
        If bUpdate Then .Calculation = xlCalculationAutomatic: .Cursor = xlDefault Else .Calculation = xlCalculationManual: .Cursor = xlWait: .EnableEvents = bUpdate: .ScreenUpdating = bUpdate: .DisplayAlerts = bUpdate: .CutCopyMode = False: .StatusBar = False
    End With
```

note that the if statement is one line... :(

**Comment by autoboosh** [comment]
Thanks for those examples, I'll take a look.

**Comment by ThunderFrame** [comment]
Beware the `Do..Loop` construct inside a Single-Line `If Then..Else` statement.

http://stackoverflow.com/a/37163528/5757159

**Comment by autoboosh** [comment]
Thanks for the examples. Single line if statements are weird. At least the second example in the first post (If False Then: Else) shouldn't actually be allowed.

Allowing something like this is also great I think:

```
Public Sub test()
    If True Then 5
5:
End Sub
```

The 5 is interpreted as a GoTo statement. Here's the VBA spec quote:

```
A <statement-label> that occurs as the first element of a <list-or-label> element has the effect 
as if the <statement-label> was replaced with a <goto-statement> containing the same 
<statement-label>. This <goto-statement> takes the place of <line-number-label> in 
<statement-list>.  
```

**Comment by ThunderFrame** [comment]
hmm, using Excel 2013, if I enter:

```vb
    If True Then 5
```
Then VBE autocorrects it to 
```vb
    If True Then GoTo 5
```

**Comment by autoboosh** [comment]
Yes, I noticed. They don't have to though right? It says "has the effect as if the statement-label was replaced with a GoTo". They just went ahead and actually replaced the GoTo.

**Comment by retailcoder** [comment]
That's the VBE assisting Dino-VB coders into writing "modern" VB code (well, "modern" as of 1998); legacy BASIC code had GOTO jumps all over the place (imagine coding without `Sub` or `Function` keywords, and line numbers everywhere) - so to make it easier on the dev BASIC could do `If foo Then 42` to jump to line 42 when `foo` evaluated to `True`.
