### ISSUE TITLE
Parse Error: Deftype B: DefType L: ...

### ISSUE THREAD

**Issue by dimitrimitropulos** [rubberduck-vba/Rubberduck#1458]
The following code:
`DefBool B: DefLng L: DefStr S: DefInt I: DefObj O: DefVar V: DefDbl W`

yeilds the following parse error:
> extraneous input 'DefBool' expecting {<EOF>, ':', REM, NEWLINE, ''', WS, LINE_CONTINUATION}

DefTypes strike again!

**Comment by autoboosh** [comment]
Weird that this ever worked, possibly a regression. The implicit definition declarations right now are only allowed inside of functions, subs etc. I'll have a look. Thanks for the issue.
