### ISSUE TITLE
Parse Error: Special Character In Array Name

### ISSUE THREAD

**Issue by dimitrimitropulos** [rubberduck-vba/Rubberduck#1460]
The following code
```
Public Sub Test()
    Dim a!()
    Dim a@()
    Dim a#()
    Dim a$()
    Dim a%()
    Dim a^()
    Dim a&()
End Sub
```

yields the following error
> no viable alternative at input ')'

for every of the above lines

**Comment by autoboosh** [comment]
The grammar has the type-suffix on the wrong side of the parentheses, will fix. Thanks for mentioning this.
