### ISSUE TITLE
Parser errors

### ISSUE THREAD

**Issue by joshuader6** [rubberduck-vba/Rubberduck#1465]
I've encountert some parser errors: 
The errors occure inside of a form: 
![image](https://cloud.githubusercontent.com/assets/10895412/15171929/ad9054a8-1752-11e6-8765-f4a6125bfefa.png)
when i comment out the `end` then this happens: 
![image](https://cloud.githubusercontent.com/assets/10895412/15171964/e2c2216a-1752-11e6-97ed-142d0b8cf6d2.png)
I hope this helps ^^

EDIT: Im running on commit: 1760189de3248e92e87e685bec1c82e8d3435ada

EDIT2: 
The Second error seems to be caused by a method i use to color a progressbar red: 

```
Private Declare Function SendMessage Lib "user32" Alias "SendMessageA" (ByVal hwnd As Long, ByVal wMsg As Long, ByVal wParam As Long, lParam As Any) As Long

Const WM_USER = &H400
Const PBM_SETBARCOLOR = (WM_USER + 9)

Private Sub UserForm_Initialize()
    SendMessage ProgressBarSmall.hwnd, PBM_SETBARCOLOR, 0, ByVal RGB(177, 0, 55)
End Sub
```

Specifically by the Private Declare line 
If i comment this line out everything works fine.
But when the parser finished after about 5 seconds the VBE shows no response for the following ~20 secs

EDIT3: Now everything gets strange.. i closed the workbook with the function commented out. and now the parser error "Any"  has returned.
even if i remove the  code form the form the error persists

**Comment by autoboosh** [comment]
1. The "End" statement problem is because it's missing in the grammar, we'll fix that
2. Do you have an example for the "Any" problem?
3. The "Declare" problem parses fine though, we'll have to look into that slowdown at the end
4. What parser error has returned in your "EDIT3"? The one in 1. and 2.? The End/Any problems? Or is that something completely different, if so please provide some example code

Thanks!

**Comment by retailcoder** [comment]
Looks like the "Search Results" toolwindow really needs a toolbar with, *at least*, a "Copy" button that copies some of the content to the clipboard.

**Comment by joshuader6** [comment]
Oh sorry the parser error that persists is the "Any" error 
see main issue 

I seem to encounter the same issue whem trying to parse the code of this free addin: [http://www.appspro.com/Utilities/ExcelUtilities.htm](http://www.appspro.com/Utilities/ExcelUtilities.htm)

**Comment by autoboosh** [comment]
Thanks for the info. Do you mind giving us some example code from that addin that's causing the problems?

**Comment by joshuader6** [comment]
well for me it occured when i pressed parse while having the first module in the addin open. 
(it's a simple xla addin without protection so anyone can see the code ^^)

**Comment by joshuader6** [comment]
Okay i updated to commit: 1ca8f8feb860b96c20efe8e50dc753aefa42f187

The "Any" Problem seems to occure randomly 
I don't think it has anything to do with the Code in a module because it persists even if i remove the code in a module so that its just an empty module. 

But today it changed so that the Addin parses fine (i don't see the [(Class), (Module), ... ] status there though. 
And today it targets another Module in my Excel list.

**Comment by joshuader6** [comment]
Well after i ran a code cleaner (exports every module as text and imports them back in) 
i encountert this: 
![image](https://cloud.githubusercontent.com/assets/10895412/15214829/9baa87b0-184f-11e6-90a6-7fabd57a1079.png)

**Comment by autoboosh** [comment]
I can't reproduce the Any problem tbh, the code compiles just fine. The end-statement problem is fixed. The random errors might be based on a problem with the parser. @retailcoder, @Vogel612 any ideas?

**Comment by retailcoder** [comment]
Well I see a problem with the parser errors UI showing up empty, but honestly parser/resolver has been moving faster than my eyes can follow - looks like you fixed it 👍
