### ISSUE TITLE
expose TypeInfo library 

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#1466]
VB6 included TlbInf32.dll which had a type library for traversing Type Libraries, but:
- It isn't licensed for distribution, so it's not widely available.
- It's 32-bit only

If we can already reflect over COM type libraries, a nice side project would be exposing a type library that mimics the original TlbInf32.dll object model (subject to Oracle v. Google).

**Comment by ThunderFrame** [comment]
@awgaya *some* TlbIn32 Type Library documentation https://web.archive.org/web/20101012025255/http://msdn.microsoft.com/en-us/magazine/bb985086.aspx

**Comment by ThunderFrame** [comment]
And the TlbInf32.chm helpfile is available for download here: https://web.archive.org/web/20110401025853/http://support.microsoft.com/kb/224331

The downloaded file is an executable that won't run under Windows 10, but you can just extract the single CHM file with 7-zip.

**Comment by retailcoder** [comment]
out of scope
