### ISSUE TITLE
COM reflection needs to pick up method aliases

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#1475]
If this can't be done, then we'll have to hard-code a little hack to correctly resolve variant/string returning functions in the VBA.Strings module.

**Comment by ThunderFrame** [comment]
I don't have access to OLEViewer, but I *think* the alias names might be found in `_HiddenInterface`, which is hardly a standard approach.

**Comment by comintern** [comment]
Looking at the tlb now and think I might have a handle on this.  The '$' at the end of the function name doesn't look like an alias.  It actually looks like it's treated internally as a type hint. Take for example the `Left` function.  This is in module Strings:

    [entry(616), helpcontext(0x000f6ea1)]
    BSTR _stdcall _B_str_Left(
                    [in] BSTR String, 
                    [in] long Length);
    [entry(617), helpcontext(0x000f653e)]
    VARIANT _stdcall _B_var_Left(
                    [in] VARIANT* String, 
                    [in] long Length);

And this is in interface _HiddenInterface:

    [restricted, helpcontext(0x000f653d)]
    void _stdcall LCase();

A little hard to tell though, oleview appears to be having issues generating an IDL file for it. It might take some poking at with code.

**Comment by retailcoder** [comment]
Removing the *critical* label here, since the inspections that would rely on this are working anyway.

**Comment by Hosch250** [comment]
No they aren't.

**Comment by Hosch250** [comment]
We just hardcoded these.
