### ISSUE TITLE
Parser "any" error

### ISSUE THREAD

**Issue by joshuader6** [rubberduck-vba/Rubberduck#1480]
I'ts me again. 
Now with definitive steps to reproduce: 

1.  install this addin: http://www.appspro.com/Utilities/ExcelUtilities.htm

2. Start excel and open vbe 

3. notice everything seems to have parsed fine: 
![image](https://cloud.githubusercontent.com/assets/10895412/15237951/3710f198-18d3-11e6-836b-171613abb56a.png)

4.  Add some code to the new workbook (notice everything works fine again)
![image](https://cloud.githubusercontent.com/assets/10895412/15237969/60004a2c-18d3-11e6-9698-541d5a8cdedb.png)
(It it a sign that now i've got the (module) in the info ? )

5.  Save the workbook as .xlam and close it

6. open the VBE again and go to the ExcelUtilities Project 

7. hit reparse and watch things go strange Oo
![image](https://cloud.githubusercontent.com/assets/10895412/15238028/13ea367e-18d4-11e6-8df5-dfcb88ddd6f6.png)
(Now the (module) label is also in the xlam project 

So i hope this helps now :)

**Comment by autoboosh** [comment]
That has helped a lot, thanks for the detailed write up.

It looks like there are multiple problems (for future reference):
1. ANY isn't ignored when resolving
2. UserForm.Controls does not only return Control subclasses but also other classes, such as Image
3. External procedure grammar rule is wrong and causes error

I'll have a fix ready sometime soon. #1484 is most likely the same issue.

**Comment by autoboosh** [comment]
The latest PR fixed this one as well. Please give it a try @joshuader6 and tell us if it works.

There's also a new issue for the problem you mentioned in regards to the GUI locking up after Rubberduck has finished the analysis: https://github.com/rubberduck-vba/Rubberduck/issues/1493.

**Comment by joshuader6** [comment]
Sounds Nice i'll give it a shot on Tuesday :)

**Comment by joshuader6** [comment]
Tested and Fixed ! Nice Work :) 
With commit: 3b659333e050038b44e7754340a2a6b8846bdbdc
