### ISSUE TITLE
Wrong inspections

### ISSUE THREAD

**Issue by joshuader6** [rubberduck-vba/Rubberduck#1481]
Following the Process in issue : #1480 
but addidtionally opening a workbook with a lot of code 

i get a huge amount of inspections. 
This inspection is strange though: 
![image](https://cloud.githubusercontent.com/assets/10895412/15238558/88aaf4da-18d9-11e6-9816-c572add2477c.png)

```
option explicit
''' Deletes all names from the ActiveWorkbook.
Public Sub DeleteAllNames(control As IRibbonControl)

    Dim bHasBadNames As Boolean
    Dim objName As Excel.Name
    
    InitGlobals
    
    If Application.ActiveWorkbook Is Nothing Then
        MsgBox gszERR_NO_WORKBOOK, vbCritical, gszAPP_TITLE
        Exit Sub
    End If
    
    Application.ScreenUpdating = False
    Application.EnableEvents = False
    Application.Calculation = xlCalculationManual
    
    On Error GoTo ErrorExit
    
    If Not Application.ActiveWorkbook Is Nothing Then
        If MsgBox(gszMSG_WARN_DELETE_NAMES, vbExclamation + vbYesNo, gszAPP_TITLE) = vbYes Then
            On Error Resume Next
                For Each objName In Application.ActiveWorkbook.Names
                    objName.Delete
                    If Err.Number <> 0 Then bHasBadNames = True
                Next objName
            On Error GoTo ErrorExit
        End If
    End If
    
ErrorExit:
    Application.ScreenUpdating = True
    Application.EnableEvents = True
    Application.Calculation = xlCalculationAutomatic
    
    If bHasBadNames Then MsgBox gszMSG_BAD_NAMES, vbExclamation, gszAPP_TITLE
    
End Sub
```
as you can see objname will be assigned under specific circumstances

**Comment by retailcoder** [comment]
@autoboosh `For Each` loops are counted as assignments, aren't they?

**Comment by retailcoder** [comment]
public void Resolve(VBAParser.ForEachStmtContext context)
        {
            var firstExpression = _bindingService.ResolveDefault(_moduleDeclaration, _currentParent,
                context.valueStmt()[0].GetText(), GetInnerMostWithExpression(), ResolutionStatementContext.Undefined);
            if (firstExpression != null)
            {
                // each iteration counts as an assignment
                _boundExpressionVisitor.AddIdentifierReferences(firstExpression,
                    (exprCtx, identifier, declaration) =>
                        CreateReference(context.valueStmt()[0], identifier, declaration,
                            RubberduckParserState.CreateBindingSelection(context.valueStmt()[0], exprCtx), true));
                // each iteration also counts as a plain usage
                _boundExpressionVisitor.AddIdentifierReferences(firstExpression,
                    (exprCtx, identifier, declaration) =>
                        CreateReference(context.valueStmt()[0], identifier, declaration,
                            RubberduckParserState.CreateBindingSelection(context.valueStmt()[0], exprCtx)));
            }

            for (int exprIndex = 1; exprIndex < context.valueStmt().Count; exprIndex++)
            {
                ResolveDefault(context.valueStmt()[exprIndex], context.valueStmt()[exprIndex].GetText());
            }
        }

**Comment by autoboosh** [comment]
Yes, they should be. Just tested the function in the image in a separate module and it seems fine, no inspection result. Perhaps the inspections are producing results before the resolver is done? I'll try to find out what's up.

**Comment by joshuader6** [comment]
@autoboosh  this only happens when folliwing the process described in #1480
