### ISSUE TITLE
Parse Error: Hidden Module -> "Input"

### ISSUE THREAD

**Issue by dimitrimitropulos** [rubberduck-vba/Rubberduck#1487]
Observe the following code:
```
Sub test()
    Dim s, x
    x = StrPtr(s) ' no parse error
    s = Input(LOF(file1), #file1) ' parse error: missing ':=' at '('
    s = Input$(LOF(file1), #file1) ' parse error: missing ':=' at '('
    s = InputB(LOF(file1), #file1) ' parse error: missing ':=' at '('
    s = InputB$(LOF(file1), #file1) ' parse error: missing ':=' at '('
    x = Width(1, 1) ' no parse error
End Sub
```

I'm not sure if this has anything to do with the fact that `Input`, `Input$`, `InputB`, and `InputB$` are in `_HiddenModule` (where `Array()` lives), but I mostly suspect this is related to #1450 maybe?

**Comment by autoboosh** [comment]
Yes, definitely looks like a similar problem.

Just for reference:
We specify the INPUT statement but without parentheses. INPUTB isn't treated as a statement at all but has filenumber-parameters (e.g. #file1) which normally aren't allowed.
