### ISSUE TITLE
Resolver bug: Argument list compatibility must be checked manually

### ISSUE THREAD

**Issue by autoboosh** [rubberduck-vba/Rubberduck#1492]
This might potentially resolve to the default member of the Range object which is not compatible argument-list-wise:

```
Public Sub Test()
  a = Range("A1")
End Sub
```

It looks like we might have to check compatibility ourselves (at least for index expressions). Here are the rules: [5.3.1.11 Procedure Invocation Argument Processing](https://msdn.microsoft.com/en-us/library/ee156838.aspx).

**Comment by retailcoder** [comment]
Now that built-in parameters have their types resolved, we should be able to validate arg-list compatibility now :smiley:

**Comment by Hosch250** [comment]
Is this obsolete?

**Comment by autoboosh** [comment]
I don't think so, unless you've done some work on it already?

**Comment by retailcoder** [comment]
no need to use argument list to resolve procedure calls, name and scope suffices.
