### ISSUE TITLE
Inspection window: Adding inspections freezes the GUI

### ISSUE THREAD

**Issue by autoboosh** [rubberduck-vba/Rubberduck#1493]
If there are a lot of inspection results the GUI freezes after analysis has been completed. Commenting out the following code has solved the problem:

```
                foreach (var codeInspectionResult in results)
                {
                    Results.Add(codeInspectionResult);
                }
```

It's in InspectionResultsViewModel, lines 186 through 189.

Is there a way to not freeze the GUI? I've tried Binding IsAsync=True as well as creating an ObservableCollection with an AddRange so that change events aren't fired to no avail.

@Hosch250, any ideas? Virtualization of the items perhaps?

**Comment by retailcoder** [comment]
[This could help](http://stackoverflow.com/a/19513181/1188513). It suggests assigning the data source from the code-behind, invoking the UI dispatcher with `DispatcherPriority.Background` - sounds promising.
