### ISSUE TITLE
COM collector: Worksheet Range only has one parameter

### ISSUE THREAD

**Issue by autoboosh** [rubberduck-vba/Rubberduck#1494]
The Worksheet/_Worksheet class should have a property Range with two parameters. Right now though there's only one parameter declaration being created, the second one is missing.

Apparently the Range object that is returned has Range property as well so you can chain calls:

`Range("A1").Range("A2")`

Declared types/AsTypes for parameters would be nice as well.

**Comment by retailcoder** [comment]
Got type info for built-in parameters, members' return type, and fields now.

**Comment by autoboosh** [comment]
Awesome :)

Could you check please if the Range property on the _Worksheet object has two parameters? One required, one optional? I think that was another problem we had.
