### ISSUE TITLE
Logging: Config file and Settings entry?

### ISSUE THREAD

**Issue by autoboosh** [rubberduck-vba/Rubberduck#1497]
I'd like to log a lot more on what the resolver does, especially failed resolutions so we don't have to figure it out ourselves if a user creates an issue.

Questions:
1. Is there an NLog config file already or should we put that into the general config file?
2. Could we perhaps a logging section to the settings dialog so that the user can configure the log level (e.g. debug, only errors, etc.) and perhaps even the location of the log file?
3. "Rotating" log files? After like 5MB, automatically create a new log file?
4. Auto-cleanup log files?

Thoughts?

**Comment by retailcoder** [comment]
We're a type library project (dll); as such, nlog configuration won't load from the config files, but the setup work is already done and a Windows EventLog event source is getting created (ref. #746) - so all we need to do is constructor-inject an `ILogger` (and possibly set up the bindings for it), but we could also consider adding the ninject logging extension for this.

**Comment by retailcoder** [comment]
I agree that a settings page for logging options would be useful; perhaps make it an opt-in feature, so we don't log things by default, and then allow setting trace/debug/info/warning/error minimum level being output to logs. If we set up multiple targets we could toggle logging to Windows EventLog and to a text log file - user could pick which targets to enable, ...and then the next step is a "report this problem" dialog that creates a new github issue lol

**Comment by Vogel612** [comment]
This would mean retroactively adding logging code to the whole codebase, correct? 

We should consider something like an Aspect-Oriented approach for trace-level logging. Additionally that would mean we can banish all `Debug.WriteLine` and related statements in favor of Logger-Calls.

I'd like to have a clear standard on what to log when and how. Huge Projects tend to be inconsistent in that regard and that makes working with the logs a fight :angry:

**Comment by retailcoder** [comment]
@Vogel612 what I like about NLog is how easy it makes sorting out log entries; we just need to make the format/layout CSV-compatible and then logs could easily be viewed and filtered in Excel.

However AOP is opposed to DI, and I'm not changing the paradigm here (DI addresses *aspects* through *interception*) - however IoC of logging seems much overkill here, as it's not hindering anything in tests, and it's not like we're going to swap the logging framework anytime.

**Comment by autoboosh** [comment]
Implemented in  #1563 and #1571.

There's a "enable detailed logging" option in the general settings now that enables Debug+Trace log messages. When disabled only messages with Level Info or above are logged. This is for files.
The event log only records error messages. The debug output window always shows everything.

**Comment by retailcoder** [comment]
Is there an option to switch off logging altogether?

**Comment by autoboosh** [comment]
No, there's only an option to reduce logging, the idea being that we still want to be notified of the worst things that happen. The log is configured so that each file is not bigger than 5MB and should I think be overwritten after 9 log files after created (I haven't tested that last part though).

**Comment by autoboosh** [comment]
Do you want an option to switch it off altogether? Perhaps I was being too quick in closing this issue?

**Comment by retailcoder** [comment]
Yeah, some users (and IT departments) may not want ducky to log things.

**Comment by autoboosh** [comment]
The user can now select the log level (or turn the logging off entirely). There's a dropdown for it in the general settings.
