### ISSUE TITLE
Parser bug: Circle and Scale are special

### ISSUE THREAD

**Issue by autoboosh** [rubberduck-vba/Rubberduck#1498]
There are two special forms that can't be parsed currently: [Circle](https://msdn.microsoft.com/en-us/library/office/aa221156(v=office.11).aspx) and [Scale](https://msdn.microsoft.com/en-us/library/office/aa221585(v=office.11).aspx). The reason is that they have a special syntax that differs from normal function calls.

Should we add those two or simply not support them? We could add circleSpecialForm and scaleSpecialForm to the grammar.

**Comment by retailcoder** [comment]
How are they currently being handled? They break the parse tree?

**Comment by autoboosh** [comment]
Yeah, it's a parser error.

**Comment by retailcoder** [comment]
Hmm let's special-case them then; their argument list may contain valuable identifier references :-)

**Comment by ThunderFrame** [comment]
https://msdn.microsoft.com/en-us/library/9dtfzwyx%28v=vs.90%29.aspx

Might need to consider other methods like:
Line
Point
Print
PSet

And there are some properties too (these might be similar to the resolver issues with properties of an Excel worksheet)
ScaleWidth
ScaleHeight
