### ISSUE TITLE
Application log event source is wrong

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#1504]
> 3>------ Build started: Project: Rubberduck, Configuration: Debug Any CPU ------
> 3>  Restoring NuGet packages...
> 3>  To prevent NuGet from downloading packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages'.
> 3>  All packages listed in packages.config are already installed.
> 3>  
> **3>  SUCCESS: An event of type 'INFORMATION' was created in the 'APPLICATION' log with 'RubberDuck.VBE' as the source.**

The event source should be `Rubberduck-VBA`.

**Comment by autoboosh** [comment]
Fixed with  #1563.
