### ISSUE TITLE
Parser: More special forms

### ISSUE THREAD

**Issue by autoboosh** [rubberduck-vba/Rubberduck#1505]
@ThunderFrame mentioned in a different issue that there are more special forms. Quote:

> https://msdn.microsoft.com/en-us/library/9dtfzwyx%28v=vs.90%29.aspx
> 
> Might need to consider other methods like:
> Line
> Point
> Print
> PSet
> 
> And there are some properties too (these might be similar to the resolver issues with properties of an Excel worksheet)
> ScaleWidth
> ScaleHeight

ScaleWidth and ScaleHeight seem to have normal syntax, so we don't have to add special rules for them. Do you have a complete list of these special forms somewhere?

Also it seems that these are VB6 methods? What's the idea here, should Rubberduck support these?

**Comment by retailcoder** [comment]
I reopened #298, so... eventually :smiley:

**Comment by Hosch250** [comment]
We handled Line recently, and Print and PSet look normal:

https://msdn.microsoft.com/en-us/library/office/ff195586.aspx
https://msdn.microsoft.com/en-us/library/office/ff197683.aspx

**Comment by mansellan** [comment]
So, now that #298 is closed, this needs revisiting. VB6 PSet has a funky syntax which our grammar hates:

Pset (x , y ), color

Note though that PSet exists on other objects (for example, PictureBox) where it follows a standard syntax.

**Comment by Vogel612** [comment]
IIRC we already have a line special form in the grammar: 

https://github.com/rubberduck-vba/Rubberduck/blob/92067d7904d3f2734765d79c9c6dd1e7ef3d94b1/Rubberduck.Parsing/Grammar/VBAParser.g4#L552

**Comment by Vogel612** [comment]
Suggested patch:

```
psetSpecialForm: (expression whitespace? DOT whitespace?)? PSET whiteSpace (STEP whiteSpace?)? tuple whiteSpace? (COMMA whiteSpace? expression)?
```
