### ISSUE TITLE
Error when renaming project

### ISSUE THREAD

**Issue by Zak-Michael-Armstrong** [rubberduck-vba/Rubberduck#1506]
Installed Version: Rubberduck 2.0 Alpha Preview (Hotfix 1)

Almost certainly related to issue #1485 but with an MCVE and slightly different error message this time.

MCVE:

Close Excel. 
Open Excel.
Create New Workbook.
Open IDE.

Rename project to `TestRename_1`. No Error.
Open `sheet1` code module. 
Write:
```
Option Explicit

Sub stuff()

End Sub
```
Rename project to `TestRename`. No Error.

Change to:
```
Option Explicit

Sub stuff()

'/ very curious

End Sub
```
Rename project to `TestRename_1`. Error (though the project *does* get renamed in the folder view before the error message appears). Error then repeats upon every subsequent renaming.

![1234](https://cloud.githubusercontent.com/assets/13286014/15274584/8cd37bb0-1aad-11e6-9e9f-654418c188bc.png)

Full Error Text:

> Unhandled exception has occurred in a component in your application. If you click Continue, the application will ignore this error and attempt to continue.
>
> Sequence contains more than one matching element.
>
> Details:
>
> System.InvalidOperationException: Sequence contains more than one matching element
>    at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
>    at Rubberduck.Parsing.VBA.RubberduckParserState.SetModuleState(VBComponent component, ParserState state, SyntaxErrorException parserError) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\Rubberduck.Parsing\VBA\RubberduckParserState.cs:line 193
>    at Rubberduck.Parsing.VBA.RubberduckParser.ParseAll() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\Rubberduck.Parsing\VBA\RubberduckParser.cs:line 149
>    at Rubberduck.Parsing.VBA.RubberduckParser.ReparseRequested(Object sender, ParseRequestEventArgs e) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\Rubberduck.Parsing\VBA\RubberduckParser.cs:line 77
>    at Rubberduck.Parsing.VBA.RubberduckParserState.OnParseRequested(Object requestor, VBComponent component) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\Rubberduck.Parsing\VBA\RubberduckParserState.cs:line 534
>    at Rubberduck.App.<sink_ProjectRenamed>d__12.MoveNext() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\App.cs:line 313
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__0(Object state)
> 
> 
> ************** Loaded Assemblies **************
> mscorlib
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.0.30319.18063 built by: FX45RTMGDR
>     CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
> ----------------------------------------
> Rubberduck
>     Assembly Version: 2.0.0.2650
>     Win32 Version: 2.0.0.0
>     CodeBase: file:///C:/ProgramData/Rubberduck/Rubberduck.DLL
> ----------------------------------------
> Ninject
>     Assembly Version: 3.2.0.0
>     Win32 Version: 3.2.2.0
>     CodeBase: file:///C:/ProgramData/Rubberduck/Ninject.DLL
> ----------------------------------------
> Ninject.Extensions.Factory
>     Assembly Version: 3.2.0.0
>     Win32 Version: 3.2.1.0
>     CodeBase: file:///C:/ProgramData/Rubberduck/Ninject.Extensions.Factory.DLL
> ----------------------------------------
> System.Core
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.0.30319.17929 built by: FX45RTMREL
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
> ----------------------------------------
> System
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.0.30319.34238 built by: FX452RTMGDR
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
> ----------------------------------------
> Castle.Core
>     Assembly Version: 3.2.0.0
>     Win32 Version: 3.2.0.14
>     CodeBase: file:///C:/ProgramData/Rubberduck/Castle.Core.DLL
> ----------------------------------------
> Microsoft.Vbe.Interop
>     Assembly Version: 15.0.0.0
>     Win32 Version: 15.0.4823.1001
>     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/Microsoft.Vbe.Interop/15.0.0.0__71e9bce111e9429c/Microsoft.Vbe.Interop.dll
> ----------------------------------------
> Rubberduck.Parsing
>     Assembly Version: 2.0.5959.2646
>     Win32 Version: 2.0.0.0
>     CodeBase: file:///C:/ProgramData/Rubberduck/Rubberduck.Parsing.DLL
> ----------------------------------------
> System.Windows.Forms
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.0.30319.34251 built by: FX452RTMGDR
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
> ----------------------------------------
> System.Drawing
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.0.30319.18021 built by: FX45RTMGDR
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
> ----------------------------------------
> Rubberduck.VBEditor
>     Assembly Version: 1.0.5959.2645
>     Win32 Version: 1.0.0.0
>     CodeBase: file:///C:/ProgramData/Rubberduck/Rubberduck.VBEditor.DLL
> ----------------------------------------
> Rubberduck.SourceControl
>     Assembly Version: 1.0.0.0
>     Win32 Version: 1.0.0.0
>     CodeBase: file:///C:/ProgramData/Rubberduck/Rubberduck.SourceControl.DLL
> ----------------------------------------
> Rubberduck.SmartIndenter
>     Assembly Version: 1.0.0.0
>     Win32 Version: 1.0.0.0
>     CodeBase: file:///C:/ProgramData/Rubberduck/Rubberduck.SmartIndenter.DLL
> ----------------------------------------
> PresentationCore
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.0.30319.18060 built by: FX45RTMGDR
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
> ----------------------------------------
> WindowsBase
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.0.30319.18060 built by: FX45RTMGDR
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
> ----------------------------------------
> PresentationFramework
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.0.30319.18060
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll
> ----------------------------------------
> System.Xaml
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.0.30319.18015 built by: FX45RTMGDR
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
> ----------------------------------------
> office
>     Assembly Version: 15.0.0.0
>     Win32 Version: 15.0.4823.1002
>     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/office/15.0.0.0__71e9bce111e9429c/office.dll
> ----------------------------------------
> System.Windows.Interactivity
>     Assembly Version: 4.0.0.0
>     Win32 Version: 2.0.20525.0
>     CodeBase: file:///C:/ProgramData/Rubberduck/System.Windows.Interactivity.DLL
> ----------------------------------------
> Ninject.Extensions.Conventions
>     Assembly Version: 3.2.0.0
>     Win32 Version: 3.2.0.0
>     CodeBase: file:///C:/ProgramData/Rubberduck/Ninject.Extensions.Conventions.DLL
> ----------------------------------------
> Antlr4.Runtime.net45
>     Assembly Version: 4.3.0.0
>     Win32 Version: 4.3.0.0
>     CodeBase: file:///C:/ProgramData/Rubberduck/Antlr4.Runtime.net45.DLL
> ----------------------------------------
> Ninject.Extensions.NamedScope
>     Assembly Version: 3.2.0.0
>     Win32 Version: 3.2.0.0
>     CodeBase: file:///C:/ProgramData/Rubberduck/Ninject.Extensions.NamedScope.DLL
> ----------------------------------------
> System.Configuration
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.0.30319.18060 built by: FX45RTMGDR
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
> ----------------------------------------
> System.Xml
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.0.30319.34234 built by: FX452RTMGDR
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
> ----------------------------------------
> DynamicProxyGenAssembly2
>     Assembly Version: 0.0.0.0
>     Win32 Version: 3.2.0.14
>     CodeBase: file:///C:/ProgramData/Rubberduck/Castle.Core.dll
> ----------------------------------------
> DynamicProxyGenAssembly2
>     Assembly Version: 0.0.0.0
>     Win32 Version: 3.2.0.14
>     CodeBase: file:///C:/ProgramData/Rubberduck/Castle.Core.dll
> ----------------------------------------
> WindowsFormsIntegration
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.0.30319.18060 built by: FX45RTMGDR
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/WindowsFormsIntegration/v4.0_4.0.0.0__31bf3856ad364e35/WindowsFormsIntegration.dll
> ----------------------------------------
> Infralution.Localization.Wpf
>     Assembly Version: 3.3.0.0
>     Win32 Version: 3.3.0.0
>     CodeBase: file:///C:/ProgramData/Rubberduck/Infralution.Localization.Wpf.dll
> ----------------------------------------
> PresentationFramework.Aero
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.0.30319.17929 built by: FX45RTMREL
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework.Aero/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.Aero.dll
> ----------------------------------------
> Anonymously Hosted DynamicMethods Assembly
>     Assembly Version: 0.0.0.0
>     Win32 Version: 4.0.30319.18063 built by: FX45RTMGDR
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
> ----------------------------------------
> Microsoft.GeneratedCode
>     Assembly Version: 1.0.0.0
>     Win32 Version: 4.0.30319.34234 built by: FX452RTMGDR
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
> ----------------------------------------
> NLog
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.0.0.0
>     CodeBase: file:///C:/ProgramData/Rubberduck/NLog.DLL
> ----------------------------------------
> System.ServiceModel
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.0.30319.34234 built by: FX452RTMGDR
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel/v4.0_4.0.0.0__b77a5c561934e089/System.ServiceModel.dll
> ----------------------------------------
> System.Data
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.0.30319.18047 built by: FX45RTMGDR
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
> ----------------------------------------
> System.Runtime.Serialization
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.0.30319.34234 built by: FX452RTMGDR
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
> ----------------------------------------
> Accessibility
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.0.30319.17929 built by: FX45RTMREL
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
> ----------------------------------------
> PresentationFramework-SystemXml
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.0.30319.17929
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework-SystemXml/v4.0_4.0.0.0__b77a5c561934e089/PresentationFramework-SystemXml.dll
> ----------------------------------------
> UIAutomationTypes
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.0.30319.17929 built by: FX45RTMREL
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/UIAutomationTypes/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationTypes.dll
> ----------------------------------------
> CustomMarshalers
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.0.30319.17929 built by: FX45RTMREL
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/CustomMarshalers/v4.0_4.0.0.0__b03f5f7f11d50a3a/CustomMarshalers.dll
> ----------------------------------------
> stdole
>     Assembly Version: 7.0.3300.0
>     Win32 Version: 7.00.9466
>     CodeBase: file:///C:/Windows/assembly/GAC/stdole/7.0.3300.0__b03f5f7f11d50a3a/stdole.dll
> ----------------------------------------
> Microsoft.GeneratedCode
>     Assembly Version: 1.0.0.0
>     Win32 Version: 4.0.30319.34234 built by: FX452RTMGDR
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
> ----------------------------------------
> Microsoft.CSharp
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.0.30319.17929
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
> ----------------------------------------
> PresentationFramework-SystemData
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.0.30319.17929
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework-SystemData/v4.0_4.0.0.0__b77a5c561934e089/PresentationFramework-SystemData.dll
> ----------------------------------------
> System.Numerics
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.0.30319.17929 built by: FX45RTMREL
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
> ----------------------------------------
> 
> ************** JIT Debugging **************
> To enable just-in-time (JIT) debugging, the .config file for this
> application or computer (machine.config) must have the
> jitDebugging value set in the system.windows.forms section.
> The application must also be compiled with debugging
> enabled.
> 
> For example:
> 
> <configuration>
>     <system.windows.forms jitDebugging="true" />
> </configuration>
> 
> When JIT debugging is enabled, any unhandled exception
> will be sent to the JIT debugger registered on the computer
> rather than be handled by this dialog box.

**Comment by Hosch250** [comment]
I don't have any evidence, but I'm almost positive this is a cache invalidation bug.  Last night I found some curious behavior where even after a value was removed from the cache (and was gone in the debug view), subsequent calls would return the element as part of the list.  I'm almost positive that this is the same problem here, and it results in a duplicate value because the old `TestRename_1` element is still in the dictionary, resulting in the error that the value already exists in the dictionary.

**Comment by retailcoder** [comment]
@Hosch250 can this issue be closed now?

**Comment by retailcoder** [comment]
> Rename project to TestRename. No Error.

I don't get that far. Full-on crash, host process dies.

**Comment by Hosch250** [comment]
First time, this either appears to succeed or displays an error about the mscorlib crashing with a TargetInvocationException.  Second time, it doesn't work at all.

**Comment by Hosch250** [comment]
> The sequence contains no matching element.
>    bei System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   bei Rubberduck.SourceControl.GitProvider.get_CurrentBranch() in c:\Users\Mathieu\Source\Repos\Rubberduck\Rubberduck.SourceControl\GitProvider.cs:Zeile 83.

Hmm.

**Comment by retailcoder** [comment]
Not exactly a repro (another different stack trace), but...

        public void AddNodes(List<Declaration> declarations)
        {
            var parents = declarations.GroupBy(item => item.ComponentName).OrderBy(item => item.Key).ToList();
            foreach (var component in parents)
            {
                try
                {
                    var moduleName = component.Key;
                    var parent = declarations.Single(item =>  /*  <<<<< here */
                        ComponentTypes.Contains(item.DeclarationType) && item.ComponentName == moduleName);
                    var members = declarations.Where(item =>
                        !ComponentTypes.Contains(item.DeclarationType) && item.ComponentName == moduleName);

                    AddChild(new CodeExplorerComponentViewModel(this, parent, members));
                }
                catch (InvalidOperationException exception)
                {
                    Console.WriteLine(exception);
                }
            }
        }

@Hosch250 definitely a caching thing.
