### ISSUE TITLE
Resolver bug/feature: Continue resolving even if some parts fail to resolve

### ISSUE THREAD

**Issue by autoboosh** [rubberduck-vba/Rubberduck#1509]
Example code:

`Range(variableA, variableB)`

If Range can't be resolved it would be nice to still resolve variableA + variableB.

**Comment by retailcoder** [comment]
Adding *critical*, since this causes variable references to be unaccounted for, which throws off *extract method*, makes *rename* break the code, and inspections yield false positive.

**Comment by autoboosh** [comment]
This should work with the latest PR. I'll go ahead and close this then if that's OK.
