### ISSUE TITLE
Adding a test method should trigger a refresh

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#1514]
Repro:

 - Add a new test module
 - Add a new test method from the test explorer

Adding the test module triggers a refresh, and the code explorer displays the members automatically; adding a test method should also trigger a refresh then.

The test module's state should be set to `Pending` upon adding a test method; it currently remains `Ready` although the code in the IDE is known to be out of sync with the parser state.

**Comment by retailcoder** [comment]
This non-refreshing has a nasty side-effect. Repro:

 - Add a new test module
 - Add a new test method
 - Refresh manually: `TestMethod1` is now in both the Code Explorer and the Test Explorer.
 - Add a new test method - it's named `TestMethod2`
 - Add another test method - it's *also* named `TestMethod2` because the previous one is not "discovered" yet.
 - Refresh manually: code will parse fine, but will not compile, and parser state will be `ResolverError`.

Side note, I would expect a resolver error to **not** affect the contents of the Code Explorer, which only needs to work off declarations.

Fun facts: refreshing manually again, will parse to a `Ready` state, and the two `TestMethod2` members will show up in the Code Explorer; only one of them will show up in the Test Explorer though (which is expected).

**Comment by Vogel612** [comment]
@retailcoder wrt. the sidenote: I'd assume that the CE won't be run when you don't hit the `Ready`-State.... If you open a separate issue, I'll investigate and fix
