### ISSUE TITLE
Code Explorer Excel Sheetnames

### ISSUE THREAD

**Issue by joshuader6** [rubberduck-vba/Rubberduck#1519]
To fully replace the Native Project explorer the CodeExplorer should display the Sheetnames 

Current:
![image](https://cloud.githubusercontent.com/assets/10895412/15313027/bc76d450-1c08-11e6-8fe9-5c4546b83392.png)
Current Native: 
![image](https://cloud.githubusercontent.com/assets/10895412/15313049/e7a9a30a-1c08-11e6-9697-39d89727116a.png)

**Comment by retailcoder** [comment]
@Hosch250 I'm not sure if it's host-agnostic, but you'll need to look at the `VBComponent.Properties`, find the correct property by name /verify it exists, and pull its value. I say "just too bad" if it doesn't work anywhere other than in Excel.
