### ISSUE TITLE
Parser Ignore Projects

### ISSUE THREAD

**Issue by joshkreud** [rubberduck-vba/Rubberduck#1520]
Like already mentioned in Chat a few days ago. 

With some addins installed the Parser does the unnecessary work of parsing these.

So how about a setting to ignore some projects ?
this of course only if there are no references from a parsed project to the ignored project

**Comment by retailcoder** [comment]
ref. #2006

**Comment by SystemsModelling** [comment]
Bump.
I'd like RD to operate on only the activeproject, rather than all.
Or maybe have an option for All if I feel like it.
But there's no point in reparsing the addins over and over again.

**Comment by retailcoder** [comment]
We parse all unlocked projects in the IDE, then use what we know to resolve references - if the active project is referencing another project, we'll pick that up and keep things consistent. Without it, identifier references to other projects would resolve to undeclared variables. We only ever get the parse trees for modified modules though.

We do need a better approach to clear identifier references though; leaving unreferenced projects alone would be a good start indeed.
