### ISSUE TITLE
Exclamation marks in square brackets break the parser

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#1521]
Adding an exclamation inside a square brackets breaks the parser.... Looks like square brackets inside square brackets is also a problem, as are empty square brackets.

If you have code like this, I feel sorry for you.

We should probably have an inspection for these implicit `ActiveWorkbook` calls

```vb
Option Explicit

Sub FooFoo()
  
  Dim Foo As Variant
  Foo = "Bar"
  
  'ActiveWorkbook...
  [Sheet2!A2] = Foo
  Foo = [Sheet2!A2]

  'Implicit Links
  [[Book2]Sheet1!A1] = Foo
  Foo = [[Book2]Sheet1!A1]

  [Book2!NamedRange] = Foo
  Foo = [Book2!NamedRange]

  Foo = ["Hello World!"]

  Foo = ["!"]
  Foo = ["[]"]

  Foo = []

End Sub
```

**Comment by retailcoder** [comment]
I don't know.. what's that shorthand syntax expanding to? If it ends up with a call to members of the `Sheet2` global object, then it's an explicit reference to a qualified address and there's not much to fix there except perhaps the late-binding (or is it early-bound?)

That said I'm also ok with blowing up when that square bracket syntax is encountered. Isn't that syntax outright lazy?

**Comment by ThunderFrame** [comment]
I'm unsure which shorthand you meant.

So I'm repeating the code, but adding comments....

```vb
Option Explicit

Sub FooFoo()

  Dim Foo As Variant
  Foo = "Bar"

  'Relies on Sheet2 being in ActiveWorkbook, not ThisWorkbook...
  [Sheet2!A2] = Foo
  Foo = [Sheet2!A2] 'Foo = "Bar"

  'Implicit Links (as in, there isn't an explicit link in Workbook Links or in vbProject References)
  'Relies on Book2 being an open Workbook in this Excel application
  [[Book2]Sheet1!A1] = Foo
  Foo = [[Book2]Sheet1!A1] 'Foo = "Bar"

  'NamedRange is a workbook defined name
  [Book2!NamedRange] = Foo
  Foo = [Book2!NamedRange] 'Foo = "Bar"

  Foo = ["Hello World!"] 'Foo = "Hello World!"

  Foo = ["!"] 'Foo = "!"
  Foo = ["[]"] 'Foo = "[]"

  Foo = [] 'Foo = xlErrValue = Error 2015

End Sub
```

**Comment by grleachman** [comment]
["  "]  === Evaluate("  ")
[  ] == Application.Evaluate, Worksheet.Evaluate, Chart.Evaluate

[]  is Evaluate()  

https://msdn.microsoft.com/en-us/library/office/ff193019.aspx

**Comment by ThunderFrame** [comment]
Indeed, but this is valid:
```
  Foo = Evaluate("[")
```

But, MSDN doesn't tell you how to escape `[`, so this doesn't compile:

```
  Foo = ["["]
```

**Comment by autoboosh** [comment]
That fix I made is wrong. Looks like this has to be a parser rule instead of a simple token to allow entire trees of foreign names?

My interpretation of the VBA spec was that something like this:

`a = [A1] + [A2]`

would yield one single foreign name, since the token allows anything except newlines. Nesting foreign identifiers shouldn't be allowed either...

@ThunderFrame's last example should actually be allowed according to spec:

`Foo = ["["]`

I'll change the grammar...

**Comment by autoboosh** [comment]
This should work with the latest PR.
