### ISSUE TITLE
Problems with source control

### ISSUE THREAD

**Issue by INOPIAE** [rubberduck-vba/Rubberduck#1529]
Working with 67967a6 on Excel 2010
I opened a repo that was created about two month ago. When I now change the branch I get this error
![image](https://cloud.githubusercontent.com/assets/2772829/15347732/a561c1e6-1cc4-11e6-9519-a2697a5c35b0.png)

**Comment by INOPIAE** [comment]
With commit 760ec98 I do NOT get this error anymore

**Comment by Hosch250** [comment]
Just to help prevent this even more, I'm going to disable the sinks from firing parses when we load/unload components, as happens during branch switches.
