### ISSUE TITLE
Inspections: Left to Left$ gone wrong

### ISSUE THREAD

**Issue by joshuader6** [rubberduck-vba/Rubberduck#1531]
It's trying to add the $ to the wrong place:
![image](https://cloud.githubusercontent.com/assets/10895412/15353440/58aa5780-1ce9-11e6-925a-12b498f678c8.png)

```
Option Explicit

Public Function tester() As String

Dim str As String

str = "teeeeeeeeeeeeeeeeeest"


tester = Left(str, 4)

End Function
```

Should be Left$(arg,arg) not Left(arg,arg)$. the latter doesn't compile.

But anyway the parser seems to be getting more stable ^^ it doesn't crash as much as just a few days before :) great work !

**Comment by Vogel612** [comment]
Whoops that's my fault there. The localization logic there had to change, but I failed to correctly inject the $ when putting the Second argument to the QuickFix caption in there. 

https://github.com/rubberduck-vba/Rubberduck/blob/next/RetailCoder.VBE/Inspections/UntypedFunctionUsageInspectionResult.cs#L32

If I read the code correctly that also results in a bugged call to that method :disappointed: 

        public override void Fix()
        {
            var originalInstruction = Context.GetText();
            var newInstruction = originalInstruction + "$";
            var selection = Selection.Selection;

            var module = Selection.QualifiedName.Component.CodeModule;
            var lines = module.get_Lines(selection.StartLine, selection.LineCount);

            var result = lines.Replace(originalInstruction, newInstruction);
            module.ReplaceLine(selection.StartLine, result);
            // FIXME trigger reparse
        }

**Comment by joshuader6** [comment]
The $ gets applied at the correct position now but it wants to do this multiple times.
Also the inspection is duplicated (notice the difference on the selection )
![image](https://cloud.githubusercontent.com/assets/10895412/15385587/d7a54e5a-1da2-11e6-8dfc-20850539a0ef.png)
![image](https://cloud.githubusercontent.com/assets/10895412/15385589/dc99938a-1da2-11e6-9f71-7beebfb4869b.png)
![image](https://cloud.githubusercontent.com/assets/10895412/15385601/f7d79ab6-1da2-11e6-9642-7b229ca032e0.png)
