### ISSUE TITLE
Parser & resolver debug output should be logged

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#1541]
We've been talking about it for a while, but haven't implemented it.

The resolver currently outputs to the debug output, which is useful for us devs, but doesn't compile into a release build, and makes tracing of post-release resolver issues pretty much impossible.

Let's get the ball rolling with NLog-logging to a file target, make the current debug output `DEBUG` level, and add some `TRACE` level entries at a finer granularity, so we can trace resolver execution without requiring the actual VBA code.

This needs to be an opt-in feature, so we'll need a checkbox somewhere in the settings dialog to enable logging.

Ref. #737 , #746 , #1497

**Comment by autoboosh** [comment]
Implemented in  #1563 and #1571.

There's a "enable detailed logging" option in the general settings now that enables Debug+Trace log messages. When disabled only messages with Level Info or above are logged. This is for files.
The event log only records error messages. The debug output window always shows everything.
