### ISSUE TITLE
Rubberduck CommandBar context-sensitive selection should display type information

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#1543]
Currently when you select an identifier reference, you know it's a *variable* or a *parameter*, or whatever its `DeclarationType` is - which is great. Let's add the type name in there.

[This is where it's at](https://github.com/rubberduck-vba/Rubberduck/blob/ba6ef311e8585ee9489e455b6605594310ff0c45/RetailCoder.VBE/UI/Command/MenuItems/RubberduckCommandBar.cs#L59-L63):

                _selectionButton.Caption = string.Format("{0} ({1}): {2} ({3})", 
                    declaration.QualifiedName.QualifiedModuleName,
                    declaration.QualifiedSelection.Selection,
                    declaration.IdentifierName,
                    RubberduckUI.ResourceManager.GetString("DeclarationType_" + declaration.DeclarationType));

So this makes the text be like `VBAProject.Module1 (L23C6): Foo (Variable)`.

I'd rather it be like `VBAProject.Module1 (L23C6): Foo (Variable: Integer)` or something like it.

**Comment by Vogel612** [comment]
Fixed with #1578
