### ISSUE TITLE
Indent > Current procedure menu item is available when no CodePanes are open.

### ISSUE THREAD

**Issue by comintern** [rubberduck-vba/Rubberduck#1546]
...and throws a NRE in `IndentCurrentProcedure()` when clicked:

![screenshot from 2016-05-19 18 06 04](https://cloud.githubusercontent.com/assets/8944005/15412462/62273b02-1ded-11e6-99d5-0526cc44e856.png)

**Comment by Hosch250** [comment]
Sheet1 is the SelectedVBComponent (or whatever that member is called) because it is selected in the Project Explorer.  That value is what it is based off of.

**Comment by retailcoder** [comment]
@Hosch250 wasn't that command activating the VBComponent? ...it should.

**Comment by comintern** [comment]
Should you be able to indent modules that aren't open?  Currently, it looks like the Indenter requires a CodePane to be active:

        public void IndentCurrentProcedure()
        {
            var pane = _vbe.ActiveCodePane;
            var module = pane.CodeModule;
            var selection = GetSelection(pane);

**Comment by Hosch250** [comment]
Hmm, looks like a bug.  I'll take a look.

**Comment by Hosch250** [comment]
Whoops, my problem.  This doesn't override CanExecute, so it is always enabled.
