### ISSUE TITLE
GIthub integration crashes upon starting

### ISSUE THREAD

**Issue by Zak-Michael-Armstrong** [rubberduck-vba/Rubberduck#1551]
When I open excel in the morning, first thing I do is open the IDE and load my repository. I've been working on this project for a couple of weeks, but starting 2/3 days ago, Excel crashes when I attempt to load it:

![image](https://cloud.githubusercontent.com/assets/13286014/15421561/e7ae9d64-1e6b-11e6-87b4-9b6c4df97fa9.png)

If however, I load a different, smaller repository first. Then, once that's online, I re-load the original, there is no problem and everything continues as normal.

The (large) repository in question has about 80 commits at the moment, and is about 2.5MB in size.

**Comment by retailcoder** [comment]
Does your source control config file look healthy?

**Comment by Zak-Michael-Armstrong** [comment]
The issue has gone away. It went away after I went into my github repo and deleted all the code modules (.bas) that are no longer in my project.

**Comment by Hosch250** [comment]
I don't think I can do anything about this for existing repos very cleanly, but if you go through RD, any components removed from the VBE should be deleted from the repo as well since #1750.
