### ISSUE TITLE
Exception Testing for Unit Tests (Feature Request)

### ISSUE THREAD

**Issue by Zak-Michael-Armstrong** [rubberduck-vba/Rubberduck#1568]
Having some way to `Assert` that a method raises a particular exception when given incorrect input.

Currently, I can't test method behavior with incorrect input because the method itself will raise an exception.

**Comment by grleachman** [comment]
Private Function ITestRunner_AssertErrorThrown(obj As Object, ByVal method As String)
    Dim errThrown As Boolean
    On Error Resume Next
    CallByName obj, method, VbMethod
    If Err.Number <> 0 Then
        errThrown = True
    End If
    m_Reporter.report errThrown, "error not thrown"
    
End Function

**Comment by ThunderFrame** [comment]
I just want to refactor that `If` block to

```
errThrown = Err.Number <> 0
```

**Comment by grleachman** [comment]
right back at you
m_Reporter.report (Err.Number <> 0), "error not thrown"

:)

**Comment by ThunderFrame** [comment]
Where'd you go @grleachman ?

**Comment by retailcoder** [comment]
The 'expected error' test method template was made for this. A VBA runtime
error looks like any other useless COMException from managed code, it's
simpler to handle them in VBA and fail the test when the error raised isn't
the expected one (or if no error is raised at all).

**Comment by retailcoder** [comment]
@ThunderFrame @grleachman the difference is that the "expected error" test template will only pass the test when a specific error is raised; passing the test when *any error* is raised doesn't seem very solid to me.
