### ISSUE TITLE
Don't allow VbProjects with the default name to be used to create new repositories

### ISSUE THREAD

**Issue by ckuhn203** [rubberduck-vba/Rubberduck#157]
Every new VBA Project is named `VBAProject`. This will cause far too much ambiguity when it comes to working with Source Control. Force the user to rename their project (and give them some help doing so. Make it easy to do from where ever they're creating the new repo).

**Comment by ckuhn203** [comment]
See discussion on #399.

**Comment by Hosch250** [comment]
Should this still be open?  Would naming the Git repo something like 'FileName_ProjectName' resolve this issue?

**Comment by ckuhn203** [comment]
Yeah. Still an issue that needs resolved.

**Comment by ThunderFrame** [comment]
Could you perhaps take advantage of VB extension attributes at the module level?
That way you could track the project and the component using a GUID, just like ClassBuilder used to track properties under VB6. I guess you could also track changes to the project names, module names etc also.
That said, I'm not sure if these attributes are readable through Interop? And they're also sticky if you copy a module to another project in Project Explorer.

```
Attribute VB_Name = "RubberDuck_sln"
Attribute VB_Ext_KEY = "RubberDuck-ProjectGUID" ,"1234"
Attribute VB_Ext_KEY = "RubberDuck-ComponentGUID" ,"5678"
'RubberDuck Solution File - Auto-generated - Do not delete
```

**Comment by retailcoder** [comment]
I didn't know about the `VB_Ext_Key` attribute, that's a very very interesting approach!

**Comment by ckuhn203** [comment]
I didn't either! That could work!

**Comment by ThunderFrame** [comment]
We could perhaps also use Ext (or property/method description) attributes instead of `'@TestModule`, and `'@TestMethod`.
Try importing this into a VBA project, and be sure to check the Object Explorer window to see the Descriptions appear for the module and each method
```
Attribute VB_Name = "basDemo"
Attribute VB_Description = "Sample Module for Test Explorer"
Attribute VB_Ext_KEY = "RubberDuck-Version" ,"2.01"
Attribute VB_Ext_KEY = "RubberDuck-ProjectGUID" ,"1234"
Attribute VB_Ext_KEY = "RubberDuck-ComponentGUID" ,"5678"
Attribute VB_Ext_KEY = "RubberDuck-TestModule" ,"True"
Attribute VB_Ext_KEY = "RubberDuck-TestMethods" ,"MyMethodReturnsTrue,MyMethod2ReturnsTrue"
Option Explicit

'@TestModule
Private Assert As New Rubberduck.AssertClass

'@TestMethod
Public Sub MyMethodReturnsTrue()
Attribute MyMethodReturnsTrue.VB_Description = "RuberDuck Test Method"
    Assert.IsTrue MyMethod
End Sub

'@TestMethod
Public Sub MyMethod2ReturnsTrue()
Attribute MyMethod2ReturnsTrue.VB_Description = "RuberDuck Test Method"
    Assert.IsTrue MyMethod2
End Sub

Public Sub TestReferenceEquals()
Attribute TestReferenceEquals.VB_Description = "Checks if 2 collections are equal"
    Dim collection1 As New Collection
    Dim collection2 As Collection
    Set collection2 = collection1
    Assert.AreSame collection1, collection2
End Sub
```

**Comment by ckuhn203** [comment]
While nifty, I don't think I'd want that to become invisible. Also, the only way I know to add these attributes is to export/modify/import the files. That's a lot of lifting to add for a feature that already works. Do you know of a way to add these attributes through the VBIDE API?

**Comment by ckuhn203** [comment]
*by that, I mean the test attribute comments. I could see it becoming confusing if a user removed the comment, but the test still ran because the actual attribute hadn't been modified.

**Comment by retailcoder** [comment]
Note, we have it on the roadmap to reuse the source control feature's code for exporting/importing modules to edit module and procedure attributes à la VB6 :-)

**Comment by ThunderFrame** [comment]
I don't know a way of getting at it from VBIDE, other than export...
But I suspect it might be reachable in one of two ways, neither of which is trivial:

 1. View the actual source directly by using ole structured storage to inspect the project binary.

2. Use reflection or tlbinf32.dll to inspect the COM model (which probably also means inspecting the ole structured storage)

**Comment by ThunderFrame** [comment]
@ckuhn203, I agree. The visual reinforcement of the comment is important. And a user could always comment out the entire test block, so there's a chance the attributes would get out of sync.
Just wanted to highlight the range of attribute capabilities, although I haven't bothered with the default method/property attributes, or the _enum attributes, as they're more widely known.

**Comment by retailcoder** [comment]
Linking related: #53 #54 #55

**Comment by Vogel612** [comment]
Those three are proxied by #786 , too which additionally includes #52

**Comment by retailcoder** [comment]
@Vogel612  ah, I knew there was an all-encompassing issue somewhere! My phone isn't smart enough...

**Comment by retailcoder** [comment]
I'm not sure why the project name even needs to be part of the repository deal - if the repository's name is that of the working directory folder, then the problem is non-existent, no?

**Comment by ckuhn203** [comment]
Because we attempt to auto-load the working directory when the SC tool window is opened. Do away with that feature, and we no longer need to know about the project name. 

Until someone accidentally opens a working directory into the wrong project. Then, we'll want it back to prevent such a thing. 

Not trying to be a wise guy. Just having a long day and thinking out loud.

**Comment by retailcoder** [comment]
So the real issue is that there's no .vbp project file in VBA, to hold metadata about the project, its components and references.

Perhaps we could come up with out own .vba project file format to do this? One of the biggest pain points with having a .vbp file under source control, was that the VBE kept changing the sort order of project references and components, which kept causing conflicts (oh memories...)

If we had a file that...

 - Identified the host document's filename (full path would be annoying though)
 - Listed all project references (name, path, GUID), lowercased and sorted name
 - Listed all VBComponent items by name and type (i.e. `vbext_ct_ComponentType`), sorted by name
 - Listed all ActiveX controls and the macro name they're hooked up to, under each component (sorted by, uh, *location*?)
 - Anything else?

...then we'd have enough metadata to:

 - Identify when we're about to turn the current VBProject into a mess by loading components from another project - we could prompt the user to either proceed (and update the host doc filename in the .vba project file), or cancel the load
 - Detect and fix added/removed/missing project references
 - Detect and add/remove added/removed/missing document modules (via COM interop / host app's PIA)
 - Detect and add/remove added/removed/modified/missing ActiveX controls in document objects (aka worksheets)

Thoughts?

**Comment by ThunderFrame** [comment]
There's already a meta-data-ish VBA project stream in the Binary, and unlike most of the other streams, it isn't encoded, and is just plain text, and structured like an INI file.

It might be worth adopting the format and syntax of that file, even if we don't actually use the real stream initially, but rather build the file ourselves. That way we control the order of things to keep Source Control happy, and we have a format that is similar to the real stream, should we ever add that capability.

I'll post a sample, once I'm back at a keyboard.

IMO, the project meta file should contain information about the project and the components, but any conponent-level detail (such as activex controls) should be persisted with the component see #1230 ), as that would let you copy a component file from one project to another, without having to do a lot of manual editing.

**Comment by retailcoder** [comment]
@ThunderFrame agreed across the board - I'm only having a hard time imagining how we'll turn module attributes into 'shapes' in a reliable way that doens't corrupt both the document module and the worksheet itself :-)

**Comment by ckuhn203** [comment]
I'm sure that there will be surprises in the implementation, but it sounds like a pretty comprehensive list to me. In the interest of seeing 2.0 ship, I'd recommend doing this the quick and dirty way (enforcing a project name) and then circling back in a future version for all that.

**Comment by ckuhn203** [comment]
* removing the enforcement at that time, of course.

**Comment by ThunderFrame** [comment]
Here's a `PROJECT` [stream](https://msdn.microsoft.com/en-us/library/dd926400(v=office.12).aspx) from a VBA Binary, from an XLSM (created in 32-bit Excel 2010) with 3 worksheets, 1 standard module, 1 class module and 1 form:

```
ID="{416008C0-8E79-413D-832D-EE1E38187D9E}"
Document=ThisWorkbook/&H00000000
Document=Sheet1/&H00000000
Document=Sheet2/&H00000000
Document=Sheet3/&H00000000
Module=Module1
Class=Class1
Package={AC9F2F90-E877-11CE-9F68-00AA00574A4F}
BaseClass=UserForm1
Name="VBAProject"
HelpContextID="0"
VersionCompatible32="393222000"
CMG="86844FCB53D7DDDBDDDBDDDBDDDB"
DPB="0C0EC551CDD6CED6CED6"
GC="92905BDFE0E0E0E01F"

[Host Extender Info]
&H00000001={3832D640-CF90-11CF-8E43-00A0C911005A};VBE;&H00000000
&H00000002={00020818-0000-0000-C000-000000000046};Excel8.0;&H00000000

[Workspace]
ThisWorkbook=176, 176, 1059, 556, C
Sheet1=110, 110, 993, 490, C
Sheet2=132, 132, 1015, 512, C
Sheet3=154, 154, 1037, 534, C
Module1=0, 0, 883, 380, C
Class1=22, 22, 905, 402, C
UserForm1=66, 66, 949, 446, C, 44, 44, 927, 424, C
```

There's also a PROJECTwm stream with module names mapped to Unicode names
```
Offset(h) 00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F

00000000  54 68 69 73 57 6F 72 6B 62 6F 6F 6B 00 54 00 68  ThisWorkbook.T.h
00000010  00 69 00 73 00 57 00 6F 00 72 00 6B 00 62 00 6F  .i.s.W.o.r.k.b.o
00000020  00 6F 00 6B 00 00 00 53 68 65 65 74 31 00 53 00  .o.k...Sheet1.S.
00000030  68 00 65 00 65 00 74 00 31 00 00 00 53 68 65 65  h.e.e.t.1...Shee
00000040  74 32 00 53 00 68 00 65 00 65 00 74 00 32 00 00  t2.S.h.e.e.t.2..
00000050  00 53 68 65 65 74 33 00 53 00 68 00 65 00 65 00  .Sheet3.S.h.e.e.
00000060  74 00 33 00 00 00 4D 6F 64 75 6C 65 31 00 4D 00  t.3...Module1.M.
00000070  6F 00 64 00 75 00 6C 00 65 00 31 00 00 00 43 6C  o.d.u.l.e.1...Cl
00000080  61 73 73 31 00 43 00 6C 00 61 00 73 00 73 00 31  ass1.C.l.a.s.s.1
00000090  00 00 00 55 73 65 72 46 6F 72 6D 31 00 55 00 73  ...UserForm1.U.s
000000A0  00 65 00 72 00 46 00 6F 00 72 00 6D 00 31 00 00  .e.r.F.o.r.m.1..
000000B0  00 00 00                                         ...
```

**Comment by ThunderFrame** [comment]
@retailcoder Adding VB_Control references to the head of an exported document-type module would need to be done explicitly by Rubberduck, as the default Export doesn't include those attributes. Likewise, the attributes would have to be parsed by Rubberduck on reading the file in, and excluded from the re-write of the module.

For the time being, Rubberduck only has to warn the user of conflicts, and/or have an inspection inform the user that there are event handlers for a non-existant ActiveX control.

But at least if you know the control's Name, Library and Type, you can make useful suggestions about the type of control that needs to be added, rather than the use guessing, based on the event handlers.

**Comment by ThunderFrame** [comment]
In the longer term, I fear that trying to extend Source Control to "other parts" of the Project and or Host document, might only be possible if the document is saved (or preferably, closed), as there are too many parts of a host document that are not sufficiently exposed by the Object Model.

**Comment by Hosch250** [comment]
We should use the `Project.HelpFile` to determine which project a repo belongs to.

**Comment by retailcoder** [comment]
Given we're hijacking `Project.HelpFile` as a pseudo-unique ID (a hash code really), I'd say that's brilliant @Hosch250!

**Comment by Hosch250** [comment]
That's exactly why I said this.

**Comment by ckuhn203** [comment]
Genius! :+1:
