### ISSUE TITLE
With block variable references creates dupes

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#1572]
Member calls inside `With` blocks shouldn't create an identifier reference for the parent - e.g. here `L41C10-L41C20` is the `With` block variable, the _parent context_ of all member calls in the `With` block:

![image](https://cloud.githubusercontent.com/assets/5751684/15492387/d1df7bae-2148-11e6-8718-04c5b0eeccf6.png)

For the compiler, yes, that dot is a member call on the _parent context_ - but for the user it looks funny. Either make the selection on the dot, or don't make With block variable member calls create a reference to the parent. Whichever makes most sense.

**Comment by autoboosh** [comment]
That sounds like a bug, right? The resolver internally translates "with expressions" into "dictionary access / member access expressions" ("dictionary access expressions" are then further translated into index expressions). So basically you'll get back a member access expression if you pass it an expression like ".Title" that includes the with block variable as lexpression.

Do you want to add a fix for this to get a feel for the resolver? I'm not trying to pass the buck or anything.

**Comment by retailcoder** [comment]
I need to re-familiarize with the resolver. I'll take it.

**Comment by Hosch250** [comment]
Can you provide the full code to reproduce this?

**Comment by comintern** [comment]
This appears to have been fixed. I can't replicate it with any test code _or_ with the code from #2460.
