### ISSUE TITLE
Locals dump/print

### ISSUE THREAD

**Issue by psedlos** [rubberduck-vba/Rubberduck#1575]
Sorry if stupid/already exist - I am beginner.

I have to review some big application to calculate train performance so it is not a basic one and I need to extract that what is useful - some part of big main routine with these subroutines that are still in use.

However as it is really big I would be happy to be able to trace all variables like I have in Locals but in some more useful form. Possible extract to new worksheet.

Also great would be to have possibility to mark which part of code was visited at last run and which not without breakpoints.

Thanks!
Maciek

**Comment by retailcoder** [comment]
I agree it would be great, but unfortunately Rubberduck doesn't have access to the runtime or call stack, which is burried inside the VBA runtime library. Of all available add-ins and tools out there, I only know **VBWatchDog** that's able to tap into the runtime (using C and ASM/hex code injection if I understand correctly) - which is pure black magic as far as I can tell.

Maybe one day Rubberduck will get to the point where it can actually "compile" and *simulate execution* of VBA code (we can already evaluate constant expressions) - if/when that happens we'll be able to compute coverage metrics (heck, and performance-profile it, too) and, assuming we go forward with a subclassed code pane...

![image](https://cloud.githubusercontent.com/assets/5751684/15514078/53fd749e-21b5-11e6-825b-ac7e2ddfba6b.png)

...then we'll be able to "highlight" code paths. The "vanilla" code pane in the VBE doesn't allow for much customization and formatting opportunities.
