### ISSUE TITLE
Project with 0 components shows blank Code Inspections Window, hangs PowerPoint

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#1586]
Open a blank PowerPoint presentation without any modules.
Open the VBE
Wait for Ready...
Press Ctrl+Shift+I to bring up CodeInspections

There should be at least one inspection (the project has default name of VBAProject), but the VBE hangs when the Inspections Window is shown.

![PPT](http://i.imgur.com/lo9oEsb.png)

Under 2016 32-bit, I was able to try to kill PowerPoint, and the VBE window closed, so that PowerPoint recovered. I was then able to go back into the VBE, and the Inspections window appears without hanging, but there aren't any inspections.

**Comment by ThunderFrame** [comment]
FYI - You can make multiple slides into document modules by adding an ActiveX control to each slide, and wiring up an event handler.

**Comment by ThunderFrame** [comment]
oops, reopening

**Comment by Hosch250** [comment]
This isn't the code inspections.  Once it hits Ready, the entire VBE hangs.

**Comment by retailcoder** [comment]
Reproduced (worse actually, the VBE doesn't even repaint) on x64
