### ISSUE TITLE
Extract Method called, it wants its UI back

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#1599]
Selecting the body of the `For` loop here:

```
'@Folder("FizzBuzz")
Option Explicit

Private Const FIZZ As Integer = 3
Private Const BUZZ As Integer = 5

Public Sub RunFizzBuzz()
    Dim result As String
    Dim value As Integer

    For value = 1 To 100
        Select Case True
            Case value Mod (FIZZ * BUZZ) = 0
                result = "FIZZBUZZ"
            Case value Mod BUZZ = 0
                result = "BUZZ"
            Case value Mod FIZZ = 0
                result = "FIZZ"
            Case Else
                result = value
        End Select
        Debug.Print result
    Next

End Sub
```

Results in:

```
Public Sub RunFizzBuzz()
    Dim result As String
    Dim value As Integer

    For value = 1 To 100
NewMethod value, result
        Debug.Print result
    Next

End Sub
Private Sub NewMethod(ByRef value As Integer, ByRef result As String)
        Select Case True
            Case value Mod (FIZZ * BUZZ) = 0
                result = "FIZZBUZZ"
            Case value Mod BUZZ = 0
                result = "BUZZ"
            Case value Mod FIZZ = 0
                result = "FIZZ"
            Case Else
                result = value
        End Select
End Sub
```

I love the changes made to the refactoring under the hood! And it's FAST! But on the surface:
- Users lose the ability to name extracted method
- Users lose the ability to preview and confirm the refactoring
- Users lose the ability to extract a `Function` and pick one of the possible return values
- The extracted method should be indented, and call site should be inserted in the same column as the extracted code started
- Previous versions put an empty line between the parent and the extracted members
- Previous versions passed unassigned (input) parameters `ByVal`

Be it only for the ability to name the method before creating (and parsing) it, and preview/confirm the refactoring, _Extract Method_ needs to have its UI back.

If the user is able to extract the method they actually want, the way they want it, then they don't need to tweak it after okaying the dialog, and so we need to parse less often.

```
Public Sub RunFizzBuzz()
    Dim result As String
    Dim value As Integer

    For value = 1 To 100
        result = FizzBuzz(value)
        Debug.Print result
    Next

End Sub

Private Function FizzBuzz(ByVal value As Integer) As String
    Dim result As String
    Select Case True
        Case value Mod (FIZZ * BUZZ) = 0
            result = "FIZZBUZZ"
        Case value Mod BUZZ = 0
            result = "BUZZ"
        Case value Mod FIZZ = 0
            result = "FIZZ"
        Case Else
            result = value
    End Select
    FizzBuzz = result
End Function
```

**Comment by grleachman** [comment]
This should really read:
Gareth. You broke it, now fix it.

So assign it back to me, and I'll get to it once the edge cases work.

**Comment by Vogel612** [comment]
What's the status on this? Is this still an issue?

**Comment by Hosch250** [comment]
The UI is still there, but it doesn't display when Extract Method is called.

**Comment by bclothier** [comment]
@Vogel612 assign to me and add to epic

**Comment by bclothier** [comment]
Restoring dialog, implementing as WinForms containing WPF elementhost as per current standard is WIP. See PR #3588 and #3586.
