### ISSUE TITLE
Make the project internals visible to the TestProject

### ISSUE THREAD

**Issue by grleachman** [rubberduck-vba/Rubberduck#1600]
Apply [internalsVisibleTo](https://msdn.microsoft.com/en-us/library/system.runtime.compilerservices.internalsvisibletoattribute%28v=vs.110%29.aspx) to all the projects.

**Comment by Vogel612** [comment]
seems excessive, actually. @retailcoder  opinions?

**Comment by Vogel612** [comment]
Castle-Windsor doesn't bind the default interface convention for internal classes. See 8794aab7939186ae04701c5c32fd76417f9dd082 as a symptom. As soon as we make stuff internal, we **will** need to find a solution to that or we can't even do this

**Comment by Vogel612** [comment]
considered done since merging #3739
