### ISSUE TITLE
Value cannot be null. Parameter name: key.

### ISSUE THREAD

**Issue by PeterMTaylor** [rubberduck-vba/Rubberduck#1611]
Received this error using the latest sync with rubberduck-vba/next.
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.Collections.Generic.Dictionary`2.Remove(TKey key)
   at Rubberduck.App.<sink_ProjectRemoved>d__28.MoveNext() in C:\Users\Peter\Dropbox\Doing\Github\Rubberduck\RetailCoder.VBE\App.cs:line 184
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

**Comment by retailcoder** [comment]
if (e.Item.HelpFile == null || e.Item.Protection == vbext_ProjectProtection.vbext_pp_locked)
            {
                _logger.Debug("Locked project '{0}' was removed.", e.Item.Name);
                return;
            }

            var projectId = e.Item.HelpFile;
            _componentsEventsSinks.Remove(projectId); // <~ boom
            _referencesEventsSinks.Remove(projectId);
            _parser.State.RemoveProject(e.Item);

Weird, `HelpFile` being `null` means the project wasn't properly added in the first place. On it.

**Comment by retailcoder** [comment]
I think I might have forgot to reference this issue... can you get a repro with the latest build?

**Comment by Stevefb** [comment]
@retailcoder hi there - I think I got pretty much the same with the latest build.

Word crashed unexpectedly.... well I mean it's usually stable for a few minutes on a Monday morning ;-)

I'm not sure what caused this, I was not actually sitting at the PC at the time, came back to find:

> See the end of this message for details on invoking 
> just-in-time (JIT) debugging instead of this dialog box.
> 
> ************** Exception Text **************
> System.ArgumentNullException: Value cannot be null.
> Parameter name: key
>    at System.Collections.Generic.Dictionary`2.Remove(TKey key)
>    at Rubberduck.App.<sink_ProjectRemoved>d__32.MoveNext() in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\RetailCoder.VBE\App.cs:line 213
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
> 
> 
> ************** Loaded Assemblies **************
> mscorlib
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1080.0 built by: NETFXREL3STAGE
>     CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
> ----------------------------------------
> Rubberduck
>     Assembly Version: 2.0.2.41756
>     Win32 Version: 2.0.2.0
>     CodeBase: file:///C:/ProgramData/Rubberduck/Rubberduck.DLL
> ----------------------------------------
> Ninject
>     Assembly Version: 3.2.0.0
>     Win32 Version: 3.2.2.0
>     CodeBase: file:///C:/ProgramData/Rubberduck/Ninject.DLL
> ----------------------------------------
> Ninject.Extensions.Factory
>     Assembly Version: 3.2.0.0
>     Win32 Version: 3.2.1.0
>     CodeBase: file:///C:/ProgramData/Rubberduck/Ninject.Extensions.Factory.DLL
> ----------------------------------------
> Microsoft.Vbe.Interop
>     Assembly Version: 14.0.0.0
>     Win32 Version: 14.0.4760.1000
>     CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/Microsoft.Vbe.Interop/14.0.0.0__71e9bce111e9429c/Microsoft.Vbe.Interop.dll
> ----------------------------------------
> Rubberduck.Parsing
>     Assembly Version: 2.0.6012.41752
>     Win32 Version: 2.0.0.0
>     CodeBase: file:///C:/ProgramData/Rubberduck/Rubberduck.Parsing.DLL
> ----------------------------------------
> System.Windows.Forms
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1038.0 built by: NETFXREL2
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
> ----------------------------------------
> System
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1081.0 built by: NETFXREL3STAGE
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
> ----------------------------------------
> System.Drawing
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1078.0 built by: NETFXREL3STAGE
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
> ----------------------------------------
> System.Core
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1038.0 built by: NETFXREL2
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
> ----------------------------------------
> Castle.Core
>     Assembly Version: 3.2.0.0
>     Win32 Version: 3.2.0.14
>     CodeBase: file:///C:/ProgramData/Rubberduck/Castle.Core.DLL
> ----------------------------------------
> NLog
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.0.0.0
>     CodeBase: file:///C:/ProgramData/Rubberduck/NLog.DLL
> ----------------------------------------
> System.Configuration
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1038.0 built by: NETFXREL2
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
> ----------------------------------------
> System.Xml
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1064.2 built by: NETFXREL3STAGE
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
> ----------------------------------------
> System.ServiceModel
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1038.0 built by: NETFXREL2
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel/v4.0_4.0.0.0__b77a5c561934e089/System.ServiceModel.dll
> ----------------------------------------
> System.Data
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1038.0 built by: NETFXREL2
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
> ----------------------------------------
> System.Runtime.Serialization
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1038.0 built by: NETFXREL2
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
> ----------------------------------------
> Rubberduck.VBEditor
>     Assembly Version: 2.0.6012.41751
>     Win32 Version: 2.0.0.0
>     CodeBase: file:///C:/ProgramData/Rubberduck/Rubberduck.VBEditor.DLL
> ----------------------------------------
> Rubberduck.SourceControl
>     Assembly Version: 2.0.0.0
>     Win32 Version: 2.0.0.0
>     CodeBase: file:///C:/ProgramData/Rubberduck/Rubberduck.SourceControl.DLL
> ----------------------------------------
> PresentationCore
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1080.0 built by: NETFXREL3STAGE
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
> ----------------------------------------
> WindowsBase
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1080.0 built by: NETFXREL3STAGE
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
> ----------------------------------------
> Rubberduck.SmartIndenter
>     Assembly Version: 2.0.0.0
>     Win32 Version: 2.0.0.0
>     CodeBase: file:///C:/ProgramData/Rubberduck/Rubberduck.SmartIndenter.DLL
> ----------------------------------------
> PresentationFramework
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1080.0
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll
> ----------------------------------------
> System.Xaml
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1080.0 built by: NETFXREL3STAGE
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
> ----------------------------------------
> office
>     Assembly Version: 14.0.0.0
>     Win32 Version: 14.0.4760.1000
>     CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/office/14.0.0.0__71e9bce111e9429c/office.dll
> ----------------------------------------
> System.Windows.Interactivity
>     Assembly Version: 4.0.0.0
>     Win32 Version: 2.0.20525.0
>     CodeBase: file:///C:/ProgramData/Rubberduck/System.Windows.Interactivity.DLL
> ----------------------------------------
> Antlr4.Runtime.net45
>     Assembly Version: 4.3.0.0
>     Win32 Version: 4.3.0.0
>     CodeBase: file:///C:/ProgramData/Rubberduck/Antlr4.Runtime.net45.DLL
> ----------------------------------------
> Ninject.Extensions.Conventions
>     Assembly Version: 3.2.0.0
>     Win32 Version: 3.2.0.0
>     CodeBase: file:///C:/ProgramData/Rubberduck/Ninject.Extensions.Conventions.DLL
> ----------------------------------------
> Rubberduck.SettingsProvider
>     Assembly Version: 2.0.0.0
>     Win32 Version: 2.0.0.0
>     CodeBase: file:///C:/ProgramData/Rubberduck/Rubberduck.SettingsProvider.DLL
> ----------------------------------------
> Ninject.Extensions.NamedScope
>     Assembly Version: 3.2.0.0
>     Win32 Version: 3.2.0.0
>     CodeBase: file:///C:/ProgramData/Rubberduck/Ninject.Extensions.NamedScope.DLL
> ----------------------------------------
> DynamicProxyGenAssembly2
>     Assembly Version: 0.0.0.0
>     Win32 Version: 3.2.0.14
>     CodeBase: file:///C:/ProgramData/Rubberduck/Castle.Core.dll
> ----------------------------------------
> DynamicProxyGenAssembly2
>     Assembly Version: 0.0.0.0
>     Win32 Version: 3.2.0.14
>     CodeBase: file:///C:/ProgramData/Rubberduck/Castle.Core.dll
> ----------------------------------------
> WindowsFormsIntegration
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1038.0 built by: NETFXREL2
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/WindowsFormsIntegration/v4.0_4.0.0.0__31bf3856ad364e35/WindowsFormsIntegration.dll
> ----------------------------------------
> Infralution.Localization.Wpf
>     Assembly Version: 3.3.0.0
>     Win32 Version: 3.3.0.0
>     CodeBase: file:///C:/ProgramData/Rubberduck/Infralution.Localization.Wpf.dll
> ----------------------------------------
> PresentationFramework.Aero
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1038.0 built by: NETFXREL2
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework.Aero/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.Aero.dll
> ----------------------------------------
> PresentationFramework.Aero2
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1038.0 built by: NETFXREL2
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework.Aero2/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.Aero2.dll
> ----------------------------------------
> Anonymously Hosted DynamicMethods Assembly
>     Assembly Version: 0.0.0.0
>     Win32 Version: 4.6.1080.0 built by: NETFXREL3STAGE
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
> ----------------------------------------
> System.Xml.Linq
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1038.0 built by: NETFXREL2
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
> ----------------------------------------
> Accessibility
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1038.0 built by: NETFXREL2
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
> ----------------------------------------
> PresentationFramework-SystemXmlLinq
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1038.0
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework-SystemXmlLinq/v4.0_4.0.0.0__b77a5c561934e089/PresentationFramework-SystemXmlLinq.dll
> ----------------------------------------
> PresentationFramework-SystemXml
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1038.0
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework-SystemXml/v4.0_4.0.0.0__b77a5c561934e089/PresentationFramework-SystemXml.dll
> ----------------------------------------
> PresentationFramework-SystemCore
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1038.0
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework-SystemCore/v4.0_4.0.0.0__b77a5c561934e089/PresentationFramework-SystemCore.dll
> ----------------------------------------
> UIAutomationTypes
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1038.0 built by: NETFXREL2
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/UIAutomationTypes/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationTypes.dll
> ----------------------------------------
> PresentationFramework-SystemData
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1038.0
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework-SystemData/v4.0_4.0.0.0__b77a5c561934e089/PresentationFramework-SystemData.dll
> ----------------------------------------
> CustomMarshalers
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1038.0 built by: NETFXREL2
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/CustomMarshalers/v4.0_4.0.0.0__b03f5f7f11d50a3a/CustomMarshalers.dll
> ----------------------------------------
> stdole
>     Assembly Version: 7.0.3300.0
>     Win32 Version: 7.00.9466
>     CodeBase: file:///C:/WINDOWS/assembly/GAC/stdole/7.0.3300.0__b03f5f7f11d50a3a/stdole.dll
> ----------------------------------------
> Microsoft.GeneratedCode
>     Assembly Version: 1.0.0.0
>     Win32 Version: 4.6.1064.2 built by: NETFXREL3STAGE
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
> ----------------------------------------
> Microsoft.GeneratedCode
>     Assembly Version: 1.0.0.0
>     Win32 Version: 4.6.1064.2 built by: NETFXREL3STAGE
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
> ----------------------------------------
> Microsoft.GeneratedCode
>     Assembly Version: 1.0.0.0
>     Win32 Version: 4.6.1064.2 built by: NETFXREL3STAGE
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
> ----------------------------------------
> Microsoft.Office.Interop.Word
>     Assembly Version: 14.0.0.0
>     Win32 Version: 14.0.4762.1000
>     CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/Microsoft.Office.Interop.Word/14.0.0.0__71e9bce111e9429c/Microsoft.Office.Interop.Word.dll
> ----------------------------------------
> Microsoft.GeneratedCode
>     Assembly Version: 1.0.0.0
>     Win32 Version: 4.6.1064.2 built by: NETFXREL3STAGE
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
> ----------------------------------------
> Microsoft.GeneratedCode
>     Assembly Version: 1.0.0.0
>     Win32 Version: 4.6.1064.2 built by: NETFXREL3STAGE
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
> ----------------------------------------
> Microsoft.GeneratedCode
>     Assembly Version: 1.0.0.0
>     Win32 Version: 4.6.1064.2 built by: NETFXREL3STAGE
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
> ----------------------------------------
> Microsoft.CSharp
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1038.0
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
> ----------------------------------------
> System.Dynamic
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1038.0
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
> ----------------------------------------
> System.Numerics
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1038.0 built by: NETFXREL2
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
> ----------------------------------------
> 
> ************** JIT Debugging **************
> To enable just-in-time (JIT) debugging, the .config file for this
> application or computer (machine.config) must have the
> jitDebugging value set in the system.windows.forms section.
> The application must also be compiled with debugging
> enabled.
> 
> For example:
> 
> <configuration>
>     <system.windows.forms jitDebugging="true" />
> </configuration>
> 
> When JIT debugging is enabled, any unhandled exception
> will be sent to the JIT debugger registered on the computer
> rather than be handled by this dialog box.

**Comment by Hosch250** [comment]
The project ID is somehow null for these calls:

    _componentsEventsSinks.Remove(projectId);
    _referencesEventsSinks.Remove(projectId);

**Comment by Stevefb** [comment]
@Hosch250  My gut feeling is that it happens when a project is opened, or perhaps closed... I did get a crash when I had inspection results open then closed a project for which results were displayed.  HTH

**Comment by Hosch250** [comment]
When a project is removed.

**Comment by Hosch250** [comment]
Can you give me the exact steps required to reproduce this?  I tried opening two Excel instances and opened the VBE, then closed one Excel instance, and RD handled removing the component correctly--no crashes.  Is this how you reproduced it, or is there another way?

**Comment by Stevefb** [comment]
Use MS Word....

**Comment by Talorthain** [comment]
Open excel

Go into vba editor

Change rubberduck settings (<-- settings issue tests from previous communications)

Exit from excel red X, without opening or creating a module or project

 

Regards

 

Anthony

**Comment by Hosch250** [comment]
I still cannot verify this.  I tried opening the VBE from Excel's default project page, and it creates a project by default.  I tried adding new projects by opening the Start page, then closing it, but still no repro.  I tried opening a single project from the start page, but it wouldn't let me open the VBE from there.  Can you still reproduce this?

**Comment by Talorthain** [comment]
I will have a go tomorrow.

**Comment by Talorthain** [comment]
![capture](https://cloud.githubusercontent.com/assets/6796503/16425485/ea726250-3d5c-11e6-9092-840e7376f12b.PNG)

Installed newest version of Rubberduck
Open excel
Open VBA editor
close vba editor from red x
close excel from red x
crash....

I dont create anything, open anything, add anything. I just open excel vba editor and close them down.

**Comment by Hosch250** [comment]
Would one of you who can consistently reproduce this check whether the Code Explorer sees the project before it is removed?  If Rubberduck doesn't know about it, I might as well just check for a null project and not try to remove it.  If Rubberduck does know about the project, something is pretty seriously wrong.

**Comment by Talorthain** [comment]
![crash on red x exit](https://cloud.githubusercontent.com/assets/6796503/16476712/f3e3a0e4-3e81-11e6-828c-f9fe4f847c37.PNG)
![project identified](https://cloud.githubusercontent.com/assets/6796503/16476714/f4034ce6-3e81-11e6-9fd5-e93a6fcc31ad.PNG)
![rd ready](https://cloud.githubusercontent.com/assets/6796503/16476713/f3ffd480-3e81-11e6-847d-4c657a9c5ced.PNG)

Installed newest version of Rubberduck
Open excel
Open VBA editor
close vba editor from red x
close excel from red x
crash....

I dont create anything, open anything, add anything. I just open excel vba editor and close them down.

**Comment by retailcoder** [comment]
@Hosch250 that's the failing `Debug.Assert` call in the sink handler for *project removed*; `Debug` calls don't get compiled into a release build. How about we replace it with a conditional early `return`?

**Comment by PeterMTaylor** [comment]
@Hosch250 and @retailcoder I have be unable to reproduce this error regarding null with RD 2.0.3.0 build with Win 10 Home. Version 1511 and OS Build 10586.420.  Attached are my three tests using ScreentoGif.
1. with Word 2010
![rd 2 0 3 0 word project test](https://cloud.githubusercontent.com/assets/2254567/16522110/f0cefdd2-3fde-11e6-9a0b-d9d9912e25f5.gif)
2. with Visio 2007 version I had
![rd 2 0 3 0 visio 2007 project test](https://cloud.githubusercontent.com/assets/2254567/16522108/f0c98136-3fde-11e6-841e-fd6ffaf920e4.gif)
3. With Excel 2010.
![rd 2 0 3 0 excel project test](https://cloud.githubusercontent.com/assets/2254567/16522109/f0cd3d08-3fde-11e6-807e-c2e86de371b4.gif)

**Comment by Talorthain** [comment]
Just for clarity, I am using;
![win 10 detail](https://cloud.githubusercontent.com/assets/6796503/16539250/65a54066-4035-11e6-8d23-2a626b9d7316.PNG)
![excel version](https://cloud.githubusercontent.com/assets/6796503/16539251/65c6f986-4035-11e6-89e5-dcf34454f9d3.PNG)

**Comment by Hosch250** [comment]
Has this been seen lately?  I completely rewrote this part of the project a while ago.

**Comment by retailcoder** [comment]
Nope.
