### ISSUE TITLE
Parser doesn't pesist VB_Description text in Declarations

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#1615]
While testing Code Explorer, I added a descriptions to a workbook, sheet, module and method (using Object Browser context menu: Properties).

Hitting refresh (a few times, for good measure) Code Explorer still shows the description as an empty string, but Code Explorer is only representing the string (for non CustomFolder nodes) as:

`return ((ICodeExplorerDeclarationViewModel) SelectedItem).Declaration.DescriptionString`

Which suggests that the parser isn't recognising the attributes.

here's the module text

```
Attribute VB_Name = "Module1"
Attribute VB_Description = "module description"
Private Type fizz
  er As Long
  led As Long
End Type

Public Type buzz
  er As Long
  led As Long
End Type

Public Sub foo()

End Sub

Private Sub bar()
Attribute bar.VB_Description = "blah blah blah"

End Sub

Private Function hoo()

End Function

Public Function car()

End Function

Public Sub ggg()

End Sub

```

**Comment by ThunderFrame** [comment]
hmmm, added a @Folder annotation and hit refresh, and the Module now shows a description (and so does the folder), but all other declarations are still empty strings.

**Comment by Hosch250** [comment]
The bug here is that we do not recreate the declarations for a component unless that component changed.

**Comment by retailcoder** [comment]
Sticking status-bydesign on this. Exporting all modules just to check if maybe perhaps some description attributes were changed is too expensive. Modify *anything* in that module's actual in-IDE content and the attributes will be parsed then.
