### ISSUE TITLE
Code Explorer enhancements

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#1616]
A few suggestions on improving CodeExplorer UI.

1. Current node should remain selected after refresh
2. Bottom panel Declaration Name and Description text should be selectable (and copyable)
3. Bottom panel Declaration Name and Description font size should be the same as the node font size
4. Bottom panel should have scroll bars if there is overflow

**Comment by Hosch250** [comment]
None of these should be too hard, but they are all fairly minor, so I'm going to put this off for now.  These are all quite easy, so I'm adding the up-for-grabs tag.

**Comment by Hosch250** [comment]
Reference 52fb48d.  (Wrong commit message.)
