### ISSUE TITLE
Code Inspections return in random order, regardless of Grouping selection

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#1618]
In these screenshots, my Code Inspections Window has `Grouping.. By Inspection Type` checked.

As per #1617 I need to refresh using the toolbar Refresh button, but these are the Code Inspection results after subsequent presses....

![Imgur](http://i.imgur.com/DhPLccF.png)

![Imgur](http://i.imgur.com/naNtykV.png)

![Imgur](http://i.imgur.com/alQMMgM.png)

![Imgur](http://i.imgur.com/HB1liqz.png)

![Imgur](http://i.imgur.com/rhb1Tw6.png)

**Comment by Hosch250** [comment]
Status-by-design.  Those are the inspection types.  I know it looks funny, I did a double-take on that the other day too...  Should we perhaps offer a third grouping here?

**Comment by Hosch250** [comment]
What is the problem here?  That it isn't grouped by inspection but by inspection type, that the order of the displayed groupings is sporadic, or that the order of the inspections in the groupings is sporadic?

**Comment by retailcoder** [comment]
@Hosch250 the results are being displayed in whatever order the inspections happen to be running; the UI intends to be sorting them - even just sorting by inspection would stabilize the sorting. I thought this was addressed loooooong ago...

**Comment by Hosch250** [comment]
<CollectionViewSource x:Key="ResultsByInspectionType" Source="{Binding Results}">
        <CollectionViewSource.SortDescriptions>
            <componentModel:SortDescription PropertyName="Inspection.InspectionType"/>
            <componentModel:SortDescription PropertyName="Inspection.Name"/>
            <componentModel:SortDescription PropertyName="QualifiedSelection.QualifiedName.Name"/>
            <componentModel:SortDescription PropertyName="QualifiedSelection.Selection.StartLine"/>
            <componentModel:SortDescription PropertyName="QualifiedSelection.Selection.StartColumn"/>
        </CollectionViewSource.SortDescriptions>
        <CollectionViewSource.GroupDescriptions>
            <PropertyGroupDescription PropertyName="Inspection" Converter="{StaticResource InspectionTypeConverter}" />
        </CollectionViewSource.GroupDescriptions>
    </CollectionViewSource>
    
    <CollectionViewSource x:Key="ResultsByModule" Source="{Binding Results}">
        <CollectionViewSource.SortDescriptions>
            <componentModel:SortDescription PropertyName="QualifiedSelection.QualifiedName.Name"/>
            <componentModel:SortDescription PropertyName="Inspection.Name"/>
            <componentModel:SortDescription PropertyName="QualifiedSelection.Selection.StartLine"/>
            <componentModel:SortDescription PropertyName="QualifiedSelection.Selection.StartColumn"/>
        </CollectionViewSource.SortDescriptions>
        <CollectionViewSource.GroupDescriptions>
            <PropertyGroupDescription PropertyName="QualifiedSelection.QualifiedName" />
        </CollectionViewSource.GroupDescriptions>
    </CollectionViewSource>

Looks like it is supposed to be sorting.  Adding `IsLiveSortingRequested="True"` makes it much more reliable than it is now, but not completely.
