### ISSUE TITLE
Website inspections should send notifications if parsing fails.

### ISSUE THREAD

**Issue by comintern** [rubberduck-vba/Rubberduck#1619]
So it just occurred to me that this feature on the website is a perfect opportunity to collect error reports from users who otherwise couldn't be bothered to open an issue for it.  I also don't remember from the screen shots if this was there or not, but there should also be a "Report Issue" link along with the results.

**Comment by ThunderFrame** [comment]
We probably need a Terms of Use that allows for recording stats, collecting error reports (that might end up in a public GitHub issue, etc.

Aside from hit/page counts, it would be very interesting to see the breakdown of inspections in real word code.

Eg:

99% of projects are called VBAProject
1% of projects use Option Private Module
1% of projects use Interfaces
The top 3 inspections are blah, blah, blah.

**Comment by Hosch250** [comment]
This could be interesting, and I see nothing wrong with recording the number of each type of inspection reported with no details.  Reporting problems is also an interesting idea.

**Comment by transistor1** [comment]
I would suggest a way to opt out as well. It probably wouldnt get through my company's firewall, and i would prefer it didnt generate a whole bunch of "access denied" errors under my account, lest the "powers that be" think it's some sort of malware.

**Comment by Hosch250** [comment]
@transistor1 The only way this would be implemented would be a link that says "report this error" in the error message--it would be completely opt-in.  On the other hand, it already tells them to make sure the code compiles and provides a link for them to report it if it does not--I don't think it needs to be any more aggressive than that.

**Comment by transistor1** [comment]
That works for me. Thanks!

**Comment by Hosch250** [comment]
@transistor1 
> It probably wouldnt get through my company's firewall, and i would prefer it didnt generate a whole bunch of "access denied" errors under my account, lest the "powers that be" think it's some sort of malware.

If that is a concern, you shouldn't use it anyway--the data is posted to the server, which runs the analysis and returns the results.

**Comment by retailcoder** [comment]
@transistor1 just to be clear, @Hosch250 is talking about a functionality of the **website**, not the actual add-in.

**Comment by transistor1** [comment]
Whew.  I was actually going to ask @Hosch250 to clarify-- thanks @retailcoder.  If automated error reporting were a feature, I probably would not be able not use it.
