### ISSUE TITLE
Code Explorer should add optional flag for members with TODO markers

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#1620]
Code Explorer is *already* a cross between VBE Project Explorer and Object Browser.

TODO explorer is great for seeing all TODO items, but it might be useful to have an indicator in the Code Explorer nodes, if and when there is a TODO entry for that node.

**Comment by Hosch250** [comment]
I disagree.  Two windows for two things.  What does @retailcoder think?

**Comment by ThunderFrame** [comment]
Well, TODO Explorer doesn't display the parent section/member/context (and maybe it could/should), but TODO Explorer is designed to explore TODOs *by marker*, while having a visual indicator next to a member name in Code Explorer would allow exploration, or at the very least a visual cue, *by folder/module/member*, so they're 2 different use cases.

Also, I suspect Code Explorer will typically be always visible, while TODO explorer will typically be visible only when *doing* TODOs, so having an extra, optional, visual cue in Code Explorer is an auxiliary reminder that there is a marker.

**Here are some very specific use cases that add value in the Code Explorer**
If Code Explorer allowed for specific user-defined TODO markers to be highlighted/flagged, then users could have TODO markers like:

- Autorun - A method that the host calls automatically on project open
- RibbonCallback - A method called by Ribbon/CustomUI
- ButtonMacroAssignment - A method called by a UI Control (eg. Excel Button/Shape)
- COMCallback - A method called by a COM add-in
- AccessExpressionFunction - A method used in a query/form/report/macro/table expression

Then you'd have visual feedback for the callback-type members.

**Comment by Hosch250** [comment]
You have a point, but I think this would be pretty hard to display nice.  Perhaps we could stick it in the bottom panel somewhere?

**Comment by retailcoder** [comment]
@Hosch250 that's a neat idea! If a member has todo items, a linkbutton that brings up the todo explorer could be shown in the bottom panel.. 

@ThunderFrame wouldn't folders and modules be a better tool for this kind of use case?

**Comment by ThunderFrame** [comment]
@Hosch250 Maybe just an overlay/extra icon?

:open_file_folder: CallbackHandlers
--:page_facing_up: modCallbacks
----:bookmark: MyUserefinedWorksheetFunction
----:triangular_flag_on_post: MyCOMAddinCallback
----:hankey: MyRibbonCallback

@retailcoder Yes, but folders are mutually exclusive, whereas markers are tags, so folders force you to classify all module members under one discrete category, whereas tags allow you to tag individual members, and you can apply more than one tag to a member.

**Comment by ThunderFrame** [comment]
#1001 lives...

**Comment by retailcoder** [comment]
So... that would encourage having large modules with various unrelated functionalities?

**Comment by ThunderFrame** [comment]
*Encourage* is a strong word. Yes, it would *allow* for large modules with unrelated functionalities, but VBA *already* allows that.

IMO, @Folders are a *Physical* approach (albeit a *Virtual* implementation by Rubberduck) to module organisation, and tags would be a *Logical* approach to extensible, user-defined *Member* attributes, without requiring much in the way of RubberDuck knowing what those attributes are.

To give a specific example, it would seem sensible to have a @Folder with modules for Ribbon Handling:
:open_file_folder: RibbonHandlers
--:page_facing_up: modRibbon
--:page_facing_up: modTabDesign
--:page_facing_up: modTabLayout

And *each* module might have Ribbon callback methods, but each module *might* also have private helper members, or public methods (eg. for triggering a Ribbon refresh) called by other VBA.

It makes sense for the Ribbon modules to be grouped by folder, and for *each* ribbon module to contain members specific to a Ribbon element, but not all of those members would necessarily be ribbon callbacks. Hence the merit of a visual indicator next to a member in Code Explorer.

**Comment by retailcoder** [comment]
Nah.. I think we have more than enough ways to navigate and organize things already.
