### ISSUE TITLE
Adding or Editing a TODO entry in Settings can cause window to close without saving

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#1622]
Strictly speaking, it's only *editing* an entry that causes this, because *adding* an item successfully creates a placeholder item named `PLACEHOLDER`, which would typically then be *edited*.

If I edit an existing entry, or I add a new entry and then edit the PLACEHOLDER name, and then click another entry in the list, then the item I just edited is now *blue*, but if I click back on the edited item, and then click out of it again, the window closes automatically, and the changes are not saved.

**Comment by Hosch250** [comment]
This is nuts.  I managed to duplicate this, but it doesn't throw an exception!

**Comment by Hosch250** [comment]
Also happens when you change the inspection severity.

**Comment by Hosch250** [comment]
Turns out the edit wasn't being committed for some reason.
