### ISSUE TITLE
Parser Error with member attributes

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#1644]
> "extraneous input 'Attribute' expecting {<EOF>, ':', CONST, DECLARE, DEFBOOL, DEFBYTE, DEFDATE, DEFDBL, DEFCUR, DEFINT, DEFLNG, DEFLNGLNG, DEFLNGPTR, DEFOBJ, DEFSNG, DEFSTR, DEFVAR, DIM, ENUM, EVENT, FRIEND, FUNCTION, GLOBAL, IMPLEMENTS, OPTION_BASE, OPTION_EXPLICIT, OPTION_COMPARE, OPTION_PRIVATE_MODULE, PRIVATE, PROPERTY_GET, PROPERTY_LET, PROPERTY_SET, PUBLIC, REM, STATIC, SUB, TYPE, NEWLINE, ''', WS, LINE_CONTINUATION}"

Looks like #1639 broke something?

**Comment by retailcoder** [comment]
Maybe not. Here's the module throwing the parser error:

	VERSION 1.0 CLASS
	BEGIN
	  MultiUse = -1  'True
	END
	Attribute VB_Name = "ProgressIndicator"
	Attribute VB_GlobalNameSpace = False
	Attribute VB_Creatable = False
	Attribute VB_PredeclaredId = True
	Attribute VB_Exposed = True
	Option Explicit

	Private Declare Sub Sleep Lib "kernel32" (ByVal dwMilliseconds As Long)

	Private Const DEFAULT_CAPTION As String = "Progress"
	Private Const DEFAULT_LABEL As String = "Please wait..."

	Private Const ERR_NOT_INITIALIZED As String = "ProgressIndicator is not initialized."
	Private Const ERR_PROC_NOT_FOUND As String = "Specified macro or object member was not found."
	Private Const ERR_OPERATION_CANCELLED As String = "Operation was cancelled by the user."

	Public Enum ProgressIndicatorError
		Error_NotInitialized = vbObjectError + 1001
		Error_ProcedureNotFound
		Error_OperationCancelled
	End Enum

	Private Type TProgressIndicator
		procedure As String
		instance As Object
		sleepDelay As Long
		canCancel As Boolean
		currentProgressValue As Double
	End Type

	Public Event BeforeCancel(ByRef throw As Boolean)

	Private this As TProgressIndicator
	Private WithEvents view As ProgressView
	Attribute view.VB_VarHelpID = -1

	Private Sub Class_Initialize()
		Set view = New ProgressView
		view.Caption = DEFAULT_CAPTION
		view.ProgressLabel = DEFAULT_LABEL
	End Sub

	Private Sub Class_Terminate()
		Set view = Nothing
		Set this.instance = Nothing
	End Sub

`Attribute view.VB_VarHelpID = -1` is a *member attribute* applied to the `Private WithEvents view As ProgressView` field. Looks like the member attribute syntax should be legal in the declarations section as well.

**Comment by retailcoder** [comment]
Looking at the `lExpression` rule definition, it seems `view.VB_VarHelpID` would be a legal name. @autoboosh any idea?

**Comment by autoboosh** [comment]
Looks like it's the order that's the issue. If you put the view.VB_VarHelpID right after the VB_Exposed attribute line it works. Also it looks like we need to always grab the member name from the attribute if there is one? Is this attribute format described somewhere...? Otherwise we could treat everything that starts with VB_ as an attribute and what comes before it as member. Is it also possible to do something like this:

`VBAProject.view.VB_VarHelpID`

If so we'd have to start giving this stuff to the resolver soon...

**Comment by retailcoder** [comment]
Don't look at me, I didn't put that attribute there - the VBE did!

> Also it looks like we need to always grab the member name from the attribute if there is one?

Yup. That's how we associate member attributes with member declarations.

>  Is this attribute format described somewhere...?

No idea.

> Is it also possible to do something like this: `VBAProject.view.VB_VarHelpID`?

I don't think so. Member attributes seem scoped to the module they're in, so they wouldn't need to be qualified with a project name.

**Comment by autoboosh** [comment]
This should be fixed with the latest PRs.

**Comment by retailcoder** [comment]
Haven't had a chance to re-test this. Hopefully I'll just close this issue tonight. Looks like we're good for a beta then.
