### ISSUE TITLE
Exception thrown: 'System.Runtime.InteropServices.COMException' in Rubberduck.VBEditor.dll

### ISSUE THREAD

**Issue by PeterMTaylor** [rubberduck-vba/Rubberduck#1649]
On commit https://github.com/rubberduck-vba/Rubberduck/commit/83b08c4500fd13f945b6589934ae2fa2381f9ff8.

Additional information: System Error &H80070006 (-2147024890).  

Using the Code Explorer on a VBA, I found a class I didn't need and right clicked to Remove this class. Ignoring the write to text file prompt. After a fair moment of time. there was a flash on me screen and this error popped up.

![capture system runtime interopservice comexception](https://cloud.githubusercontent.com/assets/2254567/15708707/744e2812-2843-11e6-8a39-0ef035817fb5.PNG)

Call stack for your information.

![capture system runtime interopservice comexception callstack](https://cloud.githubusercontent.com/assets/2254567/15708734/a7659adc-2843-11e6-8234-ab5b7483f02f.PNG)

**Comment by Hosch250** [comment]
Same as https://github.com/rubberduck-vba/Rubberduck/issues/1414
