### ISSUE TITLE
Folder annotations not recognised when immediately followed by Procedure signature

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#1652]
Both example are where no other code exists in the module.

This code *does* produce a folder in Code Explorer:

```vb
'@Folder Authentication

Sub Foo()
    DoFoo
End Sub
```

This code doesn't:

```vb
'@Folder Authentication
Sub Foo()
    DoFoo
End Sub
```

Seems to occur with `Sub`, `Function` and `Property` statements

**Comment by retailcoder** [comment]
This is by design. The `@Folder` annotation is only valid in a module's *declarations section*. By putting it immediately atop a procedure's signature, Rubberduck deems it a member annotation and attaches it to the `Declaration` of the `Foo` procedure.

**Comment by ThunderFrame** [comment]
well, if I don't have any declarations, my procedure is the only code in the module

**Comment by retailcoder** [comment]
Where's `Option Explicit`? :wink:
