### ISSUE TITLE
ImplicitVariantReturnTypeInspection quick-fix removes all comments

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#166]
Because signatures can span multiple lines, the return type of a function (or of a property getter) cannot be assumed to be on the first line of a procedure; the quick-fix therefore replaces the entire function/getter to set an explicit `Variant` return type, but because the ANTLR grammar ignores comments, they get completely wiped out.

The quick-fix also turns a multiline signature into a one-liner. This wouldn't be so bad, if it didn't mean that comments can no longer be assumed to be restorable at the line and column positions they were picked up.

The only solution I see is to get the ANTLR grammar to pick up comments.

**Comment by retailcoder** [comment]
This quickfix should be modified to leverage the ANTLR `TokenStreamRewriter` and rewrite the signature only, not the entire procedure. That would fix it I think.

**Comment by ckuhn203** [comment]
A good first step here would be to stop throwing away the comments and redirect them into their own lexer channel. It may or may not enable us to do this. Won't know until we try it.

**Comment by Hosch250** [comment]
Very much obsolete.
```
' test test test test test
Function foo( _
val1 As Variant, _
val2)   ' test test test test test

End Function
```
Is turned into:
```
' test test test test test
Function foo( _
val1 As Variant, _
val2) As Variant   ' test test test test test

End Function
```
