### ISSUE TITLE
Multiple WithEvents declarations in User Forms and Classes break the parser, corrupt the error location details

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#1660]
This code parses fine
```vb
Option Explicit

Public WithEvents colCBars As Office.CommandBars
'Public WithEvents colCBars2 As Office.CommandBars
```

This code breaks the parser
```vb
Option Explicit

Public WithEvents colCBars As Office.CommandBars
Public WithEvents colCBars2 As Office.CommandBars
```

The problem doesn't seem to occur in document-type components or standard modules.

![Imgur](http://i.imgur.com/3p1v0gW.png)

![Imgur](http://i.imgur.com/6gVmEa2.png)

Furthermore, when the ParseError is inspected, the line and column number appear to be relative to the raw text file (which would seemingly include the VB Attributes). Could it be that Line/Column values are out of Sync in the Declarations section?

**Comment by retailcoder** [comment]
RE: out of sync lines - the parser error apparently came from the attributes pass, which works off an exported temp file. That's an issue on its own IMO.

Seems related to #1644
