### ISSUE TITLE
The Parser Error window doesn't refresh on reparse.

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#1666]
Which is a little confusing if the error has been fixed, or the error has changed location.

Also, should the Caption of the Parse Error window really be `Search Results`?

**Comment by retailcoder** [comment]
There is no "Parse Error window" - it's the *search results* window, used by everything that sends a tab there, including *find all references*, *find all implementations*, and ...*find all parse errors* :-)

**Comment by Hosch250** [comment]
Duplicate of #1334
