### ISSUE TITLE
Redim "is used but not assigned" duplicate inspection

### ISSUE THREAD

**Issue by joshuader6** [rubberduck-vba/Rubberduck#1667]
On commit: 8721c6c8afe1d4cd39c27f7c3326dbc1b8ebb408 

![image](https://cloud.githubusercontent.com/assets/10895412/15741328/6adaaa6e-28b9-11e6-80c4-c921f4e87f8c.png)
```
Sub tester()
Dim myarr() As Variant
Dim i As Long

ReDim myarr(1 To 10)

For i = LBound(myarr) To UBound(myarr)

Next

End Sub
```

**Comment by ThunderFrame** [comment]
I don't see any assignments there. The For..Loop is a maningless loop without any assignments. This seems like a valid inspection.

**Comment by joshuader6** [comment]
also from a vba perspective this inspection seems a little misplaced since it is common practice to declare an array and directly resize it dynamically before assigning anything.

**Comment by ThunderFrame** [comment]
I think the reason it's there three times is that it's telling you about *each* usage without having been assigned. That's probably helpful if you subsequently assign a value, so there would be some usage before assignment, and some usage after. IMO, the inspections should pick up the instances of usage before assignment.

However, the inspections fail to catch these unassigned usages *before* the assignment:

```vb
Sub tester()
Dim myarr() As Variant
Dim i As Long

ReDim myarr(1 To 10)

For i = LBound(myarr) To UBound(myarr)

Next

'Assign
myarr(1) = 10
'Reuse
For i = LBound(myarr) To UBound(myarr)

Next

End Sub
```

Here's a usage after the assignment has been erased.and/or re-redimmed i.e. it's an unassigned usage again, but the inspections don't identify it.

```vb
Private Sub tester()
Dim myarr() As Variant
Dim i As Long

ReDim myarr(1 To 10)

'Assign
myarr(1) = 10

'Erase
Erase myarr
'and Reuse
For i = LBound(myarr) To UBound(myarr)
Next

'Redim without preserve...
ReDim myarr(1 To 10)

'and Reuse
For i = LBound(myarr) To UBound(myarr)
Next

End Sub
```

And it's not limited to Arrays. Here's an integer that has unassigned usages *before* an assignment and reusage (again the inspections don't catch it)

```vb
Private Sub testerPrimitive()

  Dim i As Integer
  
  For j = i To i
  Next j
  
  i = 0
  
  For j = i To i
  Next j
  
End Sub

```

**Comment by retailcoder** [comment]
Okay. So the inspection results should be about the `Declaration`, not every single `IdentifierReference` under it. That would solve the "duplicate results" issue.

That inspection has a weird relationship with arrays; I will make it exclude arrays, and we'll implement a separate inspection that deals specifically with arrays.

@ThunderFrame you raise a good point - the inspection currently doesn't look at *where* the assignment is made, only *whether* it's made. This should be an easy fix.

**Comment by retailcoder** [comment]
@ThunderFrame `For` and `For Each` loops *are* treated as assignments. Consider:

    Dim i
    For i = 1 To 42
        Debug.Print i
    Next

Local variable `i` is both assigned and referred to here, and that code shouldn't fire up an inspection result for `i` being not used or not assigned.

**Comment by ThunderFrame** [comment]
Well, your last example is invalid VBA, and breaks with Subscript out of range, because foo() is never Dimensioned.

```
  Dim foo()  
  For i = LBound(foo) To UBound(foo)
      foo(i) = i
  Next i
```

Using the array bounds as for..loop bounds *without* assigning the array (before, or within the loop) is a usage before assignment.

```
  'Foo is used but never assigned
  Dim foo(6)
  Dim bar(6)
  For i = LBound(foo) To UBound(foo)
      bar(i) = i
  Next i
```

**Comment by retailcoder** [comment]
> breaks with Subscript out of range, because foo() is never Dimensioned.

That's the idea: catch runtime error *before* runtime :smiley:

**Comment by ThunderFrame** [comment]
Well, in that case it's a `Usage of undimensioned array` *before* it's a `Usage before assignment`

**Comment by Hosch250** [comment]
This is a pretty tricky inspection.  As for some of @ThunderFrame's examples, well, we *could* do it solely by execution-position, but what if it is redimmed/erased before other usages, but in a conditional:

```
If condition Then
    ' redim foo
ElseIf condition Then
    ' erase foo
Else
    ' do something with foo
End If

' do something else with foo
```
Now the usages of `foo` in the `Else` block will be marked as unassigned usages.

When I look at the code for this inspection, it will only report unassigned usages if the variable is never assigned.  Based on this fact, I think this should be reported on the declaration; otherwise, it should be reported on each usage based on where it is in the control flow (e.g. in the example, the last usage of `foo` after the conditional would be marked as potentially unassigned, but the usage of `foo` in the `Else` would not be).

**Comment by Hosch250** [comment]
I am going to make this warn about the declaration for now; we do not have the infrastructure to warn about specific references yet.

**Comment by Hosch250** [comment]
Unfortunately, I had to disable the quick fix because the result did not target a specific reference anymore.
