### ISSUE TITLE
For to loop false positive inspection

### ISSUE THREAD

**Issue by joshuader6** [rubberduck-vba/Rubberduck#1668]
On commit: 8721c6c8afe1d4cd39c27f7c3326dbc1b8ebb408 

Both inspections point to the first sub the second sub inspects fine: 

Seems like it doesn't like the dynamic for.

![image](https://cloud.githubusercontent.com/assets/10895412/15741899/11f8edea-28bc-11e6-9927-7ef13565f496.png)

![image](https://cloud.githubusercontent.com/assets/10895412/15741890/03817778-28bc-11e6-91c3-fa30045eb5b9.png)

```
Option Explicit

Sub test()
Dim i As Long

For i = Tabelle1.UsedRange.Rows.Count To 1 Step -1
    
Next
End Sub


Sub test2()
Dim i As Long

For i = 100 To 1 Step -1
    
Next
End Sub
```

**Comment by autoboosh** [comment]
Thanks for the info. Tabelle1.UsedRange.Rows.Count doesn't resolve yet, that's an open issue, that's why it is treated wrongly.

**Comment by retailcoder** [comment]
@autoboosh if we don't know *what we're assigning it to*, we still know what we're assigning at each iteration, right? I think failing to resolve the expression at the right of the `=` shouldn't prevent resolving the variable referenced at the left of the `=`.
