### ISSUE TITLE
Failing to use source control

### ISSUE THREAD

**Issue by mhffmn** [rubberduck-vba/Rubberduck#1674]
Hey Christopher,

I am an absolute noob to programming, but I have to do some for my work and wanted to use rubberduck.
Unfortunately I did not manage to achieve any of the above behaviour.
I..
- created an emtpy and new repository
- cloned it
- started the excel worksheet
- opened the IDE
- chose rubberduck\source control
- clicked "open working directory"
-  entered name and password and clicked ok

I cannot chose a branch nor can I do anything else that does make sense. The files are copied to the working directory but that's it.
On just trying again I got a .NET Error which is too long to paste here (see link below) - but what looks strange at first sight is a wrong path saying
"Rubberduck.SourceControl.GitProvider.get_CurrentBranch() in c:\Users\Mathieu\Source\Repos\Rubberduck\Rubberduck.SourceControl\GitProvider.cs"

Neither is there a user Mathieu nor do the subfolders exist in my user's folder.

Creating a new repo from inside rubberduck doesn't change anything.

Can you help me? I feel very stupid...

Cheers
Martin

[rubberduck.txt](https://github.com/rubberduck-vba/Rubberduck/files/296116/rubberduck.txt)

**Comment by Hosch250** [comment]
Hmm, sounds like a bug here.  First, did you create a branch in your repo, or is it an empty shell?  If you did not create a branch, RD won't be able to see any branches.

Second, "Mathieu" is one of the project owners.  It sounds as if there is something incorrectly hard-coded somewhere if you got that crash.

**Comment by retailcoder** [comment]
Hi Martin,

I'm the Mathieu you're seeing - the stack traces show the build path of whoever made the release build; next version (2.0b) should have stack traces with @Hosch250's build path :wink: 

They're just debugging info that's normally not included in a commercial product, but including all the debugging info in releases helps us tracking issues and debugging things.

Which version are you using?

**Comment by mhffmn** [comment]
Well, I created a new repo with the master branch... I'm quite new even to Git but for my other repos it works that way: creating a repository includes creating the master branch..

I'm using 1.4.3 I guess.. the latest "stable" release

**Comment by Hosch250** [comment]
> The sequence contains no matching element
>   bei System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   bei Rubberduck.SourceControl.GitProvider.get_CurrentBranch() in c:\Users\Mathieu\Source\Repos\Rubberduck\Rubberduck.SourceControl\GitProvider.cs:Zeile 83.

That is just because there isn't a branch.  Definitely something we should be looking into.

**Comment by Hosch250** [comment]
> I'm using 1.4.3 I guess.. the latest "stable" release.

If you can clone, it is probably not 1.4.3.  I wrote that long after 1.4.3 was out.

**Comment by mhffmn** [comment]
damn.. you guys are quick... :-)
Thanks

uhm.. I clone it by using tortoisGit.. forgot to mention that

**Comment by Hosch250** [comment]
Oh.  I'm betting you can't build the latest commit, and the alpha isn't stable, so...  Basically, your issue is *old*--we've rewritten the SC twice since then...  We really need to get the beta out the door.

**Comment by retailcoder** [comment]
v1.4.3 source control integration was really just an "alpha preview" that turned out being broken... basically what @Hosch250 just said: we need to stabilize the damn thing and release a beta yesterday :octocat:

**Comment by mhffmn** [comment]
wellok.. I figured out that there seem to be no branch... trying to fix that...

**Comment by mhffmn** [comment]
no error any more, but still in tab "changes" it says branch "master"
all other tabs are empty

**Comment by mhffmn** [comment]
ok.. but using rubberduck 2.xx alpha is not recommended either?

**Comment by Hosch250** [comment]
No.

**Comment by mhffmn** [comment]
allright, so I'll be patient...
Thanks a lot for your replys and efforts. It's great anyway that anyone (you! ;-) ) builds such a cool tool.
Cheers

**Comment by Hosch250** [comment]
Closing as obsolete since this is version 1.4.3.
