### ISSUE TITLE
Selecting ImplicitPublicMemberInspection from the CI window should select only the declaration.

### ISSUE THREAD

**Issue by comintern** [rubberduck-vba/Rubberduck#1680]
Given a really long function, i.e...

```VBA
Function LoooooongFunction() As Boolean

    Debug.Print "Are we there yet?"
    Debug.Print "Are we there yet?"
    Debug.Print "Are we there yet?"
    Debug.Print "Are we there yet?"
    Debug.Print "Are we there yet?"
    Debug.Print "Are we there yet?"
    Debug.Print "Are we there yet?"
    Debug.Print "Are we there yet?"
    Debug.Print "Are we there yet?"
    Debug.Print "Are we there yet?"
    Debug.Print "Are we there yet?"
    Debug.Print "Are we there yet?"
    Debug.Print "Are we there yet?"
    Debug.Print "Are we there yet?"
    Debug.Print "Are we there yet?"
    Debug.Print "Are we there yet?"
    Debug.Print "Are we there yet?"
    Debug.Print "Are we there yet?"
    Debug.Print "Are we there yet?"
    Debug.Print "Are we there yet?"
    Debug.Print "Are we there yet?"
    Debug.Print "Are we there yet?"
    Debug.Print "Are we there yet?"
    Debug.Print "Are we there yet?"
    Debug.Print "Are we there yet?"
    Debug.Print "Are we there yet?"
    Debug.Print "Are we there yet?"
    Debug.Print "Are we there yet?"
    Debug.Print "Are we there yet?"
    Debug.Print "Are we there yet?"
    Debug.Print "Are we there yet?"
    Debug.Print "Are we there yet?"
    Debug.Print "Are we there yet?"
    Debug.Print "Are we there yet?"
    Debug.Print "Are we there yet?"
    Debug.Print "Are we there yet?"
    
    LoooooongFunction = True
    
End Function
```
...the relevant *line* for the inspection is the first line.  It should really be the only line that gets selected when clicking on the inspection result.  Instead, this happens:

![screenshot from 2016-06-02 21 08 43](https://cloud.githubusercontent.com/assets/8944005/15766697/f2ee0192-2906-11e6-8001-4a5053007fb5.png)

If the entire function doesn't fit in the scrolling area of the CodePane, nothing relevant to the inspection is visible after the selection is updated.

This selection would be much more useful/informative:

![screenshot from 2016-06-02 21 16 08](https://cloud.githubusercontent.com/assets/8944005/15766730/6567e706-2907-11e6-8c0f-ce93b8930900.png)

**Comment by retailcoder** [comment]
I think I'd make it select just the `Identifier`, aka the procedure's name.

**Comment by comintern** [comment]
Either one works for me.  It's a scrollbar position issue more than anything.

**Comment by Hosch250** [comment]
I already looked into this and decided to do nothing ATM because this uses one inspection result for +/- 5 inspections, or something--all the ones with anything related to being not used, so variable, method, parameter.  The selection is determined from the context, which cannot be changed for the quick fix.  Fixing this one will break the rest.  I'll have to look again to determine whether to twist this one into returning multiple selections somehow or to split it up.  Feel free to make this a more general issue and report others if you notice them.

**Comment by Hosch250** [comment]
OK, this is a different one than the one I was thinking about (which also has the exact same issue).  I made it so each inspection could override the navigation args, instead of just using the context we pass to the quick fix, and have already fix a few.

**Comment by retailcoder** [comment]
@Hosch250 shouldn't we fix the navigation args instead of overriding it?
