### ISSUE TITLE
Code Explorer UI - a graphic spot out of place?

### ISSUE THREAD

**Issue by PeterMTaylor** [rubberduck-vba/Rubberduck#1686]
Just to put an image here I found using code explorer which has a node I believe is in the wrong place.

![capture 1649 code explorer floating node](https://cloud.githubusercontent.com/assets/2254567/15793187/b96a0996-2a25-11e6-8cde-a05bf2776f0d.PNG)

**Comment by Hosch250** [comment]
That should be vertically aligned instead of centered, yes, but that is the only thing wrong there.

**Comment by retailcoder** [comment]
@Hosch250  looks like we should be trimming newlines as well

**Comment by retailcoder** [comment]
@Hosch250 can this one be closed?

**Comment by Hosch250** [comment]
@retailcoder It wasn't fixed yet...

**Comment by Hosch250** [comment]
Reference #1726
