### ISSUE TITLE
Split declaration and assignment

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#17]
[Suggestion]

Rubberduck should recommend splitting declaration and assignment.

    Dim foo = New Bar

Can be written as:

    Dim foo
    foo = New Bar

**Comment by retailcoder** [comment]
`Dim foo = New Bar` is valid in VB.NET, but not in VBA. Rejecting this issue.

**Comment by ckuhn203** [comment]
What about?

    Dim foo As IBar: foo = New Bar

**Comment by retailcoder** [comment]
@ckuhn203 well then, do we need an inspection for *multiple instructions on a single line*?

**Comment by ckuhn203** [comment]
:+1:

**Comment by retailcoder** [comment]
That would require yet another parse tree traversal, to locate instructions separator tokens. Seems cost < benefit here...
