### ISSUE TITLE
Wrong parse tree for [basetype]

### ISSUE THREAD

**Issue by autoboosh** [rubberduck-vba/Rubberduck#1706]
It's possible to specify the as type with [basetype] or even [OBJECT] which currently is not treated as an actual base type but as a complex type. Also, OBJECT can be both a type and a value (Nothing).

```
Public Sub Test(ByVal a As [Integer])
End Sub
```

**Comment by retailcoder** [comment]
not an issue, the VBE removes the square brackets automatically.
