### ISSUE TITLE
Parameter is never used

### ISSUE THREAD

**Issue by joshuader6** [rubberduck-vba/Rubberduck#1708]
Well this is strange: 

On Commit: ccd6225f7bc752224ad494403ffb7dc469c29aa6 

![image](https://cloud.githubusercontent.com/assets/10895412/15812542/747b332c-2bb6-11e6-9e7c-c6b991062021.png)

**Comment by retailcoder** [comment]
@Hosch250 got a repro on this one?

**Comment by Hosch250** [comment]
I'll work around the image this time, but please include the raw code as well as images in the future.

**Comment by Hosch250** [comment]
No repro.  Did you not refresh the parser after you added the call?

**Comment by retailcoder** [comment]
@Hosch250 I think one of your recent commits might have fixed this.
