### ISSUE TITLE
Excel Workbook Events Byval Byref

### ISSUE THREAD

**Issue by joshuader6** [rubberduck-vba/Rubberduck#1709]
Some events in Excel require byval or byref arguments.

This is required: 
`Private Sub Workbook_BeforeSave(ByVal SaveAsUI As Boolean, Cancel As Boolean) `

![image](https://cloud.githubusercontent.com/assets/10895412/15812851/ede54be6-2bb9-11e6-96c8-f855dc5b6bf1.png)

The Fix breaks the code because vba requires cancel to be passed byref
Strange thing is that cancel can be actually modified in this code.

**Comment by joshuader6** [comment]
You can test with this code: 

```
Option Explicit

Private Sub Workbook_BeforeSave(ByVal SaveAsUI As Boolean, ByRef cancel As Boolean)

handler (cancel)
If cancel Then
    MsgBox "Save canceled"
End If

End Sub


Sub handler(ByRef cancel As Boolean)
    
    
    Select Case MsgBox("Cancel?", vbYesNo)
        Case vbYes
            cancel = True
    End Select

End Sub

```

**Comment by retailcoder** [comment]
handler (cancel)

@joshuader6 you're aware that this passes `cancel` by value, regardless of the `ByRef` specifier in `handler`?

That said built-in events *should* be recognized as such now, and ignored by the inspection, so that's definitely a bug.

**Comment by Hosch250** [comment]
Peculiar.  It isn't being picked up as an event on my machine, or even as a built-in.  I have this in ThisWorkbook...

**Comment by joshuader6** [comment]
@retailcoder  wait what ? isn't cancel evaluated after the event and is used to cancel the save ? 
so it has to be byref right ? you're totaly confusing me now ...

**Comment by retailcoder** [comment]
@joshuader6  see #1717

**Comment by Hosch250** [comment]
This issue should be resolved now--at least on the inspection side.  The fix will not work for `Workbook_` and `Worksheet_` events because we are currently having trouble resolving them correctly.
