### ISSUE TITLE
False Positive inspection On Range Property

### ISSUE THREAD

**Issue by joshuader6** [rubberduck-vba/Rubberduck#1713]
On latest next.

Given this code
```
Public Property Get Myrange() As Excel.Range
    Set Myrange = Range("myname")

End Property
```

![image](https://cloud.githubusercontent.com/assets/10895412/15822245/e685845c-2bf4-11e6-802f-2320d37ad907.png)
The return value is assigned actually as seen in the code.

**Comment by joshuader6** [comment]
I should note that this code is in a sheet module

**Comment by Hosch250** [comment]
Is this still an issue?  I cannot reproduce it.

**Comment by joshuader6** [comment]
Seems not to be
