### ISSUE TITLE
Resolving events

### ISSUE THREAD

**Issue by Hosch250** [rubberduck-vba/Rubberduck#1718]
This code should resolve to an event.  It resolves to a procedure because it is stuck into `ThisWorkbook` instead of `Workbook`.  The same problem exists for `Sheet1` and `Worksheet` and `Class1` and `Class` and `UserForm1` and `UserForm` events.  Standard modules do not have built-in events, so they don't have this problem.
```
Option Explicit

Private Sub Workbook_BeforeSave(ByVal SaveAsUI As Boolean, ByRef cancel As Boolean)

handler (cancel)
If cancel Then
    MsgBox "Save canceled"
End If

End Sub


Sub handler(ByRef cancel As Boolean)


    Select Case MsgBox("Cancel?", vbYesNo)
        Case vbYes
            cancel = True
    End Select

End Sub
```

**Comment by retailcoder** [comment]
ref. #1709

**Comment by Hosch250** [comment]
This resolves correctly to an event handler.
