### ISSUE TITLE
Incorrect COM object handling in VBEEditor/VBEHost/HostApplicationBase.cs

### ISSUE THREAD

**Issue by tcostin** [rubberduck-vba/Rubberduck#1719]
Intuitively it makes sense to consider the Application object an unmanaged resource (it's supposed to be a COM object, which is definitely unmanaged), but that is actually incorrect. The Application object is actually a special type of managed object called a RCW (runtime callable wrapper), which has its own finalizer. Hence it is actually a **managed** resource for HostApplicationBase, so Marshal.ReleaseComObject should only be called if disposing is true (and hence HostAppBase doesn't really need a finalizer).

The potential impact of this bug is somewhat subtle. If the addon is really done with the application (e.g. is shutting down), the bug has no visible effects, because Marshal.ReleaseComObject is resilient against this type of misuse. The bug has a visible impact only if all of the following hold: 
1. The finalizer for Application runs before the finalizer for HostAppBase [non-deterministic]
2. The Application object has entered the .Net world more than once (i.e. the same raw COM pointer was returned from calls to other COM objects more than once)
3. Other parts of the program still have access to other copies of said pointer and will use them in the future [not likely if addon is shutting down]

If all of the above hold, the extra call to ReleaseComObject will curdle the .Net reference count of the RCW and cause future calls to this object to fail with a InvalidComObjectException.

See eg this link: http://stackoverflow.com/questions/2085972/release-excel-object-in-my-destructor

**Comment by comintern** [comment]
I'm not sure how I see this as an issue other than just readability .  `if (Application != null)` should be operating in the same manner as `if (disposing)`.  Also, not sure how this could leak an Application object out to be released elsewhere in code - it exposes the name of the application and the run method.  There's also a one to one relationship between creations and releases, so it isn't clear how this could "curdle the .Net reference count".  At worst it's unnecessary code.

**Comment by retailcoder** [comment]
Closing as [stale] - COM management is being completely overhauled.
