### ISSUE TITLE
Code Explorer should allow node navigation with arrow keys

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#1729]
Arrow keys already work to move focus between some nodes, but moving from certain nodes causes focus to jump to Project Explorer.

**Comment by Hosch250** [comment]
Those would be project nodes, the way I set the active project.  You aren't supposed to have the PE open, though...

**Comment by Hosch250** [comment]
This is an interesting issue.  Simply setting the active VB project causes this window to lose focus, event with the PE closed.

**Comment by retailcoder** [comment]
So, make the CE get back the focus if the active VBProject was set by an action that occurred in the CE?

**Comment by Hosch250** [comment]
This is temporarily a non-issue as I removed the (incomplete) syncing between the CE and the PE.

**Comment by comintern** [comment]
Closing as obsolete - I could probably sync the highlight in the PE without selecting the item, but there isn't much point to it.
