### ISSUE TITLE
inspection for empty modules

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#1732]
What constitutes "empty"?

White space? Option statements?

**Comment by ThunderFrame** [comment]
Might need to consider whether a @Folder annotation is meaningful, if all other content is meaningless.

Might also need to determine if non-standard VB Attributes are set.

**Comment by retailcoder** [comment]
If it's empty-empty, then `OptionExplicitInspection` is already triggered.

I don't think we need an inspection for this. The code explorer would already display the module without anything under it... 

That's the rationale?

**Comment by ThunderFrame** [comment]
If VBE settings are set to *Require Variable Declaration* then `Option Explicit` is added to all new modules. If Option Explicit is missing, then the module is inspected, but if Option Explicit is present (maybe as a result of a prior inspection fix), then there aren't any inspections that notify the user of an otherwise empty module.

If a user adds modules but fails to add code, or a user removes/refactors code out of a module, they can end up with otherwise empty *and* unused modules. That leads to bloat of the project, and makes navigation more cumbersome. i.e. It's a maintainability issue.

Relying on the Code Explorer to identify empty module is problematic for several reasons:

1. Modules in large projects or inside folders aren't necessarily visible in Code Explorer without the user deliberately scrolling/expanding modules into view.
2. The absence of module members in Code Explorer isn't quite the same visual cue as a warning or an inspection that is prompting the user into action (and/or offering a quickfix).
3. As much as I'd like to see Rubberduck installed on *every* PC, there *will* be workplaces where developers *demand* Rubberduck be installed on their PCs, but their user base might not have Rubberduck installed. For projects that are developed by Rubberduckers, but distributed to non-Rubberduckers, it makes sense for the developer to be able to tidy up the project quickly. Likewise, for Rubberduckers that receive projects from users to remediate, the developer needs to be able to tidy the project up as quickly as possible. Clicking into and out of unfamiliar and empty modules, and then removing the empty ones is tedious work that can be automated.

We have inspections for other *types* that are declared but not used. Modules, and in particular class modules, are just like types in that regard, so having an inspection would fit with that paradigm.

I forget whether the issue is raised already, but we talked about an inspection for multiple blank lines/excessive white space *in* a module (because a module with 100 leading blank lines causes bloat, *looks* empty, and might be deleted inadvertently, but also might have malicious code buried beneath the fold. Removing modules is also in keeping with maintaining a trim and tidy project.

At some point we'll know whether there are unused worksheets in a workbook, or unused ActiveX controls in a worksheet, and we'll be able to remove those too.

**Comment by MDoerner** [comment]
To come back to the original question of what constitutes an empty module: I would consider a module to be empty if it has neither a `moduleConfig`, nor `moduleBody`, nor `moduleDeclarations`, expect for `moduleOption`s and `defDirective`s.

One could argue whether non-standard attributes should also make a module non-empty, but I think they do not really contribute any usefulness to the module unless there is other code as well. The same argument goes for the `moduleOption`s and `defDirective`s.

Although often technically empty, I think we should not report this for document modules since you cannot remove them anyway.
