### ISSUE TITLE
Windows Defender prevents execution of installation 2.0b.exe

### ISSUE THREAD

**Issue by PeterMTaylor** [rubberduck-vba/Rubberduck#1741]
For your information, Windows Defender in Win 10 prevents me executing the downloaded install file.

Win Def details are as follows
![capture win def stops installation 2 0 1b](https://cloud.githubusercontent.com/assets/2254567/15893090/ec2fd34e-2dc0-11e6-8f48-20a3e4b0858e.PNG)

![2016-06-08](https://cloud.githubusercontent.com/assets/2254567/15892955/1a163d08-2dc0-11e6-862d-39524b7d75b6.png)

I was able to continue and install as I know what the product does however will installation needs a signed stamp from Microsoft as a "Trusted Publisher" vs an Unknown Publisher for release 2.0?

**Comment by Hosch250** [comment]
I get this for 1.4.x too.  I'll look into signing the release build.

**Comment by retailcoder** [comment]
Could this be #1406 all over again? I didn't submit the 2.0b installer to the Microsoft Malware Protection Center, @Hosch250 can you do that? Make sure you submit the *exact same executable* (download it from the GitHub release page to be sure).

**Comment by Vogel612** [comment]
@retailcoder nope, this is different. It's basically that "Do you really wish to run this software named ... published by ..." you also get when running freshly downloaded .exe files or similar

Basically a digital signing process needs to be completed to tell the one opening the setup: "This is from Rubberduck-VBA, 5 realz"

**Comment by Hosch250** [comment]
I just made it sign the build.  I hope to do another release on Monday, but if you want, I can make you a custom build for you to check this out.

**Comment by Hosch250** [comment]
Should be done with #1751, but we might as well leave it open until it is tested.

**Comment by Hosch250** [comment]
Please check out the latest release and see if this is still an issue.

**Comment by PeterMTaylor** [comment]
Hi @Hosch250, I have checked both your OneDrive version provided eariler this week and the new Beta Release Update 1. Both shows the same results unfornuately where Win Def black listed it as above. :(

**Comment by Hosch250** [comment]
Bother.

**Comment by Hosch250** [comment]
The latest release includes a signed build.  Please see if this fixes the issue.

For referenced, to sign a build, follow the instructions here, with one exception: http://doughennig.blogspot.com/2009/11/executable-signing-with-inno-setup.html

This is the command for the signtool.exe call (the `myPath` literal can be surrounded by quotes):

> "C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\Bin\signtool.exe" sign /f myPath /p myPassword $f

The SignTool entry in Setup looks like this:

> SignTool=RubberduckSignTool /d $qRubberduck Installer$q $f

**Comment by PeterMTaylor** [comment]
Ok will check it tonite so bear with me please.

**Comment by PeterMTaylor** [comment]
ok...with RD 2.0.6 as I predicted this fails the signed executable test as it is still an Unknown Publisher according to WinDef.

![capture 2 0 6 failed to execute](https://cloud.githubusercontent.com/assets/2254567/16948201/b5b92e68-4df6-11e6-86e7-78ddee570f79.PNG)

![capture 2 0 6 failed to execute windef details](https://cloud.githubusercontent.com/assets/2254567/16948245/f4daed20-4df6-11e6-9f70-663d8eaecb75.PNG)

**Comment by Hosch250** [comment]
I'm not real sure what else to try.  I'm guessing we'd need to buy a verified certificate from one of a certain selection of vendors, or something.

**Comment by retailcoder** [comment]
F it. We're a *project*, not a *product*.

**Comment by PeterMTaylor** [comment]
Okay. Thanks folks for exploring this option.
