### ISSUE TITLE
Indenting Option Explicit causes a Parse Error

### ISSUE THREAD

**Issue by Zak-Michael-Armstrong** [rubberduck-vba/Rubberduck#1742]
Having `Option Explicit` alone in a module parses fine.

      Option Explicit

 on the other hand (or any amount of indenting) causes a parse error.

**Comment by Hosch250** [comment]
This is not limited to `Option Explicit`.  All of the following do it as well:

        Option Base 1
---
        Sub foo(): End Sub
---
        Function foo()
    
        End Function
