### ISSUE TITLE
Double-Click Folder Icon in Code Explorer causes Excel to crash

### ISSUE THREAD

**Issue by Zak-Michael-Armstrong** [rubberduck-vba/Rubberduck#1755]
MCVE:

Open new workbook.
Wait for parse.
Open Code Explorer.

Double-Clicking on Green Circles works fine.
Double-Clicking on Red Circle causes Excel to crash.

![12345](https://cloud.githubusercontent.com/assets/13286014/15936139/c4050f50-2e61-11e6-8298-4663a1d8ef3d.png)

**Comment by Hosch250** [comment]
Easy fix.
