### ISSUE TITLE
CodeExplorer Sort by option needs to be renamed

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#1759]
`Sort... by Selection` isn't particularly intuitive. 
![rd](https://cloud.githubusercontent.com/assets/11889733/15939160/88dbd32c-2e44-11e6-8f19-55e69bcad435.PNG)

Perhaps `Sort... by Declaration Order` or `Sort... by Code Order` might be more reasonable.

**Comment by Hosch250** [comment]
Wrong message :(
