### ISSUE TITLE
Find Symbol not going to item

### ISSUE THREAD

**Issue by joshuader6** [rubberduck-vba/Rubberduck#1764]
On Current Next the Find symbol (Ctrl+T) does not seem to be working properly. 

It finds stuff but klicking the Arrow only flashes the VBE. It doesn't jump to the selected object.

Also as an enhancement: How about auto expanding the dropdown when typing ?

**Comment by Hosch250** [comment]
No repro.

**Comment by retailcoder** [comment]
I like the idea of expanding the dropdown; that would be up for grabs if anyone wants to implement it.

**Comment by joshuader6** [comment]
on commit: 20c1ab7442aefd455d338468fd947183041f7c1a

still the same behavior... 

Module1: 

```
Option Explicit

Sub tester()
    Dim mytest As Long

End Sub
```

Module2: 

```
Option Explicit

Const const1 As Long = 100

```

Trying to find doesn't jump to eg. `tester`

also when pressing CTRL+T i should set the textbox active. Rightnow the textbox has to be klicked with the mouse.

**Comment by Hosch250** [comment]
Peculiar.

**Comment by Hosch250** [comment]
Ah, this is a peculiar bug.  If the component is open, but behind another component, it will select it, but not bring the component to the front.  You can't see this in this instance because your windows are all full screen on top of each other.

**Comment by Vogel612** [comment]
[status-won'tfix]? Or can we make "Go to symbol" force focus?

**Comment by Hosch250** [comment]
It already calls `ForceFocus()`...  I tried calling `win32` (or `user32`?) `SetForegoundWindow`, but it didn't work.

**Comment by Hosch250** [comment]
Looks like we may be doing it wrong: http://stackoverflow.com/questions/14876345/using-sendmessage-to-simulate-mouse-clicks

Related: http://www.pinvoke.net/default.aspx/user32.SendInput

**Comment by comintern** [comment]
The only navigation that I can replicate this with is the Find Symbol window.  My best guess is that the simulated mouse click is getting ignored because there is a modal window open.  It's doing roughly the same thing that physically clicking in the VBE window would do with the Find Symbol window open - flashing the dialog to indicate its modality, then discarding the mouse input.
