### ISSUE TITLE
Parsing Errors in 2.0 Beta release (examples)

### ISSUE THREAD

**Issue by BobTB** [rubberduck-vba/Rubberduck#1766]
This beta is a great improvement now, it shows the parser errors and does not hang immediately ! 

I have found these code snippets that compile, but do not parse (MS Access) - 1,2,3 are most probably the same parser bug.
  
1:
```
For Each fld In tdf.Fields
        Debug.Print fld.Name,
        Debug.Print FieldTypeName(fld),
        Debug.Print fld.Size,
        Debug.Print GetDescrip(fld)
    Next

```

2:
```
If Not pFault Then
            Debug.Print "FirstO:" & vbCr & ans(0) & vbCr
            Debug.Print "SecondO:"; ans(1)
End If

```

3:
 ```
For i = LBound(sortedArray) To UBound(sortedArray)
        Debug.Print sortedArray(i) & ":";
    Next i

```
4:

It is parsing #if statements in commented out code:

           ' #if defined(WIN32)
            '    unsigned long cbElements;   // Size of an element of the array.
            '                                // Does not include size of
            '                                // pointed-to data.
            '    unsigned long cLocks;       // Number of times the array has been
            '                                // locked without corresponding unlock.
            ' #Else
            '    unsigned short cbElements;
            '    unsigned short cLocks;
            '    unsigned long handle;       // Used on Macintosh only.
            ' #End If

5: Extraneous input "Type" expecting.... 

```
Private Type PictDesc
    Size As Long
Type As Long
    hBmpOrIcon As Long
    hPal As Long
End Type
```

**Comment by retailcoder** [comment]
Thanks for all the issues / bug reports - these contributions are gold!

I believe points 1, 2 and 3 are the grammar bug in #1768, where commas and semicolons come as a surprise to the parser.

Point 4 is the preprocessor grammar bug in #1769, where the preprocessor is over-zealous with commented-out code.

Point 5 is interesting... `Type` (or any other keyword that would be reserved in any other context) is a legal identifier for a `UserDefinedTypeMember` declaration, so we need to figure out a way for it to parse correctly. In the meantime renaming it to `PictType` or something, would make it work.

**Comment by ThunderFrame** [comment]
hmm, we had `Type` and `Enum` in #1286
