### ISSUE TITLE
Parser Error window can not be opened after closing

### ISSUE THREAD

**Issue by BobTB** [rubberduck-vba/Rubberduck#1767]
After the parser error window is closed, there is no way of opening it back up. The status goes from "pending", "parsing", to a quick "parser error" and then immediately thereafter to "resolving..."

Clicking on resolving does nothing, and it just stays at resolving forever. 

I think a button or a short-cut to open the parser error window would be great (if it exists, I can not find it...)

**Comment by retailcoder** [comment]
@Hosch250 looks like the tab handling and refreshing code (which is awesome!!) might have introduced this bug. Can you look into it?

**Comment by BobTB** [comment]
After reading comment on #1769 re. going to resolving even if errors are there, I am thinking that making it always stop on the parser errors will leave the option of opening the window enabled...

**Comment by retailcoder** [comment]
@BobTB ah, yes - that would make total sense; the parser errors results tab is only displayable when parser state is *error*, by design. What's *not* by design is the fact that the parser attempts to resolve identifier references despite a known parse error state.

**Comment by retailcoder** [comment]
Should be an easy fix.

**Comment by Hosch250** [comment]
Already fixed.  Will be out in the next release.
