### ISSUE TITLE
Unit Tests only run in the context of Word's ActiveDocument

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#1771]
Word's `Application.Run` method only works with `ModuleName.MethodName` or `MethodName`, so you can't uniquely address the method by prefixing with the document name or project name.

>**Note:** There seems to be subtlety to `Application.Run` with Word (I'm using 32-bit 2016)
>
>When `Application.Run` is used *in* the VBE Immediate Window or in VBA code, the `Application.Run` executes the method that is in the *ActiveProject*, and if the method doesn't exist in the ActiveProject, then VBA will try to run the method in the ActiveDocument's project. If the method isn't present in either of those locations, `Application.Run` fails.
>
>When `Application.Run` is called by Rubberduck, `Application.Run` executes the method that is in the ActiveDocument's project. If the method isn't present, `Application.Run` fails.

If you have test methods in 2 or open documents, `Application.Run` can *only* call the methods that exist in the ActiveDocument's project. If we need to execute methods in inactive documents, then we'll need to activate the document (which might trigger `Application.WindowDeactivate` and/or `Application.WindowActivate` events).

Furthermore, if the activedocument doesn't have any testmethods, then Test Explorer hangs, although I've had varying success in recovering Test Explorer, by manually activating each correct document and pressing refresh untill all tests complete)

So, I think, we have 3 options:

1. Activate the document before executing each of the test methods.
2. Only allow unit tests against the active document
3. Find another way to execute the test methods that relies on the active project (and add some code that activates the project before executing code)

I'm voting for 1, but maybe we make it user-configurable and documented?

**Comment by retailcoder** [comment]
No need to make it user-configurable. Simply setting the `VBE.ActiveVBProject` in the `WordApplication.Run` override should fix this.

**Comment by ThunderFrame** [comment]
Um, I'll gladly be proven wrong, but the ActiveProject makes no difference (see my comments about the subtlety of what is calling Application.Run). In my testing, it seems it has to be the Active document.

**Comment by ThunderFrame** [comment]
So further testing in Rubberduck confirms that Word's `Application.Run` method requires the test module's host *document* to be active, or, if the test module is in a Template, then any single document that refers to that template must be active.

If an appropriate document is already active, then nothing needs doing, but if the host document must be activated, there will be document windows activating before test executions.

**Comment by ThunderFrame** [comment]
Another observation, if a document `Document1.docm` *references* a template `Template1.dotm` *and* another document `Document2.docm` then, while `Document1` is the *ActiveDocument*, TestMethods inside the Private Module in `Template1.dotm` *are* in scope and runnable with `Application.Run`, while TestMethods inside the Private Module in `Document2.dotm` *are not* in scope and runnable with `Application.Run'
