### ISSUE TITLE
Renaming a TestModule when 2 or more unit-test documents are open results in `Resolver error`

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#1772]
it's all in the title

**Comment by Hosch250** [comment]
No repro.

**Comment by Hosch250** [comment]
Please verify that this is still an issue--I cannot reproduce it.

**Comment by Hosch250** [comment]
@ThunderFrame Can you verify that this is an issue on the latest release?

**Comment by Hosch250** [comment]
I just tried this, and it is working.  I'm guessing this dates to before I fixed the cache with renaming.  As a matter of fact, I've fixed that twice now, the latest time shortly before the last release when I refactored the sinks.
