### ISSUE TITLE
It is impossible to click items on Add menu in code explorer

### ISSUE THREAD

**Issue by BobTB** [rubberduck-vba/Rubberduck#1773]
The only thing that can be clicked is "Test module". Moving a mouse lower just closes the menu.

![adderror](https://cloud.githubusercontent.com/assets/15887688/15967039/0e957f9a-2f26-11e6-9f82-c4182380ef1a.gif)

**Comment by retailcoder** [comment]
Wah, how did that happen?! @Hosch250 all yours!

**Comment by Hosch250** [comment]
Ugh.  This looks like an Access bug.

**Comment by Hosch250** [comment]
No repro whatsoever...  If you can produce a consistently-verifiable example, I'll look into it again.
