### ISSUE TITLE
Executing tests while code is *already* running/stepping hangs TE

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#1775]
Completing the running code, and pressing refresh will allow TE to run the tests and recover. It might be useful to have an abort button in TE, if hanging continues to be an issue.

`CanExecute` should check to see if IDE is ready to run, probably before each Application.Run command (just in case callbacks or events fire during a test run).

**Comment by retailcoder** [comment]
lol, you *asked for it* didn't you haha.. right, this is a bug. We should make sure the active project isn't in debug mode before we fire up unit tests. Ideally we would disable the commands altogether, but there's nothing in the VBIDE API to tell us we're out of debug mode.

**Comment by Hosch250** [comment]
There is no way for us to abort a run, other than programmatically "pressing" the cancel button--I already looked into this.

**Comment by ThunderFrame** [comment]
@retailcoder The Debug CommandBar has some Step buttons. We could try checking those, but when I tried inspecting them from the Immediate window, they looked Enabled, but the property said they were disabled, so I figure they *flickered* while the immediate window command executed.
The other option is perhaps the Tools..References menu item, which is usally disabled while you're debugging.

@Hosch250 - I figured as much. Once those Application.Run commands are fired, they just go into the VB queue for execution....

**Comment by Hosch250** [comment]
There is also the red square "stop everything" button.

**Comment by retailcoder** [comment]
@Hosch250 I'm not talking about *aborting* a run, I'm talking about *not launching the test run at all* :smiley:

**Comment by Hosch250** [comment]
That feature will look awfully like a bug if we don't alert the user as to why we can't start.

**Comment by retailcoder** [comment]
Then let's pop a message box saying something like:

> Rubberduck cannot start a test run while in debug mode or while other code is already running. Please exit debug mode and try again.
