### ISSUE TITLE
Hijack the "import module" command in the Project Explorer and File menu

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#1777]
The Code Explorer currently implements its own "import module" functionality, which allows importing more than one module at a time.

We should completely replace the Project Explorer's "import module" command with that.

**Comment by Hosch250** [comment]
@retailcoder What are the ID's of these commands?

**Comment by ThunderFrame** [comment]
Import File control ID is 524.
Export File control ID is 525.

**Comment by A9G-Data-Droid** [comment]
The following issues need to be rolled up together:
#2047, #4012,  #4282, #3972

**Comment by bclothier** [comment]
I don't agree with rolling up the #2047 as this is fundamentally a different feature (drag'n'drop is a whole feature in itself). That said, thanks for pointing this out. This helps consolidate & consider the design of the feature. Relevant & recentish PR: #5026

**Comment by mansellan** [comment]
Closing as stale - CE has most of this functionality now, and we should avoid hijacking built-in functionality.
