### ISSUE TITLE
Notify when a new version is available

### ISSUE THREAD

**Issue by Hosch250** [rubberduck-vba/Rubberduck#1785]
When Rubberduck is first opened, it should check whether an update is available, and make an alert if it is.  Make a setting to set whether or not it ignores prerelease updates.

**Comment by ThunderFrame** [comment]
This would need to be configurable in the settings as: `Check for updates on startup`, so users can opt out.

It would also need to allow for proxy settings and `user-agent` headers in corporate environments.

This would be a chance to measure usage. So maybe pass the host name, version and bitness in the query string?

And for the response, maybe return the new version number, along with an XHTML/ATOM/RSS message that could provide detailed messages, news and alerts.

**Comment by Hosch250** [comment]
Huh?  I'm just going to query the latest release with the GitHub API.  We won't even see the current version, one way or another.

**Comment by ThunderFrame** [comment]
Oh, seemed like a good opportunity to gather usage stats.

**Comment by ThunderFrame** [comment]
IF that is too much traffic for RDweb, maybe check github, and if there is an update, then check RDweb?

**Comment by PeterMTaylor** [comment]
Are you saying @ThunderFrame that each log entry should reference which Version it belogs?

**Comment by PeterMTaylor** [comment]
How can we gather usage stats if the client/users would not share this? Just to clarify and put my thoughts about my assumptions what you meant @ThunderFrame.  We need to know if we have/had received their user's consent in relation to receiving usage except sitting on their PC's.  If that is the case you may need to update your About page to cover the ethics (side of the equation) of data management from users so they acknowledge the information received (if sent by RD other than Gibhub issues) and will be used for debugging safely.

**Comment by ThunderFrame** [comment]
@PeterMTaylor I'm unsure what you mean about log entries.

WRT privacy, terms can be in EULA, privacy-policy/terms of use link, and *opt-in* by only allowing version checks after a user accepts terms. Maybe the user can opt to request version notifications *without* providing host details.

**Comment by PeterMTaylor** [comment]
@ThunderFrame ok, I'll rephrase what I meant in another way, pardon the confusion. Reading this issue the first time round after your suggestion about usage stats. I was initially under the impression RD would permit the user to have their already assembled DEBUG/ERROR logs available for transmission down somewhere where there opporunity to understand where the bugs are occurring as part of the usage.

**Comment by Vogel612** [comment]
>  I'm just going to query the latest release with the GitHub API. We won't even see the current version, one way or another.

Sounds like this still should be an opt-in feature. A checkbox in the settings saying "Check for updates on startup" and a comparer for semver should do the trick

**Comment by retailcoder** [comment]
A simple HTTP GET request to http://rubberduckvba.com/Build/Version/Stable returns a string containing the build that's running on the website. No need for GitHub API or anything funky; just send the request (if settings allow it), compare the version numbers and prompt user whether they would like to open the https://github.com/rubberduck-vba/Rubberduck/releases page right now.
