### ISSUE TITLE
Line break in End With, and End *Procedure* statements breaks parser

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#1786]
>mismatched input '\r\n' expecting ':='

```vb
Sub test1()
  With Application
  End _
  With
End Sub
```

**Comment by ThunderFrame** [comment]
Actually, seems to be breaks in the End *procedure* statements too:

```
Property Get foo() As String

End _
Property
```
```
Sub test1()
End _
Sub
```
```
Function test2()
End _
Function
```
**But**, VBA doesn't like line breaks in `End Type` and `End Enum`
```
'VBA doesn't allow a line break - this doesn't compile
Enum foo
  Fooo = 1
End _
Enum
```
```
'VBA doesn't allow a line break - this doesn't compile
Type Bar
  Barr As String
End _
Enum
```

**Comment by autoboosh** [comment]
Looks like the END_WITH token should allow line continuations? https://github.com/rubberduck-vba/Rubberduck/blob/next/Rubberduck.Parsing/Grammar/VBALexer.g4#L116
