### ISSUE TITLE
Indenter menu items should not disable on parser failure.

### ISSUE THREAD

**Issue by comintern** [rubberduck-vba/Rubberduck#1787]
Noticed this when I was testing to see how the indenter handled @ThunderFrame's code from #1786.  Parse failed, but the menu options in the indent menu were all disabled.  The indenter currently doesn't rely on the parser (it will try to parse any old trash), so all the menu items should stay enabled.  Note that the hotkeys were _**not**_ disabled.  Not sure if that is a separate issue or not, but menu items that are disabled should not be accessible through their hotkeys.

**Comment by Hosch250** [comment]
I'm not too sure why the Indent Current Procedure was ever disabled other than for a null active code pane.  The Indent Current Module was disabled because it was checking for the NoIndent attribute, but this command shouldn't take that into account--only the CE's Indent Project command should.
