### ISSUE TITLE
Promote local variable to parameter

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#179]
As a VBA programmer, I want to have the ability to select a local (procedure-scoped) variable (or constant) declaration, and *promote* that variable to a parameter, effectively replacing that local declaration by a parameter.

**Comment by retailcoder** [comment]
Related: #386

**Comment by retailcoder** [comment]
This should be called "Introduce Parameter" in the "Refactor" menu

**Comment by Hosch250** [comment]
Reference commit: https://github.com/rubberduck-vba/Rubberduck/pull/878/files
