### ISSUE TITLE
Resolver Error after successful parsing in Beta 2.0.1b

### ISSUE THREAD

**Issue by BobTB** [rubberduck-vba/Rubberduck#1795]
The project (approx 18k lines) parses successfully after I fix the #1766 parser errors manually. I get the resolver error thereafter. Here is the log attached, which has some lines possibly telling what is wrong and why resolver has errors. 

Code explorer works great in-spite of this. Parser knows which functions were not changed and does not parse them again :) great stuff !

[ResolverError.txt](https://github.com/rubberduck-vba/Rubberduck/files/310311/ResolverError.txt)

**Comment by retailcoder** [comment]
Interesting, a NRE thrown *acquiring* declarations...

>  Access9db.Global Code.;
2016-06-11 17:19:35.7697;ERROR;Rubberduck.Parsing.VBA.RubberduckParser;Exception thrown acquiring declarations for 'Global Code' (thread 14).;System.NullReferenceException: Object reference not set to an instance of an object.

**Comment by Hosch250** [comment]
I can't reproduce this--would it be possible for you to share the offending project with me, or a minimal verifiable example?

**Comment by BobTB** [comment]
I had to uninstall the latest rubberduck beta to finish some work. After a new beta update will be available with the parsing error fixes ( #1788, #1766,  #1769 #1790...) I will try it again on the same project to see what happens, perhaps it was all cause and effect of these...

**Comment by Hosch250** [comment]
Because this is a resolver error instead of a parser error, those changes are unlikely to fix it.  Also, this is a pretty serious issue, so I'd like to verify that it is fixed before I do another release.

**Comment by BobTB** [comment]
ok, I will try to get an example asap

**Comment by Hosch250** [comment]
Thank you.

**Comment by BobTB** [comment]
I have just emailed a verifiable example to rubberduckvba mail, it has some licensed code, I can not share here, it is mostly empty and does nothing, but it parses and then throws resolver error.

**Comment by Hosch250** [comment]
Thanks.

**Comment by Hosch250** [comment]
Parses and resolves correctly, and reaches state Ready.  Will trash this file to protect the licensed code.

**Comment by Hosch250** [comment]
Let's hope this is fixed, and if you have another issue after the release, just let us know.
