### ISSUE TITLE
Code Explorer window resizing - signature width

### ISSUE THREAD

**Issue by BobTB** [rubberduck-vba/Rubberduck#1796]
Code Explorer window should show as much of the signature as it fits in the window. 

![codeexplorer](https://cloud.githubusercontent.com/assets/15887688/15986128/595f1c2c-3000-11e6-9ab0-9efe8a499143.gif)

**Comment by ThunderFrame** [comment]
Not just *With* signatures, some node names *without* signatures can be long, or just deep in the tree.

**Comment by mansellan** [comment]
Looks like this was fixed - closing issue.
