### ISSUE TITLE
Inspection `Procedure is not referred to` is not yielding any hits for public methods

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#1802]
Neither procedure is picked up as unused in this project code:
```
Sub Foo()
  Application.Run "Bar"
End Sub

Sub Bar()
End Sub
```
Nor this Private module code:
```
Option Private Module

Sub Foo()
  Application.Run "Bar"
End Sub

Sub Bar()
End Sub
```

But both procedures are detected as unused (even though `Bar` *is* used (with `Application.Run`) by `Foo`, once the methods are *declared* private at the procedure level):

```
Private Sub Foo()
  Application.Run "Bar"
End Sub

Private Sub Bar()
End Sub
````

**Comment by Hosch250** [comment]
/// <remarks>
    /// We cannot determine whether exposed members of standard modules are called or not,
    /// so we assume they are instead of flagging them as "never called".
    /// </remarks>
