### ISSUE TITLE
Test Explorer doesn't display correct Project name after project rename

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#1806]
>Wait for PR #1805 to merge (or pull from my Next) before trying to fix this issue, as 1805 adds better support for tests in multiple projects.

I have 2 projects (both unsaved) that each have a single Test Module with a single Test Method. The Test Modules and Test Methods were inserted using the RD Test menu, and are identical in each project.

Here's a screenshot of the projects while they have common ProjectNames, ModuleNames and MethodNames. Note that Test Explorer makes it impossible to identify which TestMethod is which (we should maybe add the DisplayName to help with this).

![Imgur](http://i.imgur.com/QDJxlvP.png)

And here is a screenshot after I rename the Book2 Project name to `VBAProject2`

![Imgur](http://i.imgur.com/xhvYMVj.png)

Note that Code Explorer has refreshed and is reflecting the correct Project Names, but while Test Explorer has also refreshed, it doesn't reflect the new Project Name.

If I try to execute All Tests at this point, Test Explorer hangs.

**Comment by Hosch250** [comment]
Yeah, yeah, nasty bug here.  I'm going to have to compare project/component names and remove the non-matches, losing the test result.  Shouldn't be too hard--will do fairly soon.
