### ISSUE TITLE
Handling sink events

### ISSUE THREAD

**Issue by Hosch250** [rubberduck-vba/Rubberduck#1808]
The sink event handlers do not ensure that the project they are fired from is the one we are managing.  Deleting ProjectA.Module1 would delete SourceControlledProject.Module1

**Comment by retailcoder** [comment]
@Hosch250 could this be an opportunity to pull the sink handlers out of the `App` class?

**Comment by Hosch250** [comment]
No, this is a small `if` in the source control handler.  I will look into refactoring that soon, but not quite yet.
