### ISSUE TITLE
Code Inspection results do not refresh after changing Settings

### ISSUE THREAD

**Issue by Stevefb** [rubberduck-vba/Rubberduck#1826]
After changing Language Opportunities for 'Call' statement usage to "Do Not Show" the Code Inspections window does not seem to update.

**Comment by retailcoder** [comment]
Should we re-run inspections after inspection settings are modified? Do `Call` statement usages trigger inspection results after setting them to `DoNotShow` and refreshing inspections?

@Hosch250 there's a use-case for refreshing inspection results without requiring a reparse!

**Comment by Hosch250** [comment]
@retailcoder Want to review this?
