### ISSUE TITLE
Code Inspection false positive: constant 'ABC' not used

### ISSUE THREAD

**Issue by Stevefb** [rubberduck-vba/Rubberduck#1827]
False positive, constant detected as unused but Const is used as part of Select Case in a standard code module, MS Word.
```
Public Const ABC As Long = 1
Sub FalsePos()
    Select Case result
        Case ABC               <-- This use is not detected
            ' Do Something
    End Select
End Sub
```
Build 2.0.1.33906

**Comment by Stevefb** [comment]
2nd Example of False Positive...

```
Sub FalsePositive2 ()
    Const XYZ As String = "myProj.FalsePositive2"
    If Not Something Is Nothing Then myClass.Something XYZ    <-- This use is not detected
    ' Do Stuff
End Sub
```

**Comment by Hosch250** [comment]
No repro on either of these.

**Comment by Hosch250** [comment]
Could you provide the project you are using to duplicate this?  I can't duplicate it in an empty project with just this code.

**Comment by retailcoder** [comment]
@Hosch250 IMO this points to a silently failing resolver pass.

**Comment by Stevefb** [comment]
Morning! @Hosch250 

Sorry the project is not mine to share, I'll try to reproduce the issue and share that instead.  A few things to note:
1. now that I have applied all the suggested fixes the specific issue (Select Case) has disappeared from my code
2. a similar false positive has come to light in the Code Inspection results:
`myString = CONST1 & "someLiteral"`

Will let you know when I have something I can share

**Comment by Stevefb** [comment]
@Hosch250 I have a simple document that reproduces this issue, let me know if you want it. Basic steps and observations are:

1  Create New document, add userform with this code:
```
Option Explicit

Private Sub UserForm_Activate()
    Const RUBBERY As String = "Activate.LittleBlackDuck"
    FalsePos RUBBERY
End Sub
```
2  Add Sub to standard Module (Module1) with this code:
```
'Option Explicit       <-- Comment out to get the False Positive

Sub FalsePos(ByVal thisString As String)
Debug.Print thisString
End Sub
```
3  Run the Code Inspection
The false positive for the Const seems to happen when Option Explicit is missing.  

**Observations:**
I was able to find other ways to get a false positive result for Const RUBBERY.  Adding Option Explicit to Module1 and then adding a second dummy module (Module2) WITHOUT Option Explicit also gave the same false positive... so it seems a non related module without Option Explicit can potentially cause this?!
```
Sub Something()
Debug.Print "Ducky"
End Sub
```

**Comment by Stevefb** [comment]
Oh - should mention this applies to: RD 2.0.2b, edc2df2

**Comment by retailcoder** [comment]
Do you have logging enabled? Hopefully there's an exception thrown in the resolver, and logs have valuable stack trace information. I'll still try to repro, this glitch with/without `Option Explicit` is rather troubling.

**Comment by Stevefb** [comment]
To be honest I'm finding Word less stable than usual so the short answer is no.  I can enable it for specific tests but between RD and my own code word normal way of shutting down is by Not Responding...

**Comment by Hosch250** [comment]
I still have no repro, following your instructions exactly.

**Comment by Stevefb** [comment]
What's the best way to share a file?

**Comment by Hosch250** [comment]
Just upload it right in this issue--drag/drop should work.

**Comment by Stevefb** [comment]
Rename from .zip to .dotm
[SlowLearner.zip](https://github.com/rubberduck-vba/Rubberduck/files/324437/SlowLearner.zip)

**Comment by Hosch250** [comment]
I only see 16 issues in that document, and Constant Not Used is not one of them.

**Comment by Stevefb** [comment]
@Hosch250 my baby and I just downloaded the zip file, etc and got same issue.  Note we are using the beta preview .2b 
Cheers

**Comment by Hosch250** [comment]
Resolved with unknown commit.
