### ISSUE TITLE
Return value of function 'iReturnSomething' is never used

### ISSUE THREAD

**Issue by Stevefb** [rubberduck-vba/Rubberduck#1828]
Inspection results have numerous examples of false positives, for example I have a function called OffSet like this:
```
Function OffSet(someTable As Table) As Integer
    OffSet = someTable.Rows.Count -1
End Function

Sub UsesOffSet()
    Dim iOffSet as Integer
        iOffSet = modT.OffSet(Selection.Range.Tables(1))    <-- Result Used, but not detected
End Sub
```

Build: 2.0.1.33906

**Comment by retailcoder** [comment]
Is parser state `Ready`? If it's `Resolver Error`, the inspections shouldn't even be allowed to run.

I added a module `modT` to a new VBA project, pasted the above code in, and got no repro - inspections toolwindow is showing 14 results, all legit:

	Rubberduck Code Inspections - 06/15/2016 09:46:21
	14 issues found.
	Suggestion: Project has default name - (Book2) VBAProject., line 1
	Hint: Member 'OffSet' is implicitly public - (Book2) VBAProject.modT, line 1
	Hint: Member 'UsesOffSet' is implicitly public - (Book2) VBAProject.modT, line 5
	Suggestion: Consider renaming class 'Sheet1' - (Book2) VBAProject.Sheet1, line 1
	Suggestion: Consider renaming class 'Sheet2' - (Book2) VBAProject.Sheet2, line 1
	Suggestion: Consider renaming class 'Sheet3' - (Book2) VBAProject.Sheet3, line 1
	Hint: Parameter 'someTable' is implicitly passed by reference - (Book2) VBAProject.modT, line 1
	Error: Option Explicit is not specified in 'modT' - (Book2) VBAProject.modT, line 1
	Error: Option Explicit is not specified in 'Sheet1' - (Book2) VBAProject.Sheet1, line 1
	Error: Option Explicit is not specified in 'Sheet2' - (Book2) VBAProject.Sheet2, line 1
	Error: Option Explicit is not specified in 'Sheet3' - (Book2) VBAProject.Sheet3, line 1
	Error: Option Explicit is not specified in 'ThisWorkbook' - (Book2) VBAProject.ThisWorkbook, line 1
	Suggestion: Parameter 'someTable' can be passed by value - (Book2) VBAProject.modT, line 1
	Warning: variable 'iOffSet' is not used - (Book2) VBAProject.modT, line 6

If I right-click the `OffSet` function's identifier and select Rubberduck > Find all references, it finds two references:

![image](https://cloud.githubusercontent.com/assets/5751684/16082105/6b62d202-32de-11e6-8a5a-0245d1120eac.png)

One in `UsesOffSet`, the other being the `OffSet` result assignment.

Do you have logging enabled? I suspect a resolver issue somewhere else, above the code you posted, throwing an exception and resulting in cancellation of the identifier references pass. Set the *minimum log level* to `Trace`:

![image](https://cloud.githubusercontent.com/assets/5751684/16082267/c94efd32-32de-11e6-9645-137e4143f200.png)

Then parse your project and get to the log - you can upload the text file here.

**Comment by Stevefb** [comment]
@retailcoder Only just noticed your comments... will have a look and see what I can get

**Comment by Stevefb** [comment]
@retailcoder  Ok I have reproduced in a file that I can send. Looking into it now...

**Comment by Stevefb** [comment]
Ok, I think this also relates to the use of Option Explicit... 

Blank doc, Module1 Has:
```
Option Explicit
Function OffSet(someTable As Table) As Integer
    OffSet = someTable.Rows.Count - 1
End Function
```
Module3 has (NO option explicit)
```
Sub UsesOffSet()
    Dim iOffSet As Integer
        iOffSet = OffSet(Selection.Range.Tables(1)) '   <-- Result Used, but not detected
        Debug.Print iOffSet
End Sub
```
Code Inspection result is that Return Value of function 'OffSet' is never used.

**Comment by Hosch250** [comment]
There have been two releases since this issue was created.  Can you verify that it is still an issue?

**Comment by Stevefb** [comment]
@Hosch250  I can confirm that this is no longer creating a false +ve in my test document. Thanks :)
