### ISSUE TITLE
Source Control - Unexpected behaviour from VS2015 prompts me for SourceCode

### ISSUE THREAD

**Issue by PeterMTaylor** [rubberduck-vba/Rubberduck#1829]
Ok, I have re-cloned (deleted files and copied clone) latest commit https://github.com/rubberduck-vba/Rubberduck/commit/1ae56310cc55e0167b436e952d4ca66a82656534
Started using the SourceControl for a bit on an Excel code and pressed the initial repro button.
Received an unexpected behaviour/response from VS2015 to open a source code believed @Hosch250  was working on which I obviously have no access to.

![capture prompt sourcecontrol fileloadexception was unhandled](https://cloud.githubusercontent.com/assets/2254567/16078269/488e76ec-3341-11e6-8ce6-ee8630e17baa.PNG)
![capture prompt sourcecontrolviewviewmodel within vs2015 not exist](https://cloud.githubusercontent.com/assets/2254567/16078270/48a1d7dc-3341-11e6-93ca-d495b1520555.PNG)
![capture prompt sourcecontrolviewviewmodel within vs2015](https://cloud.githubusercontent.com/assets/2254567/16078271/48a70b1c-3341-11e6-9a5a-f136a4aedb3c.PNG)

**Comment by Hosch250** [comment]
This is... most peculiar.  I've had this before (in the test project), but I never was able to solve it...  I had to create a new test project (which didn't matter, because the tests weren't working for anyone).

**Comment by PeterMTaylor** [comment]
Sorry wrong button on my ipad

**Comment by retailcoder** [comment]
I repro'd many times. Probably something in the debug config for the SC assembly that's responsible for this... not sure.. just cancel-out and things should work anyway, I'm pretty sure it's just a debugger issue. It *is* annoying though.

**Comment by bclothier** [comment]
Closing this as inapplicable now that we deprecated source control.
