### ISSUE TITLE
Indenter settings

### ISSUE THREAD

**Issue by Talorthain** [rubberduck-vba/Rubberduck#1841]
Hi,

Changing the settings for the indentation, dont save when click OK. The defaults work correctly.

File version is: Rubberduck.Setup.2.0.1b (updated 1)

Regards

Anthony

p.s newest version is a big jump in the right direction. Brilliant work.

![settings after](https://cloud.githubusercontent.com/assets/6796503/16110939/419bdfde-33a8-11e6-9452-bffc991ba4f8.PNG)
![settings](https://cloud.githubusercontent.com/assets/6796503/16110940/419db71e-33a8-11e6-82ef-dedb01be0f49.PNG)

**Comment by Hosch250** [comment]
No repro here.  That is very peculiar...

**Comment by comintern** [comment]
No repro here either.

**Comment by Talorthain** [comment]
I set the options and when I click ok and go back in, they are back to the defaults. Could this be an antivirus issue?

 

I am using office 2016 desktop – Excel.

 

Regards

 

Anthony

**Comment by Hosch250** [comment]
No, this isn't an AV issue.

**Comment by Talorthain** [comment]
I had no issues when I installed the program and I used the program on a clean excel project.

**Comment by Talorthain** [comment]
I will have to reinstall it. I had to remove, becuase I am working on a time critical project (e.g my bosses expect it sooner rather than later!!)

I will do tomorrow..

**Comment by Talorthain** [comment]
Hi,
I have reinstalled the program and I am getting the same issue. What is the file you need? I cant see a config file in the rubberduck folder...

**Comment by Talorthain** [comment]
Hi, I have reinstalled. And I have the same issue. what file do you need me to attach, because I can see a config file in the rubberduck folder?

**Comment by Hosch250** [comment]
OK, that may well be the bug.  Which folder are you looking in?  It should be in `C:\Users\{user}\AppData\Roaming\Rubberduck`.  And you don't get a `rubberduck.config` file if you press OK in the settings view?  What about if you press Reset, then OK?

**Comment by Talorthain** [comment]
Hi,

 

                I have just checked the location you have stated and I don’t even have a rubberduck folder, never mind a config file. I have tried reset and ok, but nothing.

 

                I am also getting a crash on exit of excel.

 

 

Regards

 

Anthony

**Comment by comintern** [comment]
Permissions issue maybe?  Try manually creating a C:\Users\{user}\AppData\Roaming\Rubberduck folder.  Once you have the folder there, see if you can create an empty file named rubberduck.config inside the folder.  If you can do both of those things, try saving the settings again and see if anything is written to the file.  I can't imaging not having R\W access to AppData\Roaming, but I've been in some pretty strange security environments.

**Comment by Talorthain** [comment]
Hi,

 

                Your suggestion worked.

 

The environment is nothing special or changed from the default. It’s a home PC and not a work computer. It’s a standard win10 install with office 2016 desktop, so there should be nothing affecting the process.

 

I am still getting;

 



 

On exit.

 

Regards

 

Anthony

**Comment by comintern** [comment]
OK, I reproduced this by removing my AppData\Roaming\Rubberduck folder.  @Hosch250 @retailcoder - any ideas why this why it would be created by the installer?

**Comment by Hosch250** [comment]
I have no idea, and I was just about to comment that I had reproduced it too.

**Comment by comintern** [comment]
PR on the way for settings, but it's still going to need a fix everywhere we access the folder to cover the case where it is manually removed afterward.  The logger bombs output with...

> A first chance exception of type 'System.IO.DirectoryNotFoundException'

...from a bunch of different places.

**Comment by Hosch250** [comment]
Would it be possible to put the same check in `Create`?  Or better yet, extract it into a `EnsureDirectoryExists` method that `Create` and `Save` both call.

**Comment by comintern** [comment]
It's not just settings.  The logger needs a fix too.  Is it reasonable to just check for the required paths on start-up and create them there?  That would cover everything except the case where the folder gets deleted while RD is running.

**Comment by Vogel612** [comment]
interfering with that folder while the logger has a lock onto the log-files should make deleting it a pain anyways. I daresay that ensuring the folders exist on startup fixes the issue the cleanest way possible. We don't need to prepare for all possibilities

**Comment by Hosch250** [comment]
I just merged the fix.  This will be out in the next release.

**Comment by Talorthain** [comment]
Can I just clarify, The folder and file was never created on install or when rubberduck was run. The file and folder was never deleted.

 

Regards

 

Anthony

**Comment by Hosch250** [comment]
Yes, the fix will make sure the folder exists when Rubberduck starts.  I will probably release it late next Friday (June 24), so be sure to download it then.
