### ISSUE TITLE
changed project properties

### ISSUE THREAD

**Issue by Talorthain** [rubberduck-vba/Rubberduck#1842]
Rubber duck option to rename project selectable, but didnt work.
Selected project properties from right click menu
Changed some details, due to a name change by management
Runtime error

I am using newest version of the file.

Regards

Anthony
![changed project properties](https://cloud.githubusercontent.com/assets/6796503/16111200/5cc3dfcc-33a9-11e6-9486-c2c9927621d9.PNG)

**Comment by Hosch250** [comment]
See #1611
