### ISSUE TITLE
Opening a project in Access leaves RD status in "Resolving"

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#1843]
Every time I open an Access 2010 project in the IDE, the RD status bar gets to the "Resolving" display, then hangs:

![rd - resolving in access](https://cloud.githubusercontent.com/assets/11889733/16116943/8ac3489c-339d-11e6-858f-651eb632d304.PNG)
I'm not sure how long it's been this way, but it's been long enough for me to get a screen cap (twice), draw some nifty circles, then look through the issue log to see if it had been reported. A minimum of 10 mintues.

Here is the log file:

[rubberduck.log.txt](https://github.com/rubberduck-vba/Rubberduck/files/318364/rubberduck.log.txt)

**Comment by Hosch250** [comment]
Might be the result of the COM exception, and the resolver being incorrectly triggered somehow when the state should be Parser Error (although I'm pretty sure that bug was already fixed...)

**Comment by Hosch250** [comment]
Can you verify that this is still an issue with the latest release?

**Comment by BobTB** [comment]
I can verify that. It goes through parsing, and starts resolving (uses a lot of CPU for some time while doing this) thereafter it just stays in resolving at 0% cpu. I am using latest 2.0.2b.

**Comment by Hosch250** [comment]
Huh.  I've been testing with Access a lot lately, and I've not had this problem.

**Comment by BobTB** [comment]
Which version of Access are you running? I can replicate this in 2007 and 2010, and even 2003 - which works completely the same

**Comment by Hosch250** [comment]
2016.

**Comment by BobTB** [comment]
true, it should not.. I do not have a newer version here at the moment, but can try in a day or two to see if there is any difference and will report back.

**Comment by Hosch250** [comment]
I'll be making a new release with lots of bug fixes (and likely a few new bugs) late Friday, if you want to wait for it.

**Comment by BobTB** [comment]
Here is also my log when this happened. It does not look to healthy in the middle while going from parsing to resolving
[resolver.txt](https://github.com/rubberduck-vba/Rubberduck/files/330897/resolver.txt)
 :)

**Comment by AndrewM-** [comment]
I am also using ms-access 2010 and it just through parsing\resolving and inspecting in about 40 seconds for a 20 KLOC project (46 KLOC with whitespace and comments).  However the processor remains running a speed with my laptop fan running flat out.  The ms-access process is using 50%+ of resources on a core i7.     RD Build 2.0.2.41756

**Comment by Hosch250** [comment]
That was probably it trying to load the inspection results.  For some reason, we are experiencing horrific performance there, and with that large of a project, it could easily spend a minute or so trying to load them.

**Comment by AndrewM-** [comment]
The high processor use after 'Ready' appears runs for many minutes not just one.  The task manager just shows ms-access as the application.  It is reassuring that you know the issue and are working on it.

**Comment by BobTB** [comment]
ok, this new release (2.0.3b) seems better, but still stops consuming CPU and just stays at "resolving declarations", the log file is different

, here it is attached, seem it has some problems just at the end with a lot of "Rubberduck.Parsing.Symbols.TypeAnnotationPass;Failed to resolve type"

[rubberduck.txt](https://github.com/rubberduck-vba/Rubberduck/files/333032/rubberduck.txt)

**Comment by Hosch250** [comment]
OK.  Would there be any chance you could share the file?  It sounds like there is a bug somewhere in the resolver.

**Comment by BobTB** [comment]
Yes, I cam. I just sent it to the rubberduck gmail.

**Comment by Hosch250** [comment]
Thanks.  I'll check this out Monday.
