### ISSUE TITLE
Broken inspection: "Object reference 'x' is self assigned"

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#1846]
That error message fires on this code:

```
Public Function CreateExcelTable(ByRef Sheet As Worksheet, ByVal TopRow As Long, ByVal LeftCol As Long, ByVal BotRow As Long, ByVal RightCol As Long, ByVal TableName As String) As ListObject

  Dim NewTable As ListObject
  Set NewTable = Sheet.ListObjects.Add(xlSrcRange, Sheet.Range(Sheet.Cells(TopRow, LeftCol), Sheet.Cells(BotRow, RightCol)), xlListObjectHasHeaders:=xlYes)
  NewTable.Name = TableName
  Set CreateExcelTable = NewTable
  
End Function
```

Highlighting `NewTable As ListObject`

**Comment by Hosch250** [comment]
I tried putting this in a workbook, worksheet, class module, and std module, and I can't reproduce this.

**Comment by daFreeMan** [comment]
hrm... "5 days ago" I would have been running 2.01b, we're now on 2.0.2b.  I'll see if I can repro myself, otherwise, I'll close it.

**Comment by daFreeMan** [comment]
Sorry, @Hosch250, I am still getting the error.
I'm attaching a workbook where it happens. 
[RD Issue 1846.zip](https://github.com/rubberduck-vba/Rubberduck/files/330210/RD.Issue.1846.zip)
![rd issue 1846](https://cloud.githubusercontent.com/assets/11889733/16307837/b86de340-3930-11e6-81bc-8ca4d5e8e60b.PNG)
