### ISSUE TITLE
Code Inspection: False Positive for UserForm events in MS Word

### ISSUE THREAD

**Issue by Stevefb** [rubberduck-vba/Rubberduck#1851]
Results from Code Inspection:

> Rubberduck Code Inspections - 06/17/2016 08:44:05
> 2765 issues found.
> <snip>
> Warning: procedure 'UserForm_Activate' is not used - (myProject_a.dotm) myProject.frm_Invisi, line 7
> Warning: procedure 'UserForm_Initialize' is not used - (myProject_a.dotm) myProject.frm_Invisi, line 23
> Warning: procedure 'UserForm_QueryClose' is not used - (myProject_a.dotm) myProject.frm_Invisi, line 43
> <snip>

As far as I can tell this applies to all userforms in my project. Tested Word 2010 (Home & Business) with RD beta 2.0.1.33906

**Comment by Hosch250** [comment]
Huh, I thought I'd fixed those...

**Comment by Stevefb** [comment]
@Hosch250 I think it must have been fixed for the UserForm controls, none of the code attached to my buttons (e.g. cmdExit_OnClick) are showing up in the Inspection, but somehow the default events are showing up. Hope this helps.

**Comment by Hosch250** [comment]
The default events are not showing up for me in a userform (.frm) document.  How'd you manage to get the file extension `frm_Invisi`?

**Comment by Stevefb** [comment]
frmInvisi - that's the name of the UserForm as entered in the Properties panel, and that's exactly what RD is reporting back in the inspection results, I used the copy button and pasted to a text editor...  I don't see any .frm extension, where are you looking?

**Comment by Hosch250** [comment]
Oh, OK.  What is the file extension when you export the component?

**Comment by Stevefb** [comment]
Exporting gives a .frm & .frx

**Comment by Hosch250** [comment]
OK, this has me pretty stumped.

**Comment by retailcoder** [comment]
@Hosch250 I'm not following, what would the exported extension have anything to do with the issue? Form events are always going to be `UserForm_EventName`, and we know what these events are from iterating the MSForms library (which is automatically referenced when a form is added to a project)... IMO the problem looks like we're not telling the resolver that `vbext_ct_UserForm` vbcomponents inherit the `UserForm` class (or whatever it's called under the hood).

**Comment by Hosch250** [comment]
Would it be possible for me to see this project (or a minimal verifiable example)?  I might have overlooked something.

**Comment by Stevefb** [comment]
@Hosch250 @ThunderFrame  I can send you the project if you like, but was easy to reproduce.  Steps:

1. Start Word
2. Save the blank doc as FileName.dotm
3. Open IDE
4. Add UserForm
5. Add methods from dropdown: _Activate, _Initialize, & _QueryClose
6. Put code in each method:  MsgBox "EventName"
7. Run the RDCode Inspector

Results: 
http://i.stack.imgur.com/CPX7S.png  <-- Basic Project
http://i.stack.imgur.com/I6pZl.png  <-- Review Results

**Comment by Hosch250** [comment]
Weirrrrddd.  I finally had a repro--it seems saving the file makes all the difference :astonished: Anyway, I'll look at this tomorrow.  Interestingly enough, `_Click`, and `_KeyDown` are registered correctly as events...

**Comment by Hosch250** [comment]
Actually, saving doesn't make a difference--this is a bug in Excel too.

**Comment by Hosch250** [comment]
Huh, a handful of them aren't picked up by the COM collector at all, including these three.

**Comment by A9G-Data-Droid** [comment]
This issue is back in the latest version.


> Warning: Procedure 'UserForm_Initialize' is not used - , line 10
> Warning: Procedure 'UserForm_Initialize' is not used - , line 10
> Warning: Procedure 'UserForm_Activate' is not used - , line 15
> Warning: Procedure 'UserForm_Initialize' is not used - , line 10
> Warning: Procedure 'UserForm_Initialize' is not used - 
> Warning: Event 'Deactivate' is not used - (FM20.DLL) MSForms.FormEvents, line 1
> Warning: Event 'Initialize' is not used - (FM20.DLL) MSForms.FormEvents, line 1
> Warning: Event 'Resize' is not used - (FM20.DLL) MSForms.FormEvents, line 1
> Warning: Event 'Activate' is not used - (FM20.DLL) MSForms.FormEvents, line 1
> Warning: Event 'Terminate' is not used - (FM20.DLL) MSForms.FormEvents, line 1
> Warning: Event 'QueryClose' is not used - (FM20.DLL) MSForms.FormEvents, line 1
>

**Comment by Vogel612** [comment]
@A9G-Data-Droid please open a new issue with sufficient information to reproduce the problem, preferrably linking back to this issue.

Makes organizing them much easier
