### ISSUE TITLE
MS Word - Code Inspection: Constant is Implicitly Variable, won't fix (sometimes crashes Word)

### ISSUE THREAD

**Issue by Stevefb** [rubberduck-vba/Rubberduck#1853]
In MS Word, constants that are untyped show up correctly in the Code Inspection results. 

Trying to fix the constants doesn't change the code, and often (almost always) crashes MS Word. 

Note: So far this is for constants only, variables and parameters are fixed almost immediately.

**Comment by Hosch250** [comment]
Invalid cast because the parser changed, and the inspection was never updated.
