### ISSUE TITLE
Code Inspection - False Positive: Variable is never assigned (MS Word)

### ISSUE THREAD

**Issue by Stevefb** [rubberduck-vba/Rubberduck#1854]
Getting a false positive in this situation:
```
Sub varIsUsed()
Dim oFld As Field
  For Each oFld in ActiveDocument.Fields
    ' Do Something
  Next oFld
End Sub
```

**Comment by Stevefb** [comment]
Actually, I have a ton of "Variable is never assigned results"... and lots of them are for really straightforward things... 

I also just noticed a massive jump in the number of Code Inspection results... from 1489 to 4510 for Code Quality issues, the same code as used previously, using default settings (same as previously).  It seems that the extra 3000 issues could be all the variables in my project....   gotta love MS Word

**Comment by Stevefb** [comment]
@retailcoder @Hosch250 found something interesting with this.  I went back to my code from Wednesday (the 1st time I ran the Code Inspection, which I posted a sanitised version of the inspection results) and re-ran the Inspection.  I got the same result, as expected.

I then compared the today's version (3000 extra false positives) with Wednesdays code, the main difference was that I introduced a Const at the TOP of every single module...

Const PROC_NAME As String = "ModuleName.MethodName"

My very best guess is that these 2 things are related....

**Comment by Stevefb** [comment]
Right, I went and commented out the line Const PROC_NAME.... saved, ( @Hosch250 that's important ) and ran the Code Inspection on my current code base...  Result.... I'm short about 3000 False Positives!

Conclusion.... the line Const PROC_NAME .... has interfered with the Code Inspection.

**Comment by Stevefb** [comment]
And now for the @Hosch250  'weird' bit.... as a final stretch of my imagination I did a global find and replace on the commented out:
`' Const PROC_NAME As String = "....`
and replaced it with
`Const PROC_NAME = "....`   (deleted As String)

And re-ran the Code Inspection, I'm still short ~3000 False Positives... so my updated conclusion is that it  is specifically the "As String" that interferes with the Code Inspection...

**Comment by Hosch250** [comment]
Can you verify that this is still an issue and give exact steps to duplicate it, or share a workbook with this issue?

**Comment by Stevefb** [comment]
@Hosch250  - tested in a dev build & confirmed this issue resolved.
