### ISSUE TITLE
Indent

### ISSUE THREAD

**Issue by jpngo** [rubberduck-vba/Rubberduck#1858]
The indent format doesn't work with IF... ELSEIF... ELSE... END IF statement.

**Comment by retailcoder** [comment]
Thanks! Got sample code to reproduce the issue?

**Comment by comintern** [comment]
Also, it would help if you can upload your rubberduck.config file (should be in C:\Users{user}\AppData\Roaming\Rubberduck) or a screenshot of your indenter settings.

**Comment by comintern** [comment]
Found it.

```vba
Private Sub Testing()
If Foo Then Bar Else
Baz
End If
End Sub
```
...indents to...

```vba
Private Sub Testing()
    If Foo Then Bar Else
    Baz
End If
End Sub
```

**Comment by jpngo** [comment]
Here is the sample formatted codes:
![2016-06-17 14_23_21-microsoft visual basic for applications - ap-sd development - modedi2 code](https://cloud.githubusercontent.com/assets/4174897/16165155/2a457116-3497-11e6-8a55-b725b2f618a0.png)

And here is my setting:
![2016-06-17 14_24_49-settings](https://cloud.githubusercontent.com/assets/4174897/16165192/60d10aa6-3497-11e6-980a-d7a3e5549352.png)
Thank you.
