### ISSUE TITLE
Resolver Hangs in MS Word - New Document, No Code In Any Module (except Option Explicit)

### ISSUE THREAD

**Issue by Stevefb** [rubberduck-vba/Rubberduck#1872]
This seems 100% reproducible on my system.  Click on MS Word icon to start MS Word and open the default blank document.  Open VBA IDE (Alt + F11, if that makes a difference).  I see RD status changing until it hits "Resolving" then it stops.  This morning I left it Resolving for about 15 mins.... no change when I got back.

NOTE: I do NOT have any code in the Normal template, except for Option Explicit which was put there by the VBA IDE.  

At trace item 09:07:56.2622 I pressed the "Refresh" button on the RD toolbar.... things went quickly from there.  

**RD Trace Log** (stuck on resolving is bold)**:**
2016-06-20 

> 08:50:17.4929;DEBUG;Rubberduck.UI.Command.MenuItems.RubberduckCommandBar;RubberduckCommandBar status text changes to 'Loading references'.;
> 2016-06-20 08:50:17.5241;DEBUG;Rubberduck.UI.Command.MenuItems.RubberduckCommandBar;RubberduckCommandBar status text changes to 'Loading references'.;
> 2016-06-20 08:50:17.6934;DEBUG;Rubberduck.UI.Command.MenuItems.RubberduckCommandBar;RubberduckCommandBar status text changes to 'Loading references'.;
> 2016-06-20 08:50:17.8406;DEBUG;Rubberduck.UI.Command.MenuItems.RubberduckCommandBar;RubberduckCommandBar status text changes to 'Loading references'.;
> 2016-06-20 08:50:17.8562;DEBUG;Rubberduck.UI.Command.MenuItems.RubberduckCommandBar;RubberduckCommandBar status text changes to 'Loading references'.;
> 2016-06-20 08:50:18.1566;DEBUG;Rubberduck.Parsing.Symbols.DebugDeclarations;Loading custom declarations with VBA as parent project and Information as parent module.;
> 2016-06-20 08:50:18.1788;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'ThisDocument' state is changing to 'Pending' (thread 8);
> 2016-06-20 08:50:18.1788;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;ParserState evaluates to 'Pending' (thread 8);
> 2016-06-20 08:50:18.1944;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'ThisDocument' state is changing to 'Pending' (thread 8);
> 2016-06-20 08:50:18.1944;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;ParserState evaluates to 'Pending' (thread 8);
> 2016-06-20 08:50:18.2413;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'ThisDocument' state is changing to 'Pending' (thread 8);
> 2016-06-20 08:50:18.2413;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;ParserState evaluates to 'Pending' (thread 8);
> 2016-06-20 08:50:18.2569;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'ThisDocument' state is changing to 'Pending' (thread 6);
> 2016-06-20 08:50:18.2569;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;ParserState evaluates to 'Pending' (thread 6);
> 2016-06-20 08:50:18.2569;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'ThisDocument' state is changing to 'Parsing' (thread 8);
> 2016-06-20 08:50:18.2569;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;ParserState evaluates to 'Parsing' (thread 8);
> 2016-06-20 08:50:18.2569;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;ParserState changed to 'Parsing', raising OnStateChanged;
> 2016-06-20 08:50:18.2725;DEBUG;Rubberduck.UI.Inspections.InspectionResultsViewModel;InspectionResultsViewModel handles StateChanged...;
> 2016-06-20 08:50:18.2725;DEBUG;Rubberduck.UI.Command.MenuItems.RubberduckCommandBar;RubberduckCommandBar handles StateChanged...;
> 2016-06-20 08:50:18.2725;DEBUG;Rubberduck.UI.Command.MenuItems.RubberduckCommandBar;RubberduckCommandBar status text changes to 'Parsing...'.;
> 2016-06-20 08:50:18.2725;DEBUG;Rubberduck.App;App handles StateChanged (Parsing), evaluating menu states...;
> 2016-06-20 08:50:18.3665;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'ThisDocument' state is changing to 'Parsing' (thread 6);
> 2016-06-20 08:50:18.3665;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;ParserState evaluates to 'Parsing' (thread 6);
> 2016-06-20 08:50:18.4749;TRACE;Rubberduck.Parsing.VBA.ComponentParseTask;IParseTree for component 'ThisDocument' acquired in 0ms (thread 6);
> 2016-06-20 08:50:18.5006;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'ThisDocument' state is changing to 'Parsed' (thread 6);
> 2016-06-20 08:50:18.5006;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;ParserState evaluates to 'Parsing' (thread 6);
> 2016-06-20 08:50:18.5076;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Module 'ThisDocument' was NOT modified;
> 2016-06-20 08:50:18.5076;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'ThisDocument' state is changing to 'Resolving' (thread 6);
> 2016-06-20 08:50:18.5236;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;ParserState evaluates to 'Resolving' (thread 6);
> 2016-06-20 08:50:18.5236;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;ParserState changed to 'Resolving', raising OnStateChanged;
> 2016-06-20 08:50:18.5236;DEBUG;Rubberduck.UI.Inspections.InspectionResultsViewModel;InspectionResultsViewModel handles StateChanged...;
> 2016-06-20 08:50:18.5236;DEBUG;Rubberduck.UI.Command.MenuItems.RubberduckCommandBar;RubberduckCommandBar handles StateChanged...;
> 2016-06-20 08:50:18.5236;DEBUG;Rubberduck.UI.Command.MenuItems.RubberduckCommandBar;RubberduckCommandBar status text changes to 'Resolving...'.;
> 2016-06-20 08:50:18.5236;DEBUG;Rubberduck.App;App handles StateChanged (Resolving), evaluating menu states...;
> **2016-06-20 08:50:18.5812;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Creating declarations for module Project.ThisDocument.;**
> NB: _Pressed Refresh @ 09:07:56_
> 2016-06-20 09:07:56.2622;DEBUG;Rubberduck.Parsing.Symbols.DebugDeclarations;Loading custom declarations with VBA as parent project and Information as parent module.;
> 2016-06-20 09:07:56.2782;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'ThisDocument' state is changing to 'Pending' (thread 26);
> 2016-06-20 09:07:56.2782;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;ParserState evaluates to 'Resolving' (thread 26);
> 2016-06-20 09:07:56.2782;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'ThisDocument' state is changing to 'Ready' (thread 26);
> 2016-06-20 09:07:56.2882;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;ParserState evaluates to 'Pending' (thread 26);
> 2016-06-20 09:07:56.2882;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;ParserState changed to 'Pending', raising OnStateChanged;
> 2016-06-20 09:07:56.2882;DEBUG;Rubberduck.UI.Inspections.InspectionResultsViewModel;InspectionResultsViewModel handles StateChanged...;
> 2016-06-20 09:07:56.2882;DEBUG;Rubberduck.UI.Command.MenuItems.RubberduckCommandBar;RubberduckCommandBar handles StateChanged...;
> 2016-06-20 09:07:56.2882;TRACE;Rubberduck.UI.SourceControl.SourceControlViewViewModel;Refreshing display;
> 2016-06-20 09:07:56.2882;DEBUG;Rubberduck.UI.Command.MenuItems.RubberduckCommandBar;RubberduckCommandBar status text changes to 'Pending'.;
> 2016-06-20 09:07:56.2882;DEBUG;Rubberduck.App;App handles StateChanged (Pending), evaluating menu states...;
> 2016-06-20 09:07:56.3716;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'ThisDocument' state is changing to 'Pending' (thread 26);
> 2016-06-20 09:07:56.3716;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;ParserState evaluates to 'Pending' (thread 26);
> 2016-06-20 09:07:56.3716;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'ThisDocument' state is changing to 'Parsing' (thread 26);
> 2016-06-20 09:07:56.3816;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;ParserState evaluates to 'Parsing' (thread 26);
> 2016-06-20 09:07:56.3816;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;ParserState changed to 'Parsing', raising OnStateChanged;
> 2016-06-20 09:07:56.3816;DEBUG;Rubberduck.UI.Inspections.InspectionResultsViewModel;InspectionResultsViewModel handles StateChanged...;
> 2016-06-20 09:07:56.3816;DEBUG;Rubberduck.UI.Command.MenuItems.RubberduckCommandBar;RubberduckCommandBar handles StateChanged...;
> 2016-06-20 09:07:56.3816;DEBUG;Rubberduck.UI.Command.MenuItems.RubberduckCommandBar;RubberduckCommandBar status text changes to 'Parsing...'.;
> 2016-06-20 09:07:56.3816;DEBUG;Rubberduck.App;App handles StateChanged (Parsing), evaluating menu states...;
> 2016-06-20 09:07:56.4285;TRACE;Rubberduck.Parsing.VBA.ComponentParseTask;IParseTree for component 'ThisDocument' acquired in 0ms (thread 26);
> 2016-06-20 09:07:56.4476;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'ThisDocument' state is changing to 'Parsed' (thread 26);
> 2016-06-20 09:07:56.4476;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;ParserState evaluates to 'Parsed' (thread 26);
> 2016-06-20 09:07:56.4476;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;ParserState changed to 'Parsed', raising OnStateChanged;
> 2016-06-20 09:07:56.4476;DEBUG;Rubberduck.UI.Inspections.InspectionResultsViewModel;InspectionResultsViewModel handles StateChanged...;
> 2016-06-20 09:07:56.4476;DEBUG;Rubberduck.UI.Command.MenuItems.RubberduckCommandBar;RubberduckCommandBar handles StateChanged...;
> 2016-06-20 09:07:56.4476;DEBUG;Rubberduck.UI.Command.MenuItems.RubberduckCommandBar;RubberduckCommandBar status text changes to 'Parsed'.;
> 2016-06-20 09:07:56.4476;DEBUG;Rubberduck.App;App handles StateChanged (Parsed), evaluating menu states...;
> 2016-06-20 09:07:56.4958;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Module 'ThisDocument' was NOT modified;
> 2016-06-20 09:07:56.4958;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'ThisDocument' state is changing to 'Resolving' (thread 26);
> 2016-06-20 09:07:56.4958;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;ParserState evaluates to 'Resolving' (thread 26);
> 2016-06-20 09:07:56.4958;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;ParserState changed to 'Resolving', raising OnStateChanged;
> 2016-06-20 09:07:56.4958;DEBUG;Rubberduck.UI.Inspections.InspectionResultsViewModel;InspectionResultsViewModel handles StateChanged...;
> 2016-06-20 09:07:56.5079;DEBUG;Rubberduck.UI.Command.MenuItems.RubberduckCommandBar;RubberduckCommandBar handles StateChanged...;
> 2016-06-20 09:07:56.5079;DEBUG;Rubberduck.UI.Command.MenuItems.RubberduckCommandBar;RubberduckCommandBar status text changes to 'Resolving...'.;
> 2016-06-20 09:07:56.5079;DEBUG;Rubberduck.App;App handles StateChanged (Resolving), evaluating menu states...;
> 2016-06-20 09:07:56.5504;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Creating declarations for module Normal.ThisDocument.;
> 2016-06-20 09:07:56.5584;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;ParserState changed to 'ResolvedDeclarations', raising OnStateChanged;
> 2016-06-20 09:07:56.5584;DEBUG;Rubberduck.UI.Inspections.InspectionResultsViewModel;InspectionResultsViewModel handles StateChanged...;
> 2016-06-20 09:07:56.6061;DEBUG;Rubberduck.UI.Command.MenuItems.RubberduckCommandBar;RubberduckCommandBar handles StateChanged...;
> 2016-06-20 09:07:56.6061;DEBUG;Rubberduck.App;App handles StateChanged (ResolvedDeclarations), evaluating menu states...;
> 2016-06-20 09:07:56.6711;TRACE;Rubberduck.Parsing.Symbols.ProjectReferencePass;Built-in project references linked up in 1ms.;
> 2016-06-20 09:07:56.7239;DEBUG;Rubberduck.Parsing.Symbols.TypeHierarchyPass;Type hierarchies built in 43ms.;
> 2016-06-20 09:07:56.7688;WARN;Rubberduck.Parsing.Symbols.TypeAnnotationPass;Failed to resolve type VBProject;
> 2016-06-20 09:07:56.7688;WARN;Rubberduck.Parsing.Symbols.TypeAnnotationPass;Failed to resolve type VBE;
> 2016-06-20 09:07:56.8247;WARN;Rubberduck.Parsing.Symbols.TypeAnnotationPass;Failed to resolve type VBProject;
> 2016-06-20 09:07:56.8404;WARN;Rubberduck.Parsing.Symbols.TypeAnnotationPass;Failed to resolve type VBE;
> 2016-06-20 09:07:56.8404;TRACE;Rubberduck.Parsing.Symbols.TypeAnnotationPass;Type annotations completed in 116ms.;
> 2016-06-20 09:07:56.8559;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Resolving identifier references in 'Normal.ThisDocument'... (thread 27);
> 2016-06-20 09:07:56.8559;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Binding Resolution done for component 'ThisDocument' in 0ms (thread 27);
> 2016-06-20 09:07:56.8872;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'ThisDocument' state is changing to 'Ready' (thread 27);
> 2016-06-20 09:07:56.8872;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;ParserState evaluates to 'Ready' (thread 27);
> 2016-06-20 09:07:56.8872;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;ParserState changed to 'Ready', raising OnStateChanged;
> 2016-06-20 09:07:56.8872;DEBUG;Rubberduck.UI.Inspections.InspectionResultsViewModel;InspectionResultsViewModel handles StateChanged...;
> 2016-06-20 09:07:56.8872;DEBUG;Rubberduck.UI.Inspections.InspectionResultsViewModel;Running code inspections...;
> 2016-06-20 09:07:56.9051;DEBUG;Rubberduck.UI.Command.MenuItems.RubberduckCommandBar;RubberduckCommandBar status text changes to 'Inspecting...'.;
> 2016-06-20 09:07:56.9151;DEBUG;Rubberduck.UI.Command.MenuItems.RubberduckCommandBar;RubberduckCommandBar handles StateChanged...;
> 2016-06-20 09:07:56.9151;DEBUG;Rubberduck.UI.Command.MenuItems.RubberduckCommandBar;RubberduckCommandBar status text changes to 'Ready'.;
> 2016-06-20 09:07:56.9445;DEBUG;Rubberduck.App;App handles StateChanged (Ready), evaluating menu states...;
> 2016-06-20 09:07:56.9866;DEBUG;Rubberduck.UI.Command.MenuItems.RubberduckCommandBar;RubberduckCommandBar status text changes to 'Ready'.;
> 2016-06-20 09:07:57.0240;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;'ThisDocument' is Ready (thread 27);

**Comment by Hosch250** [comment]
I can't reproduce this.
