### ISSUE TITLE
Line Numbers Cause Parser Errors: extraneous input ' ' expecting {ABS, ....

### ISSUE THREAD

**Issue by Stevefb** [rubberduck-vba/Rubberduck#1873]
Error goes away when line numbers are removed, reappears with line numbers.  

I know line numbers are horrid and evil... but... right now they are the best way for me to pin-point errors (using the erl statement).

**Comment by ThunderFrame** [comment]
@Stevefb Got some sample code?

**Comment by Stevefb** [comment]
@ThunderFrame @Hosch250  New Document, no modules, no classes.  Put the following into ThisDocument:
```
Option Explicit
Sub SomeCode()
1         On Error GoTo eh       ' <-- Parse Error is at end of "Error" (between 'r' and ' ')
3         For i = 1 To 10
              ' do something
5         Next i
lbl_Exit:
7         Exit Sub
eh:
9         Err.Clear
11        Resume lbl_Exit
End Sub
```
Save, close and re-open, open IDE and on my PC there will be a Parse Error.

Further... if I remove the line numbers and refresh all's good EXCEPT I've just noticed there is a false negative for Code Inspections:
- Variable i is not declared, despite Option Explicit
- i is implicitly Variant (not sure if this should be picked up yet)

Here's the actual report - hope it helps.

> Rubberduck Code Inspections - 06/20/2016 19:59:01
> 3 issues found.
> Hint: Member 'SomeCode' is implicitly public - (20160620 Testing comments.docm) Project.ThisDocument, line 3
> Suggestion: Consider renaming line label 'eh' - (20160620 Testing comments.docm) Project.ThisDocument, line 13
> Warning: procedure 'SomeCode' is not used - (20160620 Testing comments.docm) Project.ThisDocument, line 3

**Comment by ThunderFrame** [comment]
It seems the parser expects colons after line numbers:

This code parses and resolves:

But because of the Option Explicit, it doesn't actually compile, and nor does Rubberduck find that the variable `i` is undeclared.

```vb
Option Explicit

Sub SomeCode()
1:         On Error GoTo eh       ' <-- Parse Error is at end of "Error" (between 'r' and ' ')
3:         For i = 1 To 10
              ' do something
5:         Next i
lbl_Exit:
7:         Exit Sub
eh:
9:         Err.Clear
11:        Resume lbl_Exit
End Sub
```

**Comment by ThunderFrame** [comment]
hmm, interesting, this code parses and resolves:

It seems a line number *and* a label is valid VBA, and in this instance, the line number *doesn't* need to be immediately followed by a colon for Rubberduck to parse it successfully.

```vb
Sub SomeCode()
1 foo: Debug.Print Now()
End Sub
```

**Comment by Stevefb** [comment]
I have been using line numbers in my code for ever... until I read a [post](http://codereview.stackexchange.com/a/94462/86050) (erm @retailcoder rant?) on the topic of error handling.  I still use them, but am working towards not relying on them in the way I have been...  Point, that I ought to reach is that RD will eventually give sensible looking results, even with code that has line numbers... I'm not quite sure what the pattern is for RD to spit out a Parse Err when line numbers are involved, but ver 1 certainly didn't force me to abandon line numbers...
