### ISSUE TITLE
Uninstalling release version does not clear eventlog registry key

### ISSUE THREAD

**Issue by Cogito** [rubberduck-vba/Rubberduck#1874]
I was trying to build from source, after installing and uninstalling the release version.

I was getting an error: 

> The command "eventcreate /ID 1 /L APPLICATION /T INFORMATION /SO RubberDuck.VBE /D "Deploying Rubberduck from Visual Studio Build"" exited with code 1.
> Source parameter is used to identify custom applications/scripts only (not installed applications).

I found some info at the [the linked website](https://blogs.msdn.microsoft.com/aaron_margosis/2013/11/01/eventcreate-and-error-source-parameter-is-used-to-identify-custom-applicationsscripts-only/), showing that this error will present when trying to create a registry key for the eventlog, when one already exists.

I tracked down the key and removed it, which allowed the build to then work. This is the key:

> HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\eventlog\Application\Rubberduck-VBA

This also appears to be the root cause of https://github.com/rubberduck-vba/Rubberduck/issues/1156

**Comment by Hosch250** [comment]
@retailcoder Would this (the last `if` block) fix this?

```
procedure UnregisterAddin();
begin
  UnregisterAddinForIDE(HKCU32, 'Software\Microsoft\VBA\VBE\6.0\Addins', '{#AddinProgId}');
  if IsWin64() then 
    UnregisterAddinForIDE(HKCU64, 'Software\Microsoft\VBA\VBE\6.0\Addins64', '{#AddinProgId}');

  if RegKeyExists(HKLM, 'SYSTEM\CurrentControlSet\services\eventlog\Application\Rubberduck-VBA') then
    RegDeleteKeyIncludingSubkeys(HKLM, 'SYSTEM\CurrentControlSet\services\eventlog\Application\Rubberduck-VBA');
end;
```

**Comment by retailcoder** [comment]
Has this been fixed yet?

**Comment by Cogito** [comment]
I haven't tested it recently, no idea if still happens or not.

**Comment by retailcoder** [comment]
Per [current nlog config](https://github.com/rubberduck-vba/Rubberduck/blob/134923994b908779d980c42e98f5c9604ed744ab/RetailCoder.VBE/NLog.dll.nlog), EventLog is no longer being [tentatively] written to.
