### ISSUE TITLE
Excel Crashes on `Init New Repo from this project`

### ISSUE THREAD

**Issue by Zak-Michael-Armstrong** [rubberduck-vba/Rubberduck#1875]
MCVE: Open New Workbook. Open VBE. Go to `Init Nee Repo from this project`. Select Destination. 

Then Excel crashes.

This was with Beta Release (maybe Update 1). 

Just upgraded to Beta Update 2 and instead of immediately crashing, Excel becomes unresponsive and has to be killed from task manager.

Just downgraded to Alpha Hotfix 1 and Source Control is working normally.

Trace Log from Wb Open (original attempt):

> 2016-06-20 09:19:16.8618;DEBUG;Rubberduck.App;Project 'Project1' was added.;
> 2016-06-20 09:19:16.9008;DEBUG;Rubberduck.App;Components sink registered and advising.;
> 2016-06-20 09:19:16.9008;DEBUG;Rubberduck.App;App handles StateChanged (Pending), evaluating menu states...;
> 2016-06-20 09:19:16.9388;DEBUG;Rubberduck.UI.Command.MenuItems.RubberduckCommandBar;RubberduckCommandBar status text changes to 'Pending'.;
> 2016-06-20 09:19:18.0234;DEBUG;Rubberduck.UI.Command.MenuItems.RubberduckCommandBar;RubberduckCommandBar status text changes to 'Loading references'.;
> 2016-06-20 09:19:18.0654;DEBUG;Rubberduck.UI.Command.MenuItems.RubberduckCommandBar;RubberduckCommandBar status text changes to 'Loading references'.;
> 2016-06-20 09:19:18.5033;DEBUG;Rubberduck.UI.Command.MenuItems.RubberduckCommandBar;RubberduckCommandBar status text changes to 'Loading references'.;
> 2016-06-20 09:19:19.0021;DEBUG;Rubberduck.UI.Command.MenuItems.RubberduckCommandBar;RubberduckCommandBar status text changes to 'Loading references'.;
> 2016-06-20 09:19:19.7779;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'ThisWorkbook' state is changing to 'Pending' (thread 7);
> 2016-06-20 09:19:19.7969;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;ParserState evaluates to 'Pending' (thread 7);
> 2016-06-20 09:19:19.8209;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'Sheet1' state is changing to 'Pending' (thread 7);
> 2016-06-20 09:19:19.8209;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;ParserState evaluates to 'Pending' (thread 7);
> 2016-06-20 09:19:20.1088;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'ThisWorkbook' state is changing to 'Pending' (thread 7);
> 2016-06-20 09:19:20.1088;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;ParserState evaluates to 'Pending' (thread 7);
> 2016-06-20 09:19:20.2558;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'Sheet1' state is changing to 'Pending' (thread 7);
> 2016-06-20 09:19:20.2558;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;ParserState evaluates to 'Pending' (thread 7);
> 2016-06-20 09:19:20.2748;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'ThisWorkbook' state is changing to 'Parsing' (thread 6);
> 2016-06-20 09:19:20.2748;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;ParserState evaluates to 'Parsing' (thread 6);
> 2016-06-20 09:19:20.2748;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;ParserState changed to 'Parsing', raising OnStateChanged;
> 2016-06-20 09:19:20.2857;DEBUG;Rubberduck.UI.Inspections.InspectionResultsViewModel;InspectionResultsViewModel handles StateChanged...;
> 2016-06-20 09:19:20.2857;DEBUG;Rubberduck.UI.Command.MenuItems.RubberduckCommandBar;RubberduckCommandBar handles StateChanged...;
> 2016-06-20 09:19:20.2857;DEBUG;Rubberduck.UI.Command.MenuItems.RubberduckCommandBar;RubberduckCommandBar status text changes to 'Parsing...'.;
> 2016-06-20 09:19:20.2857;DEBUG;Rubberduck.App;App handles StateChanged (Parsing), evaluating menu states...;
> 2016-06-20 09:19:20.5717;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'Sheet1' state is changing to 'Parsing' (thread 7);
> 2016-06-20 09:19:20.5717;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;ParserState evaluates to 'Parsing' (thread 7);
> 2016-06-20 09:19:20.6336;TRACE;Rubberduck.Parsing.VBA.ComponentParseTask;IParseTree for component 'ThisWorkbook' acquired in 0ms (thread 6);
> 2016-06-20 09:19:20.6336;TRACE;Rubberduck.Parsing.VBA.ComponentParseTask;IParseTree for component 'Sheet1' acquired in 0ms (thread 7);
> 2016-06-20 09:19:20.7776;DEBUG;Rubberduck.UI.Command.MenuItems.ParentMenus.ParentMenuItemBase;(17107576) Executing click handler for menu item '&Source Control', hash code 63059925;
> 2016-06-20 09:19:21.0405;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'ThisWorkbook' state is changing to 'Parsed' (thread 6);
> 2016-06-20 09:19:21.0405;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;ParserState evaluates to 'Parsing' (thread 6);
> 2016-06-20 09:19:21.2824;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'Sheet1' state is changing to 'Parsed' (thread 7);
> 2016-06-20 09:19:21.2864;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;ParserState evaluates to 'Parsed' (thread 7);
> 2016-06-20 09:19:21.2864;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;ParserState changed to 'Parsed', raising OnStateChanged;
> 2016-06-20 09:19:21.2864;DEBUG;Rubberduck.UI.Inspections.InspectionResultsViewModel;InspectionResultsViewModel handles StateChanged...;
> 2016-06-20 09:19:21.2864;DEBUG;Rubberduck.UI.Command.MenuItems.RubberduckCommandBar;RubberduckCommandBar handles StateChanged...;
> 2016-06-20 09:19:21.2864;DEBUG;Rubberduck.UI.Command.MenuItems.RubberduckCommandBar;RubberduckCommandBar status text changes to 'Parsed'.;
> 2016-06-20 09:19:21.2994;DEBUG;Rubberduck.App;App handles StateChanged (Parsed), evaluating menu states...;
> 2016-06-20 09:19:21.4044;TRACE;Rubberduck.Parsing.VBA.RubberduckParser;Starting resolver task;
> 2016-06-20 09:19:21.4074;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;ParserState changed to 'Resolving', raising OnStateChanged;
> 2016-06-20 09:19:21.4074;DEBUG;Rubberduck.UI.Inspections.InspectionResultsViewModel;InspectionResultsViewModel handles StateChanged...;
> 2016-06-20 09:19:21.4074;DEBUG;Rubberduck.UI.Command.MenuItems.RubberduckCommandBar;RubberduckCommandBar handles StateChanged...;
> 2016-06-20 09:19:21.4074;DEBUG;Rubberduck.UI.Command.MenuItems.RubberduckCommandBar;RubberduckCommandBar status text changes to 'Resolving...'.;
> 2016-06-20 09:19:21.4074;DEBUG;Rubberduck.App;App handles StateChanged (Resolving), evaluating menu states...;
> 2016-06-20 09:19:21.6573;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Module 'Sheet1' was NOT modified;
> 2016-06-20 09:19:21.7983;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Creating declarations for module VBAProject.Sheet1.;
> 2016-06-20 09:19:22.2102;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Module 'ThisWorkbook' was NOT modified;
> 2016-06-20 09:19:22.2941;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Creating declarations for module VBAProject.ThisWorkbook.;
> 2016-06-20 09:19:22.4961;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;ParserState changed to 'ResolvedDeclarations', raising OnStateChanged;
> 2016-06-20 09:19:22.5091;DEBUG;Rubberduck.UI.Inspections.InspectionResultsViewModel;InspectionResultsViewModel handles StateChanged...;
> 2016-06-20 09:19:22.5821;DEBUG;Rubberduck.UI.Command.MenuItems.RubberduckCommandBar;RubberduckCommandBar handles StateChanged...;
> 2016-06-20 09:19:22.5821;DEBUG;Rubberduck.App;App handles StateChanged (ResolvedDeclarations), evaluating menu states...;
> 2016-06-20 09:19:22.7270;TRACE;Rubberduck.Parsing.Symbols.ProjectReferencePass;Built-in project references linked up in 2ms.;
> 2016-06-20 09:19:22.7970;DEBUG;Rubberduck.Parsing.Symbols.TypeHierarchyPass;Type hierarchies built in 62ms.;
> 2016-06-20 09:19:22.9589;WARN;Rubberduck.Parsing.Symbols.TypeAnnotationPass;Failed to resolve type VBProject;
> 2016-06-20 09:19:23.0869;WARN;Rubberduck.Parsing.Symbols.TypeAnnotationPass;Failed to resolve type VBE;
> 2016-06-20 09:19:23.0979;TRACE;Rubberduck.Parsing.Symbols.TypeAnnotationPass;Type annotations completed in 285ms.;
> 2016-06-20 09:19:23.2119;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Resolving identifier references in 'VBAProject.Sheet1'... (thread 7);
> 2016-06-20 09:19:23.2169;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Binding Resolution done for component 'Sheet1' in 0ms (thread 7);
> 2016-06-20 09:19:23.3518;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'Sheet1' state is changing to 'Ready' (thread 7);
> 2016-06-20 09:19:23.3518;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;ParserState evaluates to 'Parsed' (thread 7);
> 2016-06-20 09:19:23.3578;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;ParserState changed to 'Parsed', raising OnStateChanged;
> 2016-06-20 09:19:23.3578;DEBUG;Rubberduck.UI.Inspections.InspectionResultsViewModel;InspectionResultsViewModel handles StateChanged...;
> 2016-06-20 09:19:23.3578;DEBUG;Rubberduck.UI.Command.MenuItems.RubberduckCommandBar;RubberduckCommandBar handles StateChanged...;
> 2016-06-20 09:19:23.3578;DEBUG;Rubberduck.UI.Command.MenuItems.RubberduckCommandBar;RubberduckCommandBar status text changes to 'Parsed'.;
> 2016-06-20 09:19:23.3578;DEBUG;Rubberduck.App;App handles StateChanged (Parsed), evaluating menu states...;
> 2016-06-20 09:19:23.4688;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;'Sheet1' is Ready (thread 7);
> 2016-06-20 09:19:23.5438;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Resolving identifier references in 'VBAProject.ThisWorkbook'... (thread 7);
> 2016-06-20 09:19:23.5438;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Binding Resolution done for component 'ThisWorkbook' in 0ms (thread 7);
> 2016-06-20 09:19:23.6727;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'ThisWorkbook' state is changing to 'Ready' (thread 7);
> 2016-06-20 09:19:23.6727;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;ParserState evaluates to 'Ready' (thread 7);
> 2016-06-20 09:19:23.6727;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;ParserState changed to 'Ready', raising OnStateChanged;
> 2016-06-20 09:19:23.6727;DEBUG;Rubberduck.UI.Inspections.InspectionResultsViewModel;InspectionResultsViewModel handles StateChanged...;
> 2016-06-20 09:19:23.6727;DEBUG;Rubberduck.UI.Inspections.InspectionResultsViewModel;Running code inspections...;
> 2016-06-20 09:19:23.6967;DEBUG;Rubberduck.UI.Command.MenuItems.RubberduckCommandBar;RubberduckCommandBar status text changes to 'Inspecting...'.;
> 2016-06-20 09:19:23.7107;DEBUG;Rubberduck.UI.Command.MenuItems.RubberduckCommandBar;RubberduckCommandBar handles StateChanged...;
> 2016-06-20 09:19:23.7307;DEBUG;Rubberduck.UI.Command.MenuItems.RubberduckCommandBar;RubberduckCommandBar status text changes to 'Ready'.;
> 2016-06-20 09:19:23.7937;DEBUG;Rubberduck.App;App handles StateChanged (Ready), evaluating menu states...;
> 2016-06-20 09:19:23.9826;DEBUG;Rubberduck.UI.Command.MenuItems.RubberduckCommandBar;RubberduckCommandBar status text changes to 'Ready'.;
> 2016-06-20 09:19:24.1856;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;'ThisWorkbook' is Ready (thread 7);

**Comment by daFreeMan** [comment]
I was able to successfully `Init New Repo from this Project` in Excel 2010 using RD 2.0.2b (Build 2.0.2.41756).

**Comment by Zak-Michael-Armstrong** [comment]
Maybe relevant. this is Excel 15.0.4823.1004

**Comment by Hosch250** [comment]
Reference #1814
