### ISSUE TITLE
Fix for obsolete Call modifier turns multi-statement lines into labels

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#1877]
So it turns out there *is* an obscure use case for `Call`

When using multiple statements in a single line, if the first statement is a method call, it must use `Call`, otherwise it is treated as a label:

```vb
'This is valid code, bar is called once, foo is called twice
Sub SomeCode()
  bar: bar
  Call foo: foo
End Sub
```

If I apply the obsolete Call fix, I get:
```vb
'This time bar is called once, foo is called once.
Sub SomeCode()
  bar: bar
  foo: foo
End Sub
```

I still think that Call should be avoided, so maybe the fix in this instance should be:
```vb
'This is valid code, bar is called once, foo is called twice
Sub SomeCode()
  bar: bar
  foo
  foo
End Sub
```

**Comment by retailcoder** [comment]
This is a known thing. TBH the problem is multiple statements in a single code line; perhaps the inspection could verify that the line has only a single instruction before firing up a result?
