### ISSUE TITLE
If RD is disabled then enabled (via Addin Manager) Word will Crash

### ISSUE THREAD

**Issue by Stevefb** [rubberduck-vba/Rubberduck#1883]
So far this has happened 3/3 times...

**Comment by retailcoder** [comment]
This is a known issue; I think fixing teardown / shutdown issues will also fix hot-unloading/reloading the add-in.

**Comment by lkavicky** [comment]
I have the same issue in Access.

**Comment by retailcoder** [comment]
Ah, I forgot to include that in the "known issues" of 2.0.10 - the add-in is much more stable now, and normal shutdown appears to no longer consistently crash the host. However re-loading after unloading from the addins manager is still going to wreck the IDE and its host.

**Comment by retailcoder** [comment]
duplicate of #1876
