### ISSUE TITLE
Parse error on VBA Name statement

### ISSUE THREAD

**Issue by mwolfe02** [rubberduck-vba/Rubberduck#1886]
I'm getting Parse errors on [`Name` statements](https://msdn.microsoft.com/en-us/library/office/gg264639.aspx).  Here's the error:

> extraneous input ' ' expecting {ABS, ANY, ARRAY, ..., LOAD, RESUME_NEXT}

<strike>One additional peculiarity is that the cursor insertion point is exactly one line below the end of the _oldpathname_ variable:

    Name Src As Dest
    '       |    <-- parser-identified location of error

</strike>

**Update:** The cursor insertion point is inconsistent and likely has nothing to do with the `Name` statement.  It likely has to do with what it considers a line versus what the IDE is considering a line.

**Comment by Hosch250** [comment]
Already fixed since the last release.  See #1824

**Comment by mwolfe02** [comment]
Sorry, @Hosch250.  I should have searched before posting.

**Comment by Hosch250** [comment]
No problem.
