### ISSUE TITLE
Code Inspection Ignore is Ignored by RD (MS Word)

### ISSUE THREAD

**Issue by Stevefb** [rubberduck-vba/Rubberduck#1898]
A ribbon callback has untyped returnedVal which RD won't ignore, neither of the following work:

``` vb
'@Ignore VariableTypeNotDeclared, VariableTypeNotDeclared, VariableTypeNotDeclared
Sub getItemSupertip(ByVal Control As IRibbonControl, ByVal index As Long, ByRef returnedVal)
```

``` vb
'@Ignore VariableTypeNotDeclared
Sub getItemSupertip(ByVal Control As IRibbonControl, ByVal index As Long, ByRef returnedVal)
```

Might be nice if RD supported something like:

``` vb
'@Ignore VariableTypeNotDeclared(returnedVal)
Sub getItemSupertip(ByVal Control As IRibbonControl, ByVal index As Long, ByRef returnedVal)
```

**Comment by Stevefb** [comment]
BTW: Build 2.0.2.31306 (the one @Hosch250  provided me for testing previously)

**Comment by retailcoder** [comment]
Interesting.. not sure how annotations apply to parameters, I'd think the procedure's `Declaration` "eats" all the annotations here.

**Comment by Stevefb** [comment]
well then, we need a hungry duck to eat them first

**Comment by retailcoder** [comment]
Nah, the inspection can just look at the parent procedure's attributes. The side-effect of that is that if you ignore a parameter inspection result, you then ignore that inspection for all parameters of that procedure... unless yeah, we parameterize the annotation.

**Comment by Hosch250** [comment]
The real fix would be to specify the declaration type and identifier and have this annotation be valid in a certain scope for a certain declaration type.

**Comment by Stevefb** [comment]
Gah, this also gets ignored (Ignore here was a RD Quick Fix).  This Inspection result is "Replace function 'Format' with existing typed function". The quick fix uses the same ignore, which RD also ignores:
```vb
    With Selection.Find
        .ClearFormatting
        .Text = FindChar
        .Replacement.Text = vbNullString
        .Forward = True
        .Wrap = wdFindContinue
'@Ignore UntypedFunctionUsage
        .Format = False
        .MatchCase = False
        .MatchWholeWord = False
        .MatchWildcards = False
        .MatchSoundsLike = False
        .MatchAllWordForms = False

        Do While .Execute    'Keep going until nothing found
            If Dialogs(wdDialogInsertSymbol).Font = FindFont Then
                strFound = True
                Select Case True
```

**Comment by Hosch250** [comment]
Ugh, that is the Untyped Function result thing again.

**Comment by Hosch250** [comment]
The parameter ignores are fixed now.

**Comment by retailcoder** [comment]
`Selection.Find.Format` also resolves correctly. Fixed.
