### ISSUE TITLE
Rubberduck should optionally handle CommandBarControl events

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#1899]
And call the OnAction argument accordingly, using HostApplication.Run

That would make it easy for users to add to VBE's CommandBars, and have the OnAction property actually execute.

See http://www.cpearson.com/excel/VbeMenus.aspx

**Comment by ThunderFrame** [comment]
Bonus feature would allow the assignment of the OnAction property of an existing control using the UI.

**Comment by retailcoder** [comment]
I can't shake the feeling that this is beyond our scope, even as an API feature.
