### ISSUE TITLE
Command line calling for unit testing test case to achieve continuous integration

### ISSUE THREAD

**Issue by harshitspiky** [rubberduck-vba/Rubberduck#1903]
Hi Team,

Can you please let me know, is there a way that i can call my unit testing test cases through command line (Externally from command prompt) to achieve the automation (For Continuous Integration) ? If not available can you please add the feature or can you give me an idea how to achieve it.

Thank you for creating such a wonderful plugin.

Regards,
Harshit Shah.

**Comment by ThunderFrame** [comment]
Rubberduck doesn't support unit-testing from the command-line.

@grleachman does have a command-line compatible project on [BitBucket](https://bitbucket.org/gleachman/vba-unittest-framework)

**Comment by harshitspiky** [comment]
Thank you @ThunderFrame  for the reply. I am using "Rubberduck" with Ms-Access application and want to achieve the automated test case execution from command line or PowerShell (Using BAS file).

**Comment by retailcoder** [comment]
The VBE doesn't load addins on command-line, the registry value `CommandLineSafe` has no effect whatsoever as far as I understand, for VBA IDE addins. Therefore, no command can be sent to Rubberduck to instruct it to run the tests.

But, the test methods themselves can be executed, and the assert calls will be made... but the logic that evaluates assert results to determine whether a test passed or not, won't.

I cannot think of any way to make this work ATM, if anyone does, feel free to share your ideas.

**Comment by ThunderFrame** [comment]
Maybe, if Rubberduck can expose a TLB method, then Tests could be triggered *from* VBA? Any Unit Test Manager code would be responsible for running the VBA trigger. That might be an explicit call (by the test runner), using Application.Run, or it might be a combination of `auto_open` and `OpenArgs`, or `auto_open` and a check for the presence of an environment variable/registry key/file-existence-flag.

```vb
Sub auto_open()
  If CheckIfUnderTestAutomation Then
    ExecuteTests
  End If
End Sub

Sub ExecuteTests()
  'Define a filepath for Test Results output
  Const TEST_RESULTS As String = "C:\TestResults.xml"

  Dim RD as Rubberduck.CommandAndControl
  Set RD =New Rubberduck.CommandAndControl

  RD.RunAllTests 200, TEST_RESULTS 'Where 200 = delay in ms (to allow VBA to exit Run mode), before Rubberduck runs tests

End Sub
```
Or maybe, if we get the `IDispatch` approach working, we pass the instance of the Test class to Rubberduck? Something like:
```vb
Option Explicit
Private oUnitTests As IUnitTests

Sub CallbacksTest()

  Dim RDUT As RubberduckUnitTester
  Set RDUT = New RubberduckUnitTester
  
  Set oUnitTests = New UnitTests

  'Add the tests
  RDUT.AddTest "Foo"
  RDUT.AddTest "Bar"
  
  'Register the event handler
  RDUT.OnExecuteMethod = oUnitTests
  RDUT.ExecuteAsync

End Sub
```
Where the UnitTests class looks like:
```vb
Option Explicit
Implements IUnitTests

Private Function IUnitTests_ExecuteTest(MethodName As String) As Variant
  VBA.CallByName Me, MethodName, VbMethod
End Function

Public Sub Foo()
  Debug.Print "Foo"
End Sub

Public Sub Bar()
  Debug.Print "Bar"
End Sub
```

**Comment by retailcoder** [comment]
@ThunderFrame this would require reworking the guts of the whole unit testing feature. Not ruling it out at all, but not going to happen in 2.0 either..
