### ISSUE TITLE
Rubberduk.Reflection

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#191]
Expose `INode` classes to COM, and implement an API that lets VBA code iterate these high-level, wrapped-up parse trees.

**Comment by ckuhn203** [comment]
Tips for doing this:

- The `System.ComponentModel.Description` attribute works like the VBA Description attribute. It allows you to expose documentation to the object browser.   
- Declare `[DispId(int)]` attributes on all of the `INode` methods. This allows us to re-order and add new methods to `INode` without breaking COM client code.

**Comment by retailcoder** [comment]
Where's the [Like] button!!!!

**Comment by retailcoder** [comment]
`INode` is gone, it's the `Declarations` API that needs to be exposed. Deferred to future version.
