### ISSUE TITLE
Crash on cloning repo

### ISSUE THREAD

**Issue by AndrewM-** [rubberduck-vba/Rubberduck#1910]
Not sure if this is a duplicate of 1814.

Ms-access 2010 crashes when I click the OK button after entering my username and password, when cloning a remote repo.  The dialog as it is set up before the crash is shown.  Note that my projects are hosted by Bitbucket.  RD build 2.0.2.41756.  I was following the source control instructions from the Wiki.
![crashonclickingpasswordok](https://cloud.githubusercontent.com/assets/5060805/16323952/846469d0-39f2-11e6-8b90-6825849c1289.jpg)

**Comment by Hosch250** [comment]
This might be because I only checked it with GitHub, or it might be because of #1814.  Please check again after I do another release tomorrow night.  If you still get it, I'll test it with BitBucket as well and see if it is because of that.

**Comment by Hosch250** [comment]
I just verified that cloning a repo from BitBucket works--if it isn't projected.  The catch comes when you have a protected repository.  Rubberduck (currently) expects a repository to already exist when cloning, so it crashes with a null-reference exception.
