### ISSUE TITLE
Crash when trying to create a new repository (Access/Excel 2010)

### ISSUE THREAD

**Issue by lkavicky** [rubberduck-vba/Rubberduck#1924]
I am having the same problem with all pre-releases of RD2, I am totally unable to use the source control: both Access and Excel 2010 crash when I try to create a new repository.

Here is what I do (in RD 2.0.3b):
1. Configured name and email in source control settings
2. Create a new DB / Excel file
3. Add a module
4. Save
5. Open RubberDuck > Source Control > Init New Repo from this Project
6. Select any folder and click OK -> Crash

**Log file:**
 [rubberduck.zip](https://github.com/rubberduck-vba/Rubberduck/files/336957/rubberduck.zip)

**Call stack:**
![callstack](https://cloud.githubusercontent.com/assets/1942695/16415944/29df68c4-3d40-11e6-945b-ce722f296208.png)

**Info from Windows Event Viewer:**
Faulting application name: MSACCESS.EXE, version: 14.0.7162.5001, time stamp: 0x5626f514
Faulting module name: KERNELBASE.dll, version: 6.1.7601.23418, time stamp: 0x5708a7e4
Exception code: 0xe0434352
Fault offset: 0x0000c54f
Faulting process id: 0x1f80
Faulting application start time: 0x01d1d148e7ddc6e0
Faulting application path: C:\Program Files (x86)\Microsoft Office\Office14\MSACCESS.EXE
Faulting module path: C:\Windows\syswow64\KERNELBASE.dll
Report Id: 323cca91-3d3c-11e6-865b-cc52af782fea

**Comment by Vogel612** [comment]
Nothing in the log indicates anything wrong in Rubberduck (apart from a few Resolver problems), since the log ends when you create the repository. The Call Stack unfortunately does not indicate any involvement of Rubberduck :neutral_face:

**Comment by Hosch250** [comment]
Please check that you have the `C:\Users\{user}\AppData\Roaming\Rubberduck` folder.

**Comment by lkavicky** [comment]
Yes, the folder is there.

**Comment by Hosch250** [comment]
Please make sure your log level is set to Trace, delete the log file, reproduce the crash, and upload the log file's content here.

**Comment by Hosch250** [comment]
NVM, I just noticed the log in the issue.

**Comment by Hosch250** [comment]
Well, I can't reproduce this, but I'll make it log any exceptions for the next release.

**Comment by lkavicky** [comment]
OK, I will update the issue if there are new log entries in the next release

**Comment by derlachendebaum** [comment]
I can confirm this problem - Excel 2013, Windows 10 - when opening existing repo or creating new one, Excel crashes. In the log only one line with UI.SourceControl:
TRACE;Rubberduck.UI.SourceControl.SourceControlViewViewModel;Opening existing repo;
There are some log entries for rubberduck afterwards (DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;ParserState evaluates to 'Pending' (thread 7) and the like - so rubberduck seems to continue to work, but Excel tries to restore and exits.
Excel crash report also mentions kernelbase.dll. 
If you need further info, please leave a message. I will also give update after next release.

**Comment by derlachendebaum** [comment]
Two more things: I remember also having the same issue when I once tried v2.0.2a, and the rubberduck appdata folder is also present (also made clean install, deleted the folder before).

**Comment by lkavicky** [comment]
Looks like RC1 solved the issue for me!

**Comment by derlachendebaum** [comment]
I still have a problem, but I could trace it more down thanks to your adaptions in RC1: Excel doesn't crash anymore, but Rubberduck prints a message that an error occured - find the log [attached](https://github.com/rubberduck-vba/Rubberduck/files/346409/rubberduck.txt). It seems to be connected with a userform, as it throws an exception "file not found" as the only line in frmview.log (German version): 

> Zeile 8: Eigenschaft OleObjectBlob in frmView enthält einen ungültigen Dateiverweis

In the resulting git repository the file frmView.frx (value of parameter "OleObjectBlob" in frmView.frm) is missing. 
As a result, the userform and all the modules following in alphabetical order get deleted from the VBA project - which is little bit dangerous ;-).

**Comment by Hosch250** [comment]
@derlachendebaum That log is awesome.  I'll look into this tomorrow (today is a holiday).

**Comment by derlachendebaum** [comment]
@Hosch250 Thanks for the great work and a happy holiday today!
