### ISSUE TITLE
Statically accessed sheet can be referred to by its CodeName (Excel-specific)

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#1926]
Consider:

```
Dim someSheet As Worksheet
Set someSheet = ThisWorkbook.Worksheets("SheetName")
someSheet.Range("A1") = "foobar"
```

When the `Sheets` or `Worksheets` collection is accessed using a string literal that matches the known name of a worksheet in `ThisWorkbook` (i.e. the same project), Rubberduck should suggest using the globally-scoped object reference that's already referring to that sheet object, discard the extraneous local variable, and replace its usages by references to the existing global object:

```
 SheetName.Range("A1") = "foobar"
```

> **Statically accessed sheet can be referred to by its CodeName**
> 
> Excel already defines a globally scoped object variable with this reference. Consider using the sheet's CodeName in code instead of creating a copy of an existing object.

**Comment by daFreeMan** [comment]
I like this one because I always forget about it.
