### ISSUE TITLE
Replace VS icons

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#1939]
After reviewing the EULA for the MS Visual Studio icon sets, it appears Rubberduck is misusing these icons, and they need to be removed from the project.

This is going to be tedious and extraordinarily annoying, but the last thing we want is Microsoft taking us down over a bunch of icons.

This is critical and needs to be fixed ASAP.

 - Icons we're using in COM command bars and VBE menus must be .bmp images with a mask version, for proper transparency.
 - Icons we're using in WPF UI elements can be .png images with an alpha channel.

**Comment by AndrewM-** [comment]
Question - what does SharpDevelop do?  They are a direct competitor to a ms product and they seem to use very similar if not the same icons as visual studio.

**Comment by comintern** [comment]
@AndrewM- They use the same icon set as RD for the non-MS icons, and custom ones for MS.  I've already bashed together a set using the #D icons for a couple things.

**Comment by Hosch250** [comment]
Is this complete now?

**Comment by comintern** [comment]
@Hosch250 Yep, assuming I didn't miss anything.
