### ISSUE TITLE
AssignedByValParameter inspection needs another quick-fix

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#1942]
Currently, the only quick-fix we offer when a `ByVal` parameter is assigned, is to pass the parameter `ByRef`. It being the only fix available, it's also the default fix for that inspection, and applying it changes the semantics of the code and can introduce bugs.

The default fix should be **Introduce a local variable**, that turns this:

```
Public Sub DoSomething(ByVal foo As Integer)
    'some code
    foo = 42
End Sub
```

Into this:

```
Public Sub DoSomething(ByVal foo As Integer)
    Dim bar As Integer
    bar = foo
    'some code
    bar = 42
End Sub
```

The fix should prompt for a name for the local variable to introduce, declare it at the top and immediately assign it with the parameter's value, and then replace all further references to the parameter with the local variable.

**Comment by BZngr** [comment]
Rather than prompting the user for a name, would a Quick-fix solution to the above example that looks something like below be an acceptable first-pass solution?

_Public Sub DoSomething(ByVal foo As Integer)
Dim localFoo as Integer
localFoo = foo
           'some code
           localFoo = 42
End Sub_

**Comment by comintern** [comment]
I'd personally prompt for a name, but prefill the selection with `localFoo`.
