### ISSUE TITLE
Refreshing parser state after closing the last project doesn't crash, but...

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#1948]
![refresh-after-closing](https://cloud.githubusercontent.com/assets/5751684/16512961/887ac9a6-3f2e-11e6-91e0-3d3e7cc64290.gif)

...but you actually need to kill the process to be able to quit (the longer periods without anything happening is me holding the ESC key down)

**Comment by retailcoder** [comment]
The log contains pages and pages of this:

> 2016-07-01 01:52:23.4934;FATAL;Rubberduck.UI.CodeExplorer.Commands.CodeExplorer_PrintCommand; System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at Microsoft.Vbe.Interop._VBComponent.get_CodeModule()
   at Rubberduck.UI.CodeExplorer.Commands.CodeExplorer_PrintCommand.CanExecuteImpl(Object parameter) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\CodeExplorer\Commands\CodeExplorer_PrintCommand.cs:line 25
   at Rubberduck.UI.Command.CommandBase.CanExecute(Object parameter) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\Command\CommandBase.cs:line 32;

**Comment by retailcoder** [comment]
Part of the problem seems to be that the CE (parser state?) doesn't refresh / clear when a project is closed, which leaves stale data in the dockable toolwindows; in this case a `COMException` is thrown when the stale/ghost `Component` is accessed in `CanExecuteImpl`:

    return node.Declaration.QualifiedName.QualifiedModuleName.Component.CodeModule.CountOfLines != 0;

**Comment by Hosch250** [comment]
This is the prompt to restart after an exception.  If I need to, I'll just swallow that exception in the Print command, but I'd rather figure out why it is happening.  (At least we have the logs!)

**Comment by Hosch250** [comment]
The problem here is the ghost project in Excel.  The VBE doesn't fire the project removed event, so Rubberduck (and even the Project Explorer, for that matter) doesn't even know the project was closed.  However, when Rubberduck tries to access the COM object, it throws.

**Comment by daFreeMan** [comment]
I just ran into this this morning in a perfectly functional XLSM. Opened Excel by double clicking the XLSM file. Running 2.0.4
[rubberduck.log.txt](https://github.com/rubberduck-vba/Rubberduck/files/357229/rubberduck.log.txt)

**Comment by Hosch250** [comment]
@daFreeMan Umm hmm, I thought I fixed that in the last release.
