### ISSUE TITLE
RD 2.0.3 Code Explorer does not load add-ins unless opening an xlsm file first

### ISSUE THREAD

**Issue by byronwall** [rubberduck-vba/Rubberduck#1950]
RD does not correctly load all of the projects in the given Excel instance if starting from a "blank" workbook or a normal xlsx file.  The projects are correctly resolved if Excel is opened from an `xlsm` file first.

Once Excel/RD are open without the projects resolved, it does not make a difference if an `xlsm` file is then opened.  There seems to be no way to get RD to resolve the projects once they are skipped.

I do not get an error message or any other indication of failure when this happens.

*Screenshots taken immediately after Excel and the VBE are open.*

Opening Excel with an `xlsm` file resolves the add-ins

![excel_2016-07-01_13-12-01](https://cloud.githubusercontent.com/assets/495404/16532247/0e8a1fb0-3f8e-11e6-8185-750ff4ea5d52.png)

Opening Excel with an `xlsx` or blank workbook does not resolve them.

![excel_2016-07-01_13-12-30](https://cloud.githubusercontent.com/assets/495404/16532253/162dc7da-3f8e-11e6-90b0-ce51808ce760.png)

Opening an xlsm file after starting from a blank state.

![excel_2016-07-01_13-11-23](https://cloud.githubusercontent.com/assets/495404/16532255/19245bd4-3f8e-11e6-92cf-6b6b539731ef.png)

**Comment by byronwall** [comment]
If I save a blank workbook as an `xlsm` file (with no user code or anything on the VBA side) RD does **not** correctly resolve the projects.  If I take that same file and add an empty module (with just the `Option Explicit` at the top) RD correctly resolves all the projects when reopening that file.

That is, it is not just saving as `xlsm` that matters but actually having a module in that file.

Note that RD resolves the projects before I hit "Enable Content" in the yellow warning bar.

**Comment by Hosch250** [comment]
This is a parser bug. Thanks for the notification.

**Comment by byronwall** [comment]
@Hosch250 

With the new Release Candidate, the projects now resolve in the Code Explorer.  I can use the Code Explorer to navigate the code, but it looks like the projects have not been fully parsed.  The Code Explorer shows a still spinning wait indicator and it says "Pending" in the toolbar.  I am not getting any exceptions however so I can't tell where it's stuck.  On other startups, it will show "Resolver Error" instead of the pending.

If you want a fresh issue for this, I can create one.

**Comment by Hosch250** [comment]
Why don't you hang on and check it with the release in about 7 hours, then create an issue?

**Comment by byronwall** [comment]
Sounds good.  Thanks for the quick response.

**Comment by byronwall** [comment]
Looks like RC2 has resolved these issue.  Thanks for all the work.
