### ISSUE TITLE
RC High CPU usage when idle after reaching Ready state

### ISSUE THREAD

**Issue by BobTB** [rubberduck-vba/Rubberduck#1953]
The release candidate does a good job of finishing through to the Ready status, but it keeps consuming approx. 30% CPU continuously even if nothing is touched or running.Some Win32Exceptions in logs after it reaches Ready (attached). 

![image](https://cloud.githubusercontent.com/assets/15887688/16539653/08a8e98e-404a-11e6-8897-ef217b2165c0.png)

![image](https://cloud.githubusercontent.com/assets/15887688/16539753/83483b8e-404c-11e6-8150-5943096c8a58.png)

[log.txt](https://github.com/rubberduck-vba/Rubberduck/files/344501/log.txt)

**Comment by Hosch250** [comment]
I'm guessing this is the point after Rubberduck is "technically" ready, but is A) running all the CanExecute's and disabling relevant commands, B) loading inspection results into the UI, and doing other things that have to way until immediately after a parse finishes.

**Comment by retailcoder** [comment]
I can see the `GroupingGrid` controls being a problem: their data is loaded at least twice - once for the default/current grouping view, and another time for the other grouping view, which is loaded, but invisible.

**Comment by Vogel612** [comment]
Is this still an issue for 2.0.8?

**Comment by Vogel612** [comment]
Haven't seen any issues like this in recent memory against my 20 module strong testproject... Issue also was last active half a year ago ...
