### ISSUE TITLE
Code Inspection False Positive for variable is not used

### ISSUE THREAD

**Issue by Stevefb** [rubberduck-vba/Rubberduck#1960]
Code inspection tells me that: variable 'newDoc' is not used (button on ribbon creates a new document).
```vb
Public Sub CalledByRibbonUI(ByVal Control As IRibbonControl)
Dim newDoc As Document
Set newDoc = Application.Documents.Add(Template:=ThisDocument.FullName)
End Sub
```
RD: 2.0.4.32649, MS Word 2010 32 bit

**Comment by Stevefb** [comment]
Doh, ok... its assigned but not used... sorry just noticed that

**Comment by retailcoder** [comment]
If you don't need to do anything with the returned reference, you could call `Documents.Add` as a procedure here;  display a message if `newDoc`  is ever `Nothing`.

**Comment by Stevefb** [comment]
@retailcoder thanks for you comments I ended up just using Documents.Add 

I've got to say RD has come a long way in a short time, well ok, in the short time that I've been poking at it... The issue raised was my error, but that said it was buried among several false positives and stood out as an easy to describe scenario.... I have a collection of false positives (which I've taken more care to verify) and will attempt to reproduce them with minimal code.  

All that said, RD is uncovering several issues with the project I'm working on and the false positives are far outweighed by the useful suggestions :-)

Cheers,

**Comment by retailcoder** [comment]
1. Make it work
2. Make it right
3. Make it fast

We are somewhere between 1 and 2 at this point; soon we'll be restructuring things to scale parsing and identifier reference resolution to perform just as well in small and large projects.
