### ISSUE TITLE
RD needs an inspection for variables that override functions

### ISSUE THREAD

**Issue by comintern** [rubberduck-vba/Rubberduck#1962]
Poked around at this after I saw somebody do it in an SO post.  VBA allows `Str` (and presumably other internal function names) to be used as variables, and they function "normally" unless that function is used in the same scope.  In that case, they cause a bizarre and uninformative compile error when the VBE chokes on parsing it:

```VB
Private Sub ApparenltyLegit()
    Dim InputBox As Long
    InputBox = 42
    Debug.Print InputBox
End Sub

Private Sub WtfError()
    Dim InputBox As String
    InputBox = InputBox("Type something here.")     '<-- compile error "Expected array"
    Debug.Print InputBox
End Sub
```
It would probably be better to do this as a separate inspection from the `UseMeaningfulNameInspection` because the severity should likely be higher.

**Comment by ThunderFrame** [comment]
linking #1002

**Comment by retailcoder** [comment]
@comintern you've found my secret stash of bad code... SO is a gold mine of code inspection ideas!

Good eye @ThunderFrame, that's indeed a duplicate issue.

The *use meaningful name* inspection pops a result only out of the lack of a vowel in the identifier's name, and that inspection only looks at user code. I completely agree, we need a separate inspection for this, *at least* at `Warning` default severity level.

The clashing names would confuse our resolver just like they confuse VBA's compiler though, so I'm not sure a refactor/rename quick-fix would work... or even a quick-fix that would properly qualify the built-in function. Still, warning about it is the least we can do.
