### ISSUE TITLE
False positive for self assigned variable inspection when variable is the same name as the type

### ISSUE THREAD

**Issue by comintern** [rubberduck-vba/Rubberduck#1963]
Discovered this while I was messing around with #1962.  VBA allows a variable name to be the same as the name of its type:

```VB
Option Explicit

Private Type Foo
    Bar As Long
End Type

Private Sub Example()
    Dim Foo As Foo          '<-- RD says "Object reference 'Foo' is self-assigned."
    Foo.Bar = 42
    Debug.Print Foo.Bar
End Sub
```

This appears to parse and resolve correctly - I get `Foo (variable: Foo)` when I put the cursor on the variable to the left of `As`, and `Foo (user-defined type)` when I put the cursor on the type name after the `As`, but it triggers the inspection.

**Comment by retailcoder** [comment]
Weird.. the "self-assigned" flag should only be set when the "as type clause" contains the `New` keyword.

**Comment by retailcoder** [comment]
Oh I know why: UDT variables are *also* set to "self-assigned", because they're not assigned directly and not setting that flag would trip a false "variable is never assigned" positive.

The inspection needs to explicitly exclude UDT's.
