### ISSUE TITLE
"Unit-Test-Only" mode

### ISSUE THREAD

**Issue by mwolfe02** [rubberduck-vba/Rubberduck#1966]
I love the idea of the enhanced Code Explorer and the other associated goodies, but for large projects it just takes too long and is too processor intensive to parse (at least for my tastes).  While I realize that parsing the code opens up a whole world of new possibilities for refactoring, code inspections, etc., it is making Rubberduck unusable for me for the one thing that really had me excited: first-class unit-testing support in VBA.

I think you should consider adding a setting to disable (automatic?) full code parsing, so that the unit testing functionality can be used without the extra processing and resulting UI lag that comes with parsing the entire code base.

**Comment by Hosch250** [comment]
Interestingly enough, the Code Explorer works at the same time the Unit Test Explorer does--it is the refactorings and inspections that won't work at that point.

**Comment by mwolfe02** [comment]
So the Test Explorer relies on the syntax parser for its content?  Is that correct?

**Comment by Hosch250** [comment]
Yes, we use the syntax parser to determine what is a test module/test method.  We are planning on going back to our old way of just parsing the module text soon.

**Comment by mwolfe02** [comment]
OK.  The syntax parser is a real tour de force, but it's just a bit too heavy for my personal workflow.  I maintain several MS Access projects that each have around 20-40K lines of code.  It just takes too long to parse everything when I'm in and out of multiple projects throughout the day.  I imagine the code inspections and refactoring tools would be really valuable for refactoring and I'd have no problem waiting for the parser to run if I wanted to take advantage of that functionality.

This is getting off on a tangent here, but I've been thinking one way to improve the performance would be to cache the parser results between sessions.  Without knowing any of the internals (so this may not work for any number of structural reasons), I imagined the following approach could speed things up significantly.  It assumes that .NET has something analogous to Python's pickle module for serializing/de-serializing objects to/from byte streams that can be saved and loaded from text files.

For each module
- Hash the contents 
- Look for a file named `C:\ProgramData\RubberDuck\pickles\{ProjectName}\{ModuleName}\{Hash}`
- If file exists, de-serialize the contents into an in-memory object
- If file does not exist:
  - Parse the module
  - Delete all files in `pickles\{ProjectName}\{ModuleName}\`
  - Serialize the contents into a file named `pickles\{ProjectName}\{ModuleName}\{Hash}`

Since most modules are not changing, they could simply be saved and re-loaded from disk.  I imagine this would be something users would opt in to (or be able to opt out of).

You would also need to do something to deal with updates to the parser version.  Clear out the `\pickles\` folder as part of the installer, or maybe add a version folder, such as: `pickles\v2.1.0\{ProjectName}`.

**Comment by Hosch250** [comment]
That's an interesting idea.  We are already caching the results between parses when the project remains open, so reparsing shouldn't be nearly as expensive as the first one, but it might be possible to somehow save the results to disk.  I wonder what it would take to serialize the data and save it, and whether people would appreciate the massive amounts of data we'd be storing.

**Comment by retailcoder** [comment]
@mwolfe02 as @Hosch250 said, we're already caching and reusing parse trees of unchanged modules; the performance problem stems from needing to reparse an entire module when only one procedure was modified. Add to that, that "parsing" is a two-pass process where the first pass exports the module to a temp file to discover `VB_Attribute` module and member attributes, and then another pass using the content as it appears in the IDE, to correctly locate/position all tokens.

We need to work on a way to parse any arbitrary procedure, and somehow offset the position of already-parsed and known to be unchanged tokens as we go; then we need to do the same for identifier references. Once we're able to single out a procedure and do that, performance improvement should be dramatic.

**Comment by Hosch250** [comment]
Umm, after we generate the tree, we actually walk it 4 times, with the most expensive pass being the declarations pass.

**Comment by mwolfe02** [comment]
Looks like .NET supports [serialization](https://msdn.microsoft.com/en-us/library/7ay27kt9(v=vs.110).aspx) of objects.  It looks a bit more involved than Python's approach of just saying, "Here, serialize this object instance."  That said, a basic approach in .NET might or might not be relatively simple to implement.

And I agree with your concerns about storing massive amounts of data.  That's why I thought it might need to be an opt-in feature.  But I'd opt in ;).

**Comment by mwolfe02** [comment]
@retailcoder Actually, the performance issue that I'm seeing is at startup, when I haven't started making any changes yet.

**Comment by retailcoder** [comment]
@mwolfe02 the initial parse processes *everything* that's why ;-)

**Comment by retailcoder** [comment]
@Hosch250 perhaps we could make an opt-out setting (or opt-in?):

 - [x] Parse all opened projects at start-up

Together with unit testing working off string module contents obtained via the VBIDE API, I think that would greatly help the usability of a stable 2.0 release.

**Comment by Hosch250** [comment]
Otherwise, we just parse the active project?  I don't think that will make too much of a different, and it would be outright confusing as well, if the user switched projects.

**Comment by retailcoder** [comment]
@Hosch250 so there's an Excel add-in loaded, and the active project is a small VBA project that references the add-in. Parsing just the active project would make references to things declared in the add-in fail to resolve... IMO either we parse everything in sight, or nothing at all.

**Comment by mwolfe02** [comment]
> the initial parse processes everything that's why ;-)

Yes, obviously.  I was referring to your earlier comment about the performance issue being tied to a single change forcing a re-parsing of an entire module.  I just wanted to clarify that the main issue I was having was at startup.  But your point about a single change forcing a re-parse of an entire module was well-taken.  Working around _that_ actually sounds more challenging than caching parse results between sessions.

Also, I agree that the parsing should be an all or nothing option.  Actually, I think we're all in agreement on that point.

**Comment by ThunderFrame** [comment]
I understand @mwolfe02's frustration. The performance of the *nth* parse is important, but if you're constantly in and out of large projects, you'll always have to endure the *first* parse.
Serialization might help, but any persisted cache would probably need to withstand:

 - A project being opened on a different PC (that maybe has 64-bit instead of 32-bit, where type libraries and compiler directives might come into play)
 - A project being opened on a PC with updated type libraries (for example an upgrade from Excel 2013 to 2016, or a MS patch for a referenced library).

IIRC, parsing the references is actually quite quick, so maybe the references should *not* be serialized, and instead be read at startup?

**Comment by retailcoder** [comment]
@ThunderFrame but we have no way of being 100% sure that what we're going to deserialize is going to match **exactly** with the code in the IDE. If **one single line** is offset, a refactor/rename can have disastrous consequences. Want to risk it?

**Comment by ThunderFrame** [comment]
Isn't that the job of the hash? If **one single line** is offset, the hash is bad, and the cache is ignored.

**Comment by Vogel612** [comment]
Aside from the hash function that *should* work just fine (important: choose a good hashing algo, something better than MD5), we're trading one slow thing for another (not quite as) slow thing. I/O + processing (aka. the parsing) is traded for full-on I/O. 

At some point it's cheaper to not cache (and consume possibly big chunks of memory) and instead actually reparse the thing. Also I'm not sure Rubberduck can afford caching **any and all** projects automatically. Projects change over time and we're never cleaning up after old hashes, which will slowly fill up the hard drive ... We could work around that with a regular cleanup or a timed cache that will remove files older than X days.

This will only be useful when modules start having more lines, so it should be intelligent-ish (and possibly optional)

**Comment by Hosch250** [comment]
I just fixed a very slow section when resolving declarations--I tested it on a project with ~80 modules, and the tests were usable in about 13 seconds.  Is that fast enough for you?

**Comment by mwolfe02** [comment]
@Hosch250 I just parsed a project with 78 modules + 174 Access Forms + 199 Access Reports with a total of 37,255 lines of code.  The total time was five and a half minutes.  Most of that time seemed to be spent in "Resolving declarations," so it sounds like your optimization would make a big difference.

Certainly, the ideal scenario would be to get the parsing optimized to the point where it's not really noticeable.  And there's always the option to not load Rubberduck at startup; I could just load it as an add-in when needed.

**Comment by retailcoder** [comment]
@mwolfe02 wow, a few versions back parsing that project would have taken a week!

**Comment by mwolfe02** [comment]
@Vogel612 I addressed the cleanup in my original algorithm.  I suggested that anytime the hash for a given project.module changes, Rubberduck would clear out any previous serialized files for that project.module.  My thinking is that it would be extremely unlikely that a user would ever change a module and then change it back *exactly* to the way it was.  So there would be very little benefit to keeping older ones around.  The idea is that if 95% of a project stays the same from session to session, there's no benefit in constantly reparsing unchanged modules.

The point about disk I/O being a bottleneck itself is a good one.  It comes down to a variety of factors: how fast is the disk (solid state vs. platters), how fast is the parsing implementation, how large are the serialized files, and how efficient are the algorithms to hash, serialize, and de-serialize.

**Comment by mwolfe02** [comment]
@retailcoder Actually, the release after the `Name As` parser fix is the first one that was able to get all the way through it without choking somewhere.  That alone was an impressive feat.

I want to make sure my suggestions are not taken as implicit criticisms.  What you guys have done with this project in such a relatively short time is truly remarkable.  Keep up the great work!

**Comment by Vogel612** [comment]
@mwolfe02 that's rather difficult, because you will need to check each and every hash (if you store them under a hash key, which is exactly what happens here) because you cannot obtain the hash for an old state that easily.   
This means slowdown. and not a small one at that. Especially since ModuleNames are not unique, Not even the ProjectName - ModuleName combination can be considered unique, so the cleanup problem still remains. Maybe I have exaggerated it a bit, but it's still something that will need quite a lot of thought

**Comment by mwolfe02** [comment]
@Vogel612 The hash would not be for the object state, but rather for the text contents of the module.  As for the ProjectName - ModuleName not being unique, I think that's OK.  For real-world purposes it should be *mostly unique*, which I think is good enough.  We're not looking for perfect efficiency.  The worst case scenario would be that Rubberduck has to re-parse a module because the ProjectName - ModuleName is not unique and so the hashed contents don't match.

**Comment by mwolfe02** [comment]
I did a quick test in MS Access to see how long it would take to hash the contents of the modules.  The test took longer than it would in C# because the interface kept updating as I was closing and opening the modules to get at their text.  But this should represent a worst-case scenario in terms of how long it takes to hash the contents.

The bottom line is that it took about 4 seconds to perform SHA1 hashes on 78 modules, totaling over 30K lines of code.

```
Private Declare Function GetTickCount Lib "kernel32" () As Long

Sub HashAllModules()
    Dim s As Long, LineCount As Long
    s = GetTickCount

    Dim enc As Object
    Set enc = CreateObject("System.Security.Cryptography.SHA1CryptoServiceProvider")

    Dim Obj As AccessObject
    For Each Obj In CurrentProject.AllModules
        Dim objLoaded As Boolean
        objLoaded = Obj.IsLoaded

        If Not objLoaded Then DoCmd.OpenModule Obj.Name
        Dim mdl As Module
        Set mdl = Application.Modules(Obj.Name)
        LineCount = LineCount + mdl.CountOfLines

        'Convert the module contents to a byte array...
        Dim Content() As Byte
        Content = mdl.Lines(1, mdl.CountOfLines)

        '...and hash it
        Dim HashedBytes    '() As Byte
        HashedBytes = enc.ComputeHash_2((Content))

        'Convert the hashed byte array to a hex string
        Dim Pos As Integer, HexedHash As String
        HexedHash = vbNullString
        For Pos = 1 To LenB((HashedBytes))
            HexedHash = HexedHash & LCase(Right("0" & Hex(AscB(MidB(HashedBytes, Pos, 1))), 2))
        Next
        Debug.Print HexedHash, mdl.Name    'Returns a 40 byte/character hex string

        Set mdl = Nothing
        If Not objLoaded Then DoCmd.Close acModule, Obj.Name

    Next Obj
    Set enc = Nothing
    Debug.Print "Done...processed "; CurrentProject.AllModules.Count; "modules with"; _
                LineCount; "lines of code in"; GetTickCount - s; "ms"
End Sub
```
Running this on my currently open project, I got the following output:

```
Done...processed  78 modules with 32263 lines of code in 4328 ms
```

**Comment by Hosch250** [comment]
@mwolfe02 Is that 5 minutes on the latest release, or the latest commit?  If it is on the latest release, you should see it speed up to less than 30 seconds in the next release.

**Comment by mwolfe02** [comment]
@Hosch250 Latest release, not latest commit.

**Comment by Hosch250** [comment]
Correction: the entire process won't be done in 30 seconds; the resolve declarations process should be in 30 seconds.

**Comment by Hosch250** [comment]
It looks like this is status-planned, but for now, you can install the latest release and checkout the improvements.

**Comment by mwolfe02** [comment]
@Hosch250 On release 2.0.5, it took about 2 minutes to parse the same project as earlier.  That's down from 5 1/2 minutes.  Or, put another way, a 275% improvement! Nice work!

My casual benchmarking had about a minute for "Resolving declarations..." and a minute for "Inspecting..."

**Comment by Hosch250** [comment]
You can use the unit tests immediately after the view populates (although I'd recommend waiting to do the Run All until after the project fully parses at least once because we re-parse the project to make sure we have them all).  The other run options just run known tests.

**Comment by peterennis** [comment]
@mwolfe02, ran this on my code,
Done...processed  20 modules with 12180 lines of code in 62 ms
Nice test and fast!

**Comment by retailcoder** [comment]
It would be a shame to get unit tests back onto the VBIDE API, when 3.0 will bring a subclassed code pane with proper event hooks - and thus drastically cut the resolver's work. I think 2.0 parsing is as good as it's going to get, let's leave unit testing discovery alone for now.
