### ISSUE TITLE
Code Explorer bottom panel label touch-ups

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#1974]
The bottom panel needs some touch-ups:

![image](https://cloud.githubusercontent.com/assets/5751684/16606437/026dd430-4306-11e6-8100-de2127b617f9.png)

 - [x] The `DeclarationType` string is the plain enum's `ToString` value. The localized string is shown in the Rubberduck toolbar. Let's make that string the same value we're displaying in the context toolbar, e.g. "Name (property get accessor: String)".
 - [x] The `Indent` link button reads `In&dent`. WPF captions can't use the same strings as `CommandBarButton` captions.
 - [ ] Both labels should wrap, not scroll.
 - [x] Multiline signatures should appear as one single line so that all nodes have the same height.

**Comment by Hosch250** [comment]
I disagree with showing the type of properties because we don't show it for functions.

**Comment by Hosch250** [comment]
Actually, why don't we just display the as type clause as well, like `Foo() As String`?

**Comment by Hosch250** [comment]
Oh, I thought you were talking about showing it in the nodes.  I agree with showing it in the bottom panel.
