### ISSUE TITLE
RubberDuck should have PasteSpecial *formatX* as classes

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#1978]
Visual Studio has:

Paste JSON as classes
Paste XML as classes

Might be worth also having:

Paste INI as classes

**Comment by retailcoder** [comment]
Visual Studio has that? I never knew... I can't think of any reason to use that, let alone in the VBE. We'd have to come up with formats for the JSON, XML, ...and INI files, and then we could parse the clipboard data and generate the class... but where would that be *copied* from?

**Comment by PeterMTaylor** [comment]
Some suggestions to get ideas here. https://github.com/brucemcpherson/VbaGit/tree/master/libraries

**Comment by ThunderFrame** [comment]
@retailcoder the JSON/XML would already *be* on the clipboard, and as long as the text is valid JSON, we don't care about its schrma, we just parse the node hierarchy and implement skeleton classes to match.

Put some JSON on your clipboard and paste-special it into VS file, to see what VS does.

Thanks @PeterMTaylor, I was aware of the McPherson VBA for Parsing structured text, but if I implement this, all the parsing would be done in C#, and skeleton VBA classes would be added.

**Comment by ThunderFrame** [comment]
huh, found this http://json2csharp.com/

pasted in [this](http://ptv.vic.gov.au/transport/direct/chronos.php?stopId=10001155&limit=10&mode=0)

Got this:

```
public class Stop
{
    public double distance { get; set; }
    public string suburb { get; set; }
    public string transport_type { get; set; }
    public int route_type { get; set; }
    public int stop_id { get; set; }
    public string location_name { get; set; }
    public double lat { get; set; }
    public double lon { get; set; }
}

public class Line
{
    public string transport_type { get; set; }
    public int route_type { get; set; }
    public int line_id { get; set; }
    public string line_name { get; set; }
    public string line_number { get; set; }
    public string line_name_short { get; set; }
    public string line_number_long { get; set; }
}

public class Direction
{
    public int linedir_id { get; set; }
    public int direction_id { get; set; }
    public string direction_name { get; set; }
    public Line line { get; set; }
}

public class Platform
{
    public int realtime_id { get; set; }
    public Stop stop { get; set; }
    public Direction direction { get; set; }
}

public class Run
{
    public string transport_type { get; set; }
    public int route_type { get; set; }
    public int run_id { get; set; }
    public int num_skipped { get; set; }
    public int destination_id { get; set; }
    public string destination_name { get; set; }
}

public class Value
{
    public Platform platform { get; set; }
    public Run run { get; set; }
    public string time_timetable_utc { get; set; }
    public object time_realtime_utc { get; set; }
    public string flags { get; set; }
    public List<object> disruptions { get; set; }
}

public class RootObject
{
    public string time { get; set; }
    public List<Value> values { get; set; }
}
```
