### ISSUE TITLE
Source control integration menu does not display

### ISSUE THREAD

**Issue by peterennis** [rubberduck-vba/Rubberduck#1997]
Move the mouse over the items and they appear.
 Seems to be a load/refresh issue.
 Access 2013 x32, Windows 7 x64
 Rubberduck 2.0.4.19949

![012capture](https://cloud.githubusercontent.com/assets/140737/16703534/61034434-4523-11e6-81af-9c24cd9cffaa.PNG)

**Comment by Hosch250** [comment]
Looks like Windows didn't paint it, possibly because it was busy doing something else.  No idea why, but I've had this sporadically with many programs.

**Comment by peterennis** [comment]
FWIW when I have had this in VBA it is typically a .refresh or .paint that is misplaced/forgotten.

**Comment by Hosch250** [comment]
We don't handle this manually in C#/WPF.  If it keeps happening, let us know, but if it is just sporadic, then it probably isn't our fault.
