### ISSUE TITLE
Code inspection does not work initially if MZ-Tools previously installed

### ISSUE THREAD

**Issue by peterennis** [rubberduck-vba/Rubberduck#1998]
I had to remove the MZ-Tools add-in to get inspection to work.
Then reinstalled MZ-Tools and inspection is OK.
Who's on first?
https://www.youtube.com/watch?v=kTcRRaXV-fg

**Comment by retailcoder** [comment]
Interesting.. this is the first time we have reports of (what appears to be) interactions between the two addins. Which versions are you running (for both)?

**Comment by Hosch250** [comment]
Which inspection?  What code caused it?  This really shouldn't be an issue one way or another...

**Comment by peterennis** [comment]
I had MZ-Tools installed then installed Rubberduck. Running inspection in Rubberduck did not work. I unloaded MZ-Tools, closed Access, open again and then Rubberduck inspection worked. Reinstall MZ-Tools and then they are both working.

**Comment by peterennis** [comment]
Just saw v2.0.5 release one hour ago.
Tested again.
Windows 7 x64, Access x32, MZ-Tools (3.0.1212) and latest Rubberduck (2.0.5.34977)
Windows 8 x32, Access x32, MZ-Tools (8.0.0.85) and latest Rubberduck (2.0.5.34977)
MZ-Tools installed first in both cases.
No problem this time but inspection is very slow to be ready.

![capture27](https://cloud.githubusercontent.com/assets/140737/16705314/5b5231f0-453a-11e6-9277-ac72079ba9a8.PNG)
![capture28](https://cloud.githubusercontent.com/assets/140737/16705316/5b561432-453a-11e6-991b-0c64775fd66e.PNG)
![capture29](https://cloud.githubusercontent.com/assets/140737/16705315/5b53c376-453a-11e6-900d-2d3fa0560f13.PNG)

**Comment by Hosch250** [comment]
Yes, the inspections can be slow-ish for large projects because we have to parse all the open projects, then resolve all the references, and then run the inspections and load them to the UI (which is quite slow...).

**Comment by retailcoder** [comment]
How many "issues" did RD find? Surely there's more than just these 14?

**Comment by peterennis** [comment]
Over 800.
Note: Ref: #2008, #2010 
Multiple references to the same thing. Seems to be some sort of loop...

**Comment by peterennis** [comment]
Also Ref: #2005, #2006
