### ISSUE TITLE
Implicit second public reference not found in compile option statement

### ISSUE THREAD

**Issue by peterennis** [rubberduck-vba/Rubberduck#2002]
v2.0.5
![capture30](https://cloud.githubusercontent.com/assets/140737/16705494/f22bdb76-453f-11e6-9585-ff55e98fd513.PNG)
![capture31](https://cloud.githubusercontent.com/assets/140737/16705493/f228a744-453f-11e6-93b9-d7951329a228.PNG)

**Comment by Vogel612** [comment]
that is status-by-design. We only analyze the currently active code. It's simplistically speaking near-impossible to parse code with conditional compilation statements.

That's why code that won't be used is not analyzed. We sort those out before actually parsing and only check "live" code.

**Comment by retailcoder** [comment]
What @Vogel612 said. Note that we're currently not reading project-scoped conditional compilation arguments, which *will* cause problems.
