### ISSUE TITLE
variable is used but not assigned, multiple error messages, and not an error

### ISSUE THREAD

**Issue by peterennis** [rubberduck-vba/Rubberduck#2004]
![capture18](https://cloud.githubusercontent.com/assets/140737/16706391/2df2ec84-455f-11e6-95aa-54ad4015abb7.PNG)

**Comment by ThunderFrame** [comment]
hmm, that is indeed an assignment.

but without hijacking this into a full-blown code-review, that doesn't look like a very efficient way of reading a file.

I'd suggest 1 of 2 approaches, depending on the expected number of lines:

1. Dimension your array *once* for more than the expected number of lines, then read each line, and then do a `Redim Preserve` *after* you know the total number of lines.

2. Read all the data, or data in multiples of 4K chunks, and do a `Split` once the data is in memory

**Comment by comintern** [comment]
This appears to partially be the same issue as #1667, although a case could be made that using `Redim Preserve` on an uninitialized array should have its own inspection.  The use of an array is really a red herring here - the real issue is that the `Line Input` isn't recognized as an assignment:

```VB
Option Explicit

Public Sub Example()
    Dim target As String            '<-- Variable 'target' is never assigned.
    Dim handle As Integer
    
    handle = FreeFile
    Open "foo.txt" For Input As #handle
    Line Input #handle, target      '<-- Variable 'target' is used but not assigned.
    Close #handle
    
    Debug.Print target              '<-- Variable 'target' is used but not assigned.
End Sub
```

**Comment by comintern** [comment]
`Get` has the same issue:

```VB
Public Sub Example()
    Dim data As Long
    Dim handle As Integer

    handle = FreeFile
    Open "foo.bin" For Random As #handle Len = Len(data)
    Get #handle, 1, MyRecord
    Close #handle

    Debug.Print data
End Sub
```

**Comment by retailcoder** [comment]
Looks like the inspection needs to dig deeper into the context of identifier references. `Input#` would also be a problem. At one point we also wanted to make that inspection look for uninitialized variables passed as `ByRef` arguments and then see if that parameter was assigned, but that was too expensive.
