### ISSUE TITLE
Incorrect report for variable not used

### ISSUE THREAD

**Issue by peterennis** [rubberduck-vba/Rubberduck#2007]
![capture20](https://cloud.githubusercontent.com/assets/140737/16706642/d0cb1b3a-4568-11e6-8fc8-226bae732385.PNG)

**Comment by ThunderFrame** [comment]
You screenshot shows the variable being assigned, but as per the inspection, the variable is never actually used after that assignment, which makes the original assignment (and declaration) redundant.

Perhaps the variable value is used/read later in the code?

**Comment by retailcoder** [comment]
Perhaps the wording could be changed from "not used" to "never referred to"?

**Comment by peterennis** [comment]
I agree that change of wording would be more accurate.
I made a change to use the variable and it is recognized.
![capture25](https://cloud.githubusercontent.com/assets/140737/16737542/bbc4358e-4746-11e6-8da7-31d77f8269dd.PNG)

**Comment by Hosch250** [comment]
How about "Variable value not accessed"?

**Comment by retailcoder** [comment]
@Hosch250 the variable might not have a value if it's not assigned.

**Comment by Hosch250** [comment]
Well, something to emphasize that the variable itself being be "used", but not the value it might contain.  And if it isn't assigned, wouldn't its value be "Nothing"?

**Comment by retailcoder** [comment]
If it's an object reference, yeah it would be `Nothing`. If it's a value, it would be the type's default value. If it's a `Variant`, it would be `Empty`.

I think this wording would be the safest, least ambiguous:

> Variable '{0}' is never referred to.

We *do* have another inspection that verifies whether a given assigned value is used, right?

e.g.

    Dim foo As Integer
    foo = 42 ' should trip the "assigned value is never used" inspection
    foo = 72
    MsgBox foo

If not, then we need it.
