### ISSUE TITLE
Status bar gets stuck on Resolving Declarations with new workbook, crashes on exit

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#2009]
Steps to reproduce:

1. Open Excel ( a new workbook, usually `Book1`, opens by default)
2. Open the VBE (other than Book1, no XLA/M add-ins/projects are open)
3. Close the original workbook, `Book1`, using Excel UI
4. Create a new workbook using Excel UI, it will usually be called `Book2`
5. Rubberduck status gets stuck at Resolving Declarations
6. You may experience a delay of up to 30 seconds while Excel and VBE are unresponsive
7. Any attempt to refresh leaves status bar stuck on Resolving Declarations
8. Quitting Excel crashes on Exit.

**Comment by Hosch250** [comment]
A couple nasty COM exceptions.
