### ISSUE TITLE
Another incorrect report for variable not used

### ISSUE THREAD

**Issue by peterennis** [rubberduck-vba/Rubberduck#2011]
![capture22](https://cloud.githubusercontent.com/assets/140737/16710367/71a12f50-45e0-11e6-964b-4e22554a8830.PNG)

**Comment by Vogel612** [comment]
that's a correct report. The value of `bin` is not "used" later in the code. While it is assigned it's never used as an expression on the right hand side of an assignment or as argument to a Function or Sub.

**Comment by peterennis** [comment]
Thanks for the clarification.
