### ISSUE TITLE
Rubberduck gets stuck on Parsing when code contains `'@Ignore`

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#2012]
It's not a complete RD annotation, but that doesn't mean RD should get stuck on Parsing.

These all get stuck at Parsing, there may be more...

```
'@Ignore
```
```
  '@Ignore
```
```
'@Ignore:
```
```
'@Ignore'
```
```
'@Ignore()
```

**Comment by Hosch250** [comment]
:frowning: Lovely...  Those *should* be reverting to normal comments....

**Comment by Hosch250** [comment]
Actually, this is a complete RD annotation--just without the parameter (the annotation for ignoring inspection results).  The exception happens in the `IgnoreAnnotation` ctor (a deliberately thrown exception, no less).  At this stage, the parser can't fall back on a different type.

**Comment by retailcoder** [comment]
The `@Ignore` annotation isn't intended to be typed up manually anyway - it requires the `Name` of at least one inspection, and that `Name` is known only to Rubberduck, and how it's being recognized is an implementation detail of each individual inspection.

In other words `@Ignore` annotations should be added via the "ignore once" inspection quickfix, not manually.

I agree that malformed annotations should be parsed as plain comments though, but `'@Ignore` is **not** a malformed annotation - so it gets parsed as one.

@Hosch250 indeed, it's too late to revert to a regular comment at that stage. The only solution I'm seeing is to not throw any exceptions in the constructor, allow the parameterless annotation to be created and added, and make an inspection that finds parameterless `@Ignore` annotations and warns about them being invalid.

**Comment by Hosch250** [comment]
I tend to agree here.  And yes, malformed annotations are parsed as plain comments.
