### ISSUE TITLE
Rubberduck suggests renaming TestModule1, move Assert to smaller scope, and does not indent

### ISSUE THREAD

**Issue by peterennis** [rubberduck-vba/Rubberduck#2017]
![capture28](https://cloud.githubusercontent.com/assets/140737/16745715/eda0c098-476b-11e6-8bc9-d90da73a0be5.PNG)

**Comment by Hosch250** [comment]
Those are both separate issues.  There should be no indenting there.

**Comment by retailcoder** [comment]
I can't repro the no indenting - both "indent module" and "indent current procedure" correctly indent the procedure's body.

Verify **Indenter Settings > Intend Options** - is *Indent entire procedure body* checked? I can't recall if it's checked by default...

The rest seems to work exactly as intended.

**Comment by peterennis** [comment]
Indent Option works.
The issue is that when the module was first created this line is not indented but other lines are.

**Comment by peterennis** [comment]
@Hosch250  Not sure how I would move Assert to a smaller scope.

**Comment by Hosch250** [comment]
Because you use `Assert` in only one scope, it wants you to do:

```
'@ModuleInitialize
Public Sub ModuleInitialize()
    'this method runs once per module.

    Dim Assert As Object
    Set Assert = CreateObject("Rubberduck.AssertClass")

End Sub
```

**Comment by Hosch250** [comment]
P.S.  Please don't try it just yet--the refactoring crashed when I tried it.  I'll need to fix that :P

**Comment by Hosch250** [comment]
Also, I that should be indented when it is inserted--I'll take a look at the template later.
