### ISSUE TITLE
Rubberduck encountered an error... request log file

### ISSUE THREAD

**Issue by peterennis** [rubberduck-vba/Rubberduck#2018]
It would be helpful if the message said where the log file could be found and also provided the
GitHub page link.
![capture29](https://cloud.githubusercontent.com/assets/140737/16747259/1fca92a4-4773-11e6-8f9d-447c93cc02c2.PNG)

**Comment by Hosch250** [comment]
Good points.  The log can be found in the General Settings tab in the Settings view.

**Comment by peterennis** [comment]
I have had this message also on a few occasions.
![capture23](https://cloud.githubusercontent.com/assets/140737/16747315/5f44f8de-4773-11e6-9ece-a5cfdd22c414.PNG)

**Comment by Hosch250** [comment]
Were you running VBA code at the time?  That doesn't look like a Rubberduck problem.

**Comment by peterennis** [comment]
Yes, it is from VBA. Other times I restart the system and RD works again. This time RD died.
I tried to get to the menu and it kept repeating the RD death chant.
I had just added the TestModule1.
![capture30](https://cloud.githubusercontent.com/assets/140737/16747765/5792d8e8-4775-11e6-918e-da3c6cd1b73e.PNG)

**Comment by peterennis** [comment]
I cannot get to the menu or system settings. Is the log file on  disk?

**Comment by Hosch250** [comment]
"C:\\users\\{username}\\AppData\\Roaming\\Rubberduck\\logs"

**Comment by Hosch250** [comment]
By the way, did you get the latest release from Friday (Rubberduck 2.0 RC 2)?

**Comment by retailcoder** [comment]
That last screenshot looks very much like #1948 - I just earlier today merged a PR that should eliminate that utterly annoying glitch.

**Comment by Vogel612** [comment]
Should've been more clear... The Rubberduck log files are under `%AppData%\Rubberduck\logs`, which usually resolves to the directory Hosch already mentioned

**Comment by peterennis** [comment]
No logs!
Is it expected to be created if I close Access?
![capture31](https://cloud.githubusercontent.com/assets/140737/16747948/3681889c-4776-11e6-98e2-12361fea9f09.PNG)

**Comment by Hosch250** [comment]
And that is because the default log setting is None.  Set it at Trace and try to reproduce this.

**Comment by retailcoder** [comment]
^^ what he said. we didn't want to clutter up users' things with tons of log files, so we made it an opt-in feature, disabled by default. If you only want to log exceptions the ERROR or FATAL level should be good enough; TRACE will log quite a lot of things :smiley:

**Comment by peterennis** [comment]
OK.  RD version 2.0.5.34977

**Comment by peterennis** [comment]
Restart. ERROR logging set. The form parse button no longer works. Log attached.
![capture32](https://cloud.githubusercontent.com/assets/140737/16748257/ef9b4cc2-4777-11e6-81fe-eb6f2584b888.PNG)

[rubberduck.zip](https://github.com/rubberduck-vba/Rubberduck/files/358169/rubberduck.zip)

**Comment by Hosch250** [comment]
That button doesn't work because there are no changes to parse.  I agree it is unintuitive, but the boss asked for it.

**Comment by retailcoder** [comment]
@Hosch250 I prefer "the mug" :wink:

**Comment by peterennis** [comment]
You could gray out the button as "disabled" and show the color when it is ready i.e. enabled. Typical ribbon style.

**Comment by Hosch250** [comment]
True.  Theoretically, it is "grayed out", except graying out doesn't work on image buttons, only text buttons.

**Comment by peterennis** [comment]
Swap the image?

**Comment by peterennis** [comment]
Change, change, change - #2004, #2008
I could see this killing the system resources...
![capture34](https://cloud.githubusercontent.com/assets/140737/16749222/7f5e7578-477d-11e6-9927-68bcbd16659c.PNG)
![capture35](https://cloud.githubusercontent.com/assets/140737/16749233/9200b934-477d-11e6-8e38-de3e4b174c5d.PNG)
![capture36](https://cloud.githubusercontent.com/assets/140737/16749235/9adedeb4-477d-11e6-86a6-6d175a0ed2cd.PNG)
![capture37](https://cloud.githubusercontent.com/assets/140737/16749239/a286435a-477d-11e6-9bc5-bf4fd7c7dfd4.PNG)

**Comment by Hosch250** [comment]
Umm, that has an interesting result on inspections...

**Comment by retailcoder** [comment]
WTF?

**Comment by Hosch250** [comment]
I'm not sure what's going on there, but I can't repro this.  Can you share a workbook with a minimal, verifiable example?

**Comment by peterennis** [comment]
This is Access 2016 x32. I will commit this version and post the GitHub link where you can download the database.

**Comment by peterennis** [comment]
Log file attached, ctor gets a mention. Access won't start so I will give the system a 3 fingered salute and get back to you.

[rubberduck.zip](https://github.com/rubberduck-vba/Rubberduck/files/358259/rubberduck.zip)

**Comment by peterennis** [comment]
Commit here: https://github.com/peterennis/aegit/commit/bbfdc5abf7f953d273f48ad9c2803b582f033e03
Download raw zip accdb v182 here: https://github.com/peterennis/aegit/blob/92ddb37b8114012c2d3525b5c81640e59a01e821/zip/adaept%20revision%20control%20accdb%20v182.zip
