### ISSUE TITLE
FunctionReturnValueNotUsedInspection inserts extra `End Sub`

### ISSUE THREAD

**Issue by comintern** [rubberduck-vba/Rubberduck#2022]
I'm still working on finding the minimal example for this, but the when I ran the code from https://github.com/peterennis/aegit/blob/master/aerc/src/basGDIPlus.bas (commit bbfdc5a) through FunctionReturnValueNotUsedInspection quick fix, I ended up with this at the bottom of the Sub:

``` VB
#If Win64 Then
    'Help function to get a OLE-Picture from Windows-Bitmap-Handle
Private Sub BitmapToPicture(ByVal hBmp As LongPtr, Optional ByRef bIsIcon As Boolean = False)

        Dim TPicConv As PICTDESC
        Dim UID As GUID

        With TPicConv
            If bIsIcon Then
                .cbSizeOfStruct = 16
                .PicType = 3    'PicType Icon
            Else
                .cbSizeOfStruct = Len(TPicConv)
                .PicType = 1    'PicType Bitmap
            End If
            .hImage = hBmp
        End With

        CLSIDFromString StrPtr(GUID_IPicture), UID
        OleCreatePictureIndirect TPicConv, UID, True, BitmapToPicture

    End Sub
    End Sub
#Else
    Private Function BitmapToPicture(ByVal hBmp As Long, Optional bIsIcon As Boolean = False) As StdPicture

        Dim TPicConv As PICTDESC, UID As GUID

        With TPicConv
            If bIsIcon Then
                .cbSizeOfStruct = 16
                .PicType = 3    'PicType Icon
            Else
                .cbSizeOfStruct = Len(TPicConv)
                .PicType = 1    'PicType Bitmap
            End If
            .hImage = hBmp
        End With

        CLSIDFromString StrPtr(GUID_IPicture), UID
        OleCreatePictureIndirect TPicConv, UID, True, BitmapToPicture

    End Function
#End If
```

This might(?) be related to #2021 (note that it exhibits that behaviour also), but I doubt it - this looks more like an issue with keeping track of the insertion point.

**Comment by Hosch250** [comment]
I just looked at this, and it is exactly the same issue.  The inspection quickfix works with the selections the parser/resolver give it.  The selections for these are off-by-one in a great many places throughout that file :(

**Comment by retailcoder** [comment]
Removing [code-inspections], this is clearly a [code-parsing] issue:

![image](https://cloud.githubusercontent.com/assets/5751684/21274538/ba73940a-c396-11e6-96f6-20639eaaa987.png)

not sure what's up with that off-by-one here...
