### ISSUE TITLE
Parser or resolver errors should invalidate Code Inspection results (or disable quick fixes)

### ISSUE THREAD

**Issue by comintern** [rubberduck-vba/Rubberduck#2023]
Still using https://github.com/peterennis/aegit/tree/master/aerc/src for testing.  I ran the "Fix all occurrences in project" for `FunctionReturnValueNotUsedInspection`, which caused a parser error.  However, it seems like the Code Inspections window was never invalidated, because I could select "Fix" for the `ImplicitVariantReturnTypeInspection` hint on this Function...

``` VB
Public Function SpFolder(ByVal SpName As String)

    Dim objShell As Object
    Set objShell = CreateObject("Shell.Application")
    Dim objFolder As Object
    Set objFolder = objShell.Namespace(SpName)
    Dim objFolderItem As Object
    Set objFolderItem = objFolder.Self

    SpFolder = objFolderItem.Path

End Function 
```

...which resulted in this:

``` VB
Public Function SpFolder(ByVal SpName As String)

    Dim objShell As Object
    Set objShell = CreateObject("Shell.Application")
    Dim objFolder As Object
    Set objFolder = objShell.Namespace(SpName) As Variant   '<-- This don't belong here.
    Dim objFolderItem As Object
    Set objFolderItem = objFolder.Self

    SpFolder = objFolderItem.Path

End Function
```

I'm not _exactly_ sure that this is related to the parser error, but I can't replicate this without the parser failing.

**Comment by Hosch250** [comment]
Yes, this is related to the parser error because the declaration selections aren't updated...

**Comment by MDoerner** [comment]
This issue is not fixed. If running inspections after parseing is disabled, the inspection results in the code inspection window do not get invalidated. 

This is a possible cause for issue #4503.
