### ISSUE TITLE
Code inspection allows refresh of project with missing references

### ISSUE THREAD

**Issue by comintern** [rubberduck-vba/Rubberduck#2024]
I managed to get a project with a missing reference (VBE warned on open).  The status bar stuck on "Resolving references", which (I guess) was to be expected.  However, the refresh button on the Code Inspection window was still active.  So... being the button pusher that I am, I clicked on it and ended up with a perpetually spinning busy indicator with all of the parser states stuck in "Pending".

**Comment by retailcoder** [comment]
Fixed. All refresh commands behave identically now.
