### ISSUE TITLE
RD should have an inspection for unused labels

### ISSUE THREAD

**Issue by comintern** [rubberduck-vba/Rubberduck#2027]
Consider this common error handling paradigm:

``` VB
Private Sub Foo()
    On Error GoTo Handler
    Application.ScreenUpdating = False

    Debug.Print "Foo"

CleanExit:
    Application.ScreenUpdating = True
    Exit Sub
Handler:
    MsgBox Err.Number
End Sub
```

The label `CleanExit:` is defined, but never used.  In the code above, this is almost certainly an error (to function as intended it needs a `Resume` in the error handler).  In other cases where labels aren't used, they arguably cause a readability issue at very least:

``` VB
Private Sub Foo()
Foo:
    Debug.Print "Foo"
Bar:
    Debug.Print "Bar"
Baz:
    Debug.Print "Baz"
End Sub
```

**Comment by Stevefb** [comment]
I think this could be built upon to include an inspection for multiple exit points, methods should have 1 and only 1 exit point.  
```vb
Private Sub Foo()
    On Error GoTo Handler
    Application.ScreenUpdating = False

    Debug.Print "Foo"

CleanExit:
    Application.ScreenUpdating = True
    Exit Sub                                               ' Intended Exit Point
Handler:
    MsgBox Err.Number
End Sub                                                  ' Unintended Exit Point
```

**Comment by Vogel612** [comment]
@Stevefb "Methods should have 1 and only 1 exit point" is only a rule of thumb in this day and age. This was an old rule to make programming in older languages more obvious where it was harder to see the context of a method.

Blindly following this rule makes for bad code. A Significant number of exit points in a method can indicate a code-smell (like a method that does too many things), but it's not per se bad. As such I'd advise against having such an inspection

**Comment by retailcoder** [comment]
The test stubs will have to replace `Arrange:`, `Act:` and `Assert:` labels with comments then.

**Comment by ThunderFrame** [comment]
looks like those test stubs were using labels as, well, erm, labels.

To draw a parallel, not all HTML anchors need to have a link that refers to them, but they can still be useful.

**Comment by comintern** [comment]
I think the main difference between HTML anchors and VBA labels is in scope -- HTML anchors are public and (perhaps literally) global.  VBA labels are only useful to author and can only be used as jump targets in local scope.  They are also primarily a flow control mechanism, so using them as comments is misleading.  I'm not sure it's any different than a number of other things you could use to "comment" code:

```VB
Private Sub FooBar()
    'Debug statements:
    Debug.Print "The FooBar sub frobs the baz."
    'If statements:
    If False Then TheFooBarSubFrobsTheBaz = True
    'Precompiler directives:
    #Const TheFooBarSubFrobsTheBaz = True
    'Etc.
End Sub
```
