### ISSUE TITLE
Parse stuck in a loop

### ISSUE THREAD

**Issue by peterennis** [rubberduck-vba/Rubberduck#2028]
Created my first RD test. After success I could not get the parser to run.
Close test window, make a change to force the parser.
Run parse and loop forever...
I will put a full Trace on in future.
![capture39](https://cloud.githubusercontent.com/assets/140737/16754875/10c8ff00-47ac-11e6-8a6b-44dd8a7e215b.PNG)
![capture40](https://cloud.githubusercontent.com/assets/140737/16754866/fd14d45c-47ab-11e6-8e68-542217148d0c.PNG)

**Comment by peterennis** [comment]
[rubberduck.zip](https://github.com/rubberduck-vba/Rubberduck/files/358548/rubberduck.zip)

**Comment by Hosch250** [comment]
Parse error.  Can you share the code to reproduce it?

**Comment by retailcoder** [comment]
deemed fixed
