### ISSUE TITLE
RD Crash

### ISSUE THREAD

**Issue by peterennis** [rubberduck-vba/Rubberduck#2029]
Installed TM-VBAInspector latest and RD crashed.
![capture41](https://cloud.githubusercontent.com/assets/140737/16755144/3c449d36-47ae-11e6-8e38-6954b16b554e.PNG)
[rubberduck.zip](https://github.com/rubberduck-vba/Rubberduck/files/358553/rubberduck.zip)

**Comment by Hosch250** [comment]
Same stack trace as https://github.com/rubberduck-vba/Rubberduck/issues/2028

**Comment by peterennis** [comment]
OK. I will restart the box and see what happens next.
