### ISSUE TITLE
Function return value is not used

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#203]
Consider a function:

    Public Function Foo(ByVal bar As String) As Integer
        Foo = 42
    End Function

Then a function call:

        Foo "bar"

Either the function has side-effects and should be a procedure, or not using the returned value is a programming error. Rubberduck should warn about the function's return value not being used; formal definition would be something like "a function call that isn't on the right-hand side of a local variable assignment".

**Possible quick-fix:**
- [ ] Introduce variable: this introduces a local declaration on the line immediately above the function call, and an assignment of that variable with the function call on the right-hand side of the `=` operator.

**Comment by ThunderFrame** [comment]
Tests:
```
Foo Foo(Foo("Bar"))
With Foo
If Foo Then
For Each Bar in Foo
While Foo
Until Foo
Address Of Foo
```

And, there are plenty of functions where you don't necessarily care about the return value, eg.

```
MsgBox "WTF"
Workbooks.Add
```

**Comment by retailcoder** [comment]
@ThunderFrame ok, you don't necessarily care about the return value of `MsgBox`... but `Workbooks.Add` followed by a reference (implicit or not) to the `ActiveWorkbook`, is bad code.

Your test cases are mostly resolver tests - the inspection simply looks at the `References` collection that the resolver populates.

**Comment by ThunderFrame** [comment]
Indeed `Workbooks.Add` is bad practise, I meant it more as an example of a method on an object where I needn't care about the result.

As you say, `Workbooks.Add` is just about worth its own inspection/refactor, given how often I find this:

```
Dim wbk As Workbook
Application.Workbooks.Add
Set wbk = ActiveWorkbook
```

**Comment by retailcoder** [comment]
that would get picked up by this very inspection here... "function's return value is not used" - I think it's the best thing to do here, remind the user that `Workbooks.Add` is a function that returns the `Workbook` it creates. That should spark *something* at least.

And for instances where the function's return value is intentionally not used, there's always the `'@Ignore` annotation.

**Comment by Vogel612** [comment]
I daresay that's an inspection that leads to a bad user experience, if geared incorrectly.

A dev is completely within their right to ignore method output for a significant number of methods, where the result actually doesn't matter. 

I'm not sure how many methods that would be, but if the inspection marks every single one of them it's not helping, it's annoying.  
FWIW IntelliJ has a similar inspection for Java. But it **only** checks for `Throwable` results, so it checks methods that `return Exception`, and it only triggers when the result is not thrown.

If my IDE starts mucking around that I don't use the result of `StringBuilder.append` I'll throw it on the garbage dump, because that's not helping...

**Comment by retailcoder** [comment]
@Vogel612 then let's make it ignore all built-in declarations except for a few cherry-picked ones, and make it concentrate on the user's code. If they're not using a `Function`'s return value anywhere, then they probably meant to write a `Sub`.

**Comment by Hosch250** [comment]
For reference, that would be `_state.AllUserDeclarations.Where(d => d.DeclarationType == DeclarationType.Function)`, where `_state` is the `ParserState`.

**Comment by autoboosh** [comment]
Here's a first possible implementation.

A function's return value is considered "not used" if:

1. it isn't used in the function's return statement
2. it isn't used in an AddressOf call
3. the function is called but it's result is not assigned to anything

Only user defined functions are considered (without an @ignore annotation).

The quick fix consists of converting the function to a procedure. Apparently there was a quick fix for that already so I went ahead and changed it to support removing return statements.

Please provide some feedback, I'm happy to change the code as needed. Thanks.

**Comment by retailcoder** [comment]
@autoboosh mostly correct, except when the function's return value isn't assigned, it already trips an inspection result (same for a property getter). Getting the `AddressOf` context involves inspecting the `Parent` of the context of the reference of the function's declaration; if that's a `AssignStmtContext` we've got a winner!

**Comment by autoboosh** [comment]
If I understood you correctly you're saying that if a function does not assign a result value, it should never appear as an issue? Even if the function's result value is used somewhere?

I couldn't find a `AddressOfStmtContext` in the code base. Right now it walks up the "context chain" and if it finds a `VsAddressOfContext` it treats it as being part of an AddressOf call. Is this correct?

**Comment by autoboosh** [comment]
Changed it a bit:

* Made a quick fix just for this new inspection as suggested by Hosch250
* Added tests suggested by Hosch250
* Show function name in code inspection GUI

**Comment by Hosch250** [comment]
Sounds good.

**Comment by autoboosh** [comment]
Changed a bit again :) This time to implement retailcoder's suggestions:
* Reused ConvertToFunctionProcedureQuickFix (moved it into its own file)
* InspectionsUI instead of RubberduckUI
