### ISSUE TITLE
Resource string for quick-fixes isn't in the correct culture

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#2035]
ref. #1220 - seems *one* thing still initializes in the OS culture, regardless of Rubberduck settings:

![image](https://cloud.githubusercontent.com/assets/5751684/16781494/8ea0d0ea-4849-11e6-8aa1-ef851e546385.png)

Quick-fixes resources should be in English here (per RD display settings), but they're in French. Note that everything else is fine, including the `DeclarationType` translations embedded in the quick-fix strings.

Sticking [critical] on this one, since it should have been fixed long ago.

**Comment by Hosch250** [comment]
I can reproduce this by changing the settings after the inspection results are loaded, but that is it.
