### ISSUE TITLE
Performance measurement

### ISSUE THREAD

**Issue by peterennis** [rubberduck-vba/Rubberduck#2040]
I use an old machine for performance tests.
W81 x32, 3GB Ram, Access 2010 x32.
Rubberduck 2.0.5.34977 takes ~1 minute to parse my project.
![capture34](https://cloud.githubusercontent.com/assets/140737/16788563/fdc9e748-485a-11e6-8678-651c5cbdc51f.PNG)

**Comment by Hosch250** [comment]
In other words, Windows starts a bunch of threads to handle our parsing/resolving/inspecting needs that fast?

**Comment by peterennis** [comment]
Closed down. Tried again. This time it took ~3 minutes to be ready.
Log is here.

[rubberduck.zip](https://github.com/rubberduck-vba/Rubberduck/files/360533/rubberduck.zip)

**Comment by peterennis** [comment]
Clicked the Add-In button and it crashed Access. Updated log here.

[rubberduck.zip](https://github.com/rubberduck-vba/Rubberduck/files/360540/rubberduck.zip)

**Comment by Vogel612** [comment]
I'm not sure how much of this is actually "actionable". What exactly is the "please implement / do X" for this issue? Is it a request for better performance or a report for the parser error messages in the log?

**Comment by Vogel612** [comment]
Closing as not actionable, if there's no differing opinions
