### ISSUE TITLE
git:  failed to set proxy

### ISSUE THREAD

**Issue by woxovvoxow** [rubberduck-vba/Rubberduck#2041]
I try to publish my existing repository to a remote location:

![image](https://cloud.githubusercontent.com/assets/10561922/16797426/cc332b58-48e7-11e6-9c96-7408fa0d8850.png)

I succeeded to set up the proxy settings via tortoise-git and i can access the remote repo via GitGui.

**Comment by rubberduck203** [comment]
I’m terribly sorry no one ever responded to this. Must’ve gotten lost in the shuffle. 
Unfortunately, we decided to remove the experimental Git features. Please see #3758.
