### ISSUE TITLE
Error when using `ParserState.Parse` method of Rubberuck Type Library

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#2042]
When executing this code in Access 2016 32-bit.

``` vb
  Dim rd As Rubberduck.ParserState
  Set rd = New Rubberduck.ParserState

  rd.Initialize Application.VBE
  rd.Parse
  '...
```

Run-time error: '-2146233088 (8131500)
"One or more errors occurred"
![parse](https://cloud.githubusercontent.com/assets/16574009/16800626/8549413a-4939-11e6-9cd9-393c69e90d8f.png)

If I choose `Debug`, the active line is `rd.Parse` and then Step Into the code, the line succeeds and the code can carry on.

**Comment by retailcoder** [comment]
Fixed.
