### ISSUE TITLE
`ParserState.AllDeclarations` property can't be inspected by index

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#2043]
The `AllDeclarations` property returns an Array of `IDeclaration`, but the array cannot be indexed. A `For Each..Next` loop can iterate the array members, but a `For..Loop` cannot:

The Rubbderduck Type Library doesn't allow me to declare a variable of type `IDeclaration`

``` vb
  Dim rd As Rubberduck.ParserState
  Set rd = New Rubberduck.ParserState

  rd.Initialize Application.VBE
  rd.Parse

  'This works, but decl must be a variant
  Dim decl As Variant  
  For Each decl In rd.AllDeclarations()
    Debug.Print decl.Name
  Next decl

  Dim iDecl As Long
  For iDecl = LBound(rd.AllDeclarations) To UBound(rd.AllDeclarations)
    'This line fails to compile with error: Wrong number of arguments or invalid property assignment
    Set decl = rd.AllDeclarations(iDecl)
  Next iDecl
```

**Comment by Hosch250** [comment]
Yeah, we need to re-write pretty much the entire COM library from scratch--and put it in its own project too, I'd recommend.

**Comment by retailcoder** [comment]
@Hosch250 actually, I'd rather not have too many type libraries floating around. IMO best-case scenario is VBA code can reference `Rubberduck.tlb` and get everything we have to offer right there. Also the `Rubberduck.API` namespace is brand new, off the 2.0 parser code.

**Comment by retailcoder** [comment]
@ThunderFrame why iterate an object collection with a `For` loop, when a `For Each` loop is known to be faster? I agree there is a bit of marshaling tweaks to be done here (it's annoying that you need a `Variant` there), and yes indeed `LBound`/`UBound` *should* work.

Also note the `ParserState` events don't work for now because of a threading issue, ref. #1239.

**Comment by ThunderFrame** [comment]
@retailcoder because the `AllDeclarations` property currently returns an array, and a For Loop is generally faster than a For Each Loop, with arrays.
