### ISSUE TITLE
Rubberduck Type Library doesn't appear to return CoClasses or their members

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#2044]
The DeclarationType enumeration doesn't seem to have a CoClass member.

Maybe I'm doing it wrong, but I'm trying to find the events that a an object implements.

For example, in Excel, to find the events for the Worksheet CoClass, I need to find the `DocEvents` interface and enumerate the DocEvents members, but currently, it seems that `AllDeclarations` does not return any details about the relationship between `Worksheet` and `DocEvents`

**Comment by retailcoder** [comment]
Does the API let you access the events under `Workbook`? Not much care was given to the COM API when we started adding support for this in Rubberduck itself.

**Comment by ThunderFrame** [comment]
No, the events aren't under Workbook. For example, the `SheetBeforeRightClick` Workbook event appears as a member of the `WorkbookEvents` declaration and the `IWorkbookEvents` declaration, but not under the `Workbook` declaration.

**Comment by ThunderFrame** [comment]
Actually, it doesn't look like I can even find the members of Workbook (or any CoClass)

**Comment by ThunderFrame** [comment]
For example, the Workbook property `BuiltinDocumentProperties' has a parent declaration of `_Workbook`

**Comment by comintern** [comment]
This information should all be in the collected declarations now (both coclasses and exposed events).
