### ISSUE TITLE
Systematic crash upon quit in MS Access

### ISSUE THREAD

**Issue by ubidev** [rubberduck-vba/Rubberduck#2046]
Hi!
I'd like to use this amazing package in MS Access but unfortunately, it almost always crashes Access when I quit the application. I'm able to reproduce the problem in many specialized/slim dev vms I'm using for VBA programming without issues when this tool is not installed. These VMs are composed of different OS (x64) / Office (x32) / SQLServer (x64) versions and fully patched.

How can I help troubleshoot this problem?

Thanks in advance for you help.

ubidev

**Comment by Vogel612** [comment]
@Hosch250 mentioned in #1190 that the crash on exit will be addressed soon. That's for excel, but I assume that Access has the same underlying problem and will be fixed, too.

**Comment by peterennis** [comment]
@ubidev, If this is what you see then I am having the same problem. RD 2.0.5.34977
![capture42](https://cloud.githubusercontent.com/assets/140737/16818388/50107aa2-48fc-11e6-89df-0050f754d361.PNG)

**Comment by Hosch250** [comment]
Yup, same problem.

**Comment by ubidev** [comment]
Yep indeed!!

**Comment by Vogel612** [comment]
I'll assume this to be tentatively fixed. I haven't been experiencing crashes on my own Access either
