### ISSUE TITLE
Remove Option Base 1 Quick Fix

### ISSUE THREAD

**Issue by Hosch250** [rubberduck-vba/Rubberduck#2051]
We can offer a quick fix to remove `Option Base 1` statements.

**Comment by retailcoder** [comment]
That would be a very dangerous quick-fix, that could instantaneously introduce a pletora of off-by-one errors everywhere in the code. IIRC it was debated at one point, and we decided that the best course of action would be to simply treat the inspection as a warning, a cue to remember "look, it's base 1 here"

**Comment by Hosch250** [comment]
Oh.  Makes sense.
