### ISSUE TITLE
Code Explorer should allow Expand/Collapse All Nodes, or Expand/Collapse All Folders

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#2053]
Maybe make the distinction of expanding all nodes/folder for *all* projects, or all nodes/folders under *current selection*.

So that would be 8 Commands, visibility being context dependent:

:file_folder: Collapse All Folders
:open_file_folder: Expand All Folders
:8ball: Collapse All Nodes
:8ball: Expand All Nodes

:file_folder: Collapse All Sub-Folders
:open_file_folder: Expand All Sub-Folders
:8ball: Expand All Child Nodes
:8ball: Collapse All Child Nodes (that aren't Folders?)

**Comment by Hosch250** [comment]
I implemented expand/collapse all subnodes at the node level.  I figured expanding collapsing/expanding at the project level would be pretty good, and it would make the UI quite as cluttered.  I put the commands in the context menu.
