### ISSUE TITLE
RD hangs on "Loading references" when RD added as a reference

### ISSUE THREAD

**Issue by lkavicky** [rubberduck-vba/Rubberduck#2054]
When opening a project containing a reference to RD, Rubberduck always hangs on "Loading references", refresh does not help. When I remove the reference and refresh RD, everything is fine, I can even add Rubberduck again (I have multiple tests with early bound Assert)

The only related log entry is this (for every module in the project - changed to XYZ):

`2016-07-14 21:12:52.9201;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'XYZ' state is changing to 'Pending' (thread 7);`

Nothing more.
I'm running RD 2.0.5-rc (I have encountered the issue on earlier versions too) on Office 2010(32bit), Win7 (64bit)

**Comment by Hosch250** [comment]
I cannot reproduce this by adding the main Rubberduck reference, but I can by adding the Rubberduck Source Control 1.0 reference.

**Comment by Hosch250** [comment]
It looks like it may be because we are exposing an `IEnumerable` to COM.  Is this a possible cause, @retailcoder & @comintern?

**Comment by retailcoder** [comment]
@Hosch250  an `IEnumerable`? Or a generic `IEnumerable<T>`? Because generics can't be exposed to COM - and I don't think `IEnumerable` is much of a problem. Which `IEnumerable` are you talking about?

**Comment by Hosch250** [comment]
TBH, I have no idea.  The only information I can see is that the type is `IEnumVARIANT`.
