### ISSUE TITLE
Configuring a feature should be more accessible

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#206]
Bring up configuration settings dialog for todo markers and inspection severity when user clicks "configure" button on the toolbar of respetive windows.

**Comment by ckuhn203** [comment]
Possibly related to #105.

**Comment by retailcoder** [comment]
Buttons are now on the toolbars, but hidden.

**Comment by retailcoder** [comment]
If not for 2.0, then for 2.x; the settings presenter needs to be refactored so that we can bring up the dialog on any "page".

**Comment by Hosch250** [comment]
Completed.
