### ISSUE TITLE
New code inspection error using RD 2.0.5 - Binary as parameter error.

### ISSUE THREAD

**Issue by PeterMTaylor** [rubberduck-vba/Rubberduck#2063]
Ok, found another code inspection error with RD 2.0.5 regarding variant for Binary type.

![capture 2 0 5 binary as variant error - before](https://cloud.githubusercontent.com/assets/2254567/16862557/bd04bc08-4a8d-11e6-8808-defe8099a95d.PNG)
![capture 2 0 5 binary as variant error - report error](https://cloud.githubusercontent.com/assets/2254567/16862556/bd0285d2-4a8d-11e6-9130-cb5c59fabddf.PNG)
[rubberduck 2.0.5 - Binary as Variant.zip](https://github.com/rubberduck-vba/Rubberduck/files/365132/rubberduck.2.0.5.-.Binary.as.Variant.zip)
![capture 2 0 5 binary as variant error - after](https://cloud.githubusercontent.com/assets/2254567/16862555/bcb140a0-4a8d-11e6-9d60-6ff9c2ee0613.PNG)

**Comment by Hosch250** [comment]
This is a quick fix bug?  It is a pretty serious one.
