### ISSUE TITLE
Code Explorer meant to shows errors? RD 2.0.5

### ISSUE THREAD

**Issue by PeterMTaylor** [rubberduck-vba/Rubberduck#2064]
Was not sure if Code Explorer by design or logic show errors as they find them. 
I presumed duirng Resolving declarations.

Comparing Module 1 there is a method yet under useful stuff node there are errors and question mark warning or errors. I didn't know how to interpret so I showed it.

![capture 2 0 5 code inspections errors](https://cloud.githubusercontent.com/assets/2254567/16862791/ff583b96-4a8f-11e6-878d-a054e5c16d14.PNG)

**Comment by Hosch250** [comment]
This means there was a parse/resolve error, and the CE doesn't know if these items are still there, but also isn't sure if they are gone.

**Comment by retailcoder** [comment]
Perhaps the bottom panel could display some useful message when one such node is selected?

> Module contains code that Rubberduck could not parse. Members are not known to still exist.

Or similar.

**Comment by Hosch250** [comment]
What about declaration resolver errors?

**Comment by retailcoder** [comment]
"or similar". got suggestions?

**Comment by PeterMTaylor** [comment]
Agreed @retailcoder. Your message would be in this format like the CI UI as shown I included in red underneath so as my eyes reads down the list does help my understanding in seeing what it means. Please also indicate all of the error icons used where applicable so no confusion arises. Thus A red circle X and yellow ! triangle was used.

> (Red X circle) Module contains code that Rubberduck could not parse. Members are not known to still exist. (for an example)

![capture 2 0 5 ce error no show of errors - suggestion](https://cloud.githubusercontent.com/assets/2254567/16892373/dcd09752-4b53-11e6-9896-674a292a4df1.png)
