### ISSUE TITLE
Rubberduck commandbar can load despite a failed startup

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#2066]
![image](https://cloud.githubusercontent.com/assets/5751684/16877467/35e41b36-4a76-11e6-9fe9-8e4e2a308100.png)

Yet, the Rubberduck commandbar is showing up, stuck on "loading references" - the Rubberduck menu isn't displayed.

This exception is top-level and Rubberduck is gone at that point: the commandbar should not have appeared. Not sure how to repro, but the commandbar must not load if the add-in fails to startup cleanly.

**Comment by Vogel612** [comment]
Is this fixed with the linked PR?

**Comment by Hosch250** [comment]
No, I was unable to mark it as unloaded.

**Comment by Vogel612** [comment]
marked as norepro 10 months ago, no new reports, considered fixed
