### ISSUE TITLE
Excel hard crash

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#2070]
After all the work gathering screen shots for #2069, I double clicked a procedure to bring up code to start working and Excel hard crashed. 

Here's the log:

[rubberduck.log.txt](https://github.com/rubberduck-vba/Rubberduck/files/366455/rubberduck.log.txt)

**Comment by Hosch250** [comment]
Are you sure this was RD's fault?  There isn't anything in the log, and, if you double-clicked from the Project Explorer, then I'm pretty sure this was more/less a fluke thing--at least, I've not been having this issue.

**Comment by retailcoder** [comment]
deemed fixed
