### ISSUE TITLE
MS Access crashes when opening an existing repo for existing project

### ISSUE THREAD

**Issue by lkavicky** [rubberduck-vba/Rubberduck#2076]
I have a project with around 30 modules/classes. I have created a repository for the project using RD Source Control. RD somehow forgot the relation between the project and the repo (possibly my fault as I was copying the project) so while I have opened accdb file in Access I tried to use the Open Existing Repo function of RD Source Control and selected the directory containing the repo. 
After that following window appeared:

![1](https://cloud.githubusercontent.com/assets/1942695/16912927/8be7a2c8-4ce7-11e6-8280-8ddec929c8e7.png)
So I clicked on yes... a lot of times (much more than the number of modules) without any effect. So after minutes of clicking on yes I have clicked on Cancel. 
That has lead to another window enabling me to set a name for some of the modules. This was repeated a few times, I have clicked on YES without renaming the modules and then Access has crashed.
The debug info was just:
`Unhandled exception at 0x2FC6ED5E in MSACCESS.EXE: 0xC0000005: Access violation reading location 0x00000001.`

When I've opened the file again, only one module has remained there, but even that is corrupted. When I've tried to open it this followed:
![2](https://cloud.githubusercontent.com/assets/1942695/16913052/4e9a2c96-4ce8-11e6-9018-9c45372cbb64.png)

I'm running Access 2010 (32bit) on 64bit Win7, RD 2.0.5-rc

**Comment by rubberduck203** [comment]
I’m sorry no one ever responded to you. 
Unfortunately, we decided to remove the feature in #3758.
