### ISSUE TITLE
Code Inspection - False Positive: Variable 'xyz' is not used

### ISSUE THREAD

**Issue by Stevefb** [rubberduck-vba/Rubberduck#2084]
In MS Word, a module with the following code results in a Code Inspection false positive, variable 'aDoc' is not used :

``` vb
Option Explicit
Sub aDocIsUsed()
   Dim aDoc As Document
   Set aDoc = setdoc(Selection.Range)
   ThisDocument.Paragraphs(1).Range.Style = aDoc.Styles("Normal")
End Sub

Function setdoc(rng As Range) As Document
    Set setdoc = rng.Parent
End Function
```

**Comment by Hosch250** [comment]
No repro.

**Comment by Stevefb** [comment]
That's odd. I'm using Wd2010, Win10 and this has been a false positive for a while for me. I'll try a different PC when time permits.

**Comment by Hosch250** [comment]
Different PC won't matter.  Are you running the latest release, and does it complain when this is in a std module and is the only code in the project?

**Comment by Stevefb** [comment]
Oh... and I just noticed that I also get this message if I have 2 documents open and I close only 1 of them.

**Comment by Stevefb** [comment]
I moved the code to a new document with so that this is the ONLY code in that doc, shut down everything (because RD would not refresh) and re-ran the inspection.
Rubberduck Code Inspections - 07/20/2016 08:36:58
5 issues found.
Hint: Member 'aDocIsUsed' is implicitly public - ((Code)]) Project.Module4, line 3
Hint: Member 'setdoc' is implicitly public - ((Code)]) Project.Module4, line 15
Hint: Parameter 'rng' is implicitly passed by reference - ((Code)]) Project.Module4, line 15
Suggestion: Parameter 'rng' can be passed by value - ((Code)]) Project.Module4, line 15
Warning: variable 'aDoc' is not used - ((Code)]) Project.Module4, line 5

**Comment by Hosch250** [comment]
Reproduced in Word.  The resolver is not resolving the last reference of `aDoc` to the variable.

**Comment by Hosch250** [comment]
What I want to know is why `Paragraphs` resolves to `Text`.

**Comment by retailcoder** [comment]
Confirmed fixed.

![image](https://cloud.githubusercontent.com/assets/5751684/21918575/a5a7f2d8-d920-11e6-8e3f-b9b970988f34.png)
