### ISSUE TITLE
Any way to use without admin privileges? Thank you; much appreciated

### ISSUE THREAD

**Issue by ZaighumRajput** [rubberduck-vba/Rubberduck#2086]

**Comment by retailcoder** [comment]
Do you mean *to use*, or *to install*? Because it can be *used* without admin privs with a little bit of manual registration (there's a PowerShell script for that somewhere).. but Rubberduck requires admin privs to install and register its COM type library, which enables unit testing, among other things.

**Comment by ZaighumRajput** [comment]
Thanks for the reply,
I'd be happy with just use and forego some of the more advanced features. 
Can you point me to the powershell script?

**Comment by retailcoder** [comment]
This will create the registry keys under the current user (the installer does too, but if you're not the admin then they keys aren't created for *your* user):

    Set-ExecutionPolicy -ExecutionPolicy RemoteSigned

    New-Item -Path 'HKCU:\Software\Microsoft\VBA\VBE\6.0\AddIns\Rubberduck.Extension' -Force

    New-ItemProperty -Path 'HKCU:\Software\Microsoft\VBA\VBE\6.0\AddIns\Rubberduck.Extension' -Name Description -PropertyType String -Value 'Rubberduck'

    New-ItemProperty -Path 'HKCU:\Software\Microsoft\VBA\VBE\6.0\AddIns\Rubberduck.Extension' -Name FriendlyName -PropertyType String -Value 'Rubberduck'

    New-ItemProperty -Path 'HKCU:\Software\Microsoft\VBA\VBE\6.0\AddIns\Rubberduck.Extension' -Name LoadBehavior -PropertyType DWord -Value 3

**Comment by ZaighumRajput** [comment]
Thank You!
