### ISSUE TITLE
`Esc` key doesn't close Find/Replace dialog boxes

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#2087]
Since the installation of 2.0.5 (including 2.0.6) the <kbd>Esc</kbd> key does not cancel the the Find/Replace dialog boxes.

I'm certain they have the focus, as <kbd>Tab</kbd> will move from field to field within the dialog, and it has the default blue active window title bar.

It was repro'd in chat: https://chat.stackexchange.com/rooms/14929/conversation/find-esc-repro

**Comment by comintern** [comment]
<kbd>Esc</kbd> is apparently throwing in the COM handler.  Each key-press gives:

`2016-07-21 20:40:53.6621;ERROR;Rubberduck.Common.WinAPI.RawInput;Error sizing the rawinput buffer: The handle is invalid;System.ComponentModel.Win32Exception (0x80004005): The handle is invalid`

**Comment by comintern** [comment]
@daFreeMan - Did this work _**prior to**_ 2.0.5?  Whatever the cause is, it seems unrelated to the changes in `RawInput.WndProc` since 2.0.4 (can reproduce after reverting them). Also doesn't seem to be related to Hotkey handling - the message handler (as expected) doesn't catch a WM_HOTKEY on <kbd>Esc</kbd>.

**Comment by daFreeMan** [comment]
Yes, I'm quite certain that it did. I've saved off all the installers since 2.0, so I'll uninstall/reinstall each in turn and find which one broke it.

**Comment by daFreeMan** [comment]
OK, it seems I was quite wrong. This worked fine in 1.4.3 (yes, I went that far back), and it works without RD installed at all. However, <kbd>Esc</kbd> does _not_ cancel the `Find` dialog box in 2.0 - 2.0.6. I am quite baffled by this, however, since I'm very much a keyboard guy and I'd think I'd have noticed much, much sooner if that wasn't working properly.

For testing purposes, I closed Excel, uninstalled each version, installed the next prior version, launched Excel and the VBE then tested a `Find` command. After installing and testing 2.0.3, I went into the settings and disabled all the hotkeys & reran the `Find` test with the same result. I tested older versions with the hotkeys disabled. I _did_ have Outlook (but _not_ a VBE for it) opened during this time, so if there is something that may have been held by Outlook, I'll have to re-run the tests.

**Comment by daFreeMan** [comment]
You know, I'm running, 2.0.11 now and just realized that <kbd>Esc</kbd> works just fine to cancel the Find dialog box. It seems that my favorite method of fixing things, benign neglect, has worked here, too! :)

**Comment by ThunderFrame** [comment]
Sporadically works for me in 2.0.11.

If <kbd>Ctrl</kbd>+<kbd>`</kbd> (Parse/Refresh projects) **doesn't** work , then <kbd>Esc</kbd> **does** work.

That suggests that RawInput isn't working at that point, and *that's* the reason that the Escape key is working.

If RawInput is working, I **can** escape from these dialogs (they all appear to be modal):
- Help..About dialog
- Tools..Options dialog
- Tools..References dialog
- Rubberduck..Rename dialog
- Rubberduck..Settings
- Rubberduck..Regex Assistant

But I **can't** escape from these:
- Context menus
- Standard menus
- Intellisense
- Find dialog
- Replace dialog
- Rubberduck..About (modal)
- Rubberduck..Find Symbol (modal)

I found these links which might be helpful:

[Combining Raw Input and keyboard Hook to selectively block input from multiple keyboards](https://www.codeproject.com/Articles/716591/Combining-Raw-Input-and-keyboard-Hook-to-selective)
This one seems to have an approach that might work for Visual-Studio style chords (see #866)

[Using Raw Input from C# to handle multiple keyboards](https://www.codeproject.com/Articles/17123/Using-Raw-Input-from-C-to-handle-multiple-keyboard)

[Properly handling keyboard input](https://blog.molecular-matters.com/2011/09/05/properly-handling-keyboard-input/)

[About Raw Input](https://msdn.microsoft.com/en-us/library/ms645543(v=vs.85).aspx)

**Comment by comintern** [comment]
Rubberduck..About and Rubberduck..Find Symbol don't have the `CancelButton` property set (they actually don't have buttons to set it to). Those should be easy to fix with a `ProcessCmdKey` handler.

**Comment by daFreeMan** [comment]
I've noticed that in .11 <kbd>esc</kbd> works sporadically to close the `Find` dialog. I've not done the thorough, weaponized @ThunderFrame level of testing, however.

**Comment by retailcoder** [comment]
As of 275ba27, a hidden command button enables ESC-out of the about box.
