### ISSUE TITLE
Encapsulate Field dialog box positioning is odd

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#2096]
Running a dual-monitor setup, the `Encapsulate Field` dialog box appears about as far away from where I right-clicked on the other monitor as it possible can.  i.e., with the IDE maximized on the right-hand monitor, the dialog box is _consistently_ showing up on the far left of the left-hand monitor.

It would be handy for it to either:
1. Appear where it was last located, or
2. Appear centered over the IDE's current window location.

**Comment by Vogel612** [comment]
May we assume that the left hand monitor is marked as "primary" monitor?

**Comment by Hosch250** [comment]
We do not control the positioning of this box.

**Comment by daFreeMan** [comment]
@Vogel612 no, actually, the right hand monitor is.

@Hosch250 is there no option to request the dialog to show itself centered over the application window that hosts is?

**Comment by Vogel612** [comment]
Since we do not control the positioning of this box, I think we can either close this as [status-by-design] or try to make it so that we can control where the box shows up. ...

I think the former is probably the better option...

**Comment by daFreeMan** [comment]
Somewhere along the line this seems to have been resolved.

I just tested in an Excel host with 2.0.11 running, and the encapsulate dialog popped up right on top of where I clicked.
