### ISSUE TITLE
Encapsulate Field does not respect Indention settings

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#2097]
Using the `Encapsulate Field` refactor indents 4 spaces, not what's set in the indenter settings configuration.

![rd](https://cloud.githubusercontent.com/assets/11889733/16986913/440ac414-4e57-11e6-81a2-517cf9279909.PNG)

**Comment by Hosch250** [comment]
Ah, this was written before we had the indenter completed, and doesn't use it.
