### ISSUE TITLE
Need a hotkey option for Refactor|Encapsulate Field

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#2101]
Now that I've discovered this, it really needs a hot key of its own!

**Comment by Hosch250** [comment]
Once we get two-step hotkeys working, it will get one.

**Comment by daFreeMan** [comment]
Yay!! 

What's a two-step hotkey?

**Comment by Hosch250** [comment]
Where you can use CTRL +R + R, for example.
