### ISSUE TITLE
2.0.6 Run-time error '-2146233088 in Source Control

### ISSUE THREAD

**Issue by eteichm** [rubberduck-vba/Rubberduck#2105]
When changing from branch next to branch master in Source Control, I've got Run-time error '-2146233088 (80131500)' after I got a message saying Checkout failed - 1 conflict prevents checkout. 

Error activating IInspection using binding from IInspection to method
A cyclical dependency was detected between the constructors of two services.

Activation path:
  4) Injection of dependency IInspection into parameter inspections of constructor of type ConfigurationLoader
  3) Injection of dependency ConfigurationLoader into parameter configLoader of constructor of type FolderHelper
  2) Injection of dependency FolderHelper into parameter folderHelper of constructor of type CodeExplorerViewModel
  1) Request for CodeExplorerViewModel

Suggestions:
  1) Ensure that you have not declared a dependency for IInspection on any implementations of the service.
  2) Consider combining the services into a single one to remove the cycle.
  3) Use property injection instead of constructor injection, and implement IInitializable
     if you need initialization logic to be run after property values have been injected.

**Comment by eteichm** [comment]
I also had a (maybe related) pop-up window saying "A source file was modified out of the editor; should Rubberduck reload it?" 
I only say it after acknowledging the Run-time error '-2146233088 (80131500)'.

**Comment by comintern** [comment]
The source file modified popup isn't related to the error. This is the same issue as #2099.

**Comment by eteichm** [comment]
Yes similar issue as #2099.
Here it seems to be caused by the fact that I didn't commit the changes before changing to the other branch.  Hence, the Checkout failed - 1 conflict prevents checkout. 
After committing the changes before changing to the other branch, RD does no more produce the error.
