### ISSUE TITLE
Hidden pop-up window Source file modified

### ISSUE THREAD

**Issue by eteichm** [rubberduck-vba/Rubberduck#2110]
I got twice a pop-up window saying "A source file was modified out of the editor; should Rubberduck reload it?" 
The issue is that the first one is hidden instead of on top of the Source Control window.

**Comment by Hosch250** [comment]
We can't really fix that, unfortunately, without making it always stay on top of all windows.  Windows chooses where this is in the layers.

**Comment by eteichm** [comment]
Well noted. Indeed unfortunate. 
Let's warn the users who need to set the VB_PredeclaredId attribute to True in an external editor.

**Comment by retailcoder** [comment]
@eteichm  hopefully Rubberduck will have a tool to modify module and member attributes without needing to do it outside the VBE :-)

**Comment by eteichm** [comment]
@retailcoder great idea.  In the mean time, I'll continue using VbaDeveloper+ SourceTree [http://www.atlassian.com/software/sourcetree/overview](url) and TortoiseGit [https://tortoisegit.org](url).

**Comment by Hosch250** [comment]
This only shows up (well, *should* only show up) if you modify the file externally from the VBE.  After you set that attribute, you shouldn't have any problems as long as you do all your changes directly in the VBE.
