### ISSUE TITLE
2.0.7 Parser Error using Excel 2010: Function with parameters and Missing Rubberduck in VBE

### ISSUE THREAD

**Issue by PeterMTaylor** [rubberduck-vba/Rubberduck#2128]
New Parser error with Code Inspection using Excel 2010 with different parameters.

Please note it's a function this time not a sub. When the message advises missing 'End Sub' which I believe implies module only.

Does RD need to honor functions with different parameters as well as modules as I recall @retailcoder indicated that may be not the case.

![capture 2 0 7 parser error](https://cloud.githubusercontent.com/assets/2254567/17081155/824597fe-5190-11e6-8dc8-7bfc2039feb0.PNG)

Kind regards. Peter.

**Comment by retailcoder** [comment]
@Hosch250 did procedures' AsTypeClause just break??

**Comment by Hosch250** [comment]
I didn't touch the parser in the last several releases.  Want to share an MVCE?

**Comment by retailcoder** [comment]
Does this reproduce it?

    Public Function Foo() As VBA.Collection
    End Function

**Comment by PeterMTaylor** [comment]
Will check. give me a moment.

**Comment by PeterMTaylor** [comment]
Ok, I have to ask... What's going on!

**Comment by PeterMTaylor** [comment]
I selected a class at random, put the Function Foo() as VBA.Collection function in.
Then discovered that Rubberduck in the Add-in disappears completely. Checking the Windows installation, its still there thus deduced that something removed Rubberduck from system. Not sure how.

**Comment by PeterMTaylor** [comment]
I have decided to try again after re-installing 2.0.7. I will check if I suspect Bruce McPherson's framework done something when triggered by VBA.Collection.

**Comment by PeterMTaylor** [comment]
Interesting! I had to kill the Excel processor that was still in memory when there is no Excel workbook about 37% memory running.

**Comment by PeterMTaylor** [comment]
I haven't worked out how to repro that Rubberduck disappears again.
However, to answer @retailcoder question, the Foo function works ok each time.

**Comment by daFreeMan** [comment]
The RD add-in not being visible in the menu, and Excel continuing to run after the program has been closed are known issues not yet resolved. 

Temporary workaround:
If you launch Excel and RD is not in the VBE menu, close Excel, then kill the Excel process that's still running. Relaunch Excel & RD will be there

**Comment by Vogel612** [comment]
May I assume that this can be closed as a norepro?

**Comment by retailcoder** [comment]
yeah
