### ISSUE TITLE
RD had an error, #3

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#2131]
Installed 2.0.7 this morning. Have received several "RD has had an error" messages.

[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/382272/RubberduckLog.txt)

**Comment by Hosch250** [comment]
The elusive Rename bug.  Can you share the project you got this on?

**Comment by daFreeMan** [comment]
For posterity:  I'm close to being able to clean up the workbook to eliminate client-specific info from it. I hope to start that tomorrow or Wed.

**Comment by Vogel612** [comment]
is this still relevant to 2.0.8?

**Comment by daFreeMan** [comment]
Holy carp, Batfish! This has been sitting for a while... I've been so swamped with other stuff, I haven't had a chance to look at it.

**Comment by retailcoder** [comment]
deemed a duplicate of #2098
