### ISSUE TITLE
Excel continues to run after shutdown

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#2132]
Excel crashed & restarted itself. I saved the file that it recovered then closed Excel. (2.0.7 installed this morning)

I restarted Excel (by double clicking the XLSM), launched the VBE and it opened _without_ the RD menu. I closed Excel, looked at Task Manager, and there was still an Excel instance with about 500MB of memory allocated.

I've had Excel remain running with the "ghost" project several times today. What information can I provide to help track this down? Other than the last line of the log indicating `Inspections loaded in 119958ms;` (which is a _lot_ of milliseconds), there doesn't appear to be anything of interest in there (to my untrained eye).

**Comment by Hosch250** [comment]
This isn't quite a "ghost project" issue if the projects are gone from the project explorer when you close them.  This is just our friend the memory leak, how I'd love to get my fingers on him.

**Comment by Hosch250** [comment]
See https://github.com/rubberduck-vba/Rubberduck/issues/1438
