### ISSUE TITLE
Code Inspection - False Positive: replace function with existing typed function

### ISSUE THREAD

**Issue by Stevefb** [rubberduck-vba/Rubberduck#2136]
Code inspection false positive if the function `Left(string, num)` like this `VBA.Left(string, num)`   (might apply to other functions, not tested)

RD 2.0.7.35311

**Comment by retailcoder** [comment]
As it stands, this looks completely by design. The inspection means to say you could be using `Left$` (or `VBA.Left$`) instead. Can you clarify?

**Comment by retailcoder** [comment]
Wait a minute, what is `VBA.Left` actually? The string function would be under the `VBA.Strings` module...

**Comment by Stevefb** [comment]
@retailcoder my quick check of vba.Le.... and vba.strings.Le....  seem to provide the same options for function selection.  I guess I was using some sort of shortcut w/o knowing.... perhaps there should be 2 suggestions pertaining to that line of code:

1. Use the typed function
2. Use the fully qualified context

I didn't understand the explanation for this issue, not clear to me that a $ makes all the difference... but yes happy to clarify that would be the appropriate solution for me.

**Comment by retailcoder** [comment]
Fixed
