### ISSUE TITLE
Code Inspection - False Positive (probably unique to MS Word)

### ISSUE THREAD

**Issue by Stevefb** [rubberduck-vba/Rubberduck#2137]
MS-Word content controls have a property called placeholder text which can be set to "" but not vbNullString

RD Code Inspection detects "" in: 
`oCCtemp.SetPlaceholderText Text:=""`
and suggests changing to vbNullString, however (in my experience) following this suggestion will crash word.

**Comment by retailcoder** [comment]
Can you include a bit of code to reproduce the issue, I'm not very familiar with the MS-Word object model. Thanks!

**Comment by Hosch250** [comment]
This will be pretty tricky to fix because we just detect string literals in the parse tree.

**Comment by retailcoder** [comment]
Adding [wiki] and [support] tags to make this issue easier to search, but closing as "won't-fix" / "declined".

Specific problematic occurrences of inspection results can be disabled with an `@Ignore` annotation (using the "ignore once" quick-fix).
