### ISSUE TITLE
RD had an error when attempting to Encapsulate a property that already had Get/Let

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#2138]
I was curious what would happen if I attempted to `Refactor|Encapsulate` a private variable in my class when it already had a `Get`/`Let` pair.

In the UI, `Let` was checked, but both `Let` and `Set` were disabled. The procedure name was properly set for the existing getter/letter, not the name of the variable I'd had selected.

I clicked `OK` and the "I had an error" dialog popped up.

[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/383973/RubberduckLog.txt)

**Comment by retailcoder** [comment]
*Encapsulate Field* shouldn't be allowed to run on a private field. This is a bug.

**Comment by daFreeMan** [comment]
OK, my terminology is wrong.

I had this:

```
Private pPageNumber As Long

Public Property Get PageNumber() As Long
  PageNumber = pPageNumber
End Property
Public Property Let PageNumber(ByVal value As Long)
  pPageNumber = value
End Property
```
then placed the cursor on the `Private pPageNumber...` declaration and reran `Encapsulate`.

**Comment by retailcoder** [comment]
Perhaps the command's `CanExecute` should also verify that a public field is not referenced in a `Public` (implicit or explicit) or `Friend Property`, too?

**Comment by comintern** [comment]
I'm not sure I'd go that far, because public fields can be used in other properties - consider this case:

```vb
Public pPageNumber As Long

Public Property Get NextPageNumber() As Long
  NextPageNumber = pPageNumber + 1
End Property
```

RD shouldn't prevent you from Encapsulating.  In fact, it only throws the error when the _name_  you select is the same as an existing property.  It allows repeatedly "re-encapsulating" with different names in a broken way.  Starting with this...

```vb
Public pPageNumber As Long

Public Property Get PageNumber() As Long
  PageNumber = pPageNumber
End Property
Public Property Let PageNumber(ByVal value As Long)
  pPageNumber = value
End Property
```
...run Encapsulate field on `pPageNumber` and name it Foobar. You end up with this:

```vb
Private pPageNumber As Long

Public Property Get Foobar() As Long
    Foobar = pPageNumber
End Property

Public Property Let Foobar(ByVal value As Long)
    pPageNumber = value
End Property

Public Property Get PageNumber() As Long
  PageNumber = Foobar
End Property
Public Property Let PageNumber(ByVal value As Long)
  Foobar = value
End Property
```

**Comment by daFreeMan** [comment]
@comintern "In fact, it only throws the error when the name you select is the same as an existing property." <<This is the problem.

When I brought up the Encapsulate UI, it had `PageNumber` in the "Property Name" entry box.

I hit Enter, RD went Boom

**Comment by Hosch250** [comment]
I'll give it a list of invalid names from members at that scope.
