### ISSUE TITLE
Extract Method should be disabled for property declaration lines.

### ISSUE THREAD

**Issue by comintern** [rubberduck-vba/Rubberduck#2139]
I was messing around with the code in #2138 and found this.

Drop this in a class:

``` vb
Private pPageNumber As Long

Public Property Get PageNumber() As Long
  PageNumber = pPageNumber
End Property
Public Property Let PageNumber(ByVal value As Long)
  pPageNumber = value
End Property
```

Put the cursor on PageNumber in the Get.  Extract Method is enabled.  Running it gives this...

``` vb
Private pPageNumber As Long

NewMethod
  PageNumber = pPageNumber
End Property
Private Sub NewMethod()
Public Property Get PageNumber() As Long
End Sub
Public Property Let PageNumber(ByVal value As Long)
  pPageNumber = value
End Property
```

...followed by the obvious parse error.

**Comment by grleachman** [comment]
I'd assign it to me, but I can't

**Comment by retailcoder** [comment]
@grleachman your wish is my command! ;-)

**Comment by grleachman** [comment]
Looks like a bit of fun. Get, Set and Let properties aren't handled as contexts in the code. However annoyingly the condition to determine if the selection is Valid should return false if the method is not within a functionStmtContext or subStmtContext.

In any event, it would be nice if one could extract a method from a property.

The future is a shiny cucumber

**Comment by Vogel612** [comment]
Since the Extract Method refactoring is in dire need of a rewrite from scratch, all [bug] issues pertaining to it, are in the process of becoming irrelevant. Closing.
