### ISSUE TITLE
Inversion of Control

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#214]
We're already writing out code *in that direction*: we're constructor-injecting dependencies, and we code against interfaces or abstract classes.

Let's leave *poor man's DI* behind, and go with a full-blown IoC container. I love using NInject for that; it isn't the top-performing out there, but it has a very nice API that sets it apart from all others.

Thoughts?

**Comment by ckuhn203** [comment]
No issues here except it's a new framework to learn for me. There will be a curve...

**Comment by ckuhn203** [comment]
Duplicate of #606 The Big Refactoring
