### ISSUE TITLE
Source Control not committing all changes in one go.

### ISSUE THREAD

**Issue by Zak-Michael-Armstrong** [rubberduck-vba/Rubberduck#2144]
**Sequence of events:**

[Made Initial Commit]

[Made Changes]:
    Changed code in 3 already-committed Modules
    Imported 1 new Module
    Changed codenames on 2 worksheets

[Clicked Refresh]
[Clicked Commit]:
    Committed one re-named codename
    Committed changes to 2 modules

[Clicked Refresh]
[Clicked Commit]:
    Committed the other re-named codename

[Clicked Refresh]
[Clicked Commit]:
    Committed changes to the 3rd module.

The module I imported successfully appeared under "Untracked files"

**Comment by Hosch250** [comment]
I assume all the changes were listed as tracked?  Untracked changes are not committed.

**Comment by Zak-Michael-Armstrong** [comment]
Sorry, don't know. Would explain the sequence of events though.

**Comment by Vogel612** [comment]
@Zak-Michael-Armstrong so .. what's the status?
