### ISSUE TITLE
Runtime error 80004003 opening a file in Excel

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#2145]
I had an XLSM open in Excel. I opened an XLSX and got:

![rd](https://cloud.githubusercontent.com/assets/11889733/17148757/5cba6800-5336-11e6-8248-97d2f0edc52c.PNG)

Object reference not set to an instance of an object.

[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/384418/RubberduckLog.txt)

**Comment by Vogel612** [comment]
The RubberduckLog doesn't even mention "Exception". This appears to happen outside of Rubberduck's control :disappointed_relieved:

**Comment by retailcoder** [comment]
Doesn't look like an error that's displayed by VBA code with a `MsgBox` though. Not sure what that is...  RD logs would have an exception if there was one, but this error seems to be strictly on the COM side of things. Not sure what RD can do here.
