### ISSUE TITLE
Indenter sample in settings should have height scale with window.

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#2155]
Look at the default Settings window size on a 1080p monitor
![settings1](https://cloud.githubusercontent.com/assets/16574009/17212955/56fc1838-5515-11e6-96c7-5318ecf61c7d.png)

Look at the same window expanded in height to nearly 1080px. Notice the indenter sample procedure text is not scaling, and not relative to the setting-controls at the top.
![settings2](https://cloud.githubusercontent.com/assets/16574009/17212959/5abbc59a-5515-11e6-9d28-4e3dc6042cea.png)

**Comment by retailcoder** [comment]
Hmm you're supposed to drag the splitter up to make the indenter preview box taller... I guess it could be automated somehow with some anchoring.

**Comment by daFreeMan** [comment]
TBH, the splitter isn't really that obvious.

**Comment by retailcoder** [comment]
Settings UI was redesigned.
