### ISSUE TITLE
COM Interop error on VBE launch

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#2156]
After a fresh rebuild of my machine (using the corporate image of Win7x64), I'm getting a COM Interop error when launching the VBE from Excel:
![rd](https://cloud.githubusercontent.com/assets/11889733/17217093/2b1fc426-54b1-11e6-84b2-81c159c06ee9.PNG)
After clicking the `OK` button, the VBE does launch, and I get this:
![rd1](https://cloud.githubusercontent.com/assets/11889733/17217171/69ebd8c0-54b1-11e6-8441-959cfce62dde.PNG)
Note that the RD menu is missing, and that RD has _not_ launched its initial parse of the project.
I can, however, click on the space where the menu is supposed to be and get to the _secret_ RD functionality. (Note, _all_ menu options are available, even though the project hasn't been parsed yet)
![rd2](https://cloud.githubusercontent.com/assets/11889733/17217253/af5c110e-54b1-11e6-8fbc-9a97d44be3aa.PNG)
I can manually initiate a parse, and it runs to completion, but the menu still doesn't appear:
![rd3](https://cloud.githubusercontent.com/assets/11889733/17217305/dd8e37fa-54b1-11e6-8ee7-181dcee881b0.PNG)
Note, though, that the parse is complete, and the menus are now functioning correctly, except that they're still _secret_:
![rd4](https://cloud.githubusercontent.com/assets/11889733/17217356/1603d2d4-54b2-11e6-9be2-067386112e48.PNG)
Finally, after opening the secret RD menu, going to `Settings`, then clicking `OK` (without having made any settings changes), the RD menu appears:
![rd5](https://cloud.githubusercontent.com/assets/11889733/17217422/517d50a6-54b2-11e6-8d38-fb5d3c85d098.PNG)

**Comment by Hosch250** [comment]
This is a failed launch, and if @retailcoder reviews and approves one of my PR's, RD will unload itself when catches the exception causing this.

**Comment by daFreeMan** [comment]
After installing all the "important" updates for my freshly minted Win7 system and rebooting overnight, this seems to have been resolved.

I opened Excel this morning, launched the VBE, RD parsed the project, the RD menu is in the menu bar & there are no _secret_ menus any more.

Long story short, if you have a fresh build, install _all_ Windows updates before complaining about RD being broken.
