### ISSUE TITLE
2.0.7 Uninstall Failed

### ISSUE THREAD

**Issue by ccampbellclearesult** [rubberduck-vba/Rubberduck#2169]
Hi Rubberduck,

Great project! I'm looking to uninstall the Add-In because I'm trying different Add-Ins and I'm new to Access/VBA.

When uninstalling, a MsgBox popped up with "Some components could not be removed. They can be removed manually."

When opening Access/VBA post-uninstall RubberDuck is still installed and active.

I noticed the DLLs in ProgramData/RubberDuck but I am thinking that there may be some registration process going on and simply removing them may cause more issues.

How can I go about removing RubberDuck?

Thank you!

**Comment by ccampbellclearesult** [comment]
I opened Access/VBA a second time and the Add-In is now no longer active...sorry! Thank you! Please leave a comment if you think I should perform any other actions.

**Comment by Hosch250** [comment]
Just to make sure everything is gone, you could search for all the values containing "Rubberduck" in your registry.
