### ISSUE TITLE
False Inspection when procedure scoped variable name matches class member name

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#2171]
This is a resolver issue that is exposed as a false positive inspection result for _Return Value for member 'x' is never assigned_.

The following code produces 2 false-positive inspection results:
- Return value for member 'Foo' is never assigned
- Return value for member 'Bar' is never assigned
- Return value for member 'Fizz' is never assigned

If you rename the variables in `Fizz`, so they don't match the names of the properties, then the inspections are not present.

``` vb
Option Explicit

Public Property Get Foo() As Long
  Foo = 5
End Property

Public Property Get Bar() As Long
  Bar = 6
End Property

Public Function Fizz() As Long
  Fizz = 2
End Function

Public Sub Buzz()
  Dim Foo As Long
  Dim Bar As Long
  Dim Fizz As Long

  Foo = 7
  Bar = 8
  Fizz = 9

  Debug.Print Foo, Bar, Fizz '7 8 9
End Sub

```

**Comment by ThunderFrame** [comment]
more explicit resolution:

```vb
Option Explicit

Public Property Get Foo() As String
  'Rubberduck thinks Foo is a Long Variable
  Foo = 5
End Property

Public Property Get Bar() As String
  'Rubberduck thinks Bar is a Long Variable
  Bar = 6
End Property

Public Function Fizz() As String
  'Rubberduck thinks Fizz is a Long Variable
  Fizz = 2
End Function

Public Sub Buzz()
  Dim Foo As Long
  Dim Bar As Long
  Dim Fizz As Long
  
  Foo = 7
  Bar = 8
  Fizz = 9
  
  Debug.Print Foo, Bar, Fizz '7 8 9
End Sub

```

**Comment by retailcoder** [comment]
OMG this bug has been bugging me forever and *just now* I see how it's happening! Good job with this mcve!

**Comment by retailcoder** [comment]
no repro with 2.1.2020, probably resolved well before that.
