### ISSUE TITLE
2.0.8 Source Control causes Out of Memory or a Crash

### ISSUE THREAD

**Issue by ccampbellclearesult** [rubberduck-vba/Rubberduck#2172]
Hi, I'd like to help provide debug information on this issue. When I try to use source control with 2.0.8 I get either Out of Memory or a Crash. For the OOM I'm not sure what my usage was at but for the crash the process (MSAccess 32-bit) held ~790mb.

What information can I provide you?

This occurs upon Initializing a New Repo.

**Comment by ccampbellclearesult** [comment]
Hi RD, is there any information I can provide you with to help debug this issue?

**Comment by daFreeMan** [comment]
You can post your `RubberduckLog.txt` located in `%AppData%\Rubberduck\logs`. (There's also an option within the VBE Rubberduck menu to open the log directory for you.)

Also, check the event log and post any messages there about the crash. You can export the events and post the results, or just copy the detail text and paste it in. Be sure to wrap any really long text with `~~~` on a line of its own at the beginning and end of the text - that will help make it more readable.

**Comment by ccampbellclearesult** [comment]
I will try to get to this today

**Comment by rubberduck203** [comment]
We’ve removed the source control feature. Please see #3758.
