### ISSUE TITLE
Shift+F2 / “Last Position”

### ISSUE THREAD

**Issue by eteichm** [rubberduck-vba/Rubberduck#2174]
There is an error in https://rubberduckvba.wordpress.com/2016/05/04/vba-rubberducking-part-1/ 
Shift+F2 / “Last Position” must be: Control-Shift+F2 / “Last Position” 
at least in Microsoft Visual Basic for Applications 7.0 (the version I'm using)

**Comment by eteichm** [comment]
BTW thanks for the tutorial :-)

**Comment by retailcoder** [comment]
Thanks, fixed!
