### ISSUE TITLE
With RD 2.0.8, I cannot move the execution point in my code.

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#2176]
Normally, when debugging in the VBE, one can drag the yellow arrow to a new line of code to change the current execution point. I've noticed, however, since the installation of 2.0.8 that I can no longer do this. (It may have broken in earlier versions, I've not tested yet, and hadn't needed to move execution point for a while.)

![rd](https://cloud.githubusercontent.com/assets/11889733/17380857/21912716-5997-11e6-9e5c-19c69306f5ca.PNG) 
<sup>Sadly, _Snipping Tool_ will not let me get a screen shot with the cursor changed, but it does change.</sup>

When I hover the cursor over the yellow arrow, the cursor changes to the black arrow outline with the up/down arrows indicating that I should be able to drag it. However, when I click on it to begin dragging, I get a break point set immediately, no matter how long I hold the button down for. Click-dragging again results in the break point clearing, but no movement of the execution point.

**Comment by retailcoder** [comment]
Doesn't look like a RD isssue. Does the context menu's *set next statement* work?

**Comment by daFreeMan** [comment]
Interesting. Even with the latest (as of today) Office updates installed, this still isn't working on my machine. It does, however, not appear to be RD's fault.
