### ISSUE TITLE
Crashes Excel.exe on start up of VBA Editor

### ISSUE THREAD

**Issue by oberoc** [rubberduck-vba/Rubberduck#2177]
I have installed RD 2.0.8-rc and installed without an issue. I fired up Excel and attempt to open up the VBA Editor and almost immediately, I get this screen. I do have .net 4.5 installed. How do I go about debug this?
![excel-vba-crashing](https://cloud.githubusercontent.com/assets/2159980/17450962/5213b6f6-5b31-11e6-940e-1f56c1f3f817.jpg)

**Comment by yw5aj** [comment]
+1 - same here. Win 10 with the system anniversary update.

**Comment by retailcoder** [comment]
Same here, Win7 but not on startup, just right in the middle of browsing some code. This is not cool.

**Comment by JGBastiat** [comment]
Same here. Tried on two Windows 10 laptop, Excel 64-bit. One is a fresh install of windows.

**Comment by Talorthain** [comment]
Hi,
 Just wanted to see how it was progressing, so installed 2.0.8. I have the same issue.
Win 10 pro
Excel 2016 32bit
24gb memory
![runtimeerror](https://cloud.githubusercontent.com/assets/6796503/18027000/4917515a-6c4f-11e6-878d-39033230c812.PNG)

**Comment by Vogel612** [comment]
I'm not able to reproduce this when starting up in Access, so this seems to be an Excel-Only thing. Are there other Hosts that exhibit the same problem?

**Comment by ThunderFrame** [comment]
I'm running from *Next* (not from 2.0.8), and I'm **unable to reproduce** using Excel 2016 32-bit on Windows 10 pro 64-bit with Anniversary update.

**Comment by opticyclic** [comment]
I can reproduce with 
Rubberduck 2.0.8
Windows 7 Enterprise 64bit
Excel 20120 Professional Plus 32bit

As soon as I click the Rubberduck menu and hover over different sub-menus looking for the Code Explorer it crashes Excel.
I don't get a crash log either.

I can reproduce with 2.0.7 but not 2.0.6.

**Comment by retailcoder** [comment]
@opticyclic is it *systematic* or intermittent/random? I'm on Win7 Professional SP1 x64 + Excel 2010 Professional 32-bit with 2.0.8 at work... and I have no repro - I *do* get occasional unexplained crashes though. There *were* a number of "fixes" between 2.0.6 and 2.0.8 involving COM interactions... that's *the* reason 2.0 isn't deemed completely stable yet :smiley:

**Comment by retailcoder** [comment]
There was an unhandled `NullReferenceException` bubbling up all the way through the call stack when loading the configuration settings and the new `WhitelistedIdentifiers` setting was missing - that explains how the crash occurred at startup and how it couldn't be reproduced consistently by everyone in this thread. I'm pretty sure @kerzhaw's PR closes this issue.

**Comment by Feby0900** [comment]
The same thing happens to me. Running Win 10 pro Excel 2016 64 bit.
It doesn't display any  message though, it just closes.

**Comment by comintern** [comment]
@Feby0900 This issue is fairly old (and closed).  What version of Rubberduck are you running?  Are you getting a log file in %AppData%\Roaming\Rubberduck\Logs?
