### ISSUE TITLE
Create automated integration tests for Source Control

### ISSUE THREAD

**Issue by rubberduck203** [rubberduck-vba/Rubberduck#218]
Just because there are dependencies doesn't mean things shouldn't be automatically tested.
They just shouldn't be run along with the unit tests (nor as frequently).

Automate integration tests for Source control.

**Comment by ckuhn203** [comment]
I just can't get this to work. Each individual test works, but running them in tandem causes file lock problems. Not sure how to get around it. Committed what I have done (commented out) and moving on for now.

**Comment by ckuhn203** [comment]
Take a look at how LibGit2Sharp did their tests. It may provide inspiration.

**Comment by rubberduck203** [comment]
#3758
