### ISSUE TITLE
Extract Interface => line with Option Explicit added twice

### ISSUE THREAD

**Issue by eteichm** [rubberduck-vba/Rubberduck#2180]
When "Require Variable Declaration" is set in Tools > Options > Code Settings, VBE adds Option Explicit as
first line when inserting a new module. 
When Rubberduck 2.0.8 performs Extract Interface, the line with Option Explicit gets added twice: at the beginning and at the end of the new class module containing the extracted interface. 
I suggest the following fix: disable the option "Require Variable Declaration" before performing Extract Interface and set it back to its original value thereafter.

**Comment by retailcoder** [comment]
Actually, best would be to only add the `Option Explicit` line *if it's not already present*. The VBE settings dialog isn't easily accessible, unfortunately.
