### ISSUE TITLE
Access crash on compact and repair with RD 2.0.8

### ISSUE THREAD

**Issue by peterennis** [rubberduck-vba/Rubberduck#2181]
Log
[RubberduckLog.zip](https://github.com/rubberduck-vba/Rubberduck/files/412544/RubberduckLog.zip)

**Comment by Vogel612** [comment]
This could use some proper instructions to reproduce. Note that the Log only contains significant amounts of Resolver Errors and some ParserErrors with the fast parser mode. None of these persisted through fallback into the slower parsing mode, so there's that ...

**Comment by Vogel612** [comment]
Inactive since over a year. Additionally repro steps are unclear. Closing as Inactive
