### ISSUE TITLE
Extract Interface adds Implements statement even when it's already there

### ISSUE THREAD

**Issue by eteichm** [rubberduck-vba/Rubberduck#2182]
When Rubberduck 2.0.8 performs Extract Interface, it adds the line "Implements IClassname" even though it is already present.  I don't know whether Visual Basic accepts multiple such lines when implementing more than one interface.
I suggest to not add the line "Implements IClassname" _if it's already present._

**Comment by retailcoder** [comment]
To be fair if you're extracting an interface, from a class, the class can't already be legally implementing the extracted interface. This is an edge case.

**Comment by Vogel612** [comment]
FWIW Rubberduck should not enable "Extract Interface" when the current Class already does implement an interface IIUC. Instead there should be options to "Pull Up / Push Down Member"

**Comment by retailcoder** [comment]
@Vogel612 counterpoint:

```vb
Option Explicit
Implements ISomething

Public Sub Foo() 'TODO extract to IFoo
Ebd Sub

Public Sub Bar() 'TODO extract to IBar
End Sub

Private Sub ISomething_DoSomething()
End Sub
```
