### ISSUE TITLE
Option Compare Binary is redundant

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#2186]
Let's make an inspection that pops a `Hint`-level result when a module contains `Option Compare Binary`, which is the default and doesn't need to be specified.

**Comment by shadowofsilicon** [comment]
Is there a known way that the default be overriden? Say, project-wide?

Consider case:
1) Default is set project-wide to Option Compare Text
2) A module is set with `Option Compare Binary`

**Comment by retailcoder** [comment]
@shadowofsilicon nope. Even in MS-Access the default is an implicit `Option Compare Binary`, overridden by an explicit `Option Compare Database` that Access adds to all modules. If a project-wide default exists, it's implemented with explicit `Option Compare` statements; the `Option Compare Binary` default is apparently built into the VBA runtime.

**Comment by shadowofsilicon** [comment]
So, there is never a use case where an explicit `Option Compare Binary` is desired?

**Comment by retailcoder** [comment]
@shadowofsilicon not any that I can think of.

**Comment by ThunderFrame** [comment]
See https://stackoverflow.com/a/42102568/5757159

**Comment by retailcoder** [comment]
Already covered by `RedundantOptionInspection` ..sorry
