### ISSUE TITLE
Code Inspection: Prefer `Me` over class name when used within predeclared components

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#2188]
VBA creates a default predeclared instance of UserForms and document-type components such as Access Forms and Reports, and Excel's Workbook and Sheet objects, and class modules can also be predeclared using the VB attribute syntax.

It is generally OK for code that is _outside_ the predeclared instance to refer to the predeclared instance by name, for example:

``` vb
  'Referencing Sheet1 from any other module than Sheet1
  Sheet1.Name = "foo"

  'Show the default instance of the UserForm
  UserForm1.Show
```

But code _within_ the instance's class should _typically_ refer to itself as `Me`, for example

``` vb
    'Set the caption for THIS instance of the form
    Me.Caption = "foo"
```

There are however, some scenarios where you might want to refer to the default instance by name. IMHO, these usages should be inspection warnings

``` vb
    'Set the caption of the default instance to the caption of this instance
    UserForm1.Caption = Me.Caption
```

**Comment by retailcoder** [comment]
Ooh that's a very much excellent one! Code breaks if the form was instantiated as an object!

**Comment by retailcoder** [comment]
Tweaking the default instance from any instance *should* trigger an inspection result - *setting the caption of the default instance to the caption of this instance* seems weird enough to warrant considering other approaches, and/or add some `@Ignore DefaultInstanceReference` annotation.

The inspection should yield a result for each reference to the default instance of a given class (class module or user form) - IMO worksheets are different, one doesn't *create an instance* of a worksheet; and document modules are somewhat special anyway.

So, given `Class1` where `VB_PredeclaredId = True`, any reference to `Class1` within `Class1` should trigger a result; same for `UserForm1`; any reference to `UserForm1` within `UserForm1` should trigger a result.

**Comment by ThunderFrame** [comment]
Indeed, synchronizing the form captions is probably a weird thing to do, but these are more realistic scenarios:

```vb
'Check if this instance is not the default instance
If Not UserForm1 Is Me

    'Keep the forms top-aligned
    Me.Top = UserForm1.Top

End If
```

![190x70](https://cloud.githubusercontent.com/assets/16574009/17711465/1712738c-6435-11e6-88cc-90f2371039ac.jpg)

I agree that one does not create instances of Workbook/Worksheet components, but one *does* create instances of Access Forms and Reports, 

![190yjw](https://cloud.githubusercontent.com/assets/16574009/17712006/7d232764-6437-11e6-9984-374c9228da07.jpg)

So *some* document-type components can be instanced.

![190xju](https://cloud.githubusercontent.com/assets/16574009/17711535/709dc32a-6435-11e6-9946-aff91616d8a8.jpg)

IMHO, Workbooks and Worksheets should contain very little code other than event handlers and public properties and methods. The event handlers *should* be passing complex operations to procedures in standard modules or to class instances, so if a reference to a worksheet needs to be passed by the worksheet, it should refer to itself as Me. At the very least, it helps when renaming the worksheet's codename.

For example:
This code is in a standard module
```vb
Public Sub DoSomething(ActivatedObject As Object)
  Debug.Print ActivatedObject.Name
End Sub
```
This code is an event handler for a worksheet
```vb
Private Sub Worksheet_Activate()
  DoSomething Me      'Prefer this paramater syntax
  DoSomething Sheet1
End Sub
```

**Comment by retailcoder** [comment]
Right. But I'd like to avoid host-specific inspection code for inspections that aren't inherently host-specific (e.g. like `ImplicitActiveSheetReference` inspection is specific to Excel hosts), and Access forms and reports are just regular class modules as far as RD can see - so there's always the *ignore once* option for the very rare cases where it *does* make sense to use the default instance inside the class' code-behind.
