### ISSUE TITLE
Should the Code Inspection Setting Grouping sort order and Code Inspection "By Inspection Type" window sort order be the same if not sortable?

### ISSUE THREAD

**Issue by connerk** [rubberduck-vba/Rubberduck#2193]
Build 2.0.8.23905 (MSIL)

![image](https://cloud.githubusercontent.com/assets/1771679/17755916/a4033f90-6491-11e6-96c6-c2e75f3bda7d.png)

**Comment by retailcoder** [comment]
Hmm that's a nice UX issue, should be an easy fix - thanks for bringing it up!

**Comment by connerk** [comment]
I'll give this a shot. Seems like a good entry point. :)

**Comment by retailcoder** [comment]
@connerk cool! don't hesitate to ask if you have any questions!
