### ISSUE TITLE
Source Control Window will not scroll over boxes

### ISSUE THREAD

**Issue by Zak-Michael-Armstrong** [rubberduck-vba/Rubberduck#2198]
RD Version: 2.0.8-rc

In the Source Control window, when scrolling using the scroll wheel, the window stops scrolling as soon as the cursor is hovering over the indicated areas:

![rd source control scrolling bug - changes window](https://cloud.githubusercontent.com/assets/13286014/17970573/290d3f9a-6acf-11e6-966b-f0865afb0c2d.png)
![rd source control scrolling bug - branches window](https://cloud.githubusercontent.com/assets/13286014/17970571/29046fdc-6acf-11e6-8c6f-d35650b51e0e.png)
![rd source control scrolling bug - unsynced commits window](https://cloud.githubusercontent.com/assets/13286014/17970572/290530a2-6acf-11e6-8aa6-6968876d2a1b.png)

This only affects the scroll wheel. Scrolling via <kbd>↑</kbd> or <kbd>↓</kbd> or <kbd>Page Up</kbd> or <kbd>Page Down</kbd> works as expected.

Whether scrolling should work when hovering over the tabs bar is possibly a design choice rather than a bug, so it's included here just for completeness.

**Comment by Hosch250** [comment]
Sorry, I've known about this since I designed it, and have been completely unable to fix this.  It also affects the hotkey box in the settings, and perhaps a couple other things--I don't have Rubberduck installed ATM.
