### ISSUE TITLE
RD 2.0.8 crash log file

### ISSUE THREAD

**Issue by eteichm** [rubberduck-vba/Rubberduck#2201]
RD 2.0.8 crashed while I was saving an Excel 2003 workbook (_.xls) containing macros as an Excel macro-enabled workbook (_.xlsm).  Here is the log file.
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/444654/RubberduckLog.txt)

**Comment by Vogel612** [comment]
There's a handful of parser errors and a few resolver errors in the log, but it looks clear near the end... 

This basically could be everything and it's unlikely to be fixable without more information :cry:
