### ISSUE TITLE
Extraneous parentheses forcing ByVal arguments trip a parser error

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#2206]
ref.#2205

Grammar bug; the argument_list needs to allow parens around individual args.

**Comment by retailcoder** [comment]
This is proving to be much harder than I anticipated.

I have a failing test using this code:

    Sub Test()
        DoSomething (foo), (bar)
    End Sub

From the failing test's stack trace, the parser correctly identifies a `callStmt`, then an `expression`, and then a `lExpression`, and parsing fails at the comma.

The `lExpresion` rule has higher precedence than the `parenthesizedExpr` that it should be matching, however moving `lExpr` anywhere below `parenthesizedExpr` completely wrecks the entire parser for some reason.

So I tried tweaking the `argumentExpression` rule, but no luck:

    argumentExpression :
        (BYVAL whiteSpace)? expression
        | addressOfExpression
        // Special case for redim statements. The resolver doesn't have to deal with this because it is "picked apart" in the redim statement.
        | lowerBoundArgumentExpression whiteSpace TO whiteSpace upperBoundArgumentExpression
    ;

Here I tried adding an alternative involving `LPAREN+ expression RPAREN+`; I also tried a recursive `byvalArgumentExpression`, no luck either.

I'm out of ideas.

**Comment by CoRrRan** [comment]
Is the following piece of code resulting in this bug as well?

I receive he following error:
`PersonalWorkbook.modStringFunctions(9,3): extraneous input 'if' expecting NEWLINE`

My procedure:
```
Public Function ExtractData(ByVal StringData As String, Optional Separator As String = " ", Optional ArrayItem As Integer = -1)
  
      While InStr(StringData, Separator & Separator) > 0
        StringData = Replace(StringData, Separator & Separator, Separator)
      Wend

    If ArrayItem = -1 Then
      ExtractData = Split(StringData, Separator)
    Else
      ExtractData = Split(StringData, Separator)(ArrayItem)
    End If

End Function
```

**Comment by retailcoder** [comment]
@CoRrRan Good news: I can't reproduce any parsing error with the `ExtractData` function you provided.
Bad news: I can't reproduce any parsing error with the `ExtractData` function you provided.

:confused:

**Comment by retailcoder** [comment]
The tests passes with this code:

    Sub Test()
        DoSomething foo, ((bar))
    End Sub

The problem is that `DoSomething (...)` matches a `lexpression` (because an `indexExpr` expression matches the parens), which captures the first parenthesized argument as an index.

In other words our grammar gets confused between a method call and an array index call.

**Comment by retailcoder** [comment]
Asked on SO: http://stackoverflow.com/q/40583141/1188513

**Comment by MDoerner** [comment]
Regarding the answers on SO, I think using the proposed parse-then-resolve approach, i.e. first parsing an ambiguous `function_ot_array` expression and then resolving it afterwards, is preferable over the context sensitive parsing approach, for `VAB`. 
The problem I see with the context sensitive approach is that, in contrast to `C` and `C++`, `VBA` does not force you to make forward declarations via some header include. So, it might be quite tricky to figure out whether a given symbol is an array or a function in case there are function calls to public functions of another module, which maybe even contains function calls to public functions of the first module.
