### ISSUE TITLE
CodeExplorer Doesn't Sort Sheets Numerically

### ISSUE THREAD

**Issue by opticyclic** [rubberduck-vba/Rubberduck#2207]
I have 45 sheets in a workbook (not mine!). If I open the Code Explorer the sheets are ordered like this:

Sheet1 (...Name...)
Sheet10 (...Name...)
Sheet11 (...Name...)
Sheet12 (...Name...)
....
Sheet19 (...Name...)
Sheet2 (...Name...)
Sheet20 (...Name...)

Obviously Sheet2 should be listed before Sheet10 and not after Sheet19!

**Comment by retailcoder** [comment]
> I have 45 sheets in a workbook (not mine!)

:smile: 

Project components are sorted alphabetically by default, to mimick the sorting in the VBE's *Project Explorer*:

![image](https://cloud.githubusercontent.com/assets/5751684/18217489/218968ae-712b-11e6-9b51-f457acf6686a.png)

I guess we *could* try to extract a numeric prefix out of component names and sort them by numeric order, but then that would no longer match the *Project Explorer* sort... and, a worksheet being essentially a glorified class module, it *should* have a meaningful name - if the *use meaningful names* inspection isn't disabled, your inspection results should have 45 results suggesting to rename each worksheet :wink:

**Comment by retailcoder** [comment]
Hmm.. was this a feature request?

**Comment by opticyclic** [comment]
Perhaps a feature request.
Even if you name your Excel Sheets `README`, `MappingData`, `SQL` etc the project explorer still displays them as `Sheet1(README)`, `Sheet2(MappingData)`, `Sheet3(SQL)`.

Maybe the feature request is to have an option that says 

1. Mimic the Visual Basic Editor sorting (default)
2. Sort by the order that the sheets are in the workbook

**Comment by ThunderFrame** [comment]
@opticyclic You're talking about the `Worksheet.Name` of the sheets in the Excel interface, but the VBE lets you change the `Worksheet.CodeName` of the sheet *module*. That lets you refer to sheets in code without being concerned if a user has changed the name of the sheet in the Excel interface. The `Worksheet.Name` property can contain spaces, but the `Worksheet.CodeName` cannot.

Sou you could have

```
mapData (Mapping Data)
notes (Read Me)
sql (SQL Statements)
```
