### ISSUE TITLE
Inspection for duplication of function out parameter(s) and return value

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#2208]
Given a function that tries to act as a procedure with an out parameter _and_ like a function with a return value:

``` vb
Function Foo(Bar As Variant) As Variant
  Bar = Array(1,2,3)
  Foo = Bar
End Function
```

Rubberduck should have an inspection and warn of the design, logical and performance problems.

Maybe something like:

> Function return value is unnecessarily duplicated by output/ByRef parameter.

**Comment by retailcoder** [comment]
That seems rather *specific*... could it be generalized/broaden a bit?

**Comment by ThunderFrame** [comment]
hmmm. How about:

> It looks like you're in dire need of help... or trying to write a letter....
>
> I can help with that o.O

**Comment by ThunderFrame** [comment]
but yes, I take your point

**Comment by retailcoder** [comment]
eh, if someone wants to implement it, I won't stop 'em.

**Comment by Vogel612** [comment]
@ThunderFrame this may prove to be complicated without proper code-path analysis. Let's ignore the part where we have to think of things like:
```
Function Foo(Bar As Variant) As Variant
  Dim Baz As Variant
  Baz = Array(1, 2, 3)
  Bar = Baz
  Foo = Baz
End Function
```

Even without consideration of this simplistic idea, the whole thing goes beyond the scope of what a code-quality tool can easily check. The logic doesn't look difficult on first look, but the deeper I dig, the more problems appear.
