### ISSUE TITLE
"variable 'foo' is used but not assigned" - nope

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#2228]
False positive here:

```
Dim fso As Object
Dim Fileout As Object
Dim myFile As String
Dim rng As Range
myFile = cOutputFile
Open myFile For Output As #1
For Each rng In pFinalRange
    Print #1, rng
Next rng
Close 1
```

The `fso` variable spawns these inspection results:
- Variable 'fso' is not used. (OK)
- Variable 'fso' is never assigned. (OK)
- Variable 'fso' is used but not assigned. (WTF?)

The variable has zero references - that inspection shouldn't pop up at all.

**Comment by ThunderFrame** [comment]
MVCE

```vb
Sub Foo
  Dim str As String
End Sub
```
