### ISSUE TITLE
Provide filename of modified source file

### ISSUE THREAD

**Issue by eteichm** [rubberduck-vba/Rubberduck#2230]
When I export all the vba code outside of Rubberduck (with my own code) in the directory serving as git repo, RD detects a change in the source code and sends a warning saying: "A source file was modified out of the editor; should Rubberduck reload it?"  This is good!
(I exported it with my own code because I erroneously thought RD was not fully functional.)  
Could the warning tell which source file has changed? 
See also #2229

**Comment by rubberduck203** [comment]
Please see #3758.
