### ISSUE TITLE
Rubberduck fails to identify/resolve pseudo-worksheet functions

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#2236]
Excel allows you to bypass the `WorksheetFunction` object and just use `Application.FunctionName`:

``` vb
  Debug.Print Application.WorksheetFunction.Pi
  Debug.Print Application.Pi

  Dim app As Excel.Application
  Set app = Application

  Debug.Print app.WorksheetFunction.Pi
  Debug.Print app.Pi
```

If you omit `WorksheetFunction`, you don't get any Intellisense.

Furthermore, there's a small behavioral difference:

[Chip Pearson](http://www.cpearson.com/excel/callingworksheetfunctionsinvba.aspx):

> The difference between using or omitting the WorksheetFunctions reference is how errors are handled.
> 
>  If you do include the WorksheetFunction property, errors will manifest themselves as runtime error that need an On Error statement and a test of the Err.Number value. If you do not include the WorksheetFunction property, you must declare the result variable as a Variant type and test that variable with the IsError function.

This is going to be Excel-specific, but Rubberduck needs to add pseudo-declarations for each of the _function_ members in the `WorksheetFunction` object, so that RD can resolve their usage _with_ Application, _with_ **and** _without_ `WorksheetFunction`.

Note that `WorksheetFunction` contains 3 properties: `Application`, `Creator` and `Parent` that are _already_ implemented by `Application, so they shouldn't be made as pseudo-declarations.

**Comment by ThunderFrame** [comment]
Excel VBA would seem to be using [`Application.[_WSFunction]`](https://msdn.microsoft.com/en-us/library/microsoft.office.interop.excel._application._wsfunction.aspx) as a pseudo-signature for the WorksheetFunction functions, so that any usage of:

`Application.Average(1, 2)`

is internally compiled to

`Application._WSFunction(1, 2)`

but executed as

`Application.Average(1, 2)`

This behavior is demonstrated by this bizarre syntax behavior:

```vb
Debug.Print Application.WorksheetFunction.Average(1, 2) '1.5
Debug.Print Application.WorksheetFunction.[Average](1, 2) '1.5
Debug.Print Application.WorksheetFunction.[Average(1, 2)] ' Run-time error '438': Object doesn't support this property or method

Debug.Print Application.Average(1, 2) '1.5
Debug.Print Application.[Average](1, 2) 'Wrong number of arguments or invalid property assignment
Debug.Print Application.[Average(1, 2)] '1.5
```

**NOTE** - Rubberduck parses all of the above lines *without* error, but `Object.Member(n)` *should be considered invalid syntax, *unless* it is this Worksheet function behavior?

**Comment by retailcoder** [comment]
#2512 will merely *allow* the resolver to know (not without quite a bit of work) that a member call is made on an extensible type; it will *not* resolve these calls to the corresponding WorksheetFunction members, unless specific code is implemented to do it in the resolver. Not sure I like host-specific resolver code... needs more thought.

**Comment by ThunderFrame** [comment]
I wonder if the functions *were* part of the Type library in Excel 95.

I don't think anything should be done in the resolver. If anything, the COM collector should special case the Worksheet functions when reading the Excel TLB, in much the same way as Format$ is special cased when collecting from the VBA TLB.

**Comment by retailcoder** [comment]
Hmm, a host-specific custom loader would make sense. And we could even make it "alias" the `WorksheetFunction` members the way we're aliasing `_B_var_Foo` functions in the VBA type library - that would work without altering the resolver. Quite a bit of work to alias them all though, but definitely feasible.

**Comment by retailcoder** [comment]
Note, the term "host-specific" is misleading; we should create these declarations under `Excel.Application` regardless of the host.

**Comment by comintern** [comment]
This would be trivial to do with access to the Excel COMProject - all you would need to do would be to add the `WorksheetFunction` interface to `Application`.

**Comment by PeterMTaylor** [comment]
Forgive my confusion as I read what @ThunderFrame is saying. Would this resolve Excel.Application explicitly for excel 2010, 2013, 2016 as opposed to eariler versions less than 2007?

**Comment by comintern** [comment]
@PeterMTaylor - My implementation is specific to the `Excel.Application` coclass Guid (which I got from Excel 2013x32).  It _should_ be the same for all versions of Excel though - if not, it's just a simple Linq tweak. I was guessing it was more efficient to locate it by Guid as opposed to name.
