### ISSUE TITLE
Rubberduck reports `auto_open` and `auto_close` procedures as unused

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#2239]
Excel will automatically execute procedures named `auto_open` and `auto_close`, _if_ they are present in a project.

``` vb
Private Sub auto_open()
  MsgBox "auto_open"
End Sub

Private Sub auto_close()
  MsgBox "auto_close"
End Sub
```

Rubberduck needs to treat these special cases accordingly.

**Comment by comintern** [comment]
Fixed in commit 415fa932.
