### ISSUE TITLE
Coupling issues in CodeInspectionSettings

### ISSUE THREAD

**Issue by Vogel612** [rubberduck-vba/Rubberduck#2240]
As mentioned in #2115 the CodeInspectionSettings have coupling issues that make working with them somewhat fragile.

This issue serves as reminder to fix these issues.

**Comment by rkapka** [comment]
Are these issues still present?

**Comment by Vogel612** [comment]
The linked PR diff is enlightening. The problem is that CodeInspectionSettings defaults were a royal mess. It's basically fixed, as long as the changes to default settings are merged. I think #3718 can be though of as fixing this issue.

**Comment by Vogel612** [comment]
fixed as of #3718
