### ISSUE TITLE
RD needs an inspection for variable reassigned but never re-used

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#2243]
RD already has an inspection for `Variable 'x' is not used`, which catches this:

```vb
Private Sub Test1()
  Dim status As String
  status = foo
End Sub
```

But it fails to catch unused re-assignments *after* usage:

```vb
Private Sub Test2()
  Dim status As String
  status = "foo"
  Debug.Print status
  status = "bar"
End Sub
```

This is related to #882, but instead of being a reassignment *before use*, this inspection is for unused reassignment *after* prior use.

**Comment by retailcoder** [comment]
#882 *Value not used* is meant to do exactly that
