### ISSUE TITLE
Feature Request: Remove commit message when commit succeeds

### ISSUE THREAD

**Issue by Zak-Michael-Armstrong** [rubberduck-vba/Rubberduck#2247]
Just a UI thing. 

If I write a commit message, and then commit the change, and it goes through, it is irritating to have to delete said message before writing a new one.

**Comment by Hosch250** [comment]
This was initially added because people weren't sure what was happening. I think the best solution is to have it hide itself after 1 second (maybe make it customizable in the settings?).

**Comment by rubberduck203** [comment]
There’s now a PR to remove the feature. 
Please see #3758
