### ISSUE TITLE
Function returning Enum: Object is assigned without the `Set` keyword - Nope

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#2256]
Resolver erroneously thinks the function is returning an object and expects the result assignment to use the `Set` keyword.

```vb
Option Explicit

Private Enum foo
  useprod = 1
  UseDev = 2
  useuat = 4
End Enum

Private Function GetFoo() As foo
  GetFoo = useuat
End Function
```

**Comment by retailcoder** [comment]
The inspection is excluding a finite range of known value types; if the return type resolves to an enum or UDT declaration, we need to exclude it as well.

**Comment by retailcoder** [comment]
commit 0eb337889e98171d91d4e16940338d65fce73b88 fixed this
