### ISSUE TITLE
Function returning Type - Return value is never assigned - Nope

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#2257]
Rubberduck is erroneously reporting the return value of `GetFoo` as unassigned. VBA implicitly creates the return type, and it's perfectly valid to return *that* type *without* any member assignments, but even if you do assign one of the members, Rubberduck treats the return value as never assigned.

```vb
Option Explicit

Private Type bar
  someint As Integer
End Type

Sub test()
  Debug.Print GetFoo.someint
End Sub

Private Function GetFoo() As bar
  GetFoo.someint = 6
End Function
```

**Comment by retailcoder** [comment]
So, if the return type is a UDT, we should issue an inspection result only if none of the UDT members are assigned?

Even though `GetFoo.someint = 6` is valid, I'd deem it a usage of the function as a local variable - which is an inspection we're currently lacking (under *readability/maintainability issues* I guess).

> **Member identifier is used as a local variable**
> The member identifier should only be used to assign the return value. Member access and/or other reads should be done off a local variable instead.

Thoughts?

**Comment by retailcoder** [comment]
So, regardless of whether there should be an inspection result for the *member identifier being used as a local variable*, a function returning a UDT will now be deemed "returning" when there's a `LetStmt` (an assignment) where text of the left-most member of the left-hand-side expression matches the member's name.
