### ISSUE TITLE
Meaningful names inspection doesn't catch consecutive vowels

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#2260]
3 or more consecutive vowels seem to be treated as acceptable variable names:

``` vb
Private aaa As String
Private bbb As String 'Consider renaming variable
Private ccc As String 'Consider renaming variable
Private ddd As String 'Consider renaming variable
Private eee As String
Private iii As String
Private ooo As String
Private uuu As String

```

**Comment by retailcoder** [comment]
Removing the [bug] label here, because the inspection works exactly as specified, outputting a result for <=3 letter identifiers and identifiers without any vowels. It's really more of an [enhancement], I think there's actually countless different ways this inspection can be refined.
