### ISSUE TITLE
Parser doesn't consider a function declaration's "array of objects" return values as an array

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#2266]
While trying to fix #2265, I found that a function that returns an Array of a complex types (eg. arrays of Objects, Worksheets, Workbooks, etc.) is not considered an array.

The culprit line appears to be the `LPAREN` function in:

https://github.com/rubberduck-vba/Rubberduck/blob/393c10d39ed5a2f91f3be997157b7e5f56995a7c/Rubberduck.Parsing/Symbols/DeclarationSymbolsListener.cs#L484

``` c#
var isArray = asTypeClause != null && asTypeClause.type().LPAREN() != null;
```

This would seem to be a grammar issue?

Linking #2265 and #2256

**Comment by retailcoder** [comment]
A member is known to return an array when its signature explicitly says so:

    Public Function Foo() As Bar()

The `type` in the `asTypeClause` contains a `LPAREN` token; that's how we know we're dealing with an array. If a function is returning a `Variant`, we know nothing... it could be an array as much as it could be a string or a `Dictionary`.

What's your function signature like?

**Comment by ThunderFrame** [comment]
Well, I think my signatures look consistent:

```vb
Sub test()

  Dim bar As Variant
  bar = stringarray

  Dim foo As Variant
  foo = worksheetarray
  
End Sub


Private Function stringarray() As String()
  Dim temp(0 To 2) As String
  temp(0) = "a"
  temp(1) = "b"
  temp(2) = "c"
  stringarray = temp 'Doesn't trigger the inspection result
End Function

Private Function worksheetarray() As Worksheet()
  Dim temp(0 To 2) As Worksheet
  Set temp(0) = Sheet1
  Set temp(1) = Sheet1
  Set temp(2) = Sheet1
  worksheetarray = temp 'Triggers the inspection result
End Function
```

**Comment by retailcoder** [comment]
Huh, definitely a bug... nice catch!

**Comment by comintern** [comment]
Just out of curiosity, why is the value of `Declaration.IsArray` being set using the parser context here anyway? 

`var isArray = asTypeName.EndsWith("()");` seems just as reasonable unless I'm totally missing something.  I didn't think it was possible to return an array without "()" notation period.

FWIW, changing that line of code doesn't trigger the ObjectVariableNotSetInspection anymore and all the unit tests still pass.

**Comment by retailcoder** [comment]
@comintern that's one of the many things that have been collecting dust in the `Declaration` class forever... should be (yet another) ctor parameter?

**Comment by comintern** [comment]
@retailcoder - Nah, I think the fix above is good for now. The grammar is a bit complex there, so the `LPAREN` is buried about 10 steps inside of the type clause if it's not an intrinsic type. The grammar actually works in that `asTypeClause.type().GetText()` is pulling the correct type - no sense in calling for the `.type()` twice for something this simple.

This will be in my next PR along with a test.
