### ISSUE TITLE
Wrap the VBIDE API

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#2268]
In order to help stabilizing 2.0, we need to call `Marshal.ReleaseComObject` in every single COM object we're referencing. That's easily said, but we have critical types that hold on to such objects, and don't quite clean up properly.

So we need to wrap the whole VBIDE API with disposable wrappers that clean up after themselves, and effectively replace every single COM object with a wrapper - and call `.Dispose` on everything when we're done.

This work is already in progress, creating this issue just to relate the commits to it when it's time to merge.

**Comment by retailcoder** [comment]
`Dispose` didn't cut it, but the VBIDE API is now completely wrapped and implemented. The VB6 wrappers aren't fully implemented though.

**Comment by Vogel612** [comment]
I assume that doesn't yet mean that `Marshal.ReleaseComObject` has been removed from the project (ignoring the necessary uses in the SafeWrappers)? read: Are there remaining changes to do for cleaning up code that doesn't use the SafeWrappers or code that tries to release them as COM Objects?
