### ISSUE TITLE
Add "ImportOmatic" as a Host Application

### ISSUE THREAD

**Issue by tdwright** [rubberduck-vba/Rubberduck#2269]
ImportOmatic is a niche tool for importing data into a well-used charity CRM product called The Raiser’s Edge. https://www.omaticsoftware.com/Solutions/RaisersEdge/ImportOmatic.aspx

One of it's killer features is the ability to use VB to transform data during the import process. As far as I can tell, the code editor provided uses the standard VBE:

![iom_code_editor_ss](https://cloud.githubusercontent.com/assets/95890/19034705/e76336a6-895c-11e6-8ea2-8a6f22900cc9.PNG)

I'm planning to fork the project and add ImportOmatic as a host application.

**Comment by ThunderFrame** [comment]
That screenshot above is not the VBE and the code is VisualBasic.NET. Google suggests that RaisersEdge did/does support VBA.

**Comment by tdwright** [comment]
Ah, damn. Sorry for the confusion. I'll mark this as closed.

The VBA module for RE is an optional module that we don't (currently) have a licence for. I'll revisit RD if and when we do get it. (More info: https://kb.blackbaud.co.uk/articles/Article/52934)
