### ISSUE TITLE
Inspection for placement/order of `Option` statements as first statements in module Declarations section

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#2279]
The following `Option` statements can appear _anywhere_ in a module's declarations section:
- `Option Compare Database|Binary|Text` -'MS-Access only
- `Option Explicit`
- `Option Private Module` 
- `Option Base 0|1`

But by convention, `Option` statements appear _before_ any actual declarations, but not necessarily before any comments at the top of the module.

MS-Access places the `Option Compare Database` statement before an `Option Explicit` statement, so we should probably preserve that order in MS-Access, so as not to cause changes to source code in potentially _every_ module.

For the other 3 potential `Option` statements, `Option Explicit` is likely to be the most common, followed by `Option Private Module` and then `Option Base 0|1`. As such, I propose that Rubberduck prefers _that_ order (although the exact order could be a user-configurable RD setting). For example:

**Before:**

``` vb
'Some overbearing licence that requires comments be at the top....
'/\/\/\/\/\/\/\/\/\/\/\/\/\/\/
'* Some change-log/ASCII ART *
'=============================
Dim foo

Option Compare Database
Option Private Module
Option Explicit

Dim fizz
Option Base 0

Sub bar()
End Sub
```

**After:**

``` vb
'Some overbearing licence that requires comments be at the top....
'/\/\/\/\/\/\/\/\/\/\/\/\/\/\/
'* Some change-log/ASCII ART *
'=============================
Option Compare Database
Option Explicit
Option Private Module
Option Base 0

Dim foo
Dim fizz

Sub bar()
End Sub
```

**Comment by retailcoder** [comment]
We could make a "refactoring" that regroups `Option` statements at the top of the module, but we shouldn't need an inspection result for it.
