### ISSUE TITLE
Running Extract method doesn't check validity of the new method name, can cause Resolver Error

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#2283]
RD's ExtractMethod refactoring names the new method `NewMethod` regardless of whether the module already contains a declaration named `NewMethod`.

If the user performs an Extract Method followed by another ExtractMethod, the user ends up with 2 methods called `NewMethod`, and no way to distinguish the calls to each method.

**Before:**

``` vb
Sub foo()

  Dim x As String
  x = "foo"

  Dim y As String
  y = "bar"

End Sub
```

**After:**

``` vb
Sub foo()


NewMethod

NewMethod
End Sub
Private Sub NewMethod()
  Dim y As String
  y = "bar"
End Sub
Private Sub NewMethod()
  Dim x As String
  x = "foo"
End Sub
```

Rubberduck should potentially ask for the name of the new method and/or check the validity of the intended new name _before_ creating and referring to the method.

**Comment by retailcoder** [comment]
ref. #1599 - the *Extract Method* dialog solves this problem.

**Comment by Vogel612** [comment]
Since the Extract Method refactoring is in dire need of a rewrite from scratch, all [bug] issues pertaining to it, are in the process of becoming irrelevant. Closing.
