### ISSUE TITLE
Indenter should have setting for number of blank lines between procedures

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#2286]
My preference is for 1 blank line _after_ a declaration, so that Types/Enums/Procedures are easier to identify visually:

**Before:**

``` vb
Option Explicit
Type Fizz
  Foo As String
  Bar As String
End Type
Enum Buzz
  aaa =1
  bbb = 2
End Enum
Sub Foo()
End Sub
Sub Bar()
End Sub
'TODO - Refactor FooBar
Sub FooBar
End Sub
```

becomes

**After:**

``` vb
Option Explicit

Type Fizz
  Foo As String
  Bar As String
End Type

Enum Buzz
  aaa =1
  bbb = 2
End Enum

Sub Foo()
End Sub

Sub Bar()
End Sub

'TODO - Refactor FooBar
Sub FooBar
End Sub

```

**Comment by retailcoder** [comment]
Technically not *indentation*, but I like it very much. Good idea!

**Comment by comintern** [comment]
Any thoughts on what would be reasonable limits on the settings for this?  0 to 5 lines between functions with a default of 1? 

When I implement this I'll probably also add a setting to remove extra vertical white-space *inside* of procedures also. My thought is that it should be a separate setting. Something like "Compress blank lines inside of procedures" with a related setting of "Maximum blank lines".

**Comment by ThunderFrame** [comment]
I think 0 to 5 seems reasonable. Personally, I'd never use more than 2, and would default to 1.

Might be worth having a setting for vertical space *between* declarations, and vertical space *within* declarations, and maybe settings for leading/trailing vertical space?

**Comment by retailcoder** [comment]
I'd make it 0 or 1... maybe have 2 available to pick from, but 5 seems a bit arbitrary and.. well, excessive IMO.

 - Whitespace between procedures
  The vertidal whitespace between module body members.
 - Whitespace between declaration blocks
   Assuming user is regrouping their declarations, the vertical whitespace between blocks in modules' declaration section; `Type` and `Enum` blocks, but also `Declare` external members, `Const`, and variable fields (but not between *each* `Declare`, `Const` or variable).
 - There might need to have another setting to determine whether to remove or maintain the vertical whitespace between a comment block and whatever declaration that follows.

**Comment by retailcoder** [comment]
@comintern should this one be closed?

**Comment by comintern** [comment]
@retailcoder - I'd leave it open.  The only thing that's currently implemented is spacing between procedures - I'm still planning on adding support for spacing between `Type` and `Enum` members and declaration blocks.

**Comment by comintern** [comment]
This should have been closed quite a while ago. Already supported.
