### ISSUE TITLE
Using the Rubberduck..Refactor..Rename context menu opens Rename dialog twice

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#2292]
Using the Rubberduck..Refactor..Rename context menu opens the Rename Dialog.

If you press OK to perform a rename, the dialog reopens when the rename is complete (but shows the OLD identifier). Cancelling the second instance closes successfully.

If you press Cancel, the dialog immediately reopens. Cancelling the second instance closes successfully.

**Comment by ThunderFrame** [comment]
This *doesn't* happen when using the Rubberduck..Rename context menu on a vbComponent.

**Comment by ThunderFrame** [comment]
The second instance showing the OLD identifier seems to be related to #2293

**Comment by retailcoder** [comment]
I believe this has been fixed with the merge of #2289. Can you confirm?

**Comment by retailcoder** [comment]
Yup, no repro. Closing.
