### ISSUE TITLE
After a rename, Rename command should be disabled until after reparse

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#2293]
Renaming a declaration requires that RD reparse the projects, otherwise the next rename won't necessarily be accurate.

After a reame, RD should either:
1. Automatically reparse after each rename
2. Disable the refactor..rename command until the next parse is complete

There may be other refactoring commands that should adopt the same approach.

**Comment by retailcoder** [comment]
Huh, that's not the current behavior? It was certainly the intended one..
