### ISSUE TITLE
Renaming a PublicNotCreatable Class in a referenced project gets the name incorrect

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#2294]
`Project1` references `Project2`. `Project2` exposes `Class1` as `PublicNotCreatable` using a `Public` factory method in `Project2.Module1.CreateClass1`.

I don't think it matters, but `Project1` also has its own class named `Class1`, but with different members.

`Project1` declares a variable of type `Project2.Class1` and assigns the variable with `Project2.GetClass1`.

Using Rubberduck.Rename on the `Project2.Class1` identifier causes  the new name to include partial repetitions of the new identifier name, across _both_ projects.

I'll try to produce an MVCE, and post the source.

**Comment by retailcoder** [comment]
Confirmed fixed.
