### ISSUE TITLE
Inspection for Worksheet ActiveX controls that can be Form controls

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#2296]
Very often a worksheet will have an ActiveX control that only has a single `Click` event handler, and the control isn't referenced by any other code.

Such controls could be converted, in the right conditions, to Form controls that have an `OnMacro` handler, which would move the event handler out of the Worksheet component and into a standard module.

Linking #389

**Comment by Vogel612** [comment]
This possibly needs further discussion. From how I read this it seems a bit out of scope for RD to provide a refactoring for this. It might be viable to implement an Inspection at the "Language Opportunities"-level. @retailcoder thoughts?

**Comment by ThunderFrame** [comment]
Imagine a workbook with 4 sheets, 3 of which have ActiveX Command Buttons that change the ActiveSheet to `Sheet1`.

So `Sheet2`, `Sheet3` and `Sheet4` all require their own handlers:

**Sheet2**
```
Private Sub CommandButton1_Click()
  ReturnHome
End Sub
```

**Sheet3**
```
Private Sub CommandButton1_Click()
  ReturnHome
End Sub
```

**Sheet4**
```
Private Sub CommandButton1_Click()
  ReturnHome
End Sub
```

**modHelper**
```
Public Sub ReturnHome()
  Sheet1.Activate
End Sub
```

If the ActiveXControls were all replaced with Form controls, the onAction property for *all 3* buttons could be set to `ReturnHome`, and the ActiveX handlers omitted entirely.

**Comment by retailcoder** [comment]
@Vogel612 I agree it's a bit of a stretch, but at the same time, there's a real possible gain here. Tagging with [host-specific] and [up-for-grabs] for now.

FWIW nothing is currently accessing worksheet controls.

**Comment by ThunderFrame** [comment]
This gets *really ducking* hard if there is any code that reads or modifies, for example, the appearance of the control. Setting colors and fonts on an ActiveX control is *very* different to that of a shape, and even a TextBox shape is different to a button shape.

**Comment by retailcoder** [comment]
@ThunderFrame I think I have a solution... hold on...

**Comment by retailcoder** [comment]
:smiley:
