### ISSUE TITLE
Corel X4 crashes when opening IDE

### ISSUE THREAD

**Issue by Octopus134** [rubberduck-vba/Rubberduck#2298]
After installing rubberduck 2.8, I tried to open the IDE in Corel Draw X4. 
Corel immediately crashes, not even seen anything of the IDE.
I had to deinstall rubberduck.
Win8.1-64, rubberduck 2.0.8.30557

Thomas

**Comment by Vogel612** [comment]
Hi Tomas,

sorry to hear. Is there possibly any more information you could give us about how Corel crashed?
Basically anything could help to fix this...

Thanks, Vogel

**Comment by Octopus134** [comment]
Hi Vogel

I like to do, but how?
I reinstalled rubberduck, started corel X4, tried to open the IDE by Extras > Makros > Makro editor (german version): Corel draw funktioniert nicht mehr. Wenn ich auf debuggen klicke wird eine Datei ..users\Hosch\...\rubber

**Comment by Vogel612** [comment]
That already gives us a start. The problem seems to be situated in the class responsible for listening to key-combinations ([here](https://github.com/rubberduck-vba/Rubberduck/blob/next/RetailCoder.VBE/Common/RubberduckHooks.cs)) apparently #1710 could be related.

It seems there used to be some bug that made Rubberduck roll over when reloaded from inside the VBE ...  It might be a start. Thanks!

**Comment by ThunderFrame** [comment]
hmm, CorelDRAW X6 64-bit VBE fails to load Rubberduck. I don't think I've run Rubberduck in CorelDRAW since I reinstalled Corel, so I'm unsure what's causing this.

**Comment by retailcoder** [comment]
@ThunderFrame can you repro with 2.0.11?

**Comment by ThunderFrame** [comment]
My copy of CorelDRAW X6 was having problems (although it worked on a different computer many months ago). But I have Office XP, Visio 2003, Office 2016 and CorelDRAW X6 installed. I believe they all have their own version of the Office TLB - `MSO.DLL` (primarily for the CommandBar classes).

As per #2496, having 4 different versions of `MSO.DLL` as well as having updates in an inconsistent order, has likely put my registry entries in harm's way.

While running CorelDRAW as Administrator did help, Rubberduck does parse, but the status bar briefly says it's a Resolver Error before changing to say that it's a Parser Error (although no errors are listed in the window).

I seem to recall a similar problem when originally getting Rubberduck to work in CorelDRAW - I had to unload some/all of the Global Macros from within the Host UI, *before* opening the VBE and parsing. I need to investigate that further, but I'll raise a separate issue for that.

@Octopus134 Are you able to confirm if running X4 as Administrator helps? You may have a corrupted registry if you have CorelDRAW and any other Office product installed - See this SO answer for details http://stackoverflow.com/a/12962795/5757159

**Comment by bclothier** [comment]
Closing the issue since we changed both how we were installing the add in and executing code (cf #3836 and #3778 ). In theory, Rubberduck should now work on any host. If this is a issue still even with current release, open a new issue with more recent repro.
