### ISSUE TITLE
Parens () are added into the code when comitting

### ISSUE THREAD

**Issue by Octopus134** [rubberduck-vba/Rubberduck#2299]
several times, when commiting the code in the source control dialog
in the first class (form_xxx) there are added several pairs of parentheses () at the end of the code.

(Access2013-32, Win8.1-64, rubberduck 2.0.8.30557):

**Comment by retailcoder** [comment]
Huh, that's a weird one! Thanks for reporting it!

**Comment by retailcoder** [comment]
This could be a bug in the VBIDE API *export* functionality - we're already working around one such bug where the VBIDE API adds empty lines at the top of a UserForm class module.

Got an example of these parentheses? (I don't have MS-Access to repro, @ThunderFrame can you check?)

**Comment by Octopus134** [comment]
()
()
()
()
()
something like this, several lines, depending how much commits

**Comment by Vogel612** [comment]
Seems like this could be a general export bug. Removing the source-control label, as source control got removed with #3758

**Comment by bclothier** [comment]
Cannot reproduce, closing. Exporting either a standard module or a document module does not produce this.
