### ISSUE TITLE
Unreacheable code detected

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#23]
[Warning]

Rubberduck should detect unreacheable code, and warn about it.

    DoSomething 123
    Exit Sub

    DoSomethingElse 456 'unreacheable code (not under a label, and/or no reacheable jump to that label)

    DoSomething 123
    Err.Raise SomeError

    DoSomethingElse 456 'unreacheable code (unless On Error Resume Next is specified)

    DoSomething 123
    If False Then
        DoSomethingElse 456 'unreacheable code (condition expression must be statically evaluatable)
    End If

**Comment by bigandyherd** [comment]
Hi guys,

I like what you've created here. I really want to use it, but this particular issue is something of a stumbling block for me. Where I work we have a couple of corporate XL add ins with protected code. Every time I open up one of Rubberduck menus (e.g the to dos). I get a pop up warning that it's found some code that it doesn't know how to analyse. Any idea when this particular issue might be fixed? It would be awesome if it can ignore the protected code a bit more quietly :-)


Cheers,
Andy

**Comment by ckuhn203** [comment]
Hi there @bigandyherd! We're really happy you like what we've done so far. I've opened issue #289 and added it to our our next milestone. I'd like to fix this in the next release if possible, but it might get bumped to the one after depending on time constraints.

**Comment by bigandyherd** [comment]
Thanks @ckuhn203, I'll keep a lookout :-)

**Comment by ckuhn203** [comment]
You're welcome @bigandyherd! :+1: Make sure to subscribe to the other issue so you'll get notifications. 

![image](https://cloud.githubusercontent.com/assets/2716800/6505488/c030ad20-c310-11e4-97b2-48260b821189.png)

**Comment by retailcoder** [comment]
As of version 1.21, locked projects will show up like this in the Code Explorer:

![image](https://cloud.githubusercontent.com/assets/5751684/6542629/6de40c7a-c4cc-11e4-8235-550af66bf1d1.png)

Also the parser will now check to see if a project is locked before it tries to access its components.

**Comment by retailcoder** [comment]
Detecting unreacheable code implies simulating the compiler... which is a little bit beyond the scope of this project.
