### ISSUE TITLE
Parse error with EverythingsAccess-Watchdog

### ISSUE THREAD

**Issue by Octopus134** [rubberduck-vba/Rubberduck#2301]
I use the addin "Watchdog" as errormanagement in my access-databases.
If watchdog modules are added, there is the following parse error if I try to fill/refresh the code explorer:
ErrEx_Helper    Module  L287C1  extraneous input 'Public' expecting {<EOF>, ':', ATTRIBUTE, REM, NEWLINE, ''', WS, LINE_CONTINUATION}
The code explorer remains empty. If I remove watchdog from the database, the code explorer is filled.

The error message means nothing to me. In line 287 there is `# End If`   (as end of a compile instruction `#If Win64 = False Then`)

What is wrong with this?

Thomas
(Access2013-32, Win8.1-64, rubberduck 2.0.8.30557)

**Comment by ThunderFrame** [comment]
@Octopus134 Can you post all of the lines between `#If Win64 = False` and `#End If`?

And If possible, the 10 lines before and after?

You can omit lines that begin with statements like:
`    NativeCode = NativeCode & "HfZztDjztdQKq;AhIjYDWlYRklYRjC\DabTaG\hpRcWOmAm>haWOm>WlUoKswoKqKL;qKm@@NrWCvcOohGOyTGOyThJo_IBJyv?`

**Comment by Octopus134** [comment]
It's 

`#If Win64 = False Then
Public Sub NATIVECODE0000_EVERYTHINGACCESS(): End Sub
... (counting from 0000 to 0126)
Public Sub NATIVECODE0126_EVERYTHINGACCESS(): End Sub
#Else
Public Sub NATIVECODE0000_EVERYTHINGACCESS(): End Sub
... (counting from 0000 to 0137)
Public Sub NATIVECODE0137_EVERYTHINGACCESS(): End Sub
#End If
`
Line 287 is the last one.
Hint: if the function ToggleLineNumbers is from rubberduck, it counts only to the else, then not anymore. (the toolbar ToggleLineNumbers is left, although I removed the addin rubberduck from my database.

**Comment by retailcoder** [comment]
Rubberduck can't parse line numbers; we actually strip them from the input string we give our parser, so we have no line number tokens, but then whether or not line numbers are present should make no difference for Rubberduck - "toggle line numbers" definitely isn't a RD feature, so the fact that it remains on your toolbar is a good sign, it means RD teardown isn't affecting other add-ins' stuff.

Please clarify, is the last line actually reading like this?

    Public Sub NATIVECODE0137_EVERYTHINGACCESS(): End Sub #End If

If so, try moving the `#Preprocessor` instructions on their own line:

    #Else
    Public Sub NATIVECODE0137_EVERYTHINGACCESS(): End Sub
    #End If 

This could be a bug in our preprocessor instructions parser/interpreter.

**Comment by Octopus134** [comment]
no the code is as yours, but copy&paste into the code-brackets <> here in this edit field made one line only out of it - I realized that problem, but do not know, how I get linefeeds in that post.

**Comment by retailcoder** [comment]
Just indent with 4 spaces ;-)

This has all the details: **https://guides.github.com/features/mastering-markdown/**

**Comment by retailcoder** [comment]
Ok so I put this into a new standard module:

    Option Explicit
    #If Win64 = False Then
    Public Sub NATIVECODE0000_EVERYTHINGACCESS(): End Sub
    Public Sub NATIVECODE0126_EVERYTHINGACCESS(): End Sub
    #Else
    Public Sub NATIVECODE0000_EVERYTHINGACCESS(): End Sub
    Public Sub NATIVECODE0137_EVERYTHINGACCESS(): End Sub
    #End If

Then I triggered a reparse, and got no error.

Which version are you running again?
