### ISSUE TITLE
Properties are just procedures with a twist

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#2317]
VBA parses this without blinking:

    Public Property Get Foo()
        Foo = "WTF!"
    End Function

And this too:

    Public Property Get Bar()
        Bar = "WTF!"
    End Sub

We need to tweak the grammar rule that defines a `Property` member to accept these non-orthodox formulations.

...and then implement an inspection and a quick-fix to make it right.

**Comment by ThunderFrame** [comment]
Need to handle the exit statements too:

```
Public Property Get Foo(i As Byte)
  Select Case i
    Case 0
      Exit Sub
    Case 1
      Exit Function
    Case Else
      Exit Property
  End Select
End Function
```

**Comment by retailcoder** [comment]
@ThunderFrame the exit statements are not formally constrained within a `Block`, so that wouldn't be ab issue.

**Comment by retailcoder** [comment]
Not going to fix. Changing the grammar to support this actually breaks the parser:

	propertyGetStmt : 
		(visibility whiteSpace)? (STATIC whiteSpace)? PROPERTY_GET whiteSpace functionName (whiteSpace? argList)? (whiteSpace asTypeClause)? endOfStatement 
		block 
		(END_PROPERTY | END_SUB | END_FUNCTION)
	;

This single modification results in an empty module with nothing but `Option Explicit` in it, failing to parse:

> Sheet2	Module	L1C1 extraneous input 'Option Explicit' expecting {<EOF>, ATTRIBUTE, BEGIN, CONST, DECLARE, DEFBOOL, DEFBYTE, DEFDATE, DEFDBL, DEFCUR, DEFINT, DEFLNG, DEFOBJ, DEFSNG, DEFSTR, DEFVAR, DIM, ENUM, EVENT, FRIEND, FUNCTION, GLOBAL, IMPLEMENTS, OPTION_BASE, OPTION_EXPLICIT, OPTION_COMPARE, OPTION_PRIVATE_MODULE, PRIVATE, PROPERTY_GET, PROPERTY_LET, PROPERTY_SET, PUBLIC, REM, STATIC, SUB, TYPE, VERSION, LINE_CONTINUATION, NEWLINE, ''', ':', WS, DEFLNGLNG, DEFLNGPTR}
