### ISSUE TITLE
Log file not created

### ISSUE THREAD

**Issue by kpstolk** [rubberduck-vba/Rubberduck#2325]
I was trying to connect to my existing Git repo, but then an error occurred:

![2016-10-25 21_02_09-source control](https://cloud.githubusercontent.com/assets/538170/19700324/20a9e5d0-9af7-11e6-8b26-f3859810c772.jpg)

But strange thing is that no log file was created, only the log folder:
C:\Users\{username}\AppData\Roaming\Rubberduck\Logs

So now I can only report that there is an issue with an issue 😆 

Rubberduck version 2.0.9.0 with Excel 2016.

**Comment by retailcoder** [comment]
Logging gets very verbose, very fast, so we've disabled it by default; you can enable logging by changing the minimum log level from "No Logging" to anywhere between "TRACE" and "FATAL", where `TRACE` is the most verbose log level.

**Comment by kpstolk** [comment]
OK, that explains something 😄 
I thought these were crash logs, maybe it could help to add that note to the error message?

**Comment by retailcoder** [comment]
Agreed :+1:

**Comment by retailcoder** [comment]
You'll want to look at your `SourceControl.Rubberduck` config file to make sure your repo is there (looks like it is, from the "online" git status label). Did you have the local VBA project opened?

**Comment by kpstolk** [comment]
Just got another error (will create separate issue) but now I do have a log, so creating a log does indeed work when the setting has changed.

BTW, why not setting the severity by default to a restricted value like Error or Fatal? I hope not that many errors occur?

**Comment by kpstolk** [comment]
No, the `SourceControl.Rubberduck` is not there, maybe because the status is Online because the .git folder is already there and in my case controlled by TurtoiseGit?

**Comment by retailcoder** [comment]
Good point. Although.... we *do* have a regular consistent crash on exit :disappointed:

**Comment by kpstolk** [comment]
..Still nice to know that in user reports I guess? 😉

**Comment by kpstolk** [comment]
Just noticed that an error message like that is already used in the Source Control window:

![image](https://cloud.githubusercontent.com/assets/538170/19701887/a235dd42-9afd-11e6-8b00-c95f2b8768e8.png)

So maybe that can be reused, but still have to be able to reproduce again before a user submits an issue.

**Comment by kpstolk** [comment]
FYI: I see that I get the online status when I set the Default Repository Location, click update and then click the refresh icon.

Source Control still doesn't work for me but I now just click the refresh icon so I at least have the files which I then can commit using TortoiseGit. Already happy I can use that at least 😃 

To get back to the original issue:
Only the message has to be changed or the default log setting, in my opinion it is nice to have critical logging by default and maybe cleanup the file when it gets to large.

**Comment by Vogel612** [comment]
IIUC since 2.0.8 the default log-level is not "NONE" anymore, which means that we usually have a log in case something blows up. A such this issue has been fixed, IMO. 

If any of the participants wish to make this into a feature-request, a separate issue linking back here would IMO be the best option :smile:
