### ISSUE TITLE
Extract Method is broken

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#2326]
Excel 2010 - 

First I have to manually parse, reparse, compile the code, then reparse again to get RD to enable the `Extract Method` option, then with the following code, I highlight the lines between the lines of comment `'`, select `Extract Method` and nothing happens.

``` vba
Public Sub SaveFile()

  If ThisWorkbook.FileFormat = xlOpenXMLTemplateMacroEnabled Then

    Dim DefaultDirectory As String
    DefaultDirectory = GetDefaultDirectory
'''''''''''''''''''''''''''''''''''''''''''''''''''''  
    Dim Dialog As FileDialog
    Set Dialog = Application.FileDialog(msoFileDialogFolderPicker)
    Dim SavePath As String
    With Dialog
      .AllowMultiSelect = False
      .InitialFileName = DefaultDirectory
      .Title = "Select where you want to save the workboook"
      If .Show = -1 Then
        SavePath = .SelectedItems(1)
      Else
        SavePath = vbNullString
      End If
    End With
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

'save type: xlOpenXMLWorkbookMacroEnabled

  End If

End Sub
```

**Comment by Vogel612** [comment]
wtf?? I just tried to repro this ... and at first it didn't work. When I restarted and attached a debugger it suddenly worked ...

**Comment by Vogel612** [comment]
Since the refactoring has been disabled for now, this is not quite as critical anymore. Would still be great to get a fix ...

**Comment by Vogel612** [comment]
Since the Extract Method refactoring is in dire need of a rewrite from scratch, all [bug] issues pertaining to it, are in the process of becoming irrelevant. Closing.
