### ISSUE TITLE
Double-click navigation doesn't always highlight code

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#2331]
I'm finding that in Excel 2010 w RD 2.0.9, double-clicking an inspection will take me to the line of code, but doesn't always highlight the offending bit. It seems to highlight the first inspection selected after launching Excel, opening the workbook, opening the VBE, running the parser, then double clicking. After that, not so much.

![rd](https://cloud.githubusercontent.com/assets/11889733/19736051/14375f32-9b7c-11e6-9312-5ffe8aefcc00.PNG)
I believe that the circled usage it what it's complaining about.
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/553962/RubberduckLog.txt)

**Comment by retailcoder** [comment]
I noticed this as well. The code pane doesn't get the focus for some reason - the selection is set, but the code pane doesn't have focus. You can verify this by activating the code pane without changing the selection with a click on the code pane's scrollbar.

**Comment by daFreeMan** [comment]
Indeed, that is a temporary workaround.

**Comment by retailcoder** [comment]
The `CodePane` wrapper implementation specifically addresses this, by systematically calling `ForceFocus` whenever `SetSelection` is called:

        private void SetSelection(int startLine, int startColumn, int endLine, int endColumn)
        {
            Target.SetSelection(startLine, startColumn, endLine, endColumn);
            ForceFocus();
        }

        private void ForceFocus()
        {
            Show();

            var window = VBE.MainWindow;
            var mainWindowHandle = window.Handle();
            var caption = window.Caption;
            var childWindowFinder = new NativeMethods.ChildWindowFinder(caption);

            NativeMethods.EnumChildWindows(mainWindowHandle, childWindowFinder.EnumWindowsProcToChildWindowByCaption);
            var handle = childWindowFinder.ResultHandle;

            if (handle != IntPtr.Zero)
            {
                NativeMethods.ActivateWindow(handle, mainWindowHandle);
            }
        }

...and it's only ever called from the wrapper's `Selection` setter:

        public Selection Selection
        {
            get { return GetSelection(); }
            set { SetSelection(value.StartLine, value.StartColumn, value.EndLine, value.EndColumn); }
        }

Given the `ForceFocus` method was merely *moved* (was formerly a `Microsoft.Vbe.Interop.CodePane` extension method IIRC) and not *modified*, and that it *generally* works, I feel the best we can do is this:

    if (handle != IntPtr.Zero)
    {
        NativeMethods.ActivateWindow(handle, mainWindowHandle);
    }
    else
    {
        System.Diagnostics.Debug.WriteLine("CodePane.ForceFocus() failed to get a handle on the MainWindow.");
    }
