### ISSUE TITLE
RubberDuck has encountered an error when Resolving declarations

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#2337]
Excel 2010, RD 2.0.9

Project compiled clean, then Ctrl-` to reparse. Hung on Resolving declarations for 10-15 seconds on only 2-300 LOC.

[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/561829/RubberduckLog.txt)

**Comment by retailcoder** [comment]
Does the project contain a UserForm?

**Comment by daFreeMan** [comment]
No.

Lots of cells, a couple hundred (max) lines of code, and a couple of MsgBoxen is it.

**Comment by retailcoder** [comment]
The log is ending with a failing `CodeExplorer.Commands.RemoveCommand.CanExecuteImpl`, trying to access `VBComponent.Type` threw a `COMException`. This runs in response to parse state changing to "Resolving declarations". Not sure why the same exception is thrown and logged multiple times though. Needs investigation.

**Comment by daFreeMan** [comment]
Glad #2338 was a duplicate and not 2 new errors.

**Comment by retailcoder** [comment]
Can you repro with 2.0.11?

**Comment by daFreeMan** [comment]
I would say no, I've been running 2.0.11 for a couple of days and haven't had any `errors`.
