### ISSUE TITLE
Rubberduck has encountered an error

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#2338]
Excel 2010, RD 2.0.9

I right clicked in the CE and immediately got the error. I right-clicked again, and the `Export` option is disabled (which is what I wanted to do).
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/562422/RubberduckLog.txt)

I closed Excel, reopened the XLTM & was able to export my code.

**Comment by retailcoder** [comment]
That's the same exception/bug as #2337
