### ISSUE TITLE
Array variables are not marked as such in Rubberduck toolbar

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#2348]
Declaring a string array doesn't reflect as being a string array in the Rubberduck toolbar.

![array](https://cloud.githubusercontent.com/assets/16574009/20049205/a8d4abac-a515-11e6-974e-0bc3d3fc0f91.png)

Arrays should appear as arrays, including their bounds (where defined) and Type.

**Comment by retailcoder** [comment]
I believe that is now fixed and released.

**Comment by retailcoder** [comment]
The bounds aren't rendered though.

**Comment by Vogel612** [comment]
IIUC we'd need locals evaluation and execution graph to properly render bounds, especially with runtime redimming to special bounds
