### ISSUE TITLE
Rubberduck in Excel XP gets stuck at *Loading references*, crashes on Inspections refresh

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#2351]
Rubberduck crashed the first time I opened and parsed with the latest build, although Excel/VBE were still stable.

Subsequent instances of Excel XP/VBE result in successful load of Rubberduck, but upon parse, status gets stuck at "Loading references". If I then press the refresh button in the Inspections window (as opposed to the button on the toolbar), Excel crashes.

**Comment by retailcoder** [comment]
Can you repro with #2372 merged?
