### ISSUE TITLE
Rubberduck won't work in Excel 2016

### ISSUE THREAD

**Issue by simplesolutionssas** [rubberduck-vba/Rubberduck#2352]
I uninstalled Rubberduck 1.4.3.0 today (using advanced uninstaller, to delete all traces), and then installed 2.0.9.0, but nothing worked. The installation was made with the administrative account. I also tried the 'Installing for non-admin users' procedure, with no success. 

I opened a file I've been working lately, which has 85 passing test cases, some TODOs and a couple of code inspection messages. None of these things show in the new version. Trying to refresh each of these panes won't help either (the code inspections panel shows a never ending progress indicator, but does nothing at the end, and the other two panes don't even show the progress indicator).  

I tried adding a new test module, but it wouldn't show in test explorer. I tried to add test cases to this new module, but was unable because the buttons are disabled. 

I also tried using Rubberduck with another file with some VBA code, and again, nothing worked. 

Finally, no logs were present in the AppData\Roaming\Rubberduck folder (which I take is the one where those should be created). 

Any ideas? 

Excel 2016 (16.0.7329.1017) 32 bits. 

ps. please let me know if you need further details.

**Comment by retailcoder** [comment]
There should be a *Rubberduck* commandbar docked at the top, featuring a "refresh" button. Rubberduck won't automatically launch a parse task at startup, because we found that the VBE loads its addins before it finishes constructing the object model for the opened projects, which lead to rather annoying startup crashes. So the first thing to do is to manually trigger the initial parse - if all goes well within a few seconds the Rubberduck commandbar's status button/label should say "Ready", and all the functionality should be there.

Was the initial parse triggered?

**Comment by retailcoder** [comment]
Logging gets very verbose, very fast, and so we've disabled it by default (we're going to change that next release). You can set the minimum log level from the "general settings" page of the settings dialog. "TRACE" being the most verbose, "FATAL" logging pretty much only critical exceptions.

**Comment by retailcoder** [comment]
We need to fix the toolwindows' "refresh" commands, they're not as instinctive as they should be - I'll have them work exactly like the "main" commandbar's refresh command  for 2.0.10, so that the initial parse can be triggered from the code explorer or inspection results toolwindows.

**Comment by Hosch250** [comment]
Oh boy, you had me spend hours disabling those when we detected that we were "up-to-date".  I knew it would come to this.

**Comment by carlossierra311** [comment]
Hi guys. Yes, IMHO, the initial refresh requirement is not very instinctive (I hadn't even noticed the refresh button in the toolbar). A naive question: would triggering the refresh when you open any of the Rubberduck toolwindows make sense (and avoid the problems you described above)? 

Anyway, I tried refreshing when opening the VBA window, and still nothing happens: the 'Loading references' text is displayed, and nothing is shown when I open the toolwindows, even after I hit refresh on them too. Here is the log (Trace level). 

For now, I'm going back to 1.4.3.0 agan :( 

[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/578402/RubberduckLog.txt)

**Comment by retailcoder** [comment]
Looks very much like #2351, should be fixed once we get the toolwindows' refresh command to be the same as the main commandbar's. I'm considering simply triggering the initial parse after a delay, as we had it in early 2.x releases.

**Comment by simplesolutionssas** [comment]
Thanks. Let me know if there's any other information I can provide...
