### ISSUE TITLE
Implement Interface refactor doesn't work for document-type classes

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#2356]
Document-type classes are valid interfaces too...

The RD refactoring *Implement Interface* doesn't implement any members, but does trigger a reparse (side-issue - Why a reparse if nothing was changed?).

```
Implements ThisWorkbook
Implements Sheet1
```

**Comment by retailcoder** [comment]
This should be a very easy fix.
