### ISSUE TITLE
Inital Parse hangs at "Loading References" Build 2.0.9

### ISSUE THREAD

**Issue by NotableAudio** [rubberduck-vba/Rubberduck#2361]
I had Build 1.4.3 working apart from a few parse errors here: #2360 

I took @retailcoder 's advice and updated to Build 2.0.9. Here are the summarized steps that I took:

1) Uninstall Build 1.4.3
2) Manually delete the associated registry files
3) Install Build 2.0.9 as an administrator
4) Checked for registries, install failed to create as admin
5) Launch MS Access Project VBE anyway, no Rubberduck menu item as expected.
6) Close Access
7) Manually inputted keys through regedit as listed on the installation page (but bypassing Powershell because they didn't appear in regedit when I did this through powershell the first time)
8) Open MS Access project
9) Launch VBE
10) Rubberduck listed in add-in manager as startup/loaded
11) Checked reference libraries, Rubberduck reference is enabled
10) Hit Refresh to begin initial parse

The first time I tried this it hung here for a couple of hours, but didn't have the log settings set properly. I eventually quit, uninstalled, and reinstalled using the same steps above. It's hung again at the same spot, and has been for 15 minutes or so already.

I set the log settings to "debug", cleared the file and reproduced the steps. Here is the log file:

[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/596037/RubberduckLog.txt)

This log was uploaded at 2016-11-16 17:07ish, so there is a gap in time from the last log entry to extracting the log file. I don't mind waiting for the process, but it never seems to finish. 

On further attempts the log hangs at the same point each time. I even renamed my module in case it didn't like the `PublicFunction` name, but to no avail.

Not sure if I did something wrong (I'm _very_ good at that :smile:) but any help is appreciated.

I am running W7 Pro 64-bit with MS Office 2010.

**Comment by retailcoder** [comment]
I think there's an issue with loading the COM types in the Rubberduck COM type library (damn ironic), leading to parser silently bailing out of "Loading references..." state.

Can you confirm things work if you remove the reference to `Rubberduck.tlb`?

If so, we have two things to fix: one - get the COM type loader to kick and scream its way to failure, and two - get the Rubberduck.tlb type library to stop blowing up the COM type loader.

Note, v2.x supports late-binding for unit testing now.

**Comment by NotableAudio** [comment]
That did the trick!

Unchecked Rubberduck in the References window

Parse completed in seconds, and I see all objects in the code explorer now.

Thanks for your help!

**Comment by retailcoder** [comment]
@NotableAudio I hope you enjoy 2.x, it's *packed* with TONS of new features (vs 1.4.3 anyway) - for example you can use the Code Explorer to organize your code modules into folders now. Feel free to poke around and mess with everything; again 2.0.9 has a few known bugs that have been fixed, and a few more that will be fixed before a "green" 2.0 release. Have fun!
