### ISSUE TITLE
Refactoring multiple variables caused broken code V2.0.9

### ISSUE THREAD

**Issue by NotableAudio** [rubberduck-vba/Rubberduck#2362]
I was refactoring a sub with a dozen or so variables and after a few of them it starts missing the mark. I waited for the parse to complete after each refactor. I noticed after the Nth refactor I suddenly had a new parse error. I have replicated the process and here is an example of the output:

**Refactors:**
D = dtmDate
job = intJobID
emp = intEmployeeID
shift = intShift

**Original concatenation:**
`...& "VALUES(#" & D & "#, " & job & ", " & emp & ", " & shift & ", "...`

**And after the fourth refactor I get an obvious parse error:**
`...& "VALUES(#" & dtmDate & "#, " & intJobID & ", " & intEmployeeIDintShift " & shift & ", "...`

In each instance it seemed to replace `& ",`  instead of the variable. It only appears when building a string, other lines of code for assigning values don't seem to be effected in the same way.

No issue for me, code review is planned anyway if I miss any corrections, just wanted to bring to your attention that it's breaking code.

I am running W7 & Office 2010 with Build 2.0.9

**Comment by retailcoder** [comment]
Thanks for reporting it. Is there a `For Each` loop involved by any chance? See #2276, #2319 and possibly also #2314.

**Comment by retailcoder** [comment]
That said... it looks like you're concatenating parameters into an SQL / INSERT command string; consider making a parameterized `Command` instead ;-)

See https://xkcd.com/327/ :wink:

**Comment by NotableAudio** [comment]
There is not a `For Each` loop involved. 

Yes, I need to protect against SQLi.  Being the sole dev and self-taught, there is a myriad of stuff I need to learn and incorporate. Hence downloading Rubberduck for code inspection etc. But not too bad for an accountant! :laughing: Thanks for pointing it out though!

**Comment by retailcoder** [comment]
Hmm if no `For Each` loop is involved then it looks like the parser state is holding on to some cached `IdentifierReference`  instances, leading the refactoring to see a reference to a variable in its old location.

> There are only two hard things in Computer Science: cache invalidation and naming things.
> 
> -- Phil Karlton

I bet *find all references* is reporting references in the wrong places, too.

**Comment by retailcoder** [comment]
Linking #2293
