### ISSUE TITLE
Inspection for assignment of return value does not recognize assignments delegated to another method.

### ISSUE THREAD

**Issue by MDoerner** [rubberduck-vba/Rubberduck#2365]
The code inspection for missing assignments to return values does not recognize the, admittedly rather unusual, situation that the assignment of the return value is delegated to another method via a ByRef parameter, as e.g. in the example below.

```vba
Private Function Class2_Foo4() As String
    Dim strMethodName As String
    strMethodName = "Foo4"
    baseMock.RegisterMethodCall strMethodName
    baseMock.AssignReturnValue Class2_Foo4, strMethodName
End Function
```

Here, `AssignReturnValue` assignes to its first argument based on the second argument and a stored mapping. 

```vba
Private Sub IMockBase_AssignReturnValue(ByRef ReturnValueVariable As Variant, ByVal MethodName As String)
    If HasObjectTypeReturnValue(MethodName) Then
        Set ReturnValueVariable = Self.ReturnValue(MethodName)
    Else
        ReturnValueVariable = Self.ReturnValue(MethodName)
    End If
End Sub
```

I guess that this issue is rather complicated to fix since, potentially, one would have to trace all ByRef arguments, possibly several calls deep. 

I actually think that this is not of major concern as one should know what one is doing if one assignes the return value via indirection. I just wanted to mention it anyway since I just stumbled upon it.

**Comment by retailcoder** [comment]
Ha, nice catch!

**Comment by retailcoder** [comment]
The "ignore once" quick-fix works as intended, does it?

**Comment by MDoerner** [comment]
In the code inspections window, clicking on Fix while having this result selected does not do anything.
Adding the annotation manually works, though.

Regarding the original issue, I thought about it again and came to the conclusion that finding out whether there is a delegated assignment is impossible in general: to know whether an assignment takes place one needs to know the concrete class implementing the method that potentially performs the assignment. This is impossible if dependency injection is used.

**Comment by retailcoder** [comment]
@MDoerner we can't tell for sure, but we could certainly detect that the variable is passed as a `ByRef` argument, and *not* issue a result then. Would that be reasonable?

**Comment by retailcoder** [comment]
Wait a minute, not the *variable*, the function identifier...

**Comment by MDoerner** [comment]
To be honest, I think the best way to go is show the inspection result and let whoever wrote to code use the ignored once quickfix. So, this issue being closed now is just fine.
