### ISSUE TITLE
Resolver error if modeless UserForm is open during parse

### ISSUE THREAD

**Issue by comintern** [rubberduck-vba/Rubberduck#2369]
This is a bit of the corner case, but I was messing around with a modeless UserForm and had it open when I hit the "Parse all open projects" button.  The only code was as follows:

```
'In Sheet1:
Public Sub DisplayUserForm1()
    UserForm1.Show vbModeless
End Sub
```

```
'In UserForm1:
Private Sub UserForm_Click()
    Unload Me
End Sub
```

No controls on UserForm1, and it resolves fine if the form isn't open or if there haven't been changes to the UserForm since the last parse.   

Error log:

> 2016-11-19 14:00:45.3402;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'ThisWorkbook' state is changing to 'Pending' (thread 10);
> 2016-11-19 14:00:45.3860;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'Sheet1' state is changing to 'Pending' (thread 10);
> 2016-11-19 14:00:45.3919;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'UserForm1' state is changing to 'Pending' (thread 10);
> 2016-11-19 14:01:05.6556;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'UserForm1' state is changing to 'Parsing' (thread 8);
> 2016-11-19 14:01:05.6556;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'Sheet1' state is changing to 'Parsing' (thread 12);
> 2016-11-19 14:01:05.6917;DEBUG;Rubberduck.App;App handles StateChanged (Parsing), evaluating menu states...;
> 2016-11-19 14:01:06.4866;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'ThisWorkbook' state is changing to 'Parsing' (thread 6);
> 2016-11-19 14:01:11.7816;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'ThisWorkbook' state is changing to 'Parsed' (thread 6);
> 2016-11-19 14:01:11.9280;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'ThisWorkbook' state is changing to 'ResolvingDeclarations' (thread 9);
> 2016-11-19 14:01:12.2259;DEBUG;Rubberduck.App;App handles StateChanged (ResolvingDeclarations), evaluating menu states...;
> 2016-11-19 14:01:12.8343;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Creating declarations for module VBAProject.ThisWorkbook.;
> 2016-11-19 14:01:13.6712;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;941ms to resolve declarations for component ThisWorkbook;
> 2016-11-19 14:01:55.2650;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'Sheet1' state is changing to 'Parsed' (thread 12);
> 2016-11-19 14:01:55.3021;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'Sheet1' state is changing to 'ResolvingDeclarations' (thread 11);
> 2016-11-19 14:01:55.3187;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Creating declarations for module VBAProject.Sheet1.;
> 2016-11-19 14:01:55.3763;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;57ms to resolve declarations for component Sheet1;
> 2016-11-19 14:02:07.0277;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'UserForm1' state is changing to 'Parsed' (thread 8);
> 2016-11-19 14:02:07.0521;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'UserForm1' state is changing to 'ResolvingDeclarations' (thread 10);
> 2016-11-19 14:02:07.0618;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Creating declarations for module VBAProject.UserForm1.;
> 2016-11-19 14:02:07.1077;ERROR;Rubberduck.Parsing.VBA.RubberduckParser;Exception thrown acquiring declarations for 'UserForm1' (thread 10).;System.NullReferenceException: Object reference not set to an instance of an object.
>    at Rubberduck.VBEditor.SafeComWrappers.ComWrapperEnumerator`1..ctor(IEnumerable source, Func`2 itemWrapper) in c:\Dev\Rubberduck\Rubberduck.VBEEditor\SafeComWrappers\ComWrapperEnumerator.cs:line 16
>    at Rubberduck.VBEditor.SafeComWrappers.VBA.Controls.System.Collections.Generic.IEnumerable<Rubberduck.VBEditor.SafeComWrappers.Office.Core.Abstract.IControl>.GetEnumerator() in c:\Dev\Rubberduck\Rubberduck.VBEEditor\SafeComWrappers\VBA\Controls.cs:line 29
>    at Rubberduck.Parsing.Symbols.DeclarationSymbolsListener.DeclareControlsAsMembers(IVBComponent form) in c:\Dev\Rubberduck\Rubberduck.Parsing\Symbols\DeclarationSymbolsListener.cs:line 168
>    at Rubberduck.Parsing.Symbols.DeclarationSymbolsListener..ctor(RubberduckParserState state, QualifiedModuleName qualifiedName, ComponentType type, IEnumerable`1 annotations, IDictionary`2 attributes, Declaration projectDeclaration) in c:\Dev\Rubberduck\Rubberduck.Parsing\Symbols\DeclarationSymbolsListener.cs:line 119
>    at Rubberduck.Parsing.VBA.RubberduckParser.ResolveDeclarations(IVBComponent component, IParseTree tree) in c:\Dev\Rubberduck\Rubberduck.Parsing\VBA\RubberduckParser.cs:line 571
> 2016-11-19 14:02:07.1351;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'UserForm1' state is changing to 'ResolverError' (thread 10);
> 2016-11-19 14:02:07.1419;DEBUG;Rubberduck.App;App handles StateChanged (ResolverError), evaluating menu states...;
> 2016-11-19 14:02:07.2806;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;217ms to resolve declarations for component UserForm1;

**Comment by ThunderFrame** [comment]
what a surprise to find you in the corner.

**Comment by Stevefb** [comment]
Hi guys - this might explain some of my issues. Will try to investigate
further.

**Comment by retailcoder** [comment]
> *it resolves fine if the form isn't open or if there haven't been changes to the UserForm since the last parse.*

The former doesn't surprise me; that's the parser noticing the module's `ContentHash` matches the previous parse's hash. The latter is irritating though... do you mean "open" as in, *runtime open* or *designer open*? Because the parser *does* get ahold of the designer to create declarations for all form controls... but even the VBE itself can't open the designer when a form is displayed (at runtime). ...are we not blocking parse unless the VBE is known to be in design mode?

**Comment by comintern** [comment]
Open as in runtime open. I'm a bit off the grid right now, but IIR the VBE doesn't behave as if it's in runtime mode when a modeless form is running. That is, you can do things that you normally can't while it's in break mode (like delete a module). If you make any changes to the code of the running form, the running instance immediate closes.

**Comment by retailcoder** [comment]
Fixed. This part of the stack trace was key:

```
2016-11-19 14:02:07.1077;ERROR;Rubberduck.Parsing.VBA.RubberduckParser;Exception thrown acquiring declarations for 'UserForm1' (thread 10).;System.NullReferenceException: Object reference not set to an instance of an object.
at Rubberduck.VBEditor.SafeComWrappers.ComWrapperEnumerator1..ctor(IEnumerable source, Func2 itemWrapper) in c:\Dev\Rubberduck\Rubberduck.VBEEditor\SafeComWrappers\ComWrapperEnumerator.cs:line 16
```

`ComWrapperEnumerator` line 16 is the constuctor - more specifically, the instruction that calls `source.GetEnumerator()`; the [wrong] assumption here was that `source` would never possibly be `null`.

The patch/fix therefore verifies if `source == null` first, and assigns the `_internal` enumerator to `Enumerable.Empty<TWrapperItem>().GetEnumerator()`; as a result the NRE is no longer thrown, not only when iterating a `Controls` collection, but also in *any* collection type that spawns a `ComWrapperEnumerator`.
