### ISSUE TITLE
Identifier names with special characters should display with their square-brackets

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#2373]
An evil identifier like this:

```vb
Enum fizz
  [Dim Option(Base 0 To Base 1) As Explicit Binary Case Do : Loop] = 4
End Enum

Sub foo()
    Debug.Print [Dim Option(Base 0 To Base 1) As Explicit Binary Case Do : Loop]
End Sub
```

Appears like this in the toolbar (yes, it truncates):
![text](https://cloud.githubusercontent.com/assets/16574009/20520164/df3d4da8-b0f9-11e6-933e-231fef7d4012.png)

And like this in the Inspections window (yes, those inspections are ALL incorrect:
![inspect](https://cloud.githubusercontent.com/assets/16574009/20520198/ff6fb8c2-b0f9-11e6-82ba-7db6169a73f3.png)

**Comment by retailcoder** [comment]
that one looks like it's fixed already
