### ISSUE TITLE
Split Mismatched Input produces parsing error

### ISSUE THREAD

**Issue by LarrySDare** [rubberduck-vba/Rubberduck#2389]
This piece of code produces a Mismatched Input parsing error.

```
Sub TestSplit
dim s as string 
dim t as string
s = "A00010=45 Days until end, 12/23/2015
t = split(s,"=")(0)   ' Error occurs on this line
debug.print "Value of s: " & t
End Sub
```

**Comment by retailcoder** [comment]
I suppose you're using v1.4.3? This (and many other) parser issue has been fixed already, and released under the v2.x "pre-release" tags.

v2.0 currently still has issues with properly shutting down, but if you're okay with that you can try the latest release v2.0.9, or wait for 2.0.10 (should be released soon), or a "green" 2.x (will release as soon as Rubberduck correctly tears down).

**Comment by retailcoder** [comment]
Alternatively, you can split the function result and the index access into separate instructions. This will parse fine with v1.4.3:

    Dim result
    result = Split(s, "=")
    t = result(0)
