### ISSUE TITLE
Indent First Comment Block setting not honored for Enum

### ISSUE THREAD

**Issue by CHR-IS-B** [rubberduck-vba/Rubberduck#2396]
I noticed the indenter doesn't honor the setting to indent the first comment block inside Enums.  My preference is that indenting in Enums be the same as in Subs and Functions.

Here's an example.  With the indent first comment block setting on, it looks like this:

```
Public Enum rowOrColumnOption
    ' Custom variable type, used to limit allowed values in a custom
    ' function parameter to either r (row) or "c" (column).
    r = 0: Row = 0
    c = 1: Column = 1
End Enum
```

I would prefer it look like this:

```
Public Enum rowOrColumnOption
' Custom variable type, used to limit allowed values in a custom
' function parameter to either r (row) or "c" (column).
    r = 0: Row = 0
    c = 1: Column = 1
End Enum
```

**Comment by retailcoder** [comment]
The *indent first comment block* really applies to procedure bodies, as the checkbox position implies in the settings dialog; as far as I can tell whether that box it checked or not has no bearing on how the first comment block in an `Enum` member is indented.

![image](https://cloud.githubusercontent.com/assets/5751684/20847928/0daa85a6-b89e-11e6-87b4-2c87e0cf6a04.png)

If I understand correctly, by un-checking the *Indent first comment block* box, the `' some comment` comment under `TestEnum` should follow the alignment of the `'SMART INDENTER` comment block under `ExampleProc`:

![image](https://cloud.githubusercontent.com/assets/5751684/20848024/5a5a0ae8-b89e-11e6-90b8-4c7975fe79fb.png)

I think this should be a separate/new setting under *Indent Options*, separate from the *Indent procedure body* setting. Something like:

> *Indent comments in Enum and Type blocks like in procedures*

Thoughts?

**Comment by CHR-IS-B** [comment]
An additional setting would do the trick...maybe others want different indent settings for procedure bodies and Enum and Type blocks.  However for me it makes no difference for me either way.
