### ISSUE TITLE
Get SpecialFormsDeclarations out of DebugDeclarations 

### ISSUE THREAD

**Issue by Vogel612** [rubberduck-vba/Rubberduck#2414]
> The SpecialFormDeclarations being in DebugDeclarations is likely technical debt indeed; I don't see a reason other than historical for it to be there.

See #2413 for further information:

**Comment by MDoerner** [comment]
I think I can do this tomorrow. There are only two places where the `DebugDeclarations` are injected, `ParserState` and `MockParserState`. So extracting the `SpecialFormsDeclarations` into their own class and injecting that as well should be easy.

**Comment by ThunderFrame** [comment]
@MDoerner Are you aware of the dev [chat](http://chat.stackexchange.com/rooms/14929/vba-rubberducking) where we <s>swap war stories</s>, <s>hack our way into the VBE</s> make RD better? Come join the chat if you have any questions or comments. If you don't have a reputation of at least 20 on CodeReview, you'll need to get @retailcoder to add you in.
