### ISSUE TITLE
Indenter Settings: Import from File

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#2420]
Per a [dicsussion in the RubberduckWeb repo](https://github.com/rubberduck-vba/RubberduckWeb/issues/21#issuecomment-266811425), let's add a button to import indenter settings from a .xml file on disk. This will allow website users to export indenter settings from the website, and use the same settings on their desktop ducky.

**Comment by EBrown8534** [comment]
Likewise, we should have an Export button on RubberDuck, so that we can put an Import button on the website.
