### ISSUE TITLE
GetSelectionText logic needs a refactor

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#2422]
Resolving this code:

```vb
Dim shp As Shape
Set shp = Sheet1.Shapes(1)
Debug.Print shp.Type = msoAutoShape
```

And then inspecting the `msoAutoShape` shows the identifier is:

`MSO.DLL;Office.Office.msoAutoShape (enum member: Long)`

When it should probably be:
`MSO.DLL;Office.MsoShapeType.msoAutoShape (enum member: Long)`

---

The logic for this is in `App.GetSelectionText`. Arguably it doesn't even belong there, and the method's logic is an ugly tangled mess of `if..else if` blocks and duplicated code, and at the end of the day it results in strings that aren't as descriptive as they could be.

This ..thing needs to be extracted elsewhere, into its own class perhaps, and `App` probably doesn't need to care about it - the formatter basically only needs a `Declaration` object and, in case the declaration is `null`, the active code pane, to get the `QualifiedSelection` when that active code pane isn't `null`.

The logic should be something like this:

 - When there is no active code pane, return an empty string
 - If the declaration is `null`, return the string representation of the `QualifiedSelection` in the active code pane.
 - If the declaration is not null, things get fun:
  - If it's a built-in declaration, we want a general format like:

        Selection | LibraryName;QualifiedMemberName (DeclarationType: AsTypeName)

  - If it's a user declaration, we want a general format like:

        Selection | QualifiedMemberName (DeclarationType: AsTypeName)

The fun part is, well, that `QualifiedMemberName`, for an `Enum` or `UDT` member, needs to be tweaked to display the `ParentDeclaration.IdentifierName` instead of the module name (which for a built-in enum would match the project name, as reported above).

Another tweak: modules should display their `QualifiedModuleName` instead, because the `MemberName` would duplicate the class name. And the `AsTypeName` of a module is redundant, too, and of course a `Sub` procedure doesn't even have an `AsTypeName`... and then a variable whose type isn't declared, but *hinted* with a `TypeHint` would have to display its type name just as seamlessly as a variable with an actual declared type.

...Also, if we're looking at a `ConstantDeclaration` or anything that has a known value, it would be nice to display it there too.

**Comment by retailcoder** [comment]
That's purely a UI issue. The built-in `Enum` and `UserDefinedType` declarations don't have a module, so when we create them we fake a module name that's named after the type library.

It's really just the string representation of `QualifiedModuleName` that needs a tweak for these built-in declarations.

**Comment by retailcoder** [comment]
hmm looks like this is an opportunity to improve the representation of user-code enums too.

**Comment by retailcoder** [comment]
Okay, this whole `GetSelectionText` thing is a bloody mess. Adding [tech-debt] and editing the issue.

**Comment by retailcoder** [comment]
![image](https://cloud.githubusercontent.com/assets/5751684/21170687/d4d8bd1a-c194-11e6-84b9-40041f6a667c.png)

![image](https://cloud.githubusercontent.com/assets/5751684/21170699/e4ca1bec-c194-11e6-848d-e1e4c7f32cd8.png)
