### ISSUE TITLE
Move as much logic as possible from Test Explorer to Presenter

### ISSUE THREAD

**Issue by ckuhn203** [rubberduck-vba/Rubberduck#243]
Pull Request #242 went a long way toward cleaning up the Test Explorer, but there's still a lot of logic bound up in the view that should probably be in the presenter.

For example, the logic in the `Control` (i.e. view) here should probably be in the presenter.

        public void RunTests(IEnumerable<TestMethod> tests)
        {
            Control.ClearResults(); 
            Control.SetPlayList(tests);
            Control.ClearProgress();
            _testEngine.Run(tests);
        }

**Comment by Hosch250** [comment]
Is this done now that this was re-written in WPF?

**Comment by retailcoder** [comment]
OMG blast from the past! Definitely @Hosch250, *definitely*!
