### ISSUE TITLE
Insufficient memory

### ISSUE THREAD

**Issue by halcwb** [rubberduck-vba/Rubberduck#2439]
I ran into an Insufficient memory exception. The Rubberduck log doesn't show a trace of this. It shows a Microsoft .NET Framework dialog box with the exception message:

> See the end of this message for details on invoking 
> just-in-time (JIT) debugging instead of this dialog box.
> 
> ************** Exception Text **************
> System.OutOfMemoryException: Insufficient memory to continue the execution of the program.
>    at System.Windows.Media.Composition.DUCE.Channel.SyncFlush()
>    at System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet)
>    at System.Windows.Interop.HwndTarget.UpdateWindowPos(IntPtr lParam)
>    at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
>    at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
>    at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
>    at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
>    at MS.Win32.SafeNativeMethods.SetWindowPos(IntPtr hWnd, IntPtr hWndInsertAfter, Int32 x, Int32 y, Int32 cx, Int32 cy, Int32 flags)
>    at System.Windows.Forms.Integration.ElementHost.SetHWndSourceWindowPos()
>    at System.Windows.Forms.Integration.ElementHost.WndProc(Message& m)
>    at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
>    at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
>    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by retailcoder** [comment]
Wah, WTF! Is there a memory leak in WPF interop?

**Comment by halcwb** [comment]
I'm sorry for this. Rubberduck is in itself an excellent and much needed tool!

**Comment by retailcoder** [comment]
Ok, so we have a repro with a *truckload* of inspection results; the inspection completes (eventually), but the grid blows up with an OOM exception trying to display all the results.

How about we limit the displayed results to, say, 255 per inspection?

**Comment by retailcoder** [comment]
I don't like setting an arbitrary limit like that though. The grid will perfectly handle 5000 results of one inspection type, but then if all 30-some inspections issue 5000 results then there will be a problem.

Not sure what the best UX would be.

**Comment by Vogel612** [comment]
@retailcoder where exactly do we OOM? I daresay it's just when displaying the results. As such it might be advisable to limit the number of total results before limiting the number of results per inspection. 

it might be conceivable to have a "rolling" limit for inspection results depending on the ratios of actually reported inspectons.

**Comment by retailcoder** [comment]
@Vogel612 exactly - it's the grid that can't handle that many results. However the inspections run asynchronously, and the results are sorted in the XAML, so if we limit the total number of results there's a reasonable chance that we won't be able to display a result for all triggered inspections.

I think we could make the `Inspector` a bit smarter, and exclude individual results from inspections that spawn more than, say, 1024 results. Yet we could tweak the XAML template and introduce some `AggregateInspectionResult` type that would still show up, and look something like this:

> (warning) Implicit reference to ActiveSheet: 14,732 results  [disable this inspection]

Aggregated results would have more limited functionality (no double-click navigation (, no quickfixes?), but we could still show the inspection's meta-description in the bottom panel), but then we wouldn't blow up the GroupingGrid, and we'd still be reporting all issues.

**Comment by comintern** [comment]
@Vogel612 - When I was testing this, RD didn't flinch at generating 30,000 inspection results.  It obviously _took_ a while, but the memory overhead for a result object isn't really that high. With a reasonably sized inspection window, each result is being rendered to a ~800px by 27px bitmap as it's drawn to the form. That's ~86kb per result pushed at the GDI.  My understanding of how a scrollable WPF container works is that it actually renders the entire thing and then windows it using the scrollbar.  So 30K results comes out to right around 2.4GB for that control _alone_.

**Comment by PeterMTaylor** [comment]
Just thinking here folks. So we could setup to have a summary of inspections (a listing totals per inspection type) and somewhere in the grid the individual "detail" which potentially like Comintern  indicated up to 30,000 equal 2.4 Gb, would the settings be a good place to put some limit of say 500 as default at any one time similar to how database admin can restrict the fetch of memory pages to improve network performances for databases.

**Comment by retailcoder** [comment]
@PeterMTaylor I like the idea of adding that arbitrary limit to the *inspection settings* configuration page.

**Comment by ThunderFrame** [comment]
![zen](https://cloud.githubusercontent.com/assets/16574009/21368154/67e0fa08-c755-11e6-955e-281102298435.png)

**Comment by PeterMTaylor** [comment]
Nice @ThunderFrame so I get to select strawberry flavour  for small tweaks to see if it works with my user interface  or a strong chocolate flavour for an all nighter major code change as a patch, so each flavour changes the default set arbitrary limit. Cool 😎

**Comment by Hosch250** [comment]
OK, before you do anything here, I want to stick my oar in.  The *first* step, of course, is the figure out what is eating the memory.  I don't know for sure, but is it possibly the quick fixes?  Remember that it is on the books to generate the quick fixes lazily, so...

**Comment by retailcoder** [comment]
@Hosch250 the OOM stack trace is pretty explicit about what's blowing up.

**Comment by Hosch250** [comment]
NVM.

**Comment by retailcoder** [comment]
PR #2502 (and thus #2443) should work around this issue in a rather elegant way. Considering it fixed for now.

**Comment by retailcoder** [comment]
![image](https://cloud.githubusercontent.com/assets/5751684/21795822/ad93ab22-d6d2-11e6-9010-404dddf7671c.png)

the default quick-fix for an inspection can be executed (double-click and "fix" both only apply to the first result in the aggregate), and if the default fix can be executed in the project or module, the options are available - here I've just fixed 250 inspection results with 1 click, across 10 lines of code in the module:

![image](https://cloud.githubusercontent.com/assets/5751684/21795851/ddc801b2-d6d2-11e6-8851-0f7c55e79d8e.png)

It's pretty fun to watch actually. Makes me wish there was an `Application.ScreenUpdating` to toggle off...
