### ISSUE TITLE
Cannot disable implicit references inspection

### ISSUE THREAD

**Issue by halcwb** [rubberduck-vba/Rubberduck#2440]
In my project I use workbook scoped named ranges. However, Rubberduck upon code inspection generates tons of warnings because of this. I do not seem to be able to disable this inspection:

<img width="2009" alt="rubberduckdisableinspection" src="https://cloud.githubusercontent.com/assets/683631/21324283/6108883e-c621-11e6-9e3a-82397c2b4c0f.png">

**Comment by retailcoder** [comment]
Ok that one's weird. Inspections set to `DoNotShow` don't even run.... except, I just reproduced the issue off the current build. Something isn't right. Possibly has to do with the fact that it's one of the few host-specific inspections.

**Comment by retailcoder** [comment]
Looking at [Inspector.cs](https://github.com/rubberduck-vba/Rubberduck/blob/next/RetailCoder.VBE/Inspections/Concrete/Inspector.cs#L75) I'm puzzled about how that is even possible.

````csharp
var inspections = _inspections.Where(inspection => inspection.Severity != CodeInspectionSeverity.DoNotShow)
    .Select(inspection =>
        Task.Run(() =>
        {
            token.ThrowIfCancellationRequested();
            var inspectionResults = inspection.GetInspectionResults();
                            
            foreach (var inspectionResult in inspectionResults)
            {
                allIssues.Add(inspectionResult);
            }
        }, token)).ToList();
````

Definitely needs a fix before next release.

**Comment by retailcoder** [comment]
@halcwb how many results is it spawning? Something tells me this might possibly have something to do with #2439 ...

**Comment by retailcoder** [comment]
The settings are retrieved using the localized inspection description. Needs to use the inspection's `Name` instead.
