### ISSUE TITLE
ConfigurationLoader's constructor is a problem

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#2449]
The constructor for `ConfigurationLoader` needs its parameters made optional, so that adding arguments no longer breaks 40+ tests. At least as a first step. Next step would be to refactor the settings API so that perhaps we don't need to mock `ConfigurationLoader` at all in the tests.

**Comment by comintern** [comment]
Related: #2240

**Comment by rkapka** [comment]
@retailcoder Could you tell me a little bit more what you mean by

> Next step would be to refactor the settings API so that perhaps we don't need to mock ConfigurationLoader at all in the tests.

?

**Comment by rkapka** [comment]
I am trying to tackle this issue and optional parameters are not an option, because Moq doesn't support them - you still need to provide all arguments when creating a mock. So I decided to go full-way here, but I don't understand what needs to be done 😀

**Comment by retailcoder** [comment]
@rkapka I have to verify... might not be relevant anymore.

**Comment by rkapka** [comment]
@retailcoder Thanks for the very quick response. By the way, at this time only 5 or 6 tests break when another parameter is added to the constructor, so it's not **that** bad...

**Comment by retailcoder** [comment]
I think we can live with that then... no?

**Comment by rkapka** [comment]
Sure. I'm closing the issue.
