### ISSUE TITLE
Rubberduck disappeared

### ISSUE THREAD

**Issue by halcwb** [rubberduck-vba/Rubberduck#2450]
After using Rubberduck successfully in Excel 2013. After some time Rubberduck suddenly was gone from the add-ins. I definitely didn't do anything to remove or uninstall Rubberduck. It just wasn't there anymore in Excel. Looking in the list of installed programs, it is still there. I have added my log file.
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/668421/RubberduckLog.txt)

And then, after a restart (had to install updates) of Windows, it reappeared??

**Comment by ThunderFrame** [comment]
Does Rubberduck appear in the list of available addins in the VBE's add-in manager? It may be that you just need to re-enable Rubberduck to load at startup, and that is done using the VBE's add-in manager, or in the registry.

**Comment by halcwb** [comment]
No, I checked the add-in manager. There was no Rubberduck. But as I added to my issue, after a restart of Windows it reappeared as an add-in. Strange!

**Comment by Vogel612** [comment]
I'm tempted to mark this as status-norepro since the behaviour was intermittent and was fixed with an OS restart.
