### ISSUE TITLE
Renaming funtion name messes up local variable names

### ISSUE THREAD

**Issue by halcwb** [rubberduck-vba/Rubberduck#2451]
Somehow, renaming a public function name messed up local variable names. After every rename, I make sure that Rubberduck is refreshed. Still this problem occurred, resulting in a difficult mess trying to figure out what the original code looked like ;-(.

It pasted a new function name right into an existing local variable name and did not change the function name in that same procedure as the local variable name.

**Comment by halcwb** [comment]
Renaming feature suffers some serious issues:

1. It's slow, really slow. For example renaming 10 procedure or function names takes about 5 minutes.
2. It's very buggy, see the problem above and:

<img width="1065" alt="rubberduckrename" src="https://cloud.githubusercontent.com/assets/683631/21571063/de5056e8-cecb-11e6-97b2-ba98485fe42b.png">

I tried to rename "strFileName", but somehow Rubberduck thinks I am in the shtPatData and I want to rename that sheet name. Unfortunately, the renaming feature is barely useful this way.

**Comment by Hosch250** [comment]
Is this 1.4.3 or 2.0rc?  We fixed thousands of bugs from 1.4.3 in 2.0, so this may not be an issue any more.

**Comment by ThunderFrame** [comment]
Looks like 2.x given the Rubberduck statusbar.

**Comment by Hosch250** [comment]
Ah, you're right.

**Comment by halcwb** [comment]
Sorry, this is the 2.0.9 RC version. I use it with MS Office 2013.

**Comment by comintern** [comment]
Pretty sure the issue on this is in `RubberduckParserState.FindSelectedDeclaration` - overlapping declarations are using a naive approach based on the location of the selection. More correct behavior would be to find all of the overlapping declarations and select the one with the smallest scope.

**Comment by retailcoder** [comment]
Pretty sure this is fixed by now. Refactor/Rename was essentially rewritten since 2.0.9, and performance dramatically improved since then as well.

**Comment by retailcoder** [comment]
Yup, consistently using the ModuleRewriters definitely fixed this.
