### ISSUE TITLE
Error renaming module

### ISSUE THREAD

**Issue by halcwb** [rubberduck-vba/Rubberduck#2453]
I ran into the following error trying to rename a module ModGlobal to ModConst:
<img width="1047" alt="rubberduckrenameerror" src="https://cloud.githubusercontent.com/assets/683631/21424227/a748af78-c841-11e6-8691-f66765359624.png">

And the logfile: 
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/668616/RubberduckLog.txt)

**Comment by halcwb** [comment]
After this error, Rubberduck disappeared again from Excel, see issue: https://github.com/rubberduck-vba/Rubberduck/issues/2450

**Comment by Vogel612** [comment]
This duplicates issue #2098
