### ISSUE TITLE
Cannot install Rubberduck after removing other version

### ISSUE THREAD

**Issue by halcwb** [rubberduck-vba/Rubberduck#2454]
I was using the latest version of Rubberduck (version 2.0.9), however, due to the number of issues I had, I tried and remove this version and install the latest stable version (1.4.3). This resulted in:

<img width="402" alt="rubberducknotloading" src="https://cloud.githubusercontent.com/assets/683631/21425388/23133f0e-c849-11e6-9e16-e20e7b98afc1.png">

It also left Excel completely nonreactive.

**Comment by halcwb** [comment]
So, I did some more cleaning up after Rubberduck uninstall. I removed the app data roaming Rubberduck folder. This solved my issue. Seems that the uninstall procedure needs to take care of this.

**Comment by comintern** [comment]
Without checking, I'd guess that this is due to rubberduck.config not being removed\over-written. A log file with an unexpected format is handled in the current builds. See #1336 et.al.
