### ISSUE TITLE
Parse errors in stable 1.4.3 version

### ISSUE THREAD

**Issue by halcwb** [rubberduck-vba/Rubberduck#2455]
Trying the 'stable version', I immediately ran into:

<img width="957" alt="rubberduckparseerror" src="https://cloud.githubusercontent.com/assets/683631/21425629/ae60b194-c84a-11e6-9bd4-d026a35c4041.png">

The window parse error shows an error message, but it is impossible to copy it or find a log for it.

**Comment by halcwb** [comment]
I think it has something to do with trying to rename a procedure that is being used in code as:

Call ProcFooBar

**Comment by retailcoder** [comment]
Hmm, 1.4.3 is some 5K commits behind the current build; the entire parser, resolver, UI and application architecture have been rewritten or heavily refactored since. I need 2.0.10 to be a "green" release ;-)

**Comment by retailcoder** [comment]
I need to dig up the issue#, but this is most certainly related to the parser not handling array/subscript or member access on function return values, requiring an intermediate variable to hold the return value, e.g.

    Dim foo
    Set foo = Range("foobar")
    foo.Value = "123"

**Comment by retailcoder** [comment]
Ref. #861, #900, #961
