### ISSUE TITLE
Find references shows duplicates

### ISSUE THREAD

**Issue by halcwb** [rubberduck-vba/Rubberduck#2460]
When I try to find all references to a sheet object, it shows many duplicate references:

<img width="812" alt="rubberduckduplicaterefs" src="https://cloud.githubusercontent.com/assets/683631/21467295/c76fd742-c9e8-11e6-86ca-5e4ac24c9856.png">

**Comment by retailcoder** [comment]
Ah, that's #1572 - each dupe is an `IdentifierReference` that's created against `shtPatData` for each member access through a `With` block.
