### ISSUE TITLE
RD's log file should report the build number.

### ISSUE THREAD

**Issue by comintern** [rubberduck-vba/Rubberduck#2461]
This _may_ only be helpful for ERROR level logging, but it's currently difficult to tell from log files attached to issues what build they apply to.  Instead of relying on users to supply this information (it isn't obvious from the "submit new issue" form that this might be helpful), that should be obvious from just examining the log.

This has (at least) 2 benefits:

First and most obvious, it makes it possible to determine if an issue is unreproducible because it's been **_fixed_**. 

Second, it makes it possible to determine if an issue is actually a _regression_ instead of a duplicate.

**Comment by retailcoder** [comment]
FWIW I tried using NLog's `{assembly-version}` output formatter for this, but it doesn't work because we're a dll - so it can't quite be done by tweaking the nlog.config xml, it needs to be configured at runtime.
