### ISSUE TITLE
Public Field Breaks Encapsulation inspection suggestion is unhelpful in standard modules

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#2467]
In a standard module, in the declarations section, `Public x as New Excel.Application` triggers the "public field breaks encapsulation" inspection. "Consider exposing a property" doesn't seem like a valid/thorough suggestion, as standard modules can't have properties.

I guess the field could be moved to a predeclared class, and then exposed as a property?

**Comment by MDoerner** [comment]
Alternatively, one could expose the public field like a property but with a `GetX` function and a `SetX` sub.

**Comment by comintern** [comment]
Actually, I'm torn on this given that standard modules *can* have properties. My stance is that a "static" Module property would actually be better practice than exposing a global variable, in that it _forces_ you to qualify it with the namespace.  This prevents variables declared as public globals from polluting the namespace of their project.  If there is a quick-fix for this, I'd propose treating it exactly the same way as a class:

```
'In Module1
Public foo As Long   '<--*should* trigger the inspection.
```
```
'Somewhere else
Sub Bar()
    foo = 42
    Debug.Print foo
End Sub
```

What I'd consider better coding style:

```
'In Module1
Private foo As Long

Public Property Get GlobalFoo() As Long
    GlobalFoo = foo
End Property

Public Property Let GlobalFoo(inFoo As Long)
    foo = inFoo
End Property
```
```
'Somewhere else
Sub Bar()
    Module1.GlobalFoo = 42
    Debug.Print Module1.GlobalFoo
End Sub
```
The rough OOP translation here would be a stateful member of a static class.

**Comment by retailcoder** [comment]
@comintern you had me at *it forces you to qualify it with the namespace* :-) 👍

**Comment by ThunderFrame** [comment]
Indeed, they *can* have Properties, but I always forget that they can :-/

**Comment by CHR-IS-B** [comment]
> @comintern you had me at _it forces you to qualify it with the namespace_ :-)

I like the idea of qualifying the namespace, but how does this _force_ me to do so?  Even in another module, I can still use `GlobalFoo` without being forced to qualify it as `Module1.GlobalFoo`.

**Comment by bclothier** [comment]
That'd need to be its own inspection, I think. `UnqualifiedCallInspection` or something like that. Not exactly "forcing" but at least it'll call your attention to a potential problem.

If you want to be forced, create a 2nd module, name it `YouForgotToDisambiguate` and create fields with same names. Then compiler will complain about ambiguous names when you use unqualified `GlobalFoo` in other modules. 😆
