### ISSUE TITLE
Initial Install Fails to load

### ISSUE THREAD

**Issue by Bullfrog1234** [rubberduck-vba/Rubberduck#2473]
I have Excel 2016, new install of your add-in, no other add-ins were operating.

Produces the following error on load of the VBE window, which I don't understand. Never been able to get it to work

![image](https://cloud.githubusercontent.com/assets/24860613/21580555/e954ca72-d053-11e6-8b9c-33735c3832ea.png)

Thanks Bullfrog

**Comment by Vogel612** [comment]
Seems related to #2385 the Excel version is the same, too... What build are you using? Could you please attach the logfile generated by Rubberduck from `C:\Users{username}\AppData\Roaming\Rubberduck\Logs`? Thanks

**Comment by Bullfrog1234** [comment]
V2.0.9 also same with V2.0.8

Also V1.4.3 failed for different reasons, It just crashes when try to do anything.

Tried a few uninstalls and reinstalls first before posting so quite a few entries in the log
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/679999/RubberduckLog.txt)

**Comment by retailcoder** [comment]
Not sure why it *does* work on some installs, a dll dependency is missing in the 2.0.9 build/release; that's fixed now, we'll be releasing 2.0.10 this week (it's been too long already!!).

**Comment by Bullfrog1234** [comment]
Understood and thanks
