### ISSUE TITLE
Can't name a variable bf

### ISSUE THREAD

**Issue by Vogel612** [rubberduck-vba/Rubberduck#2478]
As noted in chat yesterday I cannot `Dim bf`  without producing a parser error related to the [`Line`-Method](https://msdn.microsoft.com/en-us/library/office/aa221362(v=office.11).aspx) (kudos to Thunderframe for finding the method)

The relevant token in the grammar is [here](https://github.com/rubberduck-vba/Rubberduck/blob/81a62a060de0b6eb2ddaf0a05b5b11ab493c3f2f/Rubberduck.Parsing/Grammar/VBALexer.g4#L24)

**Comment by ThunderFrame** [comment]
Seems to be any identifier.
```vb
Sub bf()

End Sub
```

**Comment by retailcoder** [comment]
Ha, need to keep that in mind for my VBA BrainFuck interpreter...
