### ISSUE TITLE
LEFT function identified as variable

### ISSUE THREAD

**Issue by CHR-IS-B** [rubberduck-vba/Rubberduck#2480]
The code inspection window shows that `LEFT` is identified as a variable instead of a function.

_Variable 'Left' is used but not assigned._

```
Sub Test()
    Debug.Print Left("abcdef", 3)
End Sub
```

**Comment by retailcoder** [comment]
Also `Right`, `Mid`, and any other aliased built-in function out there. 2.0.11 is out as soon as this one is fixed, no ifs no buts ;-)

**Comment by comintern** [comment]
This is almost certainly the same issue as #2349.
