### ISSUE TITLE
Incorrect Let modifier message in code inspection 

### ISSUE THREAD

**Issue by halcwb** [rubberduck-vba/Rubberduck#2483]
In build 2.0.10 I get: Us of explicit Let statement for the following statement:

`    strError = strError & "Waarschijnlijk is het Afspraken project niet geopend (beveiligd met een passwoord)." & vbNewLine
`

However, `Let` is not used.

**Comment by retailcoder** [comment]
That's rather awkward... the inspection is an `IParseTreeInspection<LetStmtContext>`, which means it's merely wrapping up `ParserRuleContext` instances that the `ObsoleteLetStatementListener` is spitting up as the ANTLR parser does its work - and the only way an instance is returned is if the `LET` token exists in the `LetStmtContext` (every value assignment is picked up as a `LetStmtContext`):

````csharp
public class ObsoleteLetStatementListener : VBAParserBaseListener
{
    private readonly IList<VBAParser.LetStmtContext> _contexts = new List<VBAParser.LetStmtContext>();
    public IEnumerable<VBAParser.LetStmtContext> Contexts { get { return _contexts; } }

    public override void ExitLetStmt(VBAParser.LetStmtContext context)
    {
        if (context.LET() != null)
        {
            _contexts.Add(context);
        }
    }
}
````

I can't reproduce the issue with the provided code.
