### ISSUE TITLE
All menu items greyed out (2.0.11)

### ISSUE THREAD

**Issue by neilt17** [rubberduck-vba/Rubberduck#2491]
Rubberduck - 2.0.11

I've tried installing Rubberduck on three systems and am opening the VBE from PowerPoint - and in all cases the options from the drop down Rubberduck menu are greyed out - the only thing I can open and do anything with is the settings window and view the about window.

I've tried installing as administrator and running Powerpoint as administrator. In all cases I am using Office 2010, I've tried installing on Windows Vista on two machines and Windows 10 on another.

I've tried putting the cursor in different places, selecting different things, but the menu items remain greyed out.

**Comment by MDoerner** [comment]
@neilt17 Did you initiate the initial parse from the Rubberduck command bar? Before the first parse, most of Rubberduck is deactivated. The first parse is not automatically initiated atm because there are timing issues with the build up of the VBE.

**Comment by neilt17** [comment]
Brilliant - that's what I needed to do - all looking amazing now - thank you!
