### ISSUE TITLE
Can't initiate Parse in Office XP

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#2496]
The Parse button is enabled and clickable in Excel, Word and Access, but the Parse doesn't appear to commence, and so never completes.

In PowerPoint, the button is clickable, and the spinning circles appear in the Code Explorer and Code Inspections windows, but there is no other visible sign of progress, and parsing never completes.

**Comment by retailcoder** [comment]
I think you're on your own with that one.. it could be anything from the VBIDE version to the ... I've no idea actually. Do the logs show any sign of failure?

**Comment by ckuhn203** [comment]
I hate to say this, but we decided not to support XP if I recall correctly. It's highly likely that the correct version of .Net isn't present. 

@retailcoder any chance you can post instructions on how to check the parser log? I'm afraid I've had one too many here mate.

**Comment by retailcoder** [comment]
@ckuhn203 it should be under `%appdata%\Rubberduck\Logs` - there's a button in the settings dialog that opens it up for you :wink:

**Comment by ThunderFrame** [comment]
Will check the logs later.

@ckuhn203 Office XP, not Windows XP. Office 95 and later can be installed on Windows 10, so *any* Office version can have access to the right .NET version.

**Comment by ThunderFrame** [comment]
Well, it looks like my registry might be borked. Who knew Window Update in 2017, would try to apply service packs for Office XP.

http://stackoverflow.com/a/12962795/5757159

I can run Excel 2002 as Administrator, and Rubberduck works again. Now I just need to follow the guide in the SO artlicle above, and it should all be fine. Closing this as unique to my PC, but probably worth remembering that multiple versions of Office can mess with COM, and that running the host as admin will make some errors disappear, until a registry fix is applied.
