### ISSUE TITLE
Evaluate LibGit2Sharp v0.23/v0.24

### ISSUE THREAD

**Issue by Vogel612** [rubberduck-vba/Rubberduck#2497]
On December 23 2016 LibGit2Sharp released [v0.23](https://github.com/libgit2/libgit2sharp/releases/tag/v0.23)

On June 22 2017 LibGit2Sharp [v0.24](https://github.com/libgit2/libgit2sharp/releases/tag/v0.24)

We should evaluate whether to update the dependency or carry on. If we update we should do so without destabilizing the Release

**Comment by retailcoder** [comment]
That *should* be a pretty straightforward upgrade, in theory.

**Comment by daFreeMan** [comment]
"In theory, there is no difference between practice and theory, in practice, however, there often is."
  - Someone other than me

**Comment by NelsonVides** [comment]
Hey,
I'm a new guy in the project. Upgrading to v0.24 was actually the first thing I did when got my hands on Rubberduck, just out of curiosity. There were just a few of very easy to fix compile-issues: '.stage()' moves to the 'Commands' namespace, and '.commit()' now takes author and committer as two separate and both mandatory parameters. Then it compiled with no issues. As for actual unit test and running the new version on my every-day VBA life, I can't tell you much yet, but I haven't experiment any new crash.
I could help here, but please forgive me I'm just a hungry amateur. Somebody to help me to help? :)

**Comment by Hosch250** [comment]
Awesome. I don't remember at the moment, but I thought there was a deeper problem here than just the API breaking things. Maybe @rubberduck203 would remember?

**Comment by Vogel612** [comment]
TBH I wouldn't even care much about destabilizing Source Control at this point ... It's marked experimental, 0.24 could even bring some stability into it. As long as it doesn't obviously break the build, we can still stabilize it as the issues crop up.

**Comment by NelsonVides** [comment]
So I've just sent you my changes on a pull request. Just a bunch of API differences. To be honest I find the repo.command(parameters) more intuitive than the command(repo,parameters). I'm acting on my repo object actually. But that's basically the main change from the guys at libgit.
