### ISSUE TITLE
Upgrade to Antlr 4.6

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#2498]
We're currently running off Antlr 4.3; Antlr 4.6 has important performance improvements that RD will massively benefit from, but upgrading isn't going to work if we merely swap the library - we need to rebuild *every single parser* with 4.6.

- Rubberduck.Parsing.Grammar has **VBALexer.g4** and **VBAParser.g4**.
- Rubberduck.Parsing.Preprocessing has **VBAConditionalCompilationParser.g4**, **VBADate.g4**, and **VBALike.g4**.

When 4.6 was released I rebuilt VBALexer and VBAParser, but forgot about the Preprocessing grammars; that resulted in several hundred broken tests.

**Comment by MDoerner** [comment]
Just wanted to update this to point out that Antlr has relased version 4.7 in the meantime.

**Comment by Hosch250** [comment]
https://github.com/tunnelvisionlabs/antlr4cs/issues/173

The latest release is 4.6.4, although the core ANTLR is at 4.7.
