### ISSUE TITLE
Refresh button disabled after removing module

### ISSUE THREAD

**Issue by mattpalermo** [rubberduck-vba/Rubberduck#2503]
I am having a trouble where the refresh button becomes permanently disabled after removing a module. I can reproduce the problem very successfully with the following steps:

1. Open Excel 2016
2. Open new workbook from blank template
3. Open the VBE
4. Press the parse / refresh button for the initial parse
5. Open the Code explorer
6. Add a new standard module (via the code explorer button)
7. Press the refresh button to show the new module in the code explorer
8. Right click on the module and press remove
9. Press the refresh button to update the code explorer.

What I end up with is this
![capture](https://cloud.githubusercontent.com/assets/16647352/21798032/20836416-d75e-11e6-832e-f845433ebd1a.PNG)

Here is the log output with max level DEBUG:
[RubberduckLog - Copy.txt](https://github.com/rubberduck-vba/Rubberduck/files/695527/RubberduckLog.-.Copy.txt)

Here is the log output with max level TRACE:
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/695528/RubberduckLog.txt)

I believe this is a similar issue to issue #2085

**Comment by retailcoder** [comment]
Thanks for reporting the issue. As a (lame) work-around, I think you can get the button enabled again by adding a new test module (will trigger a reparse, which will tickle the refresh button state).

**Comment by mattpalermo** [comment]
Thank you. The work-around works :)
