### ISSUE TITLE
Initialising Repo from Active MS Access VBA Project fails if Report name contains backslash

### ISSUE THREAD

**Issue by chrisdukey** [rubberduck-vba/Rubberduck#2505]
I'm looking into using Rubberduck to manage the code in some large Microsoft Access databases that I inherited. When I initialise a git repository using an existing MS Access VBA project and the project contains Reports with a backslash in the name e.g. [Report Cost Centre Governing Criteria By CC\Grade] then the import fails be cause Rubberduck thinks the backslash equates to a new directory (see [RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/695883/RubberduckLog.txt)). Afraid renaming reports is not an option as there are so many of them.

**Comment by ThunderFrame** [comment]
Same thing applies to Form names too.

Forms and Report also seem to allow `:` (Alternate Data Streams under NTFS!!!)

The VBE seems to replace all invalid characters with underscores (`_`), so that should probably be the approach that RD uses.

However, even the VBE fails to actually honor the underscores that it used, and exporting the file fails:

![report](https://cloud.githubusercontent.com/assets/16574009/21804100/54ac0bee-d781-11e6-9657-1a50a68ae44b.png)

**Comment by chrisdukey** [comment]
Good to know, thanks. Do you know are there any plans to support the checking in and out of MS Access Database objects (Tables, Reports etc)?

**Comment by ThunderFrame** [comment]
There aren't any plans for checking in data, but there are plans for parsing the controls in Forms and Reports.

**Comment by ThunderFrame** [comment]
Fix in the hole with PR #2506

**Comment by retailcoder** [comment]
@chrisdukey for now there isn't anything host-specific, but we're planning to; as @ThunderFrame said I don't think the *data* itself would be under source control (isn't that the role of backups?), but DDL scripts for drop+create tables and querydefs isn't impossible, if Access supports that (not familiar with Access myself).

**Comment by chrisdukey** [comment]
Cheers guys. Yeah, when I said Tables I was referring to the structure rather than any data contained within it. In Access VBA you can use Application.saveAsText and Application.loadFromText to export and import Form objects, Table objects etc. I'd be happy to do some beta testing if that would help.
