### ISSUE TITLE
Export todo items

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#2507]
A recent tweet asked if it was possible to access todo items via VBA code. Of course, it isn't something that's possible at this point (the experimental COM API doesn't expose todo's), but the *Todo Explorer* toolwindow could easily have the same "copy to clipboard" button that we have on the *Test Explorer* and *Inspection Results* toolwindows (heck, even the *Code Explorer* has it).

![image](https://cloud.githubusercontent.com/assets/5751684/21823371/bb6d595c-d748-11e6-8478-2025fb675793.png)

**Comment by Hosch250** [comment]
@ThunderFrame You did the others. Interested?

**Comment by ThunderFrame** [comment]
Sure. Approach needs a revamp, the original clipboard stuff is working off arrays.
