### ISSUE TITLE
Rubberduck should be able to identify extended members

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#2512]
some objects can have extended members:

Eg. Calling a stored procedure from a connection object
```
  Dim conn As ADODB.connection
  Set conn = New ADODB.connection
  conn.ConnectionString = "foo"
  conn.Open
  Dim rst As Recordset
  Set rst = New Recordset
  conn.sp_help "dbo.Vendor", rst
```

Rubberduck should be able to identify such members as being extended.

**Comment by comintern** [comment]
Support for this in COMReflection will be in my next PR.

**Comment by retailcoder** [comment]
Ref. http://stackoverflow.com/a/28237063/1188513 - I'm giving it a +100 bounty :smiley:

**Comment by ThunderFrame** [comment]
linking #2236 #2237 and #2238
