### ISSUE TITLE
RD 2.0.11 extract method fails with GoTo statement

### ISSUE THREAD

**Issue by byronwall** [rubberduck-vba/Rubberduck#2515]
I've got a chunk of code within a larger `Sub` that I am trying to extract.  That code contains a `GoTo` that is contained within the part being extracted.  Rubberduck fails to extract the method correctly.  Specifically it seems to want to declare a variable for the `GoTo` label instead of just carrying the existing label into the new `Sub`.  Also, I did not get the normal GUI to edit the parameters and name the new method.

Original code (I have called out where I am extracting inclusive):
```vb
Sub TestOuter()
    Dim index As Long
    'start extract
    For index = 0 To 10
        If index > 5 Then
            GoTo StopCode
        End If
    Next
StopCode:
    'end extract
    Debug.Print index
End Sub
```
When I call for the extract, I get this:
```vb
Sub TestOuter()
    Dim index As Long
NewMethod StopCode, index
    Debug.Print index
End Sub

Private Sub NewMethod(ByRef StopCode As , ByRef index As Long)
    'start extract
    For index = 0 To 10
        If index > 5 Then
            GoTo StopCode
        End If
    Next
StopCode:
    'end extract
End Sub
```

You can see that the reference to `StopCode` is breaking things where it is called and down below in the `Sub` definition.

**Comment by retailcoder** [comment]
Linking #2326 ... *extract method* is considered broken at this point.

**Comment by Vogel612** [comment]
Since the Extract Method refactoring is in dire need of a rewrite from scratch, all [bug] issues pertaining to it, are in the process of becoming irrelevant. Closing.
