### ISSUE TITLE
RD needs a unicorn for when GitHub is unavailable

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#2519]
When GitHub is unreachable, you get this unicorn:

![unicorn](https://cloud.githubusercontent.com/assets/16574009/21881728/9958c81a-d8fb-11e6-8751-34256ab91624.png)

RD *could* show something like this instead:

![unicorn-rubber-duck-front](https://cloud.githubusercontent.com/assets/16574009/21881757/b7b51b74-d8fb-11e6-9ecf-31bd1cdd63c9.jpg)

**Comment by Vogel612** [comment]
to clarify ... is this for source-control when the remote to publish to is unavailable? Because that may have multiple reasons, with only one of them being the host actually being unavailable ...

I'd prefer a standard error message ...

**Comment by PeterMTaylor** [comment]
Nice visually but @ThunderFrame the unicorn word is misleading as unicorn could also mean growth or traction in business terms. See https://en.m.wikipedia.org/wiki/Unicorn_(finance)

**Comment by retailcoder** [comment]
Naaah
