### ISSUE TITLE
Annotations can't be followed by a comment

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#2523]
Say you have a variable reported as "unassigned", and add an `@Ignore` annotation:

````vb
    '@Ignore VariableNotAssigned
    ReDim orgs(0 To items.Count - 1, 0 To 1)
````

If you add an explanatory comment:

````vb
    '@Ignore VariableNotAssigned: that's actually a Rubberduck bug, see #2522
    ReDim orgs(0 To items.Count - 1, 0 To 1)
````

All of a sudden the `@Ignore` annotation seems to get parsed as an ordinary comment, and the inspection results pops back into the results list.

That would be a grammar issue.

**Comment by Vogel612** [comment]
Does this also apply for the following constellation?

```
'@Ignore VariableNotAssigned
'that's a Rubberduck bug, see #2522
ReDim orgs(0 To items.Count -1, 0 To 1)
```

**Comment by retailcoder** [comment]
ref. #2547
