### ISSUE TITLE
ParserState caching issue?

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#2528]
Might be a one-off, but seems identifier references don't *consistently* get cleaned up:

![image](https://cloud.githubusercontent.com/assets/5751684/21912709/9604095a-d8f5-11e6-97d1-7a14a5103034.png)

That selection was the location of the *other* reference to `SageContext` (`With New SageContext`) in the first parse, now shifted a number of lines below.

**Comment by MDoerner** [comment]
Indeen, we did not clean up references for modules that did not get reparsed (not new and not modified). That has been fixed in PR #2738. Futher cahnges have been made in PR #2764, but should not have reintroduced the problem.

So, if this cannot be reproduced anymore, this issue can be closed.

**Comment by MDoerner** [comment]
Can this still be reproduced. According to the changes that went into the removal of references, this issue should not exist anymore.

**Comment by MDoerner** [comment]
Again, does this problem still occur?
