### ISSUE TITLE
Add/Remove references UI needs some work

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#2530]
The UI currently looks like this:

![image](https://cloud.githubusercontent.com/assets/5751684/21917405/874578f2-d915-11e6-8db3-5046a1688752.png)

Some issues:

 - [ ] The title label needs a binding to the project name.
 - [ ] ListView column width isn't right; descriptions aren't visible unless 2nd column is expanded, and it's not clear why there's a 3rd column.
 - [ ] ListView items need push-pin toggle buttons.
 - [ ] ListView needs drag-and-drop item sort and up/down buttons to reorder items.
 - [ ] The [Recent] tab should be removed.
 - [ ] The search field needs a caption and a watermark text.
 - [ ] The control needs a margin.
 - [ ] The full path of the selected type library should be displayed in a box/label under the listview; a button should bring up a *file explorer* window at that location.

**Comment by ThunderFrame** [comment]
The VBE references dialog doesn't allow for referring to indexed Type Libraries, even though `References.AddFromString` does. Rubberduck should be able to allow for adding indexed TLBs, and maybe even prompt the user if there is more than one type library available.

For example, the following line adds a reference to the `VBRUN` Type Library with index 3 - note the `\3` in the reference string:
`ThisWorkbook.VBProject.References.AddFromFile "C:\Windows\SysWOW64\MSVBVM60.dll\3"`
