### ISSUE TITLE
@ignore all

### ISSUE THREAD

**Issue by mattpalermo** [rubberduck-vba/Rubberduck#2532]
I would like to turn off code inspections for an entire module. This module is maintained by someone else and it raises many issues in the code inspection. I would prefer not to maintain my own version of the library as I would like to just be able to import new versions of the library without modification.

I tried to enter '@ignore all' at the top of the module in hope that it would turn off all the code inspections but this didn't work. Is there a statement that I can use to achieve this?

At the moment I am able to ignore the issues by sorting the code inspection issues my module.

**Comment by comintern** [comment]
I kind of like this idea. Something like an `@IgnoreModule` attonation that would go at the top of the module.  Something for ignoring individual inspection on a module level would also be useful too -  `@IgnoreInModule UseMeaningfulNameInspection` would be nice for modules with a ton of API declarations.

**Comment by retailcoder** [comment]
In the meantime you can regroup results by module, and collapse those you're not interested in.

**Comment by mattpalermo** [comment]
@retailcode thanks, I didn't realise I could collapse those section.

**Comment by comintern** [comment]
Linking #2006.

**Comment by retailcoder** [comment]
Implemented/merged in #2761; the annotation is `@IgnoreModule` - there's no UI command for it yet, but it should "just work".. I need to blog about RD annotations / "magic comments"...

**Comment by CharlesRHall** [comment]
Collapsing the modules one is not interested is painful - even scrolling when there are a lot of modules is not user friendly - for code inspections to be used, it needs to be user friendly
