### ISSUE TITLE
Inspection QuickFixes should be lazy loading.

### ISSUE THREAD

**Issue by comintern** [rubberduck-vba/Rubberduck#2534]
AFAICT, there isn't any reason for `QuickFix` objects to be created until they are requested from the code inspections window.  Currently, the majority of them are being created in the ctors of the inspection results objects, i.e.:

```
            _quickFixes = new QuickFixBase[]
            {
                new RenameDeclarationQuickFix(target.Context, target.QualifiedSelection, target, parserState, messageBox),
                new IgnoreOnceQuickFix(Context, target.QualifiedSelection, Inspection.AnnotationName), 
                new AddIdentifierToWhiteListQuickFix(Context, target.QualifiedSelection, target, settings)
            };
```

These aren't usable until the inspection result is actually selected.  For inspections with large numbers of results, this means that there is the distinct possibility that they'll never be needed. I'd propose moving the generation to the `InspectionResultBase.QuickFixes` override so that they're only created on demand.

Since the demand for the `QuickFixes` is entirely UI driven, it makes more sense to defer the object creation overhead.

**Comment by ckuhn203** [comment]
Should be pretty simple to convert them to `Lazy<T>`.
