### ISSUE TITLE
Undeclared variable cannot be a bracketed identifier

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#2548]
This code compiles, but throws a runtime error 424 / "Object required":

````vb
Public Sub Test()
    [foo bar] = 42
    Debug.Print [foo bar]
End Sub
````

By *not* creating an undeclared variable declaration for undeclared bracketed identifiers, we'll stop tripping inspection results for actual legit bracketed expressions, for example `[H2]` here:

      Set rFind = sheet.Cells.Find("Index", [H2], xlValues, xlWhole, xlByColumns, xlNext)

If, instead of spawning a variable for an undeclared bracketed identifier, the resolver spawned some `DeclarationType.RuntimeExpression` (or something like it), ...we would still have visibility on them, and wouldn't pollute the `Declarations` collection with variables that aren't variables.

**Comment by comintern** [comment]
AFAICT, these should all be resolved as function calls.  Linking #2565.
