### ISSUE TITLE
Else If inside a Select Case does not align correctly

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#2552]
(originally reported on [RubberduckWeb](https://github.com/rubberduck-vba/RubberduckWeb/issues/41))

I have an `If` with multiple `Else If`s inside of a `Select Case` inside of a `For` loop.

The indenter is mis-aligning the `Else If`s and everything else below with `Case`.  The actual code is much longer, but I think this reflects the issue.  Below is the code after running the Indenter...

````vb
 For CurrentRow = 9 To MaxRows - 1
     Select Case .Cells(CurrentRow, "A")
       Case "[b]", "[f]", "[h]", "[t]"
         'Not a data row - skip
       Case "fMTCnty"
         'Do Stuff
       Case Else              
         If Mid(ReportName, 3, 1) = "r" Then
         iMult = -1      
       ElseIf ReportName = "SRadj" Or ReportName = "SRoth" Then
         iMult = -1
       ElseIf ReportName = "RBbarr" Then
         iMult = -1            
       Else                                    
         iMult = 1
       End If
       wsData.Calculate
       'More Stuff
     End Select
 Next iRow
````

**Comment by rdster** [comment]
Config file below
[rubberduck.config.txt](https://github.com/rubberduck-vba/Rubberduck/files/714250/rubberduck.config.txt)


I'll update, I'm currently on 2.09....and test.

**Comment by retailcoder** [comment]
Ah, it's probably fixed already then - @comintern's current build seems to indent accordingly with specified indenter settings (ref. [comment](https://github.com/rubberduck-vba/RubberduckWeb/issues/41#issuecomment-273479921)).

**Comment by rdster** [comment]
Just updated, and it is indenting as would be expected.  Sorry for the false alarm.
