### ISSUE TITLE
Indenter mis-aligning IF ELSE inside Select Case inside For loop

### ISSUE THREAD

**Issue by rdster** [rubberduck-vba/Rubberduck#2553]
I have an If with multiple ElseIfs inside of a Select Case inside of a For loop.

The Indenter is mis-aligning the ElseIfs and everything else below with Case. The actual code is much longer, but I think this reflects the issue. Below is the code after running the Indenter...

```
For CurrentRow = 9 To MaxRows - 1
  Select Case .Cells(CurrentRow, "A")
    Case "[b]", "[f]", "[h]", "[t]"
      'Not a data row - skip
    Case "fMTCnty"
      'Do Stuff
    Case Else              
      If Mid(ReportName, 3, 1) = "r" Then
      iMult = -1      
    ElseIf ReportName = "SRadj" Or ReportName = "SRoth" Then
      iMult = -1
    ElseIf ReportName = "RBbarr" Then
      iMult = -1            
    Else                                    
      iMult = 1
    End If
    wsData.Calculate
    'More Stuff
  End Select
Next iRow
```

**Comment by retailcoder** [comment]
Oops, I had already re-posted the issue, see #2552 :smile:

**Comment by rdster** [comment]
Ok, sorry, didn't see it.

**Comment by retailcoder** [comment]
No problem, thanks for reporting the issue! Can you confirm you're running v2.0.11?
