### ISSUE TITLE
UseMeaningfulNameInspection should ignore parameter names in Declare Functions\Subs

### ISSUE THREAD

**Issue by comintern** [rubberduck-vba/Rubberduck#2573]
Take this example declaration:

`Private Declare PtrSafe Function CLSIDFromString Lib "ole32" (ByVal lpsz As Any, ByRef pclsid As GUID) As Long`

The parameter `lpsz` trips the `UseMeaningfulNameInspection` because it doesn't contain any vowels.  I'd argue that code using the parameter names of external library procedures is "meaningful" in that it matches the documented signature of the function.

**Comment by retailcoder** [comment]
Mine! =)

**Comment by retailcoder** [comment]
Fixed. Also won't trigger in built-in event handlers either.
