### ISSUE TITLE
Selecting "Run All Tests" from the menu should show the Test Explorer if it isn't visible.

### ISSUE THREAD

**Issue by comintern** [rubberduck-vba/Rubberduck#2584]
Title pretty much covers it.  If the Test Explorer window isn't visible, there is absolutely zero indication that anything happens when you select "Run All Tests".  I doubt there's any use case for running tests if you don't want to see the results.

**Comment by ckuhn203** [comment]
Regression? I could have sworn we fixed this like 2 years ago.
