### ISSUE TITLE
Excel hung while the VBE remained functional

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#2587]
Excel 2010, RD 2.0.11

Excel has hung, i.e., my Excel window is white(ish) with no menu, no title bar, no status bar, no response. It's been hung for the better part of an hour while I went to eat lunch.

The VBE window is totally responsive and working just fine. I was actually able to copy my most recently changed code and paste it into NP++, just in case. 

I had 1 XLSM and 3 XLSX open at the time.

[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/736132/RubberduckLog.txt)

After terminating Excel via TaskManager, it came back up, presented me with the list of recovered files & my code seems to all be there with the most recent changes (I probably hit <kbd>Ctrl-S</kbd> prior to <kbd>F5</kbd>)

**Comment by retailcoder** [comment]
I doubt we'll have a repro on that one, but thanks for submitting :+1:

**Comment by daFreeMan** [comment]
Easy reproduction:

* Ensure clean compile
* Begin code parse
* Immediately hit F5 to start code execution

voila!

How does he know, you may ask? He just did it again without realizing that's what caused it the first time.

**Comment by comintern** [comment]
Interesting.  I can't repro that with those steps in the current build.  There's been some work done around the parser state, so it may have already been fixed.
