### ISSUE TITLE
Add a custom programmable output window

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#2591]
The Immediate window is limited in a number of ways:
- Limited number of lines of history
- Limited number of characters per line
- Tab stops are fixed at modulo 15
- Despite `Tab(x)` and `Spc(x)` functions, text alignment is hard
- Despite `,` and `;` operators, text-alignment is hard
- Font-family, size, colors, code-page, text-lignment RTL *must* be the *same* as the IDE
- Can't clear the window during code execution

Rubberduck already exposes objects through the Type Library, and could easily add a `Console`-type object:

Suggested Methods:

```vb
Console.Write(format As String, ParamArray args() As Variant) ' Get .NET formatting for free
Console.WriteLine(format As String, ParamArray args() As Variant) ' Get .NET formatting for free
Console.Clear(Optional numberOfLines As Long = -1, Optional fromEnd As Boolean = True)
Console.SetBufferSize()
Console.SaveToFile(path As String)
Console.Copy()
```

Suggested Properties
```vb
Console.Font.Name = "Comic Sans"
Console.Font.Bold = True
Console.Font.Italic = True
Console.Font.Size = 16
Console.RTL = True
Console.TextAlignLeft = False
Console.ForegroundColor = RGB(239,239,239)
Console.BackgroundColor = RGB(0,0,0)
Console.TabWidth = 15 - 5
```

Pretty soon, @comintern will have ASCII Tetris running in the VBA Rubberduck Console...

Stretch goal - Markdown support ;-)

**Comment by Vogel612** [comment]
re markdown support: I think that's a bad idea. Console is intended for dev-readable output, mardown is for user-facing. That's to say that the console is intended for development use.

If we want to have a .NET-Type visible user-control (including input), that'd be somewhat out of scope, especially since this is basically an atomic feature. It would be significantly simpler to just create a "UI library" that can be referenced as .tlb dependency instead of "stuffing" this into rubberduck as well.

**Comment by ThunderFrame** [comment]
@Vogel612 Yep, Markdown was tongue-in-cheek, but I notice you didn't nuke Tetris.

Ideally the UI would be a ToolWindow, so it would be dockable, so I *think* that means it needs to be an add-in, unless, maybe, it was written as an ActiveX and then the user could use CreateToolWindow, but that's plumbing the user doesn't want.

Extra properties:

```vb
WordWrap As Boolean 'Words that... _
 wrap...
ShowFormattingSymbols As Boolean 'Shows paragraph marks and formatting characters
ViewHex As Boolean 'Shows the output in hex notation
```
