### ISSUE TITLE
Concurrency issues randomly make tests fail

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#2597]
Utterly annoying. There appears to be some parser (parser state?) concurrency issues that cause unit tests to randomly fail. This is affecting CI/AppVeyor.

**Comment by retailcoder** [comment]
ref. #2759 - the tests are currently being ignored, so that the CI builds can be useful in any way.

**Comment by PeterMTaylor** [comment]
@retailcoder consider asking Appveyor themselves for depth investigation and present their results here to support this pathway (https://github.com/appveyor/ci/issues)

**Comment by comintern** [comment]
Could be related to thread safety in Moq.  See...

[Moq still doesn't support multithreading #91](https://github.com/moq/moq4/issues/91)
...and...
[Thread safety issue on setup #326](https://github.com/moq/moq4/issues/326)

**Comment by rubberduck203** [comment]
Does the test fail randomly when run locally, or just on the CI server?

**Comment by comintern** [comment]
@rubberduck203 It's 5 tests, all related to binding in the resolver.  Usually about 2 or 3 will fail on my home machine and 1 or 2 on my work machine. It's never the same ones, and they always pass (at least for me) if they're run by themselves.

**Comment by retailcoder** [comment]
@comintern I've had an instance or two of one (or two) failing more than once. like, had to run it individually 3 times and it turned green. **Slightly** annoying issue!

**Comment by rubberduck203** [comment]
That's actually very telling @comintern. Tests are cross talking. Multi-threading was mentioned. Is async-await involved here or something lower level? 

Any chance you guys can link me to one of the tests?

**Comment by comintern** [comment]
@rubberduck203 [EnclosingProjectComesBeforeOtherModuleInEnclosingProject](https://github.com/rubberduck-vba/Rubberduck/blob/next/RubberduckTests/Binding/SimpleNameTypeBindingTests.cs#L39-L56) is a good example. The multi-threading would be in the parser - IIR it's all just straight-up parallel threads.  I don't recall any asych-await.

**Comment by rubberduck203** [comment]
Thanks. Man, I miss VS right about now. I don't see anything obviously off, but *anytime* I've ever run across an issue where a test ran in isolation, but not many at once, one of two things was going on. 

1. The test was inadvertently keeping global state (this one isn't). 
2. A test was running a "fire and forget" asynchronous method. 

I'm theorizing that something is being spun off into the background, but the test doesn't know to wait for it. I don't see anything that would be doing this though. Not ruling out the Moq issues linked, just adding some extra insight. 

Tangential reading via Stephen Cleary: https://msdn.microsoft.com/en-us/magazine/dn818493.aspx

I know there's no async/await involved here, but feels like a similar problem.

**Comment by MDoerner** [comment]
I still have one test that sometimes fails randomly on my machine, I think it is `GivenPrivateSub_DefaultQuickFixRemovesParameter`. However, it never fails when run in the debugger.

Apart from this test, this issue has been made nearly non-existent after the refactring of the coordination of the parsing runs, which allowed to run the test synchronously by injecting appropriate implementations of the parser and the resolvers.
