### ISSUE TITLE
Serialized declarations need versioning and fallback behavior.

### ISSUE THREAD

**Issue by comintern** [rubberduck-vba/Rubberduck#2600]
Maybe it's just because I'm lazy or _always_ forget to delete them after touching anything in the COM collector or serializer, but RD should do 2 things:

1.) Check to make sure that the serialized declaration file for a library is "current" before it's loaded.
2.) Fall back to loading the TypeLib if deserialization fails.

Currently the only way to tell that there was a deserialization issue is to look in the log file for the throw, and/or notice that the inspection results are whacked.

**Comment by Vogel612** [comment]
Serialization of declarations is not used in Inspections anymore, neither is it a supported feature, because it's only in development builds.

I'm pretty sure that we won't need this, and if we do, we can still take care of it
