### ISSUE TITLE
Feature request: automatically split long strings

### ISSUE THREAD

**Issue by Falthazar** [rubberduck-vba/Rubberduck#2610]
Sometimes I'll have really long strings for directories, and it'd be nice if they were auto split.

`strDir = "C:\user\folder 1\folder 2\folder 3\folder 4\folder 5\folder 6\folder 7\folder 8\"`

and it splits it like:

    strDir = "C:\user\folder 1\folder 2\folder 3\folder 4\" & _   
             "folder 5\folder 6\folder 7\folder 8\"

**Comment by comintern** [comment]
Couldn't agree more - this is already on my todo list.  See #2406.
