### ISSUE TITLE
Feature request: Code inspection only for current module or procedure

### ISSUE THREAD

**Issue by Falthazar** [rubberduck-vba/Rubberduck#2611]
I have a lot of modules in my personal workbook, and when the code inspection pops up, it has a LOT of entries. 

Some of the modules are just essentially scratch paper to try things, or old ones I don't want to delete. It'd be nice if I could just inspect my current code.

Also, does the fix button fix all? I'd rather it ask me if I want to do that, and then iterate through each one and say "do you want me to fix this?" Sometimes it can make a mistake, so I don't want everything auto fixed.

example I just noticed:
went from `Dim corName, sendEmail As String`
to
```
     Dim corName
     Dim sendEmail As String
```

**Comment by comintern** [comment]
If you only want to see results from a particular code module, the "Grouping" drop-down allows you to change the display to "By location".  Then you can just collapse the ones you don't care about.

 There's also a similar request #2532 to add ignore annotations scoped to modules.

Re the fix button, some inspections allow "fix all", other don't.  Unless the fix explicitly says "in project" or "in module", it's a single instance.

**Comment by retailcoder** [comment]
The "fix" menu only affects the selected individual inspection result. If that's an aggregate, it only affects the first result in the aggregate - you can double-click the result to navigate to where it points to, and review whether you'd want to fix that instance or not. Most inspections have an "ignore once" quick-fix that you can use for these cases.

The "fix all occurrences in project" and "fix all occurrences in module" links at the bottom of the inspection results toolwindow, apply the default quick-fix (the first one in the "fix" menu) to all results of the selected inspection; note that this option isn't available for all inspections, and some inspections may be auto-fixable in the module but not in the project, or vice-versa.

**Comment by retailcoder** [comment]
Note: "fix all occurrences in xxxxx" will *not* prompt to confirm every single fix - it's your responsibility to review the inspection results of that inspection type and assess whether you want to fix them all in one click or not; there's no cherry-picking, but places with an `@Ignore [InspectionName]` annotation will not be producing results, and therefore will not be affected by "fix all occurrences".
