### ISSUE TITLE
"Inspections" context menu

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#2614]
Soon the parse coordinator will take the inspector under its umbrella, and so inspection tasks will become cancellable, and inspection results can take a first step towards becoming discoverable by simply looking at a `Declaration` or an `IdentifierReference` .

Then we need to add an *Inspections* parent menu in the code pane's context menu:

 - Rubberduck
   - Inspections
      - Issues
         - `IEnumerable<InspectionResultBase>`
            - Fix
               - `IEnumerable<QuickFixBase>` quickfixes available, except `IgnoreOncrQuickFix`
            - Ignore
               - Once
               - In module
               - In project (i.e. in all modules of *this* project)
         - Severity
            - *list severity levels*
      - Settings
   - ...

For project and module-level inspection results, the Rubberduck commandbar also needs to have this menu, to offer the same functionality for inspection results that are attached to a project or module and thus cannot be selected in a code pane.

**Comment by bclothier** [comment]
This is partially addressed in the PR #4717 - pinging @retailcoder  / @comintern  to decide if this is good enough to close or to enhance further.
