### ISSUE TITLE
 Local variable 'Is' is not declared 

### ISSUE THREAD

**Issue by SystemsModelling** [rubberduck-vba/Rubberduck#2619]
Select Case … Case Is > 1  etc

**Comment by SystemsModelling** [comment]
Same for Space function
 Local variable 'Space' is not declared 
eg Space(3)

**Comment by comintern** [comment]
I can't replicate an result with `Case Is ...`.  The grammar was changed after 2.0.11 to pick up those cases.

The `Space` function is different, and I can repro it with this code:

```
Sub foo()
    Dim x As String
    x = Space(3)
End Sub
```

**Comment by comintern** [comment]
` Case Is > 1` is a duplicate of #2514, which is fixed in next.  The second referenced issue duplicates #2618.  Closing in favor of that issue.
