### ISSUE TITLE
Inspection for empty module members

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#2627]
Similar to #1732 in that it locates empty scopes - this time at procedure level.

ref. #2625

**Comment by MDoerner** [comment]
I have to say that I am not a big fan of this inspection. I would have to turn this off immediately because I have tons of interfaces, which only consist of empty public members.

**Comment by ThunderFrame** [comment]
If the interface is implemented anywhere, then RD should know that the module is an interface.

Either way, there's an interface annotation since #1878

**Comment by ckuhn203** [comment]
There's also always the option of using the settings to turn an inspection off.

**Comment by retailcoder** [comment]
There's also an `'@Interface` annotation, meant to flag a class as an interface to Rubberduck.
