### ISSUE TITLE
Removed a class using code explorer throws exception in Visual Studio.

### ISSUE THREAD

**Issue by PeterMTaylor** [rubberduck-vba/Rubberduck#2631]
Was using the Code Explorer (with the recent sync of next to my fork) to delete an existing class with the same file I had resolver error (not found yet) and am surprised to find Visual Studio throws an exception at my face...
The Output says...
```
Exception thrown: 'System.MissingMethodException' in mscorlib.dll
Exception thrown: 'System.MissingMethodException' in mscorlib.dll
The thread 0x194c has exited with code 0 (0x0).
The thread 0x17d4 has exited with code 0 (0x0).
The thread 0x1680 has exited with code 0 (0x0).
Exception thrown: 'System.Runtime.InteropServices.COMException' in Rubberduck.VBEditor.dll
Exception thrown: 'System.Reflection.TargetInvocationException' in mscorlib.dll
```
The clipboard says...
```
System.Reflection.TargetInvocationException was unhandled
Message: An unhandled exception of type 'System.Reflection.TargetInvocationException' occurred in mscorlib.dll
Additional information: Exception has been thrown by the target of an invocation.
```
Here is the snap of the error.
![rd cdataset removed a class then vs throws an exception](https://cloud.githubusercontent.com/assets/2254567/22617107/77197944-eb10-11e6-96e9-a8cab110f4e4.PNG)
Here is the snap of the CallStackTrace and associated Disassembly.
![rd cdataset removed a class then vs throws an exception stacktrace](https://cloud.githubusercontent.com/assets/2254567/22617136/3f7e1ae8-eb11-11e6-85be-6d8c93129480.PNG)
![rd cdataset removed a class then vs throws an exception disassember](https://cloud.githubusercontent.com/assets/2254567/22617138/479865f8-eb11-11e6-9a39-34fd7c975851.PNG)

**Comment by comintern** [comment]
I followed the code path for the `RemoveCommand` back and found a missing null check in `VBComponents.Remove` (and another that wasn't checking what it was supposed to), but that probably only addresses the symptom here.  Did you happen to save the log file?

**Comment by PeterMTaylor** [comment]
unfortunately no, sorry.

**Comment by PeterMTaylor** [comment]
I had a previous copy of RD v2.0.9 I believe while running VS latest build.
Have uninstalled this, ran the VS build noticed no Rubberduck showing up, used the references to find it.

**Comment by PeterMTaylor** [comment]
Question: Are there any cases of having version mismatces between production installation vs development builds?

**Comment by PeterMTaylor** [comment]
Closing this issue as I feel the code explorer from development cannot be reproduced.
However, #2638 provides more context and detail from production version 2.0.12 to the task at hand.
