### ISSUE TITLE
Weird case where var ByVal can be changed and passed back

### ISSUE THREAD

**Issue by SystemsModelling** [rubberduck-vba/Rubberduck#2634]
Parameter 'KeyCode' is passed ByVal and assigned a value	
Private Sub txtNote_KeyDown(ByVal KeyCode As MSForms.ReturnInteger, ByVal Shift As Integer)
...code...
KeyCode = 0 ' do not move to next field - works even though passed byVal !

**Comment by comintern** [comment]
`MSForms.ReturnInteger` is actually an object, and `KeyCode = 0` is assigning to the default member `.Value`.  This is a known issue - see  #2602.
