### ISSUE TITLE
 'Sheets' should be recognised as a valid type

### ISSUE THREAD

**Issue by SystemsModelling** [rubberduck-vba/Rubberduck#2642]
Warning: Member 'Sheets' implicitly references ActiveSheet -
Dim AllOrSelectedSheets As Sheets

**Comment by retailcoder** [comment]
Ha, good catch!

**Comment by retailcoder** [comment]
If you put the cursor on `Sheets`, does the context status look right? I suspect this is just an inspection bug, the type would actually be resolved fine.

**Comment by comintern** [comment]
This is working in the current build:

![untitled](https://cloud.githubusercontent.com/assets/8944005/22651625/54e48c94-ec49-11e6-9bb2-32240adad708.png)

The reason that it gives an inspection result is that it is an implicit reference to `Excel.[_Global].Sheets`, which returns `ActiveWorkbook.Sheets`.  A good explanation for the rationale of the inspection is on SO:  http://stackoverflow.com/q/41981099/4088852.

Looks like the description just needs to be fixed.

**Comment by retailcoder** [comment]
@comintern but does the inspection fire a result for an `AsType` reference?

**Comment by comintern** [comment]
@retailcoder  Yep. The description in `ImplicitActiveWorkbookReferenceInspectionResult` is just pointed to the wrong resource:

```
        public override string Description
        {
            get { return string.Format(InspectionsUI.ImplicitActiveSheetReferenceInspectionResultFormat, Context.GetText() /*_reference.Declaration.IdentifierName*/); }
        }
```

**Comment by retailcoder** [comment]
So there's 2 issues: one is the wrong resource, the other is that `Dim foo As Sheets` shouldn't trigger a result.
