### ISSUE TITLE
Is RD recognising conditional compilation directives?

### ISSUE THREAD

**Issue by SystemsModelling** [rubberduck-vba/Rubberduck#2643]
Suggestion: Parameter 'lpszRemoteName' is specified on multiple lines
, line 8

#If VBA7 Then   ' Excel 2010+
Declare PtrSafe Function WNetGetConnection32 Lib "MPR.DLL" Alias _
   "WNetGetConnectionA" (ByVal lpszLocalName As String, ByVal _                         <-- line 8
   lpszRemoteName As String, lSize As Long) As Long  
#Else
Declare Function WNetGetConnection32 Lib "MPR.DLL" Alias _
   "WNetGetConnectionA" (ByVal lpszLocalName As String, ByVal _
   lpszRemoteName As String, lSize As Long) As Long  
#End If

**Comment by comintern** [comment]
Yes and no.  RD currently evaluates the precompiler directives to determine which code block to inspect.  If the result is inside the top block, then RD evaluated `#If VBA7` as `True` and inspected the top block.  As far as the parser is concerned, the bottom block doesn't exist.  The inspection is suggesting not splitting the parameter declaration itself (`ByVal lpszRemoteName As String`) between two lines - i.e., putting the line continuation either before...
```
 Declare PtrSafe Function WNetGetConnection32 Lib "MPR.DLL" Alias _
    "WNetGetConnectionA" (ByVal lpszLocalName As String, _
    ByVal lpszRemoteName As String, lSize As Long) As Long
```
...or after:
```
 Declare PtrSafe Function WNetGetConnection32 Lib "MPR.DLL" Alias _
    "WNetGetConnectionA" (ByVal lpszLocalName As String, ByVal lpszRemoteName As String, _
    lSize As Long) As Long
```

**Comment by retailcoder** [comment]
The inspection is suggesting to keep the `ByVal` modifier together with the parameter it's for, which is currently on another line.

**Comment by SystemsModelling** [comment]
OK, thanks.
