### ISSUE TITLE
an underscore is not always a continuation line

### ISSUE THREAD

**Issue by SystemsModelling** [rubberduck-vba/Rubberduck#2644]
````vb
Sub testRD2()
Dim i As Long
10 For i = 1 To 10
20    Debug.Print i  ' comment_
30 Next i
' putting an underscore on the end of comment gets:
'   Consider renaming line label '30'   VBAProject.Module1

End Sub
````

same happens if a variable name ends in an underscore and is last on the line and the next line has a line number .

**Comment by retailcoder** [comment]
Does it happen if you remove line numbers?

**Comment by SystemsModelling** [comment]
It does not happen if  I remove line numbers.
Try
10 X = MY_CONST_
20 stop

Line continuation is space underscore at end of line. Ignore any other _ at EOL.

**Comment by comintern** [comment]
Fix will be in my next PR.
