### ISSUE TITLE
Name .. As ... not seen as using a var

### ISSUE THREAD

**Issue by SystemsModelling** [rubberduck-vba/Rubberduck#2646]
> Variable 's2' is not used	VBAProject.Module1

````vb
Sub testRDUsed()
Dim s1 As String, s2 As String
s1 = "test.xls"
s2 = s1 & ".bak"
Name s1 As s2
End Sub
````

**Comment by comintern** [comment]
This probably just needs to be added in the `IdentifierReferenceResolver`.   `NameStmtContext` appears to have been missed.

**Comment by comintern** [comment]
Confirmed that adding a `NameStmtContext` listener fixes this - will be in my next PR.
