### ISSUE TITLE
How to turn off inspections

### ISSUE THREAD

**Issue by SystemsModelling** [rubberduck-vba/Rubberduck#2647]
So, how do I disable certain tests

a) for the whole project

b) for one module

c) for one procedure

d) for one line

Some things are not an issue in my eyes:

	Member 'testrd1' is implicitly public	VBAProject.Module1
Implicitly Public I accept.

	Instruction contains multiple declarations	VBAProject.Module1
Dim s1 As String, s2 As String
How else would I do it? One per line?
I can understand catching Dim x,y As Long but that would be caught by "implicitly Variant"

**Comment by retailcoder** [comment]
You can disable an inspection by selecting any of its results and clicking the "Disable this inspection" link at the bottom of the toolwindow; this is a shortcut for finding the inspection in the inspection settings and setting its *severity* level to "Do not show"; inspections at that severity level simply don't run.

Alternatively, you can ignore specific inspection results by "fixing" them using the "Ignore once" quickfix, in the "Fix" menu. This adds a special comment on the code line immediately above the target, e.g.:

    '@Ignore MultipleDeclarations
    Dim s1 As String, s2 As String

**Comment by retailcoder** [comment]
Module-level `@Ignore` annotations are planned, but not implemented yet.

**Comment by SystemsModelling** [comment]
"retailcoder changed the title from How to turn off tests to How to turn off inspections "

Ah yes ... tests are a whole other thing I haven't looked yet, I've just been focusing on Code Inspection

**Comment by retailcoder** [comment]
@SystemsModelling that feedback is terrific BTW, keep it coming! :smile:
