### ISSUE TITLE
Reopening project raises "An item with the same key has already been added."

### ISSUE THREAD

**Issue by SystemsModelling** [rubberduck-vba/Rubberduck#2653]
Open a .xlsm, click Pending.
Close it.
Re-open the workbook.
This is with no Excel add-ins, and no VBE addins other than RD.

---------------------------
Microsoft Visual Basic for Applications
---------------------------
Run-time error '-2147024809 (80070057)':

An item with the same key has already been added.
---------------------------
OK   Help   
---------------------------

**Comment by Falthazar** [comment]
I'm getting the same error.

![image](https://cloud.githubusercontent.com/assets/19520197/22704314/3f009ef8-ed35-11e6-8715-d8076c40e3a2.png)

**Comment by retailcoder** [comment]
Are you waiting for 'Ready' state before closing? RD is doing *a lot* of work on background threads, and task cancellation isn't quite there yet (it's improving greatly in 2.0.12 though).. in any case this looks like it would be a cache invalidation issue (the project and its modules are expected to be removed from parser state when it's re-added) - I'm just puzzled with the msgbox coming from VBA and not .NET...

**Comment by Falthazar** [comment]
For me, I was restarting because it got stuck on "Resolving declarations".

**Comment by comintern** [comment]
The function that is causing the exception is `RegisterComponentsEventSink` when the project is reopened.  It appears that `UnregisterComponentsEventSink` isn't getting called when a project is closed. I can replicate this even if the parse\inspection is allowed to run to completion. 

This doesn't strictly seem to be a problem with the parser either.  If I do this:

1. Open Excel
2. Open the VBE
3. Open foo.xlam
4. Close foo.xlam
5. Reopen foo.xlam
6. Hit the parse button

It throws on `ExportDocumentModule` with an IO exception in mscorib.dll:

![untitled](https://cloud.githubusercontent.com/assets/8944005/22763035/05f9170e-ee28-11e6-9597-915494b69b5a.png)

**Comment by retailcoder** [comment]
Hmm, that would be the temp file the parser exports in the module/procedure attributes pass... which is supposed to get promptly deleted. WTF?

**Comment by comintern** [comment]
This appears to have been resolved in the current build.
