### ISSUE TITLE
Version check throws error if server is unreachable

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#2657]
************** Exception Text **************
System.Net.WebException: The remote name could not be resolved: 'rubberduckvba.com'
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)

**Comment by retailcoder** [comment]
Oh, yeah, well, that's kind of a problem indeed.

**Comment by retailcoder** [comment]
I can't fix that one from my fork just now, my [next] branch is in some sort of broken state with the inspections half-redesigned.
