### ISSUE TITLE
Source Control: Excel crashes after providing credentials for GitHub

### ISSUE THREAD

**Issue by JoLuGit** [rubberduck-vba/Rubberduck#2662]
I tried to use Source Control with the following environment
- Windows 7
- Excel 2010
- Rubberduck 2.0.11.2453
I did the steps according to 
https://github.com/rubberduck-vba/Rubberduck/wiki/Source-Control:-Getting-Started

With the first commit Rubberduck asks for the credentials of GitHub and after typing in the data Excel crashes.
This behavior is independent of using first commit or using Push or Sync on the page "Unsynced commits". Here Excel crashed also after typing in the credentials of GitHub

Last lines of the log...
```
2017-02-08 08:57:11.2046;TRACE-2.0.11.2453;Rubberduck.UI.SourceControl.UnsyncedCommitsViewViewModel;Pushing;
2017-02-08 08:57:21.7867;TRACE-2.0.11.2453;Rubberduck.UI.SourceControl.SourceControlViewViewModel;Requesting login;
```

**Comment by JoLuGit** [comment]
I have tried it also on Windows 10 with Excel 2013 -> same error

**Comment by YuriMatizen** [comment]
I have the same issue using office 2016, windows 10. Rubberduck 2.1.0.8593

**Comment by retailcoder** [comment]
Fixed.

**Comment by Vogel612** [comment]
@retailcoder as of #3401 ?

**Comment by retailcoder** [comment]
@Vogel612 should be, yeah.

**Comment by Vogel612** [comment]
useful information in case it crops up again ... ;)
