### ISSUE TITLE
SQL Editor

### ISSUE THREAD

**Issue by Imh0t3b** [rubberduck-vba/Rubberduck#2664]
Hi,

I`m missing an SQL-Editor with Syntax-Highlighting and Code Formating. 

BTW nice work, this tool. It will make my life easier.

Greetz Imh0t3b

**Comment by retailcoder** [comment]
Thanks for the feedback!

Unfortunately it seems this feature would be a bit out of scope for now - it might make an interesting plugin idea though, once we've restructured our add-in into a plugin architecture (that's planned).

In the meantime issues #1277 / #929 seem to be a fair compromise in terms of project scope; once that's implemented you can copy SQL statements from your favorite SQL editor, and "paste as string literal" into the VBE.

**Comment by Imh0t3b** [comment]
Thanks for information. SQL-Editor would be great for all MS-Access devs. I will stay patient, may be I can program this on my own. Cloud be a nice project or are there any urgent Isses where I can help (e.g.: german translation or minor programing tasks).

**Comment by retailcoder** [comment]
There are several low-hanging fruit in the issues list, indeed - we're just a handful of devs with limited time and resources, and any help/contribution is welcome!

Feel free to star+fork the repository; the wiki has all the information for the initial setup - note that inspections are currently on a feature freeze, with major structural changes coming up. Don't hesitate to ask if you have any questions!
