### ISSUE TITLE
Parser & Resolver errors with VBA project using vbWatchDog

### ISSUE THREAD

**Issue by bclothier** [rubberduck-vba/Rubberduck#2665]
If a VBA project contains modules from vbWatchDog ( http://www.everythingaccess.com/vbwatchdog.asp ), parser will fail to parse ErrEx_Helper which contains empty stubs for internal uses.

Even if I hand-edit the module to use line breaks instead of colon for breaking statements, the parse phase will succeed but it will fail with resolver error (and won't go into details why it failed.

**Comment by retailcoder** [comment]
ref. #2301

**Comment by comintern** [comment]
Can you post the code from the module?

**Comment by retailcoder** [comment]
Looking at the last comment on the linked issue, it seems possible that the parse might actually be failing in the module/procedure attributes pass. Are the line numbers off in the reported parse errors?

**Comment by WaynePhillipsEA** [comment]
Thanks for posting this issue.   I've had a few customers mention this to me.  The issue appears to be due to the Attribute VB_Description appearing after the End Sub, which your parser doesn't seem to like:

`Public Sub Foo(): End Sub
Attribute Foo.VB_Description = "Foo description"

Public Sub Bar()
End Sub`

**Comment by retailcoder** [comment]
@WaynePhillipsEA Ooooh!! Indeed that would do it! The grammar we're using is assuming the procedure attributes are enclosed in the procedure's scope.. should be an easy fix, thanks a bunch!

**Comment by ckuhn203** [comment]
It seems not a day goes by where this project doesn't make me go "Wait! That compiles!" :+1:

**Comment by ThunderFrame** [comment]
instruction separators strike again
