### ISSUE TITLE
Member 'Sheets' implicitly references ActiveSheet	 

### ISSUE THREAD

**Issue by SystemsModelling** [rubberduck-vba/Rubberduck#2669]
Dim AllOrSelectedSheets As Sheets

**Comment by ThunderFrame** [comment]
Where is that delared? In a standard module? In a procedure or at module level?

**Comment by SystemsModelling** [comment]
Sorry, in a proc in a standard module

Function AllOrSelectedWorkSheets(wb As Workbook, bAll As Boolean) As Collection
   Dim oSheet As Object, AllOrSelectedSheets As Sheets
   If bAll Then
      Set AllOrSelectedSheets = wb.Worksheets
   Else
      Set AllOrSelectedSheets = ActiveWindow.SelectedSheets
   End If
   Set AllOrSelectedWorkSheets = New Collection
   For Each oSheet In AllOrSelectedSheets
      If TypeOf oSheet Is Worksheet Then AllOrSelectedWorkSheets.Add oSheet
   Next
End Function

**Comment by ThunderFrame** [comment]
I can't repro this in the latest branch.

**Comment by retailcoder** [comment]
Fixed. Added to the project tracker for, well, trackability :smile:
