### ISSUE TITLE
Move module-level variable '...' to a smaller scope

### ISSUE THREAD

**Issue by SystemsModelling** [rubberduck-vba/Rubberduck#2670]
To access class variables they need to be public. Otherwise I have to write pairs of Let/Get properties which do no more than Let/Get and just add clutter.

Example
Source:
https://msdn.microsoft.com/en-us/library/office/ff192938.aspx

Class EventClassModule:
Public WithEvents App As Application

 
Standard module:
Dim X As New EventClassModule 
Sub InitializeApp() 
 Set X.App = Application 
End Sub

**Comment by ThunderFrame** [comment]
But Encapsulation!!!

**Comment by SystemsModelling** [comment]
I'll encapsulate if I ever have a problem that would be solved by it  :-)

**Comment by ThunderFrame** [comment]
In my experience, it's the problems you avoid by using it.

How about a factory method that you pass `Application` to?

    Dim X As EventClassModule
    Set X = Factory.CreateEventClassModule(Application)

**Comment by SystemsModelling** [comment]
As in http://stackoverflow.com/questions/15224113/pass-arguments-to-constructor-in-vba

OK, but just looks a more obscure way of doing something that is more simply expressed as 
Set X.App = Application

Shall we close this as it's a matter of consistency, style and taste?

**Comment by ckuhn203** [comment]
I'm just going to chime in for posterity here and say that this request violates the spirit and purpose of the project. RD is largely meant to encourage well accepted coding practices, such as encapsulation. Exposing public fields violates that principle.

**Comment by retailcoder** [comment]
There's an *encapsulate field* refactoring that makes writing the `Property Get` / `Property Set` boilerplate pretty effortless, too.

**Comment by SystemsModelling** [comment]
Thanks!
