### ISSUE TITLE
Feature suggestion: Project statistics

### ISSUE THREAD

**Issue by SystemsModelling** [rubberduck-vba/Rubberduck#2672]
After all that parsing, how about a command that dumps a sheet of summary statistics on modules, procs, variables, LOC count, comment count, ...?

**Comment by ThunderFrame** [comment]
linking #1410

**Comment by Vogel612** [comment]
at the time was closed, because the intention was to cram it into the Code Explorer. This also seems a good place to put other analytical results like avg/max/min cyclomatic complexity and other "maintainability" scores

**Comment by retailcoder** [comment]
ref. #403 - the plan is to have an actual toolwindow (perhaps reusing the *search results* toolwindow) to display these, along with more advanced code and code path analysis results.
