### ISSUE TITLE
Using 'Fix all occurrences in project' on an aggregate inspection result only fixes one instance.

### ISSUE THREAD

**Issue by MDoerner** [rubberduck-vba/Rubberduck#2686]
Results when starting:
![globalinspectionresulthasnoname2](https://cloud.githubusercontent.com/assets/22868956/22907367/0a3212b0-f249-11e6-9903-13b829f6995d.jpg)

Results after hitting 'Fix all occurrences in project' and waiting a few minutes for the inspections to rerun:
![aggregatefixallonlyoneinstanceafter](https://cloud.githubusercontent.com/assets/22868956/22907385/269bfb32-f249-11e6-9333-26e7f883ce5f.jpg)

**Comment by mbl123** [comment]
It seems that this also applies for "Fix all occurrences in module". It only fixes the first occurrence.

**Comment by Vogel612** [comment]
This is somewhat nontrivial for both cases, since the AggregateInspection doesn't really know which inspection it aggregates. 

Additionally this is blocked by the refactoring around Inspections in the works at #2951

**Comment by retailcoder** [comment]
@Hosch250 I need to check, but could your last PR have fixed this?

**Comment by Hosch250** [comment]
This was fixed a few PR's ago, back when I rewired the quick fixes after rewriting them.
