### ISSUE TITLE
Refactorings use Regex-Replaces and Raw String operations too often

### ISSUE THREAD

**Issue by Vogel612** [rubberduck-vba/Rubberduck#2688]
It's been discussed in #2684 already: A lof of the refactorings use Regex-Replaces or String operations to perform their duties.

This leads to problems when not considering corner cases. Finding and handling said corner cases results in a lot of additional code. It's quite possibly much cleaner and less dangerous to instead use the `TokenStreamRewriter` we get from ANTLR to "correct" the parse-tree as needed. 

Access to said rewriter or a factory could be encapsulated in a separate Code-Rewriting API to expose a simple but powerful API for dogfooding.

**Comment by Vogel612** [comment]
@retailcoder is this issue still relevant?  I haven't seen any quick-fixes or refactorings use raw strings for a while now ...

**Comment by retailcoder** [comment]
Must have been lost in the pile lol
