### ISSUE TITLE
Attributions should be updated in the About dialog.

### ISSUE THREAD

**Issue by comintern** [rubberduck-vba/Rubberduck#2689]
It's been a while since this has updated, and @MDoerner and AvalonEdit (at least) are deserving of attributions there.

**Comment by ThunderFrame** [comment]
HTML Agility Pack too?

**Comment by retailcoder** [comment]
@ThunderFrame right. Otherwise we'd be parsing HTML with ....regex? :see_no_evil: :hear_no_evil: :speak_no_evil:
