### ISSUE TITLE
Comment with table tags in square brackets

### ISSUE THREAD

**Issue by addohm** [rubberduck-vba/Rubberduck#2696]
I discovered today that if I reference a db table inside brackets within a comment, the indenter for some reason changes everything to the following...

`'update ].].] DB for one part in the clamshell`

**Comment by comintern** [comment]
That's a problem - the placeholder text isn't being reverted back to the non-placeholder text.  What did the code look like before it was indented?

**Comment by comintern** [comment]
Never mind about the original code, I got a repro with this:
```
Public Sub Test()
Debug.Print "foo" 'update [foo].[bar] in the frob.
End Sub
```
Should be an easy fix.

**Comment by retailcoder** [comment]
removed actual square brackets from title... it messes up our chatbot :smile: 

![image](https://cloud.githubusercontent.com/assets/5751684/23034061/78d55a5a-f448-11e6-81d3-6a5a13a86d42.png)
