### ISSUE TITLE
RD shouldn't blow away the log file on open if logging is disabled in settings.

### ISSUE THREAD

**Issue by comintern** [rubberduck-vba/Rubberduck#2697]
This one might be my fault - the log file header always writes regardless of the logging level.  Need to test it though.

**Comment by shadowofsilicon** [comment]
I'm working on this and have it mostly implemented...  My fix has it write the header on startup only if the `LogLevel` is not `Off`.  If it is `Off` on startup, then it writes the header when the `LogLevel` changes, i.e. when the user selects a different log level via the Settings window.

I'm thinking, though, would it be worth it to log anytime that the `LogLevel` changes to anything other than `Off`?  Would that be useful debugging information?
