### ISSUE TITLE
ByValParameterAssignmentInspection

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#270]
A parameter that is passed by value shouldn't need to be assigned; such assignments may indicate the author *intended* for the caller to receive the new value, but did not pass the parameter by reference - this would be a bug.

**Comment by ckuhn203** [comment]
A bug, or terribly confusing. :+1:

**Comment by retailcoder** [comment]
This issue should already be closed:

![image](https://cloud.githubusercontent.com/assets/5751684/10115976/29192e1c-63ec-11e5-97d6-4fdff09284da.png)
