### ISSUE TITLE
Moving toolwindows in VBE, crashes host

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#2701]
Move/drag/dock/undock - it doesn't matter (although it doesn't appear to be all windows)

Steps to reproduce:

1. Open Excel with or without a new default workbook
2. Launch the VBE and wait for the auto-parse to complete
3. Do **not** press the parse button
4. Drag a built-in or RD toolwindow to a new location (I dragged Code Explorer from below Project Explorer to above Project Explorer.
5. Crash Excel

It doesn't seem to happen if you **DO** press the parse button, and then move toolwindow.

**Comment by ThunderFrame** [comment]
Linking #2700 
These seem to be related. Dragging the immeiate window has the same impact as pressing Ctrl+G.

**Comment by comintern** [comment]
This should be resolved as of commit d24ed826.
