### ISSUE TITLE
Code Explorer should support exporting multiple modules/components

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#2707]
RD lets me import multiple modules, but doesn't let me export multiple modules.

the CE context menu should let me choose "Export Components..." and then let me choose which components to export.

**Comment by ckuhn203** [comment]
This should be simple to implement. I'd be happy to help a first timer with this one.

**Comment by daFreeMan** [comment]
_considers waiving his hand. Wants to play with Git more before he does..._

**Comment by ckuhn203** [comment]
Ok @daFreeMan. I'll do some leg week this weekend and post it here for you.
