### ISSUE TITLE
SourceControl doesn't allow picking a network location 

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#2709]
RD 2.0.11 Excel 2007 Win10
I set my `Default Repository Location` by UNC to point to the network. Unfortunately, the `Browse for Folder` dialog presented when trying to `Initialize New Repository` doesn't default to that location, nor does it give a `Network` folder option for me to browse to my preferred location.
![rd sc 2](https://cloud.githubusercontent.com/assets/11889733/23146115/eef403ce-f7a1-11e6-843f-cfef04825f48.PNG)

**Comment by retailcoder** [comment]
I agree it's an issue, but I'd argue you probably want your local to be, well, *local*.

**Comment by comintern** [comment]
Closed via #2735.
