### ISSUE TITLE
Source Control Clone generated an unknown error

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#2711]
RD 2.0.11 Excel 2007 Win10

I used `git init --bare` on a network folder to create an empty master repo.
In RD-SC, I used `Manage|Clone Remote Repository` to create a copy of the repo as my `local`. 
I got an `Unknown error` as follows
![rd sc 3](https://cloud.githubusercontent.com/assets/11889733/23148327/ff65e7b6-f7b2-11e6-83bc-8c05369d8aae.PNG)
the log is attached.
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/788929/RubberduckLog.txt)
I know that this error
`2017-02-20 21:17:52.6133;TRACE-2.0.11.2453;Rubberduck.UI.SourceControl.SourceControlViewViewModel;Displaying Error with title 'Failed to clone remote repository.' and message ''d:/users/brett/documents/SourceCode/CheapHotels' exists and is not an empty directory';`
is exactly as it said, since I had the folder on my D: drive. I deleted the folder and allowed SC to recreate it & clone the master into it which generated the rest of the log.

**Comment by Hosch250** [comment]
Ouch.  Looks like you cloned an empty repo, and you can't do that (no branches found).  I don't remember everything that happens here, but I fought that long and hard last summer; looks like I missed a situation.  There are two ways to fix this.

1) Create a local repo and do a "push" to the remote.
2) Initialize the remote and then clone it.

**Comment by retailcoder** [comment]
Also, make sure you take a look at your `%appdata%\Rubberduck\SourceControl.rubberduck` file and delete any `<Repository>` node that shouldn't be there anymore. Hmm, we need to fix that too.

**Comment by Vogel612** [comment]
One issue here is that we seem to overrule the specific error message as evidenced by the log here:

```
2017-02-20 21:18:08.7631;TRACE-2.0.11.2453;Rubberduck.UI.SourceControl.SourceControlViewViewModel;Displaying Error with title 'No branches found' and message 'Repository does not contain any branches.';
2017-02-20 21:18:08.7631;TRACE-2.0.11.2453;Rubberduck.UI.SourceControl.SourceControlViewViewModel;Displaying Error with title 'An unknown error occurred.' and message 'If logging is enabled, you may create an issue on our GitHub page with the contents of your log file in '%AppData%\Roaming\Rubberduck\Logs' for support.';
```

@daFreeMan could you please verify what happens when you give the remote path as explicit file path like so:

    file://nas/data/SourceCode/CheapHotels

**Comment by daFreeMan** [comment]
@Vogel612 I will do so when I'm in a position I can recreate (i.e. back on my home machine)

**Comment by daFreeMan** [comment]
I got an almost identical error trying to do `Manage | Open Existing Repository`, but it looks like the error is on a different line of code in `SourceControlViewViewModel.cs`

[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/793427/RubberduckLog.txt)

**Comment by Vogel612** [comment]
@daFreeMan from what I can tell in the log, they're both on line 229, sooo ... does seem to be the same

**Comment by rubberduck203** [comment]
#3758
