### ISSUE TITLE
SourceControl `Initialize New Repo` throws error, yet works

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#2715]
RD 2.0.11 Excel2010 Win7

I deleted `..\Rubberduck\SourceControl.rubberduck`, then I opened an Excel workbook that I've got code in, then selected `Initialize New Repo` to export my code so git can manage it, the SC module returns an error:
```
2017-02-21 08:24:56.9315;TRACE-2.0.11.2453;Rubberduck.UI.SourceControl.SourceControlViewViewModel;Initializing repo;
2017-02-21 08:24:57.1785;TRACE-2.0.11.2453;Rubberduck.UI.SourceControl.SourceControlViewViewModel;Displaying Error with title 'Unable to perform initial commit.' and message 'Configuration value 'user.name' is missing or invalid.';
```
Yet all my code appears in the directory I pointed it to, along with the `.git` folder with all its files.
Full Log: [RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/790214/RubberduckLog.txt)

Closing out Excel, I again deleted '..\Rubberduck\SourceControl.rubberduck', deleted all code from the local drive location, opened my Excel file, went to the SC settings tab and click `Update` without making any changes, then executed `Initialize New Repo` the error repeated, yet the init was successful.

Repeating the clean up and restart steps, this time I went to `SC|Settings` and entered a `Default Repository Location`. hit update and was notified that 'user name, email address, and default repository location` were saved.  Executing `Initialize New Repo` _still_ returns the "Configuration value 'user.name' is missing or invalid." error, but generates the code.

I believe the issue is that it's assuming that I'm going to maintain my code on a hosted service, when, in fact, I'm going to maintain my local repo on my local hard drive and the "master" repo on our internal network, _not_ on GitHub or other service requiring a log-in.

**Comment by mansellan** [comment]
This should be fixed now, as of #3401.
