### ISSUE TITLE
`Procedure 'x' can be written as a function` shouldn't fire if the parameter is an object

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#2719]
If a procedure has only one `ByRef` argument, the `Procedure 'x' can be written as a function` inspection fires.

However, if that argument happens to be an object type, the `Procedure 'x' can be written as a function` should _not_ fire, instead, a the `Object passed ByRef can be passed ByVal` inspection should fire.

If this change is declined, then the QuickFix for `Procedure 'x' can be written as a function` needs to be aware of the fact that the parameter could be an object because the generated code will create a RTE 91.

```VBA
Dim foo as Object
Set foo = new Object
DoSomething foo

Sub DoSomething (ByRef bar as Object)
  bar.baz = 'x'
End Sub
```

After the current QuickFix:
```VBA
Dim foo as Object
Set foo = new Object
foo = DoSomething 

Function DoSomething (ByVal bar as Object) as Object
  bar.baz = 'x'
  DoSomething = bar
End Sub
```

generates run time error 91 invalid use of Object

**Comment by retailcoder** [comment]
I support this modification. Rewriting the procedure as a function shouldn't be a suggestion when the parameter is an object, it just looks too awkward.

The parameter can still be passed `ByVal` though.

**Comment by daFreeMan** [comment]
The only drawback to passing the object `ByVal` to a `Sub` is it can mask the fact that the object is being updated within the `Sub`. Of course clean code means the `Sub` is small enough to make that fairly obvious, but not everyone using RD will have clean code to begin with. 

Still, this change needs to be made.

**Comment by comintern** [comment]
@daFreeMan - The caller isn't responsible for protecting the state of the underlying object - only protecting the *reference* to the object.  The state of the object is the responsibility of the object, not the code that uses it.  The assumption should always be that unless an object reference is `Nothing` that any bit of code that holds that reference can use it - including setting properties or calling methods that have side effects. If the use case is to be able to pass an immutable set of data around, it should be implemented with a `Type`, not as an `Object`.

**Comment by retailcoder** [comment]
@comintern ....or an immutable object ;-)

**Comment by A9G-Data-Droid** [comment]
Gee whiz. I did a similar thing. My code runs but I'm not seeing that suggestion in code inspection. I copy and pasted your code above. No such warning or suggestion in code inspection. I even went in to settings and hit reset on code inspections. I still don't see that message.

```
Public Sub canBeFunction()
    Dim foo As Object
    Set foo = CreateObject("Scripting.Dictionary")
    Debug.Print foo.Count
    DoSomething foo
    Debug.Print foo.Count
End Sub

Private Sub DoSomething(ByRef bar As Object)
    bar.Add "x"
End Sub
```

**Comment by IvenBach** [comment]
I double checked this and I'm not getting any issue either.

Tried with code below that I know used to give results.
```
Public Sub test()
    Dim bar As String
    bar = "old value"
    RewriteAsFunction bar
    
    Debug.Print bar
End Sub

Public Sub RewriteAsFunction(ByRef value As String)
    value = "new value"
End Sub
```

`Procedure can be written as a function` is set to `Suggestion` and there is no annotation to ignore this inspection.

**Comment by MDoerner** [comment]
I think the title for this issue is very misleading. The inspection should also fire for object type parameters, but only if they are assigned to. That is not the case in the provided MCVE.

So, I guess the issue should rather be called. Procedure can be written as function should not return results if there is no assignment to the parameter.
