### ISSUE TITLE
About box needs FB logo/link

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#2723]
Rubberduck is on Facebook! Has been for quite a while.. recently I've connected RD news to the RD Facebook page, so RD news get posted there too.

The about box should have a link to Rubberduck's Facebook page.

Also... how about some of you guys +1/like that page? Would anyone like to co-administrate it?

**Comment by PeterMTaylor** [comment]
I have a few Facebook posts mentioning RD that's linked to a couple of twitter responses I like too.

**Comment by ThunderFrame** [comment]
I'm a luddite - don't have a facebook account, although I was once tempted to join just for https://www.facebook.com/shitbrickfencesofmelbourne/

I can produce a XAML version of the logo though.

**Comment by retailcoder** [comment]
@PeterMTaylor posting more often than I do about how the project is progressing, screenshots of the current/next build, what we're working on.. it's not that I don't like FB, it's just that I.. well, ok, I don't like FB.

I think it could just as well be RD News articles - these update the news feed on the website, and get posted to both Twitter and Facebook (I should set up Google+ too)... IDK, I feel like the RD News blog should be about the project's progress, announcements, and then also articles about using RD, writing testable OOP code in VBA, how and when to use refactorings, and how to perform them manually too. Pretty much everything that revolves around the project.

**Comment by PeterMTaylor** [comment]
I can help if there is a project (RD) defined content plan done so a delegate (usual admin) can grasp the goals of the project from a social media point of view that is consistent with the spirit and focus of GitHub direction. mind you it includes google plus, fb, twitter, blogs that helps summarises how it fits. Sort of like how COM fits with VBE on a technical level.

**Comment by retailcoder** [comment]
Basically the idea is to *generate content* in the Wild Wild Web 🌏 I think the easiest way to do that is to author posts on RD News; then the linked social media accounts publish the content.

**Comment by PeterMTaylor** [comment]
Food for thought about social media. https://blog.bufferapp.com/social-media-storytelling?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+bufferapp+%28Updates+and+tips+from+Buffer%29
