### ISSUE TITLE
SourceControl doesn't honor `Default Repository Location` setting

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#2726]
I set a `Default Repository Location` in the settings tab of my SC dialog. When I select any of the options in the `Manage` drop down, the folder selector always starts at `Computer` with all options collapsed.
![rd sc default](https://cloud.githubusercontent.com/assets/11889733/23232224/717ca572-f918-11e6-8ad9-f260b9fb08b0.PNG)
One might assume (with all attendant risk) that it would expand the appropriate drive to the path selected in the `Default Repository Location` field in order to ease the selection of a source or destination.

**Comment by Vogel612** [comment]
This boils down to setting the "current path" on the "directory chooser dialog" (didn't check for it deeply).

**Comment by daFreeMan** [comment]
hmmm.. it seems that it does honor the `Default Repository Location` when Cloning a Remote.

I entered the remote:
![rd sc clone remote repository](https://cloud.githubusercontent.com/assets/11889733/23241595/e563bf7e-f941-11e6-8cde-47f0797f8c4e.PNG)

it nicely added a backslash behind the local default, right in front of the 2 backslashes at the beginning of the UNC. :)

**Comment by ckuhn203** [comment]
@daFreeMan would you mind opening up s new issue for that? The correct behavior should definitely be the local directory reading `D:\Users\Brett\Documents\SourceCode\TestGit4`

**Comment by daFreeMan** [comment]
@ckuhn203 - sure. I'll do it this evening when I'm home and have access to that same image again.

**Comment by ckuhn203** [comment]
Thanks!

**Comment by daFreeMan** [comment]
@comintern is it safe to assume that the path problem I noted [here](https://github.com/rubberduck-vba/Rubberduck/issues/2726#issuecomment-281867704) was resolved, despite my not posting an additional issues as @rubberduck203 requested?
