### ISSUE TITLE
`Rename` issues invalid name clash error

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#2727]
The relevant bits of source code:

```VBA
Option Explicit
'@folder "Data Objects"

Private pName As String
Private pIndustryCode As Long
Private pIndustry As String
Private pLastYearAppts As Long
Private pLastYearEmail As Long

Public Property Get IndustryCode() As String
  IndustryCode = pIndustryCode
End Property
Public Property Let IndustryCode(ByVal Value As String)
  pIndustryCode = Value
End Property

Public Property Get Industry() As String
  Industry = pIndustry
End Property
Public Property Let Industry(ByVal ic As String)
  pIndustry = ic
End Property

Public Property Get LastYearAppts() As Long
  LastYearAppts = pLastYearAppts
End Property
Public Property Let LastYearAppts(ByVal Value As Long)
  pLastYearAppts = Value
End Property
```
`Refactor | Rename` changing `ic` to `Value` generates this error message:

![rs scope clash](https://cloud.githubusercontent.com/assets/11889733/23233574/453ca84a-f91d-11e6-8f91-8b5c80cc66de.PNG)

and the _looong_ log (yikes! 3+MB), in case there's anything useful down near the bottom:
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/794872/RubberduckLog.txt)

**Comment by daFreeMan** [comment]
It _will_ rename if I click `Yes` and it compiles and parses just fine.

**Comment by retailcoder** [comment]
That's just the "scope check" being a bit zealous. Truth is, that "scope check" should be implemented elsewhere - VBA scoping rules shouldn't need to be reimplemented everywhere we need to check if a name is already accessible from a given scope.
