### ISSUE TITLE
Parameter Not Referred To QuickFix leaves uncompilable code

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#2730]
RD 2.0.11 Excel2010 Win7

Starting with this:

```VBA
Private Sub PrintBannerCell(ByVal Rng As Range, ByVal BackColor As Double, ByVal BackTint As Double, ByVal Width As Single, ByVal Text As String, _
                                   ByVal SpanColCount As Long, ByVal BoldFlag As Boolean, ByVal Borders As Boolean, ByVal BottomBorder As Boolean, ByVal TopBorder As Boolean, _
                                   Optional ByVal FormatFlag As String = "t")
```
Executing the `Remove Unused Parameter` QuickFix leaves this:
```VBA
Private Sub PrintBannerCell(ByVal Rng As Range, ByVal BackColor As Double, ByVal BackTint As Double, ByVal Width As Single, ByVal Text As String, _
                                   ByVal SpanColCount As Long, ByVal BoldFlag As Boolean, ByVal Borders As Boolean, ByVal BottomBorder As Boolean, ByVal TopBorder As Boolean, _
                                   Optional ByVal FormatFlag As String = "t")

Dim rng2 As Range
Private Sub PrintBannerCell(ByVal Rng As Range, ByVal BackColor As Double, ByVal BackTint As Double, ByVal Width As Single, ByVal Text As String, ByVal SpanColCount As Long, ByVal BoldFlag As Boolean, ByVal BottomBorder As Boolean, ByVal TopBorder As Boolean, Optional ByVal FormatFlag As String = "t")
  Else
    Rng.Value = Text
```
The parameter didn't get removed from the procedure signature, but the signature was duplicated several rows below without the parameter.

Executing `Refactor|Remove Parameter` does not work correctly either (as would be expected).

In experimenting on reproductions, I have had this work once or twice, but I cannot replicate the _working_ conditions.

I believe this had been reported previously, but I couldn't find the issue.

**Comment by comintern** [comment]
That quick-fix\refactoring should probably preserve the line breaks in the original signature too.  I'd say the only case where it should combine a line is to avoid having the close parens on it's own line - for example...
```
Private Sub Foo(x As Long, y As Long, _
                z As Long)
```
...shouldn't refactor to this if you remove `z`:
```
Private Sub Foo(x As Long, y As Long, _
                )
```
But it should retain the line break if `y` is removed:
```
Private Sub Foo(x As Long, _
                z As Long)
```

**Comment by comintern** [comment]
I can't replicate this with the current build no matter what I try.  Did the module in question have any pre-compiler directives in it?

**Comment by comintern** [comment]
This is probably related to the implementation of `FindSelectedDeclaration`.  Linking #2451.

**Comment by daFreeMan** [comment]
No, no precompiler directives.

I really have a feeling that I ran into this last summer and reported it then, but haven't been able to find an issue (open or closed) on it. It could just be weak gitfu on my part.
