### ISSUE TITLE
False positive `Variable is not referred to` inspection result

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#2731]
```VBA
      Dim CohortYear As String
      CohortYear = GetNamedRangeValue(COHORT_YEAR_RANGE, COHORT_YEAR_PROMPT, False)
```
Is getting flagged:
![image](https://cloud.githubusercontent.com/assets/11889733/23277418/ca5eec7c-f9db-11e6-90d2-295abb68a48f.png)

**Comment by retailcoder** [comment]
Seems legit. The variable is *assigned*, but not *referred to*,

**Comment by retailcoder** [comment]
That said we need to fine-tune the resource strings for that one.

**Comment by daFreeMan** [comment]
crap, you're right. It's been one of those kind of days...

Leave it open for the resource string update or close it because I can't read - your choice.

**Comment by retailcoder** [comment]
@daFreeMan nah, that would be a separate issue - happy to see Rubberduck catching a potential bug in your code though! :smile:
