### ISSUE TITLE
'ByRef' modifier is redundant

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#2736]
We have [a number of open inspection issues](https://github.com/rubberduck-vba/Rubberduck/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20%22is%20redundant%22) that suggest implementing inspections that identify *redundant* settings.

We have an inspection that locates implicit `ByRef` modifiers. The rationale is that explicit modifiers make the code easier to read, especially if you're coming to VBA from another language.

But an explicit `ByRef` modifier *is* redundant; in 3.0 with the subclassed code pane it would be nice to be able to color it a few shades lighter than `ByVal` would be, accordingly with user preferences. In the same vein, an inspection for redundant explicit `ByRef` modifier makes sense - it's just the flipside of the current existing inspection; user fixes one, gets the other, decides which one they're disabling, and everybody gets to write consistent code, regardless of their preferences.

**Comment by rkapka** [comment]
A similar inspection called `ImplicitByRefParameterInspection` only adds explicit `ByRef`modifier to interface members. Is this the correct behaviour? For example, having `Foo(arg1 As Integer)` in the interface and `IClass1_Foo(arg1 As Integer)` in the implementation, only one inspection is displayed, aiming at the former declaration. Should I implement my inspection in the same vein or show to possible fixes and later on correct the existing inspection?

**Comment by retailcoder** [comment]
I'll have to test this with the current build.. 2.0.13 (release build) seems to [correctly] identify the implicit `ByRef` modifier on the interface members (in the interface class), and [correctly] ignore implicit `ByRef` modifiers in interface *implementation* members.

The idea is that, since interface implementation signatures must match, inspections with fixes that can change a method's signature should warn about the interface (once) rather than for every implementation of it; conversely, the quick-fix that adds an explicit `ByRef` modifier to an interface member signature, should also add the modifier to all implementations of that member. In other words, the signature of an interface member and every single one of its implementations is (should be) treated as one.

So the inspection is supposed to ignore `Class1.IClass1_Foo(arg1 As Integer)` and report on `IClass1.Foo(arg1 As Integer)`, and the fix *should* (doesn't seem to) be applied to `IClass1.Foo` and all its implementations; looks like we're missing a few [failing] tests...

**Comment by MDoerner** [comment]
Fixed in PR #3069
