### ISSUE TITLE
Source Control needs support for using upstream repositories from the file system.

### ISSUE THREAD

**Issue by comintern** [rubberduck-vba/Rubberduck#2744]
This has been supported by libgit2sharp for quite a while (see [#247 on libgit2sharp](https://github.com/libgit2/libgit2sharp/issues/247)). Currently it's impossible to use a non-http transport in RD unless the git config files are edited by hand or the local repositories are set up via the command line.  Attempting to clone a repository from the file system *or* publish to the file system generates errors. I haven't played around with it much, but I'd also suspect that pushing, pulling, and synching to repositories set up this way is similarly broken. Note also that VS 2013 had similar issues (mainly with "Publish"), but these were fixed in VS 2015.

Taken in combination, this makes using source control a non-starter in environments where non-local hosting of source code is either not required or prohibited by policy. For example, in my workplace all of the git head repositories are located on the development team's network share as bare repositories, and the working repos are cloned from there.  It's also common to fork another developer's working repo, which _also_ requires using file system transport.

It's likely that this is at the root of some of the other open issues around Source Control.  Without additional information about how users are attempting to set up, I'd suspect that #2041, #2561, #2477, #2715, and #2711 could be related in one way or another.

While this would technically be an "enhancement", it's also classifiable as a "bug", in that the source control module should also be handling valid git config files originating from the command line tools.

**Comment by rubberduck203** [comment]
Just a clarifying question. When you say "setting it up on the command line", are you talking about the native git shell, or the COM lib via the immediate window?

**Comment by comintern** [comment]
@rubberduck203 - I'm referring to using the git shell (or Command Prompt\PowerShell with git extensions).

**Comment by rubberduck203** [comment]
A quick look at the `GitProvider` leads me to believe that the issue is somewhere in the UI layer. 

https://github.com/rubberduck-vba/Rubberduck/blob/next/Rubberduck.SourceControl/GitProvider.cs#L102

We don't modify the file path/URI in any way at the library level. 
This could be confirmed by using a raw `GitProvider` to clone a repository on the file system. 

https://github.com/rubberduck-vba/Rubberduck/wiki/Source-Control-API#clone

If we can confirm the underlying lib works, that reduces the places we need to look. 
Man. I could swear I tested this on a `\\server\share` repository in v1 of the git code.

**Comment by comintern** [comment]
That sounds right.  I think there are some places where it's making the assumption that the path separator in the remote is `/`.

**Comment by rubberduck203** [comment]
I don't think we need to convert anything to Unix style, but I could be wrong. It's been a very long time since I worked on that code.

**Comment by mansellan** [comment]
I've done some investigation on this. It *is* possible to clone from a filesystem repo, but there are some caveats:

1. The repo must be properly initialised and contain at least one branch.
2. If the the remote is on a network drive (which must already be mapped and authenticated), then a policy key must be set in the registry - see https://technet.microsoft.com/en-us/library/ee844140%28v=ws.10%29.aspx.

Given these pre-requisites, the repo will clone:

![image](https://user-images.githubusercontent.com/25420409/31099459-f94d380a-a7bd-11e7-87cb-87afb5d07618.png)

The policy key is a problem, investigating options.

**Comment by retailcoder** [comment]
@mansellan meh, the remote path should be http/https anyway, no?

**Comment by rubberduck203** [comment]
@retailcoder, no. It will only be https/ssh if the remote is on a Git server. Git also supports file system URIs like `//server/share/repo` or mapped drives like `K:\`

**Comment by mansellan** [comment]
Appears to be a limitation of LibGit2Sharp. Question asked on SO:

https://stackoverflow.com/questions/46534743/libgit2sharp-cloning-from-a-network-file-share

**Comment by Vogel612** [comment]
@mansellan have you investigated the behaviour when adding the network location as a drive letter?

**Comment by mansellan** [comment]
@Vogel612 yes - that's the only way I could find to get it to work. It does require a policy key under HKLM though, which is unfortunate.

I have a SO question open about it, if need be I'll post an issue to LibGit2Sharp too.

**Comment by rubberduck203** [comment]
#3758
