### ISSUE TITLE
Code Inspections: Fix all occurrences in procedure

### ISSUE THREAD

**Issue by IvenBach** [rubberduck-vba/Rubberduck#2750]
I see there is the option for Module and Project but none for procedure.

**Comment by Vogel612** [comment]
May not be applicable for all inspections. Also makes me be more cautious about `CanFixInModule` and `CanFixInProject`...

This sounds like a good place for a `[Flags]` enum

**Comment by retailcoder** [comment]
Implemented. Not sure when or which commit, but this issue is closed.
