### ISSUE TITLE
Refactor: Move Closer To Usage

### ISSUE THREAD

**Issue by IvenBach** [rubberduck-vba/Rubberduck#2753]
When trying to move closer it appears to be breaking with named parameters. In this case 'Type:=8' as it replaces ':' with vbNewLine

```
Public Sub BreakingOnMove()
    Dim ParameterList As Range

    
    Set ParameterList = Application.InputBox("Select the cells that have the input parameters.", Type:=8)
End Sub
```

**Comment by comintern** [comment]
Yep - That's an issue.  Pretty sure it's in [this section of code](https://github.com/rubberduck-vba/Rubberduck/blob/next/RetailCoder.VBE/Refactorings/MoveCloserToUsage/MoveCloserToUsageRefactoring.cs#L174-L189).

**Comment by IvenBach** [comment]
When the move is successful it appears like the indentation from where it was moved FROM is preserved and may not be the same as where it was moved TO.
