### ISSUE TITLE
Refactor: Move Closer To Usage (Declaration Deletion)

### ISSUE THREAD

**Issue by IvenBach** [rubberduck-vba/Rubberduck#2754]
Tied to #2753. Once you undo to get it back to normal without 'Auto Syntax Check' red you need to resolve the 'Parse Error'. On doing that `Dim ParameterList As Range` is deleted.

An undo is required to fix the deletion then parsing appears to work without issue.

**Comment by comintern** [comment]
This would be the expected behavior for any refactoring or quick "fix" that breaks code enough that it can't be parsed anymore.  The parser needs to run after the refactoring or quickfix in order to keep track of the location of identifiers in the code.

Closing in favor of #2753.
