### ISSUE TITLE
Indefinite Parse:  Caused by {Standard || Class} Module or Form deletion

### ISSUE THREAD

**Issue by IvenBach** [rubberduck-vba/Rubberduck#2756]
Deleted both a Standard Module, Class Module, and Form which caused the parse button to be grayed out. Solution to this was to insert a blank Module or Form.

***Edit: Appears that doing anything with RD like Indenting will cause it to parse correctly and resume normal operation.

**Comment by comintern** [comment]
Changed the title to remove square brackets - they confuse our issue notifier on SE. 

Did the parse complete between each deletion?

**Comment by IvenBach** [comment]
I think so but the UI never reflected this. In my OP my edit where I mention Indentation leads me to believe it's something just graphical.

**Comment by IvenBach** [comment]
RD 2.1.6478.39476 Doesn't have this issue. Can someone else confirm? If so I'll close this.

**Comment by IvenBach** [comment]
Closing now that the issues appears to be resolved.
