### ISSUE TITLE
Code Inspection: Variable 'Mid$' is used bot not assigned && Local variable 'Mid$' is not declared

### ISSUE THREAD

**Issue by IvenBach** [rubberduck-vba/Rubberduck#2757]
Updated to Mid$ from Mid based on RD's suggestion. Now it's flagging Mid$ in some locations but not others. Appears to be just the first usage.

**Comment by comintern** [comment]
Can you post some sample code that demonstrates the issue?  By "flagging", do you mean that it's still reporting an inspection result for `Mid$`?

**Comment by comintern** [comment]
This was fixed after the 2.0.11 release.  See #2618
