### ISSUE TITLE
`Constant not used` QuickFix enhancement

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#2760]
The `QuickFix` removes all text from the line up to the start of the comment.

Add a `QuickFix`  option that will remove the whole line.

**Comment by retailcoder** [comment]
Needs to account for this:

    Const foo = 12, bar = 42 ' bar is not used
    MsgBox foo

To avoid turning it into that:

    MsgBox foo ' foo was removed and now the code is broken

**Comment by Vogel612** [comment]
Sounds like a good place for the code-rewriting API to explicitly test for ...

**Comment by IvenBach** [comment]
`Const foo = 12, bar = 42 ' bar is not used` has `foo` and `bar` both as an `Integer` in the Locals window. Inspection results have them coming up as `... implicitly Variant`.

**Comment by Vogel612** [comment]
@IvenBach that is most likely a resolver problem. Fixing the Resolver there should enable us to fix "implicitly Variant". This also relates to DefTypes, because Implicitly Variant needs to correctly take DefType assigned types into account

**Comment by retailcoder** [comment]
Is this bug still even present? Not sure we had the rewriter stuff implemented back in March 2017...

**Comment by IvenBach** [comment]
Looking at this and testing quick fix it looks like this has been taken care of.
```
Public Sub Temp()
    Const foo = 12, bar = 42 ' bar is not used
    MsgBox foo
End Sub
```
Becomes
```
Public Sub Temp()
    Const foo = 12 ' bar is not used
    MsgBox foo
End Sub
```

**Comment by Vogel612** [comment]
well... "fixed somewhen in the last year" then
