### ISSUE TITLE
Add-in will not show up after installing latest version

### ISSUE THREAD

**Issue by pokemoncvue** [rubberduck-vba/Rubberduck#2762]
Hi, I am new to rubberduck and have installed the latest version. After admin installed, I go to excel and check my com-addins and it does now show rubberduck there. I've check my programdata folder and yes, rubberduck is there with all files ect. It is just not showing up on my add in for excel. Help?

OS: windows 7 pro
Excel 2007
64bit

**Comment by Vogel612** [comment]
Just to make perfectly sure: the installer completed without any error? Did you restart the system?

If the answer to both is yes, is your account a non-admin? 
If yes, please check whether adding the registry keys described in [Installing][wiki_installing] fixes your problem. (Please check whether the keys exist, while you're at it ;))

[wiki_installing]: https://github.com/rubberduck-vba/Rubberduck/wiki/Installing#installing-for-non-admin-users

**Comment by retailcoder** [comment]
Ref. http://stackoverflow.com/a/42538268/1188513

**Comment by retailcoder** [comment]
See [installing for non-admin users](https://github.com/rubberduck-vba/Rubberduck/wiki/Installing#installing-for-non-admin-users) - let us know if that fixes it!

**Comment by pokemoncvue** [comment]
Yes, that worked. thanks all. I had to register under my name and not under the admin user.

**Comment by pokemoncvue** [comment]
I now have another issue, I have the add in ect. but all the controls are grey out like i can't click them when i try to use them such as unit test controls ect?

**Comment by retailcoder** [comment]
:+1:  See http://stackoverflow.com/q/41601588/1188513; you need to trigger the initial parse manually - that's now fixed in the current/next build; version 2.0.12 is scheduled to release this weekend!

**Comment by pokemoncvue** [comment]
that did it!

**Comment by retailcoder** [comment]
@pokemoncvue awesome! Feel free to star us if you like - and make sure you update to 2.0.12 next week, we're releasing a TON of fixes!
