### ISSUE TITLE
Something like "Integer Overflow in ComAlias with 64bit Office"

### ISSUE THREAD

**Issue by IvenBach** [rubberduck-vba/Rubberduck#2770]
Comintern requested this issue.

**Comment by IvenBach** [comment]
Changed .tlb to .txt so it would accept the file type.
[stdole32.txt](https://github.com/rubberduck-vba/Rubberduck/files/812939/stdole32.txt)

**Comment by comintern** [comment]
Can you test this again using a current pull from next?  I'm not sure how to replicate it outside of your specific environment.

**Comment by comintern** [comment]
Closed via #2771.
