### ISSUE TITLE
Tools>Regex Assistant

### ISSUE THREAD

**Issue by IvenBach** [rubberduck-vba/Rubberduck#2776]
Have a toggle that could convert whitespace to \s in the description. Helps for those like myself that rarely use them and don't have everything memorized. `[0-9]{3}[ -][0-9]{3}[ -][0-9]{4}` as an example where whitespace may be used.

**Comment by comintern** [comment]
Another option for this would be to display a warning - something along the lines of "Warning - regular expression contains embedded whitespace".

**Comment by Vogel612** [comment]
makes no sense from my perspective ... Both alternatives are equally valid. We can unfortunately not assume anything about what the user *actually* wants ... If you deem this necessary ... well do what you please. You're looking for `LiteralExpression`s where the `Specifier` equals `" "`

**Comment by retailcoder** [comment]
@Vogel612 the use case is that in the *what the regex does* part it's hard to tell when a whitespace is being matched.

> Matches ... : , - exactly once.

**Comment by Vogel612** [comment]
Then the request makes even less sense ... `\s != " "` ...

whitespace (`\s`) depending on the exact specs includes tab, horizontal tab, non-breaking whitespace and other peculiarities. ...  
Pretending one is the other in *what the regex does* is simply wrong. The correct fix for that use-case is a different formatting or a special enclosing. RD does generally use `'{0}'` and similar constructs. This seems adequate here ...

**Comment by retailcoder** [comment]
@Vogel612 fine by me, it addresses the concern!
