### ISSUE TITLE
Rubberduck fails on load in DeleteExistingCommandBar

### ISSUE THREAD

**Issue by IvenBach** [rubberduck-vba/Rubberduck#2779]
Gets stuck on `var existing = Target[name];` and won't move past it.

**Comment by comintern** [comment]
Linking chat transcript:  http://chat.stackexchange.com/transcript/message/35799595#35799595

**Comment by ThunderFrame** [comment]
Might be worth trying to run the host as Administrator - some registry entries seem to get messed up with multiple versions of `MSO.DLL` installed. See #2496

**Comment by comintern** [comment]
Closed along with #2805.
