### ISSUE TITLE
Code Inspection Settings window is missing resources somewhere.

### ISSUE THREAD

**Issue by comintern** [rubberduck-vba/Rubberduck#2787]
No clue yet what this inspection is supposed to be, but it's apparently missing resource strings:

![untitled](https://cloud.githubusercontent.com/assets/8944005/23580710/2bc716a0-00cc-11e7-86e9-dd6f93045d3b.png)

**Comment by retailcoder** [comment]
Ha! Good catch! It's `MalformedAnnotationInspection`, whose keys were renamed to `MissingAnnotationArgumentInspection` a little while back. Fix on the way.

**Comment by retailcoder** [comment]
Ok this is weird:

![image](https://cloud.githubusercontent.com/assets/5751684/23584615/574a5842-0134-11e7-80b4-05b5f0bfe0e8.png)
