### ISSUE TITLE
Word executes AutoOpen/AutoClose and not Auto_Open/Auto_Close

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#2799]
Because, Word is its own monster, isn't defined by others.

Ref #2239

**Comment by daFreeMan** [comment]
I'd be willing to take a look at it, but I'll need some guidance.

**Comment by Vogel612** [comment]
@daFreeMan you should be able to just drop by in the war room and ask around if there's guidance you need ;)

**Comment by ThunderFrame** [comment]
Also has `AutoExec` and `AutoNew`, but they don't seem to fire in all versions of Word.
