### ISSUE TITLE
Code Inspections are left over when a workbook is closed.

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#2804]
RD .12 Excel2010 Win7

I closed an Excel workbook. RD initiated a reparse, but left several inspection results for the closed workbook behind.

![rd lazy inspections](https://cloud.githubusercontent.com/assets/11889733/23616958/6bda030e-0259-11e7-90d5-12bb4a1e3bbd.PNG)
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/821620/RubberduckLog.txt)

**Comment by retailcoder** [comment]
Getting the inspections under the `ParseCoordinator` should fix this.

**Comment by retailcoder** [comment]
Can you repro with the latest build? Several changes to parser state caching have been made since.

**Comment by bclothier** [comment]
Appears to be been fixed already. Closing.
