### ISSUE TITLE
Contextual status label should tell us the scope we're in

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#2805]
When the cursor is on the current procedure's identifier, the context status tells us about it:

![image](https://cloud.githubusercontent.com/assets/5751684/23622308/215e0f6a-026c-11e7-8e13-013d77c8f8d1.png)

However if the cursor is in the body of the procedure (not on any declaration or identifier reference), then the *module* is deemed selected:

![image](https://cloud.githubusercontent.com/assets/5751684/23622395/78595068-026c-11e7-97ce-a923e5116832.png)

We should make it so that we report the *current scope* selected instead - that way the status bar tells us which procedure we're in, even when we don't see its signature. And we *still* know which module we're in, because <s>the title bar tells us already ffs</s> the name is fully-qualified.

**Comment by retailcoder** [comment]
Implemented - currently relying on `ICodeModule.GetProcOfLine`, which means the RD context status matches what the VBE considers the beginning/end of a procedure, even if that's outside the `Sub` and `End Sub` tokens. I think that should be good enough.

**Comment by ThunderFrame** [comment]
Is it worth identifying whether it is an event handler, and if it is, what the details are?

**Comment by ThunderFrame** [comment]
and, I guess, whether it's an interface member implementation

**Comment by retailcoder** [comment]
@ThunderFrame nah, it would probably get clipped anyway - there's only that much room to fit stuff!

**Comment by retailcoder** [comment]
Reopening. The referenced commit was sort-of-reverted, because it made context-sensitive selection description annoyingly flaky. Truth is, the `FindSelectedDeclaration` function needs a serious refactor.
