### ISSUE TITLE
Inspection for Enum name with implied plural

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#2806]
Convention has it that an emum name is *singlular* rather than plural:

- `Enum VbMsgBoxStyle` not `Enum VbMsgBoxStyles`
- `Enum XlPaperSize` not `Enum XlPaperSizes`

Although there are some Enums that break with convention:
- `Enum XlConditionValueTypes`
- `Enum XlTimePeriods`

And some that are valid because there's a verb in the Enum name:
- `Enum XlPivotFieldRepeatLabels`
- `Enum XlUpdateLinks`

And some that just happen to end in `s`
- `Enum XlYesNoGuess`

RD can probably do a reasonable job of finding pluralized Enum names by looking for the plural form of common Enum suffixes, and that should work across languages.

Example suffixes:
- `Colors`
- `Formats`
- `Modes`
- `Options`
- `Positions`
- `Settings`
- `Types`

**Comment by rubberduck203** [comment]
I'm a bit skeptical of this one. It doesn't hurt to implement I guess, but it feels like ramming style choices down users throats. 

If this happens, the reciprocal inspection should also be implemented. I'm not sure I'd turn either on by default.

**Comment by ThunderFrame** [comment]
I don't care what convention you follow, as long as it's ---singular--- consistent.

**Comment by retailcoder** [comment]
How about making it a new feature? Instead of naming inspections there could be a configurable set of naming style rules - might mean death for the *use meaningful name* and *Hungarian notation* inspections..

**Comment by ThunderFrame** [comment]
Project/Module level annotations?
`@style AbstractMinimalism 'use NBSP variable names`

**Comment by retailcoder** [comment]
Declining in its current form - also... I think we have something like 60 pending inspections requested/suggested but not implemented.
