### ISSUE TITLE
We should expose the APIs of RDs different functionalities in separate assemblies

### ISSUE THREAD

**Issue by MDoerner** [rubberduck-vba/Rubberduck#2826]
Let me explain why I propose this.

At the moment we have several assemblies for the different main components of RD. In case one functionality, e.g. the inspections, should change to be run from the code in another assembly, e.g. the `ParseCoordinator` in the `Rubberduck.Parsing` assembly, we run into the problem that, quite often, we cannot simply do that without moving the functionality. The problem is that we would get circular references between the assemblies. Regarding the example of the inspections, the `IInspector` interface directly depends on the `RubberduckParserState` in `Rubberduck.Parsing` and basically every inspection depends on `Declaration` in `Rubberduck.Parsing`.

An assembly level pattern that prevents such problems is the stairway pattern. In this pattern the APIs of the different functionalities are extracted into their own assemblies, basically like interfaces on the assembly level. Furthermore, the implementing assemblies only use the APIs to refer to functionality in other assemblies. 

When this pattern is fully applied, the only ingoing edge in the reference graph to the implementing assemblies is the one from the composition root, where everything gets wired up. So every implementing assembly is free to reference every API it feels necessary to reference, without restrictions.

That is why I propose to slowly work towards such a design. This would probably also be a good step towards the plug-in design envisioned for RD 3.0.

The problem is that it will be nasty work to change RD into this direction. At the moment, a lot of code relies on concrete classes in other assemblies, even the interfaces. That is a problem for the stairway pattern because it only works if the APIs only depend on the other APIs. So, to make extracting one API useful it will be necessary to remove dependencies to concrete implementations and extract the APIs it depends on, too.

Let me demonstrate this problem on the example of the inspections. Just pulling the `IInspector` out into its own assembly would not yield any benefit since it depends on the `RubberduckParserState`. This dependency could be removed by passing an `IDataForInspections` instead that gets implemented in `Rubberduck.Parsing` or wherever the user of `IInspection` lives. (This requires amending all inspections to use it instead of the state, which we should do anyway for other reasons.) Problem is, this interface will have to depend on `Declaration` since declarations are used in the concrete inspections. Because of this, it would become necessary to extract `Declaration` and everything it depends on to some `BaseSymbols` assembly.

What I would like to hear from you is what you think about this design approach and whether you think that it would be worth to go down this somewhat painful route and sort out the dependencies in RD.

Please feel free to comment below.

**Comment by comintern** [comment]
This is the main reason why I extracted the settings provider into its own assembly, and I'm going to hit the same problem with Hotkeys shortly.  As a general rule, I'd say it's a good idea to extract assemblies when it simplifies the structure, and the scattering of RD objects declared as `dynamic` also attest to that.

About the only potential drawback that I'd see is the explosion of libraries, but that's a purely cosmetic concern.

**Comment by rubberduck203** [comment]
I would recommend this approach. The project has grown immensely in the last few years and would benefit from this architecture. I think it's the next natural progression now that y'all moved to DI all the way down. :+1:

Just a word of advice, take after Comintern and only make the changes as you feel a need to, incrementally. Any effort to do this wholesale is a fool's errand.

**Comment by bclothier** [comment]
Since we already addressed this with the PR #3739, this can be considered to be partially addressed. Furthermore, we have an open issue that's more recent --  #3862, so I'm closing this to minimize duplication.
