### ISSUE TITLE
Comment Block Keyboard Shortcut

### ISSUE THREAD

**Issue by IvenBach** [rubberduck-vba/Rubberduck#2830]
Couldn't find any shortcuts. I try to circumvent the mouse whenever possible.

**Comment by IvenBach** [comment]
Method for it already exists http://stackoverflow.com/questions/12933279/how-to-comment-and-uncomment-blocks-of-code-in-the-office-vba-editor/23954017#23954017

**Comment by Vogel612** [comment]
annoyingly hard to do in VBE, should be part of basic v3 editor functionality
