### ISSUE TITLE
RD>Settings>Indenter Settings

### ISSUE THREAD

**Issue by IvenBach** [rubberduck-vba/Rubberduck#2831]
Clicking on a link in the example brings up a window, can't navigate `Back`. You have to click on another settings option then back to Indenter to have it show the example again.

**Comment by comintern** [comment]
Just to be clear, clicking the hidden hyperlinks does this (at least in Windows 10):

![untitled](https://cloud.githubusercontent.com/assets/8944005/23809958/3ecd2afa-0595-11e7-9f8f-977127dd20a0.png)

Changing the settings view to something else and then coming back resets it to the indenter settings (unclear what happens to the *browser*...). I'm almost positive that they opened in an external browser window on my Windows 7 VM at home.  Is this screenshot above similar to the behavior that you're getting?

**Comment by IvenBach** [comment]
Yes. That's the same as what I'm having happen.

**Comment by retailcoder** [comment]
So we need to start a process that the given url then... or drop the links
