### ISSUE TITLE
Change Signature Refactoring

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#284]
We need this feature to properly address #283.

A *change signature* refactoring would update a modified interface method's implementations, but it would also update all calls to that method.

Reordering, removing or renaming parameters, or changing how a parameter is passed (`ByRef`/`ByVal`), changing a parameter's type, or changing a function's return type are all actions that should trigger this refactoring.

**Comment by Vogel612** [comment]
So this is fixed as of ??

**Comment by Hosch250** [comment]
@Vogel612 Cancelled, more like it.
