### ISSUE TITLE
UserForm controls trigger "Public field breaks encapsulation" inspection

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#2840]
There isn't much a user can do about Controls being public fields. The inspection should ignore fields that are of type `DeclarationType.Control`.

**Comment by retailcoder** [comment]
Pretty sure I have that one fixed already

**Comment by comintern** [comment]
According to the comment...

`// we're creating a public field for every control on a form, needs to be ignored.`

Is this specific to Access forms?

**Comment by ThunderFrame** [comment]
standard userforms

**Comment by comintern** [comment]
Ooops... I think I might have broken this when I started resolving the types of controls to the actual interface instead of having everything resolve as a generic `Control`:

![untitled](https://cloud.githubusercontent.com/assets/8944005/23829433/b4ddf77a-06b6-11e7-8edc-e4c40a94a112.png)

I'm a bit perplexed as to why the AsTypeDeclaration is showing Excel.TextBox as the parent declaration instead of something in the MSForms namespace.

**Comment by ThunderFrame** [comment]
just a matter of setting the correct parent declaration in the Controls collector?

**Comment by retailcoder** [comment]
@comintern wouldn't the `DeclarationType` be `DeclarationType.Control` anyway?

**Comment by comintern** [comment]
@retailcoder - If it's pulling from the COM collector, no:

```
			<Node>
				<Accessibility>Public</Accessibility>
				<AsTypeName>TextBox2</AsTypeName>
				<Attributes>
					<SerializableMemberAttribute>
						<Name>VB_Customizable</Name>
						<Values xmlns:d7p1="http://schemas.microsoft.com/2003/10/Serialization/Arrays">
							<d7p1:string>True</d7p1:string>
						</Values>
					</SerializableMemberAttribute>
				</Attributes>
				<ComponentName>TextBox2</ComponentName>
				<DeclarationType>ClassModule</DeclarationType>
				<IdentifierName>TextBox2</IdentifierName>
				<IsArray>false</IsArray>
				<IsBuiltIn>true</IsBuiltIn>
				<IsByRefParam>false</IsByRefParam>
				<IsControl>false</IsControl>
				<IsExtensible>false</IsExtensible>
				<IsOptionalParam>false</IsOptionalParam>
				<IsParamArray>false</IsParamArray>
				<IsSelfAssigned>false</IsSelfAssigned>
				<IsWithEvents>true</IsWithEvents>
				<MemberName>TextBox2</MemberName>
				<ParentScope>VBE</ParentScope>
				<ProjectName>MSForms</ProjectName>
				<ProjectPath>C:\Windows\SysWOW64\FM20.DLL</ProjectPath>
				<TypeHint i:nil="true" />
			</Node>
```
I need to take a look at the code that's resolving the control declaration though - I have no clue why it picked the Excel version in the screener above ATM.

**Comment by Vogel612** [comment]
@retailcoder fixed since when?
