### ISSUE TITLE
Event handlers aren't identified as such, can be distinguished from standard procedures.

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#2842]
The context bar just lists the procedure name:

`VBAProject.Class1.myEventItem_Change (procedure)`

It would be more informative to use something like

`VBAProject.Class1.myEventItem_Change (event procedure)` 

or, better still:

`VBAProject.Class1.myEventItem_Change (procedure - handles MSForms.Textbox 'Change' event)` 

Ref: [would it be overkill for the RD commandbar to say....](http://chat.stackexchange.com/transcript/14929?m=35334529#35334529)

**Comment by retailcoder** [comment]
Not sure how useful that would be, given:

![image](https://cloud.githubusercontent.com/assets/5751684/23829561/feae94a2-06c2-11e7-8289-c92f083e875b.png)

**Comment by ThunderFrame** [comment]
Touché!

![whatami](https://cloud.githubusercontent.com/assets/16574009/23829667/39814794-074c-11e7-8f77-7cb29227e103.png)
