### ISSUE TITLE
Assert.AreEqual and Assert.AreNotEqual should return Inconclusive for reference types

### ISSUE THREAD

**Issue by comintern** [rubberduck-vba/Rubberduck#2846]
If a `_COMObject` is passed as both the `expected` and `actual` parameter of these two asserts, the test that is being performed is reference equality. This doesn't match the semantics of VBA, because VBA can implicitly call the default member if an `Object` is used in an equity comparison:

```
'@TestMethod
Public Sub TestMethod1() 'TODO Rename test
    On Error GoTo TestFail
    
    Dim foo As Range
    Set foo = Sheet1.Range("A1")
    foo.Value = "Foo"
    
    Dim bar As Range
    Set bar = Sheet1.Range("A2")
    bar.Value = "Foo"
    
    Dim equity As Boolean
    Debug.Print foo = bar       '<-- True
    
    Assert.AreEqual foo, bar    '<-- Assert fails

TestExit:
    Exit Sub
TestFail:
    Assert.Fail "Test raised an error: #" & Err.Number & " - " & Err.Description
End Sub
```
![untitled](https://cloud.githubusercontent.com/assets/8944005/23833111/32f4befc-070f-11e7-895a-d5a3e2d5c6fa.png)

However, .NET *doesn't* call the default member in this case so the `AreEqual` and `AreNotEqual` asserts are actually performing the test that `AreSame` is performing. This is non-obvious, especially given that the failure message just shows them both as `_ComObject`.

Ref #908 - Arrays are similar given how the are marshaled.

**Comment by Greedquest** [comment]
This doesn't seem to be solved in the PermissiveAssert class (still failing rather than inconclusive). At any rate, for that I think the test result should be _passed_ to reflect what VBA does.

**Comment by retailcoder** [comment]
@Greedquest doing "what VBA does" on the .NET side involves querying the first COM object for a default member, invoking that default member, recursing (recursion limit is specified as "host-dependent") until we get something that isn't an object, then doing that for the second COM object, comparing the two values, and passing if they match.

Resolving the default member calls explicitly on the VBA side of things doesn't strike me as a bad idea, especially in unit test code. If your tests *require* implicit default member calls, what you're testing is the presence/location of a special hidden attribute value, for code that wouldn't be able to compile in the first place without that attribute. You want to test whether `x.Value` is equal to `y.Value`, independently and regardless of the class' default member being `Value` today or `Name` tomorrow.

**Comment by Greedquest** [comment]
@retailcoder complex or not, and even if it may have the fortunate side effect of promoting better practices (I do agree that if it's values we're unit testing then it's better to explicit), I still think the current behaviour is *misleading*. I certainly got the impression that the permissive assert class would mimic VBA comparisons as closely as possible, although I see there's a significant technical jump between mimicking default type casting and full blown recursive member resolution.

Still, I think at the very least some explanatory text and an inconclusive result would be better than failing, and the complicated resolution to allow passing tests would be best (although I'm not sure what's typical for unit tests in other languages with default members)

After all, I have actually written tests solely to check for the presence of a hidden member (the `DefaultPropertyLetGet` test in my question on CR) . It's a good way of ensuring the attributes are in sync. And I don't know if my workaround there would also work for default object members or recursive stuff. But yeah I agree, all the other ones aren't testing that so should just use explicit members.
