### ISSUE TITLE
Add VB Attribute Annotations and associated inspections

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#2851]
[Chat](http://chat.stackexchange.com/transcript/message/35997632#35997632)
> What if RD supported some annotations like `@PredeclaredClass`, `@DefaultMember`, `@EnumMember`, `@ShortcuttedMember`, `@MemberHasDescription`, and/or `@MemberHasAttribute`.  That would help identify when attributes are inadvertently lost, but also help with inspections? RD could have inspections like "Expected ClassX to be pre-declared, but attribute is missing or removed", or "Class X default member attribute is missing or removed", and the quickfix could apply or reinstate the attribute

> Wait a minute... I think you've just found the very best way for Rubberduck to handle module/procedure attributes! 

But do we follow the arcane VB syntax, or make the attributes more user friendly, or both?

> @EnumMember instead of @VB_Attribute_UserMemId(-4)
> Or do both: @EnumMember as an alias for @UserMemId(-4) 

If we make the annotation class hierarchy richer, then `@Procedure.EnumMember` might be clearer, provide better categorization and work better with eventual intellisense?
```
'@Attribute ProcName.VB_UserMemId = -4
'@Procedure.EnumMember True
```

> [But] If we deprecate the old annotation format, I'd recommend that we still support it with an added DeprecatedAnnotationInspection that has a quickfix to reformat them.

Fully implemented, RD could:

- Add/Edit/Manage/Remove attributes, eventually with full intellisense support
- Identify real VB Attributes that have been inadvertently dropped through code edits
- Provide a visual cue that a module/procedure has attributes

Linking #52 #53 #54 #55 #786 #1656 #1965

**Comment by retailcoder** [comment]
About the mentioned inspections:

> *RD could have inspections like "Expected ClassX to be pre-declared, but attribute is missing or removed", or "Class X default member attribute is missing or removed", and the quickfix could apply or reinstate the attribute*

I think it would be the other way around:

> **Missing Annotation** Procedure 'DoSomething' has member attribute '`VB_Description`', but no corresponding `@Description` annotation. Consider making module and member attributes explicit with annotations.

> **Missing Annotation** Module 'Something' has module attribute '`VB_PredeclaredId`' set to non-default value, but no corresponding `@PredeclaredId` annotation. Consider making module and member attributes explicit with annotations.

We will be using the attributes pass of the parser to inject actual module & member attributes into the exported temp files, effectively translating the annotations into module/member attributes. If the actual attributes are different from what the annotations say, we update the attribute values accordingly.

---

Also:

> **Redundant Annotation** Module 'Something' has a `@PredeclaredId(False)` annotation; this being the default, it does not need to be specified.

I suggest making the Boolean flags default to the non-default value, e.g. a parameterless `@PredeclaredId` annotation translates to `VB_PredeclaredId = True`, while a `@PredeclaredId(False)` annotation translates to the default `VB_PredeclaredId = False`.

This inspection/synchronizing mechanism will therefore pop inspection results on all UserForm modules, which have a `VB_PredeclaredId = True` attribute - this will contribute to the feature's discoverability.

**Comment by retailcoder** [comment]
BTW this is my new favorite RD feature :+1:

**Comment by ThunderFrame** [comment]
I see your point about flipping the inspection, but IMO we need *both* perspectives, for 2 reasons.

- Procedure level attributes are susceptible to being deleted if you edit the signature or first line of a procedure
- Copying/Moving the codepane text of a module or procedure isn't enough to also copy the underlying attributes to the target

If the annotation survives the edit, then RD could reimplement the VB Attribute

**Comment by ThunderFrame** [comment]
Also, I'm unsure how we'll make this work in document-type modules.

**Comment by retailcoder** [comment]
Document-type modules are simply excluded; they can't have attributes, simple as that. Perhaps we could have an inspection to warn about such annotations in document modules.

> *If the annotation survives the edit, then RD could reimplement the VB Attribute*

My view is that the annotations dictate what attributes should be present; if there's an attribute without a corresponding annotation, then there's something implicit going on that an inspection needs to reveal; if there's an annotation without a corresponding attribute, then we need to inject the attribute - an inspection for this wouldn't even produce results, because by the time inspections run, the attributes have been sync'd with the annotations!

**Comment by ThunderFrame** [comment]
Well, I just *exported* this from my project...

```vb
VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Sheet1"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = True
Attribute VB_Description = "The Sheet with the Foo"
Option Explicit

Sub Foo(Bar As String)
Attribute Foo.VB_Description = "This does the Foo with the Bar"
  Beep
End Sub
```

**Comment by retailcoder** [comment]
@ThunderFrame if you can figure out a way to *import* it back in, you get a cookie :stuck_out_tongue_winking_eye:

**Comment by MDoerner** [comment]
With PRs #4641, #4642, #4669 and #4679 merged, I think this is covered now.
