### ISSUE TITLE
Source Control: Setting Github Username and Password crashes Access 2013

### ISSUE THREAD

**Issue by Xipooo** [rubberduck-vba/Rubberduck#2857]
Trying to set up source control.  Created a repo online.  Try to sync code to new repo.  I get the username and password prompt.  When I enter in my login and click Ok.  All of Access crashes.  It also causes a "File not found" error when I try to reopen the code window of the database.

**Comment by retailcoder** [comment]
Source Control initial setup is ...*picky* to say the least - we have a dedicated project to *git* it on track.

I was able to get it to work (through some trial & error) and documented the steps in the [wiki](https://github.com/rubberduck-vba/Rubberduck/wiki/Source-Control:-Getting-Started) - did you follow the steps described there?

**Comment by Xipooo** [comment]
Yes, I am following those steps exactly.  When prompted for my username and password, Access crashes.  Note, I am using Access 2013 x64.

**Comment by mansellan** [comment]
OK, can repro (in 2010). Investigating.
