### ISSUE TITLE
@Ignore Parameter is not referred to 

### ISSUE THREAD

**Issue by SystemsModelling** [rubberduck-vba/Rubberduck#2867]
Can we have an '@ignore for this one - ribbon control

Public Sub Mainproc(control As IRibbonControl)

Same for a Procedure not referred to which is intended to be called from an external user of the module.

**Comment by ThunderFrame** [comment]
I think we *should* have an ignore for this, but I'm currently working on #1186 - we should know all of the Ribbon callbacks very soon.

**Comment by retailcoder** [comment]
If you put all macros (public procedures in standard module, intended to be called externally) in the same module, and put `@IgnoreModule ProcedureNotUsed` at the top of that module, do the inspections still fire results for them?

**Comment by SystemsModelling** [comment]
That looks like a good solution. I'll try it later.

**Comment by retailcoder** [comment]
@ThunderFrame how about we simply assume any `Public Sub Whatever` with a `IRibbonControl` parameter is a Ribbon callback, at least for now?

**Comment by retailcoder** [comment]
I get no inspection result for this:

```vb
'@Ignore ProcedureNotUsed
Public Sub Mainproc(Control As IRibbonControl)

End Sub
```

Closing.
