### ISSUE TITLE
Going straight into Parsing without my clicking Pending

### ISSUE THREAD

**Issue by SystemsModelling** [rubberduck-vba/Rubberduck#2869]
I didn't get a Pending button, it straightaway started parsing. Then a Parse error and an Excel crash.
I restarted Excel and it now works normally.
I thought I'd report this in case it happens again.

**Comment by SystemsModelling** [comment]
Just to check:
Open a workbook with VBA. Press Alt+F11, RD splash appears. Button says "Pending". As expected
Open a second workbook with VBA. Alt+F11. RD says "Parsing" although I had not clicked Pending.
No crash this time, just an unwanted Parse. I still only want RD when I want to use it, it drags performance too much to have it parse without being asked.

**Comment by Vogel612** [comment]
Seems like we need another setting for this. "Parse automatically [ ]" or something along these lines. FWIW originally RD was intended to automatically start parsing when the vba project was opened the first time. This especially allows using all commands.

**Comment by retailcoder** [comment]
I'd go with:

- [x] Process opened projects at startup

Opt-in or opt-out?

**Comment by SystemsModelling** [comment]
Whatever the default is expected to be now - I had thought it was supposed to stay Pending so I'd have to Opt-In. I don't mind.

**Comment by Vogel612** [comment]
Considering the issues we had with parsing on start for so long and how we declined multiple feature requests surrounding this, I am somewhat surprised to see this open ...
