### ISSUE TITLE
False positive of "extraneous input" due to RaiseEvent

### ISSUE THREAD

**Issue by bclothier** [rubberduck-vba/Rubberduck#2870]
I have a complex procedure that is causing a parser error.

The offending line is simply this:

            mFrmQueue.RecordSource = strSQL

and it reports `extraneous input 'strSQL' expecting {')', WS, LINE_CONTINUATION}`.

Few things that raise red flags:

It reports the error being located at the line 313, on column 52. This is the correct line but the end of the line (after the `strSQL`) is at column 40. Hmm....

Commenting out this line _stills_ results in a parse error

Deleting the lines and pasting it back -> parse error
Typing the whole line by hand -> parse error
Commenting the entire body of the procedure -> no more parse error
Copy'n'paste the entire body of the procedure -> error parse again. (I used Immediate windows which normally would strip out any unprintable characters).

The procedure does not contain any hidden instructions like `VB_Attribute` or anything of that sort. 

While writing the bug report, I found a piece of clue -- if I comment the `RaiseEvent` line, no more parse error.... So it seems to be related to the raiseevent somehow.

    'Several lines of code...
    RaiseEvent FilterQueue(bolDoNotContinue, ByVal strSQL, colSpecials)

    If bolDoNotContinue = False Then
        If Len(strSQL) Then
            strSQL = "WHERE " & strSQL
        End If
        strOrigSQL = mFrmQueue.RecordSource
        strSQL = ReplaceWhereClause(strOrigSQL, strSQL)
        mFrmQueue.RecordSource = strSQL
        On Error Resume Next
        If Err.Number Then
            lngError = Err.Number
            strError = Err.Description & ", (" & Err.Source & ")"
            mFrmQueue.RecordSource = strOrigSQL
        End If
        On Error GoTo 0
        If lngError Then
            Err.Raise lngError, mconstrModuleName, "Cannot perform ApplyFilters due to error: " & vbNewLine & strError
        End If
    End If

I verified that even if I commented everything else leaving only the `RaiseEvent` in the code, I get an parse error. Comment out only the `RaiseEvent`, it parses OK. So it looks like RaiseEvent is causing this problem somehow and this cascades to subsequent lines.

In case it matters... the definition of event is...

    Public Event FilterQueue(ByRef Cancel As Boolean, ByVal SQLWhereClause As String, ByRef UnprocessedControls As VBA.Collection)

**Comment by comintern** [comment]
I can replicate this without any surrounding code.  As far as the location is concerned, are there any precompiler directives?

**Comment by bclothier** [comment]
The project does contain it but not in the class module where the bug arose.

**Comment by retailcoder** [comment]
Can you export the module and show us what you see on (313,52)? I suspect the parser error occurred while pre-processing / collecting module & member attributes. Parser tokens are otherwise exactly aligned with what's in the code panes.

**Comment by comintern** [comment]
@retailcoder - That's not it.  The grammar completely ignores `ByRef` and `ByVal` modifiers in `eventArgument`. I'd need to check, but I _think_ the `eventStmt` is technically wrong too - you can't have an `Optional` event parameter.  That one is probably fine though - the compiler would catch it but RD would just go ahead and parse it as optional.

**Comment by bclothier** [comment]
Confirmed. Removing the `ByVal` from my `RaiseEvent`'s argument list lets the parser parse correctly.

**Comment by comintern** [comment]
Just to clarify (and document a bit further), `ByVal` is supported here to explicitly pass the argument by value, but `ByRef` results in a compile error.

**Comment by bclothier** [comment]
Just so I understand the grammar - why would we include the `BYREF` in the .g4 file if it wouldn't compile in VBA?

**Comment by comintern** [comment]
@bclothier - There's a 2nd commit that followed that one that removed it again - I didn't find it until I was writing the unit tests.  It's a bit *ahem* underspecified in the MS documentation.
