### ISSUE TITLE
Code Explorer should automatically add a `@Folder` annotation when modules are added.

### ISSUE THREAD

**Issue by comintern** [rubberduck-vba/Rubberduck#2884]
I was watching @Xipooo's "Real World Demo of Using Interfaces" video and realized that we're missing a pretty big opportunity in the context menu.  We can tell pretty easily what folder in the Code Explorer is right-clicked to open the context menu:

![screenshot from 2017-03-16 23 03 02](https://cloud.githubusercontent.com/assets/8944005/24028424/d3e339de-0a9c-11e7-81ef-6bafebbdf442.png)

Why wouldn't we just add the  `@Folder("FolderThatWasRightClicked")` annotation to the new module? This would make organization a _lot_ easier as you're adding new code, and would be similar to how .NET and VS handle folders and namespaces.

**Comment by retailcoder** [comment]
Not only that - it should also add `@Folder("VBAProject")` in all modules without a `@Folder` annotation.

**Comment by daFreeMan** [comment]
Even better we could prompt for "What folder would you like that to be in?" if it a module without an `@folder` was clicked.
