### ISSUE TITLE
CodeExplorer Project Rename doesn't (always?) trigger a reparse

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#2889]
When I right click a project in the _CodeExplorer_ and select `Rename`, nothing happens.
![rd project rename 1](https://cloud.githubusercontent.com/assets/11889733/24042589/0c000e0e-0ae9-11e7-8990-4e343a4e7f61.PNG)
![rd project rename 2](https://cloud.githubusercontent.com/assets/11889733/24042591/0e7f2fca-0ae9-11e7-9251-15efe938d1d1.PNG)
even after forcing a reparse.

However, if I right click the project and select `Project Properties`, it will rename the project and trigger a reparse.
![rd project rename 3](https://cloud.githubusercontent.com/assets/11889733/24042626/300cc562-0ae9-11e7-85be-6e038e702d47.PNG)
![rd project rename 4](https://cloud.githubusercontent.com/assets/11889733/24042629/31c2d8c4-0ae9-11e7-82e4-04668f5cb2c0.PNG)

If this is expected behavior, the `Rename` option should be disabled when the project level node is selected.

**Comment by retailcoder** [comment]
This is because the command parameter uses the selected node. This needs to be fixed.

**Comment by retailcoder** [comment]
No repro, but after renaming the project parser state goes to `Pending`, which feels very weird. It should trigger a reparse automatically, instead of requiring a manual one.

**Comment by bclothier** [comment]
Cannot reproduce the original report -- the reparse does happen automatically, though we do fall into "doesn't see anything yet" which requires 2nd (manual) reparse to see the new project. If that's a problem, that should be its own issue.
