### ISSUE TITLE
Signature with single Implicit/Explicit ByRef Parameter triggers "Comment uses obsolete 'Rem' marker" inspection

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#2898]
Any procedure/function (including declare) or property signature such as:

```vb
Property Get Foo(Cancel As Boolean)
'...
Function Get Foo(Cancel As Boolean)
'...
.Sub Foo(Cancel As Boolean)

Private Declare Function QueryPerformanceFrequency Lib "kernel32" (lpFrequency As Currency) As Long
```

Has exactly 1 parameter, and triggers the "Comment uses obsolete 'Rem' marker" inspection.

It doesn't seem to matter if the `Declare` is a `Sub` of a `Function`, or if it is `PtrSafe`. The inspection still triggers if there are line continuations:

```vb
Private Declare Function QueryPerformanceFrequency Lib "kernel32" _
  (lpFrequency As Currency) _
  As Long
```

What *does* seem to matter is that there is exactly one parameter, and it is not marked as `ByVal`

**Comment by ThunderFrame** [comment]
A Const with a value of `""` is also inspected as an obsolete Rem Comment.

```vb
Const abcd As String = ""
```

**Comment by ThunderFrame** [comment]
As is this declaration:

```vb
Function fncSplitProjectString( _
              spIn As String _
              )
```

**Comment by ThunderFrame** [comment]
And also:

```vb
Option Base 0
```

**Comment by Hosch250** [comment]
This is a curious parser bug--this inspection runs off the parser results.
