### ISSUE TITLE
Variable declared with Global keyword is not also inspected a field breaking encapsulation

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#2899]
A declaration such as:

`Global Foo As Long`

Qualifies for 2 inspections, but only shows one:

- Use of Global Access modifier

Applying the quickfix, the declaration becomes:

`Public Foo As Long`

Which, upon reparse, triggers the second inspection:

- Public Field breaks encapsulation

If a user chooses to ignore the `Global` access modifier inspection, they're never made aware of the `Public Field` inspection result.

**Comment by retailcoder** [comment]
Seems every parse tree inspection is producing crap, because they're getting the parse tree results and not filtering properly.
