### ISSUE TITLE
Inspection for If blocks (without statements) having Else blocks (with statements)

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#2908]
I've come across code where the author seemingly didn't know that you can use a `Not` operator, and so wrote code like:

```vb
  If IsNumeric(slChr) Then
  Else
    slNewString = slChr & slNewString
  End If
```

RD should have an inspection that introduces the `Not` operator and removes the `Else`
```vb
  If Not IsNumeric(slChr) Then
    slNewString = slChr & slNewString
  End If
```

Of course, the condition might already *have* a Not operator, or use an inappropriate equality operator, and the author might have made some other inexplicable assumption about If statements. So this inspection will need to cover:

```vb
If x = 1 Then
Else
  Debug.Print x
End If
```

and

```vb
If Not x Is Nothing Then
Else
  Debug.Print x
End If
```

**Comment by Hosch250** [comment]
Reference #874
