### ISSUE TITLE
Inspection for redundant Else block

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#2909]
This Else statement doesn't add any value:

```vb
If foo Then
  DoSomething()
  Beep
Else
End If
```

RD should identify and remove the redundant `Else`

**Comment by Hosch250** [comment]
Reference #874

**Comment by SystemsModelling** [comment]
How about
Else
'don't know what to do yet
End If

**Comment by retailcoder** [comment]
@SystemsModelling I'd still like RD to *offer* to remove everything between `Else` and `End If` (including `Else` but excluding `End If`) in a case like this; in 3.x we'd use this information (the inspection result) to change the syntax highlighting and *dim* the coloring a notch, a bit like Visual Studio (/R#) does for redundant statements and code blocks.

**Comment by Vogel612** [comment]
fixed in #3120
