### ISSUE TITLE
Your program is running on the NET4.5 framework, but innosetup according to 4.0

### ISSUE THREAD

**Issue by 774115495** [rubberduck-vba/Rubberduck#2916]
`English.NETFramework40NotInstalled=Microsoft .NET Framework 4.0 installation was not detected.`

**Comment by retailcoder** [comment]
The wording is unfortunate. The requirement is the CLR (the .net runtime), not the .net framework. There is no "CLR 4.5", both .net 4 and .net 4.5 run off CLR version 4.0.30319.

**Comment by bclothier** [comment]
Just to record that I'm assuming this was sorta of already fixed as the Inno Setup code already has an explicit check for .NET 4.5 apart from 4.0, not just CLR version. However, the verbatim still said 4.0, so the PR #3836 updates the verbatim only.
