### ISSUE TITLE
No parsing, Pending/Refresh button doesn't trigger anything

### ISSUE THREAD

**Issue by ReuK212** [rubberduck-vba/Rubberduck#2919]
I've successfully installed that tool that seems to be pretty awesome, but **I can't manage to get it to parse anything**...
I've tried letting VBE opened for hours with a basic project (one sub with Debug.Print), and still pending...

It is **stuck on "Pending"** ("Pending. Click to refresh."), and **nothing happen when I click it**.

The only thing that I seem able to do (sometimes, then I can't again) is to add a modules or userform.

I've tried (in all apps) with existing projects, with a new one, and I can't seem to find a way to make parse the code! :'(

Here is the log, I've check all archived and they all are the same except for the date/hour :

> 2017-03-21 09:45:33.7541;INFO-2.0.13.32288;Rubberduck.App;Rubberduck version 2.0.13.32288 loading:
	Operating System: Microsoft Windows NT 6.1.7601 Service Pack 1 x64
	Host Product: Microsoft Office 2013 x86
	Host Version: 15.0.4885.1000
	Host Executable: EXCEL.EXE;

I've browsed the issues before posting, and I've seen that the click to refresh is logged too (cf https://github.com/rubberduck-vba/Rubberduck/issues/2717) .

So I think I don't even launch anything when I click on the refresh button.

I've uninstalled RubberDuck and reinstalled the latest version, same for .Net Framework, and I'm still stuck.

**Comment by Vogel612** [comment]
Hey @ReuK212 Can you try to check with the latest green release whether this still occurs? Thanks :)
