### ISSUE TITLE
Navigator window height can only be increased at bottom right corner

### ISSUE THREAD

**Issue by SystemsModelling** [rubberduck-vba/Rubberduck#2921]
Although the double headed (N-S) arrow cursor appears when I hover over the bottom frame, I can't increase the height of the Navigation window by dragging the bottom frame, only the bottom right hand corner where the cursor is NW-SE. The horizontal drag (W-E) works to widen it.

Feature request: Can I have it opened at the last size I set it to?

**Comment by retailcoder** [comment]
The way the VBE handles its toolwindows is... Let's just say if it were intuitive we wouldn't be having half the teardown issues we're having ;-)

I believe a single clean exit is all it takes for it to remember what was where; my work laptop install seems to leave everything where I left it. Not sure what we can do about these resizing quirks - at least not without a shot of the VBE  toolwindow layout.

**Comment by Vogel612** [comment]
will not be implemented in v2 RD, partially because VBE toolwindows are fickle enough without us trying to restore them as they were last use and this should be covered under basic v3 functionality
