### ISSUE TITLE
Parse error in Excel

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#2927]
RD 2.0.13 Excel2010 Win7

The title is a bit generic, but the situation is kinda complex: I have a macro enabled workbook template (.XLTM) that automatically saves itself with the proper naming convention in the proper location as a standard workbook (.XLSX). (Because my users can't figure out a simple naming convention, so I do it for them. :/ )

When I open the file to edit the VBA (`right-click|Open`), I can edit code & run through the macro. If I accidentally hit F5, the code runs to completion, saving the file without any VBA, and really, thoroughly confuses RD. 

It attempts to do a reparse on the XLSX, and, finding no VBA, it generates a Parse Error. It leaves the folder structure for the now closed XLTM showing in the CE, it shows the code for my `PERSONAL.XLSB` showing in the code pane, and `right-click|Project Properties` on the now closed project in the CE shows me the properties for the `PERSONAL.XLSB`.
![rd](https://cloud.githubusercontent.com/assets/11889733/24255273/6ac0efb8-0fbb-11e7-8d09-41a377aef320.PNG)
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/865222/RubberduckLog.txt)

I'm going to guess that the `File closed` code needs to look at the list of files remaining open, compared to the list of files shown in the CE and delete anything from the CE that's no longer open _then_ attempt to parse anything macro-enabled that remains.

**Comment by retailcoder** [comment]
Can you repro with the current build? This feels like a caching issue, possibly already resolved.

**Comment by comintern** [comment]
A bunch of this stuff has been completely re-written.  If this pops up again, open up a new issue.
