### ISSUE TITLE
Rubberduck crashes on rearranging ToolWindows in docked frame containing Properties Window

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#2936]
This bug has irked me for a while, but I could never reproduce it. It seems to rely upon a very specific toolwindow layout, but this screencap seems to be a MCVE.

Dragging Code Inspections *from* being between Code Explorer and Properties window, to being above Code Explorer, is enough to crash the host. I suspect the hooks are to blame.

![toolwindowplacement](https://cloud.githubusercontent.com/assets/16574009/24448457/feb869a4-14bf-11e7-9ce1-96947863a061.gif)

Ref #2878

**Comment by comintern** [comment]
AFAIK, there shouldn't be anything in the hooks that would cause a crash there.  Although...  we're subclassing all of the dockable windows.  Is it possible that the window is getting recycled?  It would be nice to see a mini-dump if you have one that you can post.

**Comment by helge123** [comment]
Same issue here

**Comment by Vogel612** [comment]
Could possibly be fixed by #3866

**Comment by bclothier** [comment]
FWIW I cannot reproduce this anymore so I think we can close this issue unless anyone have a different MCVE where crash still happens?

**Comment by bclothier** [comment]
Closing this issue since this still cannot be reproduced and nobody else has reported any problems since.
