### ISSUE TITLE
Source Control removes userforms

### ISSUE THREAD

**Issue by tomhumphrey** [rubberduck-vba/Rubberduck#2939]
As in title. When trying to do anything with Source Control there is an error thrown which just states something went wrong and after processing Userform is missing

**Comment by retailcoder** [comment]
IIRC this is a known issue (will dig up the # later).

The .frm file would be in the repository folder - can it be imported back manually?

**Comment by tomhumphrey** [comment]
No it can't - it won't let me add it back in

**Comment by tomhumphrey** [comment]
I exported it manually and just noticed there was two files in my repository one with exension 'frx' and one with 'frm' the 'frm' one imported ok

**Comment by retailcoder** [comment]
That's how UserForms work in VB6/VBA. The .frx contains layout information and binary data (e.g. any embedded pictures) - it's the .frm file that you import, and the VBE uses it to locate the corresponding .frx.

**Comment by retailcoder** [comment]
If you have logging enabled, the log file should contain useful information about the specific exception that happened.

**Comment by tomhumphrey** [comment]
This is all that's in the log

`Line 8: Property OleObjectBlob in SecurityForm had an invalid file reference.`

**Comment by retailcoder** [comment]
That's the VBE's "import" log, showing why the form didn't import; I think it means the .frm was referring to a .frx that didn't exist.

What I meant was Rubberduck's logs - you can set the minimum log level (e.g. `TRACE` or `ERROR`), or turn off logging altogether, from the *General Settings* tab of the RD settings dialog: the logs get written to `%appdata%\Rubberduck\logs`, and they're extremely verbose at `TRACE` level.

**Comment by retailcoder** [comment]
No problem, happy to help!

Seems you're one of the unlucky ones that experience the teardown issues... I've been having consistent clean exits on my home/dev desktop and work laptop for the last two releases or so, but there's indeed what appears to be a race condition in the teardown of docked toolwindows, involving something very deep that looks like a bug in WPF (the UI framework we're using that makes all these lovely UI's possible) and its interaction with WinForms and Win32 stuff.

**Comment by comintern** [comment]
Linking #2315
