### ISSUE TITLE
Install fail

### ISSUE THREAD

**Issue by SystemsModelling** [rubberduck-vba/Rubberduck#2944]
Excuse me if this is already recorded,  I'm using Android phone and don't see how to search issues for 'Install "
I ran 13 setup on a client site today and rd does not appear in addins. Files are in c:programdata .
May be permission problem. Rebooted,  no change.
What should I check? 
Mztools installed ok.

**Comment by retailcoder** [comment]
See [installing for non-admin users](https://github.com/rubberduck-vba/Rubberduck/wiki/Installing#installing-for-non-admin-users) in the wiki. Rubberduck requires admin privs to install, so its COM API (e.g. `AssertClass`) can be properly registered. Problem is that doing this creates the addin registry keys under HKCU but then that *current user* isn't the non-admin end user, so the addin keys need to be created after the fact for the VBE to realize there's an add-in to load.

MZ-Tools doesn't need to register a COM API... it doesn't have a unit testing framework either.

**Comment by SystemsModelling** [comment]
Thanks Mat
I have no admin access in that site. I asked their IT support to install 
it and that didn't work either. They tried adding the keys by hand 
rather than using Powershell.
Never mind, it would have been nice to have, but I've just read all 
their code by now and know what to say.
