### ISSUE TITLE
Harmonize TestModule templates

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#2956]
Currently, the late-bound and early-bound test module templates do very different things; the early-bound template declares an auto-assigned `IAssert` implementation:

    Private Assert As New Rubberduck.AssertClass

And the late-bound template declares an `Object` (duh!) and initializes it in `ModuleInitialize` and destroys it in `ModuleCleanup`:

    Private Assert As Object

    Public Sub ModuleInitialize()
        Set Assert = CreateObject("Rubberduck.AssertClass")
    End Sub

    Public Sub ModuleCleanup()
        Set Assert = Nothing
    End Sub

Given that test modules live in standard modules, the life span of the `Assert` field is unclear in the early-bound template, and could very well exceed the runtime context of the module; there's no reason not to properly initialize and clean up just like we do in the late-bound template.

Let's fix this.

**Comment by retailcoder** [comment]
Also take this opportunity to add a fakes provider instance to test modules:

    Private Fakes As IFakesProvider 'late-bound: As Object

**Comment by IvenBach** [comment]
Submitted my PR. Let me know if I set it up correctly.

**Comment by IvenBach** [comment]
I believe this has been completed.

**Comment by retailcoder** [comment]
@IvenBach if you put the magic words in a commit message, GitHub will close the issue automatically for you when the commit gets merged:

> *fixes #2956*

> *closes #2956*
