### ISSUE TITLE
Project Explorer (classic VBE) not showing installed addins after RD Loaded and Load on startup set to FALSE in 2.0.13

### ISSUE THREAD

**Issue by kolci** [rubberduck-vba/Rubberduck#2977]
Hi. I installed Rubber duck: RD 2.0.13 (hotfix).

After starting VBE to test it, RD started OK. I had it inspect my projects. I opened Project Explorer window (CTRL + R). I exited the VBE. Closed Excel. It crashed. Then I tried to open Excel and VBE, close them again and again, it crashed.
So I decided to Go to VBE > Addins > RD > and set Loaded = FALSE, Load on starup = FALSE.
Excel closed OK.
But now, I cannot see my installed addins in the VBE project window. See picture below. And I cannot Load RD back again. See issue: [Addin no longer availible in Add-ins Manager after Load on startup = FALSE 2.0.13](https://github.com/rubberduck-vba/Rubberduck/issues/2978)

![image](https://cloud.githubusercontent.com/assets/27676282/25085710/d34d1f00-2363-11e7-8f33-2804408484f4.png)

**Comment by ThunderFrame** [comment]
It seems likely that Excel may have crashed on exit (which is a known issue), but that it either didn't fully close, or it automatically restarted. It is sometimes necessary to *completely* kill Excel (the VBA host) by using Task Manager.. Details Tab.. Choose Excel, then End Task.

**Comment by kolci** [comment]
You are right. The Excel process was still running in the Task Manager. Killing it resolved the issue. Thank you.
