### ISSUE TITLE
Add Module/Code organizer (between 2 workbooks)

### ISSUE THREAD

**Issue by shairad** [rubberduck-vba/Rubberduck#2989]
Add a feature (Similar to **_MS-Project Organizer_**) which allows to view the VB Project contents of 2 Workbooks (one next to another). 

The screen (`User_Form`) allows you to see the entire project `Modules`, how many code lines you have per modules (allows you to understand if there are differences between the same module in the 2 workbooks, in case of a version upgrade).

Also, maybe a breakdown of each module: what `Sub`s are located in each Code Module, and also the last date it was modified.

![organizer](https://cloud.githubusercontent.com/assets/28016394/25399372/e3241f2e-29f7-11e7-9856-e4f819a269f2.png)

If needed, I can send over the Excel VBA code used.

**Comment by retailcoder** [comment]
I like the idea for importing modules between VBA projects (regardless of the host of either project), but some of it has a "poor man's source control" feel; I would like to see a beefed-up import tool, but IMO it would kinda suck if it was used as some kind of file-system substitute for proper source control, which we're trying very hard to achieve.

**Comment by shairad** [comment]
Of course it is (looks cheap) It was a "quick-and-dirty" job, I needed it a month ago, so I just came with something that will do the job in minimum effort. This is why I am shifting this to you guys. If you want I can send also the VBA code used.

**Comment by bclothier** [comment]
Closing this as out of scope
