### ISSUE TITLE
Code Inspection for Write-Only properties

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#2997]
Write-only properties are a sign that:

1 - The getter has been omitted inadvertently, and should be added, or;
2 - The write-only property would probably be better implemented as a method

Rubberduck knows when a property is write-only, so the inspection should allow quickfixes that either:

1 - Adds a getter, or;
2 - Converts the letter/setter to a method, along with a rename to a verbed name

**Comment by retailcoder** [comment]
http://rubberduckvba.com/Inspections/Details/WriteOnlyPropertyInspection
