### ISSUE TITLE
Adding lines to a module and reparsing confuses the status bar

### ISSUE THREAD

**Issue by MDoerner** [rubberduck-vba/Rubberduck#3002]
After adding new lines to a module and reparsing, the selections in the status bar are those for the same location before the reparse.

Before:
![screenshot_20170507_175447](https://cloud.githubusercontent.com/assets/22868956/25782631/f98d73ae-334e-11e7-931e-6c51df9a7953.png)

After:
![screenshot_20170507_175618](https://cloud.githubusercontent.com/assets/22868956/25782636/09f3bd0c-334f-11e7-90c0-88a54e429ec1.png)

**Comment by retailcoder** [comment]
That's basically Rubberduck telling the user it's out of sync. If we could, that's when we'd set that dirty module's state to `Pending` - or better, that's when we'd launch a parse task for that dirty module (and cancel it on the next keypress before launching another); *parsing on keypress* was one of the original goals for 2.0. Might not actually happen until code panes are subclassed in 3.0 though.

**Comment by MDoerner** [comment]
To clarify this, the problem is that the status bar problem stays after reparsing. The only way I could get rid of it is restarting Excel.
