### ISSUE TITLE
Can't load addin Exception in HRESULT:0x80029C4A (TYPE_E_CANTLOADLIBRARY)

### ISSUE THREAD

**Issue by joshuader6** [rubberduck-vba/Rubberduck#3007]
Hey it's me again. 

I decided to give rubberduck another shot on my dev machine. To be flexible with versioning i got the Git on the Master branch, Registerd the typelibary with resvr32 and Created the reg key for the addin manually. 
(All according to the wiki page) 

I'm using office 365 slow ring 32bit. 

Firts thing to notice was, that the reference  System.Windows.Interactivity was broken. 
So i simply installed it via nuget. 

Then when firing up the VBE i get this: 

Here is the Complete Log:
https://pastebin.com/sjTf2ZSf

`Das COM-Objekt des Typs "System.__ComObject" kann nicht in den Schnittstellentyp "Microsoft.Vbe.Interop.VBE" umgewandelt werden. Dieser Vorgang konnte nicht durchgeführt werden, da der QueryInterface-Aufruf an die COM-Komponente für die Schnittstelle mit der IID "{0002E166-0000-0000-C000-000000000046}" aufgrund des folgenden Fehlers nicht durchgeführt werden konnte: Fehler beim Laden der Typbibliothek/DLL. (Ausnahme von HRESULT: 0x80029C4A (TYPE_E_CANTLOADLIBRARY)).`

That one means translated from german something along:
> `The COM-Object of the type "System.__ComObject" cannot be converted to theinterface type "Microsoft.Vbe.Interop.VBE. This task couldn't be completed because the Queryinterface-Call to the COM-Component for the interface with the IID {}" couldn't be couldnt be executed. Error while loading the typelibary/DLL ( Exception in HRESULT:0x80029C4A (TYPE_E_CANTLOADLIBRARY)). 
`

**Comment by Vogel612** [comment]
First things first: the System.Windows.Interactivity reference was removed just recently.

Can I ask you to checkout the `next`-branch and rebuild? Also please check the bitness of VisualStudio, just to be sure. As I understand msdn, this error seems to be a problem in the typelib registration...

**Comment by joshuader6** [comment]
May i ask where to find the VS bittness? 
I can't seem to find it in the about window and in the installer. 

![image](https://cloud.githubusercontent.com/assets/10895412/25845386/fc1e522c-34ad-11e7-8f3d-af8a44d9b353.png)


My OS is Win 10.0.15063 Build 15063 64bit
Office is 365 Slow Insider 32bit

**Comment by joshuader6** [comment]
On the Next Branch it throws some ninject error: 

https://pastebin.com/1kx9VJhj

**Comment by retailcoder** [comment]
[Master] wouldn't include everything that was done since March. I haven't had a chance to build [next] myself since the last PR was merged (a few minutes ago), but an `ActivationException` for `IInspector` points to a missing binding for `Rubberduck.Parsing.Inspections.Abstract.IInspector` to its concrete `Rubberduck.Inspections.Inspector` implementation; a lot of work has been done lately, to extract inspections into their own assembly, but I don't think the wiki was updated yet for it.

Seems [this instruction](https://github.com/rubberduck-vba/Rubberduck/blob/cd0a83f10c7f20b55f3a70e84e7739518c75fc97/RetailCoder.VBE/Root/RubberduckModule.cs#L165) might not successfully be loading the `Rubberduck.Inspections.dll` assembly - make sure you:

 - Have a `\Plug-ins` folder under your `\bin` build folder.
 - Have a post-build event in the `Rubberduck.Inspections` project that copies the dll over to the `\bin` folder of the main project - that's where it's being loaded from.

**Comment by joshuader6** [comment]
Aaah i deleted the bin folder of Rubberduck.Inspections and let it build again. Then it started up just fine. But now the Original error of this issue is back.

**Comment by retailcoder** [comment]
@joshuader6 off the [next] branch? Does Office 365 ship with the VBE Extensibility library?

**Comment by joshuader6** [comment]
Yes in the next branch.

I dont know of any vbe extensibility libary

But i can reference a Microsoft Visual basic for applications Extensibility 5.3 libary in Excel VBA. 
And in the Rubberduck project it loads the reference: Microsoft.Vbe.interop just fine. 

Could this maybe happen because i had Office 2016 Professional installed on the machine previously but then i got 365 from my Scool and Switched to 365 and VS 2017 Enterprise.

**Comment by retailcoder** [comment]
Per Microsoft, Office versions *can* live side-by-side, but they *must* be installed in release order. Was Office 2016 uninstalled prior to installing 365?

Also, I'm on VS 2015, not sure if VS 2017 builds it. @Hosch250 did you end up getting RD to build in VS 2017?

**Comment by joshuader6** [comment]
Yep Office 2016 was uninstalled before installing 365. 

Well it builds just fine for me :D 

VS2017 is acutally far more tollerant with building things then 2015 in my experience. Some of my old Excel 2010 VSTO addins were loading and building just fine with 2017 while not working in 2015.

**Comment by joshuader6** [comment]
Okay i've tried something new: I noticed, that the Reference "Microsoft VBE Interop" was poninting inside the git Repository. So i removed it and added it back. But this time from the Office PIA Location. Still no luck. But i found out that i have the assembly in V15.00 and V14.00

**Comment by joshuader6** [comment]
Okay so now i have uninstalled office and vs. Then i manually cleared all office reg keys i could find. Then i reinstalled first office and then VS. 
Still the same error. 

Now i'm testing it in a VM. Clean install of Win 10 pro 64bit. Office 365 Insider Slow 32bit. and Vs 2017. 
Will post the results.

**Comment by joshuader6** [comment]
Okay so i believe the old install didn't deinstall very clean. In my test VM everything runs just fine. 
So i think my only option will be to Reinstall windows.. 

Damn office and it's fucking deep integration to the system. 

Does anyone have a better idea than reinstalling windows ?

**Comment by joshuader6** [comment]
Okay i reinstalled Windows and now everything works perfectly :) 
We'll never know why this happend.
