### ISSUE TITLE
Wiki - Source Control: Getting Started. XML file name?

### ISSUE THREAD

**Issue by emeraldjava** [rubberduck-vba/Rubberduck#3010]
The wiki page for the [Source Control: Getting Started](https://github.com/rubberduck-vba/Rubberduck/wiki/Source-Control:-Getting-Started) mentions a xml file where the repo name, local and remote details should be recorded. 

> Name the project after the repository. Rubberduck will create an entry for each repository, in a dedicated XML configuration file:

````xml
<Repository>
  <Name>TestRepo2</Name>
  <LocalLocation>C:\Dev\VBA\Rubberduck-Repos\TestRepo2</LocalLocation>
  <RemoteLocation>https://github.com/retailcoder/TestRepo2</RemoteLocation>
</Repository>
````

> It will be easier to resume working from that same project later, if you've named the project after the repository.

Is there a standard name or naming convention for this xml file. I'm happy to update the wiki once I get the correct answer.
Regards,
Paul

**Comment by retailcoder** [comment]
Thanks for the feedback! The file is named `SourceControl.rubberduck`, it's located in the install folder (default location is `%appdata%\Rubberduck`).

**Comment by Vogel612** [comment]
source control support in RD has been dead for half a decade at this point :/
