### ISSUE TITLE
Rubberduck Crashing Excel: Office 2016

### ISSUE THREAD

**Issue by ufo2mstar** [rubberduck-vba/Rubberduck#3020]
Hey @retailcoder, after your advice on #3006, I started using Rubberduck on my personal computer and things were going well. To explore some more of its features I just tried to Clone a git project from [my github](https://github.com/ufo2mstar/nab/tree/master/build) and also tried to create a Test project. But suddenly RDcrashed and every time I try to open my VB Editor (Alt+F11) I get the RD initialization screen and then the crash message...
![rd_crash](https://cloud.githubusercontent.com/assets/2426264/26135039/af61c436-3a80-11e7-9d9e-ce4cf44a2c1a.png)
Tried reinstalling, clearing out the registry and all that, but nothing seems to work to get RD running again... I tried to but did not find any previous bug that is discussing this issue, in case I missed it.

**Comment by retailcoder** [comment]
Source Control is quite flaky - the *known issues* section of the 2.0.13 release notes mentions this:

>  - **Source Control** *can* work, but its use isn't as user-friendly as it could be, and it tends to throw all kinds of exceptions for unintuitive reasons. We've made it [a project of its own](https://github.com/rubberduck-vba/Rubberduck/projects/8) to *git* it up and running smoothly.

Open `%appdata%\Rubberduck\SourceControl.rubberduck` in Notepad++ (it's an XML configuration file), there's probably junk in there; delete the file. Delete the `%appdata%\Rubberduck\Rubberduck.config` file too - RD will use its hard-coded default settings, and recreate the configuration file if settings are modified.

**Comment by ufo2mstar** [comment]
Oh, I see. That fix _almost_ worked @retailcoder, but all the options inside RD and the toolbars are disabled in the VBE IDE. And when I try changing the settings (even if I don't play with any VCS settings) more flakiness begins:

1. sometimes, Excel hangs and says that it's waiting for some OLE module to finish.
2. other times, there are closing issues with Excel itself
3. the editor randomly hangs and comes back online, etc

Additionally, if this method of **git**-ting will not work, is there any other way to version my modules and classes? (to get the files outside of the *.xlsm* file, instead of doing the 'change extension to _.zip_' trick)

**Comment by ufo2mstar** [comment]
and if there is any temporary way for me to completely reset RD and get it to work for the time being, please do let me know 😄 ...

**Comment by rubberduck203** [comment]
I’m sorry that this went unanswered for so long. 
We’ve removed the experimental source control feature per #3758. 

You can use the “Export All” feature to export your source files to the local file system and use whichever VCS you chose. This turned out to be the simplest way for us to support as many users as possible.
