### ISSUE TITLE
Option to have RD run the IDE toolbar 'Debug>Compile' on parsing

### ISSUE THREAD

**Issue by IvenBach** [rubberduck-vba/Rubberduck#3023]
I've seen the RD team comment many times 'doses that even compile?' along with many other variants. By default we could set an option that would test this for them. It would bring to their attention any code that's already causing problems pre-parse even.

**Comment by retailcoder** [comment]
We could do that, but there's not really a way to set up a conditional parse based on what the user learns from that action (RD gets no feedback from executing a commandbar button).

**Comment by IvenBach** [comment]
At the very least it would it could have them fix what's already broken before RD parses. Or if they choose to ignore it and have it parse, as RD is doing right now, they'd know something is already wrong.

**Comment by retailcoder** [comment]
Thing is, that feature would have to be disabled once we get continuous parsing (triggered by code changes) up and running... and with inspections now coordinated (and properly cancelled on request) by the parse coordinator, we're getting real close to continuous parsing being more than just a wet dream.

**Comment by IvenBach** [comment]
Duly noted.
