### ISSUE TITLE
Parse having trouble with line feed

### ISSUE THREAD

**Issue by Talorthain** [rubberduck-vba/Rubberduck#3024]
When my code parses, it flags up a line feed. When I remove the line feed, it moves on until it gets to the next line feed.
![capture](https://cloud.githubusercontent.com/assets/6796503/26283808/8f1564f4-3e26-11e7-8fcc-bbe68871b676.JPG)

The code is correct and runs correctly, so i am assuming this is a glitch. The code explorer doesn't raise any issues in the code

**Comment by Vogel612** [comment]
Looks like the same issue as #2888 to me

**Comment by Talorthain** [comment]
I did a search before submitting, but didn't see the other issue.

**Comment by MDoerner** [comment]
What I can see in the screenshot is exactly #2888, which has been fixed a few days ago.
