### ISSUE TITLE
Source Code API Dll for VBA.

### ISSUE THREAD

**Issue by adamchaz** [rubberduck-vba/Rubberduck#3026]
Hello I can't figure out how to add the RD source control dll for the VBA Editor. I'm trying to replicate source control api example.

**Comment by rubberduck203** [comment]
Hi. I apologize, but it's hard to tell exactly what you're experiencing problems with. Do you know how to add a reference, [as described in Microsoft's docs](https://msdn.microsoft.com/en-us/library/office/gg264402.aspx)? Are you having trouble finding the Rubberduck Source Control lib? Or are you receiving some kind of error?

**Comment by adamchaz** [comment]
I'm having trouble find the lib?

**Comment by adamchaz** [comment]
Hello I got it to work. Thanks
