### ISSUE TITLE
Some Parser Errors

### ISSUE THREAD

**Issue by joshuader6** [rubberduck-vba/Rubberduck#3028]
Hi guys. 

I found some strange Parser errors:

Im on Branch "next" Commit:  e13e9c6836e71218d79faee565d1d45406e5262f 

1. 

![image](https://cloud.githubusercontent.com/assets/10895412/26310636/d933ca72-3f01-11e7-85ee-c2910a07a1e7.png)

The first error seems to be happening at the end of this "With" block. 
Funny thing is that this is at L64C13 but the error reports L64C45
DBSheet is a worksheet variable

2. 

![image](https://cloud.githubusercontent.com/assets/10895412/26310522/519ad538-3f01-11e7-9f4a-cfbf02d78cb5.png)

The next one at the end of a normal function returning a string. 
Notice how it says L12C50 but the cursor is on L12C39 (Which is at the end of the "then" 
And the error message seems to be pointing to the content of L11

**Comment by Vogel612** [comment]
Re 2: I'm pretty sure that the parser dislikes the argument list with missing arguments.

does the error persist with `str = UsedRangeReset(ws, Nothing, Nothing, 10)`? 

Re 1: Unfortunately you don't show us where the Parser thinks the error is, which makes it hard to find out what exactly the problem is ...Could you provide a few lines of context around the line in question? Thanks

**Comment by joshuader6** [comment]
@Vogel612 The error is occuring at the end of the with block. (End with) Line at the bottom of the pic. 
As for err 2. Yes that seems to be the issue. 

It seems that these empty arguments are tripping the Parser somehow. 
On the first one there was a similar empty argument a few lines up. 

I have now replaced the empty args with the default values and now it seems to be working. 

But then there is this one: 
![image](https://cloud.githubusercontent.com/assets/10895412/26313109/1d0665d6-3f0a-11e7-94a8-16e3ae5b4c4c.png)

It occures at the end of the "next" line of the sub.

**Comment by ThunderFrame** [comment]
@joshuader6 In your third example, are you able to expose more of the lines above the currently visible procedure? When the "extraneous input" errors occur, it's usually because the underlying problem lies further up the module text.

**Comment by joshuader6** [comment]
Okay I have no idea what i changed but now the project parses perfectly fine. 
Funny enough i wasn't working on that module at all.
