### ISSUE TITLE
Parse Errors during late binding and early binding

### ISSUE THREAD

**Issue by ishita799** [rubberduck-vba/Rubberduck#3034]
**Installed Rubberduck 2.0.13 with Excel 2013 on machine with Non admin rights.**
Following code gives error both with early binding and late binding 

**Early Binding:** Adding RubberDuck.tlb in references results in Rubberduck parse Error(with empty results).
TestExplorer allows to run the test only once producing error “Library not registered”, then everything gets disabled and tests cannot be run

```
'@TestMethod
Public Sub test()
Dim rd As New Rubberduck.ParserState
rd.Initialize Application.VBE
  rd.Parse

  Dim decl As Variant
  For Each decl In rd.UserDeclarations()
    Debug.Print decl.Name
  Next decl
End Sub
```

[Log_Earlybinding.txt](https://github.com/rubberduck-vba/Rubberduck/files/1024909/Log_Earlybinding.txt)
---

**Late Binding :** On running the following test , error is produced “Variable uses an Automation type not supported in Visual basic” on line “  For Each decl In rd.UserDeclarations()”

```
'@TestMethod
Public Sub test()
Dim rd As Object
Set rd = CreateObject("Rubberduck.ParserState")

  rd.Initialize Application.VBE
  rd.Parse

  Dim decl As Variant
              For Each decl In rd.UserDeclarations()
    Debug.Print decl.Name
  Next decl
End Sub
```

[Log_lateBinding.txt](https://github.com/rubberduck-vba/Rubberduck/files/1024910/Log_lateBinding.txt)
---

**Comment by retailcoder** [comment]
The installer **requires** admin rights to correctly register COM APIs during installation. A non-admin end user can still use it though, but then because VBE add-in keys are created under HKCU additional steps must be taken to register Rubberduck as a VBE add-in for that user.

Can you confirm that the installer ran with admin rights?

**Comment by ishita799** [comment]
The installer ran with admin rights.
Then this script was used for further installation of rubberduck addin in excel as indicated in the installation process under "Running Rubberduck as a non-admin user"
link: https://github.com/rubberduck-vba/Rubberduck/releases

Set-ExecutionPolicy -ExecutionPolicy RemoteSigned
New-Item -Path 'HKCU:\Software\Microsoft\VBA\VBE\6.0\AddIns\Rubberduck.Extension' -Force
New-ItemProperty -Path 'HKCU:\Software\Microsoft\VBA\VBE\6.0\AddIns\Rubberduck.Extension' -Name Description -PropertyType String -Value 'Rubberduck'
New-ItemProperty -Path 'HKCU:\Software\Microsoft\VBA\VBE\6.0\AddIns\Rubberduck.Extension' -Name FriendlyName -PropertyType String -Value 'Rubberduck'
New-ItemProperty -Path 'HKCU:\Software\Microsoft\VBA\VBE\6.0\AddIns\Rubberduck.Extension' -Name LoadBehavior -PropertyType DWord -Value 3

New-Item -Path 'HKCU:\Software\Microsoft\VBA\VBE\6.0\AddIns64\Rubberduck.Extension' -Force
New-ItemProperty -Path 'HKCU:\Software\Microsoft\VBA\VBE\6.0\AddIns64\Rubberduck.Extension' -Name Description -PropertyType String -Value 'Rubberduck'
New-ItemProperty -Path 'HKCU:\Software\Microsoft\VBA\VBE\6.0\AddIns64\Rubberduck.Extension' -Name FriendlyName -PropertyType String -Value 'Rubberduck'
New-ItemProperty -Path 'HKCU:\Software\Microsoft\VBA\VBE\6.0\AddIns64\Rubberduck.Extension' -Name LoadBehavior -PropertyType DWord -Value 3

**Comment by retailcoder** [comment]
Might have something to do with using the COM API / running a parse from VBA code in a unit test setting... does it work with a test that doesn't create a `Rubberduck.ParserState` object? Looks more like an issue with the experimental API...

**Comment by ishita799** [comment]
![image](https://cloud.githubusercontent.com/assets/22786555/26436600/4d0d0d70-4135-11e7-8702-7bbf1283129b.png)

Infact in the attached image you may see that Rubberduck.ParserState object is created successfully (in Late Binding mode), but rd.UserDeclarations cannot be iterated using a For each loop, error "Variable uses an Automation type not supported in Visual basic” is produced. Please let me know:

I want to use ParserState Object api in my production code inside corporate environment. Is it stable enough or still in experimental state.  **At present if I am able to iterate rd.UserDeclarations in some way would suffice my need.** 
Thanks a lot for your reply.

**Comment by Vogel612** [comment]
@ishita799 FWIW the reflection-api has not even been mentioned in the release notes to date. As cleared in #2885 the COM API is currently [highly experimental](https://github.com/rubberduck-vba/Rubberduck/issues/2885#issuecomment-287435559)

> The COM API is advertised (if at all) as an experimental feature, subject to breaking changes.

**Comment by ishita799** [comment]
But #2043 shows that the same code is working with for each loop, then why is it not working in my case. Any clue?
Any plans to release this in future versions?

**Comment by retailcoder** [comment]
@ishita799 the ultimate goal is to offer a rich COM API that essentially allows writing reflection code in VBA... API work isn't a very complicated feature to work on, but priority is given to inspections/refactorings, source control, and the unit testing API. Contributions welcome!
