### ISSUE TITLE
Find implementations only works on members

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#3045]
2.0.13 (release build) correctly finds implementations of a given interface member, however fails to work at the type level, so using "find all implementations" on an interface class in the code explorer pops a message saying no references were found, but using the same "find all implementations" on one of that same interface's members brings up a search results toolwindow correctly identifying the implementing members.

*Find implementations* should be able to locate *classes* that implement a given interface.

**Comment by Vogel612** [comment]
That seems like something that could be useful for more than just that ... Things like automatic UML generation through a plugin and dependency analysis come to mind
