### ISSUE TITLE
Hot Key settings shouldn't allow <Shift> as the sole modifier or no modifiers.

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#3049]
If I set the Hot Keys to use <kbd>Shift</kbd>-<kbd>i</kbd> to bring up the Code Inspection window, I can no longer type a capital <kbd>I</kbd> in my code.

![rd hot key - bad](https://cloud.githubusercontent.com/assets/11889733/26802092/341d94de-4a0d-11e7-8983-699a99eb3deb.PNG)

The Settings pane should require _at least_ one of <kbd>Alt</kbd> _or_ <kbd>Ctrl</kbd> for every hot key setting to prevent people from screwing themselves up.

While setting the default Hot Keys to not require either <kbd>Alt</kbd> or <kbd>Ctrl</kbd> would be _most_ amusing, nobody would be around to enjoy the levity when the new user installs, starts typing, and all sorts of windows start popping up instead of characters appearing in his code pane.

**Comment by retailcoder** [comment]
Part of me is tempted to say "y'asked for it" to whomever configures their hotkeys in idiotic ways... The other part agrees though =)

**Comment by daFreeMan** [comment]
I don't disagree, @retailcoder, the hilarity would ensue would be priceless. Unfortunately, with nobody there to witness and enjoy it (the drawback to world-wide, anonymous distribution), there should probably be _some_ effort to prevent people from shooting themselves in the foot.

**Comment by IvenBach** [comment]
Closed by #3633
