### ISSUE TITLE
'Object variable not set' needs to smarten up

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#3052]
Consider:

```vb
Dim rs As ADODB.Recordset

'...code...
'...that doesn't use rs anywhere...

rs.Close ' error 91, object reference not set
Set rs = Nothing
```

`rs` *is* assigned with the `Set` keyword, so the inspection won't fire up a result.... but it definitely should.

Let's make the inspection ignore `Set` assignments where the RHS is `Nothing`.

**Comment by Vogel612** [comment]
the point isn't that RHS is `Nothing`, it's that rs is never assigned before usage. We should still ignore assignments with the RHS as `Nothing` for that inspection :+1:

**Comment by MDoerner** [comment]
@Vogel Not having been assigned before usage belongs to another inspection, "variable used but not assigned", (cf. issue #2458).
