### ISSUE TITLE
UnitTests: Code-Completion  does not work

### ISSUE THREAD

**Issue by FrankHentzschel** [rubberduck-vba/Rubberduck#3075]
I just created my first unittest and when I enter Assert. no code completion appears.

What may be the reason that it does not work?

Thanks in advance 

Frank

**Comment by retailcoder** [comment]
As is the case with any other library, code completion and IntelliSense only work when the library is referenced and the calls are early-bound (i.e. not made against the `Object` interface).

Late-bound:

    Dim foo As Object
    Set foo = CreateObject("ProgId")
    foo.DoSomething ' no code completion / IntelliSense

Early-bound:

    Dim foo As Library.Class
    Set foo = New Library.Class
    foo.DoSomething ' code completion / IntelliSense

Late-bound calls:

    Dim foo As Object
    Set foo = New Library.Class
    foo.DoSomething ' no code completion / IntelliSense

Whether Rubberduck test modules are set up for early or late binding by default, is configurable in the 'Unit Testing' tab of the settings dialog.

**Comment by retailcoder** [comment]
Note that code completion and IntelliSense are also unavailable for calls on extended interface calls, which are also late-bound/resolved at run-time:

    foo = Excel.Application.Average([A1:A42]) ' no IntelliSense
    bar = Excel.Application.WorksheetFunction.Average([A1:A10]) ' IntelliSense

**Comment by FrankHentzschel** [comment]
I used early binding in the options of RuberDuck/UnitTests.
But InteliSense also does not work.

**Comment by retailcoder** [comment]
I need to see your test module's declaration section. Note that settings apply to *new modules*, not existing ones.

**Comment by FrankHentzschel** [comment]
Okay, just a few minutes please ...

Von meinem iPhone gesendet

**Comment by FrankHentzschel** [comment]
ption Explicit
Option Private Module

'@TestModule
'@Folder("Tests")

Private arrTest As Variant

Private Assert As Object

'@ModuleInitialize
Public Sub ModuleInitialize()
    'Diese Methode wird einmal pro Modul ausgeführt.
    'Set Assert = CreateObject("Rubberduck.AssertClass")

End Sub

'@ModuleCleanup
Public Sub ModuleCleanup()
    'Diese Methode wird einmal pro Modul ausgeführt.
End Sub

'@TestInitialize
Public Sub TestInitialize()
    'Diese Methode wird vor jedem Test ausgeführt..
    Dim arr() As String
    Dim rr As Integer, cc As Integer
    
    ReDim arr(1 To 20, 1 To 10)
    
    For rr = LBound(arr, 1) To 10
        For cc = LBound(arr, 2) To UBound(arr, 2)
            arr(rr, cc) = "aaa"
        Next cc
        arr(rr, 2) = "key1"
    Next rr
    For rr = 11 To UBound(arr, 1)
        For cc = LBound(arr, 2) To UBound(arr, 2)
            arr(rr, cc) = "bbb"
        Next cc
        arr(rr, 2) = "key2"
    Next rr
    
    arrTest = arr
    
End Sub

'@TestCleanup
Public Sub TestCleanup()
    'Diese Methode wird nach jedem Test ausgeführt.
End Sub

'@TestMethod
Public Sub TestMethod_IsInArray_Col2Small()
    Const ExpectedError As Long = err__IsInArray__Column_Smaller_Than_Allowed
    Const key As String = "key1"
    Const KeyCol = 0
    Dim result As Boolean
    
    On Error GoTo TestFail
    
    'Arrange:
    TestInitialize

    'Act:
    result = IsInArray(arrTest, key, KeyCol)

Assert:
    Assert.Fail

TestExit:
    Exit Sub
TestFail:
    If Err.Number = ExpectedError Then
        Resume TestExit
    Else
        Debug.Print Err.Number, Err.Description
        Stop
        Resume TestExit
    End If
End Sub
