### ISSUE TITLE
Options grayed out

### ISSUE THREAD

**Issue by jsmitty01** [rubberduck-vba/Rubberduck#3081]
Not sure if this is just specific to my installation but all the menu options under the top level are grayed out.   
 For example, everything under Indent is grayed out.  I'm using Windows 10 Home, 64-bit with Office 2016 32-bit.  No errors with installing Rubberduck.

**Comment by Vogel612** [comment]
@jsmitty01 that's because Rubberduck can not really do many things without knowing about your code. To enable all these options, you need to trigger a parse-process in the Rubberduck Status bar.

**Comment by Vogel612** [comment]
See #2491

**Comment by jsmitty01** [comment]
Thank you!  I DID search for "grayed" but I should have also searched for "greyed"!

**Comment by tdalon** [comment]
with latest version installed RB ready I still have the Indent menus greyed out
