### ISSUE TITLE
Use meaningful names

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#31]
Detect when an identifier is named after its type and followed by a number, e.g. `Label1` or `TextBox1`, or when there are multiple identifiers with the same name, only with a different number suffix, like `foo1`, `foo2`, `foo3`.

More formally:
- [x] Identifier is less than 3 characters long
- [x] Identifier ends with a number
- [x] Identifier contains no vowel (suggest better name from lookup "dictionary" of disemvoweled words?)

**Comment by retailcoder** [comment]
Moving to 1.3, as this will be better implemented with #185 "Refactor/Rename" feature completed.

**Comment by Hosch250** [comment]
This is an incredibly easy issue.  Just take the Generic Project inspection and change the condition.  A tiny bit of Linq should handle it.  I will take it if no one else has it done shortly.
