### ISSUE TITLE
Presence of line number throws off Fix of Replace Left with Left$

### ISSUE THREAD

**Issue by SystemsModelling** [rubberduck-vba/Rubberduck#3100]
Works:
       If StrComp(Left(pf1.PivotItems(litem1).Caption, lheadlen), Left(pf1.PivotItems(litem2).Caption, lheadlen), vbTextCompare) = 0 Then

Result:
       If StrComp(Left$(pf1.PivotItems(litem1).Caption, lheadlen), Left$(pf1.PivotItems(litem2).Caption, lheadlen), vbTextCompare) = 0 Then

Fails:

    1234  If StrComp(Left(pf1.PivotItems(litem1).Caption, lheadlen), Left(pf1.PivotItems(litem2).Caption, lheadlen), vbTextCompare) = 0 Then
 

Result:
    1234  If StrCompLeft$t(pf1.PivotItems(litem1).Caption, lheadlen),Left$t(pf1.PivotItems(litem2).Caption, lheadlen), vbTextCompare) = 0 Then

**Comment by MDoerner** [comment]
I tested it on the current development build and the issue does not exist anymore.

Line numbers are now properly treated as labels. In 2.0.13, we still used a hack to ignore them.

**Comment by SystemsModelling** [comment]
Could this development build be made available?On 3 Jul 2017 8:29 PM, Max Dörner <notifications@github.com> wrote:I tested it on the current development build and the issue does not exist anymore.
Line numbers are now properly treated as labels. In 2.0.13, we still used a hack to ignore them.

**Comment by retailcoder** [comment]
@SystemsModelling that's the current [next] branch, if you fork the project you can keep up with everything that gets merged in the main repo... but you need to build it yourself, since we only build the installer script once we're ready to release.
