### ISSUE TITLE
Add ability to sort tests in Test Explorer

### ISSUE THREAD

**Issue by ghost** [rubberduck-vba/Rubberduck#3123]
In the Test Explorer window, the user should be able to click on a column header to sort the test results.

E.g., clicking on the "Method Name" column should sort results by Name, "Message" by message, "Duration" by duration, etc.

Not sure how the details would work; given the current grouping of the test results (by location or outcome) the sorting would have to occur separately  for each group.

**Comment by retailcoder** [comment]
If this is implemented, then let it be implemented in the `GroupingGrid.xaml` control - that way every WPF UI that uses that control will benefit from this.

Caveat: Test Explorer being a dockable toolwindow, its WPF days are counted. Docked toolwindows will be all redesigned from scratch using the more COM-friendly WinForms UI framework. Which sucks. But sucks less than a crashing add-in.
