### ISSUE TITLE
Refactor/Rename can't change case of an identifier?

### ISSUE THREAD

**Issue by CHR-IS-B** [rubberduck-vba/Rubberduck#3127]
Using the (oh so awesom) RD rename feature to change the case of a variable brings up this warning, which should probably only trigger if the proposed case insensitive variable name is different than the current case insensitive variable name.

For example, changing `myvar` to `myVar` triggers this warning:

> Renaming to 'myVar' clashes with 'Rubberduck.Parsing.Symbols.Declaration' in the same scope.

This confused me until I realized it was a false identification.

**Comment by retailcoder** [comment]
That's an annoying VBE quirk in the first place - VBA being case-insensitive, *renaming* to a different case makes no difference at all to the compiler - the *rename* dialog shouldn't have validated it as a different name... The rename dialog's OK button is meant to be disabled if you give it the same name.. that check seems to be case-sensitive, and shouldn't be.. and we let it slip up to a check that looks for an in-scope declaration, ...and matching a case-insensitive name compare it finds *itself*.

Thanks for reporting that bug - to allow/enable using refactor/rename to change the case, we need to tweak that search and filter out that declaration.

**Work-around**

To change the case of an identifier in the VBE, you just find its declaration and change the case there, and when you move the caret to another line and the VBE processes the modified line, everywhere the case was any different (including types and methods from referenced libraries) is now identical to that one single declaration you just re-processed.

Or, you just find an empty line, type `Dim myIdentifier` and hit ENTER and boom, every `MyIdentifier`, `myidentifier` and `MYIDENTIFIER` turns into `myIdentifier`.

You had it in you all along!  😉

**Comment by BZngr** [comment]
Looking into this, a couple things: 
1. The Rename dialog textbox validation is case-sensitive.  So, the OK button is disabled if `myIdentifier` is overwritten with `myIdentifier` (exact, case-sensitive match)...but `MyIdentifier` enables the OK button.  I think this is correct/desired behavior.
2. Clicking "OK" to proceed with a rename from `myIdentifier` to `MyIdentifier` results in a warning message that says 

> 
Renaming to 'MyIdentifier' clashes with 'myIdentifier' in the same scope.  Are you sure you want to proceed with this rename?

  

This is popup is annoying when simply changing case, but definitely required when the user attempts to rename to a case-insensitive match of some other declaration.  Even so, regardless of scenario, the user is allowed to continue even with a 'clashing' name.  (#Becarefulwhatyouaskfor).

So, I am thinking the only bug here is that there should be no warning issued (no popup messagebox) if the rename is a change of case.  That is, the clashing declaration and the rename-declaration are one-in-the-same.

**Comment by retailcoder** [comment]
@BZngr the intent was to have the OK button disabled if the new name was the same as the old name - that check should have been case-insensitive in the first place; using refactor/rename to address a quirk of the VBE / of a case-insensitive language, seems way overkill - as far as VBA/the VBE is concerned, the name remains the same, so no "rename" operation happens... I think I'd rather stick with the original intent and disable the OK button when the name is the same (regardless of casing).

**Comment by CHR-IS-B** [comment]
Thanks for the workaround @retailcoder.  I forgot about that one.
