### ISSUE TITLE
Code Explorer: Double-clicking method name does not always highlight entire method

### ISSUE THREAD

**Issue by christophocles** [rubberduck-vba/Rubberduck#313]
Steps to repeat:
1. Open large project with many VBA modules, each containing many subroutines and functions
2. Open Code Explorer and press refresh button
3. Double-click a method name in the Code Explorer treeview
4. Method should be entirely highlighted in code editor window.  This sometimes works as intended, but other times the highlighting extends only from the first line of the method to some seemingly-random location in the middle of the method.  The highlighting stops in the middle of a line of code.

For example, in the following method, the highlighting stops after the 'r' in the For statement:

Sub AB(CD)
. . . . . . .
For A = N + 1 To ActiveSheet.Columns.Count
. . . . . . .
End Sub

**Comment by retailcoder** [comment]
That is a possible issue with the parser, which is completely regenerated
in 1.3... let's try to get this issue fixed for 1.3 release.

**Comment by retailcoder** [comment]
Closing this issue, let's see if the 2.0 parser has the same issue.
