### ISSUE TITLE
Missing description for "Consider renaming Project" inspection

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#3133]
Picture tells a thousand words...

![projectname](https://user-images.githubusercontent.com/16574009/28252205-f1cea7d6-6ad1-11e7-8924-713cc03f57a5.png)

**Comment by retailcoder** [comment]
Deleting the settings file and re-initializing fixes the problem.

**Comment by bclothier** [comment]
Seems to be already fixed.
