### ISSUE TITLE
About box is missing attributions

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#3143]
New @rubberduck-vba/contributors need to be added, and Moq, and perhaps AppVeyor, need to be mentioned somewhere. And whatever else I'm forgetting.

**Comment by retailcoder** [comment]
- @rkapka 
- @IvenBach 
- @shadowofsilicon 
- @BZngr 

Please let us know under what name you want to be credited for your hard work!

**Comment by rkapka** [comment]
Radosław Kapka, please :-)

And thank you for the recognition!

**Comment by bbarney213** [comment]
Brandon Barney (but I maintain I havent done anything lol)

**Comment by Vogel612** [comment]
I'll just assume I can also get a credit?
Do note that this requires adjustments in all resx files, too...

**Comment by retailcoder** [comment]
@Vogel612 :omgwtf: your name wasn't in that box yet!? I'm so sorry!! That's long overdue!!

BTW the names are hard-coded into the XAML, so no resources are involved :0)

**Comment by Vogel612** [comment]
@retailcoder hmmm.. must've conflated it with [this resouce string](https://github.com/rubberduck-vba/Rubberduck/blob/6c0af89ed85c77ef4c7c6bf75bc46efde2ce9402/RetailCoder.VBE/UI/RubberduckUI.resx#L1236)
