### ISSUE TITLE
Illegal Annotation Inspection returning false positives

### ISSUE THREAD

**Issue by shadowofsilicon** [rubberduck-vba/Rubberduck#3144]
`IllegalAnnotationInspection` is returning false positives for annotations that should be legitimate.

For example, in an new, unedited Test Module, 6 results are returned when there should be zero.

![illegalannotationinspection](https://user-images.githubusercontent.com/28154402/28333353-560a01d2-6bbd-11e7-97c3-77c28e863124.png)

**Comment by Vogel612** [comment]
Could you try to remove the `Option Private Module`, please? If that doesn't help, could you please try the following code:

```
'@TestModule
'@Folder("Tests")
Option Explicit
Option Private Module
```
 Thanks

**Comment by retailcoder** [comment]
Part of that is caused by the `_annotationCounts` dictionary values being persisted between modules (listener's lifetime is that of the inspection, but dictionary doesn't mean to outlive a single module). Working on it.

**Comment by retailcoder** [comment]
Most of the false positives are gone - the only problem I'm having ATM is with detecting an illegal module annotation applied to the top-most member; this code produces no inspection result, but it should:

```
Option Explicit
Option Private Module

'@TestModule
Public Sub Test1()
End Sub

Public Sub Test2()
End Sub
```

**Comment by retailcoder** [comment]
ugh. not enough tests.
