### ISSUE TITLE
Resolver Error in build 2.1.1994

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#3151]
Access2010, Win7, RD.1986 & .1994

RD 2.1.1986 resolved the Parse Error I was getting (#3146) , but now I've hit a Resolver Error. It's consistent in .1986 and .1994. 

The mentions of resolver issues start on line 750 of the .1986 log (Search for "--- FreeMan issue starts here" that I inserted).

[RubberduckLog 2.1.1986.txt](https://github.com/rubberduck-vba/Rubberduck/files/1159041/RubberduckLog.2.1.1986.txt)

And the actual error appears to start on line 978 of the .1994 log (search for "--- FreeMan Error").

[RubberduckLog 2.1.1994.txt](https://github.com/rubberduck-vba/Rubberduck/files/1159047/RubberduckLog.2.1.1994.txt)

I note that there do seem to be quite a number of parse issues logged (SLL fails so it reverts to LL), and I don't know if that has anything to do with it.

**Comment by MDoerner** [comment]
The SLL errors mean that the faster more restrictive SLL parser was not able to process the code. In this case we fall back to the LL parser. They are guaranteed to yield the same result if both are able to finish. 
Accordingly, SLL parser errors are nothing to worry about.

**Comment by Vogel612** [comment]
searching for `;ERROR` is a better indicator :smile: It also has the benefit of being applicable to all logs

**Comment by MDoerner** [comment]
The Important piece seems to be this:
```
Rubberduck.Parsing.VBA.ReferenceResolveRunnerBase;
Exception thrown resolving 'Quarterly Report.Form_DataMove' (thread 30).;

Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 
The call is ambiguous between the following methods or properties:

'Rubberduck.Parsing.Binding.DefaultBindingContext.Visit
(
Rubberduck.Parsing.Symbols.Declaration, 
Rubberduck.Parsing.Symbols.Declaration, 
Rubberduck.Parsing.Grammar.VBAParser.LiteralExpressionContext, 
Rubberduck.Parsing.Binding.IBoundExpression, 
Rubberduck.Parsing.Binding.StatementResolutionContext
)' 

and

'Rubberduck.Parsing.Binding.DefaultBindingContext.Visit
(
Rubberduck.Parsing.Symbols.Declaration, 
Rubberduck.Parsing.Symbols.Declaration, 
Rubberduck.Parsing.Grammar.VBAParser.CallStmtContext, 
Rubberduck.Parsing.Binding.IBoundExpression, 
Rubberduck.Parsing.Binding.StatementResolutionContext
)'
```

Unfortunately, I have no idea how this can even happen. A `literalExpression` has absolutely nothing to do with a `callStmt`. Moreover, the code to relsove above is clearly a call statement.

**Comment by daFreeMan** [comment]
"Accordingly, SLL parser errors are nothing to worry about."

I thought that was the case, good to get confirmation.

**Comment by retailcoder** [comment]
Can you share the code for `Form_DataMove`?

**Comment by daFreeMan** [comment]
Your wish is my command.
[Form_DataMove.cls.txt](https://github.com/rubberduck-vba/Rubberduck/files/1160199/Form_DataMove.cls.txt)

**Comment by MDoerner** [comment]
Now, I understand the error. This is the dynamic version of a `NullReferenceException`. The exception just randomly picked those two possibilities of resolving `null` to a typed parameter.
