### ISSUE TITLE
Members of implicit default object property are not resolved

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#3153]
The default member of Workbooks is `[_Default]`, which is roughly equivalent to `Item`. Both `[_Default]` and `Item` both return a `Workbook` object, so RD should be able to resolve the `Workbook` members.

But, when the default member call is implicit, RD fails to resolve the `Workbook` properties

```vb
  Debug.Print Workbooks.[_Default](ThisWorkbook.Name).ReadOnly 'ReadOnly is recognized
  Debug.Print Workbooks.Item(ThisWorkbook.Name).ReadOnly       'ReadOnly is recognized
  Debug.Print Workbooks(ThisWorkbook.Name).ReadOnly            'ReadOnly NOT recognized
```

**Comment by ThunderFrame** [comment]
Well, this is odd, this implicitly default member seems to behave in the *opposite* way:

And it's not just s because I'm using a Let assignment, it also applies to the Gets...

```vb
  Dim sht As Worksheet
  Set sht = Sheet1
  sht.Cells.[_Default](1, 2).Value = 6 'Value NOT recognized
  sht.Cells(1, 2).Value = 6            'Value is recognized

  Debug.Print sht.Cells.[_Default](1, 2).Value 'Value NOT recognized
  Debug.Print sht.Cells(1, 2).Value            'Value is recognized
```

**Comment by retailcoder** [comment]
The type of `[_Default]` being `Object` (IIRC - could be `Variant` too), there's no way Rubberduck can know what `Value` is referring to. The VBE isn't providing IntelliSense, because it doesn't have any clue either. Indeed it would be nice to "nudge" RD into figuring that one out, but that would require hard-coding the knowledge and somehow making it override whatever RD sees un the actual type libraries.

**Comment by ThunderFrame** [comment]
Well, RD **does** identify `Value` as being `EXCEL.EXE|Excel.Range.Value (property get accessor:Variant)` when used in `Debug.Print sht.Cells(1, 2).Value` (with an implicit call to `Cells.[Default](1,2)`). Given `[_Default]` returns `Variant`, **it shouldn't be able to do that**, and it's inconsistent with being unable to identify `Value` in the equiavelent and explicit `sht.Cells.[_Default](1, 2).Value` call.

**Comment by retailcoder** [comment]
IIRC `Range.Cells` *is* parameterized, and returns an actual `Range`, I'm not sure there's an implicit `_Default` call in `sht.Cells(1, 2).Value`; RD being able to resolve it points to there *not* being such an implicit call, making `sht.Cells.[_Default](1, 2).Value` a rather convoluted way to do `sht.Cells(1, 2).Value`.

In any case, without knowing the returned type, how do you suggest we figure that one out? I'm thinking we'll have to hard-code a number of "working return type" `Declaration` references on a number of Excel object model members - a daunting task that doesn't do anything to address the same issue in other COM type libraries. IMO best we can do is warn about parameterless `Cells` invocations, which AFAICT are redundant.

**Comment by ThunderFrame** [comment]
The OB suggests that `Worksheet.Cells` *isn't* parameterized, and just returns a Range, and OLEView suggests the same:

```text
[id(0x000000ee), propget, helpcontext(0x000100ee)]
Range* Cells();
```
And here's the VBE providing a pretty strong hint that I'm calling `[_Default]`:

![default](https://user-images.githubusercontent.com/16574009/28482324-359584a8-6eab-11e7-9481-92e1782abb51.png)

That is, `Cells` can't accept parameters, it just returns *all* of the cells on the Worksheet, as a Range, which is why `sheet1.Cells.Count` is 16777216 in Excel XP, but an Overflow in Excel 2016.

So again, RD *shouldn't* be able to resolve `sht.Cells(1, 2).Value`, but *somehow it does*. There's nothing in the TLB to provide that detail.

Interestingly, the return type of `[_Default]` is *also* a `Range`!!!

```vb
?typename(cells.[_Default](1,2))
Range
```

Which means that you *should* be able to do this:

```vb
sht.Cells.[_Default](1,2).[_Default](1,1) 'Runtime error 438 - Object doesn't support this property or method
```

And yet, you **can** *somehow* do this:
```vb
sht.Cells.[_Default](1,2)(1,1)
```

Which means you can do this:
```vb
sht.Cells(1, 2)(1, 1)(1, 1)(1, 1)(1, 1)(1, 1) '....
```

So, I guess the question is, how does Excel return a value-type, from a call to `Range.[_Default]`, if `[_Default]` is just returning another `Range`)?

**Comment by MDoerner** [comment]
I think I know why RD is able to resolve `Cells(1,2).Value`. It is simply because both `Cells` and teh default member of `Range` return a `Range`, which has the `Value` property. In other words, the parameters play no role whatsoever in the process of resoving the expression. I guess the reasoning behind this is that VBA has no method overloading.

I am quite sure that RD would not resolve this if the default member returnes a different type and a property of that type was called.

**Comment by ThunderFrame** [comment]
@MDoerner  But that's just it, the default member of `Range` returns an implicit `Variant`.

```text
Property _Default([RowIndex], [ColumnIndex])
    Default member of Excel.Range
```

RD shouldn't, as it stands, be able to determine that `sht.Cells(1, 2)` is returning a `Range`, so it shouldn't be able to identify that the subsequent accessor `Value` is a call to a member of `Range`, but it does. And yet, it isn't able to resolve `Value` in `sht.Cells.[_Default](1, 2).Value`.

That's what I'm saying is strange.... These 2 statements **should** be *exactly* equivalent (and `Value` should be unresolvable in **both** cases), but RD is getting it resolving it "by accident"???

```vb
  Debug.Print sht.Cells.[_Default](1, 2).Value 'Value NOT recognized
  Debug.Print sht.Cells(1, 2).Value            'Value is recognized
```

**Comment by PeterMTaylor** [comment]
Could you retest this _Default to see any difference to eliminate assumption of variant between Value and Value2 usage

**Comment by ThunderFrame** [comment]
gah!!!:

`Debug.Print sht.Cells.[_Default] 'Runtime error 7 - Out of Memory`

<s>Turtles</s> Default properties all the way down....

**Comment by ThunderFrame** [comment]
http://www.xtremevbtalk.com/-net-office-automation/314210-cells-property-late-binding.html

**Comment by ThunderFrame** [comment]
Two great articles from Eric Lippert:

[SimpleScript Part Seven: Binder Skeleton](https://blogs.msdn.microsoft.com/ericlippert/2004/05/04/simplescript-part-seven-binder-skeleton/)

> Such is the wackiness of VB -- because the array dereference and function call syntax are conflated, they ended up making function calls on invisible methods be legal on the left hand side of an assignment statement.  **The mind fairly boggles**.

[VBScript Default Property Semantics](https://blogs.msdn.microsoft.com/ericlippert/2005/08/30/vbscript-default-property-semantics/)

> The rule for implementers of IDispatch::Invoke is if all of the following are true:
> 
>     the caller invokes a property
>     the caller passes an argument list
>     the property does not actually take an argument list
>     that property returns an object
>     that object has a default property
>     that default property takes an argument list
> 
> then invoke the default property with the argument list. Strange but true.
