### ISSUE TITLE
Test execution requires progress indicator and cancel option

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#3158]
Running a lot of tests can leave the UI hanging until all tests are complete.

RD needs a UI to show progress, and allow a user to abort a test run.

**Comment by rubberduck203** [comment]
I absolutely love that someone has so many tests for their VBA that this has become a problem/feature request.

**Comment by retailcoder** [comment]
Test runs are synchronous calls, otherwise unit testing couldn't work. Hence, we can't cancel a running test, because we're waiting for an `Application.Run` call to return at that time (i.e. we aren't in a state that lets us handle button clicks). There are several issues in this repo about cancellable tests - it can't happen.

The test explorer is *meant* to display progress though. If there isn't a progress bar, or if the progress bar doesn't indicate progress, then we have a problem/UI bug, because we *do* have code that handles that progress bar - it even changes color depending on test run state...

**Comment by MDoerner** [comment]
I think cancellation here does not mean cancelling within a test but rather cancelling the run between tests.

**Comment by rubberduck203** [comment]
I was thinking the same thing. Aborting a test run should abort after the currently running test finishes. In other words, the first available moment.

**Comment by retailcoder** [comment]
The problem is knowing that a cancellation was requested...

**Comment by Hosch250** [comment]
Is there any way to insert the button click into the queue to execute between Run calls?

**Comment by jliliamen** [comment]
@retailcoder : CancellationToken.IsCancelRequested?

**Comment by retailcoder** [comment]
@jliliamen there is no task. Tests must run synchronously, on the UI thread. Anything else and you get cancellable tests that you can't know if they passed or not.

**Comment by rubberduck203** [comment]
@retailcoder what makes you say they must run on the UI thread? You seem to be speaking from experience, but the rest of us are lacking the context.

**Comment by retailcoder** [comment]
@rubberduck203 Rubberduck isn't running any VBA code, the VBE is, through `Application.Run`; whatever you invoke with that will be running on the VBE's single thread, and everything is in the hands of the VBA runtime. The way RD knows whether a test failed or not is through a big fat hack that makes assert calls handled in a static class (C#) that simply cannot be accessed concurrently.

**Comment by rubberduck203** [comment]
I don't think anyone is suggesting *concurrency*.  What we're suggesting is *asynchronicity*. A bit of pseudo code. 


    async RunTests(CancellationToken token)
    {
        foreach (test in discoveredTests)
        {
            if(token.cancelled)
                break;
            await var result = runner.run(test);
            notify(result);
        }
    }

Does that clarify what I'm thinking? We still run one test at a time, but release back to the UI thread to give the user an opportunity to cancel running a suite.

**Comment by jliliamen** [comment]
What's being suggested is that tests are to be not cancelled during execution but rather in between test checks are made for cancellation requests. @rubberduck203 : However what would happen if there is one test to run. That'll defeat your point.

**Comment by rubberduck203** [comment]
@jliliamen to retailcoder's point, we **can't** cancel a test that is already running. What we can do is check for cancellation *before* each test. This would provide a (very) small window of time to cancel that single test. 

Hmm... I smell a confusing feature that would require an FAQ...

**Comment by retailcoder** [comment]
Well, we gotta work with what we have, and make the best out of it - a running test can't be aborted, we have to live with that constraint; cancelling a run *between two tests* is the best we could do, and even that would require significant overhaul of the whole test engine. @rubberduck203 that could work, but it's not a small change ;-)

**Comment by jliliamen** [comment]
I perfectly understand that that a running test cannot be cancelled, btw.

**Comment by rubberduck203** [comment]
I've not doubt there would be significant rework @retailcoder.

**Comment by ThunderFrame** [comment]
Well, pressing `Esc` or `Ctrl` + `Break` during the test execution allows the user to "Continue", "End" or "Debug" *that* test. So you *can* cancel a running test.. you just can't prevent the remaining tests from starting.

Interestingly, an ended test results in this Message for the execution:

`Test raised an error. Exception from HRESULT: 0x800A9C68`

Maybe RD could catch that error, and prompt the user for confirmation as to whether to continue running the remaining tests?
