### ISSUE TITLE
We need a developer/tester with Office 2013

### ISSUE THREAD

**Issue by ckuhn203** [rubberduck-vba/Rubberduck#316]
A number of bugs have recently been reported that seem to only affect Office 2013. We could really use a hand detecting and fixing bugs in that environment.

**Comment by danwagnerco** [comment]
Hey buddies -- I don't know ANYTHING about C#, but I would be happy to test builds for y'all. I have access to Office 2013 on Windows 7 (at work) and Windows 8.1 (at home).

**Comment by christophocles** [comment]
I am a C# novice but I have many years of VBA experience.  I can also test 32-bit Office 2013

**Comment by retailcoder** [comment]
:+1:  @christophocles feel free to fork the repository! We're using Microsoft Visual Studio Community 2013 (a free download). You'll need to enable/download InstallShield Express, and VS should prompt you to download the Nuget packages we're using; you already have the `Addins/Rubberduck.Extension` key registered so it *should* just work :)

If you have a Stack Exchange account (with at least 20 reputation points), @ckuhn203 and I (Mat's Mug) can be found in the [VBA](http://chat.stackexchange.com/rooms/14929) Code Review Stack Exchange chatroom, where the Duga chat bot is keeping us aware of everything that's going on in this repository. If you don't have a SE account, .........make one on [Code Review](http://codereview.stackexchange.com/), review some VBA code (or post some of your VBA code up for review) and we'll make sure you get the 20 points!

**Comment by ckuhn203** [comment]
We also have the ability to grant rights to chat, but I would encourage you to check out Code Review anyway. Also, 20 points on any SE site (excluding SO) will get you into the room.

**Comment by retailcoder** [comment]
@christophocles I could also use some help with the ANTLR grammar file (see the `GrammarIsFun` branch), which generates our parser - all of Rubberduck's code analysis and refactoring capabilities are only as good as the grammar we're using -- and that grammar has issues as you noticed ;)

The grammar definition language is pretty straightforward, but overcoming the current limitations and fixing the bugs is a tedious task that requires pretty deep knowledge of the VBA language and its syntax.

**Comment by christophocles** [comment]
Sounds like fun. I will dig into it. I have some very crusty, nasty code (not written by me) to test it against. If we can get it to interpret THAT, it can handle anything...

**Comment by ckuhn203** [comment]
@christophocles as someone new to the code base, do you feel it would help if we created an [Easy-Fix] label and tagged the issues we feel would be easy for someone new to handle?

**Comment by Hosch250** [comment]
Just to stick my thumb in, I also have Office 2013 - 64-bit.

**Comment by Ryankey** [comment]
I just found RubberDuck a few days ago but it has helped tremendously with Excel VBA work and I would love to give back where I can. I also have Office 2013 - 64-bit.

I'm fairly new to fully fleshed programming projects, but I'm glad to help with testing and small tasks like refactorings.

@ckuhn203 [Easy-Fix] type labels would definitely help, or just knowledge of what labels would be best to start with.

Thanks again for a great add-in.

**Comment by retailcoder** [comment]
@Ryankey thanks for the awesome feedback! I've created the [easy-fix] label, but I'm not sure where to apply it. I'm pretty biased when it comes to identifying what's "easy", especially with code inspections, refactorings and grammar/parsing -related issues :wink: 

I've applied it to #371 *Obsolete Error statement inspection*, I'll comment on that issue to give further details. I really need to document how code inspections are implemented...

**Comment by ckuhn203** [comment]
I also added a couple of issues to the [Easy-Fix](https://github.com/retailcoder/Rubberduck/labels/easy-fix) label @Ryankey. They don't involve code inspections. They might be a better introduction to the code base.

**Comment by retailcoder** [comment]
Right. [code-inspections](https://github.com/retailcoder/Rubberduck/labels/code-inspections) aren't exactly "easy", but some are easier than others - I've put the "easy-fix" label on the easier ones.

**Comment by ckuhn203** [comment]
Big shout out to @Hosch250 for helping us out with this and sooooo much more.
