### ISSUE TITLE
Form & class built-in events causing "Procedure is not referred to" warnings.

### ISSUE THREAD

**Issue by A9G-Data-Droid** [rubberduck-vba/Rubberduck#3164]
In Rubberduck v2.1.2003 (internal version 2.0.14.33947)

This issue appears to be a resurgence of an old issue:
"Code Inspection: False Positive for UserForm events in MS Word #1851"

All my userforms have these warnings in the code inspector because they all have default members "Initialize" and "Activate". I'm also seeing the same warnings for built-in forms coming from (FM20.DLL) MSForms.FormEvents. We shouldn't be seeing errors for MS DLL files because we have no control over those.

    Warning: Procedure 'UserForm_Initialize' is not used - , line 10
    Warning: Procedure 'UserForm_Initialize' is not used - , line 10
    Warning: Procedure 'UserForm_Activate' is not used - , line 15
    Warning: Procedure 'UserForm_Initialize' is not used - , line 10
    Warning: Procedure 'UserForm_Initialize' is not used -
    Warning: Event 'Deactivate' is not used - (FM20.DLL) MSForms.FormEvents, line 1
    Warning: Event 'Initialize' is not used - (FM20.DLL) MSForms.FormEvents, line 1
    Warning: Event 'Resize' is not used - (FM20.DLL) MSForms.FormEvents, line 1
    Warning: Event 'Activate' is not used - (FM20.DLL) MSForms.FormEvents, line 1
    Warning: Event 'Terminate' is not used - (FM20.DLL) MSForms.FormEvents, line 1
    Warning: Event 'QueryClose' is not used - (FM20.DLL) MSForms.FormEvents, line 1

**Comment by retailcoder** [comment]
Hmm.. I think recent tweaks to the parser will make it easier to write unit tests to cover these.

**Comment by daFreeMan** [comment]
I see @Vogel612 tagged this "regression". Was this fixed at one time? I know I had issues with it claiming `_OnClick` event handlers were never called. Or is this different?

**Comment by A9G-Data-Droid** [comment]
It was fixed in https://github.com/rubberduck-vba/Rubberduck/issues/1851

Just like I said in my OP.

**Comment by daFreeMan** [comment]
Reading comprehension fail.

**Comment by MDoerner** [comment]
It is not the recent tweaks to the parser. When we switched from `isBuiltIn` to `isUserDefined`, the default was left to be `true`. Apprently, it has been overlooked to adjust the `FormsEventDeclarationLoader`.

**Comment by retailcoder** [comment]
AppVeyor build 2.1.2008
