### ISSUE TITLE
Installed latest pre-release, version still showing as 2.0.14.33947

### ISSUE THREAD

**Issue by polaroidkidd** [rubberduck-vba/Rubberduck#3165]
[Downloaded](https://github.com/rubberduck-vba/Rubberduck/releases/download/Rubberduck-v2.1.2003/Rubberduck.Setup.exe) but it's showing as Version 2.0.14.33947 when I go to Rubberduck -> About.

How can I verify which version I have installed?

**Comment by retailcoder** [comment]
The AppVeyor "pre-release" builds on [next] are always going to mismatch the actual assembly build version. AppVeyor is a cloud-based continuous integration / build server, the build# is sequential and incremented every build. Assembly version is controlled by `AssemblyInfo.cs` and the build number is determined by `csc.exe`, the compiler.

So we'll update `AssemblyInfo.cs` to v2.1, but as long as we don't make a manual build off [master], the build numbers won't match. The about box is showing the correct assembly version, 2.0.14 has been a working version number for the eventual 2.1 release.

**Comment by polaroidkidd** [comment]
Ah ok. Thank-you for the explanation! Btw, you're making my VBA-Excel life a lot more bearable!
