### ISSUE TITLE
'Implicitly Variant' Inspection quick fix does nothing

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#3167]
Access2010 Win7 RD2.1.2003

![rd implicit variant inspection](https://user-images.githubusercontent.com/11889733/28675782-dfd572d4-72b6-11e7-860a-0c862eb5cdcc.PNG)

Clicking the `Fix all occurrences in procedure` link does nothing.

TBH, I'm not sure what the intent is on _how_ to fix this. Is it supposed to infer from the RHS what the type should be? Is it supposed to pop up a dialog asking for a type (by presenting a drop-down or radio buttons)? If it asks for a type, would it list _every_ type possible based on included libraries?

If there's no intent to fix, remove all the `Fix...` links, as they're confusing.

**Comment by MDoerner** [comment]
IIRC, the intended fix is to make it an explicit Variant.

**Comment by retailcoder** [comment]
The 'Fix' button in the toolstrip docked at the top of the toolwindow is a dropdown that lists all available quickfixes for the selected inspection result; using it fixes *this occurrence*, and its description says "declare as explicit variant". There is already an open issue to make it try to infer the type from usage.

**Comment by daFreeMan** [comment]
@MDoerner - ugh!

**Comment by daFreeMan** [comment]
This may just come down to a general UX issue that the 'Fix' button is not intuitively obvious as a drop down - it looks like when I click it a fix will happen.

**Comment by retailcoder** [comment]
ref. #196

**Comment by retailcoder** [comment]
@daFreeMan would changing the caption from 'Fix' to 'Available QuickFixes' solve the UX issue?

**Comment by retailcoder** [comment]
Are we getting a repro with the latest build? Linked issue #3224 was fixed by 11a25f6

**Comment by daFreeMan** [comment]
@retailcoder - I just tested this with CI build .2213. As originally written:
> Clicking the `Fix all occurrences in procedure` link does nothing.

Has been resolved, so I'll close this one.

I'll open a new issue (or track down the existing one) for the UX issue. I think I just realized what the problem is there...
