### ISSUE TITLE
'Disable this inspection' Quick Fix doesn't do anything on HN inspection

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#3168]
Access2010, Win7, RD2.1.2003

![rd disable hn inspection](https://user-images.githubusercontent.com/11889733/28676562-f93d0618-72b8-11e7-970f-0b0f2b77385d.PNG)

Clicking the `Disable this inspection` link does _not_ insert the @IgnoreInspection meta-comment

**Comment by retailcoder** [comment]
That's by design. Disabling an inspection sets that inspection's severity level to `DoNotShow`, so no annotation is added to the code.
