### ISSUE TITLE
Display issue in Code Inspection Settings

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#3170]
RD 2.1.2003

There are a couple of blank inspection types that show up in the Code Inspection Settings dialog in the `Code Quality Issues` section:

![rd inspection settings](https://user-images.githubusercontent.com/11889733/28687785-9b9f7cd2-72dd-11e7-8fd2-7dcc7269c6eb.PNG)

**Comment by MDoerner** [comment]
probably related to #3133

**Comment by retailcoder** [comment]
Fixed with a setting reset (renaming settings file).
