### ISSUE TITLE
License text in the installer has too many vbCrLf

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#3173]
RD2.1.2008

Picking nits:
![rd license text](https://user-images.githubusercontent.com/11889733/28691904-81784f3c-72ec-11e7-958f-e7054b66fafd.PNG)

Get rid of all the CRLF in there and let the text just wrap.

**Comment by retailcoder** [comment]
Does it count as a modification?

>  Everyone is permitted to copy and distribute verbatim copies of this license document, but changing it is not allowed.

**Comment by Vogel612** [comment]
@retailcoder I suppose not, since the paragraph structure will remain as is, right?

**Comment by bclothier** [comment]
This was fixed in PR #3819
