### ISSUE TITLE
Symantec detects a risk with V2.1.2010

### ISSUE THREAD

**Issue by fastzombies** [rubberduck-vba/Rubberduck#3179]
Tried to install a pre-release to see if an issue was resolved and got this from Symantec:

<pre>
“””A RISK HAS BEEN DETECTED””” 
Please go to the site below for directions on how to address the alert.
Security risk detected: WS.Reputation.1
Action taken: Leave Alone succeeded
</pre>

I cannot override the corporate settings to force an install.  I don't know what was introduced since 2.0.14 that would throw this but I won't be able to upgrade and see if [#3126](https://github.com/rubberduck-vba/Rubberduck/issues/3126) is resolved.

**Comment by retailcoder** [comment]
Symantec wants us to request every single build to be white-listed.... I have better things to do with my life than being a beggar to a corporation that despises open-source software.

We don't write viruses, and we don't package crapware into our installers. Not much more to do about this.

**Comment by rubberduck203** [comment]
What Retailcoder is trying to say is that we cannot possibly petition Symantec to whitelist every build when we produce a pre-release version on every commit...

**Comment by fastzombies** [comment]
What a pain, I didn't know it was that much extra freakin work.  If I could bypass it I would but I'm on corporate lockdown in regards to the Symantec stuff and I don't fee like getting fired just for trying to.

**Comment by retailcoder** [comment]
@rubberduck203 the part that ticks me off is that they're not even bothering to actually scan for threats, they just flag you as a "risk" the minute your executable is too young to have been downloaded thousands of times, and seen by Symantec as many times. They are actively hurting OSS and they know it, and they couldn't care less.

**Comment by rubberduck203** [comment]
It burns me too @retailcoder. It's sheer laziness on their part. 

> I've not seen this before. It ***must be*** evil!

If they were better at what they do, they'd actually scan it for attacks....

Anyway @fastzombies I apologize that you're unable to take advantage of the pre-releases. There should be enough downloads of one of the older releases for you to install. *I hope.*

**Comment by fastzombies** [comment]
No good deed goes unpunished.  I'll just have to be patient.  At least I have workarounds for 2.0.14 in the meantime.
