### ISSUE TITLE
Code inspection Fix dropdown needs redesign

### ISSUE THREAD

**Issue by puzzlepiece87** [rubberduck-vba/Rubberduck#3182]
I have one stronger suggestion and another more optional one.

Stronger: The Fix dropdown needs some indicator, like a dropdown arrow, to indicate that it *is* a dropdown. Right now visually, it looks like a button that you push once to make the fix without being sure what the fix is going to be.

More optional: maybe include a number in the dropdown that indicates how many options are present? If there's only one fix available, you could either do "(1)" for one fix (plus the ignore once), or you could do "(2)" to explicitly count the ignore once option. I understand from @retailcoder that there's sometimes more than one possible fix, so that could be "(2)" (or "(3)") for two fixes, etc.

**Comment by retailcoder** [comment]
I like both, and since this is WPF/XAML, nothing is impossible - let's do both! "Ignore once" is technically a quickfix, so it would have to be counted as one.

**Comment by daFreeMan** [comment]
I agree with the initial premise that the `Fix` button doesn't really feel right, and I think I've figured out (at least some of) why:
![rd ux issue](https://user-images.githubusercontent.com/11889733/30433143-aae01880-9931-11e7-8ea0-97fc6fc8aabb.PNG)
The red circles show, on the top row, a _disabled_ button on a default VBE tool bar, and an _enabled_ button on the RD tool bar. They look very similar - the `Copy to Clipboard` and `Settings` buttons need color in them when they're enabled. They're not the total grey of the default VBE disabled buttons, but close enough to be confusing. I wasn't sure why they would be disabled at this point, but I had to click them to actually discover that they are _not_ disabled.

The blue circles show, on the top row, an _enabled_ button on a default VBE tool bar, and **2** _totally different_ formats for enabled buttons on the RD tool bar! The `Refresh` button is perfect - colored icon on the (incredibly ugly) themed light-blue background. However, the `Fix` and `Grouping` buttons both have the default form-builder beige background. The `Fix` button has a nice brightly colored green check mark, but the `Grouping` icon is as greyed out as the disabled icons above it.

I think that fixing the fore & background colors would go a long way toward making the CI tool bar more user friendly, though I **totally agree** that adding a drop-down icon to the `Fix` button would help tremendously, as well.

**Comment by retailcoder** [comment]
@daFreeMan are you running the latest build? There were XAML toolbar styling fixes merged rather recently.

**Comment by daFreeMan** [comment]
CI build .2213

**Comment by retailcoder** [comment]
Ok. FWIW the VBE and RD toolbars look similar because they're both `CommandBar` objects, with `CommandBarButton` controls. Toolbars in the docked toolwindows are WPF and have nothing to do with the `CommandBar` API.

**Comment by daFreeMan** [comment]
These are UX issues, so the underlying technology of `CommandBar` vs `WPF button bar` don't matter to me as a user. 😉 

To me, the `Copy` and `Settings`  icons just don't have _enough_ color in them - they're bland enough that they _look_ disabled even though they're not. The `Refresh` icon has enough bright enough blue in it that it _looks_ like it's enabled.

FWIW - The CE buttons exhibit the same inconsistency in look 'n feel.
![rd ux ce](https://user-images.githubusercontent.com/11889733/30435794-a6e15940-9938-11e7-9e09-63efe2bcaa84.PNG)

- `Refresh` appears to be identical (as it should) to the Inspection window
- `Add` has a bright green icon (obviously active), but a Camry-beige background
- `Sort` has a monochrome icon (is that active or not?) and Camry-beige background
- `Toggle Signatures` has a monochrome icon, an outline (?) and a Camry-beige background
- I'm not sure what the next button is for, but it's disabled, yet still has some blue in the "window header" of the icon
- `Copy` appears identical to the one in the Inspection window

I <s>like</s> love the tool enough to continue using it whether the UI is spruced up or not. I do know that I (and others) get confused by the inconsistencies. I think that they may be strongly off-putting to new users who _don't_ know how much effort has gone into the project and how much you guys care. They may get confused and uninstall it. i.e. I won't be offended if you don't fix it to my exact specifications, I'm just trying to point out what hit me as "wrong" this morning. It is "UX", so I don't think there's any explicit right or wrong, so maybe the better word is "different" or just "inconsistent".

**Comment by daFreeMan** [comment]
To be very fair, M$ aren't particularly consistent in their ribbon design, either. From Outlook 2010:

![outlook menu](https://user-images.githubusercontent.com/11889733/30436730-e82b6042-993a-11e7-8176-25431d82e647.PNG)

Some are icons with text, some are icons without text. But, "additional options" does always seem to be accompanied by the little dropdown icon.

**Comment by retailcoder** [comment]
[Add] and [Sort] are, again, dropdowns, depicting the same consistent look of WPF dropdowns in the inspection results toolwindow; [Toggle Signatures] is outlined because it's toggled-ON, and its PNG image doesn't have a monochrome mask like the other icons, that's why it has that gray background unlike the other buttons - that will *definitely* be fixed. [Copy] and [Settings] icons are what they are; not going to come up with new rainbow-colored icons for that. The [Show Form] button looks obviously disabled, and the [Copy] icon looks obviously enabled to me.

Of course it's UX, and trust me I agree with most of what you're saying - especially the fact that the underlying tech should have little to no impact on the UI. To me the problem seems to be as simple as the WPF toolstrip having that annoying backcolor that doesn't blend with the rest of the form, and the WPF dropdowns having that annoying different backcolor. And then yeah, dropdowns need a dropdown arrow - thank Microsoft and its lovely consistency for now including one in the stock control :wink:
