### ISSUE TITLE
Parser need to be able to handle negative line numbers, and then inspect for them

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#3185]
Entering the text-line `&HFFFFFFFF Beep` results in a pretty-printed line of:

```
-1         Beep
```

That line is valid but can't be edited, as the negative number label is considered invalid.

Likewise, it is possible to enter `GoTo &HFFFFFFFF` which results in a pretty-printed `GoTo -1`

It would seem that, anywhere a line-number can be used, a negative number can be "forced" by using a hex value with the sign bit on.

RD should be able to parse such hacks, but should also inspect for them.

**Comment by retailcoder** [comment]
To be fair I doubt this would ever show up in actual code. `Priority--;`
