### ISSUE TITLE
Inspections includes FM20.DLL results

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#3189]
There's not much you can do about declarations in a TLB....

These inspections appear upon adding an empty form to a project, or having a project that references `FM20.DLL`...

![fm20](https://user-images.githubusercontent.com/16574009/28750108-599c0d86-7522-11e7-9c89-3a4510b168aa.png)

```vb
Hint: Parameter 'Cancel' is declared as Integer - (FM20.DLL) MSForms.FormEvents, line 0
Hint: Parameter 'CloseMode' is declared as Integer - (FM20.DLL) MSForms.FormEvents, line 0
Suggestion: Parameter 'Cancel' can be passed by value - (FM20.DLL) MSForms.FormEvents, line 0
Suggestion: Parameter 'CloseMode' can be passed by value - (FM20.DLL) MSForms.FormEvents, line 0
Warning: Parameter 'Cancel' is implicitly Variant - (FM20.DLL) MSForms.FormEvents, line 0
Warning: Parameter 'CloseMode' is implicitly Variant - (FM20.DLL) MSForms.FormEvents, line 0
```

**Comment by retailcoder** [comment]
#3171 should have fixed #3164... Is this off the current build?

**Comment by MDoerner** [comment]
My bad. I did not change the `ParamterDeclaration`s. I thought they were using the constructor for built-in parameters. However, they are using the general constructor and explicitly pass true as user defined, which has been built-in before.

**Comment by MDoerner** [comment]
Wrong button
