### ISSUE TITLE
SmartIndenter gets indentation incorrect when line number is followed by a colon

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#3192]
```vb
Sub foo()
5   Dim x
10: Dim x
End Sub
```

Indents to:

```vb
Sub foo()
5   Dim x
10:     Dim x
End Sub
```

I suspect that's because it is indenting the line number by 4 spaces: 
```vb
    10: Dim x
```
And the VBE's pretty printer then shifts the leading 4 spaces to after the colon.

**Comment by Vogel612** [comment]
Considered fixed as of #3434
