### ISSUE TITLE
Handle runtime errors

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#32]
Detect `On Error Resume Next` instructions, and recommend adding an error-handling subroutine instead.

```
    On Error Resume Next
    foo(42) = "bar"
```

Can be written as:

```
    On Error GoTo ErrHandler
    foo(42) = "bar"

    Exit Sub
ErrHandler:
    If Err.Number = 9 Then 'Subscript out of range
        Err.Clear
        Resume Next
    End If
```

---

Rubberduck may not be able to detect exactly which runtime error to handle. Perhaps the quickfix snippet can look like this:

```
    On Error GoTo {ErrorHandlerLabel}

    {code}

    Exit {Sub|Function|Property}
{ErrorHandlerLabel}:
    If Err.Number > 0 Then 'todo: handle specific error
        Err.Clear
        Resume Next
    End If
```

**Comment by retailcoder** [comment]
Let's make a first iteration of this inspection as a mere little "Runtime errors suppressed" warning that triggers when `On Error Resume Next` is used without being followed by an `On Error GoTo 0` statement.

**Comment by retailcoder** [comment]
Moving to 2.1 - we can't just keep adding parse tree listeners, parsing performance is taking a beating.

**Comment by rkapka** [comment]
Is adding parse tree listeners still not advised? I can't see how it would be possible to implement this inspection without one.

**Comment by Vogel612** [comment]
@rkapka that was back when each ParseTreeListener ran in a separate ParseTreeWalk. It's not remotely that problematic to register ParseTreeListeners now, since we can dispatch all walking events to a collection of listeners. As @retailcoder mentioned above: this inspection **requires** a simple parse-tree listener
