### ISSUE TITLE
Code inspection detects typed functions ChrB$() and Space$() as undeclared variables

### ISSUE THREAD

**Issue by Stevefb** [rubberduck-vba/Rubberduck#3219]
**Environment:**
Rubberduck ver: 2.1.0.9682 
Office 2010, 64 Bit ver (in MS Word)
Win10 Creators Update

**Issue:**
Code inspection detects typed functions ChrB$() and Space$() as undeclared variables

**Comment by Stevefb** [comment]
Can confirm that similar functions are treated appropriately, e.g.:
mid$()
left$()
right$()
chr$()
trim$()
lcase$()
ucase$()
environ$()
string$()
format$()
chrw$()

**Comment by Vogel612** [comment]
These "similar functions" are special cased in the Resolver. We manually add a declaration for these to the Reference Cache so Rubberduck can know about them. This should be fixable by adding the relevant functions to the [AliasDeclarationsLoader](https://github.com/rubberduck-vba/Rubberduck/blob/next/Rubberduck.Parsing/Symbols/DeclarationLoaders/AliasDeclarations.cs)
