### ISSUE TITLE
Code Explorer does not update

### ISSUE THREAD

**Issue by ghost** [rubberduck-vba/Rubberduck#3220]
The Code Explorer window does not appear to be refreshing properly.

I have a nearly-empty Excel file that I have been using for testing while working on RD.

This file:
- Contains the default `Sheet1` and `ThisWorkbook` classes
- Contains an added Userform:
- Userform: renamed `UserForm21`
- Userform: no other modifications
- Contains an added Module:
- Module: contains the following code:

```
Option Explicit

Sub foo()

    Debug.Print "Hello World"
    Dim asdf As Long

End Sub
```

When I open this file in Excel then launch RD, a project tree does not appear in the Code Explorer.
If I create an additional new project (i.e. create a new spreadsheet) the new project does not appear in the window.

If I launch Excel, create a new spreadsheet, then launch RD, a project along with the expected Sheet1 and ThisWorkbook modules appears.  However, if I add a new UserForm, standard Module, or Class Module to the project, they do not appear in the Code Explorer.

For the purposes of this bug, "does not appear" means "does not appear after the Refresh button is clicked and the parse completes successfully."

The file I am using for those that are curious: [RD testing.zip](https://github.com/rubberduck-vba/Rubberduck/files/1202803/RD.testing.zip)

**Comment by comintern** [comment]
If this isn't closed by #4661, it should be re-opened as a new issue.
