### ISSUE TITLE
Constant is not used inspection ignores usages of constant as parameter default value

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#3223]
The constant `BUILD_ON_WEEKDAYS_ONLY` *is* used by the default value for the `BuildOnWeekDays` argument

```vb
Const BUILD_ON_WEEKDAYS_ONLY = True

Sub PrintProjectCost(Optional BuildOnWeekDays As Boolean = BUILD_ON_WEEKDAYS_ONLY)
 '...
End Sub
```

**Comment by retailcoder** [comment]
Hmm, makes me wonder if we're resolving default parameter values. I presume enums to the same?
