### ISSUE TITLE
False error on properties: "Error: Object variable is assigned without the 'Set' keyword"

### ISSUE THREAD

**Issue by A9G-Data-Droid** [rubberduck-vba/Rubberduck#3234]
Using per-release version Rubberduck v2.1.2033 internal version 2.1.0.10753

I'm getting "Error: Object variable is assigned without the 'Set' keyword" on all of my properties. 

Example:
```
Public Property Let example(ByVal firstArg as String)
    localExample = firstArg
End Property

Public Sub doThing
    example = "This line will throw the error because I am not using set here"
End Sub
```

I checked the definition of a property on MSDN and they are, for sure, object members that are set like a regular variable. No "set" keyword is required to define the value of a property.

**Comment by retailcoder** [comment]
You beat me to it! Yup, aside from the broken annotation inspections, this is the only false positive I'm seeing in the latest build. Should be a pretty easy fix (looks like a little oversight).
