### ISSUE TITLE
We need a "Contributing.md" file

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#3239]
The wiki is a good starting point, but an actual `Contributing.md` file would be ideal:

https://opensource.guide/starting-a-project/#writing-your-contributing-guidelines

**Comment by Vogel612** [comment]
I'll drop a first draft of a CONTRIBUTING.md into the war room after this weekend. If anybody wants a quicker first draft, they're welcome to join, 

I'll follow along [this "tutorial"](https://mozillascience.github.io/working-open-workshop/contributing/) linked from retailcoder's reference

**Comment by Vogel612** [comment]
removing my assignment. Do we consider this fixed after the merge of #3285 ?

**Comment by retailcoder** [comment]
Yup. And thanks!
