### ISSUE TITLE
AutoSave

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#324]
Too many times I've lost hours of work in the VBE, just because I'm an idiot that can't press Ctrl+S. Let's have an option to automatically save the project whenever we're parsing it.

**Comment by Hosch250** [comment]
I'm not real sure we should do this because we will be reparsing every time a key is pressed.  We could perhaps do a save-every-ten-minutes using a timer instead.

**Comment by retailcoder** [comment]
I like the timer idea. Make it configurable in the RD settings dialog, that's one small but cool feature that can safely creep into 2.0 - go for it!
