### ISSUE TITLE
Add a Code Inspection for Select Case conditions without code

### ISSUE THREAD

**Issue by Stevefb** [rubberduck-vba/Rubberduck#3246]
There is a code inspection for If Then Else (and probably ElseIf) that warns user if a condition is met but there is no code to execute.  

Should have same for:
Select Case

(and potentially loops).

**Comment by Vogel612** [comment]
That should possibly be separate things respectively. Since VBA doesn't have default-fallthrough this should be pretty straightforward for SELECT CASE.

Accordingly this is:

 - [ ] Empty Case block
 - [ ] Empty For loop block
 - [ ] Empty Foreach loop block
 - [ ] Empty While loop block
