### ISSUE TITLE
Code Inspection some comment text resolves as variable

### ISSUE THREAD

**Issue by Stevefb** [rubberduck-vba/Rubberduck#3248]
Open a new MS Word document, put this code into ThisDocument:
```
' PURPOSE:
' RD False Positive
Private Sub SomeTest()
    '@[RD] NotA Variable
    Debug.Print vbNullString
End Sub
```

See image below:
![capture](https://user-images.githubusercontent.com/9349975/29210358-8d758a84-7ed6-11e7-939e-b275db5e34b3.PNG)

Word 2010, 64 Bit App
Win 10, 64 Bit
RD ver: v2.1.2047

**Comment by retailcoder** [comment]
Weird, could be a grammar issue... although, an unrecognized annotation should be parsed as a normal comment.

**Comment by bclothier** [comment]
This no longer reproduces, so closing.
