### ISSUE TITLE
IllegalAnnotationInspection false positives

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#3249]
ref. #3144, PR #3244, #3245.

The [`IllegalAnnotationsInspectionTests.GivenTestModule_NoResult`](https://github.com/rubberduck-vba/Rubberduck/blob/next/RubberduckTests/Inspections/IllegalAnnotationsInspectionTests.cs#L54-L103) test passes, and uses *exactly* the same code that gets parsed when a fresh new test module is added.

Yet the inspection *still* produces false positives for some reason:

![image](https://user-images.githubusercontent.com/5751684/29214925-f93375b6-7e76-11e7-9f11-9b2932136814.png)

**Comment by Vogel612** [comment]
As mentioned in Chat already: 

The difference between a unit-test and the VBE is module attributes. I think before tests regarding this can be useful we need to teach the MockVbe and MockParser about Attributes. That means we need to get these tests red **again**

**Comment by retailcoder** [comment]
Worth pointing out, the inspection results are navigating based on *attributes pass* token positions, which is also a bug that needs fixing.

**Comment by retailcoder** [comment]
@Vogel612 the inspection is a parse tree inspection working off the code pane pass (why navigation is offset is a mystery); the listener is associating annotation comments to its `CurrentScopeDeclaration`...I'm not sure how the attributes pass would interfere with that one. Different story for the `MissingAttributeInspection` and `MissingAnnotationInspection` though.

**Comment by retailcoder** [comment]
Okay, rebuilt, no repro.
