### ISSUE TITLE
Code inspection for Auto Instancing

### ISSUE THREAD

**Issue by Stevefb** [rubberduck-vba/Rubberduck#3253]
After reading here: http://www.cpearson.com/excel/Classes.aspx

I think a code inspection to detect Auto Instancing would be a good addition to RD...

```Dim x As New y``` apparently has these disadvantages:

- adds overhead to the code - the variable must be tested for Nothing every time it is encountered in code
- there's no way to test whether a auto-instancing variable is Nothing because using the variable name automatically create an instance of the variable

So better to use:
```
Dim x As y
If xIsNeeded Then
    Set x = New y
End If
```

**Comment by retailcoder** [comment]
That's.. already implemented ;-)

**Comment by Stevefb** [comment]
Hmm, does not seem to be working for my small test project :(

**Comment by retailcoder** [comment]
?

![image](https://user-images.githubusercontent.com/5751684/29245243-321b985a-7fa2-11e7-80d2-d6a5bd14bcfe.png)

**Comment by Stevefb** [comment]
Ok it picked it up now, but I swear it didn't the first time

**Comment by Stevefb** [comment]
Sorry, obvs my bad, possible that I changed the code to elicit the inspection but failed to refresh :(

**Comment by retailcoder** [comment]
It doesn't pick up module variables, but that's by design. I'm seeing two issues with the inspection:

 - "self-assigned" could be changed to "auto-instantiated"
 - "ignore once" quick-fix should be enabled

Also.. perhaps a quick-fix could be implemented to turn:

    Dim foo As New Bar

Into:

    Dim foo As Bar
    Set foo = New Bar

But only if there's no assignment to `Nothing` within the scope.

**Comment by Stevefb** [comment]
Agree with the quick fixes, that would be good.

*Scratches Head* - when I first tested I double clicked on each inspection result and am positive that the inspection did not show up.  It's there now and I can't repro... 

Tnx
