### ISSUE TITLE
"Move closer to usage" Quick Fix breaks assignment of Word.Range using .duplicate

### ISSUE THREAD

**Issue by Stevefb** [rubberduck-vba/Rubberduck#3257]
**Issue aRange2 should be a .Duplicate of aRange1**

Steps to reproduce (MS Word 2010, RD v2.1.2057) in an otherwise blank document add a standard module with:
```
Option Explicit

Private aRange1 As Word.Range
Private aRange2 As Word.Range

Private Sub duckOuttaLuck()

    Set aRange1 = ActiveDocument.Paragraphs(1).Range
    Set aRange2 = aRange1.Duplicate

End Sub
```

Run code inspection, click on `Move module-level variable to smaller scope`:

```
Option Explicit

Private Sub duckOuttaLuck()

    Dim aRange1 As Word.Range
    Set aRange1 = ActiveDocument.Paragraphs(1).Range
    Dim aRange2 As Word.Range
    Set aRange2 = aRange1

End Sub
```

**Comment by ThunderFrame** [comment]
Can't repro on 2.0.13 - although I was applying the fixes individually.

**Comment by Stevefb** [comment]
I think I have tried every possible combination of Quick Fix and always get the same result.  For (in)sanity I just restarted MS Word and still get the same result.  BTW - I'm using 64 Bit Word if that makes any difference?

**Comment by retailcoder** [comment]
@ThunderFrame 2.0.13 was before we introduced the rewriters... looks like that refactoring should have a couple of red tests ATM...

**Comment by comintern** [comment]
I can't repro this on the current build.
