### ISSUE TITLE
Need "Find all References" in Form Designer context menu

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#3260]
Currently the only RD command in the form designer is "Rename". It would be nice to have "Find all References" as well, so in-code references to a given form control can be easily located straight from the designer view.

**Comment by mansellan** [comment]
Hi,

Can I take this one up? I've read through the wiki, forked the code and figured out how to add the menu, now I just gotta make it, uh, work... 

I'm new to open source, this would (hopefully!) be my very first PR.

**Comment by retailcoder** [comment]
@mansellan absolutely! join the dev team in [chat](https://chat.stackexchange.com/rooms/14929/vba-rubberducking) on Stack Exchange!

<sub>(OMG someone read the wiki!)</sub>

**Comment by mansellan** [comment]
Thanks, been lurking there for a while, but can't talk as I don't have a 20 rep...

**Comment by retailcoder** [comment]
Not a problem, I can grant you explicit write access - I just need your user ID :smile:

**Comment by mansellan** [comment]
Sorry, router puked. User 370885.
