### ISSUE TITLE
Refresh command in RD menu

### ISSUE THREAD

**Issue by IvenBach** [rubberduck-vba/Rubberduck#3261]
https://chat.stackexchange.com/transcript/message/39433898#39433898
>@ThunderFrame: Why don't we just put a Refresh command in the RD menu? That makes the refresh requirement more obvious to a new user, and allows a user to hide the RD toolbar, but still be able to refresh.

**Comment by mansellan** [comment]
Should it be the top item?

**Comment by retailcoder** [comment]
Yup
