### ISSUE TITLE
Help me find the "Stop" debug statements sprinkled in my VBA code

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#3266]
"Find all references" is excellent for declarations, but finding usages of a specific keyword isn't something Rubberduck does [yet?]. There's one particular keyword I can think of, that should only ever exist in a debugging session: `Stop`. That instruction brings up the VBE, with the keyword highlighted: that's quite the shitty UX...

So let's make an inspection that finds and warns about the presence of `Stop` statements.

**Comment by ThunderFrame** [comment]
You're using `Stop` in a live code path. *Stop it right now*...

**Comment by retailcoder** [comment]
@ThunderFrame a first version could still be useful if it only pointed them out regardless of code paths =)

**Comment by ThunderFrame** [comment]
You're using Stop in a Workbook_Open event... but then you already knew that, because that's what opened the damned VBE.
