### ISSUE TITLE
Improve SC Repo Management menu

### ISSUE THREAD

**Issue by ghost** [rubberduck-vba/Rubberduck#3278]
The repo management menu in the source control window could be worded better.  It does little to distinguish between a local repository and a remote one.

![image](https://user-images.githubusercontent.com/28154402/29497431-0a69cc8a-85ad-11e7-9af8-22d0304626d8.png)

I propose that the text change to:
**Open Local Repository**
Open local repository from disk.  The active project will host the source code.
**Create New Local Repository**
Creates a new local repository from the active project.
**Clone Remote Repository**
Clone a remote repository from a provided URL to the local disk.  The repository will then be loaded into the active project.
**Publish Existing Repository**
Publishes an existing repository to a remote location.  The active project must be connected to a repository.

**Comment by Vogel612** [comment]
@shadowofsilicon the idea sounds good to me, NB we should also move these changes to other translations

**Comment by shadowofsilicon** [comment]
What process should I go about making these changes re: the other translations?  Deleting the corresponding translations seems the most obvious but most destructive.

**Comment by retailcoder** [comment]
I use @Vogel612 's translator /resx editor tool for RD resources; it easily identifies resource strings that are identical or missing, and creates any missing keys. Deleting the outdated resources would be the simplest way. Leaving them in would make them too easy to miss.
