### ISSUE TITLE
Default HotKey overlap

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#3280]
According to PR #3256 (fixes #2707), The default Hot Key for `Refactor|Encapsulate Field` has been changed to <kbd>Ctrl-Shift-F</kbd> while the newly added `Export Active Project` Hot Key is <kbd>Ctrl-Shift-E</kbd>. However, from a freshly installed Build .2079 (including build .2073) shows:
![rd default hot keys](https://user-images.githubusercontent.com/11889733/29525247-fd36fc3c-865f-11e7-80ee-891658a1bac9.PNG)
To be fair, the `Export Active Project` Hot Key is disabled by default, but the picture doesn't quite line up with the assignments given in the release notes (which do make sense).

**Comment by retailcoder** [comment]
Do you repro that screenshot if you wipe your settings file?

**Comment by daFreeMan** [comment]
No repro.

The bug, then, is that this needs to not require deleting the `.config` file to make it work! ;)

**Comment by retailcoder** [comment]
The bug is that we're not overwriting your custom settings with the defaults when installing a newer version?

**Comment by daFreeMan** [comment]
YES!!!

Oh, wait... I guess that makes sense... 

Since _I_ hadn't changed any of the Hot Keys, I'm perfectly fine with it. I guess some people would. I use the listing to print a screen shot of them so I can remember them.
