### ISSUE TITLE
@IgnoreInspection annotations don't seem to be working

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#3281]
`'@IgnoreInspection xxx` annotations don't seem to be working:

![rd ignoreinspection no ignoring](https://user-images.githubusercontent.com/11889733/29536227-010eacd0-868b-11e7-9378-694e779730cd.PNG)

![rd ignoreinspection no ignoring 2](https://user-images.githubusercontent.com/11889733/29536301-43145314-868b-11e7-8832-666d17ea4f09.PNG)

**Comment by retailcoder** [comment]
`@IgnoreInspection` isn't an annotation. does `@Ignore` work?

**Comment by daFreeMan** [comment]
Works like a champ...  :/

"Ignore this instance" would be awesome as a quick fix to insert that annotation for the poor chump, er... user like me.

Things like the first one that really aren't issues but that RD can't totally sort out yet really need the `'@Ignore xxx` annotation to minimize the noise in the inspections, while maintaining a note in the code that this really is OK as is.

**Comment by retailcoder** [comment]
That's "Ignore Once", available from the 'Fix' drop-down.
