### ISSUE TITLE
Problem parsing debug statements

### ISSUE THREAD

**Issue by Greedquest** [rubberduck-vba/Rubberduck#3284]
New user to RD and Github so sorry if this is already a known issue:

In a class module `myClass` I have:

```
Public Property Get Column(newVal As Long)
    colVal = newVal
End Property
Public Property Get Column() As Long
    Column = colVal
End Property
```
In a standard module I have

```
Sub getColumn
    Dim cls As New myClass
    cls.Column = 1
    Debug.Print cls.Column; "is the value"
End Sub
```
When I run a `Refactor` -> `Rename` on Column to change it to Rank, the property name is changed fine, as well as anywhere my code references it **except** in the debug statement

i.e. the module code becomes

```
Sub getColumn
    Dim cls As New myClass
    cls.Rank = 1    'Column is changed to Rank as expected
    Debug.Print cls.Column; "is the value"    'note Column is not changed here
End Sub
```

I could run some more tests but I imagine the bug is down to the `;` after the property name in my Debug statement. Please ask if you need further information / clarification.

**Comment by retailcoder** [comment]
Pretty sure the semicolon has nothing to do with it; `Debug` is a hack, it doesn't exist in the VBA standard library, so we essentially treat it as a keyword (defined a specific parser rule for it).

Thanks for reporting this!

**Comment by retailcoder** [comment]
Hmm, which version are you using? I cannot reproduce with the current build.

**Comment by Vogel612** [comment]
Off of next, the references are not even renamed at all ... Removing [status-norepro], adding [critical], because this results in code breaking

**Comment by Vogel612** [comment]
The problem seems to be that the resolver never enters the Debug.Print statement context to resolve the references in it. Needs some more digging....

**Comment by Vogel612** [comment]
Root cause of the test failing was the Mocking API being chronically difficult to get right... We should really fix that. Well at least we have a regression test for this now.
