### ISSUE TITLE
Inspection for explicit event handler invocation

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#3286]
ref. #2271, #2272

Event handlers *handle events*, invoking them explicitly is a blatant anti-pattern that needs to be erradicated.

Let's have an inspection that finds event handler procedure calls (user events or not) and screams.

There can't be a quick-fix for this, unfortunately - not for now anyway - the only real fix is to refactor/*extract method* out of the handler, and invoke the extracted method instead.

**Comment by Vogel612** [comment]
So what's the suggested solution? Fire the event or invoke the bound method explicitly? And in what way would those be different?

**Comment by retailcoder** [comment]
@Vogel612 say you're handling the `Worksheet.Change` event in the code-behind of `Sheet1`:

````
Private Sub Worksheet_Change(Target As Range)
    ' do stuff
End Sub
````

What the inspection needs to point out is that this `do stuff` code doesn't belong *in the handler*, but in its own separate procedure. Any code that wants to `do stuff` should call *that separate procedure*, not the event handler.

Hmm, this might be an exact dupe of #2272

**Comment by Vogel612** [comment]
looks like it...
