### ISSUE TITLE
QuickFix unit tests need their own namespace

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#3289]
Inspection quickfixes are currently unit-tested within the `Inspections` test category, and the tests themselves are located within the test classes for their respective inspections.

This is problematic, since quickfixes are no longer strongly coupled with a specific/particular inspection.

We need to extract the quickfix tests into their own test classes, in their own `RubberduckTests.QuickFixes` namespace (or `RubberduckTests.Inspections.QuickFixes`).

This will help improve test coverage and review edge cases for inspection quickfixes.

**Comment by Vogel612** [comment]
Fixed as of #3309
