### ISSUE TITLE
CE context menu needs an Open command

### ISSUE THREAD

**Issue by shadowofsilicon** [rubberduck-vba/Rubberduck#3296]
The context menu in the tree view of the Code Explorer window should have an Open command at the top of the menu.  (Think: right-clicking on a file in Windows Explorer.)

Additionally, when the object selected is a Userform, the "Open" menuitem should change to "Open Code", and immediately below that, a "Open Designer" menu item should appear.

**Comment by retailcoder** [comment]
I believe both of these commands are already in place, just not as menu items.

"Open" would be the `NavigateCommand` invoked by double-clicking a node.

"Open designer" exists as a button in the CE's toolstrip.

Should be pretty easy to add a `CommandMenuItem` for both.

**Comment by shadowofsilicon** [comment]
Are their logical reasons why the Open command is named "Navigate" and why it is below the Refresh command?

**Comment by retailcoder** [comment]
We wanted 'Refresh' to be at the top, and 'Navigate' doesn't feel wrong.... or does it?

**Comment by shadowofsilicon** [comment]
Both feel wrong to me.
