### ISSUE TITLE
Unqualified document-module member usages are treated as undeclared identifiers

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#3299]
In `ThisWorkbook` and/or `Sheet1`, this is a valid statement - being an implicit call to `ThisWorkbook.Name` or `Sheet1.Name` respectively, or to `Me.Name`:

```vb
Debug.Print Name
```

In the latest build RD throws 2 false inspections:
- Local variable 'Name' is not declared
- Variable 'Name' is not assigned

The resolver needs to know about built-in members of the respective document object.

**Comment by MDoerner** [comment]
This is the just a symptom of #3154.
