### ISSUE TITLE
Remove TODO items from TODO Explorer toolbar

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#330]
TODO Explorer allows browsing TODO items, and that's great. We should have an option to remove the TODO comment from within the TODO Explorer - let's add a button to the window's toolbar to do that.

**Comment by ckuhn203** [comment]
:+1:

**Comment by ckuhn203** [comment]
@RetailCoder easy fix?

**Comment by retailcoder** [comment]
If anything goes wrong... :see_no_evil:

**Comment by retailcoder** [comment]
Thanks again @Hosch250!
