### ISSUE TITLE
Parse results are cached even when references are changed

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#3300]
Adding, removing, or changing the order of a reference can alter the resolver results for a module. The parser seems to skip parsing a module if it is unchanged, even though a reference change might make a substantial impact on resolution.

The parser should take reference changes into account when caching results.

**Comment by MDoerner** [comment]
Do you have a concrete example. The way things are set up right now, all modules with references to project references that get unloaded should be reresolved.

**Comment by ThunderFrame** [comment]
AFK, but in Excel, I added a reference to Outlook, parsed code that included `Debug.Print Application.Name` and then removed the Outlook reference and reparsed. The `Application` identifier was still shown as being an `Outlook.Application`.

**Comment by MDoerner** [comment]
I have an idea what could be the problem here, but I will have to verify: in one of the compilation passes in the reference resolver, we add project references to the built-in projects to all other built-in projects. That might fool the `COMReferenceResolver`. I guess the declarations for outlook never got unloaded.

**Comment by MDoerner** [comment]
There are two problems involved here:

1. The `ReferencePriorityMap`s never get updated with regard to removed references. So we never onload no longer needed reerences. (This only concerns the case where references get removed from all open projects.)
2. We only override reference priorities but do not check whether they changed and act on it.
