### ISSUE TITLE
Code Explorer should tell the user it needs to be refreshed when it's empty

### ISSUE THREAD

**Issue by shadowofsilicon** [rubberduck-vba/Rubberduck#3304]
Currently, the TreeView section of the Code Explorer window displays nothing before a parsing run has completed, not even a top-level ProjectViewModel.

When this section is completely empty but still active (i.e., not greyed out) it projects to the user the idea that something might be broken, when in fact, the parser just needs to run.

If nothing is being displayed in the Tree View, that section of the window should be grayed with a message along the lines of "Refresh to view the project tree."

**Comment by shadowofsilicon** [comment]
An alternative idea would be to automatically run the parser when the CE window is opened.  However, I wonder if that would cause issues if 1) the project being open causes a parser error or 2) if the CE is set to load on startup, if that would create a race condition where the project isn't yet available to parse?

**Comment by retailcoder** [comment]
@shadowofsilicon in theory we're already running an initial parse on startup - it just doesn't happen *consistently* for some reason. We've had issues with the initial parse causing a hard crash / `COMException` on startup, so this is a critical area of the code that cannot be taken lightly.

I don't think we need to "gray out" everything; just a little yellow-background label (similar to what the *Source Control* panel uses) at the top of the client area could do the job:

> **Rubberduck doesn't see anything yet.**
>
> Click 'Refresh' to have Rubberduck parse and process the projects in the VBE.
>
> <sub>Don't show this message again  |  Refresh now</sub>

**Comment by shadowofsilicon** [comment]
IMHO graying it out (The tree view, not the entire CE) would be cleaner UI, it would be more natural to the user, and likely easier to implement.

I see the reason for using the yellow banner in the SC window; on that window there is nothing to grey out to show inactive.  Whereas here, we have something we can do that with.

Either one would work, though.

**Comment by retailcoder** [comment]
A disabled WPF treeview isn't grayed out. We'd have to *make it* be. IMO it makes no difference what the backcolor of an empty panel is; without the info-banner either backcolor looks like the feature is broken anyway.

**Comment by shadowofsilicon** [comment]
![image](https://user-images.githubusercontent.com/28154402/29778811-3cff6018-8bd6-11e7-9057-a982a36729d6.png)

It's a very crude mockup but that is my vision.

That came across poorly; the color is a minor detail.  We both agree that the message is most important.  When I said "grey" I intended to convey the idea of "dim out to show inactivity."

**Comment by retailcoder** [comment]
That would work. Make the background WorkArea-gray (dark), and put the centered message on a yellow-ish background banner spanning the whole width of the content panel, and it'll look pretty neat I think.

**Comment by shadowofsilicon** [comment]
If we put the message in a yellow-ish banner, then it should be at the top of the WorkArea.  It won't look right being halfway down the work area.

**Comment by shadowofsilicon** [comment]
**Exhibit A:**
![2017-08-29 16_01_54-frito-lay other plc - win7 - 3_8_2017 - vmware workstation 12 player non-commer](https://user-images.githubusercontent.com/28154402/29849656-d2feb57e-8ced-11e7-878f-e0ab7e3b85e9.png)
![2017-08-29 16_00_04-issues rubberduck-vba_rubberduck](https://user-images.githubusercontent.com/28154402/29849660-d692727a-8ced-11e7-836f-5c0e958fe277.png)

**Exhibit B:**
![image](https://user-images.githubusercontent.com/28154402/29849688-05840b7a-8cee-11e7-9b7a-9ddd99971dea.png)
![image](https://user-images.githubusercontent.com/28154402/29849696-1c52c42c-8cee-11e7-9f13-1627af98d11c.png)

Submit your votes before polling closes!!! ;)

**Comment by retailcoder** [comment]
Hmm, I like the centered one, however inconsistent it might be with the SC panel.

**Comment by shadowofsilicon** [comment]
I think the user interaction difference between the this message and the SC error messages are sufficiently different.  This message will be here when the "content" (tree) is "empty", and either the message _or_ the content will be visible. In the SC window, the "content" stays visible, and the message is specifically dismissed by the user.

**Comment by PeterMTaylor** [comment]
I vote that ALL features that is Code explorer and source controls are identical in behaviour waiting til it parses then provides a prompt.

**Comment by Vogel612** [comment]
Voting Post for Exhibit A

**Comment by Vogel612** [comment]
Voting Post for Exhibit B

**Comment by Hosch250** [comment]
Exhibit B can have that link, if that's why you aren't voting for it.
