### ISSUE TITLE
"@Ignore UnassignedVariableUsage, VariableNotAssigned" doesn't seem to work

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#3305]
The `@Ignore` annotation doesn't seem to cause the inspections to be ignored:

![rd ignore doesn t](https://user-images.githubusercontent.com/11889733/29779632-1ab48e4c-8be1-11e7-95ca-a4d7ef4f3d76.PNG)

I used the `Fix` drop down to insert the annotation, then moved the annotation to what I believe to be the correct location (see #3283), and this is the result.

**Comment by MDoerner** [comment]
Does it work if you ignore just one inspection?

**Comment by daFreeMan** [comment]
Excellent question, @MDoerner. I tried with each individually and neither seems to work.

**Comment by comintern** [comment]
This was closed along with #4364 (duplicate)
