### ISSUE TITLE
Indenter: Option to ignore single blank lines in the first comment and first declaration blocks

### ISSUE THREAD

**Issue by SteveLaycock** [rubberduck-vba/Rubberduck#3314]
At present if I select to indent the entire procedure body I also get the options to indent the first comment and declaration blocks.  However these options fail to do what I want if there are blank lines present (which I often use to organise layout, particularly for declarations.

Would it be possible to have further options to ignore single line spacing in th efirst comment and declaration blocks.

**Comment by retailcoder** [comment]
Out of curiosity, is this a regression vs. the legacy 32-bit original *Smart Indenter* add-in?
