### ISSUE TITLE
Variable is used but not assigned false positive with fixed length strings

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#3316]
The following code raises 2 false positives for Variable message is used but not assigned.

Unassigned dynamic strings default to `vbNullString`, but a fixed length string defaults to a string of spaces, and as such, is assigned.

```vb
Sub test()
  Dim message As String * 100
  Debug.Assert message = Space$(100)
  InsertAt message, 5, "Hello"
End Sub

Sub InsertAt(ByRef baseString As String, Offset As Long, Value As Variant)
  Mid(baseString, Offset) = Value
End Sub
```

**Comment by retailcoder** [comment]
That's rather debatable... the string is *initialized*, indeed, just like a `Long` is initialized to 0 and a `Boolean` to `False` - but it's indeed not *assigned*.

Also that specific example is a `ByRef` assignment, a known edge case.
