### ISSUE TITLE
Snippet for Excel: ToggleWaitMode

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#332]
Almost every macro-enabled workbook I code in, in Excel, has this method:

```
Public Sub ToggleWaitMode(Optional ByVal enabled As Boolean = False, Optional ByVal message As String = vbNullString)
    Application.Calculation = IIf(enabled, xlCalculationManual, xlCalculationAutomatic)
    Application.Cursor = IIf(enabled, xlWait, xlDefault)
    Application.StatusBar = IIf(enabled, message, False)
    Application.ScreenUpdating = Not enabled
End Sub
```

Let's start adding host application-specific snippets to the code pane's context menu!

**Comment by PetLahev** [comment]
+1
Would be awesome to see it in some future version of ducky. I'd even go further like complex snippets for progress bar, database connection, XML, custom parts.. etc.
I'd let user adding her specific snippets, maybe even maintain some NuGet-like site.. hmm I've already started dreaming about it!

**Comment by ptwales** [comment]
I use this sub to do something similar.
```
Public Sub ScreenUpdatingSwitch(ByVal state As Boolean)
    Static offLevels As Integer
    If state Then
        If offLevels > 0 Then offLevels = offLevels - 1
        Application.ScreenUpdating = (offLevels = 0)
    Else
        offLevels = offLevels + 1
        Application.ScreenUpdating = False
    End If
End Sub
```
That way you can safely nest procedures that toggle screen updating.

**Comment by retailcoder** [comment]
out of scope. I'm removing the [code-snippets] label
