### ISSUE TITLE
Spinning Ducks stop spinning between end of Parse, and refresh of Inspection Results

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#3321]
I'm unsure if this is because the CPU is flat-out when running inspections, and the WPF animation isn't updating, or whether the animation is stopped (but not removed) when the Parse/Resolve completes.

The frozen ducks <s>are delicious when slow-cooked</s> suggest that the process is hung, and should perhaps keep spinning until the inspection results are refreshed.

Obviously this UI anomaly only occurs when you have a lot of inspection results. My open projects generate about 900 results (some of which are aggregated, so the total number of inspection results is probably closer to 2000)

**Comment by retailcoder** [comment]
The ducks would be showing for as long as "busy" state is `true`. The ViewModel's `RefreshInspections` method sets it to `true`, runs the inspections asynchronously (awaits the results), then groups the results accordingly with the selected grouping, and then the very last thing that it does, is dispatching these instructions to the UI thread:

            UiDispatcher.Invoke(() =>
            {
                Results = new ObservableCollection<IInspectionResult>(results);

                IsBusy = false;
                IsRefreshing = false;
                SelectedItem = null;
            });

I don't see how else we can do this.

**Comment by shadowofsilicon** [comment]
This feels like an area where we could do some optimization and performance improvements re: the UI.  I'll see what I can do.

IMHO, its UI performance, or trying to implement multithreading.  :/

**Comment by comintern** [comment]
Should be closed by #4717.
