### ISSUE TITLE
Add search bar to Code Explorer

### ISSUE THREAD

**Issue by bclothier** [rubberduck-vba/Rubberduck#3329]
As the consequence of the discussion from issue #3323, I'm opening a separate issue to request adding a search bar to the CE, similar to an Access feature shown here:

![Search bar image](https://user-images.githubusercontent.com/2367644/29905074-0b4b94bc-8dd2-11e7-8c25-1efd0811dfd7.png)

The primary purpose of the search bar is to quickly filter a list. We have a `@Folder` annotation but when loading a existing & large project, it can be painful to have to add annotations on a per-module level just to get some level of organization not possible with the object explorer. 

This is distinct from the existing search tools such as GoTo Implementation or Find all references because the workflow is primarily to filter the list of code explorer to only a subset of modules (which can be various component types) that happens to contain a common word, making it easy to navigate between modules when applying changes to a common set of functionalities, without having to add the `@Folder` annotation.

Additionally, this can be leveraged to support mass assignment of `@Folder`. 

To help remind people, the fill-in text could be made explicit such as `Search Module Names` rather than just `Search` and provide buttons for `Find Symbol` if they need to look inside the modules rather than filtering the Code Explorer.

**Comment by Kashyap12** [comment]
hi @bclothier , can I take this up? I am quite new toopensource.

**Comment by shadowofsilicon** [comment]
@Kashyap12 If you want to fork Rubberduck and submit a PR, please, be our guest!  It will be greatly appreciated!

**Comment by bclothier** [comment]
@Kashyap12 this might be helpful:

https://github.com/rubberduck-vba/Rubberduck/wiki/Contributing

**Comment by retailcoder** [comment]
@Kashyap12 sure! do you have a Code Review Stack Exchange account? Join the [dev chat](https://chat.stackexchange.com/rooms/14929) anytime (we can grant you explicit access if you don't have the required 20 reputation points), it will be easier to ask any questions you might have.

**Comment by Kashyap12** [comment]
hi @retailcoder Thanks, joined the chat room, i think i dont hv the required 20 points
