### ISSUE TITLE
Code Explorer sorting by type should keep property accessors together

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#3340]
Currently `PropertyGet` accessors show up before `PropertyLet` accessors. That's nice, except if a property has both accessors, then navigating properties becomes ...annoying:

![image](https://user-images.githubusercontent.com/5751684/29986393-211ca136-8f31-11e7-9f50-dba914e263df.png)

ByType-sort should keep property accessors bundled together, so `PropertyGet` and `PropertyLet` and `PropertySet` should have the same weight in sorting, and properties need to be special-cased so that instead of this:

 - CategoryCode (Get)
 - 20 other members
 - CategoryCode (Let)

I'd have this:

 - CategoryCode (Get)
 - CategoryCode (Let)
 - 20 other members

**Comment by shadowofsilicon** [comment]
Oh, it's grouping Lets, Gets, and Sets individually.  I was wondering about this when I was looking at the dictionary.  Should be a simple fix.
