### ISSUE TITLE
Encapsulate field is deactivated in the context menu of the code pane for new public fields

### ISSUE THREAD

**Issue by MDoerner** [rubberduck-vba/Rubberduck#3342]
Steps to reproduce:

1. Add a new class to a project.
2. Refresh RD
3. Add a new public field to the call
4. Refresh RD
5. Select the field.

The selection will be correct, but the Encapsulate Field refactoring is deactivated in the menu.

![grafik](https://user-images.githubusercontent.com/22868956/29989702-ff49b41a-8f74-11e7-9713-f020822a1a95.png)

If you restart the host and then refresh RD, the Encapsulate Field refactoring will be available.

![grafik](https://user-images.githubusercontent.com/22868956/29989667-b492d7da-8f74-11e7-9036-b9c723baaa72.png)

For some reason, after removing a public field that has already been there at the start, refreshing, then inserting it again and refreshing again, the Encapsulate Field refactoring stays there.

It seems as if the refactoring somehow caches the fields it can work on at startup.

**Comment by BZngr** [comment]
I am unable to reproduce this issue now.  Following the steps above results in an activated `EncapsulateField` option in the menu.
