### ISSUE TITLE
Method shortcut keys lost on module rewrite

### ISSUE THREAD

**Issue by puzzlepiece87** [rubberduck-vba/Rubberduck#3348]
When using quick fixes in RD, method shortcut keys are sometimes (always?) lost.

Tentative steps to reproduce:
1. Create a method that is implicitly public.
2. Assign it a shortcut key via the Macros button in the Developer tab.
3. Use RD's code inspector to quick fix the implicitly public method to explicitly public.
4. The shortcut key no longer works/is not available in the Macros button.

Possible solutions:

There appear to be two methods here that would work
https://social.msdn.microsoft.com/Forums/en-US/7681fa96-4f83-4747-93e1-281db81e316d/assigning-keyboard-shortcut-to-vba-macro-programmatically?forum=isvvba

**Comment by ThunderFrame** [comment]
I think that's a VBE quirk - editing the signature of the method, whether manually or with Rubberduck, tends to obliterate the VB_Attributes (and the shortcut key is a VB_Attribute).

**Comment by ThunderFrame** [comment]
Also, I think that MSDN fix only applies to Excel.

If the attribute annotations included the shortcut key, then the rewriter would be able to reinstate the VB_Attribute.

**Comment by retailcoder** [comment]
@ThunderFrame TIL. And as a bonus you get the hotkey visibly documented in the editor.

**Comment by bclothier** [comment]
This should be fixed by upcoming PR #4686

**Comment by retailcoder** [comment]
Losing the attribute should be fixed, but @ThunderFrame's idea should still be implemented:

```vb
'@HotKey("T")
Public Sub DoSomething()
Attribute DoSomething.VB_ProcData.VB_Invoke_Func = "T\n14"
End Sub
```

The hotkey string/character is case-sensitive, and the <kbd>Ctrl</kbd> modifier is implicit. The attribute value simply needs to take (+validate) that character, append `"\n14"` (which presumably stands for the <kbd>Ctrl</kbd> modifier key).

**Comment by retailcoder** [comment]
Actually the annotation should be `@ExcelHotKey`, since it's apparently Excel-specific. https://stackoverflow.com/a/36961298/1188513
