### ISSUE TITLE
RD & Project help file 

### ISSUE THREAD

**Issue by bclothier** [rubberduck-vba/Rubberduck#3355]
According to the wiki, RD will store `ProjectID` in the project help file. 

What is the ramification if a project has a help file? In my testing it seems to leave the property well alone but I'm left wondering if that means RD is doomed to never know the `ProjectID` or does it just use the help file as the project ID and hope for the best?

**Comment by rubberduck203** [comment]
The thought process was that a VBA project wouldn't ever have a help file, as this was just carried over from VB6 and, to the best of our knowledge, unused. 

Of course this was prior to any of @retailcoder's efforts to actually support VB6 and Visual Studio. If that goes anywhere, we'll need to address this because it will matter in that environment.

**Comment by bclothier** [comment]
Gotcha. I actually was considering using it to help document our standard library code. 

In my tests, I can only F1 to my custom chm file only from the object browser or from the calling reference. It doesn't work inside the definition, however even when highlighting the identifier of the method. 

I'm currently looking for a nice way to document the code... short of unloading a mess of comment that the code ends up unreadable and in spite of the not using CHM file when inside the definition, it might be just useful enough so the team members can F1 to get detailed info & examples.

**Comment by bclothier** [comment]
Though, the more I think about it, the less enthused I'm about writing a CHM file. The process is just so.... **cumbersome**. I mean, I have to map everything by a numeric ID that i can't write directly in the code pane, run a 3rd party software to compile a CHM file then distribute it. Ugh. 

But the real problem is that in VBA world, I think documentation is essentially mandatory given the requirements of the language. We can't have parameterless constructors so we make do with `Init` method to actually initialize the instance since the class' `Initialize` event can't reach outside and take parameters. I see we already have case #3262 which will help track this type of cases but it won't explain *why*s & assumptions which I can't communicate via the source code alone. 

So, a question: could RD be used to help improve the help experience? For instance, could it intercept F1 and determine if it's referring to a custom identifier and thus display a nice simple markdown page that's easy to edit & update, otherwise route to VBA editor to open its usual help file?

**Comment by retailcoder** [comment]
Linking #818, currently declined as out of scope - I agree a real documentation solution would be useful, but that's a huge undertaking and a project of its own. I wouldn't reject a PR that neatly introduces the feature in RD though.

Using the project helpfile was the solution we figured could be used to uniquely identify each project. Changing it after it's assigned by Rubberduck can/will confuse it, but if it is used and points to an actual helpfile, there shouldn't be a problem... as long as the helpfile is *for that project* and no other project uses it.

**Comment by bclothier** [comment]
Closing this since the question has been answered.
