### ISSUE TITLE
Using Roslyn with Rubberduck (licensing question)

### ISSUE THREAD

**Issue by bclothier** [rubberduck-vba/Rubberduck#3367]
As per chat, it has been suggested to open an issue to investigate whether Rudderduck can use Roslyn. The initial concern was it could not because RD is using GPL license while Roslyn is using Apache Public License (APL).

However, my reading is that APL can be used in GPL'd project (but not the other way!) and therefore there should be no problem using Roslyn.

Supporting links:
http://www.apache.org/licenses/GPL-compatibility.html
http://www.gnu.org/licenses/license-list.html#SoftwareLicenses
https://github.com/dotnet/roslyn/blob/master/License.txt

**Comment by retailcoder** [comment]
Roslyn does not support VBA, or any DSL.
https://stackoverflow.com/a/34781729/1188513

**Comment by Vogel612** [comment]
As @retailcoder notices, while this is feasible from a legal standpoint, it's technically not a viable solution. As such the discussion about using roslyn is... not bringing us any net benefit
