### ISSUE TITLE
"Ignore Once" annotation line position is affected by previous executions of the quickfix

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#3373]
I have some stubs for future development that are currently not being called. The `Procedure {x} is not used` inspection is properly identifying that they are not called. The `Ignore once` Quick Fix does _not_ insert an `@Ignore {inspection}` annotation.

![rd ignore once quick fix](https://user-images.githubusercontent.com/11889733/30431336-506c0210-992c-11e7-96e7-53cde38fdfd3.PNG)

That's the same picture before & after clicking...

_Ignore the 243 meaningful name inspections, please, I know they're there..._

**Comment by retailcoder** [comment]
Just to confirm: "Removed unused declaration" *does* work, correct?

**Comment by daFreeMan** [comment]
Yes, "Remove unused declaration" does work.

**Comment by Vogel612** [comment]
So I wrote a unit-test for this and it didn't fail

**Comment by retailcoder** [comment]
@Vogel612 the procedure is first-thing in the module, it *does* make a difference. Needs tests with `Option Explicit` and an empty line before the procedure, and then others with two procedures, the first one invoked by the 2nd one, the 2nd one never invoked and triggering the inspection - at least one with and one without empty lines between the two procedures.

**Comment by daFreeMan** [comment]
According to chat, there's no repo & questions about the version.

Here's the code in question and proof of the version.
![rd ignore once quick fix 2](https://user-images.githubusercontent.com/11889733/30446415-18eacf76-9957-11e7-83a0-9e8cc5315c58.PNG)

[DBConfiguration.cls.txt](https://github.com/rubberduck-vba/Rubberduck/files/1304028/DBConfiguration.cls.txt)

**Comment by retailcoder** [comment]
No repro with .2357

**Comment by retailcoder** [comment]
Wait a minute... just got it!

**Comment by retailcoder** [comment]
Ok. So the problem seems to be that there's something we're not invalidating on reparse, causing the quickfix to think the annotation should be inserted where it would have been needed before a previous quickfix shifted the module contents down one line. Investigating.

**Comment by retailcoder** [comment]
Wow the insertion point positioning was.... weird.

**Comment by retailcoder** [comment]
Reportedly fixed.

**Comment by bclothier** [comment]
Closing this since this should be fixed in the PR #4693 (and related PRs)
