### ISSUE TITLE
"Ignore Once" for "Object reference is auto-instantiated" puts the annotation on the wrong line

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#3374]
Given:

```VBA
Private Sub Foo
  
  Dim bar As New Baz

End Sub
```

The QuickFix generates:

```VBA
Private Sub Foo
'@Ignore SelfAssignedDeclaration
  
  Dim bar As New Baz

End Sub
```

A reparse triggers the exact same `auto-instantiated` inspection. Manually editing it to:

```VBA
Private Sub Foo

'@Ignore SelfAssignedDeclaration
  Dim bar As New Baz

End Sub
```

The inspection is _not_ triggered.

**Comment by retailcoder** [comment]
I smell an off-by-one error...

**Comment by retailcoder** [comment]
The "auto-instantiated object reference" inspection's "ignore once" fix is covered by [one single test case](https://github.com/rubberduck-vba/Rubberduck/blob/next/RubberduckTests/QuickFixes/IgnoreOnceQuickFixTests.cs#L896-L928)

```csharp
            const string inputCode =
@"Sub Foo()
    Dim b As New Collection
End Sub";

            const string expectedCode =
@"Sub Foo()
'@Ignore SelfAssignedDeclaration
    Dim b As New Collection
End Sub";
```

That test class needs many, many more test cases, especially some involving vertical whitespace and line continuations.

**Comment by Vogel612** [comment]
IgnoreOnce is generally weird, since it actually pertains to basically all inspections... What actually needs the unit-test here is the `InspectionIsIgnoredFor` method

**Comment by retailcoder** [comment]
@Vogel612 true, needs that *as well* - but the coverage is insufficient here as well; this would be a failing test according to the issue:

```csharp
            const string inputCode =
@"Sub Foo()

    Dim b As New Collection

End Sub";

            const string expectedCode =
@"Sub Foo()

'@Ignore SelfAssignedDeclaration
    Dim b As New Collection

End Sub";
```
