### ISSUE TITLE
Ignore shadowing of declarations inside test modules

### ISSUE THREAD

**Issue by rkapka** [rubberduck-vba/Rubberduck#3379]
ShadowedDeclarationInspection warns about public members of test modules, which doesn't make much sense. I doubt it makes much sense to use these members outside of the module where they are declared.

**Comment by retailcoder** [comment]
Depends. In many hosts (not Excel), having 2 modules with same-name members actually breaks unit testing - that inspection result is a welcome warning / reminder to rename the duplicate methods IMO.
