### ISSUE TITLE
Dirty designer is ignored if code-behind isn't modified

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#3387]
Repro:

 - Add a UserForm module; Rubberduck parses.
 - Add a CommandButton control to the form designer.
 - Request a reparse / refresh: Rubberduck ignores the unmodified UserForm module.
 - Select the command button: Rubberduck fails to see it.

We need to treat designers like "modules" and monitor their "dirtiness" separately from their code-behind. Otherwise, it's possible to have ignored content on a UserForm, and code in other modules that refer to controls on that form: this results in inspection false positives, e.g. `VariableNotDeclared` and `UnassignedVariableUsage` firing up for `UserForm1.CommandButton1`.

**Comment by comintern** [comment]
This should have been closed with #4240.
