### ISSUE TITLE
Code Inspection for Option Explicit not working with white-space at end of file

### ISSUE THREAD

**Issue by Stevefb** [rubberduck-vba/Rubberduck#3390]
Confirmed in MS Word 2010 (64 Bit)

Steps to reproduce:
1. Create a new document 
2. Double click ThisDocument
3. Delete Option Explicit if it is automatically added
4. Run Code Inspection
5. Confirm 2 Code Quality Issues: Option Explicit is not specified

6. Add at least 2 blank lines to ThisDocument 
7. Re-run Code Inspection
8. Viola!

**Comment by comintern** [comment]
I can't replicate this in Word 2013. Is this still an issue for Word 2010 in the current build?

**Comment by Stevefb** [comment]
@comintern  I can confirm that I'm no longer able to reproduce this issue on the same PC that it was originally noticed on.
