### ISSUE TITLE
Code inspection to ensure Procedure Separator option is set

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#3394]
Many (all?) annotations are sensitive to where in relation to procedural code they are located (as demonstrated by #3393 among others). The easiest way for the (above) average VBA user to know/remember where procedures start/stop is to have the Procedure Separator line visible.

The separator line is turned on here in `Tools | Options`:

![rd procedure seperator](https://user-images.githubusercontent.com/11889733/30818795-92eea28e-a1ea-11e7-963f-acc28780941d.PNG)

There should be an inspection warning that this isn't set with a QuickFix to set it (if that's possible programmatically).

**Comment by retailcoder** [comment]
Side note, not sure whether/how the RD code panes are going to honor that setting.

**Comment by bclothier** [comment]
@retailcoder  I think the logic of separation boils down to this....

1) go to the last line that's not a comment. For procedures that's always `End XXX` varierty. For declarations, it could be anything from a `Const` or `Declare` or whatever.

2) Exclude any contiguous consecutive comment lines (they are still part of the current scope)

3) The first blank line OR the start of procedure statement (e.g. `Sub`/`Function`...) is encountered. That's the first line of the next scope.

Therefore, if RD code pane follows the same rules, it should do a good job, I think. You also have VBIDE to tell you the first/last line of a procedure, if you are in doubt, as well.

**Comment by retailcoder** [comment]
@bclothier there's this too:

    '@Description("Does something")
    Public Sub DoSomething() : End Sub
    Attribute DoSomething.VB_Description = "Does something"

oooooh how nice would it be to *toggle* "show module/member attributes" on/off!! `</unrelated-thought>`

**Comment by retailcoder** [comment]
TBH, I don't think we want an inspection for this. We don't have one for "require variable declarations" - instead we have an inspection for "Option Explicit is not specified". Similarly, we don't need one for "show procedure separator", we have an inspection for "Illegal annotation" to validate annotation position.
