### ISSUE TITLE
"Step 1" is redundant

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#3395]
Consider this code:

    Dim x As Long
    For x = 1 To 1000 Step 1
        ' do stuff
    Next

We need our static code analysis to highlight that `Step 1` is the default and therefore redundant.

**Comment by Vogel612** [comment]
Also directly warrants the complementary inspection: "Step is not specified" with QuickFix "introduce step"

**Comment by retailcoder** [comment]
@Vogel612 with default severity set to `DoNotShow`, I hope? :wink:

**Comment by SystemsModelling** [comment]
Oh, I don't know, sometimes unnecessary precision is a way of drawing attention to the fact that I really mean 1. Or mean 1 this time, and maybe it was 10 in a previous version.

**Comment by retailcoder** [comment]
@SystemsModelling yep, that's why it needs to be 2 inspections - one to warn about `Step 1` being redundant (and a quickfix to remove it), another to warn about `Step` being unspecified (and a quickfix to add it), and the user can pick which one they prefer to enable :smile:
