### ISSUE TITLE
SafeComWrappers could use some C#7 love

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#3407]
ReSharper is going frantic with all the C#7 opportunities in that namespace.

**Comment by IvenBach** [comment]
Are the opportunities brought to the attention of someone on vanilla VS2017, or does it require R#?

**Comment by Vogel612** [comment]
@IvenBach mostly you need resharper, the namespace does contain mostly simple classes though, so it's a good idea to practice your eyes without it. This gives benefits for more than just C#

**Comment by Vogel612** [comment]
Care: #3405 has also been located down in that namespace
