### ISSUE TITLE
An unknown error occurred - source code control

### ISSUE THREAD

**Issue by grandtiger** [rubberduck-vba/Rubberduck#3409]
The following error occurred every time I tried to open an existing source repository. I have one but only one under the RubberDuck default repository location.

![image](https://user-images.githubusercontent.com/4166612/31126286-44bf0d76-a819-11e7-8e6e-ca3bddcbfb89.png)
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/1352319/RubberduckLog.txt)

**Comment by mansellan** [comment]
Investigating.

**Comment by mansellan** [comment]
@grandtiger I'm having difficulty reproducing this issue, could you provide some more details please:

- How was the existing source repo created?
- Is the Excel workbook you're importing to new, or does it have existing code in it?

**Comment by grandtiger** [comment]
@mansellan Thanks for looking into this!

- The existing repo was created following the wiki page, and was able to clone it using rubberduck for the first time.
- The Excel workbook was recreated based on an existing sheet, however, I ran into some error and was not able to commit using rubberduck, so I kill excel and commit it using command line. However, when I start Excel and rubberduck again, I can no longer open the repository.

Hope this helps. I will also try to recreate the issue with a dummy sheet and get back to you.

**Comment by mansellan** [comment]
Hi @grandtiger,

The latest build (v2.1.0.2309-pre) has fixed a number of issues related to source control COM exceptions, could you please uninstall your current version and install latest and advise if the problem persists.

**Comment by grandtiger** [comment]
@mansellan Thanks a lot! I just tried and it looks like the latest build fixed the issues I had before. I can no longer reproduce them using the latest build.

However, I found that Rubberduck won't clone using SSH, such as git@HostName/ProjectName.git. Because I don't have HTTPS set up, it's using HTTP only, it gave me an error saying "Failed to clone remote repository. Too many redirects or authentication relays". FYI: I am using GitLab-CE to host my repository.

**Comment by retailcoder** [comment]
IIRC the SSH limitation is on LibGit2Sharp.

**Comment by rubberduck203** [comment]
That's what I seem to remember too. I believe they got it working on Linux, but not Windows, so it's of no use to our project. I don't expect to ever see ssh working. 

If export is working now, then you could always just export and then use a cli. I'm unsure of the status of exporting though.

**Comment by Vogel612** [comment]
See also https://github.com/libgit2/libgit2sharp/issues/1422

**Comment by retailcoder** [comment]
Closing / deferred until we update to a libgit2sharp build that supports it.
