### ISSUE TITLE
Update DE translations

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#3413]
The German resources need to be updated for a green 2.1.0 release.

**Comment by legien** [comment]
You need any help with this?

**Comment by Vogel612** [comment]
@legien since #3414 isn't cleared yet: not right now, but we're happy to have people chime in here :)

**Comment by retailcoder** [comment]
@legien it's mostly about #2734, and one or two inspection meta-descriptions include a bit that goes like "Ignore this inspection result if Rubberduck couldn't resolve the identifier" or something similar - which I'd like to remove. These are old translations that already have a key in the `.de` resx file, so the missing keys aren't affected and shouldn't be a showstopper for *this* specific issue.

That said you'll probably want to use @Vogel612's resx-editor tool to help (that's what I use for the French translations, works like a charm!) - it compares two resx files and highlights the missing keys and keys with identical values in both files, which makes it *much* easier to work with than inside Visual Studio's resx editor.

**Comment by Vogel612** [comment]
Hey @legien 

I was wondering whether you're still interested in this. #3414 has been completed now, which should make the review of the resources much easier.  
If you want to take a go at it, be advised that we're currently aiming for a release on Sunday, 15.10.

In case it's necessary, I'll fix this on Saturday, but I don't mind if anyone else does it.
