### ISSUE TITLE
Review EN resources

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#3414]
Some English resources need a bit of rewording - mostly inspection metadata strings. Review them all.

This must be completed before #3412  and #3413.

**Comment by Vogel612** [comment]
It would be easiest to perform the update for translated resources, if the corresponding resource keys are deleted in the other resx files. That makes it clear which resources changed.

**Comment by retailcoder** [comment]
@Vogel612 good call!

**Comment by Hosch250** [comment]
Easy to write a script for :)
