### ISSUE TITLE
Unit Test example 

### ISSUE THREAD

**Issue by er77** [rubberduck-vba/Rubberduck#3420]
Hello 
   Could you please update documentation and site with add full example with unit-test

**Comment by Vogel612** [comment]
note that even though this is labelled hacktoberfest, solving this issue does not entail a PR :/

**Comment by IvenBach** [comment]
Updated https://github.com/rubberduck-vba/Rubberduck/wiki/Unit-Testing with current images. Added to the Assert Class table reflecting addition of new members.

**Comment by Vogel612** [comment]
LGTM 👍
