### ISSUE TITLE
Lines up public variables

### ISSUE THREAD

**Issue by Vitosh** [rubberduck-vba/Rubberduck#3423]
Unfortunately, I do not remember what I was clicking around the tool, but initially I had some public variables in a module like this:
`Public Const STARTING_FROM_COLUMN = 6                           'In table master, the first column to start writing is column F
    Public Const COLUMNS_NOT_TOUCHED = 5                            'In the table master, the first 5 columns are not touched`

After some time the public variables were on one line. It could have been, because some of the comments were with German specific letters like üöäss.  

Sorry, that I cannot replicate it now. I was using the indenter, the error checker and pretty much anything around the tool. The error checker was telling me that I was declaring the STARTING_FROM_COLUMN as a Variant (which is true, it should not be a variant). 

Cheers! 🌵 💯 👍

**Comment by retailcoder** [comment]
Thanks for reporting, ...but without a repro that one's going to be hard to fix. :wink:

**Comment by Vitosh** [comment]
I know. But I do not remember how exactly it happened.

**Comment by retailcoder** [comment]
Could it be related to #3422?

There is no Rubberduck code that intentionally takes two constants on two lines and puts them in a single statement.

**Comment by Vitosh** [comment]
@retailcoder  - I dunno, probably. However, I think it was because the comments after the constants were in German. I can only guess.  🦆

**Comment by Vogel612** [comment]
Closing as stale no-repro
