### ISSUE TITLE
"Variable {x} is used but not assigned"; assignment in For Loop

### ISSUE THREAD

**Issue by salterm** [rubberduck-vba/Rubberduck#3426]
I'm getting two code inspection warnings, "Variable 'cell' is used but not assigned" and "Variable 'cell' is never assigned", for the sub below:

```
Public Sub PopulateColumnWithDropdowns(sht As Worksheet, startRow As Long, endRow As Long, destCol As Integer)
    Dim cell As Range
    Dim i As Integer
    For i = startRow To endRow
        Set cell = sht.Cells(i, destCol)
        cell.Validation.Add xlValidateList, , , "In Progress,In shop,Hanging,Steploading,Down,Results in review,Report in review,Failed,Retesting,Pending,Report sent"
        cell.Validation.ShowError = False
    Next i
End Sub
```
Is this because the for loop can't be guaranteed to run without knowing the index range? If so, I feel like these warnings should be changed to "Variable 'cell' may be used without being assigned" and "Variable 'cell' may never be assigned"

Moving the declaration inside the for loop didn't clear the inspection.

Version: 2.0.13.32288

**Comment by retailcoder** [comment]
Can you reproduce the issue with the latest 2.1.0 pre-release build?

**Comment by retailcoder** [comment]
Running v2.1.0.2287 here, no repro (that's not the latest build) - if you can, I'd encourage you to uninstall 2.0.13 and get the latest pre-release build, *lots* of fixes, a bunch of new inspections, and some new features are waiting!
