### ISSUE TITLE
2.1.02314: Rubberduck not visible in menu

### ISSUE THREAD

**Issue by SteveLaycock** [rubberduck-vba/Rubberduck#3430]
The rubberduck name is not visible on the menu but there is a small gap between  'Add-Ins' and 'Windows' which does pull down the Rubberduck menu.

In the pull down menu all names above  settings are not visible but the right arrow menus work OK.

**Comment by Vogel612** [comment]
Which locale do you have set in your settings? What host are you running on? Do you have a logfile? Does the problem persist between restarts?

**Comment by SteveLaycock** [comment]
The problem survives a reboot.

The problem did not go away on re-installing

WIndows 10 64 bit. (UK English)

Word 32 bit from Office 365 Business version 1709

Rubberduck runs as normal despite this oddity.  e.g. I can select a refactor rename and it works.

I tried to look at a log file but the settings option does not pull up the settings dialog page.

The status line showing Pending/Ready is visible all the time

**Comment by retailcoder** [comment]
I wonder if this might be somehow related to the localization issue I'm seeing at work, with a fr-CA desktop and Rubberduck set to en-US - some resources show up in French. Clearly there's *something* off with the resources.

**Comment by Vogel612** [comment]
Could you try changing the language in the settings? If that "fixes" the issue, I have a repro:

![unbenannt](https://user-images.githubusercontent.com/7288995/31321787-5a6ca3c4-ac8b-11e7-970c-aac1494ad377.PNG)

**Comment by SteveLaycock** [comment]
I'm afraid I can't do that as nothing appears to happen when I click on settings.

**Comment by tomhumphrey** [comment]
Having the exact same issue
![untitled](https://user-images.githubusercontent.com/908319/31330848-f61487dc-acd7-11e7-8941-c2a403b037fb.png)

**Comment by tomhumphrey** [comment]
Changing the language fixed the issue but it doesn't stay fixed on restart

**Comment by A9G-Data-Droid** [comment]
I'm seeing this problem as well using v2.1.0.2318-pre

**Comment by Vogel612** [comment]
Possibly related i18n error:

![unbenannt](https://user-images.githubusercontent.com/7288995/31364234-b35489f6-ad63-11e7-9d8d-4dfc2300cc3b.PNG)

**Comment by retailcoder** [comment]
Nah, that's the weirdness I've been experiencing forever on fr-CA machines. Definitely another localization glitch, but not related.
