### ISSUE TITLE
Code Explorer toolwindow can be shown despite the command being disabled

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#3438]
If there's no project in the IDE (ref. #3436), the CE can still be displayed using the hotkey for its command, despite the command's `CanExecute` implementation returning `false` as the disabled associated command menu item shows.

Typing anything in the CE's searchbar in that state, instantly crashes the host application.

- The CE toolwindow should not be displayable when its command is disabled.
- The CE searchbar should not be enabled when there's no content in the treeview.

**Comment by retailcoder** [comment]
Actually, *every* toolwindow should not be displayable when its corresponding command(s) cannot be executed.

**Comment by mansellan** [comment]
If we're looking to subsume all PE behaviour, shouldn't we allow CE to display when no project is active? I.e. just make sure the search box and all CE commands are disabled?

**Comment by retailcoder** [comment]
I'd like to have the search box and all CE commands disabled, but also a consistent state between the 'Show Code Explorer' command being disabled, and the CE being displayable regardless of what the command's `CanExecute` method says.

**Comment by retailcoder** [comment]
Or, let's change the CanExecute implementation to just return true.

**Comment by retailcoder** [comment]
Okay.

[CommandBase](https://github.com/rubberduck-vba/Rubberduck/blob/next/RetailCoder.VBE/UI/Command/CommandBase.cs) defines `EvaluateCanExecute` as follows:

```csharp
protected virtual bool EvaluateCanExecute(object parameter) => true;
```

[CodeExplorerCommand](https://github.com/rubberduck-vba/Rubberduck/blob/next/RetailCoder.VBE/UI/Command/CodeExplorerCommand.cs), inherited from `CommandBase`, doesn't override it.

That's the *command* though - the *menu item* has its own logic, and this is what needs to be looked at. [CommandMenuItemBase](https://github.com/rubberduck-vba/Rubberduck/blob/next/RetailCoder.VBE/UI/Command/MenuItems/CommandMenuItemBase.cs) defines `EvaluateCanExecute` as follows:

```csharp
        public virtual bool EvaluateCanExecute(RubberduckParserState state)
        {
            return state != null && _command.CanExecute(state);
        }
```

And because [CodeExplorerCommandMenuItem](https://github.com/rubberduck-vba/Rubberduck/blob/next/RetailCoder.VBE/UI/Command/MenuItems/CodeExplorerCommandMenuItem.cs) is not overriding it, the menu item is initially disabled, despite the command's `CanExecute` implementation returning `true`.

The first part of the fix for this issue, consists in adding a simple override in `CodeExplorerCommandMenuItem`, to override `EvaluateCanExecute` to return whatever `_command.CanExecute(state)` returns.

The other part of the fix for this issue, consists in tweaking the XAML markup for the *search box*; the `TextBox`, `Image` and `Button` controls](https://github.com/rubberduck-vba/Rubberduck/blob/next/RetailCoder.VBE/UI/CodeExplorer/CodeExplorerControl.xaml#L493-L495) all need a binding for their `Enabled` property, binding to some `bool CanSearch` property that returns `false` when `Projects.Count` is 0. The [setter for the `Projects` property](https://github.com/rubberduck-vba/Rubberduck/blob/next/RetailCoder.VBE/Navigation/CodeExplorer/CodeExplorerViewModel.cs#L281-L289) can then be modified to invoke `OnPropertyChanged("CanSearch")`.
