### ISSUE TITLE
Ambiguously named test methods should be inspected and/or marked as unreachable

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#3440]
Hosts such as Access do not allow a method to be qualified with a module name, so if a test method (or module/test initialize/cleanup method) name is not unique across *all* modules, then `Application.Run` will fail with error `2517 - Microsoft Access cannot find the procedure 'ProcedureName.'`.

<s>Unless</s> Until RD can find a way to call the specific method, tests involving ambiguously named methods will always fail. Rather than *attempting* to run the tests, and then reporting the test(s) as failed, the tests should be identified as unreachable, avoiding any attempt to run them.

IMO, the unreachable tests should be identified in Test Explorer, with a new category of "Unreachable" and a message of one of:
 - Test module 'ModuleName`'s ModuleInitialize method 'ModuleInitializeMethodName' is ambiguously named
 - Test module 'ModuleName`'s ModuleCleanup method 'ModuleCleanupMethodName' is ambiguously named
 - Test module 'ModuleName`'s TestInitialize method 'TestInitializeMethodName' is ambiguously named
 - Test module 'ModuleName`'s TestCleanup method 'TestCleanupMethodName' is ambiguously named
 - Test method 'ModuleName.MethodName' is ambiguously named

and the ambiguously named test methods should **also appear as inspection results.**

Access mangles the error message with a trailing period in the quoted procedure name, so customizing the message allows RD to be more specific about the cause of the error/ambiguity, and avoids any confusion introduced by the trailing period.

The Test Explorer currently has a column labelled "Outcome" for the status of tests, but it might be better renamed as "Status", to better reflect the nature of an unreachable test (which by definition, can't have a meaningful outcome).

Identifying unreachable tests will involve not only finding individual test methods that are ambiguously named, but also finding **all** test methods that are in modules that have ambiguously named methods for `ModuleInitialize`, `ModuleCleanup`, `TestInitialize`, and/or `TestCleanup`.

An ambiguously named test method will be ambiguous when *any* other module contains a public method with the same name (the other method(s) may or may not be annotated test methods - i.e. any public procedure in any module would cause the ambiguity)

**Comment by bclothier** [comment]
Given the type lib api which allow us to circumvent the limitations of `Application.Run`, the unreachability is now less of a problem.

**Comment by bclothier** [comment]
This is now moot, thanks to the PR #3778
