### ISSUE TITLE
Module/Test Initialize/Cleanup methods silently fail, leading to test methods throwing error 91 or inaccurate test outcomes

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#3441]
In Access, ambiguously named module/test initialize/cleanup methods fail silently, and then when unambiguously named test methods run, VBA raises runtime error 91 because the Assert object isn't initialized.

If the `ModuleInitialize`, `ModuleCleanup`, `TestInitialize`, and/or `TestCleanup` procedures are ambiguously named, then Access VBA can't call these methods. Currently, RD ignores the fact that the method call was unsuccessful, and continues with running tests in the module. If any of the initialize/cleanup methods had been designed to create objects (such as an `Assert` instance) or change state, then the test methods will not have access to valid objects and/or state.

If, for example, a test method expects an initialized `Assert` object, and it hasn't been initialized, then the procedure will break with a runtime error 91 dialog.

If the procedure has access to a valid Assert object, but the state is not as expected, then the test outcome might be inaccurate and/or misleading.

Ideally, this bug fix can be avoided by implementing #3440, but it still might be useful to implement the fix (should the method not be identified as being ambiguous before test execution, which might result in inaccurate test outcomes),

Refer #3417

**Comment by bclothier** [comment]
This should be irrelevant with the current build since we no longer use `Application.Run` and thus do not have the host-specific scoping resolution issues inherent with those methods anymore.

**Comment by retailcoder** [comment]
Unit testing has been wired-up with the TypeLib API, closing.
