### ISSUE TITLE
Special characters get lost commiting source code 

### ISSUE THREAD

**Issue by INOPIAE** [rubberduck-vba/Rubberduck#3461]
When I commit a form some special characters get lost.
Curiously the same character is changed differently depending where the characters is used.
It is always the German lower u Umlaut "ü".
If it is used in the caption of button nothing is changed.
If it is the caption of the form it is changed to 
`Begin {C62A69F0-16DC-11CE-9E98-00AA00574A4F} frmResetBasis 
 Caption         =   "Basis zur�cksetzen"
 ClientHeight    =   3495
 ClientLeft      =   45
ClientTop       =   390
 ClientWidth     =   5835
OleObjectBlob   =   "frmResetBasis.frx":0000
 StartUpPosition =   1  'Fenstermitte
End`
If it is in the normal vb code it is change to:
`Set wksMenge = wkb.Sheets("Mengenger?st")`

**Comment by Vogel612** [comment]
seems like a discrepancy between export and import charsets? The weirdness appears in the VBE, correct? Does it also show up if you examine the exported files by hand`?

**Comment by INOPIAE** [comment]
So far I only observed the problem when commiting. The errors are visible in the saved file in the rd-repro directory.

**Comment by MDoerner** [comment]
Is this still fixed after merging #3529?
