### ISSUE TITLE
Refactor > Rename not working for UDT 

### ISSUE THREAD

**Issue by Stevefb** [rubberduck-vba/Rubberduck#3468]
To reproduce (tested in class modules, Word 2010 (64bit), RD  2.1.0.2361):
    
    Private Type foobar
        foo As String         ' Use RD Refactor > Rename on this line to rename foo
        bar As Long
    End Type
    
    Private Sub aFoo()
        Dim a As foobar
        a.foo = "why"        ' Foo will be changed here but not in the UDT
        a.bar = 42
    End Sub

**Comment by retailcoder** [comment]
hmm, `UdtDeclaration` and `UdtMember` context aren't implementing `IIdentifierContext`. Testing a fix.

**Comment by retailcoder** [comment]
Woot!

    Private Type foobar
        renamed As String         ' Use RD Refactor > Rename on this line to rename foo
        bar As Long
    End Type
    
    Private Sub aFoo()
        Dim a As foobar
        a.renamed = "why"        ' Foo will be changed here but not in the UDT
        a.bar = 42
    End Sub

**Comment by Stevefb** [comment]
Pleasure is all mine - glad it helped!
