### ISSUE TITLE
Current L1C1 selection isn't consistently showing up in the RD toolbar

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#3472]
Not sure why, but it seems to work when it feels like it.

**Comment by comintern** [comment]
This is related to the attaching and detaching of subclasses to MDI windows being broken. The work-around is to close and reopen the module.

Ref #4080

**Comment by comintern** [comment]
Has this popped up again? This should have been either resolved by #4240 or mitigated to the point where the fail rate is acceptable.

**Comment by bclothier** [comment]
We have no idea how to reproduce so we'll optimistically hope that it was fixed. 🦄
