### ISSUE TITLE
Not everything is a "code quality issue"

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#3473]
The updated website's inspection list makes a categorization issue rather apparent:

![image](https://user-images.githubusercontent.com/5751684/31616727-7c47ae00-b25b-11e7-8486-e0b77577b9b3.png)

Some of these "code quality issues" are actually "maintainability/readability issues", notably everything having to do with empty code blocks.

**Comment by IpshitaC** [comment]
Hi!
I'd like to be assigned to this issue. What do I need to do?

**Comment by retailcoder** [comment]
@IpshitaC nice! I'll send you an invite to hop on board if you want (just let me know); you'll find the inspection classes under the [`Rubberduck.Inspections.Concrete` namespace](https://github.com/rubberduck-vba/Rubberduck/tree/next/Rubberduck.Inspections/Concrete).

Each inspection has an `override` for an abstract property getter that returns a `CodeInspectionType` enum value:

```csharp
public override CodeInspectionType InspectionType => CodeInspectionType.CodeQualityIssues;
```

So all that's needed is to change that value for a number of inspections. I'm thinking the "empty block" inspections should be under "maintainability/readability" category.

To be fair, most inspections could be arguably be classified under either category - let's just balance things out a bit!

**Comment by IpshitaC** [comment]
Sure! Please send me an invitation.

**Comment by retailcoder** [comment]
@IpshitaC if you don't have an account on [Code Review Stack Exchange](https://codereview.stackexchange.com), I'd recommend you create one - with 20 rep score you can talk in chat (I can grant you explicit write access in the meantime); our dev chat is [here](https://chat.stackexchange.com/rooms/14929/vba-rubberducking).

**Comment by IpshitaC** [comment]
Hey @retailcoder 
I've raised a PR fixing all the code inspection types in empty block files. Please let me know if there are any further changes to be made.
Also I've made a Code Review Stack Exchange account, but I don't have 20 rep score so far. 😞 
Please grant me explicit access then :)

**Comment by retailcoder** [comment]
@IpshitaC you made the PR on your own fork 😜 please make a new one, with rubberduck-vba/Rubberduck/next on the left-hand side, and your fork/branch on the right-hand side. Thanks!

**Comment by IpshitaC** [comment]
Thanks!
I've opened a new PR pointing to the base repository :)
Please let me know if there are any more changes.
