### ISSUE TITLE
Resolver Error from Multiple @Ignore Annotations

### ISSUE THREAD

**Issue by CHR-IS-B** [rubberduck-vba/Rubberduck#3474]
When applying a fix for a "Return value of [FUNCTION] is never assigned, RD placed the `'@Ignore NonReturningFunction` annotation in the wrong place.  I was able to duplicate the error on a fresh VBA project with just these lines of code:

```
'@Ignore ProcedureNotUsed
Sub MySub()
End Sub
Function TestNonReturningFunction() As Variant
End Function
```

After applying the fix, the code looks like this:
```
'@Ignore ProcedureNotUsed
Sub MySub()
'@Ignore NonReturningFunction
End Sub
Function TestNonReturningFunction() As Variant
End Function
```

Since the annotation is misplaced, the warning remains in the list of code inspections and I'm given a chance to again ignore the warning.  Doing this misplaces another annotation, on the same line as the original, and looks like this:

```
'@Ignore ProcedureNotUsed
Sub MySub()

'@Ignore NonReturningFunction'@Ignore NonReturningFunction
End Sub
Function TestNonReturningFunction() As Variant
End Function
```

I'm running RD v2.1.0.

**Comment by retailcoder** [comment]
ref. #3373

**Comment by retailcoder** [comment]
This is a dupe. The bug is in the `IgnoreQuickFix` implementation, it doesn't matter what inspection is being ignored.

**Comment by CHR-IS-B** [comment]
Got it.  Missed that when I looked for related issues.

**Comment by retailcoder** [comment]
FWIW I'm treating this bug as top-priority; this quickfix is affecting every single inspection right now, it *must* work correctly.
