### ISSUE TITLE
CreateBranchView should validate the branch name

### ISSUE THREAD

**Issue by ckuhn203** [rubberduck-vba/Rubberduck#348]
Give feedback to the user as soon as possible.
Disable the "OK" button and warn the user about invalid branch names.

[Valid/Invalid branch names](https://www.kernel.org/pub/software/scm/git/docs/git-check-ref-format.html).
Also, on [SO](http://stackoverflow.com/questions/3651860/which-characters-are-illegal-within-a-branch-name).

May or may not happen for the first version of the integration.

**Comment by Hosch250** [comment]
Closed by commit 0d3d1b8bbb98eb8e95eef500c8bf8af4375ac79d
