### ISSUE TITLE
Failed to clone remote repository: Request failed with status code 403

### ISSUE THREAD

**Issue by avalyn2** [rubberduck-vba/Rubberduck#3481]
With the email/password I use to access to GitHub I always get the mentioned error. Is there a pre-step I am missing? The reason why I want to use Rubberduck is mostly for the GitHub integration (as there are some large VBA projects we have and versioning control is needed)

Thanks!

**Comment by retailcoder** [comment]
@mansellan can you assist? IIRC it's something stupid about the way the settings ends up in the source control settings file...

@davidsanchezvasquez can you verify the `%appdata%\rubberduck\sourcecontrol.rubberduck` file, and see if the `<UserName>` and `<EmailAddress` tags contain your information? If not, edit the file manually, save, and let us know if that fixed it. Thanks!

**Comment by mansellan** [comment]
@retailcoder Sure, happy to help.

@davidsanchezvasquez If @retailcoder's suggestion doesn't solve the issue, could you please set RD logs to debug, repro the issue and post the log here.

**Comment by rubberduck203** [comment]
Please see #3758
