### ISSUE TITLE
Moved Code inspector and Test explorer off screen and can't get them back

### ISSUE THREAD

**Issue by BitSprocket** [rubberduck-vba/Rubberduck#3484]
I tried moving them to a virtual desktop on my surface pro 4 using the alt-space arrow keys which didn't work and now I can't get them back.  Tried uninstalling and reinstalling - no joy.  Please help!

**Comment by ThunderFrame** [comment]
It seems that VBA has remembered the location of your docked windows. the only way to fix this is to wipe the `HKEY_CURRENT_USER\Software\Microsoft\VBA\7.1\Common\Dock` value in your registry.  VBE will then reset *all* of your VBE windows to their default position.

Be sure to close all VBA host applications before deleting the contents of `HKEY_CURRENT_USER\Software\Microsoft\VBA\7.1\Common\Dock`

**Comment by BitSprocket** [comment]
That did the trick.  Thanks @ThunderFrame
