### ISSUE TITLE
Duration of tool tips shown is too short if text contains more words

### ISSUE THREAD

**Issue by Imh0t3b** [rubberduck-vba/Rubberduck#3487]
E.g. in Settings -> Code Inspection Settings -> Late Bound WorksheetFunction Call the tool tip is hard to read as it disappears far to soon. Duration should be infinite or depend on text length (x-times word count?).

Additional I made some translations (German) with the TranslationHelper, but I have no Visual Studio installed to fork. How should I contribute my translations?

Rubberduck Version 2.1.0.2382

**Comment by Vogel612** [comment]
Re the translations: You don't need Visual Studio to fork. I can see you already do have a fork, the next step is creating a "working copy" of your fork. For that, look to the "top" right on https://github.com/Imh0t3b/Rubberduck above the listing of files. There's a green button "clone or download". 

Use that to create a working copy (read up about git if you have problems in this step).

Then put your changes into that working copy, commit and push them to your fork and open a PR. Do note that there's currently some translation changes pending (#3479).

Last but not least: please open separate issues for separate things :wink:.
This helps us keep a good overview of what's done already

**Comment by Imh0t3b** [comment]
Thank you Clements, the wiki starts with the Rubberduck.dll, but this is just for debugging new code. I'll keep your advices in mind and separate the issues. Translation standards, will be an issue too or did I miss a discussion on that (e.g. translate member to "Element" or not)

**Comment by Vogel612** [comment]
Hä? Ich verstehe den zweiten Satz nicht so ganz. Worauf willst du hinaus?

**Comment by Imh0t3b** [comment]
Übersetze ich member als Element oder bleibe ich bei member ohne Übersetzung, z.B. class-member wird zu Klassen-Element oder bleiben wir bei  class-member? Hardware und Software werden wir ja auch nicht übersetzen, 
:smile:.

**Comment by Vogel612** [comment]
Also es gibt sowohl Übersetzungen als "Member" als auch als "Mitglied", aber anscheinend noch keine als "Element" ...

**Comment by Imh0t3b** [comment]
Hab ich von  [Leo](https://dict.leo.org/forum/viewUnsolvedquery.php?idThread=668516&idForum=2&lang=de&lp=ende) gefällt mir besser als Mitglied. Wir gehen aber jetzt ganz schön OT, wäre ein eigenes issue oder?

**Comment by IvenBach** [comment]
I too had wanted to make the tooltips duration longer. A checkbox to enable a inputbox for a time duration? Or right click to have it display the tooltip without a timer?

**Comment by Hosch250** [comment]
It should display as long as the user is hovering over it.

**Comment by IvenBach** [comment]
It displays for 5 seconds, even if the cursor is still hovering. IIRC Mug mentioned this being the default timer.

**Comment by retailcoder** [comment]
It's a 2-seconds, 1-liner fix in the XAML markup.

**Comment by IvenBach** [comment]
Once I get GitHub set up with VS I'll gladly take this one.
