### ISSUE TITLE
Version string should be copy-able from about window

### ISSUE THREAD

**Issue by Imh0t3b** [rubberduck-vba/Rubberduck#3489]
I had to write my current version by hand instead of just copying it from the about window.

Rubberduck Version 2.1.0.2382

**Comment by retailcoder** [comment]
Let's make Ctrl+C on the about box put the version string into the clipboard, and make the version label display a little dropdown menu on click, with "Copy to clipboard" as the sole item.

**Comment by bclothier** [comment]
May I suggest that the copying take in the environment, too? (e.g. Windows, which VBA host application & its version, 32/64 bit)? Those are commonly needed in diagnosis, no?

**Comment by MDoerner** [comment]
@bclothier All this information is also available at the top of the log file.

**Comment by bclothier** [comment]
@MDoerner  I suspected that was the case; I was thinking about when users doesn't have the log available/handy.

**Comment by retailcoder** [comment]
Can't hurt to have it either, but the redundancy of it makes it a not-quite-high-priority issue. Up for grabs!

**Comment by IvenBach** [comment]
I've figured out how to get the version to the clipboard when `Ctrl+C` is pressed.
Trying to figure out the dropdown on click. I'll try some more tomorrow.

**Comment by IvenBach** [comment]
Looked for how to get the Environment, VBA Host, and version bitness but I'm left stumped.

**Comment by MDoerner** [comment]
Have a look at `LogRubberduckStart` in `App`. It simply gets the information from environmental variables.

**Comment by IvenBach** [comment]
@MDoerner Thanks for the direction.
