### ISSUE TITLE
"Rubberduck doesn't see anything yet" - what then?

### ISSUE THREAD

**Issue by mfrankstein** [rubberduck-vba/Rubberduck#3490]
![image](https://user-images.githubusercontent.com/32966611/31837174-d39308ce-b5a5-11e7-9063-2697ace37168.png)
Product installation failed.

**Comment by IvenBach** [comment]
If you can seed the Code Explorer then RD didn't fail to install. You need to have it parse. Try clicking the `Refresh` button that's in blue and underlined.

**Comment by retailcoder** [comment]
Also see https://stackoverflow.com/a/41601886/1188513
