### ISSUE TITLE
Click Fix did not fix

### ISSUE THREAD

**Issue by SystemsModelling** [rubberduck-vba/Rubberduck#3494]
2.1.1.2409 is nice!  Fast.

Now a few odds and ends from a first run:

Hint: Replace function `Left` with existing typed function - (XLTest163a.xlsm) XLTest.Functions, line 374

Click Fix did not fix

**Comment by retailcoder** [comment]
I think the 2.1 prereleases aren't wiring up all inspections, and none of the quickfixes - noticed while working on the *missing annotation/attribute* inspections in my fork after synchronizing with the main repository. I have a fix in my fork's [attributes[ branch, but I'm not ready to PR it just yet.

**Comment by Vogel612** [comment]
Fixed since ... somewhen ...
