### ISSUE TITLE
'Queries' not found on the compile-time interface for type 'Workbook'. - 

### ISSUE THREAD

**Issue by SystemsModelling** [rubberduck-vba/Rubberduck#3497]
Warning: Member 'Queries' was not found on the compile-time interface for type 'Workbook'. - (XLTest163a.xlsm) XLTest.Documenter, line 515
wbCheck.Queries ' Excel 2016

**Comment by retailcoder** [comment]
I think the PIA we're using is that of Office 2010 or 2013; any new members would indeed not be showing up. I think the PIAs can be updated without issues; the inspection itself seems to work as intended.

**Comment by retailcoder** [comment]
Hmm actually this has nothing to do with the PIAs we're using.. The typelib loader is not seeing a `Queries` member on the `Workbook` interface. Is the member late-bound? If so, then the inspection result is correct, and can be ignored, or acknowledged and the code modified to use an early-bound equivalent instead.

**Comment by retailcoder** [comment]
If the member does not show up on *IntelliSense* for an `Excel.Workbook` object, then it's a late-bound member; the COM interface is extensible, and the member is added to the type at run-time.

Consider:

````
    row = Application.Match(value, source, 0)
````

The `Excel.Application` interface doesn't define a `Match` member; you don't get *IntelliSense* for it, and the extensible interface flag means whatever you put after that dot will happily compile, as long as it looks like a legit member call.

This inspection is there to remind you that there is no compile-time check on that member call.

If there is an early-bound equivalent, consider using it instead; in the above example, it means:

````
    row = Application.WorksheetFunction.Match(value, source, 0)
````

If no early-bound equivalent exists, then the inspection result is just a reminder that there's no compile-time validation on that instruction.

The inspection's default severity level should probably be `CodeInspectionSeverity.Hint`.

**Comment by SystemsModelling** [comment]
Thanks for that explanation, retailcoder. The Object Browser tells me that Queries is a read-only property of the workbook object.  .Queries _Default(NameOrIndex As WorkbookQuery) You're saying it's actually implemented as a late bound method.

**Comment by retailcoder** [comment]
Hard to tell actually - I don't have Excel 2016 to see it with my own eyes; it's possible that the member is early-bound but defined in another interface that we're somehow not picking up (see #3496). The best way to know for sure is with IntelliSense - if the VBE isn't seeing it at compile-time, we probably can't see it either. Some investigation is needed here, but if the EXCEL.EXE library we're loading is the EXCEL.EXE that's referenced by the project (Office installation mishaps may confuse the loader that gets an older version), then it looks like it's another interface; late-bound members don't show up in the Object Browser.

**Comment by retailcoder** [comment]
https://msdn.microsoft.com/library/dce102a3-25de-3ff4-2ce5-bc56e08baca7%28office.15%29.aspx

Hmm, not seeing a `Queries` property here. If Object Browser is seeing it then we're looking at essentially the same difficulty as the linked issue.

**Comment by SystemsModelling** [comment]
https://msdn.microsoft.com/en-us/vba/excel-vba/articles/queries-object-excel?f=255&MSPPError=-2147217396

**Comment by retailcoder** [comment]
I don't doubt the class exists in Excel 2016's object model. What I'm trying to find out is whether the `Workbook` interface is exposing it, and it seems it doesn't. If MS didn't modify the Workbook interface and isn't adding the type at run-time, then they have to have added a new interface and made the Workbook class implement it - our bug is that we don't seem to be seeing that interface; it's like MSForms.TextBox, we see it through MSForms.Control, and somehow MSForms.TextBox is nowhere: I bet MS put the new interface in the same dark corner of the Excel type library.
