### ISSUE TITLE
Set obj = nothing seems to raise incorrect inspection

### ISSUE THREAD

**Issue by SystemsModelling** [rubberduck-vba/Rubberduck#3498]
Suggestion: Object variable 'wb' is assigned without the 'Set' keyword - (XLTest163a.xlsm) XLTest.BatchProcs, line 925

    Set wb = Nothing

Suggestion: Object variable 'wsDoc' is assigned without the 'Set' keyword - (XLTest163a.xlsm) XLTest.Colorizer, line 398

    Set wsDoc = Nothing 

Suggestion: Object variable 'vLeft' is assigned without the 'Set' keyword - (XLTest163a.xlsm) XLTest.WBComparer, line 203

``` 
Function VarDifferent(ByRef vLeft As Variant, ByRef vRight As Variant) As Boolean
vLeft = "(" & TypeName(vLeft) & ")" & CStr(vLeft)
```

**Comment by retailcoder** [comment]
Hmm, that's two bugs. One is the result of a recent tweak to that inspection that makes it ignore assignments to `Nothing` ...but then it shouldn't fire if *the only assignment* is to `Nothing` (assuming `Set` is present).
The `ByRef/Variant` assignment shouldn't trigger the inspection at all though.

**Comment by SystemsModelling** [comment]
"The ByRef/Variant assignment shouldn't trigger the inspection at all though." Just to clarify: the inspection is not on that Function VarDifferent line, I just provided that to give the context. It's on the line vLeft = "...

Sorry, I'd better post issues one at a time and give the inspection with the line rather than as an introductory paragraph.

**Comment by MDoerner** [comment]
Still, the inspection should not trigger since `vLeft` is a `Variant`.

**Comment by comintern** [comment]
Both identified issues appear to have been fixed:

![screenshot from 2018-07-16 20-04-59](https://user-images.githubusercontent.com/8944005/42791043-b7478228-8933-11e8-90d3-1260bee58a17.png)
