### ISSUE TITLE
Refactor | Rename in class module leads to loss of member attributes

### ISSUE THREAD

**Issue by Inarion** [rubberduck-vba/Rubberduck#3505]
Given the class

    VERSION 1.0 CLASS
    BEGIN   
    MultiUse = -1  'True
    END
    Attribute VB_Name = "Foo"
    Attribute VB_GlobalNameSpace = False
    Attribute VB_Creatable = False
    Attribute VB_PredeclaredId = False
    Attribute VB_Exposed = False
    Option Explicit
    
    Private col As Collection
    
    Private Sub Class_Initialize()
        Set col = New Collection
    End Sub
    
    Private Sub Class_Terminate()
        Set col = Nothing
    End Sub
    
    Public Function item(ByVal index As Variant) As Object
    Attribute item.VB_UserMemId = 0
        'Attribute Value.VB_UserMemId = 0
        ' (enables item as default member)
        Set item = col(index)
    End Function
    
    Public Function NewEnum() As IUnknown
    Attribute NewEnum.VB_UserMemId = -4
        ' to enable 'for each' for this class
        'Attribute NewEnum.VB_UserMemId = -4
        Set NewEnum = col.[_NewEnum]
    End Function

when renaming `col` to e.g. `coll` via RD's Refactor|Rename the attributes of both functions (`item` and `NewEnum`) get lost.

I'm currently on version 2.1.0 - although I'm not sure everything installed properly as I only upgraded the installation files (due to lack of privileges I couldn't do a proper reinstall). So I'm not entirely sure the fault is on RD's or my side. If it's not reproducible for you guys, I'll take the issue to our IT department to get a fresh 2.1.0 installation.

**Comment by MDoerner** [comment]
This might be an unintended consequence of how we rewrite the modules. In that case, it will happen for all refactorings.

We will try to reproduce and investigate further if we can.

**Comment by retailcoder** [comment]
Should be easier to fix once the annotation/attributes fix is up.

**Comment by retailcoder** [comment]
Note that the VBE itself tends to drop attributes given a signature change.

**Comment by MDoerner** [comment]
Can you check whether this still a problem? This should have been fixed with PR #4686. Only the attributes for renamed members should get lost now.

**Comment by Inarion** [comment]
Hm, I seemed to have a case where the attributes got lost, but I can't reproduce it right now.  
At the moment it seems to consistently keep the attributes on rewriting the module - regardless of whether the corresponding annotations had been set.

The inspections regarding missing/mismatching attribute annotations don't seem to fire in any way, but that's for another issue.
