### ISSUE TITLE
Possible to select which tests to run manually?

### ISSUE THREAD

**Issue by BitSprocket** [rubberduck-vba/Rubberduck#3507]
I have occasion to want to selectively run tests without running the whole batch.  Any way to tell RD which tests to run selectively?  Even a hack would do.  I don't want to comment out all the tests that I don't want to run if at all possible.

**Comment by retailcoder** [comment]
Hmm, this can be considered a regression from ....v1.4.3, which (IIRC) *did* have a "run selected tests" command, and allowed multiple selections (again, IIRC - it's been a while!).

Until that's [re-]implemented, the "best" option is to use `'@IgnoreTest` annotations on the tests you don't want to run... which pretty much amounts to commenting them out.

This needs to be implemented for 2.1.1.

**Comment by BitSprocket** [comment]
Okay, thank you!
