### ISSUE TITLE
Set default branch to staging?

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#3515]
We have no open pull requests (as of this writing)... and we all have our remotes and upstreams pointing to [next]. I got #3511 to build on AppVeyor by creating a [staging](https://github.com/rubberduck-vba/Rubberduck/tree/staging) branch, and then opening a PR into it - and then opening another PR from [staging] into [next].

I think a [staging] branch could be useful - we would have much better control over what goes into "pre-release" builds on [next].

Thoughts? Should we make [staging] the repository's default branch?

**Comment by Vogel612** [comment]
Thoughts as bulletpoints:

- Seems to only add another layer of indirection. 
- Would help reduce the amount of prereleases
- Makes for a weird process in some way, though.

**Comment by retailcoder** [comment]
How is it weird, can you expand? I'm not very familiar with what's a "common" or "robust" CI configuration.. Is there a better way to, say, push a weekly prerelease build, as opposed to systematically prereleasing every single PR that gets merged into [next]?

**Comment by Vogel612** [comment]
Scheduled job. If you don't want to release every single build, that doesn't imply creating a new branch.

**Comment by Hosch250** [comment]
Wouldn't make that big of a difference; worst case we have to checkout a few different commits to find the bad one.

**Comment by MDoerner** [comment]
@bclothier I am a bit confused now. As far as I understand it, the idea of the staging branch was to conglomerate PRs in the first place.

Personally, I prefer scheduled prereleases. Alternatively, we could have a new prereleases branch to which we open a PR from next whenever we want a prerelease. I would rather like next to keep being the development branch as it always has been.

**Comment by bclothier** [comment]
@MDoerner the comments was in response to @Vogel612's point that we don't necessarily need a staging branch to consolidate the PRs; a scheduled job would be sufficient.
