### ISSUE TITLE
Give User feedback about state of merge

### ISSUE THREAD

**Issue by ckuhn203** [rubberduck-vba/Rubberduck#352]
Right now, if a merge succeeds, the Merge View simply closes.
Some feedback should be provided that the merge did indeed successfully complete.

Also, while taking care of this, remove the dependency on System.Forms.MessageBox in the presenter for reporting errors. Use the Merge View itself to report errors back. The presenter should have no references to the `System.Forms` namespace.

**Comment by ckuhn203** [comment]
Test setup for the error condition will look something like this. 

    var provider = new Mock<ISourceControlProvider>();
    provider.Setup(git => git.Merge(It.IsAny<string>(), It.IsAny<string>()))
                 .Throws(new SourceControlException("message", new LibGit2Exception("inner message"));

    //Assert State of Merge View

**Comment by Hosch250** [comment]
@retailcoder Can you verify that this is fixed?
