### ISSUE TITLE
Source Control Bug

### ISSUE THREAD

**Issue by Hosch250** [rubberduck-vba/Rubberduck#3526]
Reference: https://github.com/rubberduck-vba/RubberduckWeb/issues/48

**Comment by Vogel612** [comment]
There is absolutely nothing of use in the logs....

**Comment by CKlijs** [comment]
What do you need me to do to persue this further

**Comment by Vogel612** [comment]
Reproduce the issue and be more precise about the problems you're seeing. 
As it stands the description is too unclear to try to pin down the issue :wink: 

Just reformulate the details of the issue here and include every detail. Thanks
