### ISSUE TITLE
cannot use source control

### ISSUE THREAD

**Issue by CKlijs** [rubberduck-vba/Rubberduck#3531]
After activation of source control in settings my changes do not appear in the changelist of the source control screen.
i get an error message see the log file:
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/1436797/RubberduckLog.txt)

**Comment by Vogel612** [comment]
@CKlijs the log does not suggest any error messages. Which error message did you get? and why does this logfile not include the full logfile, but only the shutdown process?

**Comment by retailcoder** [comment]
Activating the source control integration feature doesn't automatically create a repository. You can find a "getting started" guide [in the wiki](https://github.com/rubberduck-vba/Rubberduck/wiki/Source-Control:-Getting-Started).

**Comment by rubberduck203** [comment]
Please see #3758.
