### ISSUE TITLE
Rubberduck: not available in VBE, but loaded in Add-In-Manager

### ISSUE THREAD

**Issue by MI285** [rubberduck-vba/Rubberduck#3538]
After Admin-Installing Rubberduck 2.1.0 or also tried with 2.1.1.2450-pre I cannot see the Add-in as menu-item or context-menu-item.

But everything expected is there (in Excel, Word, Powerpoint)
the SplashScreen at start, the item in Add-in-Manager, the keys in registry.
but no menu of Rubberduck.

my System: Win7 64 Pro (german), Office 2010 32bit (german).

when installing 2.0.13, during splash screen there comes this ans exception, but still no log file. But in VBE the Rubberduck menu item is available now.

for Screenshots and more diagnosis see: https://stackoverflow.com/questions/47156299/rubberduck-not-available-in-vbe-but-loaded-in-add-in-manager

**Comment by bclothier** [comment]
Closing this for three reasons:

1) age of the issue
2) we introduced a change to startup process in 2.2
3) we now have trace logging enabled at fresh installation ( ref #4447 )
