### ISSUE TITLE
Parameter 'item' is never used, but it is - different to #3499 

### ISSUE THREAD

**Issue by Stevefb** [rubberduck-vba/Rubberduck#3551]
Came across this interesting bit of code just now:

Sub and Parameter share the same name, this trips up Rubberduck's code inspection in that parameter `foo` is reported as "never used".  

Renaming the Sub removes the inspection result from the list.  

```
Option Explicit

Public Sub foo(ByVal foo As Bookmarks)
    Dim bar As Bookmark
    For Each bar In foo
        Debug.Print bar.Name
    Next
End Sub
```

Probably an edge case but might be worth inspecting for such silliness? 

Note: Issue #3499 seemed to be heading down a different path with different cause, let me know if I should have appended instead.

**Comment by retailcoder** [comment]
It *is* the same cause /bug /edge case. Worth noting that this confuses the VBE as well, not just RD.
