### ISSUE TITLE
Add or Remove Module only reparses for adding Unit Tests

### ISSUE THREAD

**Issue by IvenBach** [rubberduck-vba/Rubberduck#3560]
Adding a Test Module, with or without stubs, invokes a reparse. Adding any StandardModule, ClassModule, or Userform doesn't. Deleting a TestModule, StandardModule, ClassModule or Userform doesn't invoke a parse. 

```
Rubberduck version: Version 2.1.1.2478
Operating System: Microsoft Windows NT 6.1.7601 Service Pack 1, x64
Host Product: Microsoft Office 2013 x86
Host Version: 15.0.4971.1000
Host Executable: EXCEL.EXE
```

**Comment by IvenBach** [comment]
Rubberduck version: 2.1.6535.41637 doesn't have this error. All adds and deletions invoked a reparse.

**Comment by retailcoder** [comment]
Fixed without a referencing commit then?

**Comment by IvenBach** [comment]
Tried with work computer and latest pre-release, and it's not getting a parse.
```
Rubberduck version: Version 2.1.1.2502
Operating System: Microsoft Windows NT 6.1.7601 Service Pack 1, x64
Host Product: Microsoft Office 2013 x86
Host Version: 15.0.4971.1000
Host Executable: EXCEL.EXE
```

The clean version was on my home computer.

**Comment by comintern** [comment]
I can't replicate this. Is this still an issue?
