### ISSUE TITLE
Implicit Reference to ActiveSheet False Positives in Worksheet module

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#3569]
In a worksheet module, the use of `Range` is not implicitly referencing the ActiveSheet, it is referring to the sheet module within which it is used.

This is valid code, but the inspection fires nonetheless (although there doesn't seem to be a quickfix available, so I haven't tested what happens if a fix is applied):

```vb
Sub ComboBox1_Change()
    Range("price_zero").Copy Destination:=Range("price_on_view")
End Sub
```

Even so, my preference would be to be more explicit, by using `Me.`

```vb
Sub ComboBox1_Change()
    Me.Range("price_zero").Copy Destination:=Me.Range("price_on_view")
End Sub
```

**Comment by retailcoder** [comment]
Gah, I meant to fix that a long time ago... Simply ignore document modules for that inspection.

**Comment by retailcoder** [comment]
If we want the `Me` fix, we'll need a separate inspection for it (e.g. "Implicit reference to current instance" or something).. I'd only fire it in document modules though.

**Comment by ThunderFrame** [comment]
Except we can't ignore document modules... `Range` in a `Workbook` module is still a reference to `ActiveSheet`.

**Comment by retailcoder** [comment]
I believe with Wayne's work we are now in a position to fix this bug *correctly*.

**Comment by daFreeMan** [comment]
Also getting it here:

```VBA
  Dim sourceXL As Excel.Workbook
  newSheet.Application.DisplayAlerts = False
  Set sourceXL = XLobj.Workbooks.Open(fileName:=excelFileName, ReadOnly:=True)
  newSheet.Application.DisplayAlerts = True

  sourceXL.Sheets(sourceSheetName).Range(rangeName).Copy
```
