### ISSUE TITLE
Running a parse on a newly loaded project changes module selection

### ISSUE THREAD

**Issue by bclothier** [rubberduck-vba/Rubberduck#3576]
VBA editor traditionally remembers the last code pane that was open. However when I run parse for the first time, the code pane changes to another module for apparently no reason. Simply parsing shouldn't cause the z-order of windows to change.

**Comment by Vogel612** [comment]
Not sure whether to classify this as a bug or an enhancement. IIUC we're just exporting modules to parse them in the order they are exposed by the VBE: The last open module we touch apparently gets the highest z-index. 

We'd need to find out the z-indices of open modules and adjust the parsing process accordingly.

This will become obsolete as soon as avalon-edit comes into this. I'd prefer to keep the parsing process as simple as possible, especially given that this will "solve itself" with the direction of the project...

**Comment by bclothier** [comment]
Just as a FYI - this behavior occurs only once, at the first parse after the startup. Subsequent parsing do not change the z-order of the windows. In case this makes it simpler, we don't need all the z-order; simply retaining the last window would suffice in my case (since I rarely use windows-in-a-window; all are maximized and I use other ways to change windows) as I don't even care about the original z-ordering. 

If the avalon enhancement is more immediate, I'm happy to close that in favor of the avalon enhancement.

**Comment by bclothier** [comment]
Closing this as stale since this apparently no longer occurs in current build.
