### ISSUE TITLE
UnitTest I can't make a test to fail

### ISSUE THREAD

**Issue by JRProjectCustom** [rubberduck-vba/Rubberduck#3578]
Hi, 

Rubberduck Version 2.1.1.2511
Visio Professional 2013

I created a new TestModule and inserted a new TestMethod. 

I simply put Assert.Fail or Assert.IsTrue(False), the test succeed when I run it. 

When I go to RubberduckLog it says : 2017-11-28 11:34:47.0965;INFO-2.1.1.2511;Rubberduck.UI.UnitTesting.TestExplorerViewModel;Test run completed in 9.;

I've tried both early binding and late binding with no effect. 

What am I missing? Thanks.

```
Option Explicit
Option Private Module

'@TestModule
'@Folder("Tests")

Private Assert As Object
Private Fakes As Object

'@ModuleInitialize
Public Sub ModuleInitialize()
    'this method runs once per module.
    Set Assert = CreateObject("Rubberduck.AssertClass")
    Set Fakes = CreateObject("Rubberduck.FakesProvider")
End Sub

'@ModuleCleanup
Public Sub ModuleCleanup()
    'this method runs once per module.
    Set Assert = Nothing
    Set Fakes = Nothing
End Sub

'@TestInitialize
Public Sub TestInitialize()
    'this method runs before every test in the module.
End Sub

'@TestCleanup
Public Sub TestCleanup()
    'this method runs after every test in the module.
End Sub

'@TestMethod
Public Sub TestMethod1() 'TODO Rename test
    On Error GoTo TestFail
    
    'Arrange:

    'Act:

    'Assert:
    Assert.Fail

TestExit:
    Exit Sub
TestFail:
    Assert.Fail "Test raised an error: #" & Err.Number & " - " & Err.Description
End Sub



```

**Comment by comintern** [comment]
I can't replicate this in the current build, although it was tested in Excel and not Visio. Closing as stale. If this is still an issue in Visio, it can be re-opened as a host specific issue.

**Comment by bclothier** [comment]
FWIW, tested in Visio 2010 and it failed as expected.
