### ISSUE TITLE
Inspection for Object Type mismatch in compilable & runnable code

### ISSUE THREAD

**Issue by bclothier** [rubberduck-vba/Rubberduck#3580]
Given this silly code:
```
Public Sub durr()
    Dim x As DAO.Recordset
    
    doh x
End Sub

Public Sub doh(x As Access.Form)
    Debug.Print x Is Nothing
End Sub
```
This not only compiles but also run without any error, yet it is obvious nonsense. That is due to VBA not having a clue what `Nothing` is; and can't begin to inspect the metadata until the variable has been instantiated.

The inspection should warn against such obviously wrong assignment where the input's type cannot possibly be cast to the parameter's expected type. Note that several objects may implement multiple interfaces so there may be several legal casts. In any case, when it's obvious that it cannot be cast, the inspection should fire to alert that there is potential runtime error that would be hard to catch.

Note there is an issue #2103 already for inspecting whether a function will not return `Nothing`. However, this deals with guaranteeing that function won't return a `Nothing` but may not deal with cases where the function receive `Nothing` as a parameter or a wrong variable is assigned to its argument.

**Comment by retailcoder** [comment]
Idea: a `@DirectCast` annotation as a surrogate to `@Ignore ImplicitObjectTypeCast`
