### ISSUE TITLE
Components dialog instead of Find Symbol is brought up with hotkey

### ISSUE THREAD

**Issue by IvenBach** [rubberduck-vba/Rubberduck#3592]
The components dialog seen below comes up any time I use the `Find Symbol` hotkey for the first time. Thereafter `Find Symbol` is displayed.  ![image](https://user-images.githubusercontent.com/26076874/33626640-094dce30-d9b0-11e7-979a-0e7fbdc0b734.png)

Rubberduck version: Version 2.1.1.2502
Operating System: Microsoft Windows NT 6.1.7601 Service Pack 1, x64
Host Product: Microsoft Office 2013 x86
Host Version: 15.0.4971.1000
Host Executable: EXCEL.EXE

I need to close Excel down completely and start a new instance to have the Components show again.

**Comment by retailcoder** [comment]
I repro this with Ctrl+R. Sometimes the hotkey doesn't seem to he wired up. Activating the code pane fixes it though. I think the fix would be to explicitly activate a code pane on startup... after making sure there's one to activate (IIRC hotkeys wire up when a code pane is activated).

**Comment by comintern** [comment]
Ref #4080

**Comment by retailcoder** [comment]
Possibly fixed with the merging of #4240. Let's reopen this issue if the problem persists.
