### ISSUE TITLE
Assignment without `Set` false positive and duplicate results

### ISSUE THREAD

**Issue by bclothier** [rubberduck-vba/Rubberduck#3598]
Given this code:

```
Private Function IDbConnection_CurrentConnection() As Object
    Set IDbConnection_CurrentConnection = Nothing
End Function
````

Code Explorer shows 4 inspections `Object variable 'IDbConnection_CurrentConnection' is assigned without the Set keyword`. Clicking each inspection result highlights exactly the same line so I think the 3 are duplicates of the false positive. I think the fact that `Nothing` is being assigned is somehow tripping up the inspection, maybe?

Note: the code above is intended to NOT support the object. In hindsight, I should have done a `Err.Raise "Not implemented"` for that line.

**Comment by retailcoder** [comment]
Because the only assignment in scope is to `Nothing`, your ducky is warning you about possible runtime error 91 here (or originating here anyway). The wording isn't exactly ideal, but the inspection result is intended.

**Comment by bclothier** [comment]
Yeah, and that was a good thing because as I said, I probably really should be throwing a NotImplemented error there. Besides the wording, what about the 3 duplicates, though? That can't be right.

**Comment by comintern** [comment]
This appears to have already been fixed:

![screenshot from 2018-07-16 19-52-23](https://user-images.githubusercontent.com/8944005/42790678-015ca732-8932-11e8-8db8-9a08b255da18.png)
