### ISSUE TITLE
Refactor Extract Method Should Tell Why it Fails

### ISSUE THREAD

**Issue by BriargateExcel** [rubberduck-vba/Rubberduck#3605]
Sometimes when I select a block of code and then try to "Refactor Extract Method" it does nothing. I assume this is because it can't refactor my selected block for some reason. It would be helpful if Rubberduck told me why it couldn't refactor that block of code.

**Comment by retailcoder** [comment]
What version are you using? Extract Method was originally shipped in v1.2, removed in v2.x, and is currently being re-rewritten (it's... a *complicated* one :wink:) - long story short, I don't expect the current WIP implementation to have released.. or did you build your own ducky from the source code?

**Comment by BriargateExcel** [comment]
I'm using Rubberduck 2.1.1.2532

**Comment by bclothier** [comment]
@BriargateExcel  we are surprised here because the method is not supposed to be enabled at all.

Were you using right-click menu or hotkeys?

**Comment by BriargateExcel** [comment]
I'm using Hotkeys: Ctl+Shft+M

From the ribbon: Rubberduck -> Refactor does not list Extract Method as an option

From a Right-Click on the selected block of code: Rubberduck -> Refactor does not list Extract Method as an option

**Comment by bclothier** [comment]
Aha, thus lie the rub.

We meant to disable this since some version ago (I want to say 1.4 but I'm not 100% sure when) becuase there were numerous problems with the existing implementations.

But we did not account for hotkeys still working. We will disable it until the WIP is ready. You can see the progress [here](https://github.com/rubberduck-vba/Rubberduck/projects/2). Currently it shows all items in `TODO` but that's because they are all being worked on collectively.

**Comment by retailcoder** [comment]
Right... that's the borked version without a UI (@bclothier not sure what version it shipped in, IIRC 1.4.3 still had my original implementation)... the code wasn't deleted for reference, but we removed the menu items - looks like the command's hotkey somehow remained in there...

Well, *Extract Method* is bring rewritten from scratch anyway :smile: 

The result will be much more user-friendly (will show a preview, and will let you decide what happens to the possible inputs/outputs)... and less bugged-up.

**Comment by BriargateExcel** [comment]
I look forward to a well-oiled version of Extract Method. It's a tremendously useful capability for refactoring.

P.S. I'm in awe of the responsiveness of the Rubberduck staff! Multiple exchanges with two different staff members in 24 minutes - impressive!

**Comment by Hosch250** [comment]
Hi.

**Comment by Hosch250** [comment]
We get notified in our warroom: https://chat.stackexchange.com/rooms/14929/vba-rubberducking. Feel free to join.

**Comment by retailcoder** [comment]
<s>we're cheating</s> we have a chatbot :smiley: 

![image](https://user-images.githubusercontent.com/5751684/33911243-be42a464-df5f-11e7-9bf4-91015f1e3e86.png)

**Comment by IvenBach** [comment]
We eagerly sit around waiting for requests and hope you'd join us at the pond linked above.

**Comment by Vogel612** [comment]
"staff members"??
