### ISSUE TITLE
Issue with menu layout?

### ISSUE THREAD

**Issue by bclothier** [rubberduck-vba/Rubberduck#3611]
I noticed this and I do not know who's at fault. This is to find out what is really happening.

For a given VBE installation with few addins install, including OASIS-SVN, we have this:
![image](https://user-images.githubusercontent.com/2367644/33941311-d2f3c000-dfd7-11e7-8239-e27bb2d65141.png)

Now if we load Rubberduck, the OASIS menu get moved over:
![image](https://user-images.githubusercontent.com/2367644/33941326-dc652bf6-dfd7-11e7-966b-3fdc940e0e11.png)

Why would it be so? Who's doing it wrong?

**Comment by retailcoder** [comment]
OASIS-SVN is doing it wrong. Are they OSS?

**Comment by bclothier** [comment]
No, but I already emailed them.
