### ISSUE TITLE
Refactoring: Remove all prompts from a method and pass a model

### ISSUE THREAD

**Issue by bclothier** [rubberduck-vba/Rubberduck#3617]
Given this awful code:

```
Public Sub Derp()
  If vbYes = MsgBox("Do you want to do A or B?", vbYesNo) Then
    ... = InputBox("Please give me the name of file") 
    ...
  Else
      ... = Inputbox("Please give me the name of file")
      If vbYes = Msgbox("The file already exists. Overwrite?", vbYesNo) Then
       ...
     End If
   End If
End Sub
```

The refactoring once applied should do something like this....

```
Public Sub Derp(Data As DerpModel)
  If vbYes = Data.ActionChoice Then
    ... = Data.FileName 
    ...
  Else
      ... = Data.FileName
      If vbYes = Data.Overwrite Then
       ...
     End If
   End If
End Sub
```

The idea being to provide a safe way to refactor the code and remove all interactive logic into just *data* that can be passed into the method. The refactoring might have an option to preserve the old way (yuck!) by doing this:

```
Public Sub CollectInputsForDerp
  Dim Data As DerpModel
  Data.ActionChoice = (MsgBox("Do you want to do A or B?", vbYesNo) = vbYes)
  Data.FileName = Inputbox("Please give me the name of file")
  Data.Overwrite = (Msgbox("The file already exists. Overwrite?", vbYesNo) = vbYes)
  Derp

End Sub
```

Then we can nudge users toward correct design by using a userform to collect the inputs upfront and report on progress.

**Comment by retailcoder** [comment]
Arguably a path/filename prompt should be implemented with a much safer `Application.GetOpenFileName` (or some `FileDialog`) that taps into the host application's API, rather than through a poorly validated `InputBox`. IMO the presence of an `InputBox` call is in itself a reason to refactor, ...but I'm drifting.

Where and how do we draw the line though? Sure `VBA.MsgBox` and `VBA.InputBox` are easy to pull out, but do we really want to hunt down host API methods that prompt for user input? Do we pull `Excel.Application.InputBox`?

I think this is a nice idea, but could easily be a huge can of worms.

**Comment by bclothier** [comment]
If it were going to be implemented, it'd have to be interactive, with its dialog for users to work on. Thinking about it more - the hypothetical `DerpModel` would be insufficient if there were other parameters in the code that are used with the parameters from an interaction. For it to to work in general cases, it'd probably need all variables. But if we're now extracting all local variables, we're basically building a new class. 

Hmm. I wonder if that's what we really want? Create a class from a ugly method and transform all interactions into a method call?

**Comment by retailcoder** [comment]
IOW promote a bunch of locals to fields, encapsulate these fields / expose them as properties, and then extract these members to a new class. We already have all these tools (right?), it's just a matter of knowing when & how to use them :wink:

**Comment by bclothier** [comment]
IOWx2, we need to help document how an user can refactor a ugly method in several steps. So that they can see how they can use multiple refactoring together to get from ugly codebase to less-uglier codebase. That might be more practical.

**Comment by IvenBach** [comment]
I've been working on this in my own coding. Let me know once this documentation has been written.
