### ISSUE TITLE
Keep Code Explorer permanently docked

### ISSUE THREAD

**Issue by Greedquest** [rubberduck-vba/Rubberduck#3625]
I've recently discovered the code explorer that Rubberduck provides; looks great. I'd like to replace the default explorer with it permanently, but every time I close and reopen Excel, the Code Explorer window loses its docking (so I have to go into the Rubberduck menu to get it back)

Is there a way to keep the window docked, or if not, could this feature be added? Even better might be to have the  Rubberduck Explorer replace the normal explorer after the first parsing.

**Comment by Vogel612** [comment]
Related: https://github.com/rubberduck-vba/Rubberduck/issues/3214
Duplicate: https://github.com/rubberduck-vba/Rubberduck/issues/3215

Long story short: we know. We're working on it :)

**Comment by Vogel612** [comment]
See also #3615 and #3614
