### ISSUE TITLE
Scroll wheel in tests panel

### ISSUE THREAD

**Issue by BitSprocket** [rubberduck-vba/Rubberduck#3646]
It would be very useful to be able to use the mouse scroll wheel to scroll through the tests panel.

**Comment by Vogel612** [comment]
Is this a regression? What version of Rubberduck are you on and did it work in a previous version?

**Comment by BitSprocket** [comment]
I don't know if it's a regression or not - I've never had it work. I'm using the latest release: 

Rubberduck version: Version 2.1.1.2532
Operating System: Microsoft Windows NT 10.0.17046.0, x64
Host Product: Microsoft Office 2016 x64
Host Version: 16.0.8730.2127
Host Executable: MSACCESS.EXE

**Comment by Vogel612** [comment]
Thanks for the info _+1:

**Comment by retailcoder** [comment]
I'm removing the [feature-unit-testing] label, since this needs to be fixed at the `GroupingGrid` level: every single toolwindow that uses a grouping grid needs to support wheel scrolling, not just the *test explorer*.

**Comment by IvenBach** [comment]
I'm learning as I go to solve this.

By coinciduck, terrible pun I know, if you mouse over the vertical scroll bar you get scrolling capability.
