### ISSUE TITLE
Feature: Assert object should have pass/fail return value

### ISSUE THREAD

**Issue by BitSprocket** [rubberduck-vba/Rubberduck#3647]
This would allow for logging a test run (to a text file or some such) with the name of the test and a pass/fail flag instead of returning void.  This would really help with integrating into an issue tracking system or allow devs to trace what's failing and perhaps watch for regressions.

**Comment by Vogel612** [comment]
The test-explorer already supports copying the results of a test-run. It's not really useful to add these  return values when Rubberduck can already export what you're looking for into [XML, html, csv and Rich Text](https://github.com/rubberduck-vba/Rubberduck/blob/next/RetailCoder.VBE/UI/UnitTesting/TestExplorerViewModel.cs#L349)

**Comment by BitSprocket** [comment]
It doesn't work though.

**Comment by Vogel612** [comment]
The solution is to fix the bug, not implement a new feature that works around the bug :)

**Comment by BitSprocket** [comment]
Agreed.  Thanks.

**Comment by BitSprocket** [comment]
I know you closed this ticket and for good reason, but I would like to see if you'd be willing to reconsider giving us programmatic access to a return value on the Assert object.  I am struggling to trace a failure and I think it's because I have interdependent tests so looking at a run log would be very helpful to track it down.  It would also permit devs to run automated scripts against the log.  Having to copy/paste the results is a manual task that should be automate-able.

**Comment by retailcoder** [comment]
I hear you. In the .net world a failing `Assert` throws an exception, so you get a stack trace. We could make them throw a trappable run-time error (on top of the current behavior, i.e. handling the error wouldn't affect the test outcome).. but returning a value and executing conditional logic based on that seems like a wide-open door for abuse IMO. There must be a reason no testing framework implemented asserts that way...

**Comment by BitSprocket** [comment]
Oh, an exception would work beautifully!
