### ISSUE TITLE
RD only listens to the component events of the first project added

### ISSUE THREAD

**Issue by MDoerner** [rubberduck-vba/Rubberduck#3650]
The problem seems to be that the static event handler in `VBComponents` attaches only to the first `VBComponents` collection wrapped. However, the collections are per project. So, a static approach does not seem suitable.

To reproduce:

1. Open a workbook in Excel.
2. Open the VBE and parse.
3. Open another workbook. (This should trigger a parse.)
4. Add a module to the second workbook. (No parse)

**Comment by bclothier** [comment]
I think we should consider whether we should try to follow the example outlined here:

https://msdn.microsoft.com/en-us/library/aa716342(v=vs.60).aspx

Seems me that VBIDE exposes events differently in order to set a filter as part of the assignment.

**Comment by MDoerner** [comment]
I can no longer reproduce this.

I guess this gor fixed with the event rework.
