### ISSUE TITLE
Code Inspections and ToDo Explorer leak MouseWheel events

### ISSUE THREAD

**Issue by comintern** [rubberduck-vba/Rubberduck#367]
If the Microsoft provided MouseWheelFix add-in (http://support.microsoft.com/en-us/kb/837910) is installed, the Code Inspections and ToDo Explorer will scroll simultaneously with the VBE code window when the mouse wheel is used and the Rubberduck window doesn't have focus. This may be an issue with the MouseWheelFix add-in, but the Rubberduck windows should really be eating the event.

Steps to replicate (Office 2010):
- Download and install the MouseWheelFix add-in.
- Click inside the VBE code window.
- Move the mouse cursor over a Code Inspections or ToDo Explorer window with a scroll bar present, but do not click to give the window focus.
- Scroll with the mouse wheel.

**Comment by retailcoder** [comment]
Thanks for the feedback! That's an interesting one, not sure how to "eat" an event there, this is happening at the window handle level, right?

**Comment by retailcoder** [comment]
Note: the scrollwheel fix is specifically for the VB6 IDE

**Comment by ckuhn203** [comment]
@retailcoder we could catch it and eat it in the `NativeWindows` code. There are other hacks in there that make the dockable windows work properly. I'm just wondering how it would work if the add-in isn't installed. We need to verify that any fix doesn't affect users without the add-in.

**Comment by Hosch250** [comment]
I can test this for you if it gets done.

**Comment by retailcoder** [comment]
It will be interesting to see if the 2.0 XAML controls have the same problem.

**Comment by Hosch250** [comment]
Is this still an issue?

**Comment by comintern** [comment]
Forgot about this one - no longer an issue.
