### ISSUE TITLE
Annotations to mark string literals as resolvable identifiers

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#3671]
Consider this code:

    Public Sub DoSomething()
        Const procName As String = "DoSomething"
        On Error GoTo ErrHandler
        '...
    ErrHandler:
        Err.Raise MacroError.DoSomethingFailed, TypeName(Me) & "." & procName, Err.Description
    End Sub

Or this:

    Public Sub DoSomething()
        Dim procName As String
        procName = "DoSomething"

It would be nice to be able to annotate them like this:

        '@IdentifierLiteral
        Const procName As String = "DoSomething"

Or this:

        '@IdentifierLiteral
        procName = "DoSomething"

The annotation could then be used hint the resolver to expect that the next string literal in the next `blockStmt` node contains a string literal that needs to be resolved as an identifier reference (perhaps issue an inspection result for `IllegalAnnotationInspection` otherwise). Further enhancements could possibly even make it able to locate an identifier *within* a string literal, but I wouldn't go that far for a first iteration.

The *rename* refactoring would then be able to modify the string literal to match the new identifier name.

It would also have other implications, notably with inspections looking at identifier references: we would probably still want to fire "procedure not used" if it's only ever referenced in a string literal...

Thoughts? Other implications?

**Comment by Vogel612** [comment]
While I really like the idea, I don't see much of a usecase beyond refactoring these together with renames... 
That again should be an option on the rename refactoring, not a separate thing.

Reflection / dynamic invocation is **always** dangerous. We can try to make it more safe, or we can put our brains behind a feature that gets more use out of the effort we need to put into it...

**Comment by retailcoder** [comment]
@Vogel612 I think you're right: the sole purpose would boil down to allowing *rename* to pick up a string literal and update it as needed... and introducing a new meaning for `IndentifierReference` at this point is a breaking change we don't need to deal with. Let's smarten up the *rename* refactoring instead.
