### ISSUE TITLE
Disable Inspection link doesn't work for Hungarian Notation inspection ;)

### ISSUE THREAD

**Issue by puzzlepiece87** [rubberduck-vba/Rubberduck#3690]
When I click it, nothing happens. Could be due to the "if user = @puzzlepiece87" clause hahaha

**Comment by Vogel612** [comment]
Could you please add the version information for your installation? Thanks

**Comment by comintern** [comment]
This seems to have already been resolved in next - the setting is changed to disabled, and results no longer appear in future inspections.
