### ISSUE TITLE
Member Not On Interface inspection doesn't trigger when member is an object with subsequent member

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#3700]
This code accesses the `FormatConditions` property of the `TextBox` control, but because `FormatConditions` is an object, and one of its members *is* accessed, the *Member Not On Interface* inspection is *not* triggered:

```vb
Dim accessTextBox As Access.Control
Set accessTextBox = Me.Text0
Debug.Print accessTextBox.FormatConditions.Count
```

This code accesses the `FormatConditions` property *without* accessing a subsequent member, and *does* trigger the inspection.

```vb
  Dim accessTextBox As Access.Control
  Set accessTextBox = Me.Text0
  Dim obj As Object
  Set obj = accessTextBox.FormatConditions
```

**Comment by retailcoder** [comment]
Is this still an issue?

**Comment by retailcoder** [comment]
Fixed
