### ISSUE TITLE
Obsolete Error Statement Inspection

### ISSUE THREAD

**Issue by rubberduck203** [rubberduck-vba/Rubberduck#371]
The `Error` statement is obsolete and should be replaced with a call to `Err.Raise` per [the MSDN documentation](https://msdn.microsoft.com/EN-US/library/office/gg264544.aspx).

```
Error 11 ' simulate division by zero error
```
- Severity: Hint
- Quick Fix: Replace Error statement with proper call to `Err.Raise`
  
  ```
  Err.Raise 11
  ```

**Comment by retailcoder** [comment]
Implementing that one involves modifying the [IdentifierReferenceListener](https://github.com/retailcoder/Rubberduck/blob/ef289791aa5fe26412e704902aa13c1635983083/Rubberduck.Parsing/Symbols/IdentifierReferenceListener.cs) to override the virtual `EnterErrorStmt` method, and implement a collection property that returns all the `Error` statements encountered while walking the parse tree, and then exposing this collection in the [VBProjectParseResult](https://github.com/retailcoder/Rubberduck/blob/ef289791aa5fe26412e704902aa13c1635983083/Rubberduck.Parsing/VBProjectParseResult.cs), perhaps as some new `StatementOrToken` (or any better name) type that could be reused when we implement 

Once the `VBProjectParseResults` return all `Error` statements in the parse tree, half the job is done - all that's left to do is to implement the `ObsoleteErrorStatementInspection : IInspection` class and issue an `ObsoleteErrorStatementInspectionResult : InspectionResultBase` for each `Error` statement in the parse tree.

Implementing the quick-fix is also relatively easy: simply replace the statement with an `Err.Raise` call. Consider using the `TokenStreamRewriter` to avoid string replacements that could introduce bugs in the VBA code.

hmm implementing code inspections might not be as "easy" as I see it.
