### ISSUE TITLE
"Untracked files" needs "Include all" button

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#3710]
I have a project with ~90 modules I want to put under source control. After cloning the remote repository through command-line (got HTTP 401 from the "Clone Remote Repository" command), all the files show up as "untracked" and need to be added manually.

Of course I didn't. I went back to CLI and did `git add *.cls` and `git add *.bas` and `git add *.doccls` and `git add *.frm` and `git add *.frx`, then refreshed the SC panel and proceeded to commit.

And then push failed with HTTP 401 again, but that's another issue. Point is, if we're making a GUI, we shouldn't need to do most things in the CLI :smile:

**Comment by rubberduck203** [comment]
#3758
