### ISSUE TITLE
Another "Assignment Without Set" False Positive

### ISSUE THREAD

**Issue by CHR-IS-B** [rubberduck-vba/Rubberduck#3712]
The following code triggers the "Assignment Without Set" code inspection.  I am assigning a range to an array as described in the first example of this [CPearson.com page](http://www.cpearson.com/excel/ArraysAndRanges.aspx).

The description for the inspection says this will cause run-time error 91 but it works fine.  It would be helpful if RD either ignored this particular type of assignment or provide an expanded inspection description to explain why this was flagged.

```
Private Function TestFunction(ByVal target As Range) As String
    Dim myArray As Variant
    myArray = target    ' read range values into an array
End Function
```

**Comment by SystemsModelling** [comment]
Really a "use of default property" flag to get an array of values. Could you have a hint saying "choose one of .value, .value2, .text, .formula, .formular1c1...."
And it's not really "ignore Variant"; the LHS could equally well be any scalar type; after all target could be one cell.

**Comment by retailcoder** [comment]
I pretty much rewrote the whole inspection. Arrays are ignored for now (we don't verify if array items are objects), and we're not *really* resolving the type of the RHS expression, so a complex expression that requires a `Set` keyword might be a false *negative* now.

**Comment by retailcoder** [comment]
Ugh. Needs more tweaking... forgot to take default members into account there.

**Comment by retailcoder** [comment]
Something's not adding up. I added a test that specifically uses the code in the OP, and it passes (no inspection result). Fire up the VBE, paste the exact same code in, and the inspection yields a result for it. Investigating.
