### ISSUE TITLE
VBA Project won't disappear after the workbook has been closed.

### ISSUE THREAD

**Issue by DecimalTurn** [rubberduck-vba/Rubberduck#3714]
After installing Rubberduck, I started to notice that sometimes, I would close a workbook and it would remain visible in the Project Explorer of the VBE. And if I were to reopen the closed file, I would end up with 2 entries for the same workbook (with the latest being the one at the top).
![vba project won t close](https://user-images.githubusercontent.com/31558169/35141102-ced10714-fcc7-11e7-816f-7007a1af6470.png)

To make sure that this was indeed caused by Rubberduck, I did some tests where I would disable all my other add-ins to make sure that it was not caused by something else. Also, I noticed that this problem will only occur with workbooks that were opened after I launched the VBE (ie. after Rubberduck has been launched).

This won't occur with *.xlsx files, but I've seen it happen with *.xlam, *.xlsm and *.xlsb files.
__________
Rubberduck version: Version 2.1.2.2713

**Comment by DecimalTurn** [comment]
Maybe this SO question could be useful here: https://stackoverflow.com/questions/10696636/excel-vba-project-not-getting-closed

**Comment by MDoerner** [comment]
Thank you for reporting this.

I think I know what change in RD might have caused this problem and that is related to the SO post indeed. Depending on what the VBE API tells us after the workbook has been closed, the fix might already be on its way.

**Comment by CHR-IS-B** [comment]
I ran into this same problem after installing RD 2.1.2.2733-pre yesterday.  I don't recall which RD version I was running before.
