### ISSUE TITLE
Fake MsgBox crashes after setting return value for input box for all invocations

### ISSUE THREAD

**Issue by rbloehm** [rubberduck-vba/Rubberduck#3720]
I am currently testing code in Excel VBA that involves a MsgBox and an InputBox. So I used "Fakes.InputBox.ReturnsWhen..." and "Fakes.MsgBox.Returns" statements as I thought appropriate. 

In some cases this (reproducibly) leads to crashes and I can quickly glimpse the error message "Test raised an error. Specified cast is not valid."

Here you can find a minimal example to reproduce the issue (new, empty Excel 2016 *xlsm Workbook):

```
Option Explicit

Option Private Module

'@TestModule
'@Folder("Tests")

Private Assert As Rubberduck.AssertClass
Private Fakes As Rubberduck.FakesProvider

'@ModuleInitialize
Public Sub ModuleInitialize()
    'this method runs once per module.
    Set Assert = New Rubberduck.AssertClass
    Set Fakes = New Rubberduck.FakesProvider
End Sub

'@ModuleCleanup
Public Sub ModuleCleanup()
    'this method runs once per module.
    Set Assert = Nothing
    Set Fakes = Nothing
End Sub

'@TestMethod
Public Sub MsgBoxAfterInputBoxAnyInvocationFakeWorks()
    On Error GoTo TestFail
    
    Dim userInput As String

    Fakes.InputBox.ReturnsWhen "Prompt", "Second", "User entry 2"
    Fakes.MsgBox.Returns vbOK
    
    'This line crashes:
    MsgBox "This is faked", Title:="My Title"
    
    Fakes.MsgBox.Verify.Once

TestExit:
    Exit Sub
TestFail:
    Assert.Fail "Test raised an error: #" & Err.Number & " - " & Err.Description
End Sub
```
Another version that leads to the same crash is:
`'Fakes.InputBox.ReturnsWhen "Prompt", "Second", "User entry 2", 1`
But this will not crash:
`'Fakes.InputBox.ReturnsWhen "Prompt", "Second", "User entry 2", 2`

Rubberduck version: Version 2.1.2.2738
Operating System: Microsoft Windows NT 10.0.14393.0, x64
Host Product: Microsoft Office 2016 x64
Host Version: 16.0.8431.2131
Host Executable: EXCEL.EXE

**Comment by retailcoder** [comment]
Thanks for reporting! Could the setup with invocation index 2 isn't failing just because InputBox is only invoked once? We'll use that MCVE to get ourselves a stack trace, looks like there's a cast somewhere that's throwing... thanks a bunch!
