### ISSUE TITLE
Rubberduck crashed and don't open again

### ISSUE THREAD

**Issue by navferty** [rubberduck-vba/Rubberduck#3725]
I ran a macro with `Stop` instruction, called it from ribbon pane.
At that moment VBE editor wasn't open and rubberduck wasn't loaded either.
Rubberduck preloader was shown, and after that Excel crashed.
Now I can't even open VBE (excel also crashes, no matter which workbook is opened), unless I uninstal Rubberduck at all.
![error](https://user-images.githubusercontent.com/20906347/35380828-6f251432-01cb-11e8-838e-1e3ef62308ee.png)

**Comment by navferty** [comment]
if i try to load RubberDuck manually via Add-In Manager in VBE, it shows RubberDuck windows (like code inspections, project explorer and source control), but also crashes

**Comment by MDoerner** [comment]
It is very strange that the VBE chose to load its add-ins at that point.

Could you have a look whether there is a log in `...AppData/Roaming/Rubberduck/Logs` and post it, if there is one? 

Moreover, could you try to delete/rename the Rubberduck cofig file in `...AppData/Roaming/Rubberduck`. That will reset the settings and cure a possible corruption of the settings file.

**Comment by navferty** [comment]
After reset the settings RubberDuck loaded successfully, thank you very much for help. Unfortunately, logs contain only information on previous period, with successful exiting from excel.
I faced with another bug in source control - i cant open repository or create it from RubberDuck: `LibGit2Sharp throws System.DllNotFoundException: Unable to load DLL 'git2-15e1193'`
Should i create new issue on it?

**Comment by Vogel612** [comment]
yes, please do create a new issue for that. Thanks :)

**Comment by Vogel612** [comment]
Removing [support], since the direct corruption problem has been fixed.

**Comment by navferty** [comment]
@Vogel612 as i tried different settings, i found out that application crash when i change window settings to show test explorer on startup

the only difference in these configs is attribute
`<TestExplorerVisibleOnStartup>true</TestExplorerVisibleOnStartup>`
[rubberduck_fail.config.txt](https://github.com/rubberduck-vba/Rubberduck/files/1664182/rubberduck_fail.config.txt)
[rubberduck_success.config.txt](https://github.com/rubberduck-vba/Rubberduck/files/1664183/rubberduck_success.config.txt)

**Comment by bclothier** [comment]
Can't replicate this. Assuming it's been fixed in the intervening time and closing.
