### ISSUE TITLE
Code inspection: false positive "Object variable is assigned without Set keyword" in case of User-defined types

### ISSUE THREAD

**Issue by navferty** [rubberduck-vba/Rubberduck#3727]
User-defined types are not object variables, and assigning doesn't require the `Set` keyword

![image](https://user-images.githubusercontent.com/20906347/35390493-bd265c38-01ec-11e8-8753-503470438245.png)

**Comment by navferty** [comment]
even more, if user accepts the suggestion, it will cause compile error
![image](https://user-images.githubusercontent.com/20906347/35390774-9fa94a5c-01ed-11e8-8e8b-9787aeca164f.png)

**Comment by retailcoder** [comment]
A fix is currently WIP for this false positive, see #3719 and linked issues.

As for the quickfix, well, it does exactly what it's told to do - it's the inspection's job to determine if a `Set` keyword is required, not the quickfix'; if you *know* an inspection result is a false positive, running the quickfix for it *probably* isn't a good idea...

**Comment by retailcoder** [comment]
ref. #3712

**Comment by Vogel612** [comment]
Actually closing as duplicate.

**Comment by retailcoder** [comment]
@Vogel612 It technically *is* a dupe, but I left it open so I could reference it in a commit that specifically introduces a UDT test case... I'll leave it closed, but still reference it :smiley:
