### ISSUE TITLE
Compile before parsing

### ISSUE THREAD

**Issue by bclothier** [rubberduck-vba/Rubberduck#3732]
With type information API provided in PR #3716 , we now can request for a silent compilation of the VBA project. Before we parse, we should now require a compilation, to save ourselves from parser errors.

Furthermore, we can compile on a per-component level, a option that has not been exposed for long time (probably since Office 2000?), which may enable us to support partial parsing. 

Bonus: maybe update code explorer to mark components as having compilation errors. 

Note: In chat there has been discussion of updating the parser to continue after an error (cf. cancelled PR #3632 ). Considerations are needed as to whether this means we can skip the requirement to compile. Note that certain compilation errors also prevent VBA code from running at all; but not all errors.

**Comment by Vogel612** [comment]
FWIW It's generally a good idea to enforce that code we examine is compiling without errors, whether the Parser can recover or not. As such I'd keep those discussions separate. 

From what I can tell, the Parser handles about everything we (and our users) throw at it well enough. 
The error-recovery is then only useful in allowing Rubberduck to continue working *"good enough"*. That way parser errors are not showstoppers anymore.

**Comment by bclothier** [comment]
I think on default, it makes sense to require compiling before parsing, since that's the most desirable state, and we *do* want to encourage people to consistently compile their code. Way too many people write VBA code and never ever compile code and thus get to claim that their code has always worked which is a not-a-total lie. 

That said, there are times where being able to get list of all parser errors (which are implicitly compilation errors) is handy. VBE does not expose such ability; forcing one to compile and resolve errors one by **agonizing** one, never knowing how many more errors they are away from a successful compilation. For that reason, we need to be able to parse without compiling, but I'm totally fine with making it a special action or something similar so that for most use cases, compiling must be done before parsing.
