### ISSUE TITLE
Update to use ExecuteCode instead of Application.Run

### ISSUE THREAD

**Issue by bclothier** [rubberduck-vba/Rubberduck#3734]
We have used `Application.Run` to run code in VBA from Rubberduck, notably for unit-testing.

This has came with a number of annoying limitations because each host has chosen to implement them differently. We need to revise so that we use the `ExecuteStdCode` to run unit tests or other VBA interactions so that we now can fully qualify our invocations.

**Comment by retailcoder** [comment]
#3716 is merged - this can be implemented now.

`ExecuteStdCode` will deprecate `IHostApplication.Run`, but let's not throw the baby with the bath water just yet - let's keep `IHostApplication` (and its implementations) and carefully review its uses before considering it dead.

The test engine no longer needs `IHostApplication` though; the engine must be updated to invoke `ExecuteStdCode` directly, and then `IHostApplication.Run` can be removed. Once done, this issue can be deemed completed.
