### ISSUE TITLE
Compatibility check 32bit/64bit

### ISSUE THREAD

**Issue by PetLahev** [rubberduck-vba/Rubberduck#374]
Some sort of compatibility checker between 32bit/64bit version will be handy. 
Consider this code

```
Private Declare PtrSafe Function GetWindowLong Lib "user32" Alias "GetWindowLongA" _
(ByVal hwnd As LongPtr, ByVal nIndex As LongPtr) As LongPtr
```

This is 32/64bit safe but **won't work in 2007 or lower**

Obviously this won't work with 64bit Office

```
Private Declare Function GetWindowLong Lib "user32" Alias "GetWindowLongA" _
(ByVal hwnd As Long, ByVal nIndex As Long) As Long
```

Suggestion could be like this

```
#If VBA7 Then
Private Declare PtrSafe Function GetWindowLong Lib "user32" Alias "GetWindowLongA" _
(ByVal hwnd As LongPtr, ByVal nIndex As LongPtr) As LongPtr
#Else
Private Declare Function GetWindowLong Lib "user32" Alias "GetWindowLongA" _
(ByVal hwnd As Long, ByVal nIndex As Long) As Long
#End If
```

**Comment by ckuhn203** [comment]
:+1:

**Comment by ThunderFrame** [comment]
what happens if VBA8 comes along? Probably need to nest the conditions?

    #If VBA7 Then
      Private Declare PtrSafe Function GetWindowLong Lib "user32" Alias "GetWindowLongA" _
    (ByVal hwnd As LongPtr, ByVal nIndex As LongPtr) As LongPtr
    #Else
      #If Win64
        Private Declare PtrSafe Function GetWindowLong Lib "user32" Alias "GetWindowLongA" _
    (ByVal hwnd As LongPtr, ByVal nIndex As LongPtr) As LongPtr
      #Else
        Private Declare Function GetWindowLong Lib "user32" Alias "GetWindowLongA" _
    (ByVal hwnd As Long, ByVal nIndex As Long) As Long
      #End If
    #End If

**Comment by ckuhn203** [comment]
Then we'd have to update Rubberduck along with all the people out there updating their VBA code..

**Comment by ThunderFrame** [comment]
True enough. My nested snippet helped me find a parser bug though... Already raised.

**Comment by retailcoder** [comment]
@ThunderFrame FYI this code now parses correctly:

    #If VBA7 Then
      Private Declare PtrSafe Function GetWindowLong Lib "user32" Alias "GetWindowLongA" _
    (ByVal hwnd As LongPtr, ByVal nIndex As LongPtr) As LongPtr
    #Else
      #If Win64 Then
        Private Declare PtrSafe Function GetWindowLong Lib "user32" Alias "GetWindowLongA" _
    (ByVal hwnd As LongPtr, ByVal nIndex As LongPtr) As LongPtr
      #Else
        Private Declare Function GetWindowLong Lib "user32" Alias "GetWindowLongA" _
    (ByVal hwnd As Long, ByVal nIndex As Long) As Long
      #End If
    #End If

**Comment by ThunderFrame** [comment]
@retailcoder nice one. And custom #Const names work too?

**Comment by retailcoder** [comment]
deemed out of scope
