### ISSUE TITLE
Parse Error related to antlr4.6 update in  .2809 prerelease build

### ISSUE THREAD

**Issue by Stevefb** [rubberduck-vba/Rubberduck#3741]
Using the prerelease build .2809, this code generates a parse error:

```
Public Sub Foo()
    Dim a As Integer
    Dim b As Integer
    Dim c As Integer
    a = 1
    b = 2
    c = a - b  ' <<<<<<<< Parse Error, No alternative input 
    Debug.Print c
End Sub
```

**Comment by Stevefb** [comment]
Just confirmed the issue is NOT in Rubberduck v2.1.2.**2803**-pre

**Comment by ThunderFrame** [comment]
looks like it might be related to `B_CHAR`. Do you get the same parse error when the `b` variable is named something other than `b`?

**Comment by MDoerner** [comment]
It cannot be `B_Char` since that does not exist anymore.

**Comment by Vogel612** [comment]
it's probably `LETTER_RANGE`. Could you check whether the problem persists if you rename a to something with more than a single letter?

**Comment by Stevefb** [comment]
Thanks guys, confirmed that changing variable name from 'a' to something else works-around the parse error.

```
Public Sub Foo()
    Dim aye As Integer
    Dim b As Integer
    Dim c As Integer
    aye = 1
    b = 2
    c = aye - b
    Debug.Print c
End Sub
```

**Comment by quentinharris** [comment]
Appears to be that single letter followed by a '-' will raise the error. So single letter variables then space then "-" cause this. Lengthening the string e.g. 'ab' rather than 'a' avoid this.
