### ISSUE TITLE
Bonobo git server

### ISSUE THREAD

**Issue by dangalg** [rubberduck-vba/Rubberduck#3743]
Can you please add support for bonobo git server?

**Comment by Vogel612** [comment]
I'm not sure what exactly you mean. Rubberduck does not lock you into a git server in and of itself. 
Do note that source control is currently experimental (and pretty unstable), so you may see issues with adding git-servers in general ...

It  should work fine with manually created repositories, AFAIK.

How did you try to add that git-server? What was the error message? What's in the Logs?

**Comment by retailcoder** [comment]
@Vogel612 probably similar to GitHub and BitBucket remotes - I couldn't get a push to work.

Work-around is to do local commits, and then `git push` and `git pull` with the command-line interface. SC panel works fine-ish with everything local. Manually adding the untracked files one by one is tedious though, we need an "add all untracked files" button or something. Using the CLI is easier for now: `git add *.???cls`, `git add *.bas`, `git add *.fr?` should add all untracked classes, modules, forms, and document code-behind; refreshing the SC panel after doing that shows all the files as "added" in the 'Changes' box. Commit then works, but by then one might as well go `git commit -m "message"` - bottom line, use the SC panel to export/import the files, and the CLI for git commands (esp. remote).

**Comment by Hosch250** [comment]
FWIW, I have pushed to both GitHub and BitBucket repos. I'll try again tonight to see if I still can.

**Comment by rubberduck203** [comment]
Does your bonobo server use SSH Keys?

**Comment by Hosch250** [comment]
With a couple small tweaks, I got SC working for me again--it had broken at some point with the switch to Castle Windsor.

**Comment by dangalg** [comment]
I don't know if it uses ssh keys where do I look?
Bonobo is an on prem git server we installed it on one of our servers.

**Comment by Vogel612** [comment]
FWIW, Source Control has been discontinued. Instead we highly recommend using the `ExportAll` feature to export your code into a directory you control. You can then do the usual steps of source control in that directory. 

As this is about setting up Rubberduck's Source Control, I'm closing the issue as no longer applicable.
