### ISSUE TITLE
Code Explorer>Rename Folder

### ISSUE THREAD

**Issue by IvenBach** [rubberduck-vba/Rubberduck#3745]
Have the option of renaming the folder that updates all annotations.

Related to #3332

**Comment by Vogel612** [comment]
We may want to check for naming conflicts. It should result in a message if a user is merging two folders this way. The user should still be able to perform the rename though.

Note that this may require rubberduck to have parsed the code.

**Comment by MDoerner** [comment]
Should this feature allow to change the entire folder name or just the last subfolder?

**Comment by MDoerner** [comment]
The check for merges might also be an enhancement for `MoveFolder` since it can also lead to merging with a subfolder of the target folder.

**Comment by mansellan** [comment]
I'd say it should be for the last subfolder only. Having two folders with the same name in different paths seems to be entirely reasonable to me.

**Comment by MDoerner** [comment]
The last question did not refer to the check but the feature requested in this issue, i.e. renaming folders. The collision check would only be against the full name anyway.
