### ISSUE TITLE
Make module annotations less stiff

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#3746]
Let's make module annotations scope to the module up until the first encountered member or member annotation.

If a member annotation is found but doesn't immediately precede the first member, treat it as illegal (this should be the current behavior).

**Comment by MDoerner** [comment]
Is this still an isuue.

We should now attach all member annotations above the first member to the module.
That is not exactly what is requested here, but it is more intuitive, IMHO.
