### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#375]
Received this error while refreshing the TODO: list in Access 2010:

>Unhandled exception has occurred in a component in your application: Object reference not set to an instance of an object

Access fully crashed, so I wasn't able to get any info from it. The Dr. Watson files are located on my Dropbox. You should be able to access it [here](https://www.dropbox.com/sh/sbvok738s8ujjwv/AABpnS1Ahrin0RQpMCVInPe1a?dl=0)

**Comment by Vogel612** [comment]
@retailcoder where was this closed? Or is this issue no more relevant, because the Todo Explorer received the WPF overhaul?

**Comment by retailcoder** [comment]
@Vogel612 not only that; literally *everything* involved in producing a todo list has changed since April 2015, I deem this one was simply "forgotten" somewhere between 1.4 and 2.0... as a number of issues were.
