### ISSUE TITLE
Nesting Depth needs tweaking

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#3757]
Nesting depth metric is currently counting leading spaces (ignoring blank lines).  While this probably has a value, I'd prefer the metric to be more in line with what other code metric tools do, like NDepend:

> The metric Nesting Depth for a method is the maximum number of encapsulated scopes inside the body of the method.

Of course VBA's lowest *scope* is procedure-level, so we won't be counting scopes, but *blocks* - syntactic structures that can be nested. This includes all the control flow blocks accounted for by the *Cyclomatic Complexity* metric (loops, conditionals, `Select Case` blocks), but also `With...End With` blocks (and any other blocks not accounted by CC).

**Comment by Vogel612** [comment]
Something something design techdebt mentioned in original PR. Just a reminder to myseld
