### ISSUE TITLE
Parse Error - I can not find why - where to look for the problem?

### ISSUE THREAD

**Issue by FrankHentzschel** [rubberduck-vba/Rubberduck#3772]
I got Parse Error - 2 refernces but no information what is the concrete error.
Can anyone help?

Thanks in advance
Frank

**Comment by MDoerner** [comment]
To get an indication of the parser error, you can click on the red button to the right of the refresh botton, which is currently showing _Parser Error_. Should there be no errors listed, there has been some unexpected exception while parsing, i.e. basically a bug has been showing. In that case, you can have a look at the log, provided logging is enabled at log level at least _Error_. On higher levels than _Warning_, the log gets quite verbose. In the Rubberduck settings menu, there is a button leading you to the log folder.

One question: Does your code compile (Debug->Compile)? If not parser errors are to be expected since the base assumption of the parser is that the code is legal VBA. (There is one point where the VBE is a bit less strict and it lets you close properties with `End Sub`, which is actually not legal VBA code.)

**Comment by FrankHentzschel** [comment]
Thanks, that helps a little.

Of course the code can be compiled.

In the logfile I get entries for example like the following, but I do not see the error in the source module 'ClassFactrory'

Do you have any ideas how to locate the error?

2018-02-20 10:27:09.8974;ERROR-2.1.2.2830;Rubberduck.Parsing.VBA.ReferenceResolveRunnerBase;Exception thrown resolving 'ToleranceCalculationTemplate.classFactory' (thread 68).;System.ArgumentNullException: Der Wert darf nicht NULL sein.
Parametername: source
   bei System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   bei Rubberduck.Parsing.VBA.AttributeNode.HasValue(String value) in C:\projects\rubberduck\Rubberduck.Parsing\VBA\Attributes.cs:Zeile 54.
   bei Rubberduck.Parsing.VBA.Attributes.<>c.<HasDefaultMemberAttribute>b__3_0(AttributeNode a) in C:\projects\rubberduck\Rubberduck.Parsing\VBA\Attributes.cs:Zeile 126.
   bei System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   bei Rubberduck.Parsing.VBA.Attributes.HasDefaultMemberAttribute() in C:\projects\rubberduck\Rubberduck.Parsing\VBA\Attributes.cs:Zeile 126.
   bei Rubberduck.Parsing.Symbols.IdentifierReferenceResolver.<>c__DisplayClass21_0.<ResolveDefault>b__1(Declaration m) in C:\projects\rubberduck\Rubberduck.Parsing\Symbols\IdentifierReferenceResolver.cs:Zeile 197.
   bei System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   bei Rubberduck.Parsing.Symbols.IdentifierReferenceResolver.ResolveDefault(ParserRuleContext expression, StatementResolutionContext statementContext, Boolean isAssignmentTarget, Boolean hasExplicitLetStatement, Boolean isSetAssignment) in C:\projects\rubberduck\Rubberduck.Parsing\Symbols\IdentifierReferenceResolver.cs:Zeile 197.
   bei Rubberduck.Parsing.Symbols.IdentifierReferenceResolver.Resolve(SetStmtContext context) in C:\projects\rubberduck\Rubberduck.Parsing\Symbols\IdentifierReferenceResolver.cs:Zeile 376.
   bei Rubberduck.Parsing.Symbols.IdentifierReferenceListener.EnterSetStmt(SetStmtContext context) in C:\projects\rubberduck\Rubberduck.Parsing\Symbols\IdentifierReferenceListener.cs:Zeile 281.
   bei Rubberduck.Parsing.Grammar.VBAParser.SetStmtContext.EnterRule(IParseTreeListener listener) in C:\projects\rubberduck\Rubberduck.Parsing\obj\Release\VBAParser.cs:Zeile 11847.
   bei Antlr4.Runtime.Tree.ParseTreeWalker.EnterRule(IParseTreeListener listener, IRuleNode r)
   bei Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   bei Rubberduck.Parsing.VBA.ReferenceResolveRunnerBase.ResolveReferences(DeclarationFinder finder, QualifiedModuleName module, IParseTree tree, CancellationToken token) in C:\projects\rubberduck\Rubberduck.Parsing\VBA\ReferenceResolveRunnerBase.cs:Zeile 218.

**Comment by MDoerner** [comment]
Thank you for posting the log entry. The error is on our side. 

More precisely, something is `null` that the code handling default members does not expect to be `null`.

I will have a look later today. A fix will probably not be too hard to implement.
