### ISSUE TITLE
once i run tests even it displaying as unknown after successful

### ISSUE THREAD

**Issue by manjugb** [rubberduck-vba/Rubberduck#3773]
![rubberduckerror](https://user-images.githubusercontent.com/8070127/36418474-dfe8f0d4-1626-11e8-834c-33cf07daec66.PNG)

**Comment by manjugb** [comment]
this is happen once i updated into latest version

**Comment by Vogel612** [comment]
sounds correct...

**Comment by retailcoder** [comment]
Work-around for now: use "run all tests" command from the *Test Explorer* toolwindow.
