### ISSUE TITLE
Parse error without any parse errors

### ISSUE THREAD

**Issue by steelynx** [rubberduck-vba/Rubberduck#3781]
I get a parse error and the parse errors window is empty. Any help would be appreciated
I believe the relevant error is:
`2018-02-21 18:57:45.4141;ERROR-2.1.2.2854;Rubberduck.Parsing.VBA.ParseCoordinator;Unexpected exception thrown in parsing run. (thread 28).;System.Runtime.InteropServices.COMException (0x80004005): The expression you entered refers to an object that is closed or doesn't exist.`
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/1746143/RubberduckLog.txt)

**Comment by Vogel612** [comment]
see #3772 and #2915
