### ISSUE TITLE
FATAL-;Rubberduck._Extension;Startup sequence threw an unexpected exception

### ISSUE THREAD

**Issue by quentinharris** [rubberduck-vba/Rubberduck#3793]
Whilst opening the VBE in PowerPoint today I got the above message and RD failed to load. Please find log file attached.
[RubberduckLog20180226.txt](https://github.com/rubberduck-vba/Rubberduck/files/1757854/RubberduckLog20180226.txt)

**Comment by Vogel612** [comment]
Should be fixed as of https://github.com/rubberduck-vba/Rubberduck/pull/3784

What version are you running?

**Comment by quentinharris** [comment]
2.1.2.2839 I didn't realise I was so far behind.

**Comment by Vogel612** [comment]
@quentinharris  can you still reproduce this issue?

**Comment by bclothier** [comment]
Closing this as RD woRks in PowerPoint currently.
