### ISSUE TITLE
Source Control option disappear in 2.1.2.2886 

### ISSUE THREAD

**Issue by pbraty** [rubberduck-vba/Rubberduck#3794]
Hi,

I have just notice that Source Control Option disappear in General Settings after installing 2.1.2.2886 
![2018-02-26 12_24_45-](https://user-images.githubusercontent.com/2040289/36667991-242514e4-1af0-11e8-84ae-63a6592c667a.png)

Regards,

Pavlik

**Comment by bclothier** [comment]
It has been discontinued. See #3758 which was closed by PR #3782. 

Please note that you can continue to use `Export` / `Import` functionality to export everything between your VBA project and the filesystem, and use your preferred source control against the filesystem directly.
