### ISSUE TITLE
New setting CompileBeforeParse is not defaulting to true

### ISSUE THREAD

**Issue by bclothier** [rubberduck-vba/Rubberduck#3795]
In PR #3783 we added a new setting, `CompileBeforeParse` that should be defaulting to true. It has been reported it does not. Evidently something is missing in propagating the new default.

It is also noted that a restart is necessary for the setting to take effect. It is not certain if this can be done without requiring a restart.

**Comment by WaynePhillipsEA** [comment]
complete guess:  perhaps the defaults are only applying if the whole settings group (GeneralSettings) are not in the settings XML?  Perhaps if it encounters a new entry into an existing group, it's not applying the default..

**Comment by bclothier** [comment]
Pinging @rkapka  for help on this issue.

**Comment by bclothier** [comment]
I reviewed the problem and it looks to me the issue is with the loading of the settings. We use a `XmlReader` in the `XmlPersistanceService` class' `Load` method which converts the XML document into the given type.

However, because the setting `CompileBeforeParse` is defined with a `bool`, it cannot have a `null` value, so when it is read, `false` is assigned. This obscures whether the `false` was simply because the user wanted it originally versus the `false` because it didn't exist and the deserialization had to write a default value instead. 

One possible solution is to make it `bool?` which may allow for `null`, which would require subsequent logic to supply the correct default. The alternative is to make it`SkipCompileBeforeParse` instead but I'm not a big fan of negative boolean logic. 

This is also a problem with other data types, not just `bool`, if we want to propagate defaults that aren't default of the underlying value types, we'll need something that allows for check of missing value and assignment from the proper default stored in the `Settings` file.
