### ISSUE TITLE
Indenter cycles declaration indents on and off

### ISSUE THREAD

**Issue by CHR-IS-B** [rubberduck-vba/Rubberduck#3800]
I noticed that when the Align Dims options is on when the RD indenter is run, it indents dims (and constants) that are not already indented but it removes indentation on dims that were already indented.

If all my declarations are not indented to begin with, then everything works as expected.

If however I use the indenter on a module, then go back and add a new declaration and run the indenter again, it will indent that new declaration and un-indent all other declarations.  If I continue to run the indenter, each time it will leave some declarations indented and others indented.  The solution is to manually indent (or un-indent) all declarations and run the indenter again.

BTW, RD is awesome.

**Comment by comintern** [comment]
Thanks for submitting this issue (and sorry for the delay in addressing it). I can't seem to replicate this issue. Can you post an example of code that exhibits this behavior along with your `rubberduck.config` file?

You'll find the `.config` file in `Users\[your user name]\AppData\Roaming\Rubberduck`.

Thanks!

**Comment by CHR-IS-B** [comment]
[rubberduck.zip](https://github.com/rubberduck-vba/Rubberduck/files/2287582/rubberduck.zip)

I attached my RubberDuck config file and an example workbook.

When I use the Indenter, variable declarations that were already indented per RD settings revert to no indentation, declarations with no indentation are indented properly per RD settings and variables with indentation that doesn't match the RD Indenter settings gets changed to a different indentation level that also doesn't match RD settings.  When I run the Indenter a second time it reverts back to the state it was in before running the Indenter the first time.

I was expecting the Indenter to take all variable declarations, regardless of their current indent level, and indent them all to the same/matching level.

Here's the code from that workbook:

```
Sub StartWithOneVariable_01()
' This is the original subroutine.
    Dim a As String
End Sub


Sub AutoIndent_02()
' After using auto-indent it looks like this - properly indented.
    Dim a                                       As String            ' Properly indented per settings
End Sub


Sub AddSecondVariable_03()
' Then I add a second variable - not indented.
    Dim a                                       As String
    Dim z As Object
End Sub


Sub AddThirdVariable_04()
' Then I add a third variable, 'i'.  Assume this is a page below the first two
'   variables, so I try to match the indentation of 'a' but get it wrong.
    Dim a                                       As String
    Dim z As Object
    Dim i                               As Long
End Sub


Sub AutoIndent_05()
' When I run the auto-indenter it looks like this:
    Dim a As String                                                  ' Indentation removed.
    Dim z                                       As Object            ' Properly indented per settings
    Dim i         As Long                                            ' Indentation changed.  It neither matches it's original indent or the indenter setting.
End Sub


Sub AutoIndent_06()
' When I run the auto-indenter again it looks like this:
    Dim a                                       As String            ' Properly indented per settings
    Dim z As Object                                                  ' Indentation removed.
    Dim i                               As Long                      ' Indentation changed.  It neither matches it's original indent or the indenter setting.
End Sub


Sub AutoIndent_07()
' When I run the auto-indenter yet again it reverts to the state in
'   'AutoIndent_05'.
    Dim a As String                                                  ' Indentation removed.
    Dim z                                       As Object            ' Properly indented per settings
    Dim i         As Long                                            ' Indentation changed back but still doesn't follow the indenter setting.
End Sub
```

**Comment by comintern** [comment]
Thanks for the info! That made it trivial to track down and fix.
