### ISSUE TITLE
Wiki & README: add link to latest stable as well as very latest

### ISSUE THREAD

**Issue by cxw42** [rubberduck-vba/Rubberduck#3802]
The README and wiki currently link to [the releases list](https://github.com/rubberduck-vba/Rubberduck/releases).  I wanted to grab the latest *stable*, and was not able to find a direct link.  It's always possible I'm just missing something obvious!  If so, please point me to it and close this out.

Would anyone object if I updated/PRed the README and wiki to link to both `/releases` and `/releases/latest`?  The latter automatically skips the pre-releases --- all 77 of them, as I write this!

I had forgotten about `/releases/latest`, so I wound up doing `git tag -l --sort=authordate --format='%(objecttype)  %(refname)  %(committerdate)'`, finding out that `v2.1.1` was an annotated tag so didn't sort properly with the remaining tags, finding the next commit after that one, and plugging that into the `after` URL parameter on `/releases`.  Ick.

**Comment by Vogel612** [comment]
Updated title to not confuse our Duga. 

Also :+1:  from me that seems like a simple change that does a lot of good

**Comment by cxw42** [comment]
@Vogel612 thanks!  Wiki updated; README is #3805.
