### ISSUE TITLE
Unit Tests - Feature request test explorer to show SUT

### ISSUE THREAD

**Issue by Stevefb** [rubberduck-vba/Rubberduck#3812]
I hope I'm not alone in thinking it would be great to have an additional column(s) in the test explorer that shows the Subjects Under Test.

In the event that a test fails this would provide a very convenient way to navigate to the relevant code...  

... or...  as a stretch goal, might it be possible to automatically add a link to the code that caused a failure?

**Comment by IvenBach** [comment]
You can double click on the failing test and that takes you directly to the test.

**Comment by Stevefb** [comment]
to the _test_, yes... but what about going directly to the **bug** in the code....?

**Comment by Vogel612** [comment]
@Stevefb calm your horses, there. That's beyond next-level. There's nothing out there - that I know of - that has come even close to attaining that level of code-awareness. It's just not how unit-testing and static code analysis work.

if you could find the bugs in the code with a good algorithm by just writing enough unit-tests, then we'd not be writing code, we'd be writing the unit-tests that specify it. Given that nobody does it that way ...

**Comment by rubberduck203** [comment]
I’m sorry, but this is just a bit beyond what this team is able to take on. 
We’re really happy that you love the tool and are excited about it, but...

Well, this xkcd probably says it better than I can. 

![https://xkcd.com/1425/](https://imgs.xkcd.com/comics/tasks.png)

**Comment by Stevefb** [comment]
Ok, but for navigational purposes... _(lets forget the stretch goal)_ when _writing_ a unit test the SUT could be manually added to a SUT column so that if the test fails the developer could go straight there

**Comment by Vogel612** [comment]
still not really doable, because the SUT isn't placed in a standard format (for one), nor is it really a given that there is only a single SUT for a given TestModule, nor can we assume that the SUT is even really navigable to....

**Comment by Stevefb** [comment]
yikes, I guess is considerably more complex than I imagined... my thinking is still 'too concrete'
