### ISSUE TITLE
Source Control Wiki

### ISSUE THREAD

**Issue by Greedquest** [rubberduck-vba/Rubberduck#3820]
I've just read about the end of source control, probably for the best.

I think it might be worthwhile to deal with a few of the broken links that result from removing it, as it took me a bit of digging to find out what was going on. Specifically:

https://github.com/rubberduck-vba/Rubberduck/wiki/Source-Control:-Getting-Started
https://github.com/rubberduck-vba/Rubberduck/wiki/Source-Control-API

These could perhaps both contain short posts explaining that Source-Control has been discontinued, rather than being 'create a new page' links as they are currently. They are still the top search results when I Google _source control rubberduck_ and so a little note would be helpful

Similarly, the main site post http://rubberduckvba.com/SourceControl could be updated to reflect changes.

**Comment by Vogel612** [comment]
The last part is something that @retailcoder will need to do. The wiki is open for edits from everyone, you're very welcome to update these articles with useful information. I'd recommend backlinking to #3758

**Comment by rubberduck203** [comment]
Actually, the website is open to pull requests too. We’d only need Mat to merge & deploy. 

https://github.com/rubberduck-vba/RubberduckWeb

**Comment by bclothier** [comment]
Since wiki already has been updated, and there's now an issue on web ([ # 51](https://github.com/rubberduck-vba/RubberduckWeb/issues/51) ), we'll close this.
