### ISSUE TITLE
Excel 2016 Visual Basic button grayed out after RD crashing

### ISSUE THREAD

**Issue by jmditner** [rubberduck-vba/Rubberduck#3822]
I downloaded the latest RD version (v2.1.1) and wanted to check the new functionalities. After some tests on existing code, RD crashed. 

I then restarted Excel but discovered the VBA IDE button was grayed out. Even ALT + F11 didn't work anymore. What a panic ! 

After some search I found out that restarting the computer gave access again to VBA. I had no choice to deactivate RD to be able to work again on my VBA code.

I guess this issue comes from Excel 2016, I never had this type of issue on previous Excel versions.

**Comment by Vogel612** [comment]
Could you please check for me whether setting the LoadBehaviour of the Addin to `0` in the registry under `HKCU\Software\Microsoft\VBA\VBE\6.0\AddIns\Rubberduck.Extension`

**Comment by jmditner** [comment]
No it didn't change anything. 
One thing though, RD does not have to crash to have VBE inactivated. 
 
![image](https://user-images.githubusercontent.com/37039320/36946278-b12ddea6-1fba-11e8-942e-5f2388570d53.png)

**Comment by jmditner** [comment]
Finally the issue really came from my Excel version, now all works fine. 
Thanks for your help Vogel612
