### ISSUE TITLE
The declared variable is considered unused, although it is used in a nested For loop

### ISSUE THREAD

**Issue by InExSu** [rubberduck-vba/Rubberduck#3841]
Rubberduck version: Version 2.1.1.2532
Operating System: Microsoft Windows NT 6.1.7601 Service Pack 1, x64
Host Product: Microsoft Office 2010 x86
Host Version: 14.0.7015.1000
Host Executable: EXCEL.EXE

```
Option Explicit

Public Sub TestRubb()
  Dim i As Long
  Dim z As Long
  For i = 1 To 2
    For z = 1 To 2
    Next
  Next
End Sub
```
![default](https://user-images.githubusercontent.com/36605404/37398748-928c120a-2790-11e8-829a-c3bd76b34d2b.png)

**Comment by retailcoder** [comment]
The inspection is correct. The variables are indeed never *referenced*, even though they are both *assigned* through the loop. A result for *unassigned variable* or *unassigned variable usage* would have been a false positive, but per the given code, that's working as intended.
