### ISSUE TITLE
Code Explorer crashing due to null commands

### ISSUE THREAD

**Issue by bclothier** [rubberduck-vba/Rubberduck#3842]
Since the merge of PR #3739, the Code Explorer is now crashing because it has `null` for all of its commands.

Note that simply having `null` doesn't crash, but rather a lack of handler:

```
        private void TreeView_OnMouseDoubleClick(object sender, MouseButtonEventArgs e)
        {
            if (ViewModel != null && ViewModel.OpenCommand.CanExecute(ViewModel.SelectedItem))
            {
                ViewModel.OpenCommand.Execute(ViewModel.SelectedItem);
            }
            e.Handled = true;
        }
```

The `OpenCommand` is `null` so trying to double-click an item in code explorer will crash.

I also think because the comamnds are essential for code explorer to work, there needs to be some of guard clause at the Rubberduck's startup to validate that all commands are correctly wired up as to avoid NREs at the runtime. It's annoying because some menu items (e.g. `Refresh` apparently works, but other (e.g. `Add Test Module`) simply does nothing and does not crash. 

I think it would be better user-experience if Rubberduck was more proactive in validating all commands at the startup and thus can abort the startup to avoid offering the user a *seemingly working* instance.

**Comment by Vogel612** [comment]
There's some unit tests that check for certain bindings. We might want to expand those... We should take care to not lock ourselves into some structure though.

It's somewhat interesting that this only applies for some commands.

The Command Bindings did change in the PullRequest, relevant diff starts at [RubberduckIoCInstaller.cs#Line 525](https://github.com/rubberduck-vba/Rubberduck/pull/3739/files#diff-1d0ced34d32061d419523ca7feaeda97L525)
