### ISSUE TITLE
Unit Test inconclusive with long path

### ISSUE THREAD

**Issue by IvenBach** [rubberduck-vba/Rubberduck#3843]
The workbook with tests is stored on network which causes the path to be lengthy. I renamed a test and running it resulted in an error message `Sorry, we couldn't find '<Path>.WBName.xlsm - [ModuleNa'. Is it possible it was moved, renamed or deleted?` Note that ModuleName is cut off. I counted 108 characters when the cutoff on the ModuleName occured. When this occurs all tests result as `Inconclusive`.

If I close the workbook entirely rename it to a shorter name `Foo.xlsm`, the tests run fine.

Additional things to note
- When tests fail because of the path length being too long and I close Excel, often there's a lingering process that needs to be killed via TaskManager.
- Changing a tests name and running causes tests within the same module to pass. Those not affected by length issue?
- Renaming a test and choosing Run>All Tests a parse is invoked. This shows the updated name in Test Explorer. Run>Inconclusive doesn't show the updated test name even though the `Duration` for the tests do change. Run>All Tests also causes `Duration` to be longer than is actual while a parse is occuring, running again shows much shorter times.
- SavingAs and running the tests will open the previous workbook.

**Comment by MDoerner** [comment]
Which version of RD is this happening with?

Judging from the details provided, the culprit is the `ProjectDisplayName`, which is no longer used for running the tests.

**Comment by IvenBach** [comment]
Rubberduck version: Version 2.1.6642.26611
Operating System: Microsoft Windows NT 6.1.7601 Service Pack 1, x64
Host Product: Microsoft Office 2013 x86
Host Version: 15.0.5007.1000
Host Executable: EXCEL.EXE

**Comment by IvenBach** [comment]
I've been having lingering Excel processes and believe they are tied to this issue.

MVCE: Renaming a TestModule to `MaxLengthABCDEFGHIJKLMNOPQRSTUV` that had a test method named `ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZ` caused an inconclusive result. Closing Excel and checking TaskManager showed a lingering Excel process.

Killed that process, and opened the WB. Renamed the module from `MaxLengthABCDEFGHIJKLMNOPQRSTUV` to `ShortLength` and the method to `ABDCE`. Running tests still caused some, not all tests however, to be `Inconclusive`. Closing the WB and checking TaskManager didn't have any lingering process.

Opened WB, ran unit tests. As expected, all passed.

**Comment by IvenBach** [comment]
Updated RD to `next` Rubberduck version: Version 2.1.6655.19137. Haven't gotten any inconclusive so far, 4+ hours of testing.

**Comment by IvenBach** [comment]
Experiencing this again with `next` build. Shortened workbook name and tests come out clean.

**Comment by comintern** [comment]
I can't replicate this. Can you confirm whether this is still an issue on next?

**Comment by comintern** [comment]
I'm assuming this is no longer an issue, in that the test engine is not longer using the filepath.
