### ISSUE TITLE
Promote local variable to private field

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#386]
As a VBA programmer, I want to have the ability to select a local (procedure-scoped) variable (or constant) declaration, and promote that variable to a field (module-scoped), effectively replacing that local declaration by a `Private` field declaration.

**Comment by retailcoder** [comment]
Related: #179

**Comment by Hosch250** [comment]
Reference PR: https://github.com/rubberduck-vba/Rubberduck/pull/878/files
