### ISSUE TITLE
Bug: Unit Testing - Multiple test modules

### ISSUE THREAD

**Issue by DiogoRNeves** [rubberduck-vba/Rubberduck#3864]
Unit testing work perfectly if I have only 1 testing module, but the moment i added a second testing module the @ModuleInitialize stopped running, and that means that Assert and Fakes don't get initialized, and so I can't run the tests.

I am testing 2 different classes, so it would be ideal to have 2 different test classes.

I moved the code to the same test class and everything went ok.

I'm on version 2.1.1.2532 and Access 2013.

Cheers

**Comment by bclothier** [comment]
This was a known issue and was fixed in the PR #3778, which is a pre-release, v2.1.2.3005. So if you want to run a pre-release, you can get the current pre-release and try it again.

**Comment by DiogoRNeves** [comment]
I'll wait for the release.

Thanks and keep up the amazing work!
