### ISSUE TITLE
Code Explorer not refreshing

### ISSUE THREAD

**Issue by anevard** [rubberduck-vba/Rubberduck#3871]
When I add/delete a new module or sub it does not show in code explorer after refresh.  It will show after Excel restart.  Note that MZ-tools is also installed.

Did not work with earlier releases too, but worked a few months back before Excel .version update.

[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/1864006/RubberduckLog.txt)

**Comment by Vogel612** [comment]
that tracelog is awfully uneventful ...

```
Rubberduck version 2.1.6662.23164 loading:
Operating System: Microsoft Windows NT 10.0.16299.0 x64
Host Product: Microsoft Office 2016 x86
Host Version: 16.0.9029.2253
Host Executable: EXCEL.EXE;
```

@anevard this looks like you're on a development build. Can you verify that for me?

**Comment by anevard** [comment]
Yes I just installed the latest build to see if it would resolve the issue.  I realized that I had not been logging so that log file is only after the new install and a refresh attempt.

**Comment by comintern** [comment]
This *should* be resolved by the CE refresh. If not, please reopen.
