### ISSUE TITLE
Watch and Locals Windows broken.

### ISSUE THREAD

**Issue by SteveLaycock** [rubberduck-vba/Rubberduck#3874]
Rubberduck v2.1.2.3021-pre

I'm not sure if this is a rubber duck issue. 

I have opened the locals and watch windows as floating windows.  Nothing is showing in either window and it is not possible to close the windows.  The immediate window is also open but functioning normally.  I have run the log in trace mode and no errors are reported.

If I dock the locals and watch windows it is possible to close them.

**Comment by bclothier** [comment]
@SteveLaycock  

This looks a bit too random. As a favor, could you please disable the Rubberduck (and any other add-ins) via VBE's Add-in manager, restart the host and verify if the Watchs/Locals windows work normally?

If they do, load the Rubberduck, restart and see if it is working still? If it breaks, we'll definitely want the full log, too.

**Comment by carlos-quintero** [comment]
It's a bug introduced by the VBA editor of Office Version 1803 (Build 9126.2116) (March 27). Until Microsoft fixes it, stick to Version 1802 (Build 9029.2253) (March 13)

See: [About the unresponsive floating toolwindows of MZ-Tools for VBA with some Office 2016 applications](https://www.mztools.com/blog/about-the-unresponsive-floating-toolwindows-of-mz-tools-for-vba-with-some-office-2016-applications/)

**Comment by Vogel612** [comment]
since this is not a Rubberduck bug, I'll decline this. Updates to this thread (e.g. when a fix from MS comes in) are appreciated either way
