### ISSUE TITLE
MS Access : Crash upon Inspecting

### ISSUE THREAD

**Issue by FuSoftware** [rubberduck-vba/Rubberduck#3883]
As discussed in the chat, one of my ACCDB files (and its sibling files with only a few differences) consistently crash when performing the RD scan. Here is the trace log if you can find what's wrong. 

I haven't been able to reproduce the issue, starting with a new ACCDB so far

[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/1879639/RubberduckLog.txt)

**Comment by FuSoftware** [comment]
After deleting a few forms the problem got moved

[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/1879716/RubberduckLog.txt)

**Comment by FuSoftware** [comment]
I haven't tried this code "standalone" yet, but in my file, deleting all forms+modules but this makes the error still happen (deleting this form makes the parsing work).

[Form.txt](https://github.com/rubberduck-vba/Rubberduck/files/1879779/Form.txt)

**Comment by FuSoftware** [comment]
Narrowed down to that specific function. I still have to try with a previous version of RD to see if it's linked to the latest merge regarding Select Case

[Function.txt](https://github.com/rubberduck-vba/Rubberduck/files/1879868/Function.txt)

**Comment by Vogel612** [comment]
Copying over the function for other people to use:

```

**Comment by Vogel612** [comment]
Norepro on MSAccess 2016 from the branch of my PR. I'll attempt to repro from `next`

**Comment by FuSoftware** [comment]
I'm currently re-installing RD 3039 to try to make a proper sample file

**Comment by FuSoftware** [comment]
Well, I can't reproduce the bug on 3039 here, idk why. The only difference is that it is an Access 2013 64 bits, compared to the computer I had earlier, which had Access 2016 32 bits

**Comment by Vogel612** [comment]
Okay, just repro'd this. We have a StackOverflowException on the following line in `Declaration`:

```
public bool AsTypeIsBaseType => string.IsNullOrWhiteSpace(AsTypeName) || SymbolList.BaseTypes.Contains(AsTypeName.ToUpperInvariant());
```

**Comment by retailcoder** [comment]
@Vogel612  can you repro in a unit test? (might be hard, IIRC `ErrObject` is hacked-up with a custom type loader)

**Comment by Vogel612** [comment]
Current Suspect: `ErrObject`. We may have needed to hack that one in to get the resolver to work with it correctly. But as of now I can only see it in the serialized declarations for ADODB 6.1 😕 

We may need to make the resolver a bit smarter...

**Comment by BZngr** [comment]
I've got a resolution nearly ready.  The Recursive call to `private static string GetBaseTypeForDeclaration(Declaration declaration)`  is where the problem starts, but there is a bit more to resolve as well.
