### ISSUE TITLE
Settings are removed when uninstalling.

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#3884]
Since the great update to allow non-admin users to install RD on a per-user basis, it seems that the settings folder is being deleted on uninstall.

I had been installing the prior versions as a local admin. Once the new installer updates were released, I've been installing per-user (though still as a local admin).

It would be nice if this were a prompt during uninstall as some <s>crazy</s> people may actually want to remove RD from their machines and it would be nice to completely clean up after ourselves in this case. Default, of course, to leaving the settings behind.

**Comment by daFreeMan** [comment]
Hate to say it, but this is still an issue. :(

Just installed 2.2.0.3050 and all my settings are gone.

**Comment by bclothier** [comment]
Just to clarify - did you uninstall an older version? That would still have the incorrect behavior of deleting those settings.

**Comment by daFreeMan** [comment]
ah. Yes, I did run the uninstaller. I guess that makes sense.

_and I meant 2.2.0.308x - whatever that release build number is... :)_

**Comment by bclothier** [comment]
Yes, it's a property of the uninstaller, so previous version uninstaller would be doing what it was set up to, rather than the current version of the installer. What *would* be an issue is if you later uninstalled this version and it still deleted the settings anyway.
