### ISSUE TITLE
Reparse after code with On Error Resume Next skips over some inspection content

### ISSUE THREAD

**Issue by BZngr** [rubberduck-vba/Rubberduck#3895]
Requires a multi-step process to reproduce.

```
Option Explicit

Sub FirstSub()
    'On Error Resume Next
    Select Case Err
        Case 55
            'OK
        Case 55
            'Unreachable
    End Select
End Sub

Sub SecondSub(y As Byte)
    Select Case y
        Case 34
            'OK
        Case 0
            'OK
        Case 30 + 4
            'Unreachable
    End Select
End Sub

Sub ThirdSub(x As Long)
    Select Case x
        Case 55
            'OK
        Case 56
            'OK
        Case 55
            'Unreachable
    End Select
End Sub
```
To reproduce:
1. Parse/Inspect the above code.  Gets the correct result (3 unreachable)
2. Uncomment the `On Error Resume Next` and Reparse from the Code Inspection Pane.  Still gets the correct result (3 unreachable).
3. Reparse again (no changes).  Only the unreachable Case Statement from `FirstSub` is detected.

From some debugging within the UnreachableCaseInspection, the root cause (of the missing inspection results) appears to be that Inspection's Listener (subscribing to the `EnterSelectCaseStmt` event) is only 'hit' once after step 2.  After step 3's reparse, the number of inspection results in the code inspection pane is reduced by more than the just the two unreachable  case results.  It appears as though some inspections for `SecondSub() `and `ThirdSub()` are skipped.

Once this condition occurs, commenting out the `On Error Resume Next` statement does not 'fix' the issue.  All subsequent Reparsing only finds a single Select Case Statement (the first one).

Results after Step 1.
![image](https://user-images.githubusercontent.com/16185628/38459008-3c850d9a-3a59-11e8-914a-6caca8c1b962.png)

Results after Step 2. - added warning due to `On Error Resume Next`
![image](https://user-images.githubusercontent.com/16185628/38459022-6856bef0-3a59-11e8-91b1-17bdef51825d.png)

Results after Step 3. - Code Quality and Language opportunity results related to `SecondSub() `and `ThirdSub()` are missing
![image](https://user-images.githubusercontent.com/16185628/38459036-81a1ab4a-3a59-11e8-9b59-33afc1494917.png)

**Comment by retailcoder** [comment]
Current results after step 3:

![image](https://user-images.githubusercontent.com/5751684/113250481-95225a80-928e-11eb-80ae-5ed1697338ad.png)

Looks like it's fixed :)
