### ISSUE TITLE
Remove interop libs

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#3898]
The \libs folder contains COM Interop libraries for various VBE hosts, that were needed when the unit testing feature relied on `Application.Run` mechanics. Now that this is no longer required, we should clean up the \libs folder.

**Comment by rubberduck203** [comment]
For posterity’s sake. The now defunct source control stuff also relied on it IIRC. Good call on cleaning this up.

**Comment by bclothier** [comment]
The PR #4458 would make them needful again due to the need to know about document state via the host's OM. Thus, closing this.
