### ISSUE TITLE
Version check shouldn't display the revision & build numbers of the website build

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#3903]
The feature only looks at major & minor version numbers, so instead of this:

![Version 2.2.6672.23088 is available!](https://user-images.githubusercontent.com/5751684/38478964-387d2cfa-3b8a-11e8-8545-a1db0d05cc4a.png)

The message should say "Version 2.2 is available". That way when a debug build is deployed on the website for whatever reason, none of our tens of thousands of users (?) can tell.

**Comment by Vogel612** [comment]
FWIW, I think we should also deal with the patch part of the version. That allows us to release a clean "small" update, without incrementing the minor version. 

That release should've been "2.2.0"...

**Comment by retailcoder** [comment]
this is moot now that the website is using the GitHub API for this.
