### ISSUE TITLE
Changes in Personal Macro workbook

### ISSUE THREAD

**Issue by SystemsModelling** [rubberduck-vba/Rubberduck#3908]
I have a file 
"C:\Users\Patrick\AppData\Roaming\Microsoft\Excel\XLSTART\PERSONAL.XLSB"
Start Excel with current RD addin
Alt+F11 to enter VBE.
Alt+F4 twice to close Excel. 
I am asked if I want to save the changes in the Personal Macro Workbook.
If I do, I am not asked if I repeat the test.
So I'm guessing this is related to a recompile of the PMW

**Comment by bclothier** [comment]
Making sure - is this same as #3839?

**Comment by SystemsModelling** [comment]
That's the same message. yes.
There is no change to the code. So that's why I think it's just a recompile

**Comment by Vogel612** [comment]
Closing as duplicate then
