### ISSUE TITLE
Multi statement line interpreted as label

### ISSUE THREAD

**Issue by SystemsModelling** [rubberduck-vba/Rubberduck#3910]
``` 
DoEvents: blah
``` 

"Line label 'Doevents' is not used"

**Comment by retailcoder** [comment]
Are you *sure* the VBE itself isn't parsing it as a line label? Try indenting it...

**Comment by retailcoder** [comment]
Ok, I admittedly replied before testing it myself - apparently the VBE parses reserved keywords as such, regardless. The grammar alone can't determine if a line label is a line label, we need to hard-code the illegal identifiers there.

**Comment by SystemsModelling** [comment]
Or,
12345   DoEvents: blah

If that isn't too distasteful :-)

**Comment by Vogel612** [comment]
Hey @SystemsModelling it would be really nice if you could format the code you put into comments and issues as code by enclosing it with a "code fence" (\`\`\`). That tremendously helps readability when quickly skimming the post. Thanks!

**Comment by retailcoder** [comment]
The grammar already defines a `KEYWORD` token; we "just" need to get the grammar rule for `statementLabelDefinition` to refuse to match a `KEYWORD` token.

This `MsgBox` doesn't pop up:

```vb
Sub Test()
    End: MsgBox "Nope"
End Sub
```

So, if our `KEYWORD` list is accurate, updating `statementLabelDefinition` should do the trick.

**Comment by retailcoder** [comment]
linking #3175

**Comment by SystemsModelling** [comment]
Thanks for the reminder Vogel, it's been a while since I posted here.
``12345   DoEvents: blah``

**Comment by retailcoder** [comment]
@SystemsModelling allow me to thank you back for the invaluable quick post-release feedback! The fix for this specific issue is under way & looking good, turns out a good dozen of keywords were being parsed as line labels. You've just contributed to make Rubberduck's parser one step closer to perfection!
