### ISSUE TITLE
Prompt before wiping member attributes

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#3929]
We have a rather hard problem with the module rewriter working off the *code pane pass* tokens, and rewriting the module in-place: if the module contains members with member attributes (`VB_Description`, `VB_UserMemId`, etc.), then they get wiped out, and this can break the users' code, and there's little we can do about it.

But we *know* when a module contains members with attributes, so we could prompt/warn the user before we rewrite that module.

> This operation would result in losing the member attributes in one or more module(s).
> Proceed anyway?

If the user cancels, no code changes should be made anywhere.

This could help prevent Rubberduck from doing the very last thing we want it to do: introducing bugs.

**Comment by MDoerner** [comment]
Now that our rewriting setup has changed a bit and that we have to contexts from the attributes parse for members able to have attributes on the declarations, I would suggest to tackle the actual problem. 

My idea is to save the attributes by `QualifiedMemberName` for all affected modules when applying code pane rewriters, to hook up a new task with the state change to `Ready`, then to reapply the attributes in that task and finally unregister the task from the state changes event again.

This would mean that rewrites for modules with member attributes will trigger two parses. However, it will make sure that the attributes are there again.

Obviously, some additional work will have to be done to deal with renamed members.

**Comment by MDoerner** [comment]
Since we generally recover member attributes and the gap for renamed members is covered y issue #5278, can we close this issue.

**Comment by retailcoder** [comment]
Yup :)
