### ISSUE TITLE
Release Notes

### ISSUE THREAD

**Issue by esurbrook** [rubberduck-vba/Rubberduck#3931]
How do I suppress the question about reading new release notes when I open the IDE, after I've read them?

**Comment by retailcoder** [comment]
hmm the prompt shouldn't pop up after updating to a 2.2 build. If it still does you can disable the version-check throught the settings dialog:

![image](https://user-images.githubusercontent.com/5751684/38749363-56a26798-3f1f-11e8-93d6-2a026154e95c.png)

This could be a bug... please confirm what version you're running?

**Comment by esurbrook** [comment]
Wow that was fast.  Thanks!  And thanks for putting this software together


Erik Surbrook
Vice President, Risk Management
1331 NW Lovejoy St., Suite 700|Portland, OR 
97209
O: 503.290.5035 | C: 503.754.8322
esurbrook@creallc.com | creallc.com

**Comment by IvenBach** [comment]
In the VBE Under RubberDuck>About click the Version number and it'll copy the info to your clipboard for easy pasting.

**Comment by esurbrook** [comment]
I need to upgrade..  This (non) issue is resolved.  Thanks again!


Rubberduck version: Version 2.1.1.2532
Operating System: Microsoft Windows NT 10.0.14393.0, x64
Host Product: Microsoft Office 2016 x64
Host Version: 16.0.8431.2236
Host Executable: EXCEL.EXE
