### ISSUE TITLE
Silent crash after adding specific reference to VBA Project

### ISSUE THREAD

**Issue by mistaven** [rubberduck-vba/Rubberduck#3938]
I experience a "silent crash" when I add a VBA Project reference to a specific installed DLL and reparse the VBA project using RD 2.2.0.3086 (2.2.6672.28001).

The Reference is called "CCo" and is a COM DLL that can be used as an adapter to interact with SAP RFC libraries and allows COM-enabled application to interact with SAP's RFC libraries. It doesn't have any dependencies (for the purposes of this test anyway).

Steps to recreate:

1. Download and extract all files from: https://cco.stschnell.de/cco.zip. 
2. Register the file `CCo.dll` using `regsvr32`, for example `regsvr32.exe CCo.dll`. This will add a new reference called "CCo" to the list of references you can select in VBA.
3. Create a new Excel file and VBA Project.
4. Add the reference "CCo" to your VBA Project.
5. Click the "Ready" button on the RD toolbar.

After performing step 5, RD starts parsing and when it moves on to "Resolving References", Excel immediately quits without any kind of error message (not even a stack trace). Below is all that I have from the trace log of RD itself:

```
2018-04-17 16:47:25.3982;DEBUG-2.2.6676.7522;Rubberduck.UI.Command.MenuItems.CommandBars.AppCommandBarBase;(1182010) Executing click handler for commandbar item 'Ready', hash code 9779294;
2018-04-17 16:47:25.3982;DEBUG-2.2.6676.7522;Rubberduck.Parsing.VBA.ParseCoordinator;Parsing run started. (thread 27).;
2018-04-17 16:47:25.3982;INFO-2.2.6676.7522;Rubberduck.Parsing.VBA.RubberduckParserState;RubberduckParserState (13) is invoking StateChanged (Started);
2018-04-17 16:47:25.6032;INFO-2.2.6676.7522;Rubberduck.Parsing.VBA.RubberduckParserState;RubberduckParserState (14) is invoking StateChanged (LoadingReference);
2018-04-17 16:47:25.8082;TRACE-2.2.6676.7522;Rubberduck.Parsing.VBA.COMReferenceSynchronizerBase;Loading referenced type 'CCo'.;
2018-04-17 16:47:25.8132;TRACE-2.2.6676.7522;Rubberduck.Parsing.VBA.COMReferenceSynchronizerBase;COM reflecting reference 'CCo'.;
```
I'm using 32-bit Excel 2013 (15.0.5015.1000), VBA Retail 7.1.1068, on Win 7 64-bit SP1 (I've also tried this on a Win10 1709 64-bit with Excel 2016 with the same results.

Sorry if the above is not clear, this is my first issue - please let me know if you need any further information.

**Comment by mistaven** [comment]
I decided to try and debug this myself using my very rudimentary skills, cloning the master branch, building and then stepping through the code line by line after adding the reference.

The crash happens when the call `Task.WaitAll(loadTasks.ToArray(), token)` is made in `LoadReferences` in `COMReferenceSynchronizer.cs` (line 42):

```
try
{
    Task.WaitAll(loadTasks.ToArray(), token);
}
catch (AggregateException exception)
{
    if (exception.Flatten().InnerExceptions.All(ex => ex is OperationCanceledException))
    {
        throw exception.InnerException ?? exception; //This eliminates the stack trace, but for the cancellation, this is irrelevant.
    }
    _parserStateManager.SetStatusAndFireStateChanged(this, ParserState.Error, token);
    throw;
}
```

My very basic thought is that the crash is actually a native code crash rather than a CLR crash (hence no error) maybe caused by trying to access the object in parallel with something?

**Comment by MDoerner** [comment]
Thank you for reporting this issue. My guess is that the problem appears somewhere in the `ReferencedDeclarationsCollector`, which loads the type library into RD. (It is used in the tasks running in parallel.)
Unfortunately, I had to realize that `Task.WaitAll` will wait until all tasks have been finished. This means that the overall exception handler never catches it. We really should change the handling there.

**Comment by mistaven** [comment]
Yes, I think you're right. I did a little more investigation and it appears that the crash is repeatable and occurs when freeing a pointer `info.ReleaseTypeAttr(attribPtr);` in the `GetImplementedInterfaces` method in ComInterface.cs (line 72).

This seems to occur when inspecting the `ICOMNWRFC` Interface of the "CCo" object.

**Comment by comintern** [comment]
I missed somehow missed this issue when I was working on the COM collector last. I downloaded the .dll and examined it in oleview, but I didnt' see anything obvious in there that would make it blow up unless some of the parameters on the `ICOMNWRFC` interface aren't being processed correctly (I'd suspect a default value).

Unfortunately, the library is 32bit only and I have a 64bit Office install. Can we confirm that this is still an issue with the latest build? If so, I'll need to track down a 32bit host application.

**Comment by mistaven** [comment]
Sorry for the late reply.

I've just tried this again on 32-bit with build v2.2.0.3689-pre and unfortunately the issue still occurs.

**Comment by comintern** [comment]
I just tried this in VB6 with the current build (my only 32-bit host ATM), and it was able to process this library and gave me what appears to be a complete serialization. Note that I do not have SAP installed, and it is possible that this library uses some forward references from an SAP library.

There were a couple minor tweaks in the library reader (although I can't imagine any of the changes would have resolved this). Would it be possible for you to test this again with the current build?

**Comment by retailcoder** [comment]
@comintern I'll try with the latest build on Win7 x64 / 32-bit Office.

**Comment by bclothier** [comment]
Update - apparently releasing the typeattr corrupts the heap.

Wrapping it in a `try` block will suppress the error and allow it to continue. As far as I can tell this only happens when trying to add `IDispatch` interface to the `ICOMWRFC`'s implemented interfaces.

**Comment by bclothier** [comment]
As per chat, the consensus seems to be that while the author of the type library did something wrong since calling any release methods on the type library structs should never throw, much less corrupt the heap.

Fortunately, we can wrap the work in a `try` block and log a `Warn` level when we encounter such silliness, allow us to bind as much as we can. That seems to be suffice to prevent the crash.

**Comment by bclothier** [comment]
Unfortunately, it turns out that even though I added a `try` block with most generic `catch`, it will not actually catch the exception. When running with a VS debugger attaching, it's misleading because it lets you click `Continue` which then proceed to process as if nothing had happened. 

However when running normally, Excel will up and crash. In retrospect that makes sense, since heap has been corrupted and the "breakpoint" is coming from Excel, not RD. 

So it's not as simple as adding a `try`, unfortunately. Back to drawing board on this one.

**Comment by retailcoder** [comment]
Is the COM collector still wired-up to read .xml serialized declarations? (IIRC it was recently removed though) If so then we could have the serialized declarations available for download somewhere (here?), and bypass the throwing code while still retaining the resolver capabilities.

**Comment by bclothier** [comment]
Just to point out that from a user's POV, that implies attaching a VS debugger, ignoring the exceptions, then serializing the declarations and optionally making it available to rest of us. 

Not all users might have a VS installed. A more user-friendly approach would probably involve using tools like OleView or OleWoo, extracting the IDL file and sharing that instead. 

That said, it occurs to me that we need to double check if it's really a problem on our end. I just verified and was able to load up the IDL in OleWoo. Now, granted, the parts that deals with typeinfo in OleWoo is written in CLR C++, but so far, VBA's OB, OleView, and OleWoo (a .NET C# application with a C++ interop lib) can read the DLL without blowing up. Why not them and only us?

**Comment by bclothier** [comment]
In the end, it was actually our code that was flawed. @MDoerner  was one who noticed that we were calling `info.ReleaseTypeAttr()` after a `implemented.GetTypeAttr()`. Of course that's going to corrupt the heap. 

```
implemented.GetTypeAttr(out IntPtr attribPtr);
using (DisposalActionContainer.Create(attribPtr, info.ReleaseTypeAttr
```
