### ISSUE TITLE
Translation issues in Code Inspection

### ISSUE THREAD

**Issue by FuSoftware** [rubberduck-vba/Rubberduck#3940]
Some text seems to rely on both the installed language (English here), and the Office language (French here), giving some strange results.

Code Inspection for example gives "Consider renaming **la variable** 'oFSO'" or "**La variable** is not used"

I only foudn the issue here, but it might happen at other places.

![capture1](https://user-images.githubusercontent.com/11671860/38923930-f15b89b0-42fb-11e8-9ecc-61f1c6e83e3b.PNG)

![capture1](https://user-images.githubusercontent.com/11671860/38923638-5f1adc5e-42fb-11e8-9c96-da3fcca9056b.PNG)

**Comment by retailcoder** [comment]
Annoying indeed! Likely just a resx needing its `CurrentCulture` set along with the others, must have been missed for some reason.

**Comment by Vogel612** [comment]
IIRC we used to have similar problems... see #3607 it seems somewhat related..

**Comment by retailcoder** [comment]
#3976 should fix this

**Comment by bclothier** [comment]
The last comment indicates that this is fixed but wasn't closed. Closing in assumption it is truly fixed.
