### ISSUE TITLE
Get unit tests working in VB6

### ISSUE THREAD

**Issue by mansellan** [rubberduck-vba/Rubberduck#3953]
See https://chat.stackexchange.com/transcript/14929?m=44058227#44058227

**Comment by WaynePhillipsEA** [comment]
I'll sort this once the main PR #3935 is merged.  I think I can remove the dependency to the interface whose GUID changed between VB6 and VBA, and thus make the TypeLib API agnostic to both.

**Comment by retailcoder** [comment]
@WaynePhillipsEA  you're up! :smile:

**Comment by mansellan** [comment]
Confirmed resolved by #3958
