### ISSUE TITLE
Feature request for Code Inspection, group by By Location. Collapse ALL inspections.

### ISSUE THREAD

**Issue by PeterMTaylor** [rubberduck-vba/Rubberduck#3960]
Using Version 2.2.6685.5179 (2.2.0.3137-pre) resuming what I meant to start again as a small testing on a cDataset sheet I have to work on. This file contains the project summary of 47 modules / 35 classes / 6 forms / 117 Document objects (sheets) that needs refactoring to adapt proper coding practices that RD considers best. With the Code Inspection grouping set to "By location". Just one little annoyance with Code Inspections I want to document here is a request to collapse ALL inspections in the tree so all is closed and pick one I am working to focus.
![rd capture need collapse all option for tree](https://user-images.githubusercontent.com/2254567/39186241-18f557ba-480d-11e8-9a84-0cdee4d2e837.JPG)

**Comment by retailcoder** [comment]
One problem is that the UI is not really a tree - it's a custom *grouping grid* XAML control that we reuse in several places; I suppose we could enhance the control with better grouping capabilities, but ultimately IMO the inspection results toolwindow is *in itself* the problem... Can't wait to be able to simply remove it!

Perhaps a *module filter* could be useful and easier to implement? A bit like how inspection settings can be filtered by inspection name, results could be filtered by module/procedure name?

**Comment by PeterMTaylor** [comment]
Sounds good. Perhaps a performance benchmark of some form (thinking perhaps in minutes manually closing all inspections within one project) can be made before changing to a module filter so a comparison be realised.
