### ISSUE TITLE
Dual screen - window move 

### ISSUE THREAD

**Issue by bhames** [rubberduck-vba/Rubberduck#3977]
When moving the Code/Inspector/Todo Explorers onto another monitor (dual) and released then when moving again the 'wire-frame' will appear to the left of the  drag point.

**Comment by Vogel612** [comment]
The "wire-frame" is not our doing. That's the VBEs doing and I highly doubt we have any say in it. Happy to be proven wrong

**Comment by IvenBach** [comment]
I've not experienced any issues with moving the explorers. The wire frame doesn't shift left when I move or let go.

**Comment by ThunderFrame** [comment]
This is a windows scaling behavior, particularly when you have Display Scaling set to anything other than 100%.

**Comment by bhames** [comment]
Apologies - you are absolutely right its Display Scaling and occurs even with VB Editor pop-out boxes. I've just included a PrintScreen capture just so you see (for the others) - but yep Display Scaling of 150% (or anything greater than 100%).

![dual monitor - select todo explorer](https://user-images.githubusercontent.com/3983855/39573380-8993fb50-4ec2-11e8-979c-a2c2d13c954b.jpg)

Thanks for pointing me in the right direction.

**Comment by Vogel612** [comment]
@bhames  :+1: for the choice of wallpaper. Gotta love Ergo Proxy :)
