### ISSUE TITLE
Selection on double-click navigation isn't consistent

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#398]
When double-clicking to navigate from the *Code Explorer*, selection seems to consistently work as expected:

![correct selection from Code Explorer](http://i.stack.imgur.com/P666f.png)

But not from the *Code Inspections* list:

![borked selection from the Code Inspections](http://i.stack.imgur.com/ZMyyj.png)

**Comment by Ryankey** [comment]
What should be selected when double clicking on the inspection? The inspections currently pass the full declaration context to the InspectionResults, so in this case selecting `LAST_WEEK_ROW As Long = 77` is an easy fix.

If we want to highlight `LAST_WEEK_ROW` I *think* we'll need to change the InspectionResult class constructors to get some sort of `IdentifierName`

**Comment by retailcoder** [comment]
In the case of inspections relating to identifiers, as a user I would expect the identifier in question to be selected on double-click. Here double-click navigation selects only the first 2 characters for some reason.

**Comment by Ryankey** [comment]
Well, it's selecting the first 2 characters because `ParserRuleContextExtensions.GetSelection(this ParserRuleContext context)` has a bug I think.

```
            var startLine = context.Start.Line == 0 ? 1 : context.Start.Line;
            var startCol = context.Start.Column + 1;
            var endLine = context.Stop.Line == 0 ? 1 : context.Stop.Line;
            var endCol = startCol + context.Stop.Text.Length;
```
So in this case it's selecting startCol + Length("77"), which is only "LA".

I have a fix for that, but then the program selects the entire Declaration context "LAST_WEEK_ROW As Long = 77". I suppose I'll commit that fix for now and we can change it to only the IdentifierName later if need be?

**Comment by ckuhn203** [comment]
Possibly my fault @RyanKey. That could looks awfully familiar. If I recall correctly, under certain conditions, we get 0s in there. Which is invalid, so we adjust it one. Looks like I should have been more thorough and adjusted the end too maybe?

**Comment by ckuhn203** [comment]
Also possible that we're getting the location of the item in the parser stream instead of its location in the file.

**Comment by retailcoder** [comment]
@Ryankey the bug isn't with `GetSelection` - the problem is that the inspection is passing the whole `VariableSubStmtContext` to the inspection result; passing the context's `AmbiguousIdentifier` solves this issue.

**Comment by retailcoder** [comment]
Fixed on `VariableNotUsedInspection` and `ConstantNotUsedInspection` - more to come.
