### ISSUE TITLE
VBE Takes forever to load since version 2.26672.28001

### ISSUE THREAD

**Issue by A9G-Data-Droid** [rubberduck-vba/Rubberduck#3980]
I've been using the Rubberduck for a while and I noticed a marked change in performance recently. The new version 2.26672.28001 is great except it takes much longer to load. I end up staring at the splash screen for longer than any person would want to. 

Is this known and accepted as a result of some new way of doing things?

**Comment by A9G-Data-Droid** [comment]
I found that loading time is worse (~2 min) if you hit an exception and press the "Debug" button without having loaded VBE for that session. 

Loading time on ALT+F11 seems to be anywhere from 3-30 seconds and I can't seem to pinpoint what is causing the longer load. It could be me. Has anyone else seen this?

**Comment by retailcoder** [comment]
@A9G-Data-Droid running 2.2.6685 here, seems to load normally (3-5 seconds splash). 30-second startup is **definitely** not something that's acceptable. If this can be reproduced / confirmed to be happening on the latest build, then we need to fix it.

```
Version 2.2.6685.5179
OS: Microsoft Windows NT 6.1.7601 Service Pack 1, x64
Host Product: Microsoft Office 2010 x86
Host Version: 14.0.7197.5000
Host Executable: EXCEL.EXE
```

There's a CI build in progress; I'll update to this pre-release when it's built and report back.

**Comment by retailcoder** [comment]
```
Version 2.2.6697.14786
OS: Microsoft Windows NT 6.1.7601 Service Pack 1, x64
Host Product: Microsoft Office 2010 x86
Host Version: 14.0.7197.5000
Host Executable: EXCEL.EXE
```

~4 seconds splash.

I've deleted that CI pre-release, the [huge] PR was merged too early and I had to revert it.

But it looks like a no-repro / already-fixed so far. Can you confirm that is the case?
