### ISSUE TITLE
Indenter gives wrong indentation when functions are invoked in multiline method calls

### ISSUE THREAD

**Issue by JKAbrams** [rubberduck-vba/Rubberduck#3981]
Consider this example (which represents the expected result):

```vba
Sub createDiagram()
    Dim dimensions As typeDimension
    dimensions = createDiagram(Title:=Translate("diagram_unique_profiles"), _
                               doColor:=True, _
                               showLegend:=True)
End Sub
```

Actual result after indentation:

```vba
Sub createDiagram()
    Dim dimensions As typeDimension
    dimensions = createDiagram(Title:=Translate("diagram_unique_profiles"), _
                                                doColor:=True, _
                                                showLegend:=True)
End Sub
```

So it seems like the indenter tries to indent to the last opened parenthesis, but in this case it misses the closing of the parenthesis of the Translate function call.

**Comment by comintern** [comment]
Turns out this is completely unrelated to the function call passed as a parameter. The issue is the underscores in `"diagram_unique_profiles"`. Fix inbound.
