### ISSUE TITLE
Rubberduck.Deployment fails to build from a UNC path with a space in it

### ISSUE THREAD

**Issue by A9G-Data-Droid** [rubberduck-vba/Rubberduck#3984]
I pulled fresh from next v2.2.0.3187 and got a build error right up front.

It seems to dislike UNC paths and it truncates the string at the first space char:

> 2>------ Build started: Project: Rubberduck.Deployment, Configuration: Debug Any CPU ------
> 2>  '\\%USER%\My Documents\GitHub\Rubberduck\Rubberduck.Deployment\bin\Debug'
> 2>  CMD.EXE was started with the above path as the current directory.
> 2>  UNC paths are not supported.  Defaulting to Windows directory.
> 2>  \\%USER%\My : The term '\\%USER%\My' is not recognized as the name of a cmdlet, 
> 2>  function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is 
> 2>  correct and try again.
> 2>  At line:1 char:1
> 2>  + \\%USER%\My Documents\GitHub\Rubberduck\Rubber ...
> 2>  + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 2>      + CategoryInfo          : ObjectNotFound: (\\%USER%\My:String) [], CommandNotFoundException
> 2>      + FullyQualifiedErrorId : CommandNotFoundException

**NOTE: I have replaced my user path with "%USER%" for privacy.**

**Comment by A9G-Data-Droid** [comment]
I fixed the pre-build event command line with a bunch of quote characters:

`C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -command """$(ProjectDir)PreInnoSetupConfiguration.ps1"" -WorkingDir ""$(ProjectDir)"""`

I am working on the post build.

**Comment by A9G-Data-Droid** [comment]
I got the post build event command line to work by adding an esoteric combination of slashes and double quotes;

`C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -command """$(ProjectDir)BuildRegistryScript.ps1"" -config $(ConfigurationName) -builderAssemblyPath ""$(TargetPath)"" -netToolsDir ""$(FrameworkSDKDir)bin\NETFX 4.6.1 Tools\\"" -wixToolsDir ""$(ProjectDir)WixToolset\\"" -sourceDir ""$(TargetDir)\"" -targetDir ""$(TargetDir)\"" -includeDir ""$(ProjectDir)InnoSetup\Includes\\"" -filesToExtract Rubberduck.dll"""`

**Comment by bclothier** [comment]
Nice! I didn't think it'd work w/ UNC since I assumed it was using cmd. 

Can you please make sure to update the comments in the powershell script to explain the logic of that funky combinations of double quotes and slash for the posterity?

**Comment by A9G-Data-Droid** [comment]
Oh, it's not in the script. I modified the pre-build and post-build events. I'm not sure that comments go there.

**Comment by bclothier** [comment]
if you look in the script, there is a comment at the top describing the expected usage of the script.

**Comment by A9G-Data-Droid** [comment]
Ok, the quote magic cited above fixes the problem with command truncation at spaces but it doesn't fix the problem with running the deployment debug from a UNC path.

**Comment by A9G-Data-Droid** [comment]
Until we want to completely fix this issue.

**Comment by bclothier** [comment]
This should be addressed by the PR #4582 but not tested. Reopen if this is still an issue.
