### ISSUE TITLE
VB6 should rewrite files in-place

### ISSUE THREAD

**Issue by mansellan** [rubberduck-vba/Rubberduck#3994]
In VBA, we need to export code modules, rewrite them, then import them back. For VB6, the code is already  stored as discrete files, so in theory we could skip the export \ import steps.

I'm asking because, as I'm testing how RD fares with real-world VB6 code, I've seen a few occurrences of files getting left as their temporary names after a parse:

![image](https://user-images.githubusercontent.com/25420409/39704419-26d9ef94-5203-11e8-861e-fa9ebe7eac01.png)

Extract from .vbp:
`Type=Exe
Form=..\..\Users\USER\AppData\Local\Temp\Rubberduck\umvi55h5.45p`

This may be an result of running in debug mode and failures occurring prior to import, as it's still early days for VB6 support. However, we'd need to make sure that this can't happen in the live release, as it definitely won't win us any friends. On the flipside, it may be more dangerous to rewrite live files.

**Comment by retailcoder** [comment]
Definitely - the need to export and reimport is strictly a VBA thing, with VB6 we should be working directly with the source files.

I hate that module rewrites lose module & member attributes though...
