### ISSUE TITLE
VB6 VBForm parse errors

### ISSUE THREAD

**Issue by mansellan** [rubberduck-vba/Rubberduck#3995]
In testing RD against real-world VB6 forms, I'm finding additional parse failures with form headers.

As I find them, I'll update this issue so they can be tackled collectively.

**Comment by mansellan** [comment]
Found so far:

1) Strings can be prepended with a dollar sign:

`TextRTF         =   $"frmDocument.frx":0000`

2) Resource offsets can be in Hex (with no format identifier)

`MouseIcon       =   "frm3D.frx":014A`

3) Properties can be dotted:

`Object.ToolTipText     =   "New"`

4) Shortcut keys have a special form (exact list still TBD):

`Shortcut        =   ^N`

**Comment by mansellan** [comment]
Valid shortcut keys are:

^[A-Z]
{F[1-12]}
^{F[1-12]}
+{F[1-12]}
+^{F[1-12]}
^{INSERT}
+{INSERT}
{DEL}
+{DEL}
%{BKSP}

**Comment by ThunderFrame** [comment]
I'm not sure if you've also seen that:
- hex values are prefixed *and* suffixed with ampersands.
    `BackColor = &H00FFFFFF&`
- property names can start with an underscore
    `_ExtentX = 5741`
- frx references are *relative*, so they can include any valid path, including `\` and `:` characters.
    `TextRTF = $"C:\foo\frmMain.frx":5EE0`

Also, this is a useful test frm - https://github.com/VBGAMER45/Semi-VB-Decompiler/blob/master/Semi%20VB%20Decompiler/frmMain.frm

**Comment by MDoerner** [comment]
Thank you.

The first two should not be a problem since they are a standard hex literal and standard identifier, respectively.

For the third, we will have to see.
