### ISSUE TITLE
VBA objects procedures in worksheets

### ISSUE THREAD

**Issue by pfredin** [rubberduck-vba/Rubberduck#3999]
[Rubberduck - VBA objects procedures in worksheets.pdf](https://github.com/rubberduck-vba/Rubberduck/files/1988014/Rubberduck.-.VBA.objects.procedures.in.worksheets.pdf)
Hi,

It seems Rubberduck can't identify the code related to events procedures of an object in a worksheet.
There is an example in the attachment.
Would it be possible to adjust that?
Thank you very muc.

Best regards,

**Patrick**

**Comment by Vogel612** [comment]
See #3626 and also #2016. For now you can work around this by using `'@Ignore ProcedureNotUsed`

**Comment by Vogel612** [comment]
Actually... this is an exact duplicate of  #389, which was linked in #3626
