### ISSUE TITLE
Indent deletes and adds empty lines under procedure

### ISSUE THREAD

**Issue by SonGokussj4** [rubberduck-vba/Rubberduck#4017]
RD - Indent - Procedure

If another procedure under current procedure and there is a blank line between them then
> blank line deleted

If another procedure under current procedure and there is not a blank line between them then
> adds blank line

If another procedure not under current procedure and there is a blank line then
> everything is good

But if there is not a blank line
> adds a blank line

Video for better understanding :-)

![nmyiceu](https://user-images.githubusercontent.com/5751684/40180669-5bc03718-59b5-11e8-897f-d28730c993b4.gif)

**Comment by retailcoder** [comment]
Just to clarify the MCVE, what's your configuration for the 'maintain vertical spacing' indenter setting?

![image](https://user-images.githubusercontent.com/5751684/40180498-f74eb39a-59b4-11e8-8550-ecb6b5b71341.png)

**Comment by SonGokussj4** [comment]
Same as you. Okay, I didn't know about this. But that shouldn't remove the blank line if there is a single one, doesn't it? I think.

So. When I tried Vertial Spacing = 2, here's what happens.
From 2 blank lines it will remove the first one. On another run it will remove the second. As it is on video.
BUT when I try it for the third time, it will create not 1 blank line but 2.
