### ISSUE TITLE
No (or invisible) labels in the unit test menu

### ISSUE THREAD

**Issue by iamkylescode** [rubberduck-vba/Rubberduck#4023]
Hi

In my install of Rubberduck, I'm not seeing labels in the Unit Test menu, making it really hard to understand how to use this feature (as a new user). 

Here are my specs:
Version 2.2.6711.17170
OS: Microsoft Windows NT 6.1.7601 Service Pack 1, x64
Host Product: Microsoft Office 2010 x86
Host Version: 14.0.7177.5000
Host Executable: EXCEL.EXE

And here is a screenshot to illustrate what I'm seeing. 

![image](https://user-images.githubusercontent.com/10101986/40309775-bbd9db06-5cd8-11e8-8c7e-94ae222f89b8.png)

I do use one other com addin (MZ-Tools 8.0) but I've tried removing that add-in, restarting, and still getting the same issue.

**Comment by IvenBach** [comment]
Thank you very much for reporting this. We are aware of this behavior and it has been documented in #4011. The resolution for it can be found in that issue, nobody has gotten to it yet. Closing as duplicate.
