### ISSUE TITLE
Inconsistent false positive on 'passed ByVal and assigned a value' inspection

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#4030]
Win10, Excel2016 (desktop), RD .3280

```vba
Public Sub foo(ByVal myRange As Range)
  myRange.Value = "Bar"
End Sub
```

Generates no inspection.  However, my real code (snippet):

```VBA
Public Sub SetSummaryCell(ByVal SummaryRange As Range, ByVal value As Variant, ByVal FormatFlag As String)

  SummaryRange.value = CStr(value)
'other stuff
End Sub
```

generates the inspection.

**Comment by MDoerner** [comment]
This is not inconsistent, but still wrong. In the code snippet, for some reason the inspection thinks that the member `value` refers to the parameter `value`, which gets passed by value.  Since the potential MCVE does not have the parameter `value` and it does not reproduce the issue.

**Comment by retailcoder** [comment]
Hmm, so a resolver bug more than an inspection issue then?

**Comment by retailcoder** [comment]
Could also be an artifact of how the older inspections kind of tried to do the resolver's job - this looks like it could be a case of the inspection not using the resolved member call; investigation is needed.

**Comment by MDoerner** [comment]
It is the resolver. The inspection just looks for by value parameters with an assignment reference.

**Comment by MDoerner** [comment]
The problem seems to be that member access resolution generally fails for members of parameters. More precisely, the `MemberAccessDefaultBinding` does not take into consideration that a `lExpression` with classification `Variable` might have the `DeclarationType` `Patameter`.
I will see whether that really is the cause when I am back home tonight.

**Comment by daFreeMan** [comment]
I'm going to go out on a limb and say it _is_ inconsistent. After noting the conversation, and especially the comment about the MCVE not having the Variant parameter, I made this:

```VBA
Public Sub foo(ByVal myRange As Range, ByVal value As Variant)
  myRange.value = "Bar"
End Sub
```

and it does _not_ generate the error.

More food for thought.

**Comment by MDoerner** [comment]
Are you sure your code snippet triggers the inspection? I do not get the inspection result for the snippet.

**Comment by daFreeMan** [comment]
The MCVE does not generate the error, but my real code most certainly does.

![rd byval issue](https://user-images.githubusercontent.com/11889733/40448532-cb5f5192-5ea3-11e8-8d76-e0a8737b0bbc.PNG)


Maybe this has been obvious to the two of you, but it just hit me. The inspection is legit - I'm passing `ByVal SummaryRange As Range`, then assigning to `SummaryRange.Value`, so I am assigning to a parameter passed by value. 

However, the parameter is an object, so passing the pointer to the object ByVal really shouldn't be picked up by the inspection when I'm assigning to a property of said object, only if I'm trying  `Set SummaryRange = SomeOtherRange`. 

Right?

**Comment by retailcoder** [comment]
@daFreeMan no, you're not assigning the `SummaryRange` reference, which is what the inspection means to be flagging. You're assigning *a member* of `SummaryRange`, i.e. `SummaryRange.Value`, which shouldn't trigger the inspection in any way. This is absolutely a false positive.

**Comment by MDoerner** [comment]
Is there anything else in the method that could trigger the inspection? I cannot reproduce the issue with the snippet provided, i.e. the following code does not cause an inspection result for me, neither in a standard module nor in a class module.

```vba
Public Sub SetSummaryCell(ByVal SummaryRange As Range, ByVal value As Variant, ByVal FormatFlag As String)

  SummaryRange.value = CStr(value)
'other stuff
End Sub
```
