### ISSUE TITLE
Code Explorer not opening any object

### ISSUE THREAD

**Issue by LukeHSC** [rubberduck-vba/Rubberduck#4034]
WHen I have CodeExplorer running and refreshed, it does not open any object (Form, Module, Class). I am double clicking on the parent in the tree and also the daugthers, nothing ... : 

![image](https://user-images.githubusercontent.com/39577280/40464129-afaa42b8-5f5c-11e8-8935-d72aec6a5d29.png)

am I missing something ? I am wanting to use this as a replacement to Project Explorer.
Using MSAccess v2010

**Comment by retailcoder** [comment]
Definitely not what's supposed to happen. Does navigation work off the *search results* toolwindow (e.g. "find all references" results), and/or off the *inspection results* toolwindow?

**Comment by retailcoder** [comment]
Do you have logging enabled? If not, enable it at TRACE level, it's possible a COM exception is being thrown/swallowed. Having a stack trace might help diagnose.

**Comment by retailcoder** [comment]
The `Pending` parser state button should be saying `Ready` ...something isn't right, I'd definitely be curious to see the logs. Does it work if you click the refresh button that says `Pending` in the Rubberduck commandbar and then try double-clicking again?

**Comment by LukeHSC** [comment]
I forced a ‘refresh’ on the Code Explorer twice, now it works ….hmmm…

 

I have turned on the logging to TRACE and if happens again will let you know.

 

One request – I did have the project password locked but I turned it off and then closed MSAccess and restarted; did not help with the issue, but it would be good if RD could prompt for a password just like the MSFT Project does when you try to open an object

**Comment by LukeHSC** [comment]
on the Code Explorer issue – when I very first opened it yesterday on a medium sized project it said “Doesn’t see anything yet, refresh”, which I did. That took several mins but then worked ok-ish (per problems noted yesterday eventually worked)

 

I closed up work last night and opened the project again and when RD fires up it says again “Doesn’t see anything yet, refresh” ? I did so and again takes a few mins (~2.5) to refresh -  that will be a bit of a pain as I open and close the project (or others) a few times a day to do backups. That said, I see it sort of does it in background but it does slow my VBA response down.

 

Does RD not keep a last-know good list? if not can that be added somehow?

 

 

Regards, 

 

Luke

**Comment by retailcoder** [comment]
Reading the serialized declarations from disk would be even slower, unfortunately. We do have extensive caching going on, and strive to only process what needs to be processed, but once the host process triggers a shut-down of the add-in, all the cached knowledge is freed, and you get back your RAM.

["Inside Rubberduck, pt.2"](https://rubberduckvba.wordpress.com/2017/07/19/inside-rubberduck-pt-2/) explains everything there is to know about how parsing & resolving works.

**Comment by comintern** [comment]
Closing this as stale, as it appears to revolve around the code that was re-written in #4661 

If this persists in the current build, this can be re-opened.
