### ISSUE TITLE
Adding Custom LINQ Expressions to Code Inspection

### ISSUE THREAD

**Issue by robodude666** [rubberduck-vba/Rubberduck#404]
Would be cool to support custom LINQ expressions, so users can monitor things specific to their business needs. Could maybe be tied to #403 to power metrics.

**Comment by ckuhn203** [comment]
Can you elaborate on what you're looking for here please? Are you looking for delegates in VBA? Like, actually *Linq*?

**Comment by retailcoder** [comment]
Relevant (somewhat): http://codereview.stackexchange.com/questions/66706/wait-is-this-linq

**Comment by robodude666** [comment]
Changed the title to be more specific. Something along the lines of the Code Inspection window, but with the ability to add in custom expression... Along the lines of what (VBDepend's CQLinq)[http://www.vbdepend.com/cqlinq.aspx] offers.

Taking from VBDepend's examples, I could add a Code Metric called "Methods have <30 Lines" and set it to:

```
from m in Methods where m.NbLinesOfCode > 30 select m
```

This would then record the # of methods/procedures that have more than 30 lines of code. I'd be able to see the # of procedures, as well as a specific list.

-Eugene Vaynshteyn

**Comment by retailcoder** [comment]
Oooh I like this, very very much. Like some kind of expression evaluator that we could translate into LINQ expressions that query the `Declarations` API.

This would require implementing a brand new ANTLR grammar specifically for this.

**Comment by ckuhn203** [comment]
:+1:

**Comment by robodude666** [comment]
I'm sure it'll take a lot of work to implement, however, it might provide a unified way of creating future Code Inspection items while allowing users to produce their own for their business's needs.  The custom expressions would need to be exportable/importable to be shared between colleagues.

**Comment by retailcoder** [comment]
related: #191

**Comment by ckuhn203** [comment]
`INode`? Wow. That's been out the window for a while now. Worth reviving the concept I'd say.

**Comment by retailcoder** [comment]
@ckuhn203 not `INode`... `Declaration` :)

**Comment by ckuhn203** [comment]
I wasn't sure about this at first, but it's absolutely possible. Definitely a big feature though. We can use ANTLR to create a domain specific query language for the user. Considering its for VBA, I recommend we go with a SQL like syntax. 

Select From Methods 
Where LineCount > 30

Select From Properties
Where Module.Name Like "Foo*"

Etc. I like this. *A lot.*

**Comment by PeterMTaylor** [comment]
Sounds like a good feature. Thumbs up.

**Comment by retailcoder** [comment]
great feature, but ...out of scope (and quite massive all by itself!)
