### ISSUE TITLE
IRefactoringDialogs should not use Windows Forms API

### ISSUE THREAD

**Issue by Vogel612** [rubberduck-vba/Rubberduck#4043]
It was noted in #4006 that the `Windows.Forms` namespace is still in use for `IRefactoringDialog` usages. 
That's not really a good solution and the result of a dialog invocation should be replaced by an appropriate type (either `bool` or the same enum that's noted in #4042)

**Comment by bclothier** [comment]
This already has been addressed in PR #4072
