### ISSUE TITLE
COM collector issues

### ISSUE THREAD

**Issue by mansellan** [rubberduck-vba/Rubberduck#4045]
Several type libraries commonly used by VB6 fail to fully load COM documentation, leading to names not being set. Need to examine how OleWoo handles these so that references are loaded correctly.

**Comment by mansellan** [comment]
Removing VB6-specific tag, as it also applies in VBA:

1. Add a Common Dialog
2. Add some code to access common dialog
3. Parse

Yields a resolver error.

**Comment by comintern** [comment]
See [this in chat](https://chat.stackexchange.com/transcript/message/45603555#45603555).
Ref also #4045, #4091, and #4174.

**Comment by mansellan** [comment]
OK, so this is `vb6-specific` after all.

It seems that the References collection of VBProject (sometimes?) returns the [OCA](https://stackoverflow.com/a/4055171/8658841) file rather than the OCX. These then fail to collect properly with COMExceptions on certain calls to ITypeInfo::GetDocumentation.

**Comment by comintern** [comment]
@mansellan Can you test this in VB6 when you get a chance? If this is still broken, can you shoot me an oca file? It might be a couple days before I get VB6 installed.

**Comment by mansellan** [comment]
Resolved by #4040
