### ISSUE TITLE
Is there a discussion group for RD..?

### ISSUE THREAD

**Issue by spinjector** [rubberduck-vba/Rubberduck#4048]
Sorry to open an issue like this, but I've been trying to locate a discussion forum of some sort where questions not in the documentation can be asked. I've googled for it, looked here and on StackOverflow, but I have yet to find any forums. Is there such a thing? If so, where might it be..?

**Comment by IvenBach** [comment]
https://chat.stackexchange.com/rooms/14929/vba-rubberducking is where we discuss most anything RD related.

**Comment by daFreeMan** [comment]
If you're not already on Stack Exchange, you'll need an account. You also need 50 magical internet unicorn SE points to talk in chat, but one of the admins can (and will) grant you explicit rights until you hit that mark on SE/SO.

**Comment by Vogel612** [comment]
For the record: Questions regarding the development and inner workings of Rubberduck are best asked in the war room Iven mentioned above.

Any question about using Rubberduck itself, (e.g. why a certain inspection result is shown) may be in scope for stackoverflow. See the [rubberduck tag on StackOverflow](https://stackoverflow.com/questions/tagged/rubberduck) for more examples and usage guidance
