### ISSUE TITLE
PermissiveAssertClass not permissive enough for tests

### ISSUE THREAD

**Issue by IvenBach** [rubberduck-vba/Rubberduck#4050]
Setup
```
Dim Assert As Object
Set Assert = CreateObject("Rubberduck.PermissiveAssertClass")
Dim foo As Long
foo = 10
```

A test that has
```Assert.AreEqual "10", foo``` <-- Passes
```Assert.AreEqual 10, foo``` <-- Fails

I'd expect that anything that VBA considers as the same would pass: ```"10" = 10```, ```cint(10) = clng(10)```, ```cdbl(10) = 10```, etc...

I created a test in VS and got a passing result. I'm not understanding something or the `PermissiveAssertClass` needs a little work.
```
[Category("Unit Testing")]
[Test]
public void TestVBAIntAgainstLong()
{
    var assert = new PermissiveAssertClass();
    const short foo = 10;

    assert.AreEqual(foo, Convert.ToInt32(10));
}
```

**Comment by Vogel612** [comment]
I wonder whether this is to do with how the values are marshalled.

**Comment by IvenBach** [comment]
I copied everything from https://github.com/rubberduck-vba/Rubberduck/blob/next/RubberduckTests/UnitTesting/AssertTests.cs to make tests for the `PermissiveAssertClass`.

Edited https://github.com/IvenBach/Rubberduck/blob/InvestigatingPermissiveAssertClass/RubberduckTests/UnitTesting/PermissiveAssertTests.cs#L322 since test is expected to pass.

Something that doesn't seem right is https://github.com/IvenBach/Rubberduck/blob/InvestigatingPermissiveAssertClass/RubberduckTests/UnitTesting/PermissiveAssertTests.cs#L179 and https://github.com/IvenBach/Rubberduck/blob/InvestigatingPermissiveAssertClass/RubberduckTests/UnitTesting/PermissiveAssertTests.cs#L209 aren't getting the expected values. Shouldn't these tests be passing without requiring any changes?

The last two I'm not sure on. https://github.com/IvenBach/Rubberduck/blob/InvestigatingPermissiveAssertClass/RubberduckTests/UnitTesting/PermissiveAssertTests.cs#L199 and https://github.com/IvenBach/Rubberduck/blob/InvestigatingPermissiveAssertClass/RubberduckTests/UnitTesting/PermissiveAssertTests.cs#L307

**Comment by IvenBach** [comment]
With https://github.com/IvenBach/Rubberduck/tree/InvestigatingPermissiveAssertClass I've been able to get the results I've seen from VBA. I not trying to duplicate any work, but this is how I know to solve the restrictive permissiveness.
