### ISSUE TITLE
Version in 'About' box doesn't match downloaded version #

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#4052]
I downloaded and installed CI build `2.2.0.3291` and that's the version number shown on the splash screen.  However, when I go to RD | About, it shows me version `2.2.6720.27013`.

It seems one is from `RD.core` and one is from `RD.main`. I'm not sure which is which, but `2.2.0.3291` is much more useful for "mere users" than `2.2.6720.27013`, and it would be nice if the shorter version, which matches what the install file is named, were to be displayed in the "About" box, too.

**Comment by retailcoder** [comment]
Yeah. Looks like the "get assembly version" logic is duplicated - that didn't matter until RD.Core was pulled out of RD.Main, but now we need to encapsulate the logic in a service that both the splash and the about box can use and display the version of RD.Main.

**Comment by bclothier** [comment]
That's probably `Rubberduck.Deployment`'s responsibility now.

**Comment by retailcoder** [comment]
@bclothier I wouldn't think so. Making the assembly versions match would be though, but I'm thinking of simply injecting a service that's implemented in RD.Main, that way we wouldn't be "cheating" and would be actually using the exact same versioning source everywhere.

That said it wouldn't be a bad idea to use RD.Deployment to make the assembly versions match across the board either.
