### ISSUE TITLE
Cached VBProjectParseResult instances remain in memory

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#406]
I'm not able to come up with clear repro steps for now, but the bottom line is that the cached parse results are not cleared when the workbook is closed, and that *can* cause an exception (that's where I want the repro) to be thrown when we try to access code modules that are no longer in the VBE.

Since we can't detect exactly *when* a VBProject is removed from the IDE, we need to add an extra check in the `RubberduckParser` that verifies whether the cached results are still worth keeping, and takes out the trash before it starts stinking.

**Comment by ckuhn203** [comment]
How hard is it to get to the projects in the parser? I'm thinking the check will look like this. (Psuedo code)

    foreach(var project in cache)
    {
         If VBE.VbProjects.Any(p => p.Equals(project))
         {
               continue;
         }
         
         KillCachedProject(project);
     }

**Comment by retailcoder** [comment]
https://github.com/retailcoder/Rubberduck/blob/59e0fa7a485eaa5ed9d17c598044e59898c027c9/RetailCoder.VBE/VBA/RubberduckParser.cs#L19

**Comment by ckuhn203** [comment]
We might be able to leverage the [ItemRemoved event][1] to invalidate the cache. At least as it relates to this. To the best of my knowledge, there's still no way to invalidate a module's contents short of listening for keystrokes on the active code pane. 

[1]:https://msdn.microsoft.com/en-us/library/aa241514(v=vs.60).aspx

**Comment by retailcoder** [comment]
The `ItemRemoved` event unfortunately only seems to exist in an interface that has no exposed implementation in the VBIDE library. We're stuck here.

**Comment by JimmyHoffa** [comment]
I know nothing about this app but something like [this](https://gist.github.com/JimmyHoffa/24826bba09d3c8028f68) might do your cache eviction just fine... Maybe. Meh.

**Comment by ckuhn203** [comment]
Thanks @JimmyHoffa

**Comment by retailcoder** [comment]
Closing, seems this issue was "forgotten" - the 2.0 parser rewrite changes everything about how this works.
