### ISSUE TITLE
Should RubberduckTests project use automocking? 

### ISSUE THREAD

**Issue by bclothier** [rubberduck-vba/Rubberduck#4062]
Want to present this for discussion. I've observed that unit tests are quite brittle, especially when refactoring involves changing the constructor parameters and we have lot of objects that has non-trivial constructor injections. 

Currently, the tests will directly `new` up any objects it needs to fulfill the dependencies to execute. It does not use any IoC at the moment, and depending on who you listen to, some may regard using IoC in a UT as a code smell. 

However, from this [SO thread](https://stackoverflow.com/questions/1465849/using-ioc-for-unit-testing), Mark Seemann mentions the idea of auto-mocking things, which is expanded in [this article](http://blog.ploeh.dk/2013/03/11/auto-mocking-container/). He mentions *Fragile Test Smell*, which I think definitely applies to our test project.

There is an [example of how we can set up automocking with CW](http://blingcode.blogspot.com/2010/12/auto-mocking-nsubstitute-with-castle.html). 

Is this something we should consider doing? Why or not?

**Comment by retailcoder** [comment]
Using the same IoC configuration as the "production code" would be dead wrong indeed, if that's what "IoC in UT is a code smell" stands for. Otherwise I don't see what the problem is with having a "test IoC configuration" that wires up the mocks automatically. It could actually be rather beneficial.

The challenge would probably be to make sure we only construct the minimal dependency tree for the system under test, without needing an IoC config module per test class.

**Comment by MDoerner** [comment]
Personally, I think the problem with the tests is not that there is no IoC; the problem rather is that there are too many tests not fully using the centrally provided mocks.
For all the refactorings I did to the parsing process, I basically only had to adapt these central mocks. I only had to change families of tests that did not already have a proper method for their purpose in the centralized mocks.

**Comment by bclothier** [comment]
I agree that we need to centralize the mocks. I guess the question is whether we should consider use IoC to help with the centralization or continue to handle them by hand. 

Looking at my refactoring branch with fresh eyes, I realize a problem; if the unit test has to create an instance of a `***Refactoring` class it will implicitly call the `_factory.Create(model)`. When the refactoring class is a subject under test it makes no sense to mock this up, but without the IoC registration, it won't create the presenter using appropriate stubs. 

Unless there's any objections, I'm going to try and set up a minimal registration scheme for the refactoring dialogs and have the unit tests use that, and resolve the concrete classes provided by the factory to the stubs within the test project.
