### ISSUE TITLE
Consistent crash with build 3347

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#4063]
I installed build 3347 this afternoon and I'm getting a consistent crash in Access 2016 (desktop) running on Win10. I was running build 3342 all day yesterday and having no issues whatsoever. I've gone back and forth between the two several times and it's consistently crashing in 3347 right at the end of the initial parse.

3347 log:
[RubberduckLog.3347.txt](https://github.com/rubberduck-vba/Rubberduck/files/2077784/RubberduckLog.3347.txt)
3342 log (for comparison):
[RubberduckLog.3342.txt](https://github.com/rubberduck-vba/Rubberduck/files/2077786/RubberduckLog.3342.txt)

Both logs generated this afternoon immediately after the initial parse/crash from the same .ACCDB after confirming that the crash was consistent in .3347

**Comment by mansellan** [comment]
Hmm.... neither one of those logs looks healthy.

**Comment by mansellan** [comment]
No repro with Access 2010 running from source (next):

2018-06-06 21:31:05.0539;TRACE-2.2.6731.38670;Rubberduck.Common.LogLevelHelper;
	Rubberduck version 2.2.6731.38670 loading:
	Operating System: Microsoft Windows NT 6.2.9200.0 x64
	Host Product: Microsoft Office 2010 x86
	Host Version: 14.0.7195.5000
	Host Executable: MSACCESS.EXE;

**Comment by daFreeMan** [comment]
FYI - happened in build .3355, too, so no automagic fixing.

[RubberduckLog.3355.txt](https://github.com/rubberduck-vba/Rubberduck/files/2080562/RubberduckLog.3355.txt)

**Comment by MDoerner** [comment]
Are you experiencing this on a new Access database or do you reference additional libraries? If the latter is the case, this might be important to reproduce the issue.

**Comment by daFreeMan** [comment]
@MDoerner I have quite a number of additional libraries...
![rd libraries](https://user-images.githubusercontent.com/11889733/41238443-f0e2803c-6d63-11e8-98d4-7c766e9510a0.PNG)

On the bright side, this seems to have been resolved by build .3357 as referenced in #4059. I'm currently running that build and haven't had a crash yet - usually it happened during or just after the initial parse, so all is looking good. 

I'll run for a day or two with this build and close this out if all seems to be going well.

**Comment by MDoerner** [comment]
As the last comment reports this as fixed, I close the issue.
