### ISSUE TITLE
cannot turn off the autocomplete

### ISSUE THREAD

**Issue by LukeHSC** [rubberduck-vba/Rubberduck#4064]
running build 3342 : I cannot turn off the Autocompletion Settings. I tried several times, and am pressing OK once I have deselected them all:
turned all off:
![image](https://user-images.githubusercontent.com/39577280/41072528-be011ea0-6a41-11e8-8e02-7e4e59d114de.png)

then to back and they are on again?
![image](https://user-images.githubusercontent.com/39577280/41072537-c9c6edb4-6a41-11e8-9ec3-ebc9aba9ec64.png)

**Comment by retailcoder** [comment]
Currently investing exactly this 👍

**Comment by retailcoder** [comment]
hmm, the page needs "select all" and "deselect all" buttons.

**Comment by retailcoder** [comment]
Fix under way: the `AutoCompleteSetting.GetHashCode` override was only using the `Key`, ...and ignoring the `IsEnabled` property, which made the loader overwrite settings with the defaults *every time*.
