### ISSUE TITLE
Autocompletion settings won't save (inconsistently)

### ISSUE THREAD

**Issue by brett-x** [rubberduck-vba/Rubberduck#4067]
Hi there, 
I'm running
Version 2.2.6729.39221
OS: Microsoft Windows NT 10.0.16299.0, x64
Host Product: Microsoft Office 2016 x64
Host Version: 16.0.8431.2250
Host Executable: WINWORD.EXE

I'm using vba off and on, and have only dabbled with Rubberduck a bit. As much as autocompletion might help when writing new code, I'm mostly editing old code, so I want it turned off for everything. I went into settings and turned them all off. I clicked OK (not cancel), but the settings are still on. (I see the behavior and all options are checked when I go back to Settings.)  
I am not an administrator on my machine (🙄) so that might be a part of the issue. But I did successfully save the settings in the past... and once they did stick today until I closed and opened a new document. 
Steps to reproduce (for me, most of the time): 
Select Settings-> autocompletion and de-select at least some options
Click Ok
Select Settings-> autocompletion  = the settings are back to defaults. 

Side note, it would be nice to have a select/deselect all option on that screen. 

Thank you.

**Comment by retailcoder** [comment]
Already implemented/fixed (including select/deselect all). Try the latest-latest prerelease =)

**Comment by retailcoder** [comment]
Also note, AC will see more tweaks in the very near future: I'm getting them to work off WM_CHAR and WM_KEYDOWN messages now, at the code pane level - currently AC is working off caret messages at application level, and that's making inline completions (e.g. double quotes) rather behave annoyingly, especially when backspacing & deleting.

**Comment by brett-x** [comment]
Thank you thank you! And yes, inline completions with deleting was a major reason I wanted them disabled. But I also noticed that it unexpectedly put a "Next" inside a loop that already had the appropriate one. I don't even know when it did that or what I was doing a the time. I'm generally not a fan of AC for these reasons. Thank you again though.
