### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by RaymondWise** [rubberduck-vba/Rubberduck#4070]
I recently reformatted my machine, installed office, downloaded the last official release (of RD) and installed as admin. I did this several times, but the folder in %ProgramData% had nothing but "uninstall" in it - as well as the start menu folder.

It installed/uninstalled fine three times. Eventually the ProgramData showed up, but it still didn't load until I merged `Rubberduck.RegisterAddIn`

I couldn't find anything in the Event Viewer. Win 7, Office 2016. I know this report is pretty useless without better detail, but I just wanted to document it. Cannot reproduce.

**Comment by bclothier** [comment]
Just to clarify - was the install working in spite of not having anything in the `%ProgramData%`?

I don't follow the part "it still didn't load unitl I merged `Rubberduck.RegisterAddIn`" -> merge what how? Are you referring to the batch file that is via the start menu?

**Comment by RaymondWise** [comment]
Terrible wording. No data in Program Data, no add-in loaded, no errors. It just wasn't there.

A folder called RubberDuck would appear in the start menu, but the only thing inside would be the uninstaller, not the repair

Merge into the Registry from `C:\ProgramData\Rubberduck`

**Comment by bclothier** [comment]
That helps clarifies it, thanks. Only one more thing I need to know which version is this we're trying to install? The last green version? 

IIRC, the fix for admin auto-registration came after that release and would be a pre-release.

**Comment by RaymondWise** [comment]
Yes, the last green version

**Comment by bclothier** [comment]
In that case, i think that is expected given the present state. 

See #3948 -- maybe you can download that pre-release and see if it works.
