### ISSUE TITLE
Rubberduck Toolbar and Test Explorer Missing

### ISSUE THREAD

**Issue by GingerNins** [rubberduck-vba/Rubberduck#4073]
I just installed the latest stable version for a single user (non-admin account) using Win 7/Office2016.  When I open the VBA editor in Excel and add the reference to Rubberduck to my project, there's no toolbar or Test Explorer window.  I've tried restarting and reinstalling the add-in and still no luck. 

The editor recognizes the classes when I try writing a test, but since I can't get to the explorer window, I am unable to run any tests. 

Thanks in advance

![image](https://user-images.githubusercontent.com/28609617/41253826-8cc39380-6d8f-11e8-868a-8f859cc6b373.png)

![image](https://user-images.githubusercontent.com/28609617/41253859-a22b3aac-6d8f-11e8-88ff-831b2d19bd26.png)

**Comment by retailcoder** [comment]
Rubberduck isn't loaded - there would be a "Rubberduck" menu between "Add-Ins" and "Windows" if that were the case. Note that a number of fixes were made to the deployment process and installer since 2.2.0 was released. @bclothier what's the best prerelease build to use again?

**Comment by GingerNins** [comment]
I actually got it to work.  I was skipping the register step.

**Comment by bclothier** [comment]
@GingerNins  just so i'm absolutely sure I'm not missing something in the installer - we are referring to the last step in the installer where the register is ticked by default? You unticked that and tried to use it so?

**Comment by retailcoder** [comment]
@bclothier IIRC that checkbox wasn't there yet in the 2.2.0 build.

**Comment by GingerNins** [comment]
I can't remember if it was checked or not, but when I went through the install again I knew I hadn't done it before (so I either left it checked or checked it).
