### ISSUE TITLE
Overenthusiastic code completion

### ISSUE THREAD

**Issue by SteveLaycock** [rubberduck-vba/Rubberduck#4074]
I upgraded from .3300 to .3355 and then .3357.

In these two latter versions code completion appears to be going a bit haywire with the addition of spurious block completions and sets of parentheses to function calls.  It is like Rubberduck no longer recognises the current closure or paretheses.

Removing rubber duck sees normal behaviour again.  Resinstalling .3300 gives normal behaviour.  Reinstalling .3357 sees the odd behaviour appearing again.

e.g.

if len(a_string) = 0  then
When typing this the closing ')' is automatically inserted. However, if I then move the insertion point to just after the '(' another ')' is automatically inserted to give

if len()a_string) = 0 then

Backspacing to delete the surious ')' does not delete the ')'

Similar problems exist with 'End if''s and similar.

**Comment by retailcoder** [comment]
AutoComplete is very much WIP still. AC in these prereleases is being triggered by caret messages. [This build](https://ci.appveyor.com/api/buildjobs/4occj7lpp03272or/artifacts/Rubberduck.Deployment%2FInnoSetup%2FInstallers%2FRubberduck.Setup.2.2.0.3358-pre.exe) from #4071 (not merged yet) uses much more reliable WM_CHAR and WM_KEYDOWN messages instead - if you can confirm whether that build fixes the problem (seems to be the case for me), then I can incorporate any further needed changes as part of that PR.

**Comment by retailcoder** [comment]
FWIW the later pre-release builds have "autocompletion settings" working, so you can selectively disable/enable specific autocompletions as you see fit - I would definitely recommend trying .3358 though: backspacing, deleting, and autocompleting in general (both inline and block completions) works MUCH better now; I just need to make a couple of tweaks before the PR can be merged.

**Comment by retailcoder** [comment]
fixed with #4071
