### ISSUE TITLE
AutoComplete - Exit Function bug

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#4085]
In build .3384, I typed:

```VBA
Private Function Foo() As String

  On Error GoTo ErrorHandler
  
ErrorHandler:

End Function
```

Realizing I had forgotten a line, I went above the `ErrorHandler:` line and typed `Exit Function`. I hit {Enter} to complete the line and ended up with:

```VBA
Private Function Foo() As String

  On Error GoTo ErrorHandler
  
  Exit Function As Variant
    
  End Function
ErrorHandler:

End Function
```

with `Variant` highlighted

**Comment by retailcoder** [comment]
ooh, nice tricky one!

**Comment by retailcoder** [comment]
`Exit Sub` and `Exit Property` presumably have the same issue.

**Comment by bclothier** [comment]
Reopening the issue because I don't think it is fixed even in latest `next`... 

Given this line:

```
Dim prop As DAO.Property|
```

Typing `enter` yields:

```
Dim prop As DAO.Property
  |
End Property
```

**Comment by retailcoder** [comment]
The rewritten block completion will work off actual parse trees, which should automatically dismiss this issue.

**Comment by daFreeMan** [comment]
I'm not sure when it happened, but as of 2.5.0.5529, the examples given do _not_ cause AC to barf, so I'm closing this.
