### ISSUE TITLE
Spelling 2.2.0 release

### ISSUE THREAD

**Issue by SystemsModelling** [rubberduck-vba/Rubberduck#4106]
Language opportunities
"Fix all occurences" --> occurrences
And all occurrences where? module?

**Comment by retailcoder** [comment]
Thanks for reporting this (typo?).

Quickfixes normally operate on a single inspection result. However some quickfixes can be executed in a batch, at various scopes:

 - In the same procedure as the selected inspection result: "Fix occurrences in procedure"
 - In the same module as the selected inspection result: "Fix occurrences in module"
 - In the same project as the selected inspection result: "Fix occurrences in project"
 - Across all processed projects: "Fix all occurrences"

So "Fix all occurrences" applies the default quickfix to every inspection result that were issued by the same inspection that issued the selected inspection result, across all issued results, regardless of scope.

I think "Fix all occurrences" is clear enough in that context.
