### ISSUE TITLE
Status bar missing context-sensitive selection label

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#4112]
Win10, Office 2016 (desktop), RD .3398

Even after a clean compile and an RD parse, the status bar is _not_ showing me any information about the identifier my cursor is currently on.

![rd missing path](https://user-images.githubusercontent.com/11889733/41607792-db682174-73b4-11e8-911d-0ebd379ac484.PNG)

**Comment by daFreeMan** [comment]
This seems to have been a very much 1 time thing. I've got the VBE opened from both Access (where I saw the problem) and Excel now, and I'm not seeing it in either.

Here's the current log. Sorry, I should have posted as soon as I saw it. This is probably a conglomeration of both Access & Excel.

[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/2116055/RubberduckLog.txt)

**Comment by Vogel612** [comment]
closing as norepro, until an at least semi-stable repro is added
