### ISSUE TITLE
VB6 should display a warning of experimental feature on launch

### ISSUE THREAD

**Issue by mansellan** [rubberduck-vba/Rubberduck#4116]
VB6 is milestoned for v2.3, however it will likely be a while before it's decently stable. In the interim we should pop a message box on launch when VB6 host is detected, warning that VB6 is experimental and to ensure that any critical code used with it is adequately backed up first (exact wording TBD)

**Comment by retailcoder** [comment]
If I used RD in VB6 I'd want to be able to dismiss that warning once and for all after seeing it once... a `MessageBox` can't do that.

Can we make an `IMessageBox` implementation that brings up our own custom WinForms dialog? We could amend the returned enum value with a flag that contains the "don't show this message again" state... and then we'd need to figure out a way to make the interface expose a method for that, which the standard/current implementation could just ignore, forwarding the call to `NotifyWarn`. Or does that smell?

**Comment by mansellan** [comment]
Good point, my only concern would be that if we implement "do not show again" in the general case, there should really be a way of resetting any flags set in the past (probably sits in settings somewhere).

Maybe not essential for this, just thinking it forward.

**Comment by mansellan** [comment]
Wondering if making a dismissable WPF dialog is too ambitious for 2.3 - maybe we don't need a dialog for this case?

**Comment by retailcoder** [comment]
Might be. In that case perhaps a custom setting similar to how LegacySmartIndenterPrompted is implemented? i.e. prompt once, change the setting, and don't bother the user with it ever again?

...or do nothing, and write something about it in the release notes.

**Comment by mansellan** [comment]
The former if time permits, the latter if not!

**Comment by mansellan** [comment]
Making this optional for 2.3. We'd need the text to be localised, and it's probably not worth it for the one-off nature, given that this could be communicated in the release notes.

**Comment by mansellan** [comment]
VB6 seems stable now, so I think the need for this has passed. Closing issue.
