### ISSUE TITLE
Unreachable case inspection does not understand enums

### ISSUE THREAD

**Issue by Inarion** [rubberduck-vba/Rubberduck#4119]
Consider
```
Option Explicit

Public Enum LogLevel
    TraceLevel = 0
    DebugLevel
    InfoLevel
    WarnLevel
    ErrorLevel
    FatalLevel
End Enum

Public Function LogLevelToString(ByVal level As LogLevel) As String

    Select Case level

        Case LogLevel.DebugLevel
            ' Reachable (as per inspection results)
            LogLevelToString = "DEBUG"

        Case LogLevel.ErrorLevel
            ' Unreachable (as per inspection results)
            LogLevelToString = "ERROR"

        Case LogLevel.FatalLevel
            ' Unreachable (as per inspection results)
            LogLevelToString = "FATAL"

        Case LogLevel.InfoLevel
            ' Unreachable (as per inspection results)
            LogLevelToString = "INFO"

        Case LogLevel.TraceLevel
            ' Reachable (as per inspection results)
            LogLevelToString = "TRACE"

        Case LogLevel.WarnLevel
            ' Unreachable (as per inspection results)
            LogLevelToString = "WARNING"

    End Select

End Function
```
As per my testing, every single case is reachable (i.e. produces the correct output string. Yet RD assumes most cases to be unreachable. (First case has value 1, and RD only deems the one case with value 0 as reachable. Every case with a higher value is considered unreachable.)

Version 2.2.6738.40126
OS: Microsoft Windows NT 6.1.7601 Service Pack 1, x64
Host Product: Microsoft Office 2010 x86
Host Version: 14.0.7197.5000
Host Executable: WINWORD.EXE
(switched to Word because there are no add-ins or other modules producing inspection noise)

**Comment by Vogel612** [comment]
Does this persist if you give all Enum members an explicit value?

**Comment by Inarion** [comment]
Good catch, @Vogel612 ; it does not persist with explicit values given:
```
Public Enum LogLevel
    TraceLevel = 0
    DebugLevel = 1
    InfoLevel = 2
    WarnLevel = 3
    ErrorLevel = 4
    FatalLevel = 5
End Enum
```
This does not trigger the inspection. I guess that narrows down the list of possible culprits?
