### ISSUE TITLE
AutoCompletion adding closing double quote at end of line

### ISSUE THREAD

**Issue by IvenBach** [rubberduck-vba/Rubberduck#4120]
Found while working on `PermissiveAssertClass` unit tests. With cursor at `|` and closing parenthesis

```
Assert.AreEqual "10|, foo
```

Becomes

```
Assert.AreEqual "10"", foo"
```

Status by design?

**Comment by retailcoder** [comment]
To clarify: AC turns " into "", that's just what it does. Now when you leave a line that ends with an uncompleted string literal, the VBE itself closes the string literal - that's the closing " that was added, by the VBE, not AC.

Upcoming updates will make it easier to remove one " given "" though.
