### ISSUE TITLE
Documentation / examples for refactoring?

### ISSUE THREAD

**Issue by SystemsModelling** [rubberduck-vba/Rubberduck#4124]
I'm right at the start here. Take refactor/rename.
I have a control on a userform I want to rename. Say it's an optionbutton optComments and I want to call it optComment.

With the userform editor, Rubberduck > Refactor all items are greyed out.
Right-click the control, Rubberduck in the context menu, Rename greyed out.

Double click the control, now in Private Sub optComments_Click()
All refactorings still greyed out.

Double click the variable optComments to select it.
All refactorings still greyed out.

How do I rename it?

**Comment by SystemsModelling** [comment]
OK, found it
Click the Ready button to reparse. In the sub now right-click and choose Rename from Rubberduck -> Refactor

BTW the option button is in a frame fraOptions so if I select the optionbutton in the form designer menu the only thing it offers to rename is the frame.

**Comment by Vogel612** [comment]
See #2058
