### ISSUE TITLE
Is the '@Folder annotation working?

### ISSUE THREAD

**Issue by SteveLaycock** [rubberduck-vba/Rubberduck#4135]
I'm not seeing annotated folders appearing in the RubberDuck code explorer(03447)

There are several syntax that appear in blogs
'@Folder FolderName
'@Folder("FolderName")

Neither seem to work at present.

Is there a help page or wiki somewhere that summarises annotations?

**Comment by retailcoder** [comment]
Stupid question: did you reparse after adding the annotations?

Annotation syntax is defined as a part of the grammar, so that they show up as such (and not as comments) in parse trees.

**Comment by retailcoder** [comment]
That said [this post](https://rubberduckvba.wordpress.com/2017/03/05/annotations-the-underducks/) is where it's at. Gotta put that in the wiki...

**Comment by SteveLaycock** [comment]
Thanks for the prompt response.

This morning my '@Folder annotations were present which left me scratching my head.

A little more experimentation showed that if I add a folder annotation in the current session they do not get added to the RubberDuck code explorer pane even when I refresh (tried from the RubberDuck menu, the pending/ready prompt , and from within the code explorer pane).

If I then save the template, close and restart the parent word document, then the new folder annotations do appear in the RubberDuck code pane.

**Comment by Greedquest** [comment]
I'd like to say I've been suffering from very similar problems, not only with the most up-to-date release. Today for example I removed a module in the code explorer, but there was no update to the UI. The module was indeed removed, but I have to restart Excel to see the effects. I'd say around 50% of the time the RubberDuck code explorer will not update with new annotations even with a re-parse. I haven't got a clue how to re-produce it though :/ Are there some logs I should post?

**Comment by SteveLaycock** [comment]
Another wrinkle I'm afraid.

I annotated a set of 8 modules with '@Folder("Ribbon").

These folders appear sequentially when viewed in VBA Code Explorer.

After closing and reopening Word I found only 3 of the modules in the '@Folder("Ribbon") folder.

I repeated this with another set of 4 modules but on this occasion all four appeared in the '@Folder

**Comment by retailcoder** [comment]
Marking as a showstopper bug, this needs further investigation.

**Comment by retailcoder** [comment]
I can't repro with 2.2.0.3456?

Exactly where in the module is the `'@Folder` annotation? The annotation must be in the *declarations* section of the module:

**Correct**:

```vb
'@Folder("Parent.Child")
Option Explicit

```

**Incorrect**:

```vb
Option Explicit

'@Folder("Test")

Sub DoSomething()
```

By specifying module-level annotations *above* module options (e.g. `Option Explicit`), you ensure that the `@Folder` annotation can't be taken as an invalid member-level annotation on that module's first member.

**Comment by Greedquest** [comment]
Looks like I have some funny error messages, reminiscent of [this ](https://github.com/rubberduck-vba/Rubberduck/issues/3704).

With the code explorer in a broken state; there should be another module listed under "UnitTests" but it is missing in the UI, I get these inspection results:
![image](https://user-images.githubusercontent.com/25348920/42037412-46e80504-7ae0-11e8-88c9-57c14e559894.png)
N.B. those results point to a module that _is_ visible in the code explorer, rather than the missing one

After saving, closing and re-opening Excel the code explorer is as it should be, but now I have these inspection results instead
![image](https://user-images.githubusercontent.com/25348920/42037575-a62f6188-7ae0-11e8-9d07-6113e6daeb80.png)
![image](https://user-images.githubusercontent.com/25348920/42037583-adaa5daa-7ae0-11e8-9084-2ec85d51a506.png)

Finally, when I make some change like changing a module's folder, I get back to an out-of-date UI and the first set of error messages

All images taken after a fresh re-parse, with no changes to the code in between

**Comment by Greedquest** [comment]
@retailcoder Oh, just saw your last. In that case, the RubberDuck unit test modules are defaulting to the wrong location for these annotations. For me at least

**Comment by retailcoder** [comment]
Something's off, your annotations *are* in the declarations section, and *should* be picked up as such.

**Comment by retailcoder** [comment]
Then again, ....no repro on that either. :confused:

**Comment by SteveLaycock** [comment]
> Correct:
> 
> '@Folder("Parent.Child")
> Option Explicit

Thanks for the clarification.  All my '@Folder annotations were after the option explicit.

COrrecting my annotations as  indicated now correctly lists all modules in the '@Folder but this still only happens after closing and reopening word.

Adding a '@Folder annotation, or indeed, renaming an annotated module, does not cause the newly annotated or renamed folder to appear after a refresh.  Word need to be closed and reloaded.

**Comment by Greedquest** [comment]
Download an [offending workbook](https://github.com/Greedquest/hello-world/blob/master/Grid_v1.xlsm?raw=true). Was able to repro on 2 computers (both latest stable RD)

**Comment by retailcoder** [comment]
@Greedquest 2.2.0 "latest stable" is well out of date by now though, we're looking at ironing out any showstopper issues in the current "next" (currently 2.2.0.3456), and then 2.3.0 is a go.

**Comment by Greedquest** [comment]
@retailcoder FWIW, 2.2.0.3460 gives same behaviour, lots of `Annotation 'ModuleInitialize' illegal in this context` errors

**Comment by retailcoder** [comment]
@Greedquest I'd have to hunt down all references to the missing library in order to try to get a repro for that; without the proper refs the resolver can't do its job, and so there are no inspection results.
