### ISSUE TITLE
Premature completion of AC

### ISSUE THREAD

**Issue by bclothier** [rubberduck-vba/Rubberduck#4136]
Given the desired output of a code like this:
`Foo("bar", "baz")`

Typing `Foo("` gets us `Foo("|")`. So far, so good.

Now type in `bar`, then type `"` again, and the cursor ends up at `Foo("bar")|`... Not so good. I prefer that it be `Foo("bar"|)` so that I can continue filling out the arguments. 

Incidentally, if the desired expression typed out is `If Foo("bar", "baz") Then`, the AC causes the line to go red as soon as we try to fill out the line. That's a bit of a distraction, especially as we weren't done with the line.

**Comment by retailcoder** [comment]
I consider this a bug; typing `"` given `|"` should result in `"|` regardless of what comes after the `"`.

**Comment by retailcoder** [comment]
Not sure I understand the bit about `If..Then` going red.. is it fixed by fixing the unexpected jumping?

**Comment by retailcoder** [comment]
This *should* be fixed now; if not then SCP needs more unit tests.

**Comment by retailcoder** [comment]
Okay, the behavior is *kind of* fixed.... *if the code is legal in the first place*.

e.g. `If foo("` goes to `If foo("|")` as expected; then typing the `"` at  `If foo("bar|") now gives `If foo("bar""|")` which is different than the previous behavior, but not entirely weird.

Re-closing the closing perenthesis "skips" over it, which is expected. I'm debating whether re-closing the double quotes should skip over too, or whether it should do what it currently does, i.e. insert a new pair.

**Comment by retailcoder** [comment]
Per chat: typing `"` given `if foo("abc|")` should result in `if foo("abc"|)`, i.e. typing the pair-closing character should skip over the existing pair-closing character. Leaving it as an open bug.

**Comment by retailcoder** [comment]
This scenario just needs a unit test, I believe it's currently fixed in #4387
