### ISSUE TITLE
Holding Delete key gives alot of autocomplete

### ISSUE THREAD

**Issue by Greedquest** [rubberduck-vba/Rubberduck#4139]
In a new module:
 - Type`Function` 
 - Hold the delete key

Repeatedly triggers AC:

![image](https://user-images.githubusercontent.com/25348920/42088961-57c9de66-7b93-11e8-911d-0993974607de.png)

**Comment by retailcoder** [comment]
hmm, the <kbd>DEL</kbd> key is supposed to just "fall through". Should be an easy fix.
