### ISSUE TITLE
Some windows wont close and can not revert to previous working release.

### ISSUE THREAD

**Issue by Stevefb** [rubberduck-vba/Rubberduck#4144]
Unit Test and Code Inspection windows works on new laptop with Rubberduck ver 2 green release, breaks with latest release - unable to go back to earlier release to get working unit test window.

What not working looks like is probably best explained with an image:
<img width="960" alt="2018-07-01" src="https://user-images.githubusercontent.com/9349975/42131869-57c3d42c-7d4f-11e8-94f6-c6dd20bb4c26.png">

When test explorer is opened the 2 windows shown in the above image overlap with the blank window being on top. Although I can run unit tests, I'm unable to close the unit test window.

Other notes: first noticed with this release - Rubberduck v2.2.0.3465-pre
New laptop running Win 10, Office 365

I tried to uninstall Rubberduck and revert to the green release. The problem persisted.  Since this is a new PC I reinstalled Windows... and created a restore point prior to installing Rubberduck.  I then installed the green release (i.e. v 2) and all was good. I then installed the latest ver of Rubberduck (as above) and problem returned. 

I then uninstalled Rubberduck (via programs and apps) and used the system restore to go back to the pre-Rubberduck state. Windows told me the restore was successful.  However when I installed the green release of Rubberduck the problem persisted.

**Comment by Vogel612** [comment]
Could you try unchecking these two windows in the Settings under "open on Startup" and restart you office host? Also is there anything in the logs?

**Comment by Stevefb** [comment]
@Vogel612  I'm travelling at the moment so not keen to test this until I get home in a few days. 

I can confirm that neither of these windows was opening on startup. I can also confirm that restarting the host (MS Word) did not help.

But, when I get home how does this test sound:

- Install the stable release
- Adjust settings so these Rubberduck windows do NOT open on startup
- Update to the latest ver of Rubberduck
- Check logs...

Have anything in mind to look for in the logs?

ALSO I'm not keen to reinstall windows again - any thoughts on why a system restore point does not resolve this issue? OR what else can be tried in an attempt to avoid reinstall?

TIA

**Comment by Stevefb** [comment]
Oh.... have just discovered that this impacts MS Word but NOT Excel on the same computer.

Also plan above has been foiled... on two counts...

 1. Apparently reinstalling (resetting) Windows no longer fixes the issue
 2. I set logging to Trace but so far the log folder remains empty 

When I tried to open the log files via the Settings UI I kept getting something that amounted to a Folder Not Found error.  I created the folders manually but...

Me thinks there is something funky with my PC 🤕 

BUT...  I've also just discovered that the issue seems to be related to docking... if I move the IDE more or less off the screen and then open the Test Explorer it would seem that, as long as the window is OFF the IDE, I can drag it and dock it onto the IDE.  Doing that - so far so good everything seems to work...

Oh and now for the FACEPALM... 

#Workaround double clicking on the blank window causes it to dock and behave (more or less) normally...  

On my PC at least: In Excel the window CAN float around the screen, in Word the window MUST be docked

**Comment by bclothier** [comment]
I think it may help to note that the settings for the docking and the window positions of toolwindows within VBE are maintained by a registry key (keys?) that is managed by VBE, not by Rubberduck. For that reason, uninstalling & reinstalling will have no effect because the keys are persisted and VBE associates the positions to the GUIDs of the toolwindows. 

In a dire situation, the option is to delete/rename the registry key `HKEY_CURRENT_USER\Software\Microsoft\VBA\X.Y\Common\Dock` where `X.Y` is either `6.0` or `7.0`. This will have the effect of totally resetting every customization regarding to your toolwindow positions for _all_ toolwindows, VBE's, any other add-ins' and of course, Rubberduck's. 

Interesting that you can't float around in Word but in Excel. That bears investigation.

**Comment by bclothier** [comment]
I'm assuming this is now stale issue and was not something to do with Rubberduck. If you are still experiencing this, please reopen and update. Thanks!
