### ISSUE TITLE
Code inspection does not finish

### ISSUE THREAD

**Issue by Gener4tor** [rubberduck-vba/Rubberduck#4150]
This it how it looks now for more than 30 minutes:

![grafik](https://user-images.githubusercontent.com/40824720/42269989-081208b2-7f80-11e8-8296-208163540770.png)

And it slows the VBE massively down.

I have a new installation and a ~50 forms + 100 modules project.

The memory consumtion is also very high. Before rubberduck, the process needed ~50mb Ram. Now it is beteen 500 and 800 Mb.

**Comment by Vogel612** [comment]
What version do you have installed? Could you please try pasting the Logs (preferrably at Trace-Level) to help us nail down the issue? Thanks!

**Comment by Gener4tor** [comment]
I use:

Version 2.2.0.3468
OS: Microsoft Windows NT 10.0.16299.0, x64
Host Product: Microsoft Office 2016 x86
Host Version: 16.0.4666.1000
Host Executable: MSACCESS.EXE

I restarted access and restarted my code inspection again:

This is the log after ~5 minutes:
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/2162920/RubberduckLog.txt)

**Comment by Gener4tor** [comment]
This is the log after ~15 minutes (Memory is still ~600 mb):

[RubberduckLog after 15 minutes.txt](https://github.com/rubberduck-vba/Rubberduck/files/2162964/RubberduckLog.after.15.minutes.txt)

**Comment by Gener4tor** [comment]
ok...now it seems to have finished (after ~25 minutes) after restarting.

Here is the Log:

[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/2162984/RubberduckLog.txt)

**Comment by Vogel612** [comment]
okay let's get some overview out of the final log:

```
12:44:25.2802 Rubberduck starts parsing
12:44:27.4863 Loading References
12:44:44.6311 Parsing Complete
12:44:45.6793 Start Resolving Declarations
12:44:47.6825 Declarations are Resolved
12:44:49.7591 Start Resolving References
12:45:29.1239 Rubberduck Reports "Ready" status
// Parsing run finished after 65,3371173s;
```

Then there's another two parse passes, the first taking 5 seconds and the second taking 8 seconds actually triggering the Inspections.

The UnreachableCaseInspection throws a NullReferenceException

Now there's a metric ton of command and hotkey rewirings, I assume you've been tabbing in and out of the VBE, and lastly we get the following messages:

```
2018-07-04 13:06:26.4155;TRACE-2.2.0.3468;Rubberduck.Inspections.Abstract.InspectionBase;Intercepted invocation of 'ObjectVariableNotSetInspection.DoGetInspectionResults' returned 307 objects.;
2018-07-04 13:06:26.4155;TRACE-2.2.0.3468;Rubberduck.Inspections.Abstract.InspectionBase;Intercepted invocation of 'ObjectVariableNotSetInspection.DoGetInspectionResults' ran for 1229404ms;
2018-07-04 13:06:26.5645;TRACE-2.2.0.3468;Rubberduck.UI.Inspections.InspectionResultsViewModel;Inspections loaded in 1231232ms;
```

So we have the following final stats:

```
Parse Run 1: ~65 ecconds
Parse Run 2: ~ 5 seconds
Parse Run 3: ~ 8 seconds
Inspections:  307 Results, two exceptions, ~1230 seconds
```

That translates to almost exactly 20 minutes running time for the inspections. That is *not* acceptable...

**Comment by Vogel612** [comment]
According to the log, the culprit is the ObjectVariableNotSetInspection ...

**Comment by Vogel612** [comment]
A bit of log-analysis suggests that Rubberduck parsed 180 modules.

**Comment by comintern** [comment]
Linking [chat](https://chat.stackexchange.com/transcript/message/46418392#46418392) so I don't forget why `ObjectVariableNotSetInspection` is so slow.

**Comment by comintern** [comment]
Removing memory-management tag - this is purely CPU bound, and over 99% of the processing time is spent on one line of code:

![screenshot from 2018-08-27 23-09-22](https://user-images.githubusercontent.com/8944005/44700444-abb90300-aa4e-11e8-9f64-fdd5aa0e5f90.png)
