### ISSUE TITLE
RD displays notification about new version on every startup (while running the latest pre-release)

### ISSUE THREAD

**Issue by Inarion** [rubberduck-vba/Rubberduck#4151]
Likely related to  [#4052](https://github.com/rubberduck-vba/Rubberduck/issues/4052).

I've updated RD today (from a build a few weeks old to **2.2.0.3468-pre**) and now on every launch, RD notifies me that 

> Rubberduck version 2.2.6672.23088 is now available! Would you like to review the release notes now? [Yes/No]

This doesn't seem like the intended behavior. As such, @MDoerner asked me to open this issue.

**Comment by Vogel612** [comment]
Needs to be adressed before the next stable release!

**Comment by retailcoder** [comment]
My bad. I never updated the website build with 2.2.0, so it's an old debug build up there. There's no bug, just the version-comparison logic falls apart if a non-release build is deployed to the website. I just need to overwrite the file with the actual 2.2.0 build and it'll fix itself. I can do that tonight.

**Comment by retailcoder** [comment]
http://rubberduckvba.com/build/version/stable now reports 2.2.0.0, and next green release I'll make sure to have build 2.3.0.0 online so that this doesn't happen again.
