### ISSUE TITLE
Access crashes while writing in Code window

### ISSUE THREAD

**Issue by Gener4tor** [rubberduck-vba/Rubberduck#4154]
* opened my project
* Navigated to a codefile (a Form). It does not matter if I used the Rubberducks modul-explorer or the built in one
* uncommented a line
* wrote "Call ZFormHelper." => the autocompete list opens
* chosen "Bildobjekt" as a function
* tried to write "(" to continue => access crashes

This is the log:
[RubberduckLog Crash.txt](https://github.com/rubberduck-vba/Rubberduck/files/2163621/RubberduckLog.Crash.txt)

I restarted access several times but I crashed every time I tried to write the "(".

After unloading Rubberduck access was not crashing anymore and I was able to write the line.

I loaded Rubberduck again, but the crash is not reproducible anymore...

Here is my version:

Version 2.2.0.3468
OS: Microsoft Windows NT 10.0.16299.0, x64
Host Product: Microsoft Office 2016 x86
Host Version: 16.0.4666.1000
Host Executable: MSACCESS.EXE

**Comment by retailcoder** [comment]
Linking #4141

There's a bug in the autocompletion (exact repro steps still not confirmed though) that makes inline completion crash the process (unhandled off-by-one error, most likely).

You can disable `(`, `{`, `[` and `"` autocompletion to remove the possibility for this bug to happen.

**Comment by retailcoder** [comment]
Another work-around is to avoid `Call` altogether.

In fact, I've got the off-by-one under control, but a quirk of the VBE is literally preventing the insertion of the empty parentheses - they get "helpfully" removed as soon as they're inserted, making the `(` keypress feel like it's simply not working.
