### ISSUE TITLE
Font size in code explorer

### ISSUE THREAD

**Issue by SteveLaycock** [rubberduck-vba/Rubberduck#4155]
Could could I make a polite request to increase the text size in the code explorer window as its rather small for my aged eyes.

In the longer term could we have a setting so this is user configurable in panes that RubberDuck provides.

**Comment by retailcoder** [comment]
Tagging with difficulty 01 because no prior knowledge of how Rubberduck internals work is needed for implementing this - however it does require some experience with WPF and styling: we need these font sizes / styles in a centralized place, so that the UI can be consistent across the board.
