### ISSUE TITLE
The parser part of the parsing process needs some refactoring

### ISSUE THREAD

**Issue by MDoerner** [rubberduck-vba/Rubberduck#4156]
Currently, the organization of the parser is kind of a mess. Too many things are interwoven that do not belong into the same place and things are done in multiple places although they could be done in one place. Examples can be found in multiple places:

1. The parser does not properly separate getting the code and getting the token stream from the code: both happens in `RewriteAndPreprocess` and in the `AttributeParser`. 
2. The preprocessing logic is duplicated in the `AttributeParser`, which is organized difererntly relative to the `VBAModulePArser`.
3. The `VBAModuleParser` also runs listeners after parsing, which should not be its job.

With a proper design, a PR like #4153 would not be necessary at all.

So, here is a short list of things of which I think that they would improve the design:

1. Split the step of getting the code for the code pane pass from getting the token stream.
2. Make the preprocessor a decorator for the `ICommonTokenStreamProvider` that simply provides the proprocessed token stream. (The other parameters can be injected via constructor or property injection.)
3. Move running the listeners from inside the parser to after returning the parse tree from the parser.
4. Turn `VBAModuleParser.Parse` into a function taking only a token stream and returning an `IParseTree`. Everything else, i.e. the error listener and the module name, should be injected via the constructor or via property injection. 
5.  Remove the `AttributesParser` and replace it with a second run of the usual parser, just on a code string from another source. 

This list is just what immediately came to mind.

Please feel free to comment and/or add additional suggestions.

**Comment by bclothier** [comment]
Good points all around. I only have a question - is there something we can do with the PR #4153 so that it can help move toward that ideal you describe?

**Comment by MDoerner** [comment]
In a sense,  yes  and in a sense, no. What we could figure out in the PR is having we want to handle setting the parsing mode strategy. But maybe this will look different in the final design.

I can currently think of three ways to go for the class parsing token streams into parse trees:

1. Have one class per parsing mode strategy with the actual antlr parser getting constructor injected. 
2. Having a base class implementing the three strategies in different methods and choosing based on a settable property.
3. Like 2, but with the Antlr parser getting constructor injected instead of having separate subclasses. 

Since the SLL and LL parsing might need different error strategies, we should pass in separate error handlers for both on construction. For option 2 and 3, we would always have to provide both whereas in option 1 we would only have to pass in the strategies we need. (We might need different strategies because it makes no sense to try to recover from an error in SLL mode.) This would be an advantage of option 1.

The other two options have the advantage that the mode is settable instead of hard coded. Hard coding the available strategies should not be a problem since I really cannot think of any besides _pure SLL_,  _pure LL_ and _SLL with fallback to LL_. 

One other thing that came to my mind is to also have a `CodeParser` wrapper with functionality akin to the proposed `CodeSnippetParser`. That would take an `ICommonTokenStreamProvider` and a module parser as constructor arguments and have a `Parse` method taking module code as a string, and maybe the module name, and returning a value tuple consisting of the parse tree and a rewriter. That would conveniently encapsulate our handling of the token stream. Then all module parsing would basically look like snippet parsing, just with a different source for the code.

**Comment by MDoerner** [comment]
I do not see a need to need to let the parser in the PR to take a module parser and provider. After all, the module parser interface will change in the refactoring.
After the refactoring, we can simply swap out the implementation of the `CodeSnippedParser`. After all, constructors are implantation details(, provided you work against interfaces and follow DI).

Regarding the code reuse between the pure and the fallback parser in option 1, the fallback one could simply be a wrapper over two parsers, falling back to the second, if it receives a syntax exception from the first. 

Still, I am not sure whether that option would be the right way to go.

**Comment by bclothier** [comment]
To be honest, while that is feasible, it feels like a confusing way to wrap things. For that reason, I'm inclined to lean toward the option 2, especially since that in both the option 2 and the parser in the PR, the mode is a property we just need to set before we run the `StartRule()`. The only thing is that the parser in the PR does not allow changing the mode after it's been constructed. That should be a trivial change to make it a settable property so that we only need one class that will provide the 3 strategies we need.

Thoughts?

**Comment by MDoerner** [comment]
Since PR #4242 has been merged, I close this issue.
