### ISSUE TITLE
Code inspection give incorrect Set warnings for variants and indexed collections

### ISSUE THREAD

**Issue by SteveLaycock** [rubberduck-vba/Rubberduck#4161]
I'm starting to use the code inspector to tidy up some code.

I'm seeing a number of warning that 'Set' is not used which appear to be incorrect.

There seem to be two two cases which are incorrect

1.  A function is returning a variant, the return assignment is flagged as the error statement
    ```
    Public Function add_id_and_id_value(ID As String, Optional Content As Variant = IS_NOT_DEFINED) As Variant
    .....
    add_id_and_id_value = Content
    ```

2.  Assignment of a value to an item in a collection

    e.g. `ActiveDocument.CustomDocumentProperties("XMLNamespace") = vbNullString`

**Comment by bclothier** [comment]
Pinging @MDoerner  to see if this should be linked to the current PR for set type resolver or would be a separate PR. Tentatively linking #4318 for now.
