### ISSUE TITLE
Inspection for use of legacy On Local Error statement

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#4166]
The `Local` keyword is a holdover from days long past, and has no meaningful effect.

RD should spot usages of:

` On Local Error GoTo 0`

and replace with:

` On Error GoTo 0`

**Comment by retailcoder** [comment]
Huh I could have sworn there already was an issue for this... can't find it. `Local` keyword was breaking the parser until the grammar began supporting it at some point in 2016... looks like the inspection for it was just forgotten.
