### ISSUE TITLE
Parse Error when CDecl specified in Declare statement

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#4167]
It seems the VBA team were planning on adding support for `__cdecl` calling conventions, and allow for `CDecl` to be specified as part of a `Declare` statement, even though it seems that `__cdecl` support never quite got delivered. This statement compiles, but causes an RD parse error:

`Private Declare Sub Beep CDecl Lib "kernel32" (dwFreq As Any, dwDuration As Any)`

The parser needs to allow for these statements, but should also perhaps have an inspection for removing the `CDecl` as it's not implemented by VBA.

**Comment by wqweto** [comment]
`CDecl` is implemented in Mac version of VBA only . In VB6 it's a noop too.

**Comment by ThunderFrame** [comment]
@wqweto Thanks for that. Is it required on mac, or optional?

It's been some time sine I last saw you active on this project - are you aware that RD support in VB6 is imminent? We'd love for you to give it a go.
