### ISSUE TITLE
New Unit Test Added inside existing Unit Test

### ISSUE THREAD

**Issue by Stevefb** [rubberduck-vba/Rubberduck#4169]
Just to be clear, this is what happened when I attempted to add a 2nd Test Method using the Test Explorer UI. 

I can confirm that happens when the cursor is located:
 - Above
 - Inside, or
 - Below 

the original Unit Test.

Word 2010, Rubberduck v2.2.0.3468-pre

```
'@TestMethod
Public Sub ValidateIndexOneIsLevel1() ' Expected: IsValid = True
    On Error GoTo TestFail
    
    'Arrange:
    
    'Act:

    'Assert:
    Assert.Inconclusive

TestExit:
    Exit Sub
TestFail:
    Assert.Fail "Test raised an error: #" & Err.Number & " - " & Err.description
'@TestMethod
Public Sub TestMethod1() 'TODO Rename test
    On Error GoTo TestFail
    
    'Arrange:

    'Act:

    'Assert:
    Assert.Inconclusive

TestExit:
    Exit Sub
TestFail:
    Assert.Fail "Test raised an error: #" & Err.Number & " - " & Err.description
End Sub

End Sub
```

**Comment by Inarion** [comment]
This seems to me like a resurfacing [old issue](https://github.com/rubberduck-vba/Rubberduck/issues/2854) or maybe like a regression?

**Comment by comintern** [comment]
Ref [chat](https://chat.stackexchange.com/transcript/message/48891539#48891539).

**Comment by SmileyFtW** [comment]
If the cursor is on the last line of the test module AND the last line of the test module is the one immediately after the `End Sub` of the previous procedure then the newly added test method ends up just ahead of the `End Sub` resulting in 2 `End Sub` lines. If the last line of the test module is 2 lines after the `End Sub` then all is well, but the first line of the added test text (`'@TestMethod("Uncategorized"))` is immediately beneath the `End Sub` of the previous procedure. Seems like a line counting/placement issue. Shouldn't the new test text just be added on the last line of the module (maybe +1)?

**Comment by IvenBach** [comment]
Smiley is correct, at the end of the code pane you want what's below. If not you end up with an edit which causes uncompile-able code.
```
End Sub
' first blank line
' second blank line
| ' cursor placed here when inserting a test module
```

I want to say a line feed is being eaten as part of the addition but haven't looked at the root cause. I'll poke around for this issue after making some free time.

**Comment by IvenBach** [comment]
Tested this with Version 2.5.1.8557 and not getting OP behavior. Try with a more recent copy of RD and let us know if it's been resolved.

**Comment by SmileyFtW** [comment]
FWIW I am seeing this on
Version 2.5.1.5663
OS: Microsoft Windows NT 10.0.18363.0, x64
Host Product: Microsoft Office x86
Host Version: 16.0.13328.20356
Host Executable: EXCEL.EXE

**Comment by Vogel612** [comment]
@SmileyFtW that's ... almost three thousand builds ago ...

**Comment by SmileyFtW** [comment]
@Vogel612  When I go to the Pre releases it appears to be the latest. What am I missing?

**Comment by Vogel612** [comment]
hm ... I was going off of Iven's version specification. Apparently the latest prerelease is 2.5.1.5676, which is mostly because we had two new releases since you commented originally... Soooo.... I said some nonsense right there...
