### ISSUE TITLE
Windows XP compatibility EOL

### ISSUE THREAD

**Issue by bnote** [rubberduck-vba/Rubberduck#4180]
> Microsoft .NET Framework 4.5 installation was not detected.

On which Rubberduck version XP-compatibility support was ended?
.

**Comment by bclothier** [comment]
I don't think we ever supported XP because Rubberduck has been on v4.5 in the v2.0 cycle and we are currently on 4.6. 

See #277 -- that discussion was had in 2015 and decision already made since.

**Comment by rubberduck203** [comment]
We never have supported XP. Windows had ended support for XP around the same time, if not before, this project started. 

I know a lot of people are still using XP, but I really encourage you to upgrade if you can. Continuing to use XP is a security risk.

**Comment by bnote** [comment]
I knew it already from somewhere, just recently one person convinced me that he installed it on XP. I tried it, and, of course, unsuccessfully due to Framework 4.5 :) So I thought that he was talking about one of the early releases...

Thank you for prompt replies.
.

**Comment by bnote** [comment]
Should I to change the original issue title, removing "EOL" from it, to not mislead people, because there was not  XP-compatibility at all?
.

**Comment by rubberduck203** [comment]
Nah. I think it’s all right.
