### ISSUE TITLE
Unit tests appear to be deserializing the user declarations instead of the test ones.

### ISSUE THREAD

**Issue by comintern** [rubberduck-vba/Rubberduck#4182]
Noticed this after I serialized declarations to scan through them to validate the COM collector output. Next time I ran unit tests after that, I failed all of the Excel specific ones. I deleted them from my Declarations folder, and then :poof: all tests passed again.

This has 2 implications.  First, the cached declarations might not be current enough for the unit tests to be effective (otherwise they shouldn't care which declaration set they were using).  Second, unit tests should be repeatable, so they obviously shouldn't be traipsing off into user land to get files.

**Comment by rubberduck203** [comment]
Is this a problem with the unit test framework or the test suite?
I’m having a bit of trouble understanding the issue.

**Comment by MDoerner** [comment]
I do not see how the `MockParser` can use the user generated serialized declarations, except for the case that they got generated in a test.

This is from where the serialized declarations get added:

```csharp
public static void AddTestLibrary(this RubberduckParserState state, string serialized)
{
    var reader = new XmlPersistableDeclarations();
    var basePath = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
    basePath = Directory.GetParent(basePath).Parent.FullName;
    var path = Path.Combine(basePath, "Testfiles\\Resolver", serialized);
    var deserialized = reader.Load(path);
    AddTestLibrary(state, deserialized);
}
```

This is the path the COM synchronizer uses in the parsing process:

```csharp
serializedDeclarationsPath ?? Path.Combine(Path.GetDirectoryName(Assembly.GetAssembly(typeof(MockParser)).Location), "TestFiles", "Resolver");
```

The optional parameter `serializedDeclarationsPath` gets never passed in with anything but the default value `null`. 


I just debugged this and found the potential cause for what you are experiencing. In some (all?) tests loading the Excel reference, the major and minor version are provided as `0`, which does not agree with the file name. So, the com reflector concludes that the file does not exist and tries to com reflect it. We should really fix the versions on the mock references.

**Comment by comintern** [comment]
Update: It _should_ be using `serializedDeclarationsPath`, but it doesn't always use it. I dropped a break-point in `LoadDeclarationsFromXml` and kicked of a "debug all" test run. It hit the assert with this stack trace:

![screenshot from 2018-07-17 00-09-51](https://user-images.githubusercontent.com/8944005/42797898-11bf2288-8957-11e8-805f-3e2c2946f740.png)

**Comment by MDoerner** [comment]
The problem seems to be that the very first line of `LoadDeclarationsFromXml` does not use the `_serializedDeclarationPath` and instead sets the path the production folder.
