### ISSUE TITLE
ProcedureCanBeWrittenAsFunctionInspection should ignore members that do not assign to the ByRef parameter

### ISSUE THREAD

**Issue by comintern** [rubberduck-vba/Rubberduck#4197]
Noticed this when I was trying to find failing cases for #3906.

If you have a `Sub` with no body and a single `ByRef` parameter...

```
Private Sub foo(bar As String)
    'Do nothing
End Sub
```
...it triggers a `ProcedureCanBeWrittenAsFunctionInspection`.  I **_could_** re-write it as a `Function`, but I can't find any use case for that, and that would be a `NonReturningFunctionInspection`. 

Note that this doesn't match with the description, which states "...is assigned a new value/reference before the procedure exits...".

This should either be a new inspection, something like "Procedure has not body", or it should not return a result.

**Comment by MDoerner** [comment]
I agree with the proposal to not return an inspection result here. After all, this code should also the `ParameterCanBeMadeByVal` inspection, which provides the more useful suggestion here.
