### ISSUE TITLE
'Rename Parameter' QuickFix fixes too much

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#4202]
Starting with this code:

```VBA
Public Property Let ColorID(ByVal x As String)
  pColorID = x
End Property
Public Property Let Red(ByVal x As Long)
  pRed = x
End Property
Public Property Let Green(ByVal x As Long)
  pGreen = x
End Property
Public Property Let Blue(ByVal x As Long)
  pBlue = x
End Property
```

I get these inspections, which are perfectly reasonable:
![rd rename inspections](https://user-images.githubusercontent.com/11889733/42841597-919bc750-89d8-11e8-8328-964fd63a6cab.PNG)

I select the `Rename parameter` quickfix:
![rd rename quick fix](https://user-images.githubusercontent.com/11889733/42841650-bb108d14-89d8-11e8-9fa1-be67ea066a66.PNG)

And end up with this code:

```VBA
Public Property Let ColorID(ByVal colorCode As String)
  pColorID = colorCode
End Property
Public Property Let Red(ByVal colorCode As Long)
  pRed = colorCode
End Property
Public Property Let Green(ByVal colorCode As Long)
  pGreen = colorCode
End Property
Public Property Let Blue(ByVal colorCode As Long)
  pBlue = colorCode
End Property
```

While it's handy in this case, some may consider it a bit aggressive.

**Comment by retailcoder** [comment]
This is a regression bug, possibly involving the resolver (needs to be determined).

**Comment by daFreeMan** [comment]
Very interesting...

I've come across 2 `Consider renaming variable 'RS'` inspection results. Fixing the first one did _not_ fix the second one...

```VBA
  Dim RS As ADODB.Recordset
  Set RS = CurrentDb.OpenRecordset(SQLString)
  Do While Not RS.EOF And Not RS.BOF
  ...
```
and
```VBA
  Dim RS      As ADODB.Recordset
  Set RS = New ADODB.Recordset
  Set RS = cmd.Execute
```

And now, after reverting the change (`Ctrl-Z`), I'm only getting 1 inspection result despite me being quite certain that both sets of code (above) are present in my project. 

In the attached log, I see:

    2018-07-17 16:36:19.2888;WARN-2.2.0.3508;Rubberduck.Inspections.Rubberduck.Inspections.Inspector;System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.

and 

    2018-07-17 16:36:19.1908;ERROR-2.2.0.3508;Rubberduck.UI.Command.FindAllReferencesCommand;System.Runtime.InteropServices.COMException (0x800A09A3): Exception from HRESULT: 0x800A09A3

(in a couple of places)
and

    2018-07-17 16:36:18.7487;ERROR-2.2.0.3508;Rubberduck.UI.Command.Refactorings.FormDesignerRefactorRenameCommand;System.Runtime.InteropServices.COMException (0x800A09A3): Exception from HRESULT: 0x800A09A3

[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/2203361/RubberduckLog.txt)

**Comment by comintern** [comment]
The `RS` issue appears to be unrelated to the rename parameter issue. See #4273.
