### ISSUE TITLE
Inspection for use of `IsMissing` with non-Variant types.

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#4212]
`IsMissing` is widely misused. It can only ever return `True` if:
- the variable is a `Variant`
- the variable is an optional parameter

RD should have an inspection that identifies usages of `IsMissing` with any other variable type.

**Comment by bclothier** [comment]
> If the passed argument is anything else, I'm thinking the quickfix should be to replace it with `True`

No, you want `False` there. Falsy test is universal; Truthy isn't.

**Comment by comintern** [comment]
@bclothier Yep, just saw that.
