### ISSUE TITLE
Copyright notice is not right

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#4214]
The installer and about box bear this mention since forever:

> © Copyright 2014-${YEAR} Mathieu Guindon & Christopher McClellan

The project's website page footer says otherwise:

> Copyright © ${YEAR} Rubberduck VBA - All rights reserved.

When I transferred ownership of the repository from my account over to the 'rubberduck-vba' GitHub organization, it was to make it easier to collaborate and work as a team. Throughout the years, core contributors and domain experts have turned my initial naive and buggy mess into something outright impressive, and I feel like that old copyright notice makes the project's founders look like they own more of it than anyone else, and that just isn't right.

Let's change it to match that of the website. Rubberduck is and always has been a collective effort, "Mathieu Guindon & Christopher McClellan" couldn't have made it what it has become today (and what it will be tomorrow), without the hard work every member of this GitHub organization put into it.

CC @rubberduck203

**Comment by ThunderFrame** [comment]
Question is, is "Rubberduck VBA" an entity that can assert copyright?

**Comment by retailcoder** [comment]
@ThunderFrame  I don't know the answer. I asked on OSS.SE: https://opensource.stackexchange.com/q/7124/575

**Comment by bclothier** [comment]
This seems relevant:

https://opensource.stackexchange.com/questions/6582/can-i-remove-some-copyright-holders-from-headers-and-replace-them-by-a-generic?rq=1

**Comment by PeterMTaylor** [comment]
👍

**Comment by comintern** [comment]
Good solution with minimal effort, legal hassle, or expense. I say go for it.

**Comment by rubberduck203** [comment]
I think it’s a wonderful idea. :+1:
