### ISSUE TITLE
Add UI for editing Class/Form Attributes

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#4227]
With the attributes-as-annotations approach seemingly dead in the water, Rubberduck needs a UI for inspecting and editing VB_Attributes. In VBA:

- Standard Modules and Document Modules only have their Name attributes exposed.
- Class modules expose their name and instancing attributes in the Properties Window, but not their PredeclaredId attribute.
- UserForms expose their Name attribute, but not their Instancing attribute. Nor do they expose their PredeclaredId attribute, but a UserForm can't be made NOT Predeclared.

Furthermore, modules and procedures can have other, optional attributes, so ideally a UI would let you add, edit and remove the optional attributes.

Once an attribute is edited and validated, the module would need to be exported, removed, edited in the exported file, and then re-imported. Obviously, this won't work for Document modules.

Question is, what form should that UI take?

- An attributes pane within the Code Explorer - This would seem to be the most logical UI, as the CE already deals with Modules and declarations, so it's a natural fit.
- An attributes pane as a dedicated ToolWindow
- A popup dialog that has checkboxes, dropdowns and textboxes for various attributes - perhaps mimicking the VB6 attributes dialog - This doesn't allow for easily inspecting the attributes
- Make the attribute text visible in the AvalonEdit CodePane - Without intellisense, this relies upon the user knowing the editability and valid syntax and values for various attributes.

We also need to consider editing attributes for multiple components at once: see #4185

**Comment by bclothier** [comment]
I definitely am not fan of VB6's propensity to use popups gratuitously. So that approach for me is no-go. It would be only appropriate for performing mass edits.

AvalonEdit seems to be a way off but even if it is here today, a dediccated toolwindow seems to me the most useful.

I would probably start with supporting editing only an indviviudal component then look at a popup UI for mass editing after, reusing the commands created to support those operations.

**Comment by ThunderFrame** [comment]
What if it worked like editing the properties for a selection of multiple controls on a UserForm, where only the shared properties are editable?

**Comment by bclothier** [comment]
This is covered in the linked issue #4790 & #5120, so closing this.
