### ISSUE TITLE
Notify if an action modifies a repository outside of the VBE

### ISSUE THREAD

**Issue by ckuhn203** [rubberduck-vba/Rubberduck#423]
As a user, I want to be notified if I take an action that modifies the files in my repository (such as merging or pulling via the command line) , and re-load the project into the editor from the file-system if I choose to do so.

---

I'll need to learn how to use the [FileSystemWatcher](https://msdn.microsoft.com/en-us/library/system.io.filesystemwatcher%28v=vs.110%29.aspx) to accomplish this.

**Comment by retailcoder** [comment]
*an action that modifies the files in my repository* could also be editing a class module in Notepad to tweak some attributes. Or, in future versions, when Rubberduck itself does it.

**Comment by ckuhn203** [comment]
Good point. So, the file system watcher might not necessarily be watching a repository, but rather, an arbitrary location on the file system depending on how we implement the attributes feature. I'll keep that in mind while I'm designing this feature.

**Comment by retailcoder** [comment]
If there's no repository, there's nothing to watch.

The temp-export location for non-repo projects will probably be under `%APPDATA%\Rubberduck\Temp\some-GUID\`

**Comment by ckuhn203** [comment]
Nice work @Hosch250!
