### ISSUE TITLE
Rubberduck forces VB6 host to scale at 100% regardless of Window's Scaling factor

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#4230]
This appears to be a scaling conflict between VB6's windows and WPF.

VB6 is fine *until* RD loads.

Will post a GIF when I get a chance.

**Comment by mansellan** [comment]
I can repro. Suspect this may be tough to track down.

**Comment by mansellan** [comment]
Closed by #4555
