### ISSUE TITLE
Code Inspection gives me a notice of illegal annotation

### ISSUE THREAD

**Issue by hansvandijk1987** [rubberduck-vba/Rubberduck#4256]
I get the notice in the image. It seems odd, because it doesn't say it for other modules that have the same annotation.

![image](https://user-images.githubusercontent.com/42171347/43766854-d563cbfc-9a33-11e8-9978-a767b5b44bd7.png)

**Comment by PeterMTaylor** [comment]
Sounds a recursive reply from the inspector
Are we looping (arrays/container/collections) anything or using annotations repeatedly?

**Comment by Vogel612** [comment]
Could you please include the code that produces the inspection result? As it stands this is impossible to diagnose and fix...
