### ISSUE TITLE
ImplicitByRefModifier Debug.Assert failed; a module is null

### ISSUE THREAD

**Issue by bclothier** [rubberduck-vba/Rubberduck#4259]
During running the inspector, `ImplicitByRefModifierListener` class will invoke this line:

```
var builtInEventHandlerContexts = State.DeclarationFinder.FindEventHandlers().Select(handler => handler.Context).ToHashSet();
```

This invokes this part in the declaration finder:
```
        private IDictionary<Declaration, List<Declaration>> FindAllHandlersByWithEventField()
        {
            var withEventsFields = UserDeclarations(DeclarationType.Variable).Where(item => item.IsWithEvents);
            var events = withEventsFields.Select(field =>
                new
                {
                    WithEventsField = field,
                    AvailableEvents = FindEvents(field.AsTypeDeclaration).ToArray()
                });
...
        }
```

The `field.AsTypeDeclaration` is `null` at this point, which takes me into this `Debug.Assert` here:
```
        private IEnumerable<Declaration> FindEvents(Declaration module)
        {
            Debug.Assert(module != null);

            var members = Members(module.QualifiedName.QualifiedModuleName);
            return members == null 
                ? Enumerable.Empty<Declaration>() 
                : members.Where(declaration => declaration.DeclarationType == DeclarationType.Event);
        }
```

The `field` represents an `Access.Form` object, based on this VBA line:
`Private WithEvents frmSource As Access.Form`

Lost the log because the debugger decided it was such a great time to freeze and I forgot to copy the log before restarting. Doh! Furthermore, I cannot reproduce it again by clicking parse button. It may be related to loading the project as part of compact & repairing or something.

**Comment by MDoerner** [comment]
This needs a `null` check. The problem appears whenever the type annotation pass cannot resolve the type name to a declaration. Obviously, this only throws for with events declarations because of which this cannot be observed goo often.
