### ISSUE TITLE
Fix Experimental attribute

### ISSUE THREAD

**Issue by bclothier** [rubberduck-vba/Rubberduck#4270]
This was broken since the PR #3739. See [this comment](https://github.com/rubberduck-vba/Rubberduck/pull/3739#issuecomment-370162452) for details. Basically, we need to improve how we handle `new`ing up the view models as to not block the use of the `Experimental` attribute.

**Comment by Vogel612** [comment]
Fixed as of 6bef6a09ff5707bf1f2decacf762e148daa62c11
