### ISSUE TITLE
Some VB6 projects cause an RD Access Violation

### ISSUE THREAD

**Issue by mansellan** [rubberduck-vba/Rubberduck#4280]
Selecting any of the following project types when starting VB6 results in an access violation from RD

ActiveX EXE
ActiveX DLL
ActiveX Document DLL
ActiveX Document EXE

Obvious ActiveX trend, but oddly doesn't occur with ActiveX Control. Also occurs if the New Project dialog is cancelled.

**Comment by comintern** [comment]
[Linking chat.](https://chat.stackexchange.com/transcript/message/46233194#46233194)

**Comment by mansellan** [comment]
Only one commandbar control is involved - the main Rubberduck menu (caption Ru&bberduck). The COM target appears to have lost its pointer at the point where the caption setter is called.
