### ISSUE TITLE
AutoComplete smart concatenation ain't quite so smart

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#4293]
Starting with this bit of code:

```VBA
NPS = ExecuteStoredProcedure("CalculateNPSOverPeriod", True, DBconfig.SetupConnection(DBconfig.SQLConString), _
                             "@NPS", adInteger, 0, _
                             "@startDate", adDate, startDate, _
                             "@endDate", adDate, endDate, _
                             "@ClinicNa|", adVarChar)
```

With the cursor on the last line within the quoted text, I type "m" and I get:

```VBA
NPS = ExecuteStoredProcedure("CalculateNPSOverPeriod", True, DBconfig.SetupConnection(DBconfig.SQLConString), _
                             "@NPS", adInteger, 0, _
                             "@startDate", adDate, startDate, _
                             "@endDate", adDate, endDate, _
                             "@ClinicNa" & _
                             "", adVarChar)m"
```

**Comment by retailcoder** [comment]
https://github.com/rubberduck-vba/Rubberduck/blob/18a007a53def9e8112e021b07359da6113c2e618/Rubberduck.VBEEditor/Events/VBENativeServices.cs#L159

**Comment by retailcoder** [comment]
Removing "critical", since the feature has a killswitch.

**Comment by VBA-Bertie** [comment]
Hi, 
this might related to this,
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/2337007/RubberduckLog.txt)

These are my Autocompletion Settings
![image](https://user-images.githubusercontent.com/37850492/44865293-43526780-ac82-11e8-8820-09dd5e28768b.png)

Starting with 
```
Sub foo()
    Debug.Print "" 
End Sub

```
if i write "mo-" (also "MO_") in the quoted text i get:
```
Sub foo()
    Debug.Print "" & _
                "m" & _
                "o" & _
                "-"
End Sub
```
if i press CTRL + "o" and CTRL + "-" i get:

```
Sub foo()
    Debug.Print "" & vbNewLine & _
                "" & vbNewLine & _
                ""
End Sub
```
exception: 
- there is already something like a comment in the same line 
```


Sub foo()
    Debug.Print "mo-" 'comment
End Sub
```
- or the smart concatenation is disabled
![image](https://user-images.githubusercontent.com/37850492/44866162-bd83eb80-ac84-11e8-884b-6516c2c69e7e.png)

[AutocompletionSettings.txt](https://github.com/rubberduck-vba/Rubberduck/files/2337128/AutocompletionSettings.txt)
[GeneralSettings.txt](https://github.com/rubberduck-vba/Rubberduck/files/2337129/GeneralSettings.txt)
