### ISSUE TITLE
Could Rubberduck address the "VBE refresh bug"?

### ISSUE THREAD

**Issue by CGReetz** [rubberduck-vba/Rubberduck#4310]
I'm refering to a "bug" in vanilla VBE, not in Rubberduck.

When an UDF is called from a worksheet cell, with Calculation Mode set to Automatic, there seems to be an extra (big) overhead when comparing to the same UDF called from a buttun (by user interaction), which results in UDF's being much slower then they should be.

The effect is particularly noticeable  with multiple calls and the difference in speed can be up to 10x.

I've attached an exemple macro-enabled workbook (just replace .zip with .xlsm), in which the same 512 calls to "SampleFunction" can be performed either by triggering automatic calculation or by pressing a CommandButton. The total execution time is informed at the end (associated with the AfterCalculate event). In my machine, the times are ~0.32 s and ~0.02 s, respectively.
[vbeBug Exemple.zip](https://github.com/rubberduck-vba/Rubberduck/files/2321731/vbeBug.Exemple.zip)

One of the few places I could find reference to this behavior was this: https://fastexcel.wordpress.com/2011/06/13/writing-efficient-vba-udfs-part-3-avoiding-the-vbe-refresh-bug/

From which I borrowed the term "VBE refresh bug".
 
Given that the reasons behind this bug are likely relatod to dynamics between Excel and VBE, could a "fix" be within reach of the RubberDuck project?

(By fix, I mean somehow bypassing the extra call overhead for UDFs. I personaly think that providing such a performance boost would be a great asset, and highly desireable by users.)

**Comment by rubberduck203** [comment]
Good enough reasoning for me to consider this one out of scope. Interesting request, but I agree with comintern.

**Comment by CGReetz** [comment]
Understood, I'd already completely accept reason 1.

Nevertheless, I'd like to further pursue workarounds for this on my own. Unfortunately, I'm literally years behind Rubberduck team when it comes to understanding the innerworks of VBE. Posting it here was more intended to get advise as to what's going on then to actually see a solution incorporated into the project. I'm having a hard time searching for in depth discussions about this behavior.

As to reasons 2, 3 and 4. I, too, think the reason pointed by the blog author is in the wrong direction. My two cents go to this: https://support.microsoft.com/en-us/help/170787/description-of-limitations-of-custom-functions-in-excel (It is possible to catch "ghost" UDF calls, using Debug.Print Application.Caller after an "ilegal" operation.)

Based on commintern's comments I also made some modifications to the exemple Worksheet. It now uses a MicroTimer function (it has Double precision, instead of Timer's Single), and the UDF returns call count, along with time elapsed. It shows that the executioin order remains the same between both calling methods, and that the repeating times seen earlier came from lack of precision of the Timer function.

[vbeBug Exemple mod.zip](https://github.com/rubberduck-vba/Rubberduck/files/2322097/vbeBug.Exemple.mod.zip)

Thank you for your patience : )

**Comment by comintern** [comment]
I think the Microsoft Support link explains the what happens during calculation of UDFs, but I don't see how it addresses any of the concerns that I have with interfering with Excel's process. If anything, it seems to reinforce the notion that changing the semantics of calculation can change the results of user code.  Note that the last paragraph is basically saying that if you aren't aware of how precedence is resolved for UDFs, you can shoot yourself in the foot (my emphasis):

> For correct calculation, all ranges that are used in the calculation **_should_** be passed to the function as arguments. If you do not pass the calculation ranges as arguments, instead of referring to the ranges within the VBA code of the function, Excel cannot account for them within the calculation engine. Therefore, Excel may not adequately calculate the workbook to make sure that all precedents are calculated before calculating the user-defined function.

That's fine if you're only working with your own code, but it's not fine if you're messing with somebody else's who may not be aware of that behavior. On top of that, a smart (or dumb, depending on the circumstance) coder can circumvent most if not all of the UDF restricts listed.

As for potential implementation, working via the VBE would not be the way I'd approach this at all (see number 2 for the reason). If I _were_ going to implement this, I'd do it by hooking the appropriate calls to the runtime, probably through a TSR.
