### ISSUE TITLE
"Private" padlock icon in the CE is almost invisible

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#4316]
This code:

```VBA
Public Property Get SATCol() As Long
  SATCol = this.SATCol
End Property
Private Property Let SATCol(ByVal inVal As Long)
  this.SATCol = SATCol
End Property
```

Yields this in the CE:
![2018-08-28 10_49_23-microsoft visual basic for applications](https://user-images.githubusercontent.com/11889733/44731308-e784b480-aab0-11e8-9c98-74f38ac9698c.png)

To my not quite so great eyes, that little grey <s>blob</s> padlock indicating that it's a `Private` Let is nearly invisible, and chat indicated that others have issue resolving it as well.

It needs to change to a brighter color that can actually be seen.

**Comment by comintern** [comment]
[RDIcons.zip](https://github.com/rubberduck-vba/Rubberduck/files/2338383/RDIcons.zip)
