### ISSUE TITLE
False positive "Member {x} implicitly references 'ActiveWorkbook'" inspection

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#4326]
Win10, Excel2016 (desktop), RD .3723

This MVCE yields an "implicitly references 'ActiveWorkbook'" inspection:

```VBE
Public Sub RemoveWorksheet(ByVal TheWB As Workbook, ByVal SheetName As String)
  TheWB.Worksheets(Left(SheetName, 31)).Delete
End Sub
```

I believe that is a false positive since I'm explicitly referencing `TheWB`, whatever `workbook` that may happen to be.

**Note**: this _is_ MCVE - whatever RTE you generate by trying to delete a non-existing worksheet is on your own head. My complete code handles errors.

**Comment by daFreeMan** [comment]
Interestingly, I also get the error on this code:

```VBA
Public Function PrepareNewReportSheet(ByRef thisWB As Workbook, ByVal SheetName As String) As Worksheet
  Dim report As Worksheet
  Set report = thisWB.Worksheets.Add(before:=thisWB.Worksheets("Main"))
```

but only on the `before:=thisWB.Worksheets()` reference, it seems to be perfectly fine with the `report = thisWB` reference.

**Comment by comintern** [comment]
This looks like a resolver error:

![image](https://user-images.githubusercontent.com/8944005/44857156-d664b080-ac34-11e8-9c29-3bc0774e5ec2.png)
