### ISSUE TITLE
RD startup error when multiple new Excel projects are open before launch

### ISSUE THREAD

**Issue by mansellan** [rubberduck-vba/Rubberduck#4334]
MCVE:

1. Open Excel
2. Add another new workbook
3. Open VBE with RD set to load
4. RD fails with 'Unexpected Error'

[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/2338251/RubberduckLog.txt)

Looks like a duplicate ProjectId issue.

**Comment by Inarion** [comment]
> can an unsaved workbook be used as a reference?

I don't think it's possible. (Assuming you're only talking VBA here.) The `References` object has the methods `AddFromFile` and `AddFromGuid` - and both, I assume need an existing file in the end.
When trying to add a reference to a new workbook (with a renamed project VBAProjectNew) manually via the GUI,

1. it shows `UNSAVED: VBAProjectNew` in the reference list and
2. on trying to select that reference, a popup will tell you that you'll need to save that project to add it as a reference.
