### ISSUE TITLE
Rename clash check is a little too tight.

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#4349]
Win10, Excel201(Desktop), RD .3744

Given this code:

```VBA
Private Type TMonthScoreInfo
  veryDissatisfiedResponses As Long
End Type
Private this As TMonthScoreInfo

Public Property Get VS() As Long
  VS = this.verySatisfiedResponses
End Property
Public Property Let VS(ByVal theVal As Long)
  this.verySatisfiedResponses = theVal
End Property
```

A`Refactor | Rename` attempt on `Public Property Get VS() As Long` to `Public Property Get verySatisfiedResponses() As Long` yields a warning that there is a name clash on `verySatisfiedResponses`
![2018-09-04 14_13_28-microsoft visual basic for applications - satisfaction summary master v3 23 - de](https://user-images.githubusercontent.com/11889733/45049889-f4278080-b04d-11e8-9087-2e121655cdd9.png)
however there really isn't. Clicking "Yes" completes the rename and the code compiles cleanly

**Comment by comintern** [comment]
See [chat](https://chat.stackexchange.com/transcript/message/47490981#47490981).

**Comment by daFreeMan** [comment]
I just noticed that doing the rename in the opposite order - i.e. rename the member of `Type`, _then_ rename the Getter/Setter it works without error.
