### ISSUE TITLE
Autocomplete adding multi-line breaks where it shouldn't

### ISSUE THREAD

**Issue by IvenBach** [rubberduck-vba/Rubberduck#4350]
Attempting to write `MsgBox "Information"` leads to. 
```
        MsgBox "Inf" & _
               "or" & _
               "mati" & _
               "on"
```
This isn't 100% reproducible/consistent. Can't figure out what causes it. I've had this occur several times over the last week.

Version 2.2.6821.25004
OS: Microsoft Windows NT 6.1.7601 Service Pack 1, x64
Host Product: Microsoft Office 2013 x86
Host Version: 15.0.5045.1000
Host Executable: EXCEL.EXE

**Comment by retailcoder** [comment]
#4293
