### ISSUE TITLE
@Ignore UnassignedVariableUsage doesn't ignore error

### ISSUE THREAD

**Issue by samcan** [rubberduck-vba/Rubberduck#4364]
Hi,

In certain functions, I'm trying to return an unassigned array. Rubberduck is flagging as an UnassignedVariableUsage error, which is fine. But, if I insert the lines to have Rubberduck ignore the error, it doesn't have any effect.

Using Rubberduck:

Version 2.2.6672.28001
OS: Microsoft Windows NT 10.0.16299.0, x64
Host Product: Microsoft Office 2016 x86
Host Version: 16.0.4732.1000
Host Executable: EXCEL.EXE

Below is a simple test function illustrating the issue:

![image](https://user-images.githubusercontent.com/1220819/45514820-4dcd3080-b75b-11e8-8d0c-76121705b730.png)

I can click **Fix** > **Ignore once**, but that just gives me the following (and doesn't ignore the error):

![image](https://user-images.githubusercontent.com/1220819/45514756-1cecfb80-b75b-11e8-8787-1cd5547ca329.png)

Log file:
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/2380922/RubberduckLog.txt)

Thanks!

**Comment by Vogel612** [comment]
We have a test that should already cover this [here](https://github.com/rubberduck-vba/Rubberduck/blob/next/RubberduckTests/Inspections/UnassignedVariableUsageInspectionTests.cs#L93)

I wonder whether we're not correctly handling "return" assignments for the Ignore annotations ...

**Comment by Vogel612** [comment]
It stands to reason that we should allow selective ignoring of the results, not only ignoring whole declarations. That would entail including an "isIgnored" check in the generation of the results [here](https://github.com/rubberduck-vba/Rubberduck/blob/next/Rubberduck.CodeAnalysis/Inspections/Concrete/UnassignedVariableUsageInspection.cs#L38).

**Comment by samcan** [comment]
> Could you try moving the `'Ignore` to the variable declaration, and see whether that fixes it? If that's the solution, we need to reevaluate how this specific ignore annotation should work ..

Yes, that worked!
