### ISSUE TITLE
Excel.Workbooks.Add Triggers ActiveWorkbook Warning

### ISSUE THREAD

**Issue by CHR-IS-B** [rubberduck-vba/Rubberduck#4366]
Should this code...
```
Dim targetWs As Worksheet
Set targetWs = Workbooks.Add.Worksheets(1)
```
...trigger the warning?

> Member 'Workbooks.Add.Worksheets' implicitly references 'ActiveWorkbook'

I tried changing the code to this but it still triggered the same warning - on the last line.
```
Dim targetWb As Workbook
Dim targetWs As Worksheet
Set targetWb = Excel.Workbooks.Add
Set targetWs = targetWb.Worksheets(1)
```
I found that referencing `targetWb(ANYNUMBER)` always triggers this warning but `targetWb.Worksheets.Add` does not.

Is this a bug?  I might be missing it but I don't see the reference to `ActiveWorkbook`.

Version 2.2.0.3762
OS: Microsoft Windows NT 6.1.7601 Service Pack 1, x64
Host Product: Microsoft Office 2016 x86
Host Version: 16.0.4717.1000
Host Executable: EXCEL.EXE

**Comment by Vogel612** [comment]
Yea that seems more appropriate. I messed up. Thanks for calling this out (and even finding a duplicate 😊)

**Comment by CHR-IS-B** [comment]
No worries : )
