### ISSUE TITLE
Checking Types with code inspections

### ISSUE THREAD

**Issue by Gener4tor** [rubberduck-vba/Rubberduck#4388]
Is Rubberduck able to check types?

I had the following problem:

```
public function myFunction() as boolean
...
end function
```

Somwhere else:

```
dim myVar as string
myVar =  myFunction()
```

VBA is able to compile this, but at runtime you get a incompatible types error ("Typen unverträglich" in german).

Is Rubberduck able to find this in the code inspections?

**Comment by retailcoder** [comment]
I tagged the original issue with "up-for-grabs", it's not a particularly hard one to write.
Closing this issue as a duplicate. Thanks!
