### ISSUE TITLE
CodeInspectionResultBase instances need to be injected with an interface, not the VBE

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#439]
We need to remove the dependency on the VBE in all code inspection results, if we want to be able to write tests for them.

At the end of the day the inspection results only require the VBE to change the code in a code module, so we should be able to wrap it up with an interface, and implement a mock for it that wouldn't require us to mock up the whole VBE object model.

**Comment by ckuhn203** [comment]
Using Moq, we only need to mock up the VBE functionality that actually gets called upon. I've not looked at the code you're talking about, but it might not be as hard as you think to Moq a VBE to inject. I'm not arguing against cleaning code up, but it might not be a prerequisite.  

One big stumbling block was the Window object. I have a Mock in the source control branch that alleviates that. The feature isn't done, but it is in a place where I can merge the changes.

**Comment by retailcoder** [comment]
The one thing that bothers me above all is that the quickfix functionality
is implemented inside the InspectionResult classes - which is clearly a
violation of SRP. Splitting the concerns here would help temove the VBE
dependency from the InspectionResult classes.

Sent from my Samsung mobile

**Comment by ckuhn203** [comment]
No arguments here. The less often we need to mock the VBE and the less complicated those mocks are the better.

**Comment by retailcoder** [comment]
seems mock builder solves this problem and this issue was somehow left opened.
