### ISSUE TITLE
Missing Open Designer menu

### ISSUE THREAD

**Issue by Profex13** [rubberduck-vba/Rubberduck#4393]
After running code that shows a _UserForm_ and closes it properly (`Set View = Nothing`), the _Open Dialog_ menu is missing from the _context menu_ in the _Code Explorer_.   It doesn't re-appear for that _UserForm_ unless the code is reset.

**Comment by retailcoder** [comment]
Is the *show designer* button enabled on the toolstrip?

![image](https://user-images.githubusercontent.com/5751684/46223742-3331b480-c322-11e8-8f0a-0b93296f3354.png)

**Comment by Profex13** [comment]
Both are disabled/missing 
![image](https://user-images.githubusercontent.com/6745578/46223841-7e4bc780-c322-11e8-9c32-8b049cf14e55.png)

**Comment by comintern** [comment]
This appears to be a binding issue (as opposed to being related to setting the object to `Nothing`). When I put break-points at the top of `OpenDesignerCommand.EvaluateCanExecute` and `OpenDesignerCommand.OnExecute` I can't hit either one of them no matter what I do in the UI.
