### ISSUE TITLE
The unreachable case inspection is broken for non-english users, again

### ISSUE THREAD

**Issue by MDoerner** [rubberduck-vba/Rubberduck#4397]
I get 66 failed tests on my local machine for the unreachable case inspection, all containing floating point numbers. Apparently, there is some code parsing strings into floating point numbers not doing it in a culture invarant way, again.

**Comment by Vogel612** [comment]
I can confirm this

**Comment by BZngr** [comment]
No doubt this was my doing (or undoing)...my apologies.  Though I do not have failing tests to work with, it looks like one of the problem areas  would be the `ParseTreeValueExtensions` class in `ParseTreeValue.cs`.  For example, `decimal.Parse` is passed as a `Func<string,decimal>` parameter.  That parameter probably needs to refer to a function that wraps a cultural invariant use of `decimal.Parse`.  You've probably found this by now, but thought I'd offer up a place to start.
