### ISSUE TITLE
ImplicitDefaultMemberAssignmentInspection should ignore bang notation.

### ISSUE THREAD

**Issue by comintern** [rubberduck-vba/Rubberduck#4406]
While "technically" correct, bang notation is a shorthand *intended to* access the default member. Use of bang notation in general is smelly and should be inspected IMHO, but it needs its own inspection so it can be configured independently.

**Comment by MDoerner** [comment]
I fully agree. The inspection should be separate, especially since the bang notation indicates that you want to access the default member, at least.

**Comment by MDoerner** [comment]
The request in the title should be fulfilled already,

The request for a separate inspection will follow shortly.
