### ISSUE TITLE
CallStmt doesn't support parentheses

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#4420]
The definition for the `callStmt` parser rule is missing `LPAREN` and `RPAREN` tokens around the `argumentList`:

````
callStmt :
    CALL whiteSpace lExpression
    | lExpression (whiteSpace argumentList)?
;
````

The `argumentList` [correctly] excludes the lexer tokens, leaving `Call xy(z)` an error node.

A failing test was pushed in 8eec98c for it (it's preventing successful matching of `(` and `)` tokens when backspacing), but PR #4418 will not be addressing it, since grammar changes would be outside its wide-enough-as-it-is scope.

**Comment by MDoerner** [comment]
No, the rule is perfectly right. The explicit `argumentList` is in the case _without_ the explicit call statement.

I also doubt that the code `Call xy(z)` is a parser error. Your test does not test that.

Did your code under test consider that for an explicit call statement, the `argumentList` is part of the `lExpression`?

**Comment by retailcoder** [comment]
Then I need a better explanation for this:

![sbtkf](https://user-images.githubusercontent.com/5751684/46666651-34ba7280-cb95-11e8-88f6-cd87690b7145.png)

**Comment by Vogel612** [comment]
What was your starting rule to generate the tree?

**Comment by retailcoder** [comment]
@Vogel612 `result = VBACodeStringParser.Parse(code, p => p.blockStmt())` is the last rule that was attempted; note, I later tried appending `\r\n` to the input string, didn't make a difference.

Here's the full snippet:

````
    private Selection FindMatchingTokenPosition(SelfClosingPair pair, CodeString original)
    {
        var code = original.Code;
        code = code.EndsWith($"{pair.OpeningChar}{pair.ClosingChar}")
            ? code.Substring(0, code.LastIndexOf(pair.ClosingChar) + 1)
            : code;
        var result = VBACodeStringParser.Parse(code, p => p.startRule());
        if (((ParserRuleContext)result.parseTree).exception != null)
        {
            result = VBACodeStringParser.Parse(code, p => p.mainBlockStmt());
            if (((ParserRuleContext)result.parseTree).exception != null)
            {
                result = VBACodeStringParser.Parse(code, p => p.blockStmt());
                if (((ParserRuleContext)result.parseTree).exception != null)
                {
                    return default;
                }
            }
        }
        var visitor = new MatchingTokenVisitor(pair, original);
        visitor.Visit(result.parseTree);
        return visitor.Result;
    }
````

Not sure why it's not branching into the `return default` here, but the visitor isn't hitting any of the overrides.

**Comment by MDoerner** [comment]
What exactly do you mean with not hitting? Do you mean that after putting a breakpoint at the start of all of them none gets triggered or that the `Result` is never set?

**Comment by retailcoder** [comment]
@MDoerner with every node in the tree being an `ErrorNode`, the visitor doesn't hit any of the overrides, and thus `visitor.Result` is `default(Selection)`, i.e. `{L0C0}`, which for the calling code translates into "couldn't work out the matching token position" and results in SCP backspace handling bail-out and only the opening brace getting deleted.

**Comment by retailcoder** [comment]
The `Call` statement in the test string is RHS of an assignment, making `Call xy(z)` illegal. This is a non-issue, grammar is fine.
