### ISSUE TITLE
Range.Find may return Nothing

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#4440]
The generalized form of this inspection would be "never assume an object-returning function will return an actual object reference", or "always verify whether an object-returning function returned Nothing", but that would be overly defensive IMO.

However `Range.Find` is such a common trap, it deserves its own dedicated inspection. Where `foo` is an `Excel.Range`:

```vb
r = foo.Find(bar).Row ' if bar isn't found in range foo, .Row will throw error 91.
'other code
```

Should quick-fix to (prompt for variable name?):

```vb
Dim result As Range
Set result = foo.Find(bar)
If Not result Is Nothing Then
    r = result.Row
    'TODO: move the relevant code here
End If
'other code
```

The inspection alone is worth its weight in gold; a quick-fix for it would be awesome, but most likely requires further code-tweaking by the user... so quick-fix not mandatory here (can be done later).

**Comment by comintern** [comment]
The quickfix shouldn't be horribly difficult - I think pretty much every case would be "fixable" by just replacing the member access expression with an intermediate variable and then adding a boilerplate test with a TODO marker:

```
Public Sub Foo()
    If Range("A:A").Find.Row = 1 Then
        Debug.Print "Row 1"
    End If
End Sub
```
...QF applied...

```
Public Sub Foo()
    Dim canIHazRange As Range
    Set canIHazRange = Range("A:A").Find("Something")
    If canIHazRange Is Nothing Then
        'TODO
    End If
    
    If canIHazRange.Row = 1 Then
        Debug.Print "Row 1"
    End If
End Sub
```

**Comment by retailcoder** [comment]
@comintern I'd rather have the `.Row` member call securely inside the added conditional block though. Without inverting the condition ("Not <s>result</s> canIHasRange Is Nothing"), running the code as-is would still throw error 91. We definitely can make the illegal member call safe, plus it shows the user where the "safe" code goes.

**Comment by comintern** [comment]
@retailcoder I can definitely see that:

```
Public Sub Foo()
    Dim canIHazRange As Range
    Set canIHazRange = Range("A:A").Find("Something")
    If Not canIHazRange Is Nothing Then
        If canIHazRange.Row = 1 Then
            Debug.Print "Row 1"
        End If
    End If
End Sub
```
About the only difference there would be finding where the logical reach of the block needs to be contained to. Slightly trickier due to `GoTo` or `GoSub` allowing it to jump out of the block...
```
    If Range("A:A").Find.Row = 1 Then
        GoTo SomeLabel
    End If
```

**Comment by retailcoder** [comment]
That's why my suggestion was to just put the throwing member call inside the conditional block, and let the user move the rest of the code (with an auto-TODO comment/marker) :smiley: 

I don't think we can reliably automatically determine what the entire conditional block should be.

**Comment by retailcoder** [comment]
Plot twist: we should probably pop a result for this too:

    Dim result As Range
    Set result = Range("A:A").Find("foo")
    bar = result.Row '<< flag?

That would involve a bit of [code-path-analysis] though.

**Comment by MDoerner** [comment]
Here is another twist:

```vba
If Range("B:B").Find("bar") Then 
    Dim foo As Long
    foo = Range("A:A").Find("baz")
End If
```

This potentially throws at two places due to default member access.
