### ISSUE TITLE
Autocomplete not working

### ISSUE THREAD

**Issue by lpnzgd** [rubberduck-vba/Rubberduck#4449]
For some reason, autocomplete is not working at all for me.  I've checked the settings are all enabled (I think this is the default) and tried turning them off and back on, to no avail.  Is there something I'm missing?

Version 2.2.0.3536
OS: Microsoft Windows NT 6.1.7601 Service Pack 1, x64
Host Product: Microsoft Office 2016 x64
Host Version: 16.0.8730.2175
Host Executable: EXCEL.EXE

**Comment by retailcoder** [comment]
Yeah, there's a bit of history here, the settings UI doesn't reflect the actual features - AC was temporarily disabled pending a rewrite, but the settings UI wasn't updated accordingly.

AC is being split into two distinct features: *self-closing pairs* (aka "SCP"), and *block completion*; there's an open PR for SCP, and it's coming along nicely but there's a bit of clean-up and refactoring that needs to happen before it's merged. Block completion will follow.
Ideally we'd ship v2.3.0 with both features, but it's looking more and more like SCP will make it, and block completion will happen later, in a minor update.

If you want you can try the current SCP build [here](https://ci.appveyor.com/project/rubberduck-vba/rubberduck/builds/19597011/artifacts), and keep an eye on PR #4418 for the updates (pending merge) - any feedback on SCP is extremely welcome, especially at this early stage!

**Comment by retailcoder** [comment]
PR was merged.

**Comment by lpnzgd** [comment]
Hi Mathieu,

Thank you very much for your response.  Much appreciated.

Blessings, Grant.
