### ISSUE TITLE
Smart Indenting loses the cursor position after indenting

### ISSUE THREAD

**Issue by MikeAndLisa** [rubberduck-vba/Rubberduck#4452]
Please leave the cursor where it is or go back to the same line after indenting. For large procedures it's a real elbow having to scroll down to where you were!

Mike Green

**Comment by bclothier** [comment]
Mike, thanks for the report! We'll look at it. Note that I removed the email address to avoid harvesting; the GitHub notification system will email you with updates.

**Comment by MikeAndLisa** [comment]
Thank you! This was a first git whatever thinig for me... the two issues I posted.  Thanks for removing my email!

Mike

________________________________________
