### ISSUE TITLE
SCP puts quotes in the wrong place

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#4460]
Win10, Excel 2016 (desktop), RD .4047

Starting with this text:

      ExecuteStoredProcedure ("AddAppointmentCountForAClinic", False,dbconfig.SQLConString, & _
                              | thisClinic.ClinicID ,

I type `"` and it yields this text:

      ExecuteStoredProcedure ("AddAppointmentCountForAClinic", False,dbconfig.SQLConString, & _
                               thisClinic.ClinicID ,"|"

Yes, the cursor is at the beginning (indented) of the 2nd line, yet the `""` ends up at the end of the 2nd line.

**Comment by retailcoder** [comment]
For the sake of having a proper MCVE to test with, what's the complete logical line of code though?

**Comment by daFreeMan** [comment]
Sadly, build .4058 doesn't seem to have fixed this, or at least I can't tell because Excel crashes. Every. Single. Time.

Starting with this code (a continuation of the originally reported code):

```vba
returnCode = ExecuteStoredProcedure("AddAppointmentCountForAClinic", False, dbConfig.SQLConString, _
                                    "@clinicID", surveyListRS.Fields("ClinicID").value, adInteger, _|
                                    "@startDate", reportDate, adDate)
```

With the caret (as indicated) at the end of the 2nd line, I hit <kbd>Enter</kbd>. The caret moves to the beginning of the next line in column 1, then Excel crashes.

**However**, if I start with this code:

```vba
    returnCode = ExecuteStoredProcedure("AddAppointmentCountForAClinic", False, dbConfig.SQLConString, "@clinicID", surveyListRS.Fields("ClinicID").value, adInteger, "@startDate", reportDate, adDate)
```
with the caret _anywhere_ (except in an already quoted string) and hit <kbd>"</kbd> I get a 2nd `"` as expected.

This is the RD log from a crash:
[RubberduckLog.4058.txt](https://github.com/rubberduck-vba/Rubberduck/files/2519033/RubberduckLog.4058.txt)

And this is the log from the successful SCPs:
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/2519036/RubberduckLog.txt)

Are there any Windows logs I can provide to help track down the issue?

**Comment by retailcoder** [comment]
@daFreeMan thanks. Likely I missed an off-by-one and the service is throwing an IndexOutOfRangeException. A quick patch that should probably be in place anyway, would be to have a try/catch+logging in the AC service, which could then just resume without handling the keypress.
Note that this is an entirely different problem than originally presented though: handling " and handling ENTER are two distinct code paths - the originally reported issue is indeed fixed, as far as I can tell. Does ENTER at the end of the 2nd line still crash with smart-concat disabled? I suspect the prettifier code is making a mistake in the calculation of the indent on the new empty line.
