### ISSUE TITLE
Unexpected Error - An item with the same key has already been added - with Repro

### ISSUE THREAD

**Issue by Stevefb** [rubberduck-vba/Rubberduck#4480]
In MS Word (not sure if this would apply to Excel) if a document (no macros in document) is opened in protected view such that macros (in the attached template) are disabled, AND the user enables the macros THEN the project explorer has duplicate files and Rubberduck displays Unexpected Error. 

Excerpt from the logs (logs attached):
```
2018-11-01 16:02:10.7161;ERROR-2.2.0.4070;Rubberduck.Common.LogLevelHelper;
	Rubberduck version 2.2.0.4070 loading:
	Operating System: Microsoft Windows NT 10.0.17134.0 x64
	Host Product: Microsoft Office x64
	Host Version: 16.0.10827.20181
	Host Executable: WINWORD.EXE;
2018-11-01 16:04:18.9560;ERROR-2.2.0.4070;Rubberduck.Parsing.VBA.ParseCoordinator;Unexpected exception thrown in parsing run. (thread 18).;System.ArgumentException: An item with the same key has already been added.
```

![image](https://user-images.githubusercontent.com/9349975/47833986-a5019000-ddf1-11e8-8df5-9e6406a28106.png)

![image](https://user-images.githubusercontent.com/9349975/47834087-15a8ac80-ddf2-11e8-9895-1e137fa7e176.png)

[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/2537291/RubberduckLog.txt)

**Comment by comintern** [comment]
This looks like the same issue as #4334 based on the log files.
