### ISSUE TITLE
'Return value of function is never used' with non-returning function

### ISSUE THREAD

**Issue by FuSoftware** [rubberduck-vba/Rubberduck#4497]
When a function has no return type specified, it still yields a `Return value of function is never used`.
Some cases where a Function *should* not return, and still be a function, is when dealing with MS Access's Macro objects, on the "ExecuteCode" action, that require a non-returning function.

```
Function Init()
    'Some code that doesn't return
End Function
```

**Comment by comintern** [comment]
This is *not* a non-returning function. It returns `Empty` due to the fact that the return value is never assigned. The inspection result is correct if the return value is never assigned to anything in your code.

**Comment by retailcoder** [comment]
We can't infer the intent from the code alone here; until we poke the host document to get all the VBA code that's invoked from outside the VBA project (macros, UDFs and worksheet control handlers in Excel, etc.), we can't *know* that the function is used.

A function without a declared/specified return type, still has one - it's `Variant`, implicitly - a situation we *also* inspect for and for which there is no way to tell Rubberduck "hey I really totally *meant* it like that" --- other than with an annotation... which is exactly what annotations are for:

```vb
'@Ignore FunctionReturnValueNotUsed; invoked from Access macro
Public Function Init() As Variant
    ' code
End Function
```

Using the quite-possibly-accidental omitted return type as a trigger for ignoring the *non-returning function* inspection would have detrimental effects in every other host.

**Comment by retailcoder** [comment]
My suggestion would be to put all (related) such exposed, macro-invoked functions in the same module, and use a module-level annotation so that the inspection skips that entire module.

```vb
'@Folder("MyProject.Macros")
'@IgnoreModule FunctionReturnValueNotUsed; these functions return Variant/Empty, as required by the Access macros that invoke them.
Option Explicit

Public Function Init() As Variant
   '...
End Function

'...
```
