### ISSUE TITLE
RD should recover the selection after each rewrite in a consistent way

### ISSUE THREAD

**Issue by MDoerner** [rubberduck-vba/Rubberduck#4524]
Now that PR #4465 is merged we have one place all rewriting has to go through, the `IRewriteSession`. This presents an opportunity to consistently recover the previous selection after every rewrite.

Currently, each refactoring implements its own way of recovering the selection in the active code pane, wherease the quickfixes make no attempt at all to recover the selection.

My suggestion is to introduce some `ISelectionService` with the capability to save the selection for specified modules and recover it on request and to wire this up in the implementations of `IRewriteSession`.

Recovering the selection would include:
1. Set the selection to the selection prior to the rewrite for all affected modules.
2. Activate the previously active code pane, if there was any.

For attribute rewrites, we should make sure the same code panes are open after the rewrite. (Attributes get rewritten via exporting, removing and then reimporting the modules.)

In a later stage members to add an offset to the selection or to specify the selection could be added to the `IModuleRewriter` in order to allow for adjustments considering the code altered during the rewrite.

**Comment by BZngr** [comment]
I'm definitely in favor of a consistent 'rule' for setting the selection after a rewrite.  That said, in the case of refactorings that create something in a new module (e.g. extract interface) we may want more that an offset.  As a user, I think I would expect to be presented with a selection somewhere in the new interface declaration module.
