### ISSUE TITLE
Quick fix for "Object assigned w/o 'Set' keyword" is broken

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#4530]
Win10, Excel2016 Rd .4175

I'm getting a false-positive `Object variable '{x}' is assigned without the 'Set' keyword` inspection (#4318). Selecting the `Ignore once` quick fix is now non-functional (i.e. does nothing visible) and generates a stream of errors in the log.

[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/2599988/RubberduckLog.txt)

**Comment by Vogel612** [comment]
looks like we dropped the ball on a COM object there... Poking @bclothier as possible culprit for the COM errors at the end of the log.

**Comment by retailcoder** [comment]
fixed in #4529
