### ISSUE TITLE
"Use 'Set' keyword" quickfix doesn't insert the 'Set' keyword before the start of a member access expression

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#4531]
Win10, Excel 2016, RD .4175

Beginning with:

    Application.StatusBar = "Gathering Data: " & surveyListRS.Fields("MidName").Value

Applying the `Use 'Set' keyword` quick fix results in broken code:

    Application.Set StatusBar = "Gathering Data: " & surveyListRS.Fields("MidName").Value

This might be due to the fact that it's a false positive inspection result #4318. There was a fix for #4320 that seems to be working OK, but this one isn't.

It does not appear to throw any errors.
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/2600039/RubberduckLog.txt)

**Comment by retailcoder** [comment]
Quickfixes can't evaluate whether the inspection result is valid... *it's not their job*. This is a symptom - the real problem is the false positive.

**Comment by retailcoder** [comment]
Repro with a legit result:

    Private Sub Txtforename_Change()
        Dim foo As Range
        Set foo = [A1]
        foo.Set Font = [A1].Font
    End Sub

The `Set` keyword is being inserted just before the assigned variable - which is fine *when the assignment target is a variable*.... it needs to be inserted before the first token of the `LetStmtContext`.

**Comment by retailcoder** [comment]
The quickfix should also replace the `LET` token if it's present.

    Private Sub Txtforename_Change()
        Dim foo As Range
        Set foo = [A1]
        Let foo.Set Font = [A1].Font
    End Sub

**Comment by retailcoder** [comment]
https://github.com/rubberduck-vba/Rubberduck/blob/next/Rubberduck.CodeAnalysis/QuickFixes/UseSetKeywordForObjectAssignmentQuickFix.cs#L17

```csharp
rewriter.InsertBefore(result.Context.Start.TokenIndex, "Set ");
```

The fix is to walk the `Context` up to the parent `LetStmtContext`, determine if a `LET` token is present, then either insert the `Set` token or replace the `Let` token - something like this:

```csharp
var letStmt = result.Context.GetAncestor<VBAParser.LetStmtContext>();
var letToken = letStmt.LET();
if (letToken != null)
{
    rewriter.Replace(letToken, "Set");
}
else
{
    rewriter.InsertBefore(letStmt.Start.TokenIndex, "Set ");
}
```
