### ISSUE TITLE
Asynchronous Tasks should be cancelable

### ISSUE THREAD

**Issue by ckuhn203** [rubberduck-vba/Rubberduck#454]
> As a VBA dev, I would like to be able to cancel long running Rubberduck tasks.

Tasks like refreshing the code explorer and inspecting the code base should be cancelable as this could take a very long time on large code bases.

For example, the method that currently refreshes the code inspections is defined [like this][1].

    private async Task RefreshAsync()

We should pass a cancelation token to the Task and provide an UI element to allow the user to request a cancelation.

    //some method calling RefreshAsync

        CancellationTokenSource = cancelSource = new CancellationTokenSource();
        CancellationToken cancelToken = cancelSource.Token;

        Task.Run(() => RefreshAsync(cancelToken));

    }

    private async Task RefreshAsync(CancellationToken cancelToken)
    {
         //...

        if (cancellationRequested)
        {         
            cancelToken.ThroIfCancellationRequested();
        }

        // continue other work
    }

[1]:https://github.com/retailcoder/Rubberduck/blob/GrammarIsFun/RetailCoder.VBE/UI/CodeInspections/CodeInspectionsDockablePresenter.cs#L123

**Comment by retailcoder** [comment]
Should closing the toolwindow cancel the task, or there should be another UI element added for that, like a button on the toolbar? We already disable the "refresh" button, should we turn it into a "cancel" button instead?

**Comment by ckuhn203** [comment]
I'm not sure if closing the tool window should cancel the task or not. Since closing the tool window doesn't actually destroy it, it might be okay to just let it finish what it's doing in the back ground. Thoughts?

I do like the idea of turning the "Refresh" button into a "Cancel" button though. That's a UI that makes sense IMHO.

**Comment by retailcoder** [comment]
I'm not sure what closing the window actually does - it certainly doesn't cancel the task, but I'd have to test it to see if the treeview is refreshed if it's closed and then reopened after a while; I think the way we have it, displaying it triggers a refresh... which kills the point (of not cancelling the task when window is closed), but isn't exactly wrong either.
Same for code inspections.

Sent from my Samsung device

**Comment by ckuhn203** [comment]
It sets the visible property to false. Nothing more or less. The tool window (and incidentally, all of it's resources) open and in memory. Just invisible.

Given your point that we always refresh when showing the window, there's no reason not to cancel any tasks if the Visible property is set to false for whatever reason.

**Comment by retailcoder** [comment]
Not sure how to handle this: closing the code inspections window while it's parsing or inspecting, throws a fatal `TargetInvocationException`.

**Comment by Hosch250** [comment]
Changing the refresh button to a cancel button is standard procedure, AFAIK.

**Comment by ckuhn203** [comment]
This was done for code inspections. Let's see how it feels there and kick the rest of it down the road. How do you guys feel about that?

**Comment by Hosch250** [comment]
What's up with this?

**Comment by retailcoder** [comment]
@Hosch250 not sure if relevant anymore, this issue was created when RD was still running everything synchronously and blocking the UI.
