### ISSUE TITLE
Debug.? confuses autocomplete

### ISSUE THREAD

**Issue by Greedquest** [rubberduck-vba/Rubberduck#4543]
In a new Sub type

    Debug.? Update

Upon hitting "(" to open parentheses, the line becomes

    Debug.Print Up(); Date

similarly

    Debug.? hithere

becomes

    Debug.Print hit(); here

The same is not true of 

    Debug.Print hithere

which (upon hitting "("`) becomes

    Debug.Print hithere()

as expected, suggesting the problem is down to the `.?` expanding unexpectedly. I'd be interested to see if any of the other VBIDE built in auto-completions have similar effects but I can't think of any to test.

**Comment by ThunderFrame** [comment]
Nice catch. I was aware of that *feature*, I just didn't know that anybody actually used it.

IIUC, that's the only instance of VBE doing some autocorrect ion of it's own, and it's only done *after* the line is entered. RD should be able to handle it easily enough.

**Comment by MDoerner** [comment]
I think because this happens after every time the line is entered, this is a not so easy problem for SCP: it pastes the result of its completion when it does its job, i.e. closing the pair is considered finishing to enter a line.

Maybe we have to suppress SCP when we encounter this construct.

**Comment by Greedquest** [comment]
Another bit of autocorrect is the inline typing; e.g. `1.0` -> `1#`, but as far as I can see SCP handles that well
