### ISSUE TITLE
RD VB6 - creating new menubar entries every time IDE launches

### ISSUE THREAD

**Issue by mansellan** [rubberduck-vba/Rubberduck#4548]
Reported on VBForums:

> Tried it here. It installed ok, but added another new RubberDuck menu to the VB6 IDE very time it started.
> A whole long row of them!
> 
> Uninstalling it did not fix the problem. There appeared to be numerous entries left all over the registry. 
> Had to do a "System restore" to get rid of it all.

http://www.vbforums.com/showthread.php?861477-Rubberduck-VB6-IDE-support&p=5335347&viewfull=1#post5335347

**Comment by MDoerner** [comment]
I guess this happened with the current prerelease. Usually, we tear down eveything when shutting down.
However, since the fix for the premature release of the vbe object introduced some PRs back has not been merged yet, no shutdown happens.

**Comment by Vogel612** [comment]
We're reasonably confident that #4529 fixed this

**Comment by mansellan** [comment]
Tried to repro on a fresh VM:
Win10 x64 1803 with all updates
VB6 Enterprise with SP6
Per-user and all-user installs
Office 2010 x64

No repro under Rubberduck v2.2.0.4198-pre.
