### ISSUE TITLE
Folder annotation illegal?

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#4558]
For every module I have that has a `@Folder` annotation, the "illegal annotation" inspection is popping a result.

This happens whenever the annotation appears under `Option Explicit`.

**Comment by MDoerner** [comment]
It should not be relevant what is above the annotation, but what is right below it. Folder annotations in the annotation section of any member are deemed illegal.

**Comment by MDoerner** [comment]
In chat, the following example has been provided.
```vba
Option Explicit
'@Folder("Excel.Abstract")
Implements IWorkbookData
```
Testing with this example shows that the problem here is that the `@Folder` annotation annotates the identifier reference to the implemented interface. This makes it illegal, since `@Folder` is not an `IdentifierAnnotation`.

**Comment by MDoerner** [comment]
I can see that this behaviour might cause more unexpected illegal annotations. Shall we remove the test for illegal identifier reference annotations?

**Comment by Vogel612** [comment]
FWIW I think it's more useful to consider annotations that are recognized as belonging to an `Implements` statment to be recognized as possible module annotations.

I wonder whether we can get away with not allowing `Implements ...` to be parsed as a `mainBlockStmt`. This would make them always parse as `moduleDeclarationsElement`, which *should* sidestep the issue, IIUC.

**Comment by MDoerner** [comment]
This is not a bug as it is per current specifications.

However, to make the annotations system less annoying, I would like to propose a redesign. My suggestion is to simply only ever attach annotations to a declaration or identifier reference, if it has the correct annotation type flag. Then the illegal annotations are simply the annotations not attached to anything.
