### ISSUE TITLE
Code Inspection : Aggregated results not showing up clearly when grouping by object

### ISSUE THREAD

**Issue by FuSoftware** [rubberduck-vba/Rubberduck#4561]
Aggregated results only show up in the first object where the aggregation limit is reached (where it stops displaying results), and then they are never referenced again. In that example, the CI on the following form doesn't report empty string litterals, or undeclared variables. It would be useful if the results were aggregated for each object, with that grouping

![erreur](https://user-images.githubusercontent.com/11671860/49077643-13dcd800-f23c-11e8-8eb3-cccb92028732.PNG)

**Comment by Vogel612** [comment]
We originally want to completely do away with aggregated results. The problem they are intended to solve (namely WPF hogging tons of memory for rendering inspection results) needs to be solved before that, though.

This might be a useful intermediate improvement on how these results are aggregated. Of note here is: If the aggregation threshold for each distinct location is never reached, this boils down to never aggregating. That will most likely result in WPF hogging all the memory again.

If this feature is implemented, we'd probably want two aggregation thresholds. One (comparatively low) for location-based aggregation and one (comparatively high) for overall aggregation. For those that wish to tune their ducky's memory consumption, they might even be exposed as an "advanced" setting.

I'd want the aggregation by location to take precedence over the overall aggregation. Locationally aggregated results would be removed from consideration in overall aggregation. Note that this way we can predictably enable a "Fix All in Module". The more I think about this, the more I like this, actually...

**Comment by Vogel612** [comment]
yea, a few thousand is nice. The original issue alleviated with the aggregation is #2439. Especially enlightening here is the [observation by Comintern](https://github.com/rubberduck-vba/Rubberduck/issues/2439#issuecomment-268352609):

> When I was testing this, RD didn't flinch at generating 30,000 inspection results. [..] With a reasonably sized inspection window, each result is being rendered to a ~800px by 27px bitmap as it's drawn to the form. That's ~86kb per result pushed at the GDI. My understanding of how a scrollable WPF container works is that it actually renders the entire thing and then windows it using the scrollbar. So 30K results comes out to right around 2.4GB for that control alone.

**Comment by Vogel612** [comment]
If you can fix the WPF scrolling eating all that memory, the next thing we want to do is completely drop result aggregation.

**Comment by daFreeMan** [comment]
Definitely related: #4346

**Comment by FuSoftware** [comment]
I can try outside of RD to benchmark that kind of stuff and optimize it, but it will be hard to try it by building RD
