### ISSUE TITLE
Inspecting non-compilable code wrongly sets busy state on inspection results toolwindow

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#4562]
Triggering a reparse from the inspection results toolwindow with uncompilable code, and then cancelling the parse at the RD warning about parsing uncompilable code, wrongly sets the `IsBusy` flag on the viewmodel (duckies go spinning) - and since the parse was cancelled, state doesn't get updated.

Triggering a parse from the RD toolbar (inspections' refresh button is unavailable) normalizes the situation, but the busy state probably shouldn't be set in the first place.

OTOH, *not* setting the busy state leaves the button click feel no-op until parse is completed and inspections start running.

Ideas?

**Comment by comintern** [comment]
Just spit-balling here, but would it make sense to add a "Cancelling" parser state to account for this type of situation? If we set the state to Cancelling and then immediately to Ready afterward, we'd at least be able to respond to that event in the listeners.

**Comment by MDoerner** [comment]
I have to say that I do not really like that idea. This would introduce a new source of state changes outside the `ParseCoordinator` that could change the overall parser state anywhere in the parsing process because it would possibly be triggered from another thread.
