### ISSUE TITLE
RUbberduck 2.3.0.4227: No code metrics results

### ISSUE THREAD

**Issue by SteveLaycock** [rubberduck-vba/Rubberduck#4564]
I just wondered if you guys were aware that the code metrics pane is coming up blank.   If this is intended it would be nice to have a dialog box pop up to advise.

**Comment by Vogel612** [comment]
Did you parse before observing this?

**Comment by SteveLaycock** [comment]
Yes. I can compile and parse without errors.

**Comment by FuSoftware** [comment]
My observations are that it's project-specific (At least on the MS-Access side). Some projects have Code Metrics, others don't

**Comment by SteveLaycock** [comment]
I'm using Office 365 64 bit Word 2016

**Comment by retailcoder** [comment]
@FuSoftware would you happen to have a repro/MCVE for that error? The bug is here:

            var parameters = Parameters(procedure);

            ParameterDeclaration parameter;
            var namedArg = argExpression.GetAncestor<VBAParser.NamedArgumentContext>();
            if (namedArg != null)
            {
                // argument is named: we're lucky
                var parameterName = namedArg.unrestrictedIdentifier().GetText();
                parameter = parameters.SingleOrDefault(p => p.IdentifierName == parameterName);
            }

I can't conceive a way `parameters` could possibly have more than one parameter with a given name...

Please open a new issue when you have it - it's not related to code metrics. Thanks!

**Comment by FuSoftware** [comment]
@retailcoder I've found worse things. Deleting modules until I find the error won't work. I found that if I delete all the code, add a single module with a single function, then reparse, nothing shows up in the Code Metrics. However, if after that I quit and restart Access and VBE, then the CodeMetrics sees stuff

I have to close MS Access, re-open it, re-open the VBE to test if the Code Metrics find something

**Comment by comintern** [comment]
I think the foreign identifier is a red herring. I can duplicate this with no code at all. The first time I open the metrics window with an empty workbook, Sheet1 shows nothing and ThisWorkbook shows 0 lines of code.  After any change to ThisWorkbook, it doesn't show anything at all. It I add a module, it doesn't update the open metrics window. At the risk of sounding clichéd, that points to a caching problem.
