### ISSUE TITLE
Cannot add Test Module

### ISSUE THREAD

**Issue by ronykrell** [rubberduck-vba/Rubberduck#4567]
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/2621782/RubberduckLog.txt)
Hi there,

I installed Rubberduck, went through the Unit testing tutorial more or less successfully, and am unable to add an additional Test Module. 

At first the "Add Test Module" button was selectable and would give an error message when pressed. However, after a few times it is no longer selectable (greyed out)
Logs attached.

**Comment by retailcoder** [comment]
Ref. #4553 (duplicate)

Thanks for reporting! This has been addressed already, the feature should work as intended in [pre-release build 4227](https://github.com/rubberduck-vba/Rubberduck/releases/tag/Prerelease-v2.3.0.4227) :smiley:
