### ISSUE TITLE
"Ignore Once" quick fix for "no folder annotation" inspection doesn't work

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#4579]
Win10, Excel2016 desktop, RD .4235

`Module '{x}' has no '@folder' annotation` inspection has one quick fix: "Ignore Once". Selecting that option has no effect on the code, but leaves this in the log:

> 2018-11-29 10:09:23.8414;ERROR-2.3.0.4235;Rubberduck.UI.Inspections.InspectionResultsViewModel;System.NullReferenceException: Object reference not set to an instance of an object.
>    at Rubberduck.Inspections.QuickFixes.IgnoreOnceQuickFix.Fix(IInspectionResult result, IRewriteSession rewriteSession) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\QuickFixes\IgnoreOnceQuickFix.cs:line 47
>    at Rubberduck.Inspections.QuickFixes.QuickFixProvider.Fix(IQuickFix fix, IInspectionResult result) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\QuickFixes\QuickFixProvider.cs:line 80
>    at Rubberduck.UI.Command.CommandBase.Execute(Object parameter) in C:\projects\rubberduck\Rubberduck.Core\UI\Command\CommandBase.cs:line 47;System.NullReferenceException: Object reference not set to an instance of an object.
>    at Rubberduck.Inspections.QuickFixes.IgnoreOnceQuickFix.Fix(IInspectionResult result, IRewriteSession rewriteSession) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\QuickFixes\IgnoreOnceQuickFix.cs:line 47
>    at Rubberduck.Inspections.QuickFixes.QuickFixProvider.Fix(IQuickFix fix, IInspectionResult result) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\QuickFixes\QuickFixProvider.cs:line 80
>    at Rubberduck.UI.Command.CommandBase.Execute(Object parameter) in C:\projects\rubberduck\Rubberduck.Core\UI\Command\CommandBase.cs:line 47
> 2018-11-29 10:09:33.9569;ERROR-2.3.0.4235;Rubberduck.UI.Inspections.InspectionResultsViewModel;System.NullReferenceException: Object reference not set to an instance of an object.
>    at Rubberduck.Inspections.QuickFixes.IgnoreOnceQuickFix.Fix(IInspectionResult result, IRewriteSession rewriteSession) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\QuickFixes\IgnoreOnceQuickFix.cs:line 47
>    at Rubberduck.Inspections.QuickFixes.QuickFixProvider.Fix(IQuickFix fix, IInspectionResult result) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\QuickFixes\QuickFixProvider.cs:line 80
>    at Rubberduck.UI.Command.CommandBase.Execute(Object parameter) in C:\projects\rubberduck\Rubberduck.Core\UI\Command\CommandBase.cs:line 47;System.NullReferenceException: Object reference not set to an instance of an object.
>    at Rubberduck.Inspections.QuickFixes.IgnoreOnceQuickFix.Fix(IInspectionResult result, IRewriteSession rewriteSession) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\QuickFixes\IgnoreOnceQuickFix.cs:line 47
>    at Rubberduck.Inspections.QuickFixes.QuickFixProvider.Fix(IQuickFix fix, IInspectionResult result) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\QuickFixes\QuickFixProvider.cs:line 80
>    at Rubberduck.UI.Command.CommandBase.Execute(Object parameter) in C:\projects\rubberduck\Rubberduck.Core\UI\Command\CommandBase.cs:line 47
> 

Full log:
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/2629693/RubberduckLog.txt)

**Comment by MDoerner** [comment]
This does not only concern this inspection, but all inspections for modules. The quickfix completely assumes that it gets executed on something in a module, not the module itself. 

Fixing this will require adding a branch of the quickfix for module dclarations. This branch should also use `IgnoreModule` instead of `Ignore` because this is the version that attaches to modules.
