### ISSUE TITLE
Parse error on mutiple `WithEvents` vars

### ISSUE THREAD

**Issue by wqweto** [rubberduck-vba/Rubberduck#4591]
Grammar chokes on this
```
Private WithEvents a As VB.Form, WithEvents b As VB.Form
```
Btw, it just says `Parse Error` on the toolbar. Where can I see the actual error?

**Comment by Vogel612** [comment]
The actual error message will be in the logfiles. Assuming this code compiles, we'd need to look at how `WithEvents` is treated in the grammar. 

https://github.com/rubberduck-vba/Rubberduck/blob/87f612bc3b15fd0d7b0a321b6afc19749b001a29/Rubberduck.Parsing/Grammar/VBAParser.g4#L552-L554

The relevant grammar section is visible above. Quick, untested and unverified patch suggestion:

```diff
- variableStmt : (DIM | STATIC | visibility) whiteSpace (WITHEVENTS whiteSpace)? variableListStmt;
+ variableStmt : (DIM | STATIC | visibility) whiteSpace variableListStmt;
- variableListStmt : variableSubStmt (whiteSpace? COMMA whiteSpace? variableSubStmt)*;
+ variableListStmt : (WITHEVENTS whiteSpace)? variableSubStmt (whiteSpace? COMMA whiteSpace? (WITHEVENTS whiteSpace)? variableSubStmt)*;
```

This would move the WITHEVENTS from the variableStmt to the variableListStmt. One could argue that it should instead belong to `variableSubStmt`. I have not consulted the spec for this.

nb that this change will most likely necessitate resolver changes to correctly flag the variables as "with events"

**Comment by MDoerner** [comment]
Regarding, seeing the parser arror(s), there should be a little red error icon right next to the refresh button stating _Parser Error_. When you click it, a window with the parser error(s) will open.

**Comment by wqweto** [comment]
> there should be a little red error icon right next to the refresh button stating Parser Error. When you click it, a window with the parser error(s) will open.

Oh, I see I'm missing the icons here and the button next to `Refresh`/`Parse Error` is not apparent

![image](https://user-images.githubusercontent.com/987963/49338886-42d6bd80-f631-11e8-9787-6ace3a9dc6ce.png)

Probably something with my installation (I'm not filing a bug here:-))

**Comment by MDoerner** [comment]
Hm, that the icon does not appear might actually be a bug. The system for the buttons works a bit different in the VB6 editor compared to the VBE. So, we might have missed to implement that the button appears.

**Comment by mansellan** [comment]
It's #3952.
