### ISSUE TITLE
'@Ignore OptionBase - illegal annotation

### ISSUE THREAD

**Issue by chrisdaniels** [rubberduck-vba/Rubberduck#4594]
The '@Ignore OptionBase is throwing an Illegal Annotation warning

**Comment by Vogel612** [comment]
Could you show us where you put that annotation? Just a few days ago we merged a [fix to the illegal annotation inspection](https://github.com/rubberduck-vba/Rubberduck/pull/4568). 

What's your rubberduck version? I think this may be fixed since 2.3.0.4244.

**Comment by MDoerner** [comment]
This annotation is illegal indeed. Could you try '@IgnoreModule`?

**Comment by chrisdaniels** [comment]
I'm running 2.3.0.4235

@IgnoreModule works fine, it seems to just be @Ignore OptionBase.

I'm using it at the top of a module underneath Option Explicit but above the Option Base 1 line.

I'll try the latest version and report back

**Comment by chrisdaniels** [comment]
Same on .4244

![image](https://user-images.githubusercontent.com/70784/49375067-299a4380-f6fb-11e8-80fd-68949403b0e6.png)
