### ISSUE TITLE
Code Inspection spinner does not stop until worksheet is clicked

### ISSUE THREAD

**Issue by chrisdaniels** [rubberduck-vba/Rubberduck#4596]
Code Inspections can hang until the I click a cell on the worksheet.
I have had this happen quite a few times inc. on latest .4244.

The code inspection progress spinner will just continue to spin and will not show the updates until a cell on a worksheet is clicked.

For info, I am running dual screens, the project that this happens to contains >14k lines

**Comment by chrisdaniels** [comment]
For additional info - it does appear to be intermittent

**Comment by daFreeMan** [comment]
Thanks for reporting this! I've noticed it too and it's bugged me, but I've been too lazy to report it.

@Vogel612  - (previous behavior, see below for this morning's behavior) When you double click an inspection result to be taken to the line of code in the VBE, the spinner will remain spinning until you click on something else.

I'm in agreement with @chrisdaniels  that it is intermittent. In checking this out to respond to Vogel, I noticed that I have to work really hard to make it happen now. I'm running build .4244, what version are you on?

My results this morning:

* Double-click on an `Information` level inspection and the spinner will spin until I move the mouse
* Double-click on an `Error`, `Warning` or `Hint` level inspection and the spinner will spin for a moment while the offending line of code is presented, then the spin will stop, as expected.

**Comment by chrisdaniels** [comment]
Thanks @daFreeMan but mine is slightly different in that it does it on a refresh and the spinner I mention is the  rubber duck spinner on the code inspection window not the cursor spinner (not sure if that was what you were talking about).

**Comment by daFreeMan** [comment]
OK, ignore my comments, then - totally different issue. I'm talking about the "Windows Busy" little blue circle (Win10), not the "RD busy" spinning ducks.

**Comment by chrisdaniels** [comment]
> If the parser state is "ready" and inspections have completed and the inspection results toolwindow is still spinning duckies, then it's a problem. Is this what we're talking about?

Yes - This

Happy to share logs if required if you let me know where they are

**Comment by daFreeMan** [comment]
@chrisdaniels  - In the VBE, go to `Rubberduck | Settings`. In the middle of the screen is the log level setting and right next to that is a button that will open a Windows Explorer to the Rubberduck log directory.

Logs never hurt!

**Comment by chrisdaniels** [comment]
Thanks @daFreeMan 

What level would you guys want for this? Trace?

**Comment by retailcoder** [comment]
Though a bit verbose, trace is always ideal :smile:

**Comment by chrisdaniels** [comment]
Think I've caught it - I did a variable rename from the Code Inspection window, and its still spinning
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/2640197/RubberduckLog.txt)
