### ISSUE TITLE
Windows "busy" spinner continues to spin

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#4597]
Win10, Excel 2016, RD .4244

This has been a mild irritation for quite some time... (Since early 2.x releases, if I remember correctly.)

When clicking on an item in the `Code Inspections` dialog, the Windows busy spinner (_not_ RD's ducks) will continue to spin until something else is clicked on. In an effort to record a screen capture of this to report it, I've noted that under build .4244, it only happens _sometimes_, though not consistently, and it seems to spin until the cursor is moved and no longer requires a mouse click to make it stop.

![rd cursor issue](https://user-images.githubusercontent.com/11889733/49381263-7cff9800-f6e1-11e8-8aa7-9252f9f1788b.gif)

**Comment by comintern** [comment]
My guess is that this is a side effect of the way that the `SelectedItem` is refreshed in conjunction with how the information in the display panel is bound.  The information about the selected item is binding to the VM itself - not specific properties _**on**_ the `SelectedItem`.  This means that we're raising 5 different property change notifications in the setter to keep the UI in sync, and my best guess is that this is creating a race condition deep in the bowels of the WPF rendering.

**Comment by comintern** [comment]
#4717 addresses the worst of this, but there is a second issue (beside the one mentioned above) that will set the cursor to it's busy state. If the navigate command changes the code pane, the cursor will stick in the busy state until the mouse is moved.  This promises to be incredibly difficult to fix in that we don't have direct access to the Cursor from inside the navigate command and it's asynchronous. 

I'm inclined to ignore that last remaining bit in that the workaround is to simply move the mouse...

**Comment by daFreeMan** [comment]
I'm inclined to agree with you. Once the user is aware of the situation, it's no big deal at all. However, for the uninitiated, it does appear that RD is "locked up" until you try to move the mouse. I'm impressed that you were able to find and fix some of it! Thanks.

**Comment by comintern** [comment]
I'd consider this closed by #4717. The last remaining artifact (spinning until the mouse gets input) appears to be framework related, so I'm not sure there's anything we can do about it.
