### ISSUE TITLE
Code Inspection - false positive "Function return value is never used"

### ISSUE THREAD

**Issue by Gener4tor** [rubberduck-vba/Rubberduck#4606]
This code:

```
Public Function VTestAssert() As VTestAssertClass

    Set VTestAssert = New VTestAssertClass
    
End Function
```

is flagged from the CodeInspection as:

"Function return value is never used"

**Comment by Vogel612** [comment]
From the given code it's impossible to tell whether the inspection works as intended. Note that "Function return value is never used" is something different than "Function never returns a value". 

The first one is examining the places where the function is called. The second examines the function itself... It seems the inspection's naming and explanation isn't quite as clear as it could be.

**Comment by Gener4tor** [comment]
As I have a lot of calls like this:

Call VTestAssert.GleichStr(fn_replace_string("", "ist", "war"), "")

the inspection is a false positive either way.

**Comment by Vogel612** [comment]
umm ... you're not calling the function you mention above there... That'd be `VTestAssert().GleichStr[...]` instead

**Comment by Gener4tor** [comment]
I dont understand what you mean. 

The return value of VTestAssert is used to call the sub "GleichStr" in the class VTestAssertClass

**Comment by retailcoder** [comment]
@Vogel612 the parens aren't needed, the function call is legit.

**Comment by Vogel612** [comment]
:blush: well... that's where it'd help if I did VBA...

**Comment by bclothier** [comment]
No longer can reproduce this in .5101:
![image](https://user-images.githubusercontent.com/2367644/67209538-2b392c80-f3dd-11e9-9a9e-936f53ea1f9b.png)

In a blank workbook:
1) Create a new empty class module, named `Class1`
2) Create a new module and paste the code shown
3) Run inspections. Nada. 

Can you confirm if I've possibly missed a step or that the issue is really gone?

**Comment by bclothier** [comment]
Haven't heard anything to the contrary, so closing this.
