### ISSUE TITLE
Code Inspection settings icon isn't quite functionally complete

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#4610]
RD .4261
The Code Inspections window has a "settings gear" that will open the RD settings when it's clicked.
![2018-12-05 10_11_51-code inspections](https://user-images.githubusercontent.com/11889733/49522713-460ebb00-f876-11e8-9e21-f0c6c70973dd.png)
This great feature would be made awesome by automatically selecting the `Code Inspections Settings` section.
![2018-12-05 10_12_52-settings](https://user-images.githubusercontent.com/11889733/49522766-62aaf300-f876-11e8-9474-d65593b7dbd1.png)

**Comment by retailcoder** [comment]
huh, that was definitely the intent, and *should* have been doing that. tagging as a bug.
