### ISSUE TITLE
SCP clears brackets after event

### ISSUE THREAD

**Issue by Greedquest** [rubberduck-vba/Rubberduck#4611]
I've got a line of code

    RaiseEvent OrderChanged

Hitting `(` to open brackets (the event takes arguments) does nothing, presumably because some self-closing silliness is deleting it straight away.

In case it's relevant, it's happening in a class with this at the top:
```
Public Event OrderChanged(ByVal firstChangeIndex As Long) '0 indexed location of first different item
Public Event OnAddition(ByRef itemArray As Variant) 'when stuff added to content wrapper
Public Event AfterRemoval(ByRef itemArray As Variant) 'when stuff removed from content
```

**Comment by retailcoder** [comment]
FWIW the silliness is entirely on the VBE here.

**Comment by retailcoder** [comment]
No repro with latest (pre)release:

> Version 2.3.0.4269
> OS: Microsoft Windows NT 6.1.7601 Service Pack 1, x64
> Host Product: Microsoft Office 2010 x86
> Host Version: 14.0.7212.5000
> Host Executable: EXCEL.EXE

Confirming as fixed in bf1840e

**Comment by retailcoder** [comment]
Note that there's nothing SCP can do to auto-complete the parentheses in this situation: the VBE eats them immediately. The fix is to bail out and let the keypress through - meaning you need to type the closing parenthesis.

**Comment by Greedquest** [comment]
I'm running the latest stable release, I'll try to get a minimum example and check the pre-release. Just to clarify, I can't type the closing bracket because the opening one gets eaten up immediately
