### ISSUE TITLE
ShadowedDeclarationInspection severity defaults to 'Do not show'

### ISSUE THREAD

**Issue by Inarion** [rubberduck-vba/Rubberduck#4614]
When I delete my `rubberduck.config` file and start up RD, the severity for ShadowedDeclarationInspection is set to 'Do not show'. I don't think this is intentional.

These inspections are currently (4269-pre) defaulting to 'Do not show':

1. Redundant 'ByRef' modifier
2. Shadowed declaration
3. 'For...Next' loop step is not specified

For 1 and 3, one could argue that not showing them by default is sensible. For 2, I think there's no reason not to show it. (Or am I missing something?)

I tried finding out where this default setting is coming from, but I'm not getting it (yet).

[The CodeInspectionSettings](https://github.com/rubberduck-vba/Rubberduck/blob/406bbb0a7bddc9d438a8eb869f8ca95184dbcc05/Rubberduck.Core/Settings/CodeInspectionSettings.cs#L142) seem to have `CodeInspectionSeverity.Warning` as default value, as does the [InspectionBase](https://github.com/rubberduck-vba/Rubberduck/blob/406bbb0a7bddc9d438a8eb869f8ca95184dbcc05/Rubberduck.CodeAnalysis/Inspections/Abstract/InspectionBase.cs#L47) class.

Are there other places where default settings are set?

**Comment by retailcoder** [comment]
IIRC the inspection had issues at one point and was defaulted to DoNotShow, then fixed,...and the default wasn't changed back.

The other two are DoNotShow by design, since they're antagonistic to other inspections and a decision was made to pick one for default behavior instead of confusing the user with one inspection contradicting another.

The defaults are in `Rubberduck.Core.Properties.Settings.settings` IIRC.

**Comment by rkapka** [comment]
@retailcoder I don't think the issues have been fixed. See #3508.

**Comment by Inarion** [comment]
@rkapka You are right - I have been skimming the linked issue without actually understanding what was going on.

However, after more thoroughly re-reading it, I wonder: Does the inspection need to be perfect before enabling it? So far it has been helpful to me. It may currently miss *some* shadowed declarations, but it doesn't give **wrong** advice, does it? As such, I'd vote to activate it anyway: Being helpful sometimes beats being never helpful, imo.
