### ISSUE TITLE
RD functions are enabled in menus during "Inspection"

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#4615]
RD .4261

I have the `Inspect on Parse` setting enabled. When parsing, immediately after the status changes from `Resolving references` to `Inspecting` the `Extract Interface` menu option is enabled, while all other RD menu items remain disabled.
![2018-12-06 08_21_26-microsoft visual basic for applications - satisfaction summary master v3 29 - de](https://user-images.githubusercontent.com/11889733/49588876-e2e45d80-f935-11e8-8563-1d4b862a350a.png)

According to [chat](https://chat.stackexchange.com/transcript/message/47925549#47925549) this is likely incorrect, however there was some discussion that the parser may actually be `Ready` while the inspections are running.

**Comment by MDoerner** [comment]
`Inspecting` is not a parser state; the inspection engine simply overwrites the button label before running the inspections and changes it back afterwards. Since the inspections get triggered on the state change to `Ready`, I am more concerned why the remaining functionality is deactivated.
