### ISSUE TITLE
"commented" annotations are not recognized

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#4616]
The normal annotation format is:
`'@Ignore ...`
Which works just fine. If, however, one enters
`''@Ignore ...`
Then the annotation is skipped:
```VBA
Public Sub foo()
  Dim bar As Workbook
  ''@Ignore ObjectVariableNotSet
  bar = ActiveWorkbook
End Sub
```
![2018-12-06 15_58_18-code inspections](https://user-images.githubusercontent.com/11889733/49611553-ded53180-f96f-11e8-8bc2-4558f7b9cf84.png)

The precise location of the additional single quote doesn't seem to matter - it can be in the left margin with white space before the rest of the annotation.

Possibly related:
`' @Ignore` 
(with a space between `'` and `@` Doesn't work either.

**Comment by MDoerner** [comment]
This is currently by design. Annotations have to be at the start of a comment to be recognized.
