### ISSUE TITLE
Expand the Todo Explorer to pick up annotations

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#4617]
The Todo Explorer can be "hacked" by adding `IGNORE` as a text entry to pick up `'@Ignore` annotations. However, it _only_ finds them if the annotation has been commented out. i.e. `''@Ignore`.

Unfortunately, `''@Ignore` is, [by design](https://github.com/rubberduck-vba/Rubberduck/issues/4616), not recognized by the code inspector. 

Having the Todo Explorer recognize `'@Ignore` and other code annotations would be a great tool for finding places in code that probably do need some additional work (or have been marked as a work-around for a false-positive inspection - not that this would _ever_ happen). 

Being able to point newer users to the Todo Explorer to find all their annotations may also help with the uptake & use of the TE.

**Comment by bclothier** [comment]
Closing this in favor of #3364
