### ISSUE TITLE
(Yet another) False positive for 'Assignment without Set' inspection

### ISSUE THREAD

**Issue by Inarion** [rubberduck-vba/Rubberduck#4618]
#4604 is merged and as @MDoerner mentioned there, it should cover *most* cases. I guess I found one it doesn't cover. (For the 2 or so remaining false positives that I can see now in my project, about 100 others have disappeared with the merge, so great job!)

#### MCVE:

``` vb
Option Explicit

Private Type TFoo
'    SomeObjArr() As Object ' this produces no false positive
'    SomeObjArr() As Variant ' this produces no false positive
    SomeObjArr() As Collection ' this will result in a false positive
End Type

Private this As TFoo

Public Sub AFalsePositive()
    ReDim this.SomeObjArr(1 To 1)
    ' Object variable 'Collection' is assigned without the 'Set' keyword:
    Set this.SomeObjArr(1) = New Collection
End Sub
```

Note the difference in behavior, depending on whether the array is declared as a generic `Object` or `Variant` as opposed to a specific type. (I can replace `Collection` above with a custom class to achieve the same behavior.)

**Comment by MDoerner** [comment]
Just to clarify, do I understand correctly that you get the inspection result on the last assignment, with the `Set` present?

**Comment by Inarion** [comment]
Exactly. You should be able to reproduce the issue with Version 2.3.0.4277.

**Comment by MDoerner** [comment]
It is completely correct that the set is required here. The problem is with the resolver. Our handling of array member assignments for types with indexed default members seems to be off. Needs further investigation.
