### ISSUE TITLE
Add PredeclaredId Attribute to the Predeclared Class Template

### ISSUE THREAD

**Issue by cswartzvi** [rubberduck-vba/Rubberduck#4622]
Hi, I just installed v2.3.0 and noticed, among the many other awesome new features, that the Code Explorer now has the ability to add Predeclared Class modules from a template (I think #4225). Any chance we can automatically slap a PredeclaredId attribute on those new files by default (like the Folder attribute)? 

Thanks, keep up the good work!

**Comment by retailcoder** [comment]
Should be easy enough - simpy editing the template code should do it.

That said, need to confirm whether `@PredeclaredId` means anything anymore - IIRC all annotations/attributes synchronizations were dropped in 2.1.x.

**Comment by retailcoder** [comment]
@cswartzvi thanks for the feedback BTW! Note that v2.3.1 hotfix release is just about to be released (just a few last-minute kinks to work out, see #4619 for details), and v2.4 will include another new piece of total awesomeness (see [this video](https://youtu.be/2lfF3AOmAk4)) - is there anything else we can do to earn one more star? :wink:

**Comment by bclothier** [comment]
Yes, this should be easy to update and a good first issue. Being a built in template, the source is stored in [this resource](https://github.com/rubberduck-vba/Rubberduck/blob/next/Rubberduck.Resources/Templates.resx). I am not certain if the annotation and the inspection needs any additional updates, however. 

There is one more consideration not covered with the template. If you change the code in resource, how do you ensure that the file that was previously generated is updated? Though it is a "built-in" template, the intention was to allow customizations hence why it will generate a file in the templates folder, but only if it wasn't present. One. Way to fix this is to start versioning the builtin template so the user can be prompted to update the template if they want to. 

See #4549 for details as the template architecture is only partially implemented.

We would loce to have extra hands on this project!
