### ISSUE TITLE
SCP inserting extra "(" in method signatures

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#4629]
RD .4291

SCP is consistently inserting an extra `(` when defining a method signature:

    Public Sub Foo(|

Yields 

    Public Sub Foo((|)

a single backspace from that cursor location removes the `()` leaving

    Public Sub Foo(|

Which is where the vanilla VBE would have left me in the first place.

**Comment by MDoerner** [comment]
This has been fixed before. This is probably a regression introduces by the fix for `Call` statements.

**Comment by bclothier** [comment]
I'm not sure if this is a variant that needs its own issue:

```
Public Sub Foo|()
```

typing <kbd>Enter</kbd> yields:

```
Public Sub Foo()
    |
End Sub
()
```
