### ISSUE TITLE
Self-closing quote pair removes space in If statement after equal sign

### ISSUE THREAD

**Issue by Falthazar** [rubberduck-vba/Rubberduck#4631]
For `If` statements that are checking for strings, auto-closing quotes removes a space after the equal sign.

This:
```VBA
If TestString = "
```

Changes too:
```VBA
If TestString =""
```

VBA auto fixes it to the correct `= ""` so it isn't the biggest issue, but still mildly annoying.

Version 2.3.1.4308
OS: Microsoft Windows NT 6.1.7601 Service Pack 1, x64
Host Product: Microsoft Office 2016 x86
Host Version: 16.0.8431.2329
Host Executable: EXCEL.EXE

**Comment by retailcoder** [comment]
Tagging as a bug because this isn't the intended behavior, but given the caret is correctly positioned I'll treat this one as a lower priority issue; there's another SCP bug that's actually annoying and needs fixing - I'll try to slip a fix for both.
