### ISSUE TITLE
Weird placement of buttons on CE bar at certain sizes

### ISSUE THREAD

**Issue by bclothier** [rubberduck-vba/Rubberduck#4638]
I get that WPF will autohide controls that can't fit but I think this just looks too weird:
![image](https://user-images.githubusercontent.com/2367644/49975042-9682ba00-ff01-11e8-9764-6c34702656e1.png)

Kind of expect that the label and combobox would be a package deal.

**Comment by mansellan** [comment]
I wonder though, does this need to be permanently on show on the toolbar? Seems like Settings would be a better home for this, with a cog icon on the toolbar to jump there.

**Comment by retailcoder** [comment]
I agree settings would be a better place for this. If it's not moved there, a fix to keep the label and dropdown together could be to simply wrap the two controls in a `<StackPanel Orientation="Horizontal">` tag.
