### ISSUE TITLE
False positive 'Parameter can be passed by value'

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#4645]
Version 2.3.1.4327
OS: Microsoft Windows NT 10.0.15063.0, x64
Host Product: Microsoft Office 2016 x64
Host Version: 16.0.4711.1000
Host Executable: MSACCESS.EXE

This code is generating a `Parameter '{x}' can be passed by value' inspection.
```VBA
Public Property Get Url() As String
End Property
Public Property Let Url(ByVal Value As String)
End Property
```
![image](https://user-images.githubusercontent.com/11889733/50111992-1fed0180-020c-11e9-89ec-910438481c87.png)

[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/2687673/RubberduckLog.txt)

**Comment by bclothier** [comment]
I am unable to reproduce this. In an empty project, regardless whether it's a module, a class or a document, I cannot get the inspection to fire for the given code. 

Is there more to the story than the original report is letting on?

**Comment by daFreeMan** [comment]
I'll have to run a quick test on the most recent build. I'll let you know what I find.

**Comment by daFreeMan** [comment]
I'm no longer getting this issue in build .4445 on the originally reported code.
