### ISSUE TITLE
"Add/Remove Reference" dialogue allows removal of locked references. Sorta...

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#4649]
Version 2.3.1.4330
OS: Microsoft Windows NT 10.0.15063.0, x64
Host Product: Microsoft Office 2016 x64
Host Version: 16.0.4711.1000
Host Executable: MSACCESS.EXE

Still loving the new dialogue, and it even protects me from making bone-headed n00b mistakes, but it isn't quite obvious that it's doing so.

I start with a brand new Access project and its default references:
![2018-12-18 08_00_53-microsoft visual basic for applications - testing](https://user-images.githubusercontent.com/11889733/50156016-a3096880-029b-11e9-9fd9-e409b7237962.png)

I make bone-headed n00b mistake:
![2018-12-18 08_01_08-microsoft visual basic for applications - testing](https://user-images.githubusercontent.com/11889733/50156025-aac90d00-029b-11e9-9be4-2305f7552fe5.png)
Right here, I probably shouldn't be allowed to make this action in the first place - disable the "Remove selected reference" button when I've selected a `Locked` reference.

Clicking the `Apply` button has no noticeable effect (`Apply` button remains enabled, no notification that I've done something - valid or invalid). 
Click `OK` button to close dialogue box.
Re-open the dialogue:
![2018-12-18 08_01_38-microsoft visual basic for applications - testing](https://user-images.githubusercontent.com/11889733/50156115-e5cb4080-029b-11e9-83e9-5eba49290b05.png)

Whew! I haven't been allowed to totally bork my project!

**Comment by bclothier** [comment]
Just to note that there's probably 2 separate issues in this one bug report:

1) we shouldn't allow moving of padlocked references (obviously)
2) there should be an error message if the Apply/Ok wasn't entirely successful, so the users aren't surprised when there has been a different error and the dialog apparently not doing what they thought it did.
