### ISSUE TITLE
Add/Remove references dialog box isn't wide enough

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#4662]
As a follow on to #4647 (and after installing build .4340) the dialog box still isn't wide enough. The button visibility has been fixed, but that pushed other, arguably less important, information out of the box in its default size:
![2018-12-19 08_58_48-rubberduck - add_remove references](https://user-images.githubusercontent.com/11889733/50225738-55f6c680-036f-11e9-8347-b879f8a42815.png)

I'm running 1900x1200 resolution so there's _plenty_ of room to make that dialogue wider, though I realize that not everyone runs resolution that high (and some are higher).

Would it be possible for the two list boxen to dynamically size themselves to the necessary width, at least until the whole dialogue box reachs some sort of "reasonable" maximum size, say 90% of the VBE window's width? For those with the monitor size, there's no reason not to use it.

Yes, this info is available for each library by selecting it, but if we're going to the trouble of displaying it in the list box, may as well make it visible.

**Comment by comintern** [comment]
Agreed that information shouldn't be hidden on the right hand side. It needs its scrollbars back. Dynamically resizing the form itself would be a little weird (it would also kick the scrollbar out from under the mouse). I think I'd find that behavior surprising as hell.

Definitely needs to persist the window size though.
