### ISSUE TITLE
Issue with Userform Designer 

### ISSUE THREAD

**Issue by tallguyjenks** [rubberduck-vba/Rubberduck#4664]
First of all I LOVE this add it, its so nice especially the ToDo explorer, really love this feature.

Version 2.3.0.4221
OS: Microsoft Windows NT 6.1.7601 Service Pack 1, x64
Host Product: Microsoft Office 2013 x86
Host Version: 15.0.5085.1000
Host Executable: EXCEL.EXE

when I use the code explorer and click the designer button nothing occurs, the only time the userform designer opens is when I add a new userform (I can still use the old designer button) but even after I open a module and move away from the designer screen and I have a userform in my code explorer window, when I click designer again, even if my userform is selected, or even if I double click on the userform, nothing happens at all, I get no response from any way of accessing the Rubberduck designer button for userforms. not a big impact to me yet, but I love this add in and I want to use it as much as possible, so I thought to send this in :)

**Comment by Vogel612** [comment]
AFAICT this has been reported under https://github.com/rubberduck-vba/Rubberduck/issues/4605 and is already fixed in the latest green release v2.3.1. Could you please update to 2.3.1 and confirm that is the case?

**Comment by retailcoder** [comment]
I'll have to dig it up, but I believe this was fixed in the 2.3.1 hotfix release.

**Comment by tallguyjenks** [comment]
I thought I had the latest version, apparently I did not, new version does indeed work, thank you so much!

**Comment by retailcoder** [comment]
@tallguyjenks make sure you picked up the latest pre-release build - if you haven't been following the [project's blog](https://rubberduckvba.wordpress.com) or [social media](https://m.facebook.com/story.php?story_fbid=2266342446982944&id=1570311533252709) posts there's a big surprise feature currently in pre-release!

Feel free to star us here on GitHub, too :smiley:
