### ISSUE TITLE
Data binding leak in the InspectionResultsControl

### ISSUE THREAD

**Issue by MDoerner** [rubberduck-vba/Rubberduck#4666]
In the grouping grid in the `InspectionResultsControl` we bind to the `Result` collection on the  view model, which is an `ObservableCollection<IInspectionResult>`, and base the grouping on the `Inspection` property of the items. 
Since `IInspectionResult` does not extend `INotifyPropertyChanged` this leaks all inspection results.

The cleanest way to fix this is probably to introduce an `InspectionResultViewModel` that implements `INotifyPropertyChanged` to wrap the results.

**Comment by MDoerner** [comment]
As an alternative to the additional view model, we could change the binding mode to `OneTime`, which makes the UI use a snapshot and avoids registration to the value changed event.

**Comment by comintern** [comment]
Of those options, it seems like the more reasonable one (at least in the short term) would be to switch to `OneTime` binding.  I'd assumed that was what we were doing but that's apparently not the case. I can't really think of a situation where an inspection result would "change" with our current inspection architecture unless the entire `ObservableCollection` was being replaced.

If we ever do change the overall architecture to allow more dynamic inspection, that would be the time to add an `InspectionResultViewModel`. I think this would just warrant a comment in the xaml as to why the binding is `OneTime`.

**Comment by comintern** [comment]
This should be closed with #4717
