### ISSUE TITLE
Rubberduck menu not visible

### ISSUE THREAD

**Issue by SystemsModelling** [rubberduck-vba/Rubberduck#4668]
I just installed RD to a non-admin user on a new PC,64 bit Excel 2016 in O365. The Add-in Manager shows it Loaded, and on Startup. but there is no Rubberduck menu in the VBE. I unchecked and rechecked Loaded but it did not appear. Should I reinstall as admin?

**Comment by SystemsModelling** [comment]
I just installed RD to a non-admin user on a new PC,64 bit Excel 2016 in O365. The Add-in Manager shows it Loaded, and on Startup. but there is no Rubberduck menu in the VBE. I unchecked and rechecked Loaded but it did not appear. Should I reinstall as admin?

**Comment by bclothier** [comment]
Can you please upload the trace log?

**Comment by SystemsModelling** [comment]
2018-12-20 19:54:03.9404;INFO-;Rubberduck._Extension;Rubberduck is shutting down.;
2018-12-20 19:54:04.0664;INFO-;Rubberduck._Extension;No exceptions were thrown.;
2018-12-20 20:12:05.2856;INFO-;Rubberduck._Extension;Rubberduck is shutting down.;
2018-12-20 20:12:05.2856;INFO-;Rubberduck._Extension;No exceptions were thrown.;

**Comment by daFreeMan** [comment]
Is that the whole log?

**Comment by SystemsModelling** [comment]
Today I redownloaded and reinstalled as an admin user. For all users. Checked the box to Uninstall prev version. Ran Repair Installation script. Still appears  in Add-in Manager but no menu.

**Comment by bclothier** [comment]
Could you upload the logs again for the latest attempt?

**Comment by Inarion** [comment]
You can temporarily rename/move the file `rubberduck.config` under `%userprofile%\AppData\Roaming\Rubberduck` before starting Rubberduck. This should force the default settings which include logging on the `Trace` level.

**Comment by johnnyhawk02** [comment]
same here, office 365 with latest version of rubberduck. i have since reinstalled windows with just office and rubberduck, it's showing up in addins

**Comment by Vogel612** [comment]
@johnnyhawk02 	do you have any logfiles under `%APPDATA%/Rubberduck/Logs` that are different from the files provided by SystemsModelling? If yes, could you please upload those?

**Comment by johnnyhawk02** [comment]
i've looked in C:\Users\johnn\AppData\Local\Rubberduck and there's no 'logs' folder
am i looking in the right place?

**Comment by comintern** [comment]
@johnnyhawk02 It should be in AppData\Roaming, not Local.

**Comment by johnnyhawk02** [comment]
there's no rubberduck folder  in C:\Users\johnn\AppData\Roaming

**Comment by comintern** [comment]
@johnnyhawk02 OK, thanks for checking.  And just to confirm, you're not using anything like Terminal Services, etc. that would be restricting access to the Roaming folder?

**Comment by johnnyhawk02** [comment]
no, i just used 'reset this PC', then downloaded office from my Microsoft account, then downloaded rubber duck

**Comment by bclothier** [comment]
As a favor, can you please open up VBE, and in immediate window (<kbd>ctrl</kbd> + <kbd>G</kbd>), enter the following: 

```
?CreateObject("Rubberduck.FakesProvider") Is Nothing
```
and verify you do not get an error and a `False` as the output?

**Comment by johnnyhawk02** [comment]
if you need any other info or have any other tests - i'm more than happy to help

**Comment by johnnyhawk02** [comment]
i uninstalled then installed v2.3.1.4308 and it's now working

**Comment by bclothier** [comment]
Thanks for that followup. That's a good evidence that something broke between the green release and the subsequent pre-releases. Were you on any other pre-releases between the .4308 and the .4350?

**Comment by johnnyhawk02** [comment]
no, i only found out about rubberduck (and refactoring - which ive always called tidying-up)a day or two ago, i will uninstall and try other versions to see if i can find out where it broke,

**Comment by johnnyhawk02** [comment]
Ok I uninstalled and installed 3 inbetween versions, which all worked. Then I tried the latest version which also works now

**Comment by johnnyhawk02** [comment]
does the uninstall remove everything?

**Comment by retailcoder** [comment]
Uninstalling removes the DLLs and registry keys, but leaves the xml config file in place so user settings can be preserved between updates.
