### ISSUE TITLE
Latest release(Rubberduck v2.3.1.4308)  is reported as trojan from MS Windows defense

### ISSUE THREAD

**Issue by Garfield1985** [rubberduck-vba/Rubberduck#4671]
The latest release downloaded from github was blocked by MS Windows defense. It is said "Trojan:Win32/Cloxer.D!cl" was found and quarantined directly.

This is briefing for this threat https://go.microsoft.com/fwlink/?linkid=142185&name=Trojan:Win32/Cloxer.D!cl&threatid=2147726003

**Comment by bclothier** [comment]
I've submitted the file to Microsoft for analysis since I believe this is incorrect detection. Unfortunately we cannot do much; it's up to Microsoft to update it.

For reference: [the submission of the file](https://www.microsoft.com/en-us/wdsi/submission/df6dd3bb-8849-4c93-bf36-dbc92e249cca)

**Comment by bclothier** [comment]
![image](https://user-images.githubusercontent.com/2367644/50386213-14845500-06a8-11e9-989c-3afb70586e60.png)

**Comment by bclothier** [comment]
Since there is no contrary reports, I will close this as resolved.
