### ISSUE TITLE
Testing VBA code using Rubberduck Framework

### ISSUE THREAD

**Issue by Kuselokusi** [rubberduck-vba/Rubberduck#4682]
Hi, I am trying to test my VBA code using the Rubberduck framework however when I press "Run all tests" in the test explorer nothing happens. I don't have any experience with the frame work and don't understand what the issue is. My code is:
```
''function below can be used to calculate TPR, TNR, FPR and FNR
Public Function TPR_TNR_FPR_FNR(ByRef expected_vals As Variant, ByRef pred_vals As Variant, ByVal val_tested As Double) As Double

    Dim workValues As Variant
    Dim predValues As Variant

    If Not IsArray(expected_vals) Or Not IsArray(pred_vals) Then
        Err.Raise 5, "TPR_TNR_FPR_FNR", "Parameters must be arrays."
    Else
        workValues = expected_vals
        predValues = pred_vals
    End If
    ''To test if "expected_vals" is a range
    If TypeOf expected_vals Is Excel.Range Then
        If expected_vals.Columns.Count <> 1 Then Err.Raise 5, "TPR_TNR_FPR_FNR", "'expected_vals' must be a single column."
        workValues = Application.WorksheetFunction.Transpose(expected_vals)
    End If
    ''To test if "pred_vals" is a range
    If TypeOf pred_vals Is Excel.Range Then
        If pred_vals.Columns.Count <> 1 Then Err.Raise 5, "TPR_TNR_FPR_FNR", "'pred_vals' must be a single column."
        predValues = Application.WorksheetFunction.Transpose(pred_vals)
    End If
    ''To test if "workValues" and "predValues" are the same size
    If UBound(workValues) <> UBound(predValues) Then
        Err.Raise 5, "TPR_TNR_FPR_FNR", "'expected_vals' and 'pred_vals' must be the same size."
    End If

    Dim matchingExpectedValuesCount As Long
    Dim currentIndex As Long
    For currentIndex = LBound(workValues) To UBound(workValues)
        If workValues(currentIndex) = val_tested Then
            matchingExpectedValuesCount = matchingExpectedValuesCount + 1
        End If
    Next

    If matchingExpectedValuesCount = 0 Then
        TPR_TNR_FPR_FNR = 0
        Exit Function
    End If

    Dim count_correct As Long
    For currentIndex = LBound(predValues) To UBound(predValues)
        If workValues(currentIndex) = predValues(currentIndex) And workValues(currentIndex) = val_tested Then
            count_correct = count_correct + 1
        End If
    Next

    TPR_TNR_FPR_FNR = count_correct / matchingExpectedValuesCount

End Function
```
My test module is:
```
'@TestMethod
Public Sub GivenDifferentSizeArrays_Throws()
    Const ExpectedError As Long = 5
    On Error GoTo TestFail

    'Arrange:
    Dim expectedValues As Variant
    expectedValues = Array(1, 2, 3)

    Dim predValues As Variant
    predValues = Array(1, 2, 3, 4)

    'Act:
    Dim result As Double
    result = TPR_TNR_FPR_FNR(expectedValues, predValues, 1)

Assert:
    Assert.Fail "Expected error was not raised."

TestExit:
    Exit Sub
TestFail:
    If Err.Number = ExpectedError Then
        Resume TestExit
    Else
        Resume Assert
    End If
End Sub
```
Kindly indicate what I am doing wrong please.

**Comment by Vogel612** [comment]
Have you performed a full parse of the codebase by clicking "refresh" before that? The unit-tests should be showing up in the test explorer before you can run them ...

**Comment by bclothier** [comment]
Just to confirm - is that the entirety of the test module? No other procedures or declarations? Normally, when adding a test module via the Add menu, there are few extra stuff included for proper setup/teardown. More importantly, there'd have to be a `'@TestModule` annotation in the declaration, I believe.

**Comment by Kuselokusi** [comment]
Thank you so much, I was missing the `'@TestModule` at the top of the code. Once I inserted that it worked and yes that is the entire test module above.

**Comment by bclothier** [comment]
I should point out that the test module might seem to work because you don't have `Option Explicit` and would actually fail when you try to run `Assert.Fail`. In your test, that line never is reached because you expect an error. However, `Assert` class is not initialized. Try and use the `Add Test Module`; you'll note that it includes the procedures necessary to initialize the `Assert` and `Fakes` classes.

**Comment by Kuselokusi** [comment]
Alright I see, thank you for indicating that. But where exactly does one put the code that I wrote once I use `Add Test Module`?...my issue is that there is nothing that explicitly states that "your code must be placed here" once the Test Module appears which includes the procedures necessary to initialize the Assert and Fakes classes.

**Comment by bclothier** [comment]
I think I understand the problem here. It has been a two step process -- you use `Add Test Module`, THEN `Add Test Method` within the newly created module (or pre-existing test module). 

The `Add Test Module` create the module but not the code to run tests by default. However, you can configure that to do it by default via the settings:
![image](https://user-images.githubusercontent.com/2367644/50602614-55852200-0e7d-11e9-9cee-be8db3595f69.png)

**Comment by Kuselokusi** [comment]
> I should point out that the test module might seem to work because you don't have `Option Explicit` and would actually fail when you try to run `Assert.Fail`. In your test, that line never is reached because you expect an error. However, `Assert` class is not initialized. Try and use the `Add Test Module`; you'll note that it includes the procedures necessary to initialize the `Assert` and `Fakes` classes.

How do I stop it from failing at `Assert.Fail` cause I don't understand why it would fail.

**Comment by retailcoder** [comment]
`Assert` is an object variable that is declared at module-level; if you early-bind /reference the Rubberduck type library (there's a setting for that, IIRC the default is late-bound), adding a test module (not manually - using the "add test module" command) automatically adds that reference to your project, and the `Assert` object is declared at the top of the module, near `Option Explicit`:

    Private Assert As Rubberduck.AssertClass

Being an object variable, it must be assigned to an object reference before it can be used - so the test module template provides a `TestInitialize` method that Rubberduck runs before every test in the module, and a `ModuleInitialize` method that Rubberduck runs before any test in the module (tests are executed sequentially, one test module at a time); the template uses one of these methods to initialize the `Assert` object:

    Set Assert = New Rubberduck.AssertClass

Or:

    Set Assert = CreateObject("Rubberduck.AssertClass")

Without this assignment, a member call against the `Assert` object would throw runtime error 91 "object or with block variable not set" - hence, `Assert.Whatever` wouldn't even get to run.

I would recommend familiarizing with objects and variable declarations and scopes before venturing into unit testing though. [This wiki page](https://github.com/rubberduck-vba/Rubberduck/wiki/Unit-Testing) (hopefully not too outdated) should help understanding the assert class and the test stubs - there's an example at the bottom, too.

**Comment by Kuselokusi** [comment]
Makes sense. Thank you I have done it

**Comment by bclothier** [comment]
Glad to hear! Thanks for reporting back.
