### ISSUE TITLE
Stop rewriting dirty modules

### ISSUE THREAD

**Issue by MDoerner** [rubberduck-vba/Rubberduck#4688]
Currently, we apply rewrites to modules without regard whether the rewrite was requested on a dirty, i.e. already modified, module. This effectively reverts all changed to the module since the last parse. We should not do this.

Putting the check into the `CanExecute` methods of all commands is not an option, I think, because it checking whether a module is dirty requires computing the content hash of the module contents. Moreover, this would not cover all rewrite operations.

Technically, it is rather easy to invalidate a rewrite session in case an attempt is made to check out a rewriter for the first time that is already dirty. The problem is more that we have to decide on how to communicate that the rewrite failed because of a stale parser state. Not actively notifying the user will make the feature rather look broken instead of preventing a bad operation caused by a user error.

From the top of my head, I see already several options hoe to proceed on checkout of a dirty module.

1. Simply invalidate the rewrite session. This will make `TryRewrite` return `false` and immediately bail out.
2. As above, but also inject a notification service into the rewrite sessions that gets notified when a dirty module gets checked out.
3. As above, but with the notification on the attempt to rewrite.
4. Throw a custom exception when a dirty module gets checked out.

Option 1 and 4 push the responsibility to report the error to the users of the rewrite sessions. This means that a lot of places need to get changed in order to implement this, at least the `QuickFixProvider`, the `MemberAttributesRecoverer` and all refactorings. For option 1, the result type of `TryRewrite` would also have to change in order to allow communicating that a stale module caused the failure to rewrite. 

Option 2 and 3 require only local changes in the rewrite sessions and their factory. The downside is that the operation requiring the rewrite is not known. Thus, only a generic error that a rewrite was aborted because of a (specified) stale module can be shown to the user.

I would appreciate any opinion on how to handle this issue best. Please also feel free to suggest any other approach not covered by the four points above.

**Comment by bclothier** [comment]
I think the option 3 is the best compromise. That way, the consumers can decide for themselves if they want to provide detailed error reporting, which would require subscription to the notification service, or simply silently ignore the failure. 

Just to point out - it might be sufficient to simply return a flag rather than a boolean. That wouldn't require a notification service and consumer would still have the data they need to provide a meaningful error reporting which they must implement themselves anyway.

**Comment by MDoerner** [comment]
Yet another fifth option would be to basically follow option 1, but also change the `IsInvalidated` property to `Status` returning a flag, which would either be `Valid` or describe the reaon for the invalidation.
