### ISSUE TITLE
Enable running tests by location

### ISSUE THREAD

**Issue by bclothier** [rubberduck-vba/Rubberduck#4704]
In addition to category and selection, it should be possible (and hopefully trivial) to run tests based on their location (e.g. module they are in). 

_Originally posted by @bclothier in https://github.com/rubberduck-vba/Rubberduck/issues/4698#issuecomment-453072604_

**Comment by Vogel612** [comment]
This is somewhat abstractable to running tests based on their current grouping in the grouping grid. As such we'd need a "Run Tests in Selected Group", where group would be any single of:

 - Location
 - Outcome
 - Category
 - ...?

**Comment by Irubataru** [comment]
I think that is what I suggested when I talked about it that it would be more versatile if you could run issues in the selected group. In that case it could also replace "Run selected category" (and invalidate #4703) as that functionality would be there if you chose to group by category.

**Comment by comintern** [comment]
The problem inherent in this UI is that it kind of conflicts with "Run selected tests" if we're allowing multi-selection in the test grid (see #4701). If the user Ctrl selects multiple row in different groupings, then what exactly is the "Selected Group"? Both of them?

The menu on the toolbar currently gives the following options:

![screenshot from 2019-02-02 12-54-46](https://user-images.githubusercontent.com/8944005/52167999-d5571400-26e9-11e9-9a78-c049daf0a97d.png)

Compare this to the options available in the VS "Run..." menu:

![screenshot from 2019-02-02 12-56-35](https://user-images.githubusercontent.com/8944005/52168023-10594780-26ea-11e9-89ad-5488ea35ee6b.png)

The main difference is that VS _also_ has context menus in its TreeView for running a selected node, whether or not it has sub-nodes. If it does have sub-nodes, it runs all of them. 

The compromise here might be to just remove the "Selected Category" option from the toolbar completely (ref #4703) and change the "Selected Test" option to "Selected Tests" (plural).  We could then add context menus on the grid expanders more fine grained control. Maybe something like:

```
Run Group
---------
Collapse
Expand
```
Individual tests *could* have context menus also, but I'm not sure what to put in them other than "Run Test" (although VS has an "Add to playlist option..." :grinning: )

Thoughts?

**Comment by bclothier** [comment]
FWIW as long we gain a right-click menu to run a test in a group (regardless of what the grouping is set), I think losing the `Selected Category` and having `Run selected tests` makes more sense and as a bonus simplify the UI. I'm for it.

**Comment by comintern** [comment]
Closed via #4769.
