### ISSUE TITLE
Broken Folder Annotation 

### ISSUE THREAD

**Issue by djrivers** [rubberduck-vba/Rubberduck#4715]
Hi everyone. So I just downloaded and installed the latest version 2.3.1.4431 and noticed that the folder annotation is not recognizing the subfolder. It's just applying the main folder. `'@Folder("Class Module.Business Logic.EnoughInventoryStocks") ` should have folders Class Module>Business Logic>EnoughInventoryStocks. But after installing version 2.3.1.4431, that same folder annotation will now just show folder Class Modules. It used to work in version 2.3.1.4414

![folder annotation issue](https://user-images.githubusercontent.com/40927759/51262015-0eb42380-1977-11e9-8672-11bdba7a9ac8.png)

Version 2.3.1.4431
OS: Microsoft Windows NT 10.0.17134.0, x64
Host Product: Microsoft Office x64
Host Version: 16.0.11126.20196
Host Executable: MSACCESS.EXE

**Comment by comintern** [comment]
Thanks for the report - the Code Explorer just underwent a major re-write, so you happened to catch the "rawest" version of the performance updates.  I should be able to get a hot-fix in for this sometime later today.
