### ISSUE TITLE
Indenter does not indent preprocessor commands within procedures

### ISSUE THREAD

**Issue by CHR-IS-B** [rubberduck-vba/Rubberduck#4725]
**Rubberduck version information**
Version 2.3.0.4261
OS: Microsoft Windows NT 6.1.7601 Service Pack 1, x64
Host Product: Microsoft Office 2016 x86
Host Version: 16.0.4771.1000
Host Executable: EXCEL.EXE

**Description**
Preprocessor commands such as `#If` used within procedures are not indented.

**To Reproduce**
1. Place this in a code module:
```
Sub ReproduceBug()
#If 1 = 1 Then
MsgBox "Math still works!"
#Else
MsgBox "Match is broken."
#End If
End Sub
```
2. Run the RD indenter.
3. Notice the indentation of the `#If`, `#End` and `#End If` lines did not change.

**Expected behavior**
The `#If`, `#End` and `#End If` lines should be indented one step.

**Comment by comintern** [comment]
Can you check the following 2 indenter settings that could effect this?

Force compiler directives to column 1 would cause this behavior if checked.
Indent compiler directives would (for the sample code above) cause this behavior if unchecked.

If the problem still persists, there is an Export link in the top right corner of the indenter settings form - click the link, and then append the resulting file to the issue.

Thanks!

**Comment by comintern** [comment]
Closing as no-repro.  This can be re-opened if additional information is provided that allows it to be reproduced.

**Comment by CHR-IS-B** [comment]
@comintern, yes, it was the indenter settings.  I wanted compiler directives to be indented the same as everything else.  This works when "Force compiler directives to column 1"  is not checked and "Indent compiler directives" is checked.
