### ISSUE TITLE
Refactor rename does not use the selected identifier

### ISSUE THREAD

**Issue by SteveLaycock** [rubberduck-vba/Rubberduck#4732]
Version 2.3.1.4445
OS: Microsoft Windows NT 10.0.17763.0, x64
Host Product: Microsoft Office x64
Host Version: 16.0.11231.20080
Host Executable: WINWORD.EXE

**Description**
Refactor rename does not use the selected identifier.

In the code below I tried to rename  Logger.report to Logger.log.  I  refreshed rubberduck then selected the identifier 'report' followed by rubberduck.refactor.rename.  The identifier in the rename dialog box was the name of the procedure 'DoLogging' and not the identifier 'report'.

This behavior is consistent across restarts of Word.

Report is a method described in an interface 'LoggerMemberInterface'

There are currently two loggers defined that use 'LoggerMemberInterface'. One logs to the immediate window, the other to a text file.
```
Private Sub DoLogging(ByVal this_formatter As String, ByVal this_concern As String, ByRef this_items() As Variant)

Dim logger                              As Variant
Dim loggerItems()                       As Variant
    
    this_formatter = Striing.Foormat("{0}{tb1}{1}: ", Format$(Now(), "yyyy-mm-dd at hh:mm:ss"), this_concern) & this_formatter
    loggerItems = p.loggers.Items
    
    For Each logger In loggerItems
    
        logger.Report this_formatter, this_items
    
    Next

End Sub
```

The specific procedure that all called by report are below

Immediate logger

```
Private Sub LoggerMemberInterface_Report(ByVal this_formatter As String, ByRef this_items() As Variant)

    Report this_formatter, this_items()
    
End Sub

Public Sub Report(ByVal this_formatter As String, ByRef this_items() As Variant)

    Debug.Print Striing.Foormat(this_formatter, this_items())
    
End Sub

```
TextFile Logger

```
Private Sub LoggerMemberInterface_Report(ByVal this_formatter As String, ByRef this_items() As Variant)

    Report this_formatter, this_items()
    
End Sub

Public Sub Report(ByVal this_formatter As String, ByRef this_items() As Variant)
    
    s.fso_ts.WriteLine Striing.Foormat(this_formatter, this_items())
    
End Sub
```

**Comment by retailcoder** [comment]
`logger` is a Variant, thus Rubberduck has no idea what `logger.Report` is - there's likely a warning log entry specifically about this.

While I agree this could *probably* be improved, it isn't a bug: Rubberduck can't know what the members of a `Variant` are.

If you have a logger interface, `logger` should probably ve declared as such - that would turn your late-binding duck-typed polymorphism (works? great! doesn't? boom, error 438) into actual interface-based polymorphism (compile-time validated).

Rubberduck doesn't work with variants. The VBE doesn't work with variants. And you shouldn't be working with variants if you can avoid it.

**Comment by retailcoder** [comment]
Basically there is nothing in `DoLogging` that even remotely hints at what the interface should be; everything being `Variant`, you get no IntelliSense for any of this, and `Option Explicit` can't spare you from a typo, since the compiler has no way of knowing what the members of a variant are. This is 100% late-bound code where none of the types are known until run-time; compile-time types are all `Variant`.

As a *static* code analysis tool, Rubberduck can't know what the runtime types are.

Change the declaration so that there's a compile-time type other than `Variant` or `Object` (which would arguably be better than `Variant` in this case) to work with:

    Dim logger As ILogger ' or whatever your interface name is

And now everything works as it should.

**Comment by SteveLaycock** [comment]
Thanks for the pointers.  logger is a scripting.dictionary of LoggerMemberInterface objects.  In this specific instance if I change

Dim logger as variant
to 
Dim logger as LoggerMemberInterface

VBA throws a wobbly and insists that logger should be a variant even though it should be possible to use an object as a control variable.

Thinking about your advice I revised the DoLogging code to

 ```
Private Sub DoLogging(ByVal this_formatter As String, ByVal this_concern As String, ByRef this_items() As Variant)

Dim logger                              As Variant
Dim loggerItems()                       As Variant
Dim loggermember                        As LoggerMemberInterface

    ' The last item in this_items() is the location to report from
    
    this_formatter = Striing.Foormat("{0}{tb1}{1}: ", Format$(Now(), "yyyy-mm-dd at hh:mm:ss"), this_concern) & this_formatter
    loggerItems = p.loggers.Items
    
    For Each logger In loggerItems
        Set loggermember = logger
        loggermember.log this_formatter, this_items
    
    Next

End Sub
```

and the refactor rename is partially(?) successful. The code above is renamed successfully but for the interface code I get.

```
Private Sub LoggerMemberInterface_log(ByVal this_formatter As String, ByRef this_items() As Variant)

    Report this_formatter, this_items()
    
End Sub


Public Sub Report(ByVal this_formatter As String, ByRef this_items() As Variant)

    Debug.Print Striing.Foormat(this_formatter, this_items())
    
End Sub
```

and

```
Private Sub LoggerMemberInterface_log(ByVal this_formatter As String, ByRef this_items() As Variant)

    Report this_formatter, this_items()
    
End Sub


Public Sub Report(ByVal this_formatter As String, ByRef this_items() As Variant)

    Debug.Print Striing.Foormat(this_formatter, this_items())
    
End Sub
```

Am I mistaken in expecting a rename of Public Sub Report to Public Sub Log?

**Comment by SteveLaycock** [comment]
OK.  A bit of testing shows that it is an unreasonable expectation of mine that the Sub report renaming should occur.
