### ISSUE TITLE
Release 2.4 needs French translations 

### ISSUE THREAD

**Issue by MDoerner** [rubberduck-vba/Rubberduck#4735]
The title says it all.

**Comment by D3vlin** [comment]
Spanish translations?

**Comment by bclothier** [comment]
Any languages can be translated! The issue is that we need volunteers to help and translate them into the target language. If you are interested or know who would be, we can help get this started and thus enable Spanish (or any other languages).

**Comment by D3vlin** [comment]
Great! I have little knowledge, but how could I help?

**Comment by comintern** [comment]
@D3vlin I'd take a scan through the wiki if you haven't already. How is your c#?

**Comment by D3vlin** [comment]
My ability with C# is basic, I understand the language. Management of variables, arrays, classes.
but I do not have very advanced knowledge.

**Comment by bclothier** [comment]
Great, that's good enough. 

You should start by reading through [Contributing](https://github.com/rubberduck-vba/Rubberduck/wiki/Contributing), so you can fork the project and start building. You can also join the [chat](https://chat.stackexchange.com/rooms/14929/vba-rubberducking) - if you do not have enough SE rep, one of the room owner can authorize you and you can then start more detailed questions to get started.

**Comment by D3vlin** [comment]
ok, I will start reading to understand how to contribute. I still can not access the chat, I'm a new user in stackexchange.

**Comment by bclothier** [comment]
Ok will have mod authorize you - you're `user477247`?

**Comment by D3vlin** [comment]
Yes
