### ISSUE TITLE
Settings:Code Inspection: Code Quality Issues: Two instances of 'Inappropriate  use of 'IsMissing' function'

### ISSUE THREAD

**Issue by SteveLaycock** [rubberduck-vba/Rubberduck#4740]
**Rubberduck version information**
Version 2.3.1.4460
OS: Microsoft Windows NT 10.0.17763.0, x64
Host Product: Microsoft Office x64
Host Version: 16.0.11231.20080
Host Executable: WINWORD.EXE

As per the title there are two instances of the Inappropriate use of 'IsMissing' function in Code Quality settings.

**Comment by SteveLaycock** [comment]
Its a Rubberduck dialog box. 

Rubberduck.Code.Settings.Code Inspection Settings.Code Quality Issues.

I see two entries for 'Inappropriate use of 'IsMissing' Function'

This seems odd to me hence I've reported it.  If two entries is correct I'd again make the observation that it seems odd, but you should  feel free to close this report.

**Comment by comintern** [comment]
@SteveLaycock - Nope, you're absolutely correct, they need to appear differently in the settings window.  Nice catch!
