### ISSUE TITLE
Library not found

### ISSUE THREAD

**Issue by SteveLaycock** [rubberduck-vba/Rubberduck#4755]
**Rubberduck version information**
Version 2.4.0.4492
OS: Microsoft Windows NT 10.0.17763.0, x64
Host Product: Microsoft Office x64
Host Version: 16.0.11231.20120
Host Executable: WINWORD.EXE

Rubberduck is installed and appears in the menu bar but macros give a Library not found error.

Tools.References says that the RubberDuck addin is missing.

Looking in the ProgramData\Rubberduck directory it would seem that RebberDuck.x64.tlb is missing.
RubberDuck.x32.tlb is present.

**Comment by bclothier** [comment]
Indeed. I can reproduce this. As workaround use 4488.
