### ISSUE TITLE
autocompletion doesn't work (in my computer..)

### ISSUE THREAD

**Issue by 770shl** [rubberduck-vba/Rubberduck#4761]
thanks a lot for an amazing job 

i was looking forward to the autocompletion feature
so i enabled the autocompletion and tried it
but it doesn't do anything

it seems like i'm missing something...

if i type "if then" and then click on "enter" or "tab" nothing happened (except the new line or a tab)
i tried with space before the enter, without space,
with "autocompletion Block on Enter" or "with autocompletion Block on TAB" or with both

the self-closing pairs work fine

i have windows 10 
office 2016 64 bit

thanks again

**Comment by retailcoder** [comment]
Thanks for the feedback!
Block completion is still pending a rewrite at this time: indeed the checkbox to enable it doesn't do anything for now (should probably be removed until block AC is completed).

**Comment by 770shl** [comment]
ok, thanks
should i close the issue?
