### ISSUE TITLE
Code explorer cutting off search icon

### ISSUE THREAD

**Issue by IvenBach** [rubberduck-vba/Rubberduck#4766]
Version 2.3.1.4465
OS: Microsoft Windows NT 6.1.7601 Service Pack 1, x64
Host Product: Microsoft Office 2013 x86
Host Version: 15.0.5093.1000
Host Executable: EXCEL.EXE

![untitled](https://user-images.githubusercontent.com/26076874/52157216-42af6a00-2642-11e9-923a-02e3ac341a4d.png)

**Comment by comintern** [comment]
This was known in 2.3.1.4465 and was addressed with #4748.  Can you pull the current build and verify that it renders without clipping?

Ref #4749

**Comment by IvenBach** [comment]
Pulled Version 2.4.0.4505 and icon displays correctly.
