### ISSUE TITLE
Unable to Rename Class Property

### ISSUE THREAD

**Issue by BindiW** [rubberduck-vba/Rubberduck#4772]
**Rubberduck version information**
```
Version 2.4.0.4505
OS: Microsoft Windows NT 6.1.7601 Service Pack 1, x64
Host Product: Microsoft Office 2016 x86
Host Version: 16.0.7668.2074
Host Executable: EXCEL.EXE
```

**Description**
I'm trying to rename a property in a class. 

**To Reproduce**
1. Navigate to the property in the code explorer.
2. The property name is highlighted.
3. Click on "Rename"
4. The property name is de-selected, i.e. no longer highlighted.
3. Nothing else happens. No pop-up box appears to allow renaming.

**Additional context**
I've done this multiple times in other versions. It's not limited to one property. I can't rename anything in a class module.

**Comment by BindiW** [comment]
I copied version info from an old log file. It's actually:
Version 2.4.0.4505
OS: Microsoft Windows NT 6.1.7601 Service Pack 1, x64
Host Product: Microsoft Office 2016 x86
Host Version: 16.0.7668.2074
Host Executable: EXCEL.EXE

**Comment by comintern** [comment]
Thanks for the issue report.  This is already known and will be closed when #4765 merges.

**Comment by retailcoder** [comment]
I've merged the linked PR - there will be a new pre-release build available in 20-30 minutes, after AppVeyor completes the build and runs all the tests.

**Comment by retailcoder** [comment]
It's here! https://github.com/rubberduck-vba/Rubberduck/releases/tag/Prerelease-v2.4.0.4511
