### ISSUE TITLE
ExtractInterface: Missing parameters in Interface signatures - Optional parameters only

### ISSUE THREAD

**Issue by SteveLaycock** [rubberduck-vba/Rubberduck#4774]
**Rubberduck version information**
Version 2.4.0.4511
OS: Microsoft Windows NT 10.0.17763.0, x64
Host Product: Microsoft Office x64
Host Version: 16.0.11231.20130
Host Executable: WINWORD.EXE

**Description**
RubberDuck.Refactor.ExtractInterface gives rise to some methods of the the interface class having no parameters in the method declaration if the originating method has optional arguments.

In the implementation inserted in the class from which the interface was extracted, the method signature does include the parameters but omits the Optional clause in the signature.

Source Method

```
Public Property Get AsItemTypeValueStr(Optional ByVal this_property As String = "Item") As String

    proj.Log.Trace _
        is_module, "{0}.{1}", _
        s.name, _
        ErrEx.LiveCallstack.ProcedureName

    ' Overloading VBA style
    If LenB(this_property) = 0 Then
        AsItemTypeValueStr = AsItemTypeValueStringNoOpt
    Else
        AsItemTypeValueStr = AsItemTypeValueStringWithOpt(this_property)
    End If

End Property
```
Implementation
```
Private Property Get ITestXmlPair_AsItemTypeValueStr(ByVal this_property As String) As String
    Err.Raise 5 'TODO implement interface member
End Property
```
Interface
```
Public Property Get AsItemTypeValueStr() As String
End Property
```

**Logfile**
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/2836721/RubberduckLog.txt)

**Additional context**

[TestXmlPair.zip](https://github.com/rubberduck-vba/Rubberduck/files/2836743/TestXmlPair.zip)

**Comment by comintern** [comment]
This is apparently also an issue with Implement Interface, and `ParamArray` is also dropped.
