### ISSUE TITLE
Using PredeclaredID Template - How?

### ISSUE THREAD

**Issue by SmileyFtW** [rubberduck-vba/Rubberduck#4785]
I've seen discussion on the subject, but for the life of me cannot seem to find anything to get me started on how to actually use the PredeclaredID template (or any template for that matter). I'm probably just not looking in the right place.

A point in the right direction is much appreciated.

**Comment by comintern** [comment]
These can currently be added via the Code Explorer:

![screenshot from 2019-02-09 09-35-56](https://user-images.githubusercontent.com/8944005/52522701-6bd98700-2c4e-11e9-90b6-4e5ceefce9a0.png)

If you have suggestions as to how to make this feature more discoverable, we're all ears.

**Comment by retailcoder** [comment]
Side note, this template is kind of superseded by the `@Predeclared` annotation: you can now easily make any class have a `VB_PredeclaredId = True` attribute value by simply adding this annotation, then parsing and reviewing inspection results under the "Rubberduck Opportunities" category: an inspection result will warn about the annotation being present without a corresponding attribute value, and a quick-fix can be applied to "synchronize" attributes with the annotations, either by removing the annotation, or by adding the hidden attribute.

**Comment by SmileyFtW** [comment]
Ahhhhhh! So *that* is the magic!

 

Thank you, Mathieu!

 

I am having fun learning to set up models, using the proxies, and presenters. It is beginning to become a little more familiar to me. I still don’t have my head around all of it in a way that it is second nature and not yet how I “think about” a solution. And I haven’t even begun the journey down the Unit Testing path.

 

RD is a pleasure to use, and I know that I don’t even comprehend all that it does.

 

Miley

**Comment by SmileyFtW** [comment]
LOL… You guys are great!

 

I think it has as much to do with my lack of programming experience than anything else.

 

I have learned so much in the last few weeks my head is about to explode. Getting my brain wrapped around Interfaces, Presenters and abstracting things away has been a challenge for this 66 year-old with a huge bunch of sloppy habits and old ways of thinking. You young guys are on top of it and I am playing a huge game of catch up.

 

Thank you and everyone else who has reached out to help me and for all of you and the work that you do on this project.

 

Kindest regards,

David Miley

**Comment by SmileyFtW** [comment]
So the course of action would be to use the +Add with the template to start a fresh one (which I assume would also include the annotation) and proceed with the new class. For existing items simply adding the annotation and synchronize to alter an existing module would be the approach.

 

Thank you, Mathieu…

**Comment by bclothier** [comment]
The support seems to be resolved, so we'll close this issue. Naturally, if you have any new feedback, feel free to open a new issue. Thanks!
