### ISSUE TITLE
Put a link to the log in the "About" box

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#4797]
Since there's a wonderful new error reporting template and it prompts the user to supply all the version info from the "About" box _and_ it prompts the user to supply the log file as well, it would be really handy to have a link to the log file directory in the "About" box so I only have to open one RD dialogue in the VBE to complete my error report.

#EnableMyLazy

**Comment by daFreeMan** [comment]
This has been resolved, I believe by @Vogel612's PR.

**Comment by Vogel612** [comment]
@daFreeMan actually the PR was by @fernandreu, I just pressed the merge button
