### ISSUE TITLE
Assembly reference address doesn't always update

### ISSUE THREAD

**Issue by IvenBach** [rubberduck-vba/Rubberduck#4798]
Version 2.4.0.4533
OS: Microsoft Windows NT 6.1.7601 Service Pack 1, x64
Host Product: Microsoft Office 2013 x86
Host Version: 15.0.5093.1000
Host Executable: EXCEL.EXE

**Description**
Clicking from the left pane to the right pane the address to the assembly doesn't update. The address only updates when a new non-currently-selected assembly is selected.

**To Reproduce**
1. Rubberduck>Tools>Add/Remove references
2. Select an item it the left pane, then click to select item in right pane that's already selected. The address doesn't update.

**Expected behavior**
The address updates to show the currently selected assembly, even if it was already selected.

**Screenshots**
![legacy retailcoder folder](https://user-images.githubusercontent.com/26076874/52752585-37e0c780-2fa8-11e9-9401-9c8256736177.png)
Selecting between both already selected items doesn't update the address.

**Comment by IvenBach** [comment]
The legacy directory to RetailCoder.VBE is also something I need to look into. Directory doesn't exist on my machine when I checked for it.

**Comment by comintern** [comment]
Unless I'm missing something, this is the intended behavior. If there are multiple versions of a library, the dialog will show all of them.  You can resolve this by cleaning old versions out the the registry.

**Comment by IvenBach** [comment]
Cleared out old installs of RD. I'm still having this issue. Maybe screenshots will help me explain.

**Add/Remove References initially opened**
![nothing selected](https://user-images.githubusercontent.com/26076874/52755318-619eec00-2fb2-11e9-8190-24e428a979b6.png)

**Selecting an item in the left pane**
![left pane selected](https://user-images.githubusercontent.com/26076874/52755328-695e9080-2fb2-11e9-862d-81adf8fd02d9.png)

**Selecting item in the right pane**
![right pane selected](https://user-images.githubusercontent.com/26076874/52755340-6fed0800-2fb2-11e9-8c44-308da14fd656.png)

**Re-selecting previously selected item in left pane**
![left pane re-selected](https://user-images.githubusercontent.com/26076874/52755353-7e3b2400-2fb2-11e9-8933-701899d590d3.png)

The path for RD is still the path shown. This was the behavior I was attempting to point out.

**Comment by comintern** [comment]
Were you tabbing between fields, or using the mouse? I can't replicate this unless I move focus with the keyboard.  In that case, that's a WPF thing - it highlights the item that has focus, but it isn't actually _selected_.

**Comment by IvenBach** [comment]
I was using the mouse to click.
