### ISSUE TITLE
About box attributitions doesn't wrap text

### ISSUE THREAD

**Issue by IvenBach** [rubberduck-vba/Rubberduck#4801]
Version 2.4.0.4533
OS: Microsoft Windows NT 6.1.7601 Service Pack 1, x64
Host Product: Microsoft Office 2013 x86
Host Version: 15.0.5093.1000
Host Executable: EXCEL.EXE

**Description**
Text in the scrollviewer is cut off

**To Reproduce**
1. Rubberduck>About dialog.
2. Attributions window scroll down to bottom.

**Expected behavior**
Text should wrap.

**Screenshots**
![about box cutoff](https://user-images.githubusercontent.com/26076874/52804695-afab0280-3039-11e9-89da-cdbc839d0f5d.png)

**Comment by Vogel612** [comment]
That is at least partly intentional. We're relying on non-wrapping text for a lot of the content in that view. 

The scrollbar hiding the text could be avoided by setting a right margin to the text blocks defining the text.
