### ISSUE TITLE
Test explorer collapses group after running test

### ISSUE THREAD

**Issue by IvenBach** [rubberduck-vba/Rubberduck#4802]
Version 2.4.0.4533
OS: Microsoft Windows NT 6.1.7601 Service Pack 1, x64
Host Product: Microsoft Office 2013 x86
Host Version: 15.0.5093.1000
Host Executable: EXCEL.EXE

**Description**
Running unit tests collapses groups.

**To Reproduce**
1. Expand a group in Test Explorer.
2. Run a unit test.
3. See that groups are collapsed.

**Expected behavior**
Running tests should leave groups expanded or contracted and not modify them.

**Screenshots**
Before Running the test.
![test explorer before running test](https://user-images.githubusercontent.com/26076874/52805108-b7b77200-303a-11e9-9ac4-7a6024c41969.png)

After running test the group is collapsed.
![test explorer after running test](https://user-images.githubusercontent.com/26076874/52805120-c0a84380-303a-11e9-9e52-dd9322e12d62.png)

**Comment by comintern** [comment]
This will be closed by #4769.  I'd hold off on opening new UI issues for the TE until that merges ;-)

**Comment by comintern** [comment]
Closed via #4769.
