### ISSUE TITLE
Refactor Encapsulate field doesn't work with fields in a Type declaration 

### ISSUE THREAD

**Issue by ghost** [rubberduck-vba/Rubberduck#4805]
**Rubberduck version information**
Version 2.4.0.4533
OS: Microsoft Windows NT 10.0.17763.0, x64
Host Product: Microsoft Office x64
Host Version: 16.0.11328.20070
Host Executable: WINWORD.EXE

**Description**

If I select a field in a type definition I cannot select refactor.encapsulate.  This may be a bit of an unfair observation but arises from having followed the thinking in

https://rubberduckvba.wordpress.com/2018/04/

on 'this' and 'TSomething'.   I now use Properties and State Types in my modules and assign these as p and s respecively.  Unfortunately this means that Rubberduck doesn't see items in these Type as  fields that can be encapsulated.  

I suspect this should go on the nice to have list.

**Comment by bclothier** [comment]
Yep, this is still one of (several) things to improve. See #875; I suspect that needs to be implemented to make way clear for this suggestion.

**Comment by BZngr** [comment]
I think a better issue description would be: "Refactor Encapsulate field doesn't work with fields **_of_** a Type declaration".  IMO it does not make sense to select a `UDT Member` as the starting point of the refactoring (which is how it _seems_ to be described above).  The refactoring should only accept and operate on an instance field of the UDT.

And, currently, invoking `EncapsulateField` after selecting 'this' of  `Private this As TModuleName` does what is identified above.
