### ISSUE TITLE
Configured parsing

### ISSUE THREAD

**Issue by Gener4tor** [rubberduck-vba/Rubberduck#4809]
As the massive memory consumption of memory is the main problem I got with rubberduck (I have to restart my access db at least once/day because of this) I am thinking about ways to reduce this.

So I thought about if it would be possible to make the parsing more configurable (flexible).

So that I am able to parse all the info needed for the CodeExplorer (Which is the most needed feature for me) without parsing all the rest.

This would also speed up the start process as (in my case) rubberduck needs ~ 50 secs! to parse after starting.

**Comment by bclothier** [comment]
I'm going to close this as a duplicate because we already have an issue requesting a similar feature: #3697 and also the one about memory usage is pinned - #3347
