### ISSUE TITLE
Code Inspection: Assignment is not used ignores @IgnoreModule

### ISSUE THREAD

**Issue by SteveLaycock** [rubberduck-vba/Rubberduck#4812]
**Rubberduck version information**
Version 2.4.0.4550
OS: Microsoft Windows NT 10.0.17763.0, x64
Host Product: Microsoft Office x64
Host Version: 16.0.11328.20070
Host Executable: WINWORD.EXE

**Description**
I have a number of classes/module which have the '@IgnoreModule annotation.  I'm seeing that the code inspector is  reporting  'Assignment is not used'  in a couple of these modules.

**Comment by retailcoder** [comment]
Was the annotation added by the "ignore in module" quick-fix? What is the actual comment line (and if possible, the surrounding code)?

**Comment by retailcoder** [comment]
Confirming, `'@Ignore` is, uh, *ignored*, at individual result level, too.
