### ISSUE TITLE
Won't apply settings to newly formatted computer

### ISSUE THREAD

**Issue by djrivers** [rubberduck-vba/Rubberduck#4816]
Hi guys. So I just reformatted my laptop resetting it to the default factory. Everything was wiped out so I re-installed all the software. Then I installed the MS Suite, installed the Rubberduck and change the settings, it just won't save. You can put a tick in all of the boxes then when you click the OK button nothing happens. So only thing to do to close the settings box is to hit the close button in the upper right corner. When you open the settings of Rubberduck again, all the options that you chose were checked but it just doesn't work. And when you close the whole MS Access and relaunch it, open VBE and Rubberduck, all ticks in the boxes were removed. I don't know what happened. I never had this experience before. When the only factor to consider I guess is this is a really new installation this time. Not an update like what I usually do.

Version 2.4.0.4556
OS: Microsoft Windows NT 10.0.10586.0, x64
Host Product: Microsoft Office x64
Host Version: 16.0.11231.20174
Host Executable: MSACCESS.EXE

[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/2890868/RubberduckLog.txt)

**Comment by djrivers** [comment]
To add: Exporting settings doesn't work as well. It's not creating the .xml file.

**Comment by bclothier** [comment]
Can you download the green release and verify it works? The log suggests there's an issue w/ the persisting of the settings and there were changes made to it in recent merges for pre-releases.

**Comment by djrivers** [comment]
Ok. Let me check

**Comment by djrivers** [comment]
Version 2.4.0.4488 worked! I'll try to apply the latest update.

**Comment by djrivers** [comment]
Version 2.4.0.4556 is working now after installing and uninstalling Version 2.4.0.4488 first.

**Comment by bclothier** [comment]
This confirms that the recent PR did break something - so that means for interim, the settings won't  be saved as long you're running this pre-release. We'll try to get this fixed soon. Sorry for the inconvenience!

**Comment by djrivers** [comment]
It's fine. At least this bug was discovered.

**Comment by retailcoder** [comment]
Thanks for reporting it! We'll try to squeeze a fix for it by the time 2.4.1 is released, early next month.

**Comment by djrivers** [comment]
Great! :)
