### ISSUE TITLE
Settings form fails to load with language codes that aren't implemented.

### ISSUE THREAD

**Issue by comintern** [rubberduck-vba/Rubberduck#4818]
Pretty self explanatory. We have the UI cultures hard coded in a lookup without a check, so if the xml file uses a culture that isn't available in RD, the binder fails and the settings form doesn't load.

Can be reproduced with a settings file containing something like `<Language Code="fu-br" />`

**Comment by bclothier** [comment]
Ref [comment from PR 4699](https://github.com/rubberduck-vba/Rubberduck/pull/4699#discussion_r247512121)
