### ISSUE TITLE
Autocompletion overwrites character

### ISSUE THREAD

**Issue by IvenBach** [rubberduck-vba/Rubberduck#4826]
**Rubberduck version information**
Version 2.4.0.4533
OS: Microsoft Windows NT 6.1.7601 Service Pack 1, x64
Host Product: Microsoft Office 2013 x86
Host Version: 15.0.5093.1000
Host Executable: EXCEL.EXE

**Description**
When adding a string the addition of `""` removes characters.

**To Reproduce**
1. Have code in a module with cursor at `|`. Spaces on either side are intentional.
```
Public Sub MVCE_Autocomplete()
    Dim cell As Range
    For Each cell In Selection.Cells
        cell.Formula = "=" & cell.Row & | + cell.Column
    Next
End Sub
```
2. Type first double quote character and it removes the `+` character leaving focus between the enclosing double quotes.
```
cell.Formula = "=" & cell.Row &"|" cell.Column
```

**Expected behavior**
I'd expect `cell.Formula = "=" & cell.Row & "" + cell.Column` to be the result of adding the opening and closing quotes.

**Comment by retailcoder** [comment]
The VBE is "optimizing" it out.

    foo = "abc" & | + "xyz"

"Prettifies" to this:

    foo = "abc" & | "xyz"

...before the SCP handler even begins to process the code.. and if we put it in, the VBE would take it out - paste this:

    cell.Formula = "=" & cell.Row & + cell.Column

Then move to another line: the `+` is gone, and you're seeing the code SCP is working with.
