### ISSUE TITLE
How to Uninstall Rubberduck

### ISSUE THREAD

**Issue by gnsoria** [rubberduck-vba/Rubberduck#4837]
Apologies if this is answered somewhere and I'm just completely missing it. I'd like to uninstall Rubberduck, but I don't see how. I tried searching the docs for "Uninstall" as well as looking elsewhere for how to uninstall a VBE Add-In but haven't found much. Are there instructions for removing the Add-In? Is this as simple as unchecking "Loaded" from the VBE Add-In Manager? (And have [the issues with that](https://stackoverflow.com/questions/42538026/can-not-see-the-add-in-after-installing-rubberduck) fixed?)

**Comment by bclothier** [comment]
You should be uninstalling it the same way you do any other applications - via the *Add or Remove Programs*. This should remove everything, including the add-in registration.

The linked SO seem to indicate that the OP was looking in wrong places? As noted, Rubberduck is a VBE addin and thus managed by VBE, not by the host.

**Comment by retailcoder** [comment]
In addition to add/remove programs in the control panel, the installer creates a "Rubberduck" folder in the start menu (unless the box was unchecked), with a shortcut to uninstall.

Curious about why though?

**Comment by gnsoria** [comment]
Ah, thanks y'all! This is the first add-in like this that I've installed so I wanted to make sure I undid it correctly.

@retailcoder I'm uninstalling it because I'm distracting myself with tinkering with it when I should be focusing on other things. It's cool and shiny but it's also slowing me down a bit as I get used to it and try to learn it. I'll probably reinstall it in the future =)

**Comment by retailcoder** [comment]
@gnsoria thanks! don't hesitate to open a new issue if you have any ideas to make Rubberduck less distracting (settings to optionally hide or disable some commands and/or toolwindows?), and feel free to star us if you like! :smiley:

**Comment by gnsoria** [comment]
@retailcoder thanks, will do! My main concern was that it added a not-insignificant time to opening the VBE. I often close/open Excel frequently throughout the day to reduce the number of windows/apps I have open, but when I do open it, I'm often writing a quick script to process some data. So that meant waiting for the VBE/Rubberduck to load and parse my projects several times a day. Does it behave nicely with the "Start on launch" checkbox from the Add-In Manager? If so, maybe I can just uncheck that and load the Add-In when I need it. If not, I'd be happy to make an issue.

Thanks!
