### ISSUE TITLE
RegEx Assistant: error parsing pattern

### ISSUE THREAD

**Issue by SteveLaycock** [rubberduck-vba/Rubberduck#4839]
**Rubberduck version information**
Version 2.4.0.4580
OS: Microsoft Windows NT 10.0.17763.0, x64
Host Product: Microsoft Office x64
Host Version: 16.0.11328.20116
Host Executable: WINWORD.EXE

**Description**
The regex assistant complains when using the pattern '[^\w:\.\\]' but does not complain if the final \\ is moved to the start of the pattern e.g.  '[^\\\w:\.]'.  I'm happy to be told that my understanding of Regex is inadequate.

This pattern is being used as part of a replace to remove illegal characters from a string containing a filepath/name.

**Comment by Vogel612** [comment]
The issue here is that the pattern you provide is escaping the closing ] of the character class. That means the character class is unclosed, which is illegal

**Comment by SteveLaycock** [comment]
Ah.  The double \\\\ have been removed. My patterns should have been '[^\\w:\\.\\\\]'  and '[^\\\\\\w:\\.]'

**Comment by Vogel612** [comment]
preliminary finding: The test covering recognition of escaped literals is missing a case for `\\`.

https://github.com/rubberduck-vba/Rubberduck/blob/a77034362f08ce29c0fb6747ed247c126be4767c/RubberduckTests/RegexAssistant/LiteralTests.cs#L15

This implies that the code responsible for recognizing literals does not in fact correctly recognize `\\` as a literal, and instead assumes the first backslash there is an incorrectly placed escape, which is converted to an error token and makes the correctly escaped backslash into an escape for the closing `]`, which is of course incorrect.

I assume that the "working" pattern is not correctly analyzed either. Can you confirm that?

**Comment by SteveLaycock** [comment]
The working pattern does not raise any complaints in RegexAssistant.  I just get the statement confirming all is OK ' Matches any character that is not one of \\\\, \\w, :, \\. exactly once.'
