### ISSUE TITLE
False Positive Inspection - Variable is used but not assigned - with ByRef assignment

### ISSUE THREAD

**Issue by ChrisBrackett** [rubberduck-vba/Rubberduck#4842]
**Rubberduck version information**
The info below can be copy-paste-completed from the first lines of Rubberduck's log or the About box:

    Version 2.4.0.4578
    OS: Microsoft Windows NT 10.0.17763.0, x64
    Host Product: Microsoft Outlook x64
    Host Version: 16.0.4810.1000
    Host Executable: OUTLOOK.EXE

**Description**
When a module level variable is passed to a procedure ByRef and assigned a value, is subsequently called in a different procedure, RD returns inspection error "Variable is used but not assigned".

**To Reproduce**
Have RD inspect the following code:

```
Option Explicit
Private myModuleVar As String

Private Sub test()
    AssignValueByRef myModuleVar
    MsgBox myModuleVar
End Sub

Private Sub AssignValueByRef(ByRef var As String)
    var = 1
End Sub
```

**Expected behavior**
No inspection result.

**Comment by BZngr** [comment]
Example no longer generates an inspection result.  Fixed by previous PR.
