### ISSUE TITLE
Code Inspection window section expansion expands all

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#4849]
**Rubberduck version information**
The info below can be copy-paste-completed from the first lines of Rubberduck's log or the About box:
Version 2.4.0.4586
OS: Microsoft Windows NT 10.0.15063.0, x64
Host Product: Microsoft Office 2016 x64
Host Version: 16.0.4810.1000
Host Executable: MSACCESS.EXE

**Description**
Expanding one inspection grouping causes all to expand.

**To Reproduce**
1. Open CI window
2. Click on `Collapse all` button
3. Click on one grouping
4. All groups open

**Expected behavior**
Only the selected group should expand when clicking on it. All groups should expand when the `Expand all` button is clicked.

**Screenshots**
Clicked `Collapse All`:
![2019-03-07 08_30_54-code inspections](https://user-images.githubusercontent.com/11889733/53960533-8c152e00-40b4-11e9-877d-38315f326f0d.png)
Selecting the first group to expand:
![2019-03-07 08_31_10-code inspections](https://user-images.githubusercontent.com/11889733/53960540-8e778800-40b4-11e9-99c0-f7f86f2c43ef.png)
All groups have expanded:
![2019-03-07 08_31_19-code inspections](https://user-images.githubusercontent.com/11889733/53960545-90414b80-40b4-11e9-8bb2-705ee5082865.png)

**Logfile**
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/2941434/RubberduckLog.txt)

**Additional context**
This happens in all grouping methods. 
It seems that generally it does _not_ happen when expanding the first 2-3 groups (expand - OK, collapse, expand the next - OK, collapse). 
Group by `Location` seemed to work the longest - I had to expand/collapse about 10 locations before it triggered - once it triggered, any selection caused them all to expand/collapse all.
Clicking to collapse one group causes `Collapse all` to happen.

**Comment by SystemsModelling** [comment]
I'm still getting that in 2.4  Expand eg Code Quality and they all expand from Rubberduck Opportunities down.
