### ISSUE TITLE
Code Inspections: Its not possible to explore the contributors to a consolidated  Warning

### ISSUE THREAD

**Issue by SteveLaycock** [rubberduck-vba/Rubberduck#4870]
**Rubberduck version information**

Version 2.4.0.4618
OS: Microsoft Windows NT 10.0.17763.0, x64
Host Product: Microsoft Office x64
Host Version: 16.0.11425.20140
Host Executable: WINWORD.EXE

I have an inspection warning 

Object Variable assignment requires 'Set' Keyword (281) results.

Its doesn't appear to be possible to expand this item so I can't investigate what is causing the problem.  The code in question compiles without any issues.
Now I could allow Rubberduck to Fix this issue for me but........

Its also worth noting that this Warning does NOT appear in the list of items when you dump the  Code Inspection to the clipboard.

**Comment by SteveLaycock** [comment]
I tried to implement fix all occurences but this highlighted something odd.

If I refresh RubberDuck and select the 'Set' error message above I don't get any messages at the foot of the window.

If I click on another message 'Function is not used' I get the appropriate information about why the error is flagged and possible options to fix the problem

If I  then go back to the ' Set' error message , the ' Function not used' warning is not cleared (hence my thinking I could 'fix' all occurrences.

Furthermore, if I then double click the 'set' error  message I get taken to the line of code that refers to the 'Function not used' error.

**Comment by daFreeMan** [comment]
The original issue - grouped inspections - is a known and old and irritating issue, therefore a dupe, but I can't find the/an older one. 

Not sure about what you've got in the 2nd issue

**Comment by Vogel612** [comment]
Issues around aggregated inspection results are mostly quite aged by now.. I'm not even sure all of these still apply, but we currently have open the issues: #4561, #3597, #3172 and #2900. There is probably some overlap between these...
