### ISSUE TITLE
Clean Project has corrupted my project

### ISSUE THREAD

**Issue by mkrause01** [rubberduck-vba/Rubberduck#4871]
I've used the most excellent "Clean Project" feature many times with success but this time I accidentally initiated Clean Project while in break mode.  As a result my project now has twice the number of modules and classes with, for each existing module or class, another like component exists in the project with with a name of "Module1", for instance, or "Class1" where the "1" increments for each component.
At the moment it seems I'm screwed (will have lost an hours work) in that I cannot open or remove the generically named components nor can I import all project components to a new Access file.
In total, I have nearly 200 code-level components in the project between forms, modules and classes.
To me this seems to be a bug but perhaps there's something I don't know.  Can you help?

**Comment by SteveLaycock** [comment]
Methinks this should be in the MZtools forum.  Not rubberduck.

**Comment by Vogel612** [comment]
Considering that Rubberduck does not have a "Clean Project" feature, I'd say this is not in the right place...

**Comment by mkrause01** [comment]
Oooff, sorry.  I thought CP was your great would.

Thanks
