### ISSUE TITLE
nested folders in project explorer

### ISSUE THREAD

**Issue by tallguyjenks** [rubberduck-vba/Rubberduck#4878]
looked through related issues and didnt see this listed explicitly,

but the folder notation that allows us to place modules and other code files in folders in the RubberDuck project explorer is great, what about being able to have nexted folders for more granular separation of code chunks?

```
lvl1: VBAProject (Folder)
lvl2:     -Project Part 1 (Folder)
lvl3:          -code.bas
lvl3:          -code.bas
lvl2:     -Project part 2 (Folder)
lvl3:          -Project Chuck 1 (Folder)
lvl4:               -code.bas
lvl3:          -code.bas
```

**Comment by tallguyjenks** [comment]
markdown isnt working the way i want, so here's how i was trying to display that text 
![nest](https://user-images.githubusercontent.com/29872822/55210507-f0ec1180-51a4-11e9-8087-444da12c5225.PNG)

**Comment by retailcoder** [comment]
Tried `'@Folder("Parent.Child.SubChild")'? :😉

**Comment by tallguyjenks** [comment]
> 
> 
> Tried `'@Folder("Parent.Child.SubChild")'`? 😉
> 
> We really, _really_ need to find a way to make this more discoverable.

well i feel dumb now, but this made my night! yet another reason i love this project! thank you very much :)

**Comment by retailcoder** [comment]
Added to wiki: [Using @Folder annotations](https://github.com/rubberduck-vba/Rubberduck/wiki/Using-%40Folder-Annotations)

**Comment by tallguyjenks** [comment]
guess i forgot to close this issue if the onus for that was on me, i apologize, but anyhoo, closing this.

**Comment by retailcoder** [comment]
@tallguyjenks no problem - I had simply left this [support] issue opened, to make it easier to find - but yeah the wiki page makes it basically moot, I should have closed it. Thanks!
