### ISSUE TITLE
Allow Del key to remove module while focus is on CodeExplorer

### ISSUE THREAD

**Issue by IvenBach** [rubberduck-vba/Rubberduck#4879]
Syncing my Personal Macro Workbook I imported the files and it appended `1` to all of them. Using the Project Explorer to remove just feels dirty and something CE should be able to perform.

This goes hand in hand however with being able to import an entire project and have it automatically replace identical module names.

**Comment by mansellan** [comment]
:+1:, but with a dialog to confirm. Should also apply to references.
