### ISSUE TITLE
Has annotation but "Missing attribute" suggestion doesn't show

### ISSUE THREAD

**Issue by Irubataru** [rubberduck-vba/Rubberduck#4881]
**Rubberduck version information**

Version 2.4.1.4627
OS: Microsoft Windows NT 10.0.17134.0, x64
Host Product: Microsoft Office x64
Host Version: 16.0.11328.20222
Host Executable: EXCEL.EXE

**Description**
I recently asked [this]() question on SO, and got a great answer, but it doesn't seem to work for me.

**To Reproduce**
1. Create an empty project with the following class module:

```vb
'@Folder("VBAProject")
Option Explicit

Private Type MVars
    Items As Collection
End Type

Private this As MVars

'@Enumerator
'@Description("Gets an enumerator that iterates through the internal object collection.")
Public Property Get NewEnum() As IUnknown
    Set NewEnum = this.Items.[_NewEnum]
End Property

'@DefaultMember
'@Description("Gets/sets the element at the specified index.")
Public Property Get Item(ByVal index As Long) As Variant
    Set Item = this.Items(index)
End Property
```

Then run the code inspector.

**Expected behavior**
Expected to see Rubberduck opportunities telling me about missing attributes as shown in the SO answer.

**Screenshots**
![image](https://user-images.githubusercontent.com/5611071/55231124-ff2c4300-5221-11e9-82b7-39ee9f72d5e3.png)

**Comment by Irubataru** [comment]
Ah, never mind, found that "Missing Attribute" was set to "Do not show". Not sure if I set that or it was default or whatever. Sorry!

**Comment by retailcoder** [comment]
If you're a long-time Rubberduck user the DoNotShow setting might have been carried from older versions, where this feature was broken/experimental.

Note to self: verify default severity is no longer DoNotShow
 - [ ] confirmed.
