### ISSUE TITLE
Code Explorer doesn't update when Workbook.Close statement executed in Immediate Window

### ISSUE THREAD

**Issue by IvenBach** [rubberduck-vba/Rubberduck#4901]
Version 2.4.1.4627
OS: Microsoft Windows NT 6.1.7601 Service Pack 1, x64
Host Product: Microsoft Office 2013 x86
Host Version: 15.0.5111.1000
Host Executable: EXCEL.EXE

**Description**
Code Explorer doesn't update when `Workbook.Close` statement executed in Immediate Window

**To Reproduce**
1. Have a workbook, PersonalMacroWorkbook, in XLSTART folder that opens when you start excel.
2. Start Excel with new blank workbook. ![PMW Open and shown in Code Explorer](https://user-images.githubusercontent.com/26076874/55643845-01921e00-5789-11e9-9b58-9b58678b8444.png)

3. Execute `Workbooks(#).Close` in Immediate Window. Code Explorer still shows workbook as open. ![PMW Closed and still shown in Code Explorer](https://user-images.githubusercontent.com/26076874/55643852-08209580-5789-11e9-9f20-4ba7f010bb80.png)

**Expected behavior**
Code Explorer to remain in sync with Project Explorer

**Comment by IvenBach** [comment]
Closing as per design.

**Comment by retailcoder** [comment]
This is by design: parsing projects and invalidating caches while VBA code is programmatically altering what workbooks are open and what worksheets are in them, is explicitly disabled.
