### ISSUE TITLE
Refactor Menu inactive

### ISSUE THREAD

**Issue by gbalcom** [rubberduck-vba/Rubberduck#4912]
Using Access 2013.  Would love to use the Refactor tools, but they are never active.  Tried in Excel 2013, to make sure it wasn't application specific.  Please let me know if there is anything other information I can offer to help resolve this.  Just upgraded to the latest version (2.4.1) and it didn't resolve it.

**Comment by MDoerner** [comment]
Thanks for your interest in the refactorings.

Could you tell us which status is shown on the refresh button in the Rubberduck command bar? (Should be the left-most button in the buttom-most command bar in the VBE.)

Initially, this will show `Pending` (or the appropriately translated version if another language is selected in the settings). If that is still the case, you will have to click it in order for RD to gather all information about the code needed to execute things, e.g. the refactorings. If the status is already `Ready`, then there is another reason why the refactorings are deactivated.

One other thing is that the refactorings are only activated when you select a valid target. So, when the status is `Ready`, could you please select some name of a variable, procedure or function and see whether the menu item or context menu item are still disabled?

**Comment by MDoerner** [comment]
One more thing, in case the state is `Ready`: did you modify the module after parsing. In that case RD is no longer up-to-date and the refactorings are deactivated as a safe-guard.

**Comment by gbalcom** [comment]
Hello Max,
    Thank you for the prompt reply.  I did refresh RubberDuck, and now that I realize the menu is contextual, I am getting some things to work.  I do not see Extract method on it, and I can't get extract interface to work.   What do I need to highlight to get extract interface to work?  I was highlighting the Sub Name.  Or does it only work with Functions?

**Comment by retailcoder** [comment]
Side note, the wiki page on [refactorings](https://github.com/rubberduck-vba/Rubberduck/wiki/Refactorings) *could* use some more lovin'.

*Extract Interface* should be enabled in non-document modules (making a `Worksheet` implement user interfaces is a bad idea), popping a UI that lets you pick what public members to include in the new interface.

**Comment by gbalcom** [comment]
Thanks,  Mathieu.  So, is Extract Method deprecated?   I don't see it on, or a space for it on the menu.

**Comment by bclothier** [comment]
For now it's inactivated due to numerous problems/bugs with this method. There is a open project. Someone needs to get off his lazy duff and get it working again. ;-)

**Comment by MDoerner** [comment]
Regarding _Extract Method_, it is currently not activated because of several issues with the last version and has been waiting for a reimplementation for some time now.

**Comment by retailcoder** [comment]
*Extract Method* is... complicated :wink: 

We had a "working" version a long time ago (circa 2015), but there were too many unhandled edge cases, and the implementation was so problematic that addressing them was impossible. A passing contributor later proposed a rewrite, but that new implementation dismissed the preview UI and stripped so much of the functionality that it was taken down, pending a full rewrite... which is still pending to this date. The research on the subject is being linked to in the wiki.

This refactoring is **the** single most powerful refactoring tool an add-in like Rubberduck could possibly offer - and it has to work *perfectly*, or at least be written in such a way that allows extending it in that direction.

**Comment by retailcoder** [comment]
FYI I've just now added a bit of meat on the refactorings wiki: https://github.com/rubberduck-vba/Rubberduck/wiki/Refactorings

**Comment by gbalcom** [comment]
"his refactoring is the single most powerful refactoring tool an add-in like Rubberduck could possibly offer - and it has to work perfectly, or at least be written in such a way that allows extending it in that direction."  100% Agree

**Comment by bclothier** [comment]
Closing this as the support seems to be addressed for now. Any new issues or need for further clarification can be opened as a new issue.

**Comment by gbalcom** [comment]
Is an extract method rewrite in the works?  In the queue?  I'd love to help on this where possible, but I use VBA in MS Access, so VBA is my primary language...Unfortunately, I don't know squat about C#.

**Comment by bclothier** [comment]
It is in queue, for some value of word "in". 😉 I'm [the clown responsible for this](https://github.com/rubberduck-vba/Rubberduck/projects/2) but to be honest, I've been distracted by other shiny things. If nobody gets to it, I hope to start working on this in next few months. We welcome any contributors who want to take on the challenge. 😄
