### ISSUE TITLE
Code Inspection does not recognize Public Constants outside the module where the Public Constants are declared

### ISSUE THREAD

**Issue by David-J-Lambert** [rubberduck-vba/Rubberduck#4917]
**Rubberduck version information**
The info below can be copy-paste-completed from the first lines of Rubberduck's log or the About box:

    Rubberduck version 2.4.1.4627
    Operating System: Microsoft Windows NT 10.0.17763.0, x64
    Host Product: Microsoft Office x64
    Host Version: 16.0.11425.20204
    Host Executable: EXCEL.EXE

**Description**
Code Inspection does not recognize Public Constants outside the module where the Public Constants are declared, showing up in "Code Quality Issues" as:
1:  "Variable '<constant name>' is used but not assigned" in other modules.
2:  "Local variable '<constant name>' is not declared" in other modules.
3:  "Variable '<project name>.<module name>.<constant name>' hides constant '<project name>.<declared module name>.<constant name>'", where <declared module name> is the name of the module where the public constant is declared.

**To Reproduce**
1. At the top of Module A, put, for example, "Public Const constName As Integer = 0".
2. In other modules, assign constName to a variable.
3. Do a Code Inspection.

**Expected behavior**
Expect no identified issues.

**Screenshots**
Not Applicable

**Logfile**
Attached.
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/3076735/RubberduckLog.txt)

**Additional context**

**Comment by MDoerner** [comment]
Could you please help us and be a bit more specific about the issue at hand, in particular the code of the other module?

I tried to reproduce, and could not find any unjustified inspection results.

In my attempt to reproduce, I used the following code.
`Module 4`:
```vba
Option Explicit

Public Const constName As Integer = 0
``` 

`Module5`:
```vba
Option Explicit


Private Sub Foo()
    Dim variableName As Integer
    variableName = constName
    Debug.Print variableName
End Sub
```
This yielded the following inspection results:
![screenshot_20190413_231706](https://user-images.githubusercontent.com/22868956/56085470-226f0900-5e44-11e9-86ed-3843ed0f4462.jpg)

Then I changed the consumer code to the following:

`Module5`:
```vba
Private Sub Foo()
    Dim constName As Integer
    constName = constName
End Sub
```
This yielded the following inspection results:
![screenshot_20190413_232029](https://user-images.githubusercontent.com/22868956/56085492-7b3ea180-5e44-11e9-97e8-7470fcebbad4.jpg)

Finally, I changed the consumer code to the following:

`Module5`:
```vba
Private Sub Foo()
    someName = constName
End Sub
```
This yielded the following inspection results:
![screenshot_20190413_232610](https://user-images.githubusercontent.com/22868956/56085499-9f01e780-5e44-11e9-8c5b-b5955d670313.jpg)

All of the above inspection results seem to be correct and unrelated to the constant.

Could you please help us by detailing a bit more where specifically the usage of a constant causes inspection results that are not present without using a constant?

**Comment by David-J-Lambert** [comment]
Hi Max,

 

Wow, that was quick.  I’ll have to get back to you in a few days.

 

David Lambert

408-768-0924

**Comment by David-J-Lambert** [comment]
Hi Max,

The Code Inspector suddenly stopped complaining about the public constants.  I restarted Excel, VBE, and RubberDuck, and everything looks good.  I do not understand what happened, but I apologize for wasting your time.  I'm closing the bug report.

**Comment by Vogel612** [comment]
Better to report a bug a bit quicker than not reporting something reproducible :) No worries.
