### ISSUE TITLE
False *NEGATIVE* "Can be passed ByVal" inspection

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#4921]
**Rubberduck version information**
Version 2.4.1.4661
OS: Microsoft Windows NT 10.0.15063.0, x64
Host Product: Microsoft Office 2016 x64
Host Version: 16.0.4822.1000
Host Executable: EXCEL.EXE

**Description**
This code raised an `Implicitly passed ByRef` inspection, but did _NOT_ raise a `Can be passed ByVal` inspection. I applyed the `Implicit ByRef` QuickFix in the hopes that would cause it to trigger, but it did not trigger then, either.

```VBA
Private Function ToFileExtension(vbeComponentType As vbext_ComponentType) As String
  Select Case vbeComponentType
    Case vbext_ComponentType.vbext_ct_ClassModule
      ToFileExtension = ".cls"
    Case vbext_ComponentType.vbext_ct_StdModule
      ToFileExtension = ".bas"
    Case vbext_ComponentType.vbext_ct_MSForm
      ToFileExtension = ".frm"
    Case vbext_ComponentType.vbext_ct_ActiveXDesigner
    Case vbext_ComponentType.vbext_ct_Document
    Case Else
      ToFileExtension = vbNullString
  End Select
 
End Function
```

**To Reproduce**
1. see above

**Expected behavior**
This _should_ raise a `Can be passed ByVal` inspection either with or without the explicit `ByRef` on the parameter.

**Screenshots**
n/a

**Logfile**
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/3080042/RubberduckLog.txt)

**Additional context**
Yes, the inspection _is_ enabled. I was letting RD clean up several other `Can be passed ByVal` inspections when I noticed this one.

**Comment by daFreeMan** [comment]
I guess this is also a **false positive** on the `Implicitly ByRef` inspection, too. It should _not_ be passed `ByRef` since the parameter is never being changed.

Maybe looking at it from that angle might help.

**Comment by MDoerner** [comment]
It is definely not a false positive for the `ImplicitByRefInspection`. After all, it is passed implicitly by reference.

Whether the applicable quickfix is appropriate in this situation is another question.
