### ISSUE TITLE
Unexpected behavior - ToDo Explorer

### ISSUE THREAD

**Issue by SmileyFtW** [rubberduck-vba/Rubberduck#4931]
**Rubberduck version information**
  Version 2.4.1.4673
OS: Microsoft Windows NT 10.0.17134.0, x64
Host Product: Microsoft Office x86
Host Version: 16.0.11425.20228
Host Executable: EXCEL.EXE

**Description**
Regardless of Grouping setting, clicking on an arrow to expand (or collapse) a node expands (or collapses) the entire tree, not just a specific node.

**To Reproduce**
1. Open ToDo explorer
2. Click on an arrow to expand (or collapse) a node

**Expected behavior**
Only the selected node would expand (or collapse)

**Logfile**
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/3113405/RubberduckLog.txt)

**Additional context**
None

**Comment by retailcoder** [comment]
Fixed in #5122
