### ISSUE TITLE
Import/Replace Module

### ISSUE THREAD

**Issue by CHR-IS-B** [rubberduck-vba/Rubberduck#4944]
**Justification**
I find myself often replacing one or more code modules with updated versions of those code modules.  For example, I may have a module containing functions and methods for working with Excel Tables and another for Excel Ranges.  I add to these from time to time and then update VBA projects containing older versions of those modules.

To replace the modules, I do the following:

1. Delete the code modules from the VBA project
2. Import the replacement modules

**Description**
It would be nice to have a code explorer module right-click option like "Replace Module (s)" to do that in one step.

**Additional context**
This appears to have some overlap with issue #4781 from @MDoerner but I believe it's a separate request.

**Comment by retailcoder** [comment]
This shows just how much we need that feature... It *is* a duplicate though - linked issue indeed intends to address exactly this concern (albeit worded a bit differently)

**Comment by CHR-IS-B** [comment]
I should have read instead of just skimming...I suppose it is a duplicate.

**Comment by retailcoder** [comment]
No biggie - I see duplicate issues as some form of upvote on the original issue, giving it more weight in the balance of things to prioritize =)
