### ISSUE TITLE
Inspection results headers expand/collapse all groups

### ISSUE THREAD

**Issue by IvenBach** [rubberduck-vba/Rubberduck#4960]
Version 2.4.1.37597
OS: Microsoft Windows NT 10.0.17763.0, x64
Host Product: Microsoft Office x86
Host Version: 16.0.11601.20178
Host Executable: EXCEL.EXE

**Description**
Collapse and expand buttons for grouping expand all and collapse all.

**To Reproduce**
1. Have inspection results.
2. Click on a grouping header to expand/collapse that header.
3. See all headers expanded/collapsed.

**Expected behavior**
Each header will expand/collapse independently. Of course Expand/Collapse all will still work for all.

**Screenshots**
Clicking the header will expand everything, not just that grouping.
![RD Inspection results](https://user-images.githubusercontent.com/26076874/57747940-888dbc80-768c-11e9-96f0-7b0036bad4d5.png)

**Comment by MDoerner** [comment]
This is an exact duplicate of #4849.
Moreover, related to #4931.
