### ISSUE TITLE
VersionCheck enhancements

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#4964]
**Justification**
The `VersionCheck` feature is currently sending an asynchronous HTTP request to http://www.rubberduckvba.com/build/version/stable, which responds with the version number for the latest "green release".

With the website's recent update, that version number is now coming straight from [releases](https://github.com/rubberduck-vba/Rubberduck/releases), through the GitHub API - rather than returning the assembly version of the Rubberduck.dll assembly depoyed to the website, it's now returning a version number parsed (using a simple regex) from the latest "green release" tag name - which **must** contain the version number in the format `v0.0.0` (or `v0.0.0.0`).

The website's `BuildController` has been updated to also provide a response to http://rubberduckvba.com/build/version/prerelease, which yields a version number parsed (using a simple regex) from the latest tag against the [next] branch - the tag name **must** contain the version number in the format `v0.0.0.0` (or `v0.0.0`).

**Description**
Let's enhance the `VersionCheck` settings to offer 3 settings:

 - Check if a new pre-release build is available
 - Check if a new release build is available
 - Don't check if a new version is available at startup

For back-compat, let's treat the existing "Check if a new version is available" setting as "Check if a new release build is available". This enhanced setting would probably look best with a combobox selection (currently a simple checkbox).

**Comment by Hosch250** [comment]
Three-state radio-button would be nice too.
