### ISSUE TITLE
Module renames find collisions across projects

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#4969]
**Rubberduck version information**
Version 2.4.1.4719
OS: Microsoft Windows NT 10.0.15063.0, x64
Host Product: Microsoft Office 2016 x64
Host Version: 16.0.4834.1000
Host Executable: EXCEL.EXE

**Description**
If a module exists in Workbook1, RD will flag that name as a conflict when trying to give that name to a module in Workbook2.

**To Reproduce**
1. Open Workbook1
2. Create a module and name it "Test"
3. Open Workbook2
4. Create a module
1. Parse the projects
1. Try to rename the module in Workbook2 to "Test"
1. See the error

**Expected behavior**
Since Excel workbooks are individual scopes, naming conflicts should not be detected across projects

**Logfile**
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/3208010/RubberduckLog.txt)
_Loads o'carp in that log before the error occurred_ 

**Screenshots**
Start - All is good:
![2019-05-22 11_31_17-Microsoft Visual Basic for Applications - Book6 -  Module1 (Code)](https://user-images.githubusercontent.com/11889733/58187679-43b5e700-7c85-11e9-92da-2560335ff2fd.png)

Rename `Book5.Module1` to `Book5.Test`:
![2019-05-22 11_33_09-Microsoft Visual Basic for Applications - Book6 -  Module1 (Code)](https://user-images.githubusercontent.com/11889733/58187764-69db8700-7c85-11e9-8bf7-a24b69636945.png)

Rename `Book6.Module1` to `Book6.Test`:
![2019-05-22 11_34_18-Rubberduck - Rename](https://user-images.githubusercontent.com/11889733/58187858-9b545280-7c85-11e9-8097-6b7b57e029fd.png)

Boom! Invalid error:
![2019-05-22 11_35_08-Microsoft Visual Basic for Applications - Book6 -  Module1 (Code)](https://user-images.githubusercontent.com/11889733/58187901-b2934000-7c85-11e9-96b7-04af1840ab4c.png)

**Comment by retailcoder** [comment]
Thanks for the detailed report - the bug is somewhere in here:

https://github.com/rubberduck-vba/Rubberduck/blob/7e4ddd2de90e6e34754575ff7999607dc418af89/Rubberduck.Parsing/VBA/DeclarationCaching/DeclarationFinder.cs#L1235-L1289
