### ISSUE TITLE
Test explorer window does not show up

### ISSUE THREAD

**Issue by bjrnfrdnnd** [rubberduck-vba/Rubberduck#4971]
**Rubberduck version information**
The info below can be copy-paste-completed from the first lines of Rubberduck's log or the About box:

    Rubberduck version [...]
    Operating System: [...]
    Host Product: [...]
    Host Version: [...]
    Host Executable: [...]

**Description**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logfile**
Rubberduck generates extensive logging in TRACE-Level. If no log was created at `%APPDATA%\Rubberduck\Logs`, check your settings. Include this log for bug reports about the behavior of Rubberduck.

**Additional context**

**Comment by Vogel612** [comment]
The template is intended to guide you when giving a bugreport. Please edit this issue to include what the template prompts for and then reopen it.

As it stands this is not really helping us make Rubberduck better :/

**Comment by retailcoder** [comment]
Confirming no repro with [v2.4.1.4723](https://github.com/rubberduck-vba/Rubberduck/releases/tag/Prerelease-v2.4.1.4723). If this was a problem in an earlier [pre-?]release, it has since been fixed already.
