### ISSUE TITLE
Tabbed UI for Explorer Panes

### ISSUE THREAD

**Issue by bryceschober** [rubberduck-vba/Rubberduck#4972]
I saw the issue #4892 for a more generally tabbed UI, but I would like just the ability to put all of the RubberDuck explorers into a single tabbed pane.

**Comment by retailcoder** [comment]
Yup, that's the plan! :+1:

**Comment by bclothier** [comment]
Closing this since #4892 should take care of this issue -- I realize it's a slight different request but as alluded, this'll have to be implemented piecemeal anyway even for #4892, so...
