### ISSUE TITLE
Test Explorer window does not show up

### ISSUE THREAD

**Issue by bjrnfrdnnd** [rubberduck-vba/Rubberduck#4973]
**Rubberduck version information**
Version 2.4.1.4723
OS: Microsoft Windows NT 6.1.7601 Service Pack 1, x64
Host Product: Microsoft Office 2010 x86
Host Version: 14.0.7229.5000
Host Executable: EXCEL.EXE

**Description**
The test explorer window does not show up

**To Reproduce**
1. Install rubberduck
2. Create a new .xlsm file
3. Click "Rubberduck" -> "Refresh"
4. Click "Rubberduck" -> "Unit Tests" -> "Test Explorer"
5. Nothing happens. The Test Explorer does not show up.

**Expected behavior**
The Test Explorer should show up

**Screenshots**
No Screenshots as the Test Explorer should show up but it does not.

**Logfile**
Is attached

**Additional context**
Note that other windows do show up: e.g. the "ToDo Explorer" Under "Rubberduck" -> "Tools" -> "ToDo Items".
Note that testing functionality exists: one can write and execute tests. Just the window does not show up.
Note that this also happens with Rubberduck stable release, version 2.4.1.4627.
I reported this issue in issue #4971 . For some reason, there was no info in that issue. I hope this issue submission works with the complete information.

[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/3214052/RubberduckLog.txt)

**Comment by retailcoder** [comment]
Thanks for the [more detailed] report!

I see the click in the log:

    2019-05-23 22:30:40.3114;DEBUG-2.4.1.4723;Rubberduck.UI.Command.MenuItems.ParentMenus.ParentMenuItemBase;(65172112) Executing click handler for menu item '&Test Explorer', hash code 47799905;
    2019-05-23 22:30:40.3114;TRACE-2.4.1.4723;Rubberduck.UI._DockableWindowHost;IOleObject::DoVerb() called with iVerb OLEIVERB_SHOW.;

...followed by a ~6 seconds pause, and then the shutdown sequence is initiated, and no exceptions are thrown anywhere. From the logs, it looks like the toolwindow *is* being shown.

Are you on a multiple-monitor setup? It's possible that the toolwindow pops up on the secondary monitor.

Also lately in Excel 2016 at work some toolwindows (namely, the VBE's *Immediate* pane) *do* show up, but docked at the bottom and very very thinly visible. Resizing it, then undocking it (fully releasing it) and re-docking it *should* fix it.

**Comment by bjrnfrdnnd** [comment]
Thanks for your help!

I actually found the window! It was showing up, but at the very edge of my
second monitor, such that only its leftmost boundary was visible. I missed
that before. I now dragged the window to a different place and everything
seems to be ok.
The issue can be closed.

Regards,
Bjoern

**Comment by retailcoder** [comment]
Awesome! Don't hesitate to open new issues for anything that comes to mind, support question, feature request, bug report, or anything else!
