### ISSUE TITLE
Interface casting should be statically checked

### ISSUE THREAD

**Issue by bclothier** [rubberduck-vba/Rubberduck#4981]
**What**

Given the following code:
```vb
Dim x As Something
Dim y As IOtherThing

Set x = New Something
Set y = x 'Uh oh, SomeThing doesn't implement IOtherThing
```

It will compile but blow up with a runtime error. In this context, the `Something` is a VBA class, and there is absolutely no reason why we can't statically infer whether the cast is valid or not, since a class would have to have a `Implements IOtherThing` in its definition.

**Why**

As codebase grows and number of interfaces increase, the loose checking by VBA compiler becomes intolerant and we really really do not want runtime errors. Rubberduck should be smarter than VBA compiler and yell at us that we did something boneheaded so that we can addressed.

**Example**
This code should trigger the inspection:

`IOtherThing` Interface
```vb
Public Sub DoOtherThing()
End Sub
```

`SomeThing` class module
```vb
'Not implementing IOtherThing because it's... not "other" but "some...

Public Sub DoSomething()
End Sub
```

Test code:
```vb
Public Sub DoIt()
  Dim s As SomeThing
  Dim i As IOtherThing

  Set s = New SomeThing
  Set i = s 'runtime error
End Sub
```

---

**QuickFixes**

Not sure a Quickfix can be suggested other than removing the invalid cast (which may cause other problems). I would be fine with having no quickfixes, since this is usually something the programmer needs to correct. We could also consider having a quickfix to slap on the missing interface, though I would rather do this manually.

1. **Add missing interface**

    Example code, after quickfix is applied:

    `Something` Class
    ```vb
    Implements IOtherThing

    Public Sub DoSomething()
    End Sub

    Private Sub IOtherThing_DoOtherThing()
    End Sub
    ```

---

**Resources**
Each inspection needs a number of resource strings - please provide a suggestion here:

 - **InspectionNames**: `VBA Class does not implement the interface`
 - **InspectionInfo**: `The statement attempts to cast a VBA class to a VBA interface but the VBA class does not contain the necessary 'Implements'` statement implementing this interface. Thus, this will fail with a runtime error. VBA compiler will not check the validity of the cast.
 - **InspectionResults**: `Cannot cast {0} into {1}`; `{0}` = class name, `{1}` = interface name

**Comment by MDoerner** [comment]
I am very much in favor of this inspection as this has bitten me so many times already.

The implementation should not be too hard as long as we restrict the inspection to the assignment of variables only. 

A future follow up could be to extend it to the handling of arbitrary expressions on the RHS. However, that will require to implement expression type evaluation.

Just one subtle point. This inspection will also flag a case that does not cause a runtime error: assigning a variable that is declared as an interface where the underlying value also implements the new interface. Actually, it will flag every downcast, as well.
```vba
Dim interface As Interface1
Dim class As Class1
Set interface = New Class1
Set class = interface
```
Avoiding this will require expression type evaluation.

**Comment by MDoerner** [comment]
Thinking about it a bit more, excluding downcast from the results just requires checking the class inheritance the other way around.
