### ISSUE TITLE
Using Assert.SequenceEquals - how?

### ISSUE THREAD

**Issue by SmileyFtW** [rubberduck-vba/Rubberduck#4982]
I am creating a class to take a collection of things and turn that collection into an array that mirrors the collection. The ultimate intent is to have a collection, transform it into an array that can then be dropped onto an Excel sheet, sort it, get the sorted array back and then convert that sorted array into a sorted collection.

So, step 1: write a test to compare a prepopulated array (`ExpectedResult`) to a return array (`result`) from the class that derives the result from an initial collection - the prepopulated array and the collection are in the set up of the test.

the end of the test:

```vba
Assert.SequenceEquals ExpectedResult, result, "Array Conversion Failed"
```

The error I get when running the test in Test Explorer:

> "[expected] is a value type and [actual] is a reference type"

the `ExpectedResult` is declared as `Variant` as is the function in the class that is to return the result. 
At the moment there is nothing in the function - so it is expected to fail at this point until I actually write something to do  the work.

**Comment by retailcoder** [comment]
If the function is declared to return a `Variant` but doesn't *actually* return anything, what `Assert.SequenceEquals` receives is a `Variant/Empty`... which isn't an array, hence the error message: `Assert.SequenceEquals` expects arrays, and throws an error when it's not getting them - that is by design, and expected behavior.

> *so it is expected to fail at this point until I actually write something to do the work.*

Not sure I understand what the problem is then - isn't the test failing?

**Comment by retailcoder** [comment]
Maybe we need to handle `Variant/Empty` and report it as such, with a more specific `Inconclusive` message? The adjustment would have to be made here:

https://github.com/rubberduck-vba/Rubberduck/blob/bdef13f0747fcb0278978337d33354e2914d7e96/Rubberduck.Main/ComClientLibrary/UnitTesting/AssertClass.cs#L381-L417

**Comment by IvenBach** [comment]
I can see it going either way. At a more basic level I think `Inconclusive` is more appropriate because a pass/fail is conclusive. Anything else a nebulous mumble mumble at best. A descriptive message would help whoever is running the test to make the required changes, ultimately ending with a definitive pass/fail.

**Comment by Vogel612** [comment]
What @retailcoder said hits the core of the issue, though. The function does not return the expected type, not even the expected value. That's a clear test failure, making the test inconclusive for type mismatches is incorrect behaviour.

For what it's worth: `Assert.SequenceEquals(Empty, Empty)` could be argued to be supposed to pass, but currently result in an `Inconclusive` state.

**Comment by SmileyFtW** [comment]
Thanks, Mathieu. That is what I suspected - the Function itself being Variant/Empty is the issue. When I said "is expected to fail" I was meaning that the test failure would report back that they sequences are not the same, not that the Assert itself would fail with its error message. What I should have done is actually return an array that would not cause the Assert object to fail, but the test to return not equal. A small difference, and really not an issue since the function does indeed fail. <G>

**Comment by SmileyFtW** [comment]
So here is what I did:
In the Function CollectionToArray:
Dim result As Variant
Redim result (0 to 0)
CollectionToArray=result

Now the SequenceEquals test fails nicely (grin) with this Message: "Sequence Assertion failed. expected has 2 dimensions; actual has 1 dimensions [sic]. Array Conversion Failed" which is a very nice failure - it not only includes my custom message (Array Conversion Failed) but as an added bonus tells me a lot about the specific failure.

Thanks so much for your help and attention to this old "newbie".
