### ISSUE TITLE
Auto generate Model Code

### ISSUE THREAD

**Issue by SmileyFtW** [rubberduck-vba/Rubberduck#4985]
I find myself starting a model (or proxy) like this a lot:

```
Private Type TModel
   Property1 As String
   Property2 As Long
   MyCollection As Collection
   MyObject As MyObjectModel
End Type
Private this as TModel
```

Then  writing all the Get/Let procedures.
It sure would be nice to write the Type and this declarations and then hit a button to have the Get/Let procedures be automatically generated.

**Comment by Vogel612** [comment]
I wonder whether this could be co-opted in the "Encapsulate Field" refactoring we already have...

**Comment by retailcoder** [comment]
somewhat related: #4805, #875

**Comment by SmileyFtW** [comment]
I don't really know what that means (co-opted in the "Encapsulate Field") ... but then I have only begun my RD journey. If you can point me in that direction I'll happily explore it.

**Comment by retailcoder** [comment]
@Vogel612 I think it should be a separate "Unwrap Private Type" refactoring, or something like it.

**Comment by SmileyFtW** [comment]
I am having a blast using RD and applying the principles I've found on the WordPress site. Thanks for everything y'all do.

**Comment by SmileyFtW** [comment]
Since I was "wishing", I thought I would add another item to this request. When an item in the Type declaration is an Object also include the Class Init and Terminate procedures with an instantiation of the object(s) and setting them to Nothing.

**Comment by retailcoder** [comment]
@SmileyFtW caveat: can only work for classes that are creatable.

    Set this.Thing = New Object 'invalid

**Comment by SmileyFtW** [comment]
That would be fine, i would think, since doing something like that as part of the Type declaration would need special attention by the coder anyhow. But all valid declarations would still be a nice convenience.

**Comment by retailcoder** [comment]
I agree, however I'd rather avoid generating code we know is invalid in the first place :)

**Comment by aostromecki** [comment]
@SmileyFtW : I with you on this one. 

@Vogel612 & @retailcoder : (as a reference) in mzTool there is properties helper. 
[https://www.mztools.com/v8/onlinehelp/MZTools8Help.html?new_method_property_assistant.htm](https://www.mztools.com/v8/onlinehelp/MZTools8Help.html?new_method_property_assistant.htm)
We declare property name, type and private property name, pick GET/SET/LET'ers.
 It works nice for a single property per step. It produce code like this. 

```
Private _fooBar As String   '_ is default  prefix 

Public Property Get FooBar() As String
    FooBar = this.FooBar
End Property

Public Property Let FooBar(ByVal NewValue As String)
    this.FooBar = NewValue
End Property```

**Comment by djrivers** [comment]
This will be a very very helpful addition. :)

**Comment by SmileyFtW** [comment]
I am in the process of writing VBA to do this for me and my limited use cases. It'll end up being an add in. It will look for all open workbooks that have at least one list object (table) and present the workbooks as candidates (optionally Browse... to open a workbook). Selecting a candidate will list all worksheets that have tables. User will select the tables to be used. Models and Proxies will be created along with Presenters and UserForms with Apply and Cancel buttons. IData and IDialog interfaces implemented in the appropriate related modules.

**Comment by SmileyFtW** [comment]
DId it a little differently here: https://github.com/SmileyFtW/GeneratePropertyGettersSettersFromBackingFieldsInXLVBA

**Comment by BZngr** [comment]
@SmileyFtW  
> I don't really know what that means (co-opted in the "Encapsulate Field") ... but then I have only begun my RD journey. If you can point me in that direction I'll happily explore it.

Maybe you already have investigated the `EncapsulateField` refactoring, but just in case you have yet to:  

Based on your initial example, you can get what you are after if you let RD/EncapsulateField create the Private Type based on individual fields.

1. Simply start with the field declarations you are interested in:
```
Public Property1 As String
Public Property2 As Long
Public MyCollection As Collection
Public MyObject As MyObjectModel
```
2. Right-mouse-click `Property1` and use the Rubberduck context menu to navigate:  _Rubberduck => Refactoring => Encapsulate Field_

Using the EncapsulateField dialog:
1. Click _'Select All'_
2. Check the  _'Wrap Fields in Private Type'_ `checkbox` (The _Preview_ shows you what will be generated)
3. Click _'OK'_ 

The generated/refactored code:
```
Private Type TModule1
    Property1 As String
    Property2 As Long
    MyCollection As Collection
    MyObject As MyObjectModel
End Type

Private this As TModule1

Public Property Get Property1() As String
    Property1 = this.Property1
End Property

Public Property Let Property1(ByVal value As String)
    this.Property1 = value
End Property

Public Property Get Property2() As Long
    Property2 = this.Property2
End Property

Public Property Let Property2(ByVal value As Long)
    this.Property2 = value
End Property

Public Property Get MyCollection() As Collection
    Set MyCollection = this.MyCollection
End Property

Public Property Set MyCollection(ByVal value As Collection)
    Set this.MyCollection = value
End Property

Public Property Get MyObject() As MyObjectModel
    Set MyObject = this.MyObject
End Property

Public Property Set MyObject(ByVal value As MyObjectModel)
    Set this.MyObject = value
End Property

```
Use _RenameRefactoring_ to adjust any identifiers.

**Comment by SmileyFtW** [comment]
Wow.. Guess I need to look into it. I've jut gotten into the habit of starting with `Private Type` and putting in the backing fields. Does the Refactoring have the ability to start with the `Private Type`?

**Comment by BZngr** [comment]
Yes it does.

Select just the _`this`_ identifier from `Private this as TModel`.  Do not check the _'Wrap Fields in Private Type'_ checkbox (or you end up wrapping `this` in a new UDT!)

**Comment by SmileyFtW** [comment]
Now that sounds precisely like what I was after. *sigh*.... but then it was a good learning experience for me to write what I did

**Comment by SmileyFtW** [comment]
That is wonderful! RD keeps on surprising me with everything it does.

**Comment by retailcoder** [comment]
@BZngr FYI the *Encapsulate Field* refactoring is now a "highlight" on the website's home page carousel; every time the home page is served, 5 features are picked at random, and *Encapsulate Field* is representing the *Refactorings* feature.
