### ISSUE TITLE
Assignment  to userform event handler Cancel

### ISSUE THREAD

**Issue by SystemsModelling** [rubberduck-vba/Rubberduck#4993]
I may have submitted this before but can't find it in the issue search box:

Assignment to 'Cancel' implicitly assigns default member of class 'ReturnBoolean'.

```
Private Sub txtQuestion_Exit(ByVal Cancel As msforms.ReturnBoolean)
 [code]
       Cancel = True
 
End Sub
```

**Comment by Vogel612** [comment]
I'm not quite following: could you spell out what you consider the issue for contributors like me who don't write VBA every day?

**Comment by retailcoder** [comment]
That is working exactly as intended... The implicit code is `Cancel.Value = True`; `Value` being the default member of the `ReturnBoolean` class.

**Comment by SystemsModelling** [comment]
Thanks, yes, I remember now, I was told before about that class. I had been confusing it with other userform events where Cancel is defined as Integer.
