### ISSUE TITLE
"member was not found on the compile-time interface " inspection incorrect

### ISSUE THREAD

**Issue by SystemsModelling** [rubberduck-vba/Rubberduck#4995]
RD 2.4

Member 'Enabled' was not found on the compile-time interface for type 'Control'.
```
Dim ctl As MSForms.control
ctl.Enabled = gdbcCCSADB.Connected
```

Member 'Name' was not found on the compile-time interface for type 'TextBox'.
```
Dim ctl As control, oTxt As MSForms.TextBox, OptionName as string
OptionName = oTxt.Name
```

Member 'Row' was not found on the compile-time interface for type 'Range'.
```
Dim rgCategoryTable As Range
Do While rgCategoryTable.Row < ActiveSheet.Rows.Count
```

**Comment by retailcoder** [comment]
The MSForms stuff is a known issue, the MSForms interfaces are messing with us.

`Range.Row` is new though. Interestingly as far as I can tell is *does* resolve correctly, so... that would be a bug with the inspection itself.

**Comment by retailcoder** [comment]
`Enabled` is indeed not a member of `MSForms.Control`, and `Name` is indeed not a member of `MSForms.TextBox`; these are legit results, not false positives: the member calls *are* late-bound and Rubberduck is correctly warning about it.

No repro for `Range.Row` though.
