### ISSUE TITLE
Member 'XLApp' has a 'VB_VarHelpID' attribute ?

### ISSUE THREAD

**Issue by SystemsModelling** [rubberduck-vba/Rubberduck#4996]
RD 2.4
I don't know what that means.

Member 'XLApp' has a 'VB_VarHelpID' attribute with value(s) '-1', but no corresponding annotation.

`Private WithEvents XLApp As Excel.Application   ' set in UserForm_Initialize()
`

**Comment by retailcoder** [comment]
That's RD letting you know that the VBE is hiding a member attribute for `XLApp` - if you export the module you'll find a `Attribute VB_VarHepID = 1` hidden instruction.

The inspection is working as intended: it means to warn about hidden attributes that don't have a corresponding in-code `@annotation`, and offers one quick-fix to automatically add the annotation comment, and another to remove the hidden attribute.

**Comment by SmileyFtW** [comment]
I have something similar as a question and I think the answer is less about the "XLApp" variable, but more specifically about the declaration itself and I wonder if it indeed is "working as intended" in this specific instance. For me it is here:
Private WithEvents view As FooDialog
The Attribute warning I get is the same as the OP's. Seems it is that the As FooDialog (a UserForm) is much like As Excel.Application - they both likely have the attribute and the variable inherits (if that is the right idea) it from the declaration.
So, is the proper RD resolution to add the annotation for these kinds of things? I would doubt removing the hidden attribute would be the right answer. Just learning here and don't understand the approach well enough.
Thanks!
