### ISSUE TITLE
Object variables reported for  scalar properties

### ISSUE THREAD

**Issue by SystemsModelling** [rubberduck-vba/Rubberduck#4997]
RD 2.4

Object variable 'ForeColor' is assigned without the 'Set' keyword.
`Me.lblFolderExistence.ForeColor = vbRed`
but it's Long

Object variable 'Visible' is assigned without the 'Set' keyword.
`.ChartArea.Format.Fill.Visible = False `
but it's Boolean

**Comment by retailcoder** [comment]
The type of `ForeColor` is (correctly) resolving to `OLE_COLOR`:

![image](https://user-images.githubusercontent.com/5751684/59047564-1e62d480-8852-11e9-9848-522f013f1387.png)

...a type that I can't find in the Object Browser somehow, even with hidden members shown... if RD can't find it either, then it's assuming it's dealing with an object type, which usually isn't a wrong assumption to make. Tough call.

`Fill.Visible` is actually `MsoTriState` - an enum that resolves as such, and no repro on 2.4.1.4723.

**Comment by retailcoder** [comment]
Note: the inspection is currently not evaluating the data type of the RHS expression. This is mainly what's making it so frail - however it *should* handle the simple case where the RHS expression is a `SimpleNameExpression`:

https://github.com/rubberduck-vba/Rubberduck/blob/e9f88e0c822617c2605f50ea80465ad456cb3038/Rubberduck.CodeAnalysis/Inspections/Concrete/VariableRequiresSetAssignmentEvaluator.cs#L80-L85

**Comment by daFreeMan** [comment]
Related: #4318
