### ISSUE TITLE
Settings for autosave?

### ISSUE THREAD

**Issue by Frexxxy** [rubberduck-vba/Rubberduck#4999]
Hy there,

I found the nodes in the config file::

>             <IsAutoSaveEnabled>true</IsAutoSaveEnabled>
>             <AutoSavePeriod>10</AutoSavePeriod>

But in the settings I didn't find any corresponding settings.
Can the Autosave only be activated in the config file?

greetings raohy

**Comment by Vogel612** [comment]
We may or may not have removed that feature something around ... 12 months ago? Apparently #3008 left the settings in place when removing the feature from according to #2998, soo ....

**Comment by Frexxxy** [comment]
thx for the quick answer.
