### ISSUE TITLE
GitHub integration

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#50]
A "Commit" feature will export all code files to a local repository (see #48), and a "Push" feature will send these files to a remote one, all through through command-line API calls.

A "Sync" feature will download source code from the remote repository, update the local ones, and import the modified files back into the VBA Project.

**Comment by ckuhn203** [comment]
- [ ] Clone
- [ ] Init
- [ ] Push
- [ ] Fetch
- [ ] Pull
- [ ] Commit
- [ ] Merge
- [ ] Checkout
- [ ] Undo
- [ ] Revert
- [ ] AddFile
- [ ] RemoveFile

**Comment by retailcoder** [comment]
@ckuhn203 is the above checklist up-to-date as of 1.4.3?

**Comment by ckuhn203** [comment]
It's all implemented in the code @retailcoder, but not all of it is implemented in the GUI yet.
I just updated to reflect what is and isn't done in the GUI.

**Comment by ckuhn203** [comment]
@Hosch not sure where the feature is at these days with the UI rewrite you've been working on. Is undo and revert done? If so, we can close this.

**Comment by ckuhn203** [comment]
Oops. @Hosch250 ^

**Comment by Hosch250** [comment]
@ckuhn203 That is up next.

**Comment by retailcoder** [comment]
So, all that's left is the functionality to revert a commit. Excellent work here @Hosch250 and @ckuhn203!! I'm closing this issue, for all I care the *revert* functionality can come in 2.x - the core is done, working, and tested. THOROUGHLY AWESOME!!!!

**Comment by ckuhn203** [comment]
Completely amazing. Thank you for carrying this across the finish line @Hosch250. Very cool to see issue *50* finally closed.
