### ISSUE TITLE
Add 64x regasm instructions to wiki

### ISSUE THREAD

**Issue by ckuhn203** [rubberduck-vba/Rubberduck#500]
Instructions for building/registering for 64x are missing from the wiki. 

https://github.com/retailcoder/Rubberduck/wiki/Building-&-Installation

**Comment by Hosch250** [comment]
This is the regasm command to register RD in the build events in VS: `c:\Windows\Microsoft.NET\Framework64\v4.0.30319\regasm.exe "$(TargetPath)" /codebase /tlb`

To use the command line, you probably need to replace the "$(TargetPath)" with the actual directory.

**Comment by Vogel612** [comment]
has been added to [contributing](https://github.com/rubberduck-vba/Rubberduck/wiki/Contributing)

**Comment by ckuhn203** [comment]
Thanks @Vogel612!

**Comment by Vogel612** [comment]
@ckuhn203 I never said I did it... :)
