### ISSUE TITLE
CPU usage 25% while showing "Ready"

### ISSUE THREAD

**Issue by SystemsModelling** [rubberduck-vba/Rubberduck#5000]
Not really a bug report, just an observation that might explain some delays.
This is like #1953
When RD reaches "Ready", Task Manager is still showing 25% CPU for Excel. After a minute it goes to 13% then 0% after three minutes. Memory went from 1.2MB at peak to 0.8MB. 
 So maybe I need to wait for 0% to be sure RD is stable?

 
Version 2.4.1.4729
OS: Microsoft Windows NT 10.0.17134.0, x64
Host Product: Microsoft Office x86
Host Version: 16.0.11629.20196
Host Executable: EXCEL.EXE

**Comment by retailcoder** [comment]
"ready" parser state only means that the parser has completed - that's not the end of the road though. Upon reaching that state change, several components (e.g. toolwindows) *begin* work. Inspections start running if they're configured to run automatically; toolwindows (code/todo/test explorers, code metrics, etc.) start querying, processing, and aggregating the parser state data. When inspections complete, the toolwindow refreshes, which can be another resource consumption peak.

3 minutes seems a bit long though; need to run it with a profiler to really know what's going on.

**Comment by retailcoder** [comment]
Note: toolwindows refresh on ready state *whether they're visible or not*

**Comment by bclothier** [comment]
Linking #3347 for this information. Thanks for reporting and feel free to open a new issue for new feedback!
