### ISSUE TITLE
Add ~> Existing Module

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#5008]
The "Import" functionality is currently visually rather far from the "Add Module" functionality:

![image](https://user-images.githubusercontent.com/5751684/59466227-c8b29d00-8dfa-11e9-80eb-2ff06c1be6a2.png)

Meanwhile in Visual Studio, Add -> Existing Item... is right on top of the list of available item types.

Let's leave "Export" grouped with "Remove" (they do go hand-in-hand), and move "Import" under the "Add" menu, both in the context menu and the "+" dropdown.

**Comment by mansellan** [comment]
Nice idea. Could I also suggest the label gets changed from 'Add Module' to simply 'Add'? 'Module' doesn't really fit with UserForms for example, nor with ActiveX designers (if we ever want to support them for ODE) nor with several of the VB6 component types (if we want to be a little consistent between VBA and VB6)

**Comment by Inarion** [comment]
May I suggest adding a 'Replace' functionality? Quite often I find myself wanting to replace (first delete, then re-import) a certain module, for example when rolling back changes.

**Comment by retailcoder** [comment]
@Inarion good idea! ref. #4781

**Comment by mansellan** [comment]
Currently, the Add button drop-down comes from the same resource entry as the Add context (sub) menu. If we add an entry for 'File...' there, it will show up in both places. That being so, the Import... menu item seems somewhat redundant. Did we want to keep it?

**Comment by retailcoder** [comment]
Indeed this makes the "Import..." menu item <s>somewhat</s> *completely* redundant, the "Existing Item..." menu item means to replace it, leaving "Export" close to "Remove", and effectively moving "Import" closer to the "Add" commands.

**Comment by mansellan** [comment]
So, here's what the VBA context menu looks like with the changes (including shortening add/collapse):

![image](https://user-images.githubusercontent.com/25420409/60131170-a7ee2e00-9790-11e9-94ad-e7d6231a96b7.png)

**Comment by retailcoder** [comment]
@mansellan that looks great!

**Comment by daFreeMan** [comment]
I might suggest that the main menu level be `Add/Import` to retain consistency with the standard VBE Project Explorer context menu: 
![2019-06-26 07_13_48-Microsoft Visual Basic for Applications - Satisfaction Summary Master v3 34 - De](https://user-images.githubusercontent.com/11889733/60175655-27581d80-97e2-11e9-976d-2cdca7f55ddf.png)

Having reread the issue log and knowing what was going on, it still took me a few moments to find `Add | Existing file...`. 

Perhaps at least consider changing `Existing file...` to `Existing module...` to retain consistency with the wording `module` since that's used on almost every other line of the sub-menu.

**Comment by mansellan** [comment]
Hmm, not sure... I definitely think Add/Import is too noisy. As for the Existing {?}, here's how it looks in VB6:

![image](https://user-images.githubusercontent.com/25420409/60260616-e2abaf80-98d1-11e9-8daa-d4993acf54b7.png)

I think *module* would be counter-productive there. Torn between *file* and *item* though...

**Comment by mansellan** [comment]
Incidentally, *Import* was never available to VB6, the word *Import* didn't really fit, so the functionality was missed. Now that it's *Add*, I'm adding it.

**Comment by mansellan** [comment]
I do wonder though if *Add*, *Export* and *Remove* should be in one group, separately from *Add* and *Indent*?

**Comment by mansellan** [comment]
OK, so I've tried the following:

- Grouping Add\Export\Remove
- Putting Expand All above Collapse all (seems more natural)

The question then is - where should the group go? Below Find/Indent or above it. Both options shown below:

![image](https://user-images.githubusercontent.com/25420409/60585621-09615e80-9d88-11e9-9dfe-8175ab684d5a.png)

Thoughts?

**Comment by bclothier** [comment]
For the question, I think the above makes more sense.

I would also think that I think it makes more sense & discoverable to have the `Existing file...` as a first menu option, with the new stuff following.
