### ISSUE TITLE
RD Won't start - freezes Excel

### ISSUE THREAD

**Issue by SmileyFtW** [rubberduck-vba/Rubberduck#5018]
I had previously had things set up to not load RD and MZTools on startup to control load times on large, disorganized projects. Today I went in and changed both to load at startup. Then I realized they weren't loaded so went in and clicked "Loaded". Now Excel won't open the VBIDE; says waiting on another application to complete an OLE action.
I then downloaded the latest pre-release (2,4,1,4742) thinking a clean install would fix things. It hasn't.

**Comment by daFreeMan** [comment]
Post your RD log: `%appdata%\roaming\rubberduck\logs`

**Comment by SmileyFtW** [comment]
2019-06-25 12:34:08.6656;INFO-;Rubberduck._Extension;Rubberduck is shutting down.;
2019-06-25 12:34:08.7346;INFO-;Rubberduck._Extension;No exceptions were thrown.;

**Comment by SmileyFtW** [comment]
I did a shutdown/restart and it seems to have resolved the issue. I'm guessing Office and/or Windows just got confused.
