### ISSUE TITLE
Renaming Module / Class 

### ISSUE THREAD

**Issue by Lurgadhan** [rubberduck-vba/Rubberduck#5030]
**Rubberduck version information**
The info below can be copy-paste-completed from the first lines of Rubberduck's log or the About box:

Version 2.4.1.4742
OS: Microsoft Windows NT 10.0.18362.0, x64
Host Product: Microsoft Office 2013 x86
Host Version: 15.0.5115.1000
Host Executable: MSACCESS.EXE

**Description**
When I try to rename a Module or Class using the rubberduck.rename function access hangs / stops working and I've to kill the process. Though, the rename has worked.
Sometimes Access is not freezed and I can click on refresh, but any following click in Access causes Access to work and gets freezed.

**To Reproduce**
1. Go to Project Explorer
2. Right Click on a Module / Class
3. Select Rubberduck/Rename and change name and klick ok
4. After Progress Animation Access hangs

**Expected behavior**
Success Message of renaming, eventually with details like how many references have been adapted

**Screenshots**
no screenshot

**Logfile**
No log created

**Additional context**
No additional Context

**Comment by retailcoder** [comment]
Rubberduck doesn't pop a success message, although that's a possible enhancement - it does kick off a reparse of the affected modules though. Is it possible to attach a log file? The spinning duckies are running on the UI thread, as is every COM member call (i.e. the actual renaming and writing of the affected modules) - it's possible the duckies freeze for a bit, but hanging the host process isn't expected indeed. Presumably the logs contain information about any error that might have occurred.

**Comment by Lurgadhan** [comment]
Unfortunately there is no log.
I'll do some more tests and try to get a log or maybe some other usfull hints.
Its a fresh installation on a VM. I'll also try on  the host directly

**Comment by Lurgadhan** [comment]
I just started with the AddOn and I very appreciate the Project and your Work. Great Job! Thank you 👍😊

**Comment by Lurgadhan** [comment]
hi
I downloaded the current Version.
Now Access is not hanging anymore and the Renaming is working!

Version 2.4.1.4782
OS: Microsoft Windows NT 10.0.17134.0, x64
Host Product: Microsoft Office x64
Host Version: 16.0.11727.20230
Host Executable: MSACCESS.EXE
