### ISSUE TITLE
Bulk Module Exporter/Importer for Source Code Management

### ISSUE THREAD

**Issue by Skoddiethecat** [rubberduck-vba/Rubberduck#5032]
**Justification**
Managing source code for VBA Projects is currently inelegant. Committing binaries to Git repositories prevents the use of diff tools, and manually exporting/importing modules is tedious and time consuming.

**Description**
* **Export**
The feature should allow the user to Export all modules in a specific VBA project to a specified folder on a per project basis. This will allow exporting directly into a Git repository. Additionally, the Exporter should be able to delete any files no longer used in the project, and create folders to match the Rubberduck folder hierarchy used in the project.

* **Import**
This feature should allow the user to import a specified folder into the VBA project, overwriting and deleting modules as needed.

**Additional context**
I am currently using the following code to export my modules into my repository: https://gist.github.com/Skoddiethecat/d07fa6448bd3d34f3743c179a957a62c

The downside is that this script currently doesn't organize the modules into their Rubberduck folders, but just dumps them into the same top-level folder.

There is overlap with issue #4781 however this only covers importing, whereas exporting is my primary focus.

**Comment by retailcoder** [comment]
You'll be happy to know that bulk-export is already implemented, IIRC under Rubberduck/Tools/Export Active Project =)

**Comment by retailcoder** [comment]
Leveraging the folder annotations for bulk import/export is definitely in scope as well.

**Comment by Skoddiethecat** [comment]
Oh awesome! Not sure how I missed that!

Folder annotations would be a huge plus :)

Thank you!
