### ISSUE TITLE
Code Explorer 'Add' menu - disappearing items

### ISSUE THREAD

**Issue by mansellan** [rubberduck-vba/Rubberduck#5046]
**Rubberduck version information**
Version 2.4.1.37223
OS: Microsoft Windows NT 6.2.9200.0, x64
Host Product: Visual Basic x86
Host Version: 6.00.8176
Host Executable: VB6.EXE (but repro'd in VBA too)

**Description**
The items in the Add menu in the Code explorer are invisible (albeit with space reserved for them) under certain scenarios.

**To Reproduce**
1. Go to Code Explorer
2. Right-click a component node, expand the 'Add' submenu
3. Click the 'Add' toolbar button
4. Right-click a component node, expand the 'Add' submenu
5. Menu is the correct size, but with no visible entries

**Expected behavior**
Menu items should not be invisible.

**Screenshots**
![image](https://user-images.githubusercontent.com/25420409/61154507-34fdea80-a4e6-11e9-9c4b-65576cce70ba.png)

**Comment by MDoerner** [comment]
As discribed in #5238, the bug also can be triggered the other way around. If you first click the add toolbar button and then the submenu in the context menu, the menu under the toolbar button will be empty and the one in the context menu will stay filled.
Basically, it is _the last one to initialize wins_.
