### ISSUE TITLE
Excel freezes when running test during refresh

### ISSUE THREAD

**Issue by Irubataru** [rubberduck-vba/Rubberduck#5053]
**Rubberduck version information**
Version 2.4.1.4796
OS: Microsoft Windows NT 10.0.17763.0, x64
Host Product: Microsoft Office x64
Host Version: 16.0.11727.20244
Host Executable: EXCEL.EXE

**Description**
If I run any test while Rubberduck is still parsing, e.g. during "Resolving references" etc then Excel freezes for 2-3 minutes, and finally displays a "Microsoft Excel is waiting for another application to complete an OLE action". When I click OK on the error message, everything proceeds to working as expected; Rubberduck runs the tests I asked it to.

I obviously understand why it fails to some extent, however even though I am generally careful waiting for Rubberduck to finish, I still do this by mistake probably 1-3 times day, and have to tab to something else while I wait for Excel to unfreeze.

It takes a lot longer to unfreeze than the parse would take. I generally mess up at the very last second because I am impatient, and I still have to wait for a full 2-3 minutes.

**Expected behaviour**
Either of these would solve my issue

 1. (_preferred_) Rubberduck queues your request and runs it after it is done with its refresh / reparse.
 2. Rubberduck stops you from interacting with the unit test module until it is done. For example it doesn't stop showing the spinning ducklings until the refresh is fully done. Or better, any test running is greyed out, but you can still browse. Either is fine really.

**Screenshots**
![image](https://user-images.githubusercontent.com/5611071/61377889-67bc3000-a8a4-11e9-9d30-a3dbdbf4e65b.png)

**Comment by aostromecki** [comment]
I confirm similar issue.

	Rubberduck version 2.4.1.4719 loading:
	Operating System: Microsoft Windows NT 10.0.16299.0 x64
	Host Product: Microsoft Office x86
	Host Version: 16.0.11629.20246
	Host Executable: EXCEL.EXE;

**Comment by retailcoder** [comment]
> [...] all you have to do is wait for refresh to finish before running the tests. At least as a temporary solution.

https://github.com/rubberduck-vba/Rubberduck/issues/5097#issuecomment-527909064

**Comment by bclothier** [comment]
Note; with merging of PR #5258 and #5262 this may have been fixed. Please try the [the build 5169](https://github.com/rubberduck-vba/Rubberduck/releases/tag/Prerelease-v2.4.1.5169) or newer.

**Comment by Irubataru** [comment]
Testet 5169 and it is still an issue.

**Comment by Irubataru** [comment]
Although I am sure you already know I just wanted to report that it works here as well. Thanks! 😄
