### ISSUE TITLE
ModuleAttribute disappears on Excel save

### ISSUE THREAD

**Issue by Irubataru** [rubberduck-vba/Rubberduck#5054]
**Rubberduck version information**
Version 2.4.1.4796
OS: Microsoft Windows NT 10.0.17763.0, x64
Host Product: Microsoft Office x64
Host Version: 16.0.11727.20244
Host Executable: EXCEL.EXE

**Description**
It seems to me that ModuleAttribute is deleted from the module by Excel on close. This might be an Excel issue that is either an issue on my end or just how Excel behaves in general. I only have one machine to test on, so I can't really check.

If this is a bug with my Excel somehow then please close this issue as invalid.

So, let us assume that Excel behaves like this in general. Wouldn't it then be better that Rubberduck simply ignores this attribute and its corresponding annotation? If not it seems to simply clutter the code inspector with things it can't really control. Specially since the Rubberduck predeclared class comes with a ModuleAttribute equivalent to

```vb
'@ModuleAttribute VB_Ext_KEY, "Rubberduck", "Predeclared Class Module"
```

What then happens is that if I
1. Add a new predeclared class using the template
2. Run the code inspector and fix the missing annotation
3. Save and close Excel and open it again (_edited_)
4. Run the code inspector

It will complain that I have a missing attribute.

I'd say Rubberduck is doing the right thing, but due to the fact that Excel doesn't save these changes then it will just lead to confusion/frustration.

Any thoughts?

**Comment by retailcoder** [comment]
Just to confirm, step 3 does not include a "save the host document" step, correct?

**Comment by Irubataru** [comment]
Sorry, I save the Excel document after I have applied the fix before closing it.

**Comment by Irubataru** [comment]
Also, if I export the code after applying the fix before closing the document it does contain the
```vb
Attribute VB_Ext_KEY = "Namespace" ,"Namespace Class Module"
```
line, so Rubberduck is clearly doing what I expect it to.

**Comment by retailcoder** [comment]
> *It will complain that I have a missing attribute.*

And if you export the module then, it's indeed missing? If so, I can try escalating this to the Excel product team, but I wouldn't think they'd consider it a high-priority bug... if RD is complaining about a missing attribute but the attribute is present, then the bug is on us.

**Comment by Irubataru** [comment]
There is no bug with Rubberduck as far as I can see. It behaves as expected. The question is rather: "Given Excel's behaviour, what would be the most sensible Rubberduck behaviour".

Could anyone else try to reproduce this? It would be nice to know whether anyone else is seeing this behaviour.

**Comment by retailcoder** [comment]
Confirmed repro. :confused: 

That said, `MissingModuleAnnotationInspection` has the wrong `InspectionType`, it should be under `RubberduckOpportunities`.

**Comment by retailcoder** [comment]
Not sure this one should remain open, given this is likely a bug with the host.
