### ISSUE TITLE
enum

### ISSUE THREAD

**Issue by martin-east** [rubberduck-vba/Rubberduck#5063]
**Rubberduck version information**
The info below can be copy-paste-completed from the first lines of Rubberduck's log or the About box:

    Rubberduck version [...]
    Operating System: [...]
    Host Product: [...]
    Host Version: [...]
    Host Executable: [...]

**Description**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logfile**
Rubberduck generates extensive logging in TRACE-Level. If no log was created at `%APPDATA%\Rubberduck\Logs`, check your settings. Include this log for bug reports about the behavior of Rubberduck.

**Additional context**

**Comment by retailcoder** [comment]
Looks like a woopsie submission that accidentally went through - feel free to edit as needed (we'll close this issue in the meantime, feel free to reopen when it's fleshed out)
