### ISSUE TITLE
Code inspection How to find the source line that is described

### ISSUE THREAD

**Issue by BertLindeman** [rubberduck-vba/Rubberduck#5065]
Hello, 

as a RubberDuck newbie (a few hours) I wonder what I need to do to come 
from the code inspection window 
to the source line in error, or even the SUB / FUNCTION involved.

In some instances I see on the RD workbar "n references" and those help, but 
. after I fixed the problems referred there 
. pressed refresh
there still **are** many errors but no "references"
The module has over 1400 lines, maybe I should start with a smaller module?

I must be missing something ;-)

Info from about box:
- RubberDuck Version 2.4.1.4627
- OS: Microsoft Windows NT 10.0.17134.0, x64
- Host Product: Microsoft Office x86
- Host Version: 16.0.11727.20244
- Host Executable: EXCEL.EXE

Thank you,
Bert

**Comment by daFreeMan** [comment]
Welcome to the RD family. You'll soon wonder how you ever lived without it!

In the _Code Inspection_ window, double clicking on an inspection should take you directly to the offending line of code. If it's not, then there's definitely a bug that you can report.

**Comment by BertLindeman** [comment]
Wow Brett,

Impressive response time!

And a spot-on response too.

My Code inspection window was overlaying the sourcecode, So I clicked and clicked and did not see anything happening. 
Was expecting the target window would come to the front.

Thanks for the warm welcome (36 Celsius here) and the perfet answer.
Bert

**Comment by daFreeMan** [comment]
> Impressive response time!

eh... I was hanging out in chat and our bot posted your question to the chat window.

> My Code inspection window was overlaying the sourcecode, So I clicked and clicked and did not see anything happening.

Tabbed dialogues are on the ToDo/wish list, so that won't be an issue _In The Future™_

> Was expecting the target window would come to the front.

That's not an unreasonable feature request, but I'm not sure if it can be made to happen.

> 36 C

That's a bit warm!

**Comment by BertLindeman** [comment]
Great product, Brett.

I entered a new issue to the ministry of Sun And Wind to drop about 10 degrees.
The response was: we'll add a few degrees the next days ;-)
'Nuf fun.

`That's not an unreasonable feature request, but I'm not sure if it can be made to happen.` 
Now I know what to expect it's no longer a problem.

Thanks,
Bert

**Comment by retailcoder** [comment]
Thank you @BertLindeman, don't hesitate to ask *anything* about using Rubberduck!

A few tips with inspections:

 - At this point the resolver isn't "seeing" MSForms controls' default interfaces (i.e. we only see a `Control` when we're looking at a `TextBox`). This makes "procedure not used" fire false positives for most event handlers - you'll want to `@Ignore` those.
 - Same with document modules; we see the members defined by user code in e.g. `Sheet1`, but at this point the `Worksheet` members aren't picked up (ditto with `ThisWorkbook` -> `Workbook`).
 - When annotating an inspection result e.g. `'@Ignore ProcedureNotUsed`, consider adding a comment to justify, like `'@Ignore ProcedureNotUsed; macro is attached to Button1 shape in Sheet1`.
 - While it's entirely possible to do so, never blanket-apply (e.g. "fix all occurrences in project") a quick-fix that can have destructive consequences, like removing unused variables or parameters: always review each inspection result and validate it.

Rubberduck has a number of features that are awesome, but hard to discover. Everything you can do with *annotations* is documented [here](https://github.com/rubberduck-vba/Rubberduck/wiki/Using-@Folder-Annotations) and [here](https://github.com/rubberduck-vba/Rubberduck/wiki/VB_Attribute-Annotations) in the wiki (which is fully open BTW - feel free to add more content!).

**Comment by rubberduck203** [comment]
After the meeting I just walked out of, I needed this thread to brighten my day!

**Comment by BertLindeman** [comment]
> Rubberduck has a number of features that are awesome, but hard to discover. Everything you can do with _annotations_ is documented [here](https://github.com/rubberduck-vba/Rubberduck/wiki/Using-@Folder-Annotations) and [here](https://github.com/rubberduck-vba/Rubberduck/wiki/VB_Attribute-Annotations) in the wiki (which is fully open BTW - feel free to add more content!).

Thank you. Those tips are worth so much.
Will study after temperature drops a bit.

Bert.
