### ISSUE TITLE
Can Rubberduck run headless?

### ISSUE THREAD

**Issue by coverney** [rubberduck-vba/Rubberduck#5070]
I am trying to use Rubberduck to write unit tests for Excel VBA code, and I will eventually need to connect those tests to Travis CI. I was wondering if Rubberduck can run headless.

Thank you very much!

P.S. I tried emailing this question, but delivery keeps failing to contact@rubberduckvba.com.

**Comment by Vogel612** [comment]
Poke @retailcoder re email delivery failure.

So long as there is an existing office installation Rubberduck theoretically could be run headless. Note that there is no existing support for that usecase implemented here.

If my leaky memory serves, this already came up two or three years back. A look at the forks that are actively diverging from the mainline might be useful as I recall there was at least one fork that added headless capabilities.

Additionally useful might be the observation that large parts of Rubberduck can be adapted to run even without Office. Unit-Testing is **not** doable without a host application, though.

**Comment by mansellan** [comment]
Somewhat related: https://github.com/rubberduck-vba/Rubberduck/issues/4099

**Comment by retailcoder** [comment]
Headless might possibly work for VB6, but for VBA it requires a headless install of the host application, which isn't a recommended or supported scenario - one single pop-up dialog (from Excel, from the VBE, or from the VBA code itself) would "freeze" the CI server forever! But assuming everything works and there aren't any popups and there's a macro in the host document that runs on open and tells Rubberduck to parse the project / discover all tests, run them, and then publish the results to some web API, ...then yes, in theory, it could work... it's a complete hack though!

I'm looking into the email issue. If GoDaddy removed email forwarding, they're leaving me with exactly 0 reasons to stick with them (hosting will be moving to Azure by the end of 2019 anyway).

**Comment by bclothier** [comment]
Closing this issue in favor of issue #4099 - thanks for the feedback and feel open a new issue for any additional feedback!
