### ISSUE TITLE
Reword settings dialog button to Safe & Close from Ok

### ISSUE THREAD

**Issue by IvenBach** [rubberduck-vba/Rubberduck#5090]
**Justification**
OK is implicitly saving the changes we make. We strive to do this with code already, lets do it with the settings window.

**Description**
Achieve this with Save & Close for the button text to make it explicit and unambiguous what will occur.

**Code location**
Update in the [RubberduckUI.resx](https://github.com/rubberduck-vba/Rubberduck/blob/next/Rubberduck.Resources/RubberduckUI.resx#L174-L176)

**Comment by GusAV** [comment]
PR created for this request
