### ISSUE TITLE
OLE dialog on running unit tests

### ISSUE THREAD

**Issue by IvenBach** [rubberduck-vba/Rubberduck#5097]
**Rubberduck version information**
Version 2.4.1.21157
OS: Microsoft Windows NT 6.1.7601 Service Pack 1, x64
Host Product: Microsoft Office 2013 x86
Host Version: 15.0.5023.1000
Host Executable: EXCEL.EXE

**Description**
A semi-frequent occurrence where a dialog, shown below, is presented before unit tests are run. This is not reproduce-able every time. ~5-10% of the time when running tests the dialog comes up. It locks up Excel for ~3-5 minutes before dialog is displayed. Once OK is clicked everything runs fine.

**To Reproduce**
1. Run unit tests
2. Repeat until dialog shows

**Expected behavior**
Not have this dialog display.

**Screenshots**
![RD OLE action dialog on unit test](https://user-images.githubusercontent.com/26076874/63459688-dc394000-c409-11e9-9a14-0f6c53b20346.png)

**Comment by Irubataru** [comment]
Is this the same as this issue? #5053 If it is then all you have to do is wait for refresh to finish before running the tests. At least as a temporary solution.
