### ISSUE TITLE
Suspicious Let assignment inspection

### ISSUE THREAD

**Issue by MDoerner** [rubberduck-vba/Rubberduck#5099]
**What**
The inspection should find let assignments that require default member accesses on both sides of the assignment.

**Why**
It is not unlikely that such an assignment is an error and the actual intention was to use a Set assignment between the objects. 

**Example**
This code should trigger the inspection:

```vb
Public Sub DoSomething()
    Dim target As Excel.Range
    Dim source As Excel.Range
    target = source
End Sub
```

---

**QuickFixes**

1. **AddSetQuickFix**

    Example code, after quickfix is applied:

    ```vb
    Public Sub DoSomething()
        Dim target As Excel.Range
        Dim source As Excel.Range
        Set target = source
    End Sub
    ```

---

**Resources**
Each inspection needs a number of resource strings - please provide a suggestion here:

 - **InspectionNames**: SuscpiciousLetAssignmentInspection
 - **InspectionInfo**: TBD
 - **InspectionResults**: TBD

**Comment by SystemsModelling** [comment]
People can do target = source when they mean target.value = source.value or such like. So a quick fix is not always SET.

**Comment by bclothier** [comment]
We can have a quickfix to change from `target = source` to `target.Value = source.Value` --- the point is that `target = source` should be shunned because it's usually ambiguous, especially so when the types aren't the same. Rubberduck should encourage users to write readable code.

**Comment by MDoerner** [comment]
Yes, we can add this combined quickfix. I say _combined_ because there will be separate ones for the implicit default member assignment on the left and one for the implicit default member access on the right as well.

This quickfix will only be available for early bound code. In case of default member accesses on variables of type `Object` we simply have no idea what to expand.

**Comment by retailcoder** [comment]
Just a quick note, if `target` and `source` are `Excel.Range` objects, the best quickfix we can offer without implementing any library-specific logic would be `target.[_Default] = source.[_Default]` ;-)
