### ISSUE TITLE
Renaming a module in one project to the same name as a module in another prompts warning

### ISSUE THREAD

**Issue by SmileyFtW** [rubberduck-vba/Rubberduck#5108]
Version 2.4.1.4704
OS: Microsoft Windows NT 10.0.17763.0, x64
Host Product: Microsoft Office x86
Host Version: 16.0.11901.20218
Host Executable: EXCEL.EXE

**Description**
A module in an add-in has the name "Foo". Adding a new module to a different project and attempting to rename gets a dialog warning that a module with that name already exists and proceeding may cause the sky to fall.

**To Reproduce**
1. With 2 projects have a standard module in 1 named "Foo" in Project A
2. In Project B create a new std module using right-click in CE
3. Once CE refreshes, click on the newly added module and in the CE lower pane click rename
4. Enter Foo
5. Click OK - get warning

**Expected behavior**
No warning should be presented for modules in different projects having the same name

**Screenshots**

**Logfile**
Cannot locate a logfile....

Rubberduck generates extensive logging in TRACE-Level. If no log was created at `%APPDATA%\Rubberduck\Logs`, check your settings. Include this log for bug reports about the behavior of Rubberduck.

**Comment by BZngr** [comment]
#5151 should resolve this issue.
