### ISSUE TITLE
Sunsetting Rubberduck.API?

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#5110]
The COM API was originally intended to expose RD's internal awesomeness to VBA code, so as to enable some kind of reflection capabilities in VBA.

Problem is, it's a fringe feature that was never advertised, never really completed, and using it tends to make the VBE unstable.

Shall we cure it or kill it?

**Comment by mansellan** [comment]
Sounds like it's in a similar spot to Source Control, except less used.

I vote we remove it for now, it can always be resurrected if need be.

**Comment by Greedquest** [comment]
Oh shoot, I'm developing something with it right now

**Comment by Greedquest** [comment]
@rubberduck203 Just toying around with inheritance, using RD to look at what methods different classes have as an alternative to using interfaces, very much a WIP.

**Comment by Vogel612** [comment]
Part of why the API is so unmaintainable is the difficulty of wiring up the parser. As it stands, for Rubberduck's internal needs we're wiring up the parser with CW. The API is *manually* wired up, though. This means that changes to how the parser works and is internally functioning need to be mirrored in the manual parser setup for the API, which is... not ideal.

We might be able to make good use of CW for the API if we can wire up the parser and only the parser to expose it. This would simultaneously decrease the maintenance burden for the API and could help making the RubberduckIoCInstaller more ... accessible to a wider range of contributors.

**Comment by retailcoder** [comment]
@Greedquest the API will officially unship when #5173 is merged into [next], however note that a branch was just created off current-[next], named [RubberduckAPI](https://github.com/rubberduck-vba/Rubberduck/tree/RubberduckAPI); this branch will remain untouched and unmaintained; as @bclothier said in chat, that project makes a great example of how to do COM interop in C# - the DLL can still be built off that branch if needed.
