### ISSUE TITLE
TODO Explorer crashes Excel

### ISSUE THREAD

**Issue by SmileyFtW** [rubberduck-vba/Rubberduck#5119]
Version 2.4.1.4895
OS: Microsoft Windows NT 10.0.18362.0, x64
Host Product: Microsoft Office x86
Host Version: 16.0.11901.20218
Host Executable: EXCEL.EXE

**Description**
Double-clicking an item in the TODO Explorer crashes Excel

**To Reproduce**
1. Open Excel file that has code
2. Open RD and the TODO Explorer (Refresh if necessary)
3. Double-click on an entry
4. See Excel crash

**Expected behavior**
Navigate to TODO line; no crashing.

**Screenshots**

**Logfile**
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/3560961/RubberduckLog.txt)

**Additional context**
NA

**Comment by retailcoder** [comment]
Repro confirmed with 2.4.1.4892

**Comment by Greedquest** [comment]
FWIW no issue in Version 2.4.1.4881 which narrows it a little
