### ISSUE TITLE
Horizontal scroll bar in the test explorer

### ISSUE THREAD

**Issue by Irubataru** [rubberduck-vba/Rubberduck#5133]
There is currently no horizontal scrollbar in the test explorer. This is somewhat inconvenient as the test explorer rows tend to be pretty wide due to all of the information when quite often what you want to see on top of which test is failing is the message which is all the way to the left.

At the moment I have it docked normally, but have to undock it if a test fails and I have to inspect the message as there is no way to scroll to the left to read it.

**Comment by Vogel612** [comment]
This is most likely applicable for other dockable toolwindows as well. We need to add horizontal scrollbars that automatically show up when the content overflows.

For testing purposes: What happens when you scroll while holding <kbd>Shift</kbd>?

**Comment by Irubataru** [comment]
It doesn't have a scrollbar when undocket either, it is simply that undocked I have it wide enough by default so that I see the information. I actually didn't realise until today that there was no scrollbar, I had simply made a habit out of undocking to see the information. So I guess it would make sense to simply have scrollbars for all windows where the content overflows regardless of whether it can dock it not.

Holder shift while scrolling doesn't change anything, it still scrolls vertically.

**Comment by Vogel612** [comment]
The only windows in Rubberduck that are not dockable are dialogs. We fully control their minimum sizes, so it should be comparatively easy to enforce a non-scrolling minimum width for them :) But in general, you're right.

**Comment by glowingrunes** [comment]
Since I did #5135 I might as well do this one as well.
