### ISSUE TITLE
Code Inspection Error for 'MemberNotOnInterfaceInspection'

### ISSUE THREAD

**Issue by SteveLaycock** [rubberduck-vba/Rubberduck#5134]
**Rubberduck version information**

Version 2.4.1.4901
OS: Microsoft Windows NT 10.0.18362.0, x64
Host Product: Microsoft Office x64
Host Version: 16.0.11929.20254
Host Executable: WINWORD.EXE

**Description**
RubberDuck produces an inspection error but the code compiles and works fine.

```
Option Explicit

Sub test()

    Debug.Print GetMyProject
    
End Sub


Public Function GetMyProject() As String

    GetMyProject = VBE.ActiveVBProject.Name

   
End Function
```
The code above prints the correct current project in the Immediate window

This code also generates an inspection result of

Member 'ActiveVBProject' was not found on the compile-time interface for type VBE

**Comment by bclothier** [comment]
I can't reproduce this in a fresh Word document project, adding code to a class module or standard module does not fire the inspection. Am I missing something extra?

**Comment by SteveLaycock** [comment]
Just to confirm.  I tried the code in a different template and got the same error.  I then saw the discussion in the RubberDuck forum about the non reproducibility.  Following that I rebooted and was unable to reproduce the inspection report myself.  So it looks like RubberDuck had got confused somehow during an long editing session.
