### ISSUE TITLE
Horizontal scroll bar in the code inspection

### ISSUE THREAD

**Issue by djrivers** [rubberduck-vba/Rubberduck#5135]
I read a request to add a horizontal scrolling bar in test explorer #5133 which would help a lot. Can this be also added in the code inspection window as well? I have mine docked at the lower area of my whole window together with the text explorer window and immediate window. I would be a great help if every time that the text in code inspection window overflows, I can just scroll horizontally instead of making the window.

Thank you RubberDuck Team! :)

![windows](https://user-images.githubusercontent.com/40927759/64257629-4ca48e80-ceeb-11e9-864e-baae7a017e0d.png)

![windows2](https://user-images.githubusercontent.com/40927759/64257758-82497780-ceeb-11e9-9125-07209024bcff.png)

**Comment by CHR-IS-B** [comment]
Can i piggyback text wrapping onto this or would that be a separate issue?  I would like to see all the text without resizing the code inspection window or scrolling.

**Comment by retailcoder** [comment]
Should the bottom panel font size be configurable then?
