### ISSUE TITLE
Clear SearchBox control by pressing ESC

### ISSUE THREAD

**Issue by IvenBach** [rubberduck-vba/Rubberduck#5137]
**Justification**
I've used search functionality in other programs and muscle memory on this gets me often.

**Description**
Press `ESC` and clear the [TextBox](https://github.com/rubberduck-vba/Rubberduck/blob/next/Rubberduck.Core/UI/Controls/SearchBox.xaml#L21) of the control.

**Comment by glowingrunes** [comment]
Hi, I'm new to Rubberduck but I'd like to work on this issue for Hacktoberfest. Just to clarify, you want it so that you can press the Esc key instead of clicking Cancel on all dialogs?

**Comment by Vogel612** [comment]
Not quite (although that would be cool as well). This is about the SearchBox control we built to unify the searching behavior in CodeExplorer, ToDoExplorer and the Inspections window. It may only be necessary to update [this file](https://github.com/rubberduck-vba/Rubberduck/blob/next/Rubberduck.Core/UI/Controls/SearchBox.xaml)

**Comment by rubberduck203** [comment]
To clarify, the desired behavior seems to be 

Given there is text in the SearchBox
When the Esc key is pressed
Then the textbox is cleared

**Comment by glowingrunes** [comment]
Oh I see. Thanks :) I'll start work on this tomorrow then.

**Comment by IvenBach** [comment]
Linking: #5067 Is the request for `Esc` to dismiss dialogs.

**Comment by glowingrunes** [comment]
Finished! Sorry that took so long. Tried to start work on this issue a few days ago, but couldn't get the solution to build in Visual Studio 2019. Works fine in Visual Studio 17 though. Anyway, this was nice to do - it's been a while since I've touched WPF!
