### ISSUE TITLE
Version check UX enhancements

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#5145]
**Justification**
The wording of the message box can be misinterpreted, leaving the user thinking they are presented with release notes for a newer version that was just installed.
Moreover, clicking "no" makes the next load prompt again, which can get annoying.

**Description**
Let's clarify the message box to:
 - include the currently-running version#
 - indicate how it can be configured to stop nagging

Let's also track the last time the prompt was displayed, and introduce a setting to adjust the minimum number of days (0-99) between (dismissed) prompts - that way user won't get prompted again for N days. 0 would need to be the default to maintain the current behavior.

**Additional context**
Suggested rewording:

> You are running Rubberduck version {current_local}.
> Good news: Rubberduck version {current_remote} is now available. 
> 
> To read what's new in that version and to download it, click here.
> 
> This dialog is showing because version checks are turned on.
> Turn off version checks in Rubberduck > Settings.

**Comment by bclothier** [comment]
Linking #2941 -- that would be an good opportunity to create the custom implementation of messagebox that Rubberduck should be using instead of lame old WinForms. We get the better UX by having action directly labeled in buttons and ability to toggle setting without having to close the dialog and open up settings.

**Comment by retailcoder** [comment]
@bclothier indeed! "don't ask me again" would automatically adjust the setting to no longer run the version check.
Also an opportunity to pull the version-check settings into their own "Upgrade" settings page.

**Comment by retailcoder** [comment]
Linking #4964
