### ISSUE TITLE
Code Inspection: Missing default member error

### ISSUE THREAD

**Issue by SteveLaycock** [rubberduck-vba/Rubberduck#5147]
**Rubberduck version information**
The info below can be copy-paste-completed from the first lines of Rubberduck's log or the About box:

Version 2.4.1.4938
OS: Microsoft Windows NT 10.0.18362.0, x64
Host Product: Microsoft Office x64
Host Version: 16.0.12026.20108
Host Executable: WINWORD.EXE

**Description**
Looks like I'm getting a flase defalut member requirement for the function call StringifyArray.  Its the line where I've allowed Ruberduck to insert the ignore annotation.

I'm also attaching the log as there seems to be an inordinate amount of warnings.

The code below lives in a Module and not a Class.

**To Reproduce**
```
Public Function StringifyArray _
( _
    ByVal ipArgArray As Variant, _
    Optional ByVal ipPutSquareBracketsAroundArrayFlag As Boolean = True, _
    Optional ByVal ipSeparatorBetweenArrayItems As String = "," _
) As String

Dim myArg                                       As Variant
Dim myReturn                                    As String
Dim myLeftSquareBracket                         As String
Dim myRightSquareBracket                        As String
Dim mySeparatorBetweenArrayItems                As String
    
    
    myLeftSquareBracket = IIf(ipPutSquareBracketsAroundArrayFlag, "[", vbNullString)
    myRightSquareBracket = IIf(ipPutSquareBracketsAroundArrayFlag, "]", vbNullString)
    myReturn = myLeftSquareBracket
    
    For Each myArg In ipArgArray
    
        mySeparatorBetweenArrayItems = IIf(myReturn = myLeftSquareBracket, vbNullString, ipSeparatorBetweenArrayItems)
    
        If IsArray(myArg) Then
        
            '@Ignore DefaultMemberRequired
            myReturn = myReturn & mySeparatorBetweenArrayItems & StringifyArray(myArg)
            
        Else
        
            myReturn = myReturn & mySeparatorBetweenArrayItems & StringifyItem(myArg)
            
        End If
        
    Next
    
    StringifyArray = myReturn & myRightSquareBracket
    
End Function
```

**Logfile**
Log file is attached.

[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/3614227/RubberduckLog.txt)
**Additional context**

**Comment by MDoerner** [comment]
Thanks for reporting this.

This is a problem with the resolver. Currently, the resolution of index expressions does not consider the case of a recursive call. Instead, it allways considers references to the function name as references to the variable holding the return value. This has to be changed.

The inspection itself reports the correct issues based on what the resolver provides.
