### ISSUE TITLE
Enable AC by default

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#5157]
Autocompletion has been around for over a year, and currently has very few issues - mostly edge cases and enhancements. It's also shipping disabled by default, which hinders its discoverability.

A quick Twitter poll that gathered a whopping 15 votes showed got 1/5 disabling the feature (out of annoyance?), 2/5 loving it, and 2/5 not knowing about the feature.

Let's enable it by default, and see how that goes.

**Comment by IpsumCapra** [comment]
Made a pull request to do this.
