### ISSUE TITLE
Drag and drop for navigation folders, please!

### ISSUE THREAD

**Issue by ricardoba13** [rubberduck-vba/Rubberduck#5159]
**Justification**
When working on a somewhat big project, having the option to drag and drop modules to move them across folders is really a necessity.

**Description**
I would love to be able to select say two modules from one folder and use the darg and drop feature within the code explorer and move things as needed.

**Additional context**
When refactoring it is almost certain that modules will make more sense to also change their context in the project's tree.

**Comment by retailcoder** [comment]
Definitely! What makes this complicated, is that folders don't really exist: they're parsed from annotation comments in modules, so what we're looking at is something like...

 - Get the `Declaration` for the selected node(s)
 - Get the annotation for the target folder
 - Use a rewriter session and an annotation rewriter to alter the `@Folder` annotation
 - Reparse

**Comment by retailcoder** [comment]
A bit involved internal API wise for a "good first issue" I guess

**Comment by SmileyFtW** [comment]
Would like to be able to drag & drop from one project to another as well... similar to what can be done in Project Explorer, only better: multiple modules instead of one at a time.

**Comment by retailcoder** [comment]
@SmileyFTW good idea! So:

 - Get the `Declaration` for the selected node
 - Get the parent project of the target node
 - Get the annotation for the target folder
 - Use a rewriter session and an annotation rewriter to alter the `@Folder` annotation
 - If not the same project:
   - Suspend automatic parsing
   - Export/delete the source module
   - Import back into target project, restore automatic parsing
- Reparse

**Comment by MDoerner** [comment]
ref #3332

**Comment by SmileyFtW** [comment]
It would be a "nice to have" to be able to decide if it is a "move" or a "copy" when taking modules to a different project. I would think that more often than not it would be a copy (like PE does), but there might be times when "move" is the desired action (i.e. delete from source after copy to target)

**Comment by retailcoder** [comment]
I think I would make Ctrl+drop be a copy, and standard drag-and-drop be a move.

**Comment by MDoerner** [comment]
I would like to pick this up, but put a restriction on what goes into the feature. I will exclude all the things added to this issue after the initial post. More precisely, the drag and drop will only affect the folder and nothing else.

If anybody feels that these should be added, please open a separate issue for things actually cpying and moving components in the VBE.
