### ISSUE TITLE
Please Provide Checksums (MD5, SHA256, etc.,) for .exe

### ISSUE THREAD

**Issue by KingRokHead** [rubberduck-vba/Rubberduck#5160]
Hey Devs,

Great work for the community. Would it be a terribly burdensome task to calculate and provide checksums for your releases?

Thank you in advance!

**Comment by Vogel612** [comment]
Considering that MD5 is so utterly broken that creating collisions for it is comparatively trivial, I would suggest using sha256 or even better sha512 hashes.
