### ISSUE TITLE
Rename the "Introduce Parameter" refactoring

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#5162]
**Justification**
The term `Introduce Parameter` has caused enough confusion that there have been at least 2 chat discussions about what it really means. The most recent started [here](https://chat.stackexchange.com/transcript/message/51896218#51896218) and carried on for a good 10 minutes or so.

**Description**
The term was borrowed from R#, so those who use it there are quite familiar with its meaning, carried over from R#, of "promote this local variable to be a parameter in the method header". Unfortunately, it's ambiguous enough that to some it may mean "Introduce a whole new variable to the procedure as a parameter". Renaming `Introduce Parameter` to `Promote to Parameter` will eliminate the confusion around it's exact purpose and will leave the name `Introduce Parameter` free for use in a potential new refactoring that will, indeed, add a whole new parameter to the function.

**Additional context**
Felt pressured into submitting the request for the team. Feels he's not being paid enough for his work and was about to demand double the salary until he realized...

**Comment by habeckmatt** [comment]
Mind if I give this refactoring a go?

**Comment by bclothier** [comment]
Absolutely! We always welcome contributions! If you have questions or want overview, feel free to ask either here or via [the chat](https://chat.stackexchange.com/rooms/14929/vba-rubberducking)
