### ISSUE TITLE
Inspections not working in Excel 2019

### ISSUE THREAD

**Issue by Keith1948** [rubberduck-vba/Rubberduck#5169]
**Rubberduck version information**

    Rubberduck version [2.4.1..4930]
    Operating System: [Win 10 Pro...]
    Host Product: [MS Office x86...]
    Host Version: [16.0.11929.20300..]
    Host Executable: [EXCEL.EXE]

**Description**
Rubberduck Code Inspections works fine on Excel 2016.
Tested on my backup which was made prior to installing MS Office Pro 2019.
Under Excel 2019, code inspections does not work.

**To Reproduce**
Loaded backup disk with Office 2016 same version of Rubberduck.
Works fine.
Loaded current drive with Office 2019 problem persists.
Also tried later version of Rubberduck - same result.

**Comment by daFreeMan** [comment]
I'm sure it would be **really** helpful if you would ensure logging is set to TRACE level (`Rubberduck | Settings | General Settings | Minimum Log Level = Trace`), recreate the problem, and post the log.

**Comment by retailcoder** [comment]
I have a license key for Office 2019, will install tonight.

**Comment by Keith1948** [comment]
Thanks for your responses.
I have created a simple spreadsheet with two buttons with macros.
One has an intentional error which.
The other also has an error in declaring a variable that goes nowhere.
On Excel 2016 both these errors and severlal suggestions appear after a Code Inspection run.
In excel 2019 no Code Inspection window appear after the run.
Same on latest version of Rubberduck.
Cheers
Keith

Here is the logfile and spreadsheet.
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/3678973/RubberduckLog.txt)

[RubberDusk Issue Excel 2019.zip](https://github.com/rubberduck-vba/Rubberduck/files/3678978/RubberDusk.Issue.Excel.2019.zip)

**Comment by Vogel612** [comment]
The log suggests that rubberduck finds 86 inspection results and needs 9 ms to render them. This looks like Excel 2019 is going to be very annoying...

**Comment by Keith1948** [comment]
Has anyone else used Rubberduck with Excel 2019 or is it only me that is having trouble?
Don't particularly want to go back to MZ Tools which works OK on Excel 2019 _(I am using trial version MZ Tools 8.0 at the moment.)_
I prefer Rubberduck but won't be going back to Office 2016.

**Comment by Keith1948** [comment]
> 
> 
> I have a license key for Office 2019, will install tonight.

Did it work OK?

**Comment by retailcoder** [comment]
I ...got delayed with other things, am currently downloading the ISO.

PS - consider hitting the green "comment" button instead of "close and comment" 🙃

**Comment by Keith1948** [comment]
Thank you Matthew.

I am new to GitHub and yet to learn the protocols etc 😊

Cheers

Keith

**Comment by retailcoder** [comment]
Version 2.4.1.xxxxx (debug build)
OS: Microsoft Windows NT 10.0.17763.0, x64
Host Product: Microsoft Office x86
Host Version: 16.0.10730.20102
Host Executable: EXCEL.EXE

Not the same build (that's the first run since the install off the ISO, presumably updates will follow), but inspections appear to work fine hosted in Excel 2019 (x86 install to match OP) - I even get the false positives!

![inspection results in an Excel 2019-hosted VBA project](https://user-images.githubusercontent.com/5751684/66181754-06ecfa00-e640-11e9-84ba-572d2f90d602.png)

**Comment by retailcoder** [comment]
Confirming inspections still work post-update:

Version 2.4.1.xxxxx (debug build)
OS: Microsoft Windows NT 10.0.17763.0, x64
Host Product: Microsoft Office x86
Host Version: 16.0.12026.20264
Host Executable: EXCEL.EXE

**Comment by Keith1948** [comment]
Hi Mathieu;

 

Thanks for the update.

What you show in that screen shot is exactly what I get on my Excel 2016.

Now I am concerned that something has changed in the setup so I will copy all the setup and config files to a neutral drive then replace those on my Excel 2019 one at a time.

Of course I will back the up first 😉

 

Cheers

Keith

**Comment by Keith1948** [comment]
All fixed.
Thank you for your help.
