### ISSUE TITLE
Rubberduck warns "Failed to apply the quick fix." even when fix was successful.

### ISSUE THREAD

**Issue by Senipah** [rubberduck-vba/Rubberduck#5171]
**Rubberduck version information**

	Rubberduck version 2.4.1.4627
	Operating System: Microsoft Windows NT 10.0.17763.0 x64
	Host Product: Microsoft Office x64
	Host Version: 16.0.11929.20300
	Host Executable: EXCEL.EXE;

**Description**

"Quick Fixes" when applied through the _Code Inspections_ window always result in a "Quick Fix Application Failure" even when the fix was seemingly applied sucessfully

**To Reproduce**
1. In a new Excel workbook add the below procedure to a new code module:

```
Sub Test()
    Dim rtn As Variant
    rtn = 123
End Sub
```

2. From the _Rubberduck_ menu select _Code Inspections_
3. Under the _Maintainability and Readability Issues_ section locate the "Consider renaming variable `rtn`." entry.
4. Right click the entry and from the context menu select _Rename variable_.
5. Enter a new name and click _OK_.
6. See error

**Expected behavior**
If all in scope uses of the relevant variable are renamed then no error warning should be presented

**Screenshots**
![Step1](https://user-images.githubusercontent.com/4821959/65979821-e2412880-e46d-11e9-81cb-1f9b48cb3b35.png)
![Step2](https://user-images.githubusercontent.com/4821959/65979827-e66d4600-e46d-11e9-8d03-f75c00954b68.PNG)

**Logfile**
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/3677433/RubberduckLog.txt)

**Comment by daFreeMan** [comment]
Build .4627 is fairly old. You may want to try the latest build available (.4945 as of this moment) because I've not experienced anything like that in my memory.

**Comment by retailcoder** [comment]
Thanks @daFreeMan!

**Comment by Senipah** [comment]
Thanks and apologies @daFreeMan & @retailcoder - upgrading to 2.4.1.4954 fixed the issue.

**Comment by daFreeMan** [comment]
No worries @Senipah! Always better to close a non-issue (or duplicate report) than not know about a valid bug at all.
