### ISSUE TITLE
Not possible to show TODO-List without creating code-database

### ISSUE THREAD

**Issue by Gener4tor** [rubberduck-vba/Rubberduck#5198]
I use the TODO-List very much.

But I have the problem with getting it. It seems to be the only way for getting the TODO-List is clicking on Pending/Refresh.

Pending/Refresh creates not only the TODO-List but also the code-database. 

So there is my problem:
As rubberduck uses excessive amounds of RAM when creating the code-database ms-access usually crashes soon after clicking "Pending/Refresh" because of "Out of memory".

As I can see it there are several solutions to my problem:

* A massive(=90%) reduction of rubberdukcs memory-consumption
* A way to only create/recreate the TODO-List

P.S.: My prefered solution whould be a switch to turn off the creation of the code-database completly. The features I use most (intender and TODO-List) dont use it anyway and there are a lot of actions which trigger the creation of the code-database automaticly and are resulting in a out-of-memory-crash of access.

**Comment by retailcoder** [comment]
If we don't parse the code, we don't know what todo markers are in it...
