### ISSUE TITLE
Toggle DefaultInstanceId attribute

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#52]
Provide a way to toggle the value of a class module's _default instance ID_, effectively toggling between "normal" and "static" class behavior.

Warn user when toggling the attribute to `False`, because such a change is a breaking change.

Somewhat related to #48 and #49, to import/export code files - although this specific feature can work off temporary files, import/export functionality should be reused here.

**Comment by retailcoder** [comment]
@ckuhn203 is the SCI code responsible for exporting/importing modules decoupled enough to be reused for this?

**Comment by Hosch250** [comment]
Yes, it is.

**Comment by ckuhn203** [comment]
Yes. Absolutely is. In fact, the export/import code is in an entirely different assembly and namespace. 

https://github.com/rubberduck-vba/Rubberduck/tree/next/Rubberduck.VBEEditor

**Comment by retailcoder** [comment]
Per linked issue, this will be implemented as an annotation:

    '@ModuleAttribute.VB_PredeclaredId(True)

Or

    '@VB_PredeclaredId(True)
