### ISSUE TITLE
Is there a way to declare Jagged arrays so they don't trigger the "Indexed unbound default member access" inspection?

### ISSUE THREAD

**Issue by Senipah** [rubberduck-vba/Rubberduck#5201]
**Rubberduck version information**
The info below can be copy-paste-completed from the first lines of Rubberduck's log or the About box:

    Version 2.4.1.5033
    OS: Microsoft Windows NT 10.0.18362.0, x64
    Host Product: Microsoft Office x86
    Host Version: 16.0.11328.20420
    Host Executable: EXCEL.EXE

**Description**

When working with arrays-of-arrays, accessing a stored value via `arr(i)(j)`
 syntax will alway trigger the "Indexed unbound default member access" (I think this inspection is new as of `5033` ?). Example:

````
 Sub UnboundDefaultMemberAccess()
    Dim Numbers() As Variant
    Dim Names() As Variant
    Dim ArrayOfArrays() As Variant
    
    Dim FirstNumber As Long
    Dim FirstName As String
    Dim BobsName As String

    Numbers = Array(1, 2, 3)
    Names = Array("Alice", "Bob", "Charlie")
    ArrayOfArrays = Array(Numbers, Names)
        
    FirstNumber = Numbers(0)
    FirstName = Names(0)
    ' This triggers the default member access inspection
    BobsName = ArrayOfArrays(1)(1)
End Sub
````

Are my options here to either unnest the array (`x = arr(i): y = x(j)`) or ignore the inspection, or is there a way for me to declare a nested array such that I can access it like `arr(i)(j)` while also satisfying the inspection?

Thanks all for the hard work & awesome add-in!

**Comment by retailcoder** [comment]
Sounds like a little oversight - basically array subscripts and function calls are grammatically identical in VBA, so the resolver needs to look at what's being indexed *and whether that's declared as an array*, and then we should be good.

Note that if a jagged array is just a `Variant`, I doubt we'll be able to prevent firing this result.

(@MDoerner feel free to contradict me)

---

Things may get hairy though, for arrays may be holding objects... which may have an indexed default member... in which case `ArrayOfArrays(1)(1)` looks just like `ArrayOfCollections(1)(1)`, with little hope to tell them apart.

**Comment by MDoerner** [comment]
Sorry, this is actually a resolver bug. I overlooked the possibility that a double index access can be an array access both times, if the element type is `Variant`.

I will change the resolver to not consider index accesses on variables of type `Variant` to be default member accesses.

The inspection results should then vanish automatically.

**Comment by Senipah** [comment]
Thanks @MDoerner !
