### ISSUE TITLE
Show Declared Functions in Code Explorer

### ISSUE THREAD

**Issue by CHR-IS-B** [rubberduck-vba/Rubberduck#5209]
Can we show declared functions, like Windows API calls, in code explorer?

**Comment by bclothier** [comment]
We do already?
![image](https://user-images.githubusercontent.com/2367644/66679919-00104980-ec35-11e9-8f3d-12c12cead285.png)

May be that you need to parse it to see it?

**Comment by CHR-IS-B** [comment]
You're right!  Seems I was too hasty.
