### ISSUE TITLE
'@DefaultMember Annotation - Running Any Quick-Fix applies `CurrentValue.VB_UserMemId = 0`  to both Get and Let 

### ISSUE THREAD

**Issue by Senipah** [rubberduck-vba/Rubberduck#5222]
**Rubberduck version information**

Version 2.4.1.5081
OS: Microsoft Windows NT 10.0.18362.0, x64
Host Product: Microsoft Office x86
Host Version: 16.0.11328.20420
Host Executable: EXCEL.EXE

**Description**
When a class Get property is marked as the default member annotation ('@DefaultMember), applying any quick-fix results in the `CurrentValue.VB_UserMemId = 0` attribute being added to both the getter and setter. This seems to prevent any additional quick fixes from being applied.

**To Reproduce**
1. Create a new Class module in a VBA project (here named `SomeClass`)
2. Paste the below code into the `SomeClass` class (Fig.1):
```
Option Explicit
'@Folder("SomeClass")

Private InternalValue As Variant
Private strHungarian1 As String
Private strHungarian2 As String

'@DefaultMember
Public Property Get CurrentValue() As Variant
    CurrentValue = InternalValue
End Property

Public Property Let CurrentValue(ByVal Value As Variant)
    InternalValue = Value
End Property
```
3. Refresh RubberDuck and open the "Code Inspections" window
4. You should see a "Rubberduck Opportunity" entry advising that the `DefaultMember` annotation has no corresponding attribute (Fig.2).
5. Apply the quick fix to add te attribute and let Rubberduck refresh.
6. The "Rubberduck Opportunity" defaut member entry should now have disappeared. Under "Maintainability and Readability Issues" you should see "Consider Renaming ..." prompts for `strHungarian1` & `strHungarian1` (Fig.3).
7. Right-Click the entry for `strHungarian1` and Rename the variable to something which will pass inspection (Fig.4).
8. Allow Rubberduck to refresh. Once Refreshed, a new "Rubberduck Opportunity" will appear warning that a `VB_UserMemId` is present but no corresponding annotation. This is because, after applying the variable rename quick-fix (can be any quick fix), RD has applied the attribute to both the getter and setter for the `CurrentValue` prop. 

Adding the `'@DefaultMember` annotation to Let property does not remove the warning. While the warning is present no additonal quick-fixes can be used (clicking Rename on `strHungarian2`, for example, does nothing)  

**Expected behavior**
Applying an unrelated quick fix should not apply the `CurrentValue.VB_UserMemId = 0` to both the getter and setter. The attribute only needs to be present on the getter to allow default member access to both the Get and Let properties. 

In other words, this code will work:

```
Public Sub Test()
    Dim MyClass As SomeClass
    Set MyClass = New SomeClass
    MyClass = "Foo"
    Debug.Print MyClass
End Sub
```

When just the Get had the default member attribute:

```
VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "SomeClass"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit
'@Folder("SomeClass")

Private InternalValue As Variant
Private BetterName As String
Private strHungarian2 As String

'@DefaultMember
Public Property Get CurrentValue() As Variant
Attribute CurrentValue.VB_UserMemId = 0
    CurrentValue = InternalValue
End Property

Public Property Let CurrentValue(ByVal Value As Variant)
    InternalValue = Value
End Property
```

^I ^^think...

**Screenshots**
Fig.1
<img width="570" alt="1" src="https://user-images.githubusercontent.com/4821959/66758239-cd18c080-ee95-11e9-95cf-dc78b7d10bb7.PNG">
Fig.2
<img width="639" alt="2" src="https://user-images.githubusercontent.com/4821959/66758245-d013b100-ee95-11e9-9688-8e929d7e64bc.PNG">
Fig.3
<img width="689" alt="3" src="https://user-images.githubusercontent.com/4821959/66758256-d4d86500-ee95-11e9-8485-ad481bae44a2.PNG">
Fig.4
<img width="694" alt="4" src="https://user-images.githubusercontent.com/4821959/66758263-da35af80-ee95-11e9-8485-0f6d0950501c.PNG">
Fig.5
<img width="716" alt="5" src="https://user-images.githubusercontent.com/4821959/66758267-de61cd00-ee95-11e9-9a04-ede9cb1ceb80.PNG">

**Logfile**
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/3724795/RubberduckLog.txt)

**Additional context**

**Comment by MDoerner** [comment]
This is a bug in the member attributes recovery. The problem is that it matches attributes to members by name, which does not work for properties since `Get`, `Let` and `Set` have the same name.

The reason why the recovery is in place in the first place is that the VBE erases all member attributes when we copy in the new module code as part of the Quick fix.
