### ISSUE TITLE
"Refactor | Rename" ignores "Next LoopCounter" statements and leaves uncompilable code

### ISSUE THREAD

**Issue by Inarion** [rubberduck-vba/Rubberduck#5236]
**Rubberduck version information**
Version 2.4.1.5105
OS: Microsoft Windows NT 6.1.7601 Service Pack 1, x64
Host Product: Microsoft Office 2016 x86
Host Version: 16.0.4888.1000
Host Executable: WINWORD.EXE (pretty sure it's host agnostic)

**Description**
Using the "Refactor | Rename" functionality on a loop variable that is used in any `Next counter` statement will rename the variable everywhere but in those `Next` statements, effectively breaking the code. See below for a brief example.

**To Reproduce**
``` vba
Option Explicit
' start here
Public Sub BeforeRefactorRename()
    Dim I As Long
    For I = 1 To 10
        Debug.Print I
    Next I
End Sub

' Rename: I --> TooFancyForALoopCounter
Public Sub RefactorRenameLeavesBrokenCode()
    Dim TooFancyForALoopCounter As Long
    For TooFancyForALoopCounter = 1 To 10
        Debug.Print TooFancyForALoopCounter
    Next I
End Sub
```

**Expected behavior**
The refactoring should also recognize and rename the variable in the `Next counter` statement.

**Comment by MDoerner** [comment]
Thanks for opening this issue. We currently do not resolve the expression used in the closing `Next`. I will change that.
