### ISSUE TITLE
Windows 10 support IDEA?

### ISSUE THREAD

**Issue by imranbaloch** [rubberduck-vba/Rubberduck#5245]
Is rubberduck-vba is IDE alternate to VB6 IDE? If yes then whether it is Windows 10 supported? I have a tough time to install VB6 on Windows 10 and can you help me to find a way to run VB6 code on Windows 10

**Comment by bclothier** [comment]
Unfortunately, no. It is an add-in to both VB6 and VBA. Maybe this will help?

http://blog.danbrust.net/2015/09/14/installing-visual-basic-studio-6-on-windows-10/#.XbJ-3YpOmhA

**Comment by Vogel612** [comment]
Considering that the basic premise of this issue is (unfortunately) incorrect, I'm closing this issue as not applicable. Thanks!

**Comment by mansellan** [comment]
Do note however that the VB6 IDE runs just fine on Windows 10. You just need to be careful to avoid some of the installation traps. See [this article](http://blog.danbrust.net/2015/09/14/installing-visual-basic-studio-6-on-windows-10/#.XbOBTWaIrIU) for details.

VB6 executables will be supported for the life of Windows 10, according to Microsoft.
