### ISSUE TITLE
Enhance ExpandDefaultMemberQuickFix to substitute hidden default member with equivalent member

### ISSUE THREAD

**Issue by MDoerner** [rubberduck-vba/Rubberduck#5252]
**Justification**
Currently, we expand the hidden default member `[_Default]` for `Range`, which is not very helpful to the user. 

**Description**
Instead, for a clearly defined collection of combinations of default member and number of arguments, we should expand with the equivalent non-hidden member. 

**Additional context**
In case of `Range.[_Default]`, implicit calls are equivalent to `Range.Value` and indexed calls to `Range.Item`.

**Comment by bclothier** [comment]
I would like to propose that this be made configurable. I'm fairly sure that the `[_Default]` is not the only one anomalous out there, and being able to specify for different objects in different library may be desirable.

**Comment by MDoerner** [comment]
I think for a first implementation, it is sufficient to store the substitutions in a hard-coded dictionary or some similar fixed storage.

Making this configurable via a file or settings would be a possible further enhancement.

**Comment by PeterMTaylor** [comment]
Agreed with a required thought how .range can be host agnostic.
