### ISSUE TITLE
Code Inspection - Indexed default member access fix does not work correctly for default members with underscores

### ISSUE THREAD

**Issue by chrisdaniels** [rubberduck-vba/Rubberduck#5253]
Version 2.4.1.5132
OS: Microsoft Windows NT 6.1.7601 Service Pack 1, x64
Host Product: Microsoft Office 2016 x86
Host Version: 16.0.9126.2282
Host Executable: EXCEL.EXE

**Description**
Code Inspection - Indexed default member access fix does not work

Example sub prior to fixes being applied will trigger 3 Indexed default member access 

Sub test()
Columns("M:M").Select
Cells(4, 6).Value = "x"
Sheets("Sheet1").Range("A1").Value = Range("H1").Value  
End Sub

After applying the 3 fixes, all three lines will show a syntax error as it has added **._Default** :

Sub test()
Columns._Default("M:M").Select
Cells._Default(4, 6).Value = "x"
Sheets._Default("Sheet1").Range("A1").Value = Range("H1").Value
End Sub

**Expected behavior**
Not sure, but this does not work

**Logfile**
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/3792842/RubberduckLog.txt)

**Comment by MDoerner** [comment]
Thanks for reporting this.

The problem here is that we have to make sure to (generally) that we escape declarations containing invalid characters by enclosing them in brackets.

The code would work with `[_Default]` instead of `_Default`.
