### ISSUE TITLE
Shortcut warning if enabled

### ISSUE THREAD

**Issue by SonGokussj4** [rubberduck-vba/Rubberduck#5259]
**Rubberduck version information**
    
    Version 2.4.1.5143
    OS: Microsoft Windows NT 10.0.18362.0, x64
    Host Product: Microsoft Office x86
    Host Version: 16.0.12130.20272
    Host Executable: EXCEL.EXE

**Description**
General Settings - when a shortcut is not enabled within **hotkeys**, don't show a warning if the shortcut is just a Key (without modifiers)

**Expected behavior**
Show warning after I enable the shortcut/hotkey.

**Screenshots**
http://www.noirgoku.mablog.eu/screenshots/2019-11-01_231010.png

**Comment by Vogel612** [comment]
I think it's acceptable to show the inline warning symbol if the hotkey is not enabled, but I agree that the red warning text is misleading if the shortcut is disabled. Anyone implementing this will want to adjust the `ShouldDisplayHotkeyModificationLabel` property to exclude those hotkeys that are disabled.

https://github.com/rubberduck-vba/Rubberduck/blob/e86108c5565a25749aa5dcbd38111a90f321ef76/Rubberduck.Core/UI/Settings/GeneralSettingsViewModel.cs#L111-L117
