### ISSUE TITLE
Vertical scrollbar in code inspections should not include the top and bottom information

### ISSUE THREAD

**Issue by Irubataru** [rubberduck-vba/Rubberduck#5265]
**Rubberduck version information**
Version 2.4.1.5169
OS: Microsoft Windows NT 10.0.18362.0, x64
Host Product: Microsoft Office x64
Host Version: 16.0.12130.20272
Host Executable: EXCEL.EXE

**Description**
The vertical scrollbar in the code inspections window is for the entire window and therefore also pushes the explanation banner at the bottom to the end of the scroll. It also means that by scrolling down you loose the settings at the top.

**Expected behavior**
The scrollbar should only encompass the results. I see that you end up with the same issue as #4608 where you also here in certain cases would end up with two bars when the window is too small. However, I think that is still preferable to having to scroll down to the bottom to read the explanation / click fix all. It also shouldn't happen too often.

**Screenshots**
![image](https://user-images.githubusercontent.com/5611071/68289148-ecb29b80-0085-11ea-8c3a-22ff7d081942.png)
![image](https://user-images.githubusercontent.com/5611071/68289173-f5a36d00-0085-11ea-979c-e2ef425af5df.png)

**Comment by Irubataru** [comment]
Probably not a surprise, but the test explorer has the same issue.

**Comment by MDoerner** [comment]
This and issue #5302 should be easy to fix by disabling the vertical scroll for the scroll viewer around the entire control. Then, the still existing vertical scroll viewer in the data grid will be able to work again.
