### ISSUE TITLE
not able to change the 'Empty line handling' in the Settings

### ISSUE THREAD

**Issue by natural-born-tiller** [rubberduck-vba/Rubberduck#5285]
**Rubberduck version information**
The info below can be copy-paste-completed from the first lines of Rubberduck's log or the About box:

Version 2.4.1.5196
OS: Microsoft Windows NT 10.0.15063.0, x64
Host Product: Microsoft Office 2016 x86
Host Version: 16.0.4912.1000
Host Executable: EXCEL.EXE

**Description**
I´m not able to change the entry 'Empty line handling' in the Special Options menue of Indenter Settings. If I hit save&close, the value is not changed, it is still Ignore, but I want to remove.

**Comment by TroyB9** [comment]
I agree with this as of the latest prebuild as well.  However, setting the option to remove seems to apply  for a while, then under some circumstance that I cannot reproduce, the indenter acts like it is set back to 'ignore' and i have to go back into the settings and change it back to 'remove'.

**Comment by Greedquest** [comment]
Workaround is to edit the rubberduck.config manually located in the parent folder to the logs folder. Just set the `<EmptyLineHandlingMethod>Remove</EmptyLineHandlingMethod>` key appropriately
