### ISSUE TITLE
Resolver error

### ISSUE THREAD

**Issue by mv-82** [rubberduck-vba/Rubberduck#5290]
Version 2.4.1.5196
OS: Microsoft Windows NT 10.0.18362.0, x64
Host Product: Microsoft Office x64
Host Version: 16.0.12130.20344
Host Executable: EXCEL.EXE

**Description**
Rubberduck go in a "Resolver error" status.

**To Reproduce**
1. Click on 'Pending...' button
2. Wait...
3. 'Pending' button become 'Resolver error'

**Screenshots**
![Annotazione 2019-11-19 184532](https://user-images.githubusercontent.com/51159386/69171737-c9173880-0afc-11ea-9041-4857a70149e4.jpg)

**Logfile**
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/3865263/RubberduckLog.txt)

**Comment by MDoerner** [comment]
Thanks for reporting this! However, we will need a bit more information to allow us to fix it.

There is something in your module `F09_Varianti` causing us to throw an NRE in the resolution, which should not happen. The problematic part seems to be some indexed member access inside the arguments to another indexed member access in an assignment.

It would help us immensely if you could look whether you can find such a thing in the aforementioned module and provide us with some code causing the issue. (Before posting any code directly taken out of the module, please consider whether you are allowed to publish that code.)

**Comment by mv-82** [comment]
Thank you very much for the hint. I've found the problem.

I've written this line of code
`vetroInfisso = F04_Vetri.Cells(rigaInfisso, F04_Vetri.Range("Tabella_Vetri[Vetro]").Column).Value`

without the second F04_Vetri reference like this:
`vetroInfisso = F04_Vetri.Cells(rigaInfisso, .Range("Tabella_Vetri[Vetro]").Column).Value`

Now it resolve correctly but I have the same problem that I reported with bug # 4980.
Nothing is displayed if I run the code inspection.

**Comment by MDoerner** [comment]
Hm, that code should not have compiled. Did you try to compile it?

**Comment by mv-82** [comment]
You're right, he wasn't compiling.
I had not tried to do it before finding the error.

**Comment by Vogel612** [comment]
Considering that the code did not compile, we're not expecting Rubberduck to resolve it correctly. Glad we could find the issue :)
