### ISSUE TITLE
False positive `Variable '{x}' is not used'

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#5291]
**Rubberduck version information**
The info below can be copy-paste-completed from the first lines of Rubberduck's log or the About box:
```
Version 2.4.1.5196
OS: Microsoft Windows NT 10.0.17134.0, x64
Host Product: Microsoft Office 2016 x64
Host Version: 16.0.4873.1000
Host Executable: MSACCESS.EXE
```

**Description**
I received a `Variable 'this' is not used` inspection on an interface. Variables shouldn't be _used_ in interfaces.

**To Reproduce**
1. enter code:
```
'@Interface
Option Explicit

Private Type foo
  bar as string
  baz as string
End Type
Private this as foo
```
2. parse & run inspections
3. Profit!!! er... see inspection result

**Expected behavior**
No `Variable not used` inspections should appear on Interface modules

**Screenshots**
N/A

**Logfile**
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/3866043/RubberduckLog.txt)

**Additional context**

**Comment by MDoerner** [comment]
I think in the situation of the MCVE, we really should issue a result. There is no reason why to treat private variables in interfaces any different than private variables in any other components.

For public fields, the situation is a bit different. We do not report interface members with an implementation as not used, even if they are never used. However, we report public fields on interfaces with an implementation. That is inconsistent. However, I would like to propose to actually report all interface members that are not used, no matter whether they are implemented or not.
