### ISSUE TITLE
#If...Then...#Else directive not recognized

### ISSUE THREAD

**Issue by Auto72** [rubberduck-vba/Rubberduck#5294]
**Rubberduck version information**
Version 2.4.1.4627
OS: Microsoft Windows NT 6.2.9200.0, x64
Host Product: Visual Basic x86
Host Version: 6.00.9782
Host Executable: VB6.EXE

**Description**
The #If...Then...#Else directive is not recognized.

**To Reproduce**
1. Have a module with a method using inside it a #If...Then...#Else directive,

**Expected behavior**
#If...Then...#Else directive should be recognized.

**Screenshots**
N/A

**Logfile**
ERROR-2.4.1.4627;Rubberduck.Parsing.VBA.Parsing.ModuleParser;Syntax error; offending token 'If' at line 852, column 6 in the CodePaneCode version of module modMyModule.;

**Additional context**

```vb
Private Sub Main()
Dim a as Long: a= 10
Dim b as Long: b=5
Dim c as Long : c=a+b

'- CCG_VERSION1 = -1 and CCG_VERSION2 = -1 are Conditional Compilation Constants in the project propertis, under the Make tab.

#If CCG_VERSION1 Or _
     CCG_VERSION2 Then

    c=c+c
#else
    c=c*c
#end if 

Print c

End Sub
```

**Comment by retailcoder** [comment]
The problem is the line continuation. Remove it and everything parses correctly - this is a parser bug, thanks for reporting!
