### ISSUE TITLE
Toggle Default Member Attribute

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#53]
Related: #52 (same prerequesites about importing/exporting code files)

This feature allows marking a class member as its "default member"; the feature should ensure there's only ever a single member marked as such.

Warn user when changing a class' default member, as this is a breaking change.

**Comment by retailcoder** [comment]
Same here; @ckuhn203 is the SCI code responsible for exporting/importing modules decoupled enough to be reused for this?

**Comment by ckuhn203** [comment]
Yup. See #52

**Comment by retailcoder** [comment]
@ckuhn203  Awesome! I'm making a new issue to coordinate these features.

**Comment by ckuhn203** [comment]
Sounds like a plan!

**Comment by ThunderFrame** [comment]
Oh, crap.

Member attributes are *very* sensitive to member declaration changes. Refactoring/editing a member declaration line is enough to blast the attribute into a thousand pieces of nothing.

Rubberduck needs to discover and monitor member attributes, and persist them if they're obliterated by user or refactoring actions.

**Comment by retailcoder** [comment]
@ThunderFrame  that can be considered a feature that.... *fixes a VBE bug!*

**Comment by retailcoder** [comment]
Per linked issue, this will be implemented as an annotation:

    '@MemberAttribute.VB_UserMemId(0)

Or:

    '@DefaultMember

---

This specific attribute will also need an inspection, to ensure only one module member has it.
