### ISSUE TITLE
Self-closing pairs don't when replacing selected text until moving from the line

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#5303]
**Rubberduck version information**
```
Version 2.4.1.5200
OS: Microsoft Windows NT 10.0.17134.0, x64
Host Product: Microsoft Office 2016 x64
Host Version: 16.0.4912.1000
Host Executable: EXCEL.EXE
```

**Description**
When selected text is replaced by typing a `"`, SCP doesn't kick in to place the closing `"` _until the cursor moves to a different line_.  The same hold true for `(`, and, I'd imagine, any other pairs that it works on. This is _very_ confusing, as normally, typing a `"` immediately gets you the closing quote.

**To Reproduce**
1. Select some code
2. Type `"`, which replaces the selection

**Expected behavior**
The opening character of a self-closing pair should be closed immediately when it's replacing existing text, just as it does when it's _not_ replacing existing text.

**Screenshots**
Starting with this code:
```'@Folder("VBAProject")
Option Explicit
Public Sub foo()
  Dim bar As String
  bar = "baz"
  frob bar
End Sub
```
![2019-11-25 08_47_29-Microsoft Visual Basic for Applications - Book1 -  Module1 (Code)](https://user-images.githubusercontent.com/11889733/69545799-80c6a300-0f60-11ea-8e5b-d010a0474549.png)

Type a `"` (or a `(`):
![2019-11-25 08_47_46-Microsoft Visual Basic for Applications - Book1 -  Module1 (Code)](https://user-images.githubusercontent.com/11889733/69546076-06e2e980-0f61-11ea-8ae3-773e37676fbe.png)

**Logfile**
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/3886901/RubberduckLog.txt)

**Additional context**
In mucking about to create the ticket, I realized that moving off the line where I was typing _will_ close the pair. _However_, this is very unintuitive for those who have gotten used to the immediate closing that SCP normally provides. Additionally if I were to type `frob bar`, then select `bar` and type `"text<enter>` I end up with automatic line continuation, which is... good and bad...

This all may be `Status-by-design` but it is confusing, off-putting and threw me for enough of a loop that I stopped what I was working on in Access, fired up Excel and wrote up the issue before realizing that moving from the line would get the close quote.

**Comment by retailcoder** [comment]
This is by design - SCP only ever kicks in when the selection is a blinking caret (i.e. no selection). The `"` was added by the VBE.

The automatic line continuation is smart-concat kicking in because you're in the middle of a string literal when you hit <kbd>Enter</kbd>.
