### ISSUE TITLE
Stack Exchange chat access request

### ISSUE THREAD

**Issue by testingoutgith1** [rubberduck-vba/Rubberduck#5313]
Per the instructions [here](https://rubberduckvba.wordpress.com/2019/07/15/modern-vba-best-practices-default-members/#comment-2623) for the case that one does not have 20 rep on SE, which I don't as I did not have an account until very recently. Please just let me know what you need from me.

I chose Thanks! as the "issue" because it seemed like the most appropriate for such a request. Rubberduck has been a very beneficial tool for getting unstuck on a project that felt like it had an unmanageable amount of class modules and the litany of clearly written blog posts and SE/SO answers I've read by core devs like Mathieu have been essential for gaining an actual understanding of VBA, as well as OOP in general. Both are greatly, greatly, appreciated. :)

**Comment by retailcoder** [comment]
Thanks for the feedback! You can join the chat [here](https://chat.stackexchange.com/rooms/14929/vba-rubberducking).

**Comment by testingoutgith1** [comment]
"yep its me" :)

**Comment by Vogel612** [comment]
Access has been granted
