### ISSUE TITLE
Fix multiple selected inspections in one action

### ISSUE THREAD

**Issue by Irubataru** [rubberduck-vba/Rubberduck#5316]
It is possible to mark multiple inspection results by shift-clicking them, however you cannot actually do anything with the multi select. If you right click and choose one of the fix methods it will only fix the item you right clicked. This is somewhat misleading as the UI suggests that you can do something with your multi selection, like you can in the test explorer.

A fairly clear limitation is obviously that it is hard to fix multiple inspections if they are not the same type as different inspections can have different resolution options. If it would be possible to fix all inspections with the same resolution option that would be even better.

**Comment by daFreeMan** [comment]
> fix all inspections with the same resolution option that would be even better.

![2019-12-11 07_17_12-Quarterly Reports](https://user-images.githubusercontent.com/11889733/70620925-6e966700-1be6-11ea-9c82-4a761e9a346d.png)

Will any of those options do for you?

**Comment by MDoerner** [comment]
For inspection results of the same type, applying a quickfix to all selected ones should be fairly simple. 

Doing it for inspection results for different inspections allowing the same quickfix sounds doable, but requires a bit more thought regarding the compatibility check.

I think, as a first step, we should enhance the context menu to only show quickfixes applicable to all selected inspection results.

**Comment by Irubataru** [comment]
> > fix all inspections with the same resolution option that would be even better.
> 
> ![2019-12-11 07_17_12-Quarterly Reports](https://user-images.githubusercontent.com/11889733/70620925-6e966700-1be6-11ea-9c82-4a761e9a346d.png)
> 
> Will any of those options do for you?

What I am thinking about is related to the other issue I just posted (#5315) in the sense that this functionality would be necessary if the fix I want to apply is different from the default fix.

But also, although there is a fix all bar at the bottom, the fact that you can multi-select in the inspections window is misleading because you can't do anything with the selection.

**Comment by retailcoder** [comment]
Basically, extend the quickfix commands to expand into "Fix once" / "Fix in procedure" / "Fix in project" / "Fix everywhere" (as applicable)? i.e. instead of picking e.g. "Add explicit 'Public' access modifier" you'd hover "Add explicit 'Public' access modifier" and then select "Fix once" to fix only the selected result, "Fix in procedure" to fix all results *with this quickfix* in the procedure, and so on.

**Comment by daFreeMan** [comment]
I think it may make more sense to disable multi-select. 

If you want to fix multiple `Replace variant returning function with type returning function` (i.e. `Left()` -> `Left$()` -- don't remember the exact wording) you can select the appropriate `Fix all` options from the bottom (or even better from the context menu).

However, you're probably also not going to want to fix all the `Implicit default member calls` in the same shot - there are too many possibilities (at least for my little brain) to want to fix multiple different _types_ of errors all at once. 

I for one would want to look at what the default fix for each type of error was and determine if that's the fix I want to apply (I can't see a multiple-different-error-type selection doing anything _but_ apply the default quick-fix), and if I'm doing that, I may as well select a `Fix all` option while I'm looking at and thinking about it.
