### ISSUE TITLE
Was looking up source control for Access 2016 and was directed to RubberDuckvba.com/sourcecontrol

### ISSUE THREAD

**Issue by RSquared64** [rubberduck-vba/Rubberduck#5333]
There is at least 1 website pointing to RubberDuck as being able to provide Source Control for Access.

On YOUR sites of course there is no listing of being able to provide source code control.

At the very least, it would be an awesome addition to RubberDuck.

Thanks

**Comment by rubberduck203** [comment]
At one point, years ago now, there was a git interface in RD. Unfortunately, it was highly experimental and I didn’t have the time to get it working smoothly so we removed it. 

The best option at the moment is to use the export/import feature to get the code on to the file system so you can use whichever source control system you like.

**Comment by retailcoder** [comment]
The feature was sunsetted a few years ago, for lack of a maintainer - the many issues were a complete resource drain and were pulling manpower away from the main stuff.

Resurrecting the feature isn't completely out of the question, but it's not going to happen without a maintainer that's willing to own it.

That said, the source control panel was always intended to be host-agnostic, and only handle source code - there wasn't anything Access-specific (e.g. querydefs, tabledefs, etc.) about it.

As it currently stands, Rubberduck has an "export active project" feature that exports all code modules (including document modules' code-behinds, e.g. forms, reports), and v2.5 was released with "sync project" commands that can update the VBA project from code files (a blog article about using these features is under way) - but the Access-specifics will have to be dealt with using an Access-specific add-in.

**Comment by A9G-Data-Droid** [comment]
For Access we would need more than just VBA. There is a VBA project that can dump table data to text files so they can be properly controlled. I don't like the solution because it requires a bunch of extra VBA get installed in to each project you want to control. I would much prefer it as a plug-in, like RD. For that to happen this code would need to be ported from VBA to C#:

https://github.com/timabell/msaccess-vcs-integration

Or something like it written. This is project I would love to do if I had the time but I don't right now.

**Comment by bclothier** [comment]
Yep! 

Given that Rubberduck's scope is a VBIDE add-in, I think it's safe to say that Access, which AFAIK is the only host to ever have had support for source control of its documents, is best served by specialized Access add-ins such as the one linked or various commercial offerings. For that reason, I would argue that such control would be beyond Rubberduck's scope. 

If anyone happened to find out a truly host-agnostic solution to control the documents then we might be able to talk about that, but I just don't see it happening. *Hopes that he won't have to eat a pie of crows one day for having said that.*

**Comment by rubberduck203** [comment]
@retailcoder I’m going to go ahead and close this. I’m agreed that an Access specific (table/query defs, etc.) are completely out of scope and that we’d accept a PR from a champion/maintainer of a VBA source control solution, but there’s no sense in leaving this issue open. When/if such a maintainer comes along, I’m sure they’ll open a new issue. 

@RSquared64 thank you very much for the feature request and being a RD user. I’m very sorry to close this. It still breaks my heart that I failed to deliver a working source control solution for RD.
