### ISSUE TITLE
Move closer to usage adds carriage return to end of module when line continuation character is used

### ISSUE THREAD

**Issue by IvenBach** [rubberduck-vba/Rubberduck#5335]
Version 2.5.0.16568
OS: Microsoft Windows NT 10.0.18363.0, x64
Host Product: Microsoft Office x86
Host Version: 16.0.12325.20240
Host Executable: EXCEL.EXE

**Description**
As title says.

**To Reproduce**
1. Paste code into module
```
Option Explicit

Public Sub MVCE()
    Dim Foo1 As String, Foo2 As String, Foo3 As String, Foo4 As String, Foo5 As String, Foo6 As String
    
    Foo1 = "foo1" & _
            "after continuation"
    Foo2 = "foo2" & _
            "after continuation"
    Foo3 = "foo3" & _
            "after continuation"
    Foo4 = "foo4" & _
            "after continuation"
    Foo5 = "foo5" & _
            "after continuation"
    Foo6 = "foo6" & _
            "after continuation"
End Sub
```
2. Ensure no extra carriage returns are after `End Sub`.
3. Use Move Closer To Usage on one of the variables.
4. Place cursor at end of module and see that there is now extra carriage returns for every time a variable was moved.

**Expected behavior**
Not have the added carriage returns added.

**Comment by IvenBach** [comment]
This is also occurring with Rename. My hunch is that similar functionality has this behavior as well.

**Comment by Vogel612** [comment]
The observations in [this comment](https://github.com/rubberduck-vba/Rubberduck/issues/2343#issuecomment-257877974) might be closely related. Especially the following caught my attention:

> A new line will be added every time a UserForm is imported; if nothing is done to counter this, successively exporting and importing the same form module will keep shifting the code down one line, until the module exceeds 65535 lines and the project no longer compiles.
