### ISSUE TITLE
Indentation issues after a complete loop secuence in a single line is commented out.

### ISSUE THREAD

**Issue by RandaliusX** [rubberduck-vba/Rubberduck#5355]
**Rubberduck version information**
	Rubberduck version 2.4.1.5105
	Operating System: Microsoft Windows NT 10.0.18362.0 x64
	Host Product: Microsoft Office x86
	Host Version: 16.0.12026.20264
	Host Executable: EXCEL.EXE;

**Description**
- Indentation go (wrongly) to the left after a commented line with a complete FOR loop.

**To Reproduce**
- _Please read (and optionally copy, paste and test the problem with) the following sample code lines:_
```
Sub Indentation_Test_Sample_Code()
    '===================================================================================
    '== This method is just a sample for edition purposes. It is not intended to be
    '== executed nor used as coding hint sample, and it does not do any relevant action.
    '===================================================================================
    Dim i As Long
    Do
        Do
            '--= The below line does Not affects the rest of the lines when indenting...
            For i = 1 To 1: Beep: Next
            '--* But the next line Does it.
            'For i = 1 To 1: Beep: Next
        Beep
        '- From the above line (and all after the previous commented FOR loop) will be
        ' indented by RubberDuck to the left which actually it is a wrong behaviour.
        '- This issue can be reproduced using Module indentation, tested with a shortcut.
        '- It happens with loops like For-Next, Do-Loop and While-Wend, but always when
        ' they are in the same line and that line is commented out.
        '===
    
        'While False: Wend'--= Note that this comment just at the EOL "stops" the issue.
        Beep
        'While False: Wend '--* But this one (at least an space after the EOL) does not.
    Beep
Loop
Loop
End Sub
```

**Expected behavior**
- Indentation after a commented line, even when it has a complete FOR (or other kind of) loop, must keep aligned to the previous commented line, except if that line triggers a valid rule like be at begining of the method and that rule is active, just to say a valid rule as an example.

**Screenshots**
**Logfile**
**Additional context**

**Comment by retailcoder** [comment]
Thanks for the report! I've reproduced the issue and can confirm there's a problem, but it appears to be an edge case affecting procedures with commented-out statement-syntax loops. Commented-out block syntax does not behave like this.

**Comment by retailcoder** [comment]
Side note, version 2.4.1.5105 is getting old 😉

**Comment by kirill-tkachenko7** [comment]
Not sure if it should be a separate issue or not. The indenter puts additional indent after a comment which contains a colon followed by "do", like this:
`Private Sub SomeSub()
    AnotherSub
    AndOneMoreSub
    'important comment: do not get surprised when line below gets an extra indent
        WronglyIndentedSub
    End Sub`

Version 2.5.0.5244
