### ISSUE TITLE
Mark Interop only methods as such and create a project analyzer for them.

### ISSUE THREAD

**Issue by rubberduck203** [rubberduck-vba/Rubberduck#536]
Visual Studio 2015 lets you create project specific analyzers, similar to what R# does in general. We have some code that exist to facilitate COM Interop, but that should not be used internally. I'm thinking we could create a custom attribute `InteropOnlyAttriubute` and apply it to these methods. Then, an analyzer to check the name space of any code calling on these methods. If the namespace isn't `Rubberduck.*Interop`, raise a warning. Similar to marking an old method with `[Obsolete]`, we could get a custom compile time warning about internal code using methods it shouldn't be.

Some reference links.
- [Discussion with Jereon](http://chat.stackexchange.com/rooms/8595/conversation/c-custom-attributes-and-project-analyzer)
- [MSDN Creating Custom attribute](https://msdn.microsoft.com/en-us/library/sw480ze8.aspx)

**Comment by ckuhn203** [comment]
There are also some default constructors for serialization and designers that shouldn't be directly called in our code. These would also be good targets for this kind of analysis.

**Comment by bclothier** [comment]
This issue was made 2 years ago, and we don't have any `*Interop` namespaces now. 

Do we still have a use case for this particular type of analyzer? 

Note: PR #3975 will be introducing an analyzer that enforces COM attributes but we're talking about something different here.

**Comment by rubberduck203** [comment]
No. This was specifically to look for places where we were using the source control COM interop interfaces instead of the internal ones. It was an architectural concern at the time, but those don’t exist anymore.
