### ISSUE TITLE
A big "Thank You".... and a question.

### ISSUE THREAD

**Issue by NikkRush** [rubberduck-vba/Rubberduck#5381]
Hi,
First off, thanks for your great work! I am not a programmer by education, but doing more and more coding in the line of my work. I am not familiar with Visual Studio and the tools of "real" software developers, so I am merely scratching on the surface of what RubberDuck can do. The things I use, though, mostly the Project Explorer and refactoring, are a great help for which I would like to thank you.
Here my question: I am working with MS Access and I am often obligated to close and reopen the files I work with. Whenever I restart the VDE, the refresh of the Project Explorer takes over 20 seconds. My computer is an i7 with 32 GB of memory.
I was wondering if I missed a setting that could somehow accelerate the startup.
Thanks again, keep up the great work!
Cheers,
Niklas

**Comment by Vogel612** [comment]
From what I can tell, restarting the VBE implies that Rubberduck can not cache any analysis results from before. This means to make Rubberduck safe to use, the ducky needs to look at everything in the project you opened. 

20 seconds is a pretty good time for that overall. For comparison: When I start IntelliJ for my current paid work project, that usually takes on the order of 1-2 minutes. Of course the more code you have in your project, the longer the startup takes.

**Comment by NikkRush** [comment]
OK, thanks Clemens, I thought only we in our CAD-Design-corner had to endure several minutes of waiting time ;) Good to know!
Grüße nach Stuttgart,
Niklas
