### ISSUE TITLE
Copy "Inspection Text" to clipboard

### ISSUE THREAD

**Issue by ScoobyQ** [rubberduck-vba/Rubberduck#5392]
Currently cannot copy individual (or even all) inspection results lines of text. Makes looking up issues or discussing them with others more cumbersome as have to manually type out.

I would like the ability to select lines in the inspection results and copy them to clipboard.

QHarr

Labels:  enhancement, user-interface

**Comment by MDoerner** [comment]
Thanks for reporting this.

There is a copy to clipboard button in the top-right of the inspection results window. 

However, that is broken atm, as reported in #5292. Still, there is a fix for it in the pending PR #5390.

Closing as a duplicate.
