### ISSUE TITLE
Inspection false positive "Argument with incompatible object type" for IUnknown

### ISSUE THREAD

**Issue by Greedquest** [rubberduck-vba/Rubberduck#5394]
All objects implement IUnknown in COM languages like VBA (or at least all interfaces are derived from it)

The following code:
```vb
Sub test()
    Triggered New Collection
End Sub

Private Sub Triggered(ByVal pUnk As IUnknown)
    Debug.Print TypeName(pUnk)
End Sub
```
runs just fine, but triggers the inspection.

**Comment by MDoerner** [comment]
This should be fixed via #5404.
