### ISSUE TITLE
Procedure description attribute

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#54]
This feature allows the user to enter a short description for a module member, to appear in the _object browser_ when it is selected.

related: #48 & #49 (same prerequesites, although like #52 it can work off temporary files)

**Comment by retailcoder** [comment]
Again (sorry for all the notifications!), @ckuhn203 is the SCI code responsible for exporting/importing modules decoupled enough to be reused for this?

**Comment by ckuhn203** [comment]
Yes. Absolutely. It's implemented through VBE extensions. IIRC it's even located in the VBE project.

**Comment by retailcoder** [comment]
As of yesterday, we're *reading* these attributes into `Declaration` objects. I feel like delaying *writing* to 2.x, there's really quite a bit of work left to do with the other core things.

**Comment by retailcoder** [comment]
Per linked issue, this will be implemented as annotations:

    '@ModuleAttribute.VB_Description("This module is responsible for XYZ")
    '@MemberAttribute.VB_Description("This procedure is responsible for XYZ")

Or:

    '@Description("This module is responsible for XYZ")

The `@Description` annotation would be context-sensitive and become a module attribute when found in the declarations section, or a member attribute when found in a procedure.

This annotation will require an inspection to ensure only one attribute is created per scope.
