### ISSUE TITLE
"Parameter can be passed by value" should be applicable to interface implementations and event handlers

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#541]
This inspection currently ignores members that implement an interface or that handle an event, because changing these signatures would break the code.

We need to implement a quickfix/refactoring that propagates such signature changes up to the interface/event declaration, and all of its implementations/handlers: that would be essentially #284 (*Change Signature* refactoring).

And then we can re-enable the inspection on interface members and event handlers.

**Comment by Hosch250** [comment]
When you do this, remember to make sure the inspection hits all implementations of the interface method or some might be broken.
