### ISSUE TITLE
No Actions happen in About Box

### ISSUE THREAD

**Issue by rgbigel** [rubberduck-vba/Rubberduck#5424]
**Rubberduck version information**
The info below can be copy-paste-completed from the first lines of Rubberduck's log or the About box:

Version 2.5.0.5381

I tried to open the Log file or copy the version info, or to open an issue in the about box, but nothing happens at all.

Could it be that some functions get blocked during use of other functions, but never get unblocked?

**Comment by Vogel612** [comment]
Could you try to find a logfile, preferrably at TRACE level? The file should be available under `%APP_DATA%\Rubberduck\logs`

**Comment by retailcoder** [comment]
Does the "show log folder" command work on the *Settings* dialog or it's just from the *About* box?

**Comment by rgbigel** [comment]
After I reported the above problems, Outlook crashed completely and would no longer start, asking me to contact MS Support. Which I did not, waste of time.
However, after deleting the VBAProject.OTM, reloading the Macros and References, I am up again. 

I'm including the log file here. 

The About box works again, now, but Indenting the Project still does not. 

[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/4313119/RubberduckLog.txt)

**Comment by Vogel612** [comment]
If you say that "The About box works again", then this looks like it might be related to the crash you've seen there. It's not really going to be viable to troubleshoot this without more information, so I'd close this issue here.

The indenter issue is better tracked in the issue linked above :)

**Comment by rgbigel** [comment]
OK, I agree that the About box might get corrupted when Outlook is dying.
But I just found another situation:

It appears the the About Box may stop reacting to mouse clicks (why and when, I do not know)
When this happens, you can **use the Tab key and Enter** to get the expected function.
