### ISSUE TITLE
Export Active Project should remember the directory setting by project

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#5431]
**Justification**
The `Export Active Project` feature was added to make using source control easier for the user. Unfortunately, having to navigate to the desired source code directory with each invocation of the routine makes its actual use less than ideal.

**Description**

- * When `EAP` is activated, there should be an option to save the currently selected directory for use as the defaulted output directory for the next invocation.
- * This directory should be stored on a per-project basis, so each project's source can go in its own directory.
- * Possible implementations:
  * A check box to `Save this directory for future use on this project` each time `EAP` is invocked
  * If the directory chosen this time is different than the one saved for the project, prompt to save it for future use.
  * Automatically save the currently chosen directory for the project without asking.

**Additional context**

**Comment by BZngr** [comment]
Closed by PR #5988
