### ISSUE TITLE
False Positive `Parameter {x} is never used` in an Interface

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#5433]
**Rubberduck version information**
```
Version 2.5.0.5384
OS: Microsoft Windows NT 10.0.17134.0, x64
Host Product: Microsoft Office 2016 x64
Host Version: 16.0.4966.1000
Host Executable: EXCEL.EXE
```

**Description**
An `Interface` with one Function is generating the inspection for only 1 of 3 parameters

**To Reproduce**
```
'@Interface
'@folder Utilities.Logger
Option Explicit

Public Function FormatMessage(ByVal level As LogLevel, ByVal loggerName As String, ByVal message As String) As String
End Function
```

**Expected behavior**
It's an `Interface`, there should be _no_ `Parameter never used` inspections generated.

**Screenshots**
N/A

**Logfile**
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/4356424/RubberduckLog.txt)

**Additional context**
N/A

**Comment by MDoerner** [comment]
Based on the information provided, we cannot determine whether this is indeed a false-positive or not.

Are there implementations of the interface?
If yes, does any of them use the reported parameter?

If there are implementations and none uses the parameter, the inspection result is correct.

**Comment by retailcoder** [comment]
The `@Interface` annotation should suffice for the inspection to ignore these parameters, no?

**Comment by MDoerner** [comment]
No, we also flag all parameters that are unused in all implementations, same as R# would do.

**Comment by retailcoder** [comment]
In that case then yeah whether there's a result would depend on whether or not all implementations of the interface are not using the parameter.

If there are no implementations, issuing a result is noise though.

**Comment by MDoerner** [comment]
We do not issue any results, in case there is no implementation.

**Comment by daFreeMan** [comment]
My bad. The parameter is not used in the `Implements`. The quick fix properly removes the parameter from both the `Interface` and the `Implements`.
