### ISSUE TITLE
False negative `ByRef parameter {x} could be passed ByVal`

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#5434]
**Rubberduck version information**
```
Version 2.5.0.5384
OS: Microsoft Windows NT 10.0.17134.0, x64
Host Product: Microsoft Office 2016 x64
Host Version: 16.0.4966.1000
Host Executable: EXCEL.EXE
```

**Description**
A `worksheet` parameter is being passed `ByRef`. The procedure does _not_ assign a new worksheet to the parameter (actually, the parameter is passed along to other procedures only - there are no `wsParameter.something = bar` assignments at all in _this_ procedure)

**To Reproduce**
`Private Sub PrintReport(ByRef report As Worksheet, ByVal clinicList As ProcessClinic, ByVal monthlyReportSettings As NPSbyMonthSettings)`

**Expected behavior**
This should be picked up by the inspection

**Screenshots**

**Logfile**
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/4359400/RubberduckLog.txt)

**Additional context**
_Unfortunately_, this seems to be inconsistent. In processing inspections for this module, there were quite a number of `ByRef could be ByVal` inspections. When I was down to the last 2, I noticed that _one_ of the `ByRef` parameters for this particular `Sub` had been flagged (`ByRef clinicList As ProcessClinic`). I used the quick fix on that one. After the fix and parse, there were now 4 `ByRef could be ByVal` inspections - 3 _other_ `ByRef report As Worksheet` parameters had been identified, but the one in the example above still had _not_.

**Comment by MDoerner** [comment]
In the cases where you do not get a result, is the parameter passed to another procedure or function as ByRef argument?

**Comment by daFreeMan** [comment]
No. At this point, there are no `ByRef` parameters in this module at all. There are no calls made outside the module where this parameter is passed.

**Comment by MDoerner** [comment]
Just to clarify, in my question I ask about both explicitly and implicitly ByRef.

**Comment by daFreeMan** [comment]
I do not believe that I have any implicit ByRef left in my code. I've been pretty good about specifying.

**Comment by retailcoder** [comment]
@daFreeMan are you still experiencing this one? I'm thinking it might have had something to do with assignment resolution, and possibly fixed with @MDoerner's work on default members.
