### ISSUE TITLE
False Negative `Property {x} has no getter` inspection

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#5436]
**Rubberduck version information**
```
Version 2.5.0.5384
OS: Microsoft Windows NT 10.0.17134.0, x64
Host Product: Microsoft Office 2016 x64
Host Version: 16.0.4966.1000
Host Executable: EXCEL.EXE
```

**Description**
The code below produces only 1 `Property {x} has no getter` inspection: `Property 'YtdDetractor' has no getter.` This code does compile cleanly - the properties are `Let` externally to the class, then are used internally in `Get`ter calculating functions.

**To Reproduce**
```
'@Ignore ProcedureNotUsed : False Positive
Public Property Let YtdDetractor(ByVal theVal As Long)
 this.YtdDetractor = theVal
End Property

'@Ignore ProcedureNotUsed : False Positive
Public Property Let ytdNeutral(ByVal theVal As Long)
 this.ytdNeutral = theVal
End Property

'@Ignore ProcedureNotUsed : False Positive
Public Property Let YtdPromoter(ByVal theVal As Long)
 this.YtdPromoter = theVal
End Property

'@Ignore ProcedureNotUsed : False Positive
Public Property Let ytdResponses(ByVal theVal As Double)
 this.ytdResponses = theVal
End Property
```

**Expected behavior**
It appears that it should produce 4 inspections, not just one

**Screenshots**

**Logfile**
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/4360200/RubberduckLog.txt)

**Additional context**
Please ignore the smelly code, there is some poop to scoop here...

**Comment by MDoerner** [comment]
To further home in on the core issue here, are there Property Get methods with the same name in another module?

**Comment by retailcoder** [comment]
Seems fixed.

![image](https://user-images.githubusercontent.com/5751684/113235892-d6584180-9271-11eb-8389-fef5b8e4f7f7.png)

**Comment by daFreeMan** [comment]
Fix confirmed
