### ISSUE TITLE
Broken quick fix for `Variable '{x}' is not used` inspection

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#5439]
**Rubberduck version information**
```
Version 2.5.0.5384
OS: Microsoft Windows NT 10.0.17134.0, x64
Host Product: Microsoft Office 2016 x64
Host Version: 16.0.4966.1000
Host Executable: EXCEL.EXE
```

**Description**
When a local variable is declared _and assigned to_, the `Remove unused declaration` quick fix for the `Variable '{x}' is not used` inspection _only_ removed the declaration, leaving the unused assignment and uncompilable code.

**To Reproduce**
1. enter this code:
```
Dim Foo As myObject
Set Foo = New myObject
```
2. Parse
3. Activate the `Remove unused declaration` quickfix on the `Dim Foo...` line
3. Parse

**Expected behavior**
Either:
A) There should be an additional `Remove declaration and unused assignment` quick fix that will remove _both_ lines, or
B) The quick fix should only remove the `Set Foo...` line leaving the next parse to reidentify the unused variable and offer to remove the declaration.

**Screenshots**

**Logfile**
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/4369762/RubberduckLog.txt)

**Additional context**

**Comment by MDoerner** [comment]
First of all, that only the declaration gets removed and not the assignments is on purpose. We do not want break the code in potentially unexpected ways if the RHS of the assignment has side-effects.

Second, it really is a bug that the undeclared variable gets removed like that, instead, we should deactivate the quickfix for undeclared variables.

**Comment by daFreeMan** [comment]
I may have thrown the wrong portions under the bus, but the ducky is leaving something broken and that's Bad™
