### ISSUE TITLE
Minor formatting issue in `Refactor | Encapsulate Field` dialog box

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#5447]
**Rubberduck version information**
```
Version 2.5.0.5394
OS: Microsoft Windows NT 10.0.17134.0, x64
Host Product: Microsoft Office 2016 x64
Host Version: 16.0.4966.1000
Host Executable: EXCEL.EXE
```

**Description**
The vertical text formatting is off.

**To Reproduce**
1. Execute the `Encapsulate Field` refactoring
2. Select a field to encapsulate
3. Look at the `Property Name` entry box

**Expected behavior**
The vertical text formatting should be "Centered".

**Screenshots**
![2020-03-25 13_15_55-Rubberduck - Encapsulate Field](https://user-images.githubusercontent.com/11889733/77565989-67e0e680-6e9b-11ea-8e18-f0f79b5b26b7.png)

**Logfile**
N/A

**Additional context**
This is the minorest of formatting issues and the nitiest of nit picks

**Comment by retailcoder** [comment]
I know I've stalled a lot on that work-in-progress PR I haven't touched in way too long, and I really don't want to be blocking anyone, but the UI/UX of this dialog (and the wiring with the viewmodel) is exactly what's WIP on my local. That said I'm completely swamped/buried under (dayjob-)work at the moment, so don't let my forever-WIP ghost PR block anything.
