### ISSUE TITLE
System resources in WPF should be dynamic resources

### ISSUE THREAD

**Issue by MDoerner** [rubberduck-vba/Rubberduck#5451]
We currently bind system resources, in particular from `SystemColors`, as static resources in multiple places. There are two versions of this:

Binding directly:
https://github.com/rubberduck-vba/Rubberduck/blob/5fec4adff9b43206f2339fadb040a6129583a397/Rubberduck.Core/UI/About/AboutControl.xaml#L38

Binding statically via the key:
https://github.com/rubberduck-vba/Rubberduck/blob/5fec4adff9b43206f2339fadb040a6129583a397/Rubberduck.Core/UI/Styles/LightBlueTheme.xaml#L108

This static binding means that changes to the system resources by the user are only reflected when RD gets reloaded. Consequently, system resources should always be stored in dynamic resources.

Binding dynamically via the key:
https://github.com/rubberduck-vba/Rubberduck/blob/5fec4adff9b43206f2339fadb040a6129583a397/Rubberduck.Core/UI/Styles/DefaultStyle.xaml#L45

**Comment by GmausDev** [comment]
I´ll take it ^^

**Comment by Vogel612** [comment]
This will most likely be easiest to address in multiple PRs, if only because of the sheer amount of XAML resources that may need to be changed (and the configuration changes that might be associated being complicated to review)

**Comment by GmausDev** [comment]
@Vogel612  I do the first at #6034 , its what its requested?

**Comment by GmausDev** [comment]
All the changes done

**Comment by Vogel612** [comment]
This resulted in a lot more shenanigans than anticipated, but it's in the 2.5.9 release for as many resources as appeared to continue working
