### ISSUE TITLE
CE Folder Drag/Drop should disallow drop target being the same as the drop source

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#5473]
**Justification**
Drag and drop can occur accidentally, causing an unintended reorganization involving duplication of child folders.

**Description**
Making the drop source an invalid drop target might fix the problem without needing to prompt. Failing that, user should get to confirm the drop operation.

**Additional context**
Drop operation is causing a reparse; avoiding an accidental drop avoids an accidental reparse.

**Comment by MDoerner** [comment]
I am clearly against a confirmation dialog. This feels very unnatural to me when doing drag and drop. The file explorer also does not ask whether you really want to move that folder.

I agree that we should not allow the source as the drop target. This also seems to be the preferred solution in the issue itself. I wonder why the title does not reflect this.

**Comment by retailcoder** [comment]
@MDoerner fixed - I wrote the title first, and the alternative (and better) solution appeared as I was typing up the issue :smile:

**Comment by daFreeMan** [comment]
Is there a way to add the even to the undo buffer? That would fix the originally reported issue of "oops, I accidentally dragged this class _somewhere_..."

**Comment by retailcoder** [comment]
@daFreeMan the undo buffer is too small, dragging a folder with more than 20 modules under it would bust it.
