### ISSUE TITLE
Error when parsing is Ready

### ISSUE THREAD

**Issue by eduardoxy** [rubberduck-vba/Rubberduck#5478]
**Rubberduck version information**
Version 2.5.0.5418
OS: Microsoft Windows NT 6.3.9600.0, x64
Host Product: Microsoft Office x64
Host Version: 16.0.12624.20466
Host Executable: EXCEL.EXE

**Description**
The Rubberduck start as Pending in the project. When I click at the button to sync with the project it loads all contents and shows the folders.
The status of the parser process is given as "Ready" but the Code Window freezes and I can't do nothing.

**To Reproduce**
Start the Code Window using ALT+F11 and click at the Rubberduck Menu in the refresh button.

**Expected behavior**
Shows the Code Explorer and allow to navigate it.

**Logfile**
I am sending the log file attached with this issue.
If is necessary, I can send you any file with this behavior.

Thank for the support.

[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/4533836/RubberduckLog.txt)

**Comment by MDoerner** [comment]
This sounds like it might be related to issue #5442

**Comment by eduardoxy** [comment]
Thanks @MDoerner 
I have read the entire issue and solve my problem downgrading the RB version.

I am closing the issue.
Thank you again.
