### ISSUE TITLE
False Positive on Member Not On Interface Inspection - type Application

### ISSUE THREAD

**Issue by SmileyFtW** [rubberduck-vba/Rubberduck#5485]
**Rubberduck version information**
Version 2.5.0.5418
OS: Microsoft Windows NT 10.0.18362.0, x64
Host Product: Microsoft Office x86
Host Version: 16.0.12624.20466
Host Executable: EXCEL.EXE

**Description**
For items that show up in intellisense for the Application object the Inspection flags them as not found on the compile-time interface.

**To Reproduce**
1. In a code module type Application.ScreenU (intellisense shows the ScreenUpdating member)
2. Complete with = False or = True
3. Refresh RD
4. View Code Inspections and find ScreeenUpdating flagged as not on the compile-time interface of Application
Note that many other members are flagged as well:
WorksheetFunction
Left
Width
Height
PathSeparator
etc.

**Expected behavior**
For items that Inellisense "knows" the members for an object the Inspection does not flag as MemberNotOnInterface

**Screenshots**
N/A

**Logfile**
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/4564579/RubberduckLog.txt)

**Additionl Context**
Similar to the inspection on MS Forms issue: https://github.com/rubberduck-vba/Rubberduck/issues/4995

**Comment by retailcoder** [comment]
Might have been fixed at one point, can't repro this.
