### ISSUE TITLE
False positive `Property let accessor '{x}' is not used

### ISSUE THREAD

**Issue by SmileyFtW** [rubberduck-vba/Rubberduck#5486]
**Rubberduck version information**
Version 2.5.0.5418
OS: Microsoft Windows NT 10.0.18362.0, x64
Host Product: Microsoft Office x86
Host Version: 16.0.12624.20466
Host Executable: EXCEL.EXE

**Description**
Inspection is reporting the ProcedureNotUsedInspection on a property that is used.

**To Reproduce**
Sample:
FooModel Class
```
Private Type TFoo
   ID As String
End Type
Private this as TFoo

Public Property Get ID() As String
   ID = this.ID
End Property
Public Property Let ID(byval value As String)
   this.ID = value
End Property
```

Standard Module
```
Public Sub CreateSomeFoos(byval FooIDs As Range)
Dim currCell As Range
For Each currCell In FooIDs
   Dim currFoo As FooModel
   Set currFoo = New FooModel
   With currFoo
      .ID = currCell.value
   End With
End Sub
```

ProcedureNotUsedInspection
Property let accessor 'ID' is not used

**Expected behavior**
The inspection should not Flag ID as not being used; it is being used.

**Logfile**
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/4564745/RubberduckLog.txt)

**Comment by BZngr** [comment]
Duplicate #5490
