### ISSUE TITLE
Use Meaningful Name Inspection Fix for control names doesn't work as expected

### ISSUE THREAD

**Issue by SmileyFtW** [rubberduck-vba/Rubberduck#5487]
**Rubberduck version information**
Version 2.5.0.5422
OS: Microsoft Windows NT 10.0.18362.0, x64
Host Product: Microsoft Office x86
Host Version: 16.0.12624.20466
Host Executable: EXCEL.EXE

**Description**
Selecting a flagged ms forms control and selecting Fix>Ignore Once doesn't ignore the Inspection

**To Reproduce**
On a User Form add a Label (name is Label1)
Refresh RD
In the UseMeaningfulNameInspection select flagged control (Label1)
CI Pane>Fix>Ignore Once
Refresh RD
Inspection is not ignored
Does not work as expected

Alternatively:
CI Pane>Fix>Rename control
Rename control in dialog
Refresh RD
Works as expected

**Expected behavior**
The inspection would ignore the instance selected for the Ignore Once control.

**Comment by retailcoder** [comment]
Form controls' declarations don't really exist, there is no code to annotate for them.

I submit that the expected behavior should be that the *Ignore Once* quick-fix should not be available when the target is a `Control` declaration.

*Ignore in module* works as expected.

**Comment by retailcoder** [comment]
Ah, actually inspections derived from `DeclarationInspectionUsingGlobalInformationBase` (which `UseMeaningfulNames` is) have a `protected virtual ICollection<string> DisabledQuickFixes(Declaration declaration)` method that's only missing `DeclarationType.Control` to get _ignore once_ disabled for form control targets.

Should be a very easy fix!
