### ISSUE TITLE
vbNullstring problems

### ISSUE THREAD

**Issue by AliWood282** [rubberduck-vba/Rubberduck#5488]
I would suggest that your recommendation to use vbNullSTring instead of "" is misplaced. 
In my project it slows down a 'sort' routine by a factor of 5, from 2 seconds to 10 seconds. I can reproduce this at will.
I am using VBA within Office 365 Excel.

Would value your opinion. Is this a known effect? I can assure you that I'm not imagining it - I have reproduced it several times (and reversed it) at will. Many thanks
Alistair Wood

**Comment by retailcoder** [comment]
I wouldn't say misplaced, but definitely has caveats... the idea is to prefer `vbNullString` over an empty string literal in places where they are equivalent. If they are not, then the result can & likely *should* be ignored.

If it's causing problems more often than not, consider configuring that inspection with a "do not show" severity level ("disable this inspection" from the results toolwindow), and it will no longer run.

It's like reporting a procedure as "not used" because no early-bound user code is referring to that procedure: if it's used in late-bound code, or invoked by some button on a worksheet, then the recommendation to delete the unused procedure can be seen as misplaced.

**Comment by retailcoder** [comment]
That said no, this was not a known effect. Curious about that `Sort` routine =)

**Comment by AliWood282** [comment]
OK, I'll disable the inspection. 
I could send you the Sort routine but it is very tied up with the rest of the (complicated) project, and calls numerous other routines. 
I remain mystified. 
Thanks very much.

**Comment by SmileyFtW** [comment]
Could you provide an example that could be studied to determine what the underlying cause is?

**Comment by SmileyFtW** [comment]
Also, you don't necessarily need to completely disable the Inspection. You can put `'@Ignore EmptyStringLiteral` right before the line where the empty string literal is assigned. You may still want to see other warnings about use of string literals.

**Comment by AliWood282** [comment]
Just to convince myself I wrote a simple loop to test the comparative speeds using "" and vbNullString. 
This was 5 times faster using vbNullString which proves me absolutely wrong! 
So, back to the drawing board. My guess is that doing a mass replace of "" with vbNullString picked up some instances that were not just simple empty strings on their own, and perhaps generated some invalid syntax. 
I will do a slower manual replacement being careful what I wish for.... Sorry and thanks

**Comment by SmileyFtW** [comment]
LOL. When I read "I could send you the Sort routine but it is very tied up with the rest of the (complicated) project, and calls numerous other routines." My sense was that the complexity and calls to numerous other routines might be the real culprit. Be interesting to find out what the bottleneck truly is.

**Comment by AliWood282** [comment]
It will. 
I wish I could temporarily 'disable' Rubber Duck from parsing, there it goes again chugging along in the background.... Initially I'd thought that Rubber Duck was the problem itself!

**Comment by SmileyFtW** [comment]
The way I do it is use the Add-In Manager under the Add-Ins menu to Unload/Reload RD. IIRC there has been some discussion of providing that feature in RD. My sense of it is that it wouldn't be any easier/convenient in RD itself than to just use the Add-In Manager.

**Comment by AliWood282** [comment]
ok. cheers for your help
