### ISSUE TITLE
Module disappears with colon

### ISSUE THREAD

**Issue by s3lli9** [rubberduck-vba/Rubberduck#550]
If I accidentally left a colon at the end of the line, the module disappears from the Code Explorer while VBA compiles perfectly.
Like this:
```
public sub Bar()
    dim foo1, foo2  
    foo1 = "Hello ":
    foo2 = "world!"
end sub
```
*Rubberduck 1.3.1 - Office 2013 (32-bit) - Windows 8.1 (64-bit)*

**Comment by ckuhn203** [comment]
Thanks. Most likely a grammar issue. We'll look into it.

**Comment by retailcoder** [comment]
Eh, our grammar has issues, some of which we have no idea how to fix ...other than rewrite the entire grammar from scratch. Might not be as awesome as a parser that accepts everything the VBA language does, but next release will report ANTLR parser exceptions in a dockable toolwindow:

The only thing is that these *can* sometimes be confusing:

![invalid-input](https://cloud.githubusercontent.com/assets/5751684/7907413/f1bbb61a-0806-11e5-843a-b02624038213.png)

..but it *does* indicate that there's an issue with parsing a specific module, often pretty accurately:

![invalid-input-linenumbers](https://cloud.githubusercontent.com/assets/5751684/7907488/d87b0dc6-0807-11e5-8bc7-70d04e004539.png)

![invliadinput-colon](https://cloud.githubusercontent.com/assets/5751684/7907510/25966aa6-0808-11e5-89f9-dc17ebdcfadf.png)

I'm not going to pretend this *fixes* the issue, but until we figure out a real grammar fix, this might be the best we can come up with :disappointed:

**Comment by s3lli9** [comment]
I think this is a good compromise.
Indeed, VBA is sometimes a little too permissive and allows an incorrect code.
Displaying ANTLR parser exceptions is a good idea. :+1:

**Comment by retailcoder** [comment]
Fixed on my fork.
