### ISSUE TITLE
Rel 2.5.0.5244 - Context menu not available in VBE and crash on adding Test Module - Solved (partially) with old rel .5226

### ISSUE THREAD

**Issue by gicif** [rubberduck-vba/Rubberduck#5501]
**Rubberduck version information**
    Rubberduck version: 2.5.0.5244
    Operating System: Microsoft Windows NT 10.0.18363.0 x64
    Host Product: Microsoft Office x64
    Host Version: 16.0.12730.20352
    Host Executable: EXCEL.EXE

**Description**
1 - RD context menu not available in VBE (possibily related to issue "Rubberduck: not available in VBE, but loaded in Add-In-Manager #3538")
2 - Excel and VBE are unresponsive after adding Test Module, or opening a project with a test module inside. (possibly related to issue "Excel and VBE are unresponsive #5403")

**To Reproduce**
1. Launch Excel (new xlsm file, empty vb project)
2. Enter VBIDE
3. Load RD Add-In: RD menu is available and it works, but RD context menu isn't available.
![Immagine](https://user-images.githubusercontent.com/65764572/82662848-e30e1100-9c2e-11ea-97fa-8445444f0819.jpg)
4. Add a new Test Module: Excel freezes.

**Logfile**
After loading RD on new xlsm file with VBA empty project and refreshing Code Explorer
[RubberduckLog-Startup.txt](https://github.com/rubberduck-vba/Rubberduck/files/4667811/RubberduckLog-Startup.txt)

After adding a new Test Module
[RubberduckLog-TestModule.txt](https://github.com/rubberduck-vba/Rubberduck/files/4667740/RubberduckLog-TestModule.txt)

After loading RD on new xlsm file with VBA empty project and refreshing Code Explorer (rel . 5226)
[RubberduckLog-Startup-5226.txt](https://github.com/rubberduck-vba/Rubberduck/files/4668084/RubberduckLog-Startup-5226.txt)

**Additional context**
The PC is relatively new (03/2020) and fairly clean. Other main software installed on machine: 
- Microsoft Office Professional 2019
- SharpDevelop (rel. 5.1.0.5216 - need Microsoft Visual C++ 2008 Redistributable - x86)

**Notes**
- Uninstall SharpDevelop, unistall RD, repair Office, restart PC and reinstall RD only, doesn't solve.
- Tried with Rubberduck v2.5.0.5443-pre, but it doesn't solve
- Tried with Rubberduck v2.4.1.5226-pre, still having errors in Logfile and context menu isn't yet available, but Excel and VBE remains responsive.

Many many thanks to all contributors for develop and maintain this awesome tool !

**Comment by Vogel612** [comment]
The logs contain some COM exceptions around the `RefactorExtractMethodCommand`... I dimly recall that other issues with similar behaviour also had that specific command's COM interaction acting up.

AIUI that refactoring is currently undergoing a rewrite because it's somewhat broken if only due to the complexity of the refactoring itself and should be unreachable through the GUI...

**Comment by MDoerner** [comment]
Can you retry with prerelease v2.5.0.5457-pre or newer? With that version, we fixed a bug with the test explorer UI causing freezing in some projects.

**Comment by gicif** [comment]
Hi! Thanks for your feedback! I tried with prerelease v2.5.0.5457-pre. 
Excel and VBE remains responsive, but context menu isn't yet available and vbe slow down after adding a new test module.
I attach log files at startup and after adding new test module.
Currently, my best working environment remains with v2.4.1.5226-pre: no freezing, no  slowdown with test module (and no context menu too, but this is not a big issue for me, really).
Ciao!

[RubberduckLog - 5457-pre - Test Module.txt](https://github.com/rubberduck-vba/Rubberduck/files/4850282/RubberduckLog.-.5457-pre.-.Test.Module.txt)
[RubberduckLog - 5457-pre - Startup.txt](https://github.com/rubberduck-vba/Rubberduck/files/4850284/RubberduckLog.-.5457-pre.-.Startup.txt)

**Comment by gicif** [comment]
Solved with v. 2.5.1.5557.
Excel and VBE remains responsive after adding a new test module (yet no context menu).
Thanks!
