### ISSUE TITLE
VB6 support

### ISSUE THREAD

**Issue by FoliniC** [rubberduck-vba/Rubberduck#5503]
Hi, I've just installed Rubberduck on my windows 2012 R2 dev server.
When the online menu show up only "indent" menu is enabled.
It's my installation fault or there's no "extended" support for vb6?

Thanks in advance
Carlo
![RubberDuck](https://user-images.githubusercontent.com/15870531/82816956-608a8900-9e9c-11ea-93f0-3fa81f809f87.jpg)

**Comment by mansellan** [comment]
Hi Carlo, thanks for your question.

Rubberduck fully supports VB6, all features should be available. Can I check that your code compiles and you've parsed it successfully (there's a button on the Rubberduck toolbar to initiatate a parsing run)?

**Comment by FoliniC** [comment]
OMG, I didn't realized that I should click the button!
After doing that, the contextual menu gets enabled!
Maybe the code parsing should start automatically or the button label should read "click me".

Thanks for your help!!!

**Comment by mansellan** [comment]
@FoliniC you're very welcome. There's no reliable way of automatically parsing a newly-opened project (the VBE fires the `ProjectOpened` event too early for it to be usable for this), but this definitely needs to be more discoverable.
