### ISSUE TITLE
Add a Windows menu

### ISSUE THREAD

**Issue by mansellan** [rubberduck-vba/Rubberduck#5505]
**Justification**
Increased discoverability of Rubberduck features.

**Description**
Currently, the various Rubberduck windows are accessible from many different locations. We should additionally provide a central collection of them, in the form of a `Windows` submenu from the RD main menu.

Resharper follows this (common?) design pattern:
![image](https://user-images.githubusercontent.com/25420409/83072048-ffaeac80-a065-11ea-88ea-7884aafd9daf.png)

The above entries are all available from other routes (including from other places on the ReSharper main menu), but having them all collected in one menu provides a quick answer to the questions, "What windows are available?" and "How do I open the window for {x}?". The duplication is justified by the added value.

**Comment by INOPIAE** [comment]
I started on this issue. 
![image](https://user-images.githubusercontent.com/2772829/210881508-24bc54a5-0c77-4d6b-93a0-ed24e95c66eb.png)

- Do I missed any windows?
- Is the order correct?
- Is the position within the menu correct?
