### ISSUE TITLE
Disable or improve or undo drag and drop in the code explorer

### ISSUE THREAD

**Issue by Irubataru** [rubberduck-vba/Rubberduck#5510]
**Justification**
While working I quite often drag and drop folders and modules in the code explorer by accident.

**Description**
So I am not entirely sure why I do this, if it is because the UI is just laggy enough or it doesn't always register mouse up before I have moved, or if I am just a sloppy mouse user. Regardless the result is that I have to undo that operation when I do it by mistake.

There are a few number of ways to fix this that I can think of:
* Add an option to simply disable drag and drop
* Improve it, but I am not sure how, maybe add some delays so that it has to be a more deliberate? I don't know if there is a common practice with drag and drops as it is not a common problem for me.
* Have an undo
* Add a confirmation prompt before moving

**Comment by daFreeMan** [comment]
What is it that you're dragging and dropping - is it something in the RD environment or something native to the VBIDE?

**Comment by Irubataru** [comment]
Oh sorry, should have clarified. Dragging and dropping folders and modules in the Code Explorer with the new drag and drop feature introduced somewhat recently.
