### ISSUE TITLE
not installing

### ISSUE THREAD

**Issue by bgborkosky** [rubberduck-vba/Rubberduck#5514]
trying to install RD as a single user. Win7, Office 2010. Installer seems to run successfully, with no error messages. Re-running the installer recognizes RD as being installed. However, there is no RD folder:
![image](https://user-images.githubusercontent.com/66484361/83896993-9a6c5280-a71a-11ea-9cd2-51c860dd29d7.png)

Also, running Excel, there is no splash screen and RD does not show as being loaded
![image](https://user-images.githubusercontent.com/66484361/83897149-d1daff00-a71a-11ea-8f53-7856643a730e.png)

any ideas about what to do next?

**Comment by retailcoder** [comment]
Since RD is a VBE add-in, have you tried bringing up the VBE (Alt+F11)?

**Comment by bgborkosky** [comment]
Ah, I suppose that should have been obvious, but it wasn't. Perhaps RD could mention that on the last install popup? Thanks for the info......much appreciated
