### ISSUE TITLE
completelly stuck

### ISSUE THREAD

**Issue by bertelu** [rubberduck-vba/Rubberduck#5522]
Version 2.5.0.5472
OS: Microsoft Windows NT 10.0.17763.0, x64
Host Product: Microsoft Office x86
Host Version: 16.0.11929.20776
Host Executable: EXCEL.EXE

**Description**
since last update on Excel (O365) Rubberduck takes ages to start if not completelly blocking VBA and Excel. even going simply on "settings" make Excel/VBA/Rubberduck unusable
**To Reproduce**

1 open vba code. rubberduck will take ages. after a wile a message appear "Excel is waiting another application to complete an OLE action" hence the Excel/VBA/Rubberduck get stuck

**Expected behavior**
normal  rubberduck behavior

**Screenshots**
![image](https://user-images.githubusercontent.com/36537595/84484782-8638d000-ac9b-11ea-942e-36a5669e64dd.png)

**Logfile**

[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/4769769/RubberduckLog.txt)

**Additional context**

**Comment by retailcoder** [comment]
Thinking this modal message might have been blocking the startup, making it feel much longer than it actually was. Sounds like a COM issue, would you happen to have the logs? Very likely that there's exception details in it...

**Comment by bertelu** [comment]
Hi, attached the log folder


Il giorno ven 12 giu 2020 alle ore 15:52 Mathieu Guindon <
notifications@github.com> ha scritto:

**Comment by Irubataru** [comment]
I also had the same issue today, but I am not sure why. Microsoft reported that an update was ready for office, and that is when Rubberduck froze in the same way, repeatedly freezing until I killed the process. Unfortunately it didn't leave any logs behind. When I finished updating the problem disappeared. Not sure if it is related or not.

**Comment by bertelu** [comment]
look it was also for me a problem of office updates. now it's working
normally

Il mar 23 giu 2020, 15:47 Jonas Rylund Glesaaen <notifications@github.com>
ha scritto:

**Comment by MDoerner** [comment]
Since this seems to be an issue related to an interaction between loaded add-ins and updates of office, I close this issue as something we cannot really do anything about.
