### ISSUE TITLE
 Excel freezes after processing Pending

### ISSUE THREAD

**Issue by InExSu** [rubberduck-vba/Rubberduck#5524]
**Rubberduck version information**
	Rubberduck version 2.4.1.5239 loading:
	Operating System: Microsoft Windows NT 6.2.9200.0 x64
	Host Product: Microsoft Office 2010 x86
	Host Version: 14.0.7015.1000
	Host Executable: EXCEL.EXE;

**Description**
After clicking the Pending button - freezes Excel and VBE.
Perhaps this is due to my programming style?
In the attachment, one of the files.

[Array_Filter.zip](https://github.com/rubberduck-vba/Rubberduck/files/4806303/Array_Filter.zip)

[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/4806297/RubberduckLog.txt)

**Comment by Vogel612** [comment]
You seem to be using an older version of Rubberduck. I can see from the logfiles that Rubberduck is running into a KeyNotFoundException when checking for unreachable cases in your code.

Could you please try updating Rubberduck to either the [latest "green release"](https://github.com/rubberduck-vba/Rubberduck/releases/latest) — v2.5.0.5244 at time of writing — or the latest prerelease and check whether that fixes your issue?

**Comment by InExSu** [comment]
Many thanks!
Updating the version improved the situation.
Soon I will create an Issue that Code Inspections - does not show errors - ducks move in a circle, but the list is empty.
