### ISSUE TITLE
Code Inspection Doing nothing

### ISSUE THREAD

**Issue by InExSu** [rubberduck-vba/Rubberduck#5525]
**Rubberduck version information**
	Rubberduck version 2.5.0.5244 loading:
	Operating System: Microsoft Windows NT 6.2.9200.0 x64
	Host Product: Microsoft Office 2010 x86
	Host Version: 14.0.7015.1000
	Host Executable: EXCEL.EXE;

**Description**
After the Code Inspections window appears, ducks float in a circle, the list of errors is empty, i cannot click the Refresh button.

[Array_Filter 02.zip](https://github.com/rubberduck-vba/Rubberduck/files/4806596/Array_Filter.02.zip)
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/4806597/RubberduckLog.txt)
![RD Code Inspections](https://user-images.githubusercontent.com/36605404/85177636-305cbd00-b285-11ea-9b83-ab32d782f8eb.PNG)

**Comment by retailcoder** [comment]
Thanks for the report, .5244 is a few builds behind, can you confirm a repro with the latest pre-release build .5473?

**Comment by InExSu** [comment]
Wow!
Thank!
It’s a completely different matter - even there are no interface brakes!
And then I already began to be disappointed - I used to write tests, but I ran them one at a time, manually :-).
Now they will run the tests in a crowd!
