### ISSUE TITLE
Slightly scrolling horizontally in code inspection window when selecting an item

### ISSUE THREAD

**Issue by chrisdaniels** [rubberduck-vba/Rubberduck#5527]
**Rubberduck version information**
The info below can be copy-paste-completed from the first lines of Rubberduck's log or the About box:

Version 2.5.0.5473
OS: Microsoft Windows NT 6.1.7601 Service Pack 1, x64
Host Product: Microsoft Office 2016 x86
Host Version: 16.0.9126.2282
Host Executable: EXCEL.EXE

**Description**
Looks like the fix that was applied in #5237 has bugged out.
On clicking on an item in the Inspection window, it scrolls over to the right slightly so that you cannot see the icon or read the grouping header without scrolling it back. 

**To Reproduce**
1. Go to Code Inspection list
2. Have the Code Inspections window width set to about a quarter of the screen or less
3. Click on any item under a heading
4. List will tab over

**Screenshots**
![image](https://user-images.githubusercontent.com/70784/85726991-8c449d00-b6ee-11ea-9fc8-07161c1aba13.png)

**Comment by MDoerner** [comment]
The _fix_ from #5237 has been reverted recently since it had the side-effect of completely freezing the VBE for some projects. To address this issue a more sophisticated approach will be required.

**Comment by chrisdaniels** [comment]
ok thanks :+1:
