### ISSUE TITLE
Add "Ignore All Occurrences" option to Code Inspections

### ISSUE THREAD

**Issue by chrisdaniels** [rubberduck-vba/Rubberduck#5528]
**Justification**
Sometimes I need to just ignore a lot of legacy code without fixing it, or just want to ignore a bunch of inspections for this one project without having to disable/reenable the inspection globally. Currently I have to select ignore on each one individually or resort to copy/pasting the ignore statement in for speed.

**Description**
Add options to Ignore all detection inspections by type similar to the Fix all options available at the bottom of the Inspections window. 

**Additional context**
For clarity ,this is where I think the ignore all option/s should go 
![image](https://user-images.githubusercontent.com/70784/85733193-e72cc300-b6f3-11ea-9f94-17228e5075cf.png)

**Comment by Vogel612** [comment]
So in this particular case setting to "Do not show" is not wanted because you want new code to be inspected for the inspection you got, right?

**Comment by chrisdaniels** [comment]
Yes exactly that. It would just be easier to bulk ignore a whole bunch in one go when needed. 

Another example would be to get a legacy vba project to a point where there are zero inspections left by ignoring elements that are fine and do not need to be touched, but you would want to inspect any future code additions to the same project. This makes the inspections easier to look through if there were hundreds previously.
