### ISSUE TITLE
Not able to enter Spaces  after Parsing

### ISSUE THREAD

**Issue by rentasad** [rubberduck-vba/Rubberduck#5545]
**Rubberduck version information**
The info below can be copy-paste-completed from the first lines of Rubberduck's log or the About box:

	Rubberduck version 2.5.0.5244 loading:
	Operating System: Microsoft Windows NT 10.0.18363.0 x64
	Host Product: Microsoft Office x86
	Host Version: 16.0.13001.20384
	Host Executable: EXCEL.EXE;

**Description**
After parsing my big project in the IDE I'm not able to enter a space. 
My Log is attachted here:

[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/4966171/RubberduckLog.txt)

I will show you the problem in my Video:

https://youtu.be/7ImDDuFHqqw

in an empty project I don't have this problem - my huge Project have this problem and I don't know why...
I hope you have an idea to find the reason for it?
Best greetings!

Rentasad

**Comment by daFreeMan** [comment]
Define "huge project". How many modules? How many lines of code?

Try updating to the latest pre-release (build .5508 as of today) to see if that fixes the issue. I've got a decent sized project and am not having any issues like that. Huh... only 8300 LOC over 49 modules in this Access project. No issues with build .5508 when working in Excel a couple of days ago, either.

Pre-releases are generally pretty stable and are suitable for a busy, full-time programmer. There is the _occasional_ show-stopping bug that will force you to back up to the previous pre-release, but those are usually fixed pretty quickly.

**Comment by MDoerner** [comment]
Thanks for reporting.

There was indeed a subtle issue with the UI, both for the test explorer and the inspection results that could cause a freeze in some projects. This specific issue has been fixed in the meantime. So, could you try out the current prerelease and see whether that fixes your problem? Otherwise, you will have to wait until the next stable release to see whether the problem still exists for you.

**Comment by rentasad** [comment]
I will try it and will report if it was helpfull. Thanks for your quick reply!

**Comment by rentasad** [comment]
Hi, 
today I completed my integratoin ovf code --> I don't get the error anymore -> the build .5508 fixed the problem
Thanks and best regards
Matthias//Rentasad
