### ISSUE TITLE
JSON

### ISSUE THREAD

**Issue by revans611** [rubberduck-vba/Rubberduck#5551]
Ever thought about adding JSON support to Rubberduck?  After all, C# makes all things possible.  Right?

**Comment by daFreeMan** [comment]
In what ways do you envision using "JSON support" in Rubberduck? What does that mean to you?

(BTW- there are new issue templates for requesting features that have some basic questions that will help guide the questions to provide the data needed to evaluate a new feature request.)

**Comment by retailcoder** [comment]
Earlier versions (like, a year or two ago) shipped an experimental COM API that ended up dropped for lack of attention, and today Rubberduck ships with `Rubberduck.tlb` which can be referenced by VBA projects to early-bind the unit testing API.

Technically nothing(1) prevents us from building some COM-visible library that VBA projects could reference and consume, and indeed expose functionality such as a JSON serializer that could be given an object and spits out a JSON string, but then we're talking about an API (framework-level library?) now, ...and that's a project in its own right - I'd deem it out of scope for Rubberduck, whose role is to extend the IDE.

(1) that's a little lie: there *are* significant hurdles to overcome to make .NET JSON serialization work with a VBA object. But exposing .NET functionality through COM interop isn't impossible (or hard) at all.

Within the scope of an IDE plug-in, JSON support could mean several things (brain dump follows):

- Visualizer tooling that can nicely format JSON; problem is that unlike say, a RegEx pattern, JSON being *data*, it doesn't really belong in code, so effort vs benefits doesn't make an interesting ratio.
-

**Comment by revans611** [comment]
"... out of scope for Rubberduck. ..."

I agree.
