### ISSUE TITLE
EncapsulateField Refactoring default 'value' parameter causes casing change to built-in object's "Value" member

### ISSUE THREAD

**Issue by BZngr** [rubberduck-vba/Rubberduck#5552]
**Rubberduck version information**
Version 2.5.0.25332
OS: Microsoft Windows NT 10.0.18362.0, x64
Host Product: Microsoft Office x86
Host Version: 16.0.13029.20308
Host Executable: EXCEL.EXE

**To Reproduce**
1. Given:
```
Option Explicit

Public mTestField As Long

Public Sub Test()
    Dim rg As Range
    Dim wksht As Worksheet
    Set wksht = Application.Worksheets("Sheet1")
    Set rg = wksht.Range("A1")
    mTestField = rg.Value
End Sub
```

2. Run `EncapsulateField Refactoring` on `mTestField`.  See casing change to `Range.Value` member.

```
Option Explicit

Private mTestField As Long

Public Property Get TestField() As Long
    TestField = mTestField
End Property

Public Property Let TestField(ByVal value As Long)
    mTestField = value
End Property

Public Sub Test()
    Dim rg As Range
    Dim wksht As Worksheet
    Set wksht = Application.Worksheets("Sheet1")
    Set rg = wksht.Range("A1")
    TestField = rg.value
End Sub

```

**Expected behavior**
Need to introduce a Property Let/Set parameter identifier that avoids existing names (or existing names with different casing).  
A couple options come to mind:
1. Pick a different hard-coded default: like "newValue"  
2. Avoid casing issues more generally by generating a parameter name from the Property identifier e.g,: 
```
Property Let TestField(ByVal testFieldValue As Long)
      mTestField = testFieldValue 
End Property
```
Based on some quick experiments, introducing an identifier that matches _any_ existing identifier (with different casing), changes the casing of existing identifiers everywhere in the `Project` (`Procedure`, `Module` scoping is irrelevant).  To generate a _casing-safe_ parameter might require finding a name that is unique throughout the loaded `Projects`.

**Comment by daFreeMan** [comment]
+10000 and my undying gratitude for getting this fixed up!

**Comment by daFreeMan** [comment]
also, related? #4345 (and #5243)
