### ISSUE TITLE
How to add additional templates

### ISSUE THREAD

**Issue by Irubataru** [rubberduck-vba/Rubberduck#5564]
When you right click the Code Explorer and go to Add there is an option called Templates which currently has one default, the predeclared class template. Is it possible to add your own templates? I tried adding a `.rdt` file in `%APPDATA%\Rubberduck\Templates`, but that didn't do anything.

**Comment by bclothier** [comment]
IIRC, the groundworks are there but it isn't lit up. See [this issue](https://github.com/rubberduck-vba/Rubberduck/issues/4549)

**Comment by retailcoder** [comment]
That would be something to look into expanding in 2.5.1.x, I guess.

**Comment by bclothier** [comment]
I looked over the notes and I think the main holdup here is the need to unify the filesystem API discussed in #4794. The template will rely on filesystem a lot and we need to avoid writing to the filesystem willy nilly to avoid introducing a big chunk of untestable black hole.
