### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by BuhTig4ever** [rubberduck-vba/Rubberduck#5568]
**Rubberduck version information**
2020-08-21 18:25:57.3329;INFO-2.5.0.5244;Rubberduck.Common.LogLevelHelper;
	Rubberduck version 2.5.0.5244 loading:
	Operating System: Microsoft Windows NT 6.2.9200.0 x64
	Host Product: Visual Basic x86
	Host Version: 6.00.9782
	Host Executable: VB6.EXE;

**Description**
In a huge project the line in XPKalender.ctl:
    Private strArrayJahrestage(1 To 366, 1 To 6) As Long
leads into an unexpected error. With
   Private strArrayJahrestage(1 To 366, 1 To 6)
The error is not seen.

**To Reproduce**
I have also created a small project with just this line, there the error does not happen.
Therefore it is hard to give you a clear way to reproduce it.

**Expected behavior**
No error

**Logfile**
Rubberduck generates extensive logging in TRACE-Level. If no log was created at `%APPDATA%\Rubberduck\Logs`, check your settings. Include this log for bug reports about the behavior of Rubberduck.
See attached with level Debug and Trace
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/5110079/RubberduckLog.txt)
[RubberduckLog-Trace.txt](https://github.com/rubberduck-vba/Rubberduck/files/5110102/RubberduckLog-Trace.txt)

**Additional context**
Happens also with 
2020-08-21 18:50:10.3258;TRACE-2.5.0.5550;Rubberduck.Common.LogLevelHelper;
	Rubberduck version 2.5.0.5550 loading:
	Operating System: Microsoft Windows NT 6.2.9200.0 x64
	Host Product: Visual Basic x86
	Host Version: 6.00.9782
	Host Executable: VB6.EXE;
[RubberduckLog-5550.txt](https://github.com/rubberduck-vba/Rubberduck/files/5110143/RubberduckLog-5550.txt)

**Comment by retailcoder** [comment]
The stack trace is pointing to a throwing property getter in the VBE interop wrappers:

```
2020-08-21 18:50:51.7214;ERROR-2.5.0.5550;Rubberduck.Parsing.VBA.ParseCoordinator;Unexpected exception thrown in parsing run. (thread 10).;System.Runtime.InteropServices.COMException (0x800AEA9D): Ausnahme von HRESULT: 0x800AEA9D
   bei Microsoft.Vbe.Interop.VB6._VBComponent.get_Designer()
   bei Rubberduck.VBEditor.SafeComWrappers.VB6.VBComponent.get_HasDesigner() in C:\projects\rubberduck\Rubberduck.VBEditor.VB6\SafeComWrappers\VB\VBComponent.cs:Zeile 114.
   bei Rubberduck.VBEditor.SafeComWrappers.VB6.VBComponent.ContentHash() in C:\projects\rubberduck\Rubberduck.VBEditor.VB6\SafeComWrappers\VB\VBComponent.cs:Zeile 188.
   bei Rubberduck.Parsing.VBA.RubberduckParserState.SaveContentHash(QualifiedModuleName module) in C:\projects\rubberduck\Rubberduck.Parsing\VBA\RubberduckParserState.cs:Zeile 864.
   bei Rubberduck.Parsing.VBA.Parsing.ParseRunnerBase.SaveModuleParseResultsOnState(QualifiedModuleName module, ModuleParseResults results, CancellationToken token) in C:\projects\rubberduck\Rubberduck.Parsing\VBA\Parsing\ParseRunnerBase.cs:Zeile 94.
   bei Rubberduck.Parsing.VBA.Parsing.ParseRunnerBase.SaveModuleParseResultsOnState(IReadOnlyCollection`1 parseResults, CancellationToken token) in C:\projects\rubberduck\Rubberduck.Parsing\VBA\Parsing\ParseRunnerBase.cs:Zeile 83.
   bei Rubberduck.Parsing.VBA.Parsing.ParseRunnerBase.ParseModules(IReadOnlyCollection`1 modules, CancellationToken token) in C:\projects\rubberduck\Rubberduck.Parsing\VBA\Parsing\ParseRunnerBase.cs:Zeile 42.
   bei Rubberduck.Parsing.VBA.ParsingStageService.ParseModules(IReadOnlyCollection`1 modulesToParse, CancellationToken token) in C:\projects\rubberduck\Rubberduck.Parsing\VBA\ParsingStageService.cs:Zeile 74.
   bei Rubberduck.Parsing.VBA.ParseCoordinator.ExecuteCommonParseActivities(IReadOnlyCollection`1 toParse, IReadOnlyCollection`1 toReresolveReferencesInput, IReadOnlyCollection`1 newProjectIds, CancellationToken token) in C:\projects\rubberduck\Rubberduck.Parsing\VBA\ParseCoordinator.cs:Zeile 284.
   bei Rubberduck.Parsing.VBA.ParseCoordinator.ParseAllInternal(Object requestor, CancellationToken token) in C:\projects\rubberduck\Rubberduck.Parsing\VBA\ParseCoordinator.cs:Zeile 566.
   bei Rubberduck.Parsing.VBA.ParseCoordinator.ParseAll(Object requestor) in C:\projects\rubberduck\Rubberduck.Parsing\VBA\ParseCoordinator.cs:Zeile 471.
```

Trying something... making `HasDesigner` return `false` when the COM object throws.
