### ISSUE TITLE
SmartIndenter: How do we go about it?

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#558]
Let's brainstorm a bit here. We have the source code for a COM add-in written in VB6, and we're planning to integrate it into our code base.

Obviously we won't be able to compile the VB6 code, so we have to port it to .net..

 - Option 1: Add a new VB.NET project to the solution, like, `Rubberduck.SmartIndenter`, import the VB6 modules, and tweak them to get the project to build against the .net compiler. Then tweak it to expose its functionality to the rest of Rubberduck.
 - Option 2: Add a new C# project to the solution, like, `Rubberduck.SmartIndenter`, and proceed to rewrite the VB6 code in C#.

I would really prefer option 2 over option1, because it makes fewer languages in the repository. Besides the majority of the code in the indentation algorithm consists of simple string operations and calls into the VBIDE library, that would be pretty much identical whatever the language we pick.

Also, the source involves registry keys for storing the various options - should we keep them, or change that and store indentation settings in our configuration file, along with the rest of the Rubberduck options? Either way, we'll need to have an *Indentation* tab in the settings dialog.

I would like the indentation code to be unit-testable, so we shouldn't make it depend directly on the VBIDE library - perhaps inject it with an `IActiveCodePaneEditor` interface, and also expose a method that can indent any arbitrary string, so that things like the *Extract Method* preview box can show indented code.

Thoughts?

**Comment by Hosch250** [comment]
I would like to have it be in C# too, but learning VB.NET can't be *that* hard.

**Comment by PetLahev** [comment]
How large is the VB6 code? You will spend some time even on the VB6-VB.NET conversion anyway so I'd also prefer C#.
Unit testing  :thumbsup::thumbsup::thumbsup:

**Comment by ckuhn203** [comment]
I haven't looked very hard at the VB6 code. Personally, I agree with the sentiment that we should have as few languages as possible in the repo. Also, a simple port to VB.Net would leave a lot to be desired from the code. We would have to nearly rewrite it in .Net idioms anyway. I say we use it as a roadmap for writing the test cases and implementing the functionality in C#. 

I also vote for ditching the registry in preference of our XML config, but there's a catch. Currently, the config code lives in the UI project, which is the main program file. It depends on all the other projects. None of them rely on it. If we don't move the config code *somewhere* else, we'll have a circular dependency on our hands. I'm open to thoughts about how we can better structure the project. Do we create yet another project for the config, or put it into VBEditor and rename it "core"? Or... Option 3 that I haven't thought of?

**Comment by retailcoder** [comment]
I've created an `Indentation` branch off the current `Next` (despite the pending PR's), added a `SmartIndenter` folder under the `Rubberduck` project - the C# port shall live under the `Rubberduck.SmartIndenter` namespace.

I excluded the compiled binaries, .frx and .vbw files, and added the VB6 source code under that folder, in a `VB6` subfolder (since that's non-compiled text files, `Rubberduck.SmartIndenter.VB6` isn't a namespace).

Not everything will need to be ported to C#, and some things will simply be done differently. For example, SmartIndenter is storing its options/settings in the Windows registry - Rubberduck is using an XML configuration file; let's add an "Indentation" tab to the settings dialog to include all the SmartIndenter options, and serialize these settings into `rubberduck.config` along with the rest of RD options.

The code we'll want to focus on, is mainly located in `modIndentRoutine.bas`; we will want to expose an API for the rest of Rubberduck to be able to indent any arbitrary string (e.g. the "Extract Method" refactoring preview), and we'll want to constructor-inject dependencies, and limit direct dependencies on the VBIDE API, because we'll want to write a bunch of unit tests for that feature, so the C# code has to be unit-testable.

**Comment by retailcoder** [comment]
C# rewrite is under way.

**Comment by ThunderFrame** [comment]
I don't have SmartIndenter or RubberDuck on my current PC, but I seem to recall there being an indentation bug in SmartIndenter, around the indentation of keywords that are used as Type elements

If you're integrating SmartIndenter, and working on lexing, then you might want to check this code...
```
Option Explicit

Public Type Test

  'This list is not complete

  Rem As Variant 'This compiles as a comment
  
  'Scope Declaration\use
  Private As Variant
  Public As Variant
  Friend As Variant
  Global As Variant
  Static As Variant
  'Me as Variant 'This doesn't compile
  
  'Declaration
  Sub As Variant
  Function As Variant
  Property As Variant
  Get As Variant
  Let As Variant
  Set As Variant
  Dim As Variant
  Const As Variant
  Redim As Variant
  Declare As Variant
  Enum As Variant
  Type As Variant
  New As Variant
  As As Variant
  Class As Variant
  ByVal As Variant
  ByRef As Variant
  Optional As Variant
  ParamArray As Variant
  WithEvents As Variant
  Event As Variant
  Implements As Variant
  PtrSafe As Variant
  Erase As Variant
  
  'Compiler Constants
  Win16 As Variant: Win32 As Variant: win64 As Variant
  Vba6 As Variant: Vba7 As Variant
  Mac As Variant
  
  'Options
  Option As Variant
  Explicit As Variant
  Base As Variant
  Compare As Variant
  Binary As Variant
  Text As Variant
  Module As Variant
  Database As Variant 'For Access
  
  'File Ops
  Open As Variant
  Close As Variant
  Dir As Variant
  Put As Variant
  '...
  
  'Conditions
  If As Variant
  Else As Variant
  ElseIf As Variant
  End As Variant
  Select As Variant
  Case As Variant
  
  'Code flow
  On As Variant
  Error As Variant
  Resume As Variant
  Goto As Variant
  Call As Variant
  Stop As Variant
  GoSub As Variant
  Return As Variant
  Eval As Variant 'MSAccess function

  'Loops
  Do As Variant
  Loop As Variant
  Until As Variant
  While As Variant
  Wend As Variant
  For As Variant
  Each As Variant
  Next As Variant
  Step As Variant
  
  'Functions/types/statements
  Date As Date
  Time As Date
  True As Boolean
  False As Boolean
  String As String
  'String() As String 'This doesn't compile
  aString() As String
  Space() As String
  Now() As String
  Timer As String
  Variant As Variant
  GetObject As Variant
  CreateObject As Variant
  Execute As Variant
  VBA As Variant
  ActiveWorkbook As Variant
  MsgBox(1) As Variant
  Shell(1) As Variant
  
  'Debug
  Debug As Variant
  Assert As Variant
  Print As Variant
  
End Type
```

**Comment by ckuhn203** [comment]
Thanks for the heads up @ThunderFrame!
