### ISSUE TITLE
False positive for default member inspection

### ISSUE THREAD

**Issue by bclothier** [rubberduck-vba/Rubberduck#5581]
Given the code:

```
Public Sub x()
    Debug.Print "Done validating the configuration at " & Now()
End Sub
```

This yields an inspection:

```
Error: The expression 'Now()' requires a default member access, but the type 'Variant' does not have a suitable default member.
```

Note that if `Now()` is changed to `Now`, the inspection disappears.

**Comment by MDoerner** [comment]
I will have to look into this. This result should never be returned for `Variant`, apart from the fact that this is not a default member access.
