### ISSUE TITLE
Refactor>Rename should preserve bookmarks and breakpoints

### ISSUE THREAD

**Issue by IvenBach** [rubberduck-vba/Rubberduck#5582]
**Rubberduck version information**
Version 2.5.0.20232
OS: Microsoft Windows NT 10.0.18362.0, x64
Host Product: Microsoft Office 2016 x64
Host Version: 16.0.4978.1000
Host Executable: EXCEL.EXE

**Description**
As part of renaming the entire modules contents are rewritten. This unintentionally removes bookmarks and breakpoints from modules as part of the rewrite process.

**To Reproduce**
1. Create a module with a variable.
2. Place a bookmark and breakpoint (Hotkey: `F9`) within the module.
3. Rename the variable
4. Find bookmarks and breakpoints are gone

**Expected behavior**
Store the location of bookmarks and breakpoints so they are restored/preserved as part of the renaming process.

**Comment by retailcoder** [comment]
IIRC bookmarks can be toggled via the VBIDE API, but there is no way to iterate them; breakpoints are just nowhere, we'd have to tap into the unknown depths of the VBE's innards to be able to do this.

Honestly I don't care for bookmarks at all, our TODO markers are much more useful IMO (I don't even recall the last time I toggled a bookmark, must be >15 years ago); being able to programmatically iterate, toggle, and restore breakpoints would be very nice indeed, but this is far, far from a simple thing to do.

**Comment by mansellan** [comment]
AFAICT, the only way to do this would be to able to decipher the contents of the working memory of the host process, specifically that which relates to the VBIDE. The good news is that it probably wouldn't vary from host to host or version to version (given the lack of change to the VBIDE over the years). The bad news is that it's completely undocumented (outside of MS at least), so would be a full-on reverse-engineering process.

**Comment by daFreeMan** [comment]
As much as I'd love to see this implemented, these arguments (and the ones in chat) all sound familiar and why I didn't put in a request for this quite a while ago... 😢

**Comment by Vogel612** [comment]
Considering the obvious hurdles to implementing this, not least the hurdle of basically reverse-engineering the debugger of the VBE I think we should consider this out of scope.

**Comment by retailcoder** [comment]
I wouldn't say *out of scope* because if a PR appeared with a fix, we'd probably consider it in-scope then, ...but yeah, rather unlikely 😢

**Comment by mansellan** [comment]
That said, perhaps there's room for a Research repository, where extremely low-level technical info could be stored and shared. Some of this is scattered across the internet (but increasingly disappearing), some could come from primary research. I'd certainly be interested in contributing.
