### ISSUE TITLE
Class not registered error while running tests

### ISSUE THREAD

**Issue by BluejacketSoftware** [rubberduck-vba/Rubberduck#5600]
**Rubberduck version information**
The info below can be copy-paste-completed from the first lines of Rubberduck's log or the About box:

    Rubberduck version [2.5.1.5585]
    Operating System: [Win10 6.2.9200.0]
    Host Product: [VB6]
    Host Version: [6.00.9782]
    Host Executable: [VB6.EXE]

**Description**
Trying to restore an object from a PropertyBag.ReadProperty("sut") causes runtime error 713: Class not registered.  Looking for object with CLSID {changes every time}

**To Reproduce**
1. Create unit test
2. Persist object to disk using PropertyBag.WriteProperty("sut", sut)
3. Try to rehydrate the object using PropertyBag.ReadProperty("sut")

**Expected behavior**
All other tests pass including writing to a custom XMLPropertyBag that persists the object as an xml file

**Screenshots**

**Logfile**
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/5397278/RubberduckLog.txt)

**Additional context**

**Comment by BluejacketSoftware** [comment]
It seems that this was due to a conflict with SimplyVBUnit unit test suite.  Loading just my dll project and using the RD Test runner without loading the whole project group that contains my dll project and SimplyVBUnit works as advertised.

**Comment by bclothier** [comment]
Thanks for reporting! This is a known issue, something to do with how .NET handles COM interop types from different assemblies. For posterity, linking issue #3837 and #4041.
