### ISSUE TITLE
Can RD exclude a project from parse?

### ISSUE THREAD

**Issue by BluejacketSoftware** [rubberduck-vba/Rubberduck#5601]
I'm working on a very large VB6 project group and need RD's Code Explorer (folders) to keep me from losing my sanity but there's one project (a unit test project) that won't parse - loads of test classes that refuse to parse.  The unit test suite runs as expected but RD is not happy with it.  I need to continue to use the test suite but would need RD to ignore trying to parse it and go ahead and parse the other projects in the group.  Is that possible?  Can I use the '@IgnoreModule annotation?  I'm fine with using sed to jam annotations in the files from the command line if that would do the job...

**Comment by Vogel612** [comment]
Compare #3041, #1520, #2006 as well as #1966.

This is a long-standing issue in some way, jamming annotations in the files you want ignored is definitely a feasible workaround for VB6.

**Comment by retailcoder** [comment]
Curious about the parser error (and the code around it), since I'm not sure what legal VB6/VBA code we cannot parse.

Can you repro the parser error with a small example?

**Comment by retailcoder** [comment]
Can the test project be locked? We're not parsing source code for locked projects.

**Comment by MDoerner** [comment]
Could you provide a log, on error level, say, so that we can see what is causing our parser to fail? If the information disclosed in the log is too sensitive, can you reproduce the problem with an artificial example?

Jamming the project with `@IgnoreModule` annotations will not help at all. This only affects the inspections and not the parser itself. Currently, the only way to make RD not parse a project is to lock the project, i.e. to _protect_ it with a password and to not enter that password in the session.

**Comment by mansellan** [comment]
It would indeed be very helpful see a log - the RD grammar is pretty mature now, it's been a while since we've seen a parse error. It's possible that some nuance specific to VB6 has been overlooked, as VB6 is a more recent addition to RD.

**Comment by BluejacketSoftware** [comment]
Unfortunately the library that includes the code that won't parse is a ball of yarn that won't even compile now so my suspicion is that RD won't be able to touch it until it will at least compile.  I'll work on that problem.  If I can get the project group to compile all the projects I'll send a link to a Github repo where you can download it.  I'm rather convinced that this is (at least for now) not an RD problem but a compile problem.  I'll close this issue and if I make forward progress with the vbg, I'll open a new issue if RD still won't parse. Thanks for the assist all!

**Comment by BluejacketSoftware** [comment]
Confirmed with the library developer, he doesn't compile the unit test project so I'm blaming the project and not RD.  I am going to lobby very strongly that #5604 get merged very soon - I really need that feature!

**Comment by bclothier** [comment]
Just to set expectations --

1) I expect that we will merge #5604 very soonish, usually we want to take a week or so to give contributors time to review the PR.
2) Even so, it won't be on the stable branch for a while. I hope we'll release a new stable version but that probably won't happen until next month.
3) If you really do not want to wait for either, you can actually get [the #5604 build here](https://ci.appveyor.com/api/buildjobs/6r5bddg65un48klf/artifacts/Rubberduck.Deployment%2FInnoSetup%2FInstallers%2FRubberduck.Setup.2.5.1.5622-pre.exe).

**Comment by BluejacketSoftware** [comment]
I'm totally fine with bleeding edge versions - MANY THANKS for sending the link.  I assume this mean when I install this build I should refrain from any newer builds until #5604 gets officially incorporated.

**Comment by bclothier** [comment]
Correct, if you are normally installing pre-release versions, you would need to avoid updating until #5604 is merged (which wouldn't be that much longer).
