### ISSUE TITLE
Can RD's Encapsulate Field be customized?

### ISSUE THREAD

**Issue by BluejacketSoftware** [rubberduck-vba/Rubberduck#5609]
Right now it creates private fields such as `something_1` and a public property such as `Something` which is okay - not terrible.  But it sure would be nice if the Preview window was writable so it could be tweaked before posting.  

Also, most of the time I select the "Create private this type" to hide the private fields so in that case, renaming the fields is redundant anyway.  Any chance this option could just leave the field names alone?

Also, the public properties it creates capture the incoming value as `RHS` which then immediately fails the `Use meaningful names` inspection.  Can we change `RHS` to `value` or something?  I don't want to turn off the inspection or clutter source with ignore attributes.  I'm not morally opposed to `RHS` so an adjustment to the inspection to ignore that would do also (IMHO) 

And while you're add it - the Let / Set methods that it creates don't specify `ByRef` or `ByVal` so then the inspection `Parameter can be passed by...` gets tripped.

**Comment by BZngr** [comment]
Starting with `Public test As Long` and Encapsulating using a Private Type...the results I get are:
```
Private Type TModule1
    Test As Long
End Type

Private this As TModule1

Public Property Get Test() As Long
    Test = this.Test
End Property

Public Property Let Test(ByVal RHS As Long)
    this.Test = RHS
End Property
```

Can you share more about your use case?  Based on the above, a `ByVal` parameter mechanism is provided in the Let method and the field identifier is left as-is (though capitalized to match the Property).  

Your point regarding `RHS` is well taken.  Certainly that is something we can look into addressing.

**Comment by BluejacketSoftware** [comment]
Sure, here's a **before**

`'@Folder("Web.Authenticators")
''
' Digest Authenticator v3.0.8
' (c) Tim Hall - https://github.com/VBA-tools/VBA-Web
'
' Custom IWebAuthenticator for Digest Authentication
' http://en.wikipedia.org/wiki/Digest_access_authentication
'
' @class DigestAuthenticator
' @implements IWebAuthenticator v4.*
' @author tim.hall.engr@gmail.com
' @license MIT (http://www.opensource.org/licenses/mit-license.php)
'' ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ '
Implements IWebAuthenticator
Option Explicit

' --------------------------------------------- '
' Constants and Private Variables
' --------------------------------------------- '

Private Const auth_Qop As String = "auth"
Private auth_pClientNonce As String

' --------------------------------------------- '
' Properties
' --------------------------------------------- '

Public Username As String
Public Password As String

Public Realm As String
Public ServerNonce As String
Public RequestCount As Long
Public Opaque As String

Public Property Get ClientNonce() As String
    If auth_pClientNonce = vbNullString Then
        auth_pClientNonce = WebHelpers.CreateNonce
    End If
    ClientNonce = auth_pClientNonce
End Property
Public Property Let ClientNonce(Value As String)
    auth_pClientNonce = Value
End Property

Public Property Get IsAuthenticated() As Boolean
    If ServerNonce <> vbNullString Then
        IsAuthenticated = True
    End If
End Property

' ============================================= '
' Public Methods
' ============================================= '

''
' Setup authenticator
'
' @param {String} Username
' @param {String} Password
''
Public Sub Setup(Username As String, Password As String)
    Me.Username = Username
    Me.Password = Password
End Sub

''
' Hook for taking action before a request is executed
'
' @param {WebClient} Client The client that is about to execute the request
' @param in|out {WebRequest} Request The request about to be executed
''
Private Sub IWebAuthenticator_BeforeExecute(ByVal Client As WebClient, ByRef Request As WebRequest)
    If Me.IsAuthenticated Then
        Me.RequestCount = Me.RequestCount + 1
        Request.SetHeader "Authorization", CreateHeader(Client, Request)
    End If
End Sub

''
' Hook for taking action after request has been executed
'
' @param {WebClient} Client The client that executed request
' @param {WebRequest} Request The request that was just executed
' @param in|out {WebResponse} Response to request
''
Private Sub IWebAuthenticator_AfterExecute(ByVal Client As WebClient, ByVal Request As WebRequest, ByVal Response As WebResponse)
    If Response.StatusCode = 401 And Not Me.IsAuthenticated Then
        WebHelpers.LogDebug "Extract Authenticate and retry 401 request " & Client.GetFullUrl(Request), "Digest.AfterExecute"
        ExtractAuthenticateInformation Response
        
        Request.SetHeader "Authorization", CreateHeader(Client, Request)
        Response.Update Client.Execute(Request)
    End If
End Sub

''
' Hook for updating http before send
'
' @param {WebClient} Client
' @param {WebRequest} Request
' @param in|out {WinHttpRequest} Http
''
Private Sub IWebAuthenticator_PrepareHttp(ByVal Client As WebClient, ByVal Request As WebRequest, ByVal Http As Object)
    ' e.g. Update option, headers, etc.
End Sub

''
' Hook for updating cURL before send
'
' @param {WebClient} Client
' @param {WebRequest} Request
' @param in|out {String} Curl
''
Private Sub IWebAuthenticator_PrepareCurl(ByVal Client As WebClient, ByVal Request As WebRequest, ByRef Curl As String)
    ' http://curl.haxx.se/docs/manpage.html#--digest
    Curl = Curl & " --digest --user " & WebHelpers.PrepareTextForShell(Me.Username) & ":" & WebHelpers.PrepareTextForShell(Me.Password)
End Sub

''
' Create digest header for given Client and Request
'
' @internal
' @param {WebClient} Client
' @param {WebRequest} Request
' @return {String}
''
Public Function CreateHeader(Client As WebClient, Request As WebRequest) As String
    Dim auth_Uri As String
    auth_Uri = WebHelpers.GetUrlParts(Client.GetFullUrl(Request))("Path")

    CreateHeader = "Digest " & _
        "username=""" & Me.Username & """, " & _
        "realm=""" & Me.Realm & """, " & _
        "nonce=""" & Me.ServerNonce & """, " & _
        "uri=""" & auth_Uri & """, " & _
        "qop=" & auth_Qop & ", " & _
        "nc=" & web_FormattedRequestCount & ", " & _
        "cnonce=""" & Me.ClientNonce & """, " & _
        "response=""" & web_CalculateResponse(Client, Request) & """, " & _
        "opaque=""" & Me.Opaque & """"
        
    WebHelpers.LogDebug CreateHeader, "DigestAuthenticator.CreateHeader"
End Function

''
' Extract authentication information from 401 response headers
'
' @internal
' @param {WebResponse} Response
''
Public Sub ExtractAuthenticateInformation(Response As WebResponse)
    Dim auth_Header As String
    Dim web_CrLf As String
    
    auth_Header = WebHelpers.FindInKeyValues(Response.Headers, "WWW-Authenticate")
    web_CrLf = VBA.Chr$(13) & VBA.Chr$(10)
    
    If auth_Header <> vbNullString And VBA.Left$(auth_Header, 6) = "Digest" Then
        Dim auth_Lines As Variant
        auth_Lines = VBA.Split(VBA.Mid$(auth_Header, 7), web_CrLf)
        
        Dim auth_i As Integer
        Dim auth_Key As String
        Dim auth_Value As String
        For auth_i = LBound(auth_Lines) To UBound(auth_Lines)
            auth_Key = VBA.LCase$(VBA.Trim$(VBA.Mid$(auth_Lines(auth_i), 1, VBA.InStr(1, auth_Lines(auth_i), "=") - 1)))
            auth_Value = VBA.Trim$(VBA.Mid$(auth_Lines(auth_i), VBA.InStr(1, auth_Lines(auth_i), "=") + 1, VBA.Len(auth_Lines(auth_i))))
            
            ' Remove quotes and trailing comma
            auth_Value = VBA.Replace(auth_Value, """", vbNullString)
            If VBA.Right$(auth_Value, 1) = "," Then
                auth_Value = VBA.Left$(auth_Value, VBA.Len(auth_Value) - 1)
            End If
            
            ' Find realm, nonce, and opaque
            If auth_Key = "realm" Then Me.Realm = auth_Value
            If auth_Key = "nonce" Then Me.ServerNonce = auth_Value
            If auth_Key = "opaque" Then Me.Opaque = auth_Value
        Next auth_i
        
        WebHelpers.LogDebug "realm=" & Me.Realm & ", nonce=" & Me.ServerNonce & ", opaque=" & Me.Opaque, "DigestAuthenticator.ExtractAuthenticateInformation"
    End If
End Sub

' ============================================= '
' Private Methods
' ============================================= '

''
' Calculate digest response fro given Client and Request
'
' @internal
' @param {WebClient} Client
' @param {WebRequest} Request
' @return {String}
''
Private Function web_CalculateResponse(web_Client As WebClient, web_Request As WebRequest) As String
    Dim auth_HA1 As String
    Dim auth_HA2 As String
    Dim auth_Uri As String
    
    auth_Uri = WebHelpers.GetUrlParts(web_Client.GetFullUrl(web_Request))("Path")
    auth_HA1 = web_CalculateHA1
    auth_HA2 = web_CalculateHA2(WebHelpers.MethodToName(web_Request.Method), auth_Uri)
    
    web_CalculateResponse = WebHelpers.MD5(auth_HA1 & ":" & Me.ServerNonce & ":" & web_FormattedRequestCount & ":" & Me.ClientNonce & ":" & auth_Qop & ":" & auth_HA2)
End Function

''
' Calculate HA1 portion of digest response
'
' @internal
' @return {String}
''
Private Function web_CalculateHA1() As String
    web_CalculateHA1 = WebHelpers.MD5(Me.Username & ":" & Me.Realm & ":" & Me.Password)
End Function

''
' Calculate HA1 portion of digest response
'
' @internal
' @return {String}
''
Private Function web_CalculateHA2(web_Method As String, web_Uri As String) As String
    web_CalculateHA2 = WebHelpers.MD5(web_Method & ":" & web_Uri)
End Function

''
' Pad request count to 8 places
'
' @internal
' @return {String}
''
Private Function web_FormattedRequestCount() As String
    web_FormattedRequestCount = Right("00000000" & Me.RequestCount, 8)
End Function
`

**And After**
`'@Folder("Web.Authenticators")
''
' Digest Authenticator v3.0.8
' (c) Tim Hall - https://github.com/VBA-tools/VBA-Web
'
' Custom IWebAuthenticator for Digest Authentication
' http://en.wikipedia.org/wiki/Digest_access_authentication
'
' @class DigestAuthenticator
' @implements IWebAuthenticator v4.*
' @author tim.hall.engr@gmail.com
' @license MIT (http://www.opensource.org/licenses/mit-license.php)
'' ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ '
Implements IWebAuthenticator
Option Explicit

' --------------------------------------------- '
' Constants and Private Variables
' --------------------------------------------- '

Private Const auth_Qop As String = "auth"
Private Type TDigestAuthenticator
    Auth_pClientNonce As String
    Username_1 As String
    Password_1 As String
    Realm As String
    ServerNonce As String
    RequestCount As Long
    Opaque As String
End Type

Private this As TDigestAuthenticator

Public Property Get Auth_pClientNonce() As String
    Auth_pClientNonce = this.Auth_pClientNonce
End Property

Public Property Let Auth_pClientNonce(ByVal RHS As String)
    this.Auth_pClientNonce = RHS
End Property

Public Property Get Username_1() As String
    Username_1 = this.Username_1
End Property

Public Property Let Username_1(ByVal RHS As String)
    this.Username_1 = RHS
End Property

Public Property Get Password_1() As String
    Password_1 = this.Password_1
End Property

Public Property Let Password_1(ByVal RHS As String)
    this.Password_1 = RHS
End Property

Public Property Get Realm() As String
    Realm = this.Realm
End Property

Public Property Let Realm(ByVal RHS As String)
    this.Realm = RHS
End Property

Public Property Get ServerNonce() As String
    ServerNonce = this.ServerNonce
End Property

Public Property Let ServerNonce(ByVal RHS As String)
    this.ServerNonce = RHS
End Property

Public Property Get RequestCount() As Long
    RequestCount = this.RequestCount
End Property

Public Property Let RequestCount(ByVal RHS As Long)
    this.RequestCount = RHS
End Property

Public Property Get Opaque() As String
    Opaque = this.Opaque
End Property

Public Property Let Opaque(ByVal RHS As String)
    this.Opaque = RHS
End Property

Public Property Get ClientNonce() As String
    If Auth_pClientNonce = vbNullString Then
        Auth_pClientNonce = WebHelpers.CreateNonce
    End If
    ClientNonce = Auth_pClientNonce
End Property
Public Property Let ClientNonce(Value As String)
    Auth_pClientNonce = Value
End Property

Public Property Get IsAuthenticated() As Boolean
    If ServerNonce <> vbNullString Then
        IsAuthenticated = True
    End If
End Property

' ============================================= '
' Public Methods
' ============================================= '

''
' Setup authenticator
'
' @param {String} Username
' @param {String} Password
''
Public Sub Setup(Username As String, Password As String)
    Me.Username_1 = Username
    Me.Password_1 = Password
End Sub

''
' Hook for taking action before a request is executed
'
' @param {WebClient} Client The client that is about to execute the request
' @param in|out {WebRequest} Request The request about to be executed
''
Private Sub IWebAuthenticator_BeforeExecute(ByVal Client As WebClient, ByRef Request As WebRequest)
    If Me.IsAuthenticated Then
        Me.RequestCount = Me.RequestCount + 1
        Request.SetHeader "Authorization", CreateHeader(Client, Request)
    End If
End Sub

''
' Hook for taking action after request has been executed
'
' @param {WebClient} Client The client that executed request
' @param {WebRequest} Request The request that was just executed
' @param in|out {WebResponse} Response to request
''
Private Sub IWebAuthenticator_AfterExecute(ByVal Client As WebClient, ByVal Request As WebRequest, ByVal Response As WebResponse)
    If Response.StatusCode = 401 And Not Me.IsAuthenticated Then
        WebHelpers.LogDebug "Extract Authenticate and retry 401 request " & Client.GetFullUrl(Request), "Digest.AfterExecute"
        ExtractAuthenticateInformation Response
        
        Request.SetHeader "Authorization", CreateHeader(Client, Request)
        Response.Update Client.Execute(Request)
    End If
End Sub

''
' Hook for updating http before send
'
' @param {WebClient} Client
' @param {WebRequest} Request
' @param in|out {WinHttpRequest} Http
''
Private Sub IWebAuthenticator_PrepareHttp(ByVal Client As WebClient, ByVal Request As WebRequest, ByVal Http As Object)
    ' e.g. Update option, headers, etc.
End Sub

''
' Hook for updating cURL before send
'
' @param {WebClient} Client
' @param {WebRequest} Request
' @param in|out {String} Curl
''
Private Sub IWebAuthenticator_PrepareCurl(ByVal Client As WebClient, ByVal Request As WebRequest, ByRef Curl As String)
    ' http://curl.haxx.se/docs/manpage.html#--digest
    Curl = Curl & " --digest --user " & WebHelpers.PrepareTextForShell(Me.Username_1) & ":" & WebHelpers.PrepareTextForShell(Me.Password_1)
End Sub

''
' Create digest header for given Client and Request
'
' @internal
' @param {WebClient} Client
' @param {WebRequest} Request
' @return {String}
''
Public Function CreateHeader(Client As WebClient, Request As WebRequest) As String
    Dim auth_Uri As String
    auth_Uri = WebHelpers.GetUrlParts(Client.GetFullUrl(Request))("Path")

    CreateHeader = "Digest " & _
        "username=""" & Me.Username_1 & """, " & _
        "realm=""" & Me.Realm & """, " & _
        "nonce=""" & Me.ServerNonce & """, " & _
        "uri=""" & auth_Uri & """, " & _
        "qop=" & auth_Qop & ", " & _
        "nc=" & web_FormattedRequestCount & ", " & _
        "cnonce=""" & Me.ClientNonce & """, " & _
        "response=""" & web_CalculateResponse(Client, Request) & """, " & _
        "opaque=""" & Me.Opaque & """"
        
    WebHelpers.LogDebug CreateHeader, "DigestAuthenticator.CreateHeader"
End Function

''
' Extract authentication information from 401 response headers
'
' @internal
' @param {WebResponse} Response
''
Public Sub ExtractAuthenticateInformation(Response As WebResponse)
    Dim auth_Header As String
    Dim web_CrLf As String
    
    auth_Header = WebHelpers.FindInKeyValues(Response.Headers, "WWW-Authenticate")
    web_CrLf = VBA.Chr$(13) & VBA.Chr$(10)
    
    If auth_Header <> vbNullString And VBA.Left$(auth_Header, 6) = "Digest" Then
        Dim auth_Lines As Variant
        auth_Lines = VBA.Split(VBA.Mid$(auth_Header, 7), web_CrLf)
        
        Dim auth_i As Integer
        Dim auth_Key As String
        Dim auth_Value As String
        For auth_i = LBound(auth_Lines) To UBound(auth_Lines)
            auth_Key = VBA.LCase$(VBA.Trim$(VBA.Mid$(auth_Lines(auth_i), 1, VBA.InStr(1, auth_Lines(auth_i), "=") - 1)))
            auth_Value = VBA.Trim$(VBA.Mid$(auth_Lines(auth_i), VBA.InStr(1, auth_Lines(auth_i), "=") + 1, VBA.Len(auth_Lines(auth_i))))
            
            ' Remove quotes and trailing comma
            auth_Value = VBA.Replace(auth_Value, """", vbNullString)
            If VBA.Right$(auth_Value, 1) = "," Then
                auth_Value = VBA.Left$(auth_Value, VBA.Len(auth_Value) - 1)
            End If
            
            ' Find realm, nonce, and opaque
            If auth_Key = "realm" Then Me.Realm = auth_Value
            If auth_Key = "nonce" Then Me.ServerNonce = auth_Value
            If auth_Key = "opaque" Then Me.Opaque = auth_Value
        Next auth_i
        
        WebHelpers.LogDebug "realm=" & Me.Realm & ", nonce=" & Me.ServerNonce & ", opaque=" & Me.Opaque, "DigestAuthenticator.ExtractAuthenticateInformation"
    End If
End Sub

' ============================================= '
' Private Methods
' ============================================= '

''
' Calculate digest response fro given Client and Request
'
' @internal
' @param {WebClient} Client
' @param {WebRequest} Request
' @return {String}
''
Private Function web_CalculateResponse(web_Client As WebClient, web_Request As WebRequest) As String
    Dim auth_HA1 As String
    Dim auth_HA2 As String
    Dim auth_Uri As String
    
    auth_Uri = WebHelpers.GetUrlParts(web_Client.GetFullUrl(web_Request))("Path")
    auth_HA1 = web_CalculateHA1
    auth_HA2 = web_CalculateHA2(WebHelpers.MethodToName(web_Request.Method), auth_Uri)
    
    web_CalculateResponse = WebHelpers.MD5(auth_HA1 & ":" & Me.ServerNonce & ":" & web_FormattedRequestCount & ":" & Me.ClientNonce & ":" & auth_Qop & ":" & auth_HA2)
End Function

''
' Calculate HA1 portion of digest response
'
' @internal
' @return {String}
''
Private Function web_CalculateHA1() As String
    web_CalculateHA1 = WebHelpers.MD5(Me.Username_1 & ":" & Me.Realm & ":" & Me.Password_1)
End Function

''
' Calculate HA1 portion of digest response
'
' @internal
' @return {String}
''
Private Function web_CalculateHA2(web_Method As String, web_Uri As String) As String
    web_CalculateHA2 = WebHelpers.MD5(web_Method & ":" & web_Uri)
End Function

''
' Pad request count to 8 places
'
' @internal
' @return {String}
''
Private Function web_FormattedRequestCount() As String
    web_FormattedRequestCount = Right("00000000" & Me.RequestCount, 8)
End Function


`
![image](https://user-images.githubusercontent.com/11149818/97377904-4f480d00-187e-11eb-8f6b-a1ea17e60282.png)

**Comment by BluejacketSoftware** [comment]
**Before:**
`' --------------------------------------------- '
' Properties
' --------------------------------------------- '

Public Username As String
Public Password As String

Public Realm As String
Public ServerNonce As String
Public RequestCount As Long
Public Opaque As String

Public Property Get ClientNonce() As String
    If auth_pClientNonce = vbNullString Then
        auth_pClientNonce = WebHelpers.CreateNonce
    End If
    ClientNonce = auth_pClientNonce
End Property
Public Property Let ClientNonce(Value As String)
    auth_pClientNonce = Value
End Property

Public Property Get IsAuthenticated() As Boolean
    If ServerNonce <> vbNullString Then
        IsAuthenticated = True
    End If
End Property`

**After**
`' --------------------------------------------- '
' Properties
' --------------------------------------------- '

Private Username_2 As String
Private Password_2 As String

Private realm_1 As String
Private serverNonce_1 As String
Private requestCount_1 As Long
Private opaque_1 As String

Public Property Get Username_1() As String
    Username_1 = Username_2
End Property

Public Property Let Username_1(ByVal RHS As String)
    Username_2 = RHS
End Property

Public Property Get Password_1() As String
    Password_1 = Password_2
End Property

Public Property Let Password_1(ByVal RHS As String)
    Password_2 = RHS
End Property

Public Property Get Realm() As String
    Realm = realm_1
End Property

Public Property Let Realm(ByVal RHS As String)
    realm_1 = RHS
End Property

Public Property Get ServerNonce() As String
    ServerNonce = serverNonce_1
End Property

Public Property Let ServerNonce(ByVal RHS As String)
    serverNonce_1 = RHS
End Property

Public Property Get RequestCount() As Long
    RequestCount = requestCount_1
End Property

Public Property Let RequestCount(ByVal RHS As Long)
    requestCount_1 = RHS
End Property

Public Property Get Opaque() As String
    Opaque = opaque_1
End Property

Public Property Let Opaque(ByVal RHS As String)
    opaque_1 = RHS
End Property

Public Property Get ClientNonce() As String
    If auth_pClientNonce = vbNullString Then
        auth_pClientNonce = WebHelpers.CreateNonce
    End If
    ClientNonce = auth_pClientNonce
End Property
Public Property Let ClientNonce(Value As String)
    auth_pClientNonce = Value
End Property

Public Property Get IsAuthenticated() As Boolean
    If ServerNonce <> vbNullString Then
        IsAuthenticated = True
    End If
End Property`

![image](https://user-images.githubusercontent.com/11149818/97378361-6f2c0080-187f-11eb-955f-363fc8774771.png)

**Comment by BluejacketSoftware** [comment]
This is the third time I tried to paste this correctly and I noticed something, RD isn't consistent when it renames the private variables.  Each time I ran through the process it gave different results.  Below is the most recent attempt.  Some names it did okay, others it added _1.  I also noticed that RD has now gone back to adding the ByRef again....

```
Public Username As String
Public Password As String

Public Realm As String
Public ServerNonce As String
Public RequestCount As Long
Public Opaque As String

Public Property Get ClientNonce() As String
    If auth_pClientNonce = "" Then
        auth_pClientNonce = WebHelpers.CreateNonce
    End If
    ClientNonce = auth_pClientNonce
End Property
Public Property Let ClientNonce(Value As String)
    auth_pClientNonce = Value
End Property

Public Property Get IsAuthenticated() As Boolean
    If ServerNonce <> "" Then
        IsAuthenticated = True
    End If
End Property
```
```
Private Type TDigestAuthenticator
    Username_1 As String
    Password_1 As String
    Realm As String
    ServerNonce As String
    RequestCount As Long
    Opaque As String
End Type

Private this As TDigestAuthenticator

Public Property Get Username_1() As String
    Username_1 = this.Username_1
End Property

Public Property Let Username_1(ByVal RHS As String)
    this.Username_1 = RHS
End Property

Public Property Get Password_1() As String
    Password_1 = this.Password_1
End Property

Public Property Let Password_1(ByVal RHS As String)
    this.Password_1 = RHS
End Property

Public Property Get Realm() As String
    Realm = this.Realm
End Property

Public Property Let Realm(ByVal RHS As String)
    this.Realm = RHS
End Property

Public Property Get ServerNonce() As String
    ServerNonce = this.ServerNonce
End Property

Public Property Let ServerNonce(ByVal RHS As String)
    this.ServerNonce = RHS
End Property

Public Property Get RequestCount() As Long
    RequestCount = this.RequestCount
End Property

Public Property Let RequestCount(ByVal RHS As Long)
    this.RequestCount = RHS
End Property

Public Property Get Opaque() As String
    Opaque = this.Opaque
End Property

Public Property Let Opaque(ByVal RHS As String)
    this.Opaque = RHS
End Property
```
![image](https://user-images.githubusercontent.com/11149818/97379308-c03cf400-1881-11eb-8785-eebe5ddf91f4.png)

**Comment by BluejacketSoftware** [comment]
More info:

When I try to override the field name it complains of a name conflict but there isn't any

![image](https://user-images.githubusercontent.com/11149818/97380136-a1d7f800-1883-11eb-9142-63c418fd91b8.png)

**Comment by BluejacketSoftware** [comment]
And with fields of type Variant, it creates both a Let and a Set but the Get is really a mess:

```
Public Property Get Scopes() As Variant
    Set Scopes = this.ScopesIf IsObject(this.Scopes) ThenElseIf IsObject(this.Scopes) ThenScopes = this.ScopesIf IsObject(this.Scopes) ThenEnd If
End Property

Public Property Let Scopes(ByVal RHS As Variant)
    this.Scopes = RHS
End Property

Public Property Set Scopes(ByVal RHS As Variant)
    Set this.Scopes = RHS
End Property
```

**Comment by BluejacketSoftware** [comment]
The name collision from earlier could be because I'm in VB6 working on private classes that have public fields.  RD might not be aware that each of the classes have their instancing set to 1-Private...

**Comment by BZngr** [comment]
Hmmm...I do not see a single `ByRef` Let statement in the provided code.

So, starting with your **Before** scenario 
```
Public Username As String
Public Password As String

Public Realm As String
Public ServerNonce As String
Public RequestCount As Long
Public Opaque As String

Public Property Get ClientNonce() As String
    If auth_pClientNonce = "" Then
        auth_pClientNonce = WebHelpers.CreateNonce
    End If
    ClientNonce = auth_pClientNonce
End Property
Public Property Let ClientNonce(Value As String)
    auth_pClientNonce = Value
End Property

Public Property Get IsAuthenticated() As Boolean
    If ServerNonce <> "" Then
        IsAuthenticated = True
    End If
End Property

```

and selecting 'All' as well as wrapping in a `Private Type`, I get the following:

```
Option Explicit

Private Type TDigestAuthenticator
    Username As String
    Password As String
    Realm As String
    ServerNonce As String
    RequestCount As Long
    Opaque As String
End Type

Private this As TDigestAuthenticator

Public Property Get Username() As String
    Username = this.Username
End Property

Public Property Let Username(ByVal RHS As String)
    this.Username = RHS
End Property

Public Property Get Password() As String
    Password = this.Password
End Property

Public Property Let Password(ByVal RHS As String)
    this.Password = RHS
End Property

Public Property Get Realm() As String
    Realm = this.Realm
End Property

Public Property Let Realm(ByVal RHS As String)
    this.Realm = RHS
End Property

Public Property Get ServerNonce() As String
    ServerNonce = this.ServerNonce
End Property

Public Property Let ServerNonce(ByVal RHS As String)
    this.ServerNonce = RHS
End Property

Public Property Get RequestCount() As Long
    RequestCount = this.RequestCount
End Property

Public Property Let RequestCount(ByVal RHS As Long)
    this.RequestCount = RHS
End Property

Public Property Get Opaque() As String
    Opaque = this.Opaque
End Property

Public Property Let Opaque(ByVal RHS As String)
    this.Opaque = RHS
End Property

Public Property Get ClientNonce() As String
    If auth_pClientNonce = vbNullString Then
        auth_pClientNonce = WebHelpers.CreateNonce
    End If
    ClientNonce = auth_pClientNonce
End Property
Public Property Let ClientNonce(Value As String)
    auth_pClientNonce = Value
End Property

Public Property Get IsAuthenticated() As Boolean
    If ServerNonce <> vbNullString Then
        IsAuthenticated = True
    End If
End Property
```
Not sure how `Username_1` and `Password_1` is getting introduced unless you are specifying editing Property names before running the refactoring.  Aside from that, it certainly looks like appropriate `ByVal` parameter mechanism are present in the generated code.

**Comment by BZngr** [comment]
The Get statements for the Variant type bears looking into.  It definitely looks like a bug.

**Comment by BluejacketSoftware** [comment]
Sorry, I meant ByVal not ByRef.  It's hit or miss if it includes them....

**Comment by BZngr** [comment]
Regarding the comments about a conflict...looks like a different module.  I would need to see the what's in the module to comment more.

Regarding the `ByVal`...I'm not seeing the 'misses' - can you point one out?

**Comment by BluejacketSoftware** [comment]
I think the Username_1 and Password_1 are are because there are public fields in other private modules in this project.  Could it be that RD is unaware of Instancing set to 1-Private?

**Comment by BluejacketSoftware** [comment]
It's a different class module for sure

**Comment by BluejacketSoftware** [comment]
> Regarding the comments about a conflict...looks like a different module. I would need to see the what's in the module to comment more.
> 
> Regarding the `ByVal`...I'm not seeing the 'misses' - can you point one out?

I'll catch one - I'm doing a lot of refactoring...

**Comment by BZngr** [comment]
Public fields in other private modules may be the cause of the identifer modification...another issue to look into.

**Comment by BluejacketSoftware** [comment]
Here's a link to the original code.  It's meant for VBA and I'm porting it to VB while cleaning it up.  Maybe you can grab it and then you'll have the whole picture.
[Github Repo](https://github.com/VBA-tools/VBA-Web)

**Comment by BluejacketSoftware** [comment]
But AFAIK, VBA doesn't know anything about Instancing so go figure...

**Comment by BZngr** [comment]
Thanks for the link.  Quickly looked for the code with the conflicts...but did not spot it.  Can you tell me the module name?

**Comment by BluejacketSoftware** [comment]
Sure, in the Authenticators folder there are a hand full of files that are all very similar (lots of copy/paste) The code I've been showing you is in the DigestAuthenticator module

**Comment by BluejacketSoftware** [comment]
Finished cleaning up the lib and never saw the ByVal or ByRef thing occur again - must have been brain fog.

**Comment by daFreeMan** [comment]
A comment on the `Value` vs `RHS` parameter name for the `Let`/`Set` properties:

This was just changed _from_ `value` to `RHS`. I agree `RHS` is pretty ugly, however, I championed the change because the `value` parameter that _was_ being introduced interfered with VBA's ever so "helpful" recapitalization of _every_ instance of the keyword `value` throughout the code. 

This caused display issues where:
  `Workbook{"A"}.Worksheet("B").Range("A1").Value = 10`
would be displayed
  `Workbook{"A"}.Worksheet("B").Range("A1").value = 10`
because the declaration of `(ByVal value as String)` overrode VBA's internal definition of `Range.Value`.

I agree that `RHS` is not pretty, and I lobbied for `inValue` or something else, but...

**Comment by BluejacketSoftware** [comment]
As I said, I'm not morally opposed to RHS except it triggers the Rename Variable alert in the code issues window.  Modifying that trigger would suffice as far as I'm concerned...

**Comment by retailcoder** [comment]
I think it would indeed make sense to have `RHS` in the allow-list (you'll find it in the inspection settings; click the cogwheel icon in the *inspection results* toolbar, or find the *inspection settings* tab in the RD settings dialog), since it's an identifier that the VBE will automatically use in some instances when implementing an interface (which was part of the rationale for using that identifier name).

I think the default out-of-the-box settings don't include any identifier names that *use meaningful names* would skip. Let's consider adding `RHS`, but I think that list should be as short as possible, to be configured by the user.

For a very long time I kept using `camelCase` for locals, that's how `value` happened; recently I started forcing myself to use `PascalCase` everywhere, and it *does* take a bit of getting used to, but doesn't hurt readability as much as I'd originally thought - as long as there's a `Private Type` for the private fields, there's no naming clash, or any need for funky prefixing schemes.

As for the *instancing* flag, it controls the `VB_Exposed` and `VB_Creatable` attributes, which Rubberduck absolutely picks up and - in theory - honors... but to do this we basically need to *implement* the VB scoping rules, and it's possible the name-clashing check has a bug and isn't correctly taking into account the class' visibility (needs some testing I guess).

VBA classes can be public, but are only creatable within the project they're defined in (default instances and factories come into play here); VB6 classes can be everything they want.

**Comment by BZngr** [comment]
There are two issues identified above:
1.` Variant` property code generation has a bug (a regression bug).  I have a PR nearly ready for this.
2. The `EncapsulateFieldRefactoring` conflictfinder does not properly account for MemberAccessExpressions using `Me` in local procedures.  The conflicts detected above are a conflict between the a Property name and a parameter where an assignment like `Me.ClientId= ClientId` occurs.  A PR for this is in the works.

**Comment by BZngr** [comment]
Both bugs identified above are resolved.
