### ISSUE TITLE
Microsoft Smartscreen blocking betas on Win10

### ISSUE THREAD

**Issue by chrisdaniels** [rubberduck-vba/Rubberduck#5615]
Microsoft Smartscreen is blocking installs of betas on Win10 because the publisher is "unknown".
On my companys new Win10 install, there is no option to override this due to security.

**Comment by Vogel612** [comment]
That's a known issue we unfortunately can't really fix, especially considering that all our releases are automated. Basically each change that goes into the codebase has its own beta release.

Similar issues apply for various antivirus software vendors. The effort to fix this across the board is prohibitive, especially for predeceases.

**Comment by chrisdaniels** [comment]
Found a really stupid workaround. 
Zip the .exe and run it from inside the zip.

**Comment by daFreeMan** [comment]
That, @chrisdaniels , says a whole lotta _nothing_ about the quality of MS "Smart"screen... 

I'm not sure if we should laugh or cry about this, but either way, I'm glad you found a way to get your duckie back!

**Comment by chrisdaniels** [comment]
Yeah, i cant live without RD these days!

**Comment by bclothier** [comment]
> Found a really stupid workaround.
> Zip the .exe and run it from inside the zip.

Are you sure that running .exe didn't work still when you did that? I ask because SmartScreen is supposed to drop the warning if there's been enough downloads by other people to "approve" this particular binary.

**Comment by chrisdaniels** [comment]
yep, tested both ways to make sure!

**Comment by daFreeMan** [comment]
Have there even been enough downloads of .5647 to trigger this, @bclothier ?

**Comment by bclothier** [comment]
Bizarre but good to know that it does work around the SmartScreen. @daFreeMan , SmartScreen works in mysterious way, by the grace of the Alhacking Bill Gates, so I have no idea when is enough and how.
