### ISSUE TITLE
False positive "Procedure not used" in Outlook "ThisOutlookSession" 

### ISSUE THREAD

**Issue by majkaz** [rubberduck-vba/Rubberduck#5636]
**Rubberduck version information**
Version 2.5.1.5557
OS: Microsoft Windows NT 10.0.14393.0, x64
Host Product: Microsoft Outlook x86
Host Version: 16.0.4266.1001
Host Executable: OUTLOOK.EXE

**Description**
The event procedures _Itemadd on some collections are marked as "Procedure not used"

**To Reproduce**
declare
```
Private WithEvents colCeka As Items
Private WithEvents colDrafts As Items
Private WithEvents colInbox As Items
Private WithEvents colStavyZaruk As Items
```
initialize on startup
`Set colDrafts = ses.GetDefaultFolder(olFolderDrafts).Items`

set to wait on new items in folders.
All the procedures are running as expected, but for some folders the Code inspector throws "Procedure not used". Somewhat puzzling, not for all folders this comes up - see screenshot, only the colDrafts and colInbox (default Inbox and Drafts) get this, not the colStavyZaruk and colCeka for custom folders.

**Screenshots**
![Outlook](https://user-images.githubusercontent.com/23097386/99944393-1a42b380-2d73-11eb-8808-37731135bbb0.png)

**Comment by Vogel612** [comment]
Could you check whether renaming to `colDrafts_ItemAdd` fixes the false-positive? I have a sneaking suspicion that the casing of the event that's handled is relevant here.

**Comment by majkaz** [comment]
Yes, that's true, it is case relevant. 
Everything except "ItemAdd" throws the "procedure not used. I have checked the combination of "itemadd", "itemAdd", and "Itemadd".

**Comment by Vogel612** [comment]
Okay, the root cause for that is the code we use to find event handlers, located in the DeclarationFinder. It compares for exact matches of the event name:

https://github.com/rubberduck-vba/Rubberduck/blob/0dd180eee673758130a9bfc4c130cc6a8b448d01/Rubberduck.Parsing/VBA/DeclarationCaching/DeclarationFinder.cs#L1253-L1261

**Comment by MDoerner** [comment]
Fixing this in a perfect way might require to give up on the use of the hash set. 
However, since most built-in declarations come from references only using English names, I would like to suggest to simply change all identifiers to lower case for hashing.
