### ISSUE TITLE
Function calls and the DefaultMemberRequired inspection

### ISSUE THREAD

**Issue by Irubataru** [rubberduck-vba/Rubberduck#5637]
I have a question that's probably very subjective, but maybe the VBA veterans here know something I do not.

Because of my background primarily from C++ I have a need to distinguish between a member function call and a member variable access when using a class. So just for the sake of having an example, say I have a class `MyClass`

```vb
Private Type Members
  Foo As String
  Bar As String
End Type

Private this As Members

Public Function IsEmpty() As Boolean

    IsEmpty = _
        VBA.Strings.Len(this.Foo) = 0 And _
        VBA.Strings.Len(this.Bar) = 0

End Function

' --- Member variable: Foo
Public Property Get Foo() As String
    Foo = this.Foo
End Property

Public Property Let Foo(ByVal Value As String)
    this.Foo = Value
End Property

' --- Member variable: Bar
Public Property Get Bar() As String
    Bar = this.Bar
End Property

Public Property Let Bar(ByVal Value As String)
    this.Bar = Value
End Property
```

and I use it in `MyMethod`, I would call the different public functions and properties the following way

```vb
Public Sub MyMethod()

    Dim MyObject As MyClass
    Set MyObjext = New MyClass

    MyObject.Foo = "Hello"
    MyObject.Bar = "World"

    Debug.Print MyObject.IsEmpty() 

End Sub
```

If I run the code inspector I get the [DefaultMemberRequired](https://rubberduckvba.com/inspections/details/DefaultMemberRequired) inspection because of the parentheses in `MyObject.IsEmpty()`. Personally I think there is value in having the parentheses there because at least if used consistently it informs me when reading the code that the value is a computed value of the class and not something more inherent to the object which is how I see Properties. However, I also see the value of the inspection if it hadn't included these cases. At the moment my project has well over 1000 of these, and I don't think I will change. On the other hand I would like to hear your opinions on it as there might be things such as language quirks I haven't considered.

**Comment by Irubataru** [comment]
An additional observation.

I always thought the reason I got this inspection was because the expression `MyObject.IsEmpty()` would be evaluated as `(MyObject.IsEmpty)()` and that it would do a spurious function call on the return value, but that doesn't seem to be the case. If I add another class to my project, let's call it `DebuggingDefaultCaller` and have the following class contents

```vb
'Class: DebuggingDefaultCaller

'@DefaultMember
Public Sub PrintHello()
    Debug.Print "Hello world"
End Sub
```

And I add the following method to `MyClass`

```vb
'Class: MyClass

Public Function NewCaller() As DebuggingDefaultCaller
    Set NewCaller = New DebuggingDefaultCaller
End Function
```

and tie it all together in the following method

```vb
Public Sub MyMethod()

    Dim MyObject As MyClass
    Set MyObject = New MyClass
    
    Dim Other As DebuggingDefaultCaller
    Set Other = MyObject.NewCaller()

End Sub
```

then it doesn't print `"Hello world"` to the immediate window.

**Comment by bclothier** [comment]
Can you confirm if you’re using the latest pre-release. There is a [similar issue](https://github.com/rubberduck-vba/Rubberduck/issues/5581) that was addressed in [this PR](https://github.com/rubberduck-vba/Rubberduck/pull/5597)

**Comment by SteveLaycock** [comment]
> Personally I think there is value in having the parentheses there because at least if used consistently it informs me when reading the code that the value is a computed value of the class and not something more inherent to the object which is how I see Properties.

This only works because you are aware of the internals of a Class/Object.  The whole point of an object is that you don't need to (shouldn't) know what goes on inside the Class/Object when you access a property.  Consequently your use of () is , I would argue, an artefact of your 'forbidden' knowledge.

**Comment by Irubataru** [comment]
> 
> 
> Can you confirm if you’re using the latest pre-release. There is a [similar issue](https://github.com/rubberduck-vba/Rubberduck/issues/5581) that was addressed in [this PR](https://github.com/rubberduck-vba/Rubberduck/pull/5597)

I wasn't using the latest pre-release, I was on `2.5.1.5557`, you are right, with the newest pre-release the issue goes away. On my main project I still have 250 of them, some of which doesn't seem like they should trigger, but I'll look at them more closely and alternatively open a new issue if necessary. Thanks!

**Comment by Irubataru** [comment]
> 
> 
> > Personally I think there is value in having the parentheses there because at least if used consistently it informs me when reading the code that the value is a computed value of the class and not something more inherent to the object which is how I see Properties.
> 
> This only works because you are aware of the internals of a Class/Object. The whole point of an object is that you don't need to (shouldn't) know what goes on inside the Class/Object when you access a property. Consequently your use of () is , I would argue, an artefact of your 'forbidden' knowledge.

Hmm, yes, I suppose you are right there. Stylistically I would then prefer to have parentheses after every access rather than none as `MyObject.IsEmpty` looks off to me, but that is my problem. Similarly I'd prefer it if I could call subs as `SomeSub()` as well, but then I'd have to use the `Call` prefix and I have finally managed to stop doing that. A function should only be called if it is followed by a call operator in my mind.

On the other hand, `Property` exists, so calling functions with `()` and properties without doesn't mean I know something about the internals that I shouldn't. The distinction is part of the class' public interface.

A possibly more valid reason I would sometimes want to distinguish is because VBA has no concept of a "Plain Old Structure". I.e. a class that is simply there to be a collection of things. Type exists of course, but the moment you try to actually use them then everything just breaks.
