### ISSUE TITLE
Spacebar not working while code is being inspected

### ISSUE THREAD

**Issue by toddsandford-cbre** [rubberduck-vba/Rubberduck#5641]
**Rubberduck version information**
> Version 2.5.1.5557
> OS: Microsoft Windows NT 10.0.18363.0, x64
> Host Product: Microsoft Office x86
> Host Version: 16.0.12527.21330
> Host Executable: EXCEL.EXE

**Description**
While Rubberduck is inspecting the VBA Project, any spaces entered into the VBA Code window on the end of an existing line of code get removed instantly.

**To Reproduce**
1. Open a project with a large enough codebase so Rubberduck's inspection process takes long enough to see the issue.
2. In a module or class, try pressing the spacebar to enter a space at the end of an existing line of code.
3. You should see that the space character appears momentarily before being deleted.

**Expected behavior**
That space characters can be entered while Rubberduck is inspecting the code.

**Comment by retailcoder** [comment]
Exactly *none* of the inspections interact with the code panes, but the VBE itself will suppress trailing whitespace on a line of code.

Are autocompletion features enabled? That's a more likely lead than inspections.
