### ISSUE TITLE
ImplicitVariantTypeInDeclarationList Inspection

### ISSUE THREAD

**Issue by BZngr** [rubberduck-vba/Rubberduck#5644]
**What**

Inspect code for declaration lists that contain implicitly typed `Variant` variables and constants.

**Why**

It is easy for a user to declare a module variable (or constant) like `Public var1 As Long`, and then later insert another variable `Public var1, var2 As Long` assuming all is well.  And, all appears _well_ because everything generally compiles and _works_ depending on how `var1` is used.  If `var1` is later used as an argument for a `Long` parameter, the compile error of "ByRef/ByVal argument type mismatch" is generated.  Though accurate, the message is not very helpful for users unaware of this implicit behavior.  (Note: In VB, this declaration syntax is supported and does what one might _intuitively_ expect.  So, this inspection should not flag anything in VB). 

**Example**
In VBA, this code should trigger the inspection:
```
Public var1, var2 As Long

Public Sub TestVar1()
    UsesVar1 var1
End Sub

Public Sub UsesVar1(ByRef arg As Long)
End Sub
```
---

**QuickFixes**

1. **MakeImplicitListDeclarationTypesExplicit**

    Example code, after quickfix is applied:

```
Public var1 As Long, var2 As Long

Public Sub TestVar1()
    UsesVar var1
End Sub

Public Sub UsesVar(ByRef arg As Long)
End Sub

```
---

**Resources**

 - **InspectionNames**: ImplicitVariantTypeInDeclarationList
 - **InspectionInfo**: Variables declared in a list are implicitly Variant without an explicit As-Type clause.
 - **InspectionResults**: `{0} {1} is implicitly declared 'As Variant', {0}:Variable or Constant {1}:the name of the variable).

**Comment by IvenBach** [comment]
After refactoring should each declaration be on its own line?
```vb
Public var1 as Long
Public var2 as Long
```

Having them each on their own line to begin with would have helped illustrate that the first had no declared type.

**Comment by BZngr** [comment]
That's usually my preference - though I suspect that the owner/author of the original list would usually want to keep it as a list.  Perhaps there could/should be two quickfixes available: `MakeImplicitListDeclarationTypesExplicitAsList` and `MakeImplicitListDeclarationTypesExplicitAsOnePerLine`.  These would both call a single `RefactoringAction` with the requested option flagged in the `RefactoringAction`'s model.

**Comment by retailcoder** [comment]
Would this not be already covered by [VariableTypeNotDeclared](https://rubberduckvba.com/Inspections/Details/VariableTypeNotDeclared)?

**Comment by BZngr** [comment]
`VariableTypeNotDeclared` would definitely flag the same set of variables.  The difference here is that this inspection/quickfix is constrained to un-typed variables declared in a list where only the last variable has a `non-Variant` As Type.  The inspection/quickfix _assumes_ it's most likely that the user intended for all variables to have the same `As Type` as the _last_ variable. 
 
wow...Now that I've written the above, I realize my recent (and apparently already forgotten!?) `DeclareAsExplicitType` quickfix PR should do a more reliable job of assigning the correct as type if the variable was ever used or assigned.  Otherwise, the unused variables should be removed - not assigned an As Type.
