### ISSUE TITLE
Getting RD to build in VS2019 v16.8.2

### ISSUE THREAD

**Issue by BZngr** [rubberduck-vba/Rubberduck#5645]
Well..VS2019 16.8.2 seems entirely unusable after initial install.  It is as though the project's Property `Treat Warnings as Errors` setting is always `True` regardless of the actual setting in the `.csproj` file.

The steps I found to get to a successful build were:
**1.** Create a file "Directory.Build.props" in the `Rubberduck` folder (top of the repo) with the following content:

```
<Project>
  <PropertyGroup>
   <CodeAnalysisTreatWarningsAsErrors>false</CodeAnalysisTreatWarningsAsErrors>
  </PropertyGroup>
</Project>

```
This applies the `CodeAnalysisTreatWarningsAsErrors` flag (`false`) for all projects.  This element was entirely absent in all my `.csproj` files.   Adjusting the `Treat Warnings as Errors` flag on the Property page would update element `<TreatWarningsAsErrors>false</TreatWarningsAsErrors>`.  So, that leaves me wondering if one of the fundamental 16.8.2 bugs is that the Property page does not set the `CodeAnalysisTreatWarningsAsErrors` element.
 

Doing step 1 cleared all Warning-as-Errors leaving a single 'ca0001 exception phx.fatalerror was thrown' error when building `Rubberduck.Tests` 

**2.** To clear the phx.fatalerror exception, run from the command line (as Administrator!):
regsvr32 "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Packages\Debugger\msdia140.dll"

The above cleared the final error(the path to 'msdia140.dll' could be different for other machines). 

This solution is a combination of [this](https://developercommunity.visualstudio.com/content/problem/1252459/exception-of-type-phxfatalerror-was-thrown.html) and [this](https://stackoverflow.com/questions/30490358/error-in-fxcop-phoenix-analysis-engine)

Hope this moves things along for us VS2019 late-comers until 16.9 can arrive.

**Comment by bclothier** [comment]
If you do that, does that also disable our custom code analyzers which currently treat any results as an error?

**Comment by BZngr** [comment]
Yes - The "Directory.Build.props"  file added in step one changes that behavior.

**Comment by bclothier** [comment]
That is unfortunate. Currently, we use the custom code analyzer to prevent building when it's missing required elements for COM handling or for inspection XML. With that, it would get missed. If the appveyor's VM is updated to 16.8, and thus requires this workaround, it would be now possible to miss those stuff.

**Comment by Vogel612** [comment]
Could you try adding an `.editorconfig` file in the basedirectory with the following content, if the error around that CA0001 reoccurs?

```
[*.{cs,vb}]
dotnet_diagnostic.CA0001.severity = none
```

Other than that you could reenable the "warnings as errors" and add all diagnostics that currently produce unwarranted results to that file.
That probably includes the analyzers yielding `MSB4011`, `IDE1001`, `CS7035` and `AL1053`, which should currently not yield results in VS either.

**Comment by IvenBach** [comment]
I'm on 16.8.2 and one of the solutions offered (https://developercommunity2.visualstudio.com/t/After-168-update-getting-lot-of-code-an/1251574?preview=true) for the build issue is to Build twice. Worked for me.

The first time it barfs with errors. Second attempt takes no time as Visual Studio decides all is swell and #ItJustworks.

**Comment by BZngr** [comment]
Update.  After getting to a successful build, I found that could now successfully build without the "Directory.Build.props" file (step 1).  

Perhaps step 2:
>regsvr32 "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Packages\Debugger\msdia140.dll"

was actually the only required step.

**Comment by retailcoder** [comment]
I suppose AppVeyor CI now building with VS2019 and v16.8.4 successfully building RD are making this issue moot?

**Comment by BZngr** [comment]
The release notes for 16.8.4 indicate that this version resolved the issue of treating compiler warnings as errors (regardless of settings).  Using 16.8.4 or later is the resolution to this issue.
