### ISSUE TITLE
No right-click RD menu in CE

### ISSUE THREAD

**Issue by SmileyFtW** [rubberduck-vba/Rubberduck#5650]
**Rubberduck version information**
Version 2.5.1.5676
OS: Microsoft Windows NT 10.0.18363.0, x64
Host Product: Microsoft Office x86
Host Version: 16.0.13328.20408
Host Executable: EXCEL.EXE

**Description**

**To Reproduce**
Updated to 5676 just now and went to Rick-click>Rubberduck>Ignore Module... and there is no right-click RD menu

**Expected behavior**
The menu would be there in all its blazing glory. The other items such as Annotate, Add, Sync, Move To Folder, etc. are there. 

**Logfile**
Went to get it - there isn't one. Logging is set to Trace.

**Additional context**
Re-installed 5676; didn't help. Tried reverting to a 5663 version and have the same issue. Restarted my laptop as well.

**Comment by SmileyFtW** [comment]
I ask because I found the Ignore functionality discussed in https://github.com/rubberduck-vba/Rubberduck/pull/5604. I used it recently yet now it doesn't appear anywhere.

**Comment by retailcoder** [comment]
"CE" being for the *Code Explorer* toolwindow? If the right-click RD menu being referred to is the code pane context menu, then #5702 should fix it.

**Comment by SmileyFtW** [comment]
Yes, CE = RD Code Explorer...
