### ISSUE TITLE
Obfuscation

### ISSUE THREAD

**Issue by FiSHonAUT** [rubberduck-vba/Rubberduck#5669]
Hi,
I searched the web for an easy to use code obfuscator. Mostly they work only within one module. Rubberduck already knows all functions across all modules within a project. So I think obfuscating a project by removing comments, indents and refactoring functions to random stringss should be doable, right?

**Comment by Vogel612** [comment]
@FiSHonAUT doable, sure, but quite very much against the goal of the project. The whole point of Rubberduck is to make code **easier** to understand. You can of course use Rubberduck under the GPLv3 license and add your own implementation of an obfuscator.

I'd assume that if you opened a pull-request it would probably get merged, but I don't think this is something that will get implemnented by the current contributors.
