### ISSUE TITLE
ToDo Explorer doesn't always toggle "wait" cursor off

### ISSUE THREAD

**Issue by Hosch250** [rubberduck-vba/Rubberduck#567]
When you open the ToDo explorer, then close it, then reopen it, it gets a permanent spinny cursor, and you have to force-quit Excel (or whatever).  It doesn't give an error, but in Debug mode, I believe it said something about trying to access a disposed/GC'ed item.

I don't know if this has something to do with what I did removing memory leaks, but I do not think so because everything else still works.

The same thing happens when you refresh it and there are no items.

**Comment by ckuhn203** [comment]
No repro in vNext. Looks like @Hosch250 fixed this with commit 4d2dfcd013b1cdd9911363c75c4592cb154ea51b.
