### ISSUE TITLE
Cleanest way to disable RD Addin temporarily?

### ISSUE THREAD

**Issue by Greedquest** [rubberduck-vba/Rubberduck#5672]
Hi,

Is there a way to temporarily disable Rubberduck in Excel? There's some code I'm editing which repeatedly crashes Excel and I'd like to use the default VBE for a little while. Is there a clean way to turn off the RD Excel Addin without uninstalling it, and then easily turn it back on as soon as this debugging is finished.

NB, there is no problem with RD itself (except being slower to start up than Vanila VBE), it's not causing the crashes, but I want to turn it off for a little bit while I do my research:)

**Comment by Greedquest** [comment]
![image](https://user-images.githubusercontent.com/25348920/107861482-eb9e1b80-6e3d-11eb-8ae9-634c2fbb17bf.png)
E.g. will unchecking this and checking it back later have any lasting effects on RD I should be aware of?

**Comment by SmileyFtW** [comment]
Click on Loaded to uncheck the box and turn off RD; when you are ready to turn RD back on click it to check the box….
