### ISSUE TITLE
Can't ignore ObsoleteWhileWendStatement issue in module

### ISSUE THREAD

**Issue by alvinseville7cf** [rubberduck-vba/Rubberduck#5681]
**Rubberduck version information**
The info below can be copy-paste-completed from the first lines of Rubberduck's log or the About box:

    Rubberduck version 2.5.1.5621
    Operating System: Microsoft Windows [Version 10.0.19042.804]
    Host Product: Microsoft Excel (in Microsoft Office 365)
    Host Version: 
    Host Executable: [...]

**Description**

**To Reproduce**
1. Refresh issue list.
2. Try ignore `ObsoleteWhileWendStatement ` in module for the following code:
```vba
Option Explicit

Sub main()
    While True
    Wend
End Sub
```

**Expected behavior**
Issue is being ignored after `Fix -> Ignore in module > ...`.

**Screenshots**

**Logfile**
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/6074331/RubberduckLog.txt)

**Additional context**

**Comment by retailcoder** [comment]
No repro.

After selecting Fix -> Ignore in module -> Selected Occurrence, the module looks like this:

```vb
'@IgnoreModule ObsoleteWhileWendStatement
Option Explicit

Sub main()
    While True
    Wend
End Sub
```

And there is no `ObsoleteWhileWendStatement` inspection result anymore, as expected.

Same with Ignore Once -> Selected Occurrence:

```vb
Option Explicit

Sub main()
    '@Ignore ObsoleteWhileWendStatement
    While True
    Wend
End Sub
```

Note that this particular loop is also issuing a (legitimate) result for the `EmptyWhileWendBlockInspection`.

**Comment by alvinseville7cf** [comment]
@retailcoder, please consider [this .gif](https://drive.google.com/file/d/1bueHpsY9Z3LWwsepjeVsJWd88Y9SiGls/view?usp=sharing).

**Comment by retailcoder** [comment]
@alvinseville7cf I cannot reproduce this behavior using the current build and the supplied example code, can you confirm it still happens off the latest pre-release build? Thanks!

**Comment by alvinseville7cf** [comment]
@retailcoder, in pre-build 2.5.1.5761 everything works perfectly. :)
