### ISSUE TITLE
Add capability to Rename Private Type Members from CE context menu

### ISSUE THREAD

**Issue by SmileyFtW** [rubberduck-vba/Rubberduck#5688]
**Justification**
Ease of use and ensure all references are renamed; essentially the reasoning behind all of the other Rename capabilities.

**Description**
As it stands now, everything within a class module can be renamed by RD except Private Type members

**Comment by BZngr** [comment]
I did a quick test and had success renaming Private Types and Member(s) within as Class Module.  Could you provide a code example where it is failing to rename a Private Type member?

**Comment by SmileyFtW** [comment]
I'm using:
Version 2.5.1.5731
OS: Microsoft Windows NT 10.0.18363.0, x64
Host Product: Microsoft Office x86
Host Version: 16.0.13801.20294
Host Executable: EXCEL.EXE

With the member selected in CE, there is no hyperlink to rename nor is there a right-click rename. What might I be doing wrong?

![CE Image](https://user-images.githubusercontent.com/42221335/111170224-b3d7e000-8571-11eb-83a6-60dfa1fce5d4.jpg)

**Comment by Vogel612** [comment]
needs a refresh from what I can tell

**Comment by BZngr** [comment]
I see the issue now...Yes, that looks like a bug.  RD is not offering an enabled `Rename` option from the `CodeExplorer` context menu when a Private Type is selected.  So, the workaround for now is to navigate to the declaration of the Private Type member in the code pane and select it there.  The `Rename` refactoring option is available (and works) in both the main and context menus.

**Comment by SmileyFtW** [comment]
Great! Thanks!

**Comment by retailcoder** [comment]
Same for `Enum` members.
