### ISSUE TITLE
False positive - "Variable 'xxx' is implicitly 'Variant'" for explicitly defined Variant Array declared via ReDim

### ISSUE THREAD

**Issue by Armin1979** [rubberduck-vba/Rubberduck#5690]
**Rubberduck version information**
Version 2.5.1.5557
OS: Microsoft Windows NT 10.0.17134.0, x64
Host Product: Microsoft Outlook x64
Host Version: 16.0.13801.20294
Host Executable: OUTLOOK.EXE

**Description**
When declaring a Variant type array explicitly, Rubberduck still shows the "Implicitly 'Variant' variable" message

**To Reproduce**
Define a variant type array, for example:
`ReDim ForwardInfos(1 To 1) As Variant`

**Expected behavior**
Rubberduck should not show an error for this line

**Comment by MDoerner** [comment]
This seems to be a problem around our treatment of VBA's quirk that you can declare an array via `ReDim`. It works fine for arrays declared via `Dim`.
I will have a look into it.
