### ISSUE TITLE
Cancelling code inspections leaves the "wait" cursor stuck

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#577]
Repro:

 - Open up a relatively large VBA project
 - Bring up the code inspections, click the "Refresh" button
 - After parsing completes, inspections refresh button turns into a cancel button - click it

The currently running inspection will return its results, and code inspections will then cancel and whatever results have completed will show up. Cursor remains stuck on "wait".

This *should* be an easy-fix; tagging as such.

**Comment by ckuhn203** [comment]
Looking at the commit that closed this issue, I can't possibly see how it did. Reopening until we can investigate whether or not this should have been closed.

**Comment by ckuhn203** [comment]
Here's the issue with the Code inspections. [The code to put the wait cursor back is outside of the finally block.][1]

            catch (TaskCanceledException)
            {
            }
            finally
            {
                Control.SetIssuesStatus(_issues, true);
                Control.EnableRefresh();
            }

            Control.Cursor = Cursors.Default;
        }

[1]: https://github.com/rubberduck-vba/Rubberduck/blob/next/RetailCoder.VBE/UI/CodeInspections/CodeInspectionsDockablePresenter.cs#L186-L193

**Comment by ckuhn203** [comment]
Fixed from PR #628.
