### ISSUE TITLE
Parse Error: Exception of type 'System.OutOfMemoryException' was thrown.

### ISSUE THREAD

**Issue by AstrocalcVB** [rubberduck-vba/Rubberduck#5786]
**Rubberduck version information**
	Rubberduck version 2.5.2.5927 loading:
	Operating System: Microsoft Windows NT 6.2.9200.0 x64
	Host Product: Visual Basic x86
	Host Version: 6.00.9782
	Host Executable: VB6.EXE;

**Description**
After successfully installing the latest pre-version I tried once again to parse my largest project. Again, it resulted in a Parse Error now with an OutOfMemoryException, but I can confirm that the object.Circle optional arguments bug has been fixed with this release.

Not much more to say really, the parse goes on for quite some time before the error finally appears. 

**To Reproduce**
1. Fresh parse of project, what more can I say.
2. After a lengthy time the parse error appears.

Logfile attached below.

**Expected behavior**
Project expected to parse successfully.

**Screenshots**
N/A

**Logfile**
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/6510574/RubberduckLog.txt)

**Additional context**
On study of the log I note the error seems to be triggered by one of my class files. So for convenience I attach it below (in a zip). I don't know if it matters but the class is the last one listed in Project Explorer for Class Modules. Also, it's not written by me but by Jon Johnson (aka fafalone) at VBF.

[cTaskDialog.zip](https://github.com/rubberduck-vba/Rubberduck/files/6510646/cTaskDialog.zip)

**Comment by AstrocalcVB** [comment]
For the record, I just parsed w/o problem another smaller project containing the same cTaskDialog class, so the class as such doesn't seem to be the problem. However, this project only make use of the class at one location, while the larger project use it more extensively.

**Comment by AstrocalcVB** [comment]
Again, for the record, still get a System.OutOfMemoryException when trying to Parse with RD 2.5.2.5938.
Attaching latest log file, this time as Debug log, if that possibly can throw some light on the issue?
The suggested change of setting was done when installing, to reduce memory footprint but doesn't seems to have helped. Is there any clue in the log of anything in my code that possibly causes this and I could address?

I noticed this line in the log, just before the exception was thrown:
SLL mode failed while parsing the CodePaneCode version of module Wheel. Retrying using LL.;

I'm not sure what that refers to but thought I would mention that I haven't loaded any of the RD GUI parts and use the Project Explorer from 'Code Smart 2013", if this possibly could have anything to do with it?

[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/6623728/RubberduckLog.txt)

**Comment by AstrocalcVB** [comment]
OK silly of me, I should have thought of testing w/o loading the SmartCode 2013 Add-In, and I probably didn't think of that as RD worked fine with a smaller project with SC2013 loaded. So, if I don't load SC2013 on start, and I also activated the RD Code Explorer, the Parse seems to be successful, but now instead I get errors when it changes to Resolve References. New error log attached:
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/6623909/RubberduckLog.txt)

**Comment by AstrocalcVB** [comment]
I forgot to mention that in the end VB6 IDE crashes/dies.

**Comment by Vogel612** [comment]
It remains an OutOfMemoryException, it's just that the memory runs out later in the parsing process. Memory is a ... longstanding issue that we're aware of, see #3347.

Closing this issue as a duplicate
