### ISSUE TITLE
Broken link on Books-on-programming wiki page

### ISSUE THREAD

**Issue by IvenBach** [rubberduck-vba/Rubberduck#5820]
The [Books on programing](https://github.com/rubberduck-vba/Rubberduck/wiki/Books-on-Programming) page has a link in the first paragraph that doesn't exist. Clicking on it redirects users to the main wiki page.

**Comment by MDoerner** [comment]
Apparently, closes tags do not work in wiki edit messages.

This is fixed now. The reason why it was broken was that the link was not updated when the page it linked to was renamed.
