### ISSUE TITLE
False positive AssignmentNotUsed inspection

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#5824]
**Rubberduck version information**
The info below can be copy-paste-completed from the first lines of Rubberduck's log or the About box:
```
Version 2.5.2.5953
OS: Microsoft Windows NT 10.0.18363.0, x64
Host Product: Microsoft Office 2016 x64
Host Version: 16.0.5164.1000
Host Executable: MSACCESS.EXE
```

**Description**
An "Assignment not used" inspection is triggered when a variable is assigned a value, then conditionally overwritten with a different value. It's later used in another conditional , and finally assigned as the return value of the Function.

```
Public Function EmailSubjectLine() As String

  Dim subject As String
  subject = "Please provide feedback on your recent visit to EOHS"
  
  Dim unneededEmailAddress As String
  If Not HasEmailAddress Then
    subject = "Missing email address for EOHS survey!"
  End If
  
  If DevelopmentMode Then
    subject = "TESTING: " & subject
  End If
  
  EmailSubjectLine = subject
  
End Function
```

The very first `subject = ...` line is flagged by the inspection.

This has been reported twice in the past, and was fixed on #4913, but it appears something was missed in that fix.

**To Reproduce**
See code above

**Expected behavior**
There should be no inspection triggered. At an absolute minimum, the variable is used on the last line on the RHS of the `Function` return.

**Screenshots**

**Logfile**
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/6742529/RubberduckLog.txt)

**Additional context**

**Comment by monoscale** [comment]
I am having the same issue with the following code:

```
Public Function FormBase_IsValid() As Boolean
    Dim validInput As Boolean: validInput = True

    If Not ValidationHandler.IsTextBoxValid(TextBoxAge, Numeric) Then validInput = False
    If Not ValidationHandler.IsTextBoxValid(TextBoxYear, Numeric) Then validInput = False

    FormBase_IsValid = validInput
End Function
```

This code checks if the form has any invalid inputs. The default cause is that the input is valid and only becomes false if any of the input fields are not valid. However, the inspection "Assignment is not used" triggers on the first line:

`    Dim validInput As Boolean: validInput = True`

This default case of "True" is actaully very important in this case and the inspection should not trigger here.
