### ISSUE TITLE
VariableNotUsed & VariableNotAssigned: false +ve if variable used inside conditional compilation directives block

### ISSUE THREAD

**Issue by vincehardwick** [rubberduck-vba/Rubberduck#5831]
**Rubberduck version information:**

Version 2.5.2.5953
OS: Microsoft Windows NT 10.0.19042.0, x64
Host Product: Microsoft Office x64
Host Version: 16.0.14131.20278
Host Executable: EXCEL.EXE

**Description**
An object variable which is only set and used inside a #If...Then... #End If conditional compilation directive block is flagged by code inspection as VariableNotUsed & VariableNotAssigned.

**To Reproduce**
1. Declare object variable, e.g. Dim rngPerfTimings As Range
2. Define conditional compilation argument in Tools > VBAProject properties > General tab
3. Conditionally set and refer to object variable inside #If...Then ...#End If block, checking against the value of conditional compilation argument
4. Parse project for Code Inspection
5. Review 'Code Quality Issues' section - warnings for VariableNotUsed & VariableNotAssigned flagged against the object variable.

**Expected behavior**
The object variable is set and used upon a condition being met, so no such warnings should be raised by code inspection.

**Logfile**
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/6783227/RubberduckLog.txt)

**Additional context**
```
Dim rngPerfTimings As Range

' Clear performance timings
#If PERF_TEST = 1 Then
    With wsPerformance
        
        Set rngPerfTimings = .Range("A2", .Range("A" & .Rows.Count).End(xlUp).Offset(0, 2))
        
    End With
    If rngPerfTimings.Cells(1).Address <> "$A$1" Then rngPerfTimings.Clear
#End If
```

**Comment by MDoerner** [comment]
Could you tell us whether you see the inspection results also when the conditional compilation argument is set making the condition true? If that is the case, it is a bug. 

Otherwise, this is a general limitation of Rubberduck. The code that is parsed and inspected is always the code according the currently set compilation arguments.

Anyway, if the variable is neither assigned nor used unless the compilation argument is set, why not move it into the block?

**Comment by vincehardwick** [comment]
> Could you tell us whether you see the inspection results also when the conditional compilation argument is set making the condition true? If that is the case, it is a bug.
> 
> Otherwise, this is a general limitation of Rubberduck. The code that is parsed and inspected is always the code according the currently set compilation arguments.
> 
> Anyway, if the variable is neither assigned nor used unless the compilation argument is set, why not move it into the block?

Thanks for the prompt reply - I've just checked, and no, the inspection result relating to the object variable do not appear when the conditional compilation argument is set to satisfy the condition.

I also took your advice and moved the variable's declaration to within the #If...Then #End If block (as it was the only place it was referred to) - even when the conditional compilation argument was set such that the condition was not met, this prevented the VariableNotUsed & VariableNotAssigned inspection results from appearing.

Happy for this to be closed now that I understand better how Rubberduck handles conditional compilation argument checks during parsing.
