### ISSUE TITLE
Windows "Code Inspections" leaves empty 

### ISSUE THREAD

**Issue by Tanarri** [rubberduck-vba/Rubberduck#5832]
**Rubberduck version information**
The info below can be copy-paste-completed from the first lines of Rubberduck's log or the About box:

    Rubberduck version 2.5.2.5953
    Operating System: Windows 10 (64bit)
    Host Product: MS Access
    Host Version: 2013
    Host Executable: Office 32bit

**Description**
The Inspection Windows leaved empty after a inspection of my code.

**To Reproduce**
1. - Menu "Rubberduck --> Refresh" 
- or Commandbar --> Click on "Pending" 
- or window "Code inspection" --> Click in the middle of the Window "Refresh""

**Expected behavior**
The Code inspection Window should show the result of the inspection (many entrys in my case)

**Screenshots**
![grafik](https://user-images.githubusercontent.com/6181166/125089045-4d517180-e0ce-11eb-9fde-608633d0b952.png)

**Logfile**
Rubberduck generates extensive logging in TRACE-Level. If no log was created at `%APPDATA%\Rubberduck\Logs`, check your settings. Include this log for bug reports about the behavior of Rubberduck.
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/6791858/RubberduckLog.txt)

Additional Logfile and work around:
When I click in window "Code inspection" --> in the left top(!)  "Refresh"-Icon then the window "code inspection" is filled
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/6791868/RubberduckLog.txt)
![grafik](https://user-images.githubusercontent.com/6181166/125089510-b802ad00-e0ce-11eb-8720-30d5927963ec.png)

**Comment by MDoerner** [comment]
Could you please check in the Rubberduck settings whether the option to run inspections on parse is checked? If this is not checked, the inspections will only run when a refresh is requested from the button in the code inspections window.

**Comment by Tanarri** [comment]
Hi @MDoerner ,
you are right. The option was not checked. With this option checked all went well.
Thanks!
