### ISSUE TITLE
Update method declaration

### ISSUE THREAD

**Issue by Hosch250** [rubberduck-vba/Rubberduck#584]
When the user adds a parameter to a reference, ask them if they would like to add the parameter in the method declaration if the parameter does not exist.

**Comment by retailcoder** [comment]
So, if we find a procedure call that has more arguments than the called procedure has parameters? And infer parameter type from the supplied value (assuming we can evaluate it)?

**Comment by ckuhn203** [comment]
Interesting... How does this fit in with our assumption that "the code compiles" @retailcoder? I would think it's fine. Perhaps we just shift that attitude to "the code is syntactically correct"?

**Comment by Hosch250** [comment]
I got this idea because R# asked me in real-time when I added a new value to a call.  This shouldn't be implemented until we stop statically analyzing the code, but do it dynamically (are those the right terms?).

**Comment by retailcoder** [comment]
@Hosch250 let's defer it then. We need a key listener for this to work - i.e. we need to pick up changes in the active code pane, and be constantly analyzing the code in a background thread. I'm hoping to have that implemented by RD 10.0 :wink:
