### ISSUE TITLE
Code Inspection: Variable not assigned when Variant used as Array

### ISSUE THREAD

**Issue by FullValueRider** [rubberduck-vba/Rubberduck#5845]
**Rubberduck version information**
Version 2.5.2.5958
OS: Microsoft Windows NT 10.0.19043.0, x64
Host Product: Microsoft Office x64
Host Version: 16.0.14228.20204
Host Executable: WINWORD.EXE

**Description**
When a variable is declared as a variant and redimmed to use as an array then you get a code inspection of 'Variable' not assigned even though each item of the array is assigned.

**To Reproduce**
Steps to reproduce the behaviour:
1. Declare a variable as variant
2.  Redim the variable
3. populate the array in a for loop
4. rubberduck refresh
5. In Code Inspections the variable declaration will be highlighted with a 'Variable not assigned' inspection report.

**Expected behaviour**
The redim statement should effectively be seen as assigning a value to the variable.

**Comment by philippetev** [comment]
I second that.
