### ISSUE TITLE
Spurious "Return value of '...' gets discarded" inspection result

### ISSUE THREAD

**Issue by Lx** [rubberduck-vba/Rubberduck#5853]
**Rubberduck version information**

    Version 2.5.2.5906
    OS: Microsoft Windows NT 10.0.19042.0, x64
    Host Product: Microsoft Office x64
    Host Version: 16.0.13801.20864
    Host Executable: EXCEL.EXE

**Description**
Rubberduck code inspection yields `Return value of '...' gets discarded` for a function that does not discard the return value.

**To Reproduce**
Run inspection on this code:
```VB
Private Function Credentials(ByVal Username As String, ByVal Password As String) As Dictionary
    Set Credentials = New Dictionary
    Credentials.Add "username", Username
    Credentials.Add "password", Password
End Function
```

**Expected behavior**
Spurious inspection result should not be shown.

**Comment by retailcoder** [comment]
Thanks for the report! Note that discarding of the return value would potentially be a problem at the function's call sites, not in the function itself. Hence the inspection is reporting usages of the function, unless the return value is being discarded at every single call site, then the function itself is being flagged.

Given the above, this code should trigger the inspection:

```vb
Credentials user, pwd
```

And this wouldn't:

```vb
Dim creds As Dictionary
Set creds = Credentials(user, pwd)
```

**Comment by MDoerner** [comment]
I think what might happen here is that the references to the function return value itself inside the function trigger the inspection, which is a bug. 

Generally, any method access should be ignored by the inspection. However, I think the code used to identify such cases is not quite right. 

https://github.com/rubberduck-vba/Rubberduck/blob/8b19e2563a4198702ee7ac4718c3198f53cfe3af/Rubberduck.CodeAnalysis/Inspections/Concrete/FunctionReturnValueDiscardedInspection.cs#L79-L88

I think this misses the case where the immediate parent is the method call.

Please note that this is based on offline analysis. We should look at this under a debugger to actually figure out what is going on.

**Comment by Lx** [comment]
Thank you for the very prompt responses.  I can confirm that the return value is not being discarded at the sole call site:

```VB
Dim Request As WebRequest
Set Request = New WebRequest
Set Request.Body = Credentials(Username, Password)
```

This is what gets highlighted when I double-click on the inspection result, possibly supporting @MDoerner 's analysis:

![image](https://user-images.githubusercontent.com/160164/133221231-c6746a39-9a7e-4658-8d06-d99284394fbd.png)

**Comment by retailcoder** [comment]
Yep, that's a bug! This one's on us, but as a rule of thumb (perhaps a
stylistic choice) I would systematically avoid treating a function's return
value as a local variable like this, and declare an explicit local instead;
that makes the function's identifier name only appear LHS of an assignment
in the case of the return value assignment (or, more rarely, in the case of
a recursive call), which Rubberduck should parse and analyze correctly
every time.

Thanks again for the report!
