### ISSUE TITLE
Parametrized Test Method

### ISSUE THREAD

**Issue by 1504168** [rubberduck-vba/Rubberduck#5885]
Sometimes we need to run a single test for different input argument and in that case maybe we need to only change some parameter value. We can isolate that common code into a sub or function and then call that from each test cases. Instead of it will be better if Rubberduck can have a parametrized test method (Test value source can be JSON type annotation or CSV type annotation.

**Comment by retailcoder** [comment]
Linking #1229 (aye, that's an old one!)
