### ISSUE TITLE
Doing the first install. found a guide to use (from RB). Set up a Test Module. When I run TestExplorer, the ducks just go round and round

### ISSUE THREAD

**Issue by skorpio07** [rubberduck-vba/Rubberduck#5906]
**Rubberduck version information**

Version 2.5.2.5906
OS: Microsoft Windows NT 10.0.19042.0, x64
Host Product: Microsoft Office x86
Host Version: 16.0.14527.20234
Host Executable: EXCEL.EXE

I let it run overnight (knowing that it would not stop spinning). Don't know what I am doing wrong.
The info below can be copy-paste-completed from the first lines of Rubberduck's log or the About box:

    Rubberduck version [...]
    Operating System: [...]
    Host Product: [...]
    Host Version: [...]
    Host Executable: [...]

**Description**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logfile**
Rubberduck generates extensive logging in TRACE-Level. If no log was created at `%APPDATA%\Rubberduck\Logs`, check your settings. Include this log for bug reports about the behavior of Rubberduck.

**Additional context**

**Comment by retailcoder** [comment]
Related: https://stackoverflow.com/q/70147500/1188513

Can you please elaborate a bit on the steps to reproduce the problem, and confirm that your test module has at least one unit test?

Obviously something is wrong if the toolwindow's "busy" state is erroneously set (or erroneously not reset), but the spinning duckies would only be shown while parsing / discovering tests. How was the parse triggered exactly?

**Comment by skorpio07** [comment]
I will check this when i get home (RD on laptop). but all i did was add the
Sub (with comment) to TestModule1 and then run TestExplorer. Didn't change
any settings.

**Comment by BZngr** [comment]
FWIW, Another path that reliably generates constantly spinning ducks.  
1. Open Code Inspections window
2. Open Test Explorer
3. Run a single test or a group of tests.
4. Code Inspections window presents constantly spinning ducks after the test(s).

Work around:
1. Close Code Inspections window (Test Explorer can remain open or be closed)
2. Manually initiate a Parse using the 'Ready' button.  
3. After the manually initiated Parse is finished.  Open Code Inspections...all is well.

**Comment by skorpio07** [comment]
BZngr

So I opened Code Inspections and it displayed with data (read a few errors, seemed accurate). So I closed it. then i tried to find the Ready button but don't see it. The toolbar says Parse Error with a red X. is that where the Ready button is?

**Comment by skorpio07** [comment]
Finally got it to say ready (probably by going to settings and excluding a number of add-ins). So now I click` Refresh, the ducks spin and a few seconds later they disappear. then I run Test Explorer, click Refresh and nothing appears in the window. summary says 0 of 0 test run. I can't click the Run button or the Add button. what do i need to do to run my test. 
`Option Explicit
Option Private Module

'@TestModule
'@Folder("Tests")

Private Assert As Object
Private Fakes As Object

'@ModuleInitialize
Private Sub ModuleInitialize()
    'this method runs once per module.
    Set Assert = CreateObject("Rubberduck.AssertClass")
    Set Fakes = CreateObject("Rubberduck.FakesProvider")
End Sub

'@ModuleCleanup
Private Sub ModuleCleanup()
    'this method runs once per module.
    Set Assert = Nothing
    Set Fakes = Nothing
End Sub

'@TestInitialize
Private Sub TestInitialize()
    'This method runs before every test in the module..
End Sub

'@TestCleanup
Private Sub TestCleanup()
    'this method runs after every test in the module.
End Sub

Public Sub testme()

'@TestMethod
  
Dim x, y
   
x = 1

y = 1

If x = y Then
    MsgBox ("Equal")
Else
    MsgBox ("Not Equal")
End If

End Sub
`

**Comment by BZngr** [comment]
@skorpio07

The quick answer is that the attribute `@TestMethod needs to precede the Sub declaration.   Try editing your test to match the following:
```
'@TestMethod("Uncategorized")
Private Sub testme()
    Dim x, y
    x = 1
    y = 1

    If x = y Then
         MsgBox ("Equal")
    Else
        MsgBox ("Not Equal")
    End If

End Sub

```
Once you can run the above test...

The longer answer - or things to consider/try:
1. RD can insert a TestMethod for you.  The Test Explorer's `Add` button dropdown will enable a `TestMethod` button once you have a RD test module loaded in the VBE editor.  The inserted subroutine will include some structure to help organize your test(s).  See an example below.
2. Avoid `MsgBox` or any other UI pop-up interactions within tests.  I know you are just trying to get a test to run ATM...just felt compelled to mention it :).

**RD Generated TestMethod**
```
'@TestMethod("Uncategorized")
Private Sub TestMethod1()                        'TODO Rename test
    On Error GoTo TestFail
    
    'Arrange:

    'Act:

    'Assert:
    Assert.Succeed

TestExit:
    Exit Sub
TestFail:
    Assert.Fail "Test raised an error: #" & Err.Number & " - " & Err.Description
    Resume TestExit
End Sub
```

**Comment by skorpio07** [comment]
Excellent answer. When I get back to computer I will implement it. Getting
close. Fyi, this is the third try of RB. Thanks for your help.

**Comment by skorpio07** [comment]
ok, this can be closed (which I will do). got the test module to pass, tested various things. now I need to read (alot) to get up to speed on some of the lingo. do you have any book titles that you could recommend that would cover the concepts in your program?

thanks again

**Comment by Vogel612** [comment]
While there is no book out there (at least to my knowledge), you should find a lot of the information you need on the website (https://rubberduckvba.com - which should be finishing it's reconstruction any day now :smile:) as well as on the wordpress site where Mathieu (and a few other contributors) blog: https://rubberduckvba.wordpress.com
