### ISSUE TITLE
False positive inspection results are generated for Public fields in Class Modules that define an interface

### ISSUE THREAD

**Issue by BZngr** [rubberduck-vba/Rubberduck#5908]
Version 2.5.2.x (debug)
OS: Microsoft Windows NT 10.0.19042.0, x64
Host Product: Microsoft Office x64
Host Version: 16.0.14527.20276
Host Executable: EXCEL.EXE

Public fields are acceptable declarations in classes that define interfaces.  `ImplementInterfaceRefactoring` correctly implements a Let/Set/Get Property for each Public field in the interface definition class.  These Public fields are flagged by the `VariableNotUsed` and `VariableNotAssigned` inspections. 

An interface defined like:

```
Option Explicit

'@Exposed
'@Interface

Public TestNumber As Long

Public Sub RunTests()
End Sub

```
Will result in Inspection results for `TestNumber`

**Expected behavior:**

Class Modules that have an '@Interface annotation or classes that are used as part of an `Implements`  statement should not be flagged by the `VariableNotUsed` or `VariableNotAssigned` inspections.

**Comment by BZngr** [comment]
Related #5291

**Comment by MDoerner** [comment]
@retailcoder @Vogel612 Can I get your opinion here? 
Should we report unused Public members of an interface or not?
@BZngr leans towards not reporting them and I would rather lean towards reporting them all, at least unless they are in an exported class module.

In any way, this needs some cleanup because the handling is currently inconsistent. 
We do not report unused public functions and procedures in interface modules, but we report unused public variables.

**Comment by MDoerner** [comment]
We already ignore all results for the implementing members.

I would vote to still not flag any public members of fields in an interface module, which has the `Exposed` attribute. These are kind of clearly intended for external use by another project.

**Comment by Vogel612** [comment]
I have nothing to add to the discussion itself. My vote is to keep results for public members that are not exposed and treat an exposed module like an `@EntryPoint` for the purposes of all UnusedX inspections

**Comment by MDoerner** [comment]
OK, then I will align the handling in this direction.

BTW, this is actually consistent with how major tools for other languages do this, e.g. visual studio and intellij.
