### ISSUE TITLE
Portable version without installation

### ISSUE THREAD

**Issue by philippetev** [rubberduck-vba/Rubberduck#5918]
It would be great if there is a portable version of Rubberduck that can run from any folder, similar to the approach, used with the portable version of MZ-Tools - a zip that contains all extension files in a folder, bundled with little tool that registers and unregisters the addin (for the current user).

Such version could be very useful for use in companies, which policies forbid all kind of installs, even the user ones (like the company I work in).

**Comment by daFreeMan** [comment]
I'm by no means the expert or final say on the matter, but if your company forbids installations, wouldn't they likely also forbid a stand-alone registration? 

I realize programs must read/write the registry on a regular basis, so maybe that's a moot point/not possible. However, I could see them forbidding any non-admin execution of RegEdit, which is required for registering from the command line.

**Comment by philippetev** [comment]
> I'm by no means the expert or final say on the matter, but if your company forbids installations, wouldn't they likely also forbid a stand-alone registration?
> 
> I realize programs must read/write the registry on a regular basis, so maybe that's a moot point/not possible. However, I could see them forbidding any non-admin execution of RegEdit, which is required for registering from the command line.

The obviously haven't forbid that, since I'm able to use the portable version of MZ-Tools at my work PC.

**Comment by bclothier** [comment]
I realize this is late reply but have you tried installing in per-user mode? It does the same thing being proposed here.

**Comment by philippetev** [comment]
I've already explained in the first post that per-user mode won't work in companies that have restricted all access to the Installer service (like the one I currently work in), so in such cases you can't do even user-based kind of installations.
Just take a look at the portable version of MZ-Tools and you'll see what I mean - no installation whatsoever, extract the zip in a folder of your choosing and use the provided tool to register/unregister the addon in the HKCU registry userspace. That part of the registry cannot be restricted, because Excel should save its settings somewhere after all.

**Comment by bclothier** [comment]
In the reply, Windows Installer Service was mentioned but it’s my understanding that Inno Setup does not use the service, which was why I wanted to confirm.

**Comment by philippetev** [comment]
Wasn't aware it's Inno... Well, it's true, Inno doesn't rely on the WIndows Installer service, yet, for some (unknown) reasons I get permission errors when I try to do the per-user install.
