### ISSUE TITLE
Excel is still calculating after use of Intender

### ISSUE THREAD

**Issue by kaszysz** [rubberduck-vba/Rubberduck#5933]
**Rubberduck version information**
The info below can be copy-paste-completed from the first lines of Rubberduck's log or the About box:

    Rubberduck version [...]
    Operating System: [Windows 11 Pro]
    Host Product: [Excel 365]
    Host Version: [2112 16.0.14729.20254 64bit]

**Description**
Whole project has been working as I excepted. I had used Intender and after that whole excel's file with vba program is crashing and cant event save it. In right bottom corrner is still "calculating". Tested on two different computer, effect is the same on both.

[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/7882076/RubberduckLog.txt)

**Comment by retailcoder** [comment]
Can you confirm Excel's calculation mode is *automatic*? Rubberduck does not interact with Excel itself, or any other host application... We're going to need more detailed repro steps to replicate this issue.
