### ISSUE TITLE
@VariableDescription for Constants

### ISSUE THREAD

**Issue by AndreasMatthias** [rubberduck-vba/Rubberduck#5947]
**Rubberduck version information**
Version 2.5.2.6051
OS: Microsoft Windows NT 10.0.19044.0, x64
Host Product: Microsoft Office 2013 x86
Host Version: 15.0.5423.1000
Host Executable: EXCEL.EXE

**Description**
`'@VariableDescription` annotations for *constants* always issue a warning in Code Inspections.

**To Reproduce**
```
'@VariableDescription("hello world")
Private Const helloWorld As String = "hello world"
```
This code issues the following warning in Code Inspections:
```
Module or member 'helloWorld' has a 'VariableDescription' annotation, but no corresponding attribute.
```
But looking at the exported module you will see that the attribute is actually set correctly:
```
'@VariableDescription("hello world")
Private Const helloWorld As String = "hello world"
Attribute helloWorld.VB_VarDescription = "hello world"
```

**Expected behavior**
No warning.

**Comment by MDoerner** [comment]
This issue has already been reported as #5926 and I thought that I had already fixed it in PR #5934.
However, since the version mentioned above is the latest pre-release, I guess I have to look into this again.
