### ISSUE TITLE
RubberduckMenu items not working

### ISSUE THREAD

**Issue by Hosch250** [rubberduck-vba/Rubberduck#596]
After you click OK in the settings window, everything reloads to (potentially) display the new language.  However, most of the items in RubberduckMenu.cs bust.

## Details:

All of the windows except for the Code Inspections open just fine.  Code Inspections throws an exception saying that the handler hasn't been created.

About, Settings, Test Explorer, Reorder Params, and Remove Params seem to work fine.

Rename doesn't open.

Todo Explorer and Code Explorer open, but do not show anything and refresh does not refresh the results, but doesn't cause a crash either.

Unloading and reloading the add-in works fine.

**Comment by Hosch250** [comment]
##Update:

Todo Explorer has the same issue as Code Inspections, but it is just contained in a `try { } catch { }` block:

    try
    {
        Cursor.Current = Cursors.WaitCursor;
        Control.TodoItems = await GetItems();
    }
    catch { }

Still not sure why - everything seems fine when I look at the debugger.

**Comment by ckuhn203** [comment]
Yikes! Empty ` Try...Catch`!
