### ISSUE TITLE
Manually link Add-In

### ISSUE THREAD

**Issue by nitricware** [rubberduck-vba/Rubberduck#5962]
My PC owner has a policy that purges anything from `AppData` (and probably other paths) that "doesn't belong" there on logout.

So I installed it on a drive that's not purged.

It works perfectly fine, until I log off from the machine. Which is done automatically after some hours.

After logging in again, the Add-In is not listed in Office anymore. I can run `Rubberduck.RegisterAddIn.reg` and it's listed again but Office can't find it and offers to remove it from the list.

What could I do to manually add the Add-In and link it to the correct path? (I.e. a `.bat` I run at login.)

Re-installing works fine. An unattended installation would therefore be a solution but not the preferred one. Is it even possible with the installer provided?

BTW: Installing Rubberduck to the default path instead of the other drive has the same result after a logoff. (I tried copying the files from the other drive to the default location after logoff and running the `.reg` afterwards.)

Thanks!

**Comment by bclothier** [comment]
Looking at the script, it’s likely that your machine has its registry reset in entirety and thus the script is not sufficient to fix the issue. As there are a LOT of registry entries that must be made for it to run, running the installer is probably the simplest method in such environment. [You can pass parameters for it to run quietly at login](
https://jrsoftware.org/ishelp/index.php?topic=setupcmdline).

**Comment by nitricware** [comment]
Thanks for the info, I guess the run-at-login method is the best.
