### ISSUE TITLE
Resolver Error

### ISSUE THREAD

**Issue by phobo3s** [rubberduck-vba/Rubberduck#5964]
**Rubberduck version information**
Version 2.5.2.6059
OS: Microsoft Windows NT 10.0.19044.0, x64
Host Product: Microsoft Office x86
Host Version: 16.0.14931.20132
Host Executable: EXCEL.EXE

Before anything i must say that it is the perfect project for my work. I am an civil engineer and i develop small apps for my work.
as you can guess there is not much collaboration on the subject.

**Description**
I have build an custom add-in for my work. there is plenty of things inside. Many different little procedures.
When i loaded my add-in and opened VBE editor, i get the resolver error and i can't use rubberduck.

**To Reproduce**
1.Load my add-in
2.Press Alt+F11

**Expected behavior**
Expecting the resolving attempt to be completed.

**Logfile**

https://github.com/rubberduck-vba/Rubberduck/files/8364209/RubberduckLog.txt

**Comment by daFreeMan** [comment]
Please upload the entire log to your original post. There may be things beyond what you're noting that impact the error.

**Comment by MDoerner** [comment]
I think the following line is to blame.
https://github.com/rubberduck-vba/Rubberduck/blob/a07fcac6b06b6fafcfb3e9a6065efc504a11e3ad/Rubberduck.Parsing/Symbols/Declaration.cs#L532
That blows up if the value assigned as `AsTypeDeclaration` is `null`. I guess we just have to add a `?` on the member access.
Maybe I can get to it this weekend.

**Comment by phobo3s** [comment]
am i have to change my variable declarations?

**Comment by MDoerner** [comment]
The PR above will quite certainly remove the resolver error. However, it is not clear to me how we could end up with a `null` there given how we parse. This should only ever be the `AsTypeDeclaration` for built-in types and the corresponding array types. However, them turning up here is somewhat unexpected. Accordingly, it would be interesting to know what kind of test was used after `As` in the declarations in the failed modules.

Moreover, I would be interested if there remain additional follow up problems after the symptomatic fix has been merged.
Accordingly, the PR will not automatically close this bug.

**Comment by phobo3s** [comment]
thank you. i dind't understand half of the things you said but it is solved. there is no parse error left. 
i think because of this error is early binding.

**Comment by MDoerner** [comment]
Good to hear the fix worked.

Could you show us some examples of the types (more precisely the text after _As_) you used for the variable declarations in one of the modules previously affected by the bug, e.g. from `TheBerk.ZWCADSubs`?
That would help us to understand how we ended up in the unexpected code path?

**Comment by phobo3s** [comment]
Dim isZwCad As Boolean
    Dim zcadApp As Object
    Dim zcadDoc As Object
    On Error Resume Next
    Set zcadApp = GetObject(, "ZWCAD.Application")
    'if no zwcad then try autocad
    If zcadApp Is Nothing Then
        Set zcadApp = GetObject(, "AutoCAD.Application.23")
        isZwCad = False
        If zcadApp Is Nothing Then Exit Sub
    Else
        isZwCad = True
    End If

I think this is the type of declaration that causes the error.
