### ISSUE TITLE
clear debug window

### ISSUE THREAD

**Issue by DonBorste** [rubberduck-vba/Rubberduck#5966]
**Justification**
A simple but embedded function to clear the debug window, at it's best by linking to a short-key

**Description**
The debug window is clear after execute the function over a short-key

**Additional context**

**Comment by Vogel612** [comment]
We are not the "owners" of the debug window, that's VBE native. The simple way to clear the immediate window is to just use: <key>Ctrl</key>+<key>A</key>, <key>del</key>. If you need to select the window beforehand that can be done with Ctrl+G.
