### ISSUE TITLE
Unhandled exception on exit

### ISSUE THREAD

**Issue by kimbar** [rubberduck-vba/Rubberduck#5972]
I get this every time I leave Excel.

Version 2.5.2.5906
OS: Microsoft Windows NT 10.0.19043.0, x64
Host Product: Microsoft Office 2016 x86
Host Version: 16.0.4266.1001
Host Executable: EXCEL.EXE

[unh_exc.txt](https://github.com/rubberduck-vba/RubberduckWeb/files/8520759/unh_exc.txt)

**Comment by Vogel612** [comment]
duplicates #5764
