### ISSUE TITLE
Code Inspection for Property/Function/Procedure not used  cannot be disabled

### ISSUE THREAD

**Issue by FullValueRider** [rubberduck-vba/Rubberduck#5973]
**Rubberduck version information**
Version 2.5.2.6062
OS: Microsoft Windows NT 10.0.22598.0, x64
Host Product: Microsoft Office x64
Host Version: 16.0.15028.20204
Host Executable: EXCEL.EXE

**Description**
I want to disable the Code Quality inspections for Property/Procedure/Function is not used.  However I can't do this as these items do not appear in the Rubberduck settings list for Code Quality Inspections

**Expected behavior**
If a rule appears in the Code inspections it should be possible to disable it

**Comment by BZngr** [comment]
The Code Quality inspection for 'Property/Procedure/Function is not used' is identified as "_Procedure is not referred to_" in the Code Inspection/Code Quality Settings list.  

Alternatively, if you select a flagged result for this (or any) inspection result in the Code Inspections window, a '_disable this inspection_' link is provided in the lower pane  which will also change the setting for the inspection to "Do Not Show".

**Comment by FullValueRider** [comment]
Thanks for the clarification.  In which case I'd argue that the text that appears in the code inspection pane be updated to reflect that  of the code inspection text in the code inspection settings pane or vice vera.  I'd prefer  'is not used' to 'is not referred to'
