### ISSUE TITLE
Source Control Buttons

### ISSUE THREAD

**Issue by Hosch250** [rubberduck-vba/Rubberduck#598]
A lot of the buttons throw exceptions (probably NRE's) when you are not in a repository.

**Comment by ckuhn203** [comment]
No comment. No commits. Just a closed issue???

**Comment by Hosch250** [comment]
https://github.com/retailcoder/Rubberduck/commit/b827df747a7e473b9f3601482f6f3d060d19caba
https://github.com/retailcoder/Rubberduck/commit/77d74739f7d4cedf53d82ab9ffd2962cfed97830
https://github.com/retailcoder/Rubberduck/commit/d19e22a0085244f6c3cf7116a5c3625e77de09cd

**Comment by Hosch250** [comment]
Not sure if we want to display a popup for this.  I just had it silently fail like all the other buttons.
