### ISSUE TITLE
Creating Source Control Branches

### ISSUE THREAD

**Issue by Hosch250** [rubberduck-vba/Rubberduck#599]
Creating branches hasn't worked twice, throwing an exception, and has worked twice.

**Comment by Hosch250** [comment]
No repo anymore.  My guess (about 98% sure) is I corrupted my SourceControl.rubberduck file before I figured out how to use it right, when it was busting on me all the time.

**Comment by Hosch250** [comment]
Oh, I fixed all the places it was busting before, so it should be good now.  Leaving open as tentatively fixed (needs more verification).

**Comment by ckuhn203** [comment]
Where's the related commit???

**Comment by Hosch250** [comment]
@ckuhn203 This is presumably fixed by all the commits previous to this that blocked buttons from failing in various ways - at least, it isn't happening anymore.  My best guess is that I corrupted my source control settings file somehow.

**Comment by Hosch250** [comment]
After working with Source Control some more, this either had to be trying to create a branch outside of a repo before I figured out how to use it, or a messed up config file from trying to open a non-existent repository.  Closing as general stupidity on my part.

**Comment by ckuhn203** [comment]
Those are situations we'll need to handle gracefully. I'm sure I didn't do much (*anything*) to handle them yet. They're good call outs. Let's keep this in mind as we move forward.
