### ISSUE TITLE
unexpected "Variable is used but not assigned" on array after ReDim

### ISSUE THREAD

**Issue by interservices** [rubberduck-vba/Rubberduck#5990]
Version 2.5.2.5906
OS: Microsoft Windows NT 10.0.22000.0, x64
Host Product: Microsoft Office x64
Host Version: 16.0.15225.20288
Host Executable: EXCEL.EXE
________________

I get two unexpected "Variable is used but not assigned" errors in this code:

```
Sub TEST()
    Dim i, arr
    ReDim arr(2)
    arr(0) = Array("aaa", "bbbb")
    arr(1) = Array("ccc", "dddd")
    arr(2) = Array("eee", "ffff")
    For i = LBound(arr) To UBound(arr) ' I get two "Variable 'arr' is used but not assigned." here
        '...
    Next
End Sub
```

I don't get the errors if I declare the array as fixed size without ReDim.

**Comment by SmileyFtW** [comment]
I don't know what is done in the loop, but it would seem to me that if `arr` isn't assigned (i.e not used on the right side of an equals sign) then doesn't that trigger this inspection? Using it as a counter isn't "assigning" anything.

**Comment by pricerc** [comment]
> Using it as a counter isn't "assigning" anything.

`ReDim` is assigning the _Bounds_ of the array. So `LBound(arr)` and `UBound(arr)` _have_ been assigned.
