### ISSUE TITLE
Rubberduck on Windows10 with Access2010

### ISSUE THREAD

**Issue by ntvmuc** [rubberduck-vba/Rubberduck#5998]
I'm using Rubberduck for Access2010 on Windows7. Now I have to change to Windows10. After Installing the actual version Rubberduck.Setup.2.5.2.5906.exe as Administrator, there is no choose with Addin-Manager in c:\Programmdata\Rubberduck. There are only Paths: cs - it - de - fr - installers. The Addin-Manager requires a accda or a accde-file.
Do you know what's wrong ?

**Comment by MDoerner** [comment]
From your description, I guess you are looking in the Access add-in manager. Can you open the VBE and look in its add-in manager?

**Comment by ntvmuc** [comment]
this was the solution. Inside the VBE, Rubberduck is loaded and startet. 
Thank you very much for your quickly help.
