### ISSUE TITLE
Smart Indent runs even on modules annotated with @NoIndent

### ISSUE THREAD

**Issue by pflugs30** [rubberduck-vba/Rubberduck#5999]
**Rubberduck version information**
Version 2.5.2.6059
OS: Microsoft Windows NT 10.0.19044.0, x64
Host Product: Microsoft Office x64
Host Version: 16.0.15330.20230
Host Executable: MSACCESS.EXE

**Description**
I added the `@NoIndent` attribute to the top of a module because it has hidden VB attributes (ref #5309).  However, I found that Rubberduck would still indent the module if I ran a right-click --> Rubberduck --> Indent --> Current Project.

**To Reproduce**
1. Add a new module.
2. Add some code that will be auto-indented.
3. Add the `@NoIndent` attribute.
4. Right-click --> Rubberduck --> Indent --> Current Project (or Current Module).
5. See that the code has now been indented.

**Expected behavior**
No matter how the Smart Indent is invoked, any code module annotated with `@NoIndent` should not be indented.

**Screenshots**
Code Before Indent:
```
'@NoIndent
Public Sub MyTest()
Debug.Print "Hello, there!"
End Sub
```

Code After Indent:
```
'@NoIndent
Public Sub MyTest()
    Debug.Print "Hello, there!"
End Sub
```

**Logfile**
I changed my log settings to **TRACE** prior to running the Indent, but I didn't see any logs after running the Smart Indent.

**Comment by Vogel612** [comment]
Did you reparse before requesting the indent?

**Comment by pflugs30** [comment]
Good question.  If by "reparse", you mean "clicked Rubberduck --> Refresh", then. yes, I did.  I pasted in the example text, saved the new Module (giving it a name), refreshed Rubberduck, and ran the indent.  I also tried a few other things, including compiling the project, changing the location of the attribute (meaning, at the very top of the file), etc.

**Comment by Greedquest** [comment]
Does the same thing happen if you change that to msgbox not debug.print . And also try adding `option explicit` below the annotation but above the sub. Sorry don't have a test machine to hand

**Comment by retailcoder** [comment]
Probably not a satisfactory solution, but as a work-around the hidden attributes should trigger [MissingMemberAnnotation](https://rubberduckvba.com/inspections/Details/MissingMemberAnnotation) inspection results for the member-level attributes, and [MissingModuleAnnotation](https://rubberduckvba.com/inspections/Details/MissingModuleAnnotation) for the module-level ones: these inspection results provide quickfixes to automatically add the appropriate annotations, and once the annotations are present and parsed Rubberduck would be able to issue [MissingAttribute](https://rubberduckvba.com/inspections/Details/MissingAttribute) inspection results for any attribute that might have been lost (with a quickfix to restore them), regardless of whether it was the Indenter or accidentally through some manual intervention.

**Comment by Greedquest** [comment]
(I can repro this) Excel Windows 11 latest rd pre-release

**Comment by pflugs30** [comment]
@retailcoder thanks for pointing that out.  I will add those attributes to all the modules with hidden VB Attributes.

@Greedquest thanks for confirming you can reproduce it.  I figured this issue would be a bug the team would worth mentioning.  I appreciate the two work arounds, and I will implement them both.
