### ISSUE TITLE
For info - Install instructions linked to suspect URL

### ISSUE THREAD

**Issue by joews** [rubberduck-vba/Rubberduck#6000]
The [most recent edit](https://github.com/rubberduck-vba/Rubberduck/wiki/Installing/_compare/d3597d17a6a5d29aedbf20441693ae5fe8883fec...a605404d7e0764326b03e74723e65f78dbcf6933) of the Install docs link to a suspect URL.

I have [reverted](https://github.com/rubberduck-vba/Rubberduck/wiki/Installing/_compare/a605404d7e0764326b03e74723e65f78dbcf6933...a83e6584e65a315c07e28fef1918c07fd78e06ba). Opening this issue to make the maintainers aware, and just in case the URL was intentional.

**Comment by retailcoder** [comment]
Thanks for spotting this, reverting it, and commenting here! This was most likely a wiki edit that went under the radar; sucks to have to do this, but I have now restricted wiki edits to GitHub users with push permissions to the repository... something like this shouldn't happen again.
