### ISSUE TITLE
"You can't open this location..."

### ISSUE THREAD

**Issue by tamasg** [rubberduck-vba/Rubberduck#6002]
Hello!

**Rubberduck version information**
The info below can be copy-paste-completed from the first lines of Rubberduck's log or the About box:

Version 2.5.2.5906
OS: Microsoft Windows NT 10.0.19043.0, x64
Host Product: Microsoft Office x64
Host Version: 16.0.15330.20230
Host Executable: EXCEL.EXE

**Description**
This always happens when exporting an active project. It exports, but this window pops up. It's very confusing.

**To Reproduce**
1. VBA Editor
2. Click on Rubberduck --> Tools --> Export Active Project

**Screenshots**
![Snag_4bd5c1](https://user-images.githubusercontent.com/5910815/179636057-65061a72-5a9b-43a0-a5c6-c28cfcdf0969.png)

Tamas

**Comment by daFreeMan** [comment]
* Is the path in question a network location or a local drive?
* Is this a personal machine or a corporate controlled machine?

I've run into issues over the last 12 months or so with my company clamping down on security and preventing me from doing many things with VBA when the file resides on a network drive, but still work if the file is on a local drive.

**Comment by INOPIAE** [comment]
Is the path to an OneDrive path?

**Comment by tamasg** [comment]
Hi,

not OneDrive, local drive, personal computer. C:\Users\USERNAME\source\GitHub\Excel-VBA

It's interesting that it stopped after two days. It works fine now when I created this issue tried several versions of Rubberduck.

Sorry, I haven't experienced this before. The error was probably in my environment, I don't even understand.

Thank you for your answers.
