### ISSUE TITLE
Feature suggestion: Line numbering

### ISSUE THREAD

**Issue by d1nuc0m** [rubberduck-vba/Rubberduck#6003]
**Justification**
By default VBE shows line/column number of the cursor position in the upper toolbar, it is not possible to see line numbers next to each line like in every modern IDE/text editor

**Description**
The ideal solution would be to implement proper line numbering in the UI, but I suspect this is not possible...
Even a tool to automatically insert line numbers in the code and update the existing ones would be nice (something like [this](https://www.automateexcel.com/vba-line-numbers/)).

**Comment by daFreeMan** [comment]
Dupe of #3269 (in which line numbering is vehemently argued _against_) and probably others.

**Comment by d1nuc0m** [comment]
> Dupe of #3269 (in which line numbering is vehemently argued _against_) and probably others.

Ok, closed as duplicate
