### ISSUE TITLE
Broken Hyperlinks at Wiki page VB, VBA, VBE and COM References

### ISSUE THREAD

**Issue by awb95** [rubberduck-vba/Rubberduck#6011]
see page: https://github.com/rubberduck-vba/Rubberduck/wiki/VB,-VBA,-VBE-and-COM-References

The Hyperlinks to the Microsoft pages:
- VBA language Specification
- Office VBA File Format Structure
must start with https:// instead of http://

The Tech Ed 2000 presentation seems to be dead.

Offline Office VBA Help Files leads to an archived repo with no content but maybe it's accessible through history.

**Comment by tommy9** [comment]
I've updated the wiki for the http to https change. Also updated the link for the offline office help files to the last revision before they were deleted and added a Wayback machine link for another dead link. I was able to address the Tech Ed presentation, although it was very slow
