### ISSUE TITLE
False Positive for Form Button / Control events

### ISSUE THREAD

**Issue by hecon5** [rubberduck-vba/Rubberduck#6013]
**Rubberduck version information**

Version 2.5.2.6062
OS: Microsoft Windows NT 10.0.19042.0, x64
Host Product: Microsoft Office x64
Host Version: 16.0.14931.20660
Host Executable: MSACCESS.EXE

**Description**
Code inspection shows "*so and so routine* is not used" for form control events (largely buttons, from what I can tell).

**To Reproduce**
1. Refresh code. 
![image](https://user-images.githubusercontent.com/54177882/185759987-70026d32-fa0d-4d02-a10f-5d27f6e39b74.png)

2. Look at Code Inspections
3. ![image](https://user-images.githubusercontent.com/54177882/185759921-671f7146-f76a-4683-b56e-b92a1c04df6d.png)
![image](https://user-images.githubusercontent.com/54177882/185759940-996c8e76-bb7d-4885-ac31-35ff09dbe1cd.png)

5. See error

**Expected behavior**
Routines with buttons should not throw this error. They did not used to in 1.x, from my memory.
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/9387785/RubberduckLog.txt)

**Screenshots**
See above.

**Logfile**
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/9387785/RubberduckLog.txt)

**Additional context**

**Comment by BZngr** [comment]
Duplicate #5924
