### ISSUE TITLE
Crash on initial load/refresh

### ISSUE THREAD

**Issue by ethanr-Dura** [rubberduck-vba/Rubberduck#6019]
**Rubberduck version information**
The info below can be copy-paste-completed from the first lines of Rubberduck's log or the About box:

    Rubberduck version [...]
    Operating System: [...]
    Host Product: [...]
    Host Version: [...]
    Host Executable: [...]

**Description**
When clicking the refresh button after first loading a project, the VBA Editor and Excel stop responding and a force close becomes necessary.

**To Reproduce**
1. Open the Visual Basic Editor
2. Load the vba project by clicking the Refresh button on any of the Rubberduck UI elements.
3. Loading symbol spins for about one second before freezing.

**Expected behavior**
Rubberduck refreshes and the project loads.

**Screenshots**
Screen Rubberduck is frozen on
![image](https://user-images.githubusercontent.com/67390654/189964787-44c895d8-8b22-4096-875b-b23642a6f193.png)

**Logfile**
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/9559322/RubberduckLog.txt)

Last line of log file:
2022-09-13 13:16:12.0518;TRACE-2.5.2.5906;Rubberduck.UI.Command.MenuItems.CommandBars.AppCommandBarBase;CancellationTokenSource was already disposed for OnParserStateChanged.;

**Additional context**
Been using Rubberduck with this workbook for a couple months without issue. Didn't make any significant changes outside of some simple edits to the code before this issue started.

**Comment by ethanr-Dura** [comment]
Determined the issue was with a single module in my workbook. If I deleted all the code from the module, Rubberduck could load the project without crashing. I could then paste the code back in, and refresh Rubberduck with out issues. After saving the workbook, this remained fixed.

Not sure if this should be closed since the bug still technically exists.

**Comment by daFreeMan** [comment]
Posting the code for that module (if you can) may help to identify the problem and find a solution.
