### ISSUE TITLE
Switching Source Control Branches

### ISSUE THREAD

**Issue by Hosch250** [rubberduck-vba/Rubberduck#602]
When you switch source control branches, Excel crashes.

**Comment by Hosch250** [comment]
Access violation exception here: https://github.com/retailcoder/Rubberduck/blob/68b257f3bd23438dd924a0db86d71e53abb444c6/RetailCoder.VBE/Extensions/VBComponentsExtensions.cs#L23

**Comment by retailcoder** [comment]
That's possibly because the `VBComponent` you're using, isn't the reference you think it is. This is an extension method, where is it called from?

**Comment by Hosch250** [comment]
Being called from here: https://github.com/retailcoder/Rubberduck/blob/68b257f3bd23438dd924a0db86d71e53abb444c6/RetailCoder.VBE/Extensions/VbProjectExtensions.cs#L61

**Comment by retailcoder** [comment]
That's another extension method - notice it extends `VBProject`. I bet if you go to the call site and compare the `VBProject` instance with any project loaded in the VBE, reference equality fails with every single one of them.

**Comment by Hosch250** [comment]
This returns true at the [call site](https://github.com/retailcoder/Rubberduck/blob/next/Rubberduck.SourceControl/SourceControlProviderBase.cs#L123): `ReferenceEquals(Project.VBE.ActiveVBProject, Project);`

**Comment by ckuhn203** [comment]
Can you provide exact steps for a repro? I didn't have any issues with this when I built and tested it prior to merging into next. I too am suspecting #592.

**Comment by Hosch250** [comment]
@ckuhn203 Just set up source control, add a branch, and try switching branches.  It happens every time, and started before I made a single commit.

**Comment by Hosch250** [comment]
I wonder if this is an x64 issue.  @ckuhn203 is on x86.  Can you check this out, @retailcoder?

**Comment by Hosch250** [comment]
So far, there are a couple possibilities.

1) This is an x64 issue.
2) This is an Office 2016 (Preview) issue.
3) It was broken in a later commit.

To resolve:

1) See if @retailcoder has the same issue, while @ckuhn203 doesn't.
2) If no one else has the issue, I can install a different version of Office and test again.
3) See if it still works for @ckuhn203.

**Comment by Hosch250** [comment]
This fails on x64 2013 too, but differently.  It throws an exception here:

[`c.Name == selection.QualifiedName.Component.Name`](https://github.com/rubberduck-vba/Rubberduck/blob/next/Rubberduck.VBEEditor/Extensions/VbeExtensions.cs#L19)

 -		Name	'((Microsoft.Vbe.Interop.VBComponent)(selection.QualifiedName.Component)).Name' threw an exception of type 'System.Runtime.InteropServices.COMException'	string {System.Runtime.InteropServices.COMException}
