### ISSUE TITLE
Source Control, going offline, and trashing repos

### ISSUE THREAD

**Issue by Hosch250** [rubberduck-vba/Rubberduck#603]
I went to work on one of the issues with using Source Control offline.  I had already set up Source Control for one document, so I figured I could open another document and start from there.  Surprisingly, RD automatically assigned all my documents to the same repo in Source Control.  So, you didn't give me a way to go back offline, so I closed Excel and trashed the repo in the File Explorer.  Now, Source Control doesn't even open.

**Comment by Hosch250** [comment]
Deleting the SourceControl.rubberduck file fixed this, but don't like doing this.

**Comment by Hosch250** [comment]
What I'd really like to happen here is to not auto-setup every doc on source control, and provide a way to remove individual repositories.

**Comment by ckuhn203** [comment]
What do you mean? Nothing gets "auto-setup". You have to create a repository from the active project for it to be attached to that project. I think maybe you created a repo from a project with the default "VBAProject" name. Then, when you created a new blank project (with a default name) RD got confused and said

> Oh look! We have a repository for that project!

There's an issue to prevent people from creating repositories before they've named their project, but we've also been considering using the filename as a unique identifier.

**Comment by Hosch250** [comment]
Oh, OK.  Thank you for the clarification.
