### ISSUE TITLE
Source Control - Creating branches

### ISSUE THREAD

**Issue by Hosch250** [rubberduck-vba/Rubberduck#604]
This blows up when you try to create a branch with the same name as an existing branch.

**Comment by ckuhn203** [comment]
I saw in chat you were having trouble with a test. It will need to set up the `_view.Local` property with a branch name and `_createView.UserInputText` with the same text. 

    //arrange
    var branchName = "dev";
    var branches = new List<string>() { branchName };

    _view.SetupProperty(v => v.Local, branches);
    _createView.SetupProperty(c => c.UserInputText, branchName);

    // simulate create branch button click
    _view.Raise(v => v.CreateBranch += null, new EventArgs());

    //assert
    Assert.IsFalse(_createView.Object.OkButtonEnabled);

On my phone, but that should be close. 

I would check the positive case too just to be thorough.

**Comment by Hosch250** [comment]
I have this test, which works (well, it passes, but it actually doesn't work):
    [TestMethod]
    public void CreateBranchViewBlocksBranchWithExistingName()
    {
        //arrange
        var branchName = "master";
        var branches = new List<string>() { branchName };

        _view.SetupProperty(v => v.Local, branches);
        _createView.SetupProperty(c => c.UserInputText, branchName);

        //act
        _createView.Raise(c => c.UserInputTextChanged += null, new EventArgs());

        //Assert
        Assert.IsFalse(_createView.Object.OkButtonEnabled);
    }

And this one, which fails:
    [TestMethod]
    public void CreateBranchViewAllowsBranchWithNonexistingName()
    {
        //arrange
        var existingBranchName = "master";
        var newBranchName = "bugBranch";
        var branches = new List<string>() { existingBranchName };

        _view.SetupProperty(v => v.Local, branches);
        _createView.SetupProperty(c => c.UserInputText, newBranchName);

        //act
        _createView.Raise(c => c.UserInputTextChanged += null, new EventArgs());

        //Assert
        Assert.IsTrue(_createView.Object.OkButtonEnabled);
    }

This method is hit (which actually works in the real thing):
        private void OnCreateBranchTextChanged(object sender, EventArgs e)
        {
            _createView.OkButtonEnabled = !string.IsNullOrEmpty(_createView.UserInputText) &&
                                          !_view.Local.Contains(_createView.UserInputText);
        }

I ran it through the debugger, like this:

        private void OnCreateBranchTextChanged(object sender, EventArgs e)
        {
            var okButtonEnabled = !string.IsNullOrEmpty(_createView.UserInputText) &&
                                          !_view.Local.Contains(_createView.UserInputText);

            _createView.OkButtonEnabled = !string.IsNullOrEmpty(_createView.UserInputText) &&
                                          !_view.Local.Contains(_createView.UserInputText);
        }

`okButtonEnabled` is set to `true`, but `_createView.OkButtonEnabled` is still set to `false`.

**Comment by ckuhn203** [comment]
We forgot to setup the `OkButtonEnabled` property. Add this in the "arrange" section. 

    _createView.SetupProperty(c => c.OkButtonEnabled);
