### ISSUE TITLE
Variable is used but not assigned - Variant Array ReDim

### ISSUE THREAD

**Issue by Energeer** [rubberduck-vba/Rubberduck#6052]
**Rubberduck version information**

    Rubberduck version [2.5.2.6080]
    Operating System: [Microsoft Windows NT 10.0.19044.0, x64]
    Host Product: [Microsoft Office x64]
    Host Version: [16.0.15726.20202]
    Host Executable: [EXCEL.EXE]

**Description**
Inspection false positive when assigning values to a variant array which has been ReDim'd.

**To Reproduce**

1. Causes "Variable 'Result' is used but not assigned.":
```
Public Function Test() As Variant
    Dim Result As Variant
    ReDim Result(0 To 0) As Variant
    Result(0) = "Value"
    Test = Result
End Function
```
2. Does not cause "Variable 'Result' is used but not assigned.": 
```
Public Function Test() As Variant
    Dim Result(0 To 0) As Variant
    Result(0) = "Value"
    Test = Result
End Function
```

**Expected behavior**
No "is used but not assigned" inspection

**Comment by 6DiegoDiego9** [comment]
I confirm the bug

![image](https://user-images.githubusercontent.com/109476941/211149578-f49284fc-b6aa-420f-9915-6f9f8e617c18.png)

**Comment by 6DiegoDiego9** [comment]
> This seems to be a duplicate of #5990, which is fixed since version 2.5.2.6140.

Ah sorry, I was misled by the fact that the homepage https://rubberduckvba.com/ reports and links to version 2.5.2.6059 as latest pre-release version.

**Comment by MDoerner** [comment]
Thanks for mentioning this. This is then a bug on the website synchronization.

**Comment by retailcoder** [comment]
Sort of... the new [test site](https://test.rubberduckvba.com) works fine and synchronizes on merge (via webhook); I need to grab a bunch of screenshots and write the content for all the feature pages that are still placeholders, and then the new site can go live and replace the old broken site.
