### ISSUE TITLE
harmonize `'@Folder` annotation position

### ISSUE THREAD

**Issue by Mo-Gul** [rubberduck-vba/Rubberduck#6054]
When inserting a non-test module the `'@Folder` annotation is _above_ the `Option Explicit` statement while when inserting a test module the `'@Folder` annotation is _below_ the `Option Explicit` statement.

This should be harmonized. (I am on v2.5.2.5906.)

**Comment by retailcoder** [comment]
Should be as simple as swapping the positions of `{{0}}` and `Option Explicit` in the module template string here:

https://github.com/rubberduck-vba/Rubberduck/blob/c5b603b7eea5329db939898f30fed595ca320ebd/Rubberduck.UnitTesting/CodeGeneration/TestCodeGeneratorStatics.cs#L119

**Comment by BZngr** [comment]
Related: `ExtractInterfaceRefactoringAction` also places annotations (including `Folder`) after `Option Explicit`.   And, the solution there looks fairly straightforward as well.

In function `ExtractInterfaceRefactoringAction.InterfaceModuleBody` the return statement:

`return $"{optionExplicit}{Environment.NewLine}{folderAnnotationText}{exposedAnnotationText}{interfaceAnnotationText}{Environment.NewLine}{interfaceMembers}";` would need to be adjusted as well.
