### ISSUE TITLE
The Big Refactoring: Dependency Injection w/ Inversion of Control Container

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#606]
Feature-freeze until this is completed. We need to implement proper DI/IoC and make the code *testable*, if not *tested*. No ifs, no buts.

**Comment by ckuhn203** [comment]
:+1: Let's hook up Ninject and get this done.

I'm leaving a reminder for myself here that [this][1] and [this][2] are prime targets for an IoC container.
Hell, the latter one is basically nothing more than a poor man's container...

[1]:https://github.com/rubberduck-vba/Rubberduck/blob/next/RetailCoder.VBE/UI/RubberduckMenu.cs#L143
[2}:https://github.com/rubberduck-vba/Rubberduck/blob/next/RetailCoder.VBE/UI/SourceControl/App.cs

**Comment by Hosch250** [comment]
:+1:

**Comment by retailcoder** [comment]
@ckuhn203 composition root code should go as close as possible to the entry point. For me, that's in [App.cs](https://github.com/rubberduck-vba/Rubberduck/blob/next/RetailCoder.VBE/UI/SourceControl/App.cs)

**Comment by ckuhn203** [comment]
Whatever the architecture, just know I want to see that mess of mine cleaned up. I'm glad you brought this up.

**Comment by retailcoder** [comment]
Eh, it was never going to happen without a feature-freeze and a kick in the nuts.

**Comment by retailcoder** [comment]
Merging of #756 closes this issue. Still quite a bit of work left to do though, to *reconnect* the features to their `ICommand` implementation. More issues coming up.
