### ISSUE TITLE
Inspection for conflicting name of Enum member and local variable

### ISSUE THREAD

**Issue by Energeer** [rubberduck-vba/Rubberduck#6062]
**What**
Rubberduck could warn when a local variable name conflicts with an Enum member name.

**Why**
If a module level const is defined and it's name conflicts with a local variable then the code _won't_ compile - a run-time error or bug is therefore _avoided_. If an Enum member is defined and it's name conflicts with a local variable then code _will_ compile - resulting in the risk of a run-time error or bug (unintended outcome) occurring.

The example below is very obvious however it can occur in less obvious circumstances: _"Naming is hard. Renaming is easy."_

**Example**
This code should trigger the inspection:

```vb
Option Explicit

Public Enum Number
    One = 1
    Two
End Enum

Public Sub PrintEnum(ByVal Number As Number)
    Debug.Print Number
End Sub

Public Sub PrintOne()
    Dim One As Long 'for some other purpose
    '...
    PrintEnum One '0 ...unintended outcome
End Sub

Public Sub PrintTwo()
    Dim Two As String 'for some other purpose
    '...
    PrintEnum Two 'Run-time error 13 - type mismatch
End Sub
```

---

**QuickFixes**
Perhaps a rename quick fix?

---

**Resources**
I don't know enough about this to suggest the right terminology for the resource strings.

**Comment by retailcoder** [comment]
IIRC the _shadowed declaration_ inspection isn't enabled by default, can you confirm this isn't a scenario that would be picked up by that inspection? I would expect it to be covered already.

**Comment by Energeer** [comment]
Aha yes - it's already covered then - I haven't enabled it. Cheers!

Learning new things every day!
