### ISSUE TITLE
DirectoryNotFoundExpection on new development system

### ISSUE THREAD

**Issue by INOPIAE** [rubberduck-vba/Rubberduck#6072]
**Rubberduck version information**
        TRACE-2.5.2.0;Rubberduck.Common.LogLevelHelper;
	Rubberduck version 2.5.2.0 loading:
	Operating System: Windows 10 Enterprise Evaluation 2009 x64 (Microsoft Windows NT 10.0.22000.0)
	Host Product: Microsoft Office x64
	Host Version: 16.0.15831.20208
	Host Executable: EXCEL.EXE;

**Description**
While debugging Rubberduck.Development with Excel as application on a new development system the directory c:\users\XXX\AppData\Roaming\Rubberduck\Templates is not found while switching in Excel to VBE.
After adding the directory manualy the error is not thrown anymore.

The error does not occur when running Excel directly.

**Screenshots**
![image](https://user-images.githubusercontent.com/2772829/211329471-e37ad5cf-6714-40cb-86c8-12da354bfa28.png)

**Comment by retailcoder** [comment]
Since there's no "get started" script and the deployment project deals with all the prerequisites it would make sense for that folder to be automatically created as part of deployment if it doesn't already exist.

**Comment by INOPIAE** [comment]
Where should the function go? Rubberduck.Core\App.cs
Should the path be a constant similar to Log_Folder_PATH?

**Comment by bclothier** [comment]
Note that it should be using this class to handle the path.

https://github.com/rubberduck-vba/Rubberduck/blob/51f2d139faf7c245b96e09bcd31b4424491dc186/Rubberduck.Core/Templates/TemplateFileHandler.cs#L28
