### ISSUE TITLE
Delete source control branch

### ISSUE THREAD

**Issue by Hosch250** [rubberduck-vba/Rubberduck#610]
Source control doesn't allow you to delete branches.

**Comment by ckuhn203** [comment]
[GitProvider supports it][1], so we just need to wire it up to the GUI. Should be an easy fix.

[1]:https://github.com/rubberduck-vba/Rubberduck/blob/next/Rubberduck.SourceControl/GitProvider.cs#L396

**Comment by ckuhn203** [comment]
All yours @Hosch250.

**Comment by Hosch250** [comment]
@ckuhn203 Would you mind assigning it to me?  I can't do that anymore since you removed my write access.

**Comment by ckuhn203** [comment]
Neither can I actually... It seems I can only assign to members with write access.

**Comment by Hosch250** [comment]
OK.
