### ISSUE TITLE
Code Obfuscation

### ISSUE THREAD

**Issue by daniellellouche** [rubberduck-vba/Rubberduck#6107]
**Justification**
Often VBA projects represent large investments, which need a little protection. Obfuscation is one of them although it is not fully hackproof

**Description**
In rubberduck menu, an item to get an option to obfuscate the project. During this process, the open workbook is copied in another version, same name with suffix xxx, which one is obfuscated. Idea is not to process the master workbook to simplify the maintenance later

**Comment by retailcoder** [comment]
This was discussed before; the consensus is that there is no reasonable way to do this correctly without employing shady methods that could get us flagged as malware, which we want to avoid at all costs (the InnoSetup installer script is already its own nightmare...). Also while Rubberduck is certainly a developer tool and an obfuscator would technically make sense as a feature, Rubberduck's philosophy places very heavy emphasis on readability and maintainability - two things that go against the very idea of code obfuscation; as such it was decided that obfuscation is out of scope for this project.
Consider using a trusted commercial obfuscator for this purpose.

**Comment by daniellellouche** [comment]
Thk anyway 😊

Cdt Daniel

XSBS, how to connect SAP and Excel
+41 78 892 04 68
________________________________
