### ISSUE TITLE
Saving XLA file with XLS is reverted when closing the files

### ISSUE THREAD

**Issue by hectorticoli** [rubberduck-vba/Rubberduck#6121]
**Rubberduck version information**
The info below can be copy-paste-completed from the first lines of Rubberduck's log or the About box:

	Rubberduck version 2.5.2.5906 loading:
	Operating System: Microsoft Windows NT 10.0.19045.0 x64
	Host Product: Microsoft Office 2016 x86
	Host Version: 16.0.5395.1000
	Host Executable: EXCEL.EXE;

**Description**
I have a .xls along with a .xla file. The 2 files are linked using latebinding (a method from the .xla is called when the .xls is opened). This is done this way to be able to retrieve xla from network if local copy is missing. If I open the .xls file, and modify code from the .xla file (automatically loaded), I can't save the file.

More precisely, the file is saved, but reverted when both files are closed. This does not happen when rubberduck is not installed. It is not mandatory to run a rubberduck "Refresh" to get this behavior.

**To Reproduce**
1. Get demo.xls and demo.xla in the same directory. 
![01](https://github.com/rubberduck-vba/Rubberduck/assets/22278738/2d123e74-b378-4c4d-9321-7b8b00bb003b)
2. If necessary wait up to a minute to make sure modify dates for both files are in the past
3. Open demo.xls, enabling macros 
![02](https://github.com/rubberduck-vba/Rubberduck/assets/22278738/76095440-ee89-44c7-aada-b8aed854abea)
4. Open VBA Editor
5. Update the text in ModuleBug.demo method to "Updated message"
![03](https://github.com/rubberduck-vba/Rubberduck/assets/22278738/818d5280-2c62-41e0-b899-e8fa463062d3)
6. Click on the save button from VBA Editor
![04](https://github.com/rubberduck-vba/Rubberduck/assets/22278738/1f67446b-83ee-4835-b557-8e6c80cfa865)
7. Check the dates of the files (xla file modify date is updated)
![05](https://github.com/rubberduck-vba/Rubberduck/assets/22278738/03854bb9-bae7-4f0e-8cb5-cd2b7f79faf0)
8. Close .xls file
9. The xla file modify date is back to initial value
![06](https://github.com/rubberduck-vba/Rubberduck/assets/22278738/9e1d217f-f679-417f-ba34-33850f52e96f)
10. Open .xls file again, enabling macros
11. The message displayed on opening isn't updated
![07](https://github.com/rubberduck-vba/Rubberduck/assets/22278738/b30a8e56-1cd4-4a56-b7af-806efb72d414)

**Expected behavior**
The .xla file remains saved when closing the .xls file

**Logfile**
Rubberduck generates extensive logging in TRACE-Level. If no log was created at `%APPDATA%\Rubberduck\Logs`, check your settings. Include this log for bug reports about the behavior of Rubberduck.

**Additional context**
I join demo .xls and .xla files with the logs, and the extract of each code module if you prefer to re-create the dataset.
[BugRubberDuck.zip](https://github.com/rubberduck-vba/Rubberduck/files/11869159/BugRubberDuck.zip)

**Comment by retailcoder** [comment]
I'm struggling to figure out exactly how Rubberduck is being involved here (other than being loaded), it looks more like it could be a glitch with the legacy .xla file format and/or Excel itself. Have you considered using the openxml .xlsm and .xlam file formats instead? Any bugfix or patch issued by Microsoft would presumably leave the legacy file formats alone.
