### ISSUE TITLE
Code Inspections options for actions to take is not displaying

### ISSUE THREAD

**Issue by MarkJohnstoneGitHub** [rubberduck-vba/Rubberduck#6133]
Version 2.5.9.6291
OS: Microsoft Windows NT 10.0.19045.0, x64
Host Product: Microsoft Office 2016 x64
Host Version: 16.0.5317.1000
Host Executable: MSACCESS.EXE

Updated to Version 2.5.9.6291 and must of cleared my code inspections that I disable/ignore.  When attempting to fix the it worked once then options aren't displaying to ignore once or ignore in module.  Appears restarting  MS-Access works and can fix a code inspection then no longer works. Refreshing code inspections doesn't fix it.

**To Reproduce**
1. Go to Code Inspections
2. Right Click on a code inspection

**Expected behavior**
Display various options available, which is displayed as blank.

![image](https://github.com/rubberduck-vba/Rubberduck/assets/45190970/348d601a-b13c-4509-8ce7-f4e3e96dbae3)

[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/12089700/RubberduckLog.txt)

**Comment by retailcoder** [comment]
.6294 (09/05) should have fixed this; can you confirm? Thanks!

**Comment by MarkJohnstoneGitHub** [comment]
@retailcoder Thanks.  Will take the plunge and update later tonight and confirm.  If any major issues ... going to pluck a duck. 🤣

**Comment by MarkJohnstoneGitHub** [comment]
@retailcoder Thought I posted a bug got for the pre-releasee upate.  Got an exception messsage as soon as I entered the VBE IDE looks like having duck for dinner!  Reinstalled Version 2.5.2.5906 which find the most stable version, thankgod got that tucked away.

**Comment by Vogel612** [comment]
@MarkJohnstoneGitHub does this still happen in the latest stable release?

**Comment by MarkJohnstoneGitHub** [comment]
> must of cleared my code inspections that I disable/ignore. When attempting to fix the it worked once then options aren't displaying to ignore once or ignore in module. Appea

@Vogel612 I think it was fixed in version .6294 (09/05) .  

Version 2.5.9.6316
OS: Microsoft Windows NT 10.0.19045.0, x64
Host Product: Microsoft Office 2016 x64
Host Version: 16.0.5417.1000
Host Executable: MSACCESS.EXE

Appears working.

**Comment by Vogel612** [comment]
Nice, that's great to hear :)
