### ISSUE TITLE
Code Inspection: Variable myTmpNode is not used is incorrect

### ISSUE THREAD

**Issue by FullValueRider** [rubberduck-vba/Rubberduck#6134]
**Rubberduck version information**
Version 2.5.2.6242
OS: Microsoft Windows NT 10.0.22631.0, x64
Host Product: Microsoft Office x64
Host Version: 16.0.16626.20068
Host Executable: EXCEL.EXE

**Description**
I get a ' Variable myTmpNode is not used' for the following code.

```
Private Sub RemoveAllItems()

    Dim myNode As SeqLNode
    Set myNode = s.Last
    
    Do Until myNode.Pred Is Nothing
    
        Dim myTmpNode As SeqLNode
        Set myTmpNode = myNode
        
        Set myNode = myNode.Pred
        Set myTmpNode = Nothing
        
    Loop
    
'    Set s.Last = Nothing
'    Set s.Root = Nothing
    s.Host.Count = 0
    
End Sub
```
The variable myTmpNode has an assigment so is clearly 'used'

**Expected behavior**
The explanation of the inspection is 'Variable is not referred to'.  This explanation probably requires updating to say the value of myTmpNode is never assigned to another variable, or something similar.

**Comment by retailcoder** [comment]
No-reads and no-writes are flagged by different inspections; "no used" refers to reads.

The variable is declared, assigned twice (first to myNode, then to Nothing), and indeed not being read.

As far as I can tell from the provided code, the inspection appears to be correct.
