### ISSUE TITLE
Annotations

### ISSUE THREAD

**Issue by pcarnet** [rubberduck-vba/Rubberduck#6138]
Can not add some annotations, for example, ModuleDescription: there is no way to add (write) the description.

**Comment by Crazylegs85** [comment]
Hi there...generally for the annotations you have to enclose the description in parenthesis and quotation marks.
```
'@ModuleDescription("Description of the module's purpose")
```

Have you had a look at the [annotations documentation](https://github.com/rubberduck-vba/Rubberduck/wiki/VB_Attribute-Annotations)?

**Comment by MDoerner** [comment]
I will close this as a duplicate of #6162, although that is actually the duplicate of this issue. However, the description there better conveys what the problem is.
