### ISSUE TITLE
Code Explorer expansion of class members crashing MS-Acccess

### ISSUE THREAD

**Issue by MarkJohnstoneGitHub** [rubberduck-vba/Rubberduck#6141]
**Rubberduck version information**
Version 2.5.2.5906
OS: Microsoft Windows NT 10.0.19045.0, x64
Host Product: Microsoft Office 2016 x64
Host Version: 16.0.5317.1000
Host Executable: MSACCESS.EXE

**Description**
When expanding a class in the Code Explorer crashes the application.
The CultureInfo.cls attached is the class causing the issue.  It contains the member GetCultureInfoByIetfLanguageTag containing the Obsolete annotation.  Removing the Obsolete annotation the Code Explorer no longer causes MS-Access to crash when expanding the class.  It appears the Obsolete annotation may be the cause of the issue.

```
'@Obsolete
'@Static
'@Description("Deprecated. Retrieves a read-only CultureInfo object having linguistic characteristics that are identified by the specified RFC 4646 language tag.")
Public Function GetCultureInfoByIetfLanguageTag(ByVal Name As String) As DotNetLib.CultureInfo
Attribute GetCultureInfoByIetfLanguageTag.VB_Description = "Deprecated. Retrieves a read-only CultureInfo object having linguistic characteristics that are identified by the specified RFC 4646 language tag."
   Set GetCultureInfoByIetfLanguageTag = this.DotNetLibCultureInfo.GetCultureInfoByIetfLanguageTag(Name)
End Function
```

**To Reproduce**
1. Go to Code Explorer
2. Click on the arrow next to the class module to epand
3. MS-Access crashes.

**Expected behavior**
The expansion of the class as per the image below. 
![image](https://github.com/rubberduck-vba/Rubberduck/assets/45190970/4f659ee6-aea3-4cbd-93ad-81cffe008b86)

**Screenshot before expanding the class causing MS-Access to crash**
![image](https://github.com/rubberduck-vba/Rubberduck/assets/45190970/e18dc485-335c-47c5-92f9-995bfa851aa0)

**Logfile**
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/12302553/RubberduckLog.txt)
[CultureInfo.cls.txt](https://github.com/rubberduck-vba/Rubberduck/files/12302588/CultureInfo.cls.txt)

**Comment by thefasquelle** [comment]
I have the same issue in excel with standard modules. 
Issue seems to be tied to the `@Obsolete` annotation. Removing the annotation allows to parse and expand without crashing. If I re-add the annotation RD will function properly until next app startup.

Here are two logs. 
- In the first one (with crash) the code contains obselete annotation
- In the second (no crash), I first remove the obsolete annotations, then pasrse and expand the code tree. I then re-add the annotations, parse again, fold and expand the tree -> no crash

[RubberduckLog_crash.txt](https://github.com/rubberduck-vba/Rubberduck/files/13389871/RubberduckLog_crash.txt)
[RubberduckLog_no_crash.txt](https://github.com/rubberduck-vba/Rubberduck/files/13389872/RubberduckLog_no_crash.txt)

Version 2.5.2.5906
OS: Microsoft Windows NT 10.0.19045.0, x64
Host Product: Microsoft Office 2016 x64
Host Version: 16.0.5413.1000
Host Executable: EXCEL.EXE


One funny thing is that when excel crashes due to this specific bug, at each app startup it will complain that it is not the default app for spreadsheet (although it is) until next windows reboot. It does not do that when crashing for other reasons

**Comment by MarkJohnstoneGitHub** [comment]
> I have the same issue in excel with standard modules. Issue seems to be tied to the `@Obsolete` annotation. Removing the annotation allows to parse and expand without crashing. If I re-add the annotation RD will function properly until next app startup.
> 
> Here are two logs.
> 
> * In the first one (with crash) the code contains obselete annotation
> * In the second (no crash), I first remove the obsolete annotations, then pasrse and expand the code tree. I then re-add the annotations, parse again, fold and expand the tree -> no crash
> 
> [RubberduckLog_crash.txt](https://github.com/rubberduck-vba/Rubberduck/files/13389871/RubberduckLog_crash.txt) [RubberduckLog_no_crash.txt](https://github.com/rubberduck-vba/Rubberduck/files/13389872/RubberduckLog_no_crash.txt)
> 
> Version 2.5.2.5906 OS: Microsoft Windows NT 10.0.19045.0, x64 Host Product: Microsoft Office 2016 x64 Host Version: 16.0.5413.1000 Host Executable: EXCEL.EXE
> 
> One funny thing is that when excel crashes due to this specific bug, at each app startup it will complain that it is not the default app for spreadsheet (although it is) until next windows reboot. It does not do that when crashing for other reasons

From memory definally an  issue with the @Obsolete annotation with the Code Explorer.  I had to painfully track down which member was causing the crash in a  class by slowly rebuilding it a member at a time.   Sure enough was about the last member to check.  Not sure if their planning  to address the issue as the Rubberduckies are busy with RD3.  I think changed it to  use custom annotation @Depreciated. For my .Net wrapper project tending not to implement obsolete members to  not encourrage their use so skirting around the potiential issue.  Recommend avoid using  the @Obsolete annotation until fixed.

**Comment by Vogel612** [comment]
@MarkJohnstoneGitHub can you confirm that the issue persists with version 2.5.91?

**Comment by MarkJohnstoneGitHub** [comment]
> @MarkJohnstoneGitHub can you confirm that the issue persists with version 2.5.91?

Currently using  version 2.5.9.6304 appears want to confirm the issue persists with [Rubberduck v2.5.91 (build 6316)](https://github.com/rubberduck-vba/Rubberduck/releases/tag/v2.5.91)  when take plunge later today or over Xmas and update will confirm.  

Appears got a few things to check if have been fixed in the latest update.  The Rubberduck elves have been busy. 😁

**Comment by MarkJohnstoneGitHub** [comment]
> @MarkJohnstoneGitHub can you confirm that the issue persists with version 2.5.91?

@Vogel612 

Using version  2.5.9.6316

Version 2.5.9.6316
OS: Microsoft Windows NT 10.0.19045.0, x64
Host Product: Microsoft Office 2016 x64
Host Version: 16.0.5417.1000
Host Executable: MSACCESS.EXE

Appears the issue still persists crashing Ms-Access when expanding the RD Code Explorer for a class containing a member with the @Obsolete annotation.
