### ISSUE TITLE
Unused variables in Code Quality window

### ISSUE THREAD

**Issue by paweston70** [rubberduck-vba/Rubberduck#6148]
**Rubberduck version information**
The info below can be copy-paste-completed from the first lines of Rubberduck's log or the About box:

    Version 2.5.9.6291
    OS: Microsoft Windows NT 10.0.19045.0, x64
    Host Product: Microsoft Office x64
    Host Version: 16.0.16626.20170
    Host Executable: MSACCESS.EXE

**Description**
When Rubberduck checks the code quality it reports some variables as not being used, when they clearly are.

**To Reproduce**
Obvious.

**Expected behavior**
The code should be examined in the whole of the current block before declaring a quality issue.

**Screenshots**
![image](https://github.com/rubberduck-vba/Rubberduck/assets/37217207/da345dfa-eb5b-4349-ab9b-f2ba6db23f58)

**Logfile**
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/12496650/RubberduckLog.txt)

**Comment by BZngr** [comment]
If a variable is written but never read, it is flagged by the inspection.  See also #6134

If `cbd` is ever read later within the method provided as an example, then it would be a bug.

**Comment by paweston70** [comment]
Apologies - you are absolutely right; I missed the variable later on in the code.
