### ISSUE TITLE
Uninstall not finished

### ISSUE THREAD

**Issue by RongePartner** [rubberduck-vba/Rubberduck#6154]
**Rubberduck version information**
Version 2.5.9.6294
Betriebssystem: Microsoft Windows NT 10.0.14393.0, x64
Hostprodukt: Microsoft Office x64
Hostversion: 16.0.14332.20546
Hostprogramm: MSACCESS.EXE

**Description**
Yesterday I uninstalled Rubberduck Version 2.5.9.6294.
Today I downloaded it again and installed it fresh. Then there will prompt two error-messages.

**To Reproduce**
1. Install on a clean Windows-installation
2. Uninstall
3. Start installer again
4. See error messages ...

**Expected behavior**
No error-messages

**Screenshots**
![RubberduckInstalling_1](https://github.com/rubberduck-vba/Rubberduck/assets/145337069/067da0bf-0696-4806-8301-0cdeeffe3c2c)
![RubberduckInstalling_2](https://github.com/rubberduck-vba/Rubberduck/assets/145337069/476e1213-9204-41dd-b98e-254a92a0a52c)

**Logfile**
There was no new logfile created. The old logfile still exists!

**Additional context**
--

**Comment by retailcoder** [comment]
If the original installation was done per-machine with administrative privileges, uninstalling per-user without administrative privileges cannot write to the machine registry to fully remove it.

Depends what options were selected for the installation, and whether you're logged in as a local administrator.

**Comment by RongePartner** [comment]
The original installation was done per-user (for me only). As I have a second account (domain admin) for administering my machine I have to run install and uninstall with administrative privileges.

**Comment by RongePartner** [comment]
Just installed the new release 2.5.9.6296. The error didn´t occur. It overwrote the old installation.
