### ISSUE TITLE
Popup error at startup

### ISSUE THREAD

**Issue by phramusca** [rubberduck-vba/Rubberduck#6156]
**Rubberduck version information**

Version 2.5.9.6291
OS: Microsoft Windows NT 10.0.22621.0, x64
Host Product: Microsoft Office x86
Host Version: 16.0.16130.20766
Host Executable: EXCEL.EXE

**Description**
Popup error at startup

**To Reproduce**
Open Excel vb editor

**Expected behavior**
No error

**Logfile**
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Threading.Tasks.TaskCanceledException: Une tâche a été annulée.

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Rubberduck
    Assembly Version: 2.5.9.6291
    Win32 Version: 2.5.9.6291
    CodeBase: file:///C:/Users/[User]/AppData/Local/Rubberduck/Rubberduck.dll
----------------------------------------
Microsoft.VisualStudio.Interop
    Assembly Version: 17.0.0.0
    Win32 Version: 17.0.31723.112
    CodeBase: file:///C:/Users/[User]/AppData/Local/Rubberduck/Microsoft.VisualStudio.Interop.DLL
----------------------------------------
NLog
    Assembly Version: 4.0.0.0
    Win32 Version: 4.5.10.8381
    CodeBase: file:///C:/Users/[User]/AppData/Local/Rubberduck/NLog.DLL
----------------------------------------
CrowdStrike.Sensor.ScriptControl
    Assembly Version: 6.58.17212.0
    Win32 Version: 6.58.17212.0
    CodeBase: file:///C:/WINDOWS/SysNative/CrowdStrike.Sensor.ScriptControl17212.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0

**Comment by vba-excel** [comment]
Duplicated issue:
Already reported on issue #6152
