### ISSUE TITLE
Microsoft .NET Framework Error for v2.5.9.6291

### ISSUE THREAD

**Issue by the1howie** [rubberduck-vba/Rubberduck#6159]
**Rubberduck version information**
The info below can be copy-paste-completed from the first lines of Rubberduck's log or the About box:

    Rubberduck version: 2.5.9.6291/4
    Operating System: Windows 11
    Host Product: Excel for Micorsoft 365
    Host Version: Version 2310 Build 16.0.16918.20002 64-bit
    Host Executable: [...]

**Description**
The first time that I install Rubberduck. See screenshots below for the warnings that I get. My Excel application just crashes i.e., does not open up again. I have to restart my whole machine and remove Rubberduck, for Excel app to work again.

**To Reproduce**
1. install rubberduck on Windows 11 / Excel for Microsoft 365.
2. open Excel
3. ALT+F11
4. Get the error in the first screenshot.
5. Close Excel
6. Get the error in the 2nd screenshot.
7. Try open Excel, nothing happens.

**Expected behavior**
I don't know what to expect, since this is the first time I'm trying to use rubberduck...

**Screenshots**
When opening VBIDE:
![image](https://github.com/rubberduck-vba/Rubberduck/assets/32492300/8a58d51b-c510-402e-9127-cfe2ce76fcff)

and when closing the Excel workbook:
![image](https://github.com/rubberduck-vba/Rubberduck/assets/32492300/29a4d024-bc3a-44cb-b92a-9f49a652ad10)

**Logfile**
Rubberduck generates extensive logging in TRACE-Level. If no log was created at `%APPDATA%\Rubberduck\Logs`, check your settings. Include this log for bug reports about the behavior of Rubberduck.

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Threading.Tasks.TaskCanceledException: A task was canceled.
```

**Additional context**

**Comment by retailcoder** [comment]
Hi! This should be fixed now with build .6296 from earlier this morning:
 https://github.com/rubberduck-vba/Rubberduck/releases/tag/Prerelease-v2.5.9.6296

**Comment by the1howie** [comment]
Thank you Mathieu! The new release works! :)

**Comment by the1howie** [comment]
Hi Mathieu @retailcoder ,
Sorry to bug you about this bug again :)
Opening the VBIDE with Rubberduck v2.5.9.6926 is working fine now, but closing Excel still gives the same error in the 2nd screenshot above. And Excel does not want to open up again. I still have to restart my machine to reopen Excel.

**Comment by retailcoder** [comment]
No worries!

The tear-down issues are a different problem that v3 will definitely have less of an issue with (state will be mostly held on the server side of things, and there will be far fewer native interactions and VBIDE hooking, all of which should help).
It's possible that upon shutting down, a "ghost" Excel process remains stuck in Task Manager (Ctrl+Shift+Esc) where it can be stopped manually. Killing the ghost process will free the (native) resources being held in a deadlock, which should allow you to then start another Excel process normally, without rebooting (a reboot is essentially taking a nuke to that ghost process).

**Comment by the1howie** [comment]
A-ha, brilliant! Thank you Mathieu, ending the "ghost" Excel process in Task Manager did the trick :) 
Awesome, thanks again for the speedy response. Looking forward to v3.

**Comment by vba-excel** [comment]
```
Version 2.5.9.6296
OS: Microsoft Windows NT 10.0.19044.0, x64
Host Product: Microsoft Office x64
Host Version: 16.0.13127.21216
Host Executable: EXCEL.EXE
```


I think this issue is still happenning.
Just got this error on Rubberduck 2.5.9.6296


![image](https://github.com/rubberduck-vba/Rubberduck/assets/58116485/4d875939-451e-453f-b349-e6529943f65b)

[RubberduckLog_GetCOMIPFromRCW.txt](https://github.com/rubberduck-vba/Rubberduck/files/12749828/RubberduckLog_GetCOMIPFromRCW.txt)

**Comment by Brian45Fr** [comment]
@retailcoder 
It's still the same thing and the same problem for months :-(
![image](https://github.com/rubberduck-vba/Rubberduck/assets/93922349/3f969ea3-10aa-4b62-b91e-0e046a297f35)

You should know that a colleague who has the same versions as me for Windows and Office does not have this error.
So what makes...

**Comment by retailcoder** [comment]
@Brian45Fr if the cause of the exception is the same reported here with build .6291, that's the version check feature blowing up without handling exceptions, confirmed as fixed in .6296; if you updated to .6296 and are still having this startup error, the underlying cause must be something else.
Can you confirm the Rubberduck version you're using is the same as your colleague's? .6296?
Thanks for the report!

**Comment by Brian45Fr** [comment]
@retailcoder 
Yes i confirm that the version is the same v2.5.9.629**6** (Edited)
I asked him if he could give me a list of software installed on his computer.

**Comment by retailcoder** [comment]
No need! Deactivating the version check on startup (you can find the settings file under `%appdata%/Rubberduck/Rubberduck.config`) should prevent the exception from being thrown in the first place (I really need to look into what the heck is going on with the API hosted on GoDaddy).
Installing build .6296 would fix the version check exception handling issue so the check can remain active without crashing the whole thing (it simply logs a warning instead).

**Comment by Brian45Fr** [comment]
@retailcoder 
I'm so sorry, I meant before that the version was the last and I still had the same problem and not my colleague
In config file -> general settings i have this

```xml
<GeneralSettings>
    <Language Code="fr" />
    <CanShowSplash>false</CanShowSplash>
    <CanCheckVersion>false</CanCheckVersion>
    <IncludePreRelease>false</IncludePreRelease>
    <CompileBeforeParse>true</CompileBeforeParse>
    <IsSmartIndenterPrompted>false</IsSmartIndenterPrompted>
    <IsAutoSaveEnabled>false</IsAutoSaveEnabled>
    <AutoSavePeriod>10</AutoSavePeriod>
    <UserEditedLogLevel>true</UserEditedLogLevel>
    <MinimumLogLevel>1</MinimumLogLevel>
    <SetDpiUnaware>false</SetDpiUnaware>
    <EnableFolderDragAndDrop>true</EnableFolderDragAndDrop>
    <EnableExperimentalFeatures />
  </GeneralSettings>
```

**Comment by retailcoder** [comment]
Hm in that case it looks like a COM issue, we've had that happen before (albeit somewhat unreliably) when other add-ins are installed. Could it be that?

**Comment by Brian45Fr** [comment]
First of all, thank you very much for your interest in my concern.
Is this the type of supplement you are talking about?
![image](https://github.com/rubberduck-vba/Rubberduck/assets/93922349/40490863-ebc1-4f53-84d8-558c5300c375)
I deactivated the first and last 2, restarted Excel, but that doesn't change anything
A+

**Comment by MDoerner** [comment]
This is similar, but not exactly what he referred to. There is a separate addins menu in the VBE. Usually, the addins with which we have compatibility issues are found there.

**Comment by Brian45Fr** [comment]
Ok, I have several supplements that I tested, but only 1 activated is Rubberduck
![image](https://github.com/rubberduck-vba/Rubberduck/assets/93922349/49fdd2ec-0f4c-4b86-8caa-e3ebef22bf19)
