### ISSUE TITLE
Unhandled exception within 10 seconds of loading into VBE.

### ISSUE THREAD

**Issue by KySoto** [rubberduck-vba/Rubberduck#6160]
**Rubberduck version information**
The info below can be copy-paste-completed from the first lines of Rubberduck's log or the About box:

Version 2.5.9.6291
OS: Microsoft Windows NT 10.0.19045.0, x64
Host Product: Microsoft Office x86
Host Version: 16.0.16731.20234
Host Executable: MSACCESS.EXE

**Description**
when I open the VBE, rubber duck crashes. I suspect an incompatibility with office 365. I checked my log folder, and the last log was from july 2023.

**To Reproduce**
1. Open VBE
2. Wait 1-10 seconds
3. rubber duck has an unhandled exception

**Expected behavior**
i open the VBE and i dont have an unhandled exception.

**Screenshots**
![image](https://github.com/rubberduck-vba/Rubberduck/assets/835408/6c779a31-22cc-43cc-8425-fcf106c8bce4)

**Logfile**
Rubberduck generates extensive logging in TRACE-Level. If no log was created at `%APPDATA%\Rubberduck\Logs`, check your settings. Include this log for bug reports about the behavior of Rubberduck.
my last log file was from back in july. i'll include it just in case it might help somehow.

[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/12719745/RubberduckLog.txt)

[errormessage.txt](https://github.com/rubberduck-vba/Rubberduck/files/12719742/errormessage.txt)

EDIT: im a dummy i forgot to set the logging level to trace. i have a log.
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/12719785/RubberduckLog.txt)

**Additional context**

**Comment by retailcoder** [comment]
Fixed in .6294 released this morning 😇
(see #6159)

**Comment by MDoerner** [comment]
Is this fixed an can be closed?
