### ISSUE TITLE
Insert Annotation update:  Act when Rubberduck cannot parse

### ISSUE THREAD

**Issue by FullValueRider** [rubberduck-vba/Rubberduck#6165]
**Justification**
I often run into the situation where I have set an annotation but Rubberduck cannot apply the Annotation because there is a parsing error which is due to the absence of the (usually class) attribute related to the annotation.   This is a significant irritation, particularly when trying to Rubberduck existing VBA,  the workaround for which is to export the affected class, add the relevant attributes by hand and then reimport.

**Description**
I'm therefore requesting that the right click insert annotation is updated to allow an annotation and its corresponding attribute to be inserted even when Rubberduck cannot parse.  This seems to be a straightforward editing enhancement.

**Comment by MDoerner** [comment]
This is actually not as straightforward as it sounds. All code changed Rubberduck performs are based on manipulating the parse tree we get from parsing the module. Accordingly, we cannot perform these actions if we fail to parse.

Could you give an example where these failures to parse happen? The absence of an attribute should not make the parser fail.

**Comment by FullValueRider** [comment]
This may be a consequence of the way in which I now use create classes.  I now invariable create class with a built in factory method and set that factory method to be the default member.  This allows VBA to more closely emulate other languages when instancing a class.

for example if I defined a class as a collection Wrapper (wCollection) I would then typically be able to write
```
Dim myC as wCollection: set myc=wCollection.Deb  ' where Deb is the factory method
```
If I'm adding a class to a project which is already failing to compile (and where the attempt at compilation crashes Excel) and which rubberduck cannot parse, then I have to manually export the wCollection class to set the attibutes otherwise wCollection will become another Debug error until rubberduck can parse.

I've attached a rather large excel workbook which kind of demonstrates this issue.  Trying to debug.compile crashes excel (on my PC at least - 64 bit excel 365, 32 gb, Ryzen 3700X) and Rubberduck stops with a Parse error.  The best solution I've found to date is to export the project then import into twinBasic.

[oldVBALib.zip](https://github.com/rubberduck-vba/Rubberduck/files/13062716/oldVBALib.zip)

**Comment by MDoerner** [comment]
Do I understand that the problem at hand is that adding attributes for annotations does not work in a module if _another_ module does not parse?

If you add a class as above in a project that parses before, it still parses, right? Hm, it might not _resolve_, though? Does RD state that it has a parser error or a resolver error?

**Comment by FullValueRider** [comment]
In the case of the zip file I posted its a parse error.  I'm sorry to be the cause of problems as I though this would be very simple to implement as Rubberduck would basically be doing the equivalent of export project then use notepad++ to search and replace for the relevant attribute across all files'  This is what I have to do for the creatable attribute when I export the project to VBA.

**Comment by MDoerner** [comment]
In principle, we could add the missing attributes if only the module itself parses and the declarations therein resolve. However, we have implemented this as a pair of inspection and quickfix and we never run inspections unless we have clean parsing and resolution run.

Accordingly, I do not think this will come to RD2 anymore. However, we should keep in mind for RD3 to run inspections depending on the type of info they need. E.g. inspections needing resolved members in a module should run whenever these are available, no matter whether parsing or resolution fails somewhere else.

**Comment by FullValueRider** [comment]
And as if by magic

https://www.thevbahelp.com/vbe-extras-download.  Allows attributes to be set from within VBA via a menu choice.

**Comment by Vogel612** [comment]
I'm classifying this as declined, since it would involve a complete restructure of how Rubberduck works internally.

That is quite out of scope for Rubberduck2 and instead informs our interaction model for Rubberduck3
