### ISSUE TITLE
Latest Rubberduck version 2.5.9.6291 - throws error concerning JIT debugger

### ISSUE THREAD

**Issue by akrlsh** [rubberduck-vba/Rubberduck#6174]
**Rubberduck version information**
The info below can be copy-paste-completed from the first lines of Rubberduck's log or the About box:

Version 2.5.9.6291
OS: Microsoft Windows NT 10.0.19045.0, x64
Host Product: Microsoft Office x64
Host Version: 16.0.16924.20124
Host Executable: MSACCESS.EXE

**Description**
MS Access database => DataBase Tools => Visual Basic 

An Error Box pops up and tells me that a task has stopped / failed.
I use the same on Windows 11 in the same database ; here it does work without issues.

--
Part of the log when clicking Details...

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Threading.Tasks.TaskCanceledException: A task was canceled.

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Rubberduck
    Assembly Version: 2.5.9.6291
    Win32 Version: 2.5.9.6291
    CodeBase: file:///C:/Users/reint/AppData/Local/Rubberduck/Rubberduck.dll
----------------------------------------
Microsoft.VisualStudio.Interop
    Assembly Version: 17.0.0.0
    Win32 Version: 17.0.31723.112
    CodeBase: file:///C:/Users/reint/AppData/Local/Rubberduck/Microsoft.VisualStudio.Interop.DLL
----------------------------------------
..
----------------------------------------
System.Dynamic.DynamicAssembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.9037.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: 13.0.1.25517
    CodeBase: file:///C:/Users/reint/AppData/Local/Rubberduck/Newtonsoft.Json.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

===
The previous version which I had installed worked properly:
Rubberduck.Setup.2.5.2.5906

...

**To Reproduce**
1.  Open a DataBase
2.  Click on Database Tools > Visual Basic
3.  Wait -- the error message appears

Microsoft .NET Framework
Unhandled exception..

**Expected behavior**

**Screenshots**

![image](https://github.com/rubberduck-vba/Rubberduck/assets/100513473/35a7644b-4ed5-4229-a90c-8943da395ead)

**Logfile**
Rubberduck generates extensive logging in TRACE-Level. If no log was created at `%APPDATA%\Rubberduck\Logs`, check your settings. Include this log for bug reports about the behavior of Rubberduck.

Please advise what to do?
thanks
Reint

**Comment by akrlsh** [comment]
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/13241897/RubberduckLog.txt)
Accompanying log-file

**Comment by retailcoder** [comment]
Hi, thanks for the report! This is a known issue with release 2.5.9; pre-release build .6304 should fix this.
A new release will be packaged soon to bring the fix into the main branch.
Cheers!

**Comment by Vogel612** [comment]
Duplicates #6152
