### ISSUE TITLE
Rubberduck->Tools->Import Saved Project (restore all backup source code modules/forms/classes)

### ISSUE THREAD

**Issue by lube-it** [rubberduck-vba/Rubberduck#6177]
**Justification**

There is not import all source code modules/forms function that was saved before in the Rubberduck.

**Description**

Need a plus function in Rubberduck Tools, Import Backup Project...
This is tool for import all stored source code modules from a selected file directory.

**Additional context**

![Import tool for Rubberduck](https://github.com/rubberduck-vba/Rubberduck/assets/67216620/6c7bd072-e9a6-48b8-8430-16b8bc1ccb10)

**Comment by retailcoder** [comment]
I believe this functionality was implemented in the Code Explorer context menu, see  http://rubberduckvba.blog/2020/12/11/sync-project-with-files/

![image (2).png](https://github.com/rubberduck-vba/Rubberduck/assets/5751684/4b3572ed-5ad0-40b4-88da-3453313f3638)
