### ISSUE TITLE
Timestamp annotation OR Just insert/paste Timestamp

### ISSUE THREAD

**Issue by 5TjpWBU2wkwHpFDb** [rubberduck-vba/Rubberduck#6179]
Often, I do not have access to proper version control: I need a timestamp.
I believe that I want a context menu item to add/paste a Timestamp annotation OR Just insert/paste Timestamp.

**Comment by Vogel612** [comment]
This is the sort of crutch that Rubberduck is opinionated against, since we're explicitly exposing "Export Project" as a means for version control.
