### ISSUE TITLE
Add a comment to selected lines of code

### ISSUE THREAD

**Issue by sberruti** [rubberduck-vba/Rubberduck#6201]
**Justification**
sometimes I have to replace several lines of code with new ones and I don't want to delete the pre-existing ones, so I make them become annotations by adding a ' at the beginning of the line.

**Description**
I want to select some lines of code and add a ' at the beginning

**Additional context**
could be added in Refactoring

**Comment by FullValueRider** [comment]
That's already part of the VBA ide. View.Toolbar.edit.

**Comment by retailcoder** [comment]
Side note, "Comment/Uncomment Selected Lines" is definitely a planned editor feature in v3.0 ☺️

**Comment by Vogel612** [comment]
retriaging in v3, should be part of the basic editor experience
