### ISSUE TITLE
Export / Import to various folders

### ISSUE THREAD

**Issue by Deedolith** [rubberduck-vba/Rubberduck#6213]
**Justification**
Hello,

For now, the export / import project functionalities assumes that all files are within the same folder, wich can be confusing when accessing the files from a file explorer.

**Description**
I suggest to add the possibility to dispatch the source code in custom folders / subfolders when exporting the project.
The idea is to segregate the main code from test code.
Of course the reverse operation is desirable.
(eventually, go a step further and export / import the folder structure shown in the code explorer).

**Additional context**
This is to accomodate with source code managment third party software and plateforms, such as GitHub.

**Comment by retailcoder** [comment]
There's an open issue somewhere about honoring the `@Folder` annotations when exporting, however without somewhere to hold the information about where the files are, importing could get messy with the ability to recursively import files from any folder hierarchy out there.
The metadata could be in the host document, but then the implementation becomes host-dependent. Or it could be in a "comment module", but then it would pollute every project RD touches with such a not-a-module, which isn't desirable.
RD3 is going to solve this by introducing workspaces, which are exactly that: a folder hierarchy with the metadata for the project, stored on the file system in a host-agnostic way.

**Comment by Vogel612** [comment]
solved by v3 paradigm shift
