### ISSUE TITLE
Inspection fails due to resolver error

### ISSUE THREAD

**Issue by SevC10** [rubberduck-vba/Rubberduck#6218]
**Rubberduck version information**

Version 2.5.9.6316
OS: Microsoft Windows NT 10.0.19045.0, x64
Host Product: Microsoft Office x64
Host Version: 16.0.17726.20078
Host Executable: EXCEL.EXE

**Description**
Rubberduck fails to parse a specific function in a module, and so the inspection fails, even if the VBA compiler compiles the code without problems.
The module containing the function that is failing:

    Option Explicit

    #If Mac Then

        #If VBA7 Then
        
            ' 64-bit Mac (2016)
            Private Declare PtrSafe Function utc_popen Lib "/usr/lib/libc.dylib" Alias "popen" _
                (ByVal utc_Command As String, ByVal utc_Mode As String) As LongPtr
            Private Declare PtrSafe Function utc_pclose Lib "/usr/lib/libc.dylib" Alias "pclose" _
                (ByVal utc_File As LongPtr) As LongPtr
            Private Declare PtrSafe Function utc_fread Lib "/usr/lib/libc.dylib" Alias "fread" _
                (ByVal utc_Buffer As String, ByVal utc_Size As LongPtr, ByVal utc_Number As LongPtr, ByVal utc_File As LongPtr) As LongPtr
            Private Declare PtrSafe Function utc_feof Lib "/usr/lib/libc.dylib" Alias "feof" _
                (ByVal utc_File As LongPtr) As LongPtr
        
        #Else
        
            ' 32-bit Mac
            Private Declare Function utc_popen Lib "libc.dylib" Alias "popen" _
                (ByVal utc_Command As String, ByVal utc_Mode As String) As Long
            Private Declare Function utc_pclose Lib "libc.dylib" Alias "pclose" _
                (ByVal utc_File As Long) As Long
            Private Declare Function utc_fread Lib "libc.dylib" Alias "fread" _
                (ByVal utc_Buffer As String, ByVal utc_Size As Long, ByVal utc_Number As Long, ByVal utc_File As Long) As Long
            Private Declare Function utc_feof Lib "libc.dylib" Alias "feof" _
                (ByVal utc_File As Long) As Long
        
        #End If

    #ElseIf VBA7 Then

        Private Declare PtrSafe Function utc_GetTimeZoneInformation Lib "kernel32" Alias "GetTimeZoneInformation" _
            (utc_lpTimeZoneInformation As utc_TIME_ZONE_INFORMATION) As Long
        Private Declare PtrSafe Function utc_SystemTimeToTzSpecificLocalTime Lib "kernel32" Alias "SystemTimeToTzSpecificLocalTime" _
            (utc_lpTimeZoneInformation As utc_TIME_ZONE_INFORMATION, utc_lpUniversalTime As utc_SYSTEMTIME, utc_lpLocalTime As utc_SYSTEMTIME) As Long
        Private Declare PtrSafe Function utc_TzSpecificLocalTimeToSystemTime Lib "kernel32" Alias "TzSpecificLocalTimeToSystemTime" _
            (utc_lpTimeZoneInformation As utc_TIME_ZONE_INFORMATION, utc_lpLocalTime As utc_SYSTEMTIME, utc_lpUniversalTime As utc_SYSTEMTIME) As Long

    #Else

        Private Declare Function utc_GetTimeZoneInformation Lib "kernel32" Alias "GetTimeZoneInformation" _
            (utc_lpTimeZoneInformation As utc_TIME_ZONE_INFORMATION) As Long
        Private Declare Function utc_SystemTimeToTzSpecificLocalTime Lib "kernel32" Alias "SystemTimeToTzSpecificLocalTime" _
            (utc_lpTimeZoneInformation As utc_TIME_ZONE_INFORMATION, utc_lpUniversalTime As utc_SYSTEMTIME, utc_lpLocalTime As utc_SYSTEMTIME) As Long
        Private Declare Function utc_TzSpecificLocalTimeToSystemTime Lib "kernel32" Alias "TzSpecificLocalTimeToSystemTime" _
            (utc_lpTimeZoneInformation As utc_TIME_ZONE_INFORMATION, utc_lpLocalTime As utc_SYSTEMTIME, utc_lpUniversalTime As utc_SYSTEMTIME) As Long

    #End If

    #If Mac Then

        #If VBA7 Then
            Private Type utc_ShellResult
                utc_Output As String
                utc_ExitCode As LongPtr
            End Type
        
        #Else
            Private Type utc_ShellResult
                utc_Output As String
                utc_ExitCode As Long
            End Type
        
        #End If

    #Else

        Private Type utc_SYSTEMTIME
            utc_wYear As Integer
            utc_wMonth As Integer
            utc_wDayOfWeek As Integer
            utc_wDay As Integer
            utc_wHour As Integer
            utc_wMinute As Integer
            utc_wSecond As Integer
            utc_wMilliseconds As Integer
        End Type
        
        Private Type utc_TIME_ZONE_INFORMATION
            utc_Bias As Long
            utc_StandardName(0 To 31) As Integer
            utc_StandardDate As utc_SYSTEMTIME
            utc_StandardBias As Long
            utc_DaylightName(0 To 31) As Integer
            utc_DaylightDate As utc_SYSTEMTIME
            utc_DaylightBias As Long
        End Type

    #End If

    Public Function ParseUtc(utc_UtcDate As Date) As Date
        On Error GoTo utc_ErrorHandling

    #If Mac Then
        ParseUtc = utc_ConvertDate(utc_UtcDate)
    #Else
        Dim utc_TimeZoneInfo As utc_TIME_ZONE_INFORMATION
        Dim utc_LocalDate As utc_SYSTEMTIME

        utc_GetTimeZoneInformation utc_TimeZoneInfo
        utc_SystemTimeToTzSpecificLocalTime utc_TimeZoneInfo, utc_DateToSystemTime(utc_UtcDate), utc_LocalDate

        ParseUtc = utc_SystemTimeToDate(utc_LocalDate)
    #End If

        Exit Function

    utc_ErrorHandling:
        Err.Raise 10011, "UtcConverter.ParseUtc", "UTC parsing error: " & Err.Number & " - " & Err.Description
    End Function

    Public Function ParseIso(utc_IsoString As String) As Date
        On Error GoTo utc_ErrorHandling

        Dim utc_Parts() As String
        Dim utc_DateParts() As String
        Dim utc_TimeParts() As String
        Dim utc_OffsetIndex As Long
        Dim utc_HasOffset As Boolean
        Dim utc_NegativeOffset As Boolean
        Dim utc_OffsetParts() As String
        Dim utc_Offset As Date

        utc_Parts = VBA.Split(utc_IsoString, "T")
        utc_DateParts = VBA.Split(utc_Parts(0), "-")
        ParseIso = VBA.DateSerial(VBA.CInt(utc_DateParts(0)), VBA.CInt(utc_DateParts(1)), VBA.CInt(utc_DateParts(2)))

        If UBound(utc_Parts) > 0 Then
            If VBA.InStr(utc_Parts(1), "Z") Then
                utc_TimeParts = VBA.Split(VBA.Replace(utc_Parts(1), "Z", ""), ":")
            Else
                utc_OffsetIndex = VBA.InStr(1, utc_Parts(1), "+")
                If utc_OffsetIndex = 0 Then
                    utc_NegativeOffset = True
                    utc_OffsetIndex = VBA.InStr(1, utc_Parts(1), "-")
                End If

                If utc_OffsetIndex > 0 Then
                    utc_HasOffset = True
                    utc_TimeParts = VBA.Split(VBA.Left$(utc_Parts(1), utc_OffsetIndex - 1), ":")
                    utc_OffsetParts = VBA.Split(VBA.Right$(utc_Parts(1), Len(utc_Parts(1)) - utc_OffsetIndex), ":")

                    Select Case UBound(utc_OffsetParts)
                    Case 0
                        utc_Offset = TimeSerial(VBA.CInt(utc_OffsetParts(0)), 0, 0)
                    Case 1
                        utc_Offset = TimeSerial(VBA.CInt(utc_OffsetParts(0)), VBA.CInt(utc_OffsetParts(1)), 0)
                    Case 2
                        ' VBA.Val does not use regional settings, use for seconds to avoid decimal/comma issues
                        utc_Offset = TimeSerial(VBA.CInt(utc_OffsetParts(0)), VBA.CInt(utc_OffsetParts(1)), Int(VBA.Val(utc_OffsetParts(2))))
                    End Select

                    If utc_NegativeOffset Then: utc_Offset = -utc_Offset
                Else
                    utc_TimeParts = VBA.Split(utc_Parts(1), ":")
                End If
            End If

            Select Case UBound(utc_TimeParts)
            Case 0
                ParseIso = ParseIso + VBA.TimeSerial(VBA.CInt(utc_TimeParts(0)), 0, 0)
            Case 1
                ParseIso = ParseIso + VBA.TimeSerial(VBA.CInt(utc_TimeParts(0)), VBA.CInt(utc_TimeParts(1)), 0)
            Case 2
                ' VBA.Val does not use regional settings, use for seconds to avoid decimal/comma issues
                ParseIso = ParseIso + VBA.TimeSerial(VBA.CInt(utc_TimeParts(0)), VBA.CInt(utc_TimeParts(1)), Int(VBA.Val(utc_TimeParts(2))))
            End Select

            ParseIso = ParseUtc(ParseIso)

            If utc_HasOffset Then
                ParseIso = ParseIso - utc_Offset
            End If
        End If

        Exit Function

    utc_ErrorHandling:
        Err.Raise 10013, "UtcConverter.ParseIso", "ISO 8601 parsing error for " & utc_IsoString & ": " & Err.Number & " - " & Err.Description
    End Function

    #If Mac Then

    Private Function utc_ConvertDate(utc_Value As Date, Optional utc_ConvertToUtc As Boolean = False) As Date
        Dim utc_ShellCommand As String
        Dim utc_Result As utc_ShellResult
        Dim utc_Parts() As String
        Dim utc_DateParts() As String
        Dim utc_TimeParts() As String

        If utc_ConvertToUtc Then
            utc_ShellCommand = "date -ur `date -jf '%Y-%m-%d %H:%M:%S' " & _
                "'" & VBA.Format$(utc_Value, "yyyy-mm-dd HH:mm:ss") & "' " & _
                " +'%s'` +'%Y-%m-%d %H:%M:%S'"
        Else
            utc_ShellCommand = "date -jf '%Y-%m-%d %H:%M:%S %z' " & _
                "'" & VBA.Format$(utc_Value, "yyyy-mm-dd HH:mm:ss") & " +0000' " & _
                "+'%Y-%m-%d %H:%M:%S'"
        End If

        utc_Result = utc_ExecuteInShell(utc_ShellCommand)

        If utc_Result.utc_Output = "" Then
            Err.Raise 10015, "UtcConverter.utc_ConvertDate", "'date' command failed"
        Else
            utc_Parts = Split(utc_Result.utc_Output, " ")
            utc_DateParts = Split(utc_Parts(0), "-")
            utc_TimeParts = Split(utc_Parts(1), ":")

            utc_ConvertDate = DateSerial(utc_DateParts(0), utc_DateParts(1), utc_DateParts(2)) + _
                TimeSerial(utc_TimeParts(0), utc_TimeParts(1), utc_TimeParts(2))
        End If
    End Function

    Private Function utc_ExecuteInShell(utc_ShellCommand As String) As utc_ShellResult
    #If VBA7 Then
        Dim utc_File As LongPtr
        Dim utc_Read As LongPtr
    #Else
        Dim utc_File As Long
        Dim utc_Read As Long
    #End If

        Dim utc_Chunk As String

        On Error GoTo utc_ErrorHandling
        utc_File = utc_popen(utc_ShellCommand, "r")

        If utc_File = 0 Then: Exit Function

        Do While utc_feof(utc_File) = 0
            utc_Chunk = VBA.Space$(50)
            utc_Read = CLng(utc_fread(utc_Chunk, 1, Len(utc_Chunk) - 1, utc_File))
            If utc_Read > 0 Then
                utc_Chunk = VBA.Left$(utc_Chunk, CLng(utc_Read))
                utc_ExecuteInShell.utc_Output = utc_ExecuteInShell.utc_Output & utc_Chunk
            End If
        Loop

    utc_ErrorHandling:
        utc_ExecuteInShell.utc_ExitCode = CLng(utc_pclose(utc_File))
    End Function

    #Else

    Private Function utc_DateToSystemTime(utc_Value As Date) As utc_SYSTEMTIME
        utc_DateToSystemTime.utc_wYear = VBA.Year(utc_Value)
        utc_DateToSystemTime.utc_wMonth = VBA.Month(utc_Value)
        utc_DateToSystemTime.utc_wDay = VBA.Day(utc_Value)
        utc_DateToSystemTime.utc_wHour = VBA.Hour(utc_Value)
        utc_DateToSystemTime.utc_wMinute = VBA.Minute(utc_Value)
        utc_DateToSystemTime.utc_wSecond = VBA.Second(utc_Value)
        utc_DateToSystemTime.utc_wMilliseconds = 0
    End Function

    Private Function utc_SystemTimeToDate(utc_Value As utc_SYSTEMTIME) As Date
        utc_SystemTimeToDate = DateSerial(utc_Value.utc_wYear, utc_Value.utc_wMonth, utc_Value.utc_wDay) + _
            TimeSerial(utc_Value.utc_wHour, utc_Value.utc_wMinute, utc_Value.utc_wSecond)
    End Function

    #End If

**To Reproduce**
1. Copy the module in a VBA project
2. Launch or refresh Rubberduck inspection
3. The inspection fails with resolver error

**Expected behavior**
The inspection should terminate without error; no issue was raised with previous Rubberduck version.

**Screenshots**
![immagine](https://github.com/rubberduck-vba/Rubberduck/assets/87227699/8ed1b1e4-20af-40b6-bf65-cf354397d24a)

**Logfile**
[RubberduckLog.txt](https://github.com/user-attachments/files/15969878/RubberduckLog.txt)

Thanks!
Severino

**Comment by tommy9** [comment]
This looks like it is the same issue as #6187. The latest pre-release version of RubberduckVBA has a fix for this, so that would be the best option if you are okay with that.

**Comment by SevC10** [comment]
Just installed the pre-release version (2.5.9.6321) and the problem is solved! The resolver runs without problem and the inspection is correctly completed!
I did read older similar issues, but I didn't try the pre-release version.
Thank you very much for your help!

Severino
