### ISSUE TITLE
Resolver Error after Importing VBA-JSON

### ISSUE THREAD

**Issue by naiguylikespi** [rubberduck-vba/Rubberduck#6220]
**Rubberduck version information**
The info below can be copy-paste-completed from the first lines of Rubberduck's log or the About box:

Version 2.5.9.6316
OS: Microsoft Windows NT 10.0.19044.0, x64
Host Product: Microsoft Office x86
Host Version: 16.0.17726.20160
Host Executable: EXCEL.EXE

**Description**
Rubberduck goes into Resolver Error state when JsonConverter module ( https://github.com/VBA-tools/VBA-JSON ) is imported and RD is refreshed. 

Log file seems to indicate a problem is encountered at line 1018 of the JsonConverter module with a mismatched 'End Function' but the module works fine when used in a project.

**To Reproduce**
1. Import JsonConverter.bas from the VBA-JSON project into any working VBA project.
2. JsonConverter depends on VBA-Dictionary ( https://github.com/VBA-tools/VBA-Dictionary ), so import that .cls file as well to ensure the project compiles.
3. Refresh Rubberduck.
4. Rubberduck goes into Resolver Error state.

**Expected behavior**
Rubberduck should successfully refresh on working code. 

**Logfile**
[RubberduckLog.txt](https://github.com/user-attachments/files/16285937/RubberduckLog.txt)

**Comment by tommy9** [comment]
Hi, this was a known issue with the last major release. If you can install the [latest pre-release version](https://github.com/rubberduck-vba/Rubberduck/releases), it should be fixed. Same as #6202

**Comment by naiguylikespi** [comment]
Thanks! I tried searching for anything to do with the issue, but for some reason that didn't come up. Seems to have fixed the issue.
