### ISSUE TITLE
Increase Memory

### ISSUE THREAD

**Issue by smokeypete** [rubberduck-vba/Rubberduck#6221]
Hi there,

Apologies as I am sure this will have been asked before, but I couldn't find any earlier posts. Is it possible to run Excel/Rubberduck with increased memory? When running complex tests it is forever giving me Out of Memory errors.

Thanks,

Pete

**Comment by Vogel612** [comment]
There is the "Large-Address-Aware" mode for Excel which is automatically enabled for Office 2013 and later. Other than that, there is unfortunately no way to allocate additional memory. Rubberduck 3.0 will work around this problem by running its memory-intensive tasks in a separate process that doesn't need to share its address space with all the other stuff that the VBE has sitting around (let alone the whole document you're working on).

See also the discussion on #3347
