### ISSUE TITLE
Rubberduck doesn't find anything when it's scanning

### ISSUE THREAD

**Issue by Rovo1211** [rubberduck-vba/Rubberduck#6227]
**Rubberduck version information**
The info below can be copy-paste-completed from the first lines of Rubberduck's log or the About box:

    Rubberduck version 2.5.9.6316
    Operating System: Windows 11 Home 23H2
    Host Product: Excel VBE 7.1
    Host Version:  Excel 365
    Host Executable: [...]

**Description**
When I refresh the window of the Code Explorer, it doesn't find anything. I've tried many things to solve it, but so far no result. Sometimes it finds FUNCRES.XLAM, but no other things although there are more files open.

**To Reproduce**
1. Go to menu Rubberduck
2. Click on 'Refresh'

**Expected behavior**
A clear and concise overview of all MY objects in the Excel file
![Rubberduck, Code Inspector](https://github.com/user-attachments/assets/e27fc332-52e5-4ac4-b140-094d1e8d8d7d)
![Rubberduck, Code Explorer](https://github.com/user-attachments/assets/b827dd88-b02a-444f-8a5d-da6bbc1afbe4)
[RubberduckLog.txt](https://github.com/user-attachments/files/17748809/RubberduckLog.txt)
.

**Screenshots**

**Logfile**
Rubberduck generates extensive logging in TRACE-Level. If no log was created at `%APPDATA%\Rubberduck\Logs`, check your settings. Include this log for bug reports about the behavior of Rubberduck.

**Additional context**

**Comment by Rovo1211** [comment]
Only one time Rubberduck has worked PERFECTLY. After that time it didn't find anything to show although there was a file open with at least 20 macros, forms, etc.
Why it doesn't display the third level as in "@Folder("Aandelen/Update/Declaraties")?

**Comment by Vogel612** [comment]
Are you certain that the file fully parses as is? The Logs suggest there is a syntax error in "Aandelen_Update". If that is the case, Rubberduck basically disables most of its features to not accidentally break anything ...

**Comment by Rovo1211** [comment]
That is what Rubberduck is for: to find errors in your code and correct it. If Rubberduck already falls about syntax-errors...

**Comment by retailcoder** [comment]
> That is what Rubberduck is for.

No. Rubberduck has always assumed the code it's looking at is legal code that VBA can compile and run. We strive to ensure any legal VBA code can be correctly processed, but it's the compiler's job to produce the executable P-Code and report any errors that might occur while doing so; Rubberduck (or any other tool) literally cannot do the compiler's job without being a compiler itself.

**Comment by Vogel612** [comment]
Judging by the follow-up issues you opened that both expect rubberduck to work off code that does not compile, that was the underlying issue here as well. Closing for the same reason. The underlying paradigm for Rubberduck is that we **need** code that parses correctly, otherwise we could irrecoverably break user code, which is unacceptable. To prevent that, we instead severely limit Rubberduck's functionality until the code we are supposed to analyze parses.

**Comment by Rovo1211** [comment]
If a functionallity is working perfectly, DON’T put in the program till it does!!!!!

 

Van: Clemens Lieb ***@***.***> 
Verzonden: vrijdag 6 december 2024 23:05
Aan: rubberduck-vba/Rubberduck ***@***.***>
CC: Rovo1211 ***@***.***>; Author ***@***.***>
Onderwerp: Re: [rubberduck-vba/Rubberduck] Rubberduck doesn't find anything when it's scanning (Issue #6227)

 

Judging by the follow-up issues you opened that both expect rubberduck to work off code that does not compile, that was the underlying issue here as well. Closing for the same reason. The underlying paradigm for Rubberduck is that we need code that parses correctly, otherwise we could irrecoverably break user code, which is unacceptable. To prevent that, we instead severely limit Rubberduck's functionality until the code we are supposed to analyze parses.
