### ISSUE TITLE
Missing"End with" quits functionallity Rubberduck

### ISSUE THREAD

**Issue by Rovo1211** [rubberduck-vba/Rubberduck#6229]
**Rubberduck version information**
The info below can be copy-paste-completed from the first lines of Rubberduck's log or the About box:

    Rubberduck version 2.5.9.6321
    Operating System: Windows 11 Home 23H2
    Host Product: MS Excekl
    Host Version: Office365
    Host Executable: Excel.exe

**Description**
The Rubberduck parser completely fails to parse a project when an End With statement is missing. This small mistake causes parsing issues and prevents essential features like Code Explorer and Code Inspections from functioning. While the error is correctly displayed in the Parse Errors window (after clicking the red cross in the Parser Status), this behavior blocks the rest of the project from being processed.

**To Reproduce**
Create a macro with this code
[code]
sub TestWithBlock
with Thisworkbook
.save
' Missing"End with"
End sub
[/Code]
Execute the parser, you get a red cross next to the parser. Click on it and you get the position of the error.

![Parse Error(s)](https://github.com/user-attachments/assets/d375e11d-e4c7-4808-a454-084ed56d263b)

**Expected behavior**
A Code Explorer which is finding my "@-annotations.
 
**Screenshots**
![Parse Error(s) 24-12-06, 11h40](https://github.com/user-attachments/assets/a9680f5d-a86c-4426-96f4-de5a9595977a)

**Logfile**
Rubberduck generates extensive logging in TRACE-Level. If no log was created at `%APPDATA%\Rubberduck\Logs`, check your settings. Include this log for bug reports about the behavior of Rubberduck.
[RubberduckLog.txt](https://github.com/user-attachments/files/18036893/RubberduckLog.txt)

**Additional context**
The parser should mark the missing End With as a non-critical error in the Parse Errors window but continue parsing the rest of the module and project. Code Explorer and Code Inspections should remain accessible for error-free modules.
Current Behavior

    The parser completely halts when a missing End With is encountered.
    A red cross appears in the Parser Status.
    The Parse Errors window correctly reports the error, including its location (module, line, and context).
    Code Explorer and Code Inspections remain completely empty, even for modules without errors.

Impact

    This behavior makes Rubberduck less reliable and not user-friendly for working with large projects, as one small error blocks the functionality of the entire add-in.
    Users are forced to manually fix the error before accessing vital tools like Code Explorer.

Proposed Solution

    Update the parser to treat a missing End With as a non-critical error in the Parse Errors window.
    Allow the parser to continue processing the rest of the project so that features like Code Explorer and Code Inspections remain functional.
    Add a clear warning to the Parse Errors window, such as:
        "Missing 'End With' statement in Sub TestWithBlock."

Environment

    Rubberduck version: 2.5.9.6321
    Operating System: Windows 11 Home, version 23H2
    Host Program: Microsoft Excel 16.0.18129.20158 (64-bit)

Why This Improvement Is Important

Rubberduck is designed to handle large and complex projects. Completely halting the parsing process due to a small mistake like a missing End With undermines its reliability and makes it not user-friendly. Treating such small mistakes as non-critical errors will allow Rubberduck to remain functional and suitable for real-world projects.

**Comment by IvenBach** [comment]
Any time there is non-compileable code Rubberduck's functionality is disabled intentionally. The current design of version 2.x.y.z relies on compileable code to function properly ensuring there won't be any problems when Rubberduck does its magic. The next version, being worked on by the other ducks, shouldn't have this limitation.
