### ISSUE TITLE
Conflicting/redundant TODO markers are allowed

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#637]
This configuration is perfectly valid:

    <ToDoListSettings>
      <ToDoMarkers>
        <ToDoMarker Text="NOTE:" Priority="Low" />
        <ToDoMarker Text="TODO:" Priority="Normal" />
        <ToDoMarker Text="BUG:" Priority="High" />
        <ToDoMarker Text="NOTE:" Priority="Normal" />
        <ToDoMarker Text="NOTE:" Priority="Low" />
        <ToDoMarker Text="NOTE:" Priority="High" />
      </ToDoMarkers>
    </ToDoListSettings>

...and doesn't make any sense. TODO Explorer just seems to grab the first matching marker; TODO Settings shouldn't allow dupicate markers.

**Comment by ckuhn203** [comment]
Lol. Oh wow. It never occurred to me before. I wonder how well a dictionary will serialize.

**Comment by ckuhn203** [comment]
Good work on the UI @Hosch250. :+1: 
I'll fix the config.
