### ISSUE TITLE
Refactor QualifiedModuleName

### ISSUE THREAD

**Issue by rubberduck203** [rubberduck-vba/Rubberduck#639]
> ```
> /// <summary>
> /// Represents a VBComponent or a VBProject.
> /// </summary>
> ```

A smell if there ever was one. Different parts of the struct can be null depending on which ctor is used to create it. A struct should always be valid upon creation. We're in need of a `QualifiedProjectName` extracted from this file. 

https://github.com/rubberduck-vba/Rubberduck/blob/next/Rubberduck.VBEEditor/QualifiedModuleName.cs

Having it will make it easier to get the TestExplorer under test.

**Comment by retailcoder** [comment]
This is **exactly** why I put that XML comment you're quoting right there.

This struct needs to become a class, and we need an actual class hierarchy here, something like:

 - `QualifiedProjectName` (although that does sound a bit weird)
 - `QualifiedModuleName : QualifiedProjectName`
 - `QualifiedMemberName : QualifiedModuleName`

This is obviously a dangerous thing to do, and ripples pretty much everywhere in the code base.

**Comment by ckuhn203** [comment]
Then let's wait until after 1.4 releases.

**Comment by Vogel612** [comment]
The proposed hierarchy really seems weird and there are `QualifiedMemberName` and `QualifiedModuleName` structs... in what way would they break?

**Comment by retailcoder** [comment]
That was forever ago... pretty sure `ProjectId` appeared after this issue was created; `QualifiedProjectName` wouldn't make sense now.

**Comment by Vogel612** [comment]
after some short (cough 2 hours) investigation, it seems that to really fix this, the whole mess that is `Declaration` will need to be properly tackled ... Which is a **major** rewrite, that's apparently been necessary for ["since forever"](https://chat.stackexchange.com/transcript/message/41197046#41197046)
