### ISSUE TITLE
Document Breaking Changes to Config

### ISSUE THREAD

**Issue by ckuhn203** [rubberduck-vba/Rubberduck#645]
Localization and the change to priority levels has broken the config. We need to alert users to this on release.

The old mid level priority for todo markers was "Normal", it is now "Medium".

**Comment by Hosch250** [comment]
I'm guessing this is mostly irrelevant at this point since we are over half a year away from both the initial 1.4 release latest release (1.4.3).

**Comment by retailcoder** [comment]
@Hosch250 correct.
