### ISSUE TITLE
Create/Delete/Merge branch views should be inline, not forms

### ISSUE THREAD

**Issue by ckuhn203** [rubberduck-vba/Rubberduck#662]
Create controls that can be added to the SourceControlPanel rather than the current dialog boxes.

**Comment by retailcoder** [comment]
I'd keep that for the WPF redesign; forms are good enough for now no?

**Comment by ckuhn203** [comment]
Good enough, yeah. Let's leave it open for the WPF migration though.

**Comment by Hosch250** [comment]
Will be done in WPF display shortly.

**Comment by Hosch250** [comment]
Done in my branch.
