### ISSUE TITLE
Code Explorer reports 'Parsing' and never indicates completion

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#674]
When I open an Excel project and open the _Code Explorer_ window, I get the following:
![rd1](https://cloud.githubusercontent.com/assets/11889733/8432133/2992af64-1f0c-11e5-9eba-832622fa3723.PNG)
It will remain that way for 15 minutes or more. (Note that the last `VBAProject` listed is my actual code for this project - it's since been properly renamed.)
If I close and re-open the _Code Explorer_ window, it appears blank:
![rd1 5](https://cloud.githubusercontent.com/assets/11889733/8432161/4866dd52-1f0c-11e5-9b3d-a22948c651ef.PNG)
Opening the _Code Inspections_ window shows a _very_ quick parse, then displays issues. Closing and reopening the _Code Explorer_ then displays the properly parsed project.

This particular Workbook has 13 worksheets with a few, short subs/functions on 2 worksheets, 1500 lines of code in _ThisWorkbook_ and 2 class modules with 173 lines of code in one and 727 lines of code in the other (in case that matters).

I cannot post the workbook as it contains company confidential information.

**Comment by daFreeMan** [comment]
I have the `Smart Indenter v3.5` and `MZ-Tools 3.0` add-ins installed. 

Disabling them has not improved the situation. Uninstalling them doesn't help either.

**Comment by retailcoder** [comment]
The bug causing this has been fixed, but if the resolver crashes, the UI will behave the same way. Keeping this issue opened, and tagging with [user-interface].
