### ISSUE TITLE
Code Inspections incorrectly picking up Private variables as unassigned/unused

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#675]
The _Code Inspections_ window is incorrectly claiming that variables are not being used in a class, when they are, in fact, being used in the Getter & Letter.
![rd never used](https://cloud.githubusercontent.com/assets/11889733/8433087/b93b3a46-1f11-11e5-99a1-6b50ad372d23.PNG)

This could be due to the `NullReferenceException` generated if _Code Inspections_ is the first of the RD windows to be opened in a newly opened Excel workbook. (See Issue: #676)

**Comment by retailcoder** [comment]
I need to repro this one... I *think* it might have been related to #676/#674, but can't confirm. This is going to be fun.
