### ISSUE TITLE
RemoveParameterRefactoring shouldn't allow removal of the only param in a setter.

### ISSUE THREAD

**Issue by ckuhn203** [rubberduck-vba/Rubberduck#690]
Consider the following VBA code.

    Private Property Set Foo(ByVal arg1 As Integer) 
    End Property

Removing it's only parameter makes the setter.... well, useless.

    Private Property Set Foo()
    End Property

And upon further inspection, uncompilable.  A Setter requires at least one param, although, they *can* have more and we should allow others to be removed. Just not all of them.

**Comment by Hosch250** [comment]
This only happens when there is no getter.  Will fix tomorrow.

**Comment by Hosch250** [comment]
Also applies to letters.
