### ISSUE TITLE
False Positive in Code Inspections on "Procedure {x} is never used"

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#697]
I have a `Public Function` declared in a class module. The function is called from a `Sub` located in `ThisWorkbook`, but the function is flagged `Procedure {x} is never used`.

Declaration & Error:
![rd15 07 08](https://cloud.githubusercontent.com/assets/11889733/8572256/6fb0ffde-2559-11e5-9ccc-ba55df793223.PNG)

Use:

![rd15 07 08-2](https://cloud.githubusercontent.com/assets/11889733/8572259/770136f0-2559-11e5-8f6e-09cc5816a511.PNG)

**Comment by retailcoder** [comment]
Is `Clinics.LastYearScore` correctly resolved as a reference to `ProcessClinic.LastYearScore`? If you right-click the function's name in the `ProcessClinic` class (i.e. in its signature), and select "find all references".. do you get any references outside the function itself?

**Comment by daFreeMan** [comment]
No, I do not.

**Comment by retailcoder** [comment]
Congratulations, you found a bug in the resolver! :clap:

**Comment by daFreeMan** [comment]
:bow:

**Comment by retailcoder** [comment]
Let's try something. Extract a local variable for `Clinics.LastYearScore` at the call site, and use that local variable in the `SetTableCell` call instead.

I would expect the inspection to now pick up the reference to the function at the assignation of the local variable, and... *possibly* the local variable might be picked up as *not used*.

I'm curious about the other member calls made in the surrounding code - why `LastYearScore` and not the other members?

**Comment by daFreeMan** [comment]
I believe this is what you were after, and it still doesn't find it:
![rd15 07 08-3](https://cloud.githubusercontent.com/assets/11889733/8573081/c7fb123e-255d-11e5-9a2d-673d530ef4a7.PNG)

Also, `LastYearScore` was an example, not an anomaly. It finds 9 functions in use, but those are _within_ the Class. It finds 14 _not_ in use, but they're used _outside_ the class.
![rd15 07 08-4](https://cloud.githubusercontent.com/assets/11889733/8573159/2769dd90-255e-11e5-99ae-281a64fb7ad6.PNG)
Yellow highlight are the `Not used`, red line are `used`.
![rd15 07 08-5](https://cloud.githubusercontent.com/assets/11889733/8573445/94982c4a-255f-11e5-993e-97a3da316d2e.PNG)

**Comment by retailcoder** [comment]
This is a serious issue that affects refactorings. I'll need to figure out how to repro.

**Comment by retailcoder** [comment]
Resolver has been completely rewritten since this issue was brought up. Closing.
