### ISSUE TITLE
Code Inspections sort order not maintained on refresh

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#698]
Sort _Code Inspections_ grid by `Issue`
Click `Refresh` button
_CI_ window returns to default sort order
_However_, clicking on `Issue` column header again now gets a _reverse_ sort, so it was aware of what its last sort order was.

**Comment by Hosch250** [comment]
Issue also applies to todo and test explorers.

**Comment by retailcoder** [comment]
Declining this issue, as code inspections will be displayed in a WPF TreeView in 2.0:

![image](https://cloud.githubusercontent.com/assets/5751684/10141036/46086e14-65d8-11e5-8645-57b4fedfb426.png)
