### ISSUE TITLE
The fix for "Member {x} is implicitly Public" isn't fixing it.

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#699]
This code is in a `worksheet`:

```VBA
Sub CreateMail()

Dim objOutlook As Object
Dim objMail As Object

Set objOutlook = CreateObject("Outlook.Application")
Set objMail = objOutlook.CreateItem(0)

With objMail
    .To = "recipient"
    .Subject = "Automated messaging"
    .body = "test message"
    .send
End With

Set objOutlook = Nothing
Set objMail = Nothing

End Sub
```

Clicking the `Fix` button to resolve the `Member 'CreateMail' is implicitly Public` Warning doesn't seem to do anything but trigger a refresh. In particular, it did _not_ add `Public` to the beginning of the declaration. This seems to be an issue with 

- both `Sub` and `Function`
- both attached to a specific worksheet or in `ThisWorkbook`
- both with and without parameters. 

<sup>Yes, I know the code isn't particularly useful. I saw it go by on SO and grabbed it, tested to make sure we could use it in our network, and have left it stored here for future reference. Not the best way, I'm sure, but it's working for me as a template. So sue me.</sup>

**Comment by Hosch250** [comment]
No repo here.

**Comment by retailcoder** [comment]
Yup, fixed.
