### ISSUE TITLE
Option to sort Code Explorer alphabetically

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#703]
It's handy being able to click on a method name in the _Code Explorer_ and go directly to the method, but it's not particularly easy to _find_ the method when they're listed in the order declared within the code. It would make life much easier if the _CE_ could be sorted alphabetically.

Possibilities could include:
- Sort purely by name
- Sort  by name within object type
 - all constants by alpha,
 - then all globals by alpha,
 - then all methods by alpha, etc

Possibly implemented withing the configuration options, but a more user-friendly method would be a 'Sort` button at the top of the _CE_ pane with a drop down giving the various options.

**Comment by retailcoder** [comment]
I like that. We also need a "rearrange members" feature.

**Comment by ckuhn203** [comment]
Far too lazy to go find it right this second, but I think this might be a dupe.

**Comment by ckuhn203** [comment]
I was thinking of #267, but I thought that was done already. Did we lose something along the way, or am I just hopelessly confused?

**Comment by retailcoder** [comment]
The Code Explorer treeview will be redesigned for 2.0; we'll add a toggle button in the toolbar to toggle alphabetical vs. same-as-in-code sorting.

**Comment by Hosch250** [comment]
What's up with this?  Does the folders thing make this obsolete?  Are the folders/files sorted alphabetically in their level (they should be)?

**Comment by retailcoder** [comment]
@Hosch250 Ironically I've been working in my *Code Explorer* branch for a while now, and did tons of work on pretty much everything but the *Code Explorer* itself. The folders don't solve the problem, although the tree nodes are sorted alphabetically now, but IMO they should be sorted by type *and then* by name.

Still a lot of work is needed to get the *Code Explorer* working properly.

**Comment by ThunderFrame** [comment]
@Hosch250 The Code Explorer projects and components are sorting by name, but in VBE's Project Explorer, the Project "name" node is actually `ProjectName + "(" FileName + ")"`, and *depending" on the component type, the Component name is sometimes `ComponentName` and sometimes `ComponentName + "(" + DocumentName + ")"`

VBE allows concurrent projects to share the same project name (but AFAIK, the project file names must be unique), so if 2 or more projects share the same project name, then they're sorted by `ProjectName + FileName`. *But*, in some hosts, like Excel, the FileName isn't available (accessing the vbComponent getter throws an exception) for host projects that haven't yet been saved. But you can still get the FileName of an unsaved project host...

In Excel, the FileName is equivalent to the Name of the workbook, and even an unsaved workbook has a name. You can discover the Workbooks name by inspecting the Workbook `Component.Properties("Name").Value`, but first you need to know which component is the workbook component, and for that, you need to check if `Component.Properties("Parent").Properties("Name") = Component.Properties("Application").Properties("Name")`

Likewise, you can get the name of the Sheet components by using `Component.Properties("Name").Value` and you the Type of the Sheet by using `Component.Properties("Type").Value`, but first you need to know if a component is a sheet, which is done with `Component.Properties("Parent").Properties("Name") != Component.Properties("Application").Properties("Name")`
