### ISSUE TITLE
'fileNumber' grammar rule needs to accept 'valueStmt', not just an identifier or a literal

### ISSUE THREAD

**Issue by Ronaldvr** [rubberduck-vba/Rubberduck#714]
The parser gives the error:
extraneous input 'if' expecting NEWLINE

on the following piece of code:

```vba 
Mid(f.buffer, f.buffer_pos + 1, 1) = Chr(I)
    f.buffer_pos = (f.buffer_pos + 1)
    If .buffer_pos >= &H4000 Then
```

Probably because it expects mid() to be a function. However in this case it is used to assign a value, which is  valid vb(a)

**Comment by Vogel612** [comment]
If .buffer_pos >= &H4000 Then

This looks like you're either using a `With` or you meant to write `If f.buffer_pos >= &H4000 Then`...

**Comment by retailcoder** [comment]
@Vogel612 I doubt it would be that. Grammar isn't context-sensitive, *the resolver* identifies the context of an instruction.

It could be the parentheses around `(f.buffer_pos + 1)` but I can't be 100% sure until I repro. Will do that later for sure.

**Comment by Ronaldvr** [comment]
@Vogel612 : I did ineed use a with in the code itself, but added the variable again here in the snippet for readability: and then I omitted it once which actually did not improve the readability then.. sorry about that...

**Comment by retailcoder** [comment]
No repro with 1.4.3 and this code:

    Sub DoSomething()
        With f
            Mid(.buffer, .buffer_pos + 1, 1) = Chr(I)
            .buffer_pos = (.buffer_pos + 1)
            If .buffer_pos >= &H4000 Then Debug.Print .buffer_pos
        End With
    End Sub

Or this code:

    Sub DoSomething()
        Mid(f.buffer, f.buffer_pos + 1, 1) = Chr(I)
        f.buffer_pos = (f.buffer_pos + 1)
        If f.buffer_pos >= &H4000 Then Debug.Print f.buffer_pos
    End Sub

However if I remove the `Debug.Print` instruction and leave the `If...Then` block without any instruction in the `Then` part, I get the *extraneous input "If" expecting NEWLINE* parser error... but the code doesn't compile either.

An `If...Then` instruction that doesn't have any statement after the `Then`, requires an `End If` statement further down the line.

The Rubberduck grammar/parser assumes the code is compilable VBA code. Use the `Compile [ProjectName]` button in the VBE's `Debug` menu to ensure the code is compilable.

**Comment by Ronaldvr** [comment]
OK, the code compilesand works. here is the complete sub

```vba
Private Sub BinWrite(ByRef fFile As BinFile, ByVal intChar As Integer)
    With fFile
    Mid(.buffer, .buffer_pos + 1, 1) = Chr(intChar)
    .buffer_pos = (.buffer_pos + 1)
    If .buffer_pos >= &H4000 Then
        Put .file_num, , .buffer
        .buffer_pos = 0
    End If
    End With
End Sub

``

**Comment by retailcoder** [comment]
@Ronaldvr found it, thanks!

It's a grammar bug, specifically with the `fileNumber` grammar rule:

    fileNumber : '#'? (ambiguousIdentifier | INTEGERLITERAL);

The rule is expecting an identifier, so until I fix the grammar to make it expect a `valueStmt` (which may cause other unsuspected issues - we'll see!), a temporary fix could be to introduce a local variable to hold the file number - this code parses fine:

    Private Sub BinWrite(ByRef fFile As BinFile, ByVal intChar As Integer)
        Dim fn As Long
        With fFile
        fn = .file_num
        Mid(.buffer, .buffer_pos + 1, 1) = Chr(intChar)
        .buffer_pos = (.buffer_pos + 1)
        If .buffer_pos >= &H4000 Then
            Put fn, , .buffer
            .buffer_pos = 0
        End If
        End With
    End Sub

**Comment by Ronaldvr** [comment]
Thanks for the quick follow up @retailcoder! The workaround will do for me for the moment thanks!

**Comment by retailcoder** [comment]
Fixed in my fork. Looking good!
