### ISSUE TITLE
Callstack enhancements

### ISSUE THREAD

**Issue by zippy1981** [rubberduck-vba/Rubberduck#719]
I'd love the following Callstack enhancements:

* Docking the callstack window, or writing a new one thats dockable
* Seeing the unmanaged stack trace, the internal C API calls happening in a call.

How possible are these?

**Comment by ckuhn203** [comment]
Man..... I would love to see these features too, but it's unlikely to happen. The only project I know of that has accomplished this did it by injected some pre-compiled code into the kernel... something that is way above my head. You'll find a related discussion on #325 explaining why we declined this request in the past (and am declining it now).

**Comment by retailcoder** [comment]
I know one single tool that can tap into the VBA stack trace, and it did that with - brace yourselves - not C#, not C++, not C, not even Assembler - it was freakin' *hex code*! As much as I'd love to do that.... it ain't happening, at least not as long as Rubberduck is free and open-source.

**Comment by mwolfe02** [comment]
Not suggesting you actually implement this, but the Enterprise Edition of vbWatchDog now provides a LiveCallStack function that one could build a GUI around.  Obviously, you would have to make it completely optional as most users won't have a license for vbWatchDog.  And there may be philosophical reasons not to tie any of your code to a commercial project (even if only for optional features) .

But if you were going to make an exception, this would be the place to make it.

If the goal is to move the VBA IDE in the direction of Visual Studio, this would give it a big boost.  There is also likely to be a lot of overlap among the sort of users who will use Rubberduck and the users who have licenses for vbWatchdog.

I'm sure the EverythingAccess folks would not mind the free advertising and the tight integration might be enough to draw some of them in to the Rubberduck project as contributors.

**Comment by ckuhn203** [comment]
That's an interesting idea @mwolfe2. Very interesting idea.
