### ISSUE TITLE
How much work would it be to get Antly to compile the VBA to .NET

### ISSUE THREAD

**Issue by zippy1981** [rubberduck-vba/Rubberduck#724]
I have no experience with language development. However, since you have the grammar mostly implemented with Antlr, how hard would it be to get it compile down to .NET (whether IL, or converted to VBA or whatever)?

**Comment by ckuhn203** [comment]
Why not use Microsoft's VB6 to VB.Net conversion tool?

**Comment by zippy1981** [comment]
For a one time conversion, yes that's fine. My ultimate goal would be to be able to run VBA code from EPPlus .NET (not the author, but a minor contributor). This would have some side benefits. For example, a separate VBA interpreter could capture better exception data  than VBE does if a CreateObject() call fails.

**Comment by ckuhn203** [comment]
I just don't think our grammar is up to the task yet. Rubberduck was never meant to compile/run code. [This project][1] is just getting started, but I actually hope to someday replace our grammar/lexer/parser with it. I believe that *someday* it will be up to the task of actually interpreting VBA. The guy whose working on it is striving to write it to the spec. 

[1]: https://github.com/rossknudsen/Vba.Language

**Comment by ckuhn203** [comment]
I've thought about this a bit and I'm going to decline this. Like I mentioned before, RD was never intended to compile or interpret VBA, but simply provide static code analysis. I'm sure the parser code would make a good basis for such a project, but I can't see the value it would add to this project. 

Please feel free to fork the code and use it though. The parser code is licensed under the GPL, so you're absolutely free to modify it & distribute your modifications.
