### ISSUE TITLE
Code Inspection, VariableNeverUsed, flagging incorrect code

### ISSUE THREAD

**Issue by byronwall** [rubberduck-vba/Rubberduck#727]
Issue discussion started in #725.

The Code Inspector flags a number of variables as never used when they are used in the same procedure/scope.  These issues were identified using the code found in https://github.com/byronwall/bUTL/blob/master/bUTL.xlam but the same code copied to a blank module in a new project leads to the same erroneous flags.

This example flags `Variable 'ax' is never used`
```vba
Sub Chart_Axis_AutoX()
    Dim cht_obj As ChartObject
    For Each cht_obj In Chart_GetObjectsFromObject(Selection)
        Dim cht As Chart
        Dim ax As Axis
        Set cht = cht_obj.Chart
        Set ax = cht.Axes(xlCategory)
        ax.MaximumScaleIsAuto = True
        ax.MinimumScaleIsAuto = True
        ax.MajorUnitIsAuto = True
        ax.MinorUnitIsAuto = True
    Next cht_obj
End Sub
```

There are other examples which are flagged when inspected from the add-in but are not flagged when they stand alone on their own.  Example `Sub` include: [`SplitIntoColumns`](https://github.com/byronwall/bUTL/blob/master/src/code/Formatting_Helpers.vba#L418) which flags `arrParts` as never assigned or used, but when that code is on its own, there is no issue.

**Comment by retailcoder** [comment]
Found the issue with `VariableNotUsedInspection`:

            var declarations = parseResult.Declarations.Items.Where(declaration =>
                !declaration.IsBuiltIn 
                && declaration.DeclarationType == DeclarationType.Variable
                && declaration.References.All(reference => reference.IsAssignment));

The problem isn't so much with the inspection itself - if all references of a variable are assignment targets, then none of the references are actual usages. The problem is in the resolver code that turns this `IsAssignment` flag on, which struggles to correctly identify the assignment target on a `ICS_S_MemberCall`.

**Comment by retailcoder** [comment]
Narrowed down to `LetStmt` - `Set` assignments don't have this problem. This bug is on its way out :smiley:
