### ISSUE TITLE
Code Inspection returning some false positives

### ISSUE THREAD

**Issue by ckuhn203** [rubberduck-vba/Rubberduck#729]
Received via email:

Mathieu, Christopher Congrats for the great project. Some false positive during code inspection: 

1. Ribbon callbacks are reported as 'not used' 

        Private Sub COMAddins_OnAction(ByVal control As RibbonCommander.IRibbonControl)     
             Application.CommandBars.ExecuteMso "ComAddInsDialog" 
         End Sub 

2. "Success" is reported as 'not used', check all Event params 

        Private Sub Workbook_AfterSave(ByVal Success As Boolean) 

3. Procedures run with `Application.OnTime` only, are reported as 'not used'.  

4. Parser errors with conditional declarations: #If Win64 ... 

Regards 
Petros Chatzipantazis

**Comment by ckuhn203** [comment]
1. This is a known issue and limitation. If there is no VBA actually calling it, there is no way for us to know that the code is indeed being used by an outside source.

2. Same as above, but I believe we've hardcoded some things related to Workbook/Worksheet events already, so we may be able to do something for their params as well.

3. Again, same issue. Application.OnTime and Application.Run both run procedures by passing their names as text. This makes them undiscoverable via the abstract syntax tree as being called.

4. This is a known limitation of the parser that we hope to someday correct. Issue #730 has been opened for this.

**Comment by retailcoder** [comment]
#810 addresses this issue the way it needs to be addressed. Closing.
