### ISSUE TITLE
Grammar should handle directive conditionals

### ISSUE THREAD

**Issue by ckuhn203** [rubberduck-vba/Rubberduck#730]
Our current grammar doesn't handle directives well. Add support.

**Comment by retailcoder** [comment]
Just to be clear: `#If` directives *are* handled. What breaks the parser is when the directives are intertwined with other code blocks - I can't really think of a fix for that, no offense intended, but IMO it's badly structured code more than a grammar problem.

**Comment by ThunderFrame** [comment]
I agree that directives in other code blocks is bad practice, but 1.4 gets a Parse error ("No viable alternative at Input") on nested directives

    #If VBA7 Then
      #If Win64 Then
      #Else
      #End If
    #Else
    #End If
