### ISSUE TITLE
Website should have a favicon and title

### ISSUE THREAD

**Issue by ckuhn203** [rubberduck-vba/Rubberduck#731]
> Name
> Justin Dearing
> Email
> [redacted]
> Subject
> I suggest making your title tags say "Rubberduck - "
> Message
> Having a tab with no favico and the title Home makes me unable to know whats in this tab on my browser without clicking on it. Can you change e.g. Home to "Rubberduck - Home" and so on. Also, can you make the ribberduck icon the favicon.ico?

**Comment by retailcoder** [comment]
I agree it would be nice, but I'd have to upgrade the GoDaddy/WebsiteBuilder plan to enable this. I'd rather let the WebsiteBuilder subscription wear off and change the hosting in due time, perhaps to WordPress.

**Comment by retailcoder** [comment]
I managed to add "Rubberduck - " in front of every page's title. For some reason the *About* and *News* pages don't seem to have it... I'm going to blame caching.

**Comment by retailcoder** [comment]
Sticking [status-deferred] for the favicon.

**Comment by byronwall** [comment]
If you're considering hosting, GitHub Pages does an excellent job for static content.  You can always copy the html generated by your current page and just move it over.  You don't have to use Markdown or Jekyll. The favicon is free and you can CNAME a domain to it.  Finally, the site lives inside the main repo so you get version control, pull requests, and all that automatically.

**Comment by ckuhn203** [comment]
He's got a point Mug. Maybe we should consider it and save yourself a few bucks. No rush on any of this. Our site is better than most OOS projects.

**Comment by retailcoder** [comment]
@ckuhn203 oh, but I *am* considering :wink:

**Comment by retailcoder** [comment]
Done! www.rubberduckvva.com uses the same ducky.ico favicon as our in-app dialogs :-)
