### ISSUE TITLE
Installing Blockspring excel addin causes CONSISTENT Com exception on VBE startup

### ISSUE THREAD

**Issue by zippy1981** [rubberduck-vba/Rubberduck#732]
I've not been able to rpproduce issue #720 in a while. However, I just installed [Blockspring](https://blockspring.com/). Its an awesome tool for grabbing data from web services. It seems to be a C# Excel addin. It breaks rubberduck on my machine.

**Comment by ckuhn203** [comment]
Blockspring is a runtime tool. Rubberduck is a development time tool. Simply go into the VBE and disable Rubberduck unless you're actively developing.

1. Add-Ins
2. Add-In Manager
3. Select Rubberduck
4. Uncheck the "Loaded/Unloaded" box, and optionally, the "Load on Startup" box.

Re-enable Rubberduck when you want to use it.

**Comment by zippy1981** [comment]
That's an ok workaround. Would you accept a patch if I narrowed down and fixed the issue?

**Comment by Hosch250** [comment]
Of course.

**Comment by ckuhn203** [comment]
Yes! Of course we would!

**Comment by zippy1981** [comment]
So the actual issue is the long fixed in dev parse error window being opened twice.
