### ISSUE TITLE
Cannot compile setup file

### ISSUE THREAD

**Issue by zippy1981** [rubberduck-vba/Rubberduck#734]
Line 14 is `AppId={{979AFF96-DD9E-4FC2-802D-9E0C36A60D09}`, and its been this for a while. Is the first open bracket escaping the second one?

	C:\Users\jdearing\Documents\deleteme\Rubberduck>"c:\Program Files (x86)\Inno Setup 5\ISCC.exe" "Installer Build Script.iss"
	Inno Setup 5 Command-Line Compiler
	Copyright (C) 1997-2015 Jordan Russell. All rights reserved.
	Portions Copyright (C) 2000-2015 Martijn Laan
	Inno Setup Preprocessor
	Copyright (C) 2001-2004 Alex Yackimoff. All rights reserved.

	Compiler engine version: Inno Setup 5.5.6 (a)

	[ISPP] Preprocessing.
	[ISPP] Preprocessed.

	Parsing [Setup] section, line 14
	Parsing [Setup] section, line 15
	Parsing [Setup] section, line 16
	Parsing [Setup] section, line 17
	Parsing [Setup] section, line 18
	Parsing [Setup] section, line 19
	Parsing [Setup] section, line 20
	Parsing [Setup] section, line 22
	Parsing [Setup] section, line 23
	Parsing [Setup] section, line 24
	Parsing [Setup] section, line 25
	Parsing [Setup] section, line 26
	Parsing [Setup] section, line 27
	Parsing [Setup] section, line 28
	Parsing [Setup] section, line 29
	Parsing [Setup] section, line 31
	Parsing [Setup] section, line 32
	Error in C:\Users\jdearing\Documents\deleteme\Rubberduck\Installer Build Script.iss: The [Setup] section must include an AppVersion or AppVerName directive.
	Compile aborted.

**Comment by ckuhn203** [comment]
@rubberduck-vba/contributors sorry to ping everyone, but it wouldn't let me directly ping Ross for some reason....

Ross, I've still not learned as much as I should have about Innoscript. Any ideas?

@zippy1981 is there a reason you're trying to create an installer instead of running in debug mode?

**Comment by zippy1981** [comment]
Well it was suggestedd that powershell be used to automate the "compile and make installer" I was going to add a post deploy script instead. 

This doesn't really stop my ComException yak shaving though.

**Comment by rossknudsen** [comment]
@rossknudsen This is a test to see whether it notifies me.

@zippy1981 I just installed Inno Setup again (upgraded to Win10 the other day).  Based on your error message, I would suggest that you may have forgotten the precompiler during your installation:

![image](https://cloud.githubusercontent.com/assets/2489915/9018776/ebcb3c7a-3836-11e5-80ff-4687a33f9270.png)

**Comment by rossknudsen** [comment]
In response to creating scripts to build etc...  The installer is only useful for shipping binaries to the end user.  Devs run builds from Visual Studio and don't use the installer.  I think hooking into the VS post build event will not be a good idea.

We could add a post build event to the AppVeyor build system on the master branch though.  That would be cool.  You'd just need to install Inno Setup on the build server.  I see [this config](https://github.com/Phonations/Joker/blob/master/appveyor.yml) that installs Inno as part of the build.

My comment was based on my observation that a number of OS projects have one or more scripts in the root directory which build the installation packages in one step.  Someone who is interested in building the latest product from source would just download the source and run the script.  Though I'm not sure where you get MSBuild from now.

**Comment by ckuhn203** [comment]
@Rossknudsen, I would like to have the build server generate an actual installer eventually. I just don't understand why @zippy1981 is trying to build one or who suggested that or why. I'm hopelessly lost as to what the real issue is that he's trying to solve.

**Comment by rossknudsen** [comment]
> Well it was suggestedd that powershell be used to automate the "compile and make installer"

Is a reference to a comment I made in chat.  It was an offhand remark about imitating other projects I seen which include a batch file to build the entire project from scratch in one step.  It can be completely ignored.

I'd wait for @zippy1981 to respond regarding whether the precompiler is installed on his system as the error is complaining:

> The [Setup] section must include an AppVersion or AppVerName directive

The setup script defines the [AppName directive](https://github.com/retailcoder/Rubberduck/blob/next/Installer%20Build%20Script.iss#L15), but it uses a precompiler directive (`#define AppName "Rubberduck"`).  I'd imagine if the precompiler is not run before trying to compile the script that it would produce that message.

**Comment by rossknudsen** [comment]
According to the manual [`GetFileVersion`](http://www.jrsoftware.org/ispphelp/index.php?topic=getfileversion), will return an empty string if the file it is passed doesn't contain valid version info.  I have no idea why a clean build would not have that version info present but it could be that the file permissions prevent the script from seeing it or the path is wrong some how?...

**Comment by zippy1981** [comment]
@ckuhn203 at one point I didn't understand if I just ran visual studio under elevation, and hit F5 (afterconfiguring the debug setting), I'd get excel with the freshly compiled addin. That's why I thought I needed to compile the setup program. At this point, I'd just like to compile the setup program, because I've used innosetup in the past and it wasn't that hard. 

@rossknudsen I did indeed check the precompiler box. I do indeed have ISPP.dll in C:\Program Files (x86)\Inno Setup 5. Is there something I have to do to enable it? I'm runnning windows 7 64 bit. I installed the 32 bit version of innosetup. I tried the command line and gui compil32.exe compilers and get the same messages.

**Comment by rossknudsen** [comment]
I made a mistake in commenting about the preprocessor, on closer reading of your log it clearly says the preprocessor was executed successfully.  

What I'm guessing happened is that the preprocessor statement

    GetFileVersion(SourcePath + "RetailCoder.VBE\bin\release\Rubberduck.dll")

is evaluated to an empty string.  Hence `AppVersion` is assigned an empty string.  So when the compiler gets to the end of the `[Setup]` section (after line 32 in your log) it realises that the required field `AppVersion` (or `AppVerName`) hasn't been assigned.

Based on this [SO answer](http://stackoverflow.com/a/2267733/2301065), can you confirm this by adding:

    #if AppVersion == ""
    #error GetFileVersion() failed
    #endif

after the evaluation of AppVersion (after line 4).  This should push your compilation error up into the precompiler stage and confirm my diagnosis.

**Comment by rossknudsen** [comment]
@zippy1981 You will need to add some registry keys manually to get RD to appear in the VBE after you've built the project with elevated VS.  The keys are added by the installer normally.

Required key path:
 > HKCU/SOFTWARE/Microsoft/VBA/VBE/6.0/Addins/Rubberduck.Extension

Add the following values to the above key:
 > REG_SZ          Description       "Rubberduck"
 > REG_SZ          FriendlyName  "Rubberduck"
 > REG_DWORD LoadBehavior   3

**Comment by retailcoder** [comment]
@rossknudsen  @zippy1981 with 64-bit office (not sure with 32-bit), you may also need to run a manual `regasm.exe` command *once* for everything to register correctly - I had to use this command when I set up my fork:

    c:\Windows\Microsoft.NET\Framework64\v4.0.30319\regasm.exe "[path to your fork]\rubberduck\retailcoder.vbe\bin\debug\rubberduck.dll" /codebase /tlb

**Comment by zippy1981** [comment]
Ok I missed all the responses here since my last response, but  figured out the issue with `GetFileVersion()` on my own. Closing this.

**Comment by ckuhn203** [comment]
@zippy1981 for posterity, what was the issue/solution?

**Comment by zippy1981** [comment]
The solution was to compile a release build.

On that note, if we are tightly coupling the ISS file with the Release build, why not just make invoking the installer a post buiild step for release.

**Comment by ckuhn203** [comment]
Because we may have other reasons for compiling in release mode. For example, if we were having issues that don't show up in debug because of (the lack of) compiler optimizations. We have a build server set up, I'd like to get to a point where each build also creates an installer for that particular build.
