### ISSUE TITLE
Website download link points to wrong releases page.

### ISSUE THREAD

**Issue by zippy1981** [rubberduck-vba/Rubberduck#736]
The downlad page links to https://github.com/retailcoder/Rubberduck/releases, which only has source file zips. 

The correct releases page, with installers is https://github.com/rubberduck-vba/Rubberduck/releases

**Comment by retailcoder** [comment]
Ah, thanks for that! When I transferred ownership of the repo I must have forgotten to update the download link.

**Comment by retailcoder** [comment]
and done!
