### ISSUE TITLE
"Variable can be passed ByVal" inspection incorrectly raised.

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#739]
I have Method (A) which receives a parameter, but doesn't explicitly change that parameter. Instead, it passes it to Method (B) which changes the value of that parameter.  In both methods, I had the parameter declared `ByRef`.

_Code Inspections_ identified the parameter to Method (A) as a candidate to be changed from `ByRef` to `ByVal`. Without thorough investigation, I allowed it to fix it, then later realized the bug when Method (A) no longer returned the changed value for the parameter.

Example Code:

~~~
Private Sub PrintDataRows(ByVal Report As Worksheet, ByRef AllClinicRow As Integer, ByRef AllClinicStartRow As Integer, ByRef NoStateRow As Integer, ByRef NoStateStartRow As Integer, _
                  ByRef NoStatePageBreak As Integer, ByVal ClinicList As ProcessClinic)

Dim CI As ClinicItem
Const ClinicsToSkip As String = "State of Indiana"
        
  For Each CI In ClinicList.ClinicItems
    Application.StatusBar = "Printing: " & CI.Name
    DoEvents
    PrintDataRow AllClinicRow, AllClinicStartRow, Report, ClinicList, CI.Name, psPrintState
    IncAll Report, AllClinicRow, NoStateRow, NoStateStartRow, NoStatePageBreak
    If InStr(1, ClinicsToSkip, CI.Name) = 0 Then      'If the clinic isn't one to be skipped, print it
      PrintDataRow NoStateRow, NoStateStartRow, Report, ClinicList, CI.Name, psDoNotPrintState
      IncNoState Report, AllClinicRow, NoStateRow
    End If
  Next
  
End Sub


Private Sub IncAll(ws As Worksheet, ByRef Clinic As Integer, ByRef State As Integer, ByRef NoStateStartRow As Integer, ByRef PageBreakRow As Integer)

  Clinic = Clinic + 1           'prepare for next row of all-clinic data
  Rows(Clinic + 1).EntireRow.Insert 'insert a new blank row
  'increment all the other pointers to account for increased table sizes
  State = State + 1
  NoStateStartRow = NoStateStartRow + 1
  PageBreakRow = PageBreakRow + 1
  
End Sub
~~~

**Comment by retailcoder** [comment]
The fix for this involves verifying whether a parameter is passed *directly* into another method that accepts it `ByRef`, effectively treating that operation as an assignment. We need to think of a way to implement this without impacting performance too much.

**Comment by retailcoder** [comment]
@daFreeMan haven't forgotten about this issue.

Quite a lot of little things had to be improved for this to work, but as with all improvements, the result is an even more powerful API! :smile: 

So...

When called parameter is passed by value, the `ByRef` parameter being passed there can be passed by value if it's a "primitive type":

![image](https://cloud.githubusercontent.com/assets/5751684/10094008/52fb4b8a-6328-11e5-9b1a-54543e3afb45.png)

When called parameter is passed by reference, the `ByRef` parameter being passed there can't be passed by value without breaking the code, so there's no inspection result for it:

![image](https://cloud.githubusercontent.com/assets/5751684/10094017/80f76974-6328-11e5-944d-4721aa280c32.png)

Same if the `ByRef` parameter is passed to a `ByRef` parameter that's assigned - except now neither `foo` nor `bar` can be passed by value here:

![image](https://cloud.githubusercontent.com/assets/5751684/10094067/11b3773c-6329-11e5-8b8b-e9f6908f772d.png)

Rubberduck will not suggest to pass `Variant` and object types by value.

See commit [580fcca235eb877a6e2fc0e676d8154b24ef3aad](https://github.com/retailcoder/Rubberduck/commit/580fcca235eb877a6e2fc0e676d8154b24ef3aad) on my fork; this issue will be closed when I merge my changes in.

**Comment by ckuhn203** [comment]
Hmm... Should we open a separate issue to add this inspection for object types?

**Comment by retailcoder** [comment]
@ckuhn203 no need. The 'primitive types only' part of the spec is nothing new, and it was argued that objects passed by reference shouldn't be quickfixed to byval, for performance reasons. I would be more than happy to remove all this additional logic!

**Comment by ckuhn203** [comment]
Seems like that should be configurable to me. Turn it off if you want to. Personally, I pass everything ByVal (including objects) for the safety factor, but it is true that there's a performance consideration there.

Your call.
