### ISSUE TITLE
HostApplicationBase can throw an unhandled NRE

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#744]
The generic class `HostApplicationBase<TApplication>`, under `Rubberduck.VBEditor.VBEHost`, has a finalizer that calls `Marshal.ReleaseComObject()` to release the host app instance:

        ~HostApplicationBase()
        {
            Marshal.ReleaseComObject(Application);
        }

For some reason that needs to be investigated, `Application` can be `null` at that point, and `ReleaseComObject` throws a `NullReferenceException` when that's the case, that isn't handled.

This simple check would fix the issue:

        ~HostApplicationBase()
        {
            if (Application != null)
            {
                Marshal.ReleaseComObject(Application);
            }
        }

Anyone?

**Comment by retailcoder** [comment]
Probably related to the fact that [Master] has no reference to `Microsoft.Office.Interop.Outlook`, and `Application` is referring to `Microsoft.Vbe.Interop.Application` - see [OutlookApp.cs on Master](https://github.com/rubberduck-vba/Rubberduck/blob/master/Rubberduck.VBEEditor/VBEHost/OutlookApp.cs#L2)

**Comment by Vogel612** [comment]
this seems to be fixed in `next`, or more correctly since b64d2cfa4821bcfae10e66410e8b54543626ebae
@retailcoder can you confirm this or is further investigation necessary?

**Comment by ckuhn203** [comment]
Looks fixed to me. Closing it.
