### ISSUE TITLE
Grammar doesn't understand function's array return value being accessed in the same instruction

### ISSUE THREAD

**Issue by yadimon** [rubberduck-vba/Rubberduck#749]
Hi, I tried some RD function over some projects,
the parser shows error, but for different lines, somewhere near the code examples.
The following code examples generates errors for Parser:

`somevar = Split(anyvar, "anystring")(0)` (the last part is the problem)

and

`Dir$`

**Comment by ckuhn203** [comment]
Any chance you have the error message from the parser handy?

**Comment by retailcoder** [comment]
The grammar doesn't understand that a function can return an *array* that's accessed immediately; the grammar rule allows for chained *member calls*, but the *array or procedure call* rule is currently standing on its own, which means...

Repro:

    Sub Foo()
        bar = Split("abc,def", ",")(0)
    End Sub

Work-around:

    Sub Foo()
        temp = Split("abc,def", ",")
        bar = temp(0)
    End Sub

By splitting the call on two instructions, the grammar rules are satisfied and the parser understands what's going on.

Not ideal, but note taken - we'll see how the grammar can be tweaked to understand that an array call can be made there.

**Comment by yadimon** [comment]
and what about Dir$ error?

```
Sub `Foo()
    Dir$ ("/")
End Sub
```

**Comment by retailcoder** [comment]
Interesting. The same code using `Dir` instead of `Dir$` doesn't blow up the parser.

My guess is that the `$` trips the parser because in this context `Dir` is interpreted as a procedure call, and it seems only a *function* call is legal with a type hint - this code doesn't blow up the parser:

    Sub Foo()
        bar = Dir$("/")
    End Sub

We might need to special-case `Dir$`.

**Comment by manfredk** [comment]
Just to stress the importance of this issue: 

I tried Rubberduck with a medium complex project where I'm using this construct (function's array return value immediately indexed) quite frequently. Unfortunately the parser breaks, showing only the first parse error and parsing would never come to an end (showing VBProject parsing ... indefinitely, refresh not working). No time to change dozens of lines just to get code explorer working.

But Rubberduck seems very promising and a quantum leap in vba coding assistance. I'll definitely take a closer look and dive into debugging RD itself, meanwhile KEEP GOING! 

Cheers

**Comment by retailcoder** [comment]
@manfredk thanks! I see you forked the project - feel free to contact me anytime if you have questions... I haven't really documented how to compile the ANTLR grammar and re-generate the parser and other needed base classes... I need to do that.

I'm currently working on *reconnecting the pieces* (see #759), and that a lot of the issues linked there are "up-for-grabs", as a result of #606. In the process, we're swapping some WinForms UI for some WPF/XAML, toward a MVVM approach. This change is far from being *just* cosmetic, and significantly simplifies and organizes the code base... on top of being more elegant in both Visual Studio and the VBE.

I was planning on implementing the grammar fixes after I get the code inspections and regex search/replace up, so a number of weeks still; I'll gladly accept a PR that fixes grammar issues before I get to them! :smiley:

**Comment by manfredk** [comment]
Hi Mathieu,

I did a project with VSTO in 2013 (Excel only), but Rubberduck is far more
complex. I'm still wrapping my head around some concepts which are at the
core of rubberduck (Parsing with Antlr), so probably no PR from my side
concerning this issue. Currently I'm busy with a project, but I hope to
dive deeper into Rubberduck in 2 months. Would you need someone for
translating the german locale ? ... I'd be ready to do that in November.

Again, great work !!. I'm curious about v2.

Cheers, Manfred

On Sun, Sep 13, 2015 at 5:40 AM, Mathieu Guindon <notifications@github.com>
wrote:

> @manfredk <https://github.com/manfredk> thanks! I see you forked the
> project - feel free to contact me anytime if you have questions... I
> haven't really documented how to compile the ANTLR grammar and re-generate
> the parser and other needed base classes... I need to do that.
>
> I'm currently working on *reconnecting the pieces* (see #759
> <https://github.com/rubberduck-vba/Rubberduck/issues/759>), and that a
> lot of the issues linked there are "up-for-grabs", as a result of #606
> <https://github.com/rubberduck-vba/Rubberduck/issues/606>. In the
> process, we're swapping some WinForms UI for some WPF/XAML, toward a MVVM
> approach. This change is far from being *just* cosmetic, and
> significantly simplifies and organizes the code base... on top of being
> more elegant in both Visual Studio and the VBE.
>
> I was planning on implementing the grammar fixes after I get the code
> inspections and regex search/replace up, so a number of weeks still; I'll
> gladly accept a PR that fixes grammar issues before I get to them! [image:
> :smiley:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rubberduck-vba/Rubberduck/issues/749#issuecomment-139842647>
> .
>



-- 

 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
- -


Manfred Kipfelsberger, Schwabacher Str. 129, 90763 Fürth
web: http://www.cen-seo.de, email:  mk@cen-seo.de
Tel. 0151-270 20 866, skype: manfred.kipfelsberger
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
- -

**Comment by Vogel612** [comment]
Hi @manfredk,

this is the current translator for German locale speaking :smile: 
Amendmends and improvement ideas are very welcome.

You can find the current Translation under `Retailcoder.VBE/UI/RubberduckUI.de.resx`

If you need something to make this nasty XML file look better, you may want to check
https://github.com/Vogel612/TranslationHelper or https://github.com/Hosch250/ResxEditor

Greets, Vogel612

**Comment by ckuhn203** [comment]
Hey there @manfredk. I can completely understand having other things to do, but don't let ANTLR scare you away. You couldn't fix this issue without learning a bit about it, but there are lots of other areas that could use some TLC. All PRs are considered, we're always happy for any help we get. We hope that you'll come back around down the road and contribute. 

Cheers

**Comment by manfredk** [comment]
@Vogel612 Hi Clemens, good to know, I'll have a look.

**Comment by retailcoder** [comment]
Looks like this issue is now fixed on my fork and will be closed when I merge my changes in :smiley:
