### ISSUE TITLE
Parser error: Select Case, multi Case

### ISSUE THREAD

**Issue by yadimon** [rubberduck-vba/Rubberduck#750]
example:

```
Sub Foo()
    Dim a As Variant
    
    Select Case a
        Case 1 To 3, 4 To 6
        
        Case Else
        
    End Select
End Sub
```

**Comment by retailcoder** [comment]
Nice one, good catch!

**Comment by retailcoder** [comment]
This:

    | INTEGERLITERAL WS TO WS valueStmt (WS? ',' WS? valueStmt)*    # caseCondTo

Is the problematic part. In fact, even with that sub-rule fixed, this valid code would still break the parser:
    
    Select Case foo
        Case Is < 15, 25 To 35, 65

    End Select

We need to rewrite the whole `sC_Cond` rule, and break it down properly.

**Comment by EBrown8534** [comment]
I would try breaking the grammar down a little further, as follows:

    sC_Case : 
        CASE WS sC_Type WS? (':'? NEWLINE* | NEWLINE+)  
        (block NEWLINE+)?
    ;

    sC_Type :
        ELSE                                                            # caseCondElse
        | sC_Selection (WS? ',' WS? sC_Selection)*                      # caseCondSelection
    ;

    sC_Selection :
        IS WS? comparisonOperator WS? valueStmt                         # caseCondIs
        | valueStmt                                                     # caseCondValue
        | INTEGERLITERAL WS TO WS INTEGERLITERAL                        # caseCondTo
    ;

If my EBNF is correct, this should allow you to support the proper chaining of all applicable `Case` types (in any order as well). That is:

    Select Case foo
        Case Is < 15, 25 To 35, 65
        Case 16 To 24, 36, 38 To 64, Is > 65
        Case 37
        Case Else
    End Select

(I don't have a grammar tester handy, if I did I would know for sure if this is valid.)

**Comment by EBrown8534** [comment]
Additionally, upon further research, in VB.NET the `To` style of `Case` statements can have alphabetical values, and double values as well. I.e.:

    Select Case Foo
        Case "a"
        Case "bolts" To "nuts"
        Case Else
    End Select

And:

    Select Case Foo
        Case Is < 15, 19.5
        Case 15 To 22.5, 46
        Case 22.5 To 40, 45, Is > 47
        Case 40 To 47
        Case Else
    End Select

This means that `INTEGERLITERAL` in the `TO` syntax tree is not going to suffice. We'll need a more proper grammar for the `TO` portion.

**Comment by EBrown8534** [comment]
Alright, so after reading through a lot of the grammar, I think the following solution should take care of this issue:

Replace the current `Select Case` grammar:

>     selectCaseStmt : 
        SELECT WS CASE WS valueStmt NEWLINE+ 
        sC_Case*
        WS? END_SELECT
    ;

>     sC_Case : 
        CASE WS sC_Cond WS? (':'? NEWLINE* | NEWLINE+)  
        (block NEWLINE+)?
    ;

>     // ELSE first, so that it is not interpreted as a variable call
    sC_Cond : 
        ELSE                                                            # caseCondElse
        | IS WS? comparisonOperator WS? valueStmt                       # caseCondIs
        | valueStmt (WS? ',' WS? valueStmt)*                            # caseCondValue
        | INTEGERLITERAL WS TO WS valueStmt (WS? ',' WS? valueStmt)*    # caseCondTo
    ;

With a more supportive version:

    selectCaseStmt : 
        SELECT WS CASE WS valueStmt NEWLINE+ 
        sC_Case*
        WS? END_SELECT
    ;

    sC_Case : 
        CASE WS sC_Cond WS? (':'? NEWLINE* | NEWLINE+)  
        (block NEWLINE+)?
    ;

    // ELSE first, so that it is not interpreted as a variable call
    sC_Cond :
        ELSE                                                            # caseCondElse
        | sC_Selection (WS? ',' WS? sC_Selection)*                      # caseCondSelection
    ;

    sC_Selection :
        IS WS? comparisonOperator WS? valueStmt                         # caseCondIs
        | valueStmt                                                     # caseCondValue
        | (INTEGERLITERAL | DOUBLELITERAL) WS TO WS (INTEGERLITERAL | DOUBLELITERAL)                        # caseCondToNumeric
        | STRINGLITERAL WS TO WS STRINGLITERAL                          # caseCondToString
    ;

Optionally (and I would heavily recommend this), we could consider creating a `NUMERICLITERAL` as:

    NUMERICLITERAL : INTEGERLITERAL | DOUBLELITERAL;

And rewrite `sC_Selection` as:

    sC_Selection :
        IS WS? comparisonOperator WS? valueStmt                         # caseCondIs
        | valueStmt                                                     # caseCondValue
        | NUMERICLITERAL WS TO WS NUMERICLITERAL                        # caseCondToNumeric
        | STRINGLITERAL WS TO WS STRINGLITERAL                          # caseCondToString
    ;

The only other `TODO` this might raise is to verify if `STRINGLITERAL WS TO WS STRINGLITERAL` is also valid as `STRINGLITERAL WS? TO WS? STRINGLITERAL`.

**Comment by wqweto** [comment]
This has to be valid `sC_Selection`

    Case f(1) To f(5)

Why are you insisting on using LITERAL of any king instead of `valueStmt`? Just order these as not to be ambiguous like this

    sC_Selection :
        IS WS? comparisonOperator WS? valueStmt                         # caseCondIs
        | valueStmt WS? TO WS? valueStmt                                # caseCondTo
        | valueStmt                                                     # caseCondValue
    ;

Or there is something I'm missing?

**Comment by EBrown8534** [comment]
It looks like that is valid, as well as:

    Case 15 To "asdf"
    Case Val("25") To Val("52")
    etc.

So, maybe that is the most appropriate way to handle all the situations.

**Comment by ckuhn203** [comment]
`valueStatement` :+1:

**Comment by retailcoder** [comment]
@EBrown8534 @wqweto @ckuhn203 this seems to fix the problem:

	selectCaseStmt : 
		SELECT WS CASE WS valueStmt NEWLINE+ 
		sC_Case*
		WS? END_SELECT
	;

	sC_Selection :
		IS WS? comparisonOperator WS? valueStmt                         # caseCondIs
		| valueStmt WS TO WS valueStmt                                # caseCondTo
		| valueStmt                                                     # caseCondValue
	;

	sC_Case : 
		CASE WS sC_Cond WS? (':'? NEWLINE*)
		(block NEWLINE+)*
	;

	// ELSE first, so that it is not interpreted as a variable call
	sC_Cond :
		ELSE                                                            # caseCondElse
		| sC_Selection (WS? ',' WS? sC_Selection)*                      # caseCondSelection
	;

Notice `(block NEWLINE+)*` instead of `(block NEWLINE+)?` supports empty case blocks.
