### ISSUE TITLE
Grammar of `INTEGERLITERAL` and `DOUBLELITERAL` is too permissive

### ISSUE THREAD

**Issue by EBrown8534** [rubberduck-vba/Rubberduck#753]
I noticed an issue with the following grammar when I was reading over it:

>     INTEGERLITERAL : (PLUS|MINUS)? ('0'..'9')+ ( ('e' | 'E') INTEGERLITERAL)* ('#' | '&')?;
    DOUBLELITERAL : (PLUS|MINUS)? ('0'..'9')* '.' ('0'..'9')+ ( ('e' | 'E') (PLUS|MINUS)? ('0'..'9')+)* ('#' | '&')?;

These allow for invalid values, such as `1e1e5e1`, and `1.5e4e3`.

Possible solution:

    INTEGERLITERAL : (PLUS|MINUS)? ('0'..'9')+ ( E ('0'..'9')+ )? ('#' | '&')?;
    DOUBLELITERAL : (PLUS|MINUS)? ('0'..'9')* '.' ('0'..'9')+ ( E (PLUS|MINUS)? ('0'..'9')+)? ('#' | '&')?;

* Rewrite them from `( ... )*` in the exponent group to `( ... )?`, to allow for **only zero or one** exponent group instead of any number of them;
* Replace `('e' | 'E')` with the `E` fragment;
* Remove `INTEGERLITERAL` from the exponent grouping on `INTEGERLITERAL`, replace with `('0'..'9')+` group, to restrict to numbers only;

Additional considerations included in this issue
---

I would also consider adding:

    fragment DIGIT : ('0'..'9');

So that instances of `('0'..'9')` within all the grammar can be replaced with a more canonical name. I.e.:

    INTEGERLITERAL : (PLUS|MINUS)? DIGIT+ ( E DIGIT+ )? ('#' | '&')?;
    DOUBLELITERAL : (PLUS|MINUS)? DIGIT* '.' DIGIT+ ( E (PLUS|MINUS)? DIGIT+)? ('#' | '&')?;

Lastly, it could also be considered to add `SIGN`:

    SIGN : (PLUS | MINUS);

To achieve:

    INTEGERLITERAL : SIGN? DIGIT+ ( E DIGIT+ )? ('#' | '&')?;
    DOUBLELITERAL : SIGN? DIGIT* '.' DIGIT+ ( E SIGN? DIGIT+)? ('#' | '&')?;

This makes it much more canonical throughout.

**Comment by retailcoder** [comment]
:+1:

**Comment by ckuhn203** [comment]
:+1:

**Comment by wqweto** [comment]
I think `INTEGERLITERAL` must accept `%` and `&` suffixes only (for integer and long) while `DOUBLELITERAL` can accept `@`, `!` and `#` (for decimal, single and double) and then `'.' DIGIT*` part has to be optional.

**Comment by wqweto** [comment]
[Obviously much better to stick to language specification](https://github.com/rossknudsen/Vba.Language/blob/next/Vba.Language/Vba.Grammars/VbaLexer.g4#L10) or just backport edge cases (like accepting `1.23D4`) to current implementation.

**Comment by ckuhn203** [comment]
Yeah. I'd prefer to stick to the specification too. It's my hope that *someday* we'll be able to switch over to Ross's grammar. Once he has it stable. I haven't checked up on that project recently though.

**Comment by retailcoder** [comment]
I'm going to [status-deferred] this issue for now; the parser needs to assume the parsed code *compiles* - if VBA can't handle it, then Rubberduck has no reason to handle it. A side-effect of this, is that an integer literal that, in theory, is too permissive, is in practice not a problem.

**Comment by retailcoder** [comment]
The lexer rules that make up a `LITERAL` token have been fleshed up.

	// literals
	STRINGLITERAL : '"' (~["\r\n] | '""')* '"';
	DATELITERAL : '#' BYTEDIGIT+ '/' BYTEDIGIT+ '/' BYTEDIGIT+ '#';
	OCTLITERAL : '&O' [0-8]+ '&'?;
	HEXLITERAL : '&H' [0-9A-F]+ '&'?;
	SHORTLITERAL : (PLUS|MINUS)? BYTEDIGIT+ ('#' | '&' | '@')?;
	INTEGERLITERAL : SHORTLITERAL (E SHORTLITERAL)?;
	DOUBLELITERAL : (PLUS|MINUS)? BYTEDIGIT* '.' BYTEDIGIT+ (E SHORTLITERAL)?;
	BYTEDIGIT : [0-9];

I named it `BYTEDIGIT` over `DIGIT`, because the former implies its values, while the latter becomes ambiguous with the presence of the new `OCTLITERAL` and `HEXLITERAL` tokens.
