### ISSUE TITLE
Parser errors: Extraneous input on Worksheets(2)

### ISSUE THREAD

**Issue by vdubya** [rubberduck-vba/Rubberduck#754]
```
Sub test()
    Dim ws1, ws2 As Worksheet
    Set ws1 = Worksheets(1)
    Set ws2 = Worksheets(2)
    ws1.Range("namedrange")(2) = ws2.Range("A1")
End Sub
```

**Comment by retailcoder** [comment]
Hi @vdubya, this is a known issue that we expect to fix for next release: basically our grammar (more precisely the parser ANTLR generates with it) has a problem with an array call that's made out of the result of a function.

In other words, this works around the issue:

    Sub test()
        Dim ws1, ws2 As Worksheet
        Set ws1 = Worksheets(1)
        Set ws2 = Worksheets(2)
        Dim rng As Range
        Set rng = ws1.Range("namedrange")
        rng(2) = ws2.Range("A1")
    End Sub

Thanks for your feedback!

**Comment by retailcoder** [comment]
#749 covers it.

**Comment by vdubya** [comment]
@retailcoder Sorry for the duplicate, still getting familiarized with the project and github for that matter. Kudos to you guys on RD, it is a fantastic tool!

**Comment by retailcoder** [comment]
No problem at all! Thanks again for the feedback - duplicate or not, all feedback is welcome and highly appreciated :-)
