### ISSUE TITLE
Implement a more permissive AssertClass

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#755]
The COM-visible `Rubberduck.AssertClass` is implementing `AreEqual` in a type-safe way that is *expected* in .net but that can be surprising in VBA:

            if (expected.GetType() != actual.GetType())
            {
                AssertHandler.OnAssertInconclusive("[expected] and [actual] values are not the same type.");
                return;
            }

Let's implement and expose a `PermissiveAssertClass` that implements equality checks in a more VBA-like way - this involves type checks, casts and `TryParse` calls that will probably impact performance, but if done right can enhance usability.

**Comment by retailcoder** [comment]
The current `AssertClass` members could be made `virtual` and the new class derived from it, to simplify implementing the `IAssert` interface.

**Comment by retailcoder** [comment]
Nothing else needs to change anywhere; the VBA code is responsible for creating the `AssertClass` instance, and the test engine listens for `public static event EventHandler<AssertCompletedEventArgs> OnAssertCompleted` in the `AssertHandler` static class, so the `PermissiveAssertClass` could look like this (assuming `AssertClass` members are made `virtual`):

    [ComVisible(true)]
    [ComDefaultInterface(typeof(IAssert))]
    [Guid(ClassId)]
    [ProgId(ProgId)]
    public class PermissiveAssertClass : AssertClass
    {
        private const string ClassId = "(some GUID)";
        private const string ProgId = "Rubberduck.PermissiveAssertClass";

        public override void AreEqual(object expected, object actual, string message = null)
        {
            // permissive implementation

            // - call AssertHandler.OnAssertSucceeded()
            //   to make the assertion succeed
            // - call AssertHandler.OnAssertFailed("AreEqual", string.Concat("expected: ", expected.ToString(), "; actual: ", actual.ToString(), ". ", message));
            //   to make the assertion fail
        }

        public override void AreNotEqual(object expected, object actual, string message = null)
        {
            // permissive implementation

            // - call AssertHandler.OnAssertSucceeded();
            //   to make the assertion succeed
            // - call AssertHandler.OnAssertFailed("AreNotEqual", string.Concat("expected: ", expected.ToString(), "; actual: ", actual.ToString(), ". ", message));
            //   to make the assertion fail
        }
    }

---

Then we can consider adding a "Unit Testing" options page in the Rubberduck settings, to determine which `IAssert` implementation gets referenced when a new test module is added (and perhaps other options while we're at it).

**Comment by Vogel612** [comment]
I find it counterintuitive to decide how exact my Asserts are by a configurable setting. I'd sure prefer one statement to always mean the same across all projects. Instead I'd personally move these "loose" asserts into differently named methods / a different class. 

This may allow you to still configure which of these two you prefer, but `AssertEquals(a, b, "wat")` should for the same a and b always return the same result.

**Comment by retailcoder** [comment]
@Vogel612 fair point; the problem is that VBA and C#'s respective definition of "same a and b" are different, because VBA is quite generous with implicit conversions.

The current `AssertClass` behaves more like C# and, while it's good to be strict with types, a VBA programmer may prefer, or *expect* (or *need*?) "123" to be considered equal to 123. Or more subtly, 123 (`Integer`) to be equal to 123 (`Byte`) or 123 (`Long`).

I'd keep the current implementation the default, but allow the user to work with more VBA-ish equality comparisons.

**Comment by retailcoder** [comment]
@Vogel612 just picked up "or move them to a different class" - that's exactly what I'm suggesting: by default, adding a new test module would create a new standard module featuring this line:

    Private Assert As New Rubberduck.AssertClass

What this issue is suggesting, is to give the ability to do this:

    Private Assert As New Rubberduck.PermissiveAssertClass

The configurable part merely determines which class is being instantiated by default - user can switch one for the other at any time; I don't see this as anything much different than sticking `Option Strict` at the top of a VB.NET module.

**Comment by ckuhn203** [comment]
So, my first thought is that there's a reason the AssertClass is in the main project, rather than in it's own library. We had issues with COM typing between projects.

One possible work around is (perhaps, *maybe*) referencing the VisualBasic namespace?? I'm not sure if we could get the weaker, more implicit, typing this way or not.

**Comment by Vogel612** [comment]
@ Zak just raised a very valid concern in chat:

> [except I don't know how
`option compare text`
works with unit testing](http://chat.stackexchange.com/transcript/message/23976685#23976685)

Are we respecting options for the unit-tests? If no: Are we planning to?

Is there somewhere I can find the exact rules for the implicit typing, as to avoid referencind the VisualBasic namespace?

**Comment by ckuhn203** [comment]
I didn't check on the code, but I'd bet my hat we're following [standard C# rules for text comparrison][1] and I *guarantee* that we're ignoring the text compare option. Which means `"Text" != "text"` as far as our current implementation is concerned. 

I'd consider Text Compare Option support to be a "nice to have" feature, but not a solid requirement. We'll probably want to support it *eventually*, so we'd want to keep the implementation flexible enough to add support later.

**Comment by Vogel612** [comment]
Current implementation checks for type-equality and fails early if `expected` and `actual` do not have the exact same type. If they are the same type the check is `expected.Equals(actual)`, as such we currently respect case when comparing strings.

**Comment by INOPIAE** [comment]
When I try to compile the next branch (sha-1: 49ae39383d7cbb0f30b65155fe3578192147eda) I run into these two errors:
 "'Rubberduck.Unit.Testing.PermissiveAssertClass.AreEqual()': cannot override inherited member 'Rubberduck.Unit.Testing.AssertClass.AreEqual()' because it is not marked virtual, abstract, or override"
 "Rubberduck.Unit.Testing.PermissiveAssertClass.AreNotEqual()': cannot override inherited member 'Rubberduck.Unit.Testing.AssertClass.AreNotEqual()' because it is not marked virtual, abstract, or override"

**Comment by Vogel612** [comment]
@INOPIAE oh yes.. that one's my (or maybe mono's) fault. I wrote that class and at least that class compiled fine. 4b9423b0d35878d950b903d8b8f5930fdc9e38b2 fixes these compile errors, thanks to @retailcoder

**Comment by retailcoder** [comment]
I'm closing this issue, @Vogel612 implemented the thing - now we need unit tests for it :stuck_out_tongue_winking_eye:
