### ISSUE TITLE
Implement RefactorRemoveParametersCommand

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#762]
Similar to #761, implement a command for the *remove parameters* refactoring:

    public class RefactorRemoveParametersCommand : CommandBase
    {
        public override void Execute(object parameter)
        {
            throw new NotImplementedException();
        }
    }

Move this code from the now-deprecated `RefactorMenu` class:

        private void RemoveParameter(QualifiedSelection selection)
        {
            var progress = new ParsingProgressPresenter();
            var result = progress.Parse(_parser, IDE.ActiveVBProject);

            using (var view = new RemoveParametersDialog())
            {
                var factory = new RemoveParametersPresenterFactory(_editor, view, result, new MessageBox());
                var refactoring = new RemoveParametersRefactoring(factory, _editor);
                refactoring.Refactor(selection);
            }
        }

Related: #759

**Comment by Vogel612** [comment]
fixed in #783 , but github didn't catch it. NLP is **hard**

**Comment by retailcoder** [comment]
Thanks @Vogel612!
