### ISSUE TITLE
Problem starting RubberDuck on a German Office 2013

### ISSUE THREAD

**Issue by INOPIAE** [rubberduck-vba/Rubberduck#778]
After compling the project with the lastest code version I run into this error:
![image](https://cloud.githubusercontent.com/assets/2772829/9958461/74e9e62a-5e0a-11e5-88f3-0327446c7d96.png)
The problem arises as in the German version it must be "Menüleiste" instead of "Menu Bar"
in line 40
var parent = _kernel.Get<VBE>().CommandBars["Menu Bar"].Controls;

**Comment by retailcoder** [comment]
Oh nice catch - I would have never caught that one, you have just prevented
an embarrassing bug to be released! Thanks!

The menu will need to be accessed by index (in this case, #1) - there are
other instances of named command bars accessed by name, that will need to
be tweaked as well.

Can you verify whether v1.4.3 has this problem too? If I remember correctly
the code pane and form designer context menus are accessed by name, too...

(if not, then it means Microsoft only localized the main command bar
name... which is... like, wow)

Thanks!

**Comment by Vogel612** [comment]
This Looks like there is a necessity to actually localize the code or what the heck is going on?

Anyways the same way of Access is also used in lines 50, 60, 70, 80 and probably also in some other places throughout the [`CommandBarsModule`](https://github.com/rubberduck-vba/Rubberduck/blob/next/RetailCoder.VBE/Root/CommandBarsModule.cs)

It may or may not be possible to work around the Localization issue with index-based Access. If not, [`CommandBars.FindControls`](https://msdn.microsoft.com/en-us/library/office/microsoft.office.core._commandbars.findcontrols.aspx) may be an option

**Comment by INOPIAE** [comment]
I did not see the problem on v.1.4.3 when I installed it from the setup file.
As far as I can see only the first 4 menues have been translated to German
![image](https://cloud.githubusercontent.com/assets/2772829/9958765/60b5b7b2-5e0d-11e5-89be-474a60460703.png)
I have a bug fix on my fork.

**Comment by ckuhn203** [comment]
By all means! Please submit the Pull Request!
Thank you!
