### ISSUE TITLE
Small UI problems to be fixed for localization

### ISSUE THREAD

**Issue by INOPIAE** [rubberduck-vba/Rubberduck#781]
I found the following problems on the next branch:
* On the About Rubberduck form the text of the SpecialThanksList is not translated. The resource file show som of the text.
* On the SettingsDialog form the Reset button is not wide enough to hold the German translation "Zurücksetzen"
![image](https://cloud.githubusercontent.com/assets/2772829/9959808/ef2d58c0-5e16-11e5-98ff-ba021f248439.png)
* It might be a good idea to have this remark when changing the language settings:
"You should restart your office application to have the language settings applied throughout the whole Rubberduck AddIn."
The remark can either be placed on the language settings pane or as popup after the language settings change.

**Comment by retailcoder** [comment]
This was fixed with your PR wasn't it?

**Comment by Vogel612** [comment]
No this was not fixed with #779 or #780 and also not with my subsequent Pull Requests.

Issue is still valid and not fixed :cry:

**Comment by Vogel612** [comment]
seems to be fixed with #802

**Comment by retailcoder** [comment]
Sticking a [status-declined] on this one, because XAML automatically resizes controls to fit content - the 2.0 UI's make this issue moot! :smile:

**Comment by Hosch250** [comment]
I think this was addressed, rather than being declined.
