### ISSUE TITLE
Test Explorer test runner is adding reference to Rubberduck type library

### ISSUE THREAD

**Issue by mwolfe02** [rubberduck-vba/Rubberduck#784]
I'm trying to run tests with late-binding.  I switched from `New Rubberduck.AssertClass` to `CreateObject("Rubberduck.AssertClass")`.  I can remove the reference to the Rubberduck type library and the project compiles.  Everything's good so far.

When I run the tests from the Test Explorer, though, the reference to the Rubberduck type library is being re-added to my project without warning.  It's just an annoyance, but I don't want to ship out a production version of my Access app with a library that won't be available on the end-user machines.

I am currently running: Build 1.4.3.2343 (MSIL).

**Comment by mwolfe02** [comment]
It looks like this may have already been fixed on August 22 in revision ff60ef93f231b50c8956853819df620b0c781d05.

The following lines were removed from \RetailCoder.VBE\UI\UnitTesting\TestExplorerDockablePresenter.cs:

        public void RunTests(IEnumerable<TestMethod> tests)
        {
            try
            {
                _view.ClearResults();

                var testMethods = tests as IList<TestMethod> ?? tests.ToList(); //bypasses multiple enumeration
                _view.SetPlayList(testMethods);

                _view.ClearProgress();

                var projects = testMethods.Select(t => t.QualifiedMemberName.QualifiedModuleName.Project).Distinct();
                foreach (var project in projects)
                {
                    project.EnsureReferenceToAddInLibrary();
                }
            
                _testEngine.Run(testMethods);
            }
            catch (Exception exception)
            {
                // WTF is going on here?
            }
        }

I believe the problem was with these lines, in particular:

            var projects = testMethods.Select(t => t.QualifiedMemberName.QualifiedModuleName.Project).Distinct();
            foreach (var project in projects)
            {
                project.EnsureReferenceToAddInLibrary();
            }

**Comment by retailcoder** [comment]
"Fixed" is a big word, the whole feature was pretty much rewritten! I'm creating an issue to make sure I remember to make a checkbox for this in the Rubberduck Settings dialog.
