### ISSUE TITLE
Add a "Unit Testing" page to the Rubberduck Settings dialog

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#785]
Let's add a "Unit Testing" page to the settings dialog, and make the following configurables:

 - [ ] **Early-bind the Rubberduck type library** - when this option is checked (checked by default), running Rubberduck tests will ensure the VBA project has a reference to the Rubberduck type library. Unchecking this box can cause runtime errors if unit tests require early binding (e.g. if `AssertClass` is being instantiated directly).

 - [ ] **Use permissive equality asserts** - when this option is checked (unchecked by default), creating a new test module will declare a `Private Assert As New Rubberduck.PermissiveAssertClass` instead of a `New Rubberduck.AssertClass`. Also consider sync'ing test modules with the status of this option - i.e. if it's checked, *change existing test modules* to use `PermissiveAssertClass`.

...what else?

**Comment by retailcoder** [comment]
If #291 is implemented, then this setting should also determine whether a new test module gets created with a late or early bound `AssertClass`.

Also:

 - [ ] **Use permissive equality asserts** - when this option is checked (unchecked by default), creating a new test module will declare a `Private Assert As New Rubberduck.PermissiveAssertClass` instead of a `New Rubberduck.AssertClass`. Also consider sync'ing test modules with the status of this option - i.e. if it's checked, *change existing test modules* to use `PermissiveAssertClass`.

**Comment by ckuhn203** [comment]
Sounds like it for now. I like this idea. :+1:

**Comment by Hosch250** [comment]
Completed.
