### ISSUE TITLE
Parser errors should disable code inspections

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#787]
When the code can't be parsed, identifier references cannot be properly resolved, which makes inspections report false positives.

Let's add a flag in the parse results that turns on when there are parser errors, and use that to disable code inspections / display a user-friendly message in the code inspection results window to that effect.

**Comment by ckuhn203** [comment]
:+1:  good idea

**Comment by retailcoder** [comment]
Parser errors should also disable refactorings, since refactorings based on partial parse results can completely break the code.

**Comment by retailcoder** [comment]
The infrastructure for this is implemented, every `CommandMenuIten` can override a `EvaluateCanExecute` method that uses the parser state to determine if a menu item should be enabled.
