### ISSUE TITLE
No Add-In available after install

### ISSUE THREAD

**Issue by scottadoyle** [rubberduck-vba/Rubberduck#800]
I just installed the 1.4 Setup file.  The files installed to the Program Data folder but there is no add-in available in the VB IDE.  My setup is Win 10 Home 64 bit.  Excel 2016 32 bit.

**Comment by retailcoder** [comment]
I believe this is the same issue as #629: Office/VBE doesn't look for HKLM keys, so the add-in can only be registered under HKCU, and requires admin privs to register the COM types that enable some of the core features (namely, unit testing) - does it load from a local admin account?

**Comment by scottadoyle** [comment]
If I log into the admin account it does load.

**Comment by ckuhn203** [comment]
@scottadoyle there's a work around in #458. You just need to export the registry keys from HKCU (current user) when logged in as admin, then log in as the target user and execute the .reg file. That should fix it.

Alternatively, this powershell script *should* do the trick. (again, logged in as the target user).

    New-Item -Path 'HKCU:\Software\Microsoft\VBA\VBE\6.0\AddIns\Rubberduck.Extension' -Force

    New-ItemProperty -Path 'HKCU:\Software\Microsoft\VBA\VBE\6.0\AddIns\Rubberduck.Extension' -Name Description -PropertyType String -Value 'Rubberduck'

    New-ItemProperty -Path 'HKCU:\Software\Microsoft\VBA\VBE\6.0\AddIns\Rubberduck.Extension' -Name FriendlyName -PropertyType String -Value 'Rubberduck'

    New-ItemProperty -Path 'HKCU:\Software\Microsoft\VBA\VBE\6.0\AddIns\Rubberduck.Extension' -Name LoadBehavior -PropertyType DWord -Value 3

**Comment by retailcoder** [comment]
I've added the PowerShell commands to the release notes.

**Comment by scottadoyle** [comment]
The script did the trick.  Thanks
