### ISSUE TITLE
Code Inspections UI tune-ups are needed

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#805]
The Code Inspections UI (XAML) needs a bit of a tune-up:

default view:

![image](https://cloud.githubusercontent.com/assets/5751684/10266504/7f523f6c-6a36-11e5-8a9f-e9b578822110.png)

module view:

![image](https://cloud.githubusercontent.com/assets/5751684/10266526/c555d508-6a38-11e5-98b3-1b6e25b11bf5.png)

 - Inspection results need to wrap to fit the available horizontal space, perhaps assuming a minimum width
 - Something is off with the margins in the bottom panel: the qualified module name needs to be a bit further to the right
 - In the treeview, inspection results look very much naked. An icon for each one would feel bloated, and the entire qualified name would feel too verbose - OTOH, seeing "Option Explicit is not specified" 4 times without any visual cue about which instance is about which module, is annoying - at least in the default view.

Anything else?

**Comment by retailcoder** [comment]
Needs visual cue to indicate it's working. v1.4 had a hourglass icon and a label saying "(parsing...)" and "(resolving...)" and "(inspecting...)" to indicate progress; this UI doesn't communicate that background work is being done.

**Comment by retailcoder** [comment]
Module view should use the Code Explorer icons for each module type: office-document, standard module, class module and form.

**Comment by Hosch250** [comment]
In the default view, the item height is not the same size:

![](http://imgur.com/RGX1wkW.png)
---
![](http://imgur.com/z6x6bNK.png)

**Comment by Hosch250** [comment]
Also, it is not impossible to build a resx for these values and use a non-PascalCase name for them.

**Comment by retailcoder** [comment]
I fixed the item height in the data templates when you mentioned the issue @Hosch250, I have it in my fork.

**Comment by Hosch250** [comment]
The individual inspections now have reasonable names, but the different groups do not.

**Comment by retailcoder** [comment]
@Hosch250  correct. we need to localize these enums too - and we'll use these captions in the settings dialog too

**Comment by Hosch250** [comment]
What's up with this issue?

**Comment by retailcoder** [comment]
Closing. The `TreeView` is gone and replaced with a `GroupingGrid` now, which solves all of the layout issues. I deem the *Inspection Results* toolwindow pretty much final at this point. *Maybe* some minor last-minute tweaks will happen though.
