### ISSUE TITLE
Error while using the latest commit

### ISSUE THREAD

**Issue by INOPIAE** [rubberduck-vba/Rubberduck#808]
If I compile from next (728a815)  and go to the VBA Editor I get this error in line 11 of VBProjectParseResult.cs
(German error message)
InvalidCastException wurde nicht von Benutzercode behandelt.

"Eine Ausnahme vom Typ "System.InvalidCastException" ist in System.Core.dll aufgetreten, doch wurde diese im Benutzercode nicht verarbeitet.

Zusätzliche Informationen: Das Objekt des Typs "<>c" kann nicht in Typ "Rubberduck.Parsing.Symbols.Declaration" umgewandelt werden."

Using Excel 2013 32bit, Visual Studio 2015 Community Edition

**Comment by retailcoder** [comment]
Looking at the home/readme page, the CI build is passing, seems to be a local issue. I understand the invalid cast message, but not what `<>c` might be. [Line 11 of `VBProjectParseResult`](https://github.com/rubberduck-vba/Rubberduck/blob/next/Rubberduck.Parsing/VBProjectParseResult.cs#L22) seems to be the line adding the `Declaration` object that represents the project... and there is no reason for that to happen.

Do you get the same error in VS2013? We are not building Rubberduck with VS2015.

**Comment by retailcoder** [comment]
Oh wait, I just had a facepalm moment. That's a runtime exception, not a compile error...

**Comment by retailcoder** [comment]
Ok so I've merged [next] back into my fork from the main repo... and no repro.

**Comment by retailcoder** [comment]
@Hosch250 had similar issues with VS2015, do you get the same error in VS2013? Note that VS2013 and VS2015 can run side-by-side without any issues.

**Comment by INOPIAE** [comment]
I can reproduce the problem on VS2015 but not on VS2012

**Comment by retailcoder** [comment]
Please use VS2013. If a PR comes along that changes the VS version in the .csproj file, things will break.

**Comment by ckuhn203** [comment]
I'm surprised to hear that 2015 has issues and even more surprised to hear 2012 does not... Yes. Please use 2013. Changes to the *.csproj file are easy to overlook and can cause difficult to fix problems.
