### ISSUE TITLE
Multiple opened instances of the host app break unit testing

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#811]
The code that fetches the `HostApplication` instance does not return the actual *host* instance.

Repro:

 - Open up Excel
 - Start a new instance of Excel, load a macro-enabled workbook with Rubberduck unit tests
 - Run all tests
 - All tests are inconclusive / raise an error about macros not being enabled or test methods that can't be found.

The "host" instance is always only the first one to be opened. This is a problem.

**Comment by ckuhn203** [comment]
This might be extremely difficult to fix. Let me take a look at the code and see if there are any alternatives.

**Comment by ckuhn203** [comment]
We're using `Marshal.GetActiveObject` to get the host instance, which is only guaranteed to return **a** instance of the specified running program. This is indeed a problem. I'm searching for alternatives. 

https://msdn.microsoft.com/en-us/library/system.runtime.interopservices.marshal.getactiveobject(v=vs.100).aspx

**Comment by retailcoder** [comment]
@ckuhn203  If you find anything, get imaginary internet points here: http://stackoverflow.com/q/32953450/1188513

**Comment by ckuhn203** [comment]
Here's a possibility. 

1. Fire up Two instances of excel and open the VBE. 
2. Open the Task Manager
3. Right click the VBE instance and "Go to Process"
4. Note that the process is actually one of the two instances of Excel.

Based on this, we *can* in fact get to the correct host instance.

    class Program
    {

        [DllImport("user32.dll")]
        static extern int GetWindowThreadProcessId(int hWnd, out int lpdwProcessId);

        static void Main(string[] args)
        {
            const int hwnd = 1902056; //replace this value with vbe.MainWindow.Hwnd
            int id;
            GetWindowThreadProcessId(hwnd, out id);

            Console.WriteLine(id);

            var vbeProcess = Process.GetProcessById(id);
            Console.WriteLine("Id: {0}; Name: {1}", vbeProcess.Id, vbeProcess.ProcessName);
            Console.WriteLine();

            foreach (var process in Process.GetProcesses().OrderBy(p => p.ProcessName))
            {
                Console.WriteLine("Id: {0}; Name: {1}", process.Id, process.ProcessName);
            }
        }
    }

**Comment by ckuhn203** [comment]
Now... the hard part if figuring out how to get an `Excel.Application` instance back from the process....

**Comment by ThunderFrame** [comment]
you can get an Application (and a bunch of other properties) from the properties of a document-type vbComponent. That means you can get the Application for an Excel or Word host, from a Workbook/Worksheet or a Word Document.
But, I just found this snippet which suggests that you can get the Application Object from the hwnd...
http://www.experts-exchange.com/questions/25394641/Excel-VBA-Get-an-Excel-instance-from-the-window-handle.html

**Comment by ThunderFrame** [comment]
So, this seems to be the approach:
 1. Get the VBE-hWnd from VBE.MainWindow.hWnd
 2. Get the pID from VBE-hWnd using GetWindowThreadProcessId
At this point we know there must be at least 2 windows that have the same pID, so we need to find the main window...
 3. Get the Main Window hWnd using Process.MainWindowHandle http://referencesource.microsoft.com/#System/services/monitoring/system/diagnosticts/Process.cs,4a6008b8d55b354b
 4. Get the Application object from the MainWindow hWnd using GetAccessibleObject/IDispatch

**Comment by ckuhn203** [comment]
Interesting. Thanks @ThunderFrame.

**Comment by ThunderFrame** [comment]
Referencing #964 - CoelDRAW runs into trouble trying to use `GetActiveObject`

**Comment by ThunderFrame** [comment]
This [SO](http://stackoverflow.com/questions/770173/how-to-get-excel-instance-or-excel-instance-clsid-using-the-process-id) post seems to have the right approach.
 > Once you identify the process via the process id, you can get the Process.MainWindowHandle and then use that along with the AccessibleObjectFromWindow API to get access to the Excel object model for that process.

It references a dead blog post, *Getting the Application Object in a Shimmed Automation Add-in*, which WayBack resurrects [here](https://web.archive.org/web/20130518152056/http://blogs.officezealot.com/whitechapel/archive/2005/04/10/4514.aspx)

**Comment by ThunderFrame** [comment]
And while @retailcoder thinks we can do away with the need for the Application object for running tests, we'll still ultimately need an Application reference once we start enumerating Shapes in host documents etc.
