### ISSUE TITLE
GoTo Implementation could be smarter

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#821]
I have code like this, where `UnitOfWork` is of type `IUnitOfWork`, and `Add` is a method of `IRepository`:

    UnitOfWork.Repository("CustomerGroups").Add NewCustomerGroup(description:=description)
    UnitOfWork.Commit

The VBE's "goto definition" (Shift+F2) resolves to `IUnitOfWork.Commit` and `IRepository.Add`, respectively; Rubberduck's "find all references" works as expected:

![image](https://cloud.githubusercontent.com/assets/5751684/10378862/6c62c150-6dd9-11e5-9e3f-403bc629d1a0.png)

But "goto implementation" doesn't pick it up and does nothing from such an identifier *reference*: it only works from an identifier *declaration*, like if you navigated from the actual interface method, or from the code explorer:

![image](https://cloud.githubusercontent.com/assets/5751684/10378992/32ef386c-6dda-11e5-8039-46f535aa8fa9.png)

We need to get this to work off identifier references, too.

**Comment by retailcoder** [comment]
I'd leave it up for grabs, but the code in the dockable presenter needs to be refactored into a ViewModel and the actual UI needs a XAML-ification first, so this issue is a bit premature...

**Comment by AndrewM-** [comment]
Can you make a history list from Shift-F2 jumps?  In my call tree of 15 procedures for a feature I am working on, I am always using Shift-F2 to go deeper into the code and the Window menu to go back.  Shift F2 works for going deeper but the Window menu does not always do such a good job of going back as it might not take me back to where I made the jump from.  I also have to remember which code-module I jumped from. I takes me a while to re-figure out how things are linked and I get lost on larger call trees frequently.  

The Window menu is a history list and it does remember which procedure (or line number) and it is half good.   The work mentioned above may solve this by making it easier to find and jump to references in the reverse direction.  A history list might just be a dumb list that remembers which procedures were edited during the current session and clicking on a entry will take you there.  This is my rubberducking for the day. 
Cheers.

**Comment by retailcoder** [comment]
@AndrewM- I don't think this would be possible, since the VBE API does not
fire up an event everytime a module is activated, like Excel's
`Worksheet_Activate` handler.

We could implement our own navigation history, but then we wouldn't be
picking up Shift+F2.

That said I feel your pain, that "navigate back" feature is used
extensively in my Visual Studio IDE. If we ever manage to implement a
keyboard hook we'll have to seriously consider reimplementing "go to
definition" and that "navigate back" feature.

**Comment by wqweto** [comment]
@AndrewM- 
>  I am always using Shift-F2 to go deeper into the code and the Window menu to go back.

Can you use Ctrl+Shift+F2 to get back instead of the Window menu?

**Comment by AndrewM-** [comment]
@wqweto Thanks, I will give that a try.  There is also the *last position* option in the context menu in the VBE, that remembers the last five positions.  However if you use find and replace to update some variable's name to a new name, then you effectively loose your ability to navigate back as all the last positions and windows show procedures that were subject to find/replace.  The find and replace is just an opportunistic improvement and not really part of the current flow of code and loosing the navigate back ability is annoying.  Thats the fundamental issue with the build in navigation.

What happens is that you get so used to the shortcomings in ms-office that you don't see them anymore.  So I try to raise them when I think of them.

**Comment by AndrewM-** [comment]
@retailcoder The bar at the top of the IDE updates whenever a different procedure is jumped to.  Can this be a source of navigation history information?  That would avoid having to capture keystrokes.
![currentproc](https://cloud.githubusercontent.com/assets/5060805/10713340/c7ec95de-7afc-11e5-875e-a46474fc01b1.png)

**Comment by retailcoder** [comment]
Perhaps a 'call tree' feature that extends the *find usage* feature and tells you *who's calling who*  would help mitigate the issue?

**Comment by Vogel612** [comment]
This would be consistent with most IDEs I worked with, including information about: Who is calling who and who is called by whom.

**Comment by AndrewM-** [comment]
I think the call tree would be the answer too.  Mz tools already lists the callers and somehow he has managed to do it very smartly. There is however no list of called-by procedures.

**Comment by Hosch250** [comment]
Is this fixed now?

**Comment by Hosch250** [comment]
Obsolete.
