### ISSUE TITLE
Discussion about German translation of "Inspection"

### ISSUE THREAD

**Issue by INOPIAE** [rubberduck-vba/Rubberduck#825]
While working on the German translation I stumbled over the different translation of "inspection" in the area for the "Code Inspection".
I prefere to have a constant way to translate it.
My favourite is "Untersuchung" instead of "Inspektion".
Just my 2 cents

**Comment by Vogel612** [comment]
That's actually a better translation, I agree.

**Comment by ckuhn203** [comment]
If @Vogel's good with it, so am I. +1. 
Thanks @INOPIAE.

**Comment by Vogel612** [comment]
This was fixed in some PR I can't find on mobile right now. Feel free to close :)

**Comment by ckuhn203** [comment]
Taking your word for it. Thanks all!

**Comment by vogel** [comment]
Hmm, not sure why I was mentioned here...

**Comment by ckuhn203** [comment]
My fault @Vogel. I meant to ping @Vogel612. My apologies.

**Comment by vogel** [comment]
Oh right ;) No problems.
