### ISSUE TITLE
Invalid Operation Exception on Startup

### ISSUE THREAD

**Issue by ckuhn203** [rubberduck-vba/Rubberduck#828]
System.InvalidOperationException occurred
      HResult=-2146233079
      Message=Sequence contains no matching element
      Source=System.Core
      StackTrace:
           at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
           at Rubberduck.Root.CommandBarsModule.ConfigureCodePaneContextMenu() in c:\Users\Christopher\Source\Repos\Rubberduck\RetailCoder.VBE\Root\CommandBarsModule.cs:line 59
      InnerException: 

Link to offending line of code: https://github.com/rubberduck-vba/Rubberduck/blob/next/RetailCoder.VBE/Root/CommandBarsModule.cs#L59

**Comment by ckuhn203** [comment]
Changing all instances of 

    var beforeIndex = parent.Cast<CommandBarControl>().First(control => control.Id == sineMenuId).Index;

To

            var beforeControl = parent.Cast<CommandBarControl>().FirstOrDefault(control => control.Id == someMenuId);

            var beforeIndex = (beforeControl == null) ? 1 : beforeControl.Index;

fixes the issue, but I have no idea if using 1 is the right thing or not.

**Comment by retailcoder** [comment]
I think it makes a reasonable default, putting the parent menu as the first child if the expected sibling can't be found in the parent commandbar control, which isn't a crazy thing to do at all, since it's fairly possible that commandbars are user-customized.

:+1:
