### ISSUE TITLE
Test Explorer hangs if it runs with a test module that cannot compile

### ISSUE THREAD

**Issue by AndrewM-** [rubberduck-vba/Rubberduck#831]
To make a series of similar tests, I copied and pasted the last method a number of times, then forgot to rename each method to something different.  The compiler would picks this up if I try to compile but if I try to open Test Explorer without first compiling, then the ms-access application hangs with high processor activity.

**Comment by AndrewM-** [comment]
Renaming a test module via the ms-access GUI whilst Test Explorer window is open might also crash test explorer.

**Comment by Vogel612** [comment]
This one sounds rather nontrivial to fix. Could you add a detailed step-by-step repro to make finding the problem easier for ckuhn and retailcoder?

**Comment by retailcoder** [comment]
Test discovery will run off parse results in 2.0, so we can better analyze what we have before we blindly try to run stuff. This problem will just vaporize once we can display a message about there being same-name methods in the project.

**Comment by Hosch250** [comment]
To get the test to complete execution, cancel the run from the VBE.  What happens is the VBE does not return from the Run call until the user explicitly closes the error notification and cancels the run.  Rubberduck currently has no way of determining whether the test is running for a long time or whether there was a compilation error.
