### ISSUE TITLE
Parsing Expressions with Dates

### ISSUE THREAD

**Issue by AndrewM-** [rubberduck-vba/Rubberduck#836]
This is just a food for thought item.  

Dates in ms-access are a disaster area for non-North Americans.  Allan Browne, perhaps the best source of info on coding in ms-access has written this up http://allenbrowne.com/ser-36.html.  This is like the Y2K bug everyday of the year.  I have two workarounds, both of which are fairly new.  One is to have a user defined type for handling dates (typeSQLDates).  This at least lets me tag the date as an American Date or an International Date.  When using dates in SQL, the American format has to be used, however VBA uses the regional format, so there is a lot of date massaging in my code.  SQL also uses Strings for dates so that is a further complication.  Another solution is to always surround string dates with "# -date- #"  so that I know the date is destined for the where clause in a SQL statement.  

Ideally, it should be possible to detect use of dates in code in ways that are potentially ambiguous. 

Cheers,

Andrew

**Comment by retailcoder** [comment]
Like, scanning every single string literal, check to see if it matches one of *n* date formats, and suggest to use a date literal instead? Possible, yes... performant, not likely. This would have to be implemented as a feature of its own; code inspections don't walk the parse tree looking for literals.

**Comment by AndrewM-** [comment]
Thanks.  My instinct was that it was very difficult. It is not possible to recognise a date format by looking at the date so a better solution is needed.  I will abandon using dates directly in my code and move toward using TypeDate which will allow me to know for sure whether I am using a regional date format or an American date.  The 'struct' will have two members, one of which is of date data type and the other will be a SQL date which will be a string with an American date inside.  That will let me use functions like DateAdd(), then turn around and put the result into a SQL statement using the SQL Date part of the struct.  

There is very low awareness of this issue and it would be good if code inspection raise a flag if there was potential for an issue.  Half the issue is that ms-access VBE does not parse the SQL statement in procedures so issues remain hidden until runtime.  I can see what you mean by code inspections not scanning string literals and that there is no easy solution.

**Comment by retailcoder** [comment]
Well, the VBE parses VBA... Access parses SQL. I don't see Rubberduck parsing SQL either.

**Comment by AndrewM-** [comment]
Agreed.
