### ISSUE TITLE
Mapping relationships between code - Code Explorer

### ISSUE THREAD

**Issue by AndrewM-** [rubberduck-vba/Rubberduck#841]
Code Explorer does a good job of mapping the organisational relationship between procedures.  It shows which procedures are in each class or module (I am writing modern procedural).  As far as I know it does not map how things are functionally related.  In my project, there is a modDrives module for working with storage volumes, a modFolders for working with folders etc.  This makes development easy.  About half the modules provide generic services and can dropped into other projects without adjustment and care is taken to keep application specific logic out of these modules.  The result is that the organisation of procedures in modules does not map to the way code is called.  What I am hoping for is a procedure call tree.

Here is a link to someone else dealing with the same issue.  I have not checked it out yet.
http://www.vbaexpress.com/forum/showthread.php?46027-Building-a-Call-Tree-(work-in-progress)

If the internal infrastructure is present in 2.0, then the user interface could built later.  You already have a lot on your plates.  At this stage, I can't have a crack at it as the API will change with 2.0 and I am not up to speed with C#.

I have manually put together a call tree that results from a button press in my current project to show you why I need one.  The main reason is that I need to prevent conflicts between call trees - a procedure is adjusted to work with one call tree in a way that breaks it for other call trees.  Unit testing will not help as most of my procedures access filing system, operating system and database. Perhaps the issue falls in the integration testing arena.  I just have to be aware of shared parts of the call trees, something I can already do with code explorer, however I have to be able to navigate to called procedures easily first to see if they have other references.

Call tree for updating photo counts.  Brackets indicate a loop.

Level 1 | Level 2 | Level 3 | Level 4 | Level 5
–------ | –------ | –------ | –------ | –------
cmdUpdateCounts |  |  |  |
 | RunCardReviewPhotoCounts |  |  |
 |  | FindNewParentFolderPhotos |  |
 |  |  | ListFiles |
 |  | AppendNewParentDrivePhotos |  |
 |  | (CreatePhotoHashes) |  |
 |  |  | ReadDrivePhotoHashes |
 |  |  |  | DrivePhotoTagsToJson
 |  |  |  | ReadNewDrivePhotoTagsFromJSON
 |  | CountCardVirtualFolderPhotos |  |
End |  |  |  |

**Comment by retailcoder** [comment]
Assuming 0 parse errors, that's indeed something that could be done with
the 2.0 API, and to some extent with the 1.4 API too. I like this idea..
but I don't expect to work on it until after 2.0 is released.

As for not being able to unit test procedures that access the file system
and/or databases, it's a problem that can be solved with interfaces.

If you make a class that's solely responsible for accessing the file
system, and pass that class as a parameter to your procedure, and modify
your procedure to only ever access for file system via that object, then
you can write tests that pass a "fake" implementation that doesn't access
the file system.

The key is interfaces: make an `IFileSystemService` class that only
contains the signatures for the methods you need, and then implement that
in a `FileSystemService` class which `Implements IFileSystemService`, and
access the file system there; then make a `MockFileSystemService` class
that also `Implements IFileSystemService`, but that works off a collection
of strings or whatever, and/or prints to the debug pane. Your actual code
will take any `IFileSystemService` parameter, and use the real class, while
unit tests can give it the mock implementation.

The same can be done for abstracting away a database, with an `IRepository`
interface and perhaps an `IUnitOfWork`, and corresponding *actual* (ADODB)
and *fake* (Collection) implementations - of course it's quite a bit of
work, but who said decoupling VBA code was easy? :smile:

**Comment by retailcoder** [comment]
Actually.. at the level you're interested in, it's already something the 1.4 API can do - *find all references* leverages this ability; this feature request is essentially taking that feature to the next leve:  I like that we can now identify a recursive procedure/function/method.

What the 2.0 API brings, is let's say you have this object:

    Dim foo As New Class1

When `foo.DoSomething` is called, the 1.4 API knows to add an identifier to the declaration of `Class1.DoSomething`; the 2.0 API knows to also add that identifier reference to the declaration of the `foo` variable.

I'm not very far from being able to create a `Declaration` object to represent variables of an unknown type, and then to still be able to resolve `DoSomething` in `foo.DoSomething`, to that on-the-fly declaration; knowing where unresolved/undeclared identifiers are being used opens the door to finally being able to implement a `VariableNotDeclaredInspection` - because `Explicit` is an `Option` after all.. anyway it would also open the door to being able to type code that doesn't compile in the VBE because it's referring to types that don't exist, but then the user clicks `Rubberduck this` in the code pane context menu, and we *generate classes and their members* by analyzing how the undeclared identifiers are used: and then a new era in VBA development has arrived! :happy:

**Comment by AndrewM-** [comment]
That is great!  And i am happy to wait.  

I will stay with procedural coding for now.  Just to let you know the main issue with going OOP in ms-access was loosing the ability to break on error in objects.  I would have know the object broke, then in design time put a breakpoint in the class the rerun the code then step through the code following the breakpoint.  That is a known issue with ms-access and even the bods at FMS have not got a solution for that one other than their clunky procedure logging system.  The break on error was also not as good in visual studio until recently so that also made staying with ms-access an option.  The giant cascade of compiler error messages when one tiny thing is wrong is also something which VBA does not hit people with.  With my approach, I have to replace methods with functions and I do not have letters and getters.  I do not have interfaces either but then neither does ms-access.  My interface substitute is a function prefixed with Run that runs a lot of other functions as a package.  If anything fails, an error message will be returned.  I no longer use functions with single returns but add a success flag, error message etc so the  return data value and the function metadata are kept separate.  This all works brilliantly.  The only disadvantage so far is that functions and the user defined types they operate on are not in the same class package.  The true points of pain lie elsewhere, one is dealing with recordsets as my code rarely processes one record at a time (which would be unit testable) and the other is dealing with GUIs.  Even with as much functionality as possible passed to the middle layer modules, there is a lot of logic in the form modules for locking and unlocking controls and for passing on error messages.  A principle from the Access Bible is that no middle layer class/module should ever display a messagebox.  All messages should be reported via the GUI.  So my code pipes error messages up from deeper levels back to the form code module where a msgbox is displayed.  Each layer adds some info so the error has what amounts to a call stack and generally this info is quite user friendly.  E.g Can't add photo: Photo Collection not set.  The idea of using callbacks is a big and hostile idea for VBA developers.  I don't think that using callbacks would be viable without RubberDuck or MZ tools.  One day I will get around to testing OOP in ms-access again to see how it fares against my current approach.  I think that OOP and unit testing are better friends with Excel.

**Comment by ckuhn203** [comment]
@AndrewM-  Under options there is a radio button that says "Break in class module" that will allow you to do just that. Great feature request btw.

**Comment by AndrewM-** [comment]
MZ tools uses a tree view for identifying procedure callers.  I like this approach.  If this approach was extended a little so that the procedures called by the current procedure were visible, that would be great.  There are fancier approaches such as used by NDepend and Resharper and I have been using NClass which is open source.  These map whole applications at once, which results in complexity.  There is an in between step where the callers and dependencies of a single module are mapped and I think a tree view can handle the results. The UI would probably have two panes.  The top one would show the current class or modules procedures.  The bottom pane would have a tree view that updates when a procedure in the top pane is clicked.  There would probably also be a whole module option which shows everything the module is connected to.  In summary, there would a drill down approach to reduce clutter.

**Comment by retailcoder** [comment]
We can definitely come up with a treeview or something, to list a member's callers - the 1.x *find all references* toolwindow already somewhat does that, albeit in a very basic way: this *will* be improved in future releases.

**Comment by retailcoder** [comment]
the 2.x improved *find all references* is deemed sufficient. perhaps a separate plugin will be a better place to implement this feature come RD 3.0.
