### ISSUE TITLE
Renaming a Class Module in the Code Explorer errors

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#847]
I have a class module that I wanted to rename. I right clicked on it in the _Code Explorer_, selected _Rename_ and gave it a new name. (Note: the entire code base does compile cleanly) I got the following error, and the module was NOT renamed:

>************** Exception Text **************
System.ArgumentOutOfRangeException: Index and count must refer to a location within the string.
Parameter name: count
   at System.String.Remove(Int32 startIndex, Int32 count)
   at Rubberduck.Refactorings.Rename.RenameRefactoring.GetReplacementLine(String content, String newName, Selection selection) in c:\Users\Mathieu\Source\Repos\Rubberduck\RetailCoder.VBE\Refactorings\Rename\RenameRefactoring.cs:line 359
   at Rubberduck.Refactorings.Rename.RenameRefactoring.RenameUsages(Declaration target, String interfaceName) in c:\Users\Mathieu\Source\Repos\Rubberduck\RetailCoder.VBE\Refactorings\Rename\RenameRefactoring.cs:line 321
   at Rubberduck.Refactorings.Rename.RenameRefactoring.Rename() in c:\Users\Mathieu\Source\Repos\Rubberduck\RetailCoder.VBE\Refactorings\Rename\RenameRefactoring.cs:line 153
   at Rubberduck.Refactorings.Rename.RenameRefactoring.Refactor(Declaration target) in c:\Users\Mathieu\Source\Repos\Rubberduck\RetailCoder.VBE\Refactorings\Rename\RenameRefactoring.cs:line 52
   at Rubberduck.UI.RefactorMenu.Rename(Declaration target) in c:\Users\Mathieu\Source\Repos\Rubberduck\RetailCoder.VBE\UI\RefactorMenu.cs:line 452
   at Rubberduck.UI.CodeExplorer.CodeExplorerDockablePresenter.RenameSelection(Object sender, TreeNodeNavigateCodeEventArgs e) in c:\Users\Mathieu\Source\Repos\Rubberduck\RetailCoder.VBE\UI\CodeExplorer\CodeExplorerDockablePresenter.cs:line 144
   at Rubberduck.UI.CodeExplorer.CodeExplorerWindow.RenameContextButtonClick(Object sender, EventArgs e) in c:\Users\Mathieu\Source\Repos\Rubberduck\RetailCoder.VBE\UI\CodeExplorer\CodeExplorerWindow.cs:line 127
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

>************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.100.0 built by: NETFXREL2STAGE
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Rubberduck
    Assembly Version: 1.4.3.2343
    Win32 Version: 1.4.3.0
    CodeBase: file:///C:/ProgramData/Rubberduck/Rubberduck.DLL
----------------------------------------
Microsoft.Vbe.Interop
    Assembly Version: 14.0.0.0
    Win32 Version: 14.0.4760.1000
    CodeBase: file:///C:/windows/assembly/GAC_MSIL/Microsoft.Vbe.Interop/14.0.0.0__71e9bce111e9429c/Microsoft.Vbe.Interop.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.91.0 built by: NETFXREL2STAGE
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
Rubberduck.VBEditor
    Assembly Version: 1.0.5667.2338
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/ProgramData/Rubberduck/Rubberduck.VBEditor.DLL
----------------------------------------
Rubberduck.Parsing
    Assembly Version: 1.0.5667.2339
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/ProgramData/Rubberduck/Rubberduck.Parsing.DLL
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
PresentationFramework
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
PresentationCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_64/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
System.Xaml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
----------------------------------------
Rubberduck.SourceControl
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/ProgramData/Rubberduck/Rubberduck.SourceControl.DLL
----------------------------------------
Ninject
    Assembly Version: 3.2.0.0
    Win32 Version: 3.2.2.0
    CodeBase: file:///C:/ProgramData/Rubberduck/Ninject.DLL
----------------------------------------
NLog
    Assembly Version: 3.2.1.0
    Win32 Version: 3.2.1.0
    CodeBase: file:///C:/ProgramData/Rubberduck/NLog.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
office
    Assembly Version: 14.0.0.0
    Win32 Version: 14.0.4760.1000
    CodeBase: file:///C:/windows/assembly/GAC_MSIL/office/14.0.0.0__71e9bce111e9429c/office.dll
----------------------------------------
CustomMarshalers
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_64/CustomMarshalers/v4.0_4.0.0.0__b03f5f7f11d50a3a/CustomMarshalers.dll
----------------------------------------
Antlr4.Runtime.net45
    Assembly Version: 4.3.0.0
    Win32 Version: 4.3.0.0
    CodeBase: file:///C:/ProgramData/Rubberduck/Antlr4.Runtime.net45.DLL
----------------------------------------
Microsoft.CSharp
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------

**Comment by retailcoder** [comment]
The exception was thrown on [this line](https://github.com/rubberduck-vba/Rubberduck/blob/next/RetailCoder.VBE/Refactorings/Rename/RenameRefactoring.cs#L379):

     var contentWithoutOldName = content.Remove(selection.StartColumn - 1, selection.EndColumn - selection.StartColumn);

The assumption being that `selection.StartColumn` is non-zero, and `selection.EndColumn - selection.StartColumn` is greater than or equal to 1.

This looks very much like it could be an off-by-one error that could result in a `0` being passed to the `count` parameter of the `String.Remove` method, more specifically when a usage is located in column 1.

I've just reproduced this on the release build:

![image](https://cloud.githubusercontent.com/assets/5751684/10790827/dd612400-7d5b-11e5-8a95-69dbe193ec6a.png)

Results in the same exception thrown on the same line:

![image](https://cloud.githubusercontent.com/assets/5751684/10790846/f82c4b20-7d5b-11e5-83f5-88e8399e63a7.png)

I couldn't reproduce it without a reference to the renamed identifier in column 1... how's your indentation? :wink:

**Comment by daFreeMan** [comment]
Umm.. I don't have a `Private foo As Class1` in my code. 

![rd rename class](https://cloud.githubusercontent.com/assets/11889733/10798671/39bb09be-7d7f-11e5-97e4-905fa6f5bb00.PNG)

but I do start in column 1

**Comment by retailcoder** [comment]
@daFreeMan I'm just curious, what code references a class name in column 1?

**Comment by daFreeMan** [comment]
Ah, gotcha:

```vb
Private Function GatherData(ByVal SatAddress As String, ByVal ApptAddress As String, ByRef Clinics As ProcessClinic) As Collection

Dim CI As ClinicItem
```

I guess most people would indent the `Dim` statement? Not sure why, I've always left-justified my declarations.

Would indenting them be a short-term workaround?

**Comment by retailcoder** [comment]
Wait, no. I didn't reproduce the issue with a `Dim` statement on column 1. I reproduced the issue with *the actual identifier reference* in column 1 (see my screenshot above), which is tons more awkward than non-indented `Dim` statements ;-)

**Comment by daFreeMan** [comment]
The only thing I've got is `Dim x as ClinicItem`, I don't have a `Private x as ClinicItem` anywhere in my code for this workbook.

**Comment by Hosch250** [comment]
Can I say that this is now obsolete?
