### ISSUE TITLE
Thoughts on Reporting

### ISSUE THREAD

**Issue by AndrewM-** [rubberduck-vba/Rubberduck#848]
It is important to put pen to paper before the idea evaporates and this is not a feature request but something of interest to me and probably the reason I will need to leave ms-access in the future.  I have long since abandoned using ms-access reports.  Instead I write php like procedures that generate html reports.  These reports can be opened in ms-word or LibreOffice and edited and then pdf'd.  It is a very clean process and the reports created honour text styles such as headings.  The limitation is that I can't put menus or buttons on my reports that call ms-access to generate another page.  That is web server territory, however it would be nice if a report in a browser could call functions within ms-access.  Being able to use a browser for a local application would be great.  There is a developing application called spider basic that works like this but I am not sure if it can use database back ends.  Would it be possible in theory to develop a controller that calls a particular function in ms-access or a dot net application from a browser?

The attachment shows what kinds of reporting are possible once you start using VBA to make reports.
[PhotoSurvey.pdf](https://github.com/rubberduck-vba/Rubberduck/files/31384/PhotoSurvey.pdf)

Andrew

**Comment by retailcoder** [comment]
Hmm this is quite a bit beyond the scope of Rubberduck. I wouldn't go and reinvent the wheel here; get SQL Server Express 2014 with advanced features / SQL Server Data Tools (it's free!), and then you get the real deal with (almost full-featured) SSRS reports with the drill-up/drill-down capabilities you're looking for. It's more of a server than a desktop solution, but reporting *is* a server solution.

**Comment by retailcoder** [comment]
To answer your question - if I understand correctly yes it's possible, but I can only imagine something that works off a server.

**Comment by AndrewM-** [comment]
Thanks for responding.  I have just grasped a simple solution.  Put a link to *home* on every ms-access generated html file.  The home link goes to an asp.net home page from which all other reports are accessible.  If this page is missing, then ms-access generated html pages are still available.  This solution provides lots of flexibility. That was a case of the rubberduck principle, talk about it and the solution appears.  Thanks again.
Andrew
