### ISSUE TITLE
Integration Testing Idea

### ISSUE THREAD

**Issue by AndrewM-** [rubberduck-vba/Rubberduck#849]
About 15% of my current project can be unit tested without drama.  That puts a huge responsibility on integration testing and regression testing and there does not seem be be any framework for these types of tests.  I know that you have suggested that unit testing can also be used at these levels, however that would require a lot of set-up code.  I have another idea.  Create a list similar to the todo: list of workbench integration tests.  I would not use the todo: list for specifying tests as the purpose of the todo: list is to be as short as possible and the purposed of the test list is to be as inclusive as possible.  I am working on a prototype written in VBA.  The idea is to specify some tests when coding and how to run the tests in a way that tests the code, for example leaving a date field blank to see if null dates are handled.  Manual testing probably still has a role for junior developers who can't code in a way that increases applicability of unit tests.  There are also processes that are hard to isolate from the real world for testing and where mocking or some other difficult technique is usually used by professional developers but where workbench testing would be easier for junior developers.  

I have looked around and found a project that almost fills the bill.  https://github.com/amir-saniyan/Peygir.  I have downloaded it, manually reviewed most of the code for trojans and tried it and it is a bug tracker rather than organiser for manual test scripts.  However it is a C# open source project that stored data in an mdb file and is close enough to what I want to morph into what I want.  I use Asana and github but sometimes do no want to use the cloud. Here is a link to a manual test script template http://stackoverflow.com/questions/1550157/manual-test-script-templates.  That is the type of thing I am tempted to morph Peygir into-shame I am still useless at C#.

I would like to be able to display a list of factors that need to be tested for with a given form.  With ms-access, I can always make a copy of the database with local tables and manual stuff up some of the table data rather than mocking.  I could even put SQL statements in the test script database that recreate the data that causes a bug (could also put in a button to run the SQL).  This approach would also remove the need to separate the code from the GUI for testing.  If you know of anything that comes close, cloud based or not, could you please let me know.

**Comment by ckuhn203** [comment]
Hey @AndrewM-, can you clarify what exact feature you're looking for here? At a glance, this seems to be out of the project's scope.

**Comment by AndrewM-** [comment]
Hi @ckuhn203, I am also thinking that a separate tool should be used for writing functional and workbench integrations tests.  The only import factor is when coding to be able to create an entry for a functional/integration test.  For example, I might want to test progress meter function on large data imports.  This is something I don't to unit test as there is too much overhead, but I would like to flag it for function testing.  A separate application running at the same time as the VBE would seem to provide the most flexibility.  I just want 2.0 to have foundations for future features so that they can be implemented with point releases so I am racking my brains to see if their are any significant gaps.

**Comment by ckuhn203** [comment]
I'm not sure that creating this toolset inside the VBE is a great idea. Typically, these kind of test scripts (like Holywood) are stored in an external system. You could probably leverage the existing TODO system to accomplish this though. 

You could define your own `@todo` tokens in the options dialog to keep it in the code if you really wanted to store this in the code, but I'm not sure that I'd recommend it. You may be better off seeing what other tools are already available for documenting features & test cases. Like, some open source version of Visual Studio Online.

**Comment by AndrewM-** [comment]
I agree with you.  The one exception might be using the todo list to identify code that needs testing for regressions.  The reason being that the best place to add a note about regression testing is when the bug is being fixed.
