### ISSUE TITLE
Feature request, sort variable declarations

### ISSUE THREAD

**Issue by AndrewM-** [rubberduck-vba/Rubberduck#854]
I often declare about 30 variables declared at the top of a procedure and it would be nice to be able to sort them.  There are three ways to sort the variables in my mind.  First is just an alphbetical sort by variable name, next is sorting by variable type, then by variable name and the last is how I currently do it, I make one list for scalar variables and another for non-scalars (arrays, types, enum, objects).  The go for me would able to select one of the variable lists, right click and sort by type, then name.

**Comment by retailcoder** [comment]
If a procedure has 30 locals, it's clearly doing too many things. The correct way of addressing this isn't to sort the many locals, but to extract simpler, more specialized methods.

I would feel like RD gave tools to fix the symptoms rather than the actual issue, if this were implemented.

**Comment by AndrewM-** [comment]
Normally I would agree but some complex procedures defy method extraction.  I am often building mulitple SQL statements to run, then writing results to text files etc and as several domains are involved, the variable count goes up.

**Comment by retailcoder** [comment]
Oh that reminds me, I need to verify that line-continuated string concatenations no longer break the parser!

Would you have an example of such a procedure handy?

**Comment by AndrewM-** [comment]
This module is quite rich in string concatenations.

[AppCodeImportExport_ACM.txt](https://github.com/rubberduck-vba/Rubberduck/files/43330/AppCodeImportExport_ACM.txt)

In my case, i mostly break long expression up into smaller expressions, which is one of the reasons I use more variable names - they hold intermediate results.  it is a variation on self documenting code where I waste variable names to avoid having to work out what I have at each stage of computation.  

Here is a typical example of folding SQL strings.
[Refreshdata.txt](https://github.com/rubberduck-vba/Rubberduck/files/43332/Refreshdata.txt)

Cheers

**Comment by retailcoder** [comment]
Interesting code.. have you seen Blackhawk's `StringBuilder` class on Code Review? (search for "[vba] StringBuilder is:question" using the site's search functionality) - it's using low-level memory management, the result is a builder that's actually faster than the VBA runtime! Worth a look anyway..

I see what you're doing with these intermediary variables, I'd suggest you move their declaration closer to usage. It's a bit awkward when you're not used to it, but there's no coming back after you've seen the benefits - it defeats the *need* to sort a wall of declarations, and you find the declarations right next to where they're used.

If you're interested in feedback and/or ways to improve, or for help/hints with refactoring your working code, I cannot recommend posting it on [Code Review](http://codereview.stackexchange.com) enough.

**Comment by retailcoder** [comment]
#884 / "Move closer to usage" refactoring antagonizes this feature. Together with #168 / "Extract Method", they are the proper way of addressing the "too many local variables" code smell. Sorting them is only putting lipstick on a pig (no offense intended).
