### ISSUE TITLE
On Local Error

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#857]
An obsolete `On Error` syntax went under the radar and breaks the parser. Grammar needs to support it.

    On Local Error Goto handler

Also need an inspection and quickfix to find them and replace with `On Error` statements.

**Comment by retailcoder** [comment]
merging referenced commit closed this issue

**Comment by ThunderFrame** [comment]
Should there be a code suggestion for removing the *Local* keyword?

**Comment by retailcoder** [comment]
@ThunderFrame I'm pretty sure there's an issue for that. It's a simple one to implement, but involves a custom parse tree listener to pick up the `OnErrorStmt` parser rules and evaluate whether the `LOCAL` token is non-null - just like the other obselete statements, it's picked up *as the parse tree is being generated*; we don't want to re-walk the parse trees just to see if there's a `On Local Error` somewherr.
