### ISSUE TITLE
Declare Function identifier should support type hints

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#858]
Declare Function Foo$ ...

The type hint breaks the parser.

**Comment by retailcoder** [comment]
Interestingly the `typeHint` is already in the grammar rule, but after the `FUNCTION` token:

    declareStmt : (visibility WS)? DECLARE WS (PTRSAFE WS)? ((FUNCTION typeHint?) | SUB) WS ambiguousIdentifier WS LIB WS STRINGLITERAL (WS ALIAS WS STRINGLITERAL)? (WS? argList)? (WS asTypeClause)?;

adding another `typeHint` after the `ambiguousIdentifier` should fix it.

**Comment by Vogel612** [comment]
@retailcoder that would imply you can legally `Declare Function$ Foo$ ...` can you do that?? If not that needs a separate branch, right?

**Comment by retailcoder** [comment]
@Vogel612  indeed, the grammar would technically support it. But for sanity's sake, one assumption we've had from the beginning of working with the ANTLR grammar is that VBA can compile the code we're throwing at it.

**Comment by Vogel612** [comment]
sidequestion: is this caught for #200 ?

**Comment by retailcoder** [comment]
@Vogel612 good question. Probably not.

**Comment by retailcoder** [comment]
merging referenced commit closed this issue
