### ISSUE TITLE
Instructions separator breaks parser in specific circumstances

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#861]
This parses:

    Dim foo As Integer: foo = 42

This doesn't:

    fn = FreeFile: Open "filename" For Output As #fn: Close #fn

...and it should.

**Comment by retailcoder** [comment]
Update - this parses:

    Dim foo As Integer: foo = 42

This too:

    fn = FreeFile: Open "filename" For Output As #fn: Close #fn

But this doesn't:

    Dim fn As Long: fn = FreeFile: Open "filename" For Output As #fn: Close #fn

**Comment by retailcoder** [comment]
This doesn't parse either:

    Dim fn As Integer
    fn = FreeFile: Open "filename" For Output As #fn: Close #fn

Adding [critical] label, this needs to be fixed once and for all.

**Comment by Hosch250** [comment]
The last argument in a `ICS_B_ProcedureCallContext` is dropped with the following token is an instruction separator.  The comma is kept where relevant.

**Comment by retailcoder** [comment]
Sub Foo()
        Dim renamed: renamed = FreeFile: Open "filename" For Output As #renamed: Close #renamed
    End Sub

Fixed, finally. The problem was the `#fn: Close #` was being parsed as a ....*date literal*, because the `DATELITERAL` lexer rule was too relaxed:

    DATELITERAL : '#' (~[#\r\n])* '#';

Changing it to the format enforced by the VBE fixed the issue:

    DATELITERAL : '#' [0-9]+ '/' [0-9]+ '/' [0-9]+ '#';

That's still more relaxed than it needs to be, but it's tight enough to not mistake anything between `#`'s for a date literal.

**Comment by ckuhn203** [comment]
Well done!

**Comment by ThunderFrame** [comment]
Does it parse, and does the code inspector warn you if you use a literal file handle?
```
Open "filename" For Output As #1: Close #1
```

**Comment by retailcoder** [comment]
@ThunderFrame it parses, but there's no inspection for literal file handles - good call here; the quickfix would be tricky to implement though, since literals aren't handled the way identifiers are.. but not impossible. It should at least recommend introducing a local integer assigned to the result of the built-in `FreeFile` function.

**Comment by ThunderFrame** [comment]
How about a double declared with a trailing \#, used as the file handle?
```
Sub test()

  Dim freefile1#
  
  freefile1 = freefile
  
  Open "c:\bin\Temp.txt" For Binary Access Write As #freefile1#
  Close #freefile1

End Sub
```

**Comment by retailcoder** [comment]
Yup, parses fine.

    Sub test()
    
      Dim renamed#
    
      renamed = FreeFile
    
      Open "c:\bin\Temp.txt" For Binary Access Write As #renamed#
      Close #renamed
    
    End Sub
