### ISSUE TITLE
Feature that changes a static referenced library to be optional

### ISSUE THREAD

**Issue by hapm** [rubberduck-vba/Rubberduck#863]
It would be nice if you could select a static referenced library and Rubberduck would change it to be dynamically referenced one. This includes:
1. Declarations of any variables/parameters defined as being from a type of the selected library should be changed to be an Object or Variant type, based on the original type being an object or a simple type.
2. `New TypeFromLibrary` in any expression
   
   needs to be replaced by 
   
   `CreateObject("LibraryCreateObjectName.TypeFromLibrary")`
3. `Dim x As New TypeFromLibrary`
   
   in subs and functions needs to be replaced by
   
   ```
   Dim x As Object
   Set x = CreateObject("LibraryCreateObjectName.TypeFromLibrary")`
   ```
4. `Static x As New TypeFromLibrary`
   
   in subs and functions needs to be replaced by
   
   ```
   Static initialized_x As Boolean
   Static x As Object
   If Not initialized_x Then
       initialized_x = True
       Set x = CreateObject("LibraryCreateObjectName.TypeFromLibrary")`
   End If
   ```
5. The static project reference to the library needs to be removed of course. Thats what this is all about.

There are several conditions that come in my mind, where this wouldn't work. These should be checked before applying the modification:
1. There is a module variable defined as `(Private|Public|Friend|Dim) VarName As New TypeFromLibrary` in a none user defined class module.
   In this case the initialization of VarName can only happen correctly if the module is a user defined class, and the initialization is moved to the Class_Initialize subroutine.
2. There is a module that references anything else than object types (enum values, functions, subs, properties, etc.) from the global space of the referenced library. Some of these could be redefined as private constructs in the referencing modules, but at least the subroutines and functions would get tricky to replace correctly.

If I missed any preconditions to be checked or you have a solution to make some of these needless feel free to comment.

This is a minor priority feature request that bothers me atm, when deploying some of our ms office solutions. I love to have the intelli sense you get with a static referenced library at development time, but there is plenty of code that would work without problems (by not using optional libraries) for deployed projects, if the refenced libraries would be optional. But removing all the type references based on the rules given above by hand is a very odd and error prone task to do when you need to deploy a new version, especially when you drive a CI approach as we do.

**Comment by retailcoder** [comment]
I like this very much.. it would even be applicable to `Rubberduck.AssertClass`!

**Comment by hapm** [comment]
This is another feature I think about: automatic removal of test modules. This idea is also stolen from AccUnit (like the extended comments suggested in #856) what supports this already.

**Comment by retailcoder** [comment]
Not sure I agree with that though - RD test modules have `Option Private Module` and don't interfere with public macros and UDF's in any way, and with late-bound `AssertClass` they don't interfere with anything at all, and only increase file size by negligible amounts. I can only find reasons one would *keep* tests in the project... why would you remove them?

**Comment by ckuhn203** [comment]
This isn't as simple as it seems at a glance. The type name `Rubberduck.AssertClass` doesn't necessarily map to `CreateObject("Rubberduck.AssertClass")`.  I can't think of an example off the top of my head, but I know that it's not necessarily a one to one mapping.

**Comment by retailcoder** [comment]
@ckuhn203 `Rubberduck.AssertClass` is the ProgID the class is COM-registered with (e.g. [here](https://github.com/rubberduck-vba/Rubberduck/blob/next/Rubberduck.UnitTesting/AssertClass.cs#L12)) - so indeed, it's not *necessarily* [Library].[ClassName].

**Comment by ckuhn203** [comment]
I wouldn't count it out entirely. There may be some COM magic that can be performed. I was just commenting to help us avoid a naive implementation down the road. =)

**Comment by retailcoder** [comment]
ref. #1184
