### ISSUE TITLE
Remove (destroy?) declaration alignment

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#864]
Some devs like to vertically align the `As` clause of blocks of declarations, "for readability".

    Public WbSubsheet                                   As Workbook     '/ Contains all Lumin Wealth submitted Business
    Public WbAdviserReport                              As Workbook     '/ Will Contain an aggregation of the subsheet and a submission report (by month) for each adviser

    '/ Adviser Report worksheets
    Public WsAggregatedData                             As Worksheet    '/ Will contain the aggregated subsheet data
    Public WsAdviserReport                              As Worksheet    '/ Will contain the submissions report, reported by Adviser
    Public WsProviderReport                             As Worksheet    '/ Will contain the submissions report, reported by Provider
    Public WsProductReport                              As Worksheet    '/ Will contain the submissions report, reportrd by Type of Business
    Public WsChangedData                                As Worksheet    '/ Record of Data CleanUp

...and it *might* help a bit. The problem is that mainaining this alignment is sheer waste of time, especially when the original author used meaningless names and you want to refactor/rename them. 

Fixing this manually is also a waste of time, so let's add an inspection/quick-fix that detects multiple spaces between the end of an identifier declaration and the beginning of its `As` clause; the quick-fix would simply replace all whitespace with a single `WS` token.

**Comment by Vogel612** [comment]
Isn't this more part of the smart-indenter side??? I'd say that this is rather a lint than an inspection. The functional idea behind this is not affecting the functionality of the code per se, but just the whitespace in it.... I'd say that would be better suited in smart-indenter instead of a code-inspection

**Comment by retailcoder** [comment]
Thar makes sense, I'll see if SmartIndenter does it already.

Sent from my toaster

**Comment by retailcoder** [comment]
Smart Indenter handles this.
