### ISSUE TITLE
Reassign debugging keys to more convenient keys

### ISSUE THREAD

**Issue by AndrewM-** [rubberduck-vba/Rubberduck#865]
I get RSI when debugging VBA from doing shift-control-F8.  I notice that Visual Studio has F10 and F11, which are better.  Can't say I like Shift F11.  I wonder if these debugging keys could be mapped to the number pad or something so that a only a single and easy key press is needed to step forward via any of the built-in methods.

**Comment by ckuhn203** [comment]
Nope. Not a possibility. It's not exposed through Microsoft's API. Sorry.

**Comment by retailcoder** [comment]
@ckuhn203 I think it *is* possible - the "step into" and "step through" functionalities have menu items that can probably be invoked programmatically. I suggest we leave this issue closed and take it to the broader #866 about hotkeys in general.

**Comment by AndrewM-** [comment]
If you can rework the hotkeys, this suggests another possibility.  When stepping through code, I am always falling into commonly called procedures that have been run millions of times and which do not need checking.  Some examples include AddTrailingSlash(), StripSlash(), and particularly PushStack and PopStack, which generate a call stack for error reporting.  I wish there was a skip over list for these functions so that I do not find myself in them.  Pushstack is the first line of a called procedure so it is hard to avoid.  If I use shift F8, to skip of the common procedures, then I often accidentally skip important procedures and it can be hard to go back by dragging the yellow arrow.  If you can reimplement the F8 key function, then it could be modified to skip over flagged procedures.  Perhaps an new debugging key could be added for this.  The question would be how to flag the procedures to be skipped.  I imagine that some kind of in memory array would be needed to implement the feature at runtime, and you already have a code parsing system that can be used to parse the code and build such an array.  Perhaps something simple might do the trick such as putting a #$ at the end of a comment.  It would be nice if a list of procedures that are skipped could also be displayed, in the way a todo list is displayed.

**Comment by retailcoder** [comment]
@AndrewM- that's a whole can of worms there! I don't think it's impossible (although I'd rather use some `'@DebugStepOver` annotation at the top of such a procedure), but we're talking about something that *might possibly* become something to think about in 3, maybe 4 releases. Mental note taken though :wink:

**Comment by ckuhn203** [comment]
Again, we're getting into implementing a debugger and if we get into that, we might as well develop our own IDE.

**Comment by AndrewM-** [comment]
I appreciate what you are saying but when the IDE is causing me pain is the best time to try and figure out what it is that can be improved.  The alternative solution to the above issue is to put break points in the key procedures or to use watch windows.  I have never enjoyed using watch windows for some reason and this is one of my weaknesses.  So back to breakpoints.  If there is a code mapping tool, which I have suggested elsewhere, then I could easily find places to add break points and use F5 to skip over the bits I am not interested in.

**Comment by retailcoder** [comment]
@ckuhn203  if there's a way to programmatically trigger these VBE commands, I say why not - we'll need a settings page to assign the hotkeys anyway. just not top-priority.

**Comment by AndrewM-** [comment]
I don't mind things being deferred at all.  I just need to write stuff down before I forget.  If there is one wish list item above all others, it is that the main items on the table get done first.

**Comment by retailcoder** [comment]
out of scope, actually.
