### ISSUE TITLE
Parser reports completion before it finishes

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#869]
Apparently the parser state is lying. Critically important that this works as intended.

**Comment by retailcoder** [comment]
@Hosch250 that's the bug you smashed, right?

**Comment by Hosch250** [comment]
It sounds like it.

**Comment by retailcoder** [comment]
:+1:

**Comment by Vogel612** [comment]
Now just to sort out where the heck you smashed it, in case it rears it's head again??

**Comment by Hosch250** [comment]
@Vogel612 It is the `.Wait(token)` in this line here: https://github.com/rubberduck-vba/Rubberduck/blob/next/Rubberduck.Parsing/VBA/RubberduckParser.cs#L41

**Comment by Hosch250** [comment]
Reference commit: https://github.com/rubberduck-vba/Rubberduck/commit/cb3fcc8677f3b352084f4c77b527317ed1156e69
