### ISSUE TITLE
SourceControl Form does not change languages

### ISSUE THREAD

**Issue by INOPIAE** [rubberduck-vba/Rubberduck#871]
I am testing on a German Excel. 
The language of the SourceControl form stays German even if I change the language in the Rubberduck options to English. The menu is in English after the change.

**Comment by retailcoder** [comment]
I bet it'll switch language after restarting the VBE (i.e. quitting and restarting Excel). Likely that the SC panel is only grabbing its captions at startup. This will change in 2.0.

**Comment by INOPIAE** [comment]
No it still does not switch the languages even after a restart of Excel.

**Comment by retailcoder** [comment]
Hmm then the panel wasn't localized at all? @ckuhn203?

**Comment by INOPIAE** [comment]
It is locailzed but to the VBE language and not to the Rubberduck language.

**Comment by ckuhn203** [comment]
No. The feature was never localized. Honestly, it's an incomplete feature still. Bright side is the UI should be stable enough to localize now though. It's what's underneath it that will be changing.

**Comment by Hosch250** [comment]
This will be a non-issue once the XAML view is done.
