### ISSUE TITLE
Problems with SourceControl Form

### ISSUE THREAD

**Issue by INOPIAE** [rubberduck-vba/Rubberduck#873]
It seems to me that the button UpdateGlobalSettings on the global settings panel does not work.

If I try to create a new repro I get this error NullReferenceException thrown in line 434 of Rubberduck.SourceControl.GitProvider. Can this be related that there is no data store in the settings?

**Comment by retailcoder** [comment]
Related / duplicate of: #832 - basically the panel is borked in v1.4.3
