### ISSUE TITLE
Suggest to reverse condition when 'Then' block is empty

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#874]
This code:

```
If foo = 42 Then Else DoSomething
```

Should be rewritten as:

```
If Not (foo = 42) Then DoSomething
```

Or better:

```
If foo <> 42 Then DoSomething
```

But reversing operators might not be trivial in all condition expressions.

Also applies to if blocks:

```
If foo  = 42 Then
Else
    DoSomething
End If
```

Should be rewritten as:

```
If Not (foo = 42) Then
    DoSomething
End If
```

**Comment by Vogel612** [comment]
This might be interesting with more complex if-conditions...

   If foo < CONST and bar <> 545 or baz = 25 Then Else DoSomething

**Comment by Hosch250** [comment]
I handled this for C# code in VSDiagnostics.  I should be able to handle it for VBE code too.

**Comment by retailcoder** [comment]
@Hosch250 does VSD *revert* the operators, or simply sticks a `!` in front of the existing condition? I don't mind either, but it sure makes a smarter ducky if we *actually* revert the operators (correctly accounting for operator precedence and parentheses... doesn't look simple)

**Comment by Hosch250** [comment]
It actually reverts the operators:

!= becomes ==
== becomes !=
> becomes <=
<= becomes >
< becomes >=
>= becomes <
!(condition) becomes (condition)
(condition) becomes !(condition)
&& becomes ||
|| becomes &&

**Comment by retailcoder** [comment]
Ok, so

    <> becomes =
    = becomes <>
    > becomes <=
    <= becomes >
    < becomes >=
    >= becomes <
    Not {condition} becomes {condition}
    {condition} becomes Not {condition}
    And becomes Or
    Or becomes And

What of `XOr`? Also, keep in mind that C# logical operators short-circuit; not VBA's.

**Comment by Hosch250** [comment]
This will definitely be a mite trickier than VSD because Roslyn has that nifty tree defining precedence and stuff, but not impossible.  It will be a little like parsing a mathematical expression, which I have done before.  Also, I think XOr stays the same, but I can't say for sure.

**Comment by Vogel612** [comment]
"A XOr B" is basically "(A and not B) or (not A and B)", inverting those is a little trickier...

**Comment by Hosch250** [comment]
A And Not B inverted makes Not A Or B

**Comment by ThunderFrame** [comment]
Need to consider reversing these too:
    If obj Is Nothing Then
    If Not obj Is Nothing

    If IsArray(aData) Then
    If Not IsArray(aData) Then

**Comment by ThunderFrame** [comment]
Might need to apply the same functionality to Compile Directives.

**Comment by Hosch250** [comment]
Other than the code to figure out which operator needs to be inverted (only the top-level one does), this is easily doable with the rewriters at this point. Basically, this would be a parse tree inspection that checked for empty `if` blocks with non-empty `else` blocks.

A similar inspection would be an `if` block that was empty and either no `else` or an empty `else`. If there was a non-empty `Else If` block, then it would just remove the `if` and the `else` before the next `if` and leave everything else.
