### ISSUE TITLE
Code Inspector correctly identifies unused parameters, but shouldn't

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#877]
In Excel, at least, when you define event routines, Excel will write the code header for you and include a variety of parameters. These are required parameters, even if you don't use them in your code, however RD will flag them as unused. It needs to be smart enough to recognize these subroutines and ignore unused params.

In this screen shot, you can see the sub header as Excel wrote it, the unused params as RD identified them, and the compile error that's generated if I had followed RD's advice and removed the params.

![rd issue](https://cloud.githubusercontent.com/assets/11889733/11880543/48eaf648-a4cf-11e5-8cc3-8a33783d3a50.PNG)

I would think that in Excel, any sub beginning with `Worksheet_` could be excluded from the unused param check, though, for thoroughness, a complete list could be generated and checked against.

Not sure how this impacts the other Office products.

**Comment by retailcoder** [comment]
The 2.0 code base includes an [ExcelObjectModel](https://github.com/rubberduck-vba/Rubberduck/blob/next/Rubberduck.Parsing/Symbols/ExcelObjectModel.cs) class which still needs to define workbook/worksheet events, but once that's defined, this issue should simply disappear, since event handlers (and interface implementations) *should* be correctly ignored by this inspection now.

**Comment by retailcoder** [comment]
That said, we'll also need a similar `WordObjectModel`, `OutlookObjectModel`, `PowerPointObjectModel`, and whatever other VBA host app object model exists that we're officially supporting.

**Comment by daFreeMan** [comment]
Yay!

`AccessModel` would be good, too. Doing a fair bit of that at the moment.

**Comment by retailcoder** [comment]
^^ referencing commit here, declares every single built-in event for `Workbook` and `Worksheet` classes; none of these event handlers cause a `ParameterNotUsed` inspection result now.
