### ISSUE TITLE
ValueNotUsedInspection

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#882]
Sometimes a variable is both _assigned_ and _referred to_, but an inspection should be able to sort the references by line position and locate an identifier that's assigned a value that's reassigned before it's used - in other words a suspiciously redundant assignment involving a value that's never used.

That one is entering the realm of _execution paths_: it needs to account for conditionals and only flag consecutive assignments _in the same execution path_.

**Comment by Hosch250** [comment]
The good news here is this is actually quite easy.

1. Get all the references for a declaration in a given project.
2. Order by start line, then by start column: `.OrderBy(o => o.Selection.StartLine).ThenBy(t => t.Selection.StartColumn)`.
3. If two values in a row are assignments (there is a field in IdentifierReference for this), they are assignments before usage.

One thing to note, though, is this may have false positives in the event the value is used and assigned, such as could happen with the `++` operator that many languages have (not sure if VBA has this).

**Comment by retailcoder** [comment]
There's no `++` increment or `--` decrement operator in VBA.

**Comment by Hosch250** [comment]
Update - this is going to require at least basic execution path evaluation.  That is why it is delayed.

**Comment by Hosch250** [comment]
Mostly done with https://github.com/rubberduck-vba/Rubberduck/pull/4422

**Comment by Hosch250** [comment]
Closing this as possible further enhancements are not detailed in this ticket, and the main work is done. Other enhancements can be brought up after the feature has been in use.
