### ISSUE TITLE
Move variable closer to usage

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#884]
Similar to #564, but for local variables. Moves a declaration to the line just before its first reference.

This refactoring should be triggered using the same menu command that fires #564 (Move field closer to usage), but would only trigger when the target is a local variable (where 564 only triggers when target is a field).

Could/should also be paired with an inspection, and a quick-fix that runs the refactoring.

**Comment by Hosch250** [comment]
What would trigger the inspection?  Being 5+ lines away from usage?  10+ lines?

**Comment by retailcoder** [comment]
The same mental trigger that makes us say "there's too much going on between the declaration and the usage" - too many instructions a declaration and its first reference. You know what, never mind the inspection, let's just do the refactoring.

**Comment by Hosch250** [comment]
Reference commit: https://github.com/rubberduck-vba/Rubberduck/commit/e34fe49d64033ca3165bdeb4836bebc5d29a9316
