### ISSUE TITLE
Reinstate unit tests

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#889]
The 2.0 architecture is nicely extensible, relatively decoupled, and given our capability to fully mock the VBE for testing, it's testable to a much greater extent than before.

Only problem is, 2.0 was a major breaking change and the mechanics of the parser have changed quite a bit.

---

**Parsing in Rubberduck 1.x**

Starting with v1.2, Rubberduck has been pretty much *powered by* Antlr4. The parser worked "manually": you gave it a piece of code and it returned a "parse result", and that result contained the declarations and their resolved identifier references... for the entire project.

And we've written quite a crapload of tests (although, not nearly enough) that depended on this principle: *I give you a VBProject, you give me the parse results*.

**Parsing in Rubberduck 2.x**

The 2.0 parser works differently. Its interface doesn't *return a "parse result"*. Instead, there's the *parser state*: when a module's state changes, it notifies. When all modules' state is "we're good to go", then the *parse result* is "we're good to go" - the Code Explorer can now start receiving the modules pretty much instantly, and then add child nodes as soon as the member declarations are known: it doesn't need to wait for the resolver task to complete, and it doesn't.

That's wonderful. The problem is that, well, our tests are broken. They don't compile, they've been commented-out.

**We need to fix that.**

---

The following test modules are commented-out:

**Inspections**

 - AssignedByValParameterInspectionTests
 - ConstantNotUsedInspectionTests
 - DefaultProjectNameInspectionTests
 - ImplicitByRefParameterInspectionTests 
 - ImplicitPublicMemberInspectionTests
 - ImplicitVariantReturnTypeInspectionTests
 - MultipleDeclarationsInspectionTests
 - NonReturningFunctionInspectionTests
 - ObsoleteCallStatementInspectionTests
 - ObsoleteCommentSyntaxInspectionTests
 - ObsoleteGlobalInspectionTests
 - ObsoleteLetStatementInspectionTests
 - OptionExplicitInspectionTests
 - ParameterCanBeByValInspectionTests
 - ParameterNotUsedInspectionTests
 - ProcedureNotUsedInspectionTests
 - VariableIsNeverAssignedInspectionTests
 - VariableNeverUsedInspectionTests
 - VariableTypeNotDeclaredInspectionTests

This means we're *also* missing tests for these inspections and their results:

 - [ ] ImplicitActiveSheetReferenceInspection
 - [ ] ImplicitActiveWorkbookReferenceInspection
 - [ ] MultilineParameterInspection
 - [x] ObsoleteTypeHintInspection
 - [x] OptionBaseInspection
 - [ ] UnassignedVariableUsageInspection\*
 - [ ] UntypedFunctionUsageInspection
 - [ ] WriteOnlyPropertyInspection
 - [x] EmptyStringLiteralInspection
 - [x] EncapsulatePublicFieldInspection
 - [x] MoveFieldCloserToUsageInspection
 - [ ] ProcedureShouldBeFunction
 - [x] UseMeaningfulNameInspection
 - [ ] MultipleFolderAnnotationsInspection
 - [ ] IgnoreOnceQuickFix

\* that one is not yet implemented; we need to add a `ParserRuleContext` to the `IdentifierReference` type for this to work.

**Refactorings**

 - ExtractMethodTests
 - RemoveParametersTests
 - RenameTests
 - ReorderParametersTests

This means we're *also* missing tests for these refactorings:

 - [x] EncapsulateField
 - [x] IntroduceField
 - [x] IntroduceParameter
 - [x] MoveCloserToUsage
 - [ ] ExtractInterface
 - [ ] ImplementInterface
 - [ ] ExtractMethod (only one test)

**Source Control**

Needs testing:

 - [ ] Clone feature

**UnitTesting**

 - EngineTests

This means we're *also* missing tests for these classes:

 - [ ] PermissiveAssertClass

---

But just reinstating these tests, and writing the missing ones, will not be nearly enough to cover everything. We have navigation commands that have no tests:

 - [ ] RegexSearchReplace
 - [ ] NavigateAllImplementations
 - [ ] NavigateAllReferences
 - [ ] FindSymbol

And then we have the code explorer logic, the settings dialog, menus, context menus, and commandbars, that don't have any tests at all.

The 2.0 architecture makes it much obvious to see where and what the features are: everything\* is a command. Test a command, you've tested a feature.

\*well not everything *everything* yet, e.g. the `ParserStateCommandBar` needs a `ParserCommand` command. But *commandbar* is a bit different, I need to think about it a bit.

**Comment by Hosch250** [comment]
We only have 1 test for Extract method.  I'm not completely sure how that one is supposed to work.

**Comment by retailcoder** [comment]
@Hosch250 the functionality probably needs to be broken down into further specialized objects, individually testable.

**Comment by Hosch250** [comment]
I have one of the refactoring tests set up, but I'm having trouble running the it because somehow the setup seems to be trying to access the refactoring test file in a different location that it is in.  I've no idea why, and would like a second opinion.  The tests that do not use implement a second file do not have this problem, although it may be that they do not have a [setup] block.  (I don't know at the moment, will check later and update this.)

**Comment by retailcoder** [comment]
@Hosch250 *accessing the test file*... wat?

**Comment by Hosch250** [comment]
Remove Parameters tests are back up!

**Comment by Hosch250** [comment]
Reorder Parameters tests are back up!

**Comment by Hosch250** [comment]
Extract Method and Rename tests are back up!

**Comment by retailcoder** [comment]
Some tests are still missing, but "reinstate unit tests" is completed. I'm closing this issue, and let's make new ones for the missing tests.
