### ISSUE TITLE
Fix .resx files

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#893]
Pretty much every single resource string is in `RubberduckUI.resx` and its translations, which is becoming painful to maintain - the .resx editor gets slow, it's well past time to clean this up.

Should we have a separate .resx for each UI/feature? If not, how do we split and organize things?

**Comment by Hosch250** [comment]
I think we should start using the localization feature of the dialogs, etc., themselves.  Each dialog comes with its own .resx - we might as well use it.  I don't know exactly how the windows work, but it it shouldn't be a problem to give each window a .resx if it doesn't have one built in.

**Comment by INOPIAE** [comment]
If you create a set of resx files (currently 5 for each set)  for each dialog common texts will have to be translated many times. e.g.CancelDialogButton

I would prefere to have it all in on resx set.

BTW the RubberduckUI.resx shows quite a few unused entries.

**Comment by ckuhn203** [comment]
Let's start with removing the unused entries, then talk about whether or not splitting them makes sense.

**Comment by retailcoder** [comment]
We could keep the common ones in RubberduckUI.resx. I'm thinking something like this:

 - RubberduckUI.resx
  - Common button captions (Ok/Cancel/Close)
  - "Rubberduck" menu captions
 - InspectionsUI.resx
  - Inspection names, meta/descriptions, types and severities
  - Misc. captions and tooltips for the inspections toolwindow / treeview
 - {dialogname}UI.resx
  - Instructions label, misc. captions and tooltips

Then there's all the icons and images, ...they're a mess!

**Comment by retailcoder** [comment]
So, we have `RubberduckUI.resx` and `InspectionsUI.resx`. I think that's *good enough* for now.. closing.
