### ISSUE TITLE
COMException in ParseComments

### ISSUE THREAD

**Issue by Hosch250** [rubberduck-vba/Rubberduck#907]
This line will sometimes throw a COMException: https://github.com/rubberduck-vba/Rubberduck/blob/next/Rubberduck.Parsing/VBA/RubberduckParser.cs#L67

I notice it usually happens after the VBE is closed and reopened, although I cannot say for sure that is the trigger.  It also keeps happening until I close the host application and restart.

**Comment by retailcoder** [comment]
I wonder if it would help anything to move [this line](https://github.com/rubberduck-vba/Rubberduck/blob/next/Rubberduck.Parsing/VBA/RubberduckParser.cs#L36) into the `try` block to handle a `COMException` by setting an error state on the module.. and removing the key for that "lost" component instance; IIRC a `QualifiedModuleName` has a `string` copy of the component's name, so unless the whole `vbe` instance is scrap (i.e. accessing it throws a COMException), we could always make a new key for a "fresh" instance straight from the VBE API. I think at worse the exception is not caught that basically nothing changes, and at best it makes a clean recovery from a COM "disconnect" episode.

**Comment by retailcoder** [comment]
With the comments in the parse tree, this issue is now moot.
