### ISSUE TITLE
HostApplicationBase should implement IDisposable

### ISSUE THREAD

**Issue by ckuhn203** [rubberduck-vba/Rubberduck#909]
Possible source of COM exceptions and generally not nice things.

[HostApplicationBase][2] owns unmanaged COM resources, but doesn't implement IDisposable.
Instead, it tries to clean up in a [finalizer that may or may not ever run][1].

I simply didn't know what I was doing when I wrote the class. Completely my fault.

This is an api breaking change of sorts. I haven't looked to see how much impact there will be on the codebase, but hopefully it's limited. I don't believe we have calls to it all over the place. 

Anyway, to fix, change `IHostApplication` to inherit from `IDisposable` and implement the full disposable patter in `HostApplicationBase`.

  [1]:http://ericlippert.com/2015/05/18/when-everything-you-know-is-wrong-part-one/
  [2]:https://github.com/rubberduck-vba/Rubberduck/blob/9711a15b107948525dc2977c2e4cab7700905f1e/Rubberduck.VBEEditor/VBEHost/HostApplicationBase.cs

**Comment by retailcoder** [comment]
The *interface* doesn't need to inherit `IDisposable`, the `HostApplicationBase` instance lifetime is managed by Ninject - the concrete type can implement `IDisposable` and the interface can be self-contained.

**Comment by ckuhn203** [comment]
*Need* to, no. You're right. It doesn't need to, but it probably should @retailcoder. The only use case that I can think of that wouldn't have unmanaged resources is some sort of web interface or some such thing. If we put it on `HostApplicationBase` we need to program against its interface instead of `IHostApplication`, no?

**Comment by Hosch250** [comment]
Assigned @ckuhn because he just told me how to do it.

**Comment by ckuhn** [comment]
@Hosch250 I think you got the wrong ckuhn :)

**Comment by Hosch250** [comment]
@ckuhn Yes I did.  Sorry about that.

**Comment by ckuhn203** [comment]
Hahahahaha. Nice.
