### ISSUE TITLE
Allow Copy of selected names in Object Explorer form

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#924]
Allows user to copy selected names (and possibly object type), as text, to the clipboard.

**Comment by retailcoder** [comment]
Good timing, I'm specifically working on the 2.0 Code Explorer window now - I'll see what I can do. You mean copying the *tree node's text*, or just the identifier name (given the node could be displaying full signatures)?

**Comment by ThunderFrame** [comment]
Copy the node text. Ctrl-C would be good, but I'm always amazed at how many people don't know keyboard shortcuts. So maybe a context menu too?

**Comment by retailcoder** [comment]
The more I think of it, the more it's confusing whether the user should expect the identifier to be copied to clipboard, or the entire module's contents, or if pasting it into the code explorer should result in a new module ("CopyOfXyz") being created with the copied content (wait a minute, a *copy/pasta tool in Rubberduck????*)... and I can't find a reason to copy the tree node's text, whether it's the identifier or an entire declaration / signature.
