### ISSUE TITLE
Persist user preference for Hidden Member visibility

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#926]
The VBIDE Object Explorer offers a context menu that exposes the hidden members of objects in Object Explorer and in Intellisense.
In a new session of VBIDE, the default setting is to hide hidden members.
It would be great if RubberDuck could remember a user's preference and show hidden members whenever a new VBIDE opens and the user preference is show.

**Comment by retailcoder** [comment]
out of scope
