### ISSUE TITLE
Allow the insertion/pasting of multi-line string literals

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#929]
Often you'll want to insert a multi-line Lorem Ipsum, SQL-snippet, HTML/XML string, treatise or ASCII Art into VBA, and VBIDE will assume you're pasting multiple lines of code.

It would be nice if you could paste as a multiline string literal, and Rubberduck handles the double-quotes, ampersands and line continuations.
Maybe does inspection and recommends inserting as, or refactoring to a constant.
Maybe even handles the indentation on insert/paste.

**Comment by Vogel612** [comment]
Should be part of basic v3 editor interaction mode
