### ISSUE TITLE
Saved Window Layouts

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#930]
Given RD adds a number of explorers and windows, the potential for window clutter is growing.
It would be great if we could save various window layouts. I'd suggest use-case driven layouts such as:
- Debug
- Refactor
- Inspection
- Coding
- Test

I found this [project](http://perspectives.codeplex.com/) which does something similar for VS layouts.

Eclipse allows saved Perspectives, Photoshop and Illustrator allow "Saved Workspaces"

**Comment by retailcoder** [comment]
:+1: Great idea!

The *window clutter* concern is real.

**Comment by Hosch250** [comment]
Why not just remember which windows were open the last time RD was closed and their positions?

**Comment by ThunderFrame** [comment]
sure, remembering the last layout is useful, but being able to quickly change between preconfigured layouts is more useful.

**Comment by Hosch250** [comment]
We should do both.

**Comment by ckuhn203** [comment]
Both we should do, yes. Brave this developer must be. Many COM Exceptions will block the path to feature. 

Too. Much. Star Wars...

**Comment by ckuhn203** [comment]
Seriously though, I like this feature. I'm just banking on some cryptic COM Exceptions when we try to set a bunch of windows positions and some window we hadn't captured has moved. Totally doable and worth while feature. I just think it's gonna be a PITA to implement.

**Comment by ThunderFrame** [comment]
Fearless he is, heading off into the IUnknown

**Comment by ckuhn203** [comment]
As much as I like this, (and this one definitely ***is*** in scope) I'm concerned that this one might be much more trouble than it's worth. The editor already remembers the *last* window positions, even for our custom toolwindows, without us doing anything. The VBE "magically" stores those positions in the registry and loads them when the VBE opens. Maybe I'm wrong, but I don't think I want to be the guy tackling it.

**Comment by Hosch250** [comment]
I'll take it.

**Comment by whytheq** [comment]
looking forward to this feature - will it be in 2.0? when is 2.0 due? (.... no pressure)

**Comment by ckuhn203** [comment]
6-8 weeks. (Yeah, the Atwood kind of 6-8 weeks.)
The truth is, we're one developer short (me) and 2.0 was a bigger undertaking than originally thought. 

@Hosch250 don't forget to update this SO answer post release. 
http://stackoverflow.com/a/35231909/3198973

**Comment by whytheq** [comment]
Is a coding horror 6-8 weeks actually 12-16 weeks? Wish I could help as I love vba but my c# is not strong enough....I'll keep practising.

**Comment by ckuhn203** [comment]
Sometimes I wish we'd implemented this project in VB.Net. I think our users would have had an easier time contributing. 

Yeah, I believe a Coding Horror 6-8 weeks is essentially double that.

**Comment by whytheq** [comment]
I know vba, a little c#, and lots of useless mdx. I don't think it is a given that vba users are necessarily good at vb.net. I have a friend who is an expert at both vba & c# : maybe it is quite a rare couple of languages to play with as many c# writers look down on vba.

**Comment by daFreeMan** [comment]
Don't forget to include the RD toolbar in saving/restoring placement!

**Comment by ThunderFrame** [comment]
So it seems that the VBE docking abilities are more complex than the documentation suggests, and yet judging by questions online, people struggle with docking. Furthermore, VBIDE doesn't always return accurate information about LinkedWindows, their hWnds or their positions. The VBIDE doesn't expose properties regarding some aspects of docked windows.

It is possible to scale windows proportionally, as well as scale windows individually, but it's not immediately obvious how this is achieved. The gif below shows 2 VBE's (one is Excel, and the other is Word, but the host is unimportant).

The Excel VBE has been configured to have the following docked windows:
 - **Project Window** - Scaled Individually
 - **Properties, Locals & Immediate Windows** - Scaled Proportionally, as a group
 - **Watches Window** - Scaled Individually

The Word VBE has been configured to have the following docked windows:
 - **Project Window** - Scaled Individually
 - **Properties Window** - Scaled Individually
 - **Locals Window** - Scaled Individually
 - **Immediate Window** - Scaled Proportionally
 - **Watches Window** - Scaled Individually

![docking](https://cloud.githubusercontent.com/assets/16574009/21624561/b720f17a-d25b-11e6-988d-7299828b0261.gif)


Notice that when scaling the Excel VBE's Proportional Group, *all* window in the group are scaled proportionally.

**Comment by retailcoder** [comment]
we decided to save window *visibility* instead. completed.
