### ISSUE TITLE
Ribbon Callback helper

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#931]
Wizard for inserting Ribbon callback signatures.

Should probably be PtrSafe and CustomUI version aware.

Link this to Win32 Helper #894

**Comment by ckuhn203** [comment]
@ThunderFrame can you flush out what exactly you'd like this to do? It could be months (or more) before someone gets to it. It'll be nice to have a good user story to help with that. 

>  As a user, I want X, so that Y.
>  It should behave like Z.

**Comment by ThunderFrame** [comment]
As a VBA Developer that uses the Ribbon in Office solutions, I regularly need to write callback functions that allow the Ribbon to behave dynamically, read data from VBA and persist states.
The callback functions must adhere to various signatures, depending upon the Ribbon control type and event. The signatures define the argument types and return type, but not necessarily the callback function names or argument names.

Much like inserting Win32 API declarations (#894), the insertion of Ribbon callbacks in new projects/modules is repetitive and tedious. Parameters must be defined correctly, because otherwise errors (that aren't trapped, by default) can occur.

IMO, a helper for Win32 API declarations is a higher priority, but a helper for Ribbon functions could potentially use the same approach as a Win32 helper. Eg. Have the signatures defined in XML, and RD presents a Wizard/Helper that helps you choose the signature, asks for any optional/extra details, and then builds the VBA declaration.

**Comment by ckuhn203** [comment]
Awesome. Thanks. Are these callback signatures defined by Microsoft, or by the developer? i.e. Could we look up some docs to determine some default, "out of the box", callback signatures?

**Comment by ThunderFrame** [comment]
This [article](http://www.shulerent.com/2011/08/24/definitive-complete-list-of-office-ribbon-callback-signatures-for-2007-and-2010/) gives a good overview, and links to MS articles.

**Comment by ThunderFrame** [comment]
The callback function names are up to the developer, but because they accept an IRibbonControl interface, they can be reused. For example, the GetEnabled signature is:

```
Sub GetEnabled(control As IRibbonControl, ByRef enabled)
...
End Sub
```

If I have 2 RibbonControls, with IDs ButtonA and ButtonB, then I could declare the callbacks like this, and define the appropriate callback name against each respective control in the Ribbon XML:

```
Sub GetButtonAEnabled(control As IRibbonControl, ByRef enabled)
...
End Sub

Sub GetButtonAEnabled(control As IRibbonControl, ByRef enabled)
...
End Sub
```

Or, I can define a common callback name in the Ribbon XML, and define a unified callback in the VBA, like this:
```
Sub GetButtonAEnabled(control As IRibbonControl, ByRef enabled)
  Select Case control.ID)
    Case "ButtonA"
      enabled = False
    Case = "ButtonB"
      enabled = True
  End Select
End Sub
```

**Comment by ThunderFrame** [comment]
So, there's possibly a code suggestion feature in creating unified callbacks..

**Comment by peterennis** [comment]
FYI,
Here is a ribbon callback example for Access: https://github.com/peterennis/aegit/blob/master/aerc/src/basaeRibbonCallbacks.bas
Learnt from the ribbon master Avenius.
Graphic manipulations from  Sascha here:
https://github.com/peterennis/aeGDIPlusDemo/blob/master/src/aeGDayClass.bas
NOTE: Avenius uses the graphics code from Sascha.
I have permission to use the code from Sascha under LGPL3.
You live in C# land so I am not sure how much it helps but I could
certainly be a ribbon tester.
I have done ribbons in Excel and Visio. Never bothered with Word and I don't use Outlook.

**Comment by retailcoder** [comment]
out of scope. might turn into a plug-in someday...
