### ISSUE TITLE
Access Macro to VBA Converter

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#932]
Access has a built-in Macro to VBA converter, but it is really, really bad.

Converting Macros to VBA is relatively easy. It's finding and updating _all_ of the event properties so that they call the code, rather than the macro, that's more difficult.

**Comment by ckuhn203** [comment]
Might be out of scope, but let's talk.
What about Microsoft's tool is lacking exactly?
If we're going to implement something, then I want to be sure we're creating something more valuable than already exists.

**Comment by retailcoder** [comment]
out of scope
