### ISSUE TITLE
Evil VBA Test Case for parser/resolver

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#934]
This isn't even as nasty as it could be. My own brain started to have lexing issues...
```
'Project Name = MyProject
'Module Name = MyModule
Option Explicit

Private MyVar As MyProject
Private MyVar1 As MyModule

Private Type MyProject
  MyModule As String
  MySub As String
End Type

Private Type MyModule
  MyVar As String
  String As MyProject
End Type

Private Type MySub
  MyVar As MyModule
  MyVar1 As MyProject
End Type

Private Type MyVar
  MyProject As MyModule
End Type

Sub MySub()

  Dim MyProject As MyProject
  Dim MyModule As MyProject.MyModule.MyProject
  Dim MySub As MySub
  Dim MyVar As MyVar
  
  MyVar.MyProject.MyVar = "Smith"
  MySub.MyVar1.MySub = MyProject.MySub
  
  'My brain hurts....

End Sub
```

**Comment by retailcoder** [comment]
uh-oh :fearful:

**Comment by retailcoder** [comment]
I love assumptions! `FindLocalScopeDeclaration` did this

    // if we're not returning a function/getter value, then there can be only one:
    return results.Single();

Fix:

    // if we're not returning a function/getter value, then there can be only one that isn't the localScope declaration:
    return results.Single(item => !item.Equals(localScope));

**Comment by retailcoder** [comment]
Another bug: `MyProject.MySub` isn't picked up as a reference to `MyProject.MyModule.MySub`.

**Comment by retailcoder** [comment]
Refactor/rename broke the code at step 4:

    Option Explicit
    
    Private MyVar As MyProject
    Private MyVar1 As MyModule
    
    Private Type MyProject
      MyModule As String
      MySub As String
    End Type
    
    Private Type MyModule
      MyVar As String
      String As MyProject
    End Type
    
    Private Type MySub
      MyVar As MyModule
      MyVar1 As MyProject
    End Type
    
    Private Type MyVar
      MyProject As MyModule
    End Type
    
    Public Sub MySub_RenamedStep1()
    
      Dim MyProject_RenamedStep2 As MyProject
      Dim MyModule_RenamedStep3 As MyProject.MyModule.MyProject
      Dim MySub_RenamedStep4 As MySub
      Dim MyVar As MyVar
    
      MyVar.MyProject.MyVar = "Smith"
      MySub_RenamedStep4.MyVar1.MySub_RenamedStep4 = MyProject_RenamedStep2.MySub
    
    End Sub

I suspect it's because using a regex-replace to do the rename here.

**Comment by retailcoder** [comment]
Okay, I gave this one another shot after fixing #962 - renaming the `MySub` procedure no longer wrecks the code, *but*...

    Private Type RenamedStructType
      MyModule As String
      MySub As String
    End Type

    Sub renamed()
    
      Dim foo As RenamedStructType
      Dim MyModule As RenamedStructType.MyModule.MyProject
      Dim MySub As MySub
      Dim MyVar As MyVar
    
      MyVar.MyProject.MyVar = "Smith"
      MySub.MyVar1.MySub = foo.MySub
    
      'My brain hurts....
    
    End Sub

The `MyProject` private type being module-scoped...

      Dim MyModule As RenamedStructType.MyModule.MyProject

It gets found before the project-scope project name, so `MyProject` resolves to the private type, which is problematic *here*.

Not sure how to fix this without breaking something else...

**Comment by retailcoder** [comment]
I think I'll just document this as a known issue: don't expect things to go well if the project's identifier also refers to other things.

**Comment by retailcoder** [comment]
Actually... I have an idea: instead of trying to resolve member calls in one go, I'll iterate possible matches, temporarily store potential `IdentifierReference` objects, and add them to the `Declaration` "path" that goes the deepest.

This way, `MyProject.MyModule` will resolve in both matches, but since `MyProject.MyModule.MySub` will only match once, the references will go to that "path" and it will work... I think.

**Comment by retailcoder** [comment]
Man, this code is pure evil. I'm tempted to just give up.

**Comment by retailcoder** [comment]
The instruction `MyVar.MyProject.MyVar = "Smith"` breaks because the `MyVar` under `MyVar.MyProject` doesn't even *exist* as a declaration in the declaration tree - i.e. not only this code breaks the resolver, it breaks the scoping rules in such a way that  `MyVar As String` isn't even picked up as a member of the `MyModule` private type, and the code explorer doesn't render anything.

I need to figure this one out.

**Comment by retailcoder** [comment]
You've successfully broken my `GetHashCode` implementation for the `Declaration` type with this code.

**Comment by retailcoder** [comment]
Fixing the `GetHashCode` (and a few things in the resolver) gave me this:

    Private Type MyModule
      Renamed As String
      String As MyProject
    End Type

    Sub MySub()
    
      Dim MyProject As MyProject
      Dim MyModule As MyProject.MyModule.MyProject
      Dim MySub As MySub
      Dim MyVar As MyVar
    
      MyVar.MyProject.Renamed = "Smith"
      MySub.MyVar1.MySub = MyProject.MySub
    
      'My brain hurts....
    
    End Sub

The Code Explorer still doesn't render anything, but the UDT member correctly resolves now.

**Comment by retailcoder** [comment]
@ThunderFrame I know your brain hurts, but I'm missing something here, on this line:

    Dim MyModule As MyProject.MyModule.MyProject

What's that supposed to be? I'm not sure how VBA manages to compile it - IntelliSense only validates `MyProject.MyModule.MySub()`, since everything else is private... and `MyProject.MyModule` (the UDT member) is a `String` - what am I missing?

**Comment by retailcoder** [comment]
I'm not sure, but I think it works. all of it. needs further testing.

![image](https://cloud.githubusercontent.com/assets/5751684/12543381/02cffa72-c2fd-11e5-8c78-5e958c5ea84d.png)

**Comment by ThunderFrame** [comment]
I'm on a phone right now, but doesn't:

```
Dim MyModule As MyProject.MyModule.MyProject
```

Resolve as:

```
<ProjectName>.<ModuleName>.<TypeName>
```

That is, does walking up the scope-tree need to be aware of whether the expression is a Type identifier (being used in a dim as statement) or an assignment or usage?

**Comment by retailcoder** [comment]
It *should*, but:

    Dim MyModule As MyProject.<even IntelliSense is confused here>

Even with the `MyProject` UDT made `Public`, VBA's IntelliSense doesn't realize there's a usable type there.

    MyModule.<IntelliSense knows we're talking about the UDT and lists MyModule and MySub string members here>

So this is where it breaks:
 
    Public Type MyProject
      Renamed As String
      MySub As String
    End Type

    Sub MySub()
    
      Dim MyProject As MyProject
      Dim MyModule As MyProject.MyModule.MyProject 's/b As MyProject.Renamed.MyProject
      Dim MySub As MySub
      Dim MyVar As MyVar
    
      MyVar.MyProject.MyVar = "Smith"
      MySub.MyVar1.MySub = MyProject.MySub
    
      'My brain hurts....
    
    End Sub

I'll see what I can do to fix this last issue; the progress already made is tremendously helpful though.

**Comment by retailcoder** [comment]
No wait, that's *me* getting mixed up. Rubberduck is correctly *not* renaming that *AsTypeClause*.

**Comment by retailcoder** [comment]
Closing in on [this line of code](https://github.com/retailcoder/Rubberduck/blob/8ef7d8f3b4ce4b7b119a8a39df18ff8761135f3f/Rubberduck.Parsing/Symbols/IdentifierReferenceResolver.cs#L195); the `ResolveType` method is making an erroneous assumption - I'll probably have this bug fixed tonight... and this *evil* code will need to get *fiendish* to break the resolver again! :wink:

**Comment by retailcoder** [comment]
Drumroll...

![image](https://cloud.githubusercontent.com/assets/5751684/12573696/078b09a8-c3ca-11e5-8679-5719b8b65469.png)

...

Still not working. The first `MyProject` somehow doesn't resolve as a reference to the project. And I'm tired. And this code is evil.

**Comment by retailcoder** [comment]
**Ha!! I WIN!!!**

All I was missing was adding the references to the `_alreadyResolved` list.

Can we say the resolver is rock-solid now?

**Comment by retailcoder** [comment]
After re-implementing *Find all References*, I found that the resolver wasn't properly assigning references to unqualified UDT's. That's fixed now - the entire "evil.xlsm" workbook parses and resolves exactly as it should:

![image](https://cloud.githubusercontent.com/assets/5751684/13205923/9c8d091e-d8c1-11e5-84da-6a51355bb95c.png)

**Comment by retailcoder** [comment]
@ThunderFrame okay, so `MyModule As MyProject.MyModule.MyProject` doesn't resolve as it should...

....but it breaks the VBE as well:

![image](https://cloud.githubusercontent.com/assets/5751684/13896982/ef26d42e-ed76-11e5-896f-db0c350fe95e.png)

So I think we're good.
