### ISSUE TITLE
Installed Rubberduck first time. Failed on first go with errors.

### ISSUE THREAD

**Issue by PeterMTaylor** [rubberduck-vba/Rubberduck#935]
Thanks for introducing me to Rubberduck to see if it helps me.
I installed from Github as suggested and ran as it is in Excel with ALT-F11 keypress.
I got errors such as this.
![2016-01-12](https://cloud.githubusercontent.com/assets/2254567/12291944/486056da-ba3e-11e5-8f61-6514e295beaa.png)
and 
here is the file I exported from the dialogbox.
[Rubberduck run first time error.txt](https://github.com/rubberduck-vba/Rubberduck/files/88714/Rubberduck.run.first.time.error.txt)

Is this normal when there is no VBA code when this runs?

**Comment by Vogel612** [comment]
Hello and thanks for the report. 

From what I can see (not a developer on the project) Rubberduck doesn't seem to be involved in this case. The relevant modules are apparently loaded correctly, so Rubberduck should be ready to use for you :+1: 

Dropping the attached stacktrace information for easy overview:

    See the end of this message for details on invoking 
    just-in-time (JIT) debugging instead of this dialog box.
    
    ************** Exception Text **************
    System.InvalidOperationException: This operation cannot be performed while an auto-filled column is being resized.
       at System.Windows.Forms.DataGridView.PerformLayoutPrivate(Boolean useRowShortcut, Boolean computeVisibleRows, Boolean invalidInAdjustFillingColumns, Boolean repositionEditingControl)
       at System.Windows.Forms.DataGridView.SetColumnHeadersHeightInternal(Int32 columnHeadersHeight, Boolean invalidInAdjustFillingColumns)
       at System.Windows.Forms.DataGridView.AutoResizeColumnHeadersHeight(Boolean fixedRowHeadersWidth, Boolean fixedColumnsWidth)
       at System.Windows.Forms.DataGridView.OnColumnHeadersGlobalAutoSize()
       at System.Windows.Forms.DataGridView.set_TopLeftHeaderCell(DataGridViewHeaderCell value)
       at System.Windows.Forms.DataGridView.get_TopLeftHeaderCell()
       at System.Windows.Forms.DataGridView.GetCellInternal(Int32 columnIndex, Int32 rowIndex)
       at System.Windows.Forms.DataGridView.OnCellMouseEnter(DataGridViewCellEventArgs e)
       at System.Windows.Forms.DataGridView.UpdateMouseEnteredCell(HitTestInfo hti, MouseEventArgs e)
       at System.Windows.Forms.DataGridView.OnColumnWidthChanged(DataGridViewColumnEventArgs e)
       at System.Windows.Forms.DataGridView.OnBandThicknessChanged(DataGridViewBand dataGridViewBand)
       at System.Windows.Forms.DataGridView.AdjustFillingColumns()
       at System.Windows.Forms.DataGridView.ComputeLayout()
       at System.Windows.Forms.DataGridView.PerformLayoutPrivate(Boolean useRowShortcut, Boolean computeVisibleRows, Boolean invalidInAdjustFillingColumns, Boolean repositionEditingControl)
       at System.Windows.Forms.DataGridView.OnHandleCreated(EventArgs e)
       at System.Windows.Forms.Control.WmCreate(Message& m)
       at System.Windows.Forms.Control.WndProc(Message& m)
       at System.Windows.Forms.DataGridView.WndProc(Message& m)
       at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
       at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
       at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
    
    
    ************** Loaded Assemblies **************
    mscorlib
        Assembly Version: 4.0.0.0
        Win32 Version: 4.6.1063.1 built by: NETFXREL3STAGE
        CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
    ----------------------------------------
    Rubberduck
        Assembly Version: 1.4.3.2343
        Win32 Version: 1.4.3.0
        CodeBase: file:///C:/ProgramData/Rubberduck/Rubberduck.DLL
    ----------------------------------------
    Microsoft.Vbe.Interop
        Assembly Version: 14.0.0.0
        Win32 Version: 14.0.4760.1000
        CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/Microsoft.Vbe.Interop/14.0.0.0__71e9bce111e9429c/Microsoft.Vbe.Interop.dll
    ----------------------------------------
    System.Drawing
        Assembly Version: 4.0.0.0
        Win32 Version: 4.6.1038.0 built by: NETFXREL2
        CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
    ----------------------------------------
    System
        Assembly Version: 4.0.0.0
        Win32 Version: 4.6.1038.0 built by: NETFXREL2
        CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
    ----------------------------------------
    System.Windows.Forms
        Assembly Version: 4.0.0.0
        Win32 Version: 4.6.1038.0 built by: NETFXREL2
        CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
    ----------------------------------------
    Rubberduck.VBEditor
        Assembly Version: 1.0.5667.2338
        Win32 Version: 1.0.0.0
        CodeBase: file:///C:/ProgramData/Rubberduck/Rubberduck.VBEditor.DLL
    ----------------------------------------
    Accessibility
        Assembly Version: 4.0.0.0
        Win32 Version: 4.6.1038.0 built by: NETFXREL2
        CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
    ----------------------------------------
    Rubberduck.Parsing
        Assembly Version: 1.0.5667.2339
        Win32 Version: 1.0.0.0
        CodeBase: file:///C:/ProgramData/Rubberduck/Rubberduck.Parsing.DLL
    ----------------------------------------
    System.Core
        Assembly Version: 4.0.0.0
        Win32 Version: 4.6.1038.0 built by: NETFXREL2
        CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
    ----------------------------------------
    System.Xml
        Assembly Version: 4.0.0.0
        Win32 Version: 4.6.1038.0 built by: NETFXREL2
        CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
    ----------------------------------------
    PresentationFramework
        Assembly Version: 4.0.0.0
        Win32 Version: 4.6.1063.1
        CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll
    ----------------------------------------
    WindowsBase
        Assembly Version: 4.0.0.0
        Win32 Version: 4.6.1063.1 built by: NETFXREL3STAGE
        CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
    ----------------------------------------
    PresentationCore
        Assembly Version: 4.0.0.0
        Win32 Version: 4.6.1063.1 built by: NETFXREL3STAGE
        CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
    ----------------------------------------
    System.Xaml
        Assembly Version: 4.0.0.0
        Win32 Version: 4.6.1063.1 built by: NETFXREL3STAGE
        CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
    ----------------------------------------
    Rubberduck.SourceControl
        Assembly Version: 1.0.0.0
        Win32 Version: 1.0.0.0
        CodeBase: file:///C:/ProgramData/Rubberduck/Rubberduck.SourceControl.DLL
    ----------------------------------------
    Ninject
        Assembly Version: 3.2.0.0
        Win32 Version: 3.2.2.0
        CodeBase: file:///C:/ProgramData/Rubberduck/Ninject.DLL
    ----------------------------------------
    NLog
        Assembly Version: 3.2.1.0
        Win32 Version: 3.2.1.0
        CodeBase: file:///C:/ProgramData/Rubberduck/NLog.DLL
    ----------------------------------------
    System.Configuration
        Assembly Version: 4.0.0.0
        Win32 Version: 4.6.1038.0 built by: NETFXREL2
        CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
    ----------------------------------------
    
    ************** JIT Debugging **************
    To enable just-in-time (JIT) debugging, the .config file for this
    application or computer (machine.config) must have the
    jitDebugging value set in the system.windows.forms section.
    The application must also be compiled with debugging
    enabled.
    
    For example:
    
    <configuration>
        <system.windows.forms jitDebugging="true" />
    </configuration>
    
    When JIT debugging is enabled, any unhandled exception
    will be sent to the JIT debugger registered on the computer
    rather than be handled by this dialog box.

**Comment by ckuhn203** [comment]
I'm not sure what's happening here. Does the VBE open at all (after the exception)?

**Comment by PeterMTaylor** [comment]
Yes it does suprisingly. 
![2016-01-13 2](https://cloud.githubusercontent.com/assets/2254567/12293036/f96aa06a-ba44-11e5-8a4d-6b8f0fc14aa7.png)
 I thought to make sure it is documented when I run this.

**Comment by PeterMTaylor** [comment]
Sorry I pressed the wrong button (Close and comment) by mistake. On reflection i think this all is needed a place to document an such as this. I will raise a new issue after I have a few tries of writing software. Thanks for your help.

**Comment by Hosch250** [comment]
@PeterMTaylor I reopened the issue for you.

**Comment by retailcoder** [comment]
This might have something to do with a bug in one of the docked grid toolwindows. Can't repro here though (build 1.4.3.2343), but I think I recall this being an issue at one point prior to the release.

I'm re-closing this issue though, since 2.0 (/current build) will no longer use grids in docked toolwindows.

**Comment by ckuhn203** [comment]
Oops. Sorry. I didn't see the newly added comments before I reopened. Closing it again...

**Comment by PeterMTaylor** [comment]
ok. no worries.
 

    On Sunday, 17 January 2016, 0:10, Christopher McClellan <notifications@github.com> wrote:
 

 Oops. Sorry. I didn't see the newly added comments before I reopened. Closing it again...—

**Comment by jspraul** [comment]
I downloaded the latest release ([v1.4.3, 2015-07-08](https://github.com/rubberduck-vba/Rubberduck/releases/tag/v1.4.3)) linked on the [project web page](http://www.rubberduck-vba.com/#wsb-button-00000000-0000-0000-0000-000663568611) and encountered this error.

Perhaps additional documentation could be added somewhere obvious to make sure that users are aware this is a known issue and can be safely ignored?

**Comment by ckuhn203** [comment]
Does this continue to happen when you open it, or just the very first time after installation? We can add a note to the release, or the readme, but I'd like to *somehow* hunt the issue down.

**Comment by ckuhn203** [comment]
I also added the [Support] label to this issue.

**Comment by PeterMTaylor** [comment]
I am glad someone would benefit this check.

**Comment by jspraul** [comment]
This only occurred the first time for me.

Google says it is a [known issue](https://social.msdn.microsoft.com/forums/windows/en-us/b66520b7-94e4-4b13-ab82-64f3aeee23e4/autoresizecolumns-gives-operation-exception) with a few fairly straightforward work-arounds, but I agree it is not an emergency - just put out a build of v2.0 as the latest release instead!

**Comment by ckuhn203** [comment]
LOL. We want to. We're working on it. =)

**Comment by Hosch250** [comment]
I'd have to say this is kind of obsolete.
