### ISSUE TITLE
Code Suggestion for not using New keyword in variable declaration

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#939]
VBA allows a shortcut notation for declaring and instantiating objects:
```
Dim oClass as New MyClass
```
as opposed to
```
Dim oClass as MyClass
Set oClass = New MyClass
```
But, using the first syntax, VBA doesn't *actually* instantiate the class until the code accesses a method or property of the class (which I think includes inspecting the object in the Locals Window).

If the Class has an Initialize event, the event doesn't fire at the *New* statement, as the developer might expect. This can lead to debugging problems.

**Comment by ckuhn203** [comment]
My first instinct is [Status-Declined]. I'm of the opinion that using the "shortcut" leads to buggy code and should be avoided. If anything, I think we may already have the exact opposite inspection to what you're suggesting here.

**Comment by ThunderFrame** [comment]
hmm, I think I wasn't clear. I think the code-inspector should suggest *NOT* using the
```Dim o as New C```
 syntax.
If that's already a feature, then close this.

**Comment by retailcoder** [comment]
I don't think we *already* have that inspection, but I agree we need one. This code is problematic:

    Sub Surprise()
        Dim c As New Collection
        Set c = Nothing
        c.Add "this line does not blow up!"
    End Sub

**Comment by retailcoder** [comment]
The inspection would be child's play to implement: just look for declarations where the `IsSelfAssigned` property is `true`.

**Comment by ckuhn203** [comment]
Oh! I'm sorry. Then yes, :+1:  absolutely! I'm surprised we don't have this one yet.
