### ISSUE TITLE
Import module(s) directly from a closed Office document

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#944]
Currently, in order to import modules, they must reside on disk, as text files.

It would be a time saver if RubberDuck could import modules _directly_ from, for example, an XLS or DOC, without needing to firstly load the host application and export the module.

This would require the following capabilities:
- Opening an Office 2007+ file container (ZIP), to reach the VBA project binary. This comes for free with .NET 4.5
- Opening an Office 2003- file container (CFBF)
- Opening the VBA binary (CFBF)
- Decompressing the compressed VBA Project components

That would allow a user to extract modules from a DOC file without actually needing Word to be installed.

A nice-to-have would be extracting module from a file _or_ from a stream, and you could then import a module from a file from the internet.

**Comment by ckuhn203** [comment]
I don't know if this one's in scope. @retailcoder @Hosch250 what do you think?

**Comment by retailcoder** [comment]
out of scope
