### ISSUE TITLE
ResetSettings is using a hardcoded path

### ISSUE THREAD

**Issue by ckuhn203** [rubberduck-vba/Rubberduck#945]
https://github.com/rubberduck-vba/Rubberduck/blob/next/RetailCoder.VBE/UI/Settings/SettingsDialog.cs#L66

The UI/Settings/SettingsDialog.cs has the path to the config file hard coded into it.

        private void ResetSettings()
        {
            var currentLanguage = _config.UserSettings.LanguageSetting;

            System.IO.File.Delete(System.IO.Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData), "Rubberduck\\rubberduck.config"));
            var config = _configService.GetDefaultConfiguration();
            _configService.SaveConfiguration(config, !currentLanguage.Equals(config.UserSettings.LanguageSetting));
        }

There are two things wrong here. 

  1. If we really *must* expose the file path, then the `protected string ConfigFile` property of the Configuration Service (ConfigurationLoader) should be public.
  2. I'm not certain that the file should be deleted at all. Serializing the file does an over-write, so I'm not sure if the delete is needed at all.

**Comment by ckuhn203** [comment]
The more I think about it, this method should be moved to the config service and just be a call into it from the UI.

**Comment by Hosch250** [comment]
Fixed when I redesigned the Settings window in XAML.  Now, we just update the settings display when the Reset button is clicked, and nothing at all is done to the file except through `SaveConfiguration()`
