### ISSUE TITLE
References explorer enhancement

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#950]
The VBIDE provides a _typical_ dialog for inspecting the project references, and by _typical_, I mean it _doesn't_ let you see, select or copy the reference names or paths, and the window isn't sizeable, and it's scope is limited to a single project.

Whether you have one project open, or numerous, it would be nice to be able to inspect _all_ of the references for _all_ of the projects at once, and to be able to read, select and copy the entire names and paths of each.

**Comment by retailcoder** [comment]
When this gets implemented, the resolver *must* take into account inter-project references. Not because it's a prerequisite or anything... just because, if we're going to offer anything that touches references, the resolver just *needs* to account for them.

I like this idea.

**Comment by ThunderFrame** [comment]
BookA (ProjectA) references:
 - BookB (ProjectB)
 - BookC (ProjectC)
BookB (ProjectB) references:
 - BookC (ProjectC)
BookC (ProjectC) references:
 - BookBB (ProjectB)
BookBB (ProjectB)

\* yes, BookBB has project name ProjectB, which is the same as BookB (ProjectB)

**Comment by retailcoder** [comment]
@ThunderFrame shouldn't be a problem - project references go by filename, so everything could be called `VBAProject` ;-)

**Comment by ThunderFrame** [comment]
@retailcoder - great - was more the nested links that I thought might be a problem... all of the projects show in the VBIDE Project Explorer.

**Comment by retailcoder** [comment]
This issue is now a [project](https://github.com/rubberduck-vba/Rubberduck/projects/3).
