### ISSUE TITLE
Square-bracketed identifiers break the resolver

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#953]
I haven't tried parsing this, but it might be nasty...

```
Option Explicit

Sub test()

  Dim s As String
  Dim i As Integer
  Dim rng As Range
  Dim a As Variant
  Dim v As Variant
  
  'Cell address B2
  s = [B2].Address
  s = [$B2].Address
  s = [$B$2].Address
  s = [B$2].Address
  
  'multi-cell
  s = [B:B].Address
  s = [B2:B4].Address
  
  'Cell address that can't be old Excel
  s = [XFD1048576]
  
  'Function name that could be a cell address
  s = E1
  
  'Function name that can't be a cell address
  s = [EEEE1]
  
'Excel formulas...
  s = [=TODAY()]
  s = [=B1 + B2]
  s = [=B1 & B2]
  v = [=And(true,true)]
    

  'Union operators
  s = [B1,B2,B3].Address
  s = [B1, B2, B3].Address
  
  'Intersection operators
  s = [B:B 2:2 B:C].Address

  'Intersection and union operators
  s = [B:B 2:2 B:C, D1 D:D].Address

  'Named Range
  i = [MyNamedRange].Rows.Count
  
  'Get range as array
  a = [B2:D4]
  
  'Get range formulas as array
  a = [B2:B4].Formula
  
  With [MyNamedRange]
    Set rng = .Cells
  End With
  
  Set rng = [MyNamedRange]
  Set rng = Sheet1.[MyNamedRange]
  Set rng = [Sheet1].[MyNamedRange]
  Set rng = [Sheet1!MyNamedRange]

End Sub

Public Function E1() As String
  E1 = [F1]
End Function

Public Function EEEE1() As String
  EEEE1 = "Test"
End Function
```

**Comment by ThunderFrame** [comment]
And how about:

```
  'Excel vs VBA function signatures
  v = [Log(10)] ' Returns 1
  v = Log(10)   ' Returns 2.30258509299405
  
  v = Round(4.5, 0) ' Returns 4 (Bankers rounding)
  v = [Round(4.5, 0)] ' Returns 5
  
  'Excel function vs VBA operator/keyword
  v = Not [Not(True)]
```

**Comment by retailcoder** [comment]
Hmm anything in square brackets is just going to be parsed as an (undeclared) identifier. It shouldn't affect anything - I'll test it out to be sire though.

**Comment by retailcoder** [comment]
It would be nice if an inspection/quickfix could turn them into explicit `WorksheetFunctions` and `Range` calls, but this would be a quite massive effort, for little gain. As I said the parser processes them as undeclared identifiers, which complicates things because any undeclared identifier is already a problem (there's no `Declaration` for it, so there's no `IdentifierReference` either) - i.e. note taken, but I'm not sure how to do anything about this.

**Comment by retailcoder** [comment]
@ThunderFrame ok, the code parses, but completely wrecks the resolver and using refactor/rename on any of the locals in the `test` procedure, breaks the code:

    Sub test()
    
      Dim renamedS As String
      Dim renamedI As Integer
      Dim renamed As Range
      Dim renamedA As Variant
      Dim renamedV As Variant
    
      'Cell address B2
      renamedS = [B2].Address
      s = [$B2].Address
      s = [$B$2].Address
      s = [B$2].Address
    
      'multi-cell
      s = [B:B].Address
      s = [B2:B4].Address
    
      'Cell address that can't be old Excel
      s = [XFD1048576]
    
      'Function name that could be a cell address
      s = E1
    
      'Function name that can't be a cell address
      s = [EEEE1]
    
    'Excel formulas...
      s = [=TODAY()]
      s = [=B1 + B2]
      s = [=B1 & B2]
      v = [=And(true,true)]
    
    
      'Union operators
      s = [B1,B2,B3].Address
      s = [B1, B2, B3].Address
    
      'Intersection operators
      s = [B:B 2:2 B:C].Address
    
      'Intersection and union operators
      s = [B:B 2:2 B:C, D1 D:D].Address
    
      'Named Range
      i = [MyNamedRange].Rows.Count
    
      'Get range as array
      a = [B2:D4]
    
      'Get range formulas as array
      a = [B2:B4].Formula
    
      With [MyNamedRange]
        Set rng = .Cells
      End With
    
      Set rng = [MyNamedRange]
      Set rng = Sheet1.[MyNamedRange]
      Set rng = [Sheet1].[MyNamedRange]
      Set rng = [Sheet1!MyNamedRange]
    
    End Sub

...which is very scary at this point - this needs further investigation.

**Comment by ThunderFrame** [comment]
And some Enum, for testing

```
Option Explicit

Public Enum FOO
  [BAR1] = 1
  [_BAR1] = 2 'Is hidden
End Enum

Sub test()

  Dim x
  
  x = BAR1   '1
  x = [BAR1] '1
  x = [BAS1] ' = Range("BAR1").Value
  x = [_BAR1] '2
  
End Sub
```

**Comment by retailcoder** [comment]
hmm the parse tree is broken, this will require a grammar fix.

For example, this expression should be picked up under the `letStmt` rule:

    s = [B2].Address

But the `LetStmtContext` starts at line 12, and ends.... at line 63.

**Comment by retailcoder** [comment]
Fixed, at the *lexer* level.

    Option Explicit
    
    Sub Renamed6()
    
      Dim renamed1 As String
      Dim renamed2 As Integer
      Dim renamed3 As Range
      Dim renamed4 As Variant
      Dim renamed5 As Variant
    
      'Cell address B2
      renamed1 = [B2].Address
      renamed1 = [$B2].Address
      renamed1 = [$B$2].Address
      renamed1 = [B$2].Address
    
      'multi-cell
      renamed1 = [B:B].Address
      renamed1 = [B2:B4].Address
    
      'Cell address that can't be old Excel
      renamed1 = [XFD1048576]
    
      'Function name that could be a cell address
      renamed1 = Renamed8
    
      'Function name that can't be a cell address
      renamed1 = [EEEE1]
    
    'Excel formulas...
      renamed1 = [=TODAY()]
      renamed1 = [=B1 + B2]
      renamed1 = [=B1 & B2]
      renamed5 = [=And(true,true)]
    
    
      'Union operators
      renamed1 = [B1,B2,B3].Address
      renamed1 = [B1, B2, B3].Address
    
      'Intersection operators
      renamed1 = [B:B 2:2 B:C].Address
    
      'Intersection and union operators
      renamed1 = [B:B 2:2 B:C, D1 D:D].Address
    
      'Named Range
      renamed2 = [MyNamedRange].Rows.Count
    
      'Get range as array
      renamed4 = [B2:D4]
    
      'Get range formulas as array
      renamed4 = [B2:B4].Formula
    
      With [MyNamedRange]
        Set renamed3 = .Cells
      End With
    
      Set renamed3 = [MyNamedRange]
      Set renamed3 = Renamed7.[MyNamedRange]
      Set renamed3 = [Sheet1].[MyNamedRange]
      Set renamed3 = [Sheet1!MyNamedRange]
    
    End Sub
    
    Public Function Renamed8() As String
      Renamed8 = [F1]
    End Function
    
    Public Function Renamed9() As String
      Renamed9 = "Test"
    End Function

So, one problem remains: `[Sheet1]` should have been renamed to `[Renamed7]`, right? Would it be correct to assume `[Foo]` is always equivalent to `Foo`?

**Comment by retailcoder** [comment]
Ok so I've tweaked the resolver to treat `[Foo]` as `Foo`, and it works. It's also how VBA seems to handle it. I've entered the word `TEST` in cell A1, then proceeded to the immediate pane:

    ?[A1]
    TEST

As expected, `[A1]` outputs `TEST`. Then I added a standard code module, and declared a `Public A1 As String`.

    ?[A1]

The immediate pane output was blank: the global variable takes precedence over the worksheet address in VBA's own identifier resolution algorithm, so treating `[Foo]` as `Foo` seems completely correct.

@ThunderFrame  This code isn't valid however:

    Set rng = [Sheet1!MyNamedRange]

The expression `[Sheet1!MyNamedRange]` returns `Error 2023`, so I'm not going to wreck my brains over that one.

**Comment by ThunderFrame** [comment]
@retailcoder That's weird, it's not an error for me:

```
Option Explicit

Sub test()
  'Using Excel 2010
  'MyNamedRange is a Workbook level name for Cell B2 with value: 123
  'MySheetName is a Sheet1 level name for cell B4 with value: 456
  Dim x
  
  x = [Sheet1!MyNamedRange]
  Debug.Print x

  Set x = [Sheet1!MyNamedRange]
  Debug.Print x.Address


  x = [Sheet1!MySheetName]
  Debug.Print x

  Set x = [Sheet1!MySheetName]
  Debug.Print x.Address

  'Debug Output is:
  ' 123
  '$B$2
  ' 456
  '$B$4

End Sub
```

**Comment by retailcoder** [comment]
@ThunderFrame right. same output here... the `Error 2029` was probably due to a typo.

    [Sheet1!NamedRange]

is valid syntax, but I have no idea how to make it parse correctly.

**Comment by ThunderFrame** [comment]
@retailcoder Here's some usage of the ! for collections, ranges and recordsets :

```
Sub test()
  'Running in Access 2010
  
  'Excel
  Dim oXL As Excel.Application
  Dim wbk As Excel.Workbook
  Dim sht As Excel.Worksheet
  
  Dim rst As DAO.Recordset

  Dim col As Collection

  Set rst = CurrentDb().OpenRecordset("tblEmployee")

  Set col = New Collection
  col.Add 1, "a"

  Set oXL = New Excel.Application
  Set wbk = oXL.Workbooks.Add
  Set sht = wbk.Sheets(1)
  sht.Activate
  
  'All of these work...
  [a1] = [123]
  Excel.[a1] = rst!Lastname
  [a1] = rst![Lastname]
  [a1] = [rst]![Lastname]
  [a1] = [rst!Lastname]
  [Sheet1!A1] = rst!Lastname
  [a1] = col![a]
  [a1] = [col!a]


End Sub
```

**Comment by retailcoder** [comment]
@ThunderFrame  that one stalls the resolver. At this point I'm just going to label square-bracketed identifiers as a *known issue*. The entire `Declarations` API needs an overhaul to get this to work correctly, it's ....major.

**Comment by retailcoder** [comment]
I mean, square-bracketed identifiers are only a problem when they're *also* using exclamation marks.
