### ISSUE TITLE
Inspector should warn about constants that imply passwords

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#955]
I've seen a bunch of projects store passwords in the VBA. Bad practice it is, but, because sheet protection.

I've seen projects go to the trouble of applying protection to the VBA, only to expose the passwords in the Object Browser.

So constants names (not in Option Module Private modules, or Friend's in classes) containing Password or Pwd could be Inspected, and suggestions/warnings raised about visibility.

I'll admit that this issue is a bit flaky in terms of identifying password literals (it could try harder and look for password setters accepting a constant), but having at least a small amount of security-review/pen-test type inspections would _mostly_ appeal to big corporates

**Comment by PeterMTaylor** [comment]
Be good if suggestions are offered to the user/developer what to do to increase security protection for VBA storage of passwords.

**Comment by retailcoder** [comment]
out of scope
