### ISSUE TITLE
Dialogs are top-level and hide other applications

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#960]
The RD About window is a top-most window, so not only does it appear above the VBE, it also appears above any other application, which is a bit annoying.

This was seen under 1.4.x on Win8.1 64-bit, with 32-bit Excel 2013 and CorelDraw X6 hosts.

**Comment by retailcoder** [comment]
It's a modal dialog, like all others, e.g. *refactor/rename* and *extract method* dialogs would appear top-most as well. We need to tell Windows it "belongs" to the host app's process.

**Comment by Hosch250** [comment]
This can be fixed fairly easily by setting a property in the WinForms designer.  I can fix all of these if you will create a list of them.

**Comment by retailcoder** [comment]
@Hosch250 it's applicable to all dialogs. Every single one of 'em ;-)

 - [ ] About
 - [ ] Refactor / rename
 - [ ] Refactor / extract method
 - [ ] Refactor / remove parameter
 - [ ] Refactor / reorder parameters
 - [ ] Refactor / extract interface
 - [ ] Source Control / merge
 - [ ] Source Control / branch
 - [ ] ...any others?

**Comment by Hosch250** [comment]
Yeah, this is a horrible pain.  If I do not force them to be at the top, they disappear when you go to another application.  I'm pretty sure there is a way to fix between this - at least I hope so...  I can handle this by creating a WPF window and displaying it in another thread, maybe; I've done this before.

**Comment by Hosch250** [comment]
No, many of these dialogs did not have this problem  I am removing them all from the taskbar - it doesn't need to know about these dialogs since the other window has to be open anyway.  The refactorings are easy to fix, it appears to become a problem when we have a dialog open from a dockable window, like the SC ones.

**Comment by Hosch250** [comment]
This is completely fixed in my branch because we do not create dialogs from the dockable control anymore.
