### ISSUE TITLE
Rubberduck isn't visible after manual Load using Add-in Manager

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#966]
If you start VBIDE with RD set to *not* autoload, and then use VBE's add-in manager to load RD, some windows flash by, but RD is not visible.

**Comment by retailcoder** [comment]
Probably has to do with the way the add-in is initialized; I *think* I moved that code to the handler for when the VBE startup is completed, which broke the case when we want it to initialize when the VBE is *already* started. My bad!
