### ISSUE TITLE
Localize menu items

### ISSUE THREAD

**Issue by Hosch250** [rubberduck-vba/Rubberduck#975]
Items nested in menus, such as the refactorings, are not localized, although their parent menus are.

**Comment by Vogel612** [comment]
Related: #920 and #893, possibly #805

**Comment by Hosch250** [comment]
@Vogel612 I don't think those are related.  Yes, they involve localization, but this is at a different level.

**Comment by Vogel612** [comment]
It could be beneficial to attack them at the same time, which is why I wanted to mention them here, but you are right, the levels they are at are different

**Comment by retailcoder** [comment]
@Hosch250 can you clarify what you mean by "not localized"? The very architecture of *CommandMenuItems* is preventing the hard-coding of menu captions, they all override a `Key` property which represents the resource key that points to the resource string that contains the localized captions:

    public override string Key { get { return "RefactorMenu_ExtractMethod"; } }

 - [RefactorEncapsulateFieldCommandMenuItem](https://github.com/rubberduck-vba/Rubberduck/blob/next/RetailCoder.VBE/UI/Command/MenuItems/RefactorEncapsulateFieldCommandMenuItem.cs#L14)
 - [RefactorExtractInterfaceCommandMenuItem](https://github.com/rubberduck-vba/Rubberduck/blob/next/RetailCoder.VBE/UI/Command/MenuItems/RefactorExtractInterfaceCommandMenuItem.cs#L14)
 - [RefactorExtractMethodCommandMenuItem](https://github.com/rubberduck-vba/Rubberduck/blob/next/RetailCoder.VBE/UI/Command/MenuItems/RefactorExtractMethodCommandMenuItem.cs#L16)
 - [RefactorImplementInterfaceCommandMenuItem](https://github.com/rubberduck-vba/Rubberduck/blob/next/RetailCoder.VBE/UI/Command/MenuItems/RefactorImplementInterfaceCommandMenuItem.cs#L14)
 - [RefactorIntroduceFieldCommandMenuItem](https://github.com/rubberduck-vba/Rubberduck/blob/next/RetailCoder.VBE/UI/Command/MenuItems/RefactorIntroduceFieldCommandMenuItem.cs#L14)
 - [RefactorIntroduceParameterCommandMenuItem](https://github.com/rubberduck-vba/Rubberduck/blob/next/RetailCoder.VBE/UI/Command/MenuItems/RefactorIntroduceParameterCommandMenuItem.cs#L14)
 - [RefactorMoveCloserToUsageCommandMenuItem](https://github.com/rubberduck-vba/Rubberduck/blob/next/RetailCoder.VBE/UI/Command/MenuItems/RefactorMoveCloserToUsageCommandMenuItem.cs#L14)
 - [RefactorRemoveParameterCommandMenuItem](https://github.com/rubberduck-vba/Rubberduck/blob/next/RetailCoder.VBE/UI/Command/MenuItems/RefactorRemoveParametersCommandMenuItem.cs#L15)
 - [RefactorRenameCommandMenuItem](https://github.com/rubberduck-vba/Rubberduck/blob/next/RetailCoder.VBE/UI/Command/MenuItems/RefactorRenameCommandMenuItem.cs#L15)
 - [RefactorReorderParametersCommandMenuItem](https://github.com/rubberduck-vba/Rubberduck/blob/next/RetailCoder.VBE/UI/Command/MenuItems/RefactorReorderParametersCommandMenuItem.cs#L15)

The actual displayed caption is obtained in the  `CommandMenuItemBase` abstract class, by loading the localized resource string using the overridden `Key`:

        public Func<string> Caption
        {
            get
            {
                return () => Key.IsNullOrEmpty() 
                    ? string.Empty 
                    : RubberduckUI.ResourceManager.GetString(Key, RubberduckUI.Culture);
            }
        }

The actual localization occurs in `ParentMenuItemBase`, another abstract class:

        public void Localize()
        {
            if (Item == null)
            {
                return;
            }

            Item.Caption = Caption.Invoke();
            foreach (var kvp in _items)
            {
                kvp.Value.Caption = kvp.Key.Caption.Invoke();
            }
        }

I don't see how any menu item could possibly be "not localized".

**Comment by retailcoder** [comment]
Or did you mean "not translated"? (sorry for being pedantic :wink:)

**Comment by Hosch250** [comment]
http://imgur.com/I5XrxuL.png

**Comment by retailcoder** [comment]
:fearful:

**Comment by Vogel612** [comment]
Hashing this out in chat shows that this happens when **switching** language. 

The Localization works correctly after a full restart. It seems that the localization isn't updated for these menu items when the language is switched

**Comment by Vogel612** [comment]
digging through the github files this seems to be a problem in the actual handler that's called from [this line](https://github.com/rubberduck-vba/Rubberduck/blob/next/RetailCoder.VBE/Settings/XmlConfigurationServiceBase.cs#L40). For whatever reason the ConfigurationService is responsible to notify people of a language change after the SettingsDialog determined that and told the Service about this. :nose: :nose: 

I can't follow the Handler back, but I assume the menu items aren't correctly iterated down through subitems :/

**Comment by Hosch250** [comment]
@Vogel612 You are correct.  I fixed it by doing a soft-cast and check for null.  If the item is a parent menu itself, I call `Localize()`, which recursively calls until there are no more parent items.
