### ISSUE TITLE
Add support for SOLIDWORKS

### ISSUE THREAD

**Issue by ShipsWithCannons** [rubberduck-vba/Rubberduck#979]
SOLIDWORKS has had support for VBA for years. It would attract a big new user-base to add support for this to Rubberduck.

[RunAttachedMacro](http://help.solidworks.com/2016/English/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISldWorks~RunAttachedMacro.html) and [RunMacro2](http://help.solidworks.com/2016/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISldWorks~RunMacro2.html) should help to determine how feasible adding support is.

**Comment by ThunderFrame** [comment]
If possible, getting the interop from an earlier version *might* provide broader compatibility. SolidWorks is *expensive*, so I assume not all users run the latest version.

**Comment by ThunderFrame** [comment]
@retailcoder did you ever hear back from Solidworks, regarding the [email](http://chat.stackexchange.com/transcript/14929?m=27169906#27169906) you sent?

**Comment by retailcoder** [comment]
Nope. Their loss.

**Comment by retailcoder** [comment]
completed
