### ISSUE TITLE
RubberDuck should warn about reference path ambiguity

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#981]
Under Excel (and presumably most VBE hosts), the application won't let you have 2/documents open that share the same name, even if they have different paths. That implicity means that VBE can't have 2 projects open that have the same underlying file name, although they can have common project names). Also note #980 , which _does_ allow duplicate file names due to a ghosting issue).

If I have a project in C:\FileA.xls that references C:\Addins\FileB.xls and I already have a single file, C:\FileB.xls open, and then I open C:\FileA.xls, then Excel will not open the real reference, as a file called FileB.xls is already open. Iirc, at this point, the VBE shows that FileA has a reference to C:\FileB.xls and if FileA.xls is saved, then that changed reference path is persisted.

Unfortunately, I'm not certain that RubberDuck will be able to catch this. Possibly, by the time FileA is open and available to the VBE, the reference filepaths have already been changed? I guess RD could track the opened documents, and warn when a new document is opened that ends up with a reference to a file that is already open? Might also need to make a distinction between whether a file was opened at startup, because of XLSTART, or because of a file open command?

**Comment by retailcoder** [comment]
IMO that's a problem that would be solved if VBA projects weren't hosted in a document, but instead in a .vbp project file.... which would defeat the purpose of it.

Not sure there's a fix for that, the VBE already has the project opened when it loads add-ins.
