### ISSUE TITLE
New README Installation Instructions broke Wiki link

### ISSUE THREAD

**Issue by RaymondWise** [rubberduck-vba/Rubberduck#982]
New README points` [Installing](https://github.com/rubberduck-vba/Rubberduck/wiki/Installing)` but [Wiki TOC](https://github.com/rubberduck-vba/Rubberduck/wiki) points to `https://github.com/rubberduck-vba/Rubberduck/wiki/Building-&-Installation`

**Comment by Hosch250** [comment]
Is this fixed?

**Comment by ThunderFrame** [comment]
I fixed the download link on the installing page, but I haven't touched the TOC. The TOC and Wiki home page links to *installing* seems to be working, so it seems this can be closed...

**Comment by RaymondWise** [comment]
I can't find anything that's broken - closed.
