### ISSUE TITLE
How to filter-out function calls

### ISSUE THREAD

**Issue by u-riaz** [rubberduck-vba/Rubberduck#983]
Hi,
I want to get all function-calls from VBA code. For this i'had two listeners on
ExplicitCallStmt  :-> for explicit-calls with keyword 'CALL'
ImplicitCallStmt_InBlock :-> for implicit-calls e.g. print, DosomeFun, Shell(D) etc.
and they are doing pretty good. 
But, unfortunately, problem occurs when there are implicit-calls in-between statements like
var = Shell(D)
means, calls in expressions, statements etc. 
I know that ,then, rule "implicitCallStmt_InStmt" got triggered. What i want from "var = Shell(D)"  is "Shell(D)" as a function-call, but, having listener on "implicitCallStmt_InStmt" returns me three calls as:
1. var
2. Shell(D)
3. D

I'm using ANTLR-v4 parser. Can someone please help to fix it.
Regards: Usman

**Comment by retailcoder** [comment]
You need to look at the grammar and see how `implicitCallStmt_InStmt` is working:

    implicitCallStmt_InStmt :
	iCS_S_MembersCall
	| iCS_S_VariableOrProcedureCall
	| iCS_S_ProcedureOrArrayCall
	| iCS_S_DictionaryCall
    ;

Note that the parser rule doesn't have enough context to be able to tell a function call from an array call - your code is going to have to sort this out.

Your code works as expected: `var` is a *variable or procedure call*, `Shell(D)` could be a *procedure or array call*, and `D` is also a *variable or procedure call*.

In other words, to sort out variables and arrays and functions and procedures and member calls, you first need to know what's what. Rubberduck walks the parse trees and identifies all *declarations*, then walks again to locate *identifier references*, and there's pretty complex code that resolves these identifier references to a specific *declaration*.

Feel free to browse the code under [Rubberduck.Parsing.Symbols](https://github.com/rubberduck-vba/Rubberduck/tree/next/Rubberduck.Parsing/Symbols) for more information; there's no short answer or easy way to do this, at least until the ANTLR grammar contains meta-information that helps ANTLR generate a context-sensitive parser.

**Comment by ckuhn203** [comment]
As an aside, context sensitive grammars are possible by using semantic predicates, but I don't understand them well enough to say how it's done.

**Comment by retailcoder** [comment]
@ckuhn203 I need to get a hold of that ANTLR4 book!
