### ISSUE TITLE
Refactor/Rename doens't handle renaming parameter in parameterized getter

### ISSUE THREAD

**Issue by Hosch250** [rubberduck-vba/Rubberduck#987]
This code makes the parser thinks there are only two parameters (the ones in the `Let`):
```
Private Property Get Foo(ByVal arg1 As Integer) As String
End Property

Private Property Let Foo(ByVal arg1 As Integer, ByVal arg2 As String)
End Property
```
If I rename `arg1` to `arg3`, it correctly picks up all three parameters, but also makes the code uncompilable.

**Comment by retailcoder** [comment]
@Hosch250 that snippet doesn't compile.

**Comment by Hosch250** [comment]
@retailcoder Copy/pasta error.  Check it out now:

Private Property Get Foo(ByVal arg3 As Integer) As String
End Property

Private Property Let Foo(ByVal arg1 As Integer, ByVal arg2 As String)
End Property

**Comment by retailcoder** [comment]
This would be it:

    Private Property Get Foo(ByVal arg1 As Integer) As String
    End Property
    
    Private Property Let Foo(ByVal arg1 As String, ByVal arg2 As Integer)
    End Property

Renaming `arg1` to `arg` in the getter only affects the getter. This is a *rename* refactoring bug.

**Comment by retailcoder** [comment]
Darn parameterized getters... I need to confirm the order of parameters.

**Comment by Hosch250** [comment]
LOL, Remove and Reorder seem to work.

**Comment by retailcoder** [comment]
#1169 is the same issue, but with a clearer example. Closing this one.
